### ISSUE TITLE
windows下使用GPU训练deeplabV3出现以下问题怎么解决

### ISSUE THREAD

**Issue by kongxm889** [PaddlePaddle/PaddleSeg#100]
报错信息：
----------------------
Error Message Summary:
----------------------
PaddleCheckError: holder_ should not be null
Tensor holds no memory. Call Tensor::mutable_data first. at [D:\1.6.1\paddle\paddle\fluid\framework\tensor.cc:23]
  [operator < softmax_with_cross_entropy > error]
forrtl: error (200): program aborting due to control-C event

**Comment by kongxm889** [comment]
根据这个也没有解决问题 https://www.jianshu.com/p/bb823f5a935a

**Comment by ZeyuChen** [comment]
是否能提供更多机器环境、运行脚本和配置等信息给到我们进行调试？

**Comment by kongxm889** [comment]
执行PaddlePaddle/PaddleSeg/paseg/train.py出现的。使用的是V0.2.0版本的。方便的话给个QQ号，方便给脚本及配置信息等

**Comment by ZeyuChen** [comment]
QQ：85559911 也欢迎加入我们的用户群796771754

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。
