### ISSUE TITLE
训练自己数据时验证集出错了

### ISSUE THREAD

**Issue by cloudsurging** [PaddlePaddle/PaddleSeg#1001]
验证集的yml内容：
val_dataset:
  mode: val
  type: Dataset
  dataset_root: data/woven_bag
  val_path: data/woven_bag/val_list.txt
  num_classes: 2
  transforms:
    - type: RandomPaddingCrop
      crop_size: [2048, 1024]
    - type: Normalize

我想随机剪裁并验证，可是出错了：
  File "d:\PaddleSeg\paddleseg\utils\metrics.py", line 40, in calculate_area
    raise ValueError('Shape of `pred` and `label should be equal, '
ValueError: Shape of `pred` and `label should be equal, but there are [1, 1024, 2048] and [1, 3024, 4032].

**Comment by michaelowenliu** [comment]
@cloudsurging Hi, the error log has shown the reason already.

**Comment by chenjw1009** [comment]
@cloudsurging 这个问题你解决了吗

**Comment by cloudsurging** [comment]
没有解决

> @cloudsurging 这个问题你解决了吗

**Comment by chenjw1009** [comment]
@cloudsurging 
    问题大概在这，没有对“test” and "val"数据集的lable 数据transform
    def __getitem__(self, idx):
        image_path, label_path = self.file_list[idx]
        if self.mode == 'test':
            im, _ = self.transforms(im=image_path)
            im = im[np.newaxis, ...]
            return im, image_path
        elif self.mode == 'val':
            im, _ = self.transforms(im=image_path)
            label = np.asarray(Image.open(label_path))
            label = label[np.newaxis, :, :]
            return im, label
        else:
            im, label = self.transforms(im=image_path, label=label_path)
            if self.edge:
                edge_mask = F.mask_to_binary_edge(
                    label, radius=2, num_classes=self.num_classes)
                return im, label, edge_mask
            else:
                return im, label

**Comment by cloudsurging** [comment]
对，就是这个问题，就是这个transform，能否有完整项目示例，我不知道你贴的这个函数加在什么地方。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月27日(周二) 下午5:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleSeg] 训练自己数据时验证集出错了 (#1001)




 
@cloudsurging
 问题大概在这，没有对“test” and "val"数据集的lable 数据transform
 def getitem(self, idx):
 image_path, label_path = self.file_list[idx]
 if self.mode == 'test':
 im, _ = self.transforms(im=image_path)
 im = im[np.newaxis, ...]
 return im, image_path
 elif self.mode == 'val':
 im, _ = self.transforms(im=image_path)
 label = np.asarray(Image.open(label_path))
 label = label[np.newaxis, :, :]
 return im, label
 else:
 im, label = self.transforms(im=image_path, label=label_path)
 if self.edge:
 edge_mask = F.mask_to_binary_edge(
 label, radius=2, num_classes=self.num_classes)
 return im, label, edge_mask
 else:
 return im, label

**Comment by wuyefeilin** [comment]
正常验证时不会进行RandomPaddingCrop

**Comment by 02825cm** [comment]
> @cloudsurging 问题大概在这，没有对“test” and "val"数据集的lable 数据transform def **getitem**(self, idx): image_path, label_path = self.file_list[idx] if self.mode == 'test': im, _ = self.transforms(im=image_path) im = im[np.newaxis, ...] return im, image_path elif self.mode == 'val': im, _ = self.transforms(im=image_path) label = np.asarray(Image.open(label_path)) label = label[np.newaxis, :, :] return im, label else: im, label = self.transforms(im=image_path, label=label_path) if self.edge: edge_mask = F.mask_to_binary_edge( label, radius=2, num_classes=self.num_classes) return im, label, edge_mask else: return im, label

@chenjw1009 这段代码加载哪里，大佬，求助

**Comment by GexLoong** [comment]
> 正常验证时不会进行RandomPaddingCrop

请问大佬我不加RandomPaddingCrop，也为报错all the input array dimensions for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 401 and the array at index 1 has size 512，但是我的数据图片分辨率都是512*512的，有一部分是630*630的，不知道为什么报错401，求教
配置文件如下：
val_dataset:
  type: Dataset
  dataset_root: ../data/data134998/prepare_data
  val_path: ../data/data134998/prepare_data/val.txt
  num_classes: 2
  transforms:
    - type: Normalize
  mode: val
