### ISSUE TITLE
jingling2seg是不是不能用啊

### ISSUE THREAD

**Issue by cloudsurging** [PaddlePaddle/PaddleSeg#1003]
用jingling2seg的标注来训练optic不能分割，而使用label2seg的标注来训练就能分割了。jingling2seg是不是不能用啊？

**Comment by cloudsurging** [comment]
不是不能用，而是精灵标注方式得用多边形圈

**Comment by lingorX** [comment]
It seems that you are on to something and it would be kind if you could share the details with us.
