### ISSUE TITLE
动态图转静态图后推理效果骤降

### ISSUE THREAD

**Issue by zhaop-l** [PaddlePaddle/PaddleSeg#1008]
采用`Fast-scnn`进行训练。训练完后转化成静态图效果骤降。
如下图所示，最左侧为原图，中间为动态图推理，右侧为静态图推理。
![RqCp85IUHd](https://user-images.githubusercontent.com/50993924/117532158-bb1ee580-b018-11eb-969b-00aace6624be.png)
![Tt7od7WyQc](https://user-images.githubusercontent.com/50993924/117532160-beb26c80-b018-11eb-8a5a-de5eb3cd80d0.png)

运行环境为：
```
ubuntu18.04
python3.8
PaddlePaddle2.0.1
cuda11.0
cudnn8.1
```

**Comment by lingorX** [comment]
With the release of paddlepaddle 2.0, dynamic graph will become the staple for development and maintenance. If you have tough requirements for storage or inference speed, we emphatically recommend paddleslim to distill existing models.  Or if you must use this dynamic to static conversion for some reason, please post your conversion code.

**Comment by TinyQi** [comment]
我也跟你遇到一样的情况了，不知道是什么原因，楼主你解决了码
