### ISSUE TITLE
验证时报错AttributeError: 'int' object has no attribute 'numpy

### ISSUE THREAD

**Issue by Dilemma111** [PaddlePaddle/PaddleSeg#1012]
使用paddleseg动态图 无论使用那个模型进行训练都报这个错 AttributeError: 'int' object has no attribute 'numpy
我的操作是：原始数据集可以跑通 然后我将数据集做了剪裁 并使用cv2.imwrite进行保存 图片类型是uint8 训练是没有问题的 只要一验证就会报这个错误 希望大佬可以解答一下 万分感谢

**Comment by lingorX** [comment]
Can you be more specific? Perhaps the code you modified is needed to help us locate the problem.
