### ISSUE TITLE
图片输入格式错误？

### ISSUE THREAD

**Issue by xuxiaoxxxx** [PaddlePaddle/PaddleSeg#1013]
请问在运行OCRNet时数据按照原始处理了，一张图片还是512x512x3，但是为什么会出现五维这个问题？
ValueError: (InvalidArgument) The input tensor's dimension should be equal to the axis's size. But received input tensor's dimension is 5, axis's size is 4
  [Hint: Expected x_rank == axis_size, but received x_rank:5 != axis_size:4.] (at /paddle/paddle/fluid/operators/transpose_op.cc:47)
  [operator < transpose2 > error]

**Comment by lingorX** [comment]
Maybe you can try to print the information for each iteration of the dataloader. Let us know if you get any results.
