### ISSUE TITLE
BCELoss in Decoupled SegNet

### ISSUE THREAD

**Issue by Birdylx** [PaddlePaddle/PaddleSeg#1022]
I read the code of decoupled segnet, the `seg_edge_out` in the [line](https://github.com/PaddlePaddle/PaddleSeg/blob/1417b8fba841b3bf75f2e69c332ec16065bd4643/paddleseg/models/decoupled_segnet.py#L168) has  been already applied `Sigmoid` function, but in the edge loss computation stage, you use BCELoss which combines sigmoid fucn and loss layer in [line 163](https://github.com/PaddlePaddle/PaddleSeg/blob/1417b8fba841b3bf75f2e69c332ec16065bd4643/paddleseg/models/losses/binary_cross_entropy_loss.py#L163), it confused me why use sigmoid func twice, is it reasonable to use sigmoid twice in loss computation? 
wait for reply, thanks

**Comment by lingorX** [comment]
[edge_loss](https://github.com/lxtGH/DecoupleSegNets/blob/fa204d2dc28030f510048927e0deb934e8fd05a0/loss.py#L357)
[sigmoid_layer](https://github.com/lxtGH/DecoupleSegNets/blob/fa204d2dc28030f510048927e0deb934e8fd05a0/network/deepv3_decouple.py#L139)
We implemented the model in its raw form, and if you have any questions, you can ask the original author.

**Comment by Birdylx** [comment]
@0liliulei thanks for your reply！
