### ISSUE TITLE
多尺度输入

### ISSUE THREAD

**Issue by xuxiaoxxxx** [PaddlePaddle/PaddleSeg#1027]
paddleseg现在是否支持多尺度输入，比如现在想自己定义数据集，图片为100x100，paddleseg是否能支持运行？

**Comment by BeyondYourself** [comment]
目前应该是可以自定尺寸，但是不支持多尺寸训练吧

**Comment by xuxiaoxxxx** [comment]
> 目前应该是可以自定尺寸，但是不支持多尺寸训练吧

请问自定义尺寸在哪里定义，我没在参数表中看到，参数说明好像也没有

**Comment by BeyondYourself** [comment]
在transform.py中有个resize方法，可以修改size大小，默认是512X512

**Comment by xuxiaoxxxx** [comment]
> 在transform.py中有个resize方法，可以修改size大小，默认是512X512

好的，非常感谢你的解答！

**Comment by lingorX** [comment]
@BeyondYourself We have implemented [nvidia-style mscale training](https://arxiv.org/abs/2005.10821) in [here](https://github.com/PaddlePaddle/PaddleSeg/blob/release/v2.0/contrib/CityscapesSOTA/models/mscale_ocrnet.py) which adapted to arbitrary scaling.

**Comment by BeyondYourself** [comment]
OK,我也去试验一下
