### ISSUE TITLE
'relu does not exist in the current dict_keys([])'

### ISSUE THREAD

**Issue by kk125678** [PaddlePaddle/PaddleSeg#1034]
昨天还能用今天不行了
是在aistudio
@manager.BACKBONES.add_component
    349 def ResNet101_vd(**args):
--> 350     model = ResNet_vd(layers=101, **args)
    351     return model
    352 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleseg/models/backbones/resnet_vd.py in __init__(self, layers, output_stride, multi_grid, pretrained)
    231 
    232         self.conv1_1 = ConvBNLayer(
--> 233             in_channels=3, out_channels=32, kernel_size=3, stride=2, act='relu')
    234         self.conv1_2 = ConvBNLayer(
    235             in_channels=32,
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleseg/models/backbones/resnet_vd.py in __init__(self, in_channels, out_channels, kernel_size, stride, dilation, groups, is_vd_mode, act)
     54 
     55         self._batch_norm = layers.SyncBatchNorm(out_channels)
---> 56         self._act_op = layers.Activation(act=act)
     57 
     58     def forward(self, inputs):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleseg/models/layers/activation.py in __init__(self, act)
     64             else:
     65                 raise KeyError("{} does not exist in the current {}".format(
---> 66                     act, act_dict.keys()))
     67 
     68     def forward(self, x):
KeyError: 'relu does not exist in the current dict_keys([])'

**Comment by kk125678** [comment]
![图片](https://user-images.githubusercontent.com/46900538/118582075-53f5f380-b7c5-11eb-9c57-13266ed8f10b.png)

**Comment by a123b12cd** [comment]
附议

**Comment by kk125678** [comment]
感觉是 AIstudio问题，Activation复制到notebook 上是不报错的

**Comment by a123b12cd** [comment]
aistudio版本更新了

**Comment by chandler-25** [comment]
+1

**Comment by aiyasin** [comment]
+1

**Comment by a123b12cd** [comment]
是版本问题，回退版本就可以了

**Comment by aiyasin** [comment]
> 是版本问题，回退版本就可以了

多久可以修复

**Comment by kk125678** [comment]
> 
> 
> 是版本问题，回退版本就可以了

怎么弄，我是萌新

**Comment by chandler-25** [comment]
> 是版本问题，回退版本就可以了

你好 想问一下 这个怎么回退版本呢 没有操作过 把握不住啊

**Comment by a123b12cd** [comment]
> > 是版本问题，回退版本就可以了
> 
> 你好 想问一下 这个怎么回退版本呢 没有操作过 把握不住啊

pip install paddlepaddle-gpu== XXXXX  就可以的，跟本地安装一样

**Comment by chandler-25** [comment]
> > > 是版本问题，回退版本就可以了
> > 
> > 
> > 你好 想问一下 这个怎么回退版本呢 没有操作过 把握不住啊
> 
> pip install paddlepaddle-gpu== XXXXX 就可以的，跟本地安装一样

今天之前的上一个好像是2.0.1,我试试，谢谢大佬

**Comment by michaelowenliu** [comment]
@kk125678 @a123b12cd @chandler-25 Hi, all, The activation-related APIs have been modified a little bit in the NEW PaddlePaddle. We fixed the [PaddleSeg develop](https://github.com/PaddlePaddle/PaddleSeg/tree/develop) version already, and will release v2.1 soon without this problem. Sorry for that!
