### ISSUE TITLE
fine-tune on other task

### ISSUE THREAD

**Issue by MasonSuWei** [PaddlePaddle/PaddleSeg#1035]
Hi,

I want to know whether there is a way to fine-tune pretrained model on another task(for example different dataset). Just like paddleDetector's way described in the following link.
https://github.com/PaddlePaddle/PaddleDetection/blob/8968a22fb06a8a7a313ee9b4bdde7d8a58e33f0d/docs/tutorials/GETTING_STARTED.md

Fine-tune other task

When using pre-trained model to fine-tune other task, pretrain_weights can be used directly. The parameters with different shape will be ignored automatically. For example:

export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
# If the shape of parameters in program is different from pretrain_weights,
# then PaddleDetection will not use such parameters.
python -m paddle.distributed.launch --gpus 0,1,2,3,4,5,6,7 tools/train.py -c configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.yml \
                         -o pretrain_weights=output/faster_rcnn_r50_1x_coco/model_final \

**Comment by lingorX** [comment]
I would say it's absolutely feasible.

Take [deeplabv3p](https://github.com/PaddlePaddle/PaddleSeg/blob/release/v2.0/configs/deeplabv3p/deeplabv3p_resnet101_os8_cityscapes_1024x512_80k.yml) as example, by prepending the `pretrained` attribute under `model` just like following:

![image](https://user-images.githubusercontent.com/31980417/118757815-698c1b80-b8a0-11eb-9940-f0426ec7f4d4.png)

Loading pre-training parameters to finetune would do the trick.

**Comment by MasonSuWei** [comment]
> I would say it's absolutely feasible.
> 
> Take [deeplabv3p](https://github.com/PaddlePaddle/PaddleSeg/blob/release/v2.0/configs/deeplabv3p/deeplabv3p_resnet101_os8_cityscapes_1024x512_80k.yml) as example, by prepending the `pretrained` attribute under `model` just like following:
> 
> ![image](https://user-images.githubusercontent.com/31980417/118757815-698c1b80-b8a0-11eb-9940-f0426ec7f4d4.png)
> 
> Loading pre-training parameters to finetune would do the trick.

@0liliulei, thanks for quick replay. The method mentioned above works.
