### ISSUE TITLE
export导出问题

### ISSUE THREAD

**Issue by a123b12cd** [PaddlePaddle/PaddleSeg#1039]
最新版的(2021.5.19)的export.py 导出的模型中，在指定input shape的情况下，模型还是有很多op是动态shape的，导致在利用tensorrt部署时会报错，请问为什么会这样？如何解决？   之前版本中同样的模型，同样的op，就是静态shape，新代码中就是动态shape。
模型：eg：unet/deeplabv3p   op: bilinear_interp

**Comment by nepeplwu** [comment]
@a123b12cd 麻烦贴下完整的报错堆栈，另外请问下：`之前版本中同样的模型，同样的op，就是静态shape，新代码中就是动态shape。`是什么时候的版本？

**Comment by a123b12cd** [comment]
> @a123b12cd 麻烦贴下完整的报错堆栈，另外请问下：`之前版本中同样的模型，同样的op，就是静态shape，新代码中就是动态shape。`是什么时候的版本？



（1）设置+log1 （参考动态shape op前后op对应的shape设置）
![image](https://user-images.githubusercontent.com/49675099/118913370-e6c89680-b95b-11eb-8bac-51aa632517db.png)
![image](https://user-images.githubusercontent.com/49675099/118913437-0e1f6380-b95c-11eb-8c73-c3591484ff31.png)
（2）设置+log2
![image](https://user-images.githubusercontent.com/49675099/118913633-69e9ec80-b95c-11eb-9382-03e42710102c.png)
![image](https://user-images.githubusercontent.com/49675099/118913685-8554f780-b95c-11eb-94d0-cdf20dc538b8.png)
个人理解，如果（1）中的设置可以跑通，（2）中只是将min改小了，应该也可以跑通才是。


***** 之前版本就是最开始的动态图版本，export.py中主要代码如下：
   
![image](https://user-images.githubusercontent.com/49675099/118928465-d4f3ed00-b975-11eb-8e07-7e6caf5e558b.png)

**Comment by nepeplwu** [comment]
@a123b12cd ：
1. `设置+log2`示例的C++代码中，channel维度不需要 / 8，并且第十行的width维度没有 / 8，可以更新后再验证下看看
```C++
{'X', {1, 3, 1024/8, 512}}
```
2. ` 之前版本就是最开始的动态图版本，export.py中主要代码如下：`
我们近期确实修改了export.py的代码，将导出shape升级为动态shape，可以试试修改代码中的[第111行](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.1/export.py#L111)，改成你想要用的shape试试看，我们会在近期升级该脚本，支持用户指定shape

**Comment by a123b12cd** [comment]
>    我们近期确实修改了export.py的代码，将导出shape升级为动态shape，可以试试修改代码中的[第111行](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.1/export.py#L111)，改成你想要用的shape试试看，我们会在近期升级该脚本，支持用户指定shape

目前就是这么操作的，但是指定了输入的shape，中间部分op还是会出现动态shape
![image](https://user-images.githubusercontent.com/49675099/119431906-fe31c600-bd45-11eb-87a0-de7989fadf2d.png)
![image](https://user-images.githubusercontent.com/49675099/119432266-99c33680-bd46-11eb-9035-9312f6df06d6.png)

**Comment by nepeplwu** [comment]
@a123b12cd 目前这个问题暂时没有很好的解决方法（同时兼顾动态shape和静态shape），后续我们有更好的解决方案后会升级下代码。如果你确实希望使用静态shape，可以试试先在本地回滚下代码。

**Comment by a123b12cd** [comment]
> @a123b12cd 目前这个问题暂时没有很好的解决方法（同时兼顾动态shape和静态shape），后续我们有更好的解决方案后会升级下代码。如果你确实希望使用静态shape，可以试试先在本地回滚下代码。

倒不是一定要用静态shape，主要是想用tensorrt加速，而动态shape在tensorrt部署时会报错。  所以就是说使用paddle2.0（动态图版本）之后导出的模型就不能用tensorrt部署了吧？

**Comment by nepeplwu** [comment]
@a123b12cd 我看你上面贴的截图里面，设置1是可以跑得通的，设置2看着有些shape没设置对：


> 设置+log2示例的C++代码中，channel维度不需要 / 8，并且第十行的width维度没有 / 8，可以更新后再验证下看看
> 
> ```c++
> {'X', {1, 3, 1024/8, 512}}
> ```

**Comment by axxx-xxxa** [comment]
> > @a123b12cd 目前这个问题暂时没有很好的解决方法（同时兼顾动态shape和静态shape），后续我们有更好的解决方案后会升级下代码。如果你确实希望使用静态shape，可以试试先在本地回滚下代码。
> 
> 倒不是一定要用静态shape，主要是想用tensorrt加速，而动态shape在tensorrt部署时会报错。 所以就是说使用paddle2.0（动态图版本）之后导出的模型就不能用tensorrt部署了吧？

请问一下 deeplabv3怎么转为tensorrt推理
