### ISSUE TITLE
Best Model Not Saved

### ISSUE THREAD

**Issue by pubudusanjeewani** [PaddlePaddle/PaddleSeg#1042]
Hi,

I am trying to train the sample dataset as mentioned in the documentation using GPU. The program saves the model at 1000 iterations. But, it does not save the best model. It doesn't show any error. Please, see the attached snapshot of the terminal. Could you please help me to fix this ?

<img width="960" alt="Error" src="https://user-images.githubusercontent.com/28475337/118898751-9f88d880-b950-11eb-83de-18029c9e3311.PNG">

Thank You.

**Comment by michaelowenliu** [comment]
@pubudusanjeewani Hi, may I know whether you run the running command with `--do_eval`?

**Comment by pubudusanjeewani** [comment]
Hi,

Sorry, I think I haven't used --do_eval. I used it and the program is working well now. Thanks you very much for the prompt reply. 

Thank You.

**Comment by michaelowenliu** [comment]
@pubudusanjeewani Hi, glad to hear that you have solved the problem.
