### ISSUE TITLE
官方infer教程报错

### ISSUE THREAD

**Issue by xuanxiaoliqu** [PaddlePaddle/PaddleSeg#1052]
File "infer.py", line 106, in run
    self.postprocess(results, imgs)
  File "infer.py", line 118, in postprocess
    result = get_pseudo_color_map(result)
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddleseg\utils\visualize.py", line 59, in get_pseudo_color_map
    pred_mask = PILImage.fromarray(pred.astype(np.uint8), mode='P')
  File "D:\Anaconda3\envs\paddle\lib\site-packages\PIL\Image.py", line 2784, in fromarray
    raise ValueError(f"Too many dimensions: {ndim} > {ndmax}.")
ValueError: Too many dimensions: 3 > 2.

**Comment by LutaoChu** [comment]
你好，请提供一下教程链接和运行的命令，我们复现一下

**Comment by xuanxiaoliqu** [comment]
> 你好，请提供一下教程链接和运行的命令，我们复现一下

https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.1/deploy/python

**Comment by xuanxiaoliqu** [comment]
用的都是给的样例模型和图片

**Comment by MsWik** [comment]
我遇到了同样的错误（[冒号](https://colab.research.google.com/drive/1ZzZVpys3Sw7t34mglhh7-3H63kw63Eze?usp=sharing)）。

**Comment by LutaoChu** [comment]
@xuanxiaoliqu @MsWik 原因找到了，是因为示例模型网络末端没有argmax op。已经更新了示例模型，重新下载试试

**Comment by MsWik** [comment]
该演示作品。
有一个问题-尝试处理我自己的png文件列表时没有结果。您可以举一个网络摄像头的例子吗？

**Comment by LutaoChu** [comment]
> 该演示作品。
> 有一个问题-尝试处理我自己的png文件列表时没有结果。您可以举一个网络摄像头的例子吗？

```
# 通过电脑摄像头进行实时背景替换处理, 也可通过'--background_video_path'传入背景视频
python bg_replace.py \
--cfg export_model/shufflenetv2_humanseg_192x192_with_softmax/deploy.yaml \
--background_image_path data/background.jpg
```
来自https://github.com/PaddlePaddle/PaddleSeg/tree/develop/contrib/HumanSeg

**Comment by rock4you** [comment]
> @xuanxiaoliqu @MsWik 原因找到了，是因为示例模型网络末端没有argmax op。已经更新了示例模型，重新下载试试

自己训练的模型，导出后进行infer，也遇到了同样的问题，运行时添加--with_argmax 即可。
