### ISSUE TITLE
关于warmup在2.0版本里面的使用问题

### ISSUE THREAD

**Issue by kymoran3169** [PaddlePaddle/PaddleSeg#1054]
![image](https://user-images.githubusercontent.com/53987628/119964890-3d794480-bfdc-11eb-88d4-77dd93641f7e.png)
为啥2.0新版本套件里面取消了warmup的设置，
想自己添加，才发现这里是直接的返回函数，不能简单设置

**Comment by michaelowenliu** [comment]
@kymoran3169 Hi, we take it as a new feature.
