### ISSUE TITLE
关于背景的标签问题

### ISSUE THREAD

**Issue by yuemengrui** [PaddlePaddle/PaddleSeg#1055]
背景是分为255忽略更好，还是分成一个分类更好

**Comment by linhandev** [comment]
肯定不能忽略,背景分错也应该产生损失

**Comment by yuemengrui** [comment]
> 肯定不能忽略,背景分错也应该产生损失

你好！背景在图片中的占比相对较大，我想让模型更加关注需要的分类，而不分心去关注背景。在iou中，背景的iou挺高的，造成miou整体偏高。

**Comment by linhandev** [comment]
但是你在推理的过程中是不知道哪个像素是背景的，这么搞你训练的时候看着方便，但是推理的话肯定不少假阳性

**Comment by bit-scientist** [comment]
Hi, @linhandev , could you help me out on [this question](https://github.com/PaddlePaddle/PaddleSeg/issues/2524#issuecomment-1687649119) please? I'd appreciate your help
