### ISSUE TITLE
inference custom model on human_segmentation_demo

### ISSUE THREAD

**Issue by nqthai309** [PaddlePaddle/PaddleSeg#1059]
**I want to make predictions on my data and based on example human_segmentation_demo**

I trained based on fcn_hrnetw18_small_v1_humanseg_192x192_mini_supervisely.yml (folder contrib/HumanSeg/configs)
and custom data, I **didn't** change anything

Here is the result predicted on my data using python, **its work fine**
![card_test](https://user-images.githubusercontent.com/61822545/120451403-94579300-c3bb-11eb-9c7b-23674918139b.jpg)

I use paddle_lite_opt v2.8 to convert the above model, below is the result
![image](https://user-images.githubusercontent.com/61822545/120451921-09c36380-c3bc-11eb-8696-bd9a46398410.png)
![image](https://user-images.githubusercontent.com/61822545/120451976-1647bc00-c3bc-11eb-9a81-7ce3a1238fbc.png)

After converting I have **.nb**, i add them to android project human_segmentation_demo like below
![image](https://user-images.githubusercontent.com/61822545/120452443-645cbf80-c3bc-11eb-84fb-2123863c705a.png)

and change the content inside strings.xml
![image](https://user-images.githubusercontent.com/61822545/120452793-aab21e80-c3bc-11eb-8c67-536b6e371e45.png)

But when running, the program crashes. I tried to debug and found where the problem occurred  - line 224 (predictor.java)
![image](https://user-images.githubusercontent.com/61822545/120453067-e9e06f80-c3bc-11eb-8670-2290e37c95ce.png)

Looks like **outputTensor.getLongData()** has some problem (inside visualize.draw(inputImage, outputTensor) )
![image](https://user-images.githubusercontent.com/61822545/120453355-2a3fed80-c3bd-11eb-90f7-a50a49a448c0.png)

Can someone help me :((((

**Comment by LutaoChu** [comment]
Please provide the error information of Java code.

I wonder if you set `with_softmax` or `without_argmax` when exporting the model, causing the network output to be of float type

**Comment by nqthai309** [comment]
**this is what i do to export the model and result**

![image](https://user-images.githubusercontent.com/61822545/120603151-e6f58580-c475-11eb-9de2-980a3409ef5e.png)
![image](https://user-images.githubusercontent.com/61822545/120603200-f4127480-c475-11eb-8a59-82e4ceefe7eb.png)

**This is error of java code**
![image](https://user-images.githubusercontent.com/61822545/120603366-258b4000-c476-11eb-824f-d2ceaf674835.png)

@LutaoChu

**Comment by LutaoChu** [comment]
You can try not to set with_softmax or without_argmax when exporting the model

**Comment by nqthai309** [comment]
@LutaoChu  thank you so much <3, i tried it and it worked fine
