### ISSUE TITLE
为什么crop的size长和宽都是一样的

### ISSUE THREAD

**Issue by universea** [PaddlePaddle/PaddleSeg#106]
如上问题，我的训练图片是3384x1710，TRAIN_CROP_SIZE和EVAL_CROP_SIZE，应该设为多少呢，为什么不按照比例来设置这个CROP的size而用个正方形呢？

**Comment by LutaoChu** [comment]
您好，TRAIN_CROP_SIZE和EVAL_CROP_SIZE的设置不一定要求正方形，如果显存足够您可以设置为3384x1710。

实际上，TRAIN_CROP_SIZE是可以任意设置的，EVAL_CROP_SIZE按照以下条件即可：
当AUG.AUG_METHOD为unpadding时，EVAL_CROP_SIZE的宽高应不小于AUG.FIX_RESIZE_SIZE的宽高。
当AUG.AUG_METHOD为stepscaling时，EVAL_CROP_SIZE的宽高应不小于原图中最大的宽高。
当AUG.AUG_METHOD为rangscaling时，EVAL_CROP_SIZE的宽高应不小于缩放后图像中最大的宽高。

**Comment by universea** [comment]
> 您好，TRAIN_CROP_SIZE和EVAL_CROP_SIZE的设置不一定要求正方形，如果显存足够您可以设置为3384x1710。
> 
> 实际上，TRAIN_CROP_SIZE是可以任意设置的，EVAL_CROP_SIZE按照以下条件即可：
> 当AUG.AUG_METHOD为unpadding时，EVAL_CROP_SIZE的宽高应不小于AUG.FIX_RESIZE_SIZE的宽高。
> 当AUG.AUG_METHOD为stepscaling时，EVAL_CROP_SIZE的宽高应不小于原图中最大的宽高。
> 当AUG.AUG_METHOD为rangscaling时，EVAL_CROP_SIZE的宽高应不小于缩放后图像中最大的宽高。
好的，太谢谢啦！

**Comment by universea** [comment]
> 您好，TRAIN_CROP_SIZE和EVAL_CROP_SIZE的设置不一定要求正方形，如果显存足够您可以设置为3384x1710。
> 
> 实际上，TRAIN_CROP_SIZE是可以任意设置的，EVAL_CROP_SIZE按照以下条件即可：
> 当AUG.AUG_METHOD为unpadding时，EVAL_CROP_SIZE的宽高应不小于AUG.FIX_RESIZE_SIZE的宽高。
> 当AUG.AUG_METHOD为stepscaling时，EVAL_CROP_SIZE的宽高应不小于原图中最大的宽高。
> 当AUG.AUG_METHOD为rangscaling时，EVAL_CROP_SIZE的宽高应不小于缩放后图像中最大的宽高。

好的，太感谢啦！
