### ISSUE TITLE
请问下，我用2080Ti在windows10下训练，显存够的情况下怎么提高BatchSize

### ISSUE THREAD

**Issue by JustinHuang1984** [PaddlePaddle/PaddleSeg#1065]
我的2080Ti有11G显存，BatchSize设为35可以正常训练，显存大概只用了7.2G,但是我将BatchSize调大一点比如说到36，训练就会卡住如下图的地方，请问下要怎么设置才能最有效的提高BatchSize和GPU利用率而不卡住吗
 MODEL:
    DEFAULT_NORM_TYPE: "bn"
    MODEL_NAME: "deeplabv3p"
    DEEPLAB:
        BACKBONE: "mobilenetv2"
        ASPP_WITH_SEP_CONV: True
        DECODER_USE_SEP_CONV: True
        ENCODER_WITH_ASPP: False
        ENABLE_DECODER: False
![屏幕截图 2021-06-03 152010](https://user-images.githubusercontent.com/59753769/120605509-b535ec00-c480-11eb-8818-4a918e9f3e92.png)

**Comment by michaelowenliu** [comment]
@JustinHuang1984 Hi, reduce the image size.
