### ISSUE TITLE
SetCpuMathLibraryNumThreads(2)后，cpu高出了一倍，但速度没起来。

### ISSUE THREAD

**Issue by DoItNow321Go** [PaddlePaddle/PaddleSeg#1069]
c++代码进行人像分割， 使用的官网Windows cpu_avx_mkl 2.1.0预测库。

cpu:  Intel(R) Core(TM) it-4590 CPU @ 3.30GHz

配置为：
	paddle_infer::Config config;
	config.DisableGpu();
	config.EnableMKLDNN();
	config.SetCpuMathLibraryNumThreads(threadCount);
	config.SetModel(strModel.c_str(), strParams.c_str());
	config.EnableMemoryOptim();
	_main_predictor = paddle_infer::CreatePredictor(config);

预测的图像大小为: 288*160

以上threadCount，1，2，3等， cpu会爆涨（25%->50%->75%)，但每个图像的耗时没有变短。

**Comment by LutaoChu** [comment]
你好，请问你用的API是PaddleX或者Paddle Inference吗？是的话建议前往对应的repo咨询
