### ISSUE TITLE
eval bug ? 

### ISSUE THREAD

**Issue by universea** [PaddlePaddle/PaddleSeg#107]
4 gpu train 

however when eval :

![Screenshot from 2019-11-30 22-29-57](https://user-images.githubusercontent.com/13444641/69901772-feefd300-13c0-11ea-9305-3071d0017109.png)

each gpu repeat eval

**Comment by LutaoChu** [comment]
Hello, please update to the latest code to try it out and check if you have modified the training script. If it still does not work, please provide your operating environment, training configuration and PaddlSeg version.

**Comment by nepeplwu** [comment]
This issue has not been updated in the last three months. We will close this issue. Please reopen it if necessary.
