### ISSUE TITLE
段错误(吐核). FatalError: A serious error (Segmentation fault) is detected by the operating system

### ISSUE THREAD

**Issue by XuyangPan** [PaddlePaddle/PaddleSeg#1073]
你好 我在对人像视频进行分割处理时，使用的全是默认参数和官方提供的测试数据集，遇到这个bug，方便回复一下解决办法吗？ 谢谢！
![11111](https://user-images.githubusercontent.com/39898699/121008881-0f5ae800-c7c6-11eb-88a2-fa419374a4ae.jpg)

**Comment by XuyangPan** [comment]
在执行   python video_infer.py --cfg export_model/deeplabv3p_resnet50_os8_humanseg_512x512_100k_with_softmax/deploy.yaml --video_path data/video_test.mp4  时，出现了上面的bug

**Comment by nieyun04** [comment]
![image](https://user-images.githubusercontent.com/38587020/121326908-8c609b80-c945-11eb-84d3-406fd3bc6592.png)

在训练pspnet的时候报错: python train.py --config configs/pspnet/pspnet_resnet50_os8_voc12aug_512x512_40k.yml
paddleseg2.1版本不支持pspnet吗

**Comment by LutaoChu** [comment]
@XuyangPan 请check一下你的cudnn版本和cuda版本是不是符合paddle的要求呢？
![image](https://user-images.githubusercontent.com/30695251/121502255-92707e00-ca12-11eb-8c8f-4bec86f753b5.png)
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html

**Comment by LutaoChu** [comment]
> ![image](https://user-images.githubusercontent.com/38587020/121326908-8c609b80-c945-11eb-84d3-406fd3bc6592.png)
> 
> 在训练pspnet的时候报错: python train.py --config configs/pspnet/pspnet_resnet50_os8_voc12aug_512x512_40k.yml
> paddleseg2.1版本不支持pspnet吗

估计是cudnn版本和cuda版本不匹配的问题，建议cudnn版本改为7.6，或者cuda runtime API version改为11

**Comment by bldu** [comment]
> > ![image](https://user-images.githubusercontent.com/38587020/121326908-8c609b80-c945-11eb-84d3-406fd3bc6592.png)
> > 在训练pspnet的时候报错: python train.py --config configs/pspnet/pspnet_resnet50_os8_voc12aug_512x512_40k.yml
> > paddleseg2.1版本不支持pspnet吗
> 
> 估计是cudnn版本和cuda版本不匹配的问题，建议cudnn版本改为7.6，或者cuda runtime API version改为11

能否增加针对cuda10.1/10.2的cudnn的高版本支持呢？目前用的cuda10.1， cudnn8+会报错 segmentation fault。cudnn用7.6是可以的。

**Comment by LutaoChu** [comment]
建议去paddle主repo下提需求，编译一些支持高版本cudnn的paddle包出来
