### ISSUE TITLE
运行时错误：找不到指定的组件。

### ISSUE THREAD

**Issue by peteli25** [PaddlePaddle/PaddleSeg#1079]
RuntimeError: The specified component was not found vit.

**Comment by haoyuying** [comment]
您好，根据报错应该是config里面包含了非法的字段名称吧，看下你配置的yaml文件是不是有问题。可以参考paddleseg configs文件夹下的yaml文件：https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.1/configs

**Comment by peteli25** [comment]
我想把deeplabv3的backbone换了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月10日(周四) 下午5:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleSeg] 运行时错误：找不到指定的组件。 (#1079)




 
您好，根据报错应该是config里面包含了非法的字段名称吧，看下你配置的yaml文件是不是有问题。可以参考paddleseg configs文件夹下的yaml文件：https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.1/configs

**Comment by haoyuying** [comment]
请确认您使用的backbone名称是否合法，目前错误的原因是您使用的backbone的命名在我们提供的backbone中查找不到，可以参考其他config的backbone设定进行调整。

**Comment by peteli25** [comment]
在paddledetect里面把backbone都替换成了swim transformer，在paddleseg我也想试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月11日(星期五) 下午5:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleSeg] 运行时错误：找不到指定的组件。 (#1079)





 
请确认您使用的backbone名称是否合法，目前错误的原因是您使用的backbone的命名在我们提供的backbone中查找不到，可以参考其他config的backbone设定进行调整。
 
&mdash;

**Comment by haoyuying** [comment]
目前paddleseg还不支持此类backbone，因此会报错，之后我们会不断丰富backbone类型，敬请期待。
