### ISSUE TITLE
使用paddleX进行C++部署PeddleSeg编译时报错：target(for copy command) ")" is model_infer not a directory

### ISSUE THREAD

**Issue by aiwenzhu** [PaddlePaddle/PaddleSeg#1085]
参考的是官方教程https://github.com/PaddlePaddle/PaddleX/blob/develop/dygraph/deploy/cpp/docs/compile/paddle/windows.md
前边一切顺利，最后编译的时候出现target(for copy command) ")" is model_infer not a directory

**Comment by LutaoChu** [comment]
相同的issue出现在PaddleX，统一在那边进行回复  https://github.com/PaddlePaddle/PaddleX/issues/827
