### ISSUE TITLE
怎样训练遥感数据？

### ISSUE THREAD

**Issue by kingbirdWc** [PaddlePaddle/PaddleSeg#1091]
您好，我有一些遥感反射率影像，16bit，值的范围是0-10000。请问能直接训练吗？还是必须要转成0-255的范围才能训练呢？

**Comment by LutaoChu** [comment]
你好，暂时还不能直接训，需要转换一下。
或者你可以修改一下读图的代码，支持16bit数据读取。transform可能也需要相应修改

**Comment by kingbirdWc** [comment]
您好， 在paddleseg\datasets\dataset.py中修改，可以自己再定义一个类，在配置文件中引用这个类是吗？

**Comment by LutaoChu** [comment]
是的，引用相同的类名就可以
