### ISSUE TITLE
PaddleSeg输出Segmetation的坐标

### ISSUE THREAD

**Issue by wflrz123** [PaddlePaddle/PaddleSeg#1096]
PaddleSeg做推理的时候输出的是分割的图片，能否输出分割的坐标Segmetation，类似json标注文件里的形式

**Comment by nepeplwu** [comment]
@wflrz123 感谢反馈，相关的功能可以通过输出的mask自行计算实现

**Comment by BeyondYourself** [comment]
Is there a example?

**Comment by nepeplwu** [comment]
@BeyondYourself , The output result of the segmentation model is a Tensor ***`X`*** with a shape of ***`[N, H, W]`***, where ***`N`*** represents batch size, ***`H`*** represents image height, and ***`W`*** represents image width. Assuming that the task is ***`K`*** classification, then each pixel value is an integer value between ***`[0, K)`***, we can use `np.where()` to get the coordinates corresponding to each category, and then organize it into the required format. For example:
```python
import numpy as np

# Suppose X is the segmentation result of a K classification.
X = ...
K = ...

for i in range(K):
    batch_id, coord_x, coord_y = np.where(X == i)

    # Reorganize the output
    ...
```

**Comment by BeyondYourself** [comment]
@ thx ,I will try it later
