### ISSUE TITLE
BiSeNet V2  参数lambd

### ISSUE THREAD

**Issue by FjjRichard** [PaddlePaddle/PaddleSeg#1097]
def __init__(self,
                 num_classes,
                 lambd=0.25,
                 align_corners=False,
                 pretrained=None):
        super().__init__()

参数lambd 指希腊字母表中排序第十一位的字母λ（lambda）,请问为什么漏一个字母a，还是有特别的意义？

**Comment by nepeplwu** [comment]
@richarddddd198 因为lambda是python的保留字

**Comment by FjjRichard** [comment]
谢谢回答，没有考虑这个点
