### ISSUE TITLE
导出的模型属性：输入：type: float32[?,3,?,?] 输出：type: float32[?,2,?,?] 为什么是问号？

### ISSUE THREAD

**Issue by Fly-hub** [PaddlePaddle/PaddleSeg#1098]
使用paddleseg模型库训练的unet网络模型，使用export.py导出的静态图模型的属性为什么是这样：输入：type: float32[?,3,?,?] 输出：type: float32[?,2,?,?] ，为什么只有通道数是固定的？之后使用paddle2onnx转换成onnx模型，无法使用onnxruntime推理部署。转换后的onnx模型的输入输出是这样：输入type: float32[-1,3,-1,-1] 输出 type: float32[-1,2,-1,-1]
上面的输入输出type：float32 ......都是通过visualdl查看.pdimodel和.onnx模型属性得到的。

**Comment by nepeplwu** [comment]
@Fly-hub `?`表示该维度的值是不固定的，这样导出的模型，支持不同batch大小，不同的宽度和高度的输入图片。无法用onnxruntime推理部署，报的错误是什么？

**Comment by Fly-hub** [comment]
是使用onnx的错误，[ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid Feed Input Name:image 是因为输入图像的名字没写对，现在更改完了。但是使用onnxruntime推理的结果类型为什么是list？而不是numpy.ndarray?输入的数据类型明明是numpy.ndarray，是onnxruntime的问题吗？还是我哪里没搞对？

**Comment by nepeplwu** [comment]
> ... 但是使用onnxruntime推理的结果类型为什么是list？而不是numpy.ndarray?输入的数据类型明明是numpy.ndarray，是onnxruntime的问题吗？还是我哪里没搞对？

因为模型可能有多个输出，一般来讲，取第1个输出结果就行

**Comment by Fly-hub** [comment]
import cv2
import time
import numpy as np
import onnxruntime
import matplotlib.pyplot as plt

sess = onnxruntime.InferenceSession("segonnx/unetmodel.onnx")
img_path = 'PaddleSeg/data/optic_disc_seg/JPEGImages/P0010.jpg'

img0 = cv2.imread(img_path)
img1 = cv2.resize(img0, (512, 512))
ori_image = cv2.cvtColor(img1, cv2.COLOR_BGR2RGB)
input_image = ori_image.astype(np.float32) / 255.0
input_image = np.transpose(input_image, [2, 0, 1])
img_data = input_image[np.newaxis, :, :, :]

start_time = time.time()
ort_inputs = {sess.get_inputs()[0].name: img_data}
print(type(ort_inputs))
result = sess.run(None, ort_inputs)
end_time = time.time()
print("Time used: ", end_time - start_time, 's')

r_map = result[0]
print("查看result[0]是什么类型",type(r_map))

image=np.asanyarray(conf_map,dtype=np.uint8)
print(type(image))
cv2.imwrite("out.jpg", image)

#没有成功保存为图片，请问是我哪里写错了啊？

#结果显示如下：
#<class 'dict'>
#Time used: 3.0770576000213623 s
#查看result[0]是什么类型 <class 'numpy.ndarray'>
#<class 'numpy.ndarray'>
#False

**Comment by nepeplwu** [comment]
打印下image.shape看看

**Comment by Fly-hub** [comment]
输入输出图像的shape如下所示：
运行耗时: 3秒214毫秒
打印输入图像shape： (1, 3, 512, 512)
<class 'dict'>
查看result[0]是什么类型 <class 'numpy.ndarray'>
<class 'numpy.ndarray'>
打印输出图像的shape： (1, 2, 512, 512)
False

**Comment by nepeplwu** [comment]
@Fly-hub 输出的结果shape为(1, 2, 512, 512)表示这是一个二分类的结果，需要先进行argmax后（输出为单通道），才算是可以正常保存的图片
