### ISSUE TITLE
PaddleDetection

### ISSUE THREAD

**Issue by GexLoong** [PaddlePaddle/PaddleSeg#1103]
请问PaddleSeg对于存在多人的人流视频进行背景替换效果如何，我们想和PaddleDetection结合，将背景不动物体替换成单一颜色，提高行人检测精度

**Comment by LutaoChu** [comment]
你好，PaddleSeg目前的人像模型可识别单人、多人，但并非针对人数特别多的场景训练。如果你的人流视频人数很多的话，可以尝试在[MHP](https://lv-mhp.github.io/dataset)数据集上finetuning。
