### ISSUE TITLE
四波段的遥感影像训练

### ISSUE THREAD

**Issue by nieyun04** [PaddlePaddle/PaddleSeg#1107]
请问paddleseg支持四波段的图像训练吗，我尝试训练了一个模型，配置文件按照三个通道的没有修改，采用的deeplabv3p框架，resnet50骨干网，训练没有报错，但是训练出来的模型，第一层卷积的的网络输入只有三个通道，是不是四通道数据输入默认按照三个通道读取？

**Comment by michaelowenliu** [comment]
@nieyun04 Hi, four-channel images are not supported yet. Yes, only the first three channels.
