### ISSUE TITLE
What does the parameter "TEST.TEST_MODEL" mean?

### ISSUE THREAD

**Issue by xyry** [PaddlePaddle/PaddleSeg#111]
I see this parameter in 3 places, but I didn't find a description of this parameter.
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.2.0/docs/usage.md 模型评估以及模型可视化下有两处
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.2.0/docs/model_export.md 使用示例有一处

**Comment by nepeplwu** [comment]
TEST.TEST_MODEL用于指定测试模型的路径，在进行评估(eval.py)和可视化(vis.py)中会用到

**Comment by xyry** [comment]
非常感谢
