### ISSUE TITLE
关于忽略255的问题

### ISSUE THREAD

**Issue by tpg112751** [PaddlePaddle/PaddleSeg#1110]
请问 paddleseg默认忽略255白色，可是我的数据集是一个二分类，背景和目标，背景是黑色0，目标是白色255的，怎么做能让paddleseg不忽略255？还想问下，为什么要忽略白色？

**Comment by michaelowenliu** [comment]
@tpg112751 Hi, there, 255 does not mean white color. A simple solution, normalize your image first.

**Comment by tpg112751** [comment]
> @tpg112751 Hi, there, 255 does not mean white color. A simple solution, normalize your image first.

我在config里面，transforms中设置了normalize，但是我注意到dataset.py里面有ignore_index=255，并且训练中的loss一直是0.因为我的数据集的标注是255，背景是0，所以我会有疑问

**Comment by michaelowenliu** [comment]
@tpg112751 Hi, sorry, I misunderstood. Please modify the label, i.e. change 255 to 1.

**Comment by kingbirdWc** [comment]
argmax的时候是直接取的索引，类别从0开始递增
