### ISSUE TITLE
如何使用warmup+PolynomialDecay学习率

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/PaddleSeg#1116]
请问在现有的学习率基础上加上warmup应该如何修改相关配置文件：
lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

**Comment by nepeplwu** [comment]
@huilin16 感谢反馈，目前动态图模式下还不支持通过配置文件制定 warpup + decay的学习率调度方式，我们会尽快补上
