### ISSUE TITLE
关于推理后资源不释放的问题

### ISSUE THREAD

**Issue by spiderpigpig** [PaddlePaddle/PaddleSeg#1117]
首先感谢paddleseg的开源分享。我在windows上使用cpu运行了seg的cpp中的demo，发现在推理后没有释放内存资源，查找了相关资料，找到api文档里的ClearIntermediateTensor和TryShrinkMemory两个函数，在paddleseg代码里搜寻不到，请问我应该如何释放资源，谢谢

// 释放中间Tensor
// 参数：None
// 返回：None
void ClearIntermediateTensor();

// 释放内存池中的所有临时 Tensor
// 参数：None
// 返回：uint64_t - 释放的内存字节数
uint64_t TryShrinkMemory();

**Comment by nepeplwu** [comment]
@spiderpigpig 上面提到的两个方法都是PaddleInference 中Predictor类的接口，直接通过predictor对象调用即可

**Comment by spiderpigpig** [comment]
@nepeplwu 可是我现有的代码里没有这个接口，想问下是不是你们做的seg的demo里使用的paddle版本过低呢？

**Comment by nepeplwu** [comment]
你本地的paddle版本是多少？参照的是哪个demo？

**Comment by spiderpigpig** [comment]
@nepeplwu 版本PaddleSeg-v2.0，demo是legacy/deploy/cpp
