### ISSUE TITLE
部署python端infer 推断时候显示out of memory

### ISSUE THREAD

**Issue by xliu79** [PaddlePaddle/PaddleSeg#1119]
分割任务中:
部署python端infer 推断时测试了三张图片 ，其中有一张显示out of memory

Paddle 2.0.0 版本

![1](https://user-images.githubusercontent.com/31554245/124216692-646ded80-db29-11eb-9e38-cd70655def6f.png)
驱动信息：
![image](https://user-images.githubusercontent.com/31554245/124216774-8c5d5100-db29-11eb-94d6-68bab0d209f3.png)
相关代码:

![image](https://user-images.githubusercontent.com/31554245/124216852-b747a500-db29-11eb-939a-fe5dadfb778f.png)

**Comment by xliu79** [comment]
用来测试的图片地址
链接：https://pan.baidu.com/s/1wcoqld7qNHG5DDXr-gwORg
提取码：0b7v
静态图模型地址
链接：https://pan.baidu.com/s/110Yy8s4AfvlqnmAev8yAvQ
提取码：kjjz
动态图模型地址
链接：https://pan.baidu.com/s/1mE4jA2eaCJdvEvADM50SSw 
提取码：2s34

**Comment by nepeplwu** [comment]
@xliu79 动态图模型地址里面只有参数，没有结构，你使用的是什么模型结构？

**Comment by xliu79** [comment]
使用的是deeplabv3p 这个是我的训练参数
![image](https://user-images.githubusercontent.com/31554245/124432450-38aa6c00-dda4-11eb-9480-53197e287795.png)
![image](https://user-images.githubusercontent.com/31554245/124432685-7909ea00-dda4-11eb-92fe-0f655a87a32d.png)
config文件
链接：https://pan.baidu.com/s/1B7lQkJRShpWZbLyKcsDmcQ 
提取码：bv3j

**Comment by xliu79** [comment]
使用动态图预测没有出现问题，转为静态图后进行推断就出现这个显存占用的问题了。

**Comment by xliu79** [comment]
@nepeplwu 请问这个问题有解决了吗

**Comment by nepeplwu** [comment]
@xliu79 我这边没有找到合适的windows机器，使用linux机器试了下，发现2.0.0和2.1.1的paddle版本使用的显存大小是正常的，
建议使用2.1.1版本验证下呢？如果还是不行的话，可以在infer.py中第67行加入`pred_cfg.enable_memory_optim()`试试看

**Comment by xliu79** [comment]
好的我试一下
