### ISSUE TITLE
在Linux 平台编译指南第四步Step4: 编译报错

### ISSUE THREAD

**Issue by xyry** [PaddlePaddle/PaddleSeg#112]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.2.0/inference/docs/linux_build.md
在进行到make的时候报错
[100%] Linking CXX executable demo
CMakeFiles/demo.dir/demo.cpp.o: In function `__static_initialization_and_destruction_0(int, int)':
demo.cpp:(.text+0x391): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
demo.cpp:(.text+0x434): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
libpaddleseg_inference.a(seg_predictor.cpp.o): In function `PaddleSolution::Predictor::init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
seg_predictor.cpp:(.text+0x599): undefined reference to `paddle::AnalysisConfig::SetModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/demo.dir/build.make:131: recipe for target 'demo' failed
make[2]: *** [demo] Error 1
CMakeFiles/Makefile2:142: recipe for target 'CMakeFiles/demo.dir/all' failed
make[1]: *** [CMakeFiles/demo.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

本机环境信息
分割线------------------------
g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
分割线------------------------
cmake --version
cmake version 3.5.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
分割线------------------------
cat /usr/local/cuda/version.txt 
CUDA Version 9.0.176
分割线------------------------
cat /usr/local/cuda/include/cudnn.h |grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 6
#define CUDNN_PATCHLEVEL 4

#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"
分割线------------------------
$ uname -r
4.15.0-29-generic
分割线------------------------
file orgnization
//home/zhiyu/Desktop/projects$ tree -L 2
.
├── fluid_inference
│   ├── CMakeCache.txt
│   ├── paddle
│   ├── third_party
│   └── version.txt
├── fluid_inference_linux_cuda97_1.6.1.tgz
├── opencv3
│   ├── bin
│   ├── include
│   ├── lib64
│   └── share
├── opencv-3.4.6
│   ├── 3rdparty
│   ├── apps
│   ├── build
│   ├── cmake
│   ├── CMakeLists.txt
│   ├── CONTRIBUTING.md
│   ├── data
│   ├── doc
│   ├── include
│   ├── LICENSE
│   ├── modules
│   ├── platforms
│   ├── README.md
│   └── samples
├── opencv-3.4.6.zip
└── PaddleSeg
    ├── configs
    ├── contrib
    ├── dataset
    ├── docs
    ├── inference
    ├── LICENSE
    ├── pdseg
    ├── pretrained_model
    ├── README.md
    ├── requirements.txt
    ├── serving
    ├── test
    └── turtorial

30 directories, 11 files

不知道应该怎么改，看样子似乎是和demo相关，但无从下手

**Comment by joey12300** [comment]
可以按照Linux编译指南使用G++ 4.8.2 ~ 4.9.4版本的编译器重新编译。如果你使用的是ubuntu，可以参考以下方式更改gcc、g++版本。
```
sudo apt-get install -y gcc-4.8 g++-4.8
update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 100
update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 100
```

**Comment by xyry** [comment]
非常感谢，修改gcc&g++版本后，编译成功
