### ISSUE TITLE
unet系列预训练模型

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/PaddleSeg#1133]
请问有unet系列预训练模型吗，在文档中没有找到

**Comment by michaelowenliu** [comment]
@huilin16 https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.1/configs/unet

**Comment by I-am-ok-but-my-clearlove** [comment]
> @huilin16 https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.1/configs/unet

您好，我发现只要UNet有预训练模型。请问其余UNet的系列模型（如Unet3plus、attentionUnet)有预训练模型么？

**Comment by michaelowenliu** [comment]
@huilin16 Hi, the UNet models are not proper for Cityscapes, so we do not provide the pre-trained models.
