### ISSUE TITLE
预测的时候报错

### ISSUE THREAD

**Issue by xyry** [PaddlePaddle/PaddleSeg#114]
https://github.com/PaddlePaddle/PaddleSeg/tree/release/v0.2.0/inference#3%E7%BC%96%E8%AF%91
中4.3执行预测报错
下面是报错日志
./demo --conf=/home/zhiyu/Desktop/projects/PaddleSeg/inference/conf/humanseg
.yaml --input_dir=/home/zhiyu/Desktop/projects/PaddleSeg/inference/images/humanseg/
WARNING: Logging before InitGoogleLogging() is written to STDERR
W1210 19:44:22.353368 32558 device_context.cc:235] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.0, Runtime API Version: 9.0
W1210 19:44:22.355456 32558 device_context.cc:243] device: 0, cuDNN Version: 7.6.
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::CUDNNConvOpKernel<float>::Compute(paddle::framework::ExecutionContext const&) const
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::CUDNNConvOpKernel<float>, paddle::operators::CUDNNConvOpKernel<double>, paddle::operators::CUDNNConvOpKernel<paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const
6   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&)
7   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
8   paddle::NativePaddlePredictor::Run(std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> > const&, std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> >*, int)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/chenzeyu01/anaconda3/envs/paddle1.3-py36/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1748, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/chenzeyu01/anaconda3/envs/paddle1.3-py36/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/chenzeyu01/anaconda3/envs/paddle1.3-py36/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 2171, in conv2d
    'fuse_relu_before_depthwise_conv': False
  File "/ssd3/chenzeyu01/PaddleSeg/pdseg/models/libs/model_libs.py", line 110, in conv
    return fluid.layers.conv2d(*args, **kargs)
  File "/ssd3/chenzeyu01/PaddleSeg/pdseg/models/backbone/xception.py", line 125, in entry_flow
    param_attr=param_attr))
  File "/ssd3/chenzeyu01/PaddleSeg/pdseg/models/backbone/xception.py", line 86, in net
    data = self.entry_flow(input)
  File "/ssd3/chenzeyu01/PaddleSeg/pdseg/models/modeling/deeplab.py", line 205, in xception
    decode_points=decode_point)
  File "/ssd3/chenzeyu01/PaddleSeg/pdseg/models/modeling/deeplab.py", line 212, in deeplabv3p
    data, decode_shortcut = xception(img)
  File "/ssd3/chenzeyu01/PaddleSeg/pdseg/models/model_builder.py", line 143, in build_model
    logits = model_func(image, class_num)
  File "./pdseg/export_model.py", line 64, in freeze
    infer_prog, startup_prog, phase=ModelPhase.PREDICT)
  File "./pdseg/export_model.py", line 95, in main
    freeze(args)
  File "./pdseg/export_model.py", line 99, in <module>
    main()

----------------------
Error Message Summary:
----------------------
PaddleCheckError: CUDNN_STATUS_EXECUTION_FAILED at [/paddle/paddle/fluid/operators/conv_cudnn_op.cu:288]
  [operator < conv2d > error]
Aborted (core dumped)

我的显卡型号是RTX2060,以及会不会是这个显卡需要CUDA10版本及以上，我本机安装的是CUDA9

**Comment by joey12300** [comment]
你下载的预测库版本是CUDA多少的

**Comment by xyry** [comment]
我后来把CUDA版本换成10.0，预测库版本也是换成了CUDA 10.0版本
但是在预测的时候还是有报错
# 报错信息如下
./demo --conf=/home/zhiyu/Desktop/projects/PaddleSeg/inference/conf/humanse
g.yaml --input_dir=/home/zhiyu/Desktop/projects/PaddleSeg/inference/images/humanseg/
WARNING: Logging before InitGoogleLogging() is written to STDERR
W1212 14:53:59.063854 28880 device_context.cc:235] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.0, Runtime API Version: 10.0
W1212 14:53:59.065698 28880 device_context.cc:243] device: 0, cuDNN Version: 7.6.
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::CUDNNConvOpKernel<float>::Compute(paddle::framework::ExecutionContext const&) const
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::CUDNNConvOpKernel<float>, paddle::operators::CUDNNConvOpKernel<double>, paddle::operators::CUDNNConvOpKernel<paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const
6   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&)
7   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
8   paddle::NativePaddlePredictor::Run(std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> > const&, std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> >*, int)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/chenzeyu01/anaconda3/envs/paddle1.3-py36/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1748, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/chenzeyu01/anaconda3/envs/paddle1.3-py36/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/chenzeyu01/anaconda3/envs/paddle1.3-py36/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 2171, in conv2d
    'fuse_relu_before_depthwise_conv': False
  File "/ssd3/chenzeyu01/PaddleSeg/pdseg/models/libs/model_libs.py", line 110, in conv
    return fluid.layers.conv2d(*args, **kargs)
  File "/ssd3/chenzeyu01/PaddleSeg/pdseg/models/backbone/xception.py", line 125, in entry_flow
    param_attr=param_attr))
  File "/ssd3/chenzeyu01/PaddleSeg/pdseg/models/backbone/xception.py", line 86, in net
    data = self.entry_flow(input)
  File "/ssd3/chenzeyu01/PaddleSeg/pdseg/models/modeling/deeplab.py", line 205, in xception
    decode_points=decode_point)
  File "/ssd3/chenzeyu01/PaddleSeg/pdseg/models/modeling/deeplab.py", line 212, in deeplabv3p
    data, decode_shortcut = xception(img)
  File "/ssd3/chenzeyu01/PaddleSeg/pdseg/models/model_builder.py", line 143, in build_model
    logits = model_func(image, class_num)
  File "./pdseg/export_model.py", line 64, in freeze
    infer_prog, startup_prog, phase=ModelPhase.PREDICT)
  File "./pdseg/export_model.py", line 95, in main
    freeze(args)
  File "./pdseg/export_model.py", line 99, in <module>
    main()

----------------------
Error Message Summary:
----------------------
PaddleCheckError: CUDNN_STATUS_EXECUTION_FAILED at [/paddle/paddle/fluid/operators/conv_cudnn_op.cu:288]
  [operator < conv2d > error]
Aborted (core dumped)

# 本机的环境信息如下
Thu Dec 12 14:58:54 CST 2019
===========version information=========
g++ (Ubuntu 4.8.5-4ubuntu2) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

--------------separator line-----------
gcc (Ubuntu 4.8.5-4ubuntu2) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

--------------separator line-----------
CUDA Version 10.0.130
--------------separator line-----------
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 6
#define CUDNN_PATCHLEVEL 4
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"
--------------separator line-----------
cmake version 3.5.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
--------------separator line-----------
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

**Comment by xyry** [comment]
有人能帮忙看下嘛，卡在这里了

**Comment by sjtubinlong** [comment]
@xyry 请问你使用的是哪一个分支的代码，develop 分支导出的模型使用之前的代码会有问题，下载一下最新的代码试试

**Comment by xyry** [comment]
我使用这个网页下的https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.3.0/deploy/cpp/docs/linux_build.md
Step 1  git clone https://github.com/PaddlePaddle/PaddleSeg.git 这个指令，好的，我试试新的

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。
