### ISSUE TITLE
标注能支持npy格式多通道吗

### ISSUE THREAD

**Issue by jackiezzq** [PaddlePaddle/PaddleSeg#1144]
unet检测表格框线时，横线竖线会有交集，导致横线或竖线有缺失，一个像素点对应多个类别（既是横线又是竖线），是否支持标签多通道训练，输出结果也是多通道？

直接改数据读取支持npy后续训练也报 维度不匹配的错
labels_dims[axis] == 1UL, but received labels_dims[axis]:2 != 1UL:1.]

**Comment by nepeplwu** [comment]
@jackiezzq 目前PaddleSeg中的pipeline暂时不支持这种任务，需要手动修改代码。请问下你的任务场景是什么呢？必须做成这种`多标签分类`的吗？

**Comment by jackiezzq** [comment]
就根据表格横竖线区分cell，然后提取cell内的信息，单分类交点处一类就会断开，后续不好处理

**Comment by nepeplwu** [comment]
@jackiezzq 那只能手动修改代码了，一共有三处地方需要修改：
1. 读取数据时，要考虑label为多通道的场景
2. 模型的预测头和辅助头都需要改成多个二分类（预测是否为竖线，以及预测是否为横线）
3. 计算Loss时，选择对应的label结合模型输出用于计算
