### ISSUE TITLE
EISeg的exe百度网盘链接失效了呀，能否重发一下

### ISSUE THREAD

**Issue by deadkany** [PaddlePaddle/PaddleSeg#1151]

**Comment by haoyuying** [comment]
您好，感谢您的反馈，我们会尽快更新，请您使用https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.2/contrib/EISeg 中介绍的其他方式进行安装，我们目前最推荐的是医用paddleseg的repo装，这里面有我们最新更新的功能
