### ISSUE TITLE
是否有mla-transformer的预训练模型？

### ISSUE THREAD

**Issue by flyinggx** [PaddlePaddle/PaddleSeg#1160]
mla-transformer的配置文件autonue.yml中未指定具体的pre-train，是要按照setr的进行配置吗？

**Comment by michaelowenliu** [comment]
@flyinggx hi, please refer to https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/contrib/AutoNUE/configs/swin_transformer_mla_base_patch4_window7_160k_autonue.yml

**Comment by peach-xiao** [comment]
> 

我找不到这个对于的模型文件  pretrained: pretrain/pretrained.pdparams在哪里，可以帮忙解决一下吗？哪里可以下载大佬知道吗？
