### ISSUE TITLE
人像分割存在显著斑块

### ISSUE THREAD

**Issue by XinZhaoFu** [PaddlePaddle/PaddleSeg#1162]
![nil_WechatIMG1708](https://user-images.githubusercontent.com/35882457/125590014-86829f45-64a5-4227-8333-a8055cdce9bd.jpeg)
人像分割存在显著斑块 请问应该调整哪里

**Comment by ZerRui** [comment]
同样的问题，期待您的解答。谢谢！

**Comment by LutaoChu** [comment]
你这块感觉是网络没训好，可否提供一下训练配置和最后的精度呢

**Comment by XinZhaoFu** [comment]
感谢您的回复，后来我直接看预测概率，确实斑块出的推理值更低一些。

**Comment by XinZhaoFu** [comment]
网络是使用的是paddleseg提供的人像分割的网络，为deeplabv3p_resnet50_os8_humanseg_512x512_100k_with_softmax。

**Comment by LutaoChu** [comment]
上面这个人像戴着帽子，头上也有花，都会有干扰，确实也是比较难识别的。你可以基于这个模型finetune，效果应该会好一些

**Comment by XinZhaoFu** [comment]
嗯嗯，确实干扰比较多。因为之前接触的分割模型往往是边界预测效果不好，当看到这批数据有很多是人物中间位置效果不好的时候，我以为是paddleseg的某些后处理带来的影响。后来查看了预测概率后才发现斑块是概率低带来的影响。我之后在微调一下，非常感谢！

**Comment by LutaoChu** [comment]
好的，不客气~
