### ISSUE TITLE
模型导出到C++的部署模型后，在C++的demo里跑出来的效果与python跑出来的差很多

### ISSUE THREAD

**Issue by TinyQi** [PaddlePaddle/PaddleSeg#1168]

**Comment by TinyQi** [comment]
seg的模型是在2.0的分支上训练的，然后C++部署的代码时paddleX的2.1版本的代码，导出模型也是在paddleseg2.0的分支上导出的，是否存在版本上的差异呢

**Comment by TinyQi** [comment]
图传不了了，我就是拿训练素材去测试，python端的预测结果基本上就是gt的样子，但是c++端预测的结果简直不能看，望指教，用的模型就是bisenet_optic_disc_512x512_1k这个

**Comment by TinyQi** [comment]
@chliang @ZeyuChen @QingshuChen @sjtubinlong

**Comment by LutaoChu** [comment]
paddlex支持的是paddleseg2.1版本，请用2.1分支导出。
主要区别在于2.1导出会自动在网络末端添加argmax算子，而2.0不会

**Comment by LutaoChu** [comment]
模型不用重新训练

**Comment by TinyQi** [comment]
> paddlex支持的是paddleseg2.1版本，请用2.1分支导出。
> 主要区别在于2.1导出会自动在网络末端添加argmax算子，而2.0不会

最新发现，其实不是版本的问题，因为我发现原先训练的分支就是2.1的，导出也是在2.1的分支下导出的，现在的主要问题就是动态图的效果明显优于静态图。至于C++推理静态图和python推静态图的模型的结果反倒是一样的（一样的很差的效果😓）

**Comment by LutaoChu** [comment]
不是版本的问题，那也就是导出的问题了。发一下导出和静态图推理的命令吧。怀疑是不是推理静态图的时候是不是网络最后少个argmax？
