### ISSUE TITLE
人像抠图容易抠出背景,边缘抖动问题

### ISSUE THREAD

**Issue by SwordBearFire** [PaddlePaddle/PaddleSeg#1173]
大佬，您好，

我自己写了一个人像抠图的代码，模型最后一层用的是sigmoid，然后用MSE和BCE去监督人像的alpha，在验证集上感觉效果还可以，但是一但接到摄像头上，特别不稳定，特别是肩膀边缘抖动十分厉害，而且当人离开摄像头范围，总是会抠出一大片背景，而且手也抠得不太好，看了百度web端的会议抠图感觉抖动啥的都挺稳，人离开摄像头视野范围也不会抠出背景。不知道大佬们是怎么做的，用的是语意义分割还是人像抠图？

希望大佬能帮我看看我这几个问题，谢谢。

SordBear
Best regards

**Comment by LutaoChu** [comment]
你好，验证集上是图片的效果，图片效果还可以不代表视频效果好。
抖动问题，一个是需要提升单帧图片的效果，第二是可以使用光流后处理做平滑。
背景问题，可以增加纯背景图片进行训练，增强对背景的识别能力。
我们用的是语义分割。你说的抠图是指matting对吧？

**Comment by SwordBearFire** [comment]
> 你好，验证集上是图片的效果，图片效果还可以不代表视频效果好。
> 抖动问题，一个是需要提升单帧图片的效果，第二是可以使用光流后处理做平滑。
> 背景问题，可以增加纯背景图片进行训练，增强对背景的识别能力。
> 我们用的是语义分割。你说的抠图是指matting对吧？

嗯，我的是matting，测试的时候经常会带出一些背景出来，特别是人不在摄像头范围内的时候，背景闪得厉害，一般纯背景数据集加多少合适点呢。还有我用的是显著性人像数据集，不知道我们的数据是不是导致模型不稳定的原因

**Comment by LutaoChu** [comment]
纯背景加1%~10%都可以。matting这块请@wuyefeilin回答

**Comment by wuyefeilin** [comment]
@SwordBearFire 因为在训练的时候的时候每张图片都有前景和背景的区分，所以实际中当只有背景的时候也会出现背景是正常的，一方面你可以让网落对纯背景的数据进行训练，也可以考虑加一个分类器试试。另外可以给我们看一下你的数据集吗，以便我们作出判断

**Comment by SwordBearFire** [comment]
> @SwordBearFire 因为在训练的时候的时候每张图片都有前景和背景的区分，所以实际中当只有背景的时候也会出现背景是正常的，一方面你可以让网落对纯背景的数据进行训练，也可以考虑加一个分类器试试。另外可以给我们看一下你的数据集吗，以便我们作出判断

分类器应该怎么弄，类似于GAN那种方式吗，我用的是爱分割的人像数据集，然后数据处理方式直接是把800x600大小的尺寸直接resize到224x224没有做其他的处理，我看一些论文里面训练的时候是先找到alpha边缘的区域，然后在边缘区域随机找一个点作为crop的中心点，crop出来的patch来作为训练的数据，不知道这样做对于我这个情况有没有帮助。谢谢大佬解答～～

**Comment by wuyefeilin** [comment]
背景的问题增加一些纯背景图片效果会变好哈，你这边的具体应用场景是什么呢？ 分类器是指在分割之前添加一个是否有人的判断哈，这是我的个人想法，你可以尝试一下

**Comment by SwordBearFire** [comment]
> 背景的问题增加一些纯背景图片效果会变好哈，你这边的具体应用场景是什么呢？ 分类器是指在分割之前添加一个是否有人的判断哈，这是我的个人想法，你可以尝试一下

我这边主要是针对edge device做人像抠图，所以对推理速度啥的也有一定的要求，然后我对比了百度会议，腾讯会议，谷歌会议，zoom这些比较主流的应用，我发想他们对背景的处理都很好，腾讯的感觉有个人脸检测器，把脸遮住就不会抠图。现在我还有个问题就是，当衣服和背景色比较相近的时候，边缘抖动得特别厉害，这种情况应该怎么才能缓解一下

**Comment by wuyefeilin** [comment]
最好的方法就是增加这一类的训练样本了

**Comment by SwordBearFire** [comment]
> 最好的方法就是增加这一类的训练样本了

谢谢大佬们的回答，受益匪浅。
