### ISSUE TITLE
同样的模型C++部署到paddleX 预测结果差异很大

### ISSUE THREAD

**Issue by sosan-nian** [PaddlePaddle/PaddleSeg#1175]
两种预测方式：
1、paddleseg2.0 动态图版本训练的模型，直接用predict.py预测
2、直接用export.py导出静态模型后部署到paddleX，使用demo里面的model_infer.exe预测
两个结果差异很大，方式一的结果更准确

**Comment by heliqi** [comment]
请问是什么模型？ 你的环境是？ 尽量提供详细点， 我这边重现对比下。

我使用PaddleSeg的Release/2.1版本导出的bisenet_cityscapes_1024x1024_160k、deeplabv3_resnet50_os8_cityscapes_1024x512_80k、hardnet_cityscapes_1024x1024_160k 模型在cuda 10.2 上，跟最新的PaddleX cpp部署进行对比，只有非常少的diff（小于 1e-5）。

我对比使用的脚本是 PaddleSeg/deploy/python/infer.py , 建议你也使用这个脚本打印对比下。 看看结果是跟哪边对上， 方便我们定位是 导出模型的问题，还是cpp部署问题

**Comment by sosan-nian** [comment]
我使用的的release/2.0，自定义模型，cuda10.0

**Comment by heliqi** [comment]
自定义模型的话，我怀疑是前后处理没对上。 
验证方法：
你试试 PaddleSeg/deploy/python/infer.py 这个脚本进行预测，看结果跟哪个一致？ 可以的话，将Seg版本升级到 2.1试试
