### ISSUE TITLE
全景分割案例中缺少yml文件

### ISSUE THREAD

**Issue by Apokar** [PaddlePaddle/PaddleSeg#1176]
你好, 我在参照[实践案例中的全景分割](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/contrib/PanopticDeepLab)时,因为数据集下载的很慢,所以准备跳过训练与评估步骤,下载你们提供的模型进行预测,下载的模型是[ResNet50_OS32](https://bj.bcebos.com/paddleseg/dygraph/pnoptic_segmentation/panoptic_deeplab_resnet50_os32_cityscapes_1025x513_bs8_90k_lr00005/model.pdparams)
但是我发现并不能找到configs/panoptic_deeplab/panoptic_deeplab_resnet50_os32_cityscapes_**1025x513_120k.yml** 这个配置文件,请问是因为跳过训练所以没有生成吗?

另外,我下载好了数据集gtFine_trainvaltest.zip (241MB)
解压后与教程中要求的data数据集文件夹结构对比,发现要求的数据集应该不止它一个,可以明确下是哪些数据集需要下载吗?

**Comment by wuyefeilin** [comment]
@Apokar https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.2/contrib/PanopticDeepLab， 请参考这边的说明，强调一下，全景分割需要在contrib/PanopticDeepLab进行执行

**Comment by Apokar** [comment]
> @Apokar [https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.2/contrib/PanopticDeepLab，](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.2/contrib/PanopticDeepLab%EF%BC%8C) 请参考这边的说明，强调一下，全景分割需要在contrib/PanopticDeepLab进行执行

![image](https://user-images.githubusercontent.com/25199579/126116110-de385882-0b56-4b60-a4d5-9ed006c8b62f.png)
这个文件根据它前面的路径我并没有在contrib/PanopticDeepLab下的configs中找到
![image](https://user-images.githubusercontent.com/25199579/126116283-2ebaf479-fbfe-4989-b7a6-44be17904075.png)

**Comment by Apokar** [comment]
@wuyefeilin 
![image](https://user-images.githubusercontent.com/25199579/126116110-de385882-0b56-4b60-a4d5-9ed006c8b62f.png)
这个文件根据它前面的路径我并没有在contrib/PanopticDeepLab下的configs中找到
![image](https://user-images.githubusercontent.com/25199579/126116283-2ebaf479-fbfe-4989-b7a6-44be17904075.png)

**Comment by wuyefeilin** [comment]
@Apokar 那应该是文档书写错误了，感谢反馈，选用第一个就行哈
