### ISSUE TITLE
The error: RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by daixiaolei623** [PaddlePaddle/PaddleSeg#1184]
Thank you for your work.
However, when i run "CUDA_VISIBLE_DEVICES=0,1 python -u -m paddle.distributed.launch train.py --config configs/sscale_auto_nue_map+city@1920.yml --use_vdl --save_dir saved_model/sscale_auto_nue_map+city@1920 --save_interval 2000 --num_workers 2 --do_eval", 
i got the error:
"RuntimeError: can't start new thread".
Could you please tell me how to solve it? thank you.

**Comment by michaelowenliu** [comment]
@daixiaolei623 hi, can you try `ulimit -u 30000`?

**Comment by daixiaolei623** [comment]
Hi
i try ulimit -u 30000, but when i run "CUDA_VISIBLE_DEVICES=0,1 python -u -m paddle.distributed.launch train.py --config configs/sscale_auto_nue_map+city@1920.yml --use_vdl --save_dir saved_model/sscale_auto_nue_map+city@1920 --save_interval 2000 --num_workers 2 --do_eval", 
it also have the error: RuntimeError: can't start new thread.
