### ISSUE TITLE
EiSeg交互式分割工具，好像没法断点续标

### ISSUE THREAD

**Issue by tspp520** [PaddlePaddle/PaddleSeg#1185]
我有一张大图，电脑不行，标注还是很费时间，所以一张图半小时只标注了一半，如果我这时候保存，退出，
发现下次打开原图，又得重新标注了，能不能，把前面标注的，重新加载进来呢？

**Comment by haoyuying** [comment]
目前还没有开放该功能，日后会增加这个功能，感谢您的建议。

**Comment by DYJNG** [comment]
附议，希望能直接加载标签mask进行经精细化修改~

**Comment by DYJNG** [comment]
附议，希望能直接加载标签mask进行经精细化修改~

**Comment by haoyuying** [comment]
您好，eiseg0.3以上版本现在支持通过对之前对polygon进行角点修改，欢迎尝试。
