### ISSUE TITLE
release2.2中deploy/lite/human_segmentation_demo模型的训练代码

### ISSUE THREAD

**Issue by zero654655902** [PaddlePaddle/PaddleSeg#1186]
请问有release2.2中deploy/lite/human_segmentation_demo人像分割模型的训练代码吗，没有找到对应的yaml文件

**Comment by haoyuying** [comment]
请参考https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/configs/_base_/ade20k.yml#L22
