### ISSUE TITLE
如何不使用验证集仅使用测试集

### ISSUE THREAD

**Issue by s0ke** [PaddlePaddle/PaddleSeg#1187]
想要在unet模型里面用训练好的模型直接上测试集，不要验证集。配置文件应该怎么写

**Comment by haoyuying** [comment]
把yaml文件里关于val_dataset的内容全部删掉。比如这种：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/configs/_base_/ade20k.yml#L22
