### ISSUE TITLE
export 时报错

### ISSUE THREAD

**Issue by songh11** [PaddlePaddle/PaddleSeg#1189]
当 gast 为0.5时，导出模型时会报错

**Comment by zero654655902** [comment]
把gast改成0.3.3版本 @songh11

**Comment by songh11** [comment]
@zero654655902 感谢您的回复，又出现了一个新问题，就是在设置input-size得到静态模型之后，转onnx模型会出现动态size的情况，请问如何解决。
![Uploading 699149c8afb64ea2b9a535f3279ea946.png…]()

**Comment by haoyuying** [comment]
图看不到
