### ISSUE TITLE
数据transform疑问

### ISSUE THREAD

**Issue by ZiQiangXie** [PaddlePaddle/PaddleSeg#1190]
transforms:
    - type: Resize
      target_size: [1920, 1080]
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0
    - type: RandomPaddingCrop
      crop_size: [1920, 1080]
    - type: RandomHorizontalFlip
    - type: RandomDistort
  
对于数据处理的过程，是按照transform里面设置的顺序进行处理吗？还是有默认的优先级顺序？

**Comment by haoyuying** [comment]
是按照你输入的顺序https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/paddleseg/transforms/transforms.py#L64

**Comment by ZiQiangXie** [comment]
好的，感谢！ @haoyuying
