### ISSUE TITLE
human_segmentation_demo跟换模型后报错

### ISSUE THREAD

**Issue by zero654655902** [PaddlePaddle/PaddleSeg#1191]
release/2.2 human_segmentation_demo更换模型后报错：
![image](https://user-images.githubusercontent.com/24507319/126603433-af60c871-8a4e-4087-ae10-0c172e333e88.png)

1、按照
https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.1/contrib/HumanSeg
的步骤下载数据，训练模型
导出模型
export CUDA_VISIBLE_DEVICES=0 # 设置1张可用的卡
python ../../export.py \
--config configs/fcn_hrnetw18_small_v1_humanseg_192x192_mini_supervisely.yml \
--model_path saved_model/fcn_hrnetw18_small_v1_humanseg_192x192_mini_supervisely/best_model/model.pdparams \
--save_dir export_model/fcn_hrnetw18_small_v1_humanseg_192x192_mini_supervisely_with_softmax \
--without_argmax --with_softmax

得到yaml、pdiparams、pdiparams.info、pdmodel文件
无报错

2、在https://paddle-lite.readthedocs.io/zh/release-v2.8/quick_start/release_lib.html#opt
下载opt工具，linux下v2.8版本 opt_linux执行文件
使用
./opt_linux \
    --model_file=./fcn_hrnetw18_small_v1_humanseg_192x192_mini_supervisely_with_softmax/model.pdmodel \
	--param_file=./fcn_hrnetw18_small_v1_humanseg_192x192_mini_supervisely_with_softmax/model.pdiparams \
    --optimize_out_type=naive_buffer \
    --optimize_out=./hrnet_w18_small \
    --valid_targets=arm 

nb文件生成成功  ./hrnet_w18_small.nb successfully
无报错

3、将hrnet_w18_small.nb文件替换human_segmentation_demo\app\src\main\assets\image_segmentation\models\for_cpu\中的hrnet_w18_small.nb文件

4、release/2.2 human_segmentation_demo\app\build.gradle中第110行hrnet_w18_small.nb的文件名字写错，需要纠正，不然那每次都会重新下载hrnet_w18_small.nb模型，覆盖for_cpu\hrnet_w18_small.nb文件

5、重新build，build成功
6、run app
   app闪退， 报错
E/AndroidRuntime: FATAL EXCEPTION: Predictor Worker
    Process: com.baidu.paddle.lite.demo.human_segmentation, PID: 11154
    java.lang.ArrayIndexOutOfBoundsException: length=2; index=1065352727
        at com.baidu.paddle.lite.demo.segmentation.visual.Visualize.draw(Visualize.java:31)
        at com.baidu.paddle.lite.demo.segmentation.Predictor.runModel(Predictor.java:224)
        at com.baidu.paddle.lite.demo.segmentation.MainActivity.onRunModel(MainActivity.java:149)
        at com.baidu.paddle.lite.demo.segmentation.MainActivity$2.handleMessage(MainActivity.java:122)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.os.HandlerThread.run(HandlerThread.java:67)
I/Process: Sending signal. PID: 11154 SIG: 9

**Comment by LutaoChu** [comment]
你好，导出模型这块不要加--without_argmax --with_softmax试试

python ../../export.py
--config configs/fcn_hrnetw18_small_v1_humanseg_192x192_mini_supervisely.yml
--model_path saved_model/fcn_hrnetw18_small_v1_humanseg_192x192_mini_supervisely/best_model/model.pdparams
--save_dir export_model/fcn_hrnetw18_small_v1_humanseg_192x192_mini_supervisely_with_softmax

**Comment by zero654655902** [comment]
@LutaoChu 谢谢，这样导出的模型转换后，替换原来的nb不报错了，但是人像的分割效果差了很多，直接使用预训练模型转换后，效果可以，应该是模型微调时没有训练好的原因吧

**Comment by LutaoChu** [comment]
不客气。你是不是在mini_spervisely上finetune了，那个数据集数据量很小，只是用来做demo的。要提高分割效果需要符合你任务要求的数据集，数据量也不能太小

**Comment by zero654655902** [comment]
@LutaoChu 嗯嗯
