### ISSUE TITLE
模型裁剪未完成

### ISSUE THREAD

**Issue by sosan-nian** [PaddlePaddle/PaddleSeg#1200]
基于paddle2.1运行bisenet_optic_disc_512x512_1k.yml训练的模型，进行模型裁剪未完成
![图片](https://user-images.githubusercontent.com/82444943/126736245-3895a659-543f-414b-a86e-292c38443736.png)

**Comment by nepeplwu** [comment]
@sosan-nian 从截图中未看到报错信息，是否方便给下？未完成是指异常退出了吗？

**Comment by sosan-nian** [comment]
@nepeplwu 就是这样卡在这里，然后就自动退出去了，没有报错信息，我测试了不同的网络都是这样卡住了。

**Comment by nepeplwu** [comment]
请问你的paddle版本是？

**Comment by sosan-nian** [comment]
> 
> 
> 请问你的paddle版本是？
paddle2.1，我conda重新做了一遍环境，现在可以运行了
不过我直接用python/infer预测
![图片](https://user-images.githubusercontent.com/82444943/126761856-0c6083b0-8ede-473d-9341-d573a8417d9c.png)，是需要输入int8吗？

**Comment by nepeplwu** [comment]
不需要，你的输入图片是否方便给下？我们看下

**Comment by sosan-nian** [comment]
> 
> 
> 不需要，你的输入图片是否方便给下？我们看下

用的你们的demo，optic_disc_seg的数据集（视盘分割），裁剪和量化后模型预测都一样的错误

**Comment by nepeplwu** [comment]
@sosan-nian ，预测的时候加上`--with_argmax`试试看
