### ISSUE TITLE
EIseg qt plugins bug ?

### ISSUE THREAD

**Issue by chenghuaWang** [PaddlePaddle/PaddleSeg#1203]
```shell
os -> Ubuntu 20.04.1 LTS
paddlepaddle -> 2.1.1 gpu cuda10.2
```
**eiseg运行时出现下述报错:**
```shell
(eiseg) root@liu-HP-EliteDesk-880-G5-TWR:/home/liu# eiseg
QObject::moveToThread: Current thread (0x55e4a61ceee0) is not the object's thread (0x55e4a8b62720).
Cannot move to target thread (0x55e4a61ceee0)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/root/anaconda3/envs/eiseg/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1627018425 (unix time) try "date -d @1627018425" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x7900a) received by PID 495626 (TID 0x7f7af6e59180) from PID 495626 ***]

已放弃 (核心已转储)
```
**使用了pyside2解决了这个问题**
```python
dirname = os.path.dirname(PySide2.__file__)
plugin_path = os.path.join(dirname, 'plugins', 'platforms')
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = plugin_path
```

**Comment by linhandev** [comment]
收到，我们已经发现cv2和pyqt在一些linux环境下有xcb环境变量的冲突，下个版本已经加入了对于这个问题的解决，欢迎大佬在我们升级后继续关注一下这个点，也十分感谢大佬提出的方案！

**Comment by tongchangD** [comment]
您好,请问这几行代码加在哪里,可以解决这个问题

**Comment by tongchangD** [comment]
> ```python
> dirname = os.path.dirname(PySide2.__file__)
> plugin_path = os.path.join(dirname, 'plugins', 'platforms')
> os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = plugin_path
> ```

您好,请问这几行代码加在哪里,可以解决这个问题

**Comment by chenghuaWang** [comment]
@tongchangD 你好。这个项目我好久没看了，具体的有点忘了😥，因为这个bug是由cv和pyqt冲突产生的，你可以尝试在调用了pyqt的文件里面修改。

令，此法不一定能完全解决问题，我的同事尝试此法仍有bug。

**Comment by tongchangD** [comment]
@chenghuaWang  谢谢您的回复,我查到似乎可能是pyQT5环境的问题,有个.so文件链接库存在问题
libqxcb.so: (libxcb-util.so.1: cannot open shared object file: No such file or directory)"
尝试在卸载所有qt包,然后从头装环境试试
感觉在linux上环境是个大问题,然而官方也没有相应的环境介绍,哎,难受

**Comment by Vicellken** [comment]
> @chenghuaWang 谢谢您的回复,我查到似乎可能是pyQT5环境的问题,有个.so文件链接库存在问题 libqxcb.so: (libxcb-util.so.1: cannot open shared object file: No such file or directory)" 尝试在卸载所有qt包,然后从头装环境试试 感觉在linux上环境是个大问题,然而官方也没有相应的环境介绍,哎,难受

我在Linux环境中也遇到同样问题，但是没有配置环境的权限
采用的方法：
`pip uninstall PyQt5`
`conda install pyqt`

**Comment by tongchangD** [comment]
> > @chenghuaWang 谢谢您的回复,我查到似乎可能是pyQT5环境的问题,有个.so文件链接库存在问题 libqxcb.so: (libxcb-util.so.1: cannot open shared object file: No such file or directory)" 尝试在卸载所有qt包,然后从头装环境试试 感觉在linux上环境是个大问题,然而官方也没有相应的环境介绍,哎,难受
> 
>@Vicellken 我在Linux环境中也遇到同样问题，但是没有配置环境的权限 采用的方法： `pip uninstall PyQt5` `conda install pyqt`

linux 环境 你可以在这这个[issues](https://github.com/PaddlePaddle/PaddleSeg/issues/1363)找到答案

**Comment by linhandev** [comment]
@Vicellken @tongchangD 
大佬们好，我们在目前的版本[init](https://github.com/PaddleCV-SIG/EISeg/blob/b5cc067602d4b5633eca8f01a240d2d5784da581/eiseg/__init__.py#L18)文件中加入了对这个冲突的检测。可以尝试一下在加载cv2之后，qt之前加入
```shell
for k, v in os.environ.items():
    if k.startswith("QT_") and "cv2" in v:
        del os.environ[k]
```
我们项目已经很久没收到这个xcb问题的反馈了，应该是好用的。

希望有帮助
