### ISSUE TITLE
RuntimeError: (NotFound) Operator reduce_mean does not have kernel for data_type[int64_t]:data_layout[ANY_LAYOUT]:place[CUDAPlace(0)]:library_type[PLAIN].   [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at /paddle/paddle/fluid/imperative/prepared_operator.cc:135)   [operator < reduce_mean > error]

### ISSUE THREAD

**Issue by 836469383** [PaddlePaddle/PaddleSeg#1204]
- ubuntu 18.04 
- CUDA11.1
- python=3.7
- **run code** :`CUDA_VISIBLE_DEVICES=0,1 python -m paddle.distributed.launch train.py  --config configs/panoptic_deeplab/panoptic_deeplab_resnet50_os32_cityscapes_1025x513_bs8_90k_lr00005.yml --do_eval        --use_vdl --save_interval 5000 --save_dir output`
- **report error** :
![image](https://user-images.githubusercontent.com/32611043/126763248-859168ad-4ec9-4bf4-8739-43129098f6ca.png)
感谢大佬的解答

**Comment by nepeplwu** [comment]
@836469383 感谢反馈，该问题已经在最新代码中修复，请更新到最新分支使用 - release/2.2

**Comment by DejaYang** [comment]
使用release/2.2，依旧遇到上述问题

> 
> 
> @836469383 感谢反馈，该问题已经在最新代码中修复，请更新到最新分支使用 - release/2.2

使用release/2.2，依旧遇到上述问题
