### ISSUE TITLE
paddleseg2.0可视化问题

### ISSUE THREAD

**Issue by insoliang** [PaddlePaddle/PaddleSeg#1205]
您好我想请问以下paddleseg2.0取消了--vdl_log_dir这个参数，那么怎么样才能实时可视化呢，现在我只能可视化loss曲线那几个图，不能看到网络结构、样本数据等等

**Comment by nepeplwu** [comment]
@insoliang 感谢反馈，在paddleseg 2.0之后，统一通过`--save_dir`来指定模型保存路径以及vdl的日志保存路径，详细的使用文档可以参考[使用教程](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/docs/quick_start.md)。目前我们只保存了训练曲线的变化数据，后续会考虑加入网络结构，样本数据记录等功能，

**Comment by insoliang** [comment]
原来如此，感谢回复呀！
