### ISSUE TITLE
val_dataset crop error

### ISSUE THREAD

**Issue by chenjw1009** [PaddlePaddle/PaddleSeg#1207]
val_dataset:
mode: val
type: Dataset
dataset_root: data/woven_bag
val_path: data/woven_bag/val_list.txt
num_classes: 2
transforms:
- type: RandomPaddingCrop
crop_size: [2048, 1024]
- type: Normalize

File "d:\PaddleSeg\paddleseg\utils\metrics.py", line 40, in calculate_area
raise ValueError('Shape of pred and label should be equal, ' ValueError: Shape of predandlabel should be equal, but there are [1, 1024, 2048] and [1, 3024, 4032].

how to  modify the config file?

**Comment by haoyuying** [comment]
您好，在val的时候是不能进行crop的，需要把RandomPaddingCrop去掉。
