### ISSUE TITLE
关于文档没有显示内容

### ISSUE THREAD

**Issue by lxk767363331** [PaddlePaddle/PaddleSeg#1209]
![image](https://user-images.githubusercontent.com/38516795/127189286-90ca8f6d-51f2-4a63-bcb6-788463e1661c.png)
请问图中说的如下结构是什么结构，没有看到具体的结构图

**Comment by haoyuying** [comment]
您好，请将具体的链接发送给我们，帮助我们更好的定位问题。

**Comment by lxk767363331** [comment]
> 您好，请将具体的链接发送给我们，帮助我们更好的定位问题。

https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/docs/quick_start.md

**Comment by haoyuying** [comment]
收到，我们会尽快更新，感谢您的帮助。
