### ISSUE TITLE
danet

### ISSUE THREAD

**Issue by 928776539** [PaddlePaddle/PaddleSeg#1211]
请问一下,在PaddleSeg/paddleseg/models/danet.py中danet中的
class DANet(nn.Layer):
    """
    The DANet implementation based on PaddlePaddle.

    The original article refers to
    Fu, jun, et al. "Dual Attention Network for Scene Segmentation"
    (https://arxiv.org/pdf/1809.02983.pdf)

    Args:
        num_classes (int): The unique number of target classes.
        backbone (Paddle.nn.Layer): A backbone network.
        backbone_indices (tuple): The values in the tuple indicate the indices of
            output of backbone.
        align_corners (bool): An argument of F.interpolate. It should be set to False when the output size of feature
            is even, e.g. 1024x512, otherwise it is True, e.g. 769x769.  Default: False.
        pretrained (str, optional): The path or url of pretrained model. Default: None.
    """
参数backbone_indices:是什么意思,没有太看懂.希望解答一下.

**Comment by haoyuying** [comment]
就是接到head的feature从第几个stage里面抽出来的意思。比如[2,3]就是从resnet的倒数第一个和倒数第二个stage中提取feature用于接下来的计算。

**Comment by 928776539** [comment]
谢谢
