### ISSUE TITLE
训练一半中断

### ISSUE THREAD

**Issue by 836469383** [PaddlePaddle/PaddleSeg#1216]
- ubuntu 18.04   
- CUDA11.1
- python=3.7
- run code `CUDA_VISIBLE_DEVICES=0,1 python -m paddle.distributed.launch train.py --config configs/panoptic_deeplab/panoptic_deeplab_resnet50_os32_cityscapes_1025x513_bs8_90k_lr00005.yml --do_eval --use_vdl  --save_interval 5000  --save_dir output`
- report error:
![image](https://user-images.githubusercontent.com/32611043/127737544-f2d0b2ba-192d-4c3c-9110-7bbeb7c1f8f4.png)

- workerlog.0:
![image](https://user-images.githubusercontent.com/32611043/127737578-7cf6e766-ab85-4d55-ac61-27dc94ec9289.png)
Any help will be grateful!   QAQ

**Comment by LutaoChu** [comment]
你好，报错信息看有各种可能，例如数据集有脏数据。有没有python stack的报错呢？

**Comment by 836469383** [comment]
您好，感谢您的回复。
这个应该是分布式训练的问题，使用单卡的话训练是没有问题的。 报错的就贴图这些了。

**Comment by LutaoChu** [comment]
出错的是rank 1，可以打开workerlog.1看一看

**Comment by 836469383** [comment]
![image](https://user-images.githubusercontent.com/32611043/127947884-76aedbcc-4611-40a2-a451-246e5877c914.png)
我猜是nccl2 安装有问题 打扰啦哈，我自己再看看吧
