### ISSUE TITLE
changed

### ISSUE THREAD

**Issue by Squirrel1996** [PaddlePaddle/PaddleSeg#122]

**Comment by LutaoChu** [comment]
你好，你说的是标注图非png是吗？你的是什么格式呢？
PaddleSeg的源代码都是开源的，读取图片的代码请见pdseg/reader.py

**Comment by Squirrel1996** [comment]
dat



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: LutaoChu <notifications@github.com&gt;
发送时间: 2019年12月16日 10:42
收件人: PaddlePaddle/PaddleSeg <PaddleSeg@noreply.github.com&gt;
抄送: Squirrel1996 <1151524322@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[PaddlePaddle/PaddleSeg] 您好，用非png格式的比如像遥感数据，通过改数据和模型接口来跑模型是可行的吗？ (#122)




你好，你说的是标注图非png是吗？你的是什么格式呢？
 PaddleSeg的源代码都是开源的，读取图片的代码请见pdseg/reader.py

**Comment by linhandev** [comment]
感觉可以添加一个对于npy格式的读取，在做CT的分割，用框架做网络和训练很方便，但是hu值范围比较大255效果不好

**Comment by ZeyuChen** [comment]
@davidlinhl 可否提供一下更多关于npy介绍或者数据样本，我们可以提供相应的技术支持共同完善PaddleSeg在医疗领域的分割。

**Comment by linhandev** [comment]
@ZeyuChen 之前都是tensorflow最近才转到paddle，熟悉一段时间总结一下

**Comment by HOLLIZHAO** [comment]
遥感数据影像识别分割后最终也要形成矢量图吧，要不实际意义也不大。

**Comment by linhandev** [comment]
@ZeyuChen 最近在肝脏上用了一下，感觉主要的问题就是pdseg只能做2d的图像处理，医学影像都是3d的。如果把ct都导成2d的图像分割效果也不错，但是想利用3d的信息paddleseg是肯定做不了。

**Comment by HOLLIZHAO** [comment]
> @ZeyuChen 最近在肝脏上用了一下，感觉主要的问题就是pdseg只能做2d的图像处理，医学影像都是3d的。如果把ct都导成2d的图像分割效果也不错，但是想利用3d的信息paddleseg是肯定做不了。

飞桨28日资讯：[【抗击肺炎】基于CT影像的肺炎筛查及病情预评估系统](https://www.paddlepaddle.org.cn/hub/scene/pneumonia)，这个是基于PaddleSeg的吧。

**Comment by linhandev** [comment]
报道里面写的是，但是就算是基于pdseg的也是改动了不少，如果是上的3d unet网络结构也需要改。

**Comment by LielinJiang** [comment]
> 报道里面写的是，但是就算是基于pdseg的也是改动了不少，如果是上的3d unet网络结构也需要改。

是的，目前还没有上3d的分割网络

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。
