### ISSUE TITLE
关于PaddleSeg-Matting和AutoNUE开源问题

### ISSUE THREAD

**Issue by Zenobia7** [PaddlePaddle/PaddleSeg#1221]
您好，想问一下PaddleSeg-Matting是否开源了，我在PaddleSeg项目下没有找到相关的代码，然后想问一下AutoNUE模型文件什么时候开源啊？谢谢了

**Comment by michaelowenliu** [comment]
@15122901359 Hi, thanks for your attention. PaddleSeg-Matting will be released soon. The AutoNUE solution has been released already.
