### ISSUE TITLE
关于版本不同造成miou产生较大差别的问题

### ISSUE THREAD

**Issue by XingYZhu** [PaddlePaddle/PaddleSeg#1222]
我在使用paddleseg2.2的一台电脑上训练了一个unet模型，经过验证后两个类别的iou分别是0.8366和0.5553，但是我把在paddleseg2.2版本上训练好的unet模型直接拷贝到另一台paddleseg2.1的机器上使用val.py在相同的数据集上验证时发现iou分别是0.7148和0.4573。可以发现miou大约低了百分之10左右
我还尝试在另一台paddleseg2.1的机器上用相同的参数和训练集训练unet时发现iou也会比paddleseg2.2的要低很多，想问一下这个是由什么原因导致的呢？
希望可以收到您的回复，感谢！

**Comment by michaelowenliu** [comment]
@XYCHUH Hi, did you try the evaluation using paddleseg2.2?

**Comment by XingYZhu** [comment]
>@XYCHUH Hi, did you try the evaluation using paddleseg2.2?

@ michaelowenliu yes, i did it's far higher than paddleseg2.1

**Comment by wuyefeilin** [comment]
我这边利用相同的模型参数在2.2和2.1上得到的测试结果试相同的，请问你修改过代码吗
