### ISSUE TITLE
export 导出报错

### ISSUE THREAD

**Issue by Jinya90** [PaddlePaddle/PaddleSeg#1226]
python export.py \
       --config configs/quick_start/bisenet_optic_disc_512x512_1k.yml \
       --model_path output/iter_1000/model.pdparams

报错提示：AttributeError: 'Assign' object has no attribute 'type_comment'
用的版本是2.1的

**Comment by wuyefeilin** [comment]
更新到2.2试一下哈

**Comment by Jinya90** [comment]
更新到2.2之后也会报一样的错误，有没有可能和python的版本有关，我这边用的python3.7

**Comment by wuyefeilin** [comment]
我这边用python3.7没有复现你的错误，请问你用的windows系统吗？ 另外详细的报错信息给一下哈

**Comment by Jinya90** [comment]
目前解决了，是gast版本问题，改为0.3.3就可以了
