### ISSUE TITLE
EISeg 可以支持自定义的模型吗

### ISSUE THREAD

**Issue by fanweiya** [PaddlePaddle/PaddleSeg#1231]
我做的生物场景，使用通用场景的模型效果不是很好，EISeg 可以支持用飞桨训练的自定义模型吗？

**Comment by nepeplwu** [comment]
@fanweiya 目前只支持固定结构的模型，后续会支持选择自定义模型。

**Comment by nepeplwu** [comment]
请问下你的场景是什么场景呢？你训练的是什么模型？

**Comment by fanweiya** [comment]
> 请问下你的场景是什么场景呢？你训练的是什么模型？

细胞分割，UNet

**Comment by nepeplwu** [comment]
你训练的不是交互式分割模型吧？而是普通的语义分割模型？

**Comment by fanweiya** [comment]
> 你训练的不是交互式分割模型吧？而是普通的语义分割模型？

是的

**Comment by nepeplwu** [comment]
那是不行的，哪怕EISeg支持自定义模型了也不行，必须是交互式分割模型

**Comment by fanweiya** [comment]
> 那是不行的，哪怕EISeg支持自定义模型了也不行，必须是交互式分割模型

飞桨有可以训练的交互式分割模型吗？

**Comment by nepeplwu** [comment]
有的，但是目前暂时还没开源，代码还在整理中

**Comment by fanweiya** [comment]
> 有的，但是目前暂时还没开源，代码还在整理中

好的，期待尽快开源

**Comment by mengmeng716** [comment]
期待开源EISeg自训练模型
