### ISSUE TITLE
请问模型裁减之后的sen.pickle文件如何打开

### ISSUE THREAD

**Issue by terrancraft** [PaddlePaddle/PaddleSeg#1235]

**Comment by nepeplwu** [comment]
@terrancraft `sen.pickle`文件主要是用于保存敏感度计算的一些结果，裁剪完成后，该文件并无作用，无需关注

**Comment by terrancraft** [comment]
那请问我如何根据模型每层的敏感度分析结果，画一个敏感性分析的折线图

**Comment by wanghaoshuang** [comment]
可以使用这个接口加载敏感度信息：
https://paddleslim.readthedocs.io/zh_CN/latest/api_cn/static/prune/prune_api.html#load-sensitivities

**Comment by terrancraft** [comment]
3Q
