### ISSUE TITLE
【论文复现】paddleseg内置citiscapes数据集标签问题。已经star了，无法加群。

### ISSUE THREAD

**Issue by stuartchen1949** [PaddlePaddle/PaddleSeg#1248]
paddleseg内置citiscapes数据集标签问题
我现在需要使用camvid11类数据集测试，想要使用内置citiscapes训练，可是内置citiscapes类别是19，
这19个类别分别是什么呢？
我这个需求怎么操作呢？
谢谢！

**Comment by nepeplwu** [comment]
@stuartchen1949 不太理解你的问题，为什么会想要在cityscapes上测试，在camvid11上测试呢？
