### ISSUE TITLE
EISeg加载模型参数时宕机

### ISSUE THREAD

**Issue by oruchimaru420** [PaddlePaddle/PaddleSeg#1249]
我用conda创建虚拟环境，然后通过pip安装的EISeg
当启动EIseg，在加载模型参数这一步出现了问题，每次都到这就会宕机。
cmd显示信息如下：
Please NOTE: device: 0, GPU Compute Capability: 3.6, Deriver API Version: 11.1 Runtime API Version: 10.2
Note: [Recommond] copy cudnn into CUDA installation directory.
You should do this according to your CUDA installation directory and CUDNN version,
可是我照着做了以后，还是发生这个问题，请问该如何解决？

**Comment by haoyuying** [comment]
看起来是cudnn和cuda版本不匹配的原因呀，具体的cuda，cudnn, paddlepaddle-gpu的版本是什么呢，能否正常使用paddle？

**Comment by oruchimaru420** [comment]
> 看起来是cudnn和cuda版本不匹配的原因呀，具体的cuda，cudnn, paddlepaddle-gpu的版本是什么呢，能否正常使用paddle？

cuda==11.1 cudnn==11.1 paddlepaddle-gpu==2.1.1
目前只试了EISeg paddle还没有试

**Comment by haoyuying** [comment]
可以试下paddle是否能正常使用，如果能，请给出完整的报错信息，方便我们排查原因。cudnn版本查错了吗，用这个查下cat /usr/include/cudnn.h | grep CUDNN_MAJOR -A 2

**Comment by oruchimaru420** [comment]
> 可以试下paddle是否能正常使用，如果能，请给出完整的报错信息，方便我们排查原因。cudnn版本查错了吗，用这个查下cat /usr/include/cudnn.h | grep CUDNN_MAJOR -A 2

感谢答复，通过将paddlepaddle的版本修改为2.1.2.post110，问题已解决
