### ISSUE TITLE
u2net加载config文件之后会显示gnu错误

### ISSUE THREAD

**Issue by terrancraft** [PaddlePaddle/PaddleSeg#1250]
![Screenshot from 2021-08-16 11-29-32](https://user-images.githubusercontent.com/51820927/129510516-d3411452-e095-4566-b16f-44317b948ab2.png)
如图，我用其他模型如faster-scnn和ocrnet去训练都没有这个错误。

唯独u2net不行，config文件解析应该是成功了，因为可以打印model和trainset。
找不到错误原因，
望解答 谢谢～

**Comment by nepeplwu** [comment]
@terrancraft 麻烦贴下训练命令

**Comment by terrancraft** [comment]
> @terrancraft 麻烦贴下训练命令

python -m paddle.distributed.launch train.py --config configs/u2netp_tiepi_480x300_160k.yml --do_eval --use_vdl --save_interval 500 --save_dir output
