### ISSUE TITLE
iou计算的问题

### ISSUE THREAD

**Issue by lfxx** [PaddlePaddle/PaddleSeg#1252]
https://github.com/PaddlePaddle/PaddleSeg/blob/9dca3f3f489b5fe4cb83afcbaf09f08c331716a6/paddleseg/utils/metrics.py#L93-L96
您好，有两个问题：
1.这里的 if union[i] == 0:分支什么时候会走呢，理论上来说不会出现并集是0的时候吧，就算没分割出这个类别，这个类别的GT面积也不会是0，这种情况交集=0不就覆盖了?
2.想知道ignore_index这个参数是为什么场景准备的呢

**Comment by wuyefeilin** [comment]
1. 这个是有可能出现的哈，比如你计算一张图片的miou，可能只有其中几个类别。
2. ignorx_index是用于表明忽略区域的，不参与计算。 以cityscapes数据集为例，其图象底部固定为车头区域，没有训练意义，通过把它标注为ignore_index进行忽略。

**Comment by lfxx** [comment]
> 1. 这个是有可能出现的哈，比如你计算一张图片的miou，可能只有其中几个类别。
> 2. ignorx_index是用于表明忽略区域的，不参与计算。 以cityscapes数据集为例，其图象底部固定为车头区域，没有训练意义，通过把它标注为ignore_index进行忽略。

1.您好，还是有些迷惑，union的计算公式是这样的：
```
union = pred_area + label_area - intersect_area
```
如果说某个类完全没分割出来，它的pred_area是0，interact_area是0，但是label_area不是0啊，union不可能会存在0的情况。这样情况的直接用intersect_area不就可以覆盖了吗

**Comment by wuyefeilin** [comment]
@lfxx 对于整个数据集来说一般所有label都存在像素数，但是如果你只想求其中某一张图片的iou，这时候有些类别的label_area就会为0了
