### ISSUE TITLE
The inference speed of SFNet

### ISSUE THREAD

**Issue by ydhongHIT** [PaddlePaddle/PaddleSeg#1261]
Why is the inference speed much faster than the original paper? In the paper, the authors use R18 and FPS is 26 with tensorRT. You use R50 while the FPS is about 35. Do you use the tensorRT?

**Comment by haoyuying** [comment]
paddle自身有一些加速算法，如果训练的结果中含有的0比较多，会提升预测的速度。请问R50时FPS35在什么环境下测出来的，怎么测试的呢？

**Comment by ydhongHIT** [comment]
> paddle自身有一些加速算法，如果训练的结果中含有的0比较多，会提升预测的速度。请问R50时FPS35在什么环境下测出来的，怎么测试的呢？

你们图里画的啊，有一个FPS与精度的图。

**Comment by ydhongHIT** [comment]
> paddle自身有一些加速算法，如果训练的结果中含有的0比较多，会提升预测的速度。请问R50时FPS35在什么环境下测出来的，怎么测试的呢？

你们图里画的啊，有一个FPS与精度的图。

**Comment by haoyuying** [comment]
您好，我们图上测试的是r18做backbone的结果，文档有点问题，已经快马加鞭的改了。我们在计算fps时候使用了paddle.inference,将动态图转化成了静态图模型，能有效的提升计算效率，欢迎使用https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/deploy/python/infer.py进行体验。
