### ISSUE TITLE
报错：The specified component was not found xxx

### ISSUE THREAD

**Issue by yang20085936** [PaddlePaddle/PaddleSeg#1265]
1、完全按照示例中optic_disc_seg组织的数据，原始图像为jpg，标签图像为png，还有每行一个样本的train_list,val_list和test_list。对应修改之后运行，报错如上。
2、按照示例：“https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.1/configs”中，只有dataset_root,没有train_path 和val_path,这样子的yml可以训练么？框架怎样去找到数据？
3、api应用案例中，“https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/docs/api_example.md”，构建训练集和验证集的dataset_root都是只到了'data/optic_disc_seg'，也没有train_path 和val_path？可否提供更多的api应用案例？

**Comment by LutaoChu** [comment]
1 说明找不到某些模块，可以把具体报错信息贴出来
2 可以的，有些数据集的train_path,val_path在dataset类中已经定义好了，比如指定在dataset_root下寻找train.txt
3 看下源码就很清楚了 https://github.com/PaddlePaddle/PaddleSeg/blob/3de62e37741deb053c5885dd60ddf99f130375e7/paddleseg/datasets/optic_disc_seg.py#L78
除了dataset，你还想知道哪些api应用案例呢

**Comment by lixia2333** [comment]
RuntimeError:The verification dataset is not specified in the configuration file.是什么问题

**Comment by lixia2333** [comment]
mapping values are not allowed here

**Comment by lixia2333** [comment]
The specified component was not found Dataset.
