### ISSUE TITLE
配置问题，模型加载完，就卡住不动了。

### ISSUE THREAD

**Issue by nba20416** [PaddlePaddle/PaddleSeg#1266]
尝试过的方法，重新安装paddlepaddle，重新安装paddleseg，用print大法也没找到。
`又找了个简单的模型，也是卡在开头的读取中。我现在竟然找不到原因在哪里了。`
![F R141 ~L9%CBOYC R2C_V9](https://user-images.githubusercontent.com/60060273/130312943-5aafc581-3f3c-4d64-b6c7-a3bb7781a837.jpg)

**Comment by juncaipeng** [comment]
请问是否按照[文档](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/docs/install.md)中的方法安装，测试最终安装成功？
比如这个[示例](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/docs/quick_start_cn.md)是否可以跑通？

训练过程是从train.py文件进入，建议可以多处使用print大法，一步步调试下~~~

**Comment by nba20416** [comment]
> 比如是否按照[文档](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/docs/install.md)中的方法安装，测试最终安装成功？
> 比如这个[例子](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/docs/quick_start_cn.md)是否可以跑通？
> 
> 训练过程是从train.py文件进入，建议可以多处使用打印大法，一步步调试下~~~

应该是环境的问题，我换了一个小paddle模型，多处打印大法，应该是初始化数据没有加载导致的。但是确定不了是哪块出的问题。

**Comment by juncaipeng** [comment]
是训练数据读取部分吗？  这个数据数据可以先提前下载，如果不提前下载，需要在线下载，有一个进度条。

![image](https://user-images.githubusercontent.com/52520497/130399213-09c45630-5436-4574-b2d4-d6e85322996b.png)

**Comment by nba20416** [comment]
> 是训练数据读取部分吗？这个数据数据可以提前下载，如果不提前下载，需要在线下载，有一个提示条。
> 
> ![形象](https://user-images.githubusercontent.com/52520497/130399213-09c45630-5436-4574-b2d4-d6e85322996b.png)

不是的，数据集我从本地上传好了的。
正常开始训练是这样的，
![1629701133(1)](https://user-images.githubusercontent.com/60060273/130402755-52d8ac19-d1d4-451a-b424-5bcbd87677dd.jpg)
但是我的服务器上面就不走，只是加载好模型的基础数据后，就卡住了。见下图:
![F R141 ~L9%CBOYC R2C_V9](https://user-images.githubusercontent.com/60060273/130402862-e3ee6373-78df-489a-b086-c35c421b1c7e.jpg)
我把paddlepaddle和paddleseg都更新了一遍，代码也重新下载上传了一次。还是出现这个问题。不知道是卡在哪里了。关键是没有提示，我能猜到是环境的问题，但是找不到关键点在哪里。。。。。

**Comment by KazusaW1999** [comment]
可以尝试检查一下这台机器的GPU利用率 @nba20416

**Comment by YuJie-Tian** [comment]
@nba20416 你好，请问这个问题你解决了吗？
我用官方提供的案例图像进行训练是ok的，但是通过EISeg自己标注的图像进行训练就出现和你一样的情况了，程序一直不动，GPU利用率也很低，一直没找到原因

**Comment by YuJie-Tian** [comment]
> @nba20416 你好，请问这个问题你解决了吗？
> 我用官方提供的案例图像进行训练是ok的，但是通过EISeg自己标注的图像进行训练就出现和你一样的情况了，程序一直不动，GPU利用率也很低，一直没找到原因

解决问题了，但还不知道是什么原因。
解决办法：用EISeg保存的灰度图作为标注图，而非伪彩色图像即可
