### ISSUE TITLE
数据集分割脚本split_dataset_list.py

### ISSUE THREAD

**Issue by ximitiejiang** [PaddlePaddle/PaddleSeg#1271]
在看https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/docs/data/marker/marker_cn.md的介绍时，提到对数据集做分割有个脚本：
```
python tools/split_dataset_list.py <dataset_root> <images_dir_name> <labels_dir_name> ${FLAGS}
```
但在tools文件夹里边没找到这个脚本，请问下哪里可以找到这个文件？

**Comment by juncaipeng** [comment]
这个文件在develop分支上，不在release/2.2分支上

https://github.com/PaddlePaddle/PaddleSeg/blob/develop/tools/split_dataset_list.py

**Comment by ximitiejiang** [comment]
额，好吧。刚从paddleX上面找了个类似的改了改用。
谢谢啦！
