### ISSUE TITLE
关于伪彩图和背景像素

### ISSUE THREAD

**Issue by ximitiejiang** [PaddlePaddle/PaddleSeg#1275]
请教个关于背景颜色和伪彩图的问题：
通常背景像素默认为0，对应到paddleseg里边的伪彩图颜色应该是[128,0,0]，但我看到paddleseg用来做例子的数据集optic_disc_seg里边的伪彩图，背景的伪彩颜色为[0,0,0]也就是黑色，那么到底在paddleseg里边对背景像素是怎么认定的，[128,0,0]和[0,0,0]都是背景伪彩色吗？没有匹配正确的背景色会不会导致训练错误？

**Comment by ximitiejiang** [comment]
单独跟踪到`dataset/__get_item__()`函数的tranform中，发现paddleseg用PIL.Image直接打开伪彩图，得到的居然就是单通道的label图，像素值就是标注的[0,1]。
想知道实现原理是什么，怎么不需要把伪彩色查表就可以直接得到label了？

**Comment by juncaipeng** [comment]
伪彩色只是显示罢了，optic_disc_seg里边的伪彩图是有自己的伪彩色表，任何图片都可以使用不同的伪彩色表。
训练的时候，只使用图像像素数值即可。

**Comment by ximitiejiang** [comment]
看了下paddleseg的灰度转伪彩代码，清楚了：
- color map可以使任意映射的数据(比如开始3个代表背景的，可以是[128,0,0], 也可以是[0,0,0])，得到的伪彩图也可以显示成任意色彩，但label_pil本质上的数据没有改变，用Image.open()打开后的内容都是一样的。

thanks!
