### ISSUE TITLE
variables of backbone and head are not in pretrained model

### ISSUE THREAD

**Issue by ahnaf012** [PaddlePaddle/PaddleSeg#1276]
I am using pretrained model of deeplabv3p for prediction without training. I downloaded the model from url specified in deeplabv3p_resnet50_os8_voc12aug_512x512_40k.yml file. However, when I run the predict.py function with model_path as the model.pdparams of downloaded pretrained model I keep getting messages like `[WARNING]   backbone.bb_0_0.conv1._conv.weight is not in pretrained model` until I get `There are 0/615 variables loaded into DeepLabV3P.`
And the prediction doesn't detect any classes in the input images. So, how to use pretrained model directly for prediction?

**Comment by juncaipeng** [comment]
First, you should download the pretrained params from https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.2/configs/deeplabv3p
![image](https://user-images.githubusercontent.com/52520497/130443178-8a6f81ba-0e90-41e9-8727-28ef60b91c49.png)

Then, set the path the in deeplabv3p_resnet50_os8_voc12aug_512x512_40k.yml
![image](https://user-images.githubusercontent.com/52520497/130443282-150ee3cc-07cb-48df-a8da-0a0fd4a6b066.png)

**Comment by ahnaf012** [comment]
Thanks. It works now after following your comment @juncaipeng
