### ISSUE TITLE
Strange behaviour in the memory allocation

### ISSUE THREAD

**Issue by AKMourato** [PaddlePaddle/PaddleSeg#1284]
When configuring the ```_base_/cityscapes.yml``` for the use of unet, unet2 and unet3+ I've noticed that if the RandomPaddingCrop is not defined, cuda goes out of memory independently of the input size defined by the resize.
I'm working with 4k images, if the ComposeTransforms runs in the same order of the config file, the resize should be made first then the random crop:
```python
batch_size: 1
iters: 80000

train_dataset:
  type: Dataset
  dataset_root: '/home/amourato/VM/New_COCO_DPD/train/'
  
  train_path: '/home/amourato/VM/New_COCO_DPD/train/train.txt'
  num_classes: 2
  transforms:
    - type: Resize
      target_size: [512,512]
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.1
      contrast_range: 0.1
      saturation_range: 0.1
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: '/home/amourato/VM/New_COCO_DPD/test/'
  val_path: '/home/amourato/VM/New_COCO_DPD/test/test.txt'
  num_classes: 2
  transforms:
    - type: Resize
      target_size: [512,512]
    - type: Normalize
  mode: val


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.0003
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]
```
I've tried with different input sizes with the 3 networks and in order to work with a specific size defined by the Resize, I need to set the RandomPaddingCrop at least to the same size as Resize.
For the specific config above, Unet3+ is able to train, but if I remove the RandomPaddingCrop, the GPU runs out of memory even though the image size is the same in both transforms.
Is there any process in between that might explain this behaviour?
Thanks.

**Comment by michaelowenliu** [comment]
@AKMourato Hi, ResizeStepScaling will scale the image from 0.5 to 2.0. That is why you should crop the image again.

**Comment by AKMourato** [comment]
Thanks @michaelowenliu. What is the purpose of that btw?

**Comment by michaelowenliu** [comment]
@AKMourato like multi-scale training.
