### ISSUE TITLE
mac训练好的模型在ubuntu预测接口，区别太大，需要紧急修复！

### ISSUE THREAD

**Issue by lt1946** [PaddlePaddle/PaddleSeg#1292]
mac训练loss： 0.28， IoU,Acc: (基本都为9.8左右)
ubuntu训练loss： 0.28，但：IoU,Acc: 0. , 0.1 , 0. ....(基本都为0)
mac预测正常， 但：在ubuntu预测错误。
paddle,paddleseg版本一致，
git仓库也一致，
紧急修复，谢谢！！

**Comment by juncaipeng** [comment]
loss计算没问题，应该不是paddle的错误。
估计是paddleseg的计算模块不对，具体可以说一下环境、使用seg的版本
