### ISSUE TITLE
EISeg软件物体抠完图后背景如何设置成透明

### ISSUE THREAD

**Issue by janyChan** [PaddlePaddle/PaddleSeg#1294]
您好，我想请问一下，使用EISeg进行图像分割时，保存后的图像位png格式，并且我看到背景色可以选择。那么，我希望可以时透明背景，请问这里需要如何设置？还是说目前并不支持

**Comment by haoyuying** [comment]
目前不支持透明背景，我们会考虑您的建议，在日后扩充该功能

**Comment by badboy-tian** [comment]
@haoyuying 你好 现在支持分割后保存透明背景的png吗？谢谢
