### ISSUE TITLE
FatalError: `Process abort signal` is detected by the operating system.

### ISSUE THREAD

**Issue by Ultraopxt** [PaddlePaddle/PaddleSeg#1295]
I cannot open EISeg on ubuntu 20.04 with the following problem:

Maximum number of clients reachedMaximum number of clients reachedqt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1629962952 (unix time) try "date -d @1629962952" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e80001f509) received by PID 128265 (TID 0x7f7db05eb740) from PID 128265 ***]

**Comment by haoyuying** [comment]
xcb问题在新版的eiseg已经解决，请尝试安装0.3.0版本的eiseg进行体验。

**Comment by luoshuifeiyang** [comment]
> xcb问题在新版的eiseg已经解决，请尝试安装0.3.0版本的eiseg进行体验。

您好，我安装的是最新版本，但依旧出现这个问题了。
<pre>----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1631621441 (unix time) try &quot;date -d @1631621441&quot; if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e900004ffd) received by PID 20477 (TID 0x7ffb0b214740) from PID 20477 ***]

已放弃 (核心已转储)
</pre>
