### ISSUE TITLE
使用自己的VOC数据报错，Cuda error(719), unspecified launch failure.

### ISSUE THREAD

**Issue by CamelKing1997** [PaddlePaddle/PaddleSeg#1297]
使用自建VOC格式布局数据集报错，使用公开数据集无问题
自建数据仅有1个NG标签

config file:

deeplabv3p_resnet50_os8_voc12_512x512_40k.yml：
_base_: '../custom/pascal_voc12.yml'
model:
  type: DeepLabV3P
  backbone:
    type: ResNet50_vd
    output_stride: 8
    multi_grid: [1, 2, 4]
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  backbone_indices: [0, 3]
  aspp_ratios: [1, 12, 24, 36]
  aspp_out_channels: 256
  align_corners: False
  pretrained: null

(pdseg) wyy@Dinnar-WYY:~/文档/00_Project/TSMT_PaddleSeg$ python train.py --config configs/custom/deeplabv3p_resnet50_os8_voc12_512x512_40k.yml
2021-08-27 14:32:15 [INFO]      
------------Environment Information-------------
platform: Linux-5.4.0-81-generic-x86_64-with-debian-buster-sid
Python: 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) [GCC 9.3.0]
Paddle compiled with cuda: True
NVCC: Cuda compilation tools, release 10.1, V10.1.105
cudnn: 7.6
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: NVIDIA GeForce']
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PaddlePaddle: 2.1.2
OpenCV: 4.5.3
------------------------------------------------
2021-08-27 14:32:15 [INFO]      
---------------Config Information---------------
batch_size: 2
iters: 40000
loss:
  coef:
  - 1
  types:
  - ignore_index: 255
    type: CrossEntropyLoss
lr_scheduler:
  end_lr: 0
  learning_rate: 0.01
  power: 0.9
  type: PolynomialDecay
model:
  align_corners: false
  aspp_out_channels: 256
  aspp_ratios:
  - 1
  - 12
  - 24
  - 36
  backbone:
    multi_grid:
    - 1
    - 2
    - 4
    output_stride: 8
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
    type: ResNet50_vd
  backbone_indices:
  - 0
  - 3
  pretrained: null
  type: DeepLabV3P
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 4.0e-05
train_dataset:
  dataset_root: data/TSMTdevkit/
  mode: train
  transforms:
  - max_scale_factor: 2.0
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - crop_size:
    - 512
    - 512
    type: RandomPaddingCrop
  - type: RandomHorizontalFlip
  - brightness_range: 0.4
    contrast_range: 0.4
    saturation_range: 0.4
    type: RandomDistort
  - type: Normalize
  type: PascalVOC
val_dataset:
  dataset_root: data/TSMTdevkit/
  mode: val
  transforms:
  - target_size:
    - 512
    - 512
    type: Padding
  - type: Normalize
  type: PascalVOC
------------------------------------------------
W0827 14:32:15.853025 29741 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.4, Runtime API Version: 10.1
W0827 14:32:15.853040 29741 device_context.cc:422] device: 0, cuDNN Version: 7.6.
2021-08-27 14:32:16 [INFO]      Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
2021-08-27 14:32:17 [INFO]      There are 275/275 variables loaded into ResNet_vd.
/home/wyy/.conda/envs/pdseg/lib/python3.7/site-packages/paddle/nn/layer/norm.py:641: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
/home/wyy/.conda/envs/pdseg/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py:239: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float32, but right dtype is paddle.int64, the right dtype will convert to paddle.float32
  format(lhs_dtype, rhs_dtype, lhs_dtype))
Traceback (most recent call last):
  File "train.py", line 190, in <module>
    main(args)
  File "train.py", line 185, in main
    fp16=args.fp16)
  File "/home/wyy/文档/00_Project/TSMT_PaddleSeg/paddleseg/core/train.py", line 209, in train
    avg_loss += loss.numpy()[0]
OSError: (External)  Cuda error(719), unspecified launch failure.
  [Advise: Please search for the error code(719) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:394)

**Comment by juncaipeng** [comment]
自建数据仅有1个NG标签，NG是什么意思？

voc数据集代码读取文件是[链接](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/paddleseg/datasets/voc.py)，你可以看下是否可以准确读取到你自建数据集的image_path和label_path
