### ISSUE TITLE
请问PaddleSeg动态图是否支持多通道数据

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/PaddleSeg#1301]
您好，我看到静态图的contrib中支持遥感影像的多通道数据，请问静态图中是否支持多通道数据呢

**Comment by LutaoChu** [comment]
你好，动态图暂不支持多通道。不过关键在于数据读取、数据预处理和网络第一层支持多通道即可。这部分你可以参照静态图中的相关实现
