### ISSUE TITLE
遙感影像支持

### ISSUE THREAD

**Issue by skylning** [PaddlePaddle/PaddleSeg#1303]
請問支持遙感影像標注不？

**Comment by juncaipeng** [comment]
是说EISeg吗？遥感影像是几个通道的？

**Comment by skylning** [comment]
一般都是RGB三个波段的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月30日(星期一) 上午10:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleSeg] 遙感影像支持 (#1303)





 
是说EISeg吗？遥感影像是几个通道的？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by juncaipeng** [comment]
EISeg中的通用模型不支持遥感图像，分割出来的效果不好
