### ISSUE TITLE
Android demo 分割耗时100ms+不能用于视频通话

### ISSUE THREAD

**Issue by 2017398956** [PaddlePaddle/PaddleSeg#1306]
测试机型：华为 mate30 pro 5G
PaddleSeg :Release 2.2
模型生成方式：
1.paddle_lite_opt --model_file=./model.pdmodel --param_file=./model.pdiparams --quant_model=true --quant_type=QUANT_INT8 --valid_targets=arm --optimize_out_type=naive_buffer --optimize_out=***

2.(有的后缀是这个 pdparams) paddle_lite_opt --model_file=./model.pdmodel --param_file=./model.pdiparams --quant_model=true --quant_type=QUANT_INT8 --valid_targets=arm --optimize_out_type=naive_buffer --optimize_out=***

3.paddle_lite_opt --model_file=./\_\_model\_\_ --param_file=./\_\_params\_\_ --quant_model=true --quant_type=QUANT_INT8 --valid_targets=arm --optimize_out_type=naive_buffer --optimize_out=***

demo 可以正常就是时间长无法用于视频。另外，我把 demo 中的hrnet_w18_small.nb 替换成从 \PaddleSeg\contrib\HumanSeg\export_model\shufflenetv2_humanseg_192x192_with_softmax 中生成的 *.nb 时间也要100ms 左右。其它的模型也转换成 *.nb 试了下，都没有达到文档上说的 17ms左右。
方便的话能否提供一个用于手机实时视频的模型？

**Comment by juncaipeng** [comment]
请问你是参考哪个文档中说的17ms，估计不同手机有些许差异。
人像分割，可以测试一下这个模型：https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.2/contrib/PP-HumanSeg#%E5%8D%8A%E8%BA%AB%E5%83%8F%E5%88%86%E5%89%B2portrait-segmentation

**Comment by 2017398956** [comment]
我是看的这个 https://baidudanao.blog.csdn.net/article/details/106846331 。
![image](https://user-images.githubusercontent.com/12185078/131455546-76495575-9418-418d-b4dd-4b988fa86811.png)

试了下上面你给的新模型 （export_model/ppseg_lite_portrait_398x224_with_softmax 和 shufflenetv2_humanseg_192x192_with_softmax）还是 100ms+ 。
[这是我通过上面的命令生成的模型](https://github.com/PaddlePaddle/PaddleSeg/files/7081779/model.zip)
demo中替换一张图片的背景：CPU 选择的是 only big cores ，线程选择的是 1 个（选择多个耗时会增加）。
我觉得应该不是手机的问题，用华为 Mate 30 Pro5G 测试的，是不是我生成模型的参数不对或者 Android 的 demo 需要额外配置一些用于加速的参数？

**Comment by juncaipeng** [comment]
你输入图片大小是多少啊？ 上面数据是192*192输入的数据。

**Comment by 2017398956** [comment]
输入的图片是 1200 * 800 ，在分割之前 Android demo 中会把图片缩放成 192 * 192 的：

![image](https://user-images.githubusercontent.com/12185078/132189050-72ebee21-24ec-4c5d-a791-38bbd224ee2a.png)

，我记录的是从开始分割到分割结束的时间

![image](https://user-images.githubusercontent.com/12185078/132189468-159d143a-c468-4d97-bb8e-cfb4ec27c16b.png)

另外我也试了 192*192 的图片，也是一样。

**Comment by 2017398956** [comment]
我发现问题怎么解决了，如果是单张图片耗时要 100ms+ 要是一次处理大量图片就可以了（试了 100 张，总耗时 2462ms）
