### ISSUE TITLE
剪枝现在不支持deeplabev3 resnet50 吗？ValueError: cannot reshape array of size 48 into shape (304,newaxis) 

### ISSUE THREAD

**Issue by pureloveljc** [PaddlePaddle/PaddleSeg#1309]
剪枝现在不支持deeplabev3 resnet50 吗？ValueError: cannot reshape array of size 48 into shape (304,newaxis)

**Comment by michaelowenliu** [comment]
@pureloveljc Hi, please put the detailed error log info?
