### ISSUE TITLE
EISeg

### ISSUE THREAD

**Issue by Minemine-cloud** [PaddlePaddle/PaddleSeg#1313]
目前支持用HRNet18-OCR64训练自定义数据集生成相应模型参数吗，可以暴露相关参数设置的细节信息吗？

**Comment by haoyuying** [comment]
目前暂不支持训练，日后会开放相应的代码，请持续关注eiseg动态。

**Comment by duduzai2019** [comment]
> 目前暂不支持训练，日后会开放相应的代码，请持续关注eiseg动态。

请问我用eiseg标注生成的coco文件可以用于语义分割训练吗？？
