### ISSUE TITLE
PaddleSeg文档中找不到哪里有可以调整置信度（threshold）的地方

### ISSUE THREAD

**Issue by liuhuaguang** [PaddlePaddle/PaddleSeg#1317]
在使用PaddleDetection和PaddleOCR中，都有调整置信度（threshold）的地方，唯独PaddleSeg找不到，包括使用文档中也没有提及，请问是不能调整还是文档中未体现呢？

**Comment by LutaoChu** [comment]
分割不像检测、ocr有bounding box，暂时没有听说过需要调整置信度。请问你需要这个做什么呢？

**Comment by liuhuaguang** [comment]
我是看到BML上的图像分割模型中可以调整置信度，所以就来尝试测试下检测瑕疵的效果，把缺陷标注、训练、验证，看它与目标检测哪个效果好？如果是这样的话，那BML中为什么会有置信度呢

**Comment by liuhuaguang** [comment]
我是看到BML上的图像分割模型中可以调整置信度，所以就来尝试测试下检测瑕疵的效果，把缺陷标注、训练、验证，看它与目标检测哪个效果好？如果是这样的话，那BML中为什么会有置信度呢

**Comment by liuhuaguang** [comment]
目标检测好像没办法过滤检测出来的缺陷大小，图像分割倒是可以，所以就想着测试下

**Comment by LutaoChu** [comment]
了解。BML的分割模型链接发一下吧，我们看下

**Comment by liuhuaguang** [comment]
http://ai.baidu.com/bml/app/modelRepo/12778/16059?module=1

**Comment by liuhuaguang** [comment]
> 了解。BML的分割模型链接发一下吧，我们看下

你好，请问有进展了吗？

**Comment by LutaoChu** [comment]
你好，链接打不开
![image](https://user-images.githubusercontent.com/30695251/133362613-a413fe17-3e37-4a7a-b253-a29084a60118.png)

**Comment by liuhuaguang** [comment]
![捕获](https://user-images.githubusercontent.com/88823508/133378313-25e69dd4-c792-417e-93b2-f3bb84f69c87.PNG)
![屏幕截图 2021-09-15 135423](https://user-images.githubusercontent.com/88823508/133378319-50ee47a6-410c-4cbd-a4dd-e43c620dbbb3.png)
你好，详细请查看以上图片

**Comment by liuhuaguang** [comment]
![屏幕截图 2021-09-15 135641](https://user-images.githubusercontent.com/88823508/133378563-68818c4f-5e5f-46be-87a7-2e1b2e559dd1.png)

**Comment by LutaoChu** [comment]
你这个还有mAP，预测标签有2个相同的，是实例分割吗？
另外调整置信度的话，可能有多个类别超过阈值，需要是多标签分类，你的任务属于多标签分类吗？

**Comment by liuhuaguang** [comment]
是实例分割，见下图
![微信截图_20210915165420](https://user-images.githubusercontent.com/88823508/133403037-8c079be1-b42a-4a3e-9ac9-6eaefff5fa29.png)
另外，您说的“多标签分类”好像是图像分类的，我使用的是图像分割，没有分单标签\多标签

**Comment by LutaoChu** [comment]
是实例分割的话确实是可以有置信度的。因为计算mAP时需要用到实例mask，实例mask是通过选择置信度大于指定阈值的区域筛选出来。
paddleseg目录下为语义分割，没有置信度。全景分割有置信度，见
https://github.com/PaddlePaddle/PaddleSeg/blob/cc6fa1404d2b1553307f49b874b2d656be08c83c/contrib/PanopticDeepLab/utils/evaluation/instance.py#L149

**Comment by liuhuaguang** [comment]
好的，谢谢解答
