### ISSUE TITLE
为什么验证paddleseg时候，modelpath那个网址总是不能被识别？

### ISSUE THREAD

**Issue by 6031jiajia** [PaddlePaddle/PaddleSeg#1321]

**Comment by 6031jiajia** [comment]
--model_path https://bj.bcebos.com/paddleseg/dygraph/optic_disc/bisenet_optic_disc_512x512_1k/model.pdparams  这个不能别识别是怎么回事？

**Comment by juncaipeng** [comment]
这个是下载预训练模型的权重，用wegt可以下载吗？或者浏览器中点击这个链接可以下载吗？
