### ISSUE TITLE
将PP-HumanSeg-Server人像分割模型转换为VINO模型，结果很差

### ISSUE THREAD

**Issue by zhangzscn** [PaddlePaddle/PaddleSeg#1322]
使用如下代码转化
1、先转化为ONNX模型
paddle2onnx --model_dir deeplabv3p_resnet50_os8_humanseg_512x512_100k_with_softmax  --model_filename model.pdmodel --params_filename model.pdiparams  --save_file model.onnx  --opset_version 11 --enable_onnx_checker True
2、再转化为VINO模型
sudo mo_onnx.py --input_model deeplabv3p_resnet50_os8_humanseg_512x512_100k_with_softmax/model.onnx --output_dir /deeplabv3p_resnet50_os8_humanseg_512x512_100k_with_softmax --input_shape [1,3,512,512]
分割代码采用VINO官方的例子segmentation_demo。
VINO官方的模型一切正常，但PP-HumanSeg-Server这个模型，完全分割不出人体，没有出MASK，PP-HumanSeg-Mobile的分割效果很差

**Comment by heliqi** [comment]
请问你推理是怎么做的？ 直接用openvino推理是不行的， paddle套件导出的模型是由预处理的

如果是cpp部署，参考下这个文档： https://github.com/PaddlePaddle/PaddleX/blob/develop/deploy/cpp/docs/compile/openvino/README.md

**Comment by zhangzscn** [comment]
模型导出后，用openino官方的例子segmentation_demo，估计是少了预处理

**Comment by Xzavierlovescoding** [comment]
> 模型导出后，用openino官方的例子segmentation_demo，估计是少了预处理

你好，请问最后问题解决了吗？我遇到了一样的问题，也是用cpp+OpenVINO部署，结果也是很差，但是不知道预处理的部分怎么写，我是直接输入模型处理的
