### ISSUE TITLE
使用deepglobe_road_extraction.yaml运行报错

### ISSUE THREAD

**Issue by yangy996** [PaddlePaddle/PaddleSeg#1327]
教程链接：
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/legacy/docs/dice_loss.md
paddle版本2.1.1
![image](https://user-images.githubusercontent.com/15188456/132321636-4f0c7bef-0ea5-4994-814e-127732f9127c.png)
![image](https://user-images.githubusercontent.com/15188456/132321687-f3a72b17-fd48-46bc-b5a2-097da87e2f16.png)

**Comment by michaelowenliu** [comment]
@YY007H Hi, the tutorial in `legacy` might be deprecated.

**Comment by yangy996** [comment]
额，为啥要废弃呢？静态图的模型都很小，动态图的模型都太大了

**Comment by michaelowenliu** [comment]
@YY007H Hi, we provide a lot models in the new version, please refer to https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.2/configs
