### ISSUE TITLE
paddleseg 保存的模型中存在sync_batch_norm ops,怎么将该部分转为batch_norm呢？

### ISSUE THREAD

**Issue by rourou8023** [PaddlePaddle/PaddleSeg#1335]
使用paddleseg中的OCRNet，保存的模型在转onnx时，报存在sync_batch_norm，onnx不支持。
paddle2onnx issue 中提到，sync_batch_norm是只存在训练过程中，
麻烦问下，怎么修改，使得保存的模型中没有sync_batch_norm？
或者已保存的模型怎么将该部分转为batch_norm？

**Comment by haoyuying** [comment]
您好，模型转换问题请移步paddle2onnx下提问，以便获得更专业的回复。位置：https://github.com/PaddlePaddle/Paddle2ONNX

**Comment by rourou8023** [comment]
好的，已解决，谢谢

**Comment by caj-github** [comment]
怎么解决的？

**Comment by geoexploring** [comment]
@rourou8023 ，请问如何解决的？谢谢
