### ISSUE TITLE
Paddleseg转onnx

### ISSUE THREAD

**Issue by Chenzixi1** [PaddlePaddle/PaddleSeg#1336]
利用paddle2onnx转模型，转换正常，但输出模型的output shape不正常，影响后面工作，是否可以解决？

具体情况：

输入 [1, 3, 512, 512]
输出 [1, 2, -1, -1]

**Comment by juncaipeng** [comment]
模型方便放上来吗？我们专门同学来看下问题。

**Comment by Chenzixi1** [comment]
> 模型方便放上来吗？我们专门同学来看下问题。

PaddleSeg 中的 BiSeNetV2 

问题解决了，前向传播中的上采用导致的，更改为固定shape就可以了

            logit_list = [
                F.interpolate(
                    logit,
                    paddle.shape(x)[2:],
                    mode='bilinear',
                    align_corners=self.align_corners) for logit in logit_list
            ]

谢谢
