### ISSUE TITLE
加载预训练的模型参数进行预测问题

### ISSUE THREAD

**Issue by zyl2995230** [PaddlePaddle/PaddleSeg#1339]
你好：

我利用PaddleSeg训练一个HRnetw48的模型保存了最优的模型参数，当我利用PaddleSeg的模型API进行自定义调用并加载预训练模型参数进行预测，结果发现单独调用模型API去预测图片和利用PaddleSeg中predict.py进行预测相差甚远，对单独调用模型API组网进行预测并可视化结果根本就看不出任何的图片结构，而利用predict.py进行预测，输出的19个numclass都有很好的图片结构。这是为什么？同样的模型和参数，为什么结果天差地别

**Comment by juncaipeng** [comment]
应该是你组网、加载、预测中出现了错误，你可以顺着predict.py的逻辑代码排查哪里出错哦。
你是什么目的需要自己自定义调用模型API？

**Comment by zyl2995230** [comment]
> 应该是你组网、加载、预测中出现了错误，你可以顺着predict.py的逻辑代码排查哪里出错哦。
> 你是什么目的需要自己自定义调用模型API？

网络我是调用PaddleSeg里的网络API进行组网的，加载我是利用Paddle.load()和paddle.nn.layer.set_state.dict()进行预加载参数，然后我是正常预测 其中没有报错，但是结果就是不一样

**Comment by juncaipeng** [comment]
你自己组网算是高阶使用了，要求你熟悉seg的内部代码。
估计你组网、加载没有问题，你要排查数据加载、预处理、输出加argmax、输出图像伪彩色显示等步骤，这些都可以在predict.py中找到，建议你一步步调试。

**Comment by zyl2995230** [comment]
> 你自己组网算是高阶使用了，要求你熟悉seg的内部代码。
> 估计你组网、加载没有问题，你要排查数据加载、预处理、输出加argmax、输出图像伪彩色显示等步骤，这些都可以在predict.py中找到，建议你一步步调试。

嗯，我之前也认真去找了但是找不到问题，所以才过来提问的。我再仔细看看
