### ISSUE TITLE
labelme2seg文件中图片不存在时错误

### ISSUE THREAD

**Issue by L-lei** [PaddlePaddle/PaddleSeg#1343]
原文件在tools/labelme2seg.py
原逻辑是通过读取img_file文件获取图像的维度信息,是否考虑使用data['imageHeight']与data['imageWidth']

在调用shape2label函数84行img_size=img.shape,是否考虑使用img_size=(data['imageHeight'],data['imageWidth'])

**Comment by juncaipeng** [comment]
这个文件是将labelme标注的数据转为符合paddleseg格式要求的数据。
shape2label函数84行是使用从yml文件中加载出来的data，这个date格式如[链接](https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.8.0/docs/annotation/labelme_demo/2011_000025.json#L2)，必须使用data["shape"]才可以读取。

**Comment by L-lei** [comment]
我看到的labelme数据格式怎么与链接中的有写不一样了,我的是这样的{
  "imagePath": "102.jpg",
  "imageWidth": 1920,
  "version": "4.2.10",
  "imageData": "/9j/2Q==",
  "flags": {},
  "imageHeight": 1080,
  "shapes": [
    {
      "group_id": null,
      "label": "1",
      "flags": {},
      "shape_type": "polygon",
      "points": [
        [
          1294.341463414634,
          428.60975609756093
        ],
        [
          1382.1463414634145,
          387.1463414634146
        ],
        [
          1427.2682926829268,
          407.87804878048775
        ],
        [
          1418.731707317073,
          484.70731707317066
        ],
        [
          1305.3170731707316,
          463.9756097560975
        ]
      ]
    }

  ]
}
链接中的文件没有version字段,看着像v3版本(与v3相比也缺少某些字段),我的是v4版本

**Comment by L-lei** [comment]
好像是v2版本

**Comment by L-lei** [comment]
这样说也没什么问题,如果按照原逻辑但还是建议加一个提示"没找到imagePath"

**Comment by L-lei** [comment]
感谢,解决了我的疑问

**Comment by L-lei** [comment]
这样说也没什么问题,如果按照原逻辑但还是建议加一个提示"没找到imagePath"
