### ISSUE TITLE
模型保存时报错

### ISSUE THREAD

**Issue by sunhufei** [PaddlePaddle/PaddleSeg#1347]
出现如下错误：
paddle.fluid.core.save_op_compatible_info(_test_program.desc)
AttributeError: module 'paddle.fluid.core_avx' has no attribute 'save_op_compatible_info'

请问如何解决？

**Comment by wuyefeilin** [comment]
请提供一下你的paddle版本和paddleseg版本
另外提供一下完整报错信息哈
