### ISSUE TITLE
语义分割样本均衡的问题

### ISSUE THREAD

**Issue by lytk01** [PaddlePaddle/PaddleSeg#135]
你好，之前听快车道PaddleSeg的分享，讲到有样本均衡，这一块在PaddleSeg项目里有体现吗，或者具体是怎么做的呢

**Comment by LutaoChu** [comment]
你好，PaddleSeg的高级教程中有相关的文档 https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.3.0/docs/loss_select.md

**Comment by lytk01** [comment]
@LutaoChu 有没有关于多分类之间的样本均衡文档呢

**Comment by LutaoChu** [comment]
暂时没有，我们后续即将推出equibatch和lovasz loss来解决样本不均衡问题，敬请期待

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。
