### ISSUE TITLE
我猜你们中有个叛徒:-P

### ISSUE THREAD

**Issue by qianyizhang** [PaddlePaddle/PaddleSeg#1351]
https://github.com/PaddlePaddle/PaddleSeg/blob/cc6fa1404d2b1553307f49b874b2d656be08c83c/contrib/EISeg/setup.py#L38

**Comment by yzl19940819** [comment]
您好，EISeg是由PaddleSeg团队和PaddleSeg外部开发者共同完成，尤其是前端由韩霖和陈奕州同学提供了，他们留自己的邮箱是非常合理的哦

**Comment by qianyizhang** [comment]
格局大了:)
