### ISSUE TITLE
windows版本的 exe链接失效了，麻烦作者给更新一下，谢谢

### ISSUE THREAD

**Issue by qinwsq** [PaddlePaddle/PaddleSeg#1354]

**Comment by haoyuying** [comment]
已更新

**Comment by qinwsq** [comment]
你好，是eiseg的exe，刚没说清楚，不好意思

**Comment by hosea7456** [comment]
@haoyuying
目前的连接也失效了，是在维护吗?

**Comment by hosea7456** [comment]
@haoyuying 
目前的链接也失效了，是在维护吗?

**Comment by qinwsq** [comment]
@hosea7456 
https://pan.baidu.com/s/1aGxWDHSzYRNPfpgA6ib7mw
直接从这下（提取码：82z9）

**Comment by haoyuying** [comment]
develop分支上链接已更新。

**Comment by hosea7456** [comment]
> @hosea7456
> https://pan.baidu.com/s/1aGxWDHSzYRNPfpgA6ib7mw
> 直接从这下（提取码：82z9）

好的，谢谢！
