### ISSUE TITLE
EISeg:ModuleNotFoundError: No module named 'qtpy'

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSeg#1358]
```
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/contrib/EISeg/README.md

安装好所需环境后，进入EISeg，可通过直接运行eiseg打开EISeg：

cd PaddleSeg\contrib\EISeg
python -m eiseg
```

按照官方教程  报错

ModuleNotFoundError: No module named 'qtpy'

pip install QtPy

ModuleNotFoundError: No module named 'skimage'

pip install scikit-image

解决方法

应该在教程中
增加一步
pip install -r PaddleSeg\contrib\EISeg\requirements.txt

**Comment by monkeycc** [comment]
pip install QtPy

ModuleNotFoundError: No module named 'skimage'

**Comment by monkeycc** [comment]
pip install scikit-image

解决问题

应该增加在 requirements.txt

**Comment by haoyuying** [comment]
需要安装依赖的，在requirements.txt文件里面。

**Comment by monkeycc** [comment]
我知道要安装依赖

问题是  官方教程里面 应该要写出来

安装EISeg   要安装依赖
pip install -r PaddleSeg\contrib\EISeg\requirements.txt

**Comment by sea-comet** [comment]
Greate help for me!
