### ISSUE TITLE
EISeg:加载目录,没有反应

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSeg#1359]
python -m eiseg
W0916 09:31:40.033562  5348 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 11.2
W0916 09:31:40.049214  5348 device_context.cc:422] device: 0, cuDNN Version: 8.1.

--------------------

加载目录  没有反应  不显示图片
数据列表为空  
-------------------------------
加载单张图片会显示   数据列表正常

**Comment by haoyuying** [comment]
目录下要有一张张的图，就会显示，目录下不能还是目录。

**Comment by monkeycc** [comment]
目录下有一张一张的图片，但是有之前目标标注的几个XML文件。

这个应该就是导致 不能正常加载的原因
