### ISSUE TITLE
EISeg:标注保存需要两步

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSeg#1360]
EISeg
点击"完成当前目标标注"
却提示"标签尚未保存，是否保存标签"
还要另外点击”保存“按钮

这样的话  需要在 左上角 点击 "完成当前目标标注"  
然后右边 点击 数据列表 的 “保存”

鼠标基本上跨越了一个屏幕   很费劲

--------------------------
建议：
点击  “完成当前目标标注" 就自动保存

**Comment by haoyuying** [comment]
上方的工具栏有自动保存选项，需要点击下设定
![image](https://user-images.githubusercontent.com/35907364/133539690-26c69d3f-5f39-4895-9086-1df85a36757b.png)

**Comment by monkeycc** [comment]
我按了这个 ”自动保存“
但是 没有显示   打勾
