### ISSUE TITLE
EISeg: JSON和COCO，是否能同时保存，是否能互相转换

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSeg#1361]
JSON和COCO，
是否能同时保存
比如我想保存两个格式 
万一以后需要呢

如果不行
那么是否能互相转换呢
有没py代码 可以实现一键转换功能

**Comment by haoyuying** [comment]
目前只能保存一个

**Comment by duduzai2019** [comment]
同求

**Comment by duduzai2019** [comment]
> JSON和COCO， 是否能同时保存 比如我想保存两个格式 万一以后需要呢
> 
> 如果不行 那么是否能互相转换呢 有没py代码 可以实现一键转换功能

你好，我之前保存成json格式，现在想用coco格式，请问您转换成功了吗？？？

**Comment by duduzai2019** [comment]
> 你好，我之前保存成json格式，现在想用coco格式，请问您转换成功了吗？？？

你好，我之前保存成json格式，现在想用coco格式，请问怎样可以转换成coco格式
