### ISSUE TITLE
EISeg: 建议增加目标检测两点标注，或者提供转换py

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSeg#1362]
建议增加目标检测两点标注

这样可以进行目标检测标注的工作

如果感觉工作量太大

可以考虑先提供转换py
可以直接把分割的json 转换为 标注的VOC和COCO格式

**Comment by haoyuying** [comment]
目前有自动生成的bbox信息，您的建议我们会考虑的，感谢您的建议。
