### ISSUE TITLE
请问使用你们开源的最轻量级的人像分割模型+DIS光流在移动端CPU上能达到实时吗?

### ISSUE THREAD

**Issue by zane-wong-developer** [PaddlePaddle/PaddleSeg#1366]
感谢开源工作.

**Comment by LutaoChu** [comment]
你好，在移动端CPU上我们还没有测过，估计应该是可以的

**Comment by ThreeBoxWithCode** [comment]
你好，请问这个轻量级人像分割模型能在哪里看到呢

**Comment by LutaoChu** [comment]
在这里  https://github.com/PaddlePaddle/PaddleSeg/blob/develop/contrib/PP-HumanSeg/README_cn.md

**Comment by ghoshaw** [comment]
请问 送入光流处理之前为什么要给scoremap 乘255呢，我看 在 seg_fuse的时候里面判断 确定区域时用的阈值是 0.1和0.9.
