### ISSUE TITLE
When I click the image, the error is appeared.

### ISSUE THREAD

**Issue by ty199931** [PaddlePaddle/PaddleSeg#1372]
the error is:
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1631958284 (unix time) try "date -d @1631958284" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800003544) received by PID 13636 (TID 0x7f99571b90c0) from PID 13636 ***]

已放弃 (核心已转储)

**Comment by michaelowenliu** [comment]
@ty199931 Hi, may I know which model you are running?

**Comment by haoyuying** [comment]
请使用最新版eiseg及2.1版本以上的paddlepaddle，并检查paddle是否能正常使用。目前问题定位是由于paddle和cuda及cudnn版本不匹配导致的。

**Comment by ty199931** [comment]
> 请使用最新版eiseg及2.1版本以上的paddlepaddle，并检查paddle是否能正常使用。目前问题定位是由于paddle和cuda及cudnn版本不匹配导致的。

我的cuda是10.1 cudnn 7.6.5   eiseg 2.1.3
但是我在安装检验是否安装成功的时候，最后利用python -c "import paddle; paddle.utils.run_check()"

报错：ExternalError:  Cublas error, `CUBLAS_STATUS_EXECUTION_FAILED`. The GPU program failed to execute. This is often caused by a launch failure of the kernel on the GPU, which can be caused by multiple reasons.  (at /paddle/paddle/fluid/operators/math/blas_impl.cu.h:35)
      [operator < matmul > error]

我也不知道为什么

可能因为这个导致不能使用？

**Comment by ty199931** [comment]
> 请使用最新版eiseg及2.1版本以上的paddlepaddle，并检查paddle是否能正常使用。目前问题定位是由于paddle和cuda及cudnn版本不匹配导致的。

但是我再运行一次 paddle.utils.run_check()时，就会显示成功
