### ISSUE TITLE
代码优化

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleSeg#1373]
您好，有没有什么办法能够将图片中的.numpy()去掉，我用.numpy()是因为paddle中提示现在的索引支持整数、切片，但是不可以从一个Tensor当中同时索引到我想要的多个数值，就像图片中蓝色方框所示的索引方式。我想请教一下图片中的索引方式如果不转numpy直接使用paddle的API如何实现，谢谢！
![image](https://user-images.githubusercontent.com/68497831/134140495-fa9054f1-dd25-4754-8e58-c030dc2ce2af.png)

**Comment by shiyutang** [comment]
mask 索引可以使用 paddle.where 进行替代，参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/where_cn.html
一段简单的示例代码如下所示：
```
import paddle

a = paddle.randn(shape=(2,3))
mask = a>0.5
print('mask', mask)
b = paddle.ones((2,3))
zeros = paddle.zeros((2,3))
e = paddle.ones((3,2,3))
e = e[0,:,:]
f = paddle.where(mask,e,zeros)
d = paddle.where(mask,b,zeros)
print('result', d,f)

import numpy

b = b.numpy()
d = b[mask]
print('result numpy', d)
```
