### ISSUE TITLE
paddleseg  ----matting问题

### ISSUE THREAD

**Issue by gxqnba** [PaddlePaddle/PaddleSeg#1374]
请问一下paddleseg的matting部分在哪里啊？我在介绍里面看到paddleseg可以做matting，但是代码里面没有找到。
![image](https://user-images.githubusercontent.com/61399616/134264980-ad462645-7c66-42a1-bf6b-e48626fe8733.png)

**Comment by michaelowenliu** [comment]
@gxqnba Hi, thanks for your interest. The matting project will be coming soon at the end of this month.

**Comment by gxqnba** [comment]
> @gxqnba Hi, thanks for your interest. The matting project will be coming soon at the end of this month.

Thanks
