### ISSUE TITLE
在jetson nx上部署paddleseg下的用自己的数据集训练好的bisenetV2模型，部署后预测一张图需要几秒，怎么提高预测速度。

### ISSUE THREAD

**Issue by huangwan-jiayi** [PaddlePaddle/PaddleSeg#1375]
我最近成功把我自己训练的paddleseg框架下的模型 用paddle inference c++ 部署到了jetson nx 上了 可是预测的时间需要几秒，完全达不到实时的要求 ，请问一下，你有部署这方面的经验吗，是我需要修改一下代码的什么部分，预测速度才会达到网上说的那么高呢？

**Comment by juncaipeng** [comment]
创建predictor的config的参数是怎样的？ 输入预测的图像大小是多少？  我们在v100上测试bisenetv2，输入大小是1024*2048，只统计predictor预测的计算时间，fps是80左右。

**Comment by huangwan-jiayi** [comment]
![image](https://user-images.githubusercontent.com/71338215/134279944-c59a669a-2dcf-4f55-8a86-dc5be11f9e1c.png)
![image](https://user-images.githubusercontent.com/71338215/134279982-ae5facf7-f0d3-423f-9f6f-3c97ed3f0a61.png)
![image](https://user-images.githubusercontent.com/71338215/134280057-1ca2891f-02f0-44b0-bad1-049fca2ca2ab.png)
![image](https://user-images.githubusercontent.com/71338215/134280058-a600c146-38f9-4189-b1b0-c23038c7f510.png)
这是我预测的c++全部代码，输入预测的图像大小是1920*1080.

**Comment by huangwan-jiayi** [comment]
这是我的环境信息，
![image](https://user-images.githubusercontent.com/71338215/134445844-9e15849a-0e41-4821-b6d6-e03c844fd9ed.png)
![image](https://user-images.githubusercontent.com/71338215/134445836-c66a9540-ed56-44f5-a728-ced71e42dc55.png)

**Comment by huangwan-jiayi** [comment]
图像大小更正为1080*1920

**Comment by juncaipeng** [comment]
重复issue，我删除这个，使用最新的issue吧。
