### ISSUE TITLE
SFnet训练报错

### ISSUE THREAD

**Issue by oym050922021** [PaddlePaddle/PaddleSeg#1376]
sfnet训练时报错：

- 
![微信图片_20210922105342](https://user-images.githubusercontent.com/40224130/134276235-d5758266-d865-4621-a71d-06033559ff8d.png)

请问是怎么回事，谢谢？

**Comment by shiyutang** [comment]
这个初步判断是data loader出现问题分为三步分析：
1. 查看paddle版本是否更新至2.1.2
2. 查看log/worklog.0中出现的具体报错，并更新issue
3. 在issue中补充报错出现的情况，训练一段时间出错还是一开始就出错

**Comment by oym050922021** [comment]
@shiyutang  您好，padddle版本是2.1.2，一开始训练就报错，worklog.0如下：

- 2021-09-22 11:41:28 [INFO]	
------------Environment Information-------------
platform: Linux-5.3.0-28-generic-x86_64-with-debian-buster-sid
Python: 3.7.9 | packaged by conda-forge | (default, Dec  9 2020, 21:08:20) [GCC 9.3.0]
Paddle compiled with cuda: True
NVCC: Not Available
cudnn: 7.6
GPUs used: 4
CUDA_VISIBLE_DEVICES: 0,1,2,3
GPU: ['GPU 0: Tesla V100S-PCIE-32GB', 'GPU 1: Tesla V100S-PCIE-32GB', 'GPU 2: Tesla V100S-PCIE-32GB', 'GPU 3: Tesla V100S-PCIE-32GB']
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PaddlePaddle: 2.1.2
OpenCV: 4.5.1
------------------------------------------------
2021-09-22 11:41:28 [INFO]	
---------------Config Information---------------
batch_size: 2
iters: 80000
loss:
  coef:
  - 1
  types:
  - ignore_index: 255
    type: OhemCrossEntropyLoss
lr_scheduler:
  end_lr: 0
  learning_rate: 0.01
  power: 0.9
  type: PolynomialDecay
model:
  backbone:
    output_stride: 8
    pretrained: /home/ouyangmei/PaddleSeg-release-2.2/pretrained_model/resnet18_vd_ssld_v2/model.pdparams
    type: ResNet18_vd
  backbone_indices:
  - 0
  - 1
  - 2
  - 3
  type: SFNet
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 0.0005
train_dataset:
  dataset_root: /data/ouyangmei/segmentation_datasetes/handwriting-erase-voc-3c/VOCdevkit/
  mode: train
  transforms:
  - max_scale_factor: 2.0
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - crop_size:
    - 1024
    - 1024
    type: RandomPaddingCrop
  - prob: 0.2
    type: RandomVerticalFlip
  - prob: 0.05
    type: RandomNoise
  - type: RandomBlur
  - type: RandomRotation
  - brightness_range: 0.4
    contrast_range: 0.4
    saturation_range: 0.4
    type: RandomDistort
  - type: Normalize
  type: PascalVOC
val_dataset:
  dataset_root: /data/ouyangmei/segmentation_datasetes/handwriting-erase-voc-3c/VOCdevkit/
  mode: val
  transforms:
  - target_size:
    - 1024
    - 1024
    type: Padding
  - type: Normalize
  type: PascalVOC
------------------------------------------------
W0922 11:41:28.488976 32514 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.1, Runtime API Version: 10.1
W0922 11:41:28.489002 32514 device_context.cc:422] device: 0, cuDNN Version: 7.6.
2021-09-22 11:41:30 [INFO]	Loading pretrained model from /home/ouyangmei/PaddleSeg-release-2.2/pretrained_model/resnet18_vd_ssld_v2/model.pdparams
2021-09-22 11:41:31 [INFO]	There are 115/115 variables loaded into ResNet_vd.
I0922 11:41:31.465389 32514 nccl_context.cc:74] init nccl context nranks: 4 local rank: 0 gpu id: 0 ring id: 0
I0922 11:41:31.663872 32514 nccl_context.cc:107] init nccl context nranks: 4 local rank: 0 gpu id: 0 ring id: 10
2021-09-22 11:41:31,753-INFO: [topology.py:152:__init__] HybridParallelInfo: rank_id: 0, dp_degree: 4, mp_degree: 1, pp_degree: 1, dp_group: [0, 1, 2, 3], mp_group: [0], pp_group: [0], check/clip group: [0]
(83, 329, 3)
(108, 160, 3)
WARNING:root:DataLoader reader thread raised an exception.
Traceback (most recent call last):
  File "train.py", line 190, in <module>
    main(args)
  File "train.py", line 185, in main
    fp16=args.fp16)
  File "/home/ouyangmei/PaddleSeg-release-2.2/paddleseg/core/train.py", line 143, in train
    for data in loader:
  File "/home/ouyangmei/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 197, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)


请问是什么原因呢，谢谢！

**Comment by oym050922021** [comment]
@shiyutang 您好，原因已经找到了，与我添加的数据增强有关系，谢谢！
