### ISSUE TITLE
PaddleSeg C++ 预测部署方案，可以类似Detection等单独出来吗，不要跟其他的一起混到paddleX里面？

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/PaddleSeg#1377]
现在PaddleSeg C++ 预测部署方案和其他的检测等一起混合起来放到了paddleX里面，编译依赖太多，编译都编译不过去。但是Detection等里面的，就没那么多依赖，很好编译。

**Comment by heliqi** [comment]
请问你想独立出来的原因是？

**Comment by xinsuinizhuan** [comment]
> 
> 
> 请问你想独立出来的原因是？

就是，像Detection里面，很好编译。但是，现在集成成paddleX里面后，cpp直接的依赖太多，一直编译不过去。
![图片](https://user-images.githubusercontent.com/40679769/134296563-0691c5b1-81ef-4b1e-a037-196c88020c0f.png)
![图片](https://user-images.githubusercontent.com/40679769/134296603-67057a65-12b6-4bea-bb7e-7a7a9dc8d572.png)
像现在，我只要seg的，但是现在我必须把所有的其他的都加进来，但是，都加进来了，结果还是有依赖没加进来，包链接错误

**Comment by xinsuinizhuan** [comment]
像detection的，就依赖自己的，链接了paddle库和yaml库，即可。现在都链接了，依然不行。

**Comment by heliqi** [comment]
paddlex的cpp也是链接了paddle库和yaml库 ，还链接了一个opencv库(Detection应该也依赖了这个)。  多个套件的代码并不会造成更多的第三方库依赖。

你报错的原因看起来可能是：
1. 没有使用release 编译
2. 没有按照文档的操作来 https://github.com/PaddlePaddle/PaddleX/blob/release/2.0.0/deploy/cpp/docs/compile/paddle/windows.md



- 如果你想将部署加入到自己的工程， 可以先把文档中的demo编译过了；再按照cmakelist，根据其中的语法修改进行链接。
- 如果是想编译成lib库，供其它语言调用。可以参照这个文档 https://github.com/PaddlePaddle/PaddleX/tree/release/2.0.0/examples/C%23_deploy
