### ISSUE TITLE
预训练权重有ResNet的吗？

### ISSUE THREAD

**Issue by Anikily** [PaddlePaddle/PaddleSeg#138]

**Comment by ZeyuChen** [comment]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.3.0/turtorial/finetune_pspnet.md
在这个文档的最后，有ResNet50和ResNet101的Backbone参数下载。以及整个PSPNet和cityscapes的ResNet Backbone.
https://paddleseg.bj.bcebos.com/resnet50_v2_pspnet.tgz
https://paddleseg.bj.bcebos.com/resnet101_v2_pspnet.tgz
