### ISSUE TITLE
EISeg Windows版本 share链接失效

### ISSUE THREAD

**Issue by KazusaW1999** [PaddlePaddle/PaddleSeg#1380]
https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.2/contrib/EISeg#:~:text=%E8%BF%9B%E8%A1%8C%E6%89%93%E5%8C%85%E3%80%82%E5%8F%AF%E4%BB%A5%E4%BB%8E-,%E8%BF%99%E9%87%8C%E6%88%96%E7%99%BE%E5%BA%A6%E4%BA%91%E7%9B%98,-%EF%BC%88%E6%8F%90%E5%8F%96%E7%A0%81%EF%BC%9A82z9

**Comment by michaelowenliu** [comment]
https://github.com/PaddlePaddle/PaddleSeg/tree/develop/EISeg

**Comment by haoyuying** [comment]
在develop分支中已经更新链接。
