### ISSUE TITLE
EISeg 模型及参数问题

### ISSUE THREAD

**Issue by gxqnba** [PaddlePaddle/PaddleSeg#1382]
1、EISeg是否支持更多的模型如：U-Net等？
2、就HRNet18_OCR64模型而言，我能否自己采用该网络在我针对的数据集上训练得到权重文件，然后供EISeg调用。这样针对特定的数据集训练得到的参数拿来做特定数据交互式分割的效率和质量会不会更高。

**Comment by haoyuying** [comment]
您好，目前我们提供的代码只用于预测，不足以让您根据自己的数据集进行训练，因为训练过程涉及模拟交互点击采点等方面，较为复杂，今年我们有计划开源训练代码，到时候您可以根据训练代码训练自己的模型。请持续关注eiseg的发展动态。
