### ISSUE TITLE
predict file not parsing --custom_color

### ISSUE THREAD

**Issue by AKMourato** [PaddlePaddle/PaddleSeg#1386]
Greetings,
running:
```
python predict.py --config unet.yml --model_path output/unet-newsetup/best_model/model.pdparams --image_path /home/amourato/VM/New_COCO_DPD2011/train/images/2011111519.png --save_dir output/unet-fulldata/result2 --custom_color 0 0 0 255 255 255
```
got:
```
usage: predict.py [-h] [--config CFG]
                  [--model_path MODEL_PATH]
                  [--image_path IMAGE_PATH]
                  [--save_dir SAVE_DIR]
                  [--aug_pred]
                  [--scales SCALES [SCALES ...]]
                  [--flip_horizontal]
                  [--flip_vertical] [--is_slide]
                  [--crop_size CROP_SIZE CROP_SIZE]
                  [--stride STRIDE STRIDE]
predict.py: error: unrecognized arguments: --custom_color 0 0 0 255 255 255
```
Thus, not defined as arguments as stated in the docs.

-> Btw, with this colour pallete we get the "added_prediction" file without having applied any overlap colour to the background (i.e: only applying to the classes maintaining the background as the original image)?

**Edit**:
yes, apparently you removed this argument from the script.
https://github.com/PaddlePaddle/PaddleSeg/blob/e7f415db17e1bb8a9e8f9940c9e57c749709d97f/paddleseg/core/predict.py#L39-L53

How can I get a workaround of the background pseudo_color?

Thanks

**Comment by LutaoChu** [comment]
Thank you for your feedback.

Custom color map is a new feature of the develop branch. We have deleted the corresponding documents in version 2.2,
you can use `git checkout develop` to use custom color map.

> -> Btw, with this colour pallete we get the "added_prediction" file without having applied any overlap colour to the background (i.e: only applying to the classes maintaining the background as the original image)?

Yes, you can set a color other than 0 for the background

**Comment by AKMourato** [comment]
Solved, thanks.
