### ISSUE TITLE
Dice Coefficient & mAP

### ISSUE THREAD

**Issue by AKMourato** [PaddlePaddle/PaddleSeg#1389]
Greetings,

I noticed that you just defined mIoU, accuracy and kappa for segmentation metrics.
Mean average precision(mAP), recall, F1-score and dice coefficient would be more appropriate than accuracy and kappa, why not include as well?

**Edit**:
Suggestion:
The inclusion of the following losses would also be a good add-on:
- Tversky loss
- Focal Tversky loss
- log-cosh dice loss
Check:
[https://arxiv.org/pdf/2006.14822.pdf](url)
https://github.com/shruti-jadon/Semantic-Segmentation-Loss-Functions

Cheers

**Comment by AKMourato** [comment]
Hi @LutaoChu, do you intend to integrate these metrics soon?

**Comment by LutaoChu** [comment]
Hi，thank you for your advice. Miou is the most common segmentation indicator. I haven't seen mean average precision (map), recall and F1 score used in segmentation tasks, except Dice coefficient used in medical segmentation. If you have seen it, can you provide the corresponding literature? We will consider whether to integrate.

**Comment by AKMourato** [comment]
Hi @LutaoChu. Yes mIoU is the most standard for sure and dice coef. is more used in medical segmentation.
Altough the other metrics are widely used as well in known segmentation challenges.
Regarding different types of applications, certain metrics are more adequate than others, that's why I suggest including those ones as well.
Please take a look here:
- https://towardsdatascience.com/image-segmentation-choosing-the-correct-metric-aa21fd5751af
- https://arxiv.org/pdf/2010.09907.pdf

Implementations:
- https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/core/evaluation/metrics.py
- https://github.com/qubvel/segmentation_models.pytorch/blob/master/segmentation_models_pytorch/utils/metrics.py
- https://www.kaggle.com/yassinealouini/all-the-segmentation-metrics
- https://pytorch.org/ignite/master/metrics.html

Thanks

**Comment by LutaoChu** [comment]
Thank you for the information provided. We are planning to implement them, except map. MAP is indicator of instance segmentation, and you should be able to find them in paddedetection

**Comment by AKMourato** [comment]
Yes I meant precision instead of mean average precision (mAP), as you in fact need it to calculate F1 score. Thank you @LutaoChu. Nice work

**Comment by AKMourato** [comment]
hi @LutaoChu. When do you guys plan to add, precision, recall and F1 score?
Thank you

**Comment by LutaoChu** [comment]
We plan to add these indicators in the new version. You are also welcome to contribute code to us if you are interested in developing these indicators

**Comment by pushpendra9950** [comment]
@LutaoChu  When do you guys plan to add,  F1 score?
Thank you
