### ISSUE TITLE
Unet3+ model not configured to load weights

### ISSUE THREAD

**Issue by AKMourato** [PaddlePaddle/PaddleSeg#1391]
Hey guys,

I noticed that, contrary to all unet versions, I can't load pre-trained weights directly to the Unet3+, do you have any workaround?

Thanks

**Comment by michaelowenliu** [comment]
@AKMourato Hi, we have yet to provide the pre-trained weights of UNet3+. Sorry for that.

**Comment by AKMourato** [comment]
hi @michaelowenliu, thanks. More importantly than the pre-trained weights now is perhaps the argument to load weights since I've to run from scratch every I use it.
Cheers
