### ISSUE TITLE
why??

### ISSUE THREAD

**Issue by lin-lai** [PaddlePaddle/PaddleSeg#1392]
ValueError: mode should be 'train', 'val' or 'test', but got trainaug.

**Comment by michaelowenliu** [comment]
@lin-lai Hi, what is your question?

**Comment by lin-lai** [comment]
why is the loss always 0?

**Comment by lin-lai** [comment]
Due of use paddleseg,so I don't change the criterion

**Comment by michaelowenliu** [comment]
@lin-lai Hi, which model are you using?

**Comment by lin-lai** [comment]
DeepLabV3P

**Comment by michaelowenliu** [comment]
@lin-lai VOC dataset?
