### ISSUE TITLE
模型耗时问题

### ISSUE THREAD

**Issue by wangyuan111** [PaddlePaddle/PaddleSeg#1399]
我测试了deeplabv3+和BiSeNetv2的耗时，使用脚本train.py训练后直接用predict.py测试前向推理耗时，在我的数据上，deeplabv3+（resnet50）耗时25毫秒，BiSeNetv2耗时19毫秒。deeplabv3+耗时耗时比较正常，BiSeNetv2耗时太多了。按照[模型性能](https://github.com/PaddlePaddle/PaddleSeg/tree/develop/configs)中的说明BiSeNetv2应该比deeplabv3+耗时少一个量级。
这个页面下的模型耗时 batchsize是多少 是否半精度 有没有对模型压缩

**Comment by wuyefeilin** [comment]
利用导出模型进行测试哈， 具体参考链接 https://github.com/PaddlePaddle/PaddleSeg/blob/develop/docs/deployment/inference/python_inference.md 。 在测试的时候通过--benchmark输出相应信息即可查看性能

**Comment by wangyuan111** [comment]
谢谢，使用部署脚本 速度快了一倍以上。
再问一个问题   部署时主要做了哪些优化速度提高

**Comment by wuyefeilin** [comment]
部署时会对一些算子做融合处理，提升性能哈
