### ISSUE TITLE
部署时运行五分钟就会卡住不动

### ISSUE THREAD

**Issue by xliu79** [PaddlePaddle/PaddleSeg#1400]
部署分割模型时候 运行几分钟后就卡在 self.predictor.run()这个位置
其中模型用的deeplabv3
![捕获](https://user-images.githubusercontent.com/31554245/135016026-f1348863-6aea-4bcb-9a0f-ebbc0a68a196.PNG)
![捕获](https://user-images.githubusercontent.com/31554245/135016086-2696ac3f-bef7-4756-ac67-db0484fe2f2b.PNG)

**Comment by xliu79** [comment]
检测几张图片就会卡在self.predictor.run()

**Comment by wuyefeilin** [comment]
如果其他图片正常的话， 可能是因为这张图片导致的问题，比如图片过大

**Comment by xliu79** [comment]
@wuyefeilin 我用的同一张图片循环测试的。

**Comment by wuyefeilin** [comment]
查看一下数据获取是否正常
![image](https://user-images.githubusercontent.com/30919197/136492211-3876e6bc-b5ef-4ce4-8ae5-331ef903120a.png)
