### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by key-1994** [PaddlePaddle/PaddleSeg#141]
电脑并没有GPU，将batch_size设置成2会报这个错误
AssertionError: BATCH_SIZE:2 not divisble by number of GPUs:4
求教？

**Comment by ZeyuChen** [comment]
如果只有CPU，请不要使用大模型训练，推荐使用DeepLab-mobilenet模型，比较小。
另外请试试将BATCH_SIZE设置为4，这里读取到的是CPU和核数。

**Comment by key-1994** [comment]
好的，感谢！
