### ISSUE TITLE
训练过程中提示Found inf or nan,current scale is: 0.0,decrease to: 0.0*0.5

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/PaddleSeg#1412]
请问训练过程中出现很多提示
Found inf or nan,current scale is: 0.0,decrease to: 0.0*0.5
是什么原因呢

![-9c667de3e0150d6](https://user-images.githubusercontent.com/36887207/135230298-1d2d02b7-e3ef-41f6-b308-a36af2a278ac.png)

**Comment by haoyuying** [comment]
说明训练过程的某一步出现了除0等非法操作，建议定位下训练数据集处理和损失函数计算部分是不是出现了除0等非法操作

**Comment by huilin16** [comment]
好的，谢谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月29日(星期三) 晚上6:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] 训练过程中提示Found inf or nan,current scale is: 0.0,decrease to: 0.0*0.5 (#1412)





 
说明训练过程的某一步出现了除0等非法操作，建议定位下训练数据集处理和损失函数计算部分是不是出现了除0等非法操作
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
