### ISSUE TITLE
自己用paddleseg训练的模型，用c++paddle inference库部署到jetson nx 上后怎么看部署性能呢，比如预测时间    等等之类。

### ISSUE THREAD

**Issue by huangwan-jiayi** [PaddlePaddle/PaddleSeg#1414]
这样在run代码前后加计算时间的代码可以测出推理的时间吗？
![image](https://user-images.githubusercontent.com/71338215/135374777-2f1ad5c4-0f1b-4ab4-83dc-c40b818171d3.png)

**Comment by shiyutang** [comment]
你的问题我们已经收到登记，将尽快安排相关人员解决。
