### ISSUE TITLE
我使用工业表盘分割模型显卡是单块1080Ti显卡，推理速度只有两秒一张

### ISSUE THREAD

**Issue by siyangbing** [PaddlePaddle/PaddleSeg#142]
W1231 10:56:15.739400  3785 device_context.cc:235] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.0
W1231 10:56:15.741755  3785 device_context.cc:243] device: 0, cuDNN Version: 7.3.
W1231 10:56:15.741771  3785 device_context.cc:269] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.4, but CUDNN version in your machine is 7.3, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
W1231 10:56:16.498123  3785 naive_executor.cc:43] The NaiveExecutor can not work properly if the cmake flag ON_INFER is not set.
W1231 10:56:16.498152  3785 naive_executor.cc:45] Unlike the training phase, all the scopes and variables will be reused to save the allocation overhead.
W1231 10:56:16.498155  3785 naive_executor.cc:48] Please re-compile the inference library by setting the cmake flag ON_INFER=ON if you are running Paddle Inference

W1231 10:56:27.539149  3785 naive_executor.cc:43] The NaiveExecutor can not work properly if the cmake flag ON_INFER is not set.
W1231 10:56:27.539177  3785 naive_executor.cc:45] Unlike the training phase, all the scopes and variables will be reused to save the allocation overhead.
W1231 10:56:27.539180  3785 naive_executor.cc:48] Please re-compile the inference library by setting the cmake flag ON_INFER=ON if you are running Paddle Inference

**Comment by LielinJiang** [comment]
请问你输入的图片大小是多大的？如果对速度有要求的话，建议缩小图片输入尺寸，或者用deeplab +mobilenet模型。后续我们会提供更快的模型。

**Comment by siyangbing** [comment]
我使用的是960*720的jpg图片，我发现在进行推断时采用导出的模型速度反而变慢了（我使用自己的表盘数据集训练的）。在进行推断时代码显示已安装的Paddle是使用CUDNN 7.4编译的，但是您计算机上的CUDNN版本是7.3，这可能会导致严重的不兼容的错误。请使用兼容的CUDNN版本重新编译或重新安装Paddle。但是代码可以运行，结果也正常。这合理吗？

**Comment by siyangbing** [comment]
我使用的是960 * 720的jpg图片，我发现在进行分解时采用转换的模型速度反而变慢了（我使用自己的表盘数据集训练的）。在进行时时代码显示已安装的Paddle是使用CUDNN 7.4编译的，但是您计算机上的CUDNN版本是7.3，这可能会导致严重的不兼容的错误。请使用兼容的CUDNN版本重新编译或重新安装Paddle。但是代码可以运行，结果也正常。这合理吗？@LielinJiang

**Comment by LielinJiang** [comment]
> W1231 10:56:15.739400 3785 device_context.cc:235] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.0
> W1231 10:56:15.741755 3785 device_context.cc:243] device: 0, cuDNN Version: 7.3.
> W1231 10:56:15.741771 3785 device_context.cc:269] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.4, but CUDNN version in your machine is 7.3, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
> W1231 10:56:16.498123 3785 naive_executor.cc:43] The NaiveExecutor can not work properly if the cmake flag ON_INFER is not set.
> W1231 10:56:16.498152 3785 naive_executor.cc:45] Unlike the training phase, all the scopes and variables will be reused to save the allocation overhead.
> W1231 10:56:16.498155 3785 naive_executor.cc:48] Please re-compile the inference library by setting the cmake flag ON_INFER=ON if you are running Paddle Inference
> 
> W1231 10:56:27.539149 3785 naive_executor.cc:43] The NaiveExecutor can not work properly if the cmake flag ON_INFER is not set.
> W1231 10:56:27.539177 3785 naive_executor.cc:45] Unlike the training phase, all the scopes and variables will be reused to save the allocation overhead.
> W1231 10:56:27.539180 3785 naive_executor.cc:48] Please re-compile the inference library by setting the cmake flag ON_INFER=ON if you are running Paddle Inference

cudnn 那个版本不一致如果程序可以正常运行可以暂时忽略，后面inference library的warning在使用native executor的情况下也没什么问题。之前我们这边测试769x769的输入在k40上也需要600+ms。

**Comment by siyangbing** [comment]
我改了输入图片尺寸，目前在1080ti上可以达到400ms,百度有计划提供可以在移动终端运行推理的图像分割教程吗。我想要在终端上运行推理程序@LielinJiang

**Comment by LielinJiang** [comment]
> 我改了输入图片尺寸，目前在1080ti上可以达到400ms,百度有计划提供可以在移动终端运行推理的图像分割教程吗。我想要在终端上运行推理程序@LielinJiang
暂时没有分割相关的终端教程，https://github.com/PaddlePaddle/Paddle-Lite-Demo ， 这里有分类和检测的推理教程，可以先参考一下。

**Comment by siyangbing** [comment]
我想问一下百度为南方电网做的这个模型，最后推断的时候是部署在巡航小车上还是小车返回图像给服务器推断。是采用拍照，还是视频流检测。南方电网的读电表显示对延迟有没有要求。@LielinJiang

**Comment by LielinJiang** [comment]
> 我想问一下百度为南方电网做的这个模型，最后推断的时候是部署在巡航小车上还是小车返回图像给服务器推断。是采用拍照，还是视频流检测。南方电网的读电表显示对延迟有没有要求。@LielinJiang

部署在小车上的，用的tx2的板子，应该是拍照把，这个不是太清楚，我们只是部署服务。当时的延迟是满足要求的把。

**Comment by ZeyuChen** [comment]
@siyangbing 能否提供下您更多的企业信息和场景需求？或者加一下QQ 85559911我们沟通下相关需求？

**Comment by LiKangyuLKY** [comment]
> > 我想问一下百度为南方电网做的这个模型，最后推断的时候是部署在巡航小车上还是小车返回图像给服务器推断。是采用拍照，还是视频流检测。南方电网的读电表显示对延迟有没有要求。@LielinJiang
> 
> 部署在小车上的，用的tx2的板子，应该是拍照把，这个不是太清楚，我们只是部署服务。当时的延迟是满足要求的把。

您好，我最近有个表盘巡检的项目，之前一直用tf做，这次准备换成飞桨试试，方便加个微信吗（18500485183）？想跟您这边详细了解一下百度之前的案例

**Comment by ZeyuChen** [comment]
@LiKangyuLKY 好的，我让我们的PM同学跟您联系，我们拉群沟通。

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。
