### ISSUE TITLE
cityscapes-sota

### ISSUE THREAD

**Issue by kyeongjunJang** [PaddlePaddle/PaddleSeg#1420]
https://github.com/PaddlePaddle/PaddleSeg/tree/dd6e03c138f7183ed4b005bf1979ea3b9cc8fc13/contrib/CityscapesSOTA#cityscapes-sota

**Convert autolabelled data** 
|--convert_autolabelled
|  |--augsburg
|  |--bayreuth
|  |--...

**Then download Autolabelled-Data from google drive**
refinement_final_v0.zip

How make refinement final file for custom dataset?

i want autolaebelled data of custom dataset

**Comment by LutaoChu** [comment]
The autolabelled data comes from Refinement_final_v0.zip. You should download refinement_final_v0.zip and decompress it, then rename it as convert_autolabelled, and finally make sure the directory structure is the same as the one above

**Comment by kyeongjunJang** [comment]
yeah i got convert_autolabelled for cityscapes dataset. but it is only semantic segmentation image file.
but i want get a convert_autolabelled json file.

because For my custom dataset

**Comment by LutaoChu** [comment]
I see, but I haven't converted the JSON file. You may refer to this.
https://blog.csdn.net/francislucien2017/article/details/90407093

**Comment by kyeongjunJang** [comment]
thank you

**Comment by marshall-dteach** [comment]
> The autolabelled data comes from Refinement_final_v0.zip. You should download refinement_final_v0.zip and decompress it, then rename it as convert_autolabelled, and finally make sure the directory structure is the same as the one above

ahhh... I think that the rename operation is false, the true method is run the convert_cityscapes_autolabeling.py to generate the convert_autolabelled
