### ISSUE TITLE
BiseNetV2转换成.nb在Edgeboard部署效果极差

### ISSUE THREAD

**Issue by JiehangXie** [PaddlePaddle/PaddleSeg#1424]
![111](https://user-images.githubusercontent.com/51190264/136561960-6986ca6d-58fe-451b-b191-d8ff0f402b86.JPG)

模型是用文档里面提供的BisenetV2动态模型文件转静态图再转.nb的

**Comment by JiehangXie** [comment]
已解决，问题是输入图像未归一化！

**Comment by X-MingYang** [comment]
您好，能不能请问一下您是如何将导出的静态图部署至edgeboard上的？

**Comment by JiehangXie** [comment]
PaddleLite



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月20日(周三) 晚上6:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleSeg] BiseNetV2转换成.nb在Edgeboard部署效果极差 (#1424)




 
您好，能不能请问一下您是如何将导出的静态图部署至edgeboard上的？

**Comment by X-MingYang** [comment]
请问是将paddleseg中训练好的模型直接使用export.py导出的inference_model文件用paddlelite的opt转发为arm的格式进行部署吗？在转换的时候，这个模型是属于combined model还是uncombined model呢？
另外想请问部署到edgeboard以后是自动支持了对视频流的实时推理吗？
感谢您的回复！

**Comment by JiehangXie** [comment]
paddleseg导出静态图模型，paddlelite将静态图模型转换成.nb格式的模型文件



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月21日(周四) 上午10:34
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleSeg] BiseNetV2转换成.nb在Edgeboard部署效果极差 (#1424)




 
请问是将paddleseg中训练好的模型直接使用export.py导出的inference_model文件用paddlelite的opt转发为arm的格式进行部署吗？在转换的时候，这个模型是属于combined model还是uncombined model呢？
 另外想请问部署到edgeboard以后是自动支持了对视频流的实时推理吗？
 感谢您的回复！

**Comment by X-MingYang** [comment]
好的，谢谢您，另外能再请问一下您当时用的是哪个版本的edgeboard吗？

**Comment by X-MingYang** [comment]
> 好的，谢谢您，另外能再请问一下您当时用的是哪个版本的edgeboard吗？

另外想请问您当时借鉴了哪篇文档呢？不知道您能否分享一下您当时的资料？不胜感激！
