### ISSUE TITLE
SFNet's entry in the model zoo seems wrong

### ISSUE THREAD

**Issue by RolandGao** [PaddlePaddle/PaddleSeg#1425]
In the model zoo (https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.2/configs), SFNet's entry looks like the following:

SFNet | ResNet18_OS8 | 1024x1024 | 80000 | 81.49% | 81.63% | 81.85% | 28

However, when I go to the SFNet specific page(https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.2/configs/sfnet), I get

SFNet | ResNet18_OS8 | 1024x1024 | 80000 | 78.31% | 78.99% | 79.29%
SFNet | ResNet50_OS8 | 1024x1024 | 80000 | 81.49% | 81.63% | 81.85%

So in the model zoo, the entry claims that the backbone is ResNet18_OS8 but reports the accuracies of ResNet50_OS8. I think this is a problem.

**Comment by haoyuying** [comment]
Thank you for your suggestion, we will revise the document as soon as possible.

**Comment by RolandGao** [comment]
Hi, thank you for getting back to my issue so quickly!

I'm not sure if you have realized this already, but I think the predict_time(ms) column of SFNet has some problems too. ResNet18_OS8's predict_time has the potential to be 28ms, but ResNet50_OS8 definitely needs more than 28ms. For example, Deeplabv3P with ResNet50_OS8 runs at 157ms. 

This issue also affects the graph above the big chart.

**Comment by haoyuying** [comment]
Thanks for your kindly reminder.
