### ISSUE TITLE
请问论文EdgeFlow: Achieving Practical Interactive Segmentation with Edge-Guided Flow中提出的算法的源码在哪里可以看到

### ISSUE THREAD

**Issue by cccccccyj** [PaddlePaddle/PaddleSeg#1426]
@haoyuying ，您好，论文EdgeFlow: Achieving Practical Interactive Segmentation with Edge-Guided Flow中提出的算法的源码在工程的哪个位置可以找到？

**Comment by haoyuying** [comment]
您好，edgeflow的预测代码将在eiseg0.4.0放出，预计时间为十一月底，敬请期待。
