### ISSUE TITLE
How to get correct prediction classes.

### ISSUE THREAD

**Issue by fsultana44** [PaddlePaddle/PaddleSeg#1433]
I am testing the semantic segmentation using my custom data set, and the dataset has two classes(particle and crack). I modified the config file in the file **_quick_start/bisenet_optic_disc_512x512_1k.yml._** to train and tested the model, but wondering to see the prediction result does not provide the correct classes prediction, it's  give  only one class label in the  _added_prediction_ and _pseudo colour prediction_  results. I also tested with the BiSeNetV2 model and got the same prediction result.
**How can I get the correct prediction result with three classes(including background)?**
 Here I have given some relevant snippets.

![confi_modify](https://user-images.githubusercontent.com/51081858/136916100-a6e5b397-6ea8-499f-94b5-ddb7ee68cd5e.PNG)

**Comment by wuyefeilin** [comment]
Is your dataset annotated as required. Maybe you can show it to me so I can judge.

**Comment by fsultana44** [comment]
I annotated the dataset using the LabelMe tools, followed the [instructions](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/docs/data/transform/transform.md), and split the dataset using the `python tools/split_dataset_list.py <dataset_root> images annotations-split 0.6 0.2 0.2 --format jpg png`. I followed the  [procedure](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/docs/data/marker/marker.md) up to  4.2 and did not **4.3 and 4.4**.
After that I got the dataset directory look like that
```
Mparti
    |
    |--images
    |  |--image1.jpg
    |  |--image2.jpg
    |  |--...
    |
    |--annotations
    |  |--image1.png
    |  |--image1.png
    |  |--...
    |
    |--labels.txt
    |--train.txt
    |
    |--val.txt
    |
    |--test.txt
```
Here is the example of my annotations png images

**Comment by AKMourato** [comment]
@fsultana44 check if the pixel value of that class is 255. If it is, it's being neglected by paddleseg by default.
Replace all the pixel values in every image with another value, and then if you wish, run the pseudo colour generation, but it's not necessary.

**Comment by wuyefeilin** [comment]
The pixel values of the three classes should be 0, 1, 2.

**Comment by fsultana44** [comment]
The original custom data that I used for annotating in the LabelMe tool is the single-channel images with pixel value [0,255]. I run the script  python `tools/labelme2seg.py <PATH/TO/LABEL_JSON_FILE>` on the annotated images and I got the label images in png format with three-pixel values for three classes 0,1,2 for background, and two other class, respectively. I wonder that some of the label images do not show all of the one specific class; some labels of one one class visible in the images, and some are not in the label png images. 
Is this problem arises for that reason? If so, then how to solve it?
or
Do I need to change pixel value of the original images pixel value before annotating?

**Comment by AKMourato** [comment]
@fsultana44 well I don't think it is done properly, probably is the labelme2seg script that has some error or you are not doing something correctly.

I suggest you to loop through your dataset replacing the 1 and 2 pixel values with some other (e.g: 100, 200) and plot some images to have some visual clue about what is happening. The problem should be in your label generation, or the post-processing with labelme2seg.
