### ISSUE TITLE
请问点击实现目标轮廓的分割的机理是什么？

### ISSUE THREAD

**Issue by ty199931** [PaddlePaddle/PaddleSeg#1435]
你好，我在读代码的过程中，想要了解，我们感兴趣的物体需要在界面上点击一下进行分割，我想了解一下这个点击的作用，是怎么样实现只对点击的物体进行分割呢？因为我们正常训练的神经网络模型在导入后，是对点击的地方进行了区域提取然后放到神经网络模型中进行预测了还是什么机理呢？有点看不太懂，请求解答

**Comment by haoyuying** [comment]
您好，这个机制是在训练当中让网络适应的，在训练中从gt随机找出出一个或多个instance，然后然后在该instance上通过不同的机制进行样点采集和训练，可以看下交互式分割相关的论文了解具体的内容。

**Comment by ty199931** [comment]
你好，我看了好几篇相关的论文，也大概明白您说的什么意思，但我认真读了eiseg的代码，我看之前论文提到的都是生成了一个四维的输入影像，但是在这个代码上没有很明确的看出来输入的影像是四维的，但是好像对于gt有处理，利用高斯分布形成了热力图，但我觉得如果只是对gt进行了高斯分布的话，不太现实哇，不是应该同时对输入的影像和gt做一样的变换吗?
另外就是训练过程中的点是随机生成随机分布进行训练的吗?那我们实际上交互界面上点的点就是将输入影像多加了一个维度，导致最后生成的是针对该物体的分割结果吗?
最后一个问题，我在贵公司开放的公开课上看到您说的交互是运用了一种TRIM算法(可能名字没记住打错了)，但我在百度上查找了，什么都找不到，请问这个算法可以在哪里有介绍吗?请问这个有论文吗?感觉很多我都理解的不是很清楚哎，
如果能够解答疑惑，不胜感激，想去交互领域占个坑

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月13日(周三) 上午10:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleSeg] 请问点击实现目标轮廓的分割的机理是什么？ (#1435)




 
您好，这个机制是在训练当中让网络适应的，在训练中从gt随机找出出一个或多个instance，然后然后在该instance上通过不同的机制进行样点采集和训练，可以看下交互式分割相关的论文了解具体的内容。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
