### ISSUE TITLE
EISeg标注文件以Paddlex调用的问题

### ISSUE THREAD

**Issue by CashBai** [PaddlePaddle/PaddleSeg#1437]
有没有内置指令，可以直接把EISeg生成的标注文件转化成Paddlex能直接用的标注格式？

**Comment by haoyuying** [comment]
目前没有,eiseg保存格式包括伪彩色，灰度图像，单图json格式和coco的标注格式，其中灰度图像可以用paddleseg或paddlex来直接训练。
PaddleX的语义分割要求的数据集格式说明： https://github.com/PaddlePaddle/PaddleX/blob/release/2.0.0/docs/data/format/segmentation.md
在EISeg上标注数据时选择将标注文件输出为灰度图像，参考前述文档链接修改图片和标注文件的文件夹名称，后参考文档 https://github.com/PaddlePaddle/PaddleX/blob/release/2.0.0/docs/data/split.md 
划分训练集/验证集即可
