### ISSUE TITLE
Cityscapes SOTA

### ISSUE THREAD

**Issue by kyeongjunJang** [PaddlePaddle/PaddleSeg#1438]
https://github.com/PaddlePaddle/PaddleSeg/tree/dd6e03c138f7183ed4b005bf1979ea3b9cc8fc13/contrib/CityscapesSOTA

I want to train custom datasets.

When I tried it, This Network need only original image and labelid image, not polygon json file.

I have custom dataset
it have original image and polygon json file.
how to train this dataset? or how to convert polygon json file to lebelid img file

**Comment by LutaoChu** [comment]
You can refer to this [tutorial](https://github.com/PaddlePaddle/PaddleSeg/blob/develop/docs/data/transform/transform.md#1labelme), which describes how to convert the JSON file generated by labelme into LabelID img.
Corresponding [script](https://github.com/PaddlePaddle/PaddleSeg/blob/develop/tools/labelme2seg.py).
