### ISSUE TITLE
bisenetv2分割错误。

### ISSUE THREAD

**Issue by lpt-hub** [PaddlePaddle/PaddleSeg#1442]
针对bisenetv2第一次分割出错的地方，特意在样本中新添加了30多张分割错误相关的图像，训练后测试还是会在那个地方分割错误？什么原因？

**Comment by juncaipeng** [comment]
这说明bad case还是没有学习到。
你总共数据集多少啊？可以再加大bad case的图片数量。

**Comment by lpt-hub** [comment]
> 这说明bad case还是没有学习到。 你总共数据集多少啊？可以再加大bad case的图片数量。

数据集共540张，训练集合验证集是9:1。数据集是不是太少？bad case大概应该添加多少？

**Comment by juncaipeng** [comment]
嗯，数据集是相对来说比较小的。bad case数据集当然是越多越好，没有一个通常的定论。

还有一种方法是使用分割能力更强的模型，bisnetv2速度较快，但是精度中等。

**Comment by lpt-hub** [comment]
> 嗯，数据集是相对来说比较小的。bad case数据集当然是越多越好，没有一个通常的定论。
> 
> 还有一种方法是使用分割能力更强的模型，bisnetv2速度较快，但是精度中等。

好的，谢谢啦，我试下。
