### ISSUE TITLE
恢复训练时出现问题/there is an error when I resume training: local variable 'images' referenced before assignment

### ISSUE THREAD

**Issue by Xin-Lee** [PaddlePaddle/PaddleSeg#1446]
Today when I try to retrain the previous model, the following errors occurred:

------------Environment Information-------------
platform: Windows-10-10.0.19042-SP0
Python: 3.8.11 (default, Aug  6 2021, 09:57:55) [MSC v.1916 64 bit (AMD64)]
Paddle compiled with cuda: True
NVCC: Not Available
cudnn: 8.1
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: NVIDIA GeForce']
PaddlePaddle: 2.1.3
OpenCV: 4.5.1
------------------------------------------------
2021-10-18 20:17:42 [INFO]
---------------Config Information---------------
batch_size: 2
iters: 20000
loss:
  coef:
  - 1
  types:
  - ignore_index: 255
    type: CrossEntropyLoss
lr_scheduler:
  end_lr: 0
  learning_rate: 0.01
  power: 0.9
  type: PolynomialDecay
model:
  align_corners: true
  aspp_out_channels: 256
  aspp_ratios:
  - 1
  - 12
  - 24
  - 36
  backbone:
    multi_grid:
    - 1
    - 2
    - 4
    output_stride: 8
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet101_vd_ssld.tar.gz
    type: ResNet101_vd
  backbone_indices:
  - 0
  - 3
  num_classes: 2
  pretrained: null
  type: DeepLabV3P
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 4.0e-05
train_dataset:
  dataset_root: data/model1
  mode: train
  num_classes: 2
  train_path: data/model1/train.txt
  transforms:
  - max_scale_factor: 2.0
    min_scale_factor: 0.25
    scale_step_size: 0.25
    type: ResizeStepScaling
  - crop_size:
    - 1024
    - 1024
    type: RandomPaddingCrop
  - type: RandomHorizontalFlip
  - brightness_range: 0.5
    contrast_range: 0.5
    saturation_range: 0.5
    type: RandomDistort
  - target_size:
    - 480
    - 480
    type: Resize
  - type: Normalize
  type: Dataset
val_dataset:
  dataset_root: data/model1
  mode: val
  num_classes: 2
  transforms:
  - target_size:
    - 480
    - 480
    type: Resize
  - type: Normalize
  type: Dataset
  val_path: data/model1/val.txt
------------------------------------------------
W1018 20:17:42.761476 18876 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.4, Runtime API Version: 11.2
W1018 20:17:42.761476 18876 device_context.cc:422] device: 0, cuDNN Version: 8.1.
2021-10-18 20:17:44 [INFO]      Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/resnet101_vd_ssld.tar.gz
2021-10-18 20:17:45 [INFO]      There are 530/530 variables loaded into ResNet_vd.
2021-10-18 20:17:45 [INFO]      Resume model from output/model1/iter_20000
Traceback (most recent call last):
  File "train.py", line 190, in <module>
    main(args)
  File "train.py", line 169, in main
    train(
  File "C:\MyData\Documents\pythonProject\muzhisuAI\paddleseg\core\train.py", line 303, in train
    _, c, h, w = images.shape
UnboundLocalError: local variable 'images' referenced before assignment

The error only appeared when resume train, train from the beginning is ok.

**Comment by Xin-Lee** [comment]
Addition: my another model doesn't have this error when resume train.

**Comment by juncaipeng** [comment]
In "C:\MyData\Documents\pythonProject\muzhisuAI\paddleseg\core\train.py", the images is a variable, which is not loaded from resume model.

You can update paddleseg to release 2.3 or delete the following lines in "C:\MyData\Documents\pythonProject\muzhisuAI\paddleseg\core\train.py".
![image](https://user-images.githubusercontent.com/52520497/137833790-1e2bfbe0-b72d-4c03-b3c8-c8eeca7f0206.png)

**Comment by Xin-Lee** [comment]
I update to v2.3 but the error still exists, and when I delete the relative lines, the program stopped without error report here:

W1019 11:28:20.975605 15120 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.4, Runtime API Version: 11.2
W1019 11:28:20.975988 15120 device_context.cc:422] device: 0, cuDNN Version: 8.1.
2021-10-19 11:28:22 [INFO]      Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/resnet101_vd_ssld.tar.gz
2021-10-19 11:28:24 [INFO]      There are 530/530 variables loaded into ResNet_vd.
2021-10-19 11:28:24 [INFO]      Resume model from output/model1/iter_20000

might it be the problem of my previous model?

**Comment by wuyefeilin** [comment]
Do you train over? If over, It makes no sense to resume.

**Comment by Xin-Lee** [comment]
> Do you train over? If over, It makes no sense to resume.

oh, thank you very much I forgot it, sorry for my stupid question.....
