### ISSUE TITLE
半监督分割方法的集成

### ISSUE THREAD

**Issue by TimZhang001** [PaddlePaddle/PaddleSeg#1448]
是否可以考虑增加一些半监督的分割方法，比如boxinst condinst DiscoBox等
这些基于box的标注方式来进行分割可以很好的节省标注时间

**Comment by michaelowenliu** [comment]
@TimZhang001 Hi, did you try our EISeg? https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.3/EISeg
