### ISSUE TITLE
paddlepaddle是否支持qml?

### ISSUE THREAD

**Issue by jsxyhelu** [PaddlePaddle/PaddleSeg#145]
作为qt程序员，我想咨询一下paddlepaddle是否支持qml?
如果支持，有哪些资料？
如果不支持，有哪些建议？是否有这方面的考虑？
非常感谢！

**Comment by ZeyuChen** [comment]
@jsxyhelu 能否提供下具体的使用场景，需要PaddleSeg在哪些场景进行视觉GUI的可配置化开发呢？

**Comment by jsxyhelu** [comment]
是这样的，我们使用qml进行android类程序图像处理程序设计，语义分割是我们非常想集成的一个功能，但是由于之前工具链使用的都是QT，所以想了解游戏啊paddlepaddle对这个方面是否有相关支持？非常感谢！
