### ISSUE TITLE
windows c++部署问题

### ISSUE THREAD

**Issue by gxqnba** [PaddlePaddle/PaddleSeg#1451]
我依照windows c++部署说明进行c++部署，成功生成了c++项目，然后生成对应的预测dll，在自己电脑上用python或者c#能成功调用该dll进行预测，但是换了台电脑就不行了，请问我该如何才能实现一台电脑部署，多台电脑都能调用，而不是每台电脑都要部署一次。

**Comment by juncaipeng** [comment]
推荐你再每台电脑上进行部署，这种方式是单机部署，通常比较简单。
如果一台电脑部署多台电脑调用，paddle提供paddle servering进行支持，但是这种方式比较繁琐。

参考资料：
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/docs/deployment/serving/serving.md
https://github.com/PaddlePaddle/Serving
