### ISSUE TITLE
关于matting测试效果，

### ISSUE THREAD

**Issue by zhanghongyong123456** [PaddlePaddle/PaddleSeg#1453]
这是我运行的命令
![image](https://user-images.githubusercontent.com/48466610/138219280-7562f79d-fef9-4672-a4e1-efe9b8fd0d8e.png)
这是结果
![image](https://user-images.githubusercontent.com/48466610/138219100-d1befc65-560a-49ad-9186-c958af3734fa.png)
这是我的测试，我想问一下，这个需要自己继续训练吗，为什么得到的结果会差这么多呢

**Comment by wuyefeilin** [comment]
可以试一下modnet_hrnet_w18，这个效果好一些哦。

这是我们开源的模型，你如果自己有数据集，可以基于我们开源的模型进行finetune，应用于自己的场合哈

**Comment by zhanghongyong123456** [comment]
> 可以试一下modnet_hrnet_w18，这个效果好一些哦。
> 
> 这是我们开源的模型，你如果自己有数据集，可以基于我们开源的模型进行finetune，应用于自己的场合哈

你好，我测试了你说的这个模型，得到这样的结果
![image](https://user-images.githubusercontent.com/48466610/139202795-17f1ead3-21e1-4ef9-85b0-1d5b259cec97.png)

![image](https://user-images.githubusercontent.com/48466610/139203058-45bd6163-b158-42da-afb5-dc025fcf253e.png)
这是运行命令，我不确定我是否哪里搞错了，期待您的回复

**Comment by zhanghongyong123456** [comment]
> 可以试一下modnet_hrnet_w18，这个效果好一些哦。
> 
> 这是我们开源的模型，你如果自己有数据集，可以基于我们开源的模型进行finetune，应用于自己的场合哈

对于这个文件configs\modnet\modnet_mobilenetv2.yml，更换了模型，这个yml文件是否也需要修改什么

**Comment by wuyefeilin** [comment]
![image](https://user-images.githubusercontent.com/30919197/139218135-afc4025d-fc1b-4011-800c-0d8dabd4246d.png)
--config 需要对应换一下

**Comment by zhanghongyong123456** [comment]
> ![image](https://user-images.githubusercontent.com/30919197/139218135-afc4025d-fc1b-4011-800c-0d8dabd4246d.png) --config 需要对应换一下

我没有找到对应的yml文件，这个在哪里下载

**Comment by wuyefeilin** [comment]
> > ![image](https://user-images.githubusercontent.com/30919197/139218135-afc4025d-fc1b-4011-800c-0d8dabd4246d.png) --config 需要对应换一下
> 
> 我没有找到对应的yml文件，这个在哪里下载

更新一下代码

**Comment by zhanghongyong123456** [comment]
> > > ![image](https://user-images.githubusercontent.com/30919197/139218135-afc4025d-fc1b-4011-800c-0d8dabd4246d.png) --config 需要对应换一下
> > 
> > 
> > 我没有找到对应的yml文件，这个在哪里下载
> 
> 更新一下代码

哦哦，新上传的哈

**Comment by zhanghongyong123456** [comment]
> > > ![image](https://user-images.githubusercontent.com/30919197/139218135-afc4025d-fc1b-4011-800c-0d8dabd4246d.png) --config 需要对应换一下
> > 
> > 
> > 我没有找到对应的yml文件，这个在哪里下载
> 
> 更新一下代码

![image](https://user-images.githubusercontent.com/48466610/139404330-bdfd2a05-1d95-42a8-812f-f30b7ba61ac8.png)
这是我刚刚测试的结果，效果还是有些不如意，我想知道模型迭代了多少次，如果我要微调这个模型，我是需要添加新的数据集或者是增加迭代的次数，我该考虑哪些方面呢，期待您的回复

**Comment by wuyefeilin** [comment]
针对你的应用场景， 准备一些数据集进行训练就可以了

**Comment by zhanghongyong123456** [comment]
> 针对你的应用场景， 准备一些数据集进行训练就可以了

您好我想达到头发丝级别的抠像，可以实现吗用咱们的这个训练代码，只要我有数据集

**Comment by wuyefeilin** [comment]
> > 针对你的应用场景， 准备一些数据集进行训练就可以了
> 
> 您好我想达到头发丝级别的抠像，可以实现吗用咱们的这个训练代码，只要我有数据集

妥妥的

**Comment by zhanghongyong123456** [comment]
> > > 针对你的应用场景， 准备一些数据集进行训练就可以了
> > 
> > 
> > 您好我想达到头发丝级别的抠像，可以实现吗用咱们的这个训练代码，只要我有数据集
> 
> 妥妥的

好的，我试试，谢谢指点

**Comment by yangy996** [comment]
hello，你训练跑通了吗？我有份2000多张的数据集，训练了好几天，sad和mse还是非常的高
![image](https://user-images.githubusercontent.com/15188456/141880701-c729c7f1-0b48-4d1e-af02-d265e4bffc7a.png)

**Comment by wuyefeilin** [comment]
可以尝试用不同的数据增强方式哈

**Comment by yangy996** [comment]
> 可以尝试用不同的数据增强方式哈

2100张数据集合成了2万张，数据集应该是够的，但效果很差就不知道怎么回事了

**Comment by wuyefeilin** [comment]
你在训练的数据增强RandomCrop前面增加一个ResizeByShort试试：
    - type: ResizeByShort
      short_size: 512

**Comment by yangy996** [comment]
> 你在训练的数据增强RandomCrop前面增加一个ResizeByShort试试： - type: ResizeByShort short_size: 512

这个可以，试了一份小数据集，评估值很快就下来了
感觉像是图太大了，随机裁剪尺寸太小了，导致训练出问题了

**Comment by zhanghongyong123456** [comment]
> > 你在训练的数据增强RandomCrop前面增加一个ResizeByShort试试： - type: ResizeByShort short_size: 512
> 
> 这个可以，试了一份小数据集，评估值很快就下来了 感觉像是图太大了，随机裁剪尺寸太小了，导致训练出问题了



> hello，你训练跑通了吗？我有份2000多张的数据集，训练了好几天，sad和mse还是非常的高 ![image](https://user-images.githubusercontent.com/15188456/141880701-c729c7f1-0b48-4d1e-af02-d265e4bffc7a.png)

我数据集还没做好呢，想做一个头发丝级别的，不太好做，你训练是直接单独用你自己的数据集，或者和公开的数据集混合一起使用。还是修改了模型，数据增强是手动的吗，还是里面已经增加了相关代码

**Comment by newjavaer** [comment]
> > 你在训练的数据增强RandomCrop前面增加一个ResizeByShort试试： - type: ResizeByShort short_size: 512
> 
> 这个可以，试了一份小数据集，评估值很快就下来了 感觉像是图太大了，随机裁剪尺寸太小了，导致训练出问题了

最后的可视化的图呢  怎么样

**Comment by yangy996** [comment]
> > > 你在训练的数据增强RandomCrop前面增加一个ResizeByShort试试： - type: ResizeByShort short_size: 512
> > 
> > 
> > 这个可以，试了一份小数据集，评估值很快就下来了 感觉像是图太大了，随机裁剪尺寸太小了，导致训练出问题了
> 
> 最后的可视化的图呢 怎么样

图暂时没有，你可以在PPM-100数据集上测试，按上面的修改就能正常训练了

**Comment by newjavaer** [comment]
就是说 最后的效果怎么样呢 sad能到paddlepaddle上的效果嘛



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月19日(星期五) 上午8:39
收件人: "PaddlePaddle/PaddleSeg";
抄送: "Comment";
主题: Re: [PaddlePaddle/PaddleSeg] 关于matting测试效果， (Issue #1453)





    
你在训练的数据增强RandomCrop前面增加一个ResizeByShort试试： - type: ResizeByShort short_size: 512
  
这个可以，试了一份小数据集，评估值很快就下来了 感觉像是图太大了，随机裁剪尺寸太小了，导致训练出问题了
  
最后的可视化的图呢 怎么样
  
图暂时没有，你可以在PPM-100数据集上测试，按上面的修改就能正常训练了
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yangy996** [comment]
> 就是说 最后的效果怎么样呢 sad能到paddlepaddle上的效果嘛
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年11月19日(星期五) 上午8:39 收件人: "PaddlePaddle/PaddleSeg"; 抄送: "Comment"; 主题: Re: [PaddlePaddle/PaddleSeg] 关于matting测试效果， (Issue #1453) 你在训练的数据增强RandomCrop前面增加一个ResizeByShort试试： - type: ResizeByShort short_size: 512 这个可以，试了一份小数据集，评估值很快就下来了 感觉像是图太大了，随机裁剪尺寸太小了，导致训练出问题了 最后的可视化的图呢 怎么样 图暂时没有，你可以在PPM-100数据集上测试，按上面的修改就能正常训练了 &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

可以，只训练PPM-100的话，比文档中的效果更好

**Comment by newjavaer** [comment]
> > 就是说 最后的效果怎么样呢 sad能到paddlepaddle上的效果嘛
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: _**@**_.***>; 发送时间: 2021年11月19日(星期五) 上午8:39 收件人: "PaddlePaddle/PaddleSeg"; 抄送: "Comment"; 主题: Re: [PaddlePaddle/PaddleSeg] 关于matting测试效果， (Issue #1453) 你在训练的数据增强RandomCrop前面增加一个ResizeByShort试试： - type: ResizeByShort short_size: 512 这个可以，试了一份小数据集，评估值很快就下来了 感觉像是图太大了，随机裁剪尺寸太小了，导致训练出问题了 最后的可视化的图呢 怎么样 图暂时没有，你可以在PPM-100数据集上测试，按上面的修改就能正常训练了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
> 
> 可以，只训练PPM-100的话，比文档中的效果更好

好的谢谢

**Comment by yangy996** [comment]
> > > 你在训练的数据增强RandomCrop前面增加一个ResizeByShort试试： - type: ResizeByShort short_size: 512
> > 
> > 
> > 这个可以，试了一份小数据集，评估值很快就下来了 感觉像是图太大了，随机裁剪尺寸太小了，导致训练出问题了
> 
> > hello，你训练跑通了吗？我有份2000多张的数据集，训练了好几天，sad和mse还是非常的高 ![image](https://user-images.githubusercontent.com/15188456/141880701-c729c7f1-0b48-4d1e-af02-d265e4bffc7a.png)
> 
> 我数据集还没做好呢，想做一个头发丝级别的，不太好做，你训练是直接单独用你自己的数据集，或者和公开的数据集混合一起使用。还是修改了模型，数据增强是手动的吗，还是里面已经增加了相关代码

https://github.com/kelisiya/TIMI-Net，这里有一份数据集，你可以看看
![image](https://user-images.githubusercontent.com/15188456/142521990-1592bb36-00fb-46d7-8d7b-a9c6309a213f.png)

**Comment by zhanghongyong123456** [comment]
> hello，你训练跑通了吗？我有份2000多张的数据集，训练了好几天，sad和mse还是非常的高 ![image](https://user-images.githubusercontent.com/15188456/141880701-c729c7f1-0b48-4d1e-af02-d265e4bffc7a.png)

大佬，你的这个曲线图那里看到的，我昨天做好了一个数据集，尝试跑了一下，只跑了一个晚上就停了，我感觉只跑了一个epoch，我想知道在那里设置epoch

**Comment by yangy996** [comment]
> > hello，你训练跑通了吗？我有份2000多张的数据集，训练了好几天，sad和mse还是非常的高 ![image](https://user-images.githubusercontent.com/15188456/141880701-c729c7f1-0b48-4d1e-af02-d265e4bffc7a.png)
> 
> 大佬，你的这个曲线图那里看到的，我昨天做好了一个数据集，尝试跑了一下，只跑了一个晚上就停了，我感觉只跑了一个epoch，我想知道在那里设置epoch

可以將yml中的iters设置大一点

**Comment by zhanghongyong123456** [comment]
> > > hello，你训练跑通了吗？我有份2000多张的数据集，训练了好几天，sad和mse还是非常的高 ![image](https://user-images.githubusercontent.com/15188456/141880701-c729c7f1-0b48-4d1e-af02-d265e4bffc7a.png)
> > 
> > 
> > 大佬，你的这个曲线图那里看到的，我昨天做好了一个数据集，尝试跑了一下，只跑了一个晚上就停了，我感觉只跑了一个epoch，我想知道在那里设置epoch
> 
> 可以將yml中的iters设置大一点

这里不能设置epoch吗，你的这两个曲线在那里看的，我也想看一下自己的SAD 和MSE

**Comment by yangy996** [comment]
epoch是根据iters、GPU个数、批大小计算出来的，这个是我运行的命令
python  -m paddle.distributed.launch --gpus '4,5,6,7' train.py --config configs/modnet/modnet_hrnet_w18_ppm.yml --do_eval --use_vdl --save_interval 5000 --num_workers 8 --save_dir output

**Comment by zhanghongyong123456** [comment]
> 

大佬，四张显卡，牛批呀，你的iters设置多少，请教大佬，你的SAD SME 曲线那里查看

**Comment by yangy996** [comment]
弄大点多加两个0都可以了，如何查看曲线你可以看一下提供的文档

**Comment by zhanghongyong123456** [comment]
> 

好的我去看一下，谢谢指点哈

**Comment by zhanghongyong123456** [comment]
> 弄大点多加两个0都可以了，如何查看曲线你可以看一下提供的文档

大佬哪个文档，我没找到

**Comment by yangy996** [comment]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/contrib/Matting/README_CN.md
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/docs/train/train_cn.md

**Comment by zhanghongyong123456** [comment]
> [https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/contrib/Matting/README_CN.md ](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/contrib/Matting/README_CN.md) https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/docs/train/train_cn.md

![image](https://user-images.githubusercontent.com/48466610/147032753-7664f517-770e-4205-bbea-a7cbe5943c34.png)
我这里没有你显示的SAD 和SME 曲线，只有这几个曲线，我在训练的时候没有开do_eval这个选项

**Comment by wuyefeilin** [comment]
打开--do_eval， 不然训练的时候没有评估也就没有SAD和MSE曲线了

**Comment by izhaolinger** [comment]
> > 可以试一下modnet_hrnet_w18，这个效果好一些哦。
> > 这是我们开源的模型，你如果自己有数据集，可以基于我们开源的模型进行finetune，应用于自己的场合哈
> 
> 你好，我测试了你说的这个模型，得到这样的结果 ![image](https://user-images.githubusercontent.com/48466610/139202795-17f1ead3-21e1-4ef9-85b0-1d5b259cec97.png)
> 
> ![image](https://user-images.githubusercontent.com/48466610/139203058-45bd6163-b158-42da-afb5-dc025fcf253e.png) 这是运行命令，我不确定我是否哪里搞错了，期待您的回复

看到您很久之前的issue，我和您的需求类似，是期望使用Matting优化发丝精度的抠图效果，目前有几个问题想和您沟通请教：

1. 请问您最终是采用了什么方案呢？基于何种模型，训练时是否有加载预训练模型呢？
2. 请问您的数据集大小大约是多少呢？我准备了1000多张图，使用的微调方案，目前出来的效果和您图中的类似，不太理想。

**Comment by Sweezy27** [comment]
> > > 可以试一下modnet_hrnet_w18，这个效果好一些哦。
> > > 这是我们开源的模型，你如果自己有数据集，可以基于我们开源的模型进行finetune，应用于自己的场合哈
> > 
> > 
> > 你好，我测试了你说的这个模型，得到这样的结果 ![image](https://user-images.githubusercontent.com/48466610/139202795-17f1ead3-21e1-4ef9-85b0-1d5b259cec97.png)
> > ![image](https://user-images.githubusercontent.com/48466610/139203058-45bd6163-b158-42da-afb5-dc025fcf253e.png) 这是运行命令，我不确定我是否哪里搞错了，期待您的回复
> 
> 看到您很久之前的issue，我和您的需求类似，是期望使用Matting优化发丝精度的抠图效果，目前有几个问题想和您沟通请教：
> 
> 1. 请问您最终是采用了什么方案呢？基于何种模型，训练时是否有加载预训练模型呢？
> 2. 请问您的数据集大小大约是多少呢？我准备了1000多张图，使用的微调方案，目前出来的效果和您图中的类似，不太理想。

你好，想问下你ppmattingv2的训练成功了吗？我也遇到了你另一个帖子的问题，我尝试修改了不同数据增强方式，还是没成功训练出来
