### ISSUE TITLE
Does PaddleSeg need data enhancement method with RandomCenterCrop ?

### ISSUE THREAD

**Issue by zhangjinCV** [PaddlePaddle/PaddleSeg#1455]
I am a PaddleSeg user and find that the data enhancement method provided by PaddleSeg (here in paddleseg/transforms/transforms.py) does not have RandomCenterCrop (only RandomPaddingCrop). However, RandomCenterCrop and RandomPaddingCrop are very different. RandomCenterCrop does not fill the image but just crops it according to the input random ratio. Input images of any size are only cropped according to random proportions. RandomPaddingCrop has the padding size, but the value of padding may affect the overall effect of the image, and the size of the image input is unknown, and the target_size args in RandomPaddingCrop is difficult to determine. Therefore, I think RandomCenterCrop is needed. I have completed the initial RandomCenterCrop code for PaddleSeg. If you need this data enhancement method, you can reply to me and I will submit a PR to PaddleSeg.

**Comment by michaelowenliu** [comment]
@zhangjin12138 Hi, great idea! Welcome to submit the PR.

**Comment by bit-scientist** [comment]
Hi, @zhangjinCV, I know it's been long, but could you please explain the RandomCenterCrop in detail. I am struggling to put `RandomCenterCrop `into my custom training cfg file. Also, could you share a simple snippet of `RandomCenterCrop `to insert into cfg file. The following is the part where 
```
    - type: RandomPaddingCrop
      crop_size: [512, 512]
```
How do I do the same for `RandomCenterCrop`? Thank you.

**Comment by zhangjinCV** [comment]
- type: RandomCenterCrop
      retain_ratio: [0.8, 0.8]
retention_ratio indicates the minimum percentage of the original image size remaining after cropping. If it is set to 0.8, then a value from 0 to 0.2 will be selected, for example 0.16, and pixels 0.16 times the size of the image will be cropped from around the image. The recommended value is 0.8.

**Comment by bit-scientist** [comment]
@zhangjinCV, what a prompt feedback, thank you. What way is better?
1. Using both `RandomCenterCrop `and `RandomPaddingCrop`
2. Using only `RandomCenterCrop `

And, if you don't mind, what transformations would you recommend for training a segmentation model to detect defects? Appreciate your help.
