### ISSUE TITLE
是否有论文呢？

### ISSUE THREAD

**Issue by ty199931** [PaddlePaddle/PaddleSeg#1462]
请问这个有相关的论文吗？

**Comment by michaelowenliu** [comment]
@ty199931 Hi, what do you mean?

**Comment by ty199931** [comment]
&nbsp; I want to know the detail of the click theory, and when I read the code,I can not understanding it compeletely, So I would like to know if there is a paper to introduce. When I click an object,whether it will produce a heatmap to concatenate image,then get the gt?



---原始邮件---
发件人: "Liu ***@***.***&gt;
发送时间: 2021年10月25日(周一) 中午11:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleSeg] 是否有论文呢？ (Issue #1462)




 
@ty199931 Hi, what do you mean?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by michaelowenliu** [comment]
@ty199931 https://arxiv.org/abs/2109.09406
