### ISSUE TITLE
如何进行模型权重平均

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/PaddleSeg#1463]
您好，我想在训练过程中使用SWA进行加权平均，但是没有找到相关配置文件或代码，但发现了个EMA平均
请问EMA平均应该如何使用呢，配置文件、教程文档中好像没有找到相关内容

**Comment by juncaipeng** [comment]
这里有一个ema平均的实现和示例，只支持单卡训练，可以参考一下：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/paddleseg/utils/ema.py
