### ISSUE TITLE
关于matting模型导出的问题

### ISSUE THREAD

**Issue by lowfang** [PaddlePaddle/PaddleSeg#1464]
我尝试把matting导出，也把 MODNet 添加到了paddleseg/models/ 下，但是仍然报了 img 相关的一个错误，而且转化静态模型的时候也出现了shape相关错误。请问能否提供一个例子让我们把matting模型导出呢？

**Comment by wuyefeilin** [comment]
感谢你的反馈，近期我们会增加导出功能哈，欢迎关注哈。

**Comment by eisenxiao** [comment]
大佬，请问导出功能什么时候能增加？

**Comment by wuyefeilin** [comment]
> 大佬，请问导出功能什么时候能增加？

已经支持了，更新一下develop的最新代码，同时我们提供了Python部署代码
