### ISSUE TITLE
用paddleseg的predict.py预测和paddlex的model_infer推理结果相差有点大。

### ISSUE THREAD

**Issue by lpt-hub** [PaddlePaddle/PaddleSeg#1465]
用paddleseg的predict.py预测和paddlex的model_infer推理结果相差有点大。paddleseg是2.3版本，paddlex是2.0，算上背景一共有3个类别。predict.py预测两个类别都没问题，用model_infer推理，结果是第一个类别可以正常分割出来，第二个类别没有分割出一张。什么原因？

**Comment by FlyingQianMM** [comment]
您好，麻烦您参考PaddleX ISSUE模版提供下模型、相关部署环境和复现命令，https://github.com/PaddlePaddle/PaddleX/issues
PaddleX C++部署分割结果可视化可参考[FQA Q4](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#%E6%8E%A8%E7%90%86%E9%83%A8%E7%BD%B2%E9%97%AE%E9%A2%98)，可先排除下是否是可视化的问题

**Comment by lpt-hub** [comment]
> 您好，麻烦您参考PaddleX ISSUE模版提供下模型、相关部署环境和复现命令，https://github.com/PaddlePaddle/PaddleX/issues PaddleX C++部署分割结果可视化可参考[FQA Q4](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#%E6%8E%A8%E7%90%86%E9%83%A8%E7%BD%B2%E9%97%AE%E9%A2%98)，可先排除下是否是可视化的问题

不是可视化的问题，可以分割出第一个类别，只是第二个类别没有分割出一个。

**Comment by lpt-hub** [comment]
> 您好，麻烦您参考PaddleX ISSUE模版提供下模型、相关部署环境和复现命令，https://github.com/PaddlePaddle/PaddleX/issues PaddleX C++部署分割结果可视化可参考[FQA Q4](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#%E6%8E%A8%E7%90%86%E9%83%A8%E7%BD%B2%E9%97%AE%E9%A2%98)，可先排除下是否是可视化的问题

我用样本数据来测试，第一个类别可以分割出来，第二个类别没有分割出来。

**Comment by lpt-hub** [comment]
> 您好，麻烦您参考PaddleX ISSUE模版提供下模型、相关部署环境和复现命令，https://github.com/PaddlePaddle/PaddleX/issues PaddleX C++部署分割结果可视化可参考[FQA Q4](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#%E6%8E%A8%E7%90%86%E9%83%A8%E7%BD%B2%E9%97%AE%E9%A2%98)，可先排除下是否是可视化的问题

我前几周测试是正常的，用c++的model_infer推理，两个类别都可以分割出来，我自己做的可视化，保存的结果图像。本周又添加了200张样本之后训练，测试发现python的predict可以正确预测，导出模型后，用c++的model_infer推理结果就有第二个类别无法分割出来。

**Comment by lpt-hub** [comment]
> 您好，麻烦您参考PaddleX ISSUE模版提供下模型、相关部署环境和复现命令，https://github.com/PaddlePaddle/PaddleX/issues PaddleX C++部署分割结果可视化可参考[FQA Q4](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#%E6%8E%A8%E7%90%86%E9%83%A8%E7%BD%B2%E9%97%AE%E9%A2%98)，可先排除下是否是可视化的问题

使用环境：windows10, rtx 2080显卡，cuda11，paddleseg2.3，paddlex 2.0。
模型导出命令：python export.py --config configs/quick_start/bisenet_optic_disc_512x512_1k.yml --model_path output\best_model\model.pdparams --input_shape --save_dir output
推理命令：./model_infer --model_filename=model\model.pdmodel --params_filename=model\model.pdiparams --cfg_file=model\deploy.yaml --image=dataset\saveImg --model_type=seg --use_gpu=1
