### ISSUE TITLE
About Paper EdgeFlow: Consider Citation 

### ISSUE THREAD

**Issue by lxtGH** [PaddlePaddle/PaddleSeg#1467]
Hi! 
It is a very interesting idea to using flow to re-fine the object boundaries for Interactive Segmentation task. 

However, there are two ECCV 2020 paper and one axiv paper also using the flow to warping and upsampling features for **Segmentation** task. (I aslo seen these works in this repo).

1, Semantic Flow for Fast and Accurate Scene Parsing ECCV-2020
2,  Improving Semantic Segmentation via Decoupled Body and Edge Supervision ECCV-2020

Both 1 and 2 use the flow to warp and refine feature.

3,  BoundarySqueeze: Image Segmentation as Boundary Squeezing. (This paper is on arxiv at 2021.5 half year before EdgeFlow, it also using **boundary flow** to get the finer object boudaries for both instance and semantic segmentation)

**Please consider cite these paper as respect.** 
Thank you!

**Comment by hehao13** [comment]
I agree with @lxtGH. 

Adding these three papers to the reference is helpful to those who are not familiar with the flow-warping. Thus, it will be better that the authors add these papers in the next version of EdgeFlow.

**Comment by haoyuying** [comment]
Thank you for reminding， we will add these citation for next version of EdgeFlow.

**Comment by michaelowenliu** [comment]
@lxtGH @hehao13 Hi, great ideas!  Thanks for your works!
