### ISSUE TITLE
Cityscapes SOTA

### ISSUE THREAD

**Issue by kyeongjunJang** [PaddlePaddle/PaddleSeg#1471]
![image](https://user-images.githubusercontent.com/63050716/138828616-490059be-ce5d-45e8-857e-c95825262ea8.png)

![image](https://user-images.githubusercontent.com/63050716/138828654-21fd0347-b1d5-4df3-b7ab-fdf1af734ac2.png)

What role do labelTrainIds.png?
and  the images in convert_autolabelled folder?

I think we only need labelIds.png for actual training.

**Comment by LutaoChu** [comment]
There are 19 categories in labelTranIds and 30 categories in labelIds. We need labelTranIds.png when training. For specific category information, please refer to https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/helpers/labels.py
The data in the convert_autolabelled folder comes from Nvidia’s Autolabelled Data, which is converted to PaddleSeg data format by our conversion script, and finally named as convert_autolabelled.
