### ISSUE TITLE
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.

### ISSUE THREAD

**Issue by ding-Chen** [PaddlePaddle/PaddleSeg#1474]
您好，我在panoptic-deeplab基础上构建了一个新的模型，基本和panoptic-deeplab类似，在训练时出现了这个错误，请问这个是什么原因呢？ 我用的数据集格式和panoptic-deeplab是一样的，都是cityscapes。
![CH0@X_A@19T})4NL}D)ROR8](https://user-images.githubusercontent.com/85236372/139017691-35fda278-ac50-42b3-bd24-f9fd583f054c.png)

**Comment by ding-Chen** [comment]
这个是一些相关的地方
![K15$YFND`G00%Q%O6(756$W](https://user-images.githubusercontent.com/85236372/139018114-23d7a15b-9bcc-4906-bd07-d4edfc919902.png)
![BPZ$6 TAC20W)B~VV1~AC(W](https://user-images.githubusercontent.com/85236372/139018125-6a523541-714a-4d40-86c7-f7767e283805.png)

**Comment by wuyefeilin** [comment]
跑原教程可以跑通吗？ 另外你是否对数据读取过程进行了修改？

**Comment by ding-Chen** [comment]
> 跑原教程可以跑通吗？ 另外你是否对数据读取过程进行了修改？
跑原教程是可以跑通的，对数据读取过程进行了部分修改，把读取的一些数据换成了别的，是这出现了错误吗？那请问我要怎么查找并解决这个错误呢？谢谢您的解答

**Comment by wuyefeilin** [comment]
@ding-Chen 你可以单独构建datasets对象后对数据进行读取。然后寻找出错的地方

**Comment by ding-Chen** [comment]
> @ding-Chen 你可以单独构建datasets对象后对数据进行读取。然后寻找出错的地方

好的，我去试一试
