### ISSUE TITLE
使用tenosrrt_infer推理报错

### ISSUE THREAD

**Issue by lpt-hub** [PaddlePaddle/PaddleSeg#1477]
环境：win10,cuda11,paddleseg2.3,paddlex2.0,bisenetv2

用paddleseg的export导出模型的。
模型导出命令：python export.py --config configs\quick_start/bisenet_optic_disc_512x512_1k-100000.yml --model_path output\best_model\model.pdparams --input_shape 1 3 1024 1024 --save_dir output

推理命令：tensorrt_infer.exe --model_filename=model/model.pdmodel --params_filename=model/model.pdiparams --cfg_file=model/deploy.yaml --image=Z:\Member_dir\lpt\paddle\dataset\saveImg/1.jpg --model_type=seg

模型的输入输出：
![image](https://user-images.githubusercontent.com/63625557/139204418-fcc3b7c8-a4dd-4df0-84dd-d4900486bef6.png)

报错截图:
![image](https://user-images.githubusercontent.com/63625557/139204356-3cb1e6d9-e688-4659-a419-92829d32c751.png)

**Comment by juncaipeng** [comment]
在paddlex有相同issue，请关注那个issue。
