### ISSUE TITLE
slide_infer时显存溢出

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/PaddleSeg#1486]
在slide_infer过程中，使用ocrnet+hrnet48，对5000*5000大小的影像进行slide推理，crop size及stride均为512，在预测过程中，显存会不断增强，直至超出显存限制

**Comment by huilin16** [comment]
![q1](https://user-images.githubusercontent.com/36887207/139571660-d7a17f57-fdfc-4760-96ad-7b041cdd8fb6.png)

**Comment by wuyefeilin** [comment]
因为slide， 预测需要保存每一个slide的结果，显存增加是符合预期的哈。 能具体给一下显存增加的过程码
