### ISSUE TITLE
How to apply transfer learning with BiSeNet V2? 

### ISSUE THREAD

**Issue by khaep** [PaddlePaddle/PaddleSeg#1487]
Hello PaddleSeg community,

are there any pretrained weights or models of [BiSeNetV2](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.3/configs/bisenet) which can be used for transfer learning?
For example the weights/model of the [cityscapes submission](https://paperswithcode.com/paper/bisenet-v2-bilateral-network-with-guided) that reached 72.6 % mIoU and 156 FPS.

Is it possible to load some pretrained weights or model and use it as a staring point for further training with a [customized dataset](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/docs/data/custom/data_prepare.md)?
If so, how can the pretrained weights be loaded?
 - with the [resume training](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/docs/train/train.md#3resume-training) option
 - or is there a way to specify it in the [config.yml](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/configs/quick_start/bisenet_optic_disc_512x512_1k.yml) file

It would be great if someone can give me answers or hints for this topic.
I look forward to hearing from you.

Kind regards.

**Comment by wuyefeilin** [comment]
Just pass the pretrained model path to `pretrained` argument of the BiseNetV2

**Comment by khaep** [comment]
@wuyefeilin,
thank you for the reply.

I will try it by passing the _model.pdparams_ file as the [pretrained argument](https://github.com/PaddlePaddle/PaddleSeg/blob/fc4e41b676205261e95cd39d3597149f12d68705/configs/quick_start/bisenet_optic_disc_512x512_1k.yml#L39) in the config file.

**Comment by khaep** [comment]
After starting the train.py script, there are some warnings depicted in the picture below.
I would say the num_classes of the custom dataset are the reason for that. 
In the custom dataset I have only 2 classes instead of the 19 cityscapes classes.

![Screenshot from 2021-11-04 17-13-39](https://user-images.githubusercontent.com/66534155/140378235-da8acadd-dfb5-4555-a33b-f14152582e4a.png)

Can you give me some hints to work with these warnings?
Is it necessary to do some adjustments to solve it?
Maybe the input and the output layer need to be changed to the new number of classes.

Greetings
