### ISSUE TITLE
IndexError: When index contains a Tensor, its length must be 1, but received 2

### ISSUE THREAD

**Issue by ding-Chen** [PaddlePaddle/PaddleSeg#1489]
当我将一份pytorch代码转为paddle时，出现了IndexError: When index contains a Tensor, its length must be 1, but received 2。我不是特别清楚这个问题要如何解决。部分代码如下：
![22222222](https://user-images.githubusercontent.com/85236372/139637399-c3d15169-d17e-4cdc-9239-759e83b3db06.png)

**Comment by wuyefeilin** [comment]
目前paddle tensor角标不支持多元素形式输入，支持切片和单个值的输入， 例如：tensor[:, i]

**Comment by ding-Chen** [comment]
> 目前paddle tensor角标不支持多元素形式输入，支持切片和单个值的输入， 例如：tensor[:, i]

那请问有什么好的替代方案能解决这个问题吗？

**Comment by wuyefeilin** [comment]
可以提取出坐标，利用scatter或scatter_nd进行解决
