### ISSUE TITLE
CrossEntropyLoss带权重参数时有bug

### ISSUE THREAD

**Issue by justld** [PaddlePaddle/PaddleSeg#1491]
在paddleseg/models/losses/cross_entropy_loss.py中的CrossEntropyLoss类49-52行代码处，当有权重参数时会将权重扩充到256的长度，但是forward函数中调用的paddle.nn.functional.cross_entropy接受的权重参数应该和分类类别相同，这么处理会引起异常（cityscapes 19类为例）：
ValueError：inputs's class_dimension(19) must equal to weight's class_dimension(256) when weight is provided.

在paddleseg-develop和paddleseg-release2.3中都有这个问题，paddleseg-release2.2中无此bug。

部分代码如下：
`
self.weight = paddle.to_tensor(weight, dtype='float32')  

long_weight = weight + [0] * (256 - len(weight))       《============这里有bug，不应该固定为256的长度    

self.long_weight = paddle.to_tensor(long_weight, dtype='float32')  
`

**Comment by LutaoChu** [comment]
你的paddle版本是多少呢？
用long_weight的目的是为了修复之前的paddle cross_entropy OP的bug
我这边亲测paddle 2.1.3 + paddleseg develop是OK的，你可以试一下

**Comment by justld** [comment]
你好，我是在aistudio平台下使用出现的bug，paddlepaddle==2.1.2和paddlepaddle==develop，下面是aistudio的一个测试连接，可以看一下。
https://aistudio.baidu.com/aistudio/projectdetail/2562304?shared=1


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月2日(星期二) 晚上7:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] CrossEntropyLoss带权重参数时有bug (Issue #1491)





 
你的paddle版本是多少呢？
 用long_weight的目的是为了修复之前的paddle cross_entropy OP的bug
 我这边亲测paddle 2.1.3 + paddleseg develop是OK的，你可以试一下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LutaoChu** [comment]
你好，由于paddle cross_entropy OP存在问题，不同版本的PaddleSeg需要正确对应Paddle的版本，具体梳理如下：
https://github.com/PaddlePaddle/PaddleSeg/pull/1499
待上述PR合入后使用paddle dev和paddleseg dev即可正常使用了

**Comment by geoexploring** [comment]
@LutaoChu ， 直接 `git clone https://github.com/PaddlePaddle/PaddleSeg` 下来的paddleseg版本，仍然会出现这个问题

**Comment by LutaoChu** [comment]
@geoexploring 直接clone下的是2.3版本，我们刚也在2.3版本修复了这个问题，你可以git pull一下试试
