### ISSUE TITLE
Matting模型使用了多少张训练数据

### ISSUE THREAD

**Issue by zyz207** [PaddlePaddle/PaddleSeg#1496]
请问提供的Matting模型用了多少训练数据呢？

**Comment by wuyefeilin** [comment]
你可以使用诸如Composition-1k, Distinction-646, PPM-100, AIM-500, VideoMatte-240k等数据集进行训练哈，如果你有自己的数据集也可以在我们开源模型的基础上进行训练

**Comment by yangy996** [comment]
你好，请问下你训练成功了吗？我跑了3天了，sad和mse都还是非常高
![image](https://user-images.githubusercontent.com/15188456/141738007-dfb6ff43-e65a-42be-964a-49f68cd69444.png)

**Comment by zyz207** [comment]
> 你好，请问下你训练成功了吗？我跑了3天了，sad和mse都还是非常高 ![image](https://user-images.githubusercontent.com/15188456/141738007-dfb6ff43-e65a-42be-964a-49f68cd69444.png)

我的SAD和MSE也还是降不下来

**Comment by yangy996** [comment]
> > 你好，请问下你训练成功了吗？我跑了3天了，sad和mse都还是非常高 ![image](https://user-images.githubusercontent.com/15188456/141738007-dfb6ff43-e65a-42be-964a-49f68cd69444.png)
> 
> 我的SAD和MSE也还是降不下来

https://github.com/PaddlePaddle/PaddleSeg/issues/1453#issuecomment-969772014
按这个修改就可以降下来了

**Comment by zyz207** [comment]
> 

嗯嗯，谢啦，我去试试看

**Comment by largerwxt** [comment]
> > > 你好，请问下你训练成功了吗？我跑了3天了，sad和mse都还是非常高 ![image](https://user-images.githubusercontent.com/15188456/141738007-dfb6ff43-e65a-42be-964a-49f68cd69444.png)
> > 
> > 
> > 我的SAD和MSE也还是降不下来
> 
> [#1453 (comment)](https://github.com/PaddlePaddle/PaddleSeg/issues/1453#issuecomment-969772014) 按这个修改就可以降下来了

您好，我修改了这个还是降不下来，sad和mse到了100左右就不动了，请问你的配置文件是什么样子的呢。
