### ISSUE TITLE
Unet模型c++推理开启TRT，加载模型异常

### ISSUE THREAD

**Issue by HongChen123** [PaddlePaddle/PaddleSeg#1497]
使用visualdl查看网络结构图也可以看到bilinear_interp_v2层的输出结构 1x64x?x?
如果仅开启GPU，可以正常加载模型，推理结果正常，开启TRT配置后，出现下述异常。
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The input [bilinear_interp_v2_3.tmp_0] shape of trt subgraph is [1,64,-1,-1], please enable trt dynamic_shape mode by SetTRTDynamicShapeInfo. (at C:\home\workspace\Paddle_release5\paddle/fluid/inference/tensorrt/engine.h:103)

说明：推理使用的代码为peddleseg2.3版本的deploy/cpp/src/test_seg.cc

**Comment by juncaipeng** [comment]
对于大部分分割模型来说，gpu上开启trt后必须启用动态shape，默认test_seg.cc是没有开启动态shape，所以会报错。我们会尽快修复。
