### ISSUE TITLE
python2.7下infer.py问题

### ISSUE THREAD

**Issue by littletomatodonkey** [PaddlePaddle/PaddleSeg#150]
exec是python内置函数，Python2.7下这样写好像会报错
https://github.com/PaddlePaddle/PaddleSeg/blob/297d9e5f924102c76b59c1e45c473b00951e79b0/deploy/python/infer.py#L150

```
  File "deploy/python/infer.py", line 150
    with ThreadPoolExecutor(max_workers=self.config.batch_size) as exec:
                                                                      ^
SyntaxError: invalid syntax
```

**Comment by sjtubinlong** [comment]
@littletomatodonkey  
已经修复，感谢反馈
https://github.com/PaddlePaddle/PaddleSeg/commit/55e84caf683a4ff63ee06676d32d8606a7d3cfa7
