### ISSUE TITLE
EISEG 网络模型如何转onnx格式呢

### ISSUE THREAD

**Issue by lfxx** [PaddlePaddle/PaddleSeg#1501]
我看网络结构中有条件分支，这种如何处理呢

**Comment by juncaipeng** [comment]
和常规方法一样转onnx，条件分支一般是支持的。

**Comment by lfxx** [comment]
> 和常规方法一样转onnx，条件分支一般是支持的。

生成的onnx其实就是条件分支的默认路线吧
