### ISSUE TITLE
文档说明错误

### ISSUE THREAD

**Issue by little-white001** [PaddlePaddle/PaddleSeg#1503]
PaddleSeg/docs/predict/predict.md，说明文档中，第1点结尾处：At this point, you can specify image_list as train.txt and image_dir as the directory where the training data is located when predicting. The robustness of PaddleSeg allows you to do this, and the output will be the prediction result of the original training data.
实际使用的时候，并不能通过命令行设置image_list为train.txt，设置image_dir为训练数据目录运行，而是直接指定image_dir为train.txt才运行的。

**Comment by LutaoChu** [comment]
感谢反馈！已经提pr进行修复  https://github.com/PaddlePaddle/PaddleSeg/pull/1512
