### ISSUE TITLE
Run prediction on multiple GPUs

### ISSUE THREAD

**Issue by stefan-sf-wu** [PaddlePaddle/PaddleSeg#1507]
Hi, 

First of all, thank you for releasing this great work :)

I am curious about whether it is possible to run `predict.py` on multiple GPUs to increase inference speed? I am currently running large-scale remote imagery analysis that is really time-consuming...

Stefan

**Comment by juncaipeng** [comment]
`predict.py` can not use multiple GPU.  To accelerate the inference speed, you can export the model and use paddle inference python or c++ api to deploy the model. 

https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/docs/model_export.md

**Comment by stefan-sf-wu** [comment]
Thank you for your reply! 
I will give it a try.

**Comment by varungupta31** [comment]
Hi @sfstefanwu 
were you able to run/did you try running `predict.py` using any pre-trained model on a custom image?
(with or without multiple GPUs)

**Comment by stefan-sf-wu** [comment]
@varungupta31 yes. how can i help?
