### ISSUE TITLE
Loading Backbone

### ISSUE THREAD

**Issue by Mustafa744** [PaddlePaddle/PaddleSeg#1508]
How can i load a backbone to a pretrained model?

**Comment by juncaipeng** [comment]
In the config, you can set the path of pretrained model as follows. The pretrained also can be the path in your computer, such as "/work/pretrained/model/model.pdparams" .

![image](https://user-images.githubusercontent.com/52520497/140673274-a6ccdbc0-fc09-4395-b93c-389e5f8e6a9b.png)
