### ISSUE TITLE
deploy/python/infer.py并不能正确保存所有预测结果

### ISSUE THREAD

**Issue by DXVVV** [PaddlePaddle/PaddleSeg#1510]
windows平台X86 cpu预测，image_path里面有四张图片，结果只有一张，查看了预测过程，在`_save_imgs(self, results, imgs):`中i的值一直是0.然后只能保存最后一次的结果，并且名字是第一张图片的名字。

**Comment by juncaipeng** [comment]
是不是路径有点问题啊，是否有中文等字符呢？

**Comment by DXVVV** [comment]
不是诶，图片路径是`E:\lab_project\seg\test`

**Comment by juncaipeng** [comment]
是保存图片路径错误，修复pr：https://github.com/PaddlePaddle/PaddleSeg/pull/1513
