### ISSUE TITLE
paddleseg模型问题

### ISSUE THREAD

**Issue by gxqnba** [PaddlePaddle/PaddleSeg#1515]
请问paddleseg目前提供基于transformer的分割模型吗？如果支持，请问如何使用？

**Comment by michaelowenliu** [comment]
@gxqnba https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.3/configs/segformer

**Comment by gxqnba** [comment]
> @gxqnba https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.3/configs/

谢谢！
