### ISSUE TITLE
paddleseg训练bisenetv2模型时，在代码中没有找到归一化操作。

### ISSUE THREAD

**Issue by lpt-hub** [PaddlePaddle/PaddleSeg#1519]
paddleseg训练bisenetv2模型时，在代码中没有找到归一化操作。请问，图像在哪做的归一化操作？

**Comment by shiyutang** [comment]
Image normalization is done through configurations.
 
As we can see in the config file of bisenet, it inherits the config file of cityscapes.yml as shown below
![image](https://user-images.githubusercontent.com/34859558/141059226-010f4469-6636-459f-948a-4769e303d01c.png)
And in the cityscapes config file, we add normalization in the dataset part as the following pic shows. 
![image](https://user-images.githubusercontent.com/34859558/141059496-e95c686f-801e-40bd-bb76-23c92e21bb4b.png)

**Comment by lpt-hub** [comment]
> Image normalization is done through configurations.
> 
> As we can see in the config file of bisenet, it inherits the config file of cityscapes.yml as shown below ![image](https://user-images.githubusercontent.com/34859558/141059226-010f4469-6636-459f-948a-4769e303d01c.png) And in the cityscapes config file, we add normalization in the dataset part as the following pic shows. ![image](https://user-images.githubusercontent.com/34859558/141059496-e95c686f-801e-40bd-bb76-23c92e21bb4b.png)

这个我明白，只是我在训练的python代码中没有找到归一化的操作。

**Comment by shiyutang** [comment]
if you have this configuration, paddleseg will call normalize transform in the config file.
The relevant config code is here: https://github.com/PaddlePaddle/PaddleSeg/blob/6b68b0a766710e49c6e20b255b9de347b168188e/paddleseg/cvlibs/config.py#L353
the transform component is loaded then pass to the train/val dataset.

The transform code is here: https://github.com/PaddlePaddle/PaddleSeg/blob/6b68b0a766710e49c6e20b255b9de347b168188e/paddleseg/transforms/transforms.py#L437

**Comment by lpt-hub** [comment]
> if you have this configuration, paddleseg will call normalize transform in the config file. The relevant config code is here:
> 
> https://github.com/PaddlePaddle/PaddleSeg/blob/6b68b0a766710e49c6e20b255b9de347b168188e/paddleseg/cvlibs/config.py#L353
> 
> 
> the transform component is loaded then pass to the train/val dataset.
> The transform code is here:
> 
> https://github.com/PaddlePaddle/PaddleSeg/blob/6b68b0a766710e49c6e20b255b9de347b168188e/paddleseg/transforms/transforms.py#L437

谢谢啦
