### ISSUE TITLE
数据集PPM-100进行matting训练问题

### ISSUE THREAD

**Issue by yangy996** [PaddlePaddle/PaddleSeg#1522]
加载预训练模型modnet-hrnet_w18.pdparams
训练过程中会出现结果为nan的情况
![image](https://user-images.githubusercontent.com/15188456/141263677-618a0720-860d-46c3-be2d-84256e3783c4.png)

而且SAD和MSE训练的结果非常高，与预训练模型评估的结果相差甚远
[EVAL] SAD: 3141.6386, MSE: 0.2802

**Comment by wuyefeilin** [comment]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/contrib/Matting/model/modnet.py#L88 可能是这边分母出现了0的情况，在分母加一下1e-6试试，如果解决了，欢迎提个pr哈

**Comment by yangy996** [comment]
> https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/contrib/Matting/model/modnet.py#L88 可能是这边分母出现了0的情况，在分母加一下1e-6试试，如果解决了，欢迎提个pr哈

暂时不报nan了，还在训练中，到时候看看结果是否跟文档中一样

但是不明白为啥分母会变0，看数据处理是填充了128值，loss计算的时候为什么取到的值会为0
![image](https://user-images.githubusercontent.com/15188456/141278107-2fe673f0-a174-424c-ba7b-9feba711c3d1.png)
![image](https://user-images.githubusercontent.com/15188456/141278283-c93bbb90-7ff0-459e-8008-87f58f189b4e.png)

**Comment by wuyefeilin** [comment]
可能是在数据增强时进行crop的时候导致的， 如果是该问题导致的，欢迎提个pr哈

**Comment by yangy996** [comment]
> 可能是在数据增强时进行crop的时候导致的， 如果是该问题导致的，欢迎提个pr哈

好像不太对，训练了一晚上，SAD和MSE值非常大，跟文档差别太大了
![image](https://user-images.githubusercontent.com/15188456/141389252-21574af5-0dfc-40eb-8e66-8f17db8d68f0.png)
![image](https://user-images.githubusercontent.com/15188456/141389225-536ed832-4aed-4d69-adb7-061d7f173d78.png)

**Comment by wuyefeilin** [comment]
提供的只是教程，让你跑通用的。如果要训练自己的模型你需要自己准备数据集，以我们的模型作为预训练模型进行微调

**Comment by yangy996** [comment]
额，数据集PPM-100文档中的结果不是通过提供的代码和教程训练出来的？

**Comment by wuyefeilin** [comment]
内部数据训练的，不能开源哈

**Comment by yangy996** [comment]
哦哦，好的，看文档还以为只用PPM-100数据集训练得了
![)M14SEALAJW$TP)X%O~E)~P](https://user-images.githubusercontent.com/15188456/141397962-7ddef1f6-46ae-432a-8ca9-3acde56ef278.png)

**Comment by yangy996** [comment]
> 提供的只是教程，让你跑通用的。如果要训练自己的模型你需要自己准备数据集，以我们的模型作为预训练模型进行微调

大佬，还有个问题，我用提供的预训练模型对PPM-100数据集进行训练，为什么结果相差巨大呢？训练效果显示加不加载预训练模型结果都一样

**Comment by wuyefeilin** [comment]
PPM-100只是一个公开的benchmark哦， 网上有一些公开的数据集Composition-1k, Distinctions-646, VideMatte240k, 等等，你可以在这些数据集上进行训练哈

**Comment by miyane-ralo** [comment]
大佬，问下你们训练的数据集样本量大概有多少，MSE才能到0.00几

**Comment by miyane-ralo** [comment]
还有一个问题，大佬readme里的效果图是加了trimap吗？

**Comment by wuyefeilin** [comment]
没有的，就是用modnet训练的结果

**Comment by Sun-2020** [comment]
那大佬的训练数据集样本大概用了多少，MSE才能到0.00几，达到咱们发布的效果呀

**Comment by yangy996** [comment]
> 那大佬的训练数据集样本大概用了多少，MSE才能到0.00几，达到咱们发布的效果呀

还在收集数据集训练中

**Comment by yangy996** [comment]
这边找到了有两份数据集
https://github.com/kelisiya/TIMI-Net
![DHYAI_@E}8$_AYL5WY0TMM8](https://user-images.githubusercontent.com/15188456/142798334-d6d5bfbe-601b-44bb-a475-cd9f442a5294.png)

https://github.com/YY007H/P3M
![4YM (9%2S5LHOEO{HRKLROD](https://user-images.githubusercontent.com/15188456/142798341-02ce3a09-e34f-4cfa-add5-538cf483a819.png)

**Comment by zhanghongyong123456** [comment]
> 内部数据训练的，不能开源哈

您好，我想问一下训练的epoch如何设置，我做好数据，只跑了一个晚上就自己停止了，我想知道在那里设置epoch呢，期待您的回复

**Comment by wuyefeilin** [comment]
可以通过参数--iters设置训练的步数, 或者修改config目录下相关的参数

**Comment by gg22mm** [comment]
GPU  还有这个情况 loss=nan  ，cpu就正常  用的是 ：PaddleSeg: 2.6.0
