### ISSUE TITLE
onnx转化时的model？

### ISSUE THREAD

**Issue by wang971124** [PaddlePaddle/PaddleSeg#1525]
模型转成onnx之后，利用ONNXRunTime来进行ONNX模型验证测试，这里model是指什么？
![image](https://user-images.githubusercontent.com/74095885/141419262-803766c4-a7d5-48c9-8dcf-e597c5005305.png)

**Comment by juncaipeng** [comment]
这个model是paddle的动态图模型（没有导出之前）。
