### ISSUE TITLE
预测时报错

### ISSUE THREAD

**Issue by PipgZ** [PaddlePaddle/PaddleSeg#153]
----------------------
Error Message Summary:
----------------------
Error: ShapeError: broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 256, 256, 256] and the shape of Y = [1, 3]. Received [256] in X is not equal to [3] in Y
  [Hint: Expected y_dims[i] == 1, but received y_dims[i]:3 != 1:1.] at (D:\1.6.2\paddle\paddle/fluid/operators/elementwise/elementwise_op_function.h:79)
  [operator < elementwise_sub > error]

下面是这个模型训练时的配置文件：
# 数据集配置
DATASET:
    DATA_DIR: "./data/"
    NUM_CLASSES: 2
    TEST_FILE_LIST: "./data/validation.txt"
    TRAIN_FILE_LIST: "./data/training.txt"
    VAL_FILE_LIST: "./data/val_list.txt"
    VIS_FILE_LIST: "./data/validation.txt"

# 预训练模型配置
MODEL:
    MODEL_NAME: "deeplabv3p"
    DEFAULT_NORM_TYPE: "bn"
    DEEPLAB:
        BACKBONE: "xception_65"

# 其他配置
TRAIN_CROP_SIZE: (256, 256)
EVAL_CROP_SIZE: (256, 256)
AUG:
    AUG_METHOD: "unpadding"
    FIX_RESIZE_SIZE: (256, 256)
BATCH_SIZE: 4
TRAIN:
    PRETRAINED_MODEL_DIR: "./pretrained_model/deeplabv3p_xception65_bn_coco/"
    MODEL_SAVE_DIR: "./saved_model/deeplabv3p_xception65_bn_optic/"
    SNAPSHOT_EPOCH: 5
TEST:
    TEST_MODEL: "./saved_model/deeplabv3p_xception65_bn_optic/final"
SOLVER:
    NUM_EPOCHS: 10
    LR: 0.001
    LR_POLICY: "poly"
    OPTIMIZER: "adam"

**Comment by zyz207** [comment]
我也是一样的问题，感觉的模型导出的问题，用示范的模型预测就可以

**Comment by PipgZ** [comment]
@LutaoChu  作者求救

**Comment by LutaoChu** [comment]
请问你们是用vis.py预测还是导出模型后用infer.py预测呢？
提供一下复现的步骤吧

**Comment by PipgZ** [comment]
我是导出模型后用的deploy/python/infer.py进行预测的，其余训练的步骤是根据 DeepLabv3+模型使用教程 来的，不过训练的时候为了测试，我只训练了四张图片，
下面是这个模型训练时的配置文件：

数据集配置
DATASET:
DATA_DIR: "./data/"
NUM_CLASSES: 2
TEST_FILE_LIST: "./data/validation.txt"
TRAIN_FILE_LIST: "./data/training.txt"
VAL_FILE_LIST: "./data/val_list.txt"
VIS_FILE_LIST: "./data/validation.txt"

预训练模型配置
MODEL:
MODEL_NAME: "deeplabv3p"
DEFAULT_NORM_TYPE: "bn"
DEEPLAB:
BACKBONE: "xception_65"

其他配置
TRAIN_CROP_SIZE: (256, 256)
EVAL_CROP_SIZE: (256, 256)
AUG:
AUG_METHOD: "unpadding"
FIX_RESIZE_SIZE: (256, 256)
BATCH_SIZE: 4
TRAIN:
PRETRAINED_MODEL_DIR: "./pretrained_model/deeplabv3p_xception65_bn_coco/"
MODEL_SAVE_DIR: "./saved_model/deeplabv3p_xception65_bn_optic/"
SNAPSHOT_EPOCH: 5
TEST:
TEST_MODEL: "./saved_model/deeplabv3p_xception65_bn_optic/final"
SOLVER:
NUM_EPOCHS: 10
LR: 0.001
LR_POLICY: "poly"
OPTIMIZER: "adam"

**Comment by zyz207** [comment]
我是用deeplabv3p_mobilenet-1-0_pet.yaml的配置训练optic_disc_seg，然后用export_model.py导出模型以后用infer.py进行预测，使用vis.py时没有问题
TRAIN_CROP_SIZE: (512, 512) # (width, height), for unpadding rangescaling and stepscaling
EVAL_CROP_SIZE: (512, 512) # (width, height), for unpadding rangescaling and stepscaling
AUG:
    AUG_METHOD: "unpadding" # choice unpadding rangescaling and stepscaling
    FIX_RESIZE_SIZE: (512, 512) # (width, height), for unpadding

    INF_RESIZE_VALUE: 500  # for rangescaling
    MAX_RESIZE_VALUE: 600  # for rangescaling
    MIN_RESIZE_VALUE: 400  # for rangescaling

    MAX_SCALE_FACTOR: 1.25  # for stepscaling
    MIN_SCALE_FACTOR: 0.75  # for stepscaling
    SCALE_STEP_SIZE: 0.25  # for stepscaling
    MIRROR: True
BATCH_SIZE: 4
DATASET:
    DATA_DIR: "./dataset/optic_disc_seg/"
    NUM_CLASSES: 2
    TEST_FILE_LIST: "./dataset/optic_disc_seg/test_list.txt"
    TRAIN_FILE_LIST: "./dataset/optic_disc_seg/train_list.txt"
    VAL_FILE_LIST: "./dataset/optic_disc_seg/val_list.txt"
    VIS_FILE_LIST: "./dataset/optic_disc_seg/test_list.txt"
FREEZE:
    MODEL_FILENAME: "__model__"
    PARAMS_FILENAME: "__params__"
MODEL:
    MODEL_NAME: "deeplabv3p"
    DEFAULT_NORM_TYPE: "bn"
    DEEPLAB:
        BACKBONE: "mobilenetv2"
        DEPTH_MULTIPLIER: 1.0
        ENCODER_WITH_ASPP: False
        ENABLE_DECODER: False
TRAIN:
    # PRETRAINED_MODEL_DIR: "./pretrained_model/deeplabv3p_mobilenetv2-1-0_bn_cityscapes/"
    PRETRAINED_MODEL_DIR: "./pretrained_model/deeplabv3p_mobilenetv2-1-0_bn_coco/"
    MODEL_SAVE_DIR: "./saved_model/deeplabv3p_mobilenetv2-1-0_bn_pet/"
    SNAPSHOT_EPOCH: 10
TEST:
    TEST_MODEL: "./saved_model/deeplabv3p_mobilenetv2-1-0_bn_pet/final"
SOLVER:
    NUM_EPOCHS: 100
    LR: 0.005
    LR_POLICY: "poly"
    OPTIMIZER: "sgd"

python pdseg/train.py --cfg configs/deeplabv3p_mobilenet-1-0_pet.yaml --use_gpu --do_eval   --use_tb --tb_log_dir train_log   BATCH_SIZE 4 SOLVER.LR 0.001

python pdseg/export_model.py --cfg E:/Pytorch/PaddleSeg-release-v0.3.0/configs/deeplabv3p_mobilenet-1-0_pet.yaml TEST.TEST_MODEL E:/Pytorch/PaddleSeg-release-v0.3.0/saved_model/deeplabv3p_mobilenetv2-1-0_bn_pet/final

python E:/Pytorch/PaddleSeg-release-v0.3.0/deploy/python/infer.py --conf=E:/Pytorch/PaddleSeg-release-v0.3.0/freeze_model/deploy.yaml --input_dir=E:/Pytorch/PaddleSeg-release-v0.3.0/dataset/optic_disc_seg/JPEGImages --use_pr=False

**Comment by sjtubinlong** [comment]
@zyz207 @PipgZ hello，`deploy/python/infer.py` 预测的时候请设置参数 `--use_pr=1` 即可。
