### ISSUE TITLE
CityscapeSOTA的MscaleOCRNet导出静态图报错

### ISSUE THREAD

**Issue by JiehangXie** [PaddlePaddle/PaddleSeg#1532]
![QQ截图20211113132935](https://user-images.githubusercontent.com/51190264/141607069-ece86232-c716-45c7-b447-b59cb7294260.png)

我已经把CityscapeSOTA目录下的models复制加载到paddleseg.core.models的目录下，但在导出静态图的时候提示backbone输出维度有错误，因为源代码有点复杂，一时半会无法定位和解决问题，希望官方能提供修复帮助。

报错复现地址：https://aistudio.baidu.com/aistudio/projectdetail/2654280?shared=1

**Comment by juncaipeng** [comment]
这个pr可以修复导出的错误：https://github.com/PaddlePaddle/PaddleSeg/pull/1539
