### ISSUE TITLE
paddleseg 推理代码没有resize设置

### ISSUE THREAD

**Issue by yueyueshine** [PaddlePaddle/PaddleSeg#1533]
使用原图2560*1440训练了分割模型，推理时候，将图像resize到1280*720，轮廓出现锯齿。
然后重新调整了训练集，将原图及其标注文件resize到原来的1/2，即：标注点坐标*1/2 ，图像resize到1/2。推入训练，训练完成后推理，依然有锯齿。这是为什么？有什么解决方法嘛？

**Comment by juncaipeng** [comment]
出现锯齿，一般有两种解决方法，修改模型或者后处理。
你是用来了哪个模型啊？是否使用空洞卷积？可以调整空洞卷积的dilation为没有大于1的公约数，比如3,5等。
后处理即是进行均值滤波。
