### ISSUE TITLE
推理时间

### ISSUE THREAD

**Issue by wang971124** [PaddlePaddle/PaddleSeg#1541]
为什么fp16量化为int8之后的推理时间反而增加了，推理用的inference

**Comment by juncaipeng** [comment]
fp16模型无法再量化为int8，只有fp32模型才可以量化为int8。
如果fp32模型是轻量级的模型，量化为int8在gpu上可能性能没多大听提升，如果fp32模型是计算量比较大的模型，量化后提升比较明显。
部署参考文档：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/docs/deployment/inference/python_inference.md

**Comment by wang971124** [comment]
fp32量化为int模型之后，时间也会增加，时间用的是infer.py,下面附上fp32的推理日志和fp32量化为int8模型之后推理日志

> fp16模型无法再量化为int8，只有fp32模型才可以量化为int8。 如果fp32模型是轻量级的模型，量化为int8在gpu上可能性能没多大听提升，如果fp32模型是计算量比较大的模型，量化后提升比较明显。 部署参考文档：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/docs/deployment/inference/python_inference.md

**Comment by wang971124** [comment]
![image](https://user-images.githubusercontent.com/74095885/141891276-a1299c22-6045-48b1-8db4-d99bce7fea49.png)
![image](https://user-images.githubusercontent.com/74095885/141891307-6d3f89a9-5c31-45fd-b7c4-56a30e5f5af8.png)

**Comment by juncaipeng** [comment]
seg部署的文档明确了，量化模型必须开启tensorrt，否则没有加速：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/docs/deployment/inference/python_inference.md
