### ISSUE TITLE
无法加载模型参数

### ISSUE THREAD

**Issue by s348268281** [PaddlePaddle/PaddleSeg#1542]
已经下载好了模型，并按要求将model和params放在同一目录下且显示存在，但用ElSeg加载模型参数时确显示不存在，且无法打开，如下图：
![image](https://user-images.githubusercontent.com/43004817/141887351-d7ff81b3-04ca-4520-a859-76232667c72f.png)

**Comment by frandoLin** [comment]
仔细看 因为文件名后缀里多了个i 所以程序无法匹配 这是个啥bug... 啥时修复啊

**Comment by s348268281** [comment]
> 仔细看 因为文件名后缀里多了个i 所以程序无法匹配 这是个啥bug... 啥时修复啊

可文档就是这么写的啊
![image](https://user-images.githubusercontent.com/43004817/141890474-96957297-a311-461c-a205-6e1ca96436b4.png)

**Comment by haoyuying** [comment]
请问您使用的paddle版本是多少呢，本地测试没有出现该问题，是否能够给一个方便复现的环境，可以加我qq：1504781055

**Comment by s348268281** [comment]
> 请问您使用的paddle版本是多少呢，本地测试没有出现该问题，是否能够给一个方便复现的环境，可以加我qq：1504781055

如图方式下载的，启动后自动安装的依赖，找到里面的python site-packages，发现paddle是2.1.2吧应该。
![image](https://user-images.githubusercontent.com/43004817/141929844-8b632da8-842c-463b-a5b6-4e41a89cd57e.png)
![image](https://user-images.githubusercontent.com/43004817/141929982-36cad588-9ff9-4e04-a58b-f3d58cefad62.png)

**Comment by haoyuying** [comment]
exe的文件我们还没有更新，您安装的是0.3.版本的eiseg，目前0.4.0版本正在测试中，您可以clone develop代码之后进入EISeg文件夹下运行python -m eiseg，可以抢先体验0.4版本的eiseg，0.4的eiseg要求paddle的版本最低为2.2。本周将会更新0.4.0exe链接并发版pip 包安装，敬请期待。

**Comment by s348268281** [comment]
> exe的文件我们还没有更新，您安装的是0.3.版本的eiseg，目前0.4.0版本正在测试中，您可以clone develop代码之后进入EISeg文件夹下运行python -m eiseg，可以抢先体验0.4版本的eiseg，0.4的eiseg要求paddle的版本最低为2.2。本周将会更新0.4.0exe链接并发版pip 包安装，敬请期待。

好的，感谢！

**Comment by lx11** [comment]
@haoyuying 你好，我这边使用paddle2.2, git clone develop版本的eiseg代码，然后在EiSeg文件夹下运行python -m eiseg。同样会出现模型参数无法加载
