### ISSUE TITLE
导出的静态图和直接用动态图预测差别较大。

### ISSUE THREAD

**Issue by DXVVV** [PaddlePaddle/PaddleSeg#1554]
在自己数据集上在ubuntu上用gpu训练，动态图预测效果还行，导出成静态图后转到windows平台用cpu预测效果和动态图比差了不少，用的是导出后的设置deploy.yaml。下面分别为原图，gpu动态图预测出的label图和cpu预测的图片。训练用的模型为isanet。
![0945](https://user-images.githubusercontent.com/20319589/142213835-d136e3f0-fa02-416e-ae7a-abf4f4c01ddd.jpg)
![github上传](https://user-images.githubusercontent.com/20319589/142213856-424654b5-52f3-441f-ac76-cc83f2d4eb12.png)
![0945](https://user-images.githubusercontent.com/20319589/142213935-531e6dc0-d4bc-4394-9374-9a92d4bb19e2.png)

**Comment by juncaipeng** [comment]
从图片来看，蝴蝶的翅膀预测准确，其他部分预测错误，是不是预处理不对？
这个分割是前景和背景两类吗？

**Comment by DXVVV** [comment]
> 从图片来看，蝴蝶的翅膀预测准确，其他部分预测错误，是不是预处理不对？ 这个分割是前景和背景两类吗？

不是的，有多个类别（花、叶、蝴蝶、鸟等），翅膀部分似乎也是错的，黄色的是花的标签。上面是isa模型预测的结果，导出后的预测是直接用predict.py预测，无预处理过程，脚本如下：
```
python infer.py --config ./dnl/deploy.yaml --image_path ./test/0945.jpg  --device cpu --save_dir ./output
```
换一个模型导出后预测效果也一般般，如换sfnet导出后的效果如下，效果也不好，在动态图的sfnet上基本也都预测正确。
![0945](https://user-images.githubusercontent.com/20319589/142358302-75c8248f-d4f9-4050-a775-98a702fc794e.png)
，然后这边是一些其他对比原图，动态图预测图，静态图预测图。
![2209](https://user-images.githubusercontent.com/20319589/142358381-f150af17-13da-4421-8e2b-8b3ffbbf9b00.jpg)
![Quicker_20211118_134054](https://user-images.githubusercontent.com/20319589/142358656-bcdf5cab-3fe4-4ffb-b976-8cdbcbf42d03.png)

![2209](https://user-images.githubusercontent.com/20319589/142358396-cbe6d4d1-2093-4c74-835a-9f6fdee2473d.png)

**Comment by juncaipeng** [comment]
你可以把导出的预测模型和图片传上来，我们排查一下，这样看不出问题。

**Comment by DXVVV** [comment]
https://www.jianguoyun.com/p/DcZwj88Q9P-1CBiNi5wE
已经上传到云盘了，包括导出前的模型，导出后的模型，以及之前用到的一些图片，仅上传了decoupled seg

**Comment by DXVVV** [comment]
有更新吗

**Comment by DXVVV** [comment]
ping
