### ISSUE TITLE
How to generate predictions with label ID's (single channel uint8 image)?

### ISSUE THREAD

**Issue by khaep** [PaddlePaddle/PaddleSeg#1555]
Hello all,

how is it possible to create predictions of a trained modle in label ID format?
Something like a single channel  uint8 image where each pixel contains a class ID. 

Creating "added predictions" and "pseudo color predictions" with [predict.py](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/docs/predict/predict.md#prediction) works perfectly.

But for further algorithms, the single channel label ID images are needed.

Thaks for help and hints.

**Comment by haoyuying** [comment]
you can get output from https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/paddleseg/core/predict.py#L120 
 and utilize np.argmax to generate prediction.

**Comment by khaep** [comment]
Thank you, for the reply. 
I added the following lines to

* [~/core/predict.py#L86](https://github.com/PaddlePaddle/PaddleSeg/blob/b413969ab3601c3fef152df332d514ac39cb8cc5/paddleseg/core/predict.py#L86)
```shell
labelId_saved_dir = os.path.join(save_dir, 'labelId_prediction')
```

*  [ ~/core/predict.py#L136](https://github.com/PaddlePaddle/PaddleSeg/blob/b413969ab3601c3fef152df332d514ac39cb8cc5/paddleseg/core/predict.py#L136)
```shell
         # save labelId image
         labelId_image_path = os.path.join(labelId_saved_dir, im_file)
         mkdir(labelId_image_path)
         cv2.imwrite(labelId_image_path, pred)
```

That worked for me.
