### ISSUE TITLE
运行demo报错

### ISSUE THREAD

**Issue by gxcLe** [PaddlePaddle/PaddleSeg#156]
测试 python pdseg/train.py --cfg configs/unet_optic.yaml --use_gpu 报错。 

I0120 16:05:08.668180 43087 parallel_executor.cc:421] The number of CUDAPlace, which is used in ParallelExecutor, is 1. And the Program will be copied 1 copies
I0120 16:05:08.684178 43087 build_strategy.cc:363] SeqOnlyAllReduceOps:0, num_trainers:1
I0120 16:05:08.699754 43087 parallel_executor.cc:285] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0120 16:05:08.710417 43087 parallel_executor.cc:368] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
W0120 16:05:09.042984 43170 init.cc:206] *** Aborted at 1579507509 (unix time) try "date -d @1579507509" if you are using GNU date ***
W0120 16:05:09.044806 43170 init.cc:206] PC: @                0x0 (unknown)
W0120 16:05:09.044921 43170 init.cc:206] *** SIGSEGV (@0x0) received by PID 43087 (TID 0x7f265eee8700) from PID 0; stack trace: ***
W0120 16:05:09.046382 43170 init.cc:206]     @     0x7f26a8e286d0 (unknown)
W0120 16:05:09.047801 43170 init.cc:206]     @                0x0 (unknown

**Comment by ZeyuChen** [comment]
能否提供Paddle的版本号和PaddleSeg的代码版本？
以及您的操作系统和硬件，GPU卡、CUDA和CUDNN版本信息

**Comment by gxcLe** [comment]
感谢您的快速回复，刚才查了一下是cudnn版本的问题，已经解决，thx！
