### ISSUE TITLE
Cannot find the folder: pretrained_model

### ISSUE THREAD

**Issue by twang15** [PaddlePaddle/PaddleSeg#1560]
Hi,

I am reading the documentation here:
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.1.0/docs/usage.md

it says 

    # 下载预训练模型并进行解压
    python pretrained_model/download_model.py unet_bn_coco

however, there is no such a directory.
Could anyone help locate this directory? Or is there a problem in my installation?

Thanks

**Comment by juncaipeng** [comment]
The version of the above docs is release/v.0.1.0. Please check the version of the PaddleSeg you downloaded and make sure the version of docs and PaddleSeg is the same. Besides, we suggest you use the latest version of Paddleseg.
