### ISSUE TITLE
paddle2onnx : There's 2 ops  are not supported yet

### ISSUE THREAD

**Issue by zhangxianjie1314** [PaddlePaddle/PaddleSeg#1561]
![image](https://user-images.githubusercontent.com/73931078/142710344-ad3838ba-fe79-4638-8a39-04909fc2dd26.png)
![image](https://user-images.githubusercontent.com/73931078/142710360-a27a07f0-86be-4362-ade4-02efdf951097.png)

**Comment by juncaipeng** [comment]
Hi, the quantized model is not supported for exporting to ONNX for now.  You can try to export the FP32 model.
