### ISSUE TITLE
ValueError: Target(Tensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,        [9])) is out of class_dimension's upper bound(1)

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/PaddleSeg#1562]
window10
conda 创建的 python 3.8环境
分割：bisenet_optic_disc
训练：
train.py --config configs/quick_start/bisenet_optic_disc_512x512_treeboot.yml  --do_eval --use_vdl  --save_interval 500  --save_dir output
报错：
2021-11-20 18:30:21 [INFO]	
------------Environment Information-------------
platform: Windows-10-10.0.19043-SP0
Python: 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)]
Paddle compiled with cuda: True
NVCC: Not Available
cudnn: 8.1
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: NVIDIA GeForce']
GCC: gcc (i686-posix-sjlj, built by strawberryperl.com project) 4.9.2
PaddlePaddle: 2.2.0
OpenCV: 4.5.2
------------------------------------------------
2021-11-20 18:30:22 [INFO]	
---------------Config Information---------------
batch_size: 4
iters: 1000
loss:
  coef:
  - 1
  - 1
  - 1
  - 1
  - 1
  types:
  - ignore_index: 255
    type: CrossEntropyLoss
lr_scheduler:
  end_lr: 0
  learning_rate: 0.01
  power: 0.9
  type: PolynomialDecay
model:
  pretrained: null
  type: BiSeNetV2
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 4.0e-05
train_dataset:
  dataset_root: data/custom_dataset
  mode: train
  transforms:
  - target_size:
    - 512
    - 512
    type: Resize
  - type: RandomHorizontalFlip
  - type: Normalize
  type: OpticDiscSeg
val_dataset:
  dataset_root: data/custom_dataset
  mode: val
  transforms:
  - type: Normalize
  type: OpticDiscSeg
------------------------------------------------
W1120 18:30:22.069537 19108 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.0
W1120 18:30:22.069537 19108 device_context.cc:465] device: 0, cuDNN Version: 8.1.
C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle\nn\layer\norm.py:652: UserWarning: When training, we now always track global mean and variance.
  warnings.warn(
Traceback (most recent call last):
  File "D:/vison_software/paddle/PaddleSeg-release-2.3/train.py", line 198, in <module>
    main(args)
  File "D:/vison_software/paddle/PaddleSeg-release-2.3/train.py", line 176, in main
    train(
  File "D:\vison_software\paddle\PaddleSeg-release-2.3\paddleseg\core\train.py", line 192, in train
    loss_list = loss_computation(
  File "D:\vison_software\paddle\PaddleSeg-release-2.3\paddleseg\core\train.py", line 51, in loss_computation
    loss_list.append(losses['coef'][i] * loss_i(logits, labels))
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\vison_software\paddle\PaddleSeg-release-2.3\paddleseg\models\losses\cross_entropy_loss.py", line 85, in forward
    loss = F.cross_entropy(
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle\nn\functional\loss.py", line 1669, in cross_entropy
    raise ValueError(
ValueError: Target(Tensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [9])) is out of class_dimension's upper bound(1)

Process finished with exit code 1

**Comment by juncaipeng** [comment]
cross_entropy_loss输入的labe有如下要求：
![image](https://user-images.githubusercontent.com/52520497/142790199-07529ffd-b911-4b9a-a172-ef10d7fe516f.png)
链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/functional/cross_entropy_cn.html#cross-entropy

你输入的labe维度是[1]，数值是9，估计是没有加batch维度吧  [1] -> [1, 1] ?

**Comment by stduent-vehicle** [comment]
你可以把labels的值先打印出来，paddleseg好像要求labels是按照 [0,1,2,3,4...]的顺序生成

链接：(https://github.com/PaddlePaddle/PaddleSeg/issues/1569)

**Comment by xinsuinizhuan** [comment]
已经找到问题，数据集的问题。感谢

**Comment by BJHYZJ** [comment]
还有可能是“\”和“/”转换的问题

**Comment by ziyuwzf** [comment]
> 已经找到问题，数据集的问题。感谢

怎么解决的，我也遇到了。数据集已经按照要求处理成单通道的图像了。

**Comment by dongshen6** [comment]
> 已经找到问题，数据集的问题。感谢
是什么问题呀，我也遇到了这个问题 应该是数据集的问题

**Comment by dongshen6** [comment]
> cross_entropy_loss输入的labe有如下要求： ![image](https://user-images.githubusercontent.com/52520497/142790199-07529ffd-b911-4b9a-a172-ef10d7fe516f.png) 链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/functional/cross_entropy_cn.html#cross-entropy
> 
> 你输入的labe维度是[1]，数值是9，估计是没有加batch维度吧 [1] -> [1, 1] ?

这个应该怎么改呢，数据集label我也处理成单通道的了

**Comment by dongshen6** [comment]
> > cross_entropy_loss输入的labe有如下要求： ![image](https://user-images.githubusercontent.com/52520497/142790199-07529ffd-b911-4b9a-a172-ef10d7fe516f.png) 链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/functional/cross_entropy_cn.html#cross-entropy
> > 你输入的labe维度是[1]，数值是9，估计是没有加batch维度吧 [1] -> [1, 1] ?
> 
> 这个应该怎么改呢，数据集label我也处理成单通道的了

兄弟们找到原因了，是因为paddleseg的数据集要求像素点的值均从0，1，2这样递增来区分像素点，所以要对数据集进行修改。
