### ISSUE TITLE
EISeg 0.4.0进去之后没反应，过了之后就退出来了的问题

### ISSUE THREAD

**Issue by Wangwk1** [PaddlePaddle/PaddleSeg#1564]
![29X)TZJ$36D(HKVDY)LWC{7](https://user-images.githubusercontent.com/94838931/142853309-890b325e-003f-4272-936a-3b303ecd4d29.png)
![B~ 22 6I9FBVHP7E0JPL_EF](https://user-images.githubusercontent.com/94838931/142853316-a45e2811-52bc-4efa-a2f5-8c1818d02074.png)
paddle,eiseg也都按要求安装了，可就是进去之后没有反应。

感谢，问题已解决。我之前装的是0.4.0的，按理说应该没问题的。最后我把它卸载又重装了一遍，发现就可以跑了。

**Comment by haoyuying** [comment]
您好，请问您使用的paddle的版本是多少呢，是通过什么方式安装的eiseg，以及什么操作会触发该闪退？
