### ISSUE TITLE
EISeg0.3之后的版本，切换下一张存在闪退

### ISSUE THREAD

**Issue by Zachary-ZCH** [PaddlePaddle/PaddleSeg#1567]
偶发的保存完当前标注图片，点击切换到下一张的时候，偶发闪退而且没有报错。

**Comment by haoyuying** [comment]
您好，请问您在切换图片之前做了什么操作呢，可以把闪退后的终端信息截一张图给我们吗，方便排查问题。并给出具体的paddle及eiseg版本号。

**Comment by Zachary-ZCH** [comment]
1、按了空格键，在按F下一张就闪退，偶现非必现。
2、eiseg  版本：0.4.0.1 paddle 2.2.0。
3、闪退时控制台log:
anning True
0.5221112477058142 0. 7831668715587212 54. 0 340. 0 44. 0 417.0 10.0 -77.0 77.0 10. 0 77. 64663547121665
dir 0.9916720735252417 0. 1287885809773041
hover in
0.4337040129329315 0. 6505560193993972 44. 0 417.0 0.0 599.0 44. 0 -182. 0 182. 0 44. 0 187. 2431574183687
dir 0.9719981360565632 0. 23498856036532295
hover in
(eiseg_new) C: \Users\xx. x>

**Comment by haoyuying** [comment]
您好，可以安装0.4.0版本，0.4.0.x这些是我们之前一些测试版本，会有闪退问题。如果0.4.0还有此类问题，请回复我一下，我们这边排查下bug原因。

**Comment by Zachary-ZCH** [comment]
0.4.0 应该也有同样的问题，包括0.3.x都会有，0.2.x版本不会闪退。

**Comment by ff12343** [comment]
> 您好，可以安装0.4.0版本，0.4.0.x这些是我们之前一些测试版本，会有闪退问题。如果0.4.0还有此类问题，请回复我一下，我们这边排查下bug原因。

同样遇到标注保存之后，点击下一张图片，闪退的问题。版本是paddle-relese-2.3 附带的EISeg0.3.0。在图像size=2600*2000时，百分百闪退。下面是闪退的后台：
![image](https://user-images.githubusercontent.com/42758082/144776346-3965da3e-a993-4c9e-b997-e27073f1eb30.png)
在图像size=2000*1600时，极小的概率会闪退

**Comment by ff12343** [comment]
还有标注完成保存但结果正在保存中时，点击下一张会触发闪退

**Comment by haoyuying** [comment]
收到，我们会仔细排查这个问题，感谢反馈

**Comment by fangyuan2017** [comment]
我只有在放大缩小后再进行保存操作才会闪退  如果不放大缩小就不会闪退

**Comment by haoyuying** [comment]
收到，我们会在近期发一个新包来修复这些问题。

**Comment by geoyee** [comment]
@fangyuan2017 你可试试 https://github.com/PaddleCV-SIG/EISeg/tree/develop ，我们尝试修复了这个缩放引起的闪退问题，如果还有此问题，欢迎反馈

**Comment by geoyee** [comment]
> @fangyuan2017 你可试试 https://github.com/PaddleCV-SIG/EISeg/tree/develop ，我们尝试修复了这个缩放引起的闪退问题，如果还有此问题，欢迎反馈

@Zachary-ZCH @fangyuan2017 也欢迎大家试试这个版本的，如果还存在闪退的问题，希望能再次得到反馈
