### ISSUE TITLE
labels值异常：貌似PaddleSeg要求生成的labels值需要按照（0，1，2，3，4...）的顺序来生成

### ISSUE THREAD

**Issue by stduent-vehicle** [PaddlePaddle/PaddleSeg#1569]
如下图所示：
1. 样本图像为jpg格式，labels图像为png格式，设置类别个数为5；
2. 加载后输出的类别变成了 {0，15，190}。如何能变成（0，1，2，3，4）的labels？还需要自己再手动处理吗?
![微信图片_20211124171310](https://user-images.githubusercontent.com/37319219/143210567-b1ce8917-faa8-434f-a18c-0091bb523fb2.png)

**Comment by shiyutang** [comment]
Please convert your labels into the 0,1,2,3..., you can refer to the `following` pseudo-code snippet.

```
label = PIL.Image.open("image.png")
label = numpy.array(label)
cnts = len(set(label))
cnt = 0
for I in set(label):
    label[label==i] = cnt 
    cnt += 1
PIL.Image.write(label, "label_path")
```

**Comment by Niki173** [comment]
> 如下图所示：
> 
> 1. 样本图像为jpg格式，labels图像为png格式，设置类别个数为5；
> 2. 加载后输出的类别变成了 {0，15，190}。如何能变成（0，1，2，3，4）的labels？还需要自己再手动处理吗?
>    ![微信图片_20211124171310](https://user-images.githubusercontent.com/37319219/143210567-b1ce8917-faa8-434f-a18c-0091bb523fb2.png)

你好，请问如何把图片里面的标签数值输出，就是图片上的[0,15,190],如何通过代码实现

**Comment by shiyutang** [comment]
Sorry, I don't know what do you mean

**Comment by shiyutang** [comment]
This issue has no response for a long time. I will close it now. If you have further questions, please reopen it.
