### ISSUE TITLE
这段是什么环境下的代码，在cmd的窗口里执行不了？

### ISSUE THREAD

**Issue by sonic-github** [PaddlePaddle/PaddleSeg#157]
paddle seg快速入门中提到如下代码,这段是什么环境下的代码，在cmd的窗口里执行不了？

# 指定GPU卡号（以0号卡为例）
export CUDA_VISIBLE_DEVICES=0
# 训练
python pdseg/train.py --cfg configs/unet_optic.yaml \
                      --use_gpu \
                      --do_eval \
                      --use_tb \
                      --tb_log_dir train_log \
                      BATCH_SIZE 4 \
                      SOLVER.LR 0.001

**Comment by ZeyuChen** [comment]
请问您是不是Windows操作系统，如果是而且没有多GPU环境，默认不需要
`export CUDA_VISIBLE_DEVICES=0`

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。
