### ISSUE TITLE
EISeg总是存在左键点击之后闪退的情况

### ISSUE THREAD

**Issue by Look4-you** [PaddlePaddle/PaddleSeg#1570]
![image](https://user-images.githubusercontent.com/44594124/143210694-8f4b3177-c3d3-4214-b0b0-24eb4e57cccb.png)

如上图，用着用着出现闪退，重新打开软件之后，没标完几张图，又出现闪退的情况，请开发团队帮忙看看问题呀！

**Comment by Look4-you** [comment]
windows版本的0.3.0

**Comment by haoyuying** [comment]
报错信息是内存不够了，看下把其他进程杀死之后会不会出现这个问题。
