### ISSUE TITLE
模型训练：自定义数据背景像素占比太多，是否可以设置背景像素标签值为255来训练？

### ISSUE THREAD

**Issue by stduent-vehicle** [PaddlePaddle/PaddleSeg#1575]
自定义数据，背景像素占比太多，类别总共有5类，但分割效果很不好，分割结果只有一种。

是否可以把背景像素标签值设置为255，类别数变为4来训练？

**Comment by HongShiKuan** [comment]
肯定不可以忽略哈，详细解释参看下面链接里面的解释，之前刚好看到过。
[相关链接](https://github.com/PaddlePaddle/PaddleSeg/issues/1055)

**Comment by stduent-vehicle** [comment]
谢谢，但是把背景像素也当作一类之后重新训练，模型预测结果全部为一类（背景像素对应类别）。这个有什么好的建议吗？

**Comment by shiyutang** [comment]
This is a problem caused by class imbalance. You can search for relevant solutions online. Basic solutions include adding weight to your loss, using dice loss, foreground image augmentation, and so on.

**Comment by stduent-vehicle** [comment]
> This is a problem caused by class imbalance. You can search for relevant solutions online. Basic solutions include adding weight to your loss, using dice loss, foreground image augmentation, and so on.

Thanks, I will try it.
