### ISSUE TITLE
在Cityscapes数据集上训练DeepLabV3P网络mIOU过低！

### ISSUE THREAD

**Issue by HongShiKuan** [PaddlePaddle/PaddleSeg#1577]
显卡为RTX6000，使用**PaddleSeg2.3**版本，配置文件为：**deeplabv3p_resnet101_os8_cityscapes_1024x512_80k（无修改）**，Cityscapes数据集已经运行过conver_cityscapes.py文件，生成 **labelTrainIds.png在gtFine目录。具体数据集目录结构如下图所示。
![image](https://user-images.githubusercontent.com/45912889/143581168-a25a1823-28c3-4c65-ac0b-216bcf8f34e8.png)
![image](https://user-images.githubusercontent.com/45912889/143581940-964a00cd-3ea7-4b75-8547-e266be63d6d8.png)
![image](https://user-images.githubusercontent.com/45912889/143581983-a060717b-6052-4d15-9bd5-bbbc7f022cf9.png)
训练结果日志文件如下图所示：
![image](https://user-images.githubusercontent.com/45912889/143581331-c193627c-7200-4b69-9273-f24c67eed7f5.png)
训练了**46个epoch**，**mIOU才能达到0.474**。同样的查看了官网提供的日志文件[链接如下](https://bj.bcebos.com/paddleseg/dygraph/cityscapes/deeplabv3p_resnet101_os8_cityscapes_1024x512_80k/train.log)，发现训练两个epoch附近就能达到50多的mIOU。
请问这是什么问题呀？

**Comment by juncaipeng** [comment]
请问Paddle版本是？是使用4卡训练吗？ 可以尝试换一个模型训练一下，看mIoU是否准确，比如STDC1Seg模型，速度会比较快。

**Comment by HongShiKuan** [comment]
1、paddlepaddle版本为2.2
2、单卡RTX6000训练
3、是否可以这样理解，官网提供的模型是用四卡v1000训练的。因为我是用单卡训练的，所以模型收敛速度没有那么快？不知道这样理解是否准确。

**Comment by HongShiKuan** [comment]
> 请问Paddle版本是？是使用4卡训练吗？ 可以尝试换一个模型训练一下，看mIoU是否准确，比如STDC1Seg模型，速度会比较快。

1、paddlepaddle版本为2.2
2、单卡RTX6000训练
3、是否可以这样理解，官网提供的模型是用四卡v1000训练的。因为我是用单卡训练的，所以模型收敛速度没有那么快？不知道这样理解是否准确。

**Comment by HongShiKuan** [comment]
> 请问Paddle版本是？是使用4卡训练吗？ 可以尝试换一个模型训练一下，看mIoU是否准确，比如STDC1Seg模型，速度会比较快。

1、paddlepaddle版本为2.2
2、单卡RTX6000训练
3、是否可以这样理解，官网提供的模型是用四卡v100训练的。因为我是用单卡训练的，所以模型收敛速度没有那么快？不知道这样理解是否准确。

**Comment by juncaipeng** [comment]
单卡训练，batch size小了4倍，学习率lr应该减小4倍，然后迭代次数iterations应该增大4倍。
而且batch size较小，一般最终精度会差一些。

**Comment by juncaipeng** [comment]
你可以多训练，多调参学习一下，先用小模型比如bisenet或者stdc1seg模型练练手。
