### ISSUE TITLE
EISeg标注以PaddleX进行实例分割报错

### ISSUE THREAD

**Issue by ff12343** [PaddlePaddle/PaddleSeg#1581]
EISeg标注Coco格式文件 以PaddleX进行实例分割报错：标注文件存在错误。
![image](https://user-images.githubusercontent.com/42758082/144183197-06270432-c751-4c49-9ecd-ca891a724a65.png)
之后，我独立运行报错的函数 `check_dataset` 提取 `annotations.json` 报错如下：
![image](https://user-images.githubusercontent.com/42758082/144183868-de856a3a-052b-4d0b-91c2-5f3d40d0df2a.png)
也就是PaddleX 因 EISeg标注无 `iscrowd` 项而报错
当我设置 `iscrowd=None` 跳过该项时，依旧报错： 
![image](https://user-images.githubusercontent.com/42758082/144185297-81359f35-579d-4835-9379-7be6abdb6168.png)
原因是EISeg标注的 '[area]': 0, '[bbox]': [0, 0, 0, 0]两个标注项为空，这在PaddleX中会报错。
不知道是我标注的问题还是EISeg不适配PaddleX的实例分割任务。
EISeg是develop版本，PaddleX是windows GUI版本

**Comment by haoyuying** [comment]
您好，可以使用该脚本进行转化：https://github.com/PaddlePaddle/PaddleSeg/blob/develop/EISeg/tool/eiseg2paddlex.py，使用方式如下https://github.com/PaddlePaddle/PaddleSeg/blob/develop/EISeg/docs/tools.md，
如果您有mask标注，area和bbox应该不会为0，看是否标注方式存在问题。如果是空白的mask，说明该张图片没有标注，认为是坏数据，需要标注或者将该图片删除。

**Comment by ff12343** [comment]
实例分割任务：EISeg标注无法直接导入PaddleX，需要将eiseg转换为coco。
我在develop/EISeg/tool/eiseg2coco.py的基础上，修改部分代码，可以实现eiseg导入paddlex，代码上传。
注意：EISeg0.3.0保存标注信息的width、height存反了，会导致bbox上传出错，这里eiseg2coco转换时会重新导入width、height。希望能尽快修复EISeg0.3.0存在的bug
[eiseg2coco.zip](https://github.com/PaddlePaddle/PaddleSeg/files/7647266/eiseg2coco.zip)

**Comment by sword-light** [comment]
我也看到了，新的eiseg0.4的版本会出现bbox为0的问题，eiseg0.3的版本不会，而且eiseg0.4的分割点坐标好像比eiseg0.3的要小，eiseg0.4的标注文件用eiseg0.3打开，分割的多边形会在本应在的位置的左上方出现，是一个较小的相似图形，联想到eiseg0.4的交互速度快于0.3，我怀疑eiseg0.4进行了图片resize的操作，分割点的坐标却没有放大。
