### ISSUE TITLE
Paddleseg是否支持将训练日志文件输入到output文件中？

### ISSUE THREAD

**Issue by geoexploring** [PaddlePaddle/PaddleSeg#1589]
我看见paddleseg有`log.py`文件，但是不支持将训练日志文件输入到output文件中（比如生成一个`log.txt`文件），是否这是隐藏功能呢？

谢谢

**Comment by juncaipeng** [comment]
没有。你可以使用nohup python train.py *** 2>&1 >log.txt 将输出保存到log.txt文件中
