### ISSUE TITLE
CUDNN_STATUS_EXECUTION_FAILED error

### ISSUE THREAD

**Issue by bindulam** [PaddlePaddle/PaddleSeg#159]
Got this Error when Running sh run_train.sh

Error Message Summary:
----------------------
Error: CUDNN_STATUS_EXECUTION_FAILED at (/paddle/paddle/fluid/operators/conv_cudnn_op.cu:288)
  [operator < conv2d > error]

![image](https://user-images.githubusercontent.com/48243646/73922286-e505cb80-48ee-11ea-8981-0b09714e7262.png)
![image](https://user-images.githubusercontent.com/48243646/73922309-f0f18d80-48ee-11ea-9d62-dbef2e8d126e.png)
![image](https://user-images.githubusercontent.com/48243646/73922975-19c65280-48f0-11ea-9c82-a6c4fa650bf1.png)

**Comment by ZeyuChen** [comment]
Please check whether cuDNN is installed correctly.
Could you advise your Paddle version and CUDA environment?

**Comment by bindulam** [comment]
![image](https://user-images.githubusercontent.com/48243646/74714461-98a47f00-5250-11ea-879d-65a7a241b3d0.png)
![image](https://user-images.githubusercontent.com/48243646/74714513-afe36c80-5250-11ea-92fe-c09d059f8414.png)

**Comment by nepeplwu** [comment]
This issue has not been updated in the last three months. We will close this issue. Please reopen it if necessary.
