### ISSUE TITLE
按照指定的流程在大量数据集上训练模型后，得到的效果较差，作为一个新手，希望有人能帮我解答。

### ISSUE THREAD

**Issue by BJHYZJ** [PaddlePaddle/PaddleSeg#1592]
![61e0c74a1652362625b9644b5bc30ba](https://user-images.githubusercontent.com/74347732/144577590-f5f698a0-1934-42e1-97bb-829177d79c31.png
![e86f768f1d2859d5aadcec3dfbc1186](https://user-images.githubusercontent.com/74347732/144577604-0d64771c-31ff-4f55-b5be-d692a1414107.png)
![1c9474b97905d9ee44b78ebe3fe9ce1](https://user-images.githubusercontent.com/74347732/144577617-f6275472-c46b-4bf6-8bd8-d4457bffb519.png)
)

**Comment by juncaipeng** [comment]
额  这个需要你自己摸索排查一下，你给出的信息太少了，你可以提供多一些信息
