### ISSUE TITLE
MODNet的预训练模型对应的优化器参数pdopt文件能否提供?

### ISSUE THREAD

**Issue by yangjian1218** [PaddlePaddle/PaddleSeg#1598]
想接着训练.

**Comment by wuyefeilin** [comment]
你可以直接用我们提供的模型在你的数据集上进行微调哈，记得学习率调小一些

**Comment by yangjian1218** [comment]
> 你可以直接用我们提供的模型在你的数据集上进行微调哈，记得学习率调小一些

可是没有pdopt文件,怎么接着训练?  在配置modenet_hrnet_18.yml文件中:model下增加了一行pretrained: modnet-hrnet_w18.pdparams.训练了20000轮效果还是很差.这是从头训练了么?

**Comment by wuyefeilin** [comment]
学习率调小一些， 比如：0.0001
