### ISSUE TITLE
有iOS端端人像分割demo吗？仓库里提供的demo是图片的人像分割，有视频的吗？

### ISSUE THREAD

**Issue by xiakegan05** [PaddlePaddle/PaddleSeg#1599]
如题

**Comment by LutaoChu** [comment]
你好，目前没有这块demo。只有检测和分类的ios demo。可以参考https://paddle-lite.readthedocs.io/zh/latest/demo_guides/ios_app_demo.html

你说的是视频分割部署demo吧，目前还没有
