### ISSUE TITLE
自己训练的模型可以再EISeg里使用吗？

### ISSUE THREAD

**Issue by ggdonald** [PaddlePaddle/PaddleSeg#1600]
EISeg自带的模型去label我的一批图片，效果不是很好。

所以我自己label了一些图片然后用paddleseg训练了，想把训练好的模型丢进EISeg里面使用，去标注其他图片看看效果。
我训练用的网络配置是：OCRNet + hrnet_w48 + 图片size640x512

但是我发现训练好的模型model.pdparams放进EISeg3里面，会显示“权重和模型不匹配。请确保指定的权重和模型对应”，请问这个要怎么配置？
还有就是我把模型转换成静态的model.pdiparams，然后用EISeg4去运行，加载模型没有问题，但是读取完图片开始标注，一点鼠标左键程序就直接死机退出。请问这个又需要怎么配置？

**Comment by haoyuying** [comment]
您好，这种方式是不可行的，交互式分割的模型有自己的训练方法，和语义分割等训练方式不同。

**Comment by ggdonald** [comment]
> 您好，这种方式是不可行的，交互式分割的模型有自己的训练方法，和语义分割等训练方式不同。

那请问eiseg使用的交互式分割模型的训练配置，有没有公开给用户自己定义数据集，然后自己训练的程序或者方法教程呢？

**Comment by haoyuying** [comment]
目前还没有公开训练代码，目前只能使用我们提供的一些垂类模型。未来将会公开训练代码，敬请期待。

**Comment by RKYSHLM** [comment]
> 目标之前还没有公开训练代码，目标之前只能使用我们提供的一些垂类模型。未来将会公开训练代码，敬请期待。
您好，请问现在有没有更新训练的代码？
