### ISSUE TITLE
蒸馏训练有bug

### ISSUE THREAD

**Issue by ChenDirk** [PaddlePaddle/PaddleSeg#1602]
在PaddleSeg/slim/distill/distill_config.py 文件里面，from paddleslim.dygraph.dist import AdaptorBase失败，我也去paddleslim里面看了一下，确实没有这个类，请问一下文件里面对应的是哪个版本呢？顺便问一下，paddleslim里面的描述到现在还是蒸馏只支持静态图，是不是也有问题？

**Comment by ChenDirk** [comment]
我的版本是paddlepaddle-gpu==2.2.0 paddleslim==2.2.0

**Comment by juncaipeng** [comment]
请参考[文档](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/docs/slim/distill/distill.md#21-%E7%8E%AF%E5%A2%83%E5%87%86%E5%A4%87)切换paddleslim到指定分支：
![image](https://user-images.githubusercontent.com/52520497/145183128-c1fcf6c0-6d90-4483-8ded-f23fc0ead422.png)

可以支持动态图。

**Comment by ChenDirk** [comment]
感谢，实测可以正常训练，也希望后续能统一一下paddleslim的版本和描述。

**Comment by curryJ** [comment]
> 感谢，实测可以正常训练，也希望后续能统一一下paddleslim的版本和描述。

您好 为什么我不能git reset呢，我执行git reset --hard 15ef0c7dcee5a622787b7445f21ad9d1dea0a933会报错 

谢谢

**Comment by juncaipeng** [comment]
先尝试fetch一下吧

**Comment by guoxuntao** [comment]
楼主你解决了吗

**Comment by guoxuntao** [comment]
> 我的版本是paddlepaddle-gpu==2.2.0 paddleslim==2.2.0

我现在也碰到这个问题，还没有解决

**Comment by ChenDirk** [comment]
> > 我的版本是paddlepaddle-gpu==2.2.0 paddleslim==2.2.0
> 
> 我现在也碰到这个问题，还没有解决

参考一下军才的回复，需要使用指定分支。
