### ISSUE TITLE
Cannot run for resume_model, show error KeyError: 'LR_Scheduler'

### ISSUE THREAD

**Issue by SamYokai** [PaddlePaddle/PaddleSeg#1603]
This is what I had run for resume_model and it show me:

/content/PaddleSeg
2021-12-08 09:15:04 [INFO]	
------------Environment Information-------------
platform: Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
Python: 3.7.12 (default, Sep 10 2021, 00:21:48) [GCC 7.5.0]
Paddle compiled with cuda: True
NVCC: Build cuda_11.1.TC455_06.29190527_0
cudnn: 7.6
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: Tesla K80']
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PaddlePaddle: 2.2.0
OpenCV: 4.1.2
------------------------------------------------
2021-12-08 09:15:04 [INFO]	
---------------Config Information---------------
batch_size: 1
iters: 10000
loss:
  coef:
  - 1
  types:
  - ignore_index: 255
    type: CrossEntropyLoss
lr_scheduler:
  end_lr: 0
  learning_rate: 6.0e-05
  power: 1
  type: PolynomialDecay
model:
  num_classes: 2
  type: SegFormer_B5
optimizer:
  beta1: 0.9
  beta2: 0.999
  type: AdamW
  weight_decay: 0.01
train_dataset:
  dataset_root: /content/dataset/16_products
  mode: train
  num_classes: 2
  train_path: /content/dataset/16_products/new_train.txt
  transforms:
  - target_size:
    - 1024
    - 512
    type: Resize
  - type: RandomHorizontalFlip
  - type: Normalize
  type: Dataset
val_dataset:
  dataset_root: /content/dataset/16_products
  mode: val
  num_classes: 2
  transforms:
  - target_size:
    - 1024
    - 512
    type: Resize
  - type: Normalize
  type: Dataset
  val_path: /content/dataset/16_products/new_val.txt
------------------------------------------------
W1208 09:15:04.096760  1609 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 3.7, Driver API Version: 11.2, Runtime API Version: 10.2
W1208 09:15:04.096843  1609 device_context.cc:465] device: 0, cuDNN Version: 7.6.
2021-12-08 09:15:07 [INFO]	Resume model from output/iter_4000/
Traceback (most recent call last):
  File "train.py", line 198, in <module>
    main(args)
  File "train.py", line 193, in main
    profiler_options=args.profiler_options)
  File "/content/PaddleSeg/paddleseg/core/train.py", line 101, in train
    start_iter = resume(model, optimizer, resume_model)
  File "/content/PaddleSeg/paddleseg/utils/utils.py", line 111, in resume
    optimizer.set_state_dict(opti_state_dict)
  File "<decorator-gen-215>", line 2, in set_state_dict
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/optimizer/optimizer.py", line 284, in set_state_dict
    self._learning_rate.set_dict(state_dict["LR_Scheduler"])
KeyError: 'LR_Scheduler'

------------------------------------------------------------------------------
the pdopt and pdparams files both inside output/iter_4000, the log also at there output/, but it cannot run for resume the train model. I just force to stop the train and straight away resume to train but it doesnt work for me. So want to ask where is the mistake I had did.... What problem actually I meet.

**Comment by SamYokai** [comment]
by the way, Im using Google Colab to run, so want to confirm if I download the pdopt and pdparams files together with the log and all txt file needed, and I run it by next day, is it can work if I can resume to train model since Google Colab using gpu will have usage limit per day if no mistake and if close it and open next day need run everything again, so I just want to ask that if I had downloaded the all necessary file for resume model, is it possible to run successful?

**Comment by shiyutang** [comment]
The problem is that you do not have the "LR_Scheduler" in your optimizer's state_dict. You should try to load the optimizer state_dict and see the keys, if you do not have "LR_Scheduler", you cannot load it.

**Comment by SamYokai** [comment]
> The problem is that you do not have the "LR_Scheduler" in your optimizer's state_dict. You should try to load the optimizer state_dict and see the keys, if you do not have "LR_Scheduler", you cannot load it.

ohhh, I see. But logically it suppose be there right? if not how it can train before? Sorry for lack of understanding. Also, how can  I check for the optimizer state_dict, and if it is missing then is it possible that I can add it or I need to run the whole model again?

**Comment by shiyutang** [comment]
It is likely that you didn't set the lr_scheduler configuration in your config file during training, otherwise, paddle will save the lr_scheduler for you. You can set the lr_scheduler like this, and you should be ready:
![image](https://user-images.githubusercontent.com/34859558/145199697-70fd4f38-f10a-467f-94a7-a5674a837746.png)

You can train your model without lr_scheduler setting, but you should not resume it with it.

You can load the model.opt file to see keys like this.
```
           ckpt_path = os.path.join(resume_model, 'model.pdopt')
            opti_state_dict = paddle.load(ckpt_path)
```

ps: remember to check the paddleseg version, and update it to paddleseg==2.3.0

**Comment by SamYokai** [comment]
> It is likely that you didn't set the lr_scheduler configuration in your config file during training, otherwise, paddle will save the lr_scheduler for you. You can set the lr_scheduler like this, and you should be ready: ![image](https://user-images.githubusercontent.com/34859558/145199697-70fd4f38-f10a-467f-94a7-a5674a837746.png)
> 
> You can train your model without lr_scheduler setting, but you should not resume it with it.
> 
> You can load the model.opt file to see keys like this.
> 
> ```
>            ckpt_path = os.path.join(resume_model, 'model.pdopt')
>             opti_state_dict = paddle.load(ckpt_path)
> ```
> 
> ps: remember to check the paddleseg version, and update it to paddleseg==2.3.0

ok understood, thank you for the information.

**Comment by shiyutang** [comment]
You are welcome.
