### ISSUE TITLE
modnet 的c++部署代码什么时候可以开源出来？

### ISSUE THREAD

**Issue by fengyanWang** [PaddlePaddle/PaddleSeg#1607]
你好！请问modnet的c++推理代码什么时候可以开源出来？目前我按照paddleseg.cc代码进行修改出来的结果有问题

**Comment by wuyefeilin** [comment]
感谢你的关注，我们会尽快开源出c++推理代码，如果你提前实现了，欢迎提pr给我们哈

**Comment by fengyanWang** [comment]
> 感谢你的关注，我们会尽快开源出c++推理代码，如果你提前实现了，欢迎提pr给我们哈

我使用paddlex的c++ api进行推理，推理结果和onnx的推理结果一致，但是存在问题是paddleX c++推理速度是400ms左右，而onnx  python推理只有120ms左右，后续我又用paddle lite c++进行推理，结果是500ms左右。

我用的模型是backbone为MobileNetV2，输入大小为256*256
硬件配置：i5-6500      windows10     visual studio 2017

![image](https://user-images.githubusercontent.com/36984088/145536955-3e610b33-38c5-4a2f-bd7f-1bd6236784d1.png)

**Comment by fengyanWang** [comment]
> 感谢你的关注，我们会尽快开源出c++推理代码，如果你提前实现了，欢迎提pr给我们哈

#include <gflags/gflags.h>
#include <string>
#include <vector>
#include <time.h>
#include "model_deploy/common/include/paddle_deploy.h"
#include "paddle/include/paddle_inference_api.h"
#include "yaml-cpp/yaml.h"
#include "opencv2/core.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/highgui.hpp"

using namespace std;

void test_printMat(const cv::Mat img_data) {
	for (int i = 0; i < img_data.rows; i++) {
		for (int j = 0; j < img_data.cols; j++) {
			cout << "i:" << i << "--" << "j:" << j << "--";
			cout << "B:" << img_data.at<cv::Vec3f>(i, j)[0] << "---";
			cout << "G:" << img_data.at<cv::Vec3f>(i, j)[1] << "---";
			cout << "R:" << img_data.at<cv::Vec3f>(i, j)[2] << endl;
		}
	}
}

//read and preprocess img
void read_process_image(cv::Mat& img_data, const int input_size=256){
	
	const float mean = 0.5;
	const float std = 0.5;

	/*int raw_img_w = img_data.cols;
	int raw_img_h = img_data.rows;*/
	cv::cvtColor(img_data, img_data, cv::COLOR_BGR2RGB);

	//resize img to target size
	/*int short_size = raw_img_w < raw_img_h ? raw_img_w : raw_img_h;
	float scale = input_size / (short_size * 1.0);
	int new_img_w = int(raw_img_w * scale);
	int new_img_h = int(raw_img_h * scale);*/
	cv::resize(img_data, img_data, cv::Size(input_size, input_size));

	//normalize
	img_data.convertTo(img_data, CV_32F, 1.0 / 255, 0);
	img_data = (img_data - mean) / std;

}

//swap the channel
void hwc_img_2_chw_data(const cv::Mat& hwc_img, float* data) {
	int rows = hwc_img.rows;
	int cols = hwc_img.cols;
	int chs = hwc_img.channels();
	for (int i = 0; i < chs; ++i) {
		cv::extractChannel(hwc_img, cv::Mat(rows, cols, CV_32FC1, data + i * rows * cols), i);
	}
}

//load model
std::shared_ptr<paddle_infer::Predictor> create_predictor(const string model_path , 
	const string params_path , bool use_mkldnn=true , bool use_gpu=false , bool use_trt=false) {

	paddle_infer::Config infer_config;
	infer_config.SetModel(model_path, params_path);
	infer_config.EnableMemoryOptim(); 

	if (use_gpu) {
		cout << "use GPU ...." << endl;
		infer_config.EnableUseGpu(100, 0);
		if (use_trt) {
			infer_config.EnableTensorRtEngine(1 << 20, 1, 3, paddle_infer::PrecisionType::kFloat32, false, false);
		}
	}
	else {
		cout << "use CPU ...." << endl;
		if (use_mkldnn) {
			infer_config.SetCpuMathLibraryNumThreads(8);
		}
	}

	auto predictor = paddle_infer::CreatePredictor(infer_config);
	return predictor;
}


int main(void) {

	//load model
	string model_path = "F:\\project\\pythonProject\\dl_framework\\cv\\PaddleX\\deploy\\cpp\\build_vs2017_x64\\demo\\models\\model.pdmodel";
	string params_path = "F:\\project\\pythonProject\\dl_framework\\cv\\PaddleX\\deploy\\cpp\\build_vs2017_x64\\demo\\models\\model.pdiparams";
	auto predictor = create_predictor(model_path, params_path);

	clock_t start, end;
	
	//read img
	string img_path = "F:\\project\\pythonProject\\dl_framework\\cv\\PaddleX\\deploy\\cpp\\build_vs2017_x64\\demo\\imgs\\1.jpg";
	cv::Mat img_data = cv::imread(img_path, cv::IMREAD_COLOR);
	int raw_img_w = img_data.cols;
	int raw_img_h = img_data.rows;

	//img preprocess
	read_process_image(img_data);
	int rows = img_data.rows;
	int cols = img_data.cols;
	int chs = img_data.channels();
	cout << "rows:" << rows << " cols:" << cols << " chs:" << chs << endl;
	vector<float> input_data(1 * chs * rows * cols, 0.0f);
	hwc_img_2_chw_data(img_data, input_data.data());


	//set input
	auto input_names = predictor->GetInputNames();
	auto input_t = predictor->GetInputHandle(input_names[0]);
	vector<int> input_shape = { 1, chs, rows, cols };
	input_t->Reshape(input_shape);
	input_t->CopyFromCpu(input_data.data());

	//run 
	start = clock();
	predictor->Run();
	end = clock();
	std::cout << "time = " << (double(end - start) / CLOCKS_PER_SEC) * 1000 << "ms" << std::endl;
	
	//postprocess
	auto output_names = predictor->GetOutputNames();
	auto output_t = predictor->GetOutputHandle(output_names[0]);
	vector<int> output_shape = output_t->shape();
	int out_num = accumulate(output_shape.begin(), output_shape.end(), 1,std::multiplies<int>());
	
	vector<float> out_data(out_num);
	output_t->CopyToCpu(out_data.data());
	predictor->ClearIntermediateTensor();
	predictor->TryShrinkMemory();


	vector<uint8_t> out_data_u8(out_num);
	for (int i = 0; i < out_num; i++) {		
		out_data_u8[i] = static_cast<uint8_t>(out_data[i]*255);
	}

	cv::Mat out_gray_img(output_shape[2], output_shape[2], CV_8UC1, out_data_u8.data());
	
	cv::Mat out_eq_img;
	cv::equalizeHist(out_gray_img, out_eq_img);
	cv::resize(out_eq_img, out_eq_img, cv::Size(raw_img_w, raw_img_h));


	cv::imwrite("out_img.jpg", out_eq_img);

	cout << "Finish" << endl;
	
	return 0;
}


这是paddlex的推理部分代码，能力有限，写的不是很好，但是结果是没问题的

**Comment by juncaipeng** [comment]
你好，paddlex c++和onnx python推理是在GPU还是CPU，是否开启MKLDNN，是否使用了trt？
通常相同情况下，大模型使用paddle推理和onnx推理，速度差不多，小模型会差别大一点点。

**Comment by fengyanWang** [comment]
> 你好，paddle c++ 和 onnx  python 都是针对CPU的，paddle c++开启了MKLDNN，未使用trt，请问开启MKLDNN这个会对结果影响吗？如何解决这个问题？望回复，谢谢！

**Comment by juncaipeng** [comment]
开启mkldnn，通常会针对cpu进行加速，你可以尝试一下不开启mkldnn试试。
此外，这个耗时是纯预测时间吗？ paddle预测和onnx预测的线程数是一致的吗？ 一般不会存在如此大的差异。
