### ISSUE TITLE
PaddleSeg的requirements.txt中opencv-python的问题

### ISSUE THREAD

**Issue by yangrisheng** [PaddlePaddle/PaddleSeg#1612]
PaddleSeg的requirements.txt中opencv-python的问题。
清华源中没有4.5.2.54这个版本。建议修改下
`ERROR: Could not find a version that satisfies the requirement opencv-python==4.5.2.54 (from paddleseg==2.3.0) (from versions: 3.4.0.14, 3.4.2.17, 3.4.3.18, 3.4.4.19, 3.4.5.20, 3.4.6.27, 3.4.7.28, 3.4.8.29, 3.4.9.31, 3.4.9.33, 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.15.55, 3.4.16.57, 3.4.16.59, 4.0.0.21, 4.0.1.23, 4.0.1.24, 4.1.0.25, 4.1.1.26, 4.1.2.30, 4.2.0.32, 4.2.0.34, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.3.56, 4.5.4.58, 4.5.4.60)
ERROR: No matching distribution found for opencv-python==4.5.2.54 (from paddleseg==2.3.0)`

**Comment by juncaipeng** [comment]
好的，我们确认一下。

**Comment by juncaipeng** [comment]
已经提pr修复，移除opencv版本要求
