### ISSUE TITLE
载入的deeplabv3p_Xception65_cityscapes权重不对

### ISSUE THREAD

**Issue by curryJ** [PaddlePaddle/PaddleSeg#1614]
您好，我按照配置文件的配置，构建出了deeplabv3p_Xception65_cityscapes模型，但是载入[model zoo](https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.1.0/docs/model_zoo.md)给出的权重，载入之后提示权重文件不对
![image](https://user-images.githubusercontent.com/23001027/145764926-40d1ee27-377f-4b28-9fb3-2627b4d57ffa.png)
![image](https://user-images.githubusercontent.com/23001027/145764942-f35a5a94-2e54-471c-a544-e89a90fe095a.png)
![image](https://user-images.githubusercontent.com/23001027/145765003-16734989-314d-4ff6-8f3b-36eabeb4f691.png)
请问是如何使用官网给出的模型来evaluate呢，谢谢

**Comment by juncaipeng** [comment]
你好，你参考的model-zoo版本是0.1，目前最新版本是2.3，请使用最新的代码和文档。

**Comment by curryJ** [comment]
> 你好，你参考的model-zoo版本是0.1，目前最新版本是2.3，请使用最新的代码和文档。

谢谢 请问现在2.3的deeplabv3p的backbone，支持mobilenet吗，我看现在的配置文件的backbone全都是resnet
![image](https://user-images.githubusercontent.com/23001027/145922798-32f3e8ba-f510-4ec5-8ac1-b11719880dfa.png)

**Comment by juncaipeng** [comment]
目前没有提供现成mobilenet backbone的模型，我们后面会考虑加上。
