### ISSUE TITLE
用paddleseg训练二分类数据集，IOU值几乎0

### ISSUE THREAD

**Issue by Niki173** [PaddlePaddle/PaddleSeg#1618]
用paddleseg训练细胞核数据集，二分类问题，标签为1（即前景目标），IOU值几乎0，会是什么原因呢。训练label原数据是rgb通道，但是使用paddleseg要用单通道照片，因此我转为了单通道进行训练，训练过程没报错，就是标签1的IOU几乎为0。

**Comment by juncaipeng** [comment]
你可以使用visualdl查看loss曲线，同时evaluate时不仅看miou，还要看log输出的class iou（每个类别的iou）和class acc（每类像素的准确率）。
