### ISSUE TITLE
paddleseg-gpu tensorrt部署报错

### ISSUE THREAD

**Issue by zym434597594** [PaddlePaddle/PaddleSeg#1619]
cpu和gpu普通版本都能正常跑，但是gpu tensorrt部署一直报错
环境：paddle-centos7.6-py37-cuda10.2-cudnn8.1-trt7.2
显卡：Tesla P40

普通部署:
(paddle-gpu-trt) [root@10-23-44-203 PaddleSeg23]# python deploy/python/infer.py --config output/results-infer/bisenet/deploy.yaml --image_path cityscapes_demo.png
2021-12-13 19:33:50 [INFO]      Use GPU
2021-12-13 19:33:56 [INFO]      Finish

trt部署：
(paddle-gpu-trt) [root@10-23-44-203 PaddleSeg23]# python deploy/python/infer.py --config output/results-infer/bisenet/deploy.yaml --image_path cityscapes_demo.png --device gpu --use_trt True --print_detail
2021-12-13 19:37:51 [INFO]      Use GPU
2021-12-13 19:37:51 [INFO]      Use TRT
2021-12-13 19:37:51 [INFO]      Use manual set dynamic shape
W1213 19:37:54.614454 13689 analysis_predictor.cc:798] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
I1213 19:37:54.683724 13689 analysis_predictor.cc:579] TensorRT subgraph engine is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [conv_affine_channel_fuse_pass]
--- Running IR pass [adaptive_pool2d_convert_global_pass]
I1213 19:37:55.558923 13689 fuse_pass_base.cc:57] ---  detected 1 subgraphs
--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
--- Running IR pass [shuffle_channel_detect_pass]
--- Running IR pass [quant_conv2d_dequant_fuse_pass]
--- Running IR pass [delete_quant_dequant_op_pass]
--- Running IR pass [delete_quant_dequant_filter_op_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [multihead_matmul_fuse_pass_v3]
--- Running IR pass [skip_layernorm_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [unsqueeze2_eltwise_fuse_pass]
--- Running IR pass [squeeze2_matmul_fuse_pass]
--- Running IR pass [reshape2_matmul_fuse_pass]
--- Running IR pass [flatten2_matmul_fuse_pass]
--- Running IR pass [map_matmul_v2_to_mul_pass]
--- Running IR pass [map_matmul_v2_to_matmul_pass]
--- Running IR pass [map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
--- Running IR pass [tensorrt_subgraph_pass]
I1213 19:37:55.683974 13689 tensorrt_subgraph_pass.cc:138] ---  detect a sub-graph with 164 nodes
I1213 19:37:55.732421 13689 tensorrt_subgraph_pass.cc:395] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I1213 19:37:56.263988 13689 engine.cc:197] Run Paddle-TRT Dynamic Shape mode.
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [conv_elementwise_add_act_fuse_pass]
--- Running IR pass [conv_elementwise_add2_act_fuse_pass]
--- Running IR pass [transpose_flatten_concat_fuse_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I1213 19:38:10.825013 13689 ir_params_sync_among_devices_pass.cc:45] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I1213 19:38:10.833271 13689 memory_optimize_pass.cc:216] Cluster name : conv2d_102.tmp_1  size: 512
I1213 19:38:10.833302 13689 memory_optimize_pass.cc:216] Cluster name : batch_norm_52.tmp_0  size: 512
I1213 19:38:10.833308 13689 memory_optimize_pass.cc:216] Cluster name : conv2d_101.tmp_1  size: 512
I1213 19:38:10.833313 13689 memory_optimize_pass.cc:216] Cluster name : batch_norm_52.tmp_2  size: 512
--- Running analysis [ir_graph_to_program_pass]
I1213 19:38:10.925717 13689 analysis_predictor.cc:717] ======= optimize end =======
I1213 19:38:10.928658 13689 naive_executor.cc:98] ---  skip [feed], feed -> x
I1213 19:38:10.929858 13689 naive_executor.cc:98] ---  skip [save_infer_model/scale_0.tmp_1], fetch -> fetch
W1213 19:38:11.217128 13689 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Runtime API Version: 10.2
W1213 19:38:11.217588 13689 device_context.cc:465] device: 0, cuDNN Version: 8.1.
terminate called without an active exception

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
3   paddle::operators::TensorRTEngineOp::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
4   paddle::operators::TensorRTEngineOp::RunTrt(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::inference::tensorrt::TensorRTEngine*) const
5   paddle::inference::tensorrt::TensorRTEngine::Execute(int, std::vector<void*, std::allocator<void*> >*, CUstream_st*)
6   nvinfer1::rt::ExecutionContext::enqueueV2(void**, CUstream_st*, CUevent_st**)

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1639395491 (unix time) try "date -d @1639395491" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3579) received by PID 13689 (TID 0x7fa27e052740) from PID 13689 ***]

已放弃(吐核)
———————————————————————————————————————————————————————————
这是啥问题

**Comment by juncaipeng** [comment]
![7f3dedc7f286b88ddcb1b85725b83f4d](https://user-images.githubusercontent.com/52520497/145921590-a5c26e90-6235-413f-a309-b0a89cc5c2a0.png)

修改地方：[infer.py](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/deploy/python/infer.py#L196)

**Comment by zym434597594** [comment]
> ![7f3dedc7f286b88ddcb1b85725b83f4d](https://user-images.githubusercontent.com/52520497/145921590-a5c26e90-6235-413f-a309-b0a89cc5c2a0.png)
> 
> 修改地方：[infer.py](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/deploy/python/infer.py#L196)

示例已经能正常跑了，然后我跑了下matting那个工业实践，但是gpu版本处理一张图片需要16秒，使用trt部署减少到11秒左右，感觉实践中的话时间还是太长了,处理图片是挺快的，但是出现进度条之前需要10秒钟的等待，有没有方法减少这个时间？ 或者只第一次加载模型，后面能直接使用加载好的模型

## 环境
配置：4核8g 
显卡：NVIDIA Corporation GP102GL [Tesla P40] (rev a1)
环境：centos7.6 + conda3 + python3.7 + cuda10.2 + cudnn7.6.5 + trt7.2 + paddle-gpu2.2.1 + paddleseg2.3

导出模型：
![image](https://user-images.githubusercontent.com/56622184/145926381-3b1027e7-d507-4f79-8ca7-1d4c1ae96238.png)

gpu不使用trt部署
![image](https://user-images.githubusercontent.com/56622184/145926845-a5d14610-df54-4ca5-a51c-c93e43071108.png)

gpu使用trt部署
![image](https://user-images.githubusercontent.com/56622184/145926956-32aa6b20-84f6-492a-a83e-76fbc692d1d4.png)

**Comment by wuyefeilin** [comment]
你可以把要预测的图片都放在一个目录下，这样模型加载一次就能够完成所有图片的预测了
