### ISSUE TITLE
paddleseg serving部署报错

### ISSUE THREAD

**Issue by zym434597594** [PaddlePaddle/PaddleSeg#1620]
服务端正常起来：
(python37) [root@i-rqddkv57 Matting]# python -m paddle_serving_server.serve --model serving_server --thread 10 --port 9292 --ir_optim
/tmp/y/envs/python37/lib/python3.7/runpy.py:125: RuntimeWarning: 'paddle_serving_server.serve' found in sys.modules after import of package 'paddle_serving_server', but prior to execution of 'paddle_serving_server.serve'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Going to Run Comand
/tmp/y/envs/python37/lib/python3.7/site-packages/paddle_serving_server/serving-cpu-avx-mkl-0.7.0/serving -enable_model_toolkit -inferservice_path workdir_9292 -inferservice_file infer_service.prototxt -max_concurrency 0 -num_threads 10 -port 9292 -precision fp32 -use_calib=False -reload_interval_s 10 -resource_path workdir_9292 -resource_file resource.prototxt -workflow_path workdir_9292 -workflow_file workflow.prototxt -bthread_concurrency 10 -max_body_size 536870912 
I0100 00:00:00.000000  7723 op_repository.h:68] RAW: Succ regist op: GeneralDistKVInferOp
I0100 00:00:00.000000  7723 op_repository.h:68] RAW: Succ regist op: GeneralDistKVQuantInferOp
I0100 00:00:00.000000  7723 op_repository.h:68] RAW: Succ regist op: GeneralInferOp
I0100 00:00:00.000000  7723 op_repository.h:68] RAW: Succ regist op: GeneralReaderOp
I0100 00:00:00.000000  7723 op_repository.h:68] RAW: Succ regist op: GeneralResponseOp
I0100 00:00:00.000000  7723 service_manager.h:79] RAW: Service[LoadGeneralModelService] insert successfully!
I0100 00:00:00.000000  7723 load_general_model_service.pb.h:333] RAW: Success regist service[LoadGeneralModelService][PN5baidu14paddle_serving9predictor26load_general_model_service27LoadGeneralModelServiceImplE]
I0100 00:00:00.000000  7723 service_manager.h:79] RAW: Service[GeneralModelService] insert successfully!
I0100 00:00:00.000000  7723 general_model_service.pb.h:1608] RAW: Success regist service[GeneralModelService][PN5baidu14paddle_serving9predictor13general_model23GeneralModelServiceImplE]
I0100 00:00:00.000000  7723 factory.h:155] RAW: Succ insert one factory, tag: PADDLE_INFER, base type N5baidu14paddle_serving9predictor11InferEngineE
W0100 00:00:00.000000  7723 paddle_engine.cpp:29] RAW: Succ regist factory: ::baidu::paddle_serving::predictor::FluidInferEngine<PaddleInferenceEngine>->::baidu::paddle_serving::predictor::InferEngine, tag: PADDLE_INFER in macro!
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [layer_norm_fuse_pass]
---    Fused 0 subgraphs into layer_norm op.
--- Running IR pass [attention_lstm_fuse_pass]
--- Running IR pass [seqconv_eltadd_relu_fuse_pass]
--- Running IR pass [seqpool_cvm_concat_fuse_pass]
--- Running IR pass [mul_lstm_fuse_pass]
--- Running IR pass [fc_gru_fuse_pass]
---    fused 0 pairs of fc gru patterns
--- Running IR pass [mul_gru_fuse_pass]
--- Running IR pass [seq_concat_fc_fuse_pass]
--- Running IR pass [squeeze2_matmul_fuse_pass]
--- Running IR pass [reshape2_matmul_fuse_pass]
--- Running IR pass [flatten2_matmul_fuse_pass]
--- Running IR pass [map_matmul_v2_to_mul_pass]
--- Running IR pass [map_matmul_v2_to_matmul_pass]

端口也是正常的，外网可以用ip+端口打开

客户端一运行就报错：
(paddle-cpu) F:\wwwroot\learn\paddle\PaddleSeg-release-2.3\deploy\serving>python test_serving.py --serving_client_path serving_client --serving_ip_port 139.198.169.192:9292 --image_path ./3.jpg
Traceback (most recent call last):
  File "test_serving.py", line 60, in <module>
    run(args)
  File "test_serving.py", line 35, in run
    client = Client()
  File "D:\Users\Admin\miniconda3\envs\paddle-cpu\lib\site-packages\paddle_serving_client\client.py", line 146, in __init__
    from .serving_client import PredictorRes
ModuleNotFoundError: No module named 'paddle_serving_client.serving_client'
------------------------------------------------------

客户端paddle_serving_client是安装的：
(paddle-cpu) F:\wwwroot\learn\paddle\PaddleSeg-release-2.3\deploy\serving>conda list paddle
# packages in environment at D:\Users\Admin\miniconda3\envs\paddle-cpu:
#
# Name                    Version                   Build  Channel
paddle-serving-app        0.6.0                    pypi_0    pypi
paddle-serving-client     0.6.0                    pypi_0    pypi
paddlepaddle              2.2.1                    pypi_0    pypi

**Comment by juncaipeng** [comment]
你好，
你系统是windows吧，请参考[文档](https://github.com/PaddlePaddle/Serving/blob/v0.6.0/doc/WINDOWS_TUTORIAL_CN.md)安装试试。

**Comment by zym434597594** [comment]
> 你好， 你的系统是windows吧，请参考[文档](https://github.com/PaddlePaddle/Serving/blob/v0.6.0/doc/WINDOWS_TUTORIAL_CN.md)安装使用技巧。

服务端用的python,客户端是用windows请求的

**Comment by zym434597594** [comment]
> 

服务端： centos7.6 + conda
客户端是：windows + conda

**Comment by zym434597594** [comment]
> 你好， 你的系统是windows吧，请参考[文档](https://github.com/PaddlePaddle/Serving/blob/v0.6.0/doc/WINDOWS_TUTORIAL_CN.md)安装使用技巧。

https://github.com/PaddlePaddle/PaddleSeg/issues/1620#issuecomment-993102811

**Comment by zym434597594** [comment]
> 
服务端：centos7.6 + conda + python37 + paddle-cpu2.2.0
客户端：windows + conda + python37 +  paddle-cpu2.2.0

**Comment by juncaipeng** [comment]
请详细参考[server文档](https://github.com/PaddlePaddle/Serving/blob/v0.6.0/README_CN.md#%E5%8A%A8%E6%9C%BA)安装、使用。

由于seg这边主要是提供导出模型，server部署主体还是在server那边，所以如果是明确的server错误，也可以在[server](https://github.com/PaddlePaddle/Serving/issues)提出issue进行描述。

**Comment by zym434597594** [comment]
> 请详细参考[server文档](https://github.com/PaddlePaddle/Serving/blob/v0.6.0/README_CN.md#%E5%8A%A8%E6%9C%BA)安装、使用。
> 
> 由于seg这边主要是提供导出模型，server部署主体还是在server那边，所以如果是明确的server错误，也可以在[server](https://github.com/PaddlePaddle/Serving/issues)提出issue进行描述。

好的
