### ISSUE TITLE
video matting人像的边缘抖得厉害

### ISSUE THREAD

**Issue by SwordBearFire** [PaddlePaddle/PaddleSeg#1622]
你好，

我训练了一个人像抠图模型，训练的时候效果挺好的，但是抠视频中的人像，边缘特别的抖，不知道有什么好的解决办法吗？

Best regard

**Comment by wuyefeilin** [comment]
目前我们是图象matting算法，视频抖动的问题可以通过后期处理进行减弱，比如临近帧取平均值，光流算法等

**Comment by SwordBearFire** [comment]
> 

谢谢您的回答，我还有个问题想请教一下，关于模型蒸馏，假如说我想蒸馏中间层的特征，但是student模型的特征channel与teacher的特征channel不一致应该怎么计算损失，还有很多人都用KLloss来监督，我不太理解中间层的特征应该怎么做。谢谢

Best regard

**Comment by juncaipeng** [comment]
channel不一致时，通常使用conv1*1统一为相同的channel，再计算两个feature map的KL loss。

**Comment by zhubinsheng** [comment]
你的fps是多少
