### ISSUE TITLE
Matting 无法使用GPU训练

### ISSUE THREAD

**Issue by Sun-Wenfeng** [PaddlePaddle/PaddleSeg#1624]
按照readme.md中的指令python -m paddle.distributed.launch进行训练，依然是在CPU上进行的，并没有启用GPU。请问怎么解决？

**Comment by wuyefeilin** [comment]
确保安装了gpu版本的paddle，安装教程https://www.paddlepaddle.org.cn/

**Comment by Sun-Wenfeng** [comment]
安装链接中的指令安装了gpu版本，但是重新跑训练时遇到这种错误
<img width="1112" alt="截屏2021-12-15 下午3 38 28" src="https://user-images.githubusercontent.com/62273265/146143620-b064bbca-23e3-4e17-abc6-2a8918bdfe5b.png">
按照提示设置了LD_LIBRARY_PATH之后还是会报相同的错误。请问怎么解决？

**Comment by Sun-Wenfeng** [comment]
> 确保安装了gpu版本的paddle，安装教程https://www.paddlepaddle.org.cn/

按照链接中的指令安装了gpu版本，但是重新跑训练时遇到这种错误
<img width="1112" alt="截屏2021-12-15 下午3 38 28" src="https://user-images.githubusercontent.com/62273265/146149064-2a3cab76-365d-4750-a242-0c2d09dac306.png">


按照提示设置了LD_LIBRARY_PATH之后还是会报相同的错误。请问怎么解决？

**Comment by wuyefeilin** [comment]
查看一下是否安装了cuda贺cudnn？

**Comment by Sun-Wenfeng** [comment]
> 查看一下是否安装了cuda贺cudnn？

已经解决了，将cudnn降到7.6.5就能用
