### ISSUE TITLE
Matting中的modnet量化出错

### ISSUE THREAD

**Issue by fengyanWang** [PaddlePaddle/PaddleSeg#1628]
![image](https://user-images.githubusercontent.com/36984088/145965030-e13580fa-caf6-4696-afdb-fdf486a07a37.png)
参考链接Wei :https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/docs/slim/quant/quant.md

**Comment by wuyefeilin** [comment]
没找打MattingDataset， 请在程序开头进行import
from dataset import MattingDataset

**Comment by fengyanWang** [comment]
> 没找打MattingDataset， 请在程序开头进行import from dataset import MattingDataset

谢谢你的回复，包的问题解决了，但是modnet的配置文件和其他分割模型配置文件参数不同，导致调用qat_train的时候，参数解析错误，请问这个如何修改？


![image](https://user-images.githubusercontent.com/36984088/146106255-55ecffb4-1bc6-4d1f-af5e-e2bd09d021a4.png)

**Comment by wuyefeilin** [comment]
loss放置到模型文件里了，你可以直接修改，或者按照模型的字典形式传入loss_func_dict
