### ISSUE TITLE
matting model deploy on jetson nano jetpack4.4 crash

### ISSUE THREAD

**Issue by cloudlockheart** [PaddlePaddle/PaddleSeg#1634]
1. 使用MODNet+MobileNetV2 基于PPM-100 训练的模型
2. 使用export 导出模型： python export.py \
    --config configs/modnet/modnet_mobilenetv2.yml \
    --model_path output/best_model/model.pdparams \
    --save_dir output/export
3. 使用Paddle Inference C++预测库 进行推理，CPU/GPU都会报错，log如下：

-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found OpenCV: /usr/local/opencv3 (found version "3.4.7")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dlinano/works/paddleseg/PaddleSeg/deploy/cpp/build
Scanning dependencies of target test_seg
[ 50%] Building CXX object CMakeFiles/test_seg.dir/src/test_seg.cc.o
[100%] Linking CXX executable test_seg
[100%] Built target test_seg
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1215 17:40:13.040061 31668 test_seg.cc:64] Use CPU
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [layer_norm_fuse_pass]
---    Fused 0 subgraphs into layer_norm op.
--- Running IR pass [attention_lstm_fuse_pass]
--- Running IR pass [seqconv_eltadd_relu_fuse_pass]
--- Running IR pass [seqpool_cvm_concat_fuse_pass]
--- Running IR pass [mul_lstm_fuse_pass]
--- Running IR pass [fc_gru_fuse_pass]
---    fused 0 pairs of fc gru patterns
--- Running IR pass [mul_gru_fuse_pass]
--- Running IR pass [seq_concat_fc_fuse_pass]
--- Running IR pass [squeeze2_matmul_fuse_pass]
--- Running IR pass [reshape2_matmul_fuse_pass]
--- Running IR pass [flatten2_matmul_fuse_pass]
--- Running IR pass [map_matmul_v2_to_mul_pass]
--- Running IR pass [map_matmul_v2_to_matmul_pass]
--- Running IR pass [map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [repeated_fc_relu_fuse_pass]
--- Running IR pass [squared_mat_sub_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1215 17:40:13.929759 31668 fuse_pass_base.cc:57] ---  detected 36 subgraphs
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [conv_transpose_bn_fuse_pass]
--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I1215 17:40:14.073036 31668 memory_optimize_pass.cc:216] Cluster name : bilinear_interp_v2_3.tmp_0  size: 12
I1215 17:40:14.073094 31668 memory_optimize_pass.cc:216] Cluster name : img  size: 12
I1215 17:40:14.073110 31668 memory_optimize_pass.cc:216] Cluster name : relu_3.tmp_0  size: 128
I1215 17:40:14.073123 31668 memory_optimize_pass.cc:216] Cluster name : relu6_35.tmp_0  size: 5120
I1215 17:40:14.073137 31668 memory_optimize_pass.cc:216] Cluster name : tmp_0  size: 5120
I1215 17:40:14.073155 31668 memory_optimize_pass.cc:216] Cluster name : sigmoid_1.tmp_0  size: 5120
I1215 17:40:14.073201 31668 memory_optimize_pass.cc:216] Cluster name : depthwise_conv2d_15.tmp_0  size: 3840
I1215 17:40:14.073221 31668 memory_optimize_pass.cc:216] Cluster name : bilinear_interp_v2_2.tmp_0  size: 12
I1215 17:40:14.073240 31668 memory_optimize_pass.cc:216] Cluster name : batch_norm_42.tmp_3  size: 640
I1215 17:40:14.073253 31668 memory_optimize_pass.cc:216] Cluster name : elementwise_add_0  size: 96
I1215 17:40:14.073266 31668 memory_optimize_pass.cc:216] Cluster name : elementwise_add_8  size: 640
--- Running analysis [ir_graph_to_program_pass]
I1215 17:40:14.523308 31668 analysis_predictor.cc:717] ======= optimize end =======
I1215 17:40:14.546566 31668 naive_executor.cc:98] ---  skip [feed], feed -> img
I1215 17:40:14.564291 31668 naive_executor.cc:98] ---  skip [sigmoid_2.tmp_0], fetch -> fetch
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():

  Compile Traceback (most recent call last):
    File "export.py", line 111, in <module>
      main(args)
    File "export.py", line 89, in main
      paddle.jit.save(net, save_path)
    File "/home/wangkaiyu/tools/anaconda3/envs/paddleseg/lib/python3.8/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/home/wangkaiyu/tools/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/wangkaiyu/tools/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
      return func(*args, **kwargs)
    File "/home/wangkaiyu/tools/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 743, in save
      concrete_program = static_func.concrete_program_specify_input_spec(
    File "/home/wangkaiyu/tools/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 495, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "/home/wangkaiyu/tools/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 406, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/home/wangkaiyu/tools/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 723, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/home/wangkaiyu/tools/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 709, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "/home/wangkaiyu/tools/anaconda3/envs/paddleseg/lib/python3.8/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/home/wangkaiyu/tools/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/wangkaiyu/tools/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
      return func(*args, **kwargs)
    File "/home/wangkaiyu/tools/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 662, in from_func_spec
      outputs = static_func(*inputs)
    File "/home/wangkaiyu/PaddleSeg/contrib/Matting/model/modnet.py", line 58, in forward
      y = self.head(inputs=inputs, feat_list=feat_list)
    File "/home/wangkaiyu/tools/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/home/wangkaiyu/PaddleSeg/contrib/Matting/model/modnet.py", line 161, in forward
      pred_detail, hr2x = self.hr_branch(inputs['img'], enc2x, enc4x, lr8x)
    File "/home/wangkaiyu/tools/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/home/wangkaiyu/PaddleSeg/contrib/Matting/model/modnet.py", line 280, in forward
      hr4x = self.conv_hr4x(paddle.concat((hr4x, lr4x, img4x), axis=1))
    File "/home/wangkaiyu/tools/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/tensor/manipulation.py", line 345, in concat
      return paddle.fluid.layers.concat(input=x, axis=axis, name=name)
    File "/home/wangkaiyu/tools/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/layers/tensor.py", line 375, in concat
      helper.append_op(
    File "/home/wangkaiyu/tools/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/wangkaiyu/tools/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3178, in append_op
      op = Operator(
    File "/home/wangkaiyu/tools/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   paddle::operators::ConcatOp::InferShape(paddle::framework::InferShapeContext*) const
6   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
7   paddle::platform::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The 2-th dimension of input[0] and input[1] is expected to be equal.But received input[0]'s shape = [1, 64, 213, 410], input[1]'s shape = [1, 32, 216, 416].
  [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:213 != inputs_dims[i][j]:216.] (at /home/paddle/data/tc/work/e247db3b53dc4203/remove_paddle/Paddle/paddle/fluid/operators/concat_op.h:63)
  [operator < concat > error]
./run_seg_gpu.sh: line 34: 31668 Aborted                 (core dumped) ./build/test_seg --model_dir=./model --img_path=./hair_4.jpg --use_cpu=true

**Comment by wuyefeilin** [comment]
图象输入尺寸需要是32的倍数

**Comment by cloudlockheart** [comment]
但用同样的export model，使用Python infer ，并不会报错：
python deploy/python/infer.py \
    --config output/export/deploy.yaml \
    --image_path data/test_pics/ \
    --save_dir ouput/results

需要先对图像做resize么

**Comment by cloudlockheart** [comment]
将图像resize 成了32的倍数size (800,1600,3),但是报了新的错误
I1217 11:07:10.125449 14315 analysis_predictor.cc:717] ======= optimize end =======
I1217 11:07:10.148499 14315 naive_executor.cc:98] ---  skip [feed], feed -> img
I1217 11:07:10.164866 14315 naive_executor.cc:98] ---  skip [sigmoid_2.tmp_0], fetch -> fetch
W1217 11:07:10.174299 14315 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 5.3, Driver API Version: 10.2, Runtime API Version: 10.2
W1217 11:07:10.300957 14315 device_context.cc:465] device: 0, cuDNN Version: 8.0.
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   void paddle_infer::Tensor::CopyToCpuImpl<long>(long*, void*, void (*)(void*), void*) const
1   long* paddle::framework::Tensor::data<long>()
2   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
3   paddle::platform::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Tensor holds the wrong type, it holds float, but desires to be int64_t
  [Hint: Expected valid == true, but received valid:0 != true:1.] (at /home/paddle/data/tc/work/e247db3b53dc4203/remove_paddle/Paddle/paddle/fluid/framework/tensor_impl.h:51)

./run_seg_gpu.sh: line 34: 14315 Aborted                 (core dumped) ./build/test_seg --model_dir=./model --img_path=./hair_4_resized.jpg --use_cpu=false

**Comment by wuyefeilin** [comment]
![image](https://user-images.githubusercontent.com/30919197/146708729-60686091-696f-4af4-8f40-af8df55e45ff.png)
看样子使数据类型的问题，根据提示检查一下数据类型哈

**Comment by cloudlockheart** [comment]
> ![image](https://user-images.githubusercontent.com/30919197/146708729-60686091-696f-4af4-8f40-af8df55e45ff.png) 看样子使数据类型的问题，根据提示检查一下数据类型哈

有什么提示么，该如何检查数据类型，比如说是模型本身的数据类型不对，还是输入图像的数据类型

**Comment by wuyefeilin** [comment]
查看一下数据类型是否正确，顺便定位一下具体是哪一行出错的，方便做出进一步的判断

**Comment by cloudlockheart** [comment]
> 查看一下数据类型是否正确，顺便定位一下具体是哪一行出错的，方便做出进一步的判断

从Log 上看，出错是在这一行：
InvalidArgumentError: Tensor holds the wrong type, it holds float, but desires to be int64_t
[Hint: Expected valid == true, but received valid:0 != true:1.] (at /home/paddle/data/tc/work/e247db3b53dc4203/remove_paddle/Paddle/paddle/fluid/framework/tensor_impl.h:51)

目前是使用jeston nano做推理，推理基于Jetpack4.4(4.5): nv-jetson-cuda10.2-cudnn8-trt7(nano) 这个库

export model 的deploy yaml:
Deploy:
  model: model.pdmodel
  params: model.pdiparams
  transforms:
  - type: LoadImages
  - short_size: 512
    type: ResizeByShort
  - mult_int: 32
    type: ResizeToIntMult
  - type: Normalize

请问下还需要我提供哪些信息，或者应该排查模型侧的数据类型，还是推理侧的数据类型？

**Comment by wuyefeilin** [comment]
数据预处理后输入模型前查看一下数据类型哈

**Comment by cloudlockheart** [comment]
> Tensor holds the wrong type, it holds float, but desires to be int64_t

我对 test_seg.cc 进行了三处修改，使传入的图像不做normalize 处理，让Input 为CV_8UC1：
1. 将process image 函数中，将normalize 部分逻辑注释掉：
cv::Mat read_process_image(const YamlConfig& yaml_config) {
  cv::Mat img = cv::imread(FLAGS_img_path, cv::IMREAD_COLOR);
  cv::cvtColor(img, img, cv::COLOR_BGR2RGB);
  if (yaml_config.is_resize) {
    cv::resize(img, img, cv::Size(yaml_config.resize_width, yaml_config.resize_height));
  }
  /*
  if (yaml_config.is_normalize) {
    img.convertTo(img, CV_32F, 1.0 / 255, 0);
    img = (img - 0.5) / 0.5;
  }
  */
  return img;
}

2. hwc_img_2_chw_data 函数中，提取通道函数使用CV_8UC1:
void hwc_img_2_chw_data(const cv::Mat& hwc_img, int64_t* data) {
  int rows = hwc_img.rows;
  int cols = hwc_img.cols;
  int chs = hwc_img.channels();
  for (int i = 0; i < chs; ++i) {
    //cv::extractChannel(hwc_img, cv::Mat(rows, cols, CV_32FC1, data + i * rows * cols), i);
    //
    cv::extractChannel(hwc_img, cv::Mat(rows, cols, CV_8UC1, data + i * rows * cols), i);
  }
}

3. main 函数中，生成input数据从float 改成int64_t：
  //std::vector<float> input_data(1 * chs * rows * cols, 0.0f);
  //
  std::vector<int64_t> input_data(1 * chs * rows * cols, 0);

但是执行又报新的错，提示：
input and filter data type should be consistent, but received input data type is int64_t and filter type is float

完整log:
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   paddle::framework::OperatorWithKernel::ChooseKernel(paddle::framework::RuntimeContext const&, paddle::framework::Scope const&, paddle::platform::Place const&) const
6   paddle::operators::ConvOp::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const
7   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
8   paddle::platform::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: input and filter data type should be consistent, but received input data type is int64_t and filter type is float
  [Hint: Expected input_data_type == filter_data_type, but received input_data_type:3 != filter_data_type:5.] (at /home/paddle/data/tc/work/e247db3b53dc4203/remove_paddle/Paddle/paddle/fluid/operators/conv_op.cc:211)
  [operator < conv2d_fusion > error]
./run_seg_gpu.sh: line 34: 23440 Aborted                 (core dumped) ./build/test_seg --model_dir=./model --img_path=./hair_4_resized.jpg --use_cpu=false

**Comment by cloudlockheart** [comment]
发现是test_seg.cc中 copy_cpu部分的代码问题：
std::vector<float> out_data(out_num);
output_t->CopyToCpu(out_data.data());
这里原始用的是int64_t，但实际predict output实际应该是float

另外这个代码还有个bug:
cv::Mat out_gray_img(output_shape[2], output_shape[3], CV_8UC1, out_data_u8.data());
转成灰度图时，这里的shape应该取output_shape[2], output_shape[3]，而不是[1][2]

**Comment by wuyefeilin** [comment]
你c++部署是用的哪里的代码， 还是自己参考python部署写的

**Comment by cloudlockheart** [comment]
> 你c++部署是用的哪里的代码， 还是自己参考python部署写的

使用的是官方的代码：
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/deploy/cpp/src/test_seg.cc

**Comment by wuyefeilin** [comment]
matting的跟语义分割有所不同，你可以结合这个和matting python部署先自己写一下。后续我们会提供相应的c++部署
