### ISSUE TITLE
Matting HRNet Model is slow after exporting

### ISSUE THREAD

**Issue by hackkhai** [PaddlePaddle/PaddleSeg#1637]
I exported the Matting MODNet model and during inference on GPU it takes 2 seconds per image and the infer script says its using GPU and the GPU was also loading the model as it was visible in nvidia-smi. But when i use the model before exporting it takes only 200ms per image. Can I get some help?

**Comment by wuyefeilin** [comment]
Thanks for using Matting. May be the size of input image is different.

**Comment by hackkhai** [comment]
I Tried to see which one takes a lot of time and its [https://github.com/PaddlePaddle/PaddleSeg/blob/7ea27e51c8f624755917a9959e375e6c22c05f42/contrib/Matting/deploy/python/infer.py#L205](url) and it takes 1.5 seconds. which is a lot for copy from cpu

**Comment by michaelowenliu** [comment]
@hackkhai Hi, may I know how you get the execution time?

**Comment by hackkhai** [comment]
@michaelowenliu I tried to print the inference time for each line of code with cuda synchronisation

**Comment by juncaipeng** [comment]
Hi, what is the batch_size you set?

**Comment by hackkhai** [comment]
I used a batch size of 1 and its a single image inference

**Comment by juncaipeng** [comment]
> I Tried to see which one takes a lot of time and its [https://github.com/PaddlePaddle/PaddleSeg/blob/7ea27e51c8f624755917a9959e375e6c22c05f42/contrib/Matting/deploy/python/infer.py#L205](url) and it takes 1.5 seconds. which is a lot for copy from cpu



> I used a batch size of 1 and its a single image inference

This is not normal. What is the version of PaddlePaddle and PaddleSeg. Please update them to the latest version.

**Comment by hackkhai** [comment]
Tried it in the latest version, Just noticed that when i tried to do inference for multiple images, first image takes about 2 seconds and the following images takes 0.3 seconds, but all images are are of same size, and made a mistake where the model prediction takes longer time than it should.

**Comment by juncaipeng** [comment]
For the first image, the predictor has a warmup stage, which is normal.
