### ISSUE TITLE
单机多卡报错paddle.distributed.launch

### ISSUE THREAD

**Issue by zyz207** [PaddlePaddle/PaddleSeg#1642]
matting使用单卡正常训练，使用多卡时报错
2021-12-16 19:29:56 [INFO]
------------Environment Information-------------
platform: Linux-4.15.0-147-generic-x86_64-with-glibc2.27
Python: 3.8.10 (default, May  5 2021, 03:01:07) [GCC 7.5.0]
Paddle compiled with cuda: True
NVCC: Build cuda_11.2.r11.2/compiler.29618528_0
cudnn: 8.1
GPUs used: 2
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: NVIDIA GeForce', 'GPU 1: NVIDIA GeForce']
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PaddlePaddle: 2.2.0
OpenCV: 4.5.2
------------------------------------------------
2021-12-16 19:29:57 [INFO]
---------------Config Information---------------
batch_size: 2
iters: 200000
lr_scheduler:
  boundaries:
  - 40000
  - 80000
  type: PiecewiseDecay
  values:
  - 0.002
  - 0.0002
  - 2.0e-05
model:
  backbone:
    pretrained: https://paddleseg.bj.bcebos.com/matting/models/MobileNetV2_pretrained/model.pdparams
    type: MobileNetV2
  pretrained: null
  type: MODNet
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 4.0e-05
train_dataset:
  dataset_root: /hy-tmp/Matting
  mode: train
  train_file: train_comp_512.txt
  transforms:
  - type: LoadImages
  - crop_size:
    - 512
    - 512
    type: RandomCrop
  - type: RandomDistort
  - type: RandomBlur
  - type: RandomHorizontalFlip
  - type: Normalize
  type: MattingDataset
val_dataset:
  dataset_root: /hy-tmp/Matting
  get_trimap: false
  mode: val
  transforms:
  - type: LoadImages
  - short_size: 512
    type: ResizeByShort
  - mult_int: 32
    type: ResizeToIntMult
  - type: Normalize
  type: MattingDataset
  val_file: val.txt
------------------------------------------------
W1216 19:29:57.020426 15662 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.2
W1216 19:29:57.020465 15662 device_context.cc:465] device: 0, cuDNN Version: 8.1.
2021-12-16 19:29:59 [INFO]      Loading pretrained model from https://paddleseg.bj.bcebos.com/matting/models/MobileNetV2_pretrained/model.pdparams
2021-12-16 19:29:59 [INFO]      There are 265/265 variables loaded into MobileNet.
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:43331']
I1216 19:30:02.955237 15662 nccl_context.cc:74] init nccl context nranks: 2 local rank: 0 gpu id: 0 ring id: 0
INFO 2021-12-16 19:30:04,638 launch_utils.py:319] terminate process group gid:15662
INFO 2021-12-16 19:30:08,642 launch_utils.py:340] terminate all the procs
ERROR 2021-12-16 19:30:08,642 launch_utils.py:601] ABORT!!! Out of all 2 trainers, the trainer process with rank=[1] was aborted. Please check its log.
INFO 2021-12-16 19:30:12,647 launch_utils.py:340] terminate all the procs
INFO 2021-12-16 19:30:12,647 launch.py:304] Local processes completed.

这是workerlog.0
2021-12-16 19:18:14 [INFO]	
------------Environment Information-------------
platform: Linux-4.15.0-147-generic-x86_64-with-glibc2.27
Python: 3.8.10 (default, May  5 2021, 03:01:07) [GCC 7.5.0]
Paddle compiled with cuda: True
NVCC: Build cuda_11.2.r11.2/compiler.29618528_0
cudnn: 8.1
GPUs used: 2
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: NVIDIA GeForce', 'GPU 1: NVIDIA GeForce']
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PaddlePaddle: 2.2.0
OpenCV: 4.5.2
------------------------------------------------
2021-12-16 19:18:14 [INFO]	
---------------Config Information---------------
batch_size: 8
iters: 200000
lr_scheduler:
  boundaries:
  - 40000
  - 80000
  type: PiecewiseDecay
  values:
  - 0.002
  - 0.0002
  - 2.0e-05
model:
  backbone:
    pretrained: https://paddleseg.bj.bcebos.com/matting/models/MobileNetV2_pretrained/model.pdparams
    type: MobileNetV2
  pretrained: null
  type: MODNet
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 4.0e-05
train_dataset:
  dataset_root: /hy-tmp/Matting
  mode: train
  train_file: train_comp_512.txt
  transforms:
  - type: LoadImages
  - crop_size:
    - 512
    - 512
    type: RandomCrop
  - type: RandomDistort
  - type: RandomBlur
  - type: RandomHorizontalFlip
  - type: Normalize
  type: MattingDataset
val_dataset:
  dataset_root: /hy-tmp/Matting
  get_trimap: false
  mode: val
  transforms:
  - type: LoadImages
  - short_size: 512
    type: ResizeByShort
  - mult_int: 32
    type: ResizeToIntMult
  - type: Normalize
  type: MattingDataset
  val_file: val.txt
------------------------------------------------
W1216 19:18:14.381341 12410 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.2
W1216 19:18:14.381377 12410 device_context.cc:465] device: 0, cuDNN Version: 8.1.
2021-12-16 19:18:16 [INFO]	Loading pretrained model from https://paddleseg.bj.bcebos.com/matting/models/MobileNetV2_pretrained/model.pdparams
2021-12-16 19:18:16 [INFO]	There are 265/265 variables loaded into MobileNet.
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:38811']
I1216 19:18:20.043469 12410 nccl_context.cc:74] init nccl context nranks: 2 local rank: 0 gpu id: 0 ring id: 0
/usr/local/lib/python3.8/dist-packages/paddle/nn/layer/norm.py:652: UserWarning: When training, we now always track global mean and variance.
  warnings.warn(

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   void paddle::memory::Copy<paddle::platform::CPUPlace, paddle::platform::CUDAPlace>(paddle::platform::CPUPlace, void*, paddle::platform::CUDAPlace, void const*, unsigned long, CUstream_st*)
1   paddle::platform::GpuMemcpySync(void*, void const*, unsigned long, cudaMemcpyKind)

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1639653505 (unix time) try "date -d @1639653505" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x302b) received by PID 12410 (TID 0x7f6b9e55a740) from PID 12331 ***]

这是workerlog.1
/usr/lib/python3/dist-packages/urllib3/util/selectors.py:14: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import namedtuple, Mapping
/usr/lib/python3/dist-packages/urllib3/_collections.py:2: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Mapping, MutableMapping
/usr/local/lib/python3.8/dist-packages/paddleseg/cvlibs/manager.py:114: UserWarning: ResNet18_vd exists already! It is now updated to <function ResNet18_vd at 0x7f1efe718c10> !!!
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/paddleseg/cvlibs/manager.py:114: UserWarning: ResNet50_vd exists already! It is now updated to <function ResNet50_vd at 0x7f1efe720550> !!!
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/paddleseg/cvlibs/manager.py:114: UserWarning: ResNet101_vd exists already! It is now updated to <function ResNet101_vd at 0x7f1efe720670> !!!
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/paddleseg/cvlibs/manager.py:114: UserWarning: MobileNetV2 exists already! It is now updated to <function MobileNetV2 at 0x7f1efe720dc0> !!!
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/paddleseg/cvlibs/manager.py:114: UserWarning: HRNet_W18_Small_V1 exists already! It is now updated to <function HRNet_W18_Small_V1 at 0x7f1efe726940> !!!
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/paddleseg/cvlibs/manager.py:114: UserWarning: HRNet_W18_Small_V2 exists already! It is now updated to <function HRNet_W18_Small_V2 at 0x7f1efe7305e0> !!!
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/paddleseg/cvlibs/manager.py:114: UserWarning: HRNet_W18 exists already! It is now updated to <function HRNet_W18 at 0x7f1efe730670> !!!
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/paddleseg/cvlibs/manager.py:114: UserWarning: HRNet_W30 exists already! It is now updated to <function HRNet_W30 at 0x7f1efe730790> !!!
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/paddleseg/cvlibs/manager.py:114: UserWarning: HRNet_W32 exists already! It is now updated to <function HRNet_W32 at 0x7f1efe7308b0> !!!
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/paddleseg/cvlibs/manager.py:114: UserWarning: HRNet_W40 exists already! It is now updated to <function HRNet_W40 at 0x7f1efe7309d0> !!!
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/paddleseg/cvlibs/manager.py:114: UserWarning: HRNet_W44 exists already! It is now updated to <function HRNet_W44 at 0x7f1efe730af0> !!!
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/paddleseg/cvlibs/manager.py:114: UserWarning: HRNet_W48 exists already! It is now updated to <function HRNet_W48 at 0x7f1efe730c10> !!!
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/paddleseg/cvlibs/manager.py:114: UserWarning: HRNet_W60 exists already! It is now updated to <function HRNet_W60 at 0x7f1efe730d30> !!!
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/paddleseg/cvlibs/manager.py:114: UserWarning: HRNet_W64 exists already! It is now updated to <function HRNet_W64 at 0x7f1efe730e50> !!!
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/paddleseg/cvlibs/manager.py:114: UserWarning: Compose exists already! It is now updated to <class 'transforms.Compose'> !!!
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/paddleseg/cvlibs/manager.py:114: UserWarning: Resize exists already! It is now updated to <class 'transforms.Resize'> !!!
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/paddleseg/cvlibs/manager.py:114: UserWarning: ResizeByLong exists already! It is now updated to <class 'transforms.ResizeByLong'> !!!
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/paddleseg/cvlibs/manager.py:114: UserWarning: ResizeByShort exists already! It is now updated to <class 'transforms.ResizeByShort'> !!!
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/paddleseg/cvlibs/manager.py:114: UserWarning: Normalize exists already! It is now updated to <class 'transforms.Normalize'> !!!
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/paddleseg/cvlibs/manager.py:114: UserWarning: LimitLong exists already! It is now updated to <class 'transforms.LimitLong'> !!!
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/paddleseg/cvlibs/manager.py:114: UserWarning: RandomHorizontalFlip exists already! It is now updated to <class 'transforms.RandomHorizontalFlip'> !!!
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/paddleseg/cvlibs/manager.py:114: UserWarning: RandomBlur exists already! It is now updated to <class 'transforms.RandomBlur'> !!!
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/paddleseg/cvlibs/manager.py:114: UserWarning: RandomDistort exists already! It is now updated to <class 'transforms.RandomDistort'> !!!
  warnings.warn(
W1216 19:18:14.418967 12415 device_context.cc:447] Please NOTE: device: 1, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.2
W1216 19:18:14.419004 12415 device_context.cc:465] device: 1, cuDNN Version: 8.1.
I1216 19:18:17.092468 12415 gen_comm_id_helper.cc:190] Server listening on: 127.0.0.1:38811 successful.
I1216 19:18:20.043493 12415 nccl_context.cc:74] init nccl context nranks: 2 local rank: 1 gpu id: 1 ring id: 0
W1216 19:18:22.790031 12522 system_allocator.cc:205] cudaHostAlloc failed.
W1216 19:18:22.790097 12522 naive_best_fit_allocator.cc:590] cudaHostAlloc Cannot allocate 8388608 bytes in CUDAPinnedPlace

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::thread::_State_impl<std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1}> > >::_M_run()
1   std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1639653502 (unix time) try "date -d @1639653502" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x7ffff0) received by PID 12415 (TID 0x7f1e317fa700) from PID 8388592 ***]

**Comment by wuyefeilin** [comment]
查看一下显存是否充足，不够的话调小batch_size试试
