### ISSUE TITLE
如何转onnx模型呢？

### ISSUE THREAD

**Issue by 205418367** [PaddlePaddle/PaddleSeg#1643]

**Comment by 205418367** [comment]
请问下载的modnet-mobilenetv2.pdparams如何转弄下？我尝试根据paddle2onnx试了下没成功呢

**Comment by michaelowenliu** [comment]
@205418367 Hi, you should export the pdparams. Please refer to the instruction, https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.3/contrib/Matting#model-export

**Comment by juncaipeng** [comment]
我们已经在验证是否转换错误，如果不成功，会尽快尝试修复paddle2onnx

**Comment by 205418367** [comment]
可以了，谢谢
