### ISSUE TITLE
PaddleSeg  backbone_indices 

### ISSUE THREAD

**Issue by zhijiejia** [PaddlePaddle/PaddleSeg#1645]
请问 PaddleSeg的配置中的 backbone_indices 代表的是啥？ 没找到有解释这个参数的地方。另外 不同的模型有不同的loss个数，这个从哪查呢？ 每次换模型的时候，就一头雾水，不知道backbone_indices 怎么改，loss写几个？

**Comment by zhijiejia** [comment]
哦哦 这个是不是结合 定义模型代码的文件 里看的呢，刚才在deeplabv3 里看到了相应的定义

**Comment by juncaipeng** [comment]
backbone_indices表示使用backbone输出list中哪几个tensor用作head的输入，需要结合模型定义来看。
