### ISSUE TITLE
paddlseg为什么不以epoch，而是以iter作为训练的基本单位呢？

### ISSUE THREAD

**Issue by geoexploring** [PaddlePaddle/PaddleSeg#1647]
在paddlex中是以epoch为训练的基本单位，而在paddleseg中是以iter作为训练的基本单位。

请问这是什么原因呢？还是说用iter训练是历史原因？

谢谢！

**Comment by juncaipeng** [comment]
seg论文通常都是用iter来说明实验参数，所以paddleseg按照通用做法来实现。

**Comment by geoexploring** [comment]
@juncaipeng ，谢谢，明白了。
