### ISSUE TITLE
适合于paddleseg的SwinTransformer预训练模型？

### ISSUE THREAD

**Issue by geoexploring** [PaddlePaddle/PaddleSeg#1649]
请问，有没有适合于paddleseg的SwinTransformer预训练模型？如类似 https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz .

谢谢！

**Comment by juncaipeng** [comment]
目前还没有支持swintransformer，不过我们支持了如下三个transform分割模型：

![image](https://user-images.githubusercontent.com/52520497/147026724-c73e6dd5-f26f-4ada-b641-ecfc3fe62fea.png)

请参考：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/docs/model_zoo_overview.md#transformer%E7%B3%BB%E5%88%97

**Comment by geoexploring** [comment]
@juncaipeng ，好的，谢谢！

**Comment by geoexploring** [comment]
@juncaipeng .谢谢！
请问，如果用paddleclas中的[swintransformer ImageNet 预训练模型库](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/algorithm_introduction/ImageNet_models.md#16)可以吗？

**Comment by geoexploring** [comment]
@juncaipeng .谢谢！
请问，如果用paddleclas中的[swintransformer ImageNet 预训练模型库](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/algorithm_introduction/ImageNet_models.md#16)可以吗？

**Comment by juncaipeng** [comment]
可以的，paddleclass中的swintransformer可以作为backbone。但是还需要在paddleseg中修改代码，添加模型。
