### ISSUE TITLE
In F.cross_entropy, the ignore_index is invalid, which needs to be fixed.

### ISSUE THREAD

**Issue by zhijiejia** [PaddlePaddle/PaddleSeg#1650]
![image](https://user-images.githubusercontent.com/43838913/146888645-e53a2c21-40d1-4560-a8f7-0370350b17fa.png)

`paddleseg/models/losses/cross_entropy_loss.py`  第84行, 说cross_entropy中ignore_index参数无效，现在还是无效吗？

**Comment by shiyutang** [comment]
You can try it. Now it is valid with paddle 2.2.
