### ISSUE TITLE
IESeg release2.3版

### ISSUE THREAD

**Issue by MicroPhion** [PaddlePaddle/PaddleSeg#1651]
在使用IESeg的GPU版时，鼠标每点击一次，显存就会增加几百兆。切换下一张图像时，显存仍然会持续增加，不知道这种现象是否正常。

**Comment by haoyuying** [comment]
您好，图多大呢，可否给我们两张图用于复现问题，并且提供复现环境信息，比如paddle，eiseg的版本及cuda版本等
