### ISSUE TITLE
新版本sfnet_ResNet18_vd   c++推理时间翻倍

### ISSUE THREAD

**Issue by 534114658** [PaddlePaddle/PaddleSeg#1653]
数据集的分辨率是crop_size: [452, 416]
2.1版本的sfnet_ResNet18_vd   训练之后c++推理时间是19-22ms左右

2.3版本  同样的数据集训练  
同样是sfnet_ResNet18_vd   训练参数都一样  训练之后c++推理时间是38-41ms左右

是什么原因导致的？

**Comment by haoyuying** [comment]
请问您两次测试的环境细节是什么样的呢，配置是否相同？

**Comment by 534114658** [comment]
同一台电脑   2.1和2.3反复测试过2次才来问的

win10 cuda10.2  
paddlepaddle-gpu==2.2.1

![image](https://user-images.githubusercontent.com/88479008/147176858-e6d22c00-02b9-4e8f-bd28-e20e4717e976.png)


2.1和2.3的测试只更换paddleseg文件夹和train.py，其他训练数据都一样

**Comment by 534114658** [comment]
有没有发现什么问题？-1

**Comment by haoyuying** [comment]
在测试时候也不会用到train.py,请问为什么要更换呢，目前提供的信息不能找到问题，看看能不能在aistudio上提供一个可以复现的环境，方便我们排查问题？
