### ISSUE TITLE
关于训练模型的同时，transforms的设定会带来的效果以及影响。

### ISSUE THREAD

**Issue by SamYokai** [PaddlePaddle/PaddleSeg#1654]
不好意思，有一些疑惑想要请教，就是在我们训练模型之前我们会在yml file (例子：bisenet_optic_disc_512x512_1k.yml) 设置一些transforms的设定 （比如：Resize，RandomDistort 等等）再开始训练。我的疑惑是譬如RandomDistort 这样，会随机给我们一些设定数值基于我们的 contrast_range， contrast_prob 之类的。那么在训练模型时，这个随机的设定是在我们一开始训练时就已经设定并固定了呢，还是会在每一次的 iter 或者 epoch 都会随机给我们不同的设定数值？希望可以明白我的问题，如果有不明白的，我可以再尝试解释看看。

**Comment by LutaoChu** [comment]
你好，这些随机设定是在每一次iter都会带来随机效果的。比如RandomDistort，每个iter会先按contrast_prob的概率去选择是否进行对比度变换，如果进行对比度变化，再在contrast_range范围内随机选择一种对比度变换我们的图像，得到最终的变换后的图片

**Comment by SamYokai** [comment]
> 你好，这些随机设定是在每一次iter都会带来随机效果的。比如RandomDistort，每个iter会先按contrast_prob的概率去选择是否进行对比度变换，如果进行对比度变化，再在contrast_range范围内随机选择一种对比度变换我们的图像，得到最终的变换后的图片

原来如此，理解了，谢谢您的解答
