### ISSUE TITLE
执行速度

### ISSUE THREAD

**Issue by sunshineyg2018** [PaddlePaddle/PaddleSeg#1659]
/deploy/infer.py 里面的  self.predictor.run() 执行
同样两个项目 配置一样 运行速度差别太多
一个为3.7秒
一个为0.04秒
请问是什么影响了这个速度

**Comment by sunshineyg2018** [comment]
PaddleSeg/contrib/PP-HumanSeg/deploy/infer.py

**Comment by LutaoChu** [comment]
你是怎么计时的呢？预测了几张图片呢？

**Comment by sunshineyg2018** [comment]
> 你是怎么计时的呢？预测了几张图片呢？

两张图片，图片替换背景使用的是 config export_model/ppseg_lite_portrait_398x224_with_softmax/deploy.yaml 

time.now 计时

**Comment by sunshineyg2018** [comment]
<img width="484" alt="image" src="https://user-images.githubusercontent.com/40789780/147311616-b7bf3e45-80f2-4c98-931d-cd0a1911ce59.png">

**Comment by LutaoChu** [comment]
是这样的，第一张图片都会耗时比较久，因为第一次运行需要初始化很多变量，之后的图片就不需要初始化，耗时会更短。一般不算第一次运行的时间

**Comment by sunshineyg2018** [comment]
> 是这样的，第一张图片都会耗时比较久，因为第一次运行需要初始化很多变量，之后的图片就不需要初始化，耗时会更短。一般不算第一次运行的时间

可是同样两个一摸一样的服务，如果是第一次加载比较久那么 应该都是第一张图片很慢后面很快

但是两个服务反馈的是 其中一个服务 非常快，另外一个服务始终就很慢。

**Comment by LutaoChu** [comment]
是的，理论上第一张图片很慢后面很快。
两个一模一样的服务，理论上不应该一个快一个慢，请排查一下是不是有其他不一致的因素，不然就是预测引擎不稳定，可以去paddle repo里提issue看看
