### ISSUE TITLE
文档中链接失效

### ISSUE THREAD

**Issue by GT-ZhangAcer** [PaddlePaddle/PaddleSeg#166]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.3.0/turtorial/finetune_deeplabv3plus.md
![图片](https://user-images.githubusercontent.com/46156734/75221955-f94a3380-57dd-11ea-846d-4b78035b333f.png)
#
该文档下的“在线体验”链接失效，不知道是不是需要替换成下面的链接
https://aistudio.baidu.com/aistudio/projectdetail/226703

**Comment by LutaoChu** [comment]
是的，我们已经更新了上面的链接，谢谢反馈
