### ISSUE TITLE
eiseg

### ISSUE THREAD

**Issue by DoubleJR** [PaddlePaddle/PaddleSeg#1660]
新手，在用eiseg标注过程中，老是报错“MemoryError: (ResourceExhausted) Fail to alloc memory of 524288000 size.”，然后退出程序，请问是我显卡不行吗。。。

**Comment by haoyuying** [comment]
这种问题一般是由于图片过大等因素导致的显存不足。请问您具体使用的图片大小及显卡信息是什么呢？

**Comment by zhangs-cedar** [comment]
EIseg的模型除了官方提供的模型，可以提供训练模板嘛

**Comment by DoubleJR** [comment]
显卡是gtx1060，图片都很小，但有可能是软件再把它拉大？
像素很低，分辨率也很低，图片宽度和高度只有大概100px和几10px

**Comment by haoyuying** [comment]
@DoubleJR 那应该不会出现这个问题，可以查看如果用了0.4版本的eiseg是否配套了2.2版本的paddle

**Comment by haoyuying** [comment]
> EIseg的模型除了官方提供的模型，可以提供训练模板嘛

目前还没有开源训练代码
