### ISSUE TITLE
EISeg Train Code 

### ISSUE THREAD

**Issue by Mergim01** [PaddlePaddle/PaddleSeg#1661]
Dear PaddleSeg and EISeg Team, 
I have read your paper on Interactive Segmentation (EdgeFlow: Achieving Practical Interactive Segmentation with Edge-Guided Flow) and I am amazed. I am studying Information Systems at WWU in Münster, Germany, and as part of a seminar, I chose to take your Edgeflow architecture and apply it to satellite data. In order to be able to recognize smaller objects in aerial imagery better in the ElSeg program. So I wanted to ask if you could provide me with the code you used to train the precise model on the COCO +LVIS dataset? The repository only shows how the model is built, but not how it was trained. I am especially interested in how the interactive clicks were randomly generated during training.

**Comment by WuShaogui** [comment]
You may obtain more information from the article and code in Reference 50

**Comment by michaelowenliu** [comment]
@Mergim01 Hi, thanks for your interest in our work. Did you try our model for satellite data? https://github.com/PaddlePaddle/PaddleSeg/blob/develop/EISeg/docs/remote_sensing_en.md
