### ISSUE TITLE
2.3版本比2.1版本训练的模型c++推理时间翻倍

### ISSUE THREAD

**Issue by 534114658** [PaddlePaddle/PaddleSeg#1674]
测试模型 sfnet_ResNet18_vd
数据集的分辨率是crop_size: [452, 416]
同一台电脑 win10 cuda10.2 paddlepaddle-gpu==2.2.1
![image](https://user-images.githubusercontent.com/88479008/147717093-ef69182e-a0bc-4b24-83f6-496fed27b122.png)
2.3和2.1的测试只更换paddleseg文件夹和train.py，其他训练数据都一样

上一个issues  一个星期没人回复了

**Comment by haoyuying** [comment]
测试不会用到train.py，2.3和2.1是paddleseg的版本吗？请在aistudio上给一个具体的复现环境，目前根据您提供的信息很难复现该问题。

**Comment by juncaipeng** [comment]
hi，你是使用相同的c++预测库测试吗？只是导出的预测模型不同？
你可以把模型上传到这个issue中，我们看看。你也可以使用netron软件打开两个导出的预测模型，看下模型结构是否有差异。

**Comment by 534114658** [comment]
2.1和2.3的c++预测库都测试过    一样

**Comment by 534114658** [comment]
内部包含图片及2.1和2.3训练的图片


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月30日(星期四) 下午3:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] 2.3版本比2.1版本训练的模型c++推理时间翻倍 (Issue #1674)





 
测试不会用到train.py，2.3和2.1是paddleseg的版本吗？请在aistudio上给一个具体的复现环境，目前根据您提供的信息很难复现该问题。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

test.zip (98.88M, 2022年01月30日 15:21 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=5f35623703ebe09c00c4b7284035034a505751545e0301514f0054515e1805065a0c4f555e57554801060402575404045a025b02663d3111074616191c5c41655f&t=exs_ftn_download&code=b5b7f51e

**Comment by 534114658** [comment]
2.3有2处位置多了pool2d     导致c++推理时间翻倍

![image](https://user-images.githubusercontent.com/88479008/147810048-bfdd0bcc-4e3a-4d5f-8df6-54d14b11834c.png)

在2.3里面的哪个文档可以更改   不添加这2个？

**Comment by 534114658** [comment]
查看2.1的文档     2.1的sfnet_ResNet18_vd模型精度为78.31%


![image](https://user-images.githubusercontent.com/88479008/147813430-ed603b0d-f0ba-43c9-9bcf-e7a56f54cecd.png)


2.3的文档     2.3的sfnet_ResNet18_vd模型精度为78.72%


![image](https://user-images.githubusercontent.com/88479008/147813482-288007a2-e298-446f-b0d9-0068c75d8d51.png)


精度提升不是非常大  ，推理时间翻倍了

**Comment by 534114658** [comment]
现在2.3的版本有哪个模型精度高 速度快的？

2.3版本的sfnet_ResNet18_vd    速度太慢了

能不能推荐个模型？

**Comment by 534114658** [comment]
这张图也不准确

同样的数据集训练，看图的话  理论上处理时间SegFormer_B1是sfnet_ResNet18_vd的1/3

实际测试   图片分辨率：500*300
2.1版本的sfnet_ResNet18_vd处理时间：16ms
2.3版本的sfnet_ResNet18_vd处理时间：30ms
2.3版本的SegFormer_B1处理时间：46ms


![image](https://user-images.githubusercontent.com/88479008/147814564-5e63a623-cc38-4333-bdd5-37f8e7fcc33f.png)

按照文档说明   这个还是1024x512的效果

**Comment by juncaipeng** [comment]
查看后发现：2.1版本的sfnet_resnet18_os8模型存在错误，其中resnet18的output stride是32；使用下图中2.1版本的代码和模型，测试miou只有63.91%。
![image](https://user-images.githubusercontent.com/52520497/148001551-a7ccf626-e313-43f5-8a18-c94a6fd5c072.png)

2.3版本修复改该错误，其中resnet18的output stride是8，后半部分feature map的shape更大，导致算量增大；使用2.3版本的代码和模型，测试miou可以达到78.72%，只是速度会减慢。

sfnet速度不会特别快，建议使用stdcseg v1和bisenetv2。

**Comment by 534114658** [comment]
感谢！！！
