### ISSUE TITLE
关于hardnet

### ISSUE THREAD

**Issue by DnYoZn** [PaddlePaddle/PaddleSeg#1675]
model zoo中 hardnet的readme文件给出的论文链接不正确，应该是《Deep High-Resolution Representation Learning for Visual Recognition》
[https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/configs/hardnet/README.md](url)

**Comment by juncaipeng** [comment]
《Deep High-Resolution Representation Learning for Visual Recognition》 是HRNet。
