### ISSUE TITLE
跪求seg项目合集

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PaddleSeg#1676]
https://aistudio.baidu.com/aistudio/projectdetail/450925?channelType=0&channel=0
paddlex等很多套件已经出了一个项目合集,并且有静态图和动态图版本,项目合集中蕴含了paddlex的4个主要方向,图像分类,目标检测,语义分割,实例分割,每个方向都至少有一个项目,项目里面包含项目代码,一些参数和代码的解释,注释等.
希望seg也可以出一个项目合集,蕴含seg目前所包含的所有比较不同的方向,比如语义分割、交互式分割、全景分割、Matting四大图像分割能力等方向做一个项目合集,最好有量化,蒸馏,裁剪,预测,可视化,部署等相关代码,最好是包含静态图和动态图版本,如果你们没精力的话,做个动态图版本也行,这样我们这些学习者就不用到处找项目和代码来学习了.动态图版本肯定要支持飞桨2.2.1和seg最新release版本.最好就是学习完这个seg项目合集,可以把seg多数知识都会应用了,不要求掌握原理,比如模型原理等.而且你们做这个合集,希望可以包含一个项目,项目里面的网络是自定义,比较深的网络,包含卷积,池化,drop等API,这种项目太少见了,现在都是直接应用ResNet,搞得我简单的神经网络编程反而不会了有些分割只需要很小的网络,因为对于延迟要求非常低.最好再来个项目教导我们如何写ResNet,毕竟这个技术对于图像分类太有用了.做视频太慢了,还是做个项目合集好,做视频半年精力才几个小视频,甚至讲解基础知识.做项目对你们来说,7天就可以弄个项目合集了,包含很多知识了,只限于应用,不限于原理,我只需要改代码,哈哈哈哈.

**Comment by juncaipeng** [comment]
好的，我们会考虑你的建议。目前请先阅读githu上的readme文档。
