### ISSUE TITLE
如何训练自己的模型

### ISSUE THREAD

**Issue by FryeGao** [PaddlePaddle/PaddleSeg#1678]
您好：官方提供的4个模型结构（hrnet18_ocr64_cocolvis，hrnet18s_ocr48_cocolvis，hrnet18_ocr64_human，hrnet18s_ocr48_human）并不太适合当前我想要分割场景的图片，我想使用自己的数据集重新训练一个模型结构，请问支持这种操作吗？如果支持的话，应该在哪部分代码中做修改？

**Comment by juncaipeng** [comment]
EISeg目前没有公布训练代码，如果感兴趣需要细读EISeg的源码，使用PaddleSeg训练模型进行替换。

**Comment by lzhbrian** [comment]
Hi, any updates on this?
Thanks

**Comment by dgl547437235** [comment]
你好，使用paddleseg训练模型进行替换EISeg，这个模型是具体指哪个模型，还是任意的分割模型都可以
