### ISSUE TITLE
训练fastscnn报错

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleSeg#1680]
![QQ图片20220104152224](https://user-images.githubusercontent.com/48303408/148023486-cb78a3d7-4688-4873-b592-083be7923786.png)

请问这是什么原因

**Comment by wuyefeilin** [comment]
麻烦给一下 PaddleSeg的版本及运行命令

**Comment by Dandelion111** [comment]
> 
PaddleSeg版本：release2.3
运行命令：
python train.py \
       --config configs/quick_start/bisenet_optic_disc_512x512_1k.yml \
       --do_eval \
       --use_vdl \
       --save_interval 500 \
       --save_dir output

**Comment by Dandelion111** [comment]
> PaddleSeg版本：release2.3
> 运行命令：
> python train.py
> --config configs/quick_start/bisenet_optic_disc_512x512_1k.yml
> --do_eval
> --use_vdl
> --save_interval 500
> --save_dir output
> 其中--config改成了对应的配置文件

PaddleSeg版本：release2.3
运行命令：
python train.py
--config configs/quick_start/bisenet_optic_disc_512x512_1k.yml
--do_eval
--use_vdl
--save_interval 500
--save_dir output
其中--config改成了对应的配置文件

**Comment by Dandelion111** [comment]
> 麻烦给一下 PaddleSeg的版本及运行命令

PaddleSeg版本：release2.3
运行命令：
python train.py
--config configs/quick_start/bisenet_optic_disc_512x512_1k.yml
--do_eval
--use_vdl
--save_interval 500
--save_dir output
其中--config改成了对应的配置文件

**Comment by wuyefeilin** [comment]
你好，我们这边运行是正常的，请问你有改过代码吗

**Comment by Dandelion111** [comment]
> 你好，我们这边运行是正常的，请问你有改过代码吗

大佬你好，我没有改任何代码，在配置文件中我把num_classes改成了2，然后用的PaddleSeg中的工具转换的自己的数据集，请问这个num_classes的值包括背景吗

**Comment by wuyefeilin** [comment]
自定义数据可以参考这边进行整理及配置
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/docs/data/custom/data_prepare_cn.md#3%E6%95%B0%E6%8D%AE%E9%9B%86%E6%96%87%E4%BB%B6%E6%95%B4%E7%90%86
