### ISSUE TITLE
请问SwinTransformer的预训练权重及分割模型怎么找

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/PaddleSeg#1682]
请问SwinTransformer的预训练权重及分割模型怎么找，暂时没找到预训练权重，或者Swin相关的分割模型

**Comment by wuyefeilin** [comment]
这边有相应的分类预训练模型
https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/algorithm_introduction/ImageNet_models.md#16-swintransformer-%E7%B3%BB%E5%88%97

**Comment by huilin16** [comment]
收到，多谢
