### ISSUE TITLE
训练素材中加上了一部分只有背景图片的素材，训练报错

### ISSUE THREAD

**Issue by cuesong** [PaddlePaddle/PaddleSeg#1692]
训练素材中加上了一部分只有背景图片的素材，就跑不通了，去除可以。这种增加负样本训练的方式不可行吗？

**Comment by cuesong** [comment]
@ZeyuChen 分割中是怎么加负样本的呀，我这种方式是否可行

**Comment by haoyuying** [comment]
这种不可以，网络不支持这种格式的输入图片，没法产生输出结果

**Comment by haoyuying** [comment]
请提供具体的报错信息及使用图片，方便我们排查问题

**Comment by cuesong** [comment]
> 请提供具体的报错信息及使用图片，方便我们排查问题
背景图和原图如下：
![20210814171058_27_pic](https://user-images.githubusercontent.com/31815086/148475602-c581359c-2dd0-4215-b8ef-b8731d7cd7b6.png)
![20210814170558_28_pic](https://user-images.githubusercontent.com/31815086/148475993-73dcf955-3115-43db-b956-4e3a2b74923d.jpg)

报错信息如下（验证的路径都是对的）：
![分割模型报错信息](https://user-images.githubusercontent.com/31815086/148476101-ba1e8b54-cfc7-46dc-a3cd-1dd8e5f02a71.JPG)

配置信息：
![无标题](https://user-images.githubusercontent.com/31815086/148476328-c2a73a2e-cf59-4f33-8178-c8f07c5b7bf2.png)

**Comment by haoyuying** [comment]
看这个错误是由于数据集当中存在shape不一致导致当paddle组装batch的时候np.stack报错导致的，建议排查方向为：打印图像路径及组batch之前图片的shape，看看到底是哪张图片导致该问题。还有个地方与此报错无关，但是在val_dataset设置时候不用进行resize。
