### ISSUE TITLE
有用灵敏度和特异度评估Paddleseg训练的模型的吗  有没有相关文档

### ISSUE THREAD

**Issue by weiluonika** [PaddlePaddle/PaddleSeg#1695]
做了一个分割模型，想使用IOU，灵敏度以及特异性，进行评估模型的好坏，放到文章中去，查了一些文档，还想没有相关实例，请问有合适的文档推荐吗？

**Comment by LutaoChu** [comment]
你好，目前PaddleSeg还没有灵敏度和特异性的计算，你可以根据它们的[定义](https://zh.wikipedia.org/wiki/%E9%9D%88%E6%95%8F%E5%BA%A6%E5%92%8C%E7%89%B9%E7%95%B0%E5%BA%A6)改写metics.py试试 https://github.com/PaddlePaddle/PaddleSeg/blob/develop/paddleseg/utils/metrics.py
参考文档 https://blog.csdn.net/weixin_41783077/article/details/103886139
