### ISSUE TITLE
Access to Large-Scale Teleconferencing Video Dataset

### ISSUE THREAD

**Issue by rgsousa88** [PaddlePaddle/PaddleSeg#1696]
Hi,
First of all, thank you very much for your hard and great work. I have seen your YouTube video presentation about Large-Scale Teleconferencing Video Dataset. So, I would like to know if this dataset is available to use for commercial purpose. Thank you!

Best regards.

**Comment by LutaoChu** [comment]
Thanks for your interest in our work. Our dataset is available to use for commercial purpose. If you want to get the dataset, you can email us paddleseg@baidu.com
