### ISSUE TITLE
为什么 @paddlejs-models/humanseg 的代码里面会包含 elliptic 的代码？

### ISSUE THREAD

**Issue by anmail333** [PaddlePaddle/PaddleSeg#1698]
@paddlejs-models/humanseg：
<img width="1261" alt="Screen Shot 2022-01-10 at 10 53 03 AM" src="https://user-images.githubusercontent.com/97420291/148713195-affb01c9-345f-42cc-9cbb-40b17c943372.png">

https://www.npmjs.com/package/elliptic
![image](https://user-images.githubusercontent.com/97420291/148718711-64d5348d-ab31-4852-9d33-2b185c8284a6.png)

**Comment by juncaipeng** [comment]
这个问题和js部署关系比较密切，seg同学不太清楚，请在paddlejs repo中提问，应该会有js同学来解答，谢谢。
