### ISSUE TITLE
eiseg 内存/显存泄露bug

### ISSUE THREAD

**Issue by jiehuang165** [PaddlePaddle/PaddleSeg#1700]
测试过版本0.3.0和0.4.1.2，window平台和mac平台。随着标注图片增多，使用cpu的话内存会飙升，使用gpu的话显存会升高。
标了5张左右超了闪退。

**Comment by haoyuying** [comment]
请提供具体的图片及报错信息，方便我们复现问题。

**Comment by jiehuang165** [comment]
更正一下，重新测试了0.4.1.2在win10下不会有内存/显存飙升问题。
