### ISSUE TITLE
已经 conda install gdal，但是PaddleSeg 提示需要安装gdal，pdiparams 加载不了

### ISSUE THREAD

**Issue by Mrwow** [PaddlePaddle/PaddleSeg#1701]
我在anaconda里新建了一个python 3.9.7的环境，然后在这个环境中安装了
pip install paddlepaddle==2.2.1
pip install eiseg
conda install gdal

但是，当在PaddleSeg 中打开tif卫星文件时，还是提示没有安装gdal。请问大神如何解决这个问题？

**Comment by wuyefeilin** [comment]
尝试一下 pip install哈

**Comment by Mrwow** [comment]
我再用pip install gdal时， 提示 Requirement already satisfied. 现在是mac的系统，macos Big Sur 11.6

**Comment by Mrwow** [comment]
我尝试了不在anaconda里的环境安装了低版本的gdal，然后可以加载tif文件了：
pip install paddlepaddle==2.2.1
pip install eiseg
pip install gdal==2.4.2.

python 3.7.3.   macos Big Sur 11.6

但是新的问题出现了，只识别pdparams文件，不识别pdiparams,但是加载pdparams文件就会报错：
<img width="417" alt="image" src="https://user-images.githubusercontent.com/14700737/149032248-ee033ede-0413-4b78-bba6-abe1c122c745.png">

我把pdiparams 改成pdparams，也报错：
<img width="373" alt="image" src="https://user-images.githubusercontent.com/14700737/149032449-63bd3ea2-0229-494f-8bc4-9756cef25348.png">

**Comment by haoyuying** [comment]
不会的，0.4版本以上的eiseg才有遥感插件功能，请查看develop版本上eiseg的模型下载，如果不行就重新卸载安装eiseg及paddle2.2版本，此版本需要加载静态图模型pdiparams,详情请查看文档https://github.com/PaddlePaddle/PaddleSeg/tree/develop/EISeg

**Comment by Mrwow** [comment]
我看了你们的代码，发现还要安装rasterio才行。我已经修改了相关的文档说明，然后pull 了一个request给你们了

**Comment by zhudongwork** [comment]
eiseg不能打开tif文件吗
