### ISSUE TITLE
完整的语义分割网络的预训练模型

### ISSUE THREAD

**Issue by zhijiejia** [PaddlePaddle/PaddleSeg#1703]
请问，像OCRNet这种模型有完整的预训练模型吗，我只找到backbone的预训练模型，Segementation这部分网络并没有找到有预训练模型的，请问这部分预训练模型可以在哪获取的到吗？

**Comment by zhijiejia** [comment]
...,我找到了，是相应的预训练模型都会放在对应网络的config的readme里的吧

**Comment by wuyefeilin** [comment]
是的
