### ISSUE TITLE
contribution of a PaddleSeg onnxruntime C++ sample

### ISSUE THREAD

**Issue by xmba15** [PaddlePaddle/PaddleSeg#1714]
Hi PaddleSeg's dev team. Thank you for the great repo.
I created a C++ onnxruntime app sample for model trained by PaddleSeg. It took me some time to figure out how to use onnxruntime cpp to serve the model. So maybe some others can somehow know how to use PaddleSeg onnx cpp from this app:

https://github.com/xmba15/onnx_runtime_cpp#semantic-segmentation-paddle-seg
https://github.com/xmba15/onnx_runtime_cpp/blob/master/examples/SemanticSegmentationPaddleSegBisenetv2App.cpp

**Comment by juncaipeng** [comment]
Firstly, thanks for your contribution. 
You can create a folder named 'onnxruntime_cpp' under `PaddleSeg/deploy/` and push the demo to the folder. Please refer to the [cpp demo](https://github.com/PaddlePaddle/PaddleSeg/tree/develop/deploy/cpp)  and make the demo concise.
Once you create a PR, we will review and merge it.
Thank you again.

**Comment by xmba15** [comment]
@juncaipeng let me give it a try.

**Comment by xmba15** [comment]
@juncaipeng 
I created the PR here
https://github.com/PaddlePaddle/PaddleSeg/pull/1743

**Comment by xmba15** [comment]
PR merged, so close the issue.
