### ISSUE TITLE
开始训练读取数据时报错SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.

### ISSUE THREAD

**Issue by xinliyangguang** [PaddlePaddle/PaddleSeg#1716]
使用paddle-2.0训练PaddleSeg-release-v2.0时运行脚本报错如下：
![image](https://user-images.githubusercontent.com/53338761/149308521-5238a6d9-fc76-4129-9074-b4fa374dd575.png)
开始训练的脚本命令：
python3 ./train.py --config ./zhaoxin34/baidu/personal-code/icoding/PaddleSeg-release-v2.0/configs/deeplabv3/deeplabv3_resnet50_os8_cityscapes_1024x512_80k.yml --save_dir ./zhaoxin34/baidu/personal-code/icoding/PaddleSeg-release-v2.0/output/deeplab20211214 --log_iters 10

**Comment by haoyuying** [comment]
这个目前报错位置在dataloder，报错原因是transformers.py 第57行读不到图片导致cv2.imread(im)为none导致的，看下dataloader是不是读入了什么不存在的图片路径。

**Comment by xinliyangguang** [comment]
> 这个目前报错位置在dataloder，报错原因是transformers.py 第57行读不到图片导致cv2.imread(im)为none导致的，看下dataloader是不是读入了什么不存在的图片路径。

dataset_root和train_path字段配置如下
![image](https://user-images.githubusercontent.com/53338761/149469489-3caaf7cc-9b1e-4dc5-a9bd-61564b04cd10.png)

数据路径如下：
![image](https://user-images.githubusercontent.com/53338761/149469368-a0effa69-9031-4e6c-b130-26b8d79a5043.png)


我的自定义数据集结构如下：
segdata20211214crop
----images
--------1.jpg
--------2.jpg
--------3.jpg
--------4.jpg
----labels
--------1.png
--------2.png
--------3.png
--------4.png
----train.txt
----test.txt

不知是哪里出了问题
