### ISSUE TITLE
无法标注，单击只能添加样本点，不自动标注，还出现乱的标注条，提示无法生成标注边界

### ISSUE THREAD

**Issue by lililikaixu** [PaddlePaddle/PaddleSeg#1717]
![图片](https://user-images.githubusercontent.com/91947281/149443225-4ee066a9-e406-4fa6-86fe-df107fd43f64.png)

**Comment by haoyuying** [comment]
使用的什么版本的eiseg及paddle呢，是否把右边的阈值设置在了0.5呢

**Comment by Atiuiee** [comment]
请问您解决了么，遇到同样的问题
