### ISSUE TITLE
Out of memory error on GPU 0. Cannot allocate 400.000244MB memory on GPU 0, 7.288696GB memory has been allocated and available memory is only 155.187500MB.

### ISSUE THREAD

**Issue by farukonfly** [PaddlePaddle/PaddleSeg#1723]
按照文档跑icdar2015检测模型的训练
python3 tools/train.py -c configs/det/det_mv3_db.yml -o Global.pretrained_model=./pretrain_models/MobileNetV3_large_x0_5_pretrained

报错：
Out of memory error on GPU 0. Cannot allocate 400.000244MB memory on GPU 0, 7.288696GB memory has been allocated and available memory is only 155.187500MB.

nvidia-smi
![image](https://user-images.githubusercontent.com/18646553/149858468-894925d3-c04e-4bd6-83e7-b29c3a7a823b.png)

是在AWS EC2的机器上运行

**Comment by wuyefeilin** [comment]
显存不够，可以调小batch_size试试

**Comment by farukonfly** [comment]
> 显存不够，可以调小batch_size试试

你看下我截图，显存7460MB，应该是够的呀，另外还问下，batch_size是在哪些调
