### ISSUE TITLE
val 过程的batch_size为什么是1？

### ISSUE THREAD

**Issue by zhijiejia** [PaddlePaddle/PaddleSeg#1728]
不理解，为啥val 过程的batch_size为什么是1？，为啥不设置一个更大的值，或者设置成一个参数呢？

**Comment by shiyutang** [comment]
Because we need to evaluate the test set on its original size to avoid accuracy loss.  If we set bs bigger than 1, the video memory may not be enough.

**Comment by zhijiejia** [comment]
如果我把 batch_size 改为更大的数，这个精度损失会很大吗？ 验证集只有前向没有后向啊，为啥你说比1大，显存就没了？ 你们训练显存咋够的

**Comment by wuyefeilin** [comment]
还有一点是因为单卡bs等于1可以避免在多卡评估时个别图象重复预测的情况

**Comment by shiyutang** [comment]
if you set bs>1, it is likely that video memory will not be enough. If it is enough, you are free to set it bigger than 1.

**Comment by shiyutang** [comment]
If you have any further questions, you are very welcome to reopen it.
