### ISSUE TITLE
推理seg示例代码，使用trt加速，将use_trt置为true时报错

### ISSUE THREAD

**Issue by qll1003** [PaddlePaddle/PaddleSeg#1729]
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The input [x] shape of trt subgraph is [-1,3,-1,-1], please enable trt dynamic_shape mode by SetTRTDynamicShapeInfo. (at ..\paddle/fluid/inference/tensorrt/engine.h:100)

我的做法是：添加SetTRTDynamicShapeInfo函数
		std::map<std::string, std::vector<int>> min_input_shape = {
		 {"x", {1, 3, 10, 10}} };
		std::map<std::string, std::vector<int>> max_input_shape = {
			{"x", {1, 3, 1024, 1024}} };
		std::map<std::string, std::vector<int>> opt_input_shape = {
			{"x", {1, 3, 320, 320}} };
		infer_config.SetTRTDynamicShapeInfo(min_input_shape,max_input_shape, opt_input_shape,false);
然后又报错：----------------------
Error Message Summary:
----------------------
InvalidArgumentError: some trt inputs dynamic shape info not set, check the INFO log above for more details.
  [Hint: Expected all_dynamic_shape_set == true, but received all_dynamic_shape_set:0 != true:1.] (at ..\paddle/fluid/inference/tensorrt/convert/op_converter.h:245)
请问一下，后续该怎么办啊

**Comment by juncaipeng** [comment]
你好，这个错误是使用trt时需要开启动态shape，请先参考PaddleInference文档修改运行代码：https://paddleinference.paddlepaddle.org.cn/optimize/paddle_trt.html

我们会尽快完善该demo。

**Comment by qll1003** [comment]
> 你好，这个错误是使用trt时需要修改开启动态形状，请先修改PaddleInference文档运行代码：https://paddleinference.paddlepaddle.org.cn/optimize/paddle_trt.html
> 
> 我们会尽快修复该演示。

好的，首先感谢你们尽快修复。就是我还想问一下，其实我已经按照这个修改了运行代码。然后看了一下你发得文档。其中我看见动态shape得支持模型里面没有bisenet_demo_model这个模型，是因为我得模型选择错误了嘛？导致得错误嘛？

**Comment by juncaipeng** [comment]
这是develop分支的使用demo：https://github.com/PaddlePaddle/PaddleSeg/blob/develop/docs/deployment/inference/cpp_inference_cn.md

由于PaddleInference对bisenetv2支持有点问题，我们还在修复，所以换成stdcseg模型。该模型比bisenet精度更高、速度更快。

**Comment by Lyric0620** [comment]
@juncaipeng 请问pp-LiteSeg目前支持trt了吗
