### ISSUE TITLE
推理如何获取缺陷类别

### ISSUE THREAD

**Issue by Huihuihh** [PaddlePaddle/PaddleSeg#1733]
利用2.3版本的PaddleSeg进行模型预测，只能得到伪彩色标注图和叠加图，针对识别到的缺陷如何确定其类别

**Comment by haoyuying** [comment]
在训练的时候，数据集有多少个类别的缺陷的标注呢。如果训练时候存在多类别，在伪彩色图里读入是有体现的。

**Comment by Huihuihh** [comment]
> 在训练的时候，数据集有多少个类别的缺陷的标注呢。如果训练时候存在多类别，在伪彩色图里读入是有体现的。

在伪彩色图里是可以看到不同缺陷显示，但是并不知道缺陷类别
![image](https://user-images.githubusercontent.com/50944935/150284743-371993e3-5992-4100-b917-227b3224a7ec.png)

**Comment by Huihuihh** [comment]
请问这个问题现在有结果吗，推理如何获得缺陷类别

**Comment by Huihuihh** [comment]
通过cv2.findContours获取缺陷轮廓，再通过获取轮廓其中一个点对应的值，就可以得到该区域缺陷对应的class id
binary = np.array(mask)
binary = binary.astype(np.uint8)
binary, contours, hierarchy = cv2.findContours(binary,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
for i in range(n):
    class_id = binary[contours[i][0][0][1],contours[i][0][0][0]]
