### ISSUE TITLE
为何调不起来多个gpu

### ISSUE THREAD

**Issue by LISIJIA0629** [PaddlePaddle/PaddleSeg#1734]
你好，
首先我通过export CUDA_VISIABLE_DEVICES='0,1,2,3' 调用4个gpu
然后在运行代码，但是显示memory 不够。其实很足啊

SystemError: (Fatal) Operator conv2d raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError:

Out of memory error on GPU 0. Cannot allocate 413.281250MB memory on GPU 0, 23.532227GB memory has been allocated and available memory is only 123.312500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)
. (at /paddle/paddle/fluid/imperative/tracer.cc:230)

INFO 2022-01-20 12:39:07,498 launch_utils.py:342] terminate all the procs
ERROR 2022-01-20 12:39:07,498 launch_utils.py:636] ABORT!!! Out of all 4 trainers, the trainer process with rank=[0, 1, 2, 3] was aborted. Please check its log.
INFO 2022-01-20 12:39:11,503 launch_utils.py:342] terminate all the procs
INFO 2022-01-20 12:39:11,503 launch.py:391] Local processes completed.

**Comment by haoyuying** [comment]
Out of all 4 trainers, the trainer process with rank=[0, 1, 2, 3] was aborted. Please check its log.这一句说明已经用了四个gpu了。可以具体看下显存增长，是具体跑了什么数据集，或者降低batch_size 试一下。
