### ISSUE TITLE
[General Issue] 如何将coco数据集转化为符合paddleseg要求的数据格式

### ISSUE THREAD

**Issue by Cristhine** [PaddlePaddle/PaddleSeg#1736]
如何将coco数据集转化为符合paddleseg要求的数据格式 有没有相关脚本，或者我看到那个cocostuff.yml的数据 如何下载呢 有没有相关教程

**Comment by haoyuying** [comment]
coco stuff准备方式：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.4/docs/data_prepare_cn.md
目前paddleseg没有提供转换脚本，欢迎您转成功后将pr贡献给我们。

**Comment by Cristhine** [comment]
> coco stuff准备方式：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.4/docs/data_prepare_cn.md 目前paddleseg没有提供转换脚本，欢迎您转成功后将pr贡献给我们。

我自己做了一些转换成mask形式的label lable图的维度是 (h, w, 3) 执行tools/gray2pseudo_color.py 报错Too many dimensions: 3 > 2. 是什么问题
