### ISSUE TITLE
报错num classes缺少

### ISSUE THREAD

**Issue by Cristhine** [PaddlePaddle/PaddleSeg#1739]
按照要求制作自己数据集，然后替换segformer_b2_cityscapes_1024x1024_160k.yml中数据为自己的数据集 别的都没换 启动训练报错
![image](https://user-images.githubusercontent.com/26667855/150508660-692d7feb-14dc-47d8-9338-c5774631076d.png)

我看yml中是有这个参数的 除了数据路径别的都没进行修改

**Comment by henryccl** [comment]
你好 请问这个问题解决了吗？

**Comment by LutaoChu** [comment]
你好，给一下你的运行命令我们复现一下

**Comment by Winnie202** [comment]
请问解决了吗

**Comment by LutaoChu** [comment]
请提供一下复现的命令和yml

**Comment by henryccl** [comment]
不好意思 最近比较忙现在才看到，在这个issue里面关于该问题的有解答https://github.com/PaddlePaddle/PaddleSeg/issues/796
感谢解答！！！
