### ISSUE TITLE
Out of memory error on GPU 0. Cannot allocate 15.213047GB memory on GPU 0, available memory is only 471.687500MB.

### ISSUE THREAD

**Issue by jaffe-fly** [PaddlePaddle/PaddleSeg#174]
![image](https://user-images.githubusercontent.com/49515380/75607656-64746c80-5b34-11ea-9fdc-d5c7cd7d8294.png)
![image](https://user-images.githubusercontent.com/49515380/75607664-78b86980-5b34-11ea-8111-ebea83e80a18.png)
在aistudio的GPU上推理一张图片 都 这个问题是什么原因，图片大小如下
![image](https://user-images.githubusercontent.com/49515380/75607697-d9e03d00-5b34-11ea-86a1-3505b2b9479c.png)

**Comment by LutaoChu** [comment]
可以在命令行输入`export FLAGS_fraction_of_gpu_memory_to_use=0.99`试试
另外检查一下是不是有其他程序也占用了gpu显存

**Comment by jaffe-fly** [comment]
已经设置成099了 并且没有其他程序占用GPU  程序运行起来之后，检测到的显卡占用
![image](https://user-images.githubusercontent.com/49515380/76137765-82cdf100-607b-11ea-98b9-5c5993a9dd60.png)
就yi'zh一张图片，图片也不大 怎么就这么耗显存，这样训练出来部署也不实际

**Comment by ZeyuChen** [comment]
@jaffe-fly 能提供你使用的模型结构吗？这么小的图片V100应该是可以预测的。

**Comment by jaffe-fly** [comment]
模型是
![image](https://user-images.githubusercontent.com/49515380/76139612-aa798500-608c-11ea-9ae1-dc61b8f61df2.png)

**Comment by jaffe-fly** [comment]
我重新训练了 还是不行，你们有邮箱吗 我把训练权重和配置文件重新发给你帮我看看，比较着急部署

**Comment by LutaoChu** [comment]
@jaffe-fly  chulutao@baidu.com    测试图片也发给我吧

**Comment by hp-cuiwb** [comment]
怎么解决的

**Comment by jaffe-fly** [comment]
再等等，官方正在查找问题

**Comment by jaffe-fly** [comment]
官方回复：
!python /home/aistudio/infer_fire.py --conf=/home/aistudio/freeze_model/deploy.yaml --input_dir=/home/aistudio/work/dataset/images/test/   --use_pr=True
后面一定要加 --use_pr=True  否则就会报错

**Comment by jaffe-fly** [comment]
解决办法：

在程序运行的前面添加如下代码

os.environ[‘FLAGS_eager_delete_tensor_gb’] = “0.0”

主要作用是 GPU memory garbage collection optimization flags

另外 网上的其他办法做一个总结

1 如果是在多卡的环境下运行的出现错误
可以设置
CUDA_VISIBLE_DEVICES=“0” #后面是显卡编号，确保程序在这张显卡上运行

2 如果是在自己写的代码下运行报错
一定要开启model.eval()
