### ISSUE TITLE
paddleseg/models/hrnet_contrast.py 中没有执行 init_weight

### ISSUE THREAD

**Issue by zhijiejia** [PaddlePaddle/PaddleSeg#1742]
paddleseg/models/hrnet_contrast.py 中__init__()没有执行 init_weight，导致hrnet_w48_contrast 没法加载完整的模型

**Comment by zhijiejia** [comment]
https://bj.bcebos.com/paddleseg/dygraph/ccf/ocr_hrnetw48_rs_256x256_160k/model.pdparams

顺便问一下，我看到有人使用了这个链接对应的预训练模型，我从paddleseg的github主页怎么找到这个链接啊？ 找不到ccf那个啊？

**Comment by zhijiejia** [comment]
readme的日期写错了，2022年了
![image](https://user-images.githubusercontent.com/43838913/150669881-f19175c8-88a4-43d1-a380-dda7abe9c874.png)

**Comment by juncaipeng** [comment]
> 

收到，我们会马上修复。
