### ISSUE TITLE
[General Issue]请问如何保证可以复现精度

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/PaddleSeg#1744]
请问如何保证一次训练的精度可以完全复现，误差为0

我设置train.py中的seed=102，多次训练，精度仍然有误差

![image](https://user-images.githubusercontent.com/36887207/150716254-378db81c-76e8-477d-873e-07678b01dcbd.png)
![image](https://user-images.githubusercontent.com/36887207/150716303-3581c955-058c-461a-a287-ea32f531e288.png)
![image](https://user-images.githubusercontent.com/36887207/150716373-f9bf9384-f20b-4fe9-9a27-2ac0f5f3cf7f.png)

**Comment by juncaipeng** [comment]
训练本身就无法完全保证一致，目前只提供设置seed的方式尽可能保证相同。
