### ISSUE TITLE
[General Issue]导出的Matting模型，无法利用PaddleX进行部署？

### ISSUE THREAD

**Issue by 6UOOON9** [PaddlePaddle/PaddleSeg#1745]
1. PaddleSeg版本：PaddleSeg release/2.3
 2. PaddlePaddle版本：PaddlePaddle 2.1.0
 3. 操作系统信息：Windows
 4. Python版本号：Python3.8
导出了PP-HumanSeg的模型，是可以利用PaddleX的进行windows下的C++部署的，但是试了一下导出的Matting模型则显示以下信息：
Unexpected transforms op name: 'LoadImages'
Fail to generate standard configuration of tranforms

**Comment by wuyefeilin** [comment]
删除导出文件deploy.yml中的LoadImages算子试试

**Comment by 6UOOON9** [comment]
> 删除导出文件deploy.yml中的LoadImages算子试试

删了就是这样：
Unexpected transforms op name: 'ResizeByShort'
Fail to generate standard configuration of tranforms
再删就直接连报错信息都没有了。。。

**Comment by FlyingQianMM** [comment]
@6UOOON9 请确认下Matting模型的model.yml涉及的预处理算子在PaddleX是否都有实现。如果有，需替换成PaddleX的预处理算子和相应的model.yml，PaddleX的预处理算子定义：https://github.com/PaddlePaddle/PaddleX/blob/develop/paddlex/cv/transforms/operators.py 。如果不清楚PaddleX的分割模型的model.yml格式，可以先跑下https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials/train/semantic_segmentation

**Comment by FlyingQianMM** [comment]
@6UOOON9 可以参考下[PaddleX issue 使用paddledetection训练出来的非paddleX模型，可以转换成paddleX模型吗](https://github.com/PaddlePaddle/PaddleX/issues/1371) ，有类似的需求和解决方法。
