### ISSUE TITLE
DeepLabv3+模型使用教程——训练问题

### ISSUE THREAD

**Issue by wujieqi01** [PaddlePaddle/PaddleSeg#175]
DeepLabv3+模型使用教程中，一直到python pdseg/train.py --use_gpu --cfg ./configs/deeplabv3p_xception65_optic.yaml运行后，终端一直连续出现'NoneType' object has no attribute 'run'。
centos6.5 版本1.7.0post97

**Comment by LielinJiang** [comment]
您好，我使用最新的release/v0.4.0分支，paddle版本1.7.0没能够复现您的问题。您是否用的是上述环境？如果不是，建议更新一下

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。

**Comment by gujingxiao** [comment]
很奇怪我这里训练也出现了这个问题。我使用的是release 0.6.0版本，paddle1.8.0。之前训练一直都是好好的，没有这个问题，但是昨天重启了服务器，再训练就一直出现这个打印，反复出现，也看不到是哪里报的错，我从reader里进行了数据可视化，也是正确的。目前毫无头绪。

**Comment by gujingxiao** [comment]
更新描述：我刚刚使用export CUDA_VISIBLE_DEVICES=0，强制改成单卡训练，此现象消失；然后再开放多卡训练：export CUDA_VISIBLE_DEVICES=0,1，此现象又出现。然后我这边重启了服务器，再尝试这个过程，此现象多卡训练时也消失了。反复重启服务器4次，单卡均没有出现此现象，多卡偶发出现此现象。还请官方根据此现象进行查验

**Comment by gujingxiao** [comment]
> 此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。

请官方根据描述查验此问题，谢谢

**Comment by nepeplwu** [comment]
@gujingxiao 报错堆栈麻烦贴下

**Comment by gujingxiao** [comment]
> @gujingxiao 报错堆栈麻烦贴下

你好，这个现象并没有报错，程序也并没有停止，而是继续在运行。在系统打印了cuda版本之后，又打印了开始multi thread reader，到这里一切正常。然后突然开始满屏都是'NoneType' object has no attribute 'run'的打印，中间还夹杂着正常训练的loss打印，我检查了loss好像也是正常的。所以并没有程序终止的报错信息，只是出现了满屏幕的打印。我重启了服务器之后，这个问题就没了。

**Comment by CeciliaPYY** [comment]
![e5c5065f682717ca6d7bb727d813eb8f](https://user-images.githubusercontent.com/30582437/99958999-41c26c00-2dc5-11eb-8b7b-715e9c1a9ce9.png)

同样，多卡情况下出现该问题。单卡无问题。hrnet_optic config。
paddle180, centos7

起训练命令如下，
```# 指定GPU卡号（以0号卡为例）
export CUDA_VISIBLE_DEVICES=0,1
# 训练
python pdseg/train.py --cfg ./configs/hrnet_optic.yaml \
    --use_gpu  --use_vdl \
    --vdl_log_dir train_log --do_eval
```

训练配置如下，
![9cc668d987826d07957a1dd0e4ab92eb](https://user-images.githubusercontent.com/30582437/99959118-6ae2fc80-2dc5-11eb-8307-bfe9a8b5497d.png)

**Comment by CeciliaPYY** [comment]
debug解决了，应该是没有安装NCCL的问题， 安装完之后还要将lib路径加到LD_LIBRARY_PATH里面去。
