### ISSUE TITLE
[Feature Request]BootstrappedCrossEntropyLoss实现和参考文献不一致？

### ISSUE THREAD

**Issue by lsfhgty** [PaddlePaddle/PaddleSeg#1750]
BootstrappedCrossEntropyLoss的实现和给出的参考文献中的方法好像不一样？这里的实现看上去更像是ohemloss

**Comment by haoyuying** [comment]
您好，可否提供更详细的问题描述供我们来对比问题，感谢您的贡献。

**Comment by michaelowenliu** [comment]
@lsfhgty hi, the two methods share a few similar features. Are you using OHEM？

**Comment by lsfhgty** [comment]
> @lsfhgty hi, the two methods share a few similar features. Are you using OHEM？

不是，我只是刚好看到这个loss。发现参考文献中的实现方式好像是想减轻噪声label对于训练的影响，但是这边的loss的实现和文中推导的公式似乎对不上，我不清楚是否是我理解错了。
<img width="880" alt="d7c230f297d85189d93d58b265bef77f" src="https://user-images.githubusercontent.com/61674533/151284655-7d502a10-c085-4646-a0c5-92dc47c9afd4.png">

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
