### ISSUE TITLE
paddle.jit.save保存模型以后，训练变慢

### ISSUE THREAD

**Issue by ZhouFangru** [PaddlePaddle/PaddleSeg#1755]
您好，我使用paddle.jit.save保存模型，更改代码如下：
![image](https://user-images.githubusercontent.com/24693920/151483245-26afa74d-b195-48a5-aa4d-e47a427e9381.png)
发现模型刚开始训练时 batch_cost大约为0.2，在保存一次模型以后，训练变慢batch_cost=1.5（代码原来保存模型的方式不会出现这个问题）
![image](https://user-images.githubusercontent.com/24693920/151483348-04171e28-7374-4a24-8f67-311084b270fd.png)
![image](https://user-images.githubusercontent.com/24693920/151483142-dc71aa86-e669-4928-ac28-e32f490f6c82.png)
请问：
1、我想保存*.pdmodel,是否只需要更改paddle.jit.save保存模型即可，还是需要改动其他地方？
2、为什么第一次保存模型以后，训练会变慢？
期待您的解答，感谢~

**Comment by juncaipeng** [comment]
你好，建议你不用修改保存模型的代码。原先代码会在训练中保存*.pdparams，等训练完后，使用seg的导出功能加载精度最高的*pdparams导出*.pdmodel。
