### ISSUE TITLE
paddle   ImportError，大佬救命

### ISSUE THREAD

**Issue by Huhaobangbangbang** [PaddlePaddle/PaddleSeg#1756]
这是我的paddle版本信息（换了其他的paddle版本也不行）
PaddlePaddle 2.0.0-rc1, compiled with
    with_avx: OFF
    with_gpu: ON
    with_mkl: OFF
    with_mkldnn: OFF
    with_python: ON

上面显示安装成功，但是会出现
ImportError: /home/tux/conda/envs/huh/lib/python3.9/site-packages/paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE

**Comment by haoyuying** [comment]
您好，paddle的安装问题请移步paddle repo ：https://github.com/PaddlePaddle/Paddle 以便获得更专业的回复。
