### ISSUE TITLE
Which data set was used to pre-train the ResNet101 for GCNet?

### ISSUE THREAD

**Issue by khaep** [PaddlePaddle/PaddleSeg#1757]
Hello there,

can you please give me an information about the loaded pretrained ResNet101 backbone,
that was used to train [GCNet](https://github.com/PaddlePaddle/PaddleSeg/blob/742555c609b0cdfe8976d674937fdb92d73fd496/configs/gcnet/gcnet_resnet101_os8_cityscapes_1024x512_80k.yml#L6).

Which data set was used to pre-train the ResNet101 backbone network?

Was it some thing like imagenet?

Thank you for answering.

Kind regards

**Comment by michaelowenliu** [comment]
@KHeap25 Hi, we use the pretrained model provided by PaddleClas, https://github.com/PaddlePaddle/Paddleclas

**Comment by khaep** [comment]
Thanks for the information,

so it seems to be that the loaded ResNet101 backbone was pretrained with  the ImageNet dataset.

[Readme](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/README_en.md#features) of PaddleClas says:
"Rich library of pre-trained models: Provide a total of 164 ImageNet pre-trained models in 35 series, among which 6 selected series of models support fast structural modification."

Can you confirm my understanding?
