### ISSUE TITLE
学习率无法由优化器调整

### ISSUE THREAD

**Issue by Leon-E-Zion** [PaddlePaddle/PaddleSeg#1763]
查看训练输出数据时发现学习率不随优化器改变
查看源码时，发现是由yaml文件参数与Config进行固定
能否使学习率只由优化器进行调整

**Comment by shiyutang** [comment]
I am not sure what is your need.
But FYI, lr in paddle equals to the lr in optimizer multiply parameterAtrr lr and lr controlled by lr_scheduler.
If you want to change the lr, you can pass a lr_scheduler into you optimizer

**Comment by shiyutang** [comment]
If you have any further questions, you are very welcome to reopen it.
