### ISSUE TITLE
error in cross_entropy

### ISSUE THREAD

**Issue by HamidrezaHayatjou** [PaddlePaddle/PaddleSeg#1764]
hi
 1. PaddleSeg version: (PaddleSeg v2.4.0)
 2. PaddlePaddle version: (PaddlePaddle 2.2.2)
 3. Operation system: (Linux)
 4. Python version: (Python3.7)
 5. CUDA/cuDNN version: (e.g. CUDA11.)

I tried to use a model according to the instructions and used the cityscape database. But I got the following error and I can not understand where the problem is. thank you for your help.
my code : 
`from paddleseg.datasets import  Cityscapes
import paddleseg.transforms as T
from paddleseg.models import OCRNet
from paddleseg.models.backbones import HRNet_W48
from paddle import optimizer as optim
from paddleseg.models.losses import CrossEntropyLoss

transforms = [T.Resize(target_size=(256, 256)), T.Normalize()]
train_data =  Cityscapes(transforms=transforms, dataset_root='/cityscape', mode='train')
validation_data =  Cityscapes(transforms=transforms, dataset_root='/cityscape', mode='val') 

backbone=HRNet_W48()
backbone_indices = [-1]
pretrained = '/paddleseg_chekpooints/ocrnet_hrnetw48.pdparams'
model = OCRNet(num_classes=19, backbone=backbone, backbone_indices=backbone_indices, pretrained=pretrained) 

losses = {'types':[CrossEntropyLoss(),CrossEntropyLoss()],'coef':[1,1]}
optimizer = optim.Momentum(optim.lr.PolynomialDecay(0.01,
                                                   power=0.9,
                                                   decay_steps=1000,
                                                    end_lr=0),
                           parameters=model.parameters(),
                           momentum=0.9,
                           weight_decay=4.0e-5)

from paddleseg.core import train
train(
     model=model,
     train_dataset=train_data,
     val_dataset=validation_data,
     optimizer=optimizer,
     save_dir='output',
     iters=50,
     batch_size=2,
     save_interval=200,
     log_iters=10,
     losses=losses,
     use_vdl=False) `

error : 
ValueError: label should not out of bound, but gotTensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [26])

**Comment by debug851** [comment]
I HAVE the same error

**Comment by 02825cm** [comment]
me too

**Comment by 02825cm** [comment]
How to solve it?

**Comment by 02825cm** [comment]
ValueError: label should not out of bound, but gotTensor(shape=[1], dtype=int64, place=CPUPlace, stop_gradient=True,
       [181])

**Comment by nqthai309** [comment]
How to solve it? help me

**Comment by nqthai309** [comment]
i solved it. image annotations must type *.png

**Comment by 02825cm** [comment]
I have finished it,but it is erroe

**Comment by 02825cm** [comment]
i have made it ,but it's useless

**Comment by debug851** [comment]
Solved.I switched the loss function at first, and it worked.  But the segmentation is only the boundary.  So you need to check that your label meets the following criteria: single-channel image, PNG format, and the gray value of the label should be 0,1...  Instead of 0,255.  Let's just say the mentor's push helped.🙂

**Comment by HamidrezaHayatjou** [comment]
hi, in my case i was using Cityscape dataset, I had set the number of classes to 19, but I forgot that the dataset is 35 classes and I had to change it to 19 classes using the cityscape script. Doing this solved my problem.

**Comment by daibin88** [comment]
ValueError: label should not out of bound, but gotTensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,[2])
使用CrossEntropyLoss出现上述问题，更换BCEloss就不会出现这个问题，请问如何解决

**Comment by wayneck** [comment]
`
.... File "/home/project/baidu/PaddleSeg/paddleseg/models/losses/cross_entropy_loss.py", line 85, in forward loss = F.cross_entropy( File "/home/.local/lib/python3.8/site-packages/paddle/nn/functional/loss.py", line 1661, in cross_entropy raise ValueError("label should not out of bound, but got{}". ValueError: label should not out of bound, but gotTensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True, [700])
`
MY annotations file is gray png file, got the same error.
It look like paddle read annotations file error.
