### ISSUE TITLE
quick start 中的predict.py 运行，对本地图片预测为何需要联网连接到数据集 optic_disc_seg.zip ?

### ISSUE THREAD

**Issue by bldu** [PaddlePaddle/PaddleSeg#1766]
![image](https://user-images.githubusercontent.com/43374826/152964698-99db34bc-31db-48ef-96a3-81d9f083be64.png)

如图所示，我将模型下到了本地，然后按照quick start中的命令行执行 predict.py。由于我没有联网，就直接在 connecting 这里报错了。我想知道为什么一定要连接到云端的数据集？

**Comment by michaelowenliu** [comment]
@bldu Hi, the quick-start demo requires optic dataset. You can also download it locally in advance.
