### ISSUE TITLE
请问fast scnn模型有c++的推理demo吗

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleSeg#1768]
请问fast scnn模型有paddle lite框架 c++的推理demo吗

**Comment by juncaipeng** [comment]
有的，可以参考文档和示例：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.4/docs/deployment/inference/cpp_inference_cn.md

**Comment by juncaipeng** [comment]
使用paddleseg导出模型后，可以参考lite [c++文档](https://paddle-lite.readthedocs.io/zh/latest/user_guides/cpp_demo.html)进行部署。

**Comment by Dandelion111** [comment]
> 使用paddleseg导出模型后，可以参考lite [c++文档](https://paddle-lite.readthedocs.io/zh/latest/user_guides/cpp_demo.html)进行部署。

好的，谢谢大佬
