### ISSUE TITLE
使用inf跑deeplabv3+mobilnetv2报错

### ISSUE THREAD

**Issue by y-kl8** [PaddlePaddle/PaddleSeg#177]
使用量化后的deeplabv3+mobilnetv2_cityscapes模型，出现如下报错：

Traceback (most recent call last):
  File "infer.py", line 321, in <module>
    run(gflags.FLAGS.conf, gflags.FLAGS.input_dir, gflags.FLAGS.ext)
  File "infer.py", line 303, in run
    seg_predictor.predict(imgs)
  File "infer.py", line 278, in predict
    self.output_result(img_datas, output_data, gflags.FLAGS.use_pr)
  File "infer.py", line 228, in output_result
    score_png[i, j] = color_map[score_png[i, j, 0]]
IndexError: list index out of range

**Comment by slf12** [comment]
> 使用量化后的deeplabv3+mobilnetv2_cityscapes模型，出现如下报错：
> 
> Traceback (most recent call last):
> File "infer.py", line 321, in
> run(gflags.FLAGS.conf, gflags.FLAGS.input_dir, gflags.FLAGS.ext)
> File "infer.py", line 303, in run
> seg_predictor.predict(imgs)
> File "infer.py", line 278, in predict
> self.output_result(img_datas, output_data, gflags.FLAGS.use_pr)
> File "infer.py", line 228, in output_result
> score_png[i, j] = color_map[score_png[i, j, 0]]
> IndexError: list index out of range

麻烦说下使用的分支和评估文件的路径

**Comment by ShaoCorn** [comment]
使用deploy/python/infer.py，并使用该页面提供的模型时，使用cpu推理可有正常结果，使用GPU时报错。

![err01](https://user-images.githubusercontent.com/38242997/76140460-8ec6ac80-6095-11ea-81bd-8f6222b86dd2.jpg)
![err02](https://user-images.githubusercontent.com/38242997/76140463-9a19d800-6095-11ea-896b-fdcbfaaa368b.png)

![err03](https://user-images.githubusercontent.com/38242997/76140535-8cb11d80-6096-11ea-9c75-1217389efcbd.jpg)

**Comment by slf12** [comment]
> 使用deploy/python/infer.py，并使用该页面提供的模型时，使用cpu推理可有正常结果，使用GPU时报错。

int8量化模型在GPU上进行推理走的是tensorrt模式，tensorrt支持的硬件有限，麻烦发一下您的GPU型号看下是否支持。

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。
