### ISSUE TITLE
[Bug]您好，我运行MODNet的训练代码，输出的log是乱码的，麻烦看一下是什么原因导致的。

### ISSUE THREAD

**Issue by Emmmmmaa** [PaddlePaddle/PaddleSeg#1770]
------------Environment Information-------------
platform: Linux-4.15.0-151-generic-x86_64-with-debian-buster-sid
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
Paddle compiled with cuda: True
NVCC: Cuda compilation tools, release 10.2, V10.2.89
cudnn: 7.6
GPUs used: 1
CUDA_VISIBLE_DEVICES: 0
GPU: ['GPU 0: GeForce RTX', 'GPU 1: GeForce RTX']
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PaddlePaddle: 2.2.2
OpenCV: 4.5.4-dev

**Comment by wuyefeilin** [comment]
这个是环境信息，是正常的

**Comment by Emmmmmaa** [comment]
不不，我用自己的数据集跑了MODnet的训练代码，保存的log文件我用文本编辑器打开是乱码的。如下图所示。完整的log文件已添加至附件，GitHub留言的是我跑代码的环境信息，我是mac笔记本连接的服务器。麻烦您帮我看一下。盼回复。











------------------ 原始邮件 ------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月15日(星期二) 下午2:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] [Bug]您好，我运行MODNet的训练代码，输出的log是乱码的，麻烦看一下是什么原因导致的。 (Issue #1770)





 
这个是环境信息，是正常的
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

vdlrecords.1644677177.log (118.75M, 2022年03月17日 14:38 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7b6662359f88f69abb67a7bb1e65574d005f56010801065a185450535e48510404524f0d0a535c4f510501530957570400070701387c6514510a10505b0a1706464853030c5153550257550216090a05355b&code=5fb58eeb

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
