### ISSUE TITLE
PaddleSeg中如何预加载模型？

### ISSUE THREAD

**Issue by ziyuwzf** [PaddlePaddle/PaddleSeg#1772]
我查看了相关预测的代码，包括predict.py和deploy/python/infer.py文件，好像都是一次加载模型，批量预测图片。加载模型时耗费了很长时间。
我现在这边有个需求是，一次加载模型之后，根据请求多次预测图片，每次只预测一张图片。做到类似tensorflow预加载模型的效果。

**Comment by juncaipeng** [comment]
可以看下是不是serving方式部署符合你的要求：https://github.com/PaddlePaddle/PaddleSeg/blob/develop/docs/deployment/serving/serving_cn.md

关于serving方式部署的最新用法，请参考serving官方文档：https://github.com/PaddlePaddle/Serving

**Comment by ziyuwzf** [comment]
> 可以看下是不是serving方式部署符合你的要求：https://github.com/PaddlePaddle/PaddleSeg/blob/develop/docs/deployment/serving/serving_cn.md
> 
> 关于serving方式部署的最新用法，请参考serving官方文档：https://github.com/PaddlePaddle/Serving

自己修改、封装代码，将模型初始化、加载模型参数过程写到了类的init里面，近似完成了需求

**Comment by juncaipeng** [comment]
是满足了你的需求吗？还有其他问题吗？

**Comment by ziyuwzf** [comment]
> 是满足了你的需求吗？还有其他问题吗？

暂时没有问题了，感谢
