### ISSUE TITLE
执行matting预测代码时：FileNotFoundError: [Errno 2] No such file or directory: 'data/PPM-100\\val.txt' 

### ISSUE THREAD

**Issue by ziyuwzf** [PaddlePaddle/PaddleSeg#1773]
执行matting的predict.py是推理过程中，export CUDA_VISIBLE_DEVICES=0
python predict.py \
    --config configs/modnet/modnet_mobilenetv2.yml \
    --model_path output/best_model/model.pdparams \
    --image_path data/PPM-100/val/fg/ \
    --save_dir ./output/results
我本地没有准备PPM-100数据集，为什么预测过程还需要下载验证数据？这两者有什么关系？

**Comment by wuyefeilin** [comment]
问题收到了，目前可以先准备一下PPM-100数据集，后续我们会解决这个问题

**Comment by Senyao-Han** [comment]
下载了PPM-100数据集，其中并没有val.txt这个文件，请问这个文件是在哪里

**Comment by ziyuwzf** [comment]
> 问题收到了，目前可以先准备一下PPM-100数据集，后续我们会解决这个问题

准备好PPM-100数据集后，可以正常推理了
