### ISSUE TITLE
加载STDCSeg模型出错，'STDCSeg' object has no attribute 'backbone'

### ISSUE THREAD

**Issue by yangL-H** [PaddlePaddle/PaddleSeg#1775]
1. PaddleSeg版本：PaddleSeg release/2.4
 2. PaddlePaddle版本：如PaddlePaddle 2.2.2
 3. 操作系统信息：Linux
 4. Python版本号：Python3.7
 5. CUDA/cuDNN版本：CUDA10.2

目的是加载已经训练好的STDCSeg模型，代码如下：
---------------------------------------------------------------------------
#STDCSeg02
cfg = Config("/content/drive/Shareddrives/2019206023/code/PaddleSeg-release-2.4/configs/stdcseg/stdc2_rs.yml",)
print(cfg)

#构建模型
from paddleseg.models import STDCSeg
model = STDCSeg(num_classes=4,
          backbone = cfg.model.backbone,
          use_boundary_2=False,
          use_boundary_4=False,
          use_boundary_8=True,
          use_boundary_16=False,
          use_conv_last=False,
          pretrained=cfg.model.pretrained)

model_path = '/content/drive/Shareddrives/2019206023/code/PaddleSeg-release-2.3/output/stdc2_bs16_4lei_wuqianyi/best_model/model.pdparams'	# 最优模型路径
para_state_dict = paddle.load(model_path)  
model.set_dict(para_state_dict)            	# 加载模型参数
print('Loaded trained params of model successfully')
---------------------------------------------------------------------------

报错：
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-4-bcb08072e069>](https://localhost:8080/#) in <module>()
    130 from paddleseg.models import STDCSeg
    131 model = STDCSeg(num_classes=4,
--> 132           backbone = cfg.model.backbone,
    133           use_boundary_2=False,
    134           use_boundary_4=False,

[/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py](https://localhost:8080/#) in __getattr__(self, name)
   1108                     return _convert_into_variable(_buffers[name])
   1109                 return _buffers[name]
-> 1110         return object.__getattribute__(self, name)
   1111 
   1112     def __setattr__(self, name, value):

AttributeError: 'STDCSeg' object has no attribute 'backbone'
---------------------------------------------------------------------------

我的cfg文件如下：
---------------------------------------------------------------------------
batch_size: 16
iters: 100000

train_dataset:
  type: Dataset
  dataset_root: /content
  train_path: /content/train_list.txt
  transforms:
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: /content
  val_path: /content/val_list.txt
  transforms:
    - type: Normalize
  mode: val

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.001
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: OhemCrossEntropyLoss
    - type: OhemCrossEntropyLoss
    - type: OhemCrossEntropyLoss
    - type: DetailAggregateLoss
  coef: [1, 1, 1, 1]

model:
  type: STDCSeg
  backbone:
    type: STDC2
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/STDCNet2.tar.gz
  #pretrained: /content/drive/Shareddrives/2019206023/code/PaddleSeg-release-2.3/output/rsstdc2_bs16_4lei_yuxunlian/best_model/model.pdparams
  #pretrained: null
  num_classes: 4
---------------------------------------------------------------------------

**Comment by shiyutang** [comment]
I am sorry, your description is rather fuzzy, its format can be improved a lot.

The problem seems to be you try to access the backbone attribute of stdcseg that we do not have. (We pass it to the Context Path, you use it in --> 132 backbone = cfg.model.backbone).

The model definition is as the following:
![image](https://user-images.githubusercontent.com/34859558/154230910-5db22ac9-5abe-4ce3-9477-8db351782922.png)

**Comment by shiyutang** [comment]
If you have any further questions, you are very welcome to reopen it.
