### ISSUE TITLE
请问有没有增加swin_upernet模型的计划？

### ISSUE THREAD

**Issue by geoexploring** [PaddlePaddle/PaddleSeg#1778]
swin_upernet在[ade20k](https://paperswithcode.com/sota/semantic-segmentation-on-ade20k)上排名很靠前，请问有没有增加swin_upernet模型的计划？   

谢谢！

**Comment by haoyuying** [comment]
您好，目前暂时没有该模型的排期。如果您复现了，也欢迎贡献给我们，为开源社区贡献力量。

**Comment by geoexploring** [comment]
@haoyuying ，谢谢！
复现的效果不好。
另外，为了公平比较的话，肯定要基于ade20k进行精度评价，硬件条件不允许呀。
