### ISSUE TITLE
关于PaddleSeg量化的问题

### ISSUE THREAD

**Issue by zhuyushi** [PaddlePaddle/PaddleSeg#178]
请教一下，https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.4.0/slim/quantization/README.md
这个里面介绍的是“量化训练”还是“训练后量化”？如果是“量化训练”，PaddleSeg是否可以提供一下“训练后量化（离线量化）”的例子，谢谢。

**Comment by slf12** [comment]
https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/quant/quant_post 这里有分类的demo，因为对于所有模型，离线量化流程都是一样的，所以没有分割的示例

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。
