### ISSUE TITLE
[General Issue]Visual Studio 2019 Community CMake 部署不能检测视频吗？

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/PaddleSeg#1783]
demo.exe有办法检测视频吗？

**Comment by juncaipeng** [comment]
你好，你使用的是哪个demo，使用什么工具部署，可以给出链接代码和文档说明。

**Comment by zmdcs** [comment]
就是Visual Studio 2019 Community CMake 编译指南里编译生成的demo.exe

**Comment by juncaipeng** [comment]
哪个指南？链接是？

**Comment by zmdcs** [comment]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.3.0/deploy/cpp/docs/windows_vs2019_build.md







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月21日(星期一) 下午2:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] [General Issue]Visual Studio 2019 Community CMake 部署不能检测视频吗？ (Issue #1783)





 
哪个指南？链接是？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by juncaipeng** [comment]
这个版本太低了，不再维护了。
建议你参考paddleinference文档进行部署：https://paddleinference.paddlepaddle.org.cn/product_introduction/summary.html
