### ISSUE TITLE
两个ComponentManager类，请问为什么会优先选择Paddleseg的ComponentManager类？

### ISSUE THREAD

**Issue by geoexploring** [PaddlePaddle/PaddleSeg#1786]
我将paddleseg作为外部依赖库编写代码，
依照paddleseg的[deeplabv3p](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.4/paddleseg/models/deeplab.py)重写deeplabv3p部分代码，然后依然在代码`class DeepLabV3P(nn.Layer):`加上`@manager.MODELS.add_component`，此时就会在运行时有警告：
```
lib\site-packages\paddleseg\cvlibs\manager.py:116: UserWarning: DeepLabV3P exists already! It is now updated to <class 'test.deeplab.DeepLabV3P'> !!!
```
不想有这种警告，于是我就按照paddleseg的[manager.py](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.4/paddleseg/cvlibs/manager.py)创建了一个一模一样的代码文件`manager_.py`，然后在代码`class DeepLabV3P(nn.Layer):`加上`@manager_.MODELS.add_component`，但在运行时还是会优先选择Paddleseg的ComponentManager类（也就是同时存在`@manager.MODELS`和`@manager_.MODELS`, 但运行paddleseg的的deeplabv3p），请问该如何解决呢？

谢谢！

**Comment by juncaipeng** [comment]
建议你直接改一个模型的类名，避免模型类名重复。

**Comment by geoexploring** [comment]
@juncaipeng ,谢谢，我决定还是按照原来的设计（即使会有大量警告），因为这样最符合业务逻辑。
