### ISSUE TITLE
关于eval报错，可能是数据的问题，大佬们帮帮忙

### ISSUE THREAD

**Issue by gutao0315** [PaddlePaddle/PaddleSeg#1792]
![R@D1R8ATUN1TG$ }0C62~FV](https://user-images.githubusercontent.com/77281977/155088367-0ac2aaf9-40a6-4574-9413-316ea2868734.png)
应该是做eval的时候出问题了，不知道为什么。是数据的问题吗 大佬们求解答

**Comment by wuyefeilin** [comment]
看一下有没有验证集，如果没有的话先去掉--do_eval。另外，这个问题已经在修复了
