### ISSUE TITLE
基于Transfomer的模型（segformer）  类激活图（如CAM）实现

### ISSUE THREAD

**Issue by yangL-H** [PaddlePaddle/PaddleSeg#1793]
请问模型怎么导出类激活图 或 attention map，如图所示：
![image](https://user-images.githubusercontent.com/65001351/155154084-e0ebcbd6-e7cc-4305-a084-6a83d4cc7d03.png)

**Comment by haoyuying** [comment]
您好，目前我们没有提供该功能，您可以自己增加visualdl代码，可视化显示。cv2有类似的接口函数可供使用。

**Comment by aidongmandexiaowowo** [comment]
想请教一下，怎样添加激活图呢，不知道改哪里呢
