### ISSUE TITLE
deeplabv3训练cityscapes数据集，loss是负数

### ISSUE THREAD

**Issue by curryJ** [PaddlePaddle/PaddleSeg#1794]
我在aistudio上利用百度提供的cityscapes数据集进行deeplabv3p的训练，我按照paddleseg的教程进行训练，但是loss出现了负数。我调小了lr之后，问题还是没有解决。请问这是什么原因呀？谢谢
![image](https://user-images.githubusercontent.com/23001027/155281131-7b9cce34-c15d-472f-9c09-a79b0e629163.png)

**Comment by haoyuying** [comment]
您好，可以把您使用的教程链接发给我们吗，方便我们排查问题。或者您可以排查如下位置：输入损失函数中的tensor是否有异常，损失函数计算输出及加权loss部分是否存在问题。

**Comment by Gwencong** [comment]
我用paddleseg训练时遇到到了同样的问题，当我使用configs/deeplabv3p/deeplabv3p_resnet50_os8_cityscapes_1024x512_80k_rmiloss.yml训练时loss也是负的，但是我用configs/deeplabv3p/deeplabv3p_resnet50_os8_cityscapes_1024x512_80k.yml训练loss就正常

**Comment by shiyutang** [comment]
RMIloss会产生负数结果。
