### ISSUE TITLE
极端分配率图片训练效果不佳

### ISSUE THREAD

**Issue by x12901** [PaddlePaddle/PaddleSeg#1795]
我的图片分辨率为2048*500，使用hardnet训练效果不佳，除了背景acc良好，其它都不能让人满意。是否有方法能提高？

platform: Windows-10-10.0.19042-SP0
Python: 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)]
Paddle compiled with cuda: True
NVCC: Not Available
cudnn: 7.6
GPUs used: 1
CUDA_VISIBLE_DEVICES: 0,1,2
GPU: ['GPU 0: GeForce GTX', 'GPU 1: GeForce GTX', 'GPU 2: GeForce GTX']
GCC: gcc (MinGW.org GCC Build-2) 9.2.0
PaddleSeg: 2.4.0
PaddlePaddle: 2.2.1
OpenCV: 4.5.5
![屏幕截图 2022-02-23 170745](https://user-images.githubusercontent.com/30824839/155294263-49eb8727-e65c-43b1-a701-46cdd645a94f.png)

**Comment by haoyuying** [comment]
请问您的前景物体是否在整张图所占比例不均衡呢，如果是， 可以尝试其他用于样本均衡的损失函数或者更换网络。如果前景物体明显且占像素面积较大，建议检查预处理是否存在问题。

**Comment by x12901** [comment]
> 请问您的前景物体是否在整张图所占比例不均衡呢，如果是， 可以尝试其他用于样本均衡的损失函数或者更换网络。如果前景物体明显且占像素面积较大，建议检查预处理是否存在问题。

是的,我的前景大小不一,有30*30也有2000*100的

**Comment by x12901** [comment]
> 请问您的前景物体是否在整张图所占比例不均衡呢，如果是， 可以尝试其他用于样本均衡的损失函数或者更换网络。如果前景物体明显且占像素面积较大，建议检查预处理是否存在问题。

是的,我的前景大小不一,有30x30也有2000x100的
