### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by lvhuaqing** [PaddlePaddle/PaddleSeg#1799]
Traceback (most recent call last):
  File "train.py", line 198, in <module>
    main(args)
  File "train.py", line 180, in main
    optimizer=cfg.optimizer,
  File "/home/aistudio/work/PaddleSeg/paddleseg/cvlibs/config.py", line 213, in optimizer
    lr, parameters=self.model.parameters(), **args)
TypeError: __init__() got an unexpected keyword argument '_inherited_'

**Comment by LutaoChu** [comment]
请按照模板提供完整复现步骤

**Comment by GexLoong** [comment]
> Traceback (most recent call last): File "train.py", line 198, in main(args) File "train.py", line 180, in main optimizer=cfg.optimizer, File "/home/aistudio/work/PaddleSeg/paddleseg/cvlibs/config.py", line 213, in optimizer lr, parameters=self.model.parameters(), **args) TypeError: **init**() got an unexpected keyword argument '_inherited_'

请问这个问题你解决了吗，这个inherited啥意思呢，能去掉吗
