### ISSUE TITLE
[General Issue] PaddleSeg 如何加载 PaddleClass 预训练模型作为backbone？

### ISSUE THREAD

**Issue by pazifik-cyber** [PaddlePaddle/PaddleSeg#1801]
我尝试了直接从PaddleClass 下载预训练模型，例如 下载了 https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/legendary_models/ResNet18_pretrained.pdparams
然后修改 config：  pretrained: ResNet18_pretrained.pdparams

但是在运行结果如下：
```
2022-02-24 12:15:00 [INFO]	Loading pretrained model from ./ResNet18_vd_pretrained.pdparams
2022-02-24 12:15:00 [WARNING]	conv1_1._conv.weight is not in pretrained model
2022-02-24 12:15:00 [WARNING]	conv1_1._batch_norm.weight is not in pretrained model
......
```

这应该是因为PaddleClass的预训练模型ResNet18_vd中层的名字和PaddleSeg的ResNet18_vd 不同。

请问应该如何正确加载呢？ 可以通过修改 `ResNet18_pretrained.pdparams`  中层的名字，改成和PaddleSeg一样，然后再加载么？

**Comment by LutaoChu** [comment]
是的，PaddleClass的模型代码和PaddleSeg有些不同，要正确加载的话就需要将对应层的名字对齐，否则就不会加载

**Comment by sd2048** [comment]
@LutaoChu Can you give me instructions on how to align the names so that I can use the trained model as pretrained?
I want to use this one in particular: https://paddleseg.bj.bcebos.com/dygraph/cityscapes/pp_liteseg_stdc2_cityscapes_1024x512_scale0.5_160k/model.pdparams

----

Edit: Never mind, my issue was unrelated.

**Comment by LutaoChu** [comment]
This model is already a paddleseg model, and there is no need to align names.
You can use this trained model by setting pretrained parameter in config YML

```
model:  #模型说明
  type: PPLiteSeg  #设定模型类别
  backbone:  # 设定模型的backbone，包括名字和预训练权重
    type: STDC2
    pretrained: https://paddleseg.bj.bcebos.com/dygraph/cityscapes/pp_liteseg_stdc2_cityscapes_1024x512_scale0.5_160k/model.pdparams
```
