### ISSUE TITLE
[General Issue]关于模型导出并推理

### ISSUE THREAD

**Issue by TonyZPW** [PaddlePaddle/PaddleSeg#1802]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（2.4）
 2. PaddlePaddle版本：（2.1.0）
 3. 操作系统信息：（Linux）
 4. Python版本号：（3.8）
 5. CUDA/cuDNN版本：（ 11.2）
 6. 其他内容:  请问我没有使用配置文件的方式进行训练，我直接用的代码的方式做训练。且直接使用的是PaddleSeg里面自带的模型，请问：1.如何导出可以用于生产环境的模型?
 我模型训练完成后在best_model文件夹下只有.pdparam文件。 如果我用python做推理服务器，那我只需要用模型加载这个参数文件就可以了？ 我在网上看这属于动态图的方式。 不知道这样做是否是专业的做法？ 我看到还有静态图的方式，所以目前有些困惑不知道该用哪种？ 另外我看到关于模型导出的示例代码全是用的配置的方式做的，说是能一键导出。那我用api能不能做到一键导出呢？
2. 动态图推理是不是不如静态图推理？是不是不适合用于线上环境？

**Comment by TonyZPW** [comment]
另外如果我想学习配置文件的方式进行训练，有没有相关参考文档呢？

**Comment by LutaoChu** [comment]
你好，动态图不如静态图快，一般会将动态图模型导出为静态图进行部署。pdparam只是模型的权重文件。
如果要用API导出的话，目前需要修改[export.py](https://github.com/PaddlePaddle/PaddleSeg/blob/develop/export.py)，具体就是将原先用配置进行获取的model和transforms改成API调用的形式即可导出
<img width="722" alt="image" src="https://user-images.githubusercontent.com/30695251/155680395-8c3c5213-08cd-4d8a-9fb2-040b090df178.png">

**Comment by LutaoChu** [comment]
> 另外如果我想学习配置文件的方式进行训练，有没有相关参考文档呢？

参考 https://github.com/PaddlePaddle/PaddleSeg/blob/develop/docs/whole_process_cn.md

**Comment by TonyZPW** [comment]
非常感谢，已解决
