### ISSUE TITLE
静态模型转ONNX后 openvino报错无法运行

### ISSUE THREAD

**Issue by Leon-E-Zion** [PaddlePaddle/PaddleSeg#1808]
!python export.py \
       --config configs/fcn/fcn_hrnetw18_cityscapes_1024x512_80k.yml \
       --model_path FCN.pdparams

# 使用paddle2onnx将paddle模型格式转化到ONNX模型格式。
! paddle2onnx --model_dir /home/aistudio/PaddleSeg/output/ \
    --model_filename model.pdmodel \
    --params_filename model.pdiparams \
    --save_file segonnx/model.onnx \
    --opset_version 11 \
    --enable_onnx_checker True

# 导入libs
import cv2
import matplotlib.pyplot as plt
import numpy as np
import sys
from openvino.inference_engine import IECore

from notebook_utils import segmentation_map_to_image

# check by ONNX
import onnx

# onnx_file = save_path +  '.onnx'
# onnx_file ='onnx-model/detectionmodel.onnx'
save_path = ''
onnx_file = save_path +  'ff.onnx'
onnx_model = onnx.load(onnx_file)
onnx.checker.check_model(onnx_model)
print('The model is checked!')
# 加载网络
ie = IECore()

net = ie.read_network(model="ddd.onnx")
exec_net = ie.load_network(net, "CPU")

output_layer_ir = next(iter(exec_net.outputs))
input_layer_ir = next(iter(exec_net.input_info))

# 图片预处理
image = cv2.imread("test.jpg")

rgb_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
image_h, image_w, _ = image.shape

N, C, H, W = net.input_info[input_layer_ir].tensor_desc.dims

resized_image = cv2.resize(image, (W, H))

input_image = np.expand_dims(
    resized_image.transpose(2, 0, 1), 0
)
plt.imshow(rgb_image)

# 预测
result = exec_net.infer(inputs={input_layer_ir: input_image})
result_ir = result[output_layer_ir]

segmentation_mask = np.argmax(result_ir, axis=1)
plt.imshow(segmentation_mask[0])

# 可视化结果
data = {"Base Photo": rgb_image, "Segmentation": mask, "Masked Photo": image_with_mask}

# Create subplot to visualize images
f, axs = plt.subplots(1, len(data.items()), figsize=(15, 10))

# Fill subplot
for ax, (name, image) in zip(axs, data.items()):
    ax.axis('off')
    ax.set_title(name)
    ax.imshow(image)

# Display image
plt.show(f)

报错---->
Traceback (most recent call last):
  File "C:/Users/Leon/Desktop/aa.py", line 24, in <module>
    exec_net = ie.load_network(net, "CPU")
  File "ie_api.pyx", line 403, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 442, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: Ngraph operation Parameter with name x has dynamic output shape on 0 port, but CPU plug-in supports only static shape

**Comment by juncaipeng** [comment]
从最后错误来看是由于动态shape的问题，你可以尝试在export.py预测模型的时候设定固定输入size，即是设置input_shape输入参数。
参考文档：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.4/docs/model_export.md

**Comment by fanweiya** [comment]
没做normalize

**Comment by Leon-E-Zion** [comment]
Leon-Zion 工作站 已收到邮件，Leon将尽快处理
