### ISSUE TITLE
训练时epoch显示不完全的问题

### ISSUE THREAD

**Issue by jaffe-fly** [PaddlePaddle/PaddleSeg#181]
epoch=1 epoch=4  epoch=7 这些 训练的数据没有输出
![image](https://user-images.githubusercontent.com/49515380/76139634-ef9db700-608c-11ea-95d2-8bd5c8bb38c5.png)

**Comment by LutaoChu** [comment]
这是因为你的batch size=32，默认训练日志的打印周期是10个step，说明你的数据集图片数量小于320张，所以出现跳过显示。
启动训练脚本时指定较小的`--log_steps`即可
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.4.0/docs/config.md#%E5%91%BD%E4%BB%A4%E8%A1%8Cflags
