### ISSUE TITLE
大佬们 预测速度慢怎么搞 有哪些提升速度的方法 详看图

### ISSUE THREAD

**Issue by gutao0315** [PaddlePaddle/PaddleSeg#1810]
![image](https://user-images.githubusercontent.com/77281977/155920387-a86c85e7-5596-4d92-89ee-19757f81cd70.png)
图片是2448X2448的大小 1s/张
520X520的图片测试下来是 100ms/张
想问问
1.影响预测速度的因素有哪些
2.怎么提升预测速度 有相关文档介绍吗

**Comment by juncaipeng** [comment]
请参考seg文档导出预测模型再部署，速度会更快。

**Comment by justld** [comment]
可以考虑剪枝、量化，导出静态图模型再部署。
