### ISSUE TITLE
[General Issue] 使用SemanticConnectivityLoss遇到问题

### ISSUE THREAD

**Issue by gh10242048** [PaddlePaddle/PaddleSeg#1817]
训练使用如下配置，PS：1,2有问题，3正常
#############1
# loss:
#   types:
#     - type: MixedLoss
#       losses:
#         - type: CrossEntropyLoss
#         - type: SemanticConnectivityLoss
#       coef: [0.5, 0.5]
#   coef: [1]

##############2
loss:
  types:
    - type: SemanticConnectivityLoss
  coef: [1]
###########3
loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]
均遇到该问题：
88888888888888
None
False
9999999999999999999999
Traceback (most recent call last):
  File "train.py", line 207, in <module>
    main(args)
  File "train.py", line 184, in main
    train(
  File "/home/xxx/myproj/segment/PaddleSeg/paddleseg/core/train.py", line 225, in train
    loss.backward()
  File "/home/xxx/anaconda3/envs/paddlepaddle/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/xxx/anaconda3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/xxx/anaconda3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/fluid/framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "/home/xxx/anaconda3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 252, in backward
    core.dygraph_run_backward([self], [grad_tensor], retain_graph,
RuntimeError: (NotFound) Cannot find gradient of variable generated_tensor_394@GRAD
  [Hint: Expected iter != accumulators_.end() == true, but received iter != accumulators_.end():0 != true:1.] (at /paddle/paddle/fluid/imperative/basic_engine.cc:445)

INFO 2022-03-01 15:41:26,071 launch_utils.py:341] terminate all the procs
ERROR 2022-03-01 15:41:26,071 launch_utils.py:602] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0, 1] was aborted. Please check its log.

varbase_patch_methods.py相关代码：
232         if framework.in_dygraph_mode():
233             if grad_tensor is not None:
234                 assert isinstance(
235                     grad_tensor, paddle.
236                     Tensor), "The type of grad_tensot must be paddle.Tensor"
237                 assert grad_tensor.shape == self.shape, \
238                     "Tensor shape not match, Tensor of grad_tensor [ {} ] with shape {} mismatch Tensor [ {} ] with shape {}".format(
239                     grad_tensor.name, grad_tensor.shape, self.name, self.shape)
240
241             if paddle.is_compiled_with_xpu():
242                 # TODO(liuyuhui): Currently only for xpu. Will be removed in the future.
243                 scaled_loss = scale_loss(self)
244                 core.dygraph_run_backward([scaled_loss], [grad_tensor],
245                                           retain_graph,
246                                           framework._dygraph_tracer())
247             else:
248                 print('88888888888888')
249                 print(grad_tensor)
250                 print(retain_graph)
251                 print('9999999999999999999999')
252                 core.dygraph_run_backward([self], [grad_tensor], retain_graph,
253                                           framework._dygraph_tracer())

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.4）
 2. PaddlePaddle版本：（如PaddlePaddle-gpu 2.2.1.post112）
 3. 操作系统信息：（如Linux）
 4. Python版本号：（如Python3.8.12）
 5. CUDA/cuDNN版本：（ 如CUDA11.6/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by gh10242048** [comment]
将paddlepaddle升级到2.2.2后，该问题已解决，refer to #37265 https://github.com/PaddlePaddle/Paddle/issues/37265
但是遇到了新的问题，配置如下：
loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: SemanticConnectivityLoss
      coef: [0.5, 0.5]
  coef: [1]

loss1对应SemanticConnectivityLoss，不收敛
![image](https://user-images.githubusercontent.com/9912536/156165541-46d1a8bf-792f-4d33-b526-5eedeac8802f.png)

**Comment by LutaoChu** [comment]
SCLoss相比CE太大了，可以调小SCLoss的权重系数试试，保持和CE在同一个数量级上

**Comment by gh10242048** [comment]
两个都是0.5，在同一个数量级上呀

**Comment by LutaoChu** [comment]
我的意思是loss的数值在一个数量级上，不是权重
