### ISSUE TITLE
python部署时，遇到的报错，大佬们看看

### ISSUE THREAD

**Issue by gutao0315** [PaddlePaddle/PaddleSeg#1819]
![4I0W@NPA7QNQSU} 30RGF$G](https://user-images.githubusercontent.com/77281977/156145741-4a523357-3ac7-4256-9080-492a322c7a13.png)
是不是TensorRT安装的有问题

**Comment by juncaipeng** [comment]
请安装带有trt编译的paddle预测库，具体参考文档中的安装介绍：https://github.com/PaddlePaddle/PaddleSeg/blob/develop/docs/deployment/inference/python_inference_cn.md
