### ISSUE TITLE
使用eval评估deeplabv3+mobilnetv2的问题

### ISSUE THREAD

**Issue by y-kl8** [PaddlePaddle/PaddleSeg#182]
我下载了训练好的 deeplabv3+mobilnetv2模型， 使用eval进行评估，模型下载处如下图：

![1583900499](https://user-images.githubusercontent.com/37499637/76382262-1ad91c80-6393-11ea-8164-bb71fc551f98.png)

评估使用yaml文件为： deeplabv3p_mobilenetv2_cityscapes.yaml
运行会报错：
Error Message Summary:
----------------------
Error: Cannot open file saved_model/mobilenet_cityscapes/encoder/concat/weights for load op at (/paddle/paddle/fluid/operators/load_op.h:38)
  [operator < load > error]

我发现下载的标准模型里没有decorder很encoder两个文件，但是评估时要使用。

不过deeplabv3+mobilnetv2应该是不会使用decoder和aspp的，所以不是很能理解。

**Comment by y-kl8** [comment]
训练的时候 我选定其他gpu：export CUDA_VISIBLE_DEVICES=3

但还是会报错：

Error Message Summary:
----------------------
ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 140.683838MB memory on GPU 0, available memory is only 67.375000MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.

**Comment by y-kl8** [comment]
进行训练/评估的时候会有奇怪的报错：

训练/评估命令：
python -u ./slim/quantization/train_quant.py --log_steps 10 --not_quant_pattern last_conv --cfg configs/deeplabv3p_mobilenetv2_cityscapes.yaml --use_gpu --use_mpio TRAIN.PRETRAINED_MODEL_DIR "./pretrain/mobilenet_cityscapes/" TRAIN.MODEL_SAVE_DIR "./snapshots/mobilnet_cityscapes_quant_3" MODEL.DEEPLAB.ENCODER_WITH_ASPP False MODEL.DEEPLAB.ENABLE_DECODER False TRAIN.SYNC_BATCH_NORM False SOLVER.LR 0.0001 TRAIN.SNAPSHOT_EPOCH 1 SOLVER.NUM_EPOCHS 30 BATCH_SIZE 16

报错：
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::CUDADeviceContext::CUDADeviceContext(paddle::platform::CUDAPlace)
3   std::_Function_handler<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > (), std::reference_wrapper<std::_Bind_simple<paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1} ()> > >::_M_invoke(std::_Any_data const&)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::__future_base::_Result_base::_Deleter>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   std::__future_base::_Deferred_state<std::_Bind_simple<paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1} ()>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >::_M_run_deferred()
7   paddle::platform::DeviceContextPool::Get(paddle::platform::Place const&)
8   paddle::framework::GarbageCollector::GarbageCollector(paddle::platform::Place const&, unsigned long)
9   paddle::framework::UnsafeFastGPUGarbageCollector::UnsafeFastGPUGarbageCollector(paddle::platform::CUDAPlace const&, unsigned long)
10  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
11  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

----------------------
Error Message Summary:
----------------------
Error: An error occurred here. There is no accurate error hint for this error yet. We are continuously in the process of increasing hint for this kind of error check. It would be helpful if you could inform us of how this conversion went by opening a github issue. And we will resolve it with high priority.
  - New issue link: https://github.com/PaddlePaddle/Paddle/issues/new
  - Recommended issue content: all error stack information: out of memory at (/paddle/paddle/fluid/platform/device_context.cc:221)

**Comment by LielinJiang** [comment]
是的，需要将yaml文件中ENCODER_WITH_ASPP和ENABLE_DECODER，手动设置为False。

**Comment by y-kl8** [comment]
您好，yaml文件中这两个已经设置为false了，没有ENCODER_WITH_ASPP和ENABLE_DECODER这两个参数。
ASPP_WITH_SEP_CONV: False
DECODER_USE_SEP_CONV: False

**Comment by y-kl8** [comment]
我量化训练后的mobilnetv2_deeplabv3+的模型大小是为什么是14.7M而不是7.4M？ 另外量化后的模型怎么才能知道它真正的大小？没有去除aspp和decoder的mobilnetv2_deeplabv3+模型量化后有多大？

**Comment by slf12** [comment]
> 我量化训练后的mobilnetv2_deeplabv3+的模型大小是为什么是14.7M而不是7.4M？ 另外量化后的模型怎么才能知道它真正的大小？没有去除aspp和decoder的mobilnetv2_deeplabv3+模型量化后有多大？

![image](https://user-images.githubusercontent.com/8036226/76945672-cfe47980-693d-11ea-921f-0d008b9d3f9b.png)
https://github.com/PaddlePaddle/PaddleSlim/pull/179

可以修改以下参数保存int8模型
![image](https://user-images.githubusercontent.com/8036226/76945762-f4d8ec80-693d-11ea-98d7-308661bf9494.png)

https://paddlepaddle.github.io/PaddleSlim/api_cn/quantization_api.html#paddleslim.quant.convert

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。
