### ISSUE TITLE
[eiseg]请问多个人分工使用eiseg标注生成coco文件如何合并成一个呀？

### ISSUE THREAD

**Issue by dadar12138** [PaddlePaddle/PaddleSeg#1820]
有个任务数据集太大，需要多人分工使用eiseg一起标注，每个人生成的coco格式标注文件要怎么合并成一个呢？有没有大佬有用相关代码合并多个coco格式标注文件？谢谢大佬们！！！

**Comment by Piccky** [comment]
调用下coco api根据自己的数据写个脚本就好了
