### ISSUE TITLE
Does paddleseg have a test model for Apollo scape's Lane Segmentation dataset？

### ISSUE THREAD

**Issue by daigang896** [PaddlePaddle/PaddleSeg#1821]
Hello，Does paddleseg have a test model for Apollo scape's Lane segmentation dataset？Is there an image segmentation test model for lane lines and lane markings？

**Comment by shiyutang** [comment]
We haven't trained any model on the Apollo scape's Lane segmentation dataset, but you can try out our lane segmentation model [here](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.4/contrib/LaneSeg).

**Comment by daigang896** [comment]
Thank you. The lane segmentation model here only has lane lines and no lane markings. I will download that dataset and try to train it.

**Comment by shiyutang** [comment]
You are welcome. What is your application, maybe we can further help you.

**Comment by daigang896** [comment]
Not clear, just look at the effect of the current lane lines and lane markings segmentation.

**Comment by shiyutang** [comment]
If you have any further questions, you are very welcome to reopen it.
