### ISSUE TITLE
paddleseg2.4版本，使用split_dataset_list分割数据集出现异常，请问这是什么原因造成的呢？标注图和原图的数量是对应的。

### ISSUE THREAD

**Issue by chenyixun1112** [PaddlePaddle/PaddleSeg#1827]
paddleseg2.4版本，使用split_dataset_list分割数据集出现异常，请问这是什么原因造成的呢？标注图和原图的数量是对应的。
![image](https://user-images.githubusercontent.com/99322256/156524706-fdda74cc-5f11-4bd1-bb0f-0ddb10cefdcd.png)

> 具体是什么异常呢，可以描述下吗？

是我自己的疏忽哈，是标注图片与原图名称不符，导致的标签数据前后不对应，已经解决啦！感谢回复！

**Comment by chenyixun1112** [comment]
![image](https://user-images.githubusercontent.com/99322256/156525062-433c26d7-3eeb-4730-8ade-1a320aabb141.png)
使用命令如图所示

**Comment by haoyuying** [comment]
具体是什么异常呢，可以描述下吗？
