### ISSUE TITLE
[General Issue]pp_humanseg模型推理出来的人像边缘比较糊

### ISSUE THREAD

**Issue by gh10242048** [PaddlePaddle/PaddleSeg#1828]
如题，使用pp_humanseg做人像分割， 边缘比较糊（398x224），猜测是因为low level的分割信息太浅了，只做了一层3x3的Conv，不知道你们那边是否也这样？

**Comment by zhenzi0322** [comment]
> 如题，使用pp_humanseg做人像分割， 边缘比较糊（398x224），猜测是因为low level的分割信息太浅了，只做了一层3x3的Conv，不知道你们那边是否也这样？

你是采用现有的模型进行分割的吧

**Comment by gh10242048** [comment]
在现有的模型上做finetune（398x224）那个，怀疑是模型的问题，不是数据的问题
