### ISSUE TITLE
matting只能抠人像吗？怎么去做自定义的数据集？数据集中的alpha图怎么做

### ISSUE THREAD

**Issue by 02825cm** [PaddlePaddle/PaddleSeg#1832]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by wuyefeilin** [comment]
我们提供的modnet和pp-humanmatting只能进行人像抠图，dim不限物体但是需要提供trimap图象

如果要在自定义数据集上训练，需要根据我们的数据准备说明进行准备。alpha 图可以利用photoshop进行准备。

另外请问一下，你是有什么具体的应用场景呢，说不定可以达成合作。

**Comment by 02825cm** [comment]
> 我们提供的modnet和pp-humanmatting只能进行人像抠图，dim不限物体但是需要提供trimap图象
> 
> 如果要在自定义数据集上训练，需要根据我们的数据准备说明进行准备。alpha 图可以利用photoshop进行准备。
> 
> 另外请问一下，你是有什么具体的应用场景呢，说不定可以达成合作。

非常感谢回复，主要是应用在工业场景，指示灯颜色的识别，目前还在测试阶段

**Comment by wuyefeilin** [comment]
能给个例子说明应用场景吗，我们可以帮忙提供技术解决方案哈？ 如果只是正常灯颜色的识别，或许语义分割就能做到了

**Comment by zhenzi0322** [comment]
这里有一份 https://aistudio.baidu.com/aistudio/datasetdetail/131538 数据集。你可以拿来测试

**Comment by zhenzi0322** [comment]
> 能给个例子说明应用场景吗，我们可以帮忙提供技术解决方案哈？ 如果只是正常灯颜色的识别，或许语义分割就能做到了

物体间的抠图如何有效地解决，前几天采用了`dim`进行数据集地训练，但是效果很差，我在配置文件中把get_trimap设置为False，我的数据集本身没有提供trmap图像。想不明白为什么效果会这么差

**Comment by wuyefeilin** [comment]
DIM是基于trimap的方法的，get-trimap得设置为True. 如果不想使用trimap，可以使用modnet进行训练
