### ISSUE TITLE
PP-HumanMatting中的数据集是不是需要高分辨率的图片

### ISSUE THREAD

**Issue by zhenzi0322** [PaddlePaddle/PaddleSeg#1837]
如果是采用有`PP-HumanMatting`训练自己的模型是不是需要准备高分辨率的数据集，还是低分辨率的图片数据集也是可以的？

**Comment by wuyefeilin** [comment]
可以直接使用我们的模型进行预测哈， PP-Humanmatting只适合高分辨率图象， MODNet都可以哈

**Comment by zhenzi0322** [comment]
> 可以直接使用我们的模型进行预测哈， PP-Humanmatting只适合高分辨率图象， MODNet都可以哈

我用您们的模型预测过了，但是您们的模型有一些图片预测得不是很好，所以我想准备一些数据集进行训练。好像我也不能在您们的模型上进行继续训练模型，少了一个`pdopt`文件。目前我准备的数据集中只有低分辨率的图像。

**Comment by zhenzi0322** [comment]
> 可以直接使用我们的模型进行预测哈， PP-Humanmatting只适合高分辨率图象， MODNet都可以哈

可以提供`modnet-mobilenetv2.pdparams`模型对应的`modnet-mobilenetv2.pdopt`文件给我进行增加数据集继续训练嘛？

**Comment by zhenzi0322** [comment]
采用自己的数据集进行训练，出现如下报错信息：
```
D:\packages\python\python375\Envs\paddleseg\lib\site-packages\paddle\nn\layer\norm.py:653: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
    data = self.collate_fn(data)
  File "D:\packages\python\python375\Envs\paddleseg\lib\site-packages\paddle\fluid\dataloader\collate.py", line 70, in default_collate_fn
    for key in sample
  File "D:\packages\python\python375\Envs\paddleseg\lib\site-packages\paddle\fluid\dataloader\collate.py", line 70, in <dictcomp>
    for key in sample
  File "D:\packages\python\python375\Envs\paddleseg\lib\site-packages\paddle\fluid\dataloader\collate.py", line 58, in default_collate_fn
    batch = np.stack(batch, axis=0)
  File "<__array_function__ internals>", line 6, in stack
  File "D:\packages\python\python375\Envs\paddleseg\lib\site-packages\numpy\core\shape_base.py", line 426, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape

```

**Comment by summerwbb** [comment]
Excuse me, have you get PP-Humanmatting's model.pdopt?Can you share it with me？

**Comment by summerwbb** [comment]
> 

Excuse me, have you get PP-Humanmatting's model.pdopt?Can you share it with me？

**Comment by zhenzi0322** [comment]
> Excuse me, have you get PP-Humanmatting's model.pdopt?Can you share it with me？

Are you talking about the official model?

**Comment by summerwbb** [comment]
yes




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月24日(星期二) 上午9:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleSeg] PP-HumanMatting中的数据集是不是需要高分辨率的图片 (Issue #1837)





  
Excuse me, have you get PP-Humanmatting's model.pdopt?Can you share it with me？
  
Are you talking about the official model?

**Comment by zhenzi0322** [comment]
> yes

Send me your email, I will send you through the email

**Comment by summerwbb** [comment]
***@***.*** you very much!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月24日(星期二) 上午9:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleSeg] PP-HumanMatting中的数据集是不是需要高分辨率的图片 (Issue #1837)





  
yes
  
Send me your email, I will send you through the email
