### ISSUE TITLE
error inference c++

### ISSUE THREAD

**Issue by nqthai309** [PaddlePaddle/PaddleSeg#1839]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: PaddleSeg release/2.4
 2. PaddlePaddle version: PaddlePaddle-gpu 2.2.2
 4. Operation system: Linux - Ubuntu 18.04
 5. Python version: Python3.6
 6. CUDA/cuDNN version: CUDA10.2/cuDNN 7.6.5
 
  I try inference c++ in Docker but face to face this error

exec ./run_seg_gpu.sh

![image](https://user-images.githubusercontent.com/61822545/156920301-f7d79834-676c-4ccd-b8cc-d170a00c77c3.png)

**Comment by juncaipeng** [comment]
你安装的paddle版本，cpu是否使用mkldnn加速库，而不是oneblas，你看下安装库的名字即可。如下图：
<img width="628" alt="image" src="https://user-images.githubusercontent.com/52520497/156956957-15f34956-753f-4855-8920-70733cc3f73d.png">


然后 ./run_seg_gpu.sh脚本没有修改吧？

**Comment by nqthai309** [comment]
> 你安装的paddle版本，cpu是否使用mkldnn加速库，而不是oneblas，你看下安装库的名字即可。如下图： <img alt="image" width="628" src="https://user-images.githubusercontent.com/52520497/156956957-15f34956-753f-4855-8920-70733cc3f73d.png">
> 
> 然后 ./run_seg_gpu.sh脚本没有修改吧？


YES, I follow this guide
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.4/docs/deployment/inference/cpp_inference.md
