### ISSUE TITLE
模型训练报错：AttributeError: 'NoneType' object has no attribute 'astype'

### ISSUE THREAD

**Issue by huangjianyi45903** [PaddlePaddle/PaddleSeg#1840]
![image](https://user-images.githubusercontent.com/95200080/156956624-6420a91e-0dbf-45ea-af67-e782f03f6647.png)

![image](https://user-images.githubusercontent.com/95200080/156956595-35c4ad4f-8dc1-403b-85b6-090f22d37741.png)

**Comment by juncaipeng** [comment]
这是读取图片错误。

你是否修改了bisenet_optic_disc_xxx.yaml文件中的dataset配置字段？请参考seg文档中数据准备检查这部分配置信息。
