### ISSUE TITLE
如何自定义Matting数据集

### ISSUE THREAD

**Issue by zhenzi0322** [PaddlePaddle/PaddleSeg#1843]
在`https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.4/contrib/Matting`该仓库中如何正确自定义自己的数据集?

通过代码运行`PPM-100`数据集是没有什么问题的，但是我在运行自己准备的数据集时就出现了一些问题，如下：
```
2022-03-07 15:46:04 [INFO]      Loading pretrained model from https://paddleseg.bj.bcebos.com/matting/models/MobileNetV2_pretrained/model.pdparams
2022-03-07 15:46:04 [INFO]      There are 265/265 variables loaded into MobileNet.
D:\packages\python\python375\Envs\paddleseg\lib\site-packages\paddle\nn\layer\norm.py:653: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
Exception in thread Thread-5:
Traceback (most recent call last):
  File "d:\packages\python\python375\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "d:\packages\python\python375\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\packages\python\python375\Envs\paddleseg\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 213, in _thread_loop
    self._thread_done_event)
  File "D:\packages\python\python375\Envs\paddleseg\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 134, in fetch
    data = self.collate_fn(data)
  File "D:\packages\python\python375\Envs\paddleseg\lib\site-packages\paddle\fluid\dataloader\collate.py", line 70, in default_collate_fn
    for key in sample
  File "D:\packages\python\python375\Envs\paddleseg\lib\site-packages\paddle\fluid\dataloader\collate.py", line 70, in <dictcomp>
    for key in sample
  File "D:\packages\python\python375\Envs\paddleseg\lib\site-packages\paddle\fluid\dataloader\collate.py", line 58, in default_collate_fn
    batch = np.stack(batch, axis=0)
  File "<__array_function__ internals>", line 6, in stack
  File "D:\packages\python\python375\Envs\paddleseg\lib\site-packages\numpy\core\shape_base.py", line 427, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
```

- paddlepaddle==2.2.2

通过查看官方提供的`PPM-100`的数据集中尺寸不是一致的，就是想不明白为什么我准备的数据集就训练不起来呢？

**Comment by SurvivorNo1** [comment]
您好，请问你解决这个问题了吗？我也遇到了这个问题

**Comment by zhenzi0322** [comment]
> 您好，请问你解决这个问题了吗？我也遇到了这个问题

解决了

**Comment by zhenzi0322** [comment]
> 您好，请问你解决这个问题了吗？我也遇到了这个问题

你可以用 https://aistudio.baidu.com/aistudio/datasetdetail/131538 这一份数据集。

**Comment by SurvivorNo1** [comment]
[> > 您好，请问你解决这个问题了吗？我也遇到了这个
](https://github.com/PaddlePaddle/PaddleSeg/issues/1843#issuecomment-1063573502)

**Comment by SurvivorNo1** [comment]
> > 您好，请问你解决这个问题了吗？我也遇到了这个问题
> 
> 你可以用 https://aistudio.baidu.com/aistudio/datasetdetail/131538 这一份数据集。

谢谢你的数据集，能请教一下产生问题的原因吗？因为我也是需要用自己的数据集，训练其他的模型

**Comment by zhenzi0322** [comment]
> 谢谢你的数据集，能请教一下产生问题的原因吗？因为我也是需要用自己的数据集，训练其他的模型

你的数据集是怎么样的了，你报的错误是什么？发出来看看，你怎么找到这里的，我记得我关闭了这个链接了的

**Comment by SurvivorNo1** [comment]
> 

我也是使用的自定义数据集，然后报错是和你一样的。我换了一个数据集是可以启动训练的，但是就是自定义的无法开始训练。

**Comment by zhenzi0322** [comment]
你自定义的数据集的尺寸是多大的？ 配置文件中的内容发出来看一下

**Comment by SurvivorNo1** [comment]
> 你自定义的数据集的尺寸是多大的？ 配置文件中的内容发出来看一下

我的自定义数据集内，有两种尺寸的图片 1920*1024  1024*851
配置文件：
train_dataset:
dataset_root:/home/aistudio/data/data_2022 mode: train
num_classes:4
train_path:/home/aistudio/data/data_2022/train_list.txt transforms:
-max_scale_factor: 2.0
min_scale_factor:0.5 
scale_step_size:0.25 
type:ResizeStepScaling 
crop_size: 
-864 
-486
type:RandomPaddingCrop
type:RandomHorizontalFlip
brightness_range:0.4		
contrast_range: 0.4 
saturation_range:0.4
type:RandomDistort	
-type:Normalize	
type:Dataset

**Comment by zhenzi0322** [comment]
咱两的配置文件都不一样呢？你能格式化一下配置文件的内容再发出来不？

**Comment by SurvivorNo1** [comment]
> 咱两的配置文件都不一样呢？你能格式化一下配置文件的内容再发出来不？


batch_size: 4
iters: 160000

train_dataset:
  type: Dataset
  dataset_root: /home/aistudio/data/data_2022
  train_path: /home/aistudio/data/data_2022/train.txt
  num_classes: 4
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [864, 486]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train


val_dataset:
  type: Dataset
  dataset_root: /home/aistudio/data/data_2022
  val_path: /home/aistudio/data/data_2022/val.txt
  num_classes: 4
  transforms:
    - type: Resize  
      target_size: [864, 486]
      interp: 'LINEAR'  
    - type: Normalize
  mode: val

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.02

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 5.0e-4

model:
  type: HarDNet
  pretrained: null

loss:
  types:
    - type: BootstrappedCrossEntropyLoss
      min_K: 4096
      loss_th: 0.3
  coef: [1]

**Comment by SurvivorNo1** [comment]
[[](url)](https://github.com/SurvivorNo1/-/blob/d5b4572177ec66057f18c8e133e8615d5668907d/QQ%E6%88%AA%E5%9B%BE20220310161044.png)

**Comment by SurvivorNo1** [comment]
![This is an image](https://github.com/SurvivorNo1/-/blob/d5b4572177ec66057f18c8e133e8615d5668907d/QQ%E6%88%AA%E5%9B%BE20220310161044.png)

**Comment by zhenzi0322** [comment]
> ![This is an image](https://github.com/SurvivorNo1/-/blob/d5b4572177ec66057f18c8e133e8615d5668907d/QQ%E6%88%AA%E5%9B%BE20220310161044.png)
你这个项目都跟我这边的项目都不是一样的呢？你用的是城市分割，我用的是Mattings。我也不清楚你那边是什么出错

**Comment by SurvivorNo1** [comment]
> 
可以分享一下你是怎么解决的吗?我可以做个参考，谢谢啦

**Comment by Robin3Chan** [comment]
你好，我也出现同样all input arrays must have the same shape报错。我是自定义Matting数据集，数据集为不同尺寸。请教一下应当如何处理该报错，应当修改什么配置或者方法？谢谢

**Comment by NOON47** [comment]
不是尺寸问题，是图像的位深度问题，需要8位，可以检查一下自己的图片属性
