### ISSUE TITLE
小白请问各位大佬，想要使用paddleseg训练一个实例分割模型，跑通全流程的那个案例可以运行，但是换成自己的数据就不行，是根据数据处理文档进行处理的数据，是配置文件需要修改什么吗？还有配置文件如何选择呢？

### ISSUE THREAD

**Issue by chenyixun1112** [PaddlePaddle/PaddleSeg#1844]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by 02825cm** [comment]
可以检查下数据集，是用原图和伪彩色图或者灰度图训练

**Comment by chenyixun1112** [comment]
> 

那请问对于配置文件的选择呢？

**Comment by chenyixun1112** [comment]
> 可以检查下数据集，是用原图和伪彩色图或者灰度图训练
那请问对于配置文件的选择呢？

**Comment by chenyixun1112** [comment]
> 可以检查下数据集，是用原图和伪彩色图或者灰度图训练

我是使用灰度的来着

**Comment by chenyixun1112** [comment]
> 可以检查下数据集，是用原图和伪彩色图或者灰度图训练

我是使用的伪彩色的呢

**Comment by 02825cm** [comment]
为彩色是标注后生成的吗？还是转化的

**Comment by 02825cm** [comment]
看你的硬件来改下配置文件的前两个参数，然后就是改下数据集路径就可以了

**Comment by chenyixun1112** [comment]
> 为彩色是标注后生成的吗？还是转化的

标注生成的

**Comment by 02825cm** [comment]
标注的会报错，要自己用脚本转

**Comment by 02825cm** [comment]
或者用灰度图训练

**Comment by chenyixun1112** [comment]
> 或者用灰度图训练

那我试试，谢谢你~

**Comment by 02825cm** [comment]
不客气，我之前也碰到了这个问题，搞了好久，确实恼火

**Comment by chenyixun1112** [comment]
> 不客气，我之前也碰到了这个问题，搞了好久，确实恼火

它跑起来了，但是，跑几轮儿就停住了好像，这是咋回事儿呢？
![image](https://user-images.githubusercontent.com/99322256/157011053-c5e856da-be07-499b-b6d5-699a80aa125e.png)

**Comment by shiyutang** [comment]
It seems the program finished training, did you set the iter as 180?

**Comment by 02825cm** [comment]
> > 不客气，我之前也碰到了这个问题，搞了好久，确实恼火
> 
> 它跑起来了，但是，跑几轮儿就停住了好像，这是咋回事儿呢？ ![image](https://user-images.githubusercontent.com/99322256/157011053-c5e856da-be07-499b-b6d5-699a80aa125e.png)

应该是跑成功了吧success，你的配置文件是咋写的？

**Comment by shiyutang** [comment]
If you set iter equals to 180, the training process is successful and you are good to go.

**Comment by shiyutang** [comment]
It seems the issue has been solved and I will close it now. If you have further issues, please reopen it.
