### ISSUE TITLE
人像分割PP-HumanSeg能否运行在windows cpu环境下？

### ISSUE THREAD

**Issue by Alvazz** [PaddlePaddle/PaddleSeg#1848]
感谢开源付出，我的exe是运行在windows环境下，只考虑cpu环境，请问“人像分割PP-HumanSeg”这个功能库可能支持吗？

如果可以的话，一般帧率大概在多少？能否支持1920x1080的摄像头流呢？

额外我看这个库都是python写的，如果我采用的是c++，那该如何调用呢？

谢谢

**Comment by LutaoChu** [comment]
你好，人像分割是支持cpu的。只需要安装CPU版本的Paddle即可。
具体帧率还没有测过。我们有不同大小的模型，不同模型的帧率也会不一样。支持摄像头流的，文档中有提供这块的使用说明。
目前仅支持python，c++的话可以调用paddle inference的[c++接口](https://paddle-inference.readthedocs.io/en/latest/quick_start/cpp_demo.html)，需要对整体代码进行改写

**Comment by Alvazz** [comment]
好的，感谢你的回复，我主要是想跑一下PP-HumanSeg看看效果。有问题再向你们请教。谢谢

**Comment by Alvazz** [comment]
发现一个问题
![00](https://user-images.githubusercontent.com/50744096/157159527-954b0623-19f2-4c41-95ab-c62e7fa953f0.png)

**Comment by LutaoChu** [comment]
报错来看没有找到对应版本的包，建议换个版本试试，在官网安装教程里选择。不建议用develop版本。
还是安装不了的话可以去paddle官方repo下提issue

**Comment by justld** [comment]
> 感谢开源付出，我的exe是运行在windows环境下，只考虑cpu环境，请问“人像分割PP-HumanSeg”这个功能库可能支持吗？
> 
> 如果可以的话，一般帧率大概在多少？能否支持1920x1080的摄像头流呢？
> 
> 额外我看这个库都是python写的，如果我采用的是c++，那该如何调用呢？
> 
> 谢谢

可以导出onnx再C++部署，参考：https://blog.csdn.net/qq_40035462/article/details/123305451

**Comment by YiQiu1984** [comment]
> > 感谢开源付出，我的exe是运行在windows环境下，只考虑cpu环境，请问“人像分割PP-HumanSeg”这个功能库可能支持吗？
> > 如果可以的话，一般帧率大概在多少？能否支持1920x1080的摄像头流呢？
> > 额外我看这个库都是python写的，如果我采用的是c++，那该如何调用呢？
> > 谢谢
> 
> 可以导出onnx再C++部署，参考：https://blog.csdn.net/qq_40035462/article/details/123305451

请问一下，这个在windows下使用cpu推理的性能怎么样呢？可以做实时分割吗？
