### ISSUE TITLE
[Bug] 模型量化bug

### ISSUE THREAD

**Issue by justld** [PaddlePaddle/PaddleSeg#1851]
使用paddleseg进行模型量化时，发现一个bug，代码链接：https://github.com/PaddlePaddle/PaddleSeg/blob/0a7f65405a2153162d46f4065566d5e6f082879b/slim/quant/qat_train.py#L190
，根据paddleslim（2.0.0）文档，量化模型是inplace的，没有返回值，quant_model = None，所以paddleseg量化时会报错“NoneType object has no attribution 'train'”。
paddleslim(2.0.0)文档：
https://paddleslim.readthedocs.io/zh_CN/develop/api_cn/dygraph/quanter/qat.html
paddleslim（2.0.0）源码：https://github.com/PaddlePaddle/PaddleSlim/blob/c2cbef1afaeca836c7551427ebd31c6889b56f8f/paddleslim/dygraph/quant/quanter.py#L217

修改：
```
quantizer.quantize(model) 
quant_model = model
```

env:
aistudio 至尊gpu版本

PaddleSeg version:  release/2.4
PaddlePaddle version: PaddlePaddle 2.2.2
Operation system: Linux

**Comment by juncaipeng** [comment]
Fix by the above PR.
