### ISSUE TITLE
关于TensorRT预测加速的问题

### ISSUE THREAD

**Issue by gutao0315** [PaddlePaddle/PaddleSeg#1853]
大佬们看看 我这样是不是就是利用TensorRT预测成功了
![1](https://user-images.githubusercontent.com/77281977/157388372-26b5f3cd-8a87-4c68-bf04-24b60859d866.png)
![2](https://user-images.githubusercontent.com/77281977/157388484-499eb6d1-d92f-4897-8a08-16d92dfe74f4.png)
怎么看预测的速度啊 多少ms/张这样子的

**Comment by shiyutang** [comment]
Running deply/python/infer.py with benchmark=True, you will get the result like the following and tells you the inference time.
for example:
```bash
python deploy/python/infer.py --config deploy.yaml --image_path data/ --benchmark True
```

<img width="909" alt="1645 2500 H： B3 0  0 S 0" src="https://user-images.githubusercontent.com/34859558/157405827-c2a19a1b-090d-4de8-b7fd-2b402fadc5d7.png">

**Comment by gutao0315** [comment]
> Running deply/python/infer.py with benchmark=True, you will get the result like the following and tells you the inference time. for example:
> 
> ```shell
> python deploy/python/infer.py --config deploy.yaml --image_path data/ --benchmark True
> ```
> 
> <img alt="1645 2500 H： B3 0 0 S 0" width="909" src="https://user-images.githubusercontent.com/34859558/157405827-c2a19a1b-090d-4de8-b7fd-2b402fadc5d7.png">

![QQ浏览器截图20220309173452](https://user-images.githubusercontent.com/77281977/157580214-bab64a93-e741-4ae8-b757-e90aaa3299cf.png)
![QQ浏览器截图20220309173355](https://user-images.githubusercontent.com/77281977/157580226-94e047dd-f93d-4f63-8919-478aa7255fba.png)
是少了什么库吗

**Comment by Huihuihh** [comment]
同问，少了什么库

**Comment by shiyutang** [comment]
You need to install auto_log as described here:
<img width="836" alt="image" src="https://user-images.githubusercontent.com/34859558/159615546-b367af75-00b8-4aaa-a4ec-607d557a197a.png">

The tutorial to install: https://github.com/LDOUBLEV/AutoLog

**Comment by shiyutang** [comment]
If you have any further questions, you are very welcome to reopen it.
