### ISSUE TITLE
使用gpu3070推理耗时比1080ti更长

### ISSUE THREAD

**Issue by Huihuihh** [PaddlePaddle/PaddleSeg#1855]
3070gpu环境：
paddlepaddle-gpu==2.2.2.post112
cuda: 11.2
1080ti：
paddlepaddle-gpu：2.2.0
cuda：10.0

耗时：
1080ti：
54.64673042297363ms
3070：
561.3832473754883ms

**Comment by michaelowenliu** [comment]
@Huihuihh Thanks for your issue. To help us solve the issue better, please use the issue template properly.
