### ISSUE TITLE
部署时出现问题KeyError: "LoadImages does not exist in availabel transforms

### ISSUE THREAD

**Issue by zhenzi0322** [PaddlePaddle/PaddleSeg#1858]
报错信息如下：

KeyError: "LoadImages does not exist in availabel transforms:['Compose', 'RandomHorizontalFlip', 'RandomVerticalFlip', 'Resize', 'ResizeByLong', 'ResizeByShort', 'LimitLong', 'ResizeRangeScaling', 'ResizeSte
pScaling', 'Normalize', 'Padding', 'PaddingByAspectRatio', 'RandomPaddingCrop', 'RandomCenterCrop', 'ScalePadding', 'RandomNoise', 'RandomBlur', 'RandomRotation', 'RandomScaleAspect', 'RandomDistort', 'RandomAffine']"

**Comment by yangtb2** [comment]
怎么解决的，兄弟

**Comment by ZhouShaoyang** [comment]
请问一下该问题是如何解决的？

**Comment by yangtb2** [comment]
> 请问一下该问题是如何解决的？

或许你是在/PaddleSeg下执行的部署？可以尝试在/PaddleSeg/Matting下执行部署

**Comment by zhenzi0322** [comment]
注意配置。你是怎么运行的。
