### ISSUE TITLE
[Feature Request]模型裁剪和量化结合

### ISSUE THREAD

**Issue by justld** [PaddlePaddle/PaddleSeg#1861]
PaddleSeg团队你们好，目前paddleseg模型压缩提供裁剪和量化功能，但是2者功能是分开的，且裁剪后的模型不好使用paddleseg的量化功能直接量化，请问有把模型裁剪和量化结合的计划吗？

**Comment by shiyutang** [comment]
Paddleslim现在有一个自动化压缩的工具应该是可以结合的：https://github.com/PaddlePaddle/PaddleSlim/tree/develop/example/auto_compression
