### ISSUE TITLE
[Feature Request]请问有无提供PP-HumanSeg的Deeplabv3P/ResNet50这一模型的.yml配置文件？

### ISSUE THREAD

**Issue by 6UOOON9** [PaddlePaddle/PaddleSeg#1862]
我注意到PP-HumanSeg项目中的configs目录下只提供了fcn_hrnetw18_small_v1_humanseg_192x192这一模型的.yml配置文件。
.md中也提到了包括Deeplabv3P/ResNet50在内的好几个模型，但都没有提供相应的.yml配置文件。

**Comment by LutaoChu** [comment]
PP-HumanSeg目前提供的模型仅用于推理或finetune，点击链接下载，解压后的deploy.yml文件 即为对应推理yml文件。例如https://paddleseg.bj.bcebos.com/dygraph/humanseg/export/pphumanseg_lite_generic_192x192_with_softmax.zip
fcn_hrnetw18_small_v1_humanseg_192x192的yml文件是用于训练演示使用
