### ISSUE TITLE
抠头发丝有白边，白边怎么处理的?

### ISSUE THREAD

**Issue by zhenzi0322** [PaddlePaddle/PaddleSeg#1869]
示例如下：
![image](https://user-images.githubusercontent.com/34839719/158098086-01805273-0e0a-4cc2-a317-5d305c9ceefe.png)

![image](https://user-images.githubusercontent.com/34839719/158098261-b381cdd4-0ead-4eab-8e56-34d7db24eb83.png)

**Comment by juncaipeng** [comment]
我们在持续改进，目前暂时还只能做到这种程度，需要人工再筛查一下不好的图像。

**Comment by zhenzi0322** [comment]
> 我们在持续改进，目前暂时还只能做到这种程度，需要人工再筛查一下不好的图像。

是筛查出数据集中不好的图像，把不好的图像删除掉，然后再拿去训练嘛？

**Comment by zhenzi0322** [comment]
> > 我们在持续改进，目前暂时还只能做到这种程度，需要人工再筛查一下不好的图像。

@juncaipeng 
是筛查出数据集中不好的图像，把不好的图像删除掉，然后再拿去训练嘛？

**Comment by juncaipeng** [comment]
是的

**Comment by zhenzi0322** [comment]
> 是的

@juncaipeng 
哪些是不好的图像呢？我采用的数据集都是个人专门挑选出来的。alpha图像方面也是较好的。

**Comment by wuyefeilin** [comment]
用develop分支试试哈

**Comment by zhenzi0322** [comment]
> 用develop分支试试哈

@wuyefeilin 用develop分支里的Matting嘛？

**Comment by zhubinsheng** [comment]
> 用develop分支试试哈

有什么区别吗

**Comment by wuyefeilin** [comment]
你是用了那个版本的训练的呢，2.5以后我们加了前景评估的功能，可以减弱边缘白边的情况。

**Comment by zhenzi0322** [comment]
> > 用develop分支试试哈
> 
> 有什么区别吗

我试得好像没有什么区别。

**Comment by zhubinsheng** [comment]
他这个是用cpu来跑的吗，每次要400ms左右。
我现在想实时检测视频，在高通888上跑，想达到二三十fps可行吗
