### ISSUE TITLE
[Bug] ValueError: (InvalidArgument) The number of input's channels should be equal to filter's channels * groups for Op(Conv)

### ISSUE THREAD

**Issue by tuantran23012000** [PaddlePaddle/PaddleSeg#1870]
The input's channels are 1024, the input's shape is [1, 1024, 1024, 3]; 
the filter's channels are 3, the filter's shape is [64, 3, 3, 3]; 
the groups are 1, the data_format is NCHW. 
The error may come from the wrong data_format setting.
  [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:1024 != filter_dims[1] * groups:3.] (at ..\paddle/fluid/operators/conv_op.cc:119)
  [operator < conv2d > error]
Config file: bisenet_cityscapes_1024x1024_160k.yml

**Comment by juncaipeng** [comment]
You should use use np.transpose to change the dims of input image from n*h*w*c to n*c*h*w.

**Comment by tuantran23012000** [comment]
thank you, I resolve this bug

**Comment by linnnn1** [comment]
ValueError: (InvalidArgument) The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 256, the input's shape is [4, 256, 48, 48]; the filter's channels is 64, the filter's shape is [64, 64, 3, 3]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.
  [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:256 != filter_dims[1] * groups:64.] (at /paddle/paddle/phi/infermeta/binary.cc:529)，请问这样的报错应该怎么修改呢
