### ISSUE TITLE
[General Issue] cv2.addWeighted

### ISSUE THREAD

**Issue by tuantran23012000** [PaddlePaddle/PaddleSeg#1872]
cv2.addWeighted requires original_img and pseudo_img, which have the same size and the same number of channels, but, the original_img has (h,w, channels),  the original_img has (h,w, classes) in the contrast. In the case channels # classes, can we use?

**Comment by shiyutang** [comment]
You can use the argmax function on psedo-image with shape (h, w, classes) and turn it into (h,w). In this way, you can use the cv2.addWeighted correctly.
