### ISSUE TITLE
[Bug]你好，文档教程里的1.安装指南和2.快速开始，其中的训练测试命令，无法运行，请问该怎么操作呢

### ISSUE THREAD

**Issue by The-Sun-Kernel** [PaddlePaddle/PaddleSeg#1874]
Thanks for your bug report. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Full codes: (if you modify any original code，please show the comparison of the codes before and after)
 7. Detailed error information, releated running log: (if using multi-gpus，the log is saved to log/worklog.0 by default)
 8. Running command or reproduce details：
 9. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 完整的代码：(若修改过原代码，请提供修改前后代码对比）
 7. 详细的错误信息、相关log：（若使用多卡，log默认保存在log/worklog.0）
 8. 运行指令或复现步骤：
 9. 其他内容: （增加其他与问题相关的内容）

**Comment by The-Sun-Kernel** [comment]
python predict.py \
       --config configs/quick_start/bisenet_optic_disc_512x512_1k.yml \
       --model_path https://bj.bcebos.com/paddleseg/dygraph/optic_disc/bisenet_optic_disc_512x512_1k/model.pdparams\
       --image_path docs/images/optic_test_image.jpg \
       --save_dir output/result

**Comment by The-Sun-Kernel** [comment]
这个训练测试命令，由于有回车和反斜杠，无法运行。因为他会自动识别回车，导致语句断行运行。

**Comment by The-Sun-Kernel** [comment]
但是，如果我去掉回车，依然报错：因为无法识别反斜杠

**Comment by The-Sun-Kernel** [comment]
请问该如何运行训练命令呢

**Comment by shiyutang** [comment]
Based on what you described, you seem to be running the command on windows. You can try the command as 
```
python predict.py  --config configs/quick_start/bisenet_optic_disc_512x512_1k.yml 
--model_path https://bj.bcebos.com/paddleseg/dygraph/optic_disc/bisenet_optic_disc_512x512_1k/model.pdparams
--image_path docs/images/optic_test_image.jpg
--save_dir output/result
```

**Comment by The-Sun-Kernel** [comment]
okay，thank you！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年03月16日 10:30 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleSeg] [Bug]你好，文档教程里的1.安装指南和2.快速开始，其中的训练测试命令，无法运行，请问该怎么操作呢 (Issue #1874) |

Based on what you described, you seem to be running the command on windows. You can try the command as

python predict.py  --config configs/quick_start/bisenet_optic_disc_512x512_1k.yml 
--model_path https://bj.bcebos.com/paddleseg/dygraph/optic_disc/bisenet_optic_disc_512x512_1k/model.pdparams
--image_path docs/images/optic_test_image.jpg
--save_dir output/result


—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shiyutang** [comment]
It seems the issue has been solved. I will close it.
