### ISSUE TITLE
split_dataset_list.py 数据集划分脚本可能存在bug

### ISSUE THREAD

**Issue by GreatV** [PaddlePaddle/PaddleSeg#1878]
此处，使用round计算划分后的数量，在特定情况下，会多计算一个数量。导致 `IndexError: index xxx is out of bounds for axis yyyy with size xxxx` 错误。

https://github.com/PaddlePaddle/PaddleSeg/blob/a19180fd199c10676ee27f57bd2f52bcd6a07767/tools/split_dataset_list.py#L127

如：

```Python
>>> round(6665*0.7)
4666.0
>>> round(6665*0.3)
2000.0
>>> 
```

建议将`round`改为`int`。

**Comment by LutaoChu** [comment]
int也存在同样的问题，少一个数量
```
>>> int(6665*0.7)
4665
>>> int(6665*0.3)
1999
```

**Comment by LutaoChu** [comment]
请提供下出错的复现步骤

**Comment by GreatV** [comment]
对于自定义的数据集来说，少一个样本影响不大吧。或者使用减法：

```Python
>>> total_num = 6665
>>> part1 = int(total_num*0.7)
>>> part2 = int(total_num*0.3)
>>> delta = total_num - part1 - part2
>>> part1 = part1 + delta
>>> print(total_num, part1, part2)
(6665, 4666, 1999)
```

**Comment by GexLoong** [comment]
虽然报错了，但是我根据输出的txt算了算好像没错

**Comment by GexLoong** [comment]
根据txt将各个文件里面的行数加起来跟数据集里的数据总和一样
