### ISSUE TITLE
PaddleSeg Python 预测部署方案中的返回类型

### ISSUE THREAD

**Issue by HOLLIZHAO** [PaddlePaddle/PaddleSeg#188]
返回的类型中，可否 新增 返回分割轮廓的像素点数组list，而不仅仅是分割后的图片。

**Comment by Aurelius84** [comment]
感谢您的反馈，我们会评估和优化相关部署方案。

**Comment by HOLLIZHAO** [comment]
> 感谢您的反馈，我们会评估和优化相关部署方案。

非常期待！ 在统计个数、计算面积、测量距离等落地应用实现上，非常需要返回分割后各分类轮廓的像素点坐标！

**Comment by jaffe-fly** [comment]
你可以from deploy.python.infer  import run  然后run的结果就是预测的掩码 是二值图（当然infer的源码需要你修改一下，我只是提供一种方法并且我已经验证过可行），然后利用opencv 找到轮廓并结算面积等 
` mask = run(deploy_conf=conf_path, img=frame)
        binary = np.array(mask) * 255.
        binary = binary.astype(np.uint8)

        fire_contours, hierarchy = cv2.findContours(binary, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
`
大概是这样的，后续你自己发挥

**Comment by HOLLIZHAO** [comment]
> 你可以from deploy.python.infer import run 然后run的结果就是预测的掩码 是二值图（当然infer的源码需要你修改一下，我只是提供一种方法并且我已经验证过可行），然后利用opencv 找到轮廓并结算面积等
> ` mask = run(deploy_conf=conf_path, img=frame)
> binary = np.array(mask) * 255.
> binary = binary.astype(np.uint8)
> 
> ```
>     fire_contours, hierarchy = cv2.findContours(binary, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
> ```
> 
> `
> 大概是这样的，后续你自己发挥

感谢提示！已使用此方法cv2.findContours()实现！
