### ISSUE TITLE
请问如何替换Unet中的encoder？

### ISSUE THREAD

**Issue by zhongqiu1245** [PaddlePaddle/PaddleSeg#1882]
作者您好！
请问请问如何替换Unet中的encoder？比如我想把其中的encoder替换成带有pretrain的resnet50，请问我该如何修改代码呢？
谢谢！

**Comment by juncaipeng** [comment]
Unet不支持通过config yaml文件直接修改backbone，需要改动unet的组网代码，具体在如下文件。

<img width="382" alt="image" src="https://user-images.githubusercontent.com/52520497/159198254-f8c4c485-ec00-4c3c-a24a-68955acf22a2.png">

**Comment by zhongqiu1245** [comment]
谢谢
