### ISSUE TITLE
医学数据集多通道输入 npy格式

### ISSUE THREAD

**Issue by zhongqiu1245** [PaddlePaddle/PaddleSeg#1883]
作者你好
我想用pdseg作医学影像分割，输入的图像为6通道的npy。请问如何输入？

**Comment by juncaipeng** [comment]
目前pdseg文档给出的dataset配置都是图像，无法直接支持6通道的npy数据。
你需要多看看seg的文档和dataset目录代码，原理比较简单，就是一个迭代器，只是要根据你的情况改代码。

**Comment by zhongqiu1245** [comment]
谢谢！
