### ISSUE TITLE
有没有PP-HumanSeg里面能够直接跑的数据集可以下载

### ISSUE THREAD

**Issue by lzy-coder** [PaddlePaddle/PaddleSeg#1887]
目前只能使用飞浆帮忙打包的mini_supervisely，这样的数据集太少了，无法满足训练的要求

**Comment by juncaipeng** [comment]
请参考pp-humanseg论文发送邮件申请数据集。

**Comment by lzy-coder** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
邮件已经收到啦

**Comment by lzy-coder** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
邮件已经收到啦
