### ISSUE TITLE
请问有脚本可以一键分割出前景吗？

### ISSUE THREAD

**Issue by weiqingtangx** [PaddlePaddle/PaddleSeg#1888]
你好，非常感谢你们开源了PaddleSeg，PaddleSeg是我用的最舒服的一个分割库，使用非常简单，文档也非常齐全，对于刚入门的开发者来说极大的降低了入门的门槛。

通过几天的学习和训练我已经完成我的训练模型，想请问下有没现成的脚本能分割出前景并替换背景呢？

**Comment by juncaipeng** [comment]
你好，seg不提供通用前景和背景分割的模型，通常需要用户自己根据实际场景，标注前景和背景，训练模型进行分割。

**Comment by weiqingtangx** [comment]
好的，谢谢
