### ISSUE TITLE
vs2019 cmake编译的时候 报错，没有百度到解决方案，

### ISSUE THREAD

**Issue by jaffe-fly** [PaddlePaddle/PaddleSeg#189]
![image](https://user-images.githubusercontent.com/49515380/76522890-5dd5e580-64a2-11ea-9877-29e870e93eb3.png)

**Comment by Aurelius84** [comment]
windows下编译可以参考官方文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/compile_Windows.html

**Comment by jaffe-fly** [comment]
如果有遇到上面相同问题的朋友 可以参考这篇博文 https://blog.csdn.net/weixin_44831720/article/details/104835721
