### ISSUE TITLE
[Bug] (External) CUDA error(702), the launch timed out and was terminated. 

### ISSUE THREAD

**Issue by xinliyangguang** [PaddlePaddle/PaddleSeg#1898]
Thanks for your bug report. To help us solve the issue better, please provide following information：
 1. PaddleSeg version:  PaddleSeg release/2.3
 2. PaddlePaddle version: paddlepaddle-gpu 2.2.2
 3. Operation system: Win10
 4. Python version: python3.6
 5. CUDA/cuDNN version: CUDA10.2/cuDNN 7.6.5
 6. Full codes: (if you modify any original code，please show the comparison of the codes before and after)
 训练的时候报如下错误：
error log:
![image](https://user-images.githubusercontent.com/53338761/159275825-d7d8a2b1-9623-49bf-a549-537636b7b200.png)
报错的源码位置：
![image](https://user-images.githubusercontent.com/53338761/159275962-68744d70-e6c0-48ad-a2ab-6b32e0c806ae.png)

配置文件：
![image](https://user-images.githubusercontent.com/53338761/159276247-6dafc476-212c-4645-ba35-f988b666e3b3.png)
![image](https://user-images.githubusercontent.com/53338761/159276302-adc8d2f6-3310-45c3-a5f2-5457e2b66d03.png)

**Comment by wuyefeilin** [comment]
更新paddleseg版本重新运行一下看看能不能解决问题

**Comment by jawi289o** [comment]
Same issue. I am using the latest paddleseg version with cuda 11.8.
