### ISSUE TITLE
请问deeplabv3模型剪枝完，如何进行在线量化？

### ISSUE THREAD

**Issue by hp-cuiwb** [PaddlePaddle/PaddleSeg#190]

**Comment by LielinJiang** [comment]
先用之前剪枝的策略剪枝模型，加载已经训练好的剪枝模型，然后再使用相应的量化策略即可。

**Comment by hp-cuiwb** [comment]
> TRAIN.PRETRAINED_MODEL_DIR "./saved_model/deeplabv3p_mobilenetv2_wx_prue_all_0.7/final" \
> TRAIN.MODEL_SAVE_DIR "./deeplabv3p_mobilenetv2_wx_prue_all_0.7_quant" \
> MODEL.DEEPLAB.ENCODER_WITH_ASPP False \
> MODEL.DEEPLAB.ENABLE_DECODER False \
> TRAIN.SYNC_BATCH_NORM False \
> SOLVER.LR 0.0001 \
> TRAIN.SNAPSHOT_EPOCH 1 \
> SOLVER.NUM_EPOCHS 30 \
> BATCH_SIZE 4 \
> 
{'AUG': {'AUG_METHOD': 'stepscaling',
         'FIX_RESIZE_SIZE': (2048, 1024),
         'FLIP': False,
         'FLIP_RATIO': 0.5,
         'INF_RESIZE_VALUE': 500,
         'MAX_RESIZE_VALUE': 600,
         'MAX_SCALE_FACTOR': 2.0,
         'MIN_RESIZE_VALUE': 400,
         'MIN_SCALE_FACTOR': 0.5,
         'MIRROR': True,
         'RICH_CROP': {'ASPECT_RATIO': 0.33,
                       'BLUR': False,
                       'BLUR_RATIO': 0.1,
                       'BRIGHTNESS_JITTER_RATIO': 0.5,
                       'CONTRAST_JITTER_RATIO': 0.5,
                       'ENABLE': False,
                       'MAX_ROTATION': 15,
                       'MIN_AREA_RATIO': 0.5,
                       'SATURATION_JITTER_RATIO': 0.5},
         'SCALE_STEP_SIZE': 0.25},
 'BATCH_SIZE': 4,
 'DATALOADER': {'BUF_SIZE': 256, 'NUM_WORKERS': 8},
 'DATASET': {'DATA_DIM': 3,
             'DATA_DIR': './dataset/wx_data/data',
             'IGNORE_INDEX': 255,
             'IMAGE_TYPE': 'gray',
             'NUM_CLASSES': 3,
             'PADDING_VALUE': [127.5, 127.5, 127.5],
             'SEPARATOR': ' ',
             'TEST_FILE_LIST': './dataset/wx_data/data/train.txt',
             'TEST_TOTAL_IMAGES': 1169,
             'TRAIN_FILE_LIST': './dataset/wx_data/data/train.txt',
             'TRAIN_TOTAL_IMAGES': 1169,
             'VAL_FILE_LIST': './dataset/wx_data/data/train.txt',
             'VAL_TOTAL_IMAGES': 1169,
             'VIS_FILE_LIST': None},
 'EVAL_CROP_SIZE': (2049, 1025),
 'FREEZE': {'MODEL_FILENAME': '__model__',
            'PARAMS_FILENAME': '__params__',
            'SAVE_DIR': 'freeze_model_nosep'},
 'MEAN': [0.5, 0.5, 0.5],
 'MODEL': {'BN_MOMENTUM': 0.99,
           'DEEPLAB': {'ASPP_WITH_SEP_CONV': False,
                       'BACKBONE': 'mobilenetv2',
                       'DECODER_USE_SEP_CONV': False,
                       'DEPTH_MULTIPLIER': 1.0,
                       'ENABLE_DECODER': False,
                       'ENCODER_WITH_ASPP': False,
                       'OUTPUT_STRIDE': 16},
           'DEFAULT_EPSILON': 1e-05,
           'DEFAULT_GROUP_NUMBER': 32,
           'DEFAULT_NORM_TYPE': 'bn',
           'FP16': False,
           'HRNET': {'STAGE2': {'NUM_CHANNELS': [40, 80], 'NUM_MODULES': 1},
                     'STAGE3': {'NUM_CHANNELS': [40, 80, 160],
                                'NUM_MODULES': 4},
                     'STAGE4': {'NUM_CHANNELS': [40, 80, 160, 320],
                                'NUM_MODULES': 3}},
           'ICNET': {'DEPTH_MULTIPLIER': 0.5, 'LAYERS': 50},
           'MODEL_NAME': 'deeplabv3p',
           'MULTI_LOSS_WEIGHT': [1.0],
           'PSPNET': {'DEPTH_MULTIPLIER': 1, 'LAYERS': 50},
           'SCALE_LOSS': 'DYNAMIC',
           'UNET': {'UPSAMPLE_MODE': 'bilinear'}},
 'NUM_TRAINERS': 1,
 'SLIM': {'KNOWLEDGE_DISTILL': False,
          'KNOWLEDGE_DISTILL_IS_TEACHER': False,
          'KNOWLEDGE_DISTILL_TEACHER_MODEL_DIR': '',
          'NAS_ADDRESS': '',
          'NAS_IS_SERVER': True,
          'NAS_PORT': 23333,
          'NAS_SEARCH_STEPS': 100,
          'NAS_SPACE_NAME': '',
          'NAS_START_EVAL_EPOCH': 0,
          'PRUNE_PARAMS': '',
          'PRUNE_RATIOS': []},
 'SOLVER': {'BEGIN_EPOCH': 1,
            'CROSS_ENTROPY_WEIGHT': None,
            'DECAY_EPOCH': [10, 20],
            'GAMMA': 0.1,
            'LOSS': ['softmax_loss'],
            'LR': 0.0001,
            'LR_POLICY': 'poly',
            'LR_WARMUP': False,
            'LR_WARMUP_STEPS': 2000,
            'MOMENTUM': 0.9,
            'MOMENTUM2': 0.999,
            'NUM_EPOCHS': 30,
            'OPTIMIZER': 'sgd',
            'POWER': 0.9,
            'WEIGHT_DECAY': 4e-05},
 'STD': [0.5, 0.5, 0.5],
 'TEST': {'TEST_MODEL': 'saved_model/deeplabv3p_mobilenetv2_wx_prue_all_0.7/final_prue'},
 'TRAIN': {'MODEL_SAVE_DIR': './deeplabv3p_mobilenetv2_wx_prue_all_0.7_quant',
           'PRETRAINED_MODEL_DIR': './saved_model/deeplabv3p_mobilenetv2_wx_prue_all_0.7/final',
           'RESUME_MODEL_DIR': '',
           'SNAPSHOT_EPOCH': 1,
           'SYNC_BATCH_NORM': False},
 'TRAINER_ID': 0,
 'TRAIN_CROP_SIZE': (769, 769)}
#Device count: 1
batch_size_per_dev: 4
W0313 16:14:29.632486  6995 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 10.0
W0313 16:14:29.634538  6995 device_context.cc:245] device: 0, cuDNN Version: 7.6.
Pretrained model dir:  ./saved_model/deeplabv3p_mobilenetv2_wx_prue_all_0.7/final
/home/cwb/.local/lib/python3.7/site-packages/paddle/fluid/executor.py:804: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
Parameter[conv1_1_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv1_1_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv1_1_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv1_1_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv1_1_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv2_1_expand_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv2_1_expand_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv2_1_expand_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv2_1_expand_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv2_1_expand_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv2_1_dwise_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv2_1_dwise_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv2_1_dwise_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv2_1_dwise_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv2_1_dwise_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv2_1_linear_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv2_1_linear_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv2_1_linear_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv2_1_linear_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv2_1_linear_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_1_expand_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_1_expand_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_1_expand_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_1_expand_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_1_expand_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_1_dwise_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_1_dwise_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_1_dwise_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_1_dwise_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_1_dwise_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_1_linear_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_1_linear_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_1_linear_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_1_linear_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_1_linear_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_2_expand_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_2_expand_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_2_expand_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_2_expand_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_2_expand_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_2_dwise_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_2_dwise_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_2_dwise_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_2_dwise_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_2_dwise_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_2_linear_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_2_linear_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_2_linear_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_2_linear_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv3_2_linear_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_1_expand_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_1_expand_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_1_expand_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_1_expand_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_1_expand_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_1_dwise_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_1_dwise_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_1_dwise_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_1_dwise_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_1_dwise_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_1_linear_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_1_linear_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_1_linear_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_1_linear_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_1_linear_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_2_expand_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_2_expand_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_2_expand_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_2_expand_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_2_expand_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_2_dwise_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_2_dwise_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_2_dwise_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_2_dwise_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_2_dwise_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_2_linear_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_2_linear_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_2_linear_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_2_linear_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_2_linear_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_3_expand_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_3_expand_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_3_expand_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_3_expand_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_3_expand_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_3_dwise_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_3_dwise_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_3_dwise_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_3_dwise_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_3_dwise_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_3_linear_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_3_linear_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_3_linear_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_3_linear_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv4_3_linear_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_1_expand_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_1_expand_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_1_expand_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_1_expand_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_1_expand_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_1_dwise_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_1_dwise_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_1_dwise_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_1_dwise_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_1_dwise_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_1_linear_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_1_linear_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_1_linear_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_1_linear_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_1_linear_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_2_expand_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_2_expand_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_2_expand_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_2_expand_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_2_expand_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_2_dwise_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_2_dwise_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_2_dwise_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_2_dwise_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_2_dwise_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_2_linear_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_2_linear_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_2_linear_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_2_linear_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_2_linear_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_3_expand_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_3_expand_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_3_expand_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_3_expand_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_3_expand_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_3_dwise_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_3_dwise_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_3_dwise_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_3_dwise_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_3_dwise_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_3_linear_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_3_linear_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_3_linear_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_3_linear_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_3_linear_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_4_expand_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_4_expand_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_4_expand_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_4_expand_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_4_expand_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_4_dwise_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_4_dwise_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_4_dwise_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_4_dwise_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_4_dwise_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_4_linear_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_4_linear_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_4_linear_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_4_linear_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv5_4_linear_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_1_expand_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_1_expand_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_1_expand_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_1_expand_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_1_expand_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_1_dwise_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_1_dwise_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_1_dwise_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_1_dwise_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_1_dwise_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_1_linear_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_1_linear_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_1_linear_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_1_linear_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_1_linear_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_2_expand_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_2_expand_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_2_expand_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_2_expand_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_2_expand_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_2_dwise_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_2_dwise_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_2_dwise_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_2_dwise_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_2_dwise_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_2_linear_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_2_linear_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_2_linear_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_2_linear_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_2_linear_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_3_expand_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_3_expand_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_3_expand_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_3_expand_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_3_expand_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_3_dwise_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_3_dwise_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_3_dwise_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_3_dwise_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_3_dwise_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_3_linear_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_3_linear_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_3_linear_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_3_linear_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv6_3_linear_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_1_expand_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_1_expand_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_1_expand_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_1_expand_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_1_expand_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_1_dwise_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_1_dwise_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_1_dwise_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_1_dwise_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_1_dwise_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_1_linear_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_1_linear_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_1_linear_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_1_linear_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_1_linear_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_2_expand_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_2_expand_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_2_expand_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_2_expand_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_2_expand_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_2_dwise_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_2_dwise_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_2_dwise_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_2_dwise_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_2_dwise_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_2_linear_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_2_linear_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_2_linear_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_2_linear_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_2_linear_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_3_expand_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_3_expand_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_3_expand_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_3_expand_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_3_expand_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_3_dwise_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_3_dwise_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_3_dwise_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_3_dwise_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_3_dwise_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_3_linear_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_3_linear_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_3_linear_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_3_linear_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv7_3_linear_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv8_1_expand_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv8_1_expand_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv8_1_expand_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv8_1_expand_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv8_1_expand_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv8_1_dwise_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv8_1_dwise_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv8_1_dwise_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv8_1_dwise_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv8_1_dwise_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[conv8_1_linear_weights] don't exist or shape does not match current network, skip to load it.
Parameter[conv8_1_linear_bn_scale] don't exist or shape does not match current network, skip to load it.
Parameter[conv8_1_linear_bn_offset] don't exist or shape does not match current network, skip to load it.
Parameter[conv8_1_linear_bn_mean] don't exist or shape does not match current network, skip to load it.
Parameter[conv8_1_linear_bn_variance] don't exist or shape does not match current network, skip to load it.
Parameter[logit/weights] don't exist or shape does not match current network, skip to load it.
Parameter[logit/biases] don't exist or shape does not match current network, skip to load it.
0/262 pretrained parameters loaded successfully!

**Comment by hp-cuiwb** [comment]
可是这样的话，加载预训练的剪枝模型，会导致权重的shape不匹配而跳过加载，那训练出来的模型不还是原始模型的量化模型吗？

**Comment by LielinJiang** [comment]
代码里面还是要先对网络进行相同的剪枝，只不过这次剪枝完直接加载之前训好的剪枝模型。然后再量化

**Comment by hp-cuiwb** [comment]
[好的，感谢，那我测试时，怎么测试，我现在得到这些
![image](https://user-images.githubusercontent.com/47169147/76674400-09d61880-65ea-11ea-9bf8-3ee2790ec6f1.png)

**Comment by LielinJiang** [comment]
这些是权重，载入权重时，指向这个文件夹就行

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。
