### ISSUE TITLE
backbone替换问题

### ISSUE THREAD

**Issue by XiePeiyao** [PaddlePaddle/PaddleSeg#1902]
您好！PaddleSeg中的backbone类型包括vit，但是何种架构可以调用vit作为backbone？还是暂时未提供该功能，不可将FCN以及其他架构的backbone设置为vit？期待您的答复！谢谢！

**Comment by wuyefeilin** [comment]
可以的哈，不过我们这边没有提供相应的配置文件，你可以仿照其它的配置文件构建自己的配置文件进行，或者直接调用API进行组合

**Comment by XiePeiyao** [comment]
谢谢您的解答！但是运行到下面语句的第三句会出现错误，显示vision_transformer不具有feat_channels
        self.backbone = backbone
        self.use_jpu = use_jpu
        in_channels = self.backbone.feat_channels

**Comment by gg22mm** [comment]
直接调用API进行组合, 就是直接在notebook中就可以运行了吧 ！！ 这种操作简单方便~~ ！！！
