### ISSUE TITLE
如何把enable_use_gpu(100, 0)修改成多卡

### ISSUE THREAD

**Issue by zhenzi0322** [PaddlePaddle/PaddleSeg#1903]
如何把enable_use_gpu(100, 0)修改成多卡

**Comment by wuyefeilin** [comment]
如果你要进行多卡训练的话请参考训练教程https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.4/docs/whole_process.md#37-muti-card-training

**Comment by zhenzi0322** [comment]
> 如果你要进行多卡训练的话请参考训练教程https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.4/docs/whole_process.md#37-muti-card-training

我不是多卡训练，我是要在部署时使用多卡

**Comment by wuyefeilin** [comment]
部署不支持多卡

**Comment by zhenzi0322** [comment]
> 部署不支持多卡

好的
