### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by ql390962** [PaddlePaddle/PaddleSeg#1904]
您好，paddleseg.utils.metrics能否增加F1，Recall, Precision。

**Comment by shiyutang** [comment]
The metrics that you mentioned are used in detection rather than in segmentation. How do you think it can be used in paddleseg? I believe that you can find these implementations in paddledetection.

**Comment by shiyutang** [comment]
We have added it in recent PR：https://github.com/PaddlePaddle/PaddleSeg/pull/1911/files#diff-35a8845cc2c228fe8a484e6b8773c603696abe77d46a20dfc357fd43f89b38fc

**Comment by shiyutang** [comment]
If you have any further questions, you are very welcome to reopen it.
