### ISSUE TITLE
[General Issue]新冠

### ISSUE THREAD

**Issue by GexLoong** [PaddlePaddle/PaddleSeg#1906]
请问这个项目能用于新冠图像分割吗，类似于那种能够检测部分区域进行框出分割的。我读了这个项目相关案例，感觉知识用于进行区域分割的，不像是包含新冠检测的

**Comment by shiyutang** [comment]
From what you described, it seems to be a two-stage solution. First, you detect that coronavirus ROI area then you segment it. It will be better if you provide one of the images that you want to segment. And what is the "项目相关案例" that you read?

**Comment by shiyutang** [comment]
BTW, can you share the information about which project do you intend to use PaddleSeg?
