### ISSUE TITLE
跑一个四分类数据集，发现只有背景和一个类别有评估结果，其余两类就直接显示0. ，请问有什么解决方法吗，是跑的deeplabv3+

### ISSUE THREAD

**Issue by ttttnnnn13** [PaddlePaddle/PaddleSeg#1907]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by shiyutang** [comment]
You need to provide some information for us to solve your problem. It will be better if you paste the training log.

1. What is the ratio of each class in your dataset?
2. how long have you trained your model?
3. what does your data looks like?

**Comment by shiyutang** [comment]
If you have any further questions, you are very welcome to reopen it.
