### ISSUE TITLE
dim训练500迭代后预测的问题

### ISSUE THREAD

**Issue by zhenzi0322** [PaddlePaddle/PaddleSeg#1908]
请教一下：我在使用`dim`模型时遇到的一些问题如下：
第一种情况：
![image](https://user-images.githubusercontent.com/34839719/159639170-fe6c5dc3-7f5b-4e33-839a-95b5a3b8ce52.png)

我提供了`trimap`图像进行训练的，在预测时没有提供`--trimap_path`，为什么会发生成这种情况的呢？ 

第二种情况是如下：
![image](https://user-images.githubusercontent.com/34839719/159640572-b118237a-7a18-43e6-8bad-66e1880e085c.png)

我提供了`trimap`图像进行训练的，第二种情况预测时提供了`--trimap_path`，这样预测的结果好一点，但是抠的图的周边会出现白边较多的情况，如果最后部署也需要提供`trimap`图像才能把抠出图片中的效果出来嘛？问题是用户上传图片不可能同时叫用户上传`trimap`图像吧？有没有办法使得`dim`模型在预测时只上传一张图片就能处理好抠图，就像`MODNet`那样的效果。

**Comment by wuyefeilin** [comment]
不想使用trimap的话，你用modnet进行训练和预测哈

**Comment by zhenzi0322** [comment]
> 不想使用trimap的话，你用modnet进行训练和预测哈

麻烦看了问题再回答哈，我没有不想用`trimap`，就是想知道是不是每次预测都得传`trimap`才能抠出图来?

**Comment by wuyefeilin** [comment]
是的
