### ISSUE TITLE
[General Issue]如何在4K分辨率（3840*2160）的图像上进行语义分割

### ISSUE THREAD

**Issue by T0L0ve** [PaddlePaddle/PaddleSeg#1909]
我想训练一个模型在4k分辨率的图像上进行语义分割，但我发现所有的配置文件中最大的crop_size也只有1024*1024。
如果我将图像resize成小分辨率这可能会导致损失一些特征信息，而如果对图像进行裁剪这可能导致损失一些上下文信息。
我需要如何处理我的图像？

**Comment by shiyutang** [comment]
In my opinion, you can randomly crop part of the image, as big as your video memory can tolerate,  using transform. And then use slide_inference to predict the result on the whole image. In this way:
1. The network can see all of the images if you train the model long enough.
2. You will be able to get the whole prediction.

**Comment by shiyutang** [comment]
If you have any further questions, you are very welcome to reopen it.
