### ISSUE TITLE
生成模型在测试集上的指标

### ISSUE THREAD

**Issue by landscapelc** [PaddlePaddle/PaddleSeg#1916]
目前eval生成的指标只跟训练集和验证集有关，请问如何在自己的测试集上也能得到这些评估的指标呢？

**Comment by haoyuying** [comment]
您的测试集包含ground truth吗？

**Comment by landscapelc** [comment]
有ground truth的

**Comment by haoyuying** [comment]
那就把它整理成val的形式来调用val相关的操作就好了

**Comment by landscapelc** [comment]
好的呢非常感谢，我去试试，请问具体是在那些地方进行相关修改呢
