### ISSUE TITLE
[Bug] 预处理RandomCenterCrop中的问题

### ISSUE THREAD

**Issue by faye0078** [PaddlePaddle/PaddleSeg#1917]
PaddleSeg version: release/2.4
PaddleSeg/paddleseg/transforms/transforms.py

761 行:
label[p0:p1, p2:p3, :]
label为2维张量，多了一个":"导致运行出错

**Comment by haoyuying** [comment]
您好，您是使用的什么数据集导致报错呢？可否给出更具体的数据预处理策略，包括调用了哪些代码，使用的什么数据集，label的格式等，方便我们排查问题

**Comment by faye0078** [comment]
是图像语义分割的数据集，自上传的，label为8bit的单通道png图像读入，二维张量格式；
预处理过程为简单的RandomCenterCrop-RandomHorizontalFlip-Normalize；处理错误就在761行的RandomCenterCrop操作中，label的维度只有两个，不能进行三维的切割；
不过一般的数据集label应该都为二维张量，而且注意到transforms.py中其他预处理操作均为对label的二维裁剪，如695行中的RandomPaddingCrop、826行的ScalePadding操作。

**Comment by faye0078** [comment]
不好意思预处理过程有问题，这个RandomCenterCrop并不能固定长宽输出，应该使用RandomPaddingCrop。
但是这个切割的bug确实存在

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
