### ISSUE TITLE
您好，我在尝试改优化器的过程中遇到了如图问题，请问该法哪里有问题

### ISSUE THREAD

**Issue by ttttnnnn13** [PaddlePaddle/PaddleSeg#1918]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）
![1](https://user-images.githubusercontent.com/75407455/159869609-4da413b0-fb9b-46e0-8398-2c4dfef2783c.png)
![2](https://user-images.githubusercontent.com/75407455/159869616-8d53ea03-92ea-4e1d-805b-fe19c8fa1149.png)

**Comment by haoyuying** [comment]
您好，您使用的optimizer必须是paddle提供的optimizer，具体的调用可以参考https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.4/paddleseg/cvlibs/config.py#L150

**Comment by ttttnnnn13** [comment]
可是您的最新文档里有Adam等其他优化器的api接口，那我该怎么调用了，不能在配置文件里调整吗，我用的最新版paddelseg



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月24日(周四) 下午4:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleSeg] 您好，我在尝试改优化器的过程中遇到了如图问题，请问该法哪里有问题 (Issue #1918)




 
您好，您使用的optimizer必须是paddle提供的optimizer，具体的调用可以参考https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.4/paddleseg/cvlibs/config.py#L150
