### ISSUE TITLE
用命令行形式写的函数 怎么直接传参数进去？直接cfg=文件路劲不对吗？

### ISSUE THREAD

**Issue by jaffe-fly** [PaddlePaddle/PaddleSeg#192]
![image](https://user-images.githubusercontent.com/49515380/76607379-dd20f300-654e-11ea-83bc-1d3f438578fd.png)

**Comment by LDOUBLEV** [comment]
可以尝试先把文件load 进来
with open(file', 'r') as f:
    data = yaml.load(f.read())

**Comment by jaffe-fly** [comment]
谢谢
with open(conf_path, 'r',encoding='UTF-8') as f:
    data = yaml.load(f,Loader=yaml.FullLoader)
print(data['TEST']['TEST_MODEL'])
