### ISSUE TITLE
PaddleSeg怎么在aistudio里部署呢

### ISSUE THREAD

**Issue by zhenzi0322** [PaddlePaddle/PaddleSeg#1922]
请教一下`PaddleSeg`在`aistudio`怎么部署呢，有没有相关详细的`Paddleseg`部署流程之类的?

**Comment by LutaoChu** [comment]
首页有很多部署教程，可以根据这些教程进行部署   https://github.com/PaddlePaddle/PaddleSeg/blob/develop/README_CN.md
<img width="323" alt="image" src="https://user-images.githubusercontent.com/30695251/160318270-84342e96-b23e-499c-968b-2cfa6efa6198.png">

**Comment by zhenzi0322** [comment]
@LaraStuStu  麻烦看一下问题哈。我想知道的是在`aistudio`里的部署，不是在自己服务器上或者本地。示意图如下：
![image](https://user-images.githubusercontent.com/34839719/160319074-9c846d0e-ed96-4696-9e83-21d73c05b5e0.png)

**Comment by LutaoChu** [comment]
这个我没部署过。建议看看AI studio上有没有官方的部署教程呢
