### ISSUE TITLE
ViT预训练模型和数据集图片大小对应不一致问题

### ISSUE THREAD

**Issue by peach-xiao** [PaddlePaddle/PaddleSeg#1925]
paddleseg里面提供了使用VisionTransformer为backbone的分割模型segmenter,文件显示的是加载预训练模型vit_base_patch16_384_augreg.tar.gz，这个模型表示是在ImageNet上预训练的，图片的尺寸是384的大小。

![image](https://user-images.githubusercontent.com/40911688/160130872-d98e1790-4e29-45ba-8b80-7c4d4ec93e44.png)

加载该预训练模型，为什么使用512大小的图片放入segmenter网络不会报错？按理说使用VisionTransformer为backbone,patch_size=16，不同大小的图片，裁剪后的token数量不一样（如：384x384 // 16x16 = 576,  512x512 // 16x16=1024）,这样的话模型的参数也就不同了，加载应该提示错误才对。希望可以得到解释。

对于swin_transformer来说，原作者提供了swin_tiny_patch4_window7_224 和swin_tiny_patch4_window7_384大小的预训练模型，我们若加载该模型，图片的大小必须对应是224或384的大小。这是和paddleseg里最大的不同，可以解释一下为什么吗？

非常感谢！

**Comment by juncaipeng** [comment]
不同的输入和patch，得到的token数量确实不同，但是segmenter内部会使用三次插值得到positionembedding的权重，内部tensor是b*n*c(n表示token数量)，所以内部权重不用改变。具体可以参考VisionTransformer代码。
ppseg目前还没支持swin_transformer。

**Comment by JeavanCode** [comment]
> 不同的输入和patch，得到的token数量确实不同，但是segmenter内部会使用三次插值得到positionembedding的权重，内部tensor是b_n_c(n表示token数量)，所以内部权重不用改变。具体可以参考VisionTransformer代码。 ppseg目前还没支持swin_transformer。

如果需要修改patch size大小呢

**Comment by gg22mm** [comment]
我觉得输入图与也改成 384 就好了， 有没有notebook直接运行的，  整套运行太重了~~
