### ISSUE TITLE
[General Issue]unet训练过程中进行模型评估保存时报错all the input array dimensions for the concatenation axis must match exactly

### ISSUE THREAD

**Issue by GexLoong** [PaddlePaddle/PaddleSeg#1929]
unet训练过程中进行模型评估保存时报错
![HLG3JOY%LG1)$J5@A%F7Y2C](https://user-images.githubusercontent.com/71758483/160265362-dc1412f7-0a73-452e-9253-952ce920ff43.png)
**配置文件**：
val_dataset:
  type: Dataset
  dataset_root: ../data/data134998/prepare_data
  val_path: ../data/data134998/prepare_data/val.txt
  num_classes: 2
  transforms:
    - type: Normalize
  mode: val
**源码**：
if auc_roc:
                    logits = F.softmax(logits, axis=1)
                    if logits_all is None:
                        logits_all = logits.numpy()
                        label_all = label.numpy()
                    else:
                        logits_all = np.concatenate(  
                            [logits_all, logits.numpy()])  # (KN, C, H, W)  检查了logits.numpy()的尺寸为(1, 2, 512, 512)
                        label_all = np.concatenate([label_all, label.numpy()])

**Comment by GexLoong** [comment]
我发现问题的原因好像是因为我的数据集中图片分辨率有512x512、630x630、630x401的，是必须化成相同的分辨率吗，能直接在配置文件里面添加数据增强操作进行裁剪吗，我把配置文件改成下面这样，报错Shape of `pred` and `label should be equal, but there are [1, 512, 512] and [1, 630, 630]. 意思是预测的大小和真实大小不同，这样子改配置文件不会修改annotation里面图片的尺寸大小吗，请问要怎么改
val_dataset:
  type: Dataset
  dataset_root: ../data/data134998/prepare_data
  val_path: ../data/data134998/prepare_data/val.txt
  num_classes: 2
  transforms:
    - type: RandomPaddingCrop
      crop_size: [512, 512]
    - type: Normalize
  mode: val

**Comment by juncaipeng** [comment]
建议用Resize替换RandomPaddingCrop

**Comment by GexLoong** [comment]
> 建议用Resize替换RandomPaddingCrop

最后还是把图片数据分辨率都改成512*512才解决了

还有个问题就是unet能和transformer结合吗，paddleseg里面有提供吗

**Comment by GexLoong** [comment]
> > 建议用Resize替换RandomPaddingCrop
> 
> 最后还是把图片数据分辨率都改成512*512才解决了
> 
> 还有个问题就是unet能和transformer结合吗，paddleseg里面有提供吗

我看paddleseg里面只有segformer好像用到了swin transformer

**Comment by juncaipeng** [comment]
这个结合没有实现过，你可以自己看看代码进行修改。

**Comment by uipe846** [comment]
也同样遇到，跑了官方PP-Matting模型例子数据都一样，windows下报错：
`Traceback (most recent call last):
  File "E:\AIprint\KouTu\PaddleSeg\Matting\tools\predict.py", line 113, in <module>
    main(args)
  File "E:\AIprint\KouTu\PaddleSeg\Matting\tools\predict.py", line 100, in main
    predict(
  File "E:\AIprint\KouTu\PaddleSeg\Matting\tools\..\ppmatting\core\predict.py", line 166, in predict
    fg = save_result(
  File "E:\AIprint\KouTu\PaddleSeg\Matting\tools\..\ppmatting\core\predict.py", line 64, in save_result
    rgba = np.concatenate((fg, alpha), axis=-1)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 1080`
