### ISSUE TITLE
滑动窗口验证相关问题

### ISSUE THREAD

**Issue by peach-xiao** [PaddlePaddle/PaddleSeg#1931]
对于Transformer相关的语义分割模型segmenter，setr，segformer的滑动窗口验证，我还有以下问题希望可以得到你们的帮助

滑动窗口验证的步长是否会影响模型验证的结果呢？比如说我的验证集图片大小是512x512，当我的滑动窗口步长分别是256和341或者别的步长，加载同样的权重模型，验证的结果是否不同？

设置滑动窗口的步长有什么注意事项吗？我注意到不同的数据集，裁剪窗口的大小和对于的步长都有所不同。如在yaml文件里设置验证Val的参数：pascal_contex数据集 验证的CROP_SIZE: [480,480], STRIDE_SIZE: [320,320]，adk数据集 CROP_SIZE: [512,512]， STRIDE_SIZE: [341,341] ，cityscapes数据集 CROP_SIZE: [768,768] STRIDE_SIZE: [512,512]
验证时设置的裁剪窗口大小和步长是有对应关系的吗？设置其他的步长是否会对验证有影响，或者说需要按照这样设置才行

滑动窗口验证时通过将图片根据步长将验证集的图片裁剪成重叠的多个小块，然后分别将这些小块送入模型进行验证求取结果，不知道我这样的理解是否正确呢？

感谢您的耐心回复~

**Comment by juncaipeng** [comment]
结不同步长，结果差异不大，步长越小，耗时越久，精度估计高一点点。
步长一般小于窗口大小。
对的，多个小块预测，重叠区域取预测结果的平均。
