### ISSUE TITLE
Possibly Missing Brackets in "infer_dataset.py"

### ISSUE THREAD

**Issue by Pr0Wh1teGive** [PaddlePaddle/PaddleSeg#1933]
1. PaddleSeg version: 2.4
 2. PaddlePaddle version: 2.2.2
 3. Operation system: Linux
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: CUDA10.2/cuDNN 7.6.5
 6. Full codes: within deploy/python/infer_dataset.py line 284
```
        logger.info("[EVAL] Average time: %.3f ms/img" %
                    (total_time / len(dataset)) * 1000)
```
ISSUE: Should add one more bracket over  "(total_time / len(dataset)) * 1000", otherwise the "1000" will duplicate the log information 1000 times on my machine instead of covert seconds to ms.

**Comment by juncaipeng** [comment]
Thanks, we will check and fix it.
