### ISSUE TITLE
 optimizer.step() 报错

### ISSUE THREAD

**Issue by peach-xiao** [PaddlePaddle/PaddleSeg#1934]
我在自己的数据集上运行pspnet模型，使用的optimizer是SGD,在执行模型的一个训练后，计算损失，我查看了loss是有值的，反向传播计算模型参数的梯度后，执行optimizer.step()进行参数更新，报错了TypeError: 'str' object is not callable。PSPNet,里面的模型FCN我能正常运行，说明对于相应的数据集等配置应该是没有问题的，但是BiseNet，PSPNet，DANet等模型就出现了优化器更新的错误，我实在想不出是哪里可能出现了问题，希望能得到帮助，感谢！

![image](https://user-images.githubusercontent.com/40911688/160422088-1751a75f-d6a6-4f86-9763-a7322ee1ff81.png)

**Comment by shiyutang** [comment]
You should try to debug and find if there is something wrong with the optimizer because its step method seems to be a string.
Try add "import pdb; pdb.set_trace()" before this line.

**Comment by shiyutang** [comment]
If you have any further question, you are very welcomed to repoen it.
