### ISSUE TITLE
如果我要训练通用人像的模型的话，那么PaddleSeg的数据集中的数据量大概是多少呢？

### ISSUE THREAD

**Issue by zhenzi0322** [PaddlePaddle/PaddleSeg#1941]
如果我要训练通用人像的模型的话，那么PaddleSeg的数据集中的数据量大概是多少呢？

**Comment by LutaoChu** [comment]
你是说哪个PaddleSeg数据集呢？  PP-HumanSeg14K的话一共大概1万四千张，主要是半身像场景。可以再去获取supervisely person数据集一起训练

**Comment by zhenzi0322** [comment]
> 你是说哪个PaddleSeg数据集呢？ PP-HumanSeg14K的话一共大概1万四千张，主要是半身像场景。可以再去获取supervisely person数据集一起训练

如果我要训练`Mattings`中的`MODNet`的模型的话，我大概需要准备多少的数据量才能达到通用人像抠图的场景？

**Comment by wuyefeilin** [comment]
越多越好咯，至少1k以上吧

**Comment by zhenzi0322** [comment]
> 越多越好咯，至少1k以上吧

我准备了3k以上，但是预测不是数据集中的图片时效果就不太好了

@wuyefeilin

**Comment by wuyefeilin** [comment]
> > 越多越好咯，至少1k以上吧
> 
> 我准备了3k以上，但是预测不是数据集中的图片时效果就不太好了
> 
> @wuyefeilin

数据集外的数据预测比较差是正常的，可以在训练时多加一些数据增强，如颜色扰动，模糊等较少过拟合。

**Comment by zhenzi0322** [comment]
> > > 越多越好咯，至少1k以上吧
> > 
> > 
> > 我准备了3k以上，但是预测不是数据集中的图片时效果就不太好了
> > @wuyefeilin
> 
> 数据集外的数据预测比较差是正常的，可以在训练时多加一些数据增强，如颜色扰动，模糊等较少过拟合。

这方面数据增强不会设置，目前都是用现有的配置文件中的配置项
