### ISSUE TITLE
[Bug] Transform 中的 RandomAffine Label 的 padding 值是0

### ISSUE THREAD

**Issue by pazifik-cyber** [PaddlePaddle/PaddleSeg#1942]
欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：PaddleSeg release/2.4
 6. 完整的代码：(若修改过原代码，请提供修改前后代码对比）
```
        if label is not None:
            label = cv2.warpAffine(
                np.uint8(label),
                matrix,
                tuple(self.size),
                flags=cv2.INTER_NEAREST,
                borderMode=cv2.BORDER_CONSTANT)
```
应该需要增加 borderValue 参数

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
