### ISSUE TITLE
Paddleseg是否提供了计算模型params、FPS和FLOPs的方法

### ISSUE THREAD

**Issue by peach-xiao** [PaddlePaddle/PaddleSeg#1943]
对于语义分割，很多论文中在比较模型的性能，其中模型的参数Param、FPS和FLOPs也是衡量模型性能的指标，是否可以提供计算这些指标的方法？

![image](https://user-images.githubusercontent.com/40911688/160598908-b3939e0c-7727-4601-8f82-48f7db9a50fe.png)

以上截图来源于论文CSWin Transformer: A General Vision Transformer Backbone with Cross-Shaped Windows

**Comment by shiyutang** [comment]
Yes.

1. Params are the size of the model file; 
2. Flops can be calculated using [paddle.flops](https://github.com/PaddlePaddle/PaddleSeg/blob/bd46c4e3a4de788e5356c5aeff28ae2b660ab61a/paddleseg/core/train.py#L314); 
3. FPS can be deduced using the data in following picture, which is generated with benchmark on in inference. Here is the doc: https://github.com/PaddlePaddle/PaddleSeg/blob/develop/docs/deployment/inference/python_inference_cn.md#4-%E9%A2%84%E6%B5%8B

<img width="791" alt="Pte info" src="https://user-images.githubusercontent.com/34859558/160739084-7aeb1e8b-439c-4276-b0e6-80a2b5b16111.png">

**Comment by shiyutang** [comment]
If you have any further question, you are very welcomed to repoen it.

**Comment by tyh153** [comment]
> 

请问在生成的日志中FPS是哪个呢

**Comment by YonghuiTAN22** [comment]
> 是的。
> 
> 1. Params是模型文件的大小；
> 2. 可以使用[paddle.flops](https://github.com/PaddlePaddle/PaddleSeg/blob/bd46c4e3a4de788e5356c5aeff28ae2b660ab61a/paddleseg/core/train.py#L314)计算触发器；
> 3. 可以使用下图中的数据推导出 FPS，该数据是在推理中使用基准生成的。这是文档：https: [//github.com/PaddlePaddle/PaddleSeg/blob/develop/docs/deployment/inference/python_inference_cn.md#4-%E9%A2%84%E6%B5%8B](https://github.com/PaddlePaddle/PaddleSeg/blob/develop/docs/deployment/inference/python_inference_cn.md#4-%E9%A2%84%E6%B5%8B)
> 
> <img alt="个人资料" width="791" src="https://user-images.githubusercontent.com/34859558/160739084-7aeb1e8b-439c-4276-b0e6-80a2b5b16111.png">

请问在生成的日志中FPS是哪个呢
