### ISSUE TITLE
Bisenetv1运行predict.py报错-未在配置文件中指定验证集'The verification dataset is not specified in the configuration file.'

### ISSUE THREAD

**Issue by SZYD717** [PaddlePaddle/PaddleSeg#1946]
欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：release/2.4
 2. PaddlePaddle版本：PaddlePaddle 2.2.2
 3. 操作系统信息：Ubuntu20.04
 4. Python版本号：Python3.6.13
 5. CUDA/cuDNN版本：CUDA10.2/cuDNN 7.6.5
 
报错内容：
使用configs/bisenetv1/bisenetv1_resnet18_os8_cityscapes_1024x512_160k.yml进行测试
cityscapes数据集已放置到data/cityscapes下，和configs/_base_/cityscapes.yml文件中的dataset_root的值一致
使用预训练模型运行predict.py，具体命令如下
python predict.py \
       --config configs/bisenetv1/bisenetv1_resnet18_os8_cityscapes_1024x512_160k.yml \
       --model_path output/bisenetv1/model.pdparams \
       --image_path data/test.png \
       --save_dir output/result/bisenetv1
后提示The verification dataset is not specified in the configuration file

**Comment by SZYD717** [comment]
问题已解决，需要使用./tools下的create_dataset_list.py和convert_cityscapes.py进行索引提取和格式转换。

**Comment by SoUHoo** [comment]
你好  你使用的是cityscapes数据集吗，还是使用的使用的其他数据集？
