### ISSUE TITLE
用visualdl无法展示模型，请问怎么转成onnx格式

### ISSUE THREAD

**Issue by Jinji97** [PaddlePaddle/PaddleSeg#1947]
![image](https://user-images.githubusercontent.com/47912612/160968037-ef4e7a19-041d-4970-8f4f-1ec669726364.png)
想可视化模型，用visualdl无法展示，请问怎么转成onnx格式，用了官方代码无法展示成功，求救

**Comment by rainyfly** [comment]
你好，想要看模型结构需要用pdmodel格式的文件，可以通过paddle.jit.save[https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/jit/save_cn.html]方法导出。
