### ISSUE TITLE
[General Issue]在调用focalloss 时出现了cuda出错，请问是版本问题吗，问题如图上传

### ISSUE THREAD

**Issue by ttttnnnn13** [PaddlePaddle/PaddleSeg#1948]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg 2.4）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.1）
 3. 操作系统信息：（Windows10）
 4. Python版本号：（Python3.6）
 5. CUDA/cuDNN版本：（ 如CUDA10.1）
 6. 其他内容: （增加其他与问题相关的内容）
`Traceback (most recent call last):
  File "train.py", line 198, in <module>
    main(args)
  File "train.py", line 193, in main
    profiler_options=args.profiler_options)
  File "D:\PaddleSeg\paddleseg\core\train.py", line 214, in train
    avg_loss += loss.numpy()[0]
OSError: (External) CUDA error(719), unspecified launch failure.
  [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common
cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error
. To continue using CUDA, the process must be terminated and relaunched.] (at ..\paddle\fluid\platform\gpu_info.cc:441)
`

**Comment by haoyuying** [comment]
目前这个错误初步定位是cuda，cudnn及paddle的版本不匹配导致的，建议排查三者版本是否匹配。
