### ISSUE TITLE
[Bug] No performance improvement on Matting model even with tensorrt and even when reducio

### ISSUE THREAD

**Issue by hackkhai** [PaddlePaddle/PaddleSeg#1949]
Thanks for your bug report. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: PaddlePaddle 2.2.2
 3. Operation system: Linux
 4. Python version: Python3.7
 5. CUDA/cuDNN version: CUDA11.2/cuDNN 8.2.1
 6. Full codes: None
 7. Detailed error information, releated running log: None
 8. Running command or reproduce details：python deploy/python/infer.py --config ./export/deploy.yaml --device gpu --image_path ./clothing/ --use_trt True --precision fp16 --benchmark True
 9. Additional context: (Add any other context about the problem)
[without_tensorrt.txt](https://github.com/PaddlePaddle/PaddleSeg/files/8388544/without_tensorrt.txt)
[with_tensorrt.txt](https://github.com/PaddlePaddle/PaddleSeg/files/8388545/with_tensorrt.txt)
also i have cudnn in my pc but the auto_log says None but when i check it with pytorch it works fine and nvcc -V works as well.Please help me if i am doing something wrong.
Thanks

**Comment by haoyuying** [comment]
you can set min_subgraphmin_subgraph_size=10 and evaluate the performance changes.
![image](https://user-images.githubusercontent.com/35907364/161179856-6a250b0d-2b79-490f-8bd8-b4507bf0fb8c.png)
If it does not work, you can try this link: https://github.com/PaddlePaddle/Paddle2ONNX/blob/model_zoo/hardwares/tensorrt/README.md
