### ISSUE TITLE
重新训练模型resume_model时报错UnboundLocalError：local variable 'images' referenced before assignment 

### ISSUE THREAD

**Issue by huangwan-jiayi** [PaddlePaddle/PaddleSeg#1952]
环境信息：
![image](https://user-images.githubusercontent.com/71338215/161188538-76d5ea82-d584-4deb-a3d9-8d5f184e74dc.png)
报错
![image](https://user-images.githubusercontent.com/71338215/161188741-742c831f-eef0-43a3-9297-bae5a842e267.png)

**Comment by shiyutang** [comment]
It seems that you should check the image. try ```import pdb; pdb.set_trace()``` before line 315 and see if image is loaded

**Comment by huangwan-jiayi** [comment]
> It seems that you should check the image. try `import pdb; pdb.set_trace()` before line 315 and see if image is loaded

i don know what this situation mean:
![image](https://user-images.githubusercontent.com/71338215/161911013-1eb970ab-3671-4767-a564-14a1309d9df4.png)

**Comment by shiyutang** [comment]
You can check how to use [pdb](https://docs.python.org/3/library/pdb.html), and see what is the image here.

**Comment by shiyutang** [comment]
If you have any further questions, you are very welcome to reopen it.
