### ISSUE TITLE
训练时报C++ Traceback类的问题[General Issue]

### ISSUE THREAD

**Issue by xinliyangguang** [PaddlePaddle/PaddleSeg#1955]
欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）：PaddleSeg-2.3
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0） Paddle2.0
 3. 操作系统信息：（如Linux/Windows/MacOS）Linux
 4. Python版本号：（如Python3.6/7/8）Python3.7
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）cuda10.2，cuDNN7.6
 在Paddlecloud端提交了任务，发现报如下错误：
![image](https://user-images.githubusercontent.com/53338761/161249241-19d0c7e2-9969-4cd9-801b-ec2d91125779.png)

**Comment by shiyutang** [comment]
If you are training your model with multiple GPU, you can check the worklog.x under the log directory. Otherwise, you can try to train with CPU and see if the error message changes.

**Comment by shiyutang** [comment]
If you have any further questions, you are very welcome to reopen it.
