### ISSUE TITLE
[General Issue] How to use PaddleSeg on Unity?

### ISSUE THREAD

**Issue by jaehwlee** [PaddlePaddle/PaddleSeg#1961]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3) PaddleSeg release/2.4
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0) paddlepaddle-gpu 2.2.2
 3. Operation system: (e.g. Linux/Windows/MacOS) Window
 4. Python version: (e.g. Python3.6/7/8) 3.7
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5) 10.1 7.6.5
 6. Additional context: (Add any other context about the problem)

Hi! I have a question for using PaddleSeg on Unity.

I tried to import the model after converting it to ONNX format, but the following error occurred.
-![Untitled](https://user-images.githubusercontent.com/33409264/161666332-b55991d0-70f6-4db1-9d88-47ab1d4a773d.png)

What can I do?
---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 3. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 4. 操作系统信息：（如Linux/Windows/MacOS）
 5. Python版本号：（如Python3.6/7/8）
 6. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 7. 其他内容: （增加其他与问题相关的内容）

**Comment by juncaipeng** [comment]
This is the error of Paddle2ONNX, please create a new issue in https://github.com/PaddlePaddle/Paddle2ONNX.

**Comment by jaehwlee** [comment]
Thanks, I'll create a new issue.
