### ISSUE TITLE
关于上线谷歌市场是否违规的问题

### ISSUE THREAD

**Issue by androidGhost** [PaddlePaddle/PaddleSeg#1962]
PaddlePredictor.jar里面包含baidu和Tensor关键词，是否容易被检测出来而定性使用违规操作（之前使用华为的SDK直接定性违规，不处理直接下架删除的警告）

**Comment by juncaipeng** [comment]
这个不太清楚，如果你遇到该问题，需要删除特定关键字，可以在Paddle repo中提issue，给出你的需求。

https://github.com/PaddlePaddle/Paddle

**Comment by androidGhost** [comment]
好的，感谢你的回答
