### ISSUE TITLE
The inference size of real-time models such as bisenet or stdc

### ISSUE THREAD

**Issue by ydhongHIT** [PaddlePaddle/PaddleSeg#1985]
In their papers, the input size during inference is not 1024x2048. But I can not find the settings (it needs to resize the original image to a smaller resize) in your config file. Is the accuracy of these real-time models obtained with the same resolution as the paper?

**Comment by juncaipeng** [comment]
For fair comparison, PaddleSeg use the origin image as input by default. If  you want to resize the image in testing, please refer to the [demo](https://github.com/PaddlePaddle/PaddleSeg/blob/develop/configs/pp_liteseg/pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k.yml#L42)

<img width="215" alt="image" src="https://user-images.githubusercontent.com/52520497/162653357-783bca43-c9ba-46d7-8400-d7a4930ba29b.png">
