### ISSUE TITLE
[General Issue]在使用评估程序的时候 我发现2.4版本可以计算出 包括准确率 召回率  ROC曲线等在内的许多评估参数，请问下如何打开使用这个功能，

### ISSUE THREAD

**Issue by weiluonika** [PaddlePaddle/PaddleSeg#1986]
visualDL工具如何将训练参数进行可视化，只能看到注入IOU和loss之类的参数，无法看到诸如ROC曲线之类的数据

**Comment by juncaipeng** [comment]
2.4版本没有计算分割类别的Precision和Recall，develop有计算，可以切换到develop分支。ROC曲线是都没有的。

**Comment by weiluonika** [comment]
> 2.4版本没有计算分割类别的Precision和Recall，develop有计算，可以切换到develop分支。ROC曲线是都没有的。

我使用的是develop分支，自定义数据集，修改了attention_unet的config文件，但是在运行val.py的过程，运行命令
（python val.py  --config /lzl/PaddleSeg/configs/attention_unet/attention_unet_cityscapes_1024x512_80k.yml   --model_path /lzl/PaddleSeg/output/iter_2000/model.pdparams ）中还是没有Precision和Recall数据 是需要在哪打开或者添加参数嘛

**Comment by juncaipeng** [comment]
在训练阶段，Precision和Recall数值是输出在log中，没有保存在visualdl中显示。
在验证阶段，会输出类别Precision和Recall啊

![image](https://user-images.githubusercontent.com/52520497/163104038-dc59017d-c9da-4eaa-914e-0294d1428e83.png)

**Comment by weiluonika** [comment]
> 在训练阶段，Precision和Recall数值是输出在log中，没有保存在visualdl中显示。 在验证阶段，会输出类别Precision和Recall啊
> 
> ![image](https://user-images.githubusercontent.com/52520497/163104038-dc59017d-c9da-4eaa-914e-0294d1428e83.png)
我重新检查了下，在gitee的develop版本是没有的，重新拉了下github是我develop分支，进行评估的时候报错


<img width="707" alt="1649832205(1)" src="https://user-images.githubusercontent.com/50006064/163116072-959a81d3-660d-45e1-b706-17c352350e3b.png">
我尝试拉了几遍，还是相同的问题，是我环境配置的原因吗

**Comment by juncaipeng** [comment]
你是什么操作系统，Python版本是多少啊？ 我使用develop分支没有遇到该问题。

**Comment by weiluonika** [comment]
> 你是什么操作系统，Python版本是多少啊？ 我使用develop分支没有遇到该问题。

CentOS Linux release 7.9.2009 (Core)
python3.6.8
