### ISSUE TITLE
[General Issue]求教，在模型转出成ONNX后，对要输入ONNX模型的图像应该怎么样去处理？

### ISSUE THREAD

**Issue by pandalee594** [PaddlePaddle/PaddleSeg#1988]
小白求教，对输入PADDLESEG转出的ONNX模型的图像需要进行怎样的预处理？我直接使用导出模型的infer.py进行推理的结果是正确的，但是使用onnx模型的时候推出来的结果只有背景，语言py/c#。谢谢！

**Comment by juncaipeng** [comment]
同样将维度从nhwc转为nchw，还需要做normalize(mean=0.5, std=0.5)。

**Comment by liyaoshigehaoren** [comment]
有onnx模型，能否发一份给我

**Comment by juncaipeng** [comment]
可以参考paddleseg首页文档转换为onnx模型。
