### ISSUE TITLE
UNet up-sample OP issue

### ISSUE THREAD

**Issue by hi-bigcat** [PaddlePaddle/PaddleSeg#199]
Hi,
De-conv is configured as the up-sample op, but in the saved models the up-sample op is still bilinear-interp, show as below pictures:
<img width="258" alt="fb0e8272f6c44ebceb8c839398e89ea3" src="https://user-images.githubusercontent.com/46183033/76956572-463da780-694f-11ea-9934-aab64c9d1fc5.png">
<img width="405" alt="dc3fb9162440dedeb5ff284da1c4048e" src="https://user-images.githubusercontent.com/46183033/76956591-52296980-694f-11ea-99cd-2b24b9cf5242.png">

**Comment by LutaoChu** [comment]
经与用户沟通，是用户配置上的错误，目前已经可以重新训练

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。
