### ISSUE TITLE
[General Issue]deploy/python/infer.py 推理stdc模型时间异常。

### ISSUE THREAD

**Issue by huangwan-jiayi** [PaddlePaddle/PaddleSeg#1992]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：版本号2.2.0分支PaddleSeg release/2.4）
 2. PaddlePaddle版本：（如PaddlePaddle 2.2.0-gpu）
 3. 
![aa375cb0040110caf41c70ff80df137](https://user-images.githubusercontent.com/71338215/162701646-1cd402b8-f95c-4cfa-a1cc-5d41f424a969.png)
 4. 操作系统信息：Linux Ubuntu18.04
 5. Python版本号：python3.6
 6. CUDA/cuDNN版本：cuda10.2，cudnn8.1
 使用depoly/python/infer.py 对训练自定义数据集导出的bisenetV2模型和stdc1-seg模型分别推理，都调用了trt精度都是fp16.   bisenetV2的推理速度大概在7ms左右，（并且调用trt后推理速度明细提升），但是stdc模型调用trt模型后推理速度反而有所下降或者没有改动，是stdc模型不支持trt吗，我看论文不是有200多fps的推理速度么，它们是怎么实现的呢？
推理情况 BisenetV2：
![dde4473b596a12fc564588ae068b01a](https://user-images.githubusercontent.com/71338215/162702903-09a03677-eaaf-4b67-b8fc-34aa739172c3.png)
stdc1-seg：
![image](https://user-images.githubusercontent.com/71338215/162703002-8c3b3584-6271-43ce-9fa2-e4b160da7cfe.png)

这是预测时间的方式：
![image](https://user-images.githubusercontent.com/71338215/162703113-c1e0b97f-0782-4d4d-a8b7-615d71c06452.png)

**Comment by juncaipeng** [comment]
有几个因素影响测试速度：
* 论文中是对1024*2048原图进行缩小后预测，再将结果resize为原图大小
* 通常使用导出为ONNX，用TRT直接加载ONNX模型部署，速度更快（相比使用PaddleInference）
* 上述使用PaddleInference预测中，我们近期修复了一个bug，[此处](https://github.com/PaddlePaddle/PaddleSeg/blob/develop/deploy/python/infer.py#L315)设置min_subgraph_size等于3，trt加速会比较明显。

**Comment by juncaipeng** [comment]
有几个因素影响测试速度：
* 论文中是对1024*2048原图进行缩小后预测，再将结果resize为原图大小
* 通常使用导出为ONNX，用TRT直接加载ONNX模型部署，速度更快（相比使用PaddleInference）
* 上述使用PaddleInference预测中，我们近期修复了一个bug，[此处](https://github.com/PaddlePaddle/PaddleSeg/blob/develop/deploy/python/infer.py#L315)设置min_subgraph_size等于3，trt加速会比较明显。

**Comment by huangwan-jiayi** [comment]
> 有几个因素影响测试速度：
> 
> * 论文中是对1024*2048原图进行缩小后预测，再将结果resize为原图大小
> * 通常使用导出为ONNX，用TRT直接加载ONNX模型部署，速度更快（相比使用PaddleInference）
> * 上述使用PaddleInference预测中，我们近期修复了一个bug，[此处](https://github.com/PaddlePaddle/PaddleSeg/blob/develop/deploy/python/infer.py#L315)设置min_subgraph_size等于3，trt加速会比较明显。

你好，我设置等于3后推理报错
![image](https://user-images.githubusercontent.com/71338215/162871924-32fadc73-fdfa-434a-9049-4c8d487d3f21.png)
![image](https://user-images.githubusercontent.com/71338215/162871978-22d25f04-0682-45ff-950f-3abaafc05d83.png)

**Comment by juncaipeng** [comment]
可以设置输入参数`--enable_auto_tune=True`避免该错误。

https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.4/docs/deployment/inference/python_inference.md
