### ISSUE TITLE
paddleseg用C++部署，并生成DLL，python调用DLL预测的问题

### ISSUE THREAD

**Issue by ihunzi** [PaddlePaddle/PaddleSeg#1995]
背景：
把paddleseg用C++部署，生成dll给python调用。现在已经成功生成dll并且python成功加载模型。

问题：
①有关于输入图像的转换问题，我图像预处理完之后[512， 512， 3]，要怎么变换才能正确输入给预测函数？
![image](https://user-images.githubusercontent.com/87402289/162733826-ceff049f-3fde-401e-ba3f-f120131c90f9.png)

②以及输出结果的这个变量要怎么定义？
③我要怎么从预测函数中拿到结果？
④好像获取到的结果是byte[]类型，我要怎么转换成python的list或者numpy类型的数据。
![image](https://user-images.githubusercontent.com/87402289/162733944-09d3f3ec-eac7-40a2-baab-8558b4c88982.png)

我找了很久都没有测试成功，希望能指导一下，感谢

**Comment by juncaipeng** [comment]
问题1： transpose对维度进行变换，hwc->chw，使用np.transpose(img, (2, 0, 1))

为啥要这样封装，可以直接参考paddleseg的python 或者 c++部署文档啊？文档都在seg首页可以看到：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.4/README_CN.md

**Comment by ihunzi** [comment]
感谢回复！

原因：
我用pyqt5写了一个上位机，实现语义分割的功能。将程序打包，用pyinstaller打包出来之后，paddlepadle老是报错，而且在网上查了很多资料都没有解决，程序根本跑不起来。后来想到，把paddleseg用C++部署，生成DLL给python调用，来实现我的需求，于是有了上面的问题。
（或者有没有什么方法可以把paddlepaddle正确打包）
（代码、模型都已经在python测试完成了）
我用的是paddleX部署的：https://github.com/PaddlePaddle/PaddleX/blob/develop/deploy/cpp/docs/models/paddleseg.md

问题：
①Python用的是ctypes库来调用dll，我想知道的是，我预处理完的图像要转成ctypes的数据形式输入给预测函数，这一步要怎么操作或者说代码怎么写。这一步我写了一个好像没报错，但是我现在获取不到输出结果，所以不知道写得对不对：
`
input = np.asarray(img)
`
`
fake_input = input.ctypes.data_as(c_char_p)     # 输入图像
`

②我接收预测结果，用什么样的ctypes数据类型来接收，这个变量怎么定义或者说代码怎么写？
③好像C++预测完的结果是 bytes[] 类型的，我该怎么转成python的list或者numpy类型的数据或者opencv的图像。
C++函数的原型 【Seg_ModelPredict】：https://github.com/PaddlePaddle/PaddleX/blob/develop/deploy/cpp/docs/csharp_deploy/model_infer.cpp

由于我C++水平不行，这个问题困扰有几天了

**Comment by ihunzi** [comment]
![image](https://user-images.githubusercontent.com/87402289/162862036-ca8827c4-f5dc-4d86-913a-0452c8cc638e.png)
