### ISSUE TITLE
[General Issue] 能否维护一下 API应用案例的代码，已经在aistudio上跑不通了。

### ISSUE THREAD

**Issue by anzx2452** [PaddlePaddle/PaddleSeg#2003]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by anzx2452** [comment]
是否建议使用backbone中的包，mixTransformer

**Comment by shiyutang** [comment]
Please provide a link to the malfunctioning AIStudio project. 

MixTransformer is the backbone of  SegFormer_B0. Please state the reason why you need it, we can know if it is recommended.

**Comment by anzx2452** [comment]
> 

https://aistudio.baidu.com/aistudio/projectdetail/1339458

**Comment by shiyutang** [comment]
please provide the  error message.

**Comment by anzx2452** [comment]
> 

recent call last)/tmp/ipykernel_140/3532040227.py in <module> 12 num_workers=0, 13 losses=losses, ---> 14 use_vdl=True) /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleseg/core/train.py in train(model, train_dataset, val_dataset, optimizer, save_dir, iters, batch_size, resume_model, save_interval, log_iters, num_workers, use_vdl, losses, keep_checkpoint_max, test_config, fp16, profiler_options, to_static_training) 279 280 mean_iou, acc, _, _, _ = evaluate( --> 281 model, val_dataset, num_workers=num_workers, **test_config) 282 283 model.train() /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleseg/core/val.py in evaluate(model, eval_dataset, aug_eval, scales, flip_horizontal, flip_vertical, is_slide, stride, crop_size, num_workers, print_detail, auc_roc) 121 is_slide=is_slide, 122 stride=stride, --> 123 crop_size=crop_size) 124 125 intersect_area, pred_area, label_area = metrics.calculate_area( /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleseg/core/infer.py in inference(model, im, ori_shape, transforms, is_slide, stride, crop_size) 241 logit = logit.transpose((0, 3, 1, 2)) 242 if ori_shape is not None: --> 243 logit = reverse_transform(logit, ori_shape, transforms, mode='bilinear') 244 pred = paddle.argmax(logit, axis=1, keepdim=True, dtype='int32') 245 return pred, logit /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleseg/core/infer.py in reverse_transform(pred, ori_shape, transforms, mode) 100 """recover pred to origin shape""" 101 reverse_list = get_reverse_list(ori_shape, transforms) --> 102 intTypeList = [paddle.int8, paddle.int16, paddle.int32, paddle.int64] 103 dtype = pred.dtype 104 for item in reverse_list[::-1]: AttributeError: module 'paddle' has no attribute 'int8'

**Comment by shiyutang** [comment]
paddle needs to be upgrade to 2.2

**Comment by shiyutang** [comment]
We have upgrade it: https://aistudio.baidu.com/aistudio/projectdetail/1339458
<img width="798" alt="image" src="https://user-images.githubusercontent.com/34859558/163176087-17ab6ef3-e351-4fdc-86b7-e2624fbbbde2.png">
