### ISSUE TITLE
Paddleseg无法冻结预训练模型

### ISSUE THREAD

**Issue by Leon-E-Zion** [PaddlePaddle/PaddleSeg#2008]
Paddleseg无法冻结预训练模型

**Comment by haoyuying** [comment]
您好，您可以让backbone处于eval模式，自己修改optimization的优化参数的范围来实现该功能

**Comment by Leon-E-Zion** [comment]
Leon-Zion 工作站 已收到邮件，Leon将尽快处理

**Comment by Leon-E-Zion** [comment]
> 

你好，可以详细指出是在哪些文件中进行修改吗 谢谢

**Comment by shiyutang** [comment]
是需要在模型文件中打开 with paddle.no_grad(); 并调整优化器的学习率
