### ISSUE TITLE
部署预测生成的图像过大

### ISSUE THREAD

**Issue by zhenzi0322** [PaddlePaddle/PaddleSeg#2009]
我在使用`Matting`训练好了一个模型，然后导出了模型文件。最后使用导出的模型进行预测，命令如下：
```
python infer.py --config export/test/deploy.yaml --image_path ./static/uploads/ --save_dir output/result_test
```
其中`static/uploads/`有两张图片。分别为：
```
test.jpg    20.7MB
test2.jpg   5.45MB
test3.jpg  27.8KB
```
最后发现在`output/result_test/clip`文件夹抠好的图中，图片名和大小如下：
```
test.png  71.4MB
test2.png  38.3MB
test3.png  309KB
```
采用导出的模型进行预测为什么生成的抠图的文件大小会这么大的呢？

**Comment by wuyefeilin** [comment]
原图是jpg 3通道有损压缩图片，保存的是png无损压缩图片，所以大很多很正常哈

**Comment by zhenzi0322** [comment]
> 原图是jpg 3通道有损压缩图片，保存的是png无损压缩图片，所以大很多很正常哈

问题是大得不太正常呢，难道你不觉得嘛

**Comment by yangy996** [comment]
> > 原图是jpg 3通道有损压缩图片，保存的是png无损压缩图片，所以大很多很正常哈
> 
> 问题是大得不太正常呢，难道你不觉得嘛

正常的 你把图压缩一下就好了

**Comment by zhenzi0322** [comment]
> > > 原图是jpg 3通道有损压缩图片，保存的是png无损压缩图片，所以大很多很正常哈
> > 
> > 
> > 问题是大得不太正常呢，难道你不觉得嘛
> 
> 正常的 你把图压缩一下就好了

压缩后，71MB的大小变成了51MB左右，但是还是这么大，如果放到前端展示的话，那不得卡死了嘛

**Comment by wuyefeilin** [comment]
可以压缩成jpg格式，选择大压缩比

**Comment by zhenzi0322** [comment]
> 可以压缩成jpg格式，选择大压缩比

我已经采用另外的方法处理了
