### ISSUE TITLE
get_pseudo_color_map 函数返回值问题

### ISSUE THREAD

**Issue by srzxDragon** [PaddlePaddle/PaddleSeg#2010]
# basic information
PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
PaddlePaddle version: 2.2.2, PaddleSeg-release-2.4
Operation system: Ubuntu 16.04.7 LTS
Python version: Python 3.7.11
CUDA/cuDNN version: CUDA Version: 10.1
Additional context: (Add any other context about the problem)
# 描述 
in paddleseg/utils/visualize.py
in function def get_pseudo_color_map(pred, color_map=None):
```python
Returns:
        (numpy.ndarray): the pseduo image.
    """
    pred_mask = PILImage.fromarray(pred.astype(np.uint8), mode='P')
    if color_map is None:
        color_map = get_color_map_list(256)
    pred_mask.putpalette(color_map)
    print(type(pred_mask))
    return pred_mask
```
* 函数声称返回值是numpy.ndarray
* 实际上是我打印查看类型发现返回值其实是<class 'PIL.Image.Image'>
![image](https://user-images.githubusercontent.com/87605861/163302717-f1ef774f-cdcc-4962-9fac-dcb687fbaa65.png)

**Comment by haoyuying** [comment]
pred mask在70行已经变成pil.image，我们会更改注释，感谢您的提醒。
