### ISSUE TITLE
[General Issue]  evaluate 的参数eval_dataset为什么要求这个实例化对象具有属性transforms（一个transforms的list）

### ISSUE THREAD

**Issue by anzx2452** [PaddlePaddle/PaddleSeg#2012]
paddleseg.core.evaluate(
        model, 
        **eval_dataset,**             <<---   
        aug_eval = False, 
        scales = 1.0, 
        flip_horizontal = True, 
        flip_vertical = False, 
        is_slide = False, 
        stride = None, 
        crop_size = None, 
        num_workers = 0
)

eval_dataset为什么要求是一个具有有属性transforms（一个transforms的list）的实例化Dataset对象？

我有自己写好的dataset，里面定义好了我的transforms，只是有点复杂，无法写成一个list。我的datset可以正常提供data和label，无法满足验证的需要吗？

代码如下：
```val_dataset = MyDataset(224,7,10)
evaluate(
    segformer_net_1,
    val_dataset)```

报错信息如下
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleseg/core/val.py in evaluate(model, eval_dataset, aug_eval, scales, flip_horizontal, flip_vertical, is_slide, stride, crop_size, num_workers, print_detail, auc_roc)
    118                     im,
    119                     ori_shape=ori_shape,
--> 120                     transforms=eval_dataset.transforms.transforms,
    121                     is_slide=is_slide,
    122                     stride=stride,

AttributeError: 'MyDataset' object has no attribute 'transforms'

**Comment by juncaipeng** [comment]
这个是PaddleSeg的开发规范，为了各部件解耦。你看下你写的预处理是否可以使用PaddleSeg提供的transforms进行替换。
