### ISSUE TITLE
[General Issue]

### ISSUE THREAD

**Issue by zhuangqirong** [PaddlePaddle/PaddleSeg#2015]
EIseg工具生成的文件目录中为什么没有包含autosave_label.txt，eiseg2paddlex.py文件需要这个文件。

**Comment by haoyuying** [comment]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.4/EISeg/docs/tools_cn.md 可参考这个教程进行转换。

**Comment by zhuangqirong** [comment]
> https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.4/EISeg/docs/tools_cn.md可以参考这个教程进行转换。

我是根据这个进行转换的，但是eiseg2paddlex.py文件需要auto_save.txt文件，EIseg标注工具没有自动生成这个文件

**Comment by Adam-lxd** [comment]
遇到同样的问题，看了下`eiseg2paddlex.py`的源代码，在76行-85行是生成`auto_save.txt`文件的，但是文件的打开方式不对（用`w+`模式可以解决） 代码如下
```python
label_path = osp.join(lab_folder, "autosave_label.txt")
    save_label_path = osp.join(save_folder, "labels.txt")
    with open(label_path, "w+") as rf:
        with open(save_label_path, "w+") as wf:
            tmps = rf.readlines()
            wf.write("background\n")
            for i in range(len(tmps)):
                lab = tmps[i].split(" ")[1]
                wf.write(lab + "\n")
    print("===== create label finished! =====")
```

**Comment by smalie2222** [comment]
请问您解决了吗？我也遇到了一样的问题
