### ISSUE TITLE
使用segformer训练自己的数据集时，填了num_classes，却报错缺少num_classes参数

### ISSUE THREAD

**Issue by henryccl** [PaddlePaddle/PaddleSeg#2016]
我在使用segformer训练自己的数据集时，明明填了num_classes，却报错缺少num_classes参数， 怎么会这样？
![image](https://user-images.githubusercontent.com/44051761/163662759-48f0333e-b191-4e0b-ba6b-d812d1a3b08d.png)
![image](https://user-images.githubusercontent.com/44051761/163662802-32bb8ac3-49b2-4c6c-95f6-ba4bace4ad48.png)

**Comment by Winnie202** [comment]
是啊，为什么？解决了吗
