### ISSUE TITLE
[General Issue]用自定义数据集训练pp_liteseg时，AssertionError：The backbone should has feat_channels

### ISSUE THREAD

**Issue by huangwan-jiayi** [PaddlePaddle/PaddleSeg#2017]
![image](https://user-images.githubusercontent.com/71338215/163666359-6eb3bb7d-2dfa-414c-86b4-ed7c7613d996.png)

**Comment by juncaipeng** [comment]
请问你是使用哪个backbone啊？配置yaml文件可以贴出来吗？
