### ISSUE TITLE
请教人像抠图问题

### ISSUE THREAD

**Issue by androidGhost** [PaddlePaddle/PaddleSeg#2028]
人像抠图获取alpha图和原图，有好的方法让原图显示在alpha图的白色区域而其它区域显示透明像素，而不是显示背景图的像素（最终合成的bitmap只保留原图人像部分，其它则是透明的）

**Comment by wuyefeilin** [comment]
预测结果的clip目录下保存的就是这种图片的

**Comment by androidGhost** [comment]
我下载的是安卓部署版本，里面的执行代码是
//将原图与背景按照推理得到的alpha图进行合成
    private Bitmap synthetizeBitmap(Bitmap front,Bitmap background, Bitmap alpha){
        int width = front.getWidth();
        int height = front.getHeight();
        Bitmap result=Bitmap.createBitmap(width,height, Bitmap.Config.ARGB_8888);
        int[] frontPixels = new int[width * height];
        int[] backgroundPixels = new int[width * height];
        int[] alphaPixels = new int[width * height];
        front.getPixels(frontPixels,0,width,0,0,width,height);
        background.getPixels(backgroundPixels,0,width,0,0,width,height);
        alpha.getPixels(alphaPixels,0,width,0,0,width,height);
        float frontA = 0,frontR = 0,frontG = 0,frontB = 0;
        float backgroundR = 0,backgroundG = 0,backgroundB = 0;
        float alphaR = 0,alphaG = 0,alphaB = 0;
        int index=0;

        //逐个像素赋值（这种写法比较耗时，后续可以优化）
        for (int row=0; row < height; row++){
            for (int col=0; col < width; col++){
                index = width*row +col;

                //取出前景图像像素值
                frontA=(frontPixels[index]>>24)&0xff;
                frontR=(frontPixels[index]>>16)&0xff;
                frontG=(frontPixels[index]>>8)&0xff;
                frontB=frontPixels[index]&0xff;

                //取出alpha像素值
                alphaR=(alphaPixels[index]>>16)&0xff;
                alphaG=(alphaPixels[index]>>8)&0xff;
                alphaB=alphaPixels[index]&0xff;

                //取出背景图像像素值
                backgroundR=(backgroundPixels[index]>>16)&0xff;
                backgroundG=(backgroundPixels[index]>>8)&0xff;
                backgroundB=backgroundPixels[index]&0xff;

                //重新合成  ImgOut = F * alpha/255 + BG * ( 1 - alpha/255 )
                frontR= frontR*alphaR/255 + backgroundR*(1-alphaR/255);
                frontG=frontG*alphaG/255 + backgroundG*(1-alphaG/255);
                frontB=frontB*alphaB/255 + backgroundB*(1-alphaB/255);
                frontPixels[index]=(int)frontA<<24|((int)frontR<<16)|((int)frontG<<8)|(int)frontB;
            }
        }
        result.setPixels(frontPixels,0,width,0,0,width,height);;
        return result;
    }

怎样把背景的那部分处理成透明的（不能用透明背景图）

**Comment by Noahs007** [comment]
楼主有找到好方法吗

**Comment by Noahs007** [comment]
我也发现了这个问题，放一张透明图片作为背景合成后会变成黑色。

**Comment by androidGhost** [comment]
我把获取的alpha图片进行颜色滤镜处理，使人像区域和其它区域更加黑白分明（只有黑白两种颜色了），然后遍历原图，判断白色部分取原图人像区域像素，黑色部分设置成透明像素，最后合成图片就是带透明度的人像图了，效果还不错

**Comment by Noahs007** [comment]
可以发一下代码吗 ┭┮﹏┭┮，小红包予以答谢

**Comment by Noahs007** [comment]
只有黑白的话，有些抠成半透明的部分是不是不好处理。

**Comment by androidGhost** [comment]
//将原图与背景按照推理得到的alpha图进行合成，front表示原图
    private Bitmap synthetizeBitmap(Bitmap front, Bitmap alpha) {
        Bitmap bitmap = Bitmap.createBitmap(alpha.getWidth(), alpha.getHeight(), Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bitmap);
        Paint paint = new Paint();
        ColorMatrix colorMatrix = new ColorMatrix();
        float value = 2f;
        float brightness = 255 * 100 / 100 * (1f - value);
        colorMatrix.set(new float[]{
                value, 0, 0, 0, brightness,
                0, value, 0, 0, brightness,
                0, 0, value, 0, brightness,
                0, 0, 0, 1, 0});
        paint.setColorFilter(new ColorMatrixColorFilter(colorMatrix));
        canvas.drawBitmap(alpha, 0, 0, paint);

        int width = front.getWidth();
        int height = front.getHeight();
        Bitmap result = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888);
        int[] frontPixels = new int[width * height];
        int[] alphaPixels = new int[width * height];
        int[] resultPixels = new int[width * height];
        front.getPixels(frontPixels, 0, width, 0, 0, width, height);
        bitmap.getPixels(alphaPixels, 0, width, 0, 0, width, height);
        int index = 0;

        //逐个像素赋值（这种写法比较耗时，后续可以优化）
        for (int row = 0; row < height; row++) {
            for (int col = 0; col < width; col++) {
                index = width * row + col;
                if (alphaPixels[index] == Color.BLACK) {
                    resultPixels[index] = Color.TRANSPARENT;
                } else {
                    resultPixels[index] = frontPixels[index];
                }
            }
        }
        result.setPixels(resultPixels, 0, width, 0, 0, width, height);
        return result;
    }

这是里面原有的代码进行的修改，处理后的结果会比demo的效果差一些，我们自己的项目增加了手动抠图和恢复，所以抠出来的效果用户可以自行调整

**Comment by androidGhost** [comment]
你可以自己测试一下，反正进行手动抠图的话基本就是头发丝部分需要稍微调整而已，比之前一些开源的sdk效果要好很多

**Comment by Noahs007** [comment]
感谢大佬，给个收款码请你喝咖啡吧

**Comment by androidGhost** [comment]
不用了，小事

**Comment by Noahs007** [comment]
👍🏻

**Comment by badboy-tian** [comment]
@androidGhost 这个方法比原来的确实要好的多 但是边缘还是有锯齿  大佬有啥解决方案吗？
![d9618e178e60e482535da401a062448](https://user-images.githubusercontent.com/2835129/220837191-5bad2955-cadc-46b4-8ee0-66fd7387e471.jpg)

原图：
![fa76745ea1f372fcb460c54a5e3fefe](https://user-images.githubusercontent.com/2835129/220837214-5392a055-b088-4960-916e-494223da98e4.jpg)

**Comment by badboy-tian** [comment]
![3645199d11f82c15543b677018131e3](https://user-images.githubusercontent.com/2835129/220837316-e34889fc-77dd-4609-9750-45e90286fdb8.jpg)
mask是这样的
