### ISSUE TITLE
panoptic deeplab训练问题

### ISSUE THREAD

**Issue by Invisible2733** [PaddlePaddle/PaddleSeg#2032]
采用CPU训练过程如下：
![image](https://user-images.githubusercontent.com/70048885/164025957-12622107-a93a-4b22-9814-7854dd47d405.png)
output中只有如图所示的两个文件：
![image](https://user-images.githubusercontent.com/70048885/164026283-1e8fdd2c-3d84-499f-8914-ce5a99365cb5.png)
请问下这是什么问题呢？要如何解决

**Comment by wuyefeilin** [comment]
model.pdparams就是训练得到的模型参数

**Comment by Invisible2733** [comment]
请问下如何查看这个参数呢？数据集为Cityscapes，训练结果只有这两个文件吗
