### ISSUE TITLE
 怎么对Matting模型静态离线量化和量化训练？

### ISSUE THREAD

**Issue by linyucion** [PaddlePaddle/PaddleSeg#2034]
platform: Linux-4.13.0-36-generic-x86_64-with-debian-stretch-sid
Python: 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
Paddle compiled with cuda: True
NVCC: Cuda compilation tools, release 10.1, V10.1.243
cudnn: 7.6
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: Tesla V100-SXM2-16GB']
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
PaddleSeg: 2.4.0
PaddlePaddle: 2.2.2
OpenCV: 4.1.1

我尝试官方的文档进行操作，但我已经万策尽了，动态离线量化倒是能弄出来。

 ### 1.自己测试的量化训练： 
modnet_mobilenetv2_quant.yml参考modnet_mobilenetv2.yml的
只加了
------------------
loss:
  types:
    - type: CrossEntropyLoss
  coef: [1, 1, 1, 1, 1]
------------------
modnet_mobilenetv2_quant.yml中train_dataset的train.txt的数量减少些

（当前目录/home/aistudio/PaddleSeg-release-2.4/contrib/Matting） 在官方的aistudio中弄的
python3.7 /home/aistudio/PaddleSeg-release-2.4/slim/quant/qat_train.py     \
       --config configs/modnet/modnet_mobilenetv2_quant.yml   \
       --model_path output/export/model.pdiparams  \
       --learning_rate 0.001  \
       --do_eval    \
       --use_vdl   \ 
       --save_interval 250   \
       --save_dir output_quant

会报
Traceback (most recent call last):
  File "/home/aistudio/PaddleSeg-release-2.4/slim/quant/qat_train.py", line 206, in <module>
    main(args)
  File "/home/aistudio/PaddleSeg-release-2.4/slim/quant/qat_train.py", line 169, in main
    losses = cfg.loss
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleseg/cvlibs/config.py", line 241, in loss
    self._losses = self._prepare_loss('loss')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleseg/cvlibs/config.py", line 286, in _prepare_loss
    self.train_dataset.ignore_index
AttributeError: 'MattingDataset' object has no attribute 'ignore_index'

**我不知道ignore_index用什么格式，以及怎么加上去= =**

modnet_mobilenetv2_quant.yml里改成不用ignore_index的MixedLoss  （源码里看的）
loss:
  types:
    - type: MixedLoss
  coef: [1, 1, 1, 1, 1]

执行后就会报下面的错误
------------------------------------------------
Traceback (most recent call last):
  File "/home/aistudio/PaddleSeg-release-2.4/slim/quant/qat_train.py", line 206, in <module>
    main(args)
  File "/home/aistudio/PaddleSeg-release-2.4/slim/quant/qat_train.py", line 169, in main
    losses = cfg.loss
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleseg/cvlibs/config.py", line 241, in loss
    self._losses = self._prepare_loss('loss')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleseg/cvlibs/config.py", line 272, in _prepare_loss
    'Loss config should contain keys of "types" and "coef"')
ValueError: Loss config should contain keys of "types" and "coef"

### 2.自己测试的静态离线量化
      quant_post_static.py 
---------------------------------------------------------------------------------------------
import os
import sys
import logging
import paddle
import argparse
import functools
import math
import time
import random
import numpy as np
import paddle

sys.path[0] = os.path.join(
    os.path.dirname("__file__"), os.path.pardir, os.path.pardir)
sys.path.append('/home/aistudio/PaddleSeg-release-2.4/contrib/Matting/')
sys.path.append('/home/aistudio/PaddleSeg-release-2.4/contrib/Matting/dataset/')
from paddleslim.common import get_logger
from paddleslim.quant import quant_post_static
#from utility import add_arguments, print_arguments
#import imagenet_reader as reader

from paddleseg.cvlibs import manager, Config
from matting_dataset import MattingDataset

_logger = get_logger(__name__, level=logging.INFO)

parser = argparse.ArgumentParser(description=__doc__)

def quantize(args):
    shuffle = True
    '''
    if args.ce_test:
        # set seed
        seed = 111
        np.random.seed(seed)
        paddle.seed(seed)
        random.seed(seed)
        shuffle = False
    '''
    place = paddle.CUDAPlace(0) if args.use_gpu else paddle.CPUPlace()

    cfg = Config(
        "/home/aistudio/PaddleSeg-release-2.4/contrib/Matting/configs/modnet/modnet_mobilenetv2_quant.yml",
        learning_rate=None,
        iters=None,
        batch_size=None)
    val_dataset = cfg.train_dataset

    #image_shape = [3, 224, 224]
    image_shape = [3, 512, 512]
    image = paddle.static.data(
        name=args.input_name, shape=[None] + image_shape, dtype='float32')
    data_loader = paddle.io.DataLoader(
        val_dataset,
        places=place,
        feed_list=[image],
        drop_last=False,
        return_list=False,
        batch_size=args.batch_size,
        shuffle=False)

    assert os.path.exists(args.model_path), "args.model_path doesn't exist"
    assert os.path.isdir(args.model_path), "args.model_path must be a dir"

    exe = paddle.static.Executor(place)
    quant_post_static(
        executor=exe,
        model_dir=args.model_path,
        quantize_model_path=args.save_path,
        data_loader=data_loader,
        model_filename=args.model_filename,
        params_filename=args.params_filename,
        batch_size=args.batch_size,
        batch_nums=args.batch_num,
        algo=args.algo,
        hist_percent=args.hist_percent,
        is_full_quantize=args.is_full_quantize,
        bias_correction=args.bias_correction,
        )
def main():
    args = parser.parse_args()
    
    args.batch_size=16
    args.batch_num=1
    args.use_gpu=False
    args.use_gpu=True
    args.model_path="./output/export"
    args.save_path="./quant_model/MobileNet/"
    args.model_filename="model.pdmodel"
    args.params_filename="model.pdiparams"
    args.algo='hist'
    args.round_type='round'
    args.hist_percent=0.9999
    args.is_full_quantize=False
    args.bias_correction=False
    args.ce_test=False
    args.onnx_format=False
    args.input_name='inputs'
    quantize(args)
if __name__ == '__main__':
    paddle.enable_static()
    main()
---------------------------------------------------------------------------------------------------------------

**执行后出现**

W0420 16:19:48.368535 10842 device_context.cc:465] device: 0, cuDNN Version: 7.6.
Wed Apr 20 16:19:51-INFO: Collect quantized variable names ...
Wed Apr 20 16:19:51-INFO: Preparation stage ...
Traceback (most recent call last):
  File "quant_post_static.py", line 165, in <module>
    main()
  File "quant_post_static.py", line 159, in main
    quantize(args)
  File "quant_post_static.py", line 129, in quantize
    bias_correction=args.bias_correction,
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/quant/quanter.py", line 422, in quant_post_static
    post_training_quantization.quantize()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/slim/quantization/post_training_quantization.py", line 374, in quantize
    for data in self._data_loader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 273, in __next__
    data = self._reader.read_next()
ValueError: (InvalidArgument) The sample number of reader's input data and the input number of feed list are not equal.
Possible reasons are:
  The generator is decorated by `paddle.batch` and configured by `set_batch_generator`, but here need to used `set_sample_list_generator`.
  [Hint: Expected names_.size() == ret_[i].size(), but received names_.size():1 != ret_[i].size():5.] (at /paddle/paddle/fluid/pybind/reader_py.cc:200)

**Comment by wuyefeilin** [comment]
目前Matting暂时不支持量化功能，如果你需要量化操作需要参考官方文档自行进行实现（https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/paddleslim/paddle_slim_cn.html）。
后续我们会增加量化功能以方便用户直接使用。
