### ISSUE TITLE
训练报错 “train() got an unexpected keyword argument 'fp16'”

### ISSUE THREAD

**Issue by xinliyangguang** [PaddlePaddle/PaddleSeg#2035]
欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：PaddleSeg release/2.3
 2. PaddlePaddle版本：2.2.0
 3. 操作系统信息：linux
 4. Python版本号：python3.7
 5. CUDA/cuDNN版本：CUDA11.2
 6. 其他内容: requirment.txt和paddleseg都是提交到paddlecloud之后再安装的；试过多个模型都报这个错：ocrnet，deeplab，stdc1等，在windows上验证发现可以正常运行，应该不是数据的问题，且又用之前跑成功之后的数据进行重跑，也报了这个错误

在paddlecloud上训练报如下错误，定位到代码并没有异常，没有动过train.py
![QQ截图20220421165410](https://user-images.githubusercontent.com/53338761/164418494-a744d600-2f79-4547-8101-069ad670df8f.png)
![QQ截图20220421165438](https://user-images.githubusercontent.com/53338761/164418504-2b3c4b0f-0fa2-42be-91a7-a37cd860afb3.png)

训练脚本：
![image](https://user-images.githubusercontent.com/53338761/164417127-1094b57b-ce7d-4e7d-a9c4-b2b81a433312.png)
参数配置：

![image](https://user-images.githubusercontent.com/53338761/164417290-35223660-2882-415a-ab11-2f5f37e87aa6.png)
![image](https://user-images.githubusercontent.com/53338761/164417441-73327524-003c-46d5-8233-8dc6d48afeef.png)

**Comment by haoyuying** [comment]
可以打印下args.fp16是什么，要求为bool类型，core文件夹下的train.py传入参数是否有fp16

**Comment by xinliyangguang** [comment]
> 可以打印下args.fp16是什么，要求为bool类型，core文件夹下的train.py传入参数是否有fp16

打印出来是False，看了core下的train.py
![image](https://user-images.githubusercontent.com/53338761/164432859-ced18e5f-51bc-46e7-a73a-3957b332a67d.png)

**Comment by xinliyangguang** [comment]
> 可以打印下args.fp16是什么，要求为bool类型，core文件夹下的train.py传入参数是否有fp16

近期是不是在更新paddleseg呀？我跑ppliteseg网络也是会报paddleseg包有关的错误
