### ISSUE TITLE
[General Issue]PP-Matting

### ISSUE THREAD

**Issue by startdabin** [PaddlePaddle/PaddleSeg#2040]
你好， PP-Matting的configs文件还没有更新上来吗？

**Comment by suofer** [comment]
Hello, dose the PP-Matting code has been updated? I cannot find it.

**Comment by hackkhai** [comment]
They have shared only the inference weights, which is a zip which contains deploy.yaml as config which you can rub by using the file deploy/python/infer.py

**Comment by wuyefeilin** [comment]
> They have shared only the inference weights, which is a zip which contains deploy.yaml as config which you can rub by using the file deploy/python/infer.py

Yes， he is right. @startdabin You can use the inference model to predict you images directly.

**Comment by hackkhai** [comment]
Any update on releasing the training code anytime soon?

**Comment by wuyefeilin** [comment]
Coming soon.

**Comment by tarunn2799** [comment]
Hey any update on releasing the training code for PP Matting?

**Comment by wuyefeilin** [comment]
It will be release in 2.6 version.
