### ISSUE TITLE
FatalError: `Segmentation fault` is detected by the operating system.

### ISSUE THREAD

**Issue by mohamedAkif** [PaddlePaddle/PaddleSeg#2041]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.2.2)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.7)
 5. CUDA/cuDNN version: (e.g. CUDA11.1/cuDNN 7.6)
 6. Additional context: (Add any other context about the problem)

I've been trying to train my custom model using GPU version in google colab but this error shows up;

ERROR LOG:
------------Environment Information-------------
platform: Linux-5.4.144+-x86_64-with-Ubuntu-18.04-bionic
Python: 3.7.13 (default, Mar 16 2022, 17:37:17) [GCC 7.5.0]
Paddle compiled with cuda: True
NVCC: Cuda compilation tools, release 10.2, V10.2.89
cudnn: 7.6
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: Tesla T4']
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PaddleSeg: 2.5.0
PaddlePaddle: 2.2.2
OpenCV: 4.1.2
------------------------------------------------
2022-04-22 13:22:45 [INFO]	
---------------Config Information---------------
batch_size: 1
iters: 1000
loss:
  coef:
  - 1
  - 1
  - 1
  - 1
  - 1
  types:
  - ignore_index: 255
    type: CrossEntropyLoss
lr_scheduler:
  end_lr: 0
  learning_rate: 0.01
  power: 0.9
  type: PolynomialDecay
model:
  pretrained: null
  type: UNet
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 4.0e-05
train_dataset:
  dataset_root: /gdrive/MyDrive/OPG_dataset_2
  mode: train
  num_classes: 12
  train_path: /gdrive/MyDrive/OPG_dataset_2/train.txt
  transforms:
  - type: RandomHorizontalFlip
  - type: Normalize
  - target_size:
    - 1280
    - 2440
    type: Resize
  type: Dataset
val_dataset:
  dataset_root: /gdrive/MyDrive/OPG_dataset_2
  mode: val
  num_classes: 12
  transforms:
  - type: Normalize
  - target_size:
    - 1280
    - 2440
    type: Resize
  type: Dataset
  val_path: /gdrive/MyDrive/OPG_dataset_2/val.txt
------------------------------------------------
W0422 13:22:45.770524 15361 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 10.2
W0422 13:22:45.770563 15361 device_context.cc:465] device: 0, cuDNN Version: 7.6.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
1   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, paddle::platform::Place const&, bool, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
2   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap const&, paddle::framework::AttributeMap const&)
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::ActivationCudaKernel<paddle::platform::CUDADeviceContext, paddle::operators::CudaReluFunctor<float> >, paddle::operators::ActivationCudaKernel<paddle::platform::CUDADeviceContext, paddle::operators::CudaReluFunctor<double> >, paddle::operators::ActivationCudaKernel<paddle::platform::CUDADeviceContext, paddle::operators::CudaReluFunctor<paddle::platform::float16> >, paddle::operators::ActivationCudaKernel<paddle::platform::CUDADeviceContext, paddle::operators::CudaReluFunctor<paddle::platform::bfloat16> > >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   paddle::framework::Tensor::mutable_data(paddle::platform::Place const&, paddle::framework::proto::VarType_Type, unsigned long)
5   paddle::memory::AllocShared(paddle::platform::Place const&, unsigned long)
6   paddle::memory::allocation::AllocatorFacade::AllocShared(paddle::platform::Place const&, unsigned long)
7   paddle::memory::allocation::AllocatorFacade::Alloc(paddle::platform::Place const&, unsigned long)
8   paddle::memory::allocation::RetryAllocator::AllocateImpl(unsigned long)
9   paddle::memory::allocation::AutoGrowthBestFitAllocator::FreeIdleChunks()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1650633769 (unix time) try "date -d @1650633769" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x607087239) received by PID 15361 (TID 0x7fc01c15e780) from PID 117994041 ***]

INFO 2022-04-22 13:22:54,305 launch_utils.py:341] terminate all the procs
ERROR 2022-04-22 13:22:54,306 launch_utils.py:604] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2022-04-22 13:22:58,310 launch_utils.py:341] terminate all the procs
INFO 2022-04-22 13:22:58,310 launch.py:311] Local processes completed.

**Comment by juncaipeng** [comment]
I can not find the special error by your log.  Maybe the error is the installlation.
Please first run the demo to verify PaddleSeg installation: https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/docs/install.md

**Comment by mohamedAkif** [comment]
Yes, demo is working fine, got output of the optic nerve bisenet model predictions

**Comment by Wulx2050** [comment]
> Yes, demo is working fine, got output of the optic nerve bisenet model predictions

我尝试在kaggle上使用PaddleSeg也报了这个错。这个demo也报错。是因为CUDA版本和paddlepaddle不匹配。
https://github.com/PaddlePaddle/PaddleSeg/issues/1073

```
# 查看 CUDA版本 
!nvcc -V
# kaggle 目前是 11.0，   .post110
!pip install paddlepaddle-gpu==2.3.0.post110 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
```
其他版本安装命令参考：
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html

这个报错与PaddleSeg没关系

**Comment by Wulx2050** [comment]
赶紧支持高版本的cudnn

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0
```
