### ISSUE TITLE
API如何使用多卡训练，目前只找到配置化调用的方式

### ISSUE THREAD

**Issue by caj-github** [PaddlePaddle/PaddleSeg#2042]
API如何使用多卡训练，目前只找到配置化调用的方式

**Comment by juncaipeng** [comment]
api 调用多卡训练会比较麻烦，需要自己把控细节，具体可以参考代码：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/paddleseg/core/train.py

**Comment by caj-github** [comment]
我调用的就是这个tain函数来训练，我看里面存在读取环境变量判断是否使用多卡，那么要通过API使用单机多卡的话，是否可以通过设置环境变量来完成，还是说不能使用这个训练函数，必须自己实现？

**Comment by juncaipeng** [comment]
可以, export CUDA_VISIBLE_DEVICES=1,2,3 设置使用多卡

**Comment by caj-github** [comment]
设置了没有用，用spawn启动可以了，但是单卡导出onnx正常，多GPU训练后的模型导出onnx报错，There's 1 ops are not supported yet，sync_batch_norm

**Comment by juncaipeng** [comment]
一般导出为预测模型后  sync_batch_norm会变为batch_nrom啊，估计需要转换为单卡再导出
