### ISSUE TITLE
[Question]  ICNet

### ISSUE THREAD

**Issue by yanni1995** [PaddlePaddle/PaddleSeg#2046]
模型库中没有提供关于ICNet的网络模型

**Comment by juncaipeng** [comment]
这个模型没有复现，建议使用PP-LiteSeg、BiSeNetV2等，这些新的模型速度更快，精度更高。

**Comment by yanni1995** [comment]
> 这个模型没有复现，建议使用PP-LiteSeg、BiSeNetV2等，这些新的模型速度更快，精度更高。

这边有复现计划吗

**Comment by juncaipeng** [comment]
模型太老了，应该不会复现。
