### ISSUE TITLE
predict 输出 FileNotFoundError: there is not `dataset_root`

### ISSUE THREAD

**Issue by pythondever** [PaddlePaddle/PaddleSeg#2052]
1. PaddleSeg version: 2.3
 2. PaddlePaddle version: PaddlePaddle 2.1.0
 3. Operation system: Windows
 4. Python version: Python3.8
 5. CUDA/cuDNN version: 没有使用gpu
我训练了一个FCN的模型(Linux平台训练),但是当我跑预测时(Windows平台预测)遇到了报错, 
Traceback (most recent call last):
  File "predict.py", line 175, in <module>
    main(args)
  File "predict.py", line 144, in main
    val_dataset = cfg.val_dataset
  File "D:\code\pp-seg\paddleseg\cvlibs\config.py", line 351, in val_dataset
    return self._load_object(_val_dataset)
  File "D:\code\pp-seg\paddleseg\cvlibs\config.py", line 385, in _load_object
    return component(**params)
  File "D:\code\pp-seg\paddleseg\datasets\dataset.py", line 92, in __init__
    raise FileNotFoundError('there is not `dataset_root`: {}.'.format(
FileNotFoundError: there is not `dataset_root`: /data2/seg/custom_dataset.
---

**Comment by shiyutang** [comment]
The path you assign does not exit:
<img width="635" alt="image" src="https://user-images.githubusercontent.com/34859558/165473663-fb0a0d35-1e41-4b8b-9fc2-0a91dcb47d42.png">

**Comment by pythondever** [comment]
> The path you assign does not exit: <img alt="image" width="635" src="https://user-images.githubusercontent.com/34859558/165473663-fb0a0d35-1e41-4b8b-9fc2-0a91dcb47d42.png">

但是跑预测为啥要去检查训练集路径 dataset_root呢?
