### ISSUE TITLE
Matting 的那个512 ，1024模型导出 onnx 出错请问是什么原因啊

### ISSUE THREAD

**Issue by beyonehan** [PaddlePaddle/PaddleSeg#2055]
<img width="1297" alt="截屏2022-04-26 下午10 41 37" src="https://user-images.githubusercontent.com/19468927/165327484-9873dc18-628d-4339-ba7e-156294e631b9.png">

**Comment by wuyefeilin** [comment]
在转换的时候指定固定输入的shape试试，比如
paddle2onnx --model_dir inference/ --model_filename model.pdmodel --params_filename model.pdiparams --save_file model.onnx --input_shape_dict="{'x':[1,3,512,512]}"
其中'x'实模型的输入tensor名
