### ISSUE TITLE
[Bug]release/2.5的matting导出的静态图模型转paddle-lite模型转不了

### ISSUE THREAD

**Issue by dragonwarrior95** [PaddlePaddle/PaddleSeg#2058]
详细信息在这：https://aistudio.baidu.com/aistudio/projectdetail/3895346
1、转paddlejs模型
paddlejsconverter --modelPath=./pp-humanmatting-resnet34_vd/model.pdmodel --paramPath=./pp-humanmatting-resnet34_vd/model.pdiparams --outputDir=./jsmodel --useGPUOpt=False
2、转paddle-lite模型
paddle_lite_opt --model_file=./pp-humanmatting-resnet34_vd/model.pdmodel --param_file=./pp-humanmatting-resnet34_vd/model.pdiparams --valid_targets=x86 --optimize_out=./pp-humanmatting-resnet34_vd_opt
两个转都不成功，
另外macstudio跑paddle_lite_opt会崩溃，不知是m1兼容性问题还是？

**Comment by wuyefeilin** [comment]
在linux环境下通过下面的命令是可以转换的
`paddle_lite_opt --model_dir save_models/exports/pp-humanmatting-resnet34_vd --optimize_out output/paddlelite/modnet_mobilenetv2_opt`
在aistudio看样子是有些算子不支持
![image](https://user-images.githubusercontent.com/30919197/165673364-031974d6-aefc-41e2-b92f-6d193160cf32.png)

paddlejs看样子是因为需要指定输入的shape， 你可以重新导出一下模型，指定输入的shape试试
![image](https://user-images.githubusercontent.com/30919197/165688919-882f856c-d89d-450a-a761-92e7785c4698.png)

**Comment by dragonwarrior95** [comment]
> 

指定输入Shape是哪里指定？求详细解答一下？

**Comment by wuyefeilin** [comment]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/Matting/export.py#L56 传入具体的shape信息试试
