### ISSUE TITLE
images图像如果通道数只有1怎么办？另外可以用CPU训练吗？

### ISSUE THREAD

**Issue by applepieiris** [PaddlePaddle/PaddleSeg#2061]
images文件夹存放原图（通道数为3），labels文件夹存放标注图像（通道数为1），train.txt、val.txt、test.txt指定训练集、验证集和测试集。
以上是文档内写的，但是我的images只是灰度图，所以怎么去修改呢？还是说我要把图片再转化一遍？
还有文档中提到用单卡训练，请问CPU资源可以训练吗？

**Comment by haoyuying** [comment]
image不需要修改，cv2读取灰度图会自动转化成3通道。
cpu可以在这里设置：https://github.com/PaddlePaddle/PaddleSeg/blob/457af2edb51a3c85ac9fd019e564c4099b1ee8bd/train.py#L130

**Comment by applepieiris** [comment]
好的，谢谢。我的mask也就是Label是单通道的图片，看到一个issue是要变化成0,1,2,3的图，请问有具体的文档说明如何定制训练数据吗？我看到readme中写data的生成有点简略。
