### ISSUE TITLE
add web demo/model to Huggingface

### ISSUE THREAD

**Issue by AK391** [PaddlePaddle/PaddleSeg#2065]
Hi, would you be interested in adding PaddleSeg to Hugging Face? The Hub offers free hosting, and it would make your work more accessible and visible to the rest of the ML community. Models/datasets/spaces(web demos) can be added to a user account or organization similar to github.

There is already a PaddlePaddle Organization on Hugging Face similar to Github with spaces: https://huggingface.co/PaddlePaddle

Example spaces with repos:
github: https://github.com/salesforce/BLIP
Spaces: https://huggingface.co/spaces/salesforce/BLIP

github: https://github.com/facebookresearch/omnivore
Spaces: https://huggingface.co/spaces/akhaliq/omnivore

and here are guides for adding spaces/models/datasets to your org

How to add a Space: https://huggingface.co/blog/gradio-spaces
how to add models: https://huggingface.co/docs/hub/adding-a-model
uploading a dataset: https://huggingface.co/docs/datasets/upload_dataset.html

Please let us know if you would be interested and if you have any questions, we can also help with the technical implementation.

**Comment by michaelowenliu** [comment]
@AK391 Hi, thanks for your kind invitation. What can we do to help you?

**Comment by AK391** [comment]
@michaelowenliu It would be great to have the models for paddleseg hosted on Huggingface with Gradio demos, the paddlehub github for example already links to many gradio demos for models https://github.com/PaddlePaddle/PaddleHub/tree/release/v2.2/modules
