### ISSUE TITLE
用medicalseg训练自己自己数据集时出现了问题

### ISSUE THREAD

**Issue by 1640477469** [PaddlePaddle/PaddleSeg#2067]
你好：
我按照tutorial_cn.md一步步操作，在5.3 增加数据集文件的时候就报错了，
![image](https://user-images.githubusercontent.com/98088542/165870874-339eba32-8d28-44b9-a3f1-7feb66015e8e.png)
转换好的数据集文件夹和要求的也一样：
![image](https://user-images.githubusercontent.com/98088542/165870957-64a85c94-f3b4-4191-82ad-f21c4fbe0a00.png)
如果不进行这一步，直接运行的话会出现如下问题：
![image](https://user-images.githubusercontent.com/98088542/165871766-4a9b6243-a001-49a3-8dc9-8399fbd8e06a.png)
我的配置文件修改是这样的，改了数据集地址，没有修改type，这样改是不对吗？：
![image](https://user-images.githubusercontent.com/98088542/165871858-7e5e5d0f-f71b-44e1-9603-0c6c8dcb95c5.png)

求帮忙解答。。。

**Comment by shiyutang** [comment]
嗯嗯，数据集的type就要对应新建dataset.py里面对应的类（这个类的名字根据你自己的数据集重新命名，RibFrac），你这个主要问题：
1. 没有更新 dataset.py 中类的名字，而是使用LungCoronavirus
2. 没有更新配置文件中type名字
3. 数据集中 item 只有一个数值，但是却需要获得img和label

**Comment by 1640477469** [comment]
> 
你好，我现在是可以开始训练了（没有进行tutorial_cn.md种5.3的操作 ），但是结果很差。0是背景，1，2，3，4，5是类别，训练dice提升h很小，这种情况还要继续训练吗？
![image](https://user-images.githubusercontent.com/98088542/166860805-9148db96-5992-4daa-977b-12f7eae85362.png)
![image](https://user-images.githubusercontent.com/98088542/166860795-2e15e2a9-9b98-4a4c-9f60-9f241c860797.png)

**Comment by shiyutang** [comment]
Can you reproduce the result on the lung_coronavirus dataset?
If yes, The data you provide seems to be very imbalanced, try to 1. add weight on Cross Entropy loss,  2.augment your data.
If no, try to reproduce the original result first.
