### ISSUE TITLE
训练一段时间报错退出

### ISSUE THREAD

**Issue by lifucong** [PaddlePaddle/PaddleSeg#2069]
我使用的deeplabv3 自建的数据集合，训练一段时间后报这个问题
python train.py                --config configs/deeplabv3/deeplabv3_resnet50_os8_voc12aug_512x512_40k.yml        --do_eval                --use_vdl        --save_interval 500        --save_dir output
ValueError: The size of image should be less than `target_size`, but the size of image (368, 640) is larger than `target_size` (512, 512)
以下是我的配置
batch_size: 4
iters: 10000

train_dataset:
  type: Dataset
  num_classes: 3
  #dataset_root: data/VOCdevkit/
  dataset_root: data/shuiwei/
  train_path: data/shuiwei/train.txt
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  num_classes: 3
  #dataset_root: data/VOCdevkit/
  dataset_root: data/shuiwei/
  val_path: data/shuiwei/train.txt
  transforms:
    - type: Padding
      target_size: [512, 512]
    - type: Normalize
  mode: val

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]

_base_: './pascal_voc12.yml'

train_dataset:
  #mode: trainaug
  mode: train

_base_: '../_base_/pascal_voc12aug.yml'

model:
  type: DeepLabV3
  backbone:
    type: ResNet50_vd
    output_stride: 8
    multi_grid: [1, 2, 4]
    # pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
    pretrained: /root/.paddleseg/pretrained_model/resnet50_vd_ssld_v2_imagenet/model.pdparams
  backbone_indices: [3]
  aspp_ratios: [1, 12, 24, 36]
  aspp_out_channels: 256
  align_corners: False
  pretrained: null

![image](https://user-images.githubusercontent.com/5683025/165877945-47c84e95-e7a2-4425-912c-a9e5e241359b.png)

**Comment by juncaipeng** [comment]
你需要知道你训练和测试数据集中图片的尺寸。

如下测试数据集的配置文件中，由于图片尺寸超过512，导致你使用padding到512时出现错误，建议删掉Padding这个预处理操作。

```
val_dataset:
type: Dataset
num_classes: 3
#dataset_root: data/VOCdevkit/
dataset_root: data/shuiwei/
val_path: data/shuiwei/train.txt
transforms:
- type: Padding
target_size: [512, 512]
- type: Normalize
mode: val
```
