### ISSUE TITLE
请问视频级别人像分割大概什么时候上线

### ISSUE THREAD

**Issue by lesterhnu** [PaddlePaddle/PaddleSeg#207]
![image](https://user-images.githubusercontent.com/42615458/77625276-43aa0600-6f7e-11ea-8f67-407a6842da13.png)

**Comment by ZeyuChen** [comment]
@lesterhnu   会在PaddleSeg 0.5.0版本推出视频级别实时人像分割模型，发版时间预计在4月中下旬。

**Comment by lesterhnu** [comment]
你好请问新版本 0.5.0有没有发布时间表

**Comment by nepeplwu** [comment]
@lesterhnu 目前最新版本为0.6.0，视频人像分割的教程可以参考[教程](https://github.com/PaddlePaddle/PaddleSeg/tree/release/v0.6.0/contrib/HumanSeg#%E5%BF%AB%E9%80%9F%E4%BD%93%E9%AA%8C%E8%A7%86%E9%A2%91%E6%B5%81%E4%BA%BA%E5%83%8F%E5%88%86%E5%89%B2)
