### ISSUE TITLE
在自定义训练集上表现很不好，是什么原因呢？

### ISSUE THREAD

**Issue by applepieiris** [PaddlePaddle/PaddleSeg#2071]
`
2022-04-29 09:06:31 [INFO]      [EVAL] #Images: 200 mIoU: 0.4965 Acc: 0.9867 Kappa: 0.0122 Dice: 0.5030 
2022-04-29 09:06:31 [INFO]      [EVAL] Class IoU: 
[0.9867 0.0063]
2022-04-29 09:06:31 [INFO]      [EVAL] Class Precision: 
[0.9868 0.4374]
2022-04-29 09:06:31 [INFO]      [EVAL] Class Recall: 
[0.9999 0.0064]
`
以上是我的数据集在val上的表现，class one是背景，class 2是mask，也就是label.我已经将label的图片整理成了你们数据要求的从0开始的类别，也就是背景pixel做成了0，mask的pixel做成了1。其余没有其他值，在yml配置文件中我也将num_classes=2了。resize=(512,512)保持默认配置，配置文件中其他都没做变化，只是把train和val的数据集的根目录修改成我的数据集路径了。
我的数据集train 800张，val 200张。inter= 1000，batch_size没有在命令行中指定。请问是什么地方出了问题？

**Comment by juncaipeng** [comment]
你看下batch-size是多少，可以适当增加训练轮数iters。
从log来看，你的数据集中背景和目标类别不均衡吧，很多像素都预测成背景和。 建议你改下yaml文件，尝试使用加权CE loss，比如。
![image](https://user-images.githubusercontent.com/52520497/166859067-d76f162d-821c-4393-b71a-fc15c03ff90e.png)

**Comment by applepieiris** [comment]
> 你看下batch-size是多少，可以适当增加训练轮数iters。 从log来看，你的数据集中背景和目标类别不均衡吧，很多像素都预测成背景和。 建议你改下yaml文件，尝试使用加权CE loss，比如。 ![image](https://user-images.githubusercontent.com/52520497/166859067-d76f162d-821c-4393-b71a-fc15c03ff90e.png)

batch_size=20, 背景和目标类别不均衡的意思是：图片中是背景的pixel太多了，是object的像素太少了？

**Comment by juncaipeng** [comment]
对的

**Comment by Suzi1213** [comment]
> `2022-04-29 09:06:31 [INFO] [EVAL] #Images: 200 mIoU: 0.4965 Acc: 0.9867 Kappa: 0.0122 Dice: 0.5030 2022-04-29 09:06:31 [INFO] [EVAL] Class IoU: [0.9867 0.0063] 2022-04-29 09:06:31 [INFO] [EVAL] Class Precision: [0.9868 0.4374] 2022-04-29 09:06:31 [INFO] [EVAL] Class Recall: [0.9999 0.0064]` 以上是我在val上的数据集的表现，第一类是背景，第二类是面具，也就是标签。已经将标签的图片整理成我的数据要求从0的类别，也就是背景像素做(512,512，配置文件做变化，把配置文件中的其他值设置为1。 train 和val 的数据集的根成我的数据集路径。 我的数据集train 800 张，val 200 张。inter=1000，batch_size 没有在数据组中修改指定的问题。请问是什么地方查找问题？

您好，我目前的二分类的图像分割跑不起来，如果可以的话，可不可以请教点问题。

**Comment by juncaipeng** [comment]
可以参考seg文档学习一下，然后也可以在issue中详细写明你的问题。

**Comment by Suzi1213** [comment]
> 可以参考seg文档学习一下，然后也可以在issue中详细写明你的问题。

我最终预测的结果是一张纯色的图，并没有把我需要的东西分割出来（二分类），是怎么回事？

**Comment by juncaipeng** [comment]
具体查看训练log进行分析。。还有就是显示出来的结果，可能人眼无法查看。。 建议参考seg文档系统熟悉。
