### ISSUE TITLE
[General Issue] 多卡训练参数问题

### ISSUE THREAD

**Issue by AP-Kai** [PaddlePaddle/PaddleSeg#2074]
欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：PaddleSeg release/2.5
 2.平台： AI Studio 单机四卡 V100 *4

您好，我在使用Seg套件的多卡训练中遇到了问题，多卡训练的参数相当于单卡训练的参数应该如何调整？

比如在Paddle Seg的单卡训练中：batch_size 2,  iters 80000, lr 0.001  。如果要调整到四卡训练，这三个参数应该怎么变化呢，或者其它的参数也要变化？

**Comment by juncaipeng** [comment]
单卡训练中：batch_size 2, iters 80000, lr 0.001 
四卡训练改为： batch_size 2, iters 20000, lr 0.004

单卡换为四卡，batch_size不变，相当于总batch_size增加了4倍数，此时iters可以减小为1/4，学习率可以增加4倍。

**Comment by AP-Kai** [comment]
> 单卡训练中：batch_size 2, iters 80000, lr 0.001 
> 四卡训练改为： batch_size 2, iters 20000, lr 0.004
> 
> 单卡换为四卡，batch_size不变，相当于总batch_size增加了4倍数，此时iters可以减小为1/4，学习率可以增加4倍。

了解啦，谢谢您~
