### ISSUE TITLE
你好，遥感数据加载问题，gdal,ogr和rasterio已经安装上，还是出现

### ISSUE THREAD

**Issue by study1157** [PaddlePaddle/PaddleSeg#2075]
![image](https://user-images.githubusercontent.com/96522577/166129551-c93ecdae-eb77-4699-96b2-5f4478d5d9c4.png)

**Comment by juncaipeng** [comment]
是使用EISeg遥感图像标注吗？

**Comment by study1157** [comment]
是的，问题已解决，raterio安装上，但是与numpy版本冲突，更新numpy版本后就可以了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月5日(周四) 中午11:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleSeg] 你好，遥感数据加载问题，gdal,ogr和rasterio已经安装上，还是出现 (Issue #2075)




 
是使用EISeg遥感图像标注吗？
