### ISSUE TITLE
FCN 分割导出onnx input_shape与预期不一致，输出 [None, 3, None, None]

### ISSUE THREAD

**Issue by pythondever** [PaddlePaddle/PaddleSeg#2076]
1. PaddleSeg版本：2.4
 2. PaddlePaddle版本：2.2
 3. 操作系统信息：ubuntu18.04
 4. Python版本号：Python3.8
 5. CUDA/cuDNN版本：Cuda11.1/cudnn8.1
 
使用onnxruntime 获取input_shape 输出  [None, 3, None, None]

···
预测脚本
import cv2
import numpy as np
import onnx
import onnxruntime

providers = [
    ('CUDAExecutionProvider', {
        'device_id': 0,
        'arena_extend_strategy': 'kNextPowerOfTwo',
        'gpu_mem_limit': 2 * 1024 * 1024 * 1024,
        'cudnn_conv_algo_search': 'EXHAUSTIVE',
        'do_copy_in_default_stream': True,
    }),
    'CPUExecutionProvider',
]

def pred_onnx(model_file, image_file):
    m = onnx.load(model_file)
    onnx.checker.check_model(m, True)
    session = onnxruntime.InferenceSession(model_file, providers=providers)
    input_name = session.get_inputs()[0].name
    input_shape = session.get_inputs()[0].shape
    input_dtype = session.get_inputs()[0].type
    output_name = session.get_outputs()[0].name
    image = cv2.imdecode(np.fromfile(image_file, dtype=np.uint8), 1)
    # pred = session.run([output_name], {input_name: image_data})
    # print("pred = {}".format(pred[0]))
    # print(pred[0].shape)
    print(input_shape)
    print(input_name)
    print(input_dtype)

if __name__ == '__main__':
    im = '2.png'
    model = './pp_output.onnx'
    pred_onnx(model, im)

打印输出
[None, 3, None, None]
x
tensor(float)

···
有人遇到过吗?

**Comment by jiangjiajun** [comment]
预期是什么

**Comment by pythondever** [comment]
> 预期是什么

输出为None 是否意味这是动态的batch 和 shape ?

**Comment by jiangjiajun** [comment]
对的
