### ISSUE TITLE
[General Issue] Trt output vis issue

### ISSUE THREAD

**Issue by wangyidong3** [PaddlePaddle/PaddleSeg#2077]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: 2.5
 2. PaddlePaddle version: paddlepaddle-gpu 2.3.0rc0.post112
 3. Operation system: Ubuntu20
 4. Python version: python3.8.12
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

Hi, I have 2 questions  when I tried the deploy code in infer_onnx_trt.py and infer.py
1. Is there any way to load trt engine file in deploy/python/infer.py? If so, what' s the proper format for deploy.yml? or any suggestion for DeployConfig modification?

2. As in infer_onnx_trt.py,  When I feed the image numpy array(1024*512),  I got 1d vector,  and then reshape for visualization . 
```
        paddle_out_shape = (1, 1, 512, 1024)
        trt_out = trt_out.reshape(paddle_out_shape)
        trt_out =np.reshape(trt_out, (512,1024))
        x, y = np.nonzero(trt_out)
```
We assume (x, y) represent the points of segmentation results,  but the points on image we got doesn't make sense.

For the trt output, is there any doc or processing suggestions?
Thanks.

**Comment by juncaipeng** [comment]
Hi,
1. infer.py can not load trt engine, it only supports paddle inference model.
2. trt_out is the segmented image, and it has the same shape as the input image. You can refer to the official documents： https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/
