### ISSUE TITLE
[Bug]训练过程中存在显存泄露的问题，当训练iter超过了156以后显存会逐渐增长，显存到578个iter就会爆满，项目地址：https://aistudio.baidu.com/aistudio/clusterprojectdetail/3936351

### ISSUE THREAD

**Issue by marshall-dteach** [PaddlePaddle/PaddleSeg#2078]
欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：PaddleSeg release 2.5
 2. PaddlePaddle版本：2.2.2
 3. 操作系统信息：Linux
 4. Python版本号：Python3.7
 6. 完整的代码：(若修改过原代码，请提供修改前后代码对比）
 7. 详细的错误信息、相关log：（若使用多卡，log默认保存在log/worklog.0）
 8. 运行指令或复现步骤：
 9. 其他内容: （增加其他与问题相关的内容）

**Comment by shiyutang** [comment]
显存泄漏主要的原因在于存在于GPU中、在计算图中的tensor在每次训练中持续累积，因此需要关注训练或者评估中对于tensor的累加/其他计算操作。
下面为排查方向：
<img width="872" alt="image" src="https://user-images.githubusercontent.com/34859558/166859168-2bc2a60f-be56-4076-a565-3baf63cddb2b.png">

**Comment by marshall-dteach** [comment]
这是根据教程写的多卡训练的地方，您看看会不会是这里出现了问题？
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 中午11:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] [Bug]训练过程中存在显存泄露的问题，当训练iter超过了156以后显存会逐渐增长，显存到578个iter就会爆满，项目地址：https://aistudio.baidu.com/aistudio/clusterprojectdetail/3936351 (Issue #2078)





 
显存泄漏主要的原因在于存在于GPU中、在计算图中的tensor在每次训练中持续累积，因此需要关注训练或者评估中对于tensor的累加/其他计算操作。
 下面为排查方向：

**Comment by marshall-dteach** [comment]
另外paddleseg并行的API与官网提供的也不一致，可能是这里不匹配吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 中午11:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] [Bug]训练过程中存在显存泄露的问题，当训练iter超过了156以后显存会逐渐增长，显存到578个iter就会爆满，项目地址：https://aistudio.baidu.com/aistudio/clusterprojectdetail/3936351 (Issue #2078)





 
显存泄漏主要的原因在于存在于GPU中、在计算图中的tensor在每次训练中持续累积，因此需要关注训练或者评估中对于tensor的累加/其他计算操作。
 下面为排查方向：

**Comment by marshall-dteach** [comment]
![image](https://user-images.githubusercontent.com/63546191/166862734-330a7b02-c890-46c4-9a0e-f95b29c4b57e.png)

**Comment by marshall-dteach** [comment]
![image](https://user-images.githubusercontent.com/63546191/166862772-3fdb79d7-6f8a-4878-8891-1710858e4ea4.png)
![image](https://user-images.githubusercontent.com/63546191/166862778-e332b0b6-b2ce-4979-9a63-657c018635fc.png)

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
