### ISSUE TITLE
请问一下，排行榜里展示的是百度这边给出的最好的结果吗？

### ISSUE THREAD

**Issue by songyuc** [PaddlePaddle/PaddleSeg#208]
尊敬的开发者，您好！
我是一名正在学习PaddlePaddle的学生，我想请问一下，
![image](https://user-images.githubusercontent.com/27288110/77741585-188fe700-7050-11ea-972e-55757610df08.png)
这里的DeepLabV3+的测试结果是百度这边给出的最好的结果吗？
期待您的回复！

**Comment by ZeyuChen** [comment]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.4.0/docs/model_zoo.md
更详细的结果可以看下这个表格，Xception65这个Backbone是DeepLabv3+下最好的，也可以实时最新的HRNet，效果也不差，性能相对DeepLab好一些。

**Comment by songyuc** [comment]
@ZeyuChen ，好的谢谢大佬的解答！
