### ISSUE TITLE
为什么没有固定部分权重参数进行训练的功能？

### ISSUE THREAD

**Issue by KangolHsu** [PaddlePaddle/PaddleSeg#2087]
固定前N层这个功能大家都没有这需求吗？
每次都是全部权重参与训练，这样的训练效率太低了吧？
为什么没考虑将这个功能加上？
是我的打开方式不对吗？

**Comment by juncaipeng** [comment]
默认是没有支持固定部分权重的功能，后续我们会考虑加入。

通常backbone还是需要参与训练的。
