### ISSUE TITLE
[General Issue]CrossEntropyLoss weight

### ISSUE THREAD

**Issue by m828** [PaddlePaddle/PaddleSeg#2088]
CrossEntropyLoss 中的weight如何设置？
![image](https://user-images.githubusercontent.com/45037914/167255321-2efc95e6-2edf-4a73-ab95-2a77038120d2.png)
我设置这样，感觉跟none没什么区别。

**Comment by juncaipeng** [comment]
你这不同类别的权重系数差别不大啊。 如果是类别严重不均衡，可以考虑调整权重系数。  你也可以考虑使用OHEMCrossEntropyLoss

**Comment by m828** [comment]
> 如果是类别严重不均衡，可以考虑调整重系数。你也可以考虑使用OHEMCrossEntropyLoss

好的，我尝试一下OHEMCrossEntropyLoss。
我想问的是调整权重系数是这样的格式吗？如果格式正确的话，我尝试把权重拉大一下，像weight=[1, 10, 12, 8, 6, 6, 10, 8]类似的，因为我有个别类iou比较低，我想提升一下。
![1](https://user-images.githubusercontent.com/45037914/167360281-908ab902-d0fa-4ecd-9b3a-3a245162a17d.png)

**Comment by juncaipeng** [comment]
嗯  这个结果不错。
是这样调整，精度低的类别权重系数大一点。

**Comment by m828** [comment]
> 嗯，这个结果不错。 是这样调整，精确的类别权重因素大一点。

好的，感谢🙏

**Comment by m828** [comment]
> 嗯，这个结果不错。 是这样调整，精确的类别权重因素大一点。

我用weight: [1, 20, 20, 15, 10, 10, 20, 10] 跑出来的结果比没有设置weight的结果更差了，这是什么原因呢？
mIoU: 0.7804，
Class IoU:
[0.9852 0.5706 0.5046 0.8483 0.9824 0.9358 0.5434 0.873 ]
之前没有调整的：
mIoU: 0.8128
Class IoU:
[0.9886 0.6241 0.5764 0.8782 0.9846 0.9388 0.6223 0.8894]

**Comment by juncaipeng** [comment]
如果weight调整了，也需要适当调整学习率。

**Comment by m828** [comment]
> 

好的，我试试
