### ISSUE TITLE
[General Issue]推理失败

### ISSUE THREAD

**Issue by m828** [PaddlePaddle/PaddleSeg#2089]
![image](https://user-images.githubusercontent.com/45037914/167256154-0c359cb3-1276-4930-bb27-ed3b6ad0f239.png)
已经设置了enable_auto_tune=True，还是提示这个错误。
![image](https://user-images.githubusercontent.com/45037914/167256175-6849af36-efad-4d9f-8f36-01c46e81de3e.png)

**Comment by juncaipeng** [comment]
这是由于你安装的PaddlePaddle版本不支持trt，请参考文档中的环境准备说明，卸载再安装。

https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/docs/deployment/inference/python_inference_cn.md

**Comment by m828** [comment]
> 
我重新安装了一下，提示一些版本没有对应，但是也没有保报错，但是看不出来效果，感觉还是有问题。
![image](https://user-images.githubusercontent.com/45037914/167360723-eaff4155-5f0c-496c-9124-59ed6ad58a2d.png)
![image](https://user-images.githubusercontent.com/45037914/167360997-c6468e65-ca37-49fe-ba02-1a79b02bb5ec.png)

**Comment by m828** [comment]
> 这是由于你安装的PaddlePaddle版本不支持trt，请文档中的环境准备说明，卸载重新安装。
> 
> https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/docs/deployment/inference/python_inference_cn.md

我重新安装了一下，提示一些版本没有，但是也没有保报错，但是看不出来效果，感觉还是有问题。
![image](https://user-images.githubusercontent.com/45037914/167361282-aea2fc45-ac45-43ef-b3db-4458e432561f.png)
![image](https://user-images.githubusercontent.com/45037914/167361301-d93a1f53-8850-4e7f-a5c3-0497a4dc3307.png)

**Comment by juncaipeng** [comment]
看着没错啊。
如果有错误，安装准确版本的trt吧，上面给出的链接中可以下载8.0版本的trt。

**Comment by m828** [comment]
> 

我安装的是8.4版本的trt，是否是因为版本太高了，是没有错误，但是看不出来效果，看网上好多推理出来的速度，内存等信息都很清楚。

**Comment by juncaipeng** [comment]
预测没有太多输出，只是保存预测结果：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/docs/deployment/inference/python_inference_cn.md#4-%E9%A2%84%E6%B5%8B
