### ISSUE TITLE
请问一下，现在DeepLabV3+最好的backbone是哪一个呢？

### ISSUE THREAD

**Issue by songyuc** [PaddlePaddle/PaddleSeg#209]
尊敬的开发者，您好！
我是一名正在学习PaddlePaddle的学生，我想请问一下，
现在DeepLabV3+模型可以使用的效果最好的主干网络是哪一个呢？
期待您的回复！

**Comment by ZeyuChen** [comment]
@songyuc Xception65

**Comment by songyuc** [comment]
@ZeyuChen，不是Xception71吗？

**Comment by LutaoChu** [comment]
暂时还没有Xception71的预训练模型。当然你可以自己训练

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。
