### ISSUE TITLE
如何训练大图[General Issue]

### ISSUE THREAD

**Issue by LiyqSmile** [PaddlePaddle/PaddleSeg#2090]
我是个小白，想使用PPLiteSeg进行分割，自己的数据图像是2048*2000大小，如何做呢？谢谢

**Comment by juncaipeng** [comment]
建议你先多看看PaddleSeg的文档和示例，学习一下。

图像比较大，训练的时候可以进行裁剪，用小图训练。
测试的时候，可以先缩放到一定尺寸再预测，或者直接原图大小进行预测。

![image](https://user-images.githubusercontent.com/52520497/167335297-f99e0940-d8a1-4add-a8fa-b47ff11cc25d.png)

**Comment by LiyqSmile** [comment]
谢谢，已经可以训练了
