### ISSUE TITLE
Running the visualize.ipynb file with jupyterlab, there is no response, no renderings are displayed, and no errors are reported

### ISSUE THREAD

**Issue by baoqicha** [PaddlePaddle/PaddleSeg#2094]
Running the visualize.ipynb file with jupyterlab, there is no response, no renderings are displayed, and no errors are reported

**Comment by juncaipeng** [comment]
What is the visualize.ipynb file?

**Comment by baoqicha** [comment]
https://github.com/PaddlePaddle/PaddleSeg/tree/develop/contrib/MedicalSeg













--

|

乐普（北京）医疗装备有限公司

| |
|
Name： 暴启超
Tel:18810602620
***@***.***
Address:北京市顺义区顺仁路60号乐普医疗(邮编101300)
| |
|




| |
|




|




|




At 2022-05-10 10:21:25, "cc" ***@***.***> wrote:

What is the visualize.ipynb file?

**Comment by KeqingWu** [comment]
Excause me. How do you fix it?

**Comment by shiyutang** [comment]
You need to run this with jupyter notebook rather than jupyterlab. I recall this has something to do with itkwidget's support issue. https://github.com/InsightSoftwareConsortium/itkwidgets/issues/405
