### ISSUE TITLE
pp_liteseg 支持onnx格式导出吗？

### ISSUE THREAD

**Issue by Dreamerzp** [PaddlePaddle/PaddleSeg#2095]

**Comment by juncaipeng** [comment]
支持，请查看文档：https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.5/configs/pp_liteseg

![image](https://user-images.githubusercontent.com/52520497/167529597-f5538940-75c5-405e-becf-54299d988129.png)

**Comment by Quintonkd** [comment]
![image](https://user-images.githubusercontent.com/33079930/167751716-2bfaa158-a1dd-4dac-a37e-b6426dcc6be4.png)
请问 在导出过程中碰到了这样的错误该怎么解决 @juncaipeng

**Comment by juncaipeng** [comment]
这是导出onnx时不支持adaptive_pooling op。
你使用时可以调整一下输入图片的尺寸。 或者配置模型中修改一下cm_bin_sizes为[1, 2]。
