### ISSUE TITLE
预测 模式中"ANALYSIS"和NATIVE 这两种有什么区别，哪一种快？

### ISSUE THREAD

**Issue by jaffe-fly** [PaddlePaddle/PaddleSeg#210]
另外使用"ANALYSIS"的时候报错
![image](https://user-images.githubusercontent.com/49515380/77814590-3e1efe00-70ed-11ea-86cc-e2965251f4c8.png)

**Comment by sjtubinlong** [comment]
@jaffe-fly 
ANALYSIS模式做了OP融合等计算优化，性能相比NATIVE模式更好，目前推荐使用Analysis模式。

目前在windows平台上，无法使用tensorrt，请把配置的yaml文件中的开启tensorrt的开关设置为0再试试。

**Comment by jaffe-fly** [comment]
你指的是USE_PR   设置为0？

**Comment by Boyan-Liu** [comment]
@sjtubinlong

**Comment by jaffe-fly** [comment]
大佬们  上面的问题有办法解决吗？  windows平台怎么才能使用ANALYSIS模式

**Comment by jaffe-fly** [comment]
window10的平台怎么才能使用ANALYSIS模式

**Comment by OliverLPH** [comment]
@jaffe-fly 
Python部署，执行
`python infer.py --conf=/path/to/deploy.yaml --input_dir/path/to/images_directory --use_pr=False `
不要打开 `--trt_mode` 即可关闭 `TensorRT` 使用 `analysis` 模式

C++ 部署，将 `deploy.yaml` 配置文件中 `TRT_MODE` 部分删掉就可以了

**Comment by jaffe-fly** [comment]
用你的方法  使用analysis 刚开始不报错了。但是运行到几秒就卡住 然后退出  换做NATIVE是可以一致运行的。这是什么原因？
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
total_runtime=0.08779597282409668
I0410 16:15:25.052613  9812 analysis_predictor.cc:462] ======= optimize end =======
I0410 16:15:25.166309  9812 analysis_predictor.cc:84] Profiler is deactivated, and no profiling report will be generated.
I0410 16:15:25.173317  9812 analysis_predictor.cc:833] MODEL VERSION: 1.7.1
I0410 16:15:25.173317  9812 analysis_predictor.cc:835] PREDICTOR VERSION: 1.7.1
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [conv_affine_channel_fuse_pass]e[0m
e[32m--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
I0410 16:15:25.248118  9812 graph_pattern_detector.cc:101] ---  detected 29 subgraphs
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
I0410 16:15:25.258090  9812 graph_pattern_detector.cc:101] ---  detected 2 subgraphs
e[32m--- Running IR pass [multihead_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
e[32m--- Running IR pass [fc_elementwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add_act_fuse_pass]e[0m
I0410 16:15:25.312916  9812 graph_pattern_detector.cc:101] ---  detected 11 subgraphs
e[32m--- Running IR pass [conv_elementwise_add2_act_fuse_pass]e[0m
I0410 16:15:25.317931  9812 graph_pattern_detector.cc:101] ---  detected 1 subgraphs
e[32m--- Running IR pass [conv_elementwise_add_fuse_pass]e[0m
I0410 16:15:25.320895  9812 graph_pattern_detector.cc:101] ---  detected 20 subgraphs
e[32m--- Running IR pass [transpose_flatten_concat_fuse_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
I0410 16:15:25.326907  9812 ir_params_sync_among_devices_pass.cc:41] Sync params from CPU to GPU
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [memory_optimize_pass]e[0m
I0410 16:15:25.344859  9812 memory_optimize_pass.cc:223] Cluster name : elementwise_add_0  size: 2048000
I0410 16:15:25.344859  9812 memory_optimize_pass.cc:223] Cluster name : relu_0.tmp_0  size: 65277184
I0410 16:15:25.344859  9812 memory_optimize_pass.cc:223] Cluster name : relu_4.tmp_0  size: 8192000
I0410 16:15:25.344859  9812 memory_optimize_pass.cc:223] Cluster name : relu6_0.tmp_0  size: 49152000
I0410 16:15:25.344859  9812 memory_optimize_pass.cc:223] Cluster name : psp6_interp.tmp_0  size: 258048
I0410 16:15:25.344859  9812 memory_optimize_pass.cc:223] Cluster name : relu_7.tmp_0  size: 16384000
I0410 16:15:25.344859  9812 memory_optimize_pass.cc:223] Cluster name : psp1_interp.tmp_0  size: 258048
I0410 16:15:25.344859  9812 memory_optimize_pass.cc:223] Cluster name : batch_norm_35.tmp_3  size: 4608
I0410 16:15:25.344859  9812 memory_optimize_pass.cc:223] Cluster name : image  size: 12
I0410 16:15:25.344859  9812 memory_optimize_pass.cc:223] Cluster name : shape_1.tmp_0_slice_0  size: 8
I0410 16:15:25.344859  9812 memory_optimize_pass.cc:223] Cluster name : shape_0.tmp_0_slice_0  size: 8
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
total_runtime=0.0887296199798584
I0410 16:15:25.361809  9812 analysis_predictor.cc:462] ======= optimize end =======
I0410 16:15:25.475482  9812 analysis_predictor.cc:84] Profiler is deactivated, and no profiling report will be generated.
I0410 16:15:25.481493  9812 analysis_predictor.cc:833] MODEL VERSION: 1.7.1
I0410 16:15:25.481493  9812 analysis_predictor.cc:835] PREDICTOR VERSION: 1.7.1
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [conv_affine_channel_fuse_pass]e[0m
e[32m--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
I0410 16:15:25.555269  9812 graph_pattern_detector.cc:101] ---  detected 29 subgraphs
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
I0410 16:15:25.565241  9812 graph_pattern_detector.cc:101] ---  detected 2 subgraphs
e[32m--- Running IR pass [multihead_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
e[32m--- Running IR pass [fc_elementwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add_act_fuse_pass]e[0m
I0410 16:15:25.621093  9812 graph_pattern_detector.cc:101] ---  detected 11 subgraphs
e[32m--- Running IR pass [conv_elementwise_add2_act_fuse_pass]e[0m
I0410 16:15:25.625082  9812 graph_pattern_detector.cc:101] ---  detected 1 subgraphs
e[32m--- Running IR pass [conv_elementwise_add_fuse_pass]e[0m
I0410 16:15:25.628073  9812 graph_pattern_detector.cc:101] ---  detected 20 subgraphs
e[32m--- Running IR pass [transpose_flatten_concat_fuse_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
I0410 16:15:25.634057  9812 ir_params_sync_among_devices_pass.cc:41] Sync params from CPU to GPU
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [memory_optimize_pass]e[0m
I0410 16:15:25.653007  9812 memory_optimize_pass.cc:223] Cluster name : elementwise_add_0  size: 2048000
I0410 16:15:25.653007  9812 memory_optimize_pass.cc:223] Cluster name : relu_0.tmp_0  size: 65277184
I0410 16:15:25.653007  9812 memory_optimize_pass.cc:223] Cluster name : relu_4.tmp_0  size: 8192000
I0410 16:15:25.653007  9812 memory_optimize_pass.cc:223] Cluster name : relu6_0.tmp_0  size: 49152000
I0410 16:15:25.653007  9812 memory_optimize_pass.cc:223] Cluster name : psp6_interp.tmp_0  size: 258048
I0410 16:15:25.653007  9812 memory_optimize_pass.cc:223] Cluster name : relu_7.tmp_0  size: 16384000
I0410 16:15:25.653007  9812 memory_optimize_pass.cc:223] Cluster name : psp1_interp.tmp_0  size: 258048
I0410 16:15:25.653007  9812 memory_optimize_pass.cc:223] Cluster name : batch_norm_35.tmp_3  size: 4608
I0410 16:15:25.653007  9812 memory_optimize_pass.cc:223] Cluster name : image  size: 12
I0410 16:15:25.653007  9812 memory_optimize_pass.cc:223] Cluster name : shape_1.tmp_0_slice_0  size: 8
I0410 16:15:25.653007  9812 memory_optimize_pass.cc:223] Cluster name : shape_0.tmp_0_slice_0  size: 8
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m

**Comment by OliverLPH** [comment]
@jaffe-fly 
你截下来的这段log里没看到有报错信息，不太明白为什么会退出。
可以看下是不是由于内存不够导致程序被kill了？

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。
