### ISSUE TITLE
yaml-cpp相关问题

### ISSUE THREAD

**Issue by LiyqSmile** [PaddlePaddle/PaddleSeg#2100]
（1）windows下VS2017部署预测库，yaml-cpp库使用Cmake编译出来只有yaml-cpp.lib，depoly中引用#include "yaml-cpp/yaml.h"，
相关代码
        YAML::Node node = YAML::LoadFile(yaml_path);
	std::string model_file = node["Deploy"]["model"].as<std::string>();
	std::string params_file = node["Deploy"]["params"].as<std::string>();
	YamlConfig yaml_config = { model_file, params_file };
工程编辑的时候会提示Node无法解析.。
希望可以解答，非常谢谢!

**Comment by Sachielyuan** [comment]
我在vs2015也遇到相同问题，yaml-cpp版本是0.7

**Comment by juncaipeng** [comment]
应该是需要将编译的lib添加到vs的链接路径

**Comment by dragonwarrior95** [comment]
直接下载yaml-cpp源码引入可解，或者去vcpkg下载现成的库去引入估计也行
