### ISSUE TITLE
[General Issue] PP-HumanSeg14K数据集获取

### ISSUE THREAD

**Issue by fallinghan** [PaddlePaddle/PaddleSeg#2104]
您好！我想使用PP-HumanSeg14K数据集做训练。之前发过邮件，很久了未得到回复，请问怎样才能获取到这个数据集呢？

**Comment by LutaoChu** [comment]
你好，申请流程如下，注意使用官方邮箱

The data can be obtained by sending an email to [paddleseg@baidu.com](mailto:paddleseg@baidu.com) via an official email (not use qq, gmail, etc.) including your institution/company information and the purpose on the dataset.

**Comment by fallinghan** [comment]
> 你好，申请流程如下，注意使用官方邮箱
> 
> The data can be obtained by sending an email to [paddleseg@baidu.com](mailto:paddleseg@baidu.com) via an official email (not use qq, gmail, etc.) including your institution/company information and the purpose on the dataset.

我在4月25日给您给出的邮箱发了申请邮件，但没收到回复，请问是拒绝了我的使用申请吗？

**Comment by michaelowenliu** [comment]
@fallinghan Hi, could you please send the request email again?

**Comment by fallinghan** [comment]
> @fallinghan Hi, could you please send the request email again?

I just resent the application email, please check.

**Comment by yzl19940819** [comment]
done
