### ISSUE TITLE
转换 onnx 数据不匹配

### ISSUE THREAD

**Issue by sim-lab-dev** [PaddlePaddle/PaddleSeg#2107]
### 问题描述
在把pp_liteseg转换成onnx，使用如下命令
python deploy/python/infer_onnx_trt.py  --config configs/pp_liteseg/pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k.yml --model_path  pretrained_model/model.pdparams

模型是配置文件对应的模型，转换成onnx的时候出错，
Mismatched elements: 3445798 / 9961472 (34.6%)
Max absolute difference: 0.005983
Max relative difference: 14122.436
 x: array([[[[ 0.432929,  0.432929,  0.432929, ..., -0.166786, -0.166786,
          -0.166786],
         [ 0.432929,  0.432929,  0.432929, ..., -0.166786, -0.166786,...
 y: array([[[[ 0.43202 ,  0.43202 ,  0.43202 , ..., -0.167841, -0.167841,
          -0.167841],
         [ 0.43202 ,  0.43202 ,  0.43202 , ..., -0.167841, -0.167841,...

这个模型用源代码跑的时候结果是没有问题的，请问下是什么原因引起的

另外如果不加model_path参数，数据不匹配比这个少很多，但是模型实际推理的时候得到的结果和源代码跑的结果相差很大，
### 推理过程
def preprocess(image, to_rgb, mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)):
    if to_rgb:
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    image = normalize(image, mean, std)
    image = cv2.resize(image, (512, 1024), interpolation = cv2.INTER_LINEAR)
    image = np.transpose(image, (2, 0, 1))
    image = image[np.newaxis, ...]
    return image
    
def normalize(image, mean, std):
    mean = np.array(mean)[np.newaxis, np.newaxis, :]
    std = np.array(std)[np.newaxis, np.newaxis, :]

    image = image.astype(np.float32, copy=False) / 255.0
    image -= mean
    image /= std
    return image

def poseprocess(pred):
    pred = np.argmax(pred, axis=1)
    pred = pred.squeeze(0).astype('int32')
    pred = pred.astype('uint8')

    return pred

save_dir = "./result"
image_path = os.path.join(save_dir, "test.png")
input_data = cv2.imread("test.png")

input_data = preprocess(input_data, True)

color_map = visualize.get_color_map_list(256, custom_color=None)
if args.onnx_model_path is not None:  
    engine, context = TRTPredictorV2().load_engine(args.onnx_model_path)
    t = time.time()
    for i in range(100):
        out, latency = run(engine, context, np.ascontiguousarray(input_data))
        out = out.reshape(1, 19, 512, 1024)
        pred = poseprocess(out)
        # pred = cv2.resize(pred, (2048, 1024), interpolation = cv2.INTER_LINEAR)

        added_image = visualize.visualize(
            "test.png", pred, color_map, weight=0.6)
        mkdir(image_path)

### 环境配置
1. PaddleSeg版本：PaddleSeg release/2.5
2. PaddlePaddle版本：2.2.2.post111
3. 操作系统信息：docker with ubuntu18.04
4. Python版本号：python3.8
5. CUDA/cuDNN版本：cuda 11.1/cudnn 8.0

**Comment by juncaipeng** [comment]
你是在新数据集上训练了模型吗？    
从log来看绝对误差最大数值是0.005983，其实很小了，应该基本不影响分割精度。你可以修改一下infer_onnx_trt.py中的检测代码，放大允许的误差精度。

[链接](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/deploy/python/infer_onnx_trt.py#L439) 这里的rtol和atol可以随意修改。

**Comment by sim-lab-dev** [comment]
@juncaipeng 数据集是cityscapes，但是这个误匹配的数量有34.6%，而且用转换之后的模型推理出来的结果和源代码执行的图片差别很大，看上去像是马赛克

**Comment by MJD1142** [comment]
请问onnx导出误差大的问题如何解决的
