### ISSUE TITLE
paddleseg中HRNet是否支持gn？ 

### ISSUE THREAD

**Issue by lxk767363331** [PaddlePaddle/PaddleSeg#211]
在.yaml文件中设置GN，在config中设置gn ，cfg.MODEL.DEFAULT_GROUP_NUMBER = 9 不可使用GN， 请问是否支持。
第二个问题 如果本模型不支持 ，是HRNet结构导致不支持，还是模型库未修改相关配置？

**Comment by wuyefeilin** [comment]
目前hrnet直接使用bn, 并不能通过在.yaml文件中设置GN进行使用。这一块需要对模型库对bn和gn的配置进行修改

**Comment by lxk767363331** [comment]
我需要对哪里进行修改 可以给出提示么

**Comment by wuyefeilin** [comment]
![image](https://user-images.githubusercontent.com/30919197/78117908-d0e6d200-7438-11ea-9b31-4444846747bb.png)
你可以把这边的bn改成你需要的gn函数试试

**Comment by lxk767363331** [comment]
已解决 谢谢
