### ISSUE TITLE
请教一下Mattings模型训练后的怎么通过可视化VisualDL查看训练的结果好坏呢？

### ISSUE THREAD

**Issue by zhenzi0322** [PaddlePaddle/PaddleSeg#2110]
![image](https://user-images.githubusercontent.com/34839719/168043559-060e4204-21d8-498a-940e-8eeb21c92a00.png)

![image](https://user-images.githubusercontent.com/34839719/168044306-ba21a8c2-0a99-4b5f-be46-645cfcda12f5.png)

**Comment by wuyefeilin** [comment]
通过add_image进行添加，更加详细的教程请参考：https://github.com/PaddlePaddle/VisualDL

**Comment by zhenzi0322** [comment]
> 通过add_image进行添加，更加详细的教程请参考：https://github.com/PaddlePaddle/VisualDL

我知道上述的，但是我不太清楚官方提供`Mattings`中的`VisualDL`中的参数都代表什么意思？就比如：`Train/all`代表什么？
