### ISSUE TITLE
EISEG工具标注视频是否可行呢

### ISSUE THREAD

**Issue by nine-city** [PaddlePaddle/PaddleSeg#2112]
把视频抽帧为图片
然后用EISEG这类标注工具进行标注后
再拿给fairmot进行训练是否可行呢
或者说paddle有提供能方便标注fairmot的工具吗

**Comment by haoyuying** [comment]
近期我们将推出基于eiseg的视频标注工具，敬请期待。

**Comment by nine-city** [comment]
有大概的时间节点吗
