### ISSUE TITLE
输入图片resize后误差较大

### ISSUE THREAD

**Issue by sim-lab-dev** [PaddlePaddle/PaddleSeg#2114]
你好，在运行pp_liteseg模型的时候，如果cityscape图片经过resize变小之后比如360X0最后分割的很多分割的物体都会连在一起，如果输入时1024X2480预测结果物体之间的边界很清晰，请问有什么办法能解决这个问题吗

1. PaddleSeg版本：PaddleSeg release/2.5
 2. PaddlePaddle版本：如PaddlePaddle 2.2
 3. 操作系统信息：linux
 4. Python版本号：python3.6
 5. CUDA/cuDNN版本：CUDA10.2/cudnn8.1

**Comment by juncaipeng** [comment]
训练和测试时，图像缩放尺寸尽可能相同。
cityscapes原图大小是2048*1024，如果测试的时候缩小了几倍，训练的时候也要缩小几倍。

**Comment by sim-lab-dev** [comment]
@juncaipeng 这样是不是说训练出来的模型不够普适

**Comment by juncaipeng** [comment]
通常就是这样，训练和测试的图片缩放倍数差别过大，是会影响精度。
