### ISSUE TITLE
use link中的人像分割，用的是具体哪个模型啊

### ISSUE THREAD

**Issue by tengshaofeng** [PaddlePaddle/PaddleSeg#2116]
作者大大，做了令人震惊的工作，受益匪浅。能不能弱弱的问一句
Matting项目中的using link中的人像分割链接服务用的是哪一个模型啊human_matting-resnet34_vd.yml吗？
另外PP-Matting-512， PP-Matting-1024貌似没有找到对应的config文件

**Comment by wuyefeilin** [comment]
使用的时PP-Matting-512哈

PP-Matting两个模型暂时没有开源哈，可以直接使用开源的导出模型进行预测部署

**Comment by tengshaofeng** [comment]
好的，感谢作者大大耐心回复，但是拿到开源的导出模型貌似也没法部署把？我看export和deploy也是需要.yml配置文件的，可是看不到PP-Matting的配置文件

**Comment by wuyefeilin** [comment]
![image](https://user-images.githubusercontent.com/30919197/168770690-62fc8b35-be58-498c-a69e-8e4010305baf.png)
![image](https://user-images.githubusercontent.com/30919197/168770751-d7cb58ec-e1b2-47d6-a946-cf7058fa5d8f.png)
下载解压后你可以看到deploy.yaml

**Comment by tengshaofeng** [comment]
好的好的，相当于一个黑盒咯，逆向搞不出模型结构！谢谢啦



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wuyefeilin ***@***.***&gt;
发送时间: 2022年5月17日 16:50
收件人: PaddlePaddle/PaddleSeg ***@***.***&gt;
抄送: bojohn ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [PaddlePaddle/PaddleSeg] use link中的人像分割，用的是具体哪个模型啊 (Issue #2116)





 

 
 下载解压后你可以看到deploy.yaml
