### ISSUE TITLE
我想咨询下如何实现新建模型在ImageNet等预训练，比如DDRNet39的预训练权重如何获得，本项目仅提供DDRNet23的权重。

### ISSUE THREAD

**Issue by Murphy-MML** [PaddlePaddle/PaddleSeg#2117]
谢谢

**Comment by wuyefeilin** [comment]
https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/algorithm_introduction/ImageNet_models.md Paddle模型相关的backbone的分类预训练模型都在这里了

**Comment by Murphy-MML** [comment]
你好 感谢你的回复，我的意思是在进行二次开发的过程之中，飞桨是否提供了在imagenet预训练的程序实现之类 的。谢谢

**Comment by wuyefeilin** [comment]
PaddleClas就可以哈，具体操作可以到PaddleClas repo看教程哈

**Comment by Murphy-MML** [comment]
好的 感谢
