### ISSUE TITLE
fcn 转onnx 在GPU上无法预测

### ISSUE THREAD

**Issue by pythondever** [PaddlePaddle/PaddleSeg#2122]
我这有个模型基于fcn算法训练出来的,使用paddle2onnx 导出为onnx模型,在cpu 上可以正常预测,在GPU 上预测报错

onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running FusedConv node. Name:'Conv_34' Status Message: CUDNN error executing cudnnAddTensor(Base::CudnnHandle(), &alpha, Base::s.z_tensor, Base::s_.z_data, &alpha, Base::s_.y_tensor, Base::s_.y_data)

对于这种错误是否有解决的建议?

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：2.4
 2. PaddlePaddle版本：2.2
 3. 操作系统信息：ubuntu18.04
 4. Python版本号：3.8.8
 5. CUDA/cuDNN版本:Cuda11.1, Cudnn8
 6. 其他内容: 尝试过更换onnxruntime版本，使用nvidia官方的不同版本 cuda和cudnn docker 一样的错误

**Comment by jiangjiajun** [comment]
cuda升级为11.4， cudnn升级为8.2再试下，这个是onnxruntime-gpu 1.11.0的适配版本

**Comment by pythondever** [comment]
cuda11.4. cudnn8.2 onnxruntime-gpu 1.11.0 试过了，还是一样的错误

**Comment by jiangjiajun** [comment]
提供一下你的paddle模型和onnx模型，我来测试下

**Comment by pythondever** [comment]
> 提供一下你的paddle模型和onnx模型，我来测试下

怎么提供，issue 好像不能上传文件?

**Comment by jiangjiajun** [comment]
模型不大的话，直接上传即可
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/19339784/168941373-cccf8166-5825-416e-8e01-baf7c8f01f7b.png">

**Comment by pythondever** [comment]
> 模型不大的话，直接上传即可 <img alt="image" width="1106" src="https://user-images.githubusercontent.com/19339784/168941373-cccf8166-5825-416e-8e01-baf7c8f01f7b.png">

zip 格式上传 提示 is not included in the list

**Comment by jiangjiajun** [comment]
jiangjiajun#baidu.com 邮箱

**Comment by pythondever** [comment]
> jiangjiajun#baidu.com 邮箱

https://github.com/pythondever/_onnx_demo_error 这里可以下载

**Comment by jiangjiajun** [comment]
paddle模型直接提供model.pdmodel和model.pdiparams，而非权重参数

**Comment by pythondever** [comment]
> paddle模型直接提供model.pdmodel和model.pdiparams，而非权重参数

刚刚上传到仓库了

**Comment by pythondever** [comment]
@jiangjiajun 有什么进展不?

**Comment by jiangjiajun** [comment]
我复现了你的这个问题，但我没看到有任何问题跟Paddle2ONNX有关，你可能需要到onnxruntime的repo下提一个issue

**Comment by pythondever** [comment]
好的，非常感谢，已经提了一个 issue [https://github.com/microsoft/onnxruntime/issues/11548](url)
