### ISSUE TITLE
[Bug]infer时的问题

### ISSUE THREAD

**Issue by marshall-dteach** [PaddlePaddle/PaddleSeg#2124]
报错：
2022-05-18 10:51:02 [INFO]	Use GPU
W0518 10:51:04.675190  3051 analysis_predictor.cc:795] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
[libprotobuf ERROR /paddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/io/coded_stream.cc:208] A protocol message was rejected because it was too big (more than 67108864 bytes).  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
--- Running analysis [ir_graph_build_pass]
[libprotobuf ERROR /paddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/io/coded_stream.cc:208] A protocol message was rejected because it was too big (more than 67108864 bytes).  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
2022-05-18 10:51:07 [INFO]	(InvalidArgument) Failed to parse program_desc from binary string.
  [Hint: Expected desc_.ParseFromString(binary_str) == true, but received desc_.ParseFromString(binary_str):0 != true:1.] (at /paddle/paddle/fluid/framework/program_desc.cc:103)

2022-05-18 10:51:07 [INFO]	If the above error is '(InvalidArgument) some trt inputs dynamic shape info not set, ..., Expected all_dynamic_shape_set == true, ...', please set --enable_auto_tune=True to use auto_tune.

**Comment by marshall-dteach** [comment]
![image](https://user-images.githubusercontent.com/63546191/168948801-57f8ced2-cc18-474b-9bb4-7533290e269b.png)
命令

**Comment by marshall-dteach** [comment]
已经查明，是静态模型大于64MB的问题，请问有解决方法吗

**Comment by shiyutang** [comment]
You can provide the model and I will continue the infer the model in the validation phase.

**Comment by qinhuangdaoStation** [comment]
我也遇到了这个问题，但是我的inference.pdmodel的大小才227KB，inference.pdiparams的大小是104837KB。具体是跟哪个有关系啊？
