### ISSUE TITLE
The type of data we are trying to retrieve does not match the type of data currently contained in the container

### ISSUE THREAD

**Issue by Augus518** [PaddlePaddle/PaddleSeg#2126]
问题描述如下：
 1. PaddleSeg版本：PaddleSeg release/2.3
 2. PaddlePaddle版本：如PaddlePaddle 2.1.0
 3. 操作系统信息：Windows
 4. Python版本号：Python3.9
 5. CUDA/cuDNN版本：cpu
 7. 完整的代码：(若修改过原代码，请提供修改前后代码对比）
  void run(Predictor* predictor, const std::vector<float>& input,
	const std::vector<int>& input_shape, std::vector<float>* out_data) {
	auto input_names = predictor->GetInputNames();
	auto input_t = predictor->GetInputHandle(input_names[0]);
	input_t->Reshape(input_shape);
	input_t->CopyFromCpu(input.data());

	predictor->Run();
	//predictor->Run();

	auto output_names = predictor->GetOutputNames();
	auto output_t = predictor->GetOutputHandle(output_names[0]);
	std::vector<int> output_shape = output_t->shape();
	int out_num = std::accumulate(output_shape.begin(), output_shape.end(), 1,
		std::multiplies<int>());

	out_data->resize(out_num);
	output_t->CopyToCpu(out_data->data());
}

int main() {
	paddle::AnalysisConfig config;
	config.EnableUseGpu(100, 0);
	config.SetModel("E:/Git/PaddleSeg-release-2.4/EISeg/stdc1seg_infer_model/model.pdmodel",
		"E:/Git/PaddleSeg-release-2.4/EISeg/stdc1seg_infer_model/model.pdiparams");
	auto predictor{ paddle_infer::CreatePredictor(config) };
	std::vector<int> input_shape = { 1, 3, 224, 224 };
	std::vector<float> input_data(1 * 3 * 224 * 224, 1);
	std::vector<float> out_data;
	run(predictor.get(), input_data, input_shape, &out_data);
	for (auto e : out_data) {
	//	LOG(INFO) << e << '\n';
		std::cout << e  << std::endl;
	}
	return 0;
}

 9. 详细的错误信息、相关log：（若使用多卡，log默认保存在log/worklog.0）
  InvalidArgumentError: The type of data we are trying to retrieve does not match the type of data currently contained in the container. (at C:\home\workspace\Paddle_release\paddle\phi\core\dense_tensor.cc:148)
 10. 其他内容: 编译无问题，运行至output_t->CopyToCpu(out_data->data())获取检测结果时报错，提示“The type of data we are trying to retrieve does not match the type of data currently contained in the container.”，我的理解是数据类型不正确，所以将out_data数据类型修改为float/int，但是错误依旧。调试发现output_t中dtype_=FLOAT32，看了源码  _(float, DataType::FLOAT32)，也就是设置为float应该是没有问题的。

**Comment by juncaipeng** [comment]
不同模型需要使用netron可视化看下输出的类型。

**Comment by lcs1225** [comment]
> 不同模型需要使用netron可视化看下输出的类型。

请问可以说的详细点不，我好像遇到了同样的问题...
<img width="948" alt="error" src="https://user-images.githubusercontent.com/29704155/183858352-bf21d2e5-9099-4e4e-bf04-c971de9db1c4.png">

**Comment by Tangyuny** [comment]
这个问题你解决了吗 @lcs1225

**Comment by lcs1225** [comment]
> 这个问题你解决了吗 @lcs1225
在linux系统的环境训练就可以了

**Comment by pengguoqing** [comment]
我遇到相同的问题了，也是使用 CPU 进行推理
![Uploading Snipaste_2024-08-08_18-24-20.jpg…]()
