### ISSUE TITLE
DDRnet在使用ADE20K数据集训练时，报错如下。期待回复，谢谢。

### ISSUE THREAD

**Issue by Murphy-MML** [PaddlePaddle/PaddleSeg#2127]
_base_: '../_base_/ade20k.yml'

batch_size: 3
iters: 120000

train_dataset:
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [520, 520]
      im_padding_value: [0, 0, 0]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize

model:
  type: DDRNet_23
  enable_auxiliary_loss: False
  pretrained: Null

optimizer:
  type: sgd
  weight_decay: 0.0005

loss:
  types:
    - type: OhemCrossEntropyLoss
  coef: [1]
  
lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0.0
  power: 0.9

在训练时没有出现问题，在验证时
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 128, 32, 45] and the shape of Y = [1, 128, 32, 44]. Received [45] in X is not equal to [44] in Y at i:3.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/phi/kernels/funcs/common_shape.h:84)
  [operator < elementwise_add > error]

**Comment by liukp557** [comment]
I'm having the same problem.
