### ISSUE TITLE
[General Issue] 提供的模型下载不下来。

### ISSUE THREAD

**Issue by KoapT** [PaddlePaddle/PaddleSeg#2128]

**Comment by shiyutang** [comment]
Please provide the model name and model link.

**Comment by KoapT** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我已收到您的邮件，会在阅读之后尽快给您回复。

**Comment by KoapT** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我已收到您的邮件，会在阅读之后尽快给您回复。

**Comment by KoapT** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我已收到您的邮件，会在阅读之后尽快给您回复。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.

**Comment by KoapT** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我已收到您的邮件，会在阅读之后尽快给您回复。
