### ISSUE TITLE
请问Matting训练好的模型如何在aistudio里面创建趣味体验馆呢

### ISSUE THREAD

**Issue by zhenzi0322** [PaddlePaddle/PaddleSeg#2132]
如下：
![image](https://user-images.githubusercontent.com/34839719/169484841-3bfd3c02-2cf2-45a1-a7ad-4aeb55410749.png)

请问下：有没有相关的流程是关于在`aistudio`里面创建趣味体验馆的？主要针对的`Matting`模型的。j

趣味体验馆里面的制作输入输出转换器不清楚怎么写好？
![image](https://user-images.githubusercontent.com/34839719/169485608-8646b3ca-bae9-4880-974a-fce30ac2eda2.png)

**Comment by wuyefeilin** [comment]
暂时没有哈，可以联系aistudio的工作人员咨询相关问题哈。非常欢迎您建设一个体验馆，我们将会进行展示并表示感谢哈
