### ISSUE TITLE
[Bug]模型蒸馏显示缺少AdaptorBase

### ISSUE THREAD

**Issue by guoxuntao** [PaddlePaddle/PaddleSeg#2135]
报错信息：
[05-21 17:39:33 MainThread @logger.py:242] Argv: PaddleSeg-develop/slim/distill/distill_train.py --teather_config PaddleSeg-develop/configs/quick_start/deeplabv3p_resnet50_os8_optic_disc_512x512_1k_teacher.yml --student_config PaddleSeg-develop/configs/quick_start/deeplabv3p_resnet18_os8_optic_disc_512x512_1k_student.yml --do_eval --use_vdl --save_interval 250 --num_workers 3 --seed 0 --save_dir output/deeplabv3p_resnet18_distill
[05-21 17:39:33 MainThread @utils.py:79] WRN paddlepaddle version: 2.3.0. The dynamic graph version of PARL is under development, not fully tested and supported
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/remote/communication.py:38: DeprecationWarning: 'pyarrow.default_serialization_context' is deprecated as of 2.0.0 and will be removed in a future version. Use pickle or the pyarrow IPC functionality instead.
  context = pyarrow.default_serialization_context()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/__init__.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/rcsetup.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/colors.py:53: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sized
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim-1.0.0-py3.7.egg/paddleslim/nas/ofa/layers_old.py:151: DeprecationWarning: invalid escape sequence \_
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim-1.0.0-py3.7.egg/paddleslim/nas/ofa/layers_old.py:460: DeprecationWarning: invalid escape sequence \s
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim-1.0.0-py3.7.egg/paddleslim/nas/ofa/layers_old.py:151: DeprecationWarning: invalid escape sequence \_
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim-1.0.0-py3.7.egg/paddleslim/nas/ofa/layers_old.py:460: DeprecationWarning: invalid escape sequence \s
Traceback (most recent call last):
  File "PaddleSeg-develop/slim/distill/distill_train.py", line 30, in <module>
    from distill_config import prepare_distill_adaptor, prepare_distill_config
  File "/home/aistudio/PaddleSeg-develop/slim/distill/distill_config.py", line 15, in <module>
    from paddleslim.dygraph.dist import AdaptorBase
ImportError: cannot import name 'AdaptorBase' from 'paddleslim.dygraph.dist' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim-1.0.0-py3.7.egg/paddleslim/dygraph/dist/__init__.py)
用的paddle是2.3gpu版本，slim是2.3版本，paddleseg是develop版本

**Comment by juncaipeng** [comment]
目前paddleseg适配的slim特定版本，请按照下面方法进行安装slim：
![image](https://user-images.githubusercontent.com/52520497/169734554-35283e54-f6a0-43c2-ab1c-9decf8c247c5.png)

**Comment by guoxuntao** [comment]
git reset --hard 15ef0c7dcee5a622787b7445f21ad9d1dea0a933

> 目前paddleseg适配的slim特定版本，请按照下面方法进行安装slim： ![image](https://user-images.githubusercontent.com/52520497/169734554-35283e54-f6a0-43c2-ab1c-9decf8c247c5.png)

为什么输入
git reset --hard 15ef0c7dcee5a622787b7445f21ad9d1dea0a933
会报错：
aistudio@jupyter-2225020-4065307:~/PaddleSlim-develop$ git reset --hard 15ef0c7dcee5a622787b7445f21ad9d1dea0a933
fatal: Not a git repository (or any parent up to mount point /home/aistudio)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by juncaipeng** [comment]
由于你不是clone的paddleslim，而是下载的paddleslim压缩包吧。

**Comment by guoxuntao** [comment]
问题已经解决：大家要clone github上的slim，不要clone gitee上的，然后记得git clone完了之后，cd PaddleSlim，再进行git reset --hard 15ef0c7dcee5a622787b7445f21ad9d1dea0a933

**Comment by Mamaka2020** [comment]
还是不行，github下载不下来，gitee可以回退该版本，但是还是报同样的错误。
