### ISSUE TITLE
小分辨率图片结果误差大

### ISSUE THREAD

**Issue by sim-lab-dev** [PaddlePaddle/PaddleSeg#2137]
你好，请问用cityscapes重新训练分割网络的时候把输入分辨率设置为480X640之后训练的结果比paddle的预训练模型差很多，mIOU只有0.6左右，请问这是什么原因，有什么办法能供提升小分辨率图片训练的精度吗

**Comment by juncaipeng** [comment]
是将cityscapes验证集中图片的分辨率设置为480x640吧？
通常而言，图片分辨率减小，信息会丢失，分割精度会下降，预测速度会加快。 目前没有太好的办法来解决这个矛盾。
