### ISSUE TITLE
pp_liteseg的推理时间

### ISSUE THREAD

**Issue by yuexiayiren159aaa** [PaddlePaddle/PaddleSeg#2141]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: 2.5
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: linux
 4. Python version: (3.7
 5. CUDA/cuDNN version: cuda11.4

![image](https://user-images.githubusercontent.com/102778714/169761584-23e18a5a-edc2-4694-8ce9-0fdeebc5cced.png)
![image](https://user-images.githubusercontent.com/102778714/169761664-ef34379b-59d1-4431-aeb1-5564746f4eeb.png)
![image](https://user-images.githubusercontent.com/102778714/169761893-5696961c-a9ff-4b93-ad7a-b0e33cd3c0f6.png)

paddleseg的文档里说PP-LiteSeg-T1以273.6FPS速度达到了72.0%的mIoU，是我用的这个模型吗，这里模型大小又30M,时间2s，这么能达到273FPS这个速度。还是说我的配置文件用错了，不是这个模型

**Comment by juncaipeng** [comment]
请参考文档中的部署方法进行复现：https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.5/configs/pp_liteseg#inference

![image](https://user-images.githubusercontent.com/52520497/169780012-f2e46f42-6cb9-49f4-83ea-164ab05cacbb.png)

**Comment by yuexiayiren159aaa** [comment]
那我将模型转成onnx再转成mnn后的推理速度应该也很慢是吧，我最终是转onnx然后转mnn后部署

**Comment by juncaipeng** [comment]
pp-liteseg模型是针对NV GPU设计的，在NV GPU上测试的速度。
