### ISSUE TITLE
EIseg加载模型，paddle_infer.create_predictor(config) 解析出错

### ISSUE THREAD

**Issue by xdg2016** [PaddlePaddle/PaddleSeg#2156]
如题：在使用paddle推理时
![image](https://user-images.githubusercontent.com/16351823/170243624-9440b78a-7d47-48e4-9bca-adedfe1931a8.png)

最后这个C:\home\workspace\Paddle_release这个路径都不存在。

环境：
python3.9，
paddle-cpu 2.3.0，
paddelseg 2.5.0
win10 x64
无CUDA

---

**Comment by haoyuying** [comment]
您好，报错原因是模型架子啊路径提供的不对，从readme里下载https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.5/EISeg
相关模型，不要有中文路径，如果不行，尝试用paddle_infer.create_predictor单独加载模型，看是否报错，如报错，可能是paddle安装的问题，建议根据自己的环境重新安装paddle

**Comment by xdg2016** [comment]
谢谢回答，模型路径是没有问题的，我这边在两台电脑上使用 pip install eiseg安装的eiseg，打开加载模型后就直接奔溃了，提示上面的错误，换另外一台就可以了，两台都没有GPU，不清楚还会有什么会影响到。

**Comment by haoyuying** [comment]
报错部分是paddle问题，应该是paddle安装出现了问题，建议卸载后重新安装paddle
