### ISSUE TITLE
cuda11.2配置什么版本tensorRT？

### ISSUE THREAD

**Issue by cloudsurging** [PaddlePaddle/PaddleSeg#2157]
ubuntu 18.04，cuda11.2，cudnn8.1，使用tensorRT 7.2.3.4时出错：
![无标题](https://user-images.githubusercontent.com/32347832/170405988-a03ed26e-11e2-40f9-b64a-7c53fc1e7cb3.png)
提示libnvrtc.so.11.1没有，可是cuda11.2有libnvrtc.so.11.2呀。
以上问题怎么解决？

**Comment by haoyuying** [comment]
请确认cuda和cudnn是否安装正确，根据报错信息定位应该是cuda和cudnn安装有问题导致的

**Comment by xiaodaomingye459** [comment]
您好，我使用你们cuda11.2的容器镜像时也遇到这个问题，请问该怎么解决？

**Comment by wuyefeilin** [comment]
> 您好，我使用你们cuda11.2的容器镜像时也遇到这个问题，请问该怎么解决？

更换其它版本试试
