### ISSUE TITLE
when train and predict come across OSError external 

### ISSUE THREAD

**Issue by SuckChen** [PaddlePaddle/PaddleSeg#2159]
Facing this two problem:
CUDA 11.2  DRIVE VERSION 460.106
OSError external CUBLAS error(7) hint: CUBLAS_STATUS_INVALID_VALUE
OSError external CUSPARSE error(1)

**Comment by haoyuying** [comment]
您好，目前您提供的信息无法准确定位问题，请提供复现该问题的环境及使用方式，方便我们进一步跟进问题。
