### ISSUE TITLE
在测试时报错是什么原因？

### ISSUE THREAD

**Issue by ljx111** [PaddlePaddle/PaddleSeg#216]
把deeplabv3的项目fork，换上自己的训练集，提示越界了，但是可视化中却没报错
还有想问一下TRAIN_CROP_SIZE，EVAL_CROP_SIZE和FIX_RESIZE_SIZE有什么关系吗？不太理解

#Device count: 1
W0411 11:40:04.963268   696 device_context.cc:259] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.2, Runtime API Version: 9.0
W0411 11:40:04.967165   696 device_context.cc:267] device: 0, cuDNN Version: 7.3.
load test model: work/model_ffc/final
Traceback (most recent call last):
  File "./pdseg/eval.py", line 176, in <module>
    main()
  File "./pdseg/eval.py", line 172, in main
    evaluate(cfg, **args.__dict__)
  File "./pdseg/eval.py", line 138, in evaluate
    conf_mat.calculate(pred, grts, masks)
  File "/home/aistudio/pdseg/metrics.py", line 47, in calculate
    shape=(self.num_classes, self.num_classes))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/scipy/sparse/compressed.py", line 57, in __init__
    other = self.__class__(coo_matrix(arg1, shape=shape))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/scipy/sparse/coo.py", line 198, in __init__
    self._check()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/scipy/sparse/coo.py", line 285, in _check
    raise ValueError('row index exceeds matrix dimensions')
ValueError: row index exceeds matrix dimensions

**Comment by LutaoChu** [comment]
应该是类别数的设置跟实际的类别数不一致，建议检查一下`DATASET.CLASS_NUMBER`这个配置项。
关于TRAIN_CROP_SIZE，EVAL_CROP_SIZE和FIX_RESIZE_SIZE，可参考这个文档 https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.4.0/docs/data_aug.md

**Comment by ljx111** [comment]
> 应该是类别数的设置跟实际的类别数不一致，建议检查一下`DATASET.CLASS_NUMBER`这个配置项。
> 关于TRAIN_CROP_SIZE，EVAL_CROP_SIZE和FIX_RESIZE_SIZE，可参考这个文档 https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.4.0/docs/data_aug.md

好的，非常感谢！

**Comment by ljx111** [comment]
> 应该是类别数的设置跟实际的类别数不一致，建议检查一下`DATASET.CLASS_NUMBER`这个配置项。
> 关于TRAIN_CROP_SIZE，EVAL_CROP_SIZE和FIX_RESIZE_SIZE，可参考这个文档 https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.4.0/docs/data_aug.md

确认了一下，类别数没有问题，还有可能是其它原因吗？

**Comment by LutaoChu** [comment]
你有运行数据配置校验吗？check.py，可以看下是否能通过

**Comment by ljx111** [comment]
> 你有运行数据配置校验吗？check.py，可以看下是否能通过

非常感谢！问题已经解决了，我之前以为我的标签图片只有0像素和38像素所以类别为2，经过一番摸索后发现这样的类别数应为39。

**Comment by LutaoChu** [comment]
不客气~ 设置为39是可以跑的。但如果想要更好的效果，可以把像素值38的部分替换为1，再把类别数设为2
