### ISSUE TITLE
关于推理部分出现的BUG

### ISSUE THREAD

**Issue by xiaodaomingye459** [PaddlePaddle/PaddleSeg#2167]
![image](https://user-images.githubusercontent.com/83204995/170969692-85d286f3-fc1c-4b6b-9620-6e42b8b39db5.png)
![image](https://user-images.githubusercontent.com/83204995/170969750-17e8d565-8197-42de-998a-18332d86d122.png)

**Comment by xiaodaomingye459** [comment]
我按照说明文档进行实验，但是不知道在哪测试FPS，遇到了如上的问题。

**Comment by juncaipeng** [comment]
这是由于校验paddle和onnx模型输出是否存在误差，你可以将如下代码的atol设置大一点，比如1e-2。
![image](https://user-images.githubusercontent.com/52520497/171079378-b8b498d8-9fc1-4a69-ada7-8ce84cffd4d7.png)

**Comment by xiaodaomingye459** [comment]
将atol设置成1e-2后出现如下问题，如何解决？
![image](https://user-images.githubusercontent.com/83204995/171165309-6fb15659-4d45-4991-b2aa-58fd9a478131.png)

**Comment by xiaodaomingye459** [comment]
您好，上面的问题是由于tensorrt的版本BUG我已经解决。
![image](https://user-images.githubusercontent.com/83204995/171343264-b3d3b217-d781-4008-a8a3-a4633e3baa4d.png)

然后关于这里的测试结果是平均时延，论文的指标为FPS，如果计算这里的倒数，也与论文PP-LiteSeg-B1 1024X512的195.3相差很多，请问这可能是什么原因造成的？

**Comment by juncaipeng** [comment]
这个跑出来fps差距有点大，是不是这个显卡也有其他进程在运行？

**Comment by xiaodaomingye459** [comment]
您好，在cityscapes上我的测速达到了论文效果，但是想在camvid数据集上测速时，却遇到了如下问题：
![image](https://user-images.githubusercontent.com/83204995/172371249-cceab91f-d7f3-46b5-9595-7435c5845b06.png)
意思是缺少类别数，请问要在哪里修改。

**Comment by juncaipeng** [comment]
由于最近更新，引入了bug，修复pr：https://github.com/PaddlePaddle/PaddleSeg/pull/2200

**Comment by xiaodaomingye459** [comment]
万分感谢！
