### ISSUE TITLE
自定义数据集

### ISSUE THREAD

**Issue by caomao1111** [PaddlePaddle/PaddleSeg#2177]
您好，我使用自定义数据集做二分类的分割任务，然后数据集标签确定是由0和1组成（程序测试过）,但在进行模型训练和测试时Dataloader读取的label却是0和255，不知道这是为何

**Comment by shiyutang** [comment]
Please try to read the image from the dataset directly, and use pdb to see where the place that the labels changed. It could be the image transform, but we are not sure either. The example code is as follows:
```
def get_item():
    import pdb; pdb.set_trace()
    image, label = ...
    # check labels here and the following places

dataset = MyDataset(transform=...) # set params as the traning code

for image, label in dataset:
    ...
```

**Comment by Suzi1213** [comment]
> 您好，我使用自定义数据集做二分类的分割任务，然后数据集标签确定是由0和1组成（程序测试过），但在进行模型和测试时Dataloader读取的标签却是0和训练255，不知道这是为什么

您好，请问您这个二分类问题解决了嘛，目前我也是做的二分类，但是我不知道怎么去预测，我的预测结果是一张全色图。
