### ISSUE TITLE
[General Issue]推理结束如何有效释放GPU内存

### ISSUE THREAD

**Issue by wangyidong3** [PaddlePaddle/PaddleSeg#2179]
欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：PaddleSeg release/2.5
 2. PaddlePaddle版本：（PaddlePaddle 2.2.0）
 3. 操作系统信息：（如Linux/）
 4. Python版本号：（如Python3.6）
 5. CUDA/cuDNN版本：（ CUDA10.2）
 6. 其他内容: （增加其他与问题相关的内容）

现在python程序中需要控制推理时间，timer时间到就退出模型推理，并释放内存。
而现在退出时，即使del predictor及相关变量， 并 gc.collection  后，内存仍然无法释放。

请问有什么好的办法让模型unload， 并释放内存 吗？

谢谢。

**Comment by juncaipeng** [comment]
paddle没有提供接口释放显存，默认是进程推出后才释放显存。
不过，你可以试下python执行shell命令"fuser -k /dev/nvidia_id"，看是否可以清空gpu上显存。

**Comment by wangyidong3** [comment]
谢谢及时回复。
1. "fuser -k /dev/nvidia_id" 是专门杀进程的， 因此python程序本身也会被kill。
2. 因此只能多线程来管理，并且paddle的线程必须独享gpu，但同时Paddle对python 的多线程处理MultiProcessing支持的不好，会出现 Cuda error(3), initialization error.
3. 虽然 https://github.com/PaddlePaddle/PaddleOCR/issues/3070  中提到用 torch.multiprocessing 替代 python的multiprocessing的解决办法, 但因为我这需要多平台，多种硬件，也包括jetson. rk, 这样，rk35xx 对torch.multiprocessing的限制也让多线程管理非常困难。
4. 现在看来暂时只能用container 来装载paddleseg，牺牲一下速度了。

如果有更好的办法，期待讨论。
