### ISSUE TITLE
unet示例预测图片问题

### ISSUE THREAD

**Issue by seoeye** [PaddlePaddle/PaddleSeg#218]
尊敬的技术人员：

      我用百度飞浆示例https://aistudio.baidu.com/aistudio/projectdetail/102889在ai studio中运行，示例的猫狗数据能成功的预测。于是我换用自己的数据，结果重新训练模型后，发现预测结果全黑。所以进行了以下步骤：

    1、使用paddleseg的伪彩色程序，检查了示例的猫狗数据，也检查了我的数据，发现我的数据只有红色、黑色两种，猫狗数据有红色 绿色 黑色三种。
    于是我用lableme重新对我的数据进行了标记，然后用lableme自带的工具导出为json文件夹，我的数据包含三个类别，其中有 backgroup nn rr
     2、在paddleseg文件中使用labelme2seg.py想把json导出为paddleseg数据集格式，然后获取不到我的分类，生成的annotations文件夹中也是空的。

win7 64 cmd给了管理员权限，标记文件json为d盘英文目录下

**Comment by seoeye** [comment]
现在用labelme2seg.py 后面跟着文件夹参数，获取到了分类，但是程序错误，提示85行错误 元组没有最大值最小值

**Comment by LutaoChu** [comment]
你好，这个问题已经在最新版本修复 #266 ， 更新代码即可

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。
