### ISSUE TITLE
[General Issue]deploy/python/infer.py 推理修改后stdc模型出现报错

### ISSUE THREAD

**Issue by huangwan-jiayi** [PaddlePaddle/PaddleSeg#2183]
PaddleSeg版本：版本号2.2.0分支PaddleSeg release/2.4）
PaddlePaddle版本：（如PaddlePaddle 2.2.0-gpu）
4. 操作系统信息：Linux Ubuntu18.04
5. Python版本号：python3.6
6. CUDA/cuDNN版本：cuda10.2，cudnn8.1
7. 使用depoly/python/infer.py 对训练cityscapes数据集导出的和stdc1-seg原模型和对网络模型修改后的stdc1-seg模型分别推理，都调用了trt精度都是fp16. 原模型可以正常推理，但是修改后的stdc模型调用trt进行推理时当把min_subgraph_size设置为3时报错：
![3f75a87b53ffce980316ce70bfbe885](https://user-images.githubusercontent.com/71338215/171540333-36a3bbeb-26ac-4ed0-985a-530318f739a4.png)
但把min_subgraph_size设置为20时可以推理，但是速度下降特别多。原模型186fps左右，改动后的模型只有27fps。

另外我想请教一个问题，使用depoly/python/infer.py进行推理，和我自己按照以下方法对模型进行推理有什么区别吗？那种预测推理方法才能正确反应模型的推理速度。
自己手动写的预测模型推理时间代码：（还没跑通）
![1a876a0bdc47d17bc28a68d38758677](https://user-images.githubusercontent.com/71338215/171542271-5aaa6638-e534-4195-9c6b-5e0197e32998.png)
![b6e52ca1834d29fabd5bc25b4ae0594](https://user-images.githubusercontent.com/71338215/171542290-a2127ed4-61c5-4d61-80c2-186ec3f9fe9d.png)

**Comment by juncaipeng** [comment]
你这个报错没有遇到过，你可以发一下你修改过stdcseg的预测模型，我们复现一下。

你这样预测，速度会更慢，导出预测模型后使用infer.py预测，会进行预测优化，速度更快。

**Comment by huangwan-jiayi** [comment]
> 你这个报错没有遇到过，你可以发一下你修改过stdcseg的预测模型，我们复现一下。
> 
> 你这样预测，速度会更慢，导出预测模型后使用infer.py预测，会进行预测优化，速度更快。
我用邮箱给你发相关材料，被拒收了。
![image](https://user-images.githubusercontent.com/71338215/172088068-c02c7ce2-ee82-4f19-9265-55cf1b620503.png)
导出来的模型太大了发不过来，怎么办。

**Comment by huangwan-jiayi** [comment]
> 你这个报错没有遇到过，你可以发一下你修改过stdcseg的预测模型，我们复现一下。
> 
> 你这样预测，速度会更慢，导出预测模型后使用infer.py预测，会进行预测优化，速度更快。

模导出型发过来了，收到了吗？麻烦

**Comment by juncaipeng** [comment]
没收到  你可以发到 pengjuncai@baidu.com

**Comment by huangwan-jiayi** [comment]
> pengjuncai@baidu.com

您好，已经发送过去，请查收。

**Comment by huangwan-jiayi** [comment]
> 没收到 你可以发到 [pengjuncai@baidu.com](mailto:pengjuncai@baidu.com)

请问您们收到了我发过去的邮件吗？有发现这是什么原因吗？

**Comment by juncaipeng** [comment]
我在paddlepaddle2.3环境下测试了该模型，开启TRT、使用fp16类型，可以跑通。所以你升级一下paddlepaddle版本。

**Comment by huangwan-jiayi** [comment]
> 我在paddlepaddle2.3环境下测试了该模型，开启TRT、使用fp16类型，可以跑通。所以你升级一下paddlepaddle版本。

您好，我将paddlepaddle升级成2.3后，训练模型开始报错，用python下的infer.py报其他的错。后来我将重新创建了一个环境，安装了paddle2.3GPU版本，paddleseg2.5，但是训练模型还是报错，infer.py还是报错。
具体报错：
训练模型：![db2843af42785b76a0ebeae97ed26f1](https://user-images.githubusercontent.com/71338215/175029305-c97d42ce-f231-4e8e-830f-55523daa1e2a.png)
报错：
![b4e423277adb37ec7af0bf269038919](https://user-images.githubusercontent.com/71338215/175029452-29bec001-b765-4c9d-9e5c-20e3f619750d.png)
推理报错：
![b06b4160152f7013e24eba8c6157d28](https://user-images.githubusercontent.com/71338215/175029451-8bcf49bf-5b04-4252-8315-97f9f3daad27.png)
![54e413087614ce0a67a739411df2bcb](https://user-images.githubusercontent.com/71338215/175029468-23114456-58eb-447b-9e6a-9428e26ecdcb.png)

**Comment by huangwan-jiayi** [comment]
> > 我在paddlepaddle2.3环境下测试了该模型，开启TRT、使用fp16类型，可以跑通。所以你升级一下paddlepaddle版本。
> 
> 您好，我将paddlepaddle升级成2.3后，训练模型开始报错，用python下的infer.py报其他的错。后来我将重新创建了一个环境，安装了paddle2.3GPU版本，paddleseg2.5，但是训练模型还是报错，infer.py还是报错。 具体报错： 训练模型：![db2843af42785b76a0ebeae97ed26f1](https://user-images.githubusercontent.com/71338215/175029305-c97d42ce-f231-4e8e-830f-55523daa1e2a.png) 报错： ![b4e423277adb37ec7af0bf269038919](https://user-images.githubusercontent.com/71338215/175029452-29bec001-b765-4c9d-9e5c-20e3f619750d.png) 推理报错： ![b06b4160152f7013e24eba8c6157d28](https://user-images.githubusercontent.com/71338215/175029451-8bcf49bf-5b04-4252-8315-97f9f3daad27.png) ![54e413087614ce0a67a739411df2bcb](https://user-images.githubusercontent.com/71338215/175029468-23114456-58eb-447b-9e6a-9428e26ecdcb.png)

挺急的，麻烦尽快帮忙看一下是什么问题，谢谢啦

**Comment by juncaipeng** [comment]
你的python版本是？  建议使用 python 2.7

**Comment by huangwan-jiayi** [comment]
> 你的python版本是？ 建议使用 python 2.7

是python3.7，用python2.7就能解决 训练模型出现报No stack in paddle，may be caused by external reasons的问题吗？

**Comment by juncaipeng** [comment]
不好意思，写错了，是建议使用python 3.7 sorry

**Comment by juncaipeng** [comment]
都是安装环境的问题啊

**Comment by juncaipeng** [comment]
只能参考官方安装文档查查：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/macos-pip.html

**Comment by huangwan-jiayi** [comment]
> 只能参考官方安装文档查查：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/macos-pip.html

恩恩 ，好的 十分感谢你的解答。
