### ISSUE TITLE
[General Issue]AssertionError: The backbone should has feat_channels. 高层API更换模型出现feat_channels问题

### ISSUE THREAD

**Issue by zhuangqirong** [PaddlePaddle/PaddleSeg#2186]
from paddleseg.models import PPLiteSeg
from paddleseg.models.backbones import STDC2

model = PPLiteSeg(num_classes=2, backbone=STDC2)

执行上述命令，会出现  AssertionError: The backbone should has feat_channels.

**Comment by juncaipeng** [comment]
请问你安装的paddleseg版本是？

https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/paddleseg/models/backbones/stdcnet.py#L55 改backbone有feat_channels啊

**Comment by JNU-IFM** [comment]
我也想问一下这个问题，请问你解决了吗

**Comment by JNU-IFM** [comment]
> 请问你安装的paddleseg版本是？
> 
> https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/paddleseg/models/backbones/stdcnet.py#L55 改backbone有feat_channels啊

我是安装的最新的，直接git clone 下来的

**Comment by juncaipeng** [comment]
需要改为： model = PPLiteSeg(num_classes=2, backbone=STDC2())

from paddleseg.models.backbones import STDC2 导入的STDC2是一个函数。
