### ISSUE TITLE
tensorrt 推演转换模型一直卡住

### ISSUE THREAD

**Issue by Tim4AI** [PaddlePaddle/PaddleSeg#2188]
欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（paddleseg 2.5）
 2. PaddlePaddle版本：（python -m pip install paddlepaddle-gpu==2.2.2.post101 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html）
 3. 操作系统信息：linux
 4. Python版本号：python 3.7
 5. CUDA/cuDNN版本：（ cuda 10.2 cudnn 8.0）

W0603 09:07:20.758460  1350 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.6, Runtime API Version: 10.1
W0603 09:07:20.762445  1350 device_context.cc:465] device: 0, cuDNN Version: 8.0.

home/tangzixing/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  return (isinstance(seq, collections.Sequence) and
2022-06-03 09:07:25 [INFO]      Static PaddlePaddle model saved in ./output/tmp/paddle_model_static_onnx_temp_dir.
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: ./output/tmp/paddle_model_static_onnx_temp_dir/model.pdmodel
[Paddle2ONNX] Paramters file path: ./output/tmp/paddle_model_static_onnx_temp_dir/model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Use opset_version = 11 for ONNX export.
[Paddle2ONNX] PaddlePaddle model is exported as ONNX format now.
2022-06-03 09:07:26 [INFO]      ONNX model saved in ./output/tmp/pp_liteseg_stdc2_camvid_960x720_10k_model.onnx.
Completed export onnx model.

The onnx model has been checked.
The onnx model has been predicted by ONNXRuntime.
The paddle and onnx models have the same outputs.

Loading ONNX file from path ./output/tmp/pp_liteseg_stdc2_camvid_960x720_10k_model.onnx...
Beginning ONNX file parsing
[TensorRT] WARNING: onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
Completed parsing of ONNX file
Building an engine from file ./output/tmp/pp_liteseg_stdc2_camvid_960x720_10k_model.onnx; this may take a while...

最后吐槽一句，这paddle推演实在难弄，各种难以匹配上，就不能像pytorch一样轻松部署么

**Comment by juncaipeng** [comment]
trt优化模型确实会耗时，是nvidia trt预测引擎的问题，这不是paddle的问题。
https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.5/configs/pp_liteseg#deployment
