### ISSUE TITLE
关于（1）图像预处理参数crop_size，（2）iters参数的设置

### ISSUE THREAD

**Issue by yanzhou-li** [PaddlePaddle/PaddleSeg#2189]
你好，我想请问一下在图像预处理环节中选择RandomPaddingCrop后，对参数crop_size的设置有什么原则和技巧吗？
我看在不同的数据集中，这个参数设置不同，比如在ade20k数据集中`crop_size=[512, 512]`，在Cityscapes中`crop_size= [1024, 512]`或`[769, 769]`或`[1024, 1024]`，在我看来同一个数据集下crop_size不同的设置不同的话，其对模型收敛的速度以及模型的精度会产生影响。
那么，我想求证一下，在选择多尺度训练方式（ResizeStepScaling）的情况下：`crop_size`参数的不同设置会对模型训练收敛的速度、以及模型的精度产生影响吗？另外，对模型的大小影响大吗？这个对不同数据集有没有经验参考值啊？

另外，还有个问题，关于对于ppliteseg训练迭代次数问题，该网络是否有对不同数据集提供参考的具体迭代次数建议，比如对任何数据集迭代次数满足`epoch=多少`即可收敛？（因为对不同数量的数据集设定iters很难去衡量其是否收敛，能否用epoch这个参数替代，能否给出ppliteseg网络的epoch参考值）

**Comment by juncaipeng** [comment]
crop_size越大，相当于单个batch输入训练的图像像素越多，其实这个参数对最后精度影响不大。如果crop_size变小了，可以适当增加iters。
epoch和iters需要自己经验调整。比如一开始使用50个epoch，换算为iters进行设置，观察训练曲线中loss是否一直在下降；如果loss一直稳定下降，那就增大iters；如果在训练后半部分loss一直稳定，那就可以减小点iters。

**Comment by yanzhou-li** [comment]
你好，李yanzhou已经收到你的邮件，谢谢！

**Comment by yanzhou-li** [comment]
你好，李yanzhou已经收到你的邮件，谢谢！

**Comment by shiyutang** [comment]
由于长时间没有回复，将关掉这条Issue。
