### ISSUE TITLE
在应用labelme2seg.py转化labelme生成的json过程，报错如下

### ISSUE THREAD

**Issue by rgbyuv** [PaddlePaddle/PaddleSeg#219]
在line 81,有判断语句：
            if lbl.min >= 0 and lbl.max() <= 255:
总是报错：‘tuple’ object has no attribute 'min'
看源码，不应该这样啊，请问是什么原因？

**Comment by LutaoChu** [comment]
是的，lbl应该是numpy的数组，不应该是tuple。
你可以检查一下是否是line 72这个函数的输入不对导致的
`lbl = labelme.utils.shapes_to_label(
                img_shape=img.shape,
                shapes=data['shapes'],
                label_name_to_value=class_name_to_id,
            )`
