### ISSUE TITLE
关于cityscapes

### ISSUE THREAD

**Issue by xiaodaomingye459** [PaddlePaddle/PaddleSeg#2191]
如果我想去官网提交cityscapes的测试结果，怎么通过您的框架得到对应的文件呢

**Comment by xiaodaomingye459** [comment]
还有一个问题，就是我自己调大batch_size后，为什么训练时间反而延长了，按理说每一次处理的图片多一些，训练时间应该要缩短才对吧。

**Comment by wuyefeilin** [comment]
cityscape的提交按照官网的要求机型数值的对应即可。

调大batch_size后iters一样吗，如果iters数一样，那么训练时间变长是合理的

**Comment by xiaodaomingye459** [comment]
您好，我还不明白怎么提交，按照说明文档我只能得到可视化的预测结果（彩色分割图），可是官网好像需要的是对应标签灰度图，而且是原本的30类。

另外，这个iters和batch_size的对应关系是什么样得，为什么反而会延长训练时间。

**Comment by wuyefeilin** [comment]
预测存储结果有伪彩色保存的图像，用PIL.Image进行读取即可得到预测的标签，即trainID, 你按照cityscapesScripts的标签转换成id重新保存即可， https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/helpers/labels.py

训练iters就是训练的steps， batch_size是每一次训练的图片数量，两者相乘是总的训练的图片次数，（iters*batch_size / 数据集图片数）等于训练的epochs， 若要保持训练的epochs不变，调大batch_size的同时需要调小iters，这样训练时间才能减小
