### ISSUE TITLE
[General Issue]

### ISSUE THREAD

**Issue by lsfhgty** [PaddlePaddle/PaddleSeg#2195]
https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.5/contrib/CityscapesSOTA   
Cityscapes的这个打榜模型有HRNet_W18_NV，HRNet_W32_NV和HRNet_W64_NV这几种不同大小backbone的预训练模型么，我看到conf里面用的是HRNet_W48_NV，然后readme里面也只给了HRNet_W48_NV的pretrain weights

这个是HRNet_W48_NV 的pretrain weights链接https://bj.bcebos.com/paddleseg/dygraph/cityscapes/ocrnet_hrnetw48_mapillary/pretrained.pdparams

**Comment by LutaoChu** [comment]
你好，目前没有其他大小的backbone预训练模型，HRNet_W48_NV是从nvidia那边转过来的
