### ISSUE TITLE
多卡训练参数问题

### ISSUE THREAD

**Issue by xiaodaomingye459** [PaddlePaddle/PaddleSeg#2196]
您好，在PP-Lite的配置文件中：我注意到默认是按照4卡配置的
![image](https://user-images.githubusercontent.com/83204995/172509431-e1024ceb-8211-446f-b5dc-d4a114157b2a.png)
双卡训练的话，是否只要保持总的batch_size一致就行了？其他的参数是否还需要修改。
对于损失里面的min_kept参数，我计算了一下默认是按单卡的batch_size配置的 ，这个参数需要修改吗？

**Comment by juncaipeng** [comment]
双卡训练，保持总bs相同就可以，不用改其他的参数。  min_kept也不需要修改。
