### ISSUE TITLE
[Bug] FatalError: Segmentation fault is detected by the operating system, while using PaddleSeg/Matting/deploy/python/infer.py on pretrained model

### ISSUE THREAD

**Issue by gohar-malik** [PaddlePaddle/PaddleSeg#2199]
1. PaddleSeg version: 
 Verison  = 2.5.0 branch PaddleSeg release/2.5
 
 2. PaddlePaddle version:
 PaddlePaddle 2.3.0, installed using `python -m pip install paddlepaddle-gpu==2.3.0.post110 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html`
 
 3. Operation system: 
 Linux: Ubuntu 18.04.6 LTS
 
 5. Python version: 
Python 3.8.12
 
 6. CUDA/cuDNN version:
 Using single Nvidia **Tesla T4**  gpu  Driver Version: 450.142.00  **CUDA: 11.0** **cuDNN: 8.0**
 
 7. Full codes: (if you modify any original code，please show the comparison of the codes before and after)
 Used the  [PaddleSeg/Matting/deploy/python/infer.py](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/Matting/deploy/python/infer.py) script as is, without any modification.
  
 8. Detailed error information, releated running log: (if using multi-gpus，the log is saved to log/worklog.0 by default)
 Complete log:
> 2022-06-08 12:45:19 [INFO]      using GPU
> W0608 12:45:20.975037 13809 analysis_predictor.cc:1086] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
> --- Running analysis [ir_graph_build_pass]
> --- Running analysis [ir_graph_clean_pass]
> --- Running analysis [ir_analysis_pass]
> --- Running IR pass [is_test_pass]
> --- Running IR pass [simplify_with_basic_ops_pass]
> --- Running IR pass [conv_bn_fuse_pass]
> I0608 12:45:24.043675 13809 fuse_pass_base.cc:57] ---  detected 305 subgraphs
> --- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
> I0608 12:45:25.144419 13809 fuse_pass_base.cc:57] ---  detected 28 subgraphs
> --- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
> --- Running IR pass [multihead_matmul_fuse_pass_v2]
> --- Running IR pass [gpu_cpu_squeeze2_matmul_fuse_pass]
> --- Running IR pass [gpu_cpu_reshape2_matmul_fuse_pass]
> --- Running IR pass [gpu_cpu_flatten2_matmul_fuse_pass]
> --- Running IR pass [gpu_cpu_map_matmul_v2_to_mul_pass]
> --- Running IR pass [gpu_cpu_map_matmul_v2_to_matmul_pass]
> --- Running IR pass [gpu_cpu_map_matmul_to_mul_pass]
> --- Running IR pass [fc_fuse_pass]
> --- Running IR pass [fc_elementwise_layernorm_fuse_pass]
> --- Running IR pass [conv_elementwise_add_fuse_pass]
> I0608 12:45:26.404754 13809 fuse_pass_base.cc:57] ---  detected 343 subgraphs
> --- Running IR pass [transpose_flatten_concat_fuse_pass]
> --- Running IR pass [runtime_context_cache_pass]
> --- Running analysis [ir_params_sync_among_devices_pass]
> I0608 12:45:26.449178 13809 ir_params_sync_among_devices_pass.cc:100] Sync params from CPU to GPU
> --- Running analysis [adjust_cudnn_workspace_size_pass]
> --- Running analysis [inference_op_replace_pass]
> --- Running analysis [memory_optimize_pass]
> I0608 12:45:26.605695 13809 memory_optimize_pass.cc:216] Cluster name : img  size: 12
> I0608 12:45:26.605736 13809 memory_optimize_pass.cc:216] Cluster name : shape_0.tmp_0  size: 16
> I0608 12:45:26.605741 13809 memory_optimize_pass.cc:216] Cluster name : relu_180.tmp_0  size: 72
> I0608 12:45:26.605752 13809 memory_optimize_pass.cc:216] Cluster name : bilinear_interp_v2_32.tmp_0  size: 576
> I0608 12:45:26.605758 13809 memory_optimize_pass.cc:216] Cluster name : relu_163.tmp_0  size: 144
> I0608 12:45:26.605765 13809 memory_optimize_pass.cc:216] Cluster name : batch_norm_313.tmp_2  size: 1024
> I0608 12:45:26.605772 13809 memory_optimize_pass.cc:216] Cluster name : relu_181.tmp_0  size: 144
> I0608 12:45:26.605782 13809 memory_optimize_pass.cc:216] Cluster name : relu_0.tmp_0  size: 256
> I0608 12:45:26.605789 13809 memory_optimize_pass.cc:216] Cluster name : relu_271.tmp_0  size: 2048
> I0608 12:45:26.605794 13809 memory_optimize_pass.cc:216] Cluster name : relu_155.tmp_0  size: 72
> I0608 12:45:26.605798 13809 memory_optimize_pass.cc:216] Cluster name : batch_norm_309.tmp_2  size: 2048
> I0608 12:45:26.605803 13809 memory_optimize_pass.cc:216] Cluster name : relu_270.tmp_0  size: 14400
> I0608 12:45:26.605810 13809 memory_optimize_pass.cc:216] Cluster name : batch_norm_307.tmp_2  size: 14400
> --- Running analysis [ir_graph_to_program_pass]
> I0608 12:45:27.063656 13809 analysis_predictor.cc:1007] ======= optimize end =======
> I0608 12:45:27.095818 13809 naive_executor.cc:102] ---  skip [feed], feed -> img
> I0608 12:45:27.111465 13809 naive_executor.cc:102] ---  skip [tmp_75], fetch -> fetch
>   0%|                                                                                                                                    | 0/34 [00:00<?, ?it/s]W0608 12:45:27.317579 13809 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 11.0
> W0608 12:45:27.319826 13809 gpu_context.cc:306] device: 0, cuDNN Version: 8.0.`
> 
> 
> C++ Traceback (most recent call last):
> No stack trace in paddle, may be caused by external reasons.
> 
> Error Message Summary:
> FatalError: Segmentation fault is detected by the operating system.
>   [TimeInfo: *** Aborted at 1654692330 (unix time) try "date -d @1654692330" if you are using GNU date ***]
>   [SignalInfo: *** SIGSEGV (@0x0) received by PID 13809 (TID 0x7f3d489c5740) from PID 0 ***]
> 
> Segmentation fault (core dumped)

 9. Running command or reproduce details:
 - Installed all requirements using the installation section of Matting Readme [here](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.5/Matting#:~:text=Deployment%20in%20Android-,Installation,-1.%20Install%20PaddlePaddle).
 - Used the PP-Matting-512 pretrained model provided [here](https://paddleseg.bj.bcebos.com/matting/models/deploy/pp-matting-hrnet_w18-human_512.zip)
 - Command (ran from a conda env):
 `python Matting/deploy/python/infer.py --config /home/ubuntu/BG_Remover/PaddleSeg/Matting/pretrained_models/pp-matting-hrnet_w18-human_512/deploy.yaml --image_path /home/ubuntu/BG_Remover/gohar_testing_samples/originals/ --save_dir /home/ubuntu/BG_Remover/gohar_testing_samples/ppm_512_results/ --fg_estimate True`
 
 10. Additional context: (Add any other context about the problem)
 The [prediction ](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.5/Matting#:~:text=val.py%20%2D%2Dhelp-,Prediction,-export%20CUDA_VISIBLE_DEVICES%3D0)script is running fine on checkpoint models provided in this [column](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.5/Matting#:~:text=Checkpoint-,Inference%20Model,-PP%2DMatting%2D512).

**Comment by haoyuying** [comment]
This may caused by cuda, cudnn and paddle versions do not match. Please check the paddle can work normally in your environment.

**Comment by gohar-malik** [comment]
Hi @haoyuying 
As I said the predict.py in Matting is working completely fine for me, as described [here](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.5/Matting#:~:text=val.py%20%2D%2Dhelp-,Prediction,-export%20CUDA_VISIBLE_DEVICES%3D0). 
And I have also tested the installation using the steps proposed [here](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/docs/install.md#:~:text=5.-,Verify%20Installation,-In%20the%20root). The script ran fine for me as well.
So I think the installation is fine, I am only getting this error on the deploy/infer.py script [here](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.5/Matting#:~:text=export.py%20%2D%2Dhelp-,Deploy,-python%20deploy/python).

**Comment by wuyefeilin** [comment]
Sorry， I can not recurrent you problem. It run correctly.

I run it on paddlepaddle-gpu==2.3.0, cuda: 10.2, cudnn 7.6. May be you can try this environment.

**Comment by gohar-malik** [comment]
Thanks for your help @wuyefeilin and @haoyuying.
I changed the environment. I am using paddlepaddle-gpu==2.3.0, cuda: 11.2, cudnn 8.1. Also, I am using the docker image now instead of installing using pip and its working okay.
closing this issue now.

**Comment by enddlesswm** [comment]
I got this problem too ! paddlepaddle-gpu==2.3.2.post110  cuda==11.0 cudnn==8
