### ISSUE TITLE
paddleslim如何执行这一步

### ISSUE THREAD

**Issue by jaffe-fly** [PaddlePaddle/PaddleSeg#221]
![image](https://user-images.githubusercontent.com/49515380/79183868-43967b00-7e45-11ea-91bc-c2ed43cca260.png)

训练完的best_nodel下保存很多参数，但是怎么转换成train_prog?train_prog?

**Comment by jaffe-fly** [comment]
大佬们 帮忙看看   如果自己用静态方法写网络 会有这个参数 但是用下面方法训练的 这个train_prog在哪儿
!python PaddleSeg/pdseg/train.py  --cfg PaddleSeg/configs/hrnet_optic.yaml

**Comment by LielinJiang** [comment]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.4.0/pdseg/train.py#L256, 这里就已经获取了tran_prog了，可以把上述截图的语句加在这个后面，就可以打印出网络的所有参数名和维度。
