### ISSUE TITLE
[General Issue] No module named 'paddle'

### ISSUE THREAD

**Issue by deepakkupanda** [PaddlePaddle/PaddleSeg#2210]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: Trying to install paddleseg
 2. PaddlePaddle version: yet to install
 3. Operation system:  Linux in AzureML
 4. Python version: Python3.7.7
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: 
 
<img width="765" alt="image" src="https://user-images.githubusercontent.com/41481181/173186167-a6a55d3d-dfaf-4df8-bcae-194b291b7dc7.png">

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by juncaipeng** [comment]
You should first install paddle, and then install paddleseg.

https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/docs/install.md

**Comment by deepakkupanda** [comment]
It worked for me after installing the paddle with right CUDA and cudnn
https://www.paddlepaddle.org.cn/documentation/docs/en/install/pip/windows-pip_en.html
