### ISSUE TITLE
[Bug]keyerror in prepare.py when preprocess data

### ISSUE THREAD

**Issue by JayceWen** [PaddlePaddle/PaddleSeg#2212]
this bug happens due to the fact that there exists different types of data parsing in prepare.py in MedicalSeg.Here the 442th line is original code and the 441th line is modified code which is same with the one in second image. 
![image](https://user-images.githubusercontent.com/53989593/173222254-90416a8b-7405-4aca-8971-b75b39eb705f.png)
![image](https://user-images.githubusercontent.com/53989593/173222363-6c0c2012-5f2b-43d9-81ed-c97c95345b53.png)

**Comment by shiyutang** [comment]
Thank you for pointing this out, you can put forward a PR and help us fix this.
