### ISSUE TITLE
[Bug]：载入大尺寸图片启动宫格功能，连续点击两次左上角完成宫格程序自动退出

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/PaddleSeg#2213]
Thanks for your bug report. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Full codes: (if you modify any original code，please show the comparison of the codes before and after)
 7. Detailed error information, releated running log: (if using multi-gpus，the log is saved to log/worklog.0 by default)
 8. Running command or reproduce details：
 9. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本： release/2.5
 2. PaddlePaddle版本：PaddlePaddle 2.2.0
 3. 操作系统信息：Windows10
 4. Python版本号：3.7
 5. CUDA/cuDNN版本：
 7. 详细的错误信息、相关log：载入大尺寸图片启动宫格功能，连续点击两次左上角完成宫格程序自动退出， 命令行终端爆出的错误为： AttributeError: 'NoneType' object has no attribute 'splicingList'

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
