### ISSUE TITLE
统计模型flops和params

### ISSUE THREAD

**Issue by caomao1111** [PaddlePaddle/PaddleSeg#2216]
请问paddleseg如何统计模型的flops和params
我原来直接使用paddle.flops统计paddleclas里的模型是没问题的，但统计paddleseg模型时报错
  "Your model must be an instance of paddle.nn.Layer or paddle.static.Program."

**Comment by shiyutang** [comment]
不知道你是统计哪个模型出错呢？ 预期是不会出错的，如果出错可以联系我们修复

**Comment by caomao1111** [comment]
统计的BiseNetV2

**Comment by shiyutang** [comment]
能否提供一个复现指令，或者复现脚本？ 我们复现并修复～

**Comment by caomao1111** [comment]
import paddle
from paddleseg.models.bisenet import BiSeNetV2
net=BiSeNetV2
input_sizer=[1,3,512,512]
paddle.flops(net, input_size=input_sizer, print_detail=True)
用这个统计paddleclas分类模式是没有出错的
