### ISSUE TITLE
CutMix图像增强

### ISSUE THREAD

**Issue by srzxDragon** [PaddlePaddle/PaddleSeg#2218]
# CutMix图像增强
- [CutMix](https://arxiv.org/abs/1905.04899v2): Regularization Strategy to Train Strong Classifiers with Localizable Features
- 在图像分割中使用CutMix图像增强，效果确实还挺好的，希望能在图像增强中增加这个功能，谢谢。

**Comment by wuyefeilin** [comment]
感谢您的建议，我们会尽快进行评估
