### ISSUE TITLE
 vision transformer中输入图像的维度问题 [General Issue]

### ISSUE THREAD

**Issue by a123b12cd** [PaddlePaddle/PaddleSeg#2221]
paddleseg2.5 
paddlePaddle 2.1.0
Linux
Python3.7
cuda11.2

用VisionTransformer作为backbone，输入的图像宽高必须相等吗？

![1](https://user-images.githubusercontent.com/49675099/173548282-37ec1a51-d4d1-4f58-aedc-84f68b313cc2.png)

**Comment by wuyefeilin** [comment]
不需要哈

**Comment by a123b12cd** [comment]
> 不需要哈

那应该怎么配置 img_size  直接写数组报错，如果裁剪就影响效果了
![微信截图_20220615105412](https://user-images.githubusercontent.com/49675099/173726793-6cae2d0b-0417-4475-9ad7-084e1b56e471.png)

**Comment by wuyefeilin** [comment]
img_size主要是跟pos-embed有关，这个参数只能是整数。 在forward的时候对x的shape是不做要求的。

**Comment by shiyutang** [comment]
可以自行修改对应代码，使其可以传入数组，一般需要为patch_size的整数倍。

**Comment by a123b12cd** [comment]
看代码差不多明白了，谢谢
