### ISSUE TITLE
[General Issue] The number of model parameters and computation

### ISSUE THREAD

**Issue by fanxiaochen456** [PaddlePaddle/PaddleSeg#2224]
求教，我想像pytorch一样加载Paddle2.0训练好的模型参数model.pdparams，运用Summary函数可以输出参与训练的参数量和总的模型参数量，请问该怎么写呢？ The number of parameters involved in the training and the total number of parameters in the model can be displayed by using the Summary function.

import paddle
save_path = "model.pdiparams"
model = paddle.load(save_path)

This is the quantized model. Pdiparams. I want to output the number of parameters and computations output by him to predict a picture, that is, to perform a model inference operation, so as to select the development board with the appropriate computation power.

**Comment by haoyuying** [comment]
具体使用可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/summary_cn.html#summary

**Comment by fanxiaochen456** [comment]
@haoyuying 您好，我就是参考的那个文档来改写代码，但加载模型时就不对了，这是我量化之后的输出，请问我该怎么加载model.pdiparams文件呢，然后像文档里那样运用summary输出参数量呢？

这是量化之后的输出
![image](https://user-images.githubusercontent.com/101849755/174037543-db8eef57-b0d2-4eb1-82d1-34d6276f7d6c.png)

**Comment by fanxiaochen456** [comment]
@haoyuying 这是paddle2.0环境下量化的模型

**Comment by haoyuying** [comment]
pdmodel和pdiparams是静态图模型和参数，用paddle.jit.load()或者paddle inference进行加载，静态图参数量输出没找到相应的API，可以去paddle的repo下提问以便获取更精确的回复。

**Comment by fanxiaochen456** [comment]
@haoyuying 请问paddle的repo是什么
