### ISSUE TITLE
关于ppliteseg耗时问题

### ISSUE THREAD

**Issue by yanzhou-li** [PaddlePaddle/PaddleSeg#2225]
关于ppliteseg算法耗时，如果送入网络的图像尺寸改变，在我看来，网络的推理耗时会有所不同，但是ppliteseg算法推理耗时却变化不大，这是为什么？
我用512*512、2048*2048大小的图像分别测试ppliteseg算法的推理耗时，发现数值变化不大，都维持在15ms左右，这是为什么？

**Comment by juncaipeng** [comment]
你好  你测试的脚本和命令是什么？

**Comment by juncaipeng** [comment]
请导出预测模型再测试，不要使用动态图模式下测速。

**Comment by yanzhou-li** [comment]
好的，感谢，导出静态图模型测试，推理时间是准的了
