### ISSUE TITLE
运行分割模型pspnet报错

### ISSUE THREAD

**Issue by peach-xiao** [PaddlePaddle/PaddleSeg#2226]
我在使用PSPNet运行自己的数据集，实在是没有找到为什么optimizer.step()这里会出现TypeError: 'str' object is not callable错误，我尝试着将Image和label的值都打印出来查看了，里面是有值的，计算的loss也是有值的，这可能是哪里出现了问题呢？希望可以得到帮助

注意：我没有改动任何和模型有关的文件，仅仅修改了配置相应的.yml文件和加载数据集的.py文件，下面是报错的信息：

![image](https://user-images.githubusercontent.com/40911688/174019955-7d45595a-c704-4c45-a3d7-9007039eb7d6.png)
![image](https://user-images.githubusercontent.com/40911688/174020003-00402134-2491-4b4b-9407-d381d8890258.png)

这是我加载的数据集文件（已做修改）
![image](https://user-images.githubusercontent.com/40911688/174020226-8da05d11-f317-48fe-9368-ab6cc210ec52.png)
![image](https://user-images.githubusercontent.com/40911688/174020328-4de151cc-cc4f-4e76-b195-aaac63102f48.png)

配置文件pspnet.yml信息

![image](https://user-images.githubusercontent.com/40911688/174020668-edde9de4-8225-417c-a5e0-969643a3d96f.png)
![image](https://user-images.githubusercontent.com/40911688/174020749-1c36f466-baab-4358-a460-9f4847dea4fe.png)

期待您的回复，万分感谢！！！

**Comment by wuyefeilin** [comment]
![image](https://user-images.githubusercontent.com/30919197/174211990-08d41cb6-b181-45ff-8cc2-7df06aec24e4.png)
这个改成1.0e-4
