### ISSUE TITLE
Has PP-LiteSeg  ran on the phone realtime？

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/PaddleSeg#2227]
hi，
请问下PP-LiteSeg  和PP-HumanSeg 都在手机上跑过吗？或者其他小型平台上跑过实时吗？
有木有相关的介绍 链接分享下呢？ 多谢
[PP-LiteSeg](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/configs/pp_liteseg)
BR

**Comment by juncaipeng** [comment]
这个和图像尺寸相关，你可以试试。

同时在develop分支，我们推出了多个适用于移动端的分割模型：https://github.com/PaddlePaddle/PaddleSeg/tree/develop/configs/mobileseg

**Comment by 2050airobert** [comment]
那请问，paddleseg跑过哪几个尺寸的该模型，在哪种平台上，可否分享下实验结果？

**Comment by 2050airobert** [comment]
hello，anyone here?

**Comment by juncaipeng** [comment]
任何尺寸都是支持的。 
输入是224x224，单线程下， ppliteseg在手机上是40~50ms，上面提到移动端的分割模型是20ms左右。  具体也和手机有关系。

**Comment by 2050airobert** [comment]
您是说 比如第一个model
![image](https://user-images.githubusercontent.com/8407513/174578510-cd6ea0be-233d-4ead-a57b-9b7d8fcacf50.png)
mobimobilenet v2 就是在移动端跑的，分辨率1024x512 在选定的手机上实测20ms左右 分割模型耗时，对吗？

**Comment by juncaipeng** [comment]
是的   小米9上测试的

**Comment by 2050airobert** [comment]
perfect ， 是小米9 骁龙855处理器 ARM  1×2.84GHz+3×2.42GHz+4×1.80GHz ,使用四个核同时开跑出来的20ms吗 ？
还是其他core上？

**Comment by juncaipeng** [comment]
是单核运行

**Comment by 2050airobert** [comment]
大核还是小核，具体是哪个core   " ARM 1×2.84GHz+3×2.42GHz+4×1.80GHz" ?
您能double check下具体是哪个模型 您跑的20ms 单核吗？
比如下面图所示的您测过的模型列表，具体是哪个，能给出官方无误确认吗？多谢啦 (因为1024x512还是蛮大的感觉，所以希望您能好好确认再回复)
![image](https://user-images.githubusercontent.com/8407513/174755928-bbebf0d6-083b-4c11-b454-fa01db12a699.png)

**Comment by juncaipeng** [comment]
> 任何尺寸都是支持的。 输入是224x224，单线程下， ppliteseg在手机上是40~50ms，上面提到移动端的分割模型是20ms左右。 具体也和手机有关系。

输入是224x224啊

**Comment by 2050airobert** [comment]
分辨率咱们确定了哈224x224:
1  ppliteseg在手机上是40~50ms
2 上面提到移动端的分割模型是20ms
   (1)您这里指的是ppliteseg这个模型的另外版本还是其实就是这个模型224x224 ppliteseg ？ 
   (2)您这里的移动端不就是手机吗？ 难道你想突出的是 这里的手机可能跟1种提到的手机不是同一款？
   (3)这里的手机上测试的20ms，是指在arm cpu上还是npu上？

**Comment by juncaipeng** [comment]
1）就是ppliteseg模型，测试数据的输入尺寸是224x224
2) 移动端就是手机，同一款
3）arm cpu上
