### ISSUE TITLE
修订类型不一致

### ISSUE THREAD

**Issue by rgbyuv** [PaddlePaddle/PaddleSeg#223]
是的，lbl应该是numpy的数组，不应该是tuple。
你可以检查一下是否是line 72这个函数的输入不对导致的
`lbl = labelme.utils.shapes_to_label(
                img_shape=img.shape,
                shapes=data['shapes'],
                label_name_to_value=class_name_to_id,
            )`

_Originally posted by @LutaoChu in https://github.com/PaddlePaddle/PaddleSeg/issues/219#issuecomment-613200572_

通过调试，可以知道是类型没有转换导致。                                                              
1. labelme2seg.py 以及jingling2seg.py,是数据转换工具，对使用者就是个黑盒子，出现这个问题，是我调试过程的单独问题？   如果是我单独问题，请告知正确的使用方法，以飨众人。                                                                                                              
2.请问在这两个工具脚本测试过程没有产生这个问题吗？                                                       
3.如果存在，请你帮忙修订，毕竟有很多人用，影响使用

**Comment by LutaoChu** [comment]
感谢反馈！这两个脚本在之前的测试使用过程并没有出现这个问题。
请确定一下是不是标注流程的问题，是否按照这个教程来https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.4.0/docs/annotation/labelme2seg.md
如果标注流程没问题，请提供几张标注工具产出的json等文件，我这边检查下代码的问题。

**Comment by rgbyuv** [comment]
调试过程：
脚本是版本库中tools目录下的labelme2seg.py，
Json文件是docs/annntoation/labelme_demo/中JSON文件，                                                              
但就是会报错‘tuple’ object han no attribute  'min' ,                                                                             查资料说是numpy自身有这个问题，可是在labelme源码库中调试正常，所以一起确认这个问题到底怎么导致的，谢谢!

**Comment by rgbyuv** [comment]
lbl = labelme.utils.shapes_to_label( img_shape=img.shape, shapes=data['shapes'], label_name_to_value=class_name_to_id, )，                                                                                             
这个函数的使用方法有误，labelme.utils.shapes_to_label函数源码可以知道，返回值是直接返回多个值，不是包装成列表，或者元组，所以lbl就返回为元组。
修订为：lbl，_ = labelme.utils.shapes_to_label( img_shape=img.shape, shapes=data['shapes'], label_name_to_value=class_name_to_id, )就行了，                                                                              
labelme2seg.py测试代码是怎么样？

**Comment by LutaoChu** [comment]
找到原因了，因为labelme的版本升级导致的。之前的labelme返回的是单个numpy array，现在最新的labelme返回多个值。
感谢! 我们马上修复这个问题
