### ISSUE TITLE
[Feature Request] Support APCNet

### ISSUE THREAD

**Issue by Junjun2016** [PaddlePaddle/PaddleSeg#2232]
Please support [APCNet ](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/apcnet).

**Comment by shiyutang** [comment]
We have added this model to our future model list, and expect to add it in PaddleSeg before September.

**Comment by shiyutang** [comment]
We already have paddle version outside of paddleseg：https://github.com/Dylan-get/APCNet
