### ISSUE TITLE
模型训练

### ISSUE THREAD

**Issue by lililikaixu** [PaddlePaddle/PaddleSeg#2241]
请问edgeflow的模型训练、网络搭建部分的算法在哪里呢？

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by wuyefeilin** [comment]
模型都放在了padleseg/models下面了，需要了解哪个模型可以查看相应的模型文件
