### ISSUE TITLE
多进程训练时 cfg.NUM_TRAINERS 和 cfg.TRAINER_ID 

### ISSUE THREAD

**Issue by jaffe-fly** [PaddlePaddle/PaddleSeg#225]
如果设置
cfg.NUM_TRAINERS = 4
cfg.TRAINER_ID = 0，1，2，3
`        if self.shuffle and cfg.NUM_TRAINERS > 1:
            np.random.RandomState(self.shuffle_seed).shuffle(self.all_lines)
            num_lines = len(self.all_lines) // cfg.NUM_TRAINERS
            self.lines = self.all_lines[num_lines * cfg.TRAINER_ID: num_lines * (cfg.TRAINER_ID + 1)]
            self.shuffle_seed += 1`
上面代码中的self.lines 时怎么取值的？

**Comment by zhupengyang** [comment]
看代码应该是等分成NUM_TRAINERS份后分别取值

**Comment by jaffe-fly** [comment]
后面那个切片没理解  自己写了个案列运行时报错的
因为cfg.TRAINER_ID = 0，1，2，3时是无法切片的

**Comment by LielinJiang** [comment]
在每个进程中，traner_id是等于0，1，2，3中的一个数的。比如进程1，那么trainer_id=0；进程2，trainer_id=1这样。

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。
