### ISSUE TITLE
[General Issue] Which One Should I Download?

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleSeg#2250]
Thanks for your issue. To help us solve the issue better, please provide the following information：
 1. PaddleSeg version: PaddleSeg release/2.5
 2. PaddlePaddle version: PaddlePaddle 2.3.0 (actually, I use docker image "registry.baidubce.com/paddlepaddle/paddle:2.3.0")
 3. Operation system: Linux
 4. Python version: Python 3.7.13
 5. CUDA/cuDNN version: None (I use the CPU version of the docker image)
 6. Additional context: None (Just see below).

Hi there, I find an ambiguous description in the [doc](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.5/contrib/PanopticDeepLab#cityscapes-1)

It says that we need `gtFine` and `leftImg8bit`, and download those datasets from [CityScapes website](https://www.cityscapes-dataset.com/).

But this description did not specifically give the full names of the datasets. 

Concretely, there are 2 dataset names containing `gtFine`:
1. gtFinePanopticParts_trainval.zip (474MB)
2. gtFine_trainvaltest.zip (241MB)

And, there are 10 dataset names involves `leftImg8bit` :
1. leftImg8bit_trainval_rain.zip (21GB)
2. leftImg8bit_trainextra_foggy.zip (40GB)
3. leftImg8bit_trainvaltest_foggy.zip (30GB)
4. leftImg8bit_trainval_foggyDBF.zip (20GB) 
5. leftImg8bit_allFrames_frankfurt.zip (241GB)
6. leftImg8bit_sequence_trainvaltest.zip (324GB)
7. leftImg8bit_blurred.zip (11GB)
8. leftImg8bit_demoVideo.zip (6.6GB)
9. leftImg8bit_trainextra.zip (44GB)
10. leftImg8bit_trainvaltest.zip (11GB)

Finally, Which two I should download? Please illustrate the full names of 'gtFine' and 'leftImg8bit'. 

Thank you!

**Comment by wuyefeilin** [comment]
leftImg8bit_trainvaltest.zip (11GB)     gtFine_trainvaltest.zip (241MB)
