### ISSUE TITLE
[Bug] 训练模型，报 No stack in paddle，may be caused by external reasons

### ISSUE THREAD

**Issue by huangwan-jiayi** [PaddlePaddle/PaddleSeg#2251]
---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（，PaddleSeg release/2.5）
 2. PaddlePaddle版本：（PaddlePaddle 2.3.0_GPU）
 3. 操作系统信息：（Linux）
 4. Python版本号：（Python3.7）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 8.1)
 训练模型出错:
![db2843af42785b76a0ebeae97ed26f1](https://user-images.githubusercontent.com/71338215/175194878-c074cec3-b9c4-4861-ad63-6f4e82d422a7.png)
![b4e423277adb37ec7af0bf269038919](https://user-images.githubusercontent.com/71338215/175194902-43715c76-3229-4d33-96e1-3aefcce1ea48.png)
用deploy/python/infer.py推理模型出错：
![b06b4160152f7013e24eba8c6157d28](https://user-images.githubusercontent.com/71338215/175194967-2f101f4a-a7b3-4593-a8b2-10aafe2c39cc.png)
![54e413087614ce0a67a739411df2bcb](https://user-images.githubusercontent.com/71338215/175194985-04bc9a4c-b860-4a35-a673-dad02eed7c3c.png)

**Comment by haoyuying** [comment]
该错误愿意存在于paddle, cuda,cudnn版本不匹配导致的，请重新卸载paddle，然后根据官网要求进行安装https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html

**Comment by huangwan-jiayi** [comment]
> 该错误愿意存在于paddle, cuda,cudnn版本不匹配导致的，请重新卸载paddle，然后根据官网要求进行安装https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html

好的，感谢你的解答。
