### ISSUE TITLE
Preloading Pseudo Labels in EISeg

### ISSUE THREAD

**Issue by aqx95** [PaddlePaddle/PaddleSeg#2252]
Thanks for having the EISEG annotation tool which i felt was really useful! 
I have one question regarding the tool. Will there be any feature for us to pre-load annotations for our images so that we don't need to start the annotation from scratch, instead we can begin our annotation from the pseudo labels that we have generated using some pretrained model?
Thank you!

**Comment by haoyuying** [comment]
sorry, we do not provide this feature, we only support to load labels  produced by eiseg.
