### ISSUE TITLE
[General Issue]PaddleSeg模型量化为Int8

### ISSUE THREAD

**Issue by fanxiaochen456** [PaddlePaddle/PaddleSeg#2253]
请问，PaddleSeg的模型支持Int8量化吗，我采用的主干是ResNet18，分割网络为DeepLabV3P，PaddleSeg项目中只看到了量化训练，但他保存下来依旧是FP32的精度，有没有什么可以仿照的脚本或其他的将训练好的模型量化为Int18的精度？

**Comment by juncaipeng** [comment]
训练完成后，是伪量化模型，参数是fp32类型，但是数值已经是整数了，该模型可以直接应用于部署了。

https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/docs/slim/quant/quant_cn.md#33-%E9%83%A8%E7%BD%B2%E9%87%8F%E5%8C%96%E6%A8%A1%E5%9E%8B

**Comment by fanxiaochen456** [comment]
@juncaipeng 谢谢您，那请问怎样可以输出量化后模型的参数量呢，比如模型进行一次推理需要加载多少参数量呢？

**Comment by fanxiaochen456** [comment]
@juncaipeng 您说的量化训练之后是参数是整数类型，Int包括Int64,Int32,Int8，请问量化后的是属于哪一种呢，或者是他是否属于哪种Int类型取决于用来量化的模型的数值类型呢？

**Comment by juncaipeng** [comment]
参数量不好统计，不过你可以查看模型体积，使用zip压缩后，预测模型体积会减小为1/4。

是int8

**Comment by walletiger** [comment]
> 伪量化模型

伪量化模型如何转换成 int8 类型模型呢？
