### ISSUE TITLE
[General Issue] 文档中关于数据增强的方式不明确

### ISSUE THREAD

**Issue by Liyulingyue** [PaddlePaddle/PaddleSeg#2254]
README_CN.md中没有找到明确的关于transforms内容和写法的说明，希望可以补充或者提供相关介绍页面。

**Comment by haoyuying** [comment]
请参考这里：https://github.com/PaddlePaddle/PaddleSeg/blob/457af2edb51a3c85ac9fd019e564c4099b1ee8bd/docs/apis/transforms/transforms_cn.md
