### ISSUE TITLE
CrossEntropyLoss的weights设置后报错

### ISSUE THREAD

**Issue by YangQiangli** [PaddlePaddle/PaddleSeg#2255]
![image](https://user-images.githubusercontent.com/49158046/175312083-e13683e5-9b3a-4164-a082-842ea600d485.png)

**Comment by haoyuying** [comment]
报错原因是cuda，cudnn和paddle版本不匹配，建议从此方向排查原因。

**Comment by YangQiangli** [comment]
> 报错原因是cuda，cudnn和paddle版本不匹配，建议从此方向排查原因。

thanks
