### ISSUE TITLE
PaddleSeg量化模型的Flops和Params

### ISSUE THREAD

**Issue by fanxiaochen456** [PaddlePaddle/PaddleSeg#2258]
您好，我使用PaddleSlim量化PaddleSeg的模型，
![image](https://user-images.githubusercontent.com/101849755/175763002-a583bdfa-e6e3-41a0-808f-a48561830f28.png)
请问我怎样可以输出该模型执行一次推理的参数量Params和他所进行的计算量Flops呢？使用的测试脚本是deploy/python/infer.py。

**Comment by juncaipeng** [comment]
已经导出为预测模型后，目前没有工具统计预测模型的params和flops。
