### ISSUE TITLE
paddleseg下的这几个语义分割模型适合用来分割发丝吗

### ISSUE THREAD

**Issue by lfxx** [PaddlePaddle/PaddleSeg#226]
用hrnet训练了一下，效果不是很理想

**Comment by lfxx** [comment]
是否考虑增加一些抠图模型，这些模型对目标边缘精度会比较高，如Deep image matting等抠图方向网络模型@LutaoChu

**Comment by LutaoChu** [comment]
目前PaddleSeg中的语义分割模型不适合做如此精细的分割任务。我们也在考虑增加matting的模型，不过仍在摸索阶段，敬请期待！

**Comment by lfxx** [comment]
> 目前PaddleSeg中的语义分割模型不适合做如此精细的分割任务。我们也在考虑增加matting的模型，不过仍在摸索阶段，敬请期待！

嗯，目前百度的商用级语义分割的发丝分割效果也是很差．期待matting模型早日到来
