### ISSUE TITLE
[General Issue]训练模型时报错。

### ISSUE THREAD

**Issue by huangwan-jiayi** [PaddlePaddle/PaddleSeg#2260]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (PaddleSeg release/2.5)
 2. PaddlePaddle version： PaddlePaddle 2.3.0)
 3. Operation system:  Linux（Ubuntu16.04）
 4. Python version: Python3.7
 5. CUDA/cuDNN version: CUDA11.2/cuDNN 8.2.0
 
系统环境截图:
![34ea8501c22fe27b367380615b4e0be](https://user-images.githubusercontent.com/71338215/175822599-bbf8e401-2217-4d3e-a531-9ef370d8c4d2.png)
报错截图：
![55ef8a23fd8d0617ef71b15d1c51860](https://user-images.githubusercontent.com/71338215/175822609-386d0554-683a-43ea-b50c-60834b8fb6b9.png)

**Comment by juncaipeng** [comment]
我在本地没有复现该问题，估计你的环境下存在的特殊错误。 
建议你找到错误行，如下修改。

```
self.laplacian_kernel = paddle.to_tensor(
            [-1, -1, -1, -1, 8, -1, -1, -1, -1], dtype='float32').reshape(
                (1, 1, 3, 3))
```
改为
```
self.laplacian_kernel = paddle.to_tensor(
            [[[-1, -1, -1], [-1, 8, -1], [-1, -1, -1]]], dtype='float32')
```

**Comment by huangwan-jiayi** [comment]
> 我在本地没有复现该问题，估计你的环境下存在的特殊错误。 建议你找到错误行，如下修改。
> 
> ```
> self.laplacian_kernel = paddle.to_tensor(
>             [-1, -1, -1, -1, 8, -1, -1, -1, -1], dtype='float32').reshape(
>                 (1, 1, 3, 3))
> ```
> 
> 改为
> 
> ```
> self.laplacian_kernel = paddle.to_tensor(
>             [[[-1, -1, -1], [-1, 8, -1], [-1, -1, -1]]], dtype='float32')
> ```
 

按照你说的那样修改后，紧接着的代码报错了。
![728ebfb57565e42da13821357fe03de](https://user-images.githubusercontent.com/71338215/175856050-980c635d-6c3a-4f7b-a4a6-cba3221617fd.png)
![cae5a17b3ce2b3d9cc55e35f1958c9c](https://user-images.githubusercontent.com/71338215/175856064-67cd016e-54ab-4f89-a259-292309196949.png)

**Comment by juncaipeng** [comment]
估计你安装paddle的问题，请参考飞桨官网检查安装的细节是否满足。
