### ISSUE TITLE
[Bug] Out of Memory on GPU 0. (RTX 3090 with 24gb)

### ISSUE THREAD

**Issue by fschvart** [PaddlePaddle/PaddleSeg#2261]
Thanks for your bug report. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: **2.5.0**
 2. PaddlePaddle version: **2.3.0**
 3. Operation system: **Windows**
 4. Python version: **Python 3.9**
 5. CUDA/cuDNN version: **11.2/8.3**
 6. Full codes: **Using original code, using custom dataset, batch size = 1 for DeepLabV3+, image size 768,1280**
 7. Detailed error information, while training, 10 seconds after I run the code, I get an out of memory error on GPU 0
 8. Running command or reproduce details：
 9. Additional context: (Add any other context about the problem)

I've seen this happens quite often but haven't seen any solution that works. Will appreciate your help!

**Comment by juncaipeng** [comment]
I think the training framework has OOM error for this environment, we will try to fix it.
Thanks.
