### ISSUE TITLE
PaddleSeg ONNX to OV int8 optimized doesn't show detection

### ISSUE THREAD

**Issue by hannaSkyrim** [PaddlePaddle/PaddleSeg#2262]
1. PaddleSeg version: PaddleSeg v2.5.0 (release/2.5)
 2. PaddlePaddle version: 2.3.0
 3. Operation system: Linux-5.13.0-51-generic-x86_64-with-glibc2.17
 4. Python version: 3.8.10
 5. CUDA/cuDNN version: NVCC: Build cuda_11.6.r11.6/ cudnn: 8.4
 6. Problem:

I want to quantize the model from ONNX to Openvino (OV) IR FP32 to INT8.
My current OV version is 2021.4.
After quantize with OV DL workbench for int8 optimization, there's no segmentation detected.
But with FP16 and FP32, it's working.
Is there specific steps to OV int8 optimize for PaddleSeg ?

**Comment by juncaipeng** [comment]
Sorry. PaddleSeg does not guarantee the quantized model be exported to onnx.
