### ISSUE TITLE
语义分割指标OA计算问题

### ISSUE THREAD

**Issue by peach-xiao** [PaddlePaddle/PaddleSeg#2263]
您好！我在使用PaddleViT设计自己的模型，对于实验的结果我遇到了一些问题，希望可以得到帮助。首先，因为PaddleViT和PaddleSeg计算评价指标的代码我都仔细看了，是一样的。可以查阅https://github.com/BRIDL/PaddleViT/blob/develop/semantic_segmentation/src/utils/metrics.py,

以下图片是我在数据集上的实验结果，框起来的是我用PaddleViT平台跑出来的实验结果。其余的FCN、PSPNet等模型是我自己的代码的结果。

![image](https://user-images.githubusercontent.com/40911688/175894733-d9dbd021-194e-4bb6-a9ee-9fccf01cf605.png)

OA和Miou的计算公式是:
![image](https://user-images.githubusercontent.com/40911688/175895809-c39411e2-161b-4be6-b51b-80ee97e51d94.png)
![image](https://user-images.githubusercontent.com/40911688/175895849-28f52bc7-08f2-458b-a4af-52008b61f238.png)

按理说mIOU值大的OA也应该高才对，从我的实验结果在的确是mIOU达到了最高，但是OA的指标是最低的，这很明显有问题

问题1：paddleseg/utils/metrics.py中的函数：def class_measurement: --- mean_acc是不是论文中常见的OA指标？如果不是，应该怎样通过三个参数intersect_area， pred_area， label_area实现呢

![image](https://user-images.githubusercontent.com/40911688/175897626-087abda4-7ab2-45b0-977f-c3be127145e7.png)

![image](https://user-images.githubusercontent.com/40911688/175896725-1860a8c4-6957-41ce-8883-222fc50b92f3.png)

问题2：能简单解释一下是Paddle怎么计算评价指标的吗？代码显示mIOU, OA都没有根据混淆矩阵计算，而是使用的三个参数： intersect_area， pred_area， label_area进行计算，对应于混淆矩阵应该怎样理解这三个参数呢，如intersect_area就是混淆矩阵对角线素元素和np.diag(hist)，其他的 hist.sum(axis=1) ，hist.sum(axis=0)又是怎么对应的呢？

问题3：以下是我在验证过程中使用的代码，是我的计算方式出问题了吗？上图中自己实现的一些模型FCN，PSPNet（没有使用paddle平台）等模型虽然mIOU的很低，但是mIOU相对较高？而我使用paddleViT运行的模型mIOU都达到了72.99，OA却只有85.73的情况？我想整合这两个评价指标。

在验证过程中调用评价指标函数
![image](https://user-images.githubusercontent.com/40911688/175902317-e3969c4b-5ede-4a51-86ab-3bd26173e6be.png)

评价函数具体实现：通过混淆矩阵计算
![image](https://user-images.githubusercontent.com/40911688/175901659-c46f522d-9b79-43c5-9078-d629d85ca33b.png)
![image](https://user-images.githubusercontent.com/40911688/175901732-8654f9e9-80ec-415b-a5f5-c05dabfc1000.png)
![image](https://user-images.githubusercontent.com/40911688/175901808-5047d2e3-9662-4883-8fec-e2402df0fde8.png)
![image](https://user-images.githubusercontent.com/40911688/175901831-353b67b2-278b-4385-9a95-83016e0a43b2.png)

感谢！万分感谢！我已经尝试了很久，还是未能解决该问题，希望能够得到帮助

**Comment by juncaipeng** [comment]
1.  mean_acc是等同于OA
2. PaddleSeg中计算的mIoU和mAcc方法等同于使用混淆矩阵计算
