### ISSUE TITLE
EISeg鼠标左击界面闪退

### ISSUE THREAD

**Issue by Amanda-Barbara** [PaddlePaddle/PaddleSeg#2272]
模型已经上传，标签也已添加，图像也已打开，当鼠标左键点击图像区域的时候EISeg界面出现闪崩，输出bug日志如下：
Traceback (most recent call last):
  File "/PaddleSeg/EISeg/eiseg/app.py", line 1628, in canvasClick
    self.controller.addClick(x, y, isLeft)
  File "/PaddleSeg/EISeg/eiseg/controller.py", line 214, in addClick
    pred = self.predictor.get_prediction(self.clicker)
  File "/PaddleSeg/EISeg/eiseg/inference/predictor/base.py", line 96, in get_prediction
    pred_logits, pred_edges = self._get_prediction(image_nd, clicks_lists,
  File "/PaddleSeg/EISeg/eiseg/inference/predictor/base.py", line 146, in _get_prediction
    self.input_handle_2 = self.net.get_input_handle(input_names[1])
IndexError: list index out of range

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1656486368 (unix time) try "date -d @1656486368" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x24d9066d001b916e) received by PID 1806702 (TID 0x7f24333f8740) from PID 1806702 ***]
在Linux系统中通过编译代码安装以及pip install eiseg两种方式都出现了上述同样的情况，请教一下如何解决？谢谢。

**Comment by haoyuying** [comment]
看起来是模型加载出现问题，请问您模型加载在状态栏出现了成功的语句吗？

**Comment by Amanda-Barbara** [comment]
@haoyuying 我看了下代码是不是不支持自己训练的模型啊，我试了官方提供的模型，是可以正常标注的，但是自己训练的模型只能加载成功，一旦点击左键开始标注的时候界面就闪崩了。

**Comment by Vicellken** [comment]
> @haoyuying 我看了下代码是不是不支持自己训练的模型啊，我试了官方提供的模型，是可以正常标注的，但是自己训练的模型只能加载成功，一旦点击左键开始标注的时候界面就闪崩了。

https://github.com/PaddlePaddle/PaddleSeg/issues/1678#issuecomment-1003689380

您好，我也有同样需求，加载自己训练的模型也有同样报错。
不确定官方什么时候会出详细一些的指导，小小期待一下❤️

**Comment by wangcker** [comment]
在 /Users/wangcker/opt/miniconda3/envs/aihealth/lib/python3.9/site-packages/eiseg/inference/predictor/base.py
第147行添加如下代码（找到自己的安装包目录对应的位置）
   input_names.append("coord_features")
#我猜下面这行也行
#input_names.append("coord_features_org") 
最终效果如下

> 144     def _get_prediction(self, image_nd, clicks_lists, is_image_changed):
> 145         print(self.net.get_input_names())
> 146         input_names = self.net.get_input_names()
> 147         input_names.append("coord_features")
> 148         self.input_handle_1 = self.net.get_input_handle(input_names[0])

即可正常使用，bug真多啊
