### ISSUE TITLE
[Feature Request]能否弄一个自动标注的py,自动转换为Labelme格式

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSeg#2280]
目前eiseg不支持自己训练模型

能否弄一个自动标注的py

训练好模型之后
可以自动标注
然后转换为 Labelme  json  格式

**Comment by W2YN** [comment]
同求转Labelme json 格式

**Comment by duduzai2019** [comment]
好难过呀，用eiseg标了好多天,然后发现它的json和labelme的不一样！！！，求解决，急，在线等！！！

**Comment by W2YN** [comment]
自己写个转的方法不就行了

**Comment by duduzai2019** [comment]
> 自己写个转的方法不就行了

你好，可以参考一下你的转换代码吗，我用eiseg标注生成的json格式和labelme的json格式不一样，搞了好几天都训练不了
谢谢
邮箱：1194864321@qq.com

**Comment by lijoe123** [comment]
> 

请问有这个代码吗

**Comment by lijoe123** [comment]
> > 自己写个转的方法不就行了
> 
> 你好，可以参考一下你的转换代码吗，我用eiseg标注生成的json格式和labelme的json格式不一样，搞了好几天都训练不了 谢谢 邮箱：[1194864321@qq.com](mailto:1194864321@qq.com)

请问有这个代码吗

**Comment by monkeycc** [comment]
@duduzai2019  @lijoe123 

目标检测 可以转换 LabelImg 

分割的话
还差最后一步
转换mask坐标点
再保存到json

**Comment by Harryoung** [comment]
related issue: #2805
