### ISSUE TITLE
[General Issue] edge计算的问题

### ISSUE THREAD

**Issue by justld** [PaddlePaddle/PaddleSeg#2283]
paddleseg==2.5.0
您好，loss_computation中的edges参数并未使用，请问是将edge的计算放到了损失函数里面吗。
https://github.com/PaddlePaddle/PaddleSeg/blob/35a4c4d229df2d4a5ca724ad442bf5e0f75b4823/paddleseg/core/train.py#L37

**Comment by juncaipeng** [comment]
该参数默认是没使用的。  如果你需要开启该参数，需要自己修改代码。
