### ISSUE TITLE
multi class label names

### ISSUE THREAD

**Issue by Ziyadmysterio** [PaddlePaddle/PaddleSeg#2295]
I have been doing multi class segmentation.The prediction results are really good but i cant find a way to map the predicted result. The predicted result only shows the segmented part in a image using different colors. I would like to know what do all those colors map to . If there is any way i can get the classified results in a text format or in the image itself. I would also like to know if the label names can also be mapped to the predicted images
![Screenshot from 2022-07-05 14-21-30](https://user-images.githubusercontent.com/54292052/177307259-c3f75b9e-b82a-4bca-87a7-113bae3f61de.png)

.

**Comment by wuyefeilin** [comment]
In PaddleSeg repo, it is not general to do this due to different segmentation tasks. If you need， you can fix the code to meet you requirement. 
You can know the class from the  number of predicted  result.

**Comment by Ziyadmysterio** [comment]
![Screenshot from 2022-07-06 15-03-30](https://user-images.githubusercontent.com/54292052/177536605-0d45f215-7f31-45dc-85e1-e8ed227061d4.png)

The value from infer.inference() method from core.predict.py returns this . How I get the number of predicted results(labels)

**Comment by wuyefeilin** [comment]
When you get a dataset, you know the relation between labels with class name. Correspondingly, when the prediction results are obtained, the class name can be known according to the predicted value, e.x. 0 is background generally.

**Comment by Ziyadmysterio** [comment]
*

**Comment by Ziyadmysterio** [comment]
Yes i got it thank you so much

**Comment by wuyefeilin** [comment]
Thank you for you approval
