### ISSUE TITLE
[General Issue] Training loss

### ISSUE THREAD

**Issue by kkpssr** [PaddlePaddle/PaddleSeg#2297]
训练loss越来越高，eval准确率召回率越来越低，前10个epoch结果还好(eval结果miou 0.6)，再跑10个epoch miou直接归0

**Comment by shiyutang** [comment]
训练结果不理想有很多原因导致，包含学习率过大，训练数据中出现脏数据等，建议给出数据集、模型、代码中修改内容等详细信息用于问题排查。
