### ISSUE TITLE
[自训练17类 语义分割，只有0像素（背景类） 有高的IOU值]

### ISSUE THREAD

**Issue by chenxi00a1** [PaddlePaddle/PaddleSeg#2298]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (PaddleSeg release/2.3)
 2. PaddlePaddle version: (paddlepaddle-gpu    2.3.0)
 3. Operation system: (Linux)
 4. Python version: (Python3.6)
 5. CUDA/cuDNN version: (CUDA11.2)
 6. Additional context: 
各位大佬好，最近在训练一个缺陷分割的 语义分割模型，自己标注了2000训练集，加上背景有17个类别，  现在简单跑了一下 pp_liteseg_optic_disc_512x512_1k.yml , 很奇怪 跑了5轮，只有0像素（背景类） 有高的IOU值 。  我是哪里配置不对吗？
![GBH}WJS ~EXYK `RL3`AT$7](https://user-images.githubusercontent.com/49149464/177721034-615273f5-5cec-4fd9-9890-be3a61a20acf.png)

34轮的时候，有2-3类别有一点点的iou
![_%99}XP4RB0QAOIG}PXOD1C](https://user-images.githubusercontent.com/49149464/177721035-76396c31-430f-4dc9-b61c-1afcbe5478dc.png)

注：应该修改的数据路径、num_class=17 这些设置没错。 
1 是否因为数据集不完善（目前标签为2、5、8像素的训练集数据量为0，我认为这并不影响训练）？
2 是否因为选择的loss 函数不对？ paddle对loss函数并没有做详细的注解。
3 是否因为数据集极度不平衡，0像素(背景) 类别是很多很多的
。。。有兴趣研究的大佬，可以找我要数据集，我已经划分好  本人V: chenxi00233。
---

**Comment by chenxi00a1** [comment]
# 数据类型设置  目前也没看出paddle的这几种数据读取的差异。
train_dataset:
  type: Dataset
  dataset_root: ./data/data_ys
  train_path: ./data/data_ys/train.txt
  num_classes: 17

**Comment by juncaipeng** [comment]
估计是你的数据及其不均衡，可以先分析一下所有标注图片中不同类别的像素占比。

**Comment by chenxi00a1** [comment]
您好，非常感谢您的分析。
确实是，数据集分布及其不均衡，但是背景像素 肯定会远远大于 缺陷像素，这有什么好一点的办法处理吗？





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月8日(星期五) 上午10:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleSeg] [自训练17类 语义分割，只有0像素（背景类） 有高的IOU值] (Issue #2298)



估计是你的数据及其不均衡，可以先分析一下所有标注图片中不同类别的像素占比。

**Comment by juncaipeng** [comment]
最好是处理数据，比如重采样。然后可以用diceloss会好点。

**Comment by chenxi00a1** [comment]
采样，这样的方式 对图片数据来说 是不是不友好？
这些 loss的选择，有官方文档 详细说明吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月8日(星期五) 上午10:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleSeg] [自训练17类 语义分割，只有0像素（背景类） 有高的IOU值] (Issue #2298)



最好是处理数据，比如重采样。然后可以用diceloss会好点。

**Comment by juncaipeng** [comment]
这部分没有，可以参考网上文档看看。
