### ISSUE TITLE
pp-lite-seg paddle_inference 运行报错

### ISSUE THREAD

**Issue by DavidQiuChao** [PaddlePaddle/PaddleSeg#2299]
----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The shape Op's Input Variable `Input` contains uninitialized Tensor.
  [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at C:\home\workspace\Paddle_release\paddle\fluid\framework\operator.cc:2004)

**Comment by chenxi00a1** [comment]
你这个跑的是 自己的模型吗？ 跑的是自己的数据吗?

**Comment by juncaipeng** [comment]
请贴一下你的复现代码。

**Comment by chenxi00a1** [comment]
您是要哪一块的代码呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月8日(星期五) 上午10:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleSeg] pp-lite-seg paddle_inference 运行报错 (Issue #2299)



请贴一下你的复现代码。

**Comment by juncaipeng** [comment]
预测代码。
