### ISSUE TITLE
关于roadline预训练模型的配置

### ISSUE THREAD

**Issue by MaybeShewill-CV** [PaddlePaddle/PaddleSeg#23]
请问可以提供关于roadline预训练模型的相关配置吗. 例如训练数据集信息,网络训练的输入图像尺寸等信息^^

**Comment by pennypm** [comment]
> 请问可以提供关于roadline预训练模型的相关配置吗. 例如训练数据集信息,网络训练的输入图像尺寸等信息^^

您好，车道线的训练数据集使用的是公司内部数据集，不是很方便公开呢。训练时使用stepscaling，输入图像crop_size是769x769 ^^

**Comment by MaybeShewill-CV** [comment]
@pennypm 非常感谢 关于训练方面还有更多细节可以公开或者可以在什么文档中查询吗.比如您说的这个crop的策略 然后crop size对应的原始训练的数据的分辨率是多大呢?

**Comment by pennypm** [comment]
@MaybeShewill-CV crop具体策略您可以看pdseg/data_aug.py里的rand_crop函数，训练数据原始分辨率是多样的，并不单一。训练细节的话，您是遇到了什么问题，可以讲具体一点吗

**Comment by MaybeShewill-CV** [comment]
@pennypm 是想使用自己的数据集训练模型 这https://aistudio.baidu.com/aistudio/projectdetail/115541这边只看到关于人像分割的训练说明 没有关于roadline的 所以想问下训练细节用自己的数据训练一下 感觉paddleseg比自己做的模型效果好点 哈哈
