### ISSUE TITLE
[Question] Paddle version and TensorRT version

### ISSUE THREAD

**Issue by huangwan-jiayi** [PaddlePaddle/PaddleSeg#2303]
请问一下，cuda11.2，paddlepaddle2.3.0gpu，支持python版本的tensorrt推理吗，如果支持，tensorrt与cuda与cudnn之间的版本应该怎么样搭配，我看官网上说只支持cuda10.1加tensorrt6或者cuda10.2加tensorrt7？

**Comment by juncaipeng** [comment]
可以参考[链接](https://www.paddlepaddle.org.cn/inference/user_guides/download_lib.html#python)下载安装

![image](https://user-images.githubusercontent.com/52520497/178174792-8e3bbe1c-1fd9-48de-9b6a-4a7e90487d90.png)

**Comment by xiaodaomingye459** [comment]
您好，上面这个截图的连接还有吗，我并没有找到对应的镜像文件。

**Comment by juncaipeng** [comment]
https://www.paddlepaddle.org.cn/inference/v2.4/guides/install/download_lib.html#python
