### ISSUE TITLE
[General Issue]paddleseg可否用cityscapes数据集的测试（test）集对训练后的模型进行评估，得到MIOU等指标，目前看只支持对验证集使用。

### ISSUE THREAD

**Issue by huangwan-jiayi** [PaddlePaddle/PaddleSeg#2309]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by haoyuying** [comment]
在cityscape数据集调用时将mode设置为test，具体代码可以参考https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/paddleseg/datasets/cityscapes.py#L51

**Comment by huangwan-jiayi** [comment]
您好，在config文件里将mode设置为test了，但是可能是因为数据集里test集没有标签，所以报这个错：
![image](https://user-images.githubusercontent.com/71338215/178295689-fd4d382c-9198-4873-8faf-96c3e1c69b84.png)
这样的话该如何解决呢？

**Comment by haoyuying** [comment]
必须要有test label的标签，不然要怎么计算iou呢

**Comment by huangwan-jiayi** [comment]
> 必须要有test label的标签，不然要怎么计算iou呢

我的意思就是，怎么才能获得cityscapes数据集的test集的label呢？
