### ISSUE TITLE
支持动态图编程

### ISSUE THREAD

**Issue by lartpang** [PaddlePaddle/PaddleSeg#231]
Paddle出了动态图，不知这个仓库准备支持么？

我是通过在这个仓库里搜索相关关键字而得到的结论。

都没有内容返回：
* https://github.com/PaddlePaddle/PaddleSeg/search?q=dygraph&unscoped_q=dygraph
* https://github.com/PaddlePaddle/PaddleSeg/search?q=%E5%8A%A8%E6%80%81&unscoped_q=%E5%8A%A8%E6%80%81

**Comment by wuyefeilin** [comment]
暂时不支持动态图，后续版本中将会对动态图进行支持，敬请期待！

**Comment by lartpang** [comment]
OK，支持一波！
