### ISSUE TITLE
[设置GPU为1号卡，不生效]

### ISSUE THREAD

**Issue by chenxi00a1** [PaddlePaddle/PaddleSeg#2310]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: 
 2. PaddleSeg version: (PaddleSeg release/2.3)
 3. PaddlePaddle version: (paddlepaddle-gpu 2.3.0)
 4. Operation system: (Linux)
 5. Python version: (Python3.6)
 6. CUDA/cuDNN version: (CUDA11.2)
 6. Additional context: (Add any other context about the problem)
在Linux上 单卡训练模型的时候（ 有两张1080ti卡），可以看到0号卡在被使用，接下来x想设置1号卡来进行当下的训练
![1657522949237](https://user-images.githubusercontent.com/49149464/178207347-f4b5f2ab-3b7d-4c8d-b3f3-5352f2621589.png)

export CUDA_VISIBLE_DEVICES=1 # 设置1张可用的卡
![1657522882184](https://user-images.githubusercontent.com/49149464/178207084-486501ec-699e-4394-9de0-170859a057f4.jpg)

结果可以看到，使用的是0号卡 进行训练，报一个显存溢出的错误
![1657523069108](https://user-images.githubusercontent.com/49149464/178207456-f006e722-680f-4437-8791-57a02f5bb22d.jpg)

接下来做了如下的尝试，均报如上同样错误（设置为1号显卡，但是跑train的时候 使用的还是0号）：
1 在代码内顶部设置 
  设置显卡1 跑程序
  import os
  os.environ['CUDA_VISIBLE_DEVICES'] = '1'
2 在代码内部设置  
   ![d306fcb9d66fd1382163ef6c46106c0](https://user-images.githubusercontent.com/49149464/178207772-fc363115-5886-4873-a282-4352b05982f6.png)

---

**Comment by haoyuying** [comment]
请您给出具体使用的paddleseg模型及使用方式，根据您目前提供的报错信息，可以参考如下文档：单卡训练及多卡训练的命令差异可参考https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/docs/train/train_cn.md

**Comment by chenxi00a1** [comment]
启动训练前执行：export CUDA_VISIBLE_DEVICES=1 # 设置1号卡
启动训练代码：python train.py --config configs\segformer\segformer_b4_cityscapes_1024x1024_160k.yml --do_eval --use_vdl --save_interval 500 --save_dir output
接下来，做了两种代码内设置1号卡的尝试，均报0号卡显存溢出错误（设置1号卡的操作并没有成功）

**Comment by gg22mm** [comment]
确实是有这个问题，我也是，都是使用 gpu:0

**Comment by juncaipeng** [comment]
建议先升级到paddleseg 2.5，然后看下是否还存在该问题。 该问题此前缺失没遇到过。

**Comment by gg22mm** [comment]
是不是windows的问题，我用的是widows  :    set export CUDA_VISIBLE_DEVICES=1

**Comment by chenxi00a1** [comment]
我是linux




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月12日(星期二) 下午2:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] [设置GPU为1号卡，不生效] (Issue #2310)



 是不是windows的问题，我用的是widows:set export CUDA_VISIBLE_DEVICES=1

**Comment by xiegegege** [comment]
> export CUDA_VISIBLE_DEVICES=1

我这里linux下试了这两行命令：
export CUDA_VISIBLE_DEVICES=1 
python train.py --config configs/segformer/segformer_b4_cityscapes_1024x1024_160k.yml --do_eval --use_vdl --save_interval 500 --save_dir output
是在1号卡上跑的

**Comment by chenxi00a1** [comment]
谢谢，我也测试这个命令 它就不是在1号卡跑 很奇怪




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月12日(星期二) 下午3:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] [设置GPU为1号卡，不生效] (Issue #2310)



  export CUDA_VISIBLE_DEVICES=1
  我这里linux下试了这两行命令：
 export CUDA_VISIBLE_DEVICES=1
 python train.py --config configs/segformer/segformer_b4_cityscapes_1024x1024_160k.yml --do_eval --use_vdl --save_interval 500 --save_dir output
 是在1号卡上跑的

**Comment by gg22mm** [comment]
> 测试这个命令 它就不是在1号卡跑 很奇怪
我想可能是widonws 问题，因为我用的是win10出问题，linux我没试，懒得配置，以后再说  ,  你是windos or linux ?

**Comment by chenxi00a1** [comment]
我一直用的linux！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月12日(星期二) 下午3:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] [设置GPU为1号卡，不生效] (Issue #2310)



  测试这个命令 它就不是在1号卡跑 很奇怪
 我想可能是widonws 问题，因为我用的是win10出问题，linux我没试，懒得配置，以后再说,你是windos or linux ?

**Comment by chenxi00a1** [comment]
谢谢，好的 我做一下尝试。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月12日(星期二) 下午2:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] [设置GPU为1号卡，不生效] (Issue #2310)



 建议先升级到paddleseg 2.5，然后看下是否还存在该问题。 该问题此前缺失没遇到过。

**Comment by juncaipeng** [comment]
windows上是：set CUDA_VISIBLE_DEVICES=1
