### ISSUE TITLE
[Bug] PaddleSeg/deploy/cpp/run_seg_cpu.sh 编译报错

### ISSUE THREAD

**Issue by felixhjh** [PaddlePaddle/PaddleSeg#2316]
1. CMakeLists.txt 未添加 onnxruntime以及paddle2onnx  lib
2. run_seg_cpu.sh 脚本内demo名写错 readme.txt中为bisenetv2_demo_model/

**Comment by Bobholamovic** [comment]
感谢您的反馈！该问题正在解决中，请耐心等待后续消息。

**Comment by Bobholamovic** [comment]
PR已合入，请您拉取最新版本的develop分支并再次尝试。如果问题解决，麻烦关闭issue。
