### ISSUE TITLE
你好，我想问一下原supervisely数据集怎么转换成train.txt val.txt？[General Issue]

### ISSUE THREAD

**Issue by zeckireck** [PaddlePaddle/PaddleSeg#2317]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by Bobholamovic** [comment]
您好！PaddleSeg的[`SUPERVISELY`](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/paddleseg/datasets/supervisely.py)已经封装了数据集下载的功能，而从[PaddleSeg官方链接](https://paddleseg.bj.bcebos.com/dataset/Supervisely_face.zip)下载的数据集是自带file list文件的，因此您使用此数据集进行训练时只需要对配置文件的相应部分进行修改即可。如果您需要手动生成file list文件，可以参考[此文档](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/docs/data/marker/marker_cn.md#3%E5%88%87%E5%88%86%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E9%9B%86)。

**Comment by zeckireck** [comment]
我在supervisely官网下的supervisely person的数据集，得到的标注是json格式，怎么转成png？paddle有提供这个脚本吗？得到的目录结构如下：
![image](https://user-images.githubusercontent.com/81000191/179170135-db954db7-65a0-415e-9ae4-f0557bf1718e.png)

**Comment by Bobholamovic** [comment]
目前PaddleSeg没有提供相应的脚本，您可以在[这个链接](https://paddleseg.bj.bcebos.com/dataset/Supervisely_face.zip)下载带有file list文件的数据集。
