### ISSUE TITLE
[Bug] 自训练segformer算法模型，进行预测的时候加载不了模型参数

### ISSUE THREAD

**Issue by chenxi00a1** [PaddlePaddle/PaddleSeg#2322]
Thanks for your bug report. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (PaddleSeg release/2.3)
 2. PaddlePaddle version: (paddlepaddle-gpu 2.3.0.post112)
 3. Operation system: (Linux)
 4. Python version: (Python3.6.13)
 5. CUDA/cuDNN version: (CUDA11.2/cuDNN 8.1)
 6. Full codes: 
train : python train.py --config configs\segformer\segformer_b4_cityscapes_1024x1024_160k.yml --do_eval --use_vdl --save_interval 500 --save_dir output
predict: python predict.py --config configs/segformer/segformer_b4_cityscapes_1024x1024_160k.yml --model_path output/best_model/model.pdparams --image_path data/data_ys/JPEGImages/1654073382157737_c6_98.png --save_dir output/result

 7. Detailed error information, releated running log: 
 可以看到，模型加载路径没问题，也没加载错误模型(比如训练的是Segfomer 而加载的PP_Lite)
在加载(0/847)参数后，直接开始预测，预测结果很花(估计是没有加载模型参数，模型参数是一些随机数）
![1657788493353](https://user-images.githubusercontent.com/49149464/178942512-9998deef-3e74-443a-905f-6ff58ca03b11.jpg)

另外：训练segfomer-b4 是正常的(虽然训练效果不佳，由于数据问题)

![2](https://user-images.githubusercontent.com/49149464/178942865-2f97bbed-34a9-46ff-87f4-8ec270c917a6.jpg)

**Comment by shiyutang** [comment]
考虑output中模型参数是否不对呢？日志提醒模型参数没有加载上
