### ISSUE TITLE
[General Issue]语义分割，预测如何进行裁剪图片

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSeg#2327]
语义分割返回 label_map score_map，

如何进行裁剪

只需要把预测出来的，裁剪出来，保存为新的图像

**Comment by haoyuying** [comment]
没看懂您的意思，是要把背景变成透明的吗

**Comment by monkeycc** [comment]
![123](https://user-images.githubusercontent.com/6490927/179494771-f065cbcc-7f30-4166-8e3b-a9fdf555f3c7.png)

识别出来的物体
要裁剪 
高度宽度 根据物体大小

然后背景半透明 或者 白色

@haoyuying

**Comment by haoyuying** [comment]
背景为白色就把mask和原图相乘取出前景背景都置为255即可，计算高度从mask计算x,y的最大值和最小值，然后把图抠出来。paddleseg目前没有提供该脚本，需要您自己去写。

**Comment by badboy-tian** [comment]
楼主 解决了吗
