### ISSUE TITLE
[General Issue] 查看每个像素的置信度

### ISSUE THREAD

**Issue by lanjingks** [PaddlePaddle/PaddleSeg#2332]
https://github.com/PaddlePaddle/PaddleSeg/blob/d7d909cabb98fabae9e3e49b579bfb0bf8d574a3/paddleseg/core/infer.py#L243
这里怎么看每个像素的置信度呢？

**Comment by juncaipeng** [comment]
模型的输出是logit，纬度是n*c*h*w，c是分割类别数。  具体取出来特定通道数的数值，就是对应类别的置信度。

通常是使用argmax取出最大置信度的通道数，得到该像素的预测类别。
