### ISSUE TITLE
PP-HumanMatting 模型导出onnx失败

### ISSUE THREAD

**Issue by MaybeShewill-CV** [PaddlePaddle/PaddleSeg#2336]
欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：PaddleSeg release/2.5
 2. PaddlePaddle版本：PaddlePaddle 2.2.1
 3. 操作系统信息：Ubuntu 16.04 LTS
 4. Python版本号：3.7.11
 5. CUDA/cuDNN版本：CUDA10.2 / CuDNN 7.6.5
 6. 其他内容:
 
使用paddle2onnx转换PP-HumanMatting模型失败。PP-HumanMatting模型下载自 [https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/Matting/README_CN.md](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/Matting/README_CN.md) 提供的[inference model](https://paddleseg.bj.bcebos.com/matting/models/deploy/pp-humanmatting-resnet34_vd.zip)链接

使用的paddle2onnx命令如下

`paddle2onnx --model_dir ../weights/matting/human_matting-resnet34_vd --model_filename model.pdmodel --params_filename model.pdiparams --save_file model.onnx --opset_version 11`

报错信息如下：
![Screenshot from 2022-07-20 14-03-54](https://user-images.githubusercontent.com/15725187/179908634-8b535c06-f181-4bb7-8292-fc0c8b822198.png)

paddle2onnx 版本为 paddle2onnx-0.9.8 with python>=3.6, paddlepaddle>=2.0.0

如果还需要额外的信息可以提示我补充下:)

**Comment by wuyefeilin** [comment]
请参考issue：https://github.com/PaddlePaddle/PaddleSeg/issues/2055

**Comment by MaybeShewill-CV** [comment]
@wuyefeilin 感谢 已解决:)
