### ISSUE TITLE
[General Issue]使用Paddle Inference静态库推理时遇到错误

### ISSUE THREAD

**Issue by Tangyuny** [PaddlePaddle/PaddleSeg#2338]
在使用文档中的示例进行c++推理部署时，当默认使用动态链接库时程序可以正常运行，但将静态库开关 -DWITH_STATIC_LIB=ON 打开后会出现如下报错：

![1](https://user-images.githubusercontent.com/37798338/179928386-f3d6feab-85f7-4f89-988c-8f20d9e9e76a.png)
![2](https://user-images.githubusercontent.com/37798338/179928499-0f1fa790-d20d-4ecf-aec5-5fec5f572949.png)
请问是什么原因

 1. PaddleSeg版本：Release / v2.5.0
 2. PaddlePaddle版本： 2.3.1-gpu
 3. 操作系统信息：Linux 16.04.1-Ubuntu
 4. Python版本号：Python 3.6
 5. CUDA/cuDNN版本：CUDA 10.2 cuDNN 8.0.1 TRT 7.2.3.4

**Comment by Bobholamovic** [comment]
请将[此处](https://github.com/PaddlePaddle/PaddleSeg/blob/5ab49dea0f20a9cfd681f766ee1bf4b77af0a74a/deploy/cpp/run_seg_gpu.sh#L26)的`-j`选项去除，然后重新运行`run_seg_gpu.sh`脚本，并截图完整的报错信息（即出现`ERROR`字样的部分）。

**Comment by Tangyuny** [comment]
@Bobholamovic 感谢你的回复。这个问题的原因后来找到了，是paddle inference里有几个库在cmake中没有链接，加上就可以运行了。

另外还发现了一个问题。下图是官方给出的建议版本：
![5](https://user-images.githubusercontent.com/37798338/180178841-8355f6a5-5e4c-449b-a156-fb70f40f0df3.png)

采用cuda-10.1这套配置时，整体运算时间应该是正常的：
![2](https://user-images.githubusercontent.com/37798338/180179174-6d9222a9-ddda-4043-b362-74aed5788400.png)

采用cuda-10.2时，整体运算时间变得不正常：
![4](https://user-images.githubusercontent.com/37798338/180179393-dc23fd50-0044-491a-9802-f6e4725385d2.png)

根据提示的内容，将cuDNN从建议版本8.0.x 改为8.1.x 后，运算时间和cuda-10.1接近了，但整体运算时间比10.1要长，请问cuda10.2这套流程存在运算效率的问题吗。
![6](https://user-images.githubusercontent.com/37798338/180182283-05c7738b-2968-4a12-9046-36e5a4eab2c9.png)

另外官方建议的cuDNN版本是否需要更新一下。

**Comment by Bobholamovic** [comment]
1. 建议您将predictor时间不一致的问题反馈到[Paddle 官方仓库](https://github.com/PaddlePaddle/Paddle)，因为这个问题应该与PaddleInference的具体实现有关。
2. 根据您在Paddle官方仓库所提issue的具体解决情况，我们会考虑更新cuDNN版本。

感谢您的建议！

**Comment by Tangyuny** [comment]
@Bobholamovic 好的谢谢
