### ISSUE TITLE
[General Issue] PaddleSeg是否合适大分辨率的PCB主板检测

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSeg#2344]
![1111](https://user-images.githubusercontent.com/6490927/180108314-5772212e-1f4a-45bf-9d5e-3951be7b9d9e.jpg)

9000*9000
PaddleSeg是否合适大分辨率的PCB主板检测

如何检测 好的 和 坏的 

实例分割还是语义分割 ？

比如检测漏的
怎么标识 在哪里漏？

标注要怎么标注  
是否要先分割裁剪

原图9000*9000
怎么进行预测
强制裁剪 会导致部分细节 裁没了

**Comment by juncaipeng** [comment]
请问具体是什么任务，缺陷分割吗？
大尺寸图像，建议划分为重叠的小图进行训练和预测。应该是使用语义分割。标注为背景和瑕疵两类即可，可以参考PaddleSeg标注教程。

**Comment by monkeycc** [comment]
重叠裁剪之后
预测   

最后如何合并图像
在原图上 显示缺陷的位置
@juncaipeng

**Comment by juncaipeng** [comment]
paddleseg的预测支持了重叠裁剪预测，重叠区域会取均值。

**Comment by monkeycc** [comment]
原图 9000*9000
训练图尺寸是640*640


导出模型
input_shape
这个不知道 怎么设置

对应的配置  是否是
python predict.py 
--is_slide True
--stride  640 640
--crop_size  512  512

但是
--stride  640 640
--crop_size  512 512
不清楚 是不是这样改 
不知道是否合理


Python 部署
python deploy/python/infer.py
没有is_slide  stride   crop_size  
怎么办

预测9000*9000
要好几秒
应该用什么方法 才能控制在500毫秒之内

@juncaipeng

**Comment by juncaipeng** [comment]
predict.py输入参数，crop_size应该设置为640， stride应该设置为小于等于640。
infer.py不支持滑动窗口预测，只支持原图大小输入，建议自己进行裁剪和拼接。

**Comment by monkeycc** [comment]
python 部署
是不是可以直接用
predict.py
来预测

比 infer.py
速度上  是否一样

predict.py 滑动窗口预测
要1-2秒
有没办法缩短这个时间 ？？

@juncaipeng

**Comment by juncaipeng** [comment]
使用预测模型+infer.py(python api)部署会更快。
最好使用预测模型+ cpp api部署，速度最快。
