### ISSUE TITLE
[General Issue][Matting] Performance of MODNet is poor when trained on 1024x1024

### ISSUE THREAD

**Issue by hackkhai** [PaddlePaddle/PaddleSeg#2348]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: 2.6
 2. PaddlePaddle version:2.3
 3. Operation system: Linux
 4. Python version:Python3.7
 5. CUDA/cuDNN version: CUDA11.2 cuDNN 8
 6. Additional context: 
**Experiments:**
I tried all combinations givent below:
1) PPMatting, HumanMatting, MODNet
2) Resolution: 512,1024
3) Resizing techniques: ResizeByShort, LimintShort
3) Different Backbones: Mobilenetv2, HRNetw18,HRNetw48
**Observations:**
1. Out of all MODNet with 512x512 resolution did better in identifying the salient object (but not great), Though PPMatting was good it was not close to MODNet even in higher resolution
2. All models performs Bad on higher resolition training and for MODNet its bad than 512x512 training.
3. For human images, though the detail module is good, the semantic module is performing bad (I am asuming this situation, based on what i observed)  which cuts the legs or hands of the human
4. When trained on real life images it does poorly on studio quality images and decently on real life images. But if its trained on studio quality images it does bad on real life images
5. The model performance degrades when we add more salient objects. for example trained food, clothing, shoes, bags together makes the model performance pretty average
**Questions:**
1) How to make the model do better on 1024 resolution
2) What am i doing wrong in PPmatting, after reading the paper i thought it would do better than MODNet for higher resolution images. 
3) How to make the model do matting for multiple objects. Like personal care products, cars, packaged goods etc
4) how to make the model robust for studio quality images and real life images
5) Any suggestions or experiments that i could try?

**Comment by wuyefeilin** [comment]
1. In 1024 resolution， ppmatting is better than modnet. 
3. Maybe you need a dataset firstly.
4. Maybe you can train the model by combine the studio quality images and real life images.
5. When you training, you can try more data augmentation according different scenarios

**Comment by hackkhai** [comment]
Thanks for the reply, I do have a dataset of 80k anotated images.How do i fix the multiple class object matting?

**Comment by wuyefeilin** [comment]
> Thanks for the reply, I do have a dataset of 80k anotated images.How do i fix the multiple class object matting?
There's too much data to know the distribution difficultly. We need to experiment before giving you suggestion. If you don not mind, could you share your dataset with us? So I can have some experiment with it.

My email is chenguowei01@baidu.com.

**Comment by hackkhai** [comment]
Hey, sent you a mail, please check

**Comment by hackkhai** [comment]
Hey, you havent checked my mail yet :) please do check it
@wuyefeilin

**Comment by hackkhai** [comment]
@wuyefeilin its almost been a month please check the mail

**Comment by wuyefeilin** [comment]
Sorry, but I Do not receive your mail. If you don't mind, please resent it.

**Comment by hackkhai** [comment]
ca you share anyother mail id? maybe baidu mail id is not working for me
