### ISSUE TITLE
[Feature Request] Show how to set Eiseg language to English in documentation

### ISSUE THREAD

**Issue by markisus** [PaddlePaddle/PaddleSeg#2349]
It was not clear how to set the Eiseg language to English. You can do it from the program with some guessing and then restarting the program, or you can edit the eiseg/config/setting.txt to have "language=English" 

Thanks!

**Comment by haoyuying** [comment]
![image](https://user-images.githubusercontent.com/35907364/180682173-d80ca697-3552-4bc1-86ed-26e515c2b34c.png)
You may set language  as this picture and then restart the eiseg, the language will be set according to your demand.
