### ISSUE TITLE
     这样加载预训练模型对吗？这样加载训练的时候显示没有下载成功。model = DeepLabV3P(num_classes=num_class,                     backbone=ResNet50_vd(),                  align_corners=False,                  pretrained='https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz')

### ISSUE THREAD

**Issue by xiao12301** [PaddlePaddle/PaddleSeg#2353]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by shiyutang** [comment]
The code seems alright, please provide us with the error. It could be the network that cause the download failure.

**Comment by xiao12301** [comment]
Loading pretrained model from https://paddleseg.bj.bcebos.com/dygraph/backbone/mobilenetv3_large_x1_0_ssld.tar.gz
Connecting to https://paddleseg.bj.bcebos.com/dygraph/backbone/mobilenetv3_large_x1_0_ssld.tar.gz
Downloading mobilenetv3_large_x1_0_ssld.tar.gz
[==================================================] 100.00%
Uncompress mobilenetv3_large_x1_0_ssld.tar.gz
[==================================================] 100.00%
2022-07-23 09:44:45 [WARNING]	backbone.conv.conv.weight is not in pretrained model
2022-07-23 09:44:45 [WARNING]	backbone.conv.bn.weight is not in pretrained model
2022-07-23 09:44:45 [WARNING]	backbone.conv.bn.bias is not in pretrained model
2022-07-23 09:44:45 [WARNING]	backbone.conv.bn._mean is not in pretrained model
2022-07-23 09:44:45 [WARNING]	backbone.conv.bn._variance is not in pretrained model
最后显示的是这样的
There are 0/285 variables loaded into LRASPP.

**Comment by shiyutang** [comment]
显示结果表明下载成果，但是参数名称不一致导致没有加载进网络。
