### ISSUE TITLE
[Bug]L1 Loss 未使用的ignore_index参数

### ISSUE THREAD

**Issue by BlackDriver** [PaddlePaddle/PaddleSeg#2354]
1. PaddleSeg版本：PaddleSeg release/2.5
 2. PaddlePaddle版本：PaddlePaddle 2.2.0
 3. 操作系统信息：Linux
 4. Python版本号：Python3.7
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 完整的代码：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/paddleseg/models/losses/l1_loss.py

L1 loss 直接继承了 nn.L1Loss，没有任何改动
引入了ignore_index参数，但没有用上，因为nn.L1Loss里根本没这个参数，麻烦修复
ps：要么就干脆删了，还是有方法用得上这个参数的，避免误导，让人以为有了，一看loss大几十  :x

**Comment by shiyutang** [comment]
We have fixed it the mentioned PR.
