### ISSUE TITLE
如果我想单独识别人，可以在已有的模型上进行修改吗

### ISSUE THREAD

**Issue by 15651196171** [PaddlePaddle/PaddleSeg#2356]
Welcome to propose a new feature! To help us understand your great feature, please provide following information:
1. A clear and concise description of the proposed feature.
2. Tell us why the feature is useful. 
3. If possible, please show related codes .

---

欢迎提出一个新功能需求，为了帮助我们更好理解您的需求，辛苦提供下面信息：
1. 清晰简洁的语言提出新功能需求。
2. 请描述这个需求的必要性。
3. 如果可以，辛苦您提供相关代码实现效果。

**Comment by shiyutang** [comment]
We have [pphumanseg](https://github.com/shiyutang/PaddleSeg/tree/release/2.5/contrib/PP-HumanSeg) that only segment humans in the image/video,
