### ISSUE TITLE
表盘识别

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/PaddleSeg#236]
我想知道怎样通过圆心定位、数字分类、角度估算处理得到最终的读数的方法，谢谢

**Comment by littletomatodonkey** [comment]
您好，主要有以下几个步骤：

- 使用连通区域方法找到图像中最大表盘所在位置，只对其进行处理。
- 根据黑红指针的分割结果，基于最小二乘法拟合黑红指针所在直线，求其交点，视为表盘圆心。
- 基于局部自适应阈值分割算法，找到主刻度。
- 根据圆心与各个主刻度中心点所在的直线，以及示数分割结果，找到主刻度对应的示数分割图像。
- 根据标注的数字图像，进行分类模型的训练，并使用分类器进行数字识别。
- 根据刻度与圆心的角度与其数字识别进行二次校验。
- 找到与指针最近的两个主刻度，根据其角度与对应读数，计算得出黑红指针的角度。

**Comment by Sunyingbin** [comment]
> 您好，主要有以下几个步骤：
> 
> * 使用连通区域方法找到图像中最大表盘所在位置，只对其进行处理。
> * 根据黑红指针的分割结果，基于最小二乘法拟合黑红指针所在直线，求其交点，视为表盘圆心。
> * 基于局部自适应阈值分割算法，找到主刻度。
> * 根据圆心与各个主刻度中心点所在的直线，以及示数分割结果，找到主刻度对应的示数分割图像。
> * 根据标注的数字图像，进行分类模型的训练，并使用分类器进行数字识别。
> * 根据刻度与圆心的角度与其数字识别进行二次校验。
> * 找到与指针最近的两个主刻度，根据其角度与对应读数，计算得出黑红指针的角度。

您好，请问有具体的代码说明吗？

**Comment by LielinJiang** [comment]
目前还没有

**Comment by Sunyingbin** [comment]
好的，非常感谢您的回答~ ：）
