### ISSUE TITLE
请问用python的infer预测人的轮廓，图形背景的颜色和人物的颜色怎么改

### ISSUE THREAD

**Issue by 15651196171** [PaddlePaddle/PaddleSeg#2366]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by haoyuying** [comment]
colormap是由 https://github.com/PaddlePaddle/PaddleSeg/blob/12b008034854b95c70621f36bb67d680edc5d106/paddleseg/utils/visualize.py#L77 
函数生成的，如果想修改，可以按照colormap的格式自己修改颜色输入。

**Comment by 15651196171** [comment]
你好，这个可以更换背景的颜色我知道，但是目标人物的颜色该怎么修改呐，我有时候修改上面的函数get_pseudo_color_map，这里面我可以把识别到的目标256这个值修改成0变成黑色，但是只能改成黑色，怎么改成白色呐


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月25日(星期一) 上午10:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] 请问用python的infer预测人的轮廓，图形背景的颜色和人物的颜色怎么改 (Issue #2366)





 
colormap是由 https://github.com/PaddlePaddle/PaddleSeg/blob/12b008034854b95c70621f36bb67d680edc5d106/paddleseg/utils/visualize.py#L77
 函数生成的，如果想修改，可以按照colormap的格式自己修改颜色输入。
