### ISSUE TITLE
[General Issue] WIN 的环境 , C# 有没教程的

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSeg#2367]
部署
WIN 的环境 ,
nvidia显卡

C# 有没教程的

我看官方教程 基本上都是Linux环境

**Comment by haoyuying** [comment]
请具体描述您的使用场景，使用模型等，方便我们定位问题。

**Comment by monkeycc** [comment]
C# 部署 预测
win环境 nvidia 3060 显卡 GPU来预测
cuda 11.0

有没教程的
还是要用PaddleX的
https://github.com/PaddlePaddle/PaddleX/blob/develop/deploy/cpp/docs/models/paddleseg.md
PaddleSeg模型部署

但是我没看到有 滑窗 的api
C# 需要滑窗预测 怎么办

**Comment by juncaipeng** [comment]
目前没有提供c#部署的教程，你可以使用c++部署的代码，导出为dll，c#调用dll执行。

**Comment by aiwenzhu** [comment]
> 目前没有提供c#部署的教程，你可以使用c++部署的代码，导出为dll，c#调用dll执行。

请问C++部署教程在哪

**Comment by juncaipeng** [comment]
文档首页readme有链接，请查看。
