### ISSUE TITLE
paddleseg 做印章去除

### ISSUE THREAD

**Issue by LeeLear** [PaddlePaddle/PaddleSeg#2368]
Welcome to propose a new feature! To help us understand your great feature, please provide following information:
1. A clear and concise description of the proposed feature.
2. Tell us why the feature is useful. 
3. If possible, please show related codes .

---

欢迎提出一个新功能需求，为了帮助我们更好理解您的需求，辛苦提供下面信息：
1. 清晰简洁的语言提出新功能需求。
2. 请描述这个需求的必要性。
3. 如果可以，辛苦您提供相关代码实现效果。

**Comment by haoyuying** [comment]
您好，请提供您具体的业务场景，需求等，方便我们评估。

**Comment by yourchanges** [comment]
类似发票上的印章移除, 方便后续识别?

**Comment by LeeLear** [comment]
是的，分割模型中的，paddle版unet++可以实现吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月4日(星期四) 下午2:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleSeg] paddleseg 做印章去除 (Issue #2368)





 
类似发票上的印章移除, 方便后续识别?

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
