### ISSUE TITLE
[Bug]paddle inference接入pp-matting很容易崩溃

### ISSUE THREAD

**Issue by dragonwarrior95** [PaddlePaddle/PaddleSeg#2370]
1. PaddleSeg版本：PaddleSeg release/2.6
 2. PaddlePaddle版本：paddle_inference 2.3.0 (avx_mkl_cuda11.2_cudnn8.2_avx_mkl-trt8.0.1.6)
 3. 操作系统信息：Windows 10
 4. Python版本号：
 5. CUDA/cuDNN版本：
 6. 完整的代码：
                 ...
                 auto input_names = m_pPredictor->GetInputNames();
		auto input_t = m_pPredictor->GetInputHandle(input_names[0]);
		std::vector<int> input_shape = { 1, chs, rows, cols };
		input_t->Reshape(input_shape);
		input_t->CopyFromCpu(pixels);

		// Run
		m_pPredictor->Run();
                ...
图片大一点比如1000*1000左右，运行到run就很容易崩溃，崩溃信息如下：
0x00007FFDEB114FD9 处(位于 paddle64.exe 中)有未经处理的异常: Microsoft C++ 异常: phi::enforce::EnforceNotMet，位于内存位置 0x000000D6ADD8E2F0 处。

**Comment by wuyefeilin** [comment]
看样子是内存不足哈

**Comment by dragonwarrior95** [comment]
> 

就一张不超过1000*1000的图就内存不足？那这个内存吃的有点凶啊
