### ISSUE TITLE
mobileseg分割网络 是否支持voc_aug数据集

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/PaddleSeg#2373]
因为我看到大部分都是使用的cityscapes数据集，如果使用voc数据集我将如何修改配置？

**Comment by wuyefeilin** [comment]
我们也有对voc_aug进行训练，可以参考相关模型的配置，如deeplabv3p下关于voc_aug的配置：https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.6/configs/deeplabv3p

**Comment by chen-del** [comment]
好的，谢谢
