### ISSUE TITLE
如何为PSPNet修改bankbone

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/PaddleSeg#2375]
我想将pspnet的主干bankbone改为主干为mobnetv3网络，那么这样我是否需要修改源码，如果不需要的话，那么需要更改那个配置，谢谢！期待您的回复？

**Comment by Bobholamovic** [comment]
您好，更换backbone不需要修改源码，请修改`backbone`配置项：
https://github.com/PaddlePaddle/PaddleSeg/blob/12b008034854b95c70621f36bb67d680edc5d106/configs/pspnet/pspnet_resnet50_os8_cityscapes_1024x512_80k.yml#L19

具体修改方式可参考[此配置文件](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/configs/lraspp/lraspp_mobilenetv3_cityscapes_1024x512_80k_os32.yml)。

**Comment by chen-del** [comment]
好的，谢谢
