### ISSUE TITLE
UNet训练时的显存占用问题

### ISSUE THREAD

**Issue by xiao12301** [PaddlePaddle/PaddleSeg#2379]
用unt网络训练的时候这么占用显存吗？unet网络不是最容易训练的吗，我用AIstuio的40GB的显存才能训练

Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by Bobholamovic** [comment]
您好！训练时的显存占用与输入图像的大小、batch size、backbone的大小等都有关系，请您给出具体的配置，以便我们帮助您排查问题。
