### ISSUE TITLE
[General Issue] PP-LITESEG消融实验相关问题

### ISSUE THREAD

**Issue by jyang68sh** [PaddlePaddle/PaddleSeg#2384]
非常欣赏你们的论文！

关于TABLE 3的模块消融实验
请问Baseline的decoder是如何设计的？为什么增加了FLD模块后mIoU提升了，FPS下降了？似乎有些不合乎逻辑。

Thanks!

**Comment by jyang68sh** [comment]
@juncaipeng Please kindly check my question. Thanks!

**Comment by juncaipeng** [comment]
Hi, thanks for your attention. 

The computation cost of the PP-LiteSeg-B2 with FLD is bigger than the baseline model, and the number of feature channels in decoder are as follows.
* Baseline model: 96, 96, 96
* PP-LiteSeg-B2 with FLD: 64, 96, 128

![image](https://user-images.githubusercontent.com/52520497/182058963-0736cd89-7155-43ee-8c1a-21ea35619649.png)

**Comment by jyang68sh** [comment]
Hi  @juncaipeng  thanks for your answer.

So the baseline model is 3 blocks of upsample, all of them has 96 channels, and then go to seg head?

My question is: How does baseline model outperforms stdc2 original repo with batch size 4x4, pretrained, 160k iters? I tried to run stdc2 with the same setting locally and got mIoU around 76.8.

I am confused as baseline model has lower channels and doesnt have PPM, ARM and FFM modules compared as STDC2 original. 

Thanks!

**Comment by juncaipeng** [comment]
We retrain the stdc2 model and use it in our experiments.

**Comment by jyang68sh** [comment]
> We retrain the stdc2 model and use it in our experiments.

That makes sense. 
Thanks!
