### ISSUE TITLE
[General Issue]paddle加载数据出错

### ISSUE THREAD

**Issue by bah111587** [PaddlePaddle/PaddleSeg#2386]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）
 
PP-matting在加载数据的时候出错
2022-07-30 20:53:13,890 - ERROR - DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "tools/train.py", line 205, in <module>
    main(args)
  File "tools/train.py", line 200, in main
    metrics=args.metrics)
  File "/home/user02/bah/PaddleSeg/Matting/tools/../ppmatting/core/train.py", line 187, in train
    for data in loader:
  File "/home/user02/.conda/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 779, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)
请问这个是什么问题

**Comment by wuyefeilin** [comment]
检查一下数据是否按照要求的格式进行了准备

**Comment by bah111587** [comment]
![image](https://user-images.githubusercontent.com/85655567/182113308-e1a7b87f-7f0f-4daa-840c-c87f2cea1ece.png)
![image](https://user-images.githubusercontent.com/85655567/182113506-efe94c61-6554-4ffb-a373-9c7698c13996.png)
![image](https://user-images.githubusercontent.com/85655567/182113606-4e3db145-5f65-4969-aa94-2e7678f5f177.png)
![image](https://user-images.githubusercontent.com/85655567/182113671-41e44d77-2ad5-470c-844a-332adab05c10.png)
![image](https://user-images.githubusercontent.com/85655567/182113812-d1ef4e8e-d619-4352-9713-c3887fb5a709.png)
我的数据格式设置如上，我打印了读取的alpha图片的形状，感觉是能读取数据的，但是读一部分后就报错了，不知道是什么问题？

**Comment by bah111587** [comment]
> image
image
image
image
image
我的数据格式设置如上，我打印了读取的alpha图片的形状，感觉是能读取数据的，但是读一部分后就报错了，不知道是什么问题？

**Comment by bah111587** [comment]
> 检查一下数据是否按照要求的格式进行了准备
我的数据格式设置如上，我打印了读取的alpha图片的形状，感觉是能读取数据的，但是读一部分后就报错了，不知道是什么问题？

**Comment by wuyefeilin** [comment]
你利用MattingDataset构建数据读取对象，看一下所有数据能够正常阅读

**Comment by bah111587** [comment]
> 

![3c95062e4a23455e86a89c1d27b31f4](https://user-images.githubusercontent.com/85655567/182398740-440a5019-1eeb-4467-8ddb-ce7878eb170a.jpg)
我用MattingDataset构造了一个loader，还是读一部分数据就报错了，不过除了原来的报错还显示RuntimeError: Unknown data type <class 'str'>

**Comment by bah111587** [comment]
> 3c95062e4a23455e86a89c1d27b31f4
我用MattingDataset构造了一个loader，还是读一部分数据就报错了，不过除了原来的报错还显示RuntimeError: Unknown data type <class 'str'>

**Comment by bah111587** [comment]
> 你利用MattingDataset构建数据读取对象，看一下所有数据能够正常阅读

![3c95062e4a23455e86a89c1d27b31f4](https://user-images.githubusercontent.com/85655567/182399566-15ad8105-ac37-40a4-b57c-7d0e55f5f160.jpg)
我用MattingDataset构造了一个loader，还是读一部分数据就报错了，不过除了原来的报错还显示RuntimeError: Unknown data type <class 'str'>

![image](https://user-images.githubusercontent.com/85655567/182508345-7567ec3b-4898-4176-b9a9-157943030b68.png)
我用从paddle上解压的ppm100数据集也是同样的错，会是paddle版本的问题吗

**Comment by wuyefeilin** [comment]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/Matting/tools/train.py#L153 
直接利用train_dataset进行数据读取，查看哪个数据出错了

**Comment by bah111587** [comment]
> 



> https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/Matting/tools/train.py#L153 直接利用train_dataset进行数据读取，查看哪个数据出错了

直接用train_dataset是可以读取的，但是构造loader后就会报错了

**Comment by wuyefeilin** [comment]
我这边复现一下哈

**Comment by bah111587** [comment]
> 我这边复现一下哈

好的，非常感谢

**Comment by wuyefeilin** [comment]
运行多少个iters后出现的错误呢

**Comment by bah111587** [comment]
> 运行多少个iters后出现的错误呢

我好像找到原因了，MattingDataset源码的getitem那里返回的是data字典，我把他改成返回data['img']就没报错了

**Comment by wuyefeilin** [comment]
对代码进行修改在提issue的时候务必进行说明，否则很难定位问题的

**Comment by bah111587** [comment]
> 



> 对代码进行修改在提issue的时候务必进行说明，否则很难定位问题的

返回data那里没有改，下载的源码就是返回的data字典，然后就会报错
