### ISSUE TITLE
[General Issue]batch_cost 花费时间很不稳定

### ISSUE THREAD

**Issue by weekweekend** [PaddlePaddle/PaddleSeg#2389]
为什么我的batch_cost花费的时间变长了，前几次训练的batch_cost在0.4左右，现在有时飙升到了30+, 是在同样的训练环境下训练同样的模型
![image](https://user-images.githubusercontent.com/34128257/182160903-638f08bd-e834-4743-aaa2-d9e8bf11dfb0.png)

**Comment by juncaipeng** [comment]
从log来看，主要是读取数据耗时变得更长了，可以检查下是不是有其他进程占用了cpu。

**Comment by weekweekend** [comment]
您的邮件已收到 ——周

**Comment by weekweekend** [comment]
您的邮件已收到 ——周
