### ISSUE TITLE
[General Issue]paddle读取数据过程出错

### ISSUE THREAD

**Issue by bah111587** [PaddlePaddle/PaddleSeg#2392]
platform: Linux-5.4.0-122-generic-x86_64-with-debian-buster-sid
Python: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) [GCC 9.4.0]
Paddle compiled with cuda: True
NVCC: Build cuda_11.4.r11.4/compiler.30188945_0
cudnn: 8.2
GPUs used: 1
CUDA_VISIBLE_DEVICES: 1
GPU: ['GPU 0: NVIDIA TITAN', 'GPU 1: NVIDIA TITAN', 'GPU 2: NVIDIA TITAN', 'GPU 3: NVIDIA TITAN']
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PaddleSeg: 2.6.0
PaddlePaddle: 2.0.2
OpenCV: 4.5.4

![image](https://user-images.githubusercontent.com/85655567/182113308-e1a7b87f-7f0f-4daa-840c-c87f2cea1ece.png)
![image](https://user-images.githubusercontent.com/85655567/182113506-efe94c61-6554-4ffb-a373-9c7698c13996.png)
![image](https://user-images.githubusercontent.com/85655567/182113606-4e3db145-5f65-4969-aa94-2e7678f5f177.png)
![image](https://user-images.githubusercontent.com/85655567/182113671-41e44d77-2ad5-470c-844a-332adab05c10.png)
![image](https://user-images.githubusercontent.com/85655567/182113812-d1ef4e8e-d619-4352-9713-c3887fb5a709.png)
我的数据格式设置如上，我打印了读取的alpha图片的形状，感觉是能读取数据的，但是读一部分后就报错了，不知道是什么问题？

**Comment by wuyefeilin** [comment]
参见https://github.com/PaddlePaddle/PaddleSeg/issues/2386
