### ISSUE TITLE
[General Issue]布尔量求和有问题

### ISSUE THREAD

**Issue by bah111587** [PaddlePaddle/PaddleSeg#2397]
![image](https://user-images.githubusercontent.com/85655567/182749404-14ad324a-252c-4af4-9565-c9058d88a624.png)
![image](https://user-images.githubusercontent.com/85655567/182749438-c1fedfd2-0f34-4ff7-a7e8-531b60eb241c.png)
请问这个报错是不是不支持布尔量求和，应该如何解决？

**Comment by wuyefeilin** [comment]
更新一下paddle的版本

**Comment by bah111587** [comment]
> 更新一下paddle的版本

我是cuda11.4的，只找到这个版本能下，有其他对应的版本推荐吗

**Comment by wuyefeilin** [comment]
https://www.paddlepaddle.org.cn/ 参考官网安装教程，安装paddlepaddle-gpu==2.3版本哈。如果cuda不支持，建议重新安装一下cuda
