### ISSUE TITLE
[Enhance] Enhance slide_inference

### ISSUE THREAD

**Issue by Dawn-bin** [PaddlePaddle/PaddleSeg#2399]
Thanks for your bug report. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: master

---------------------------------------------------------------

hi, I have met a Bug, when I use paddle to inference a **very very big** aerial picture.

The situation is that:
I use small crop to train a model, and do referece on a big origin pic with predict.py.
That is the bug coming in [**silde_reference**](https://github.com/PaddlePaddle/PaddleSeg/blob/19eb360a5a7aaa9277345791dfcad34004e84031/paddleseg/core/infer.py#L130)
```
final_logit = paddle.to_tensor(final_logit)
```
Here, L130, transform **final_logit** to CUDA, which lead to GPU momery out. This may use to calculate loss in Validation Mode with GT. But in this situation, we just need the reference results to be saved.

Some Suggestion: 
1. to move this code afterward, to where It really needed.
3. add a judgement, when we just need the result. (note: the later [**argmax**](https://github.com/PaddlePaddle/PaddleSeg/blob/19eb360a5a7aaa9277345791dfcad34004e84031/paddleseg/core/infer.py#L170) maybe time-consuming on cpu)

**Comment by Bobholamovic** [comment]
Thanks for pointing out this problem. We will consider adding this feature in the future.

Currently, I would recommend [**PaddleRS**](https://github.com/PaddlePaddle/PaddleRS) as an alternative. PaddleRS provides the functionality of lazy loading, which significantly saves both CPU and GPU memories when doing inference on large aerial images.

**Comment by Dawn-bin** [comment]
> Thanks for pointing out this problem. We will consider adding this feature in the future.
> 
> Currently, I would recommend [**PaddleRS**](https://github.com/PaddlePaddle/PaddleRS) as an alternative. PaddleRS provides the functionality of lazy loading, which significantly saves both CPU and GPU memories when doing inference on large aerial images.

Good job! I am looking forward it to be more powerful and comprehensive.
