### ISSUE TITLE
Fast-SCNN模型训练完后怎样预测和可视化？

### ISSUE THREAD

**Issue by FUQiaobo** [PaddlePaddle/PaddleSeg#240]

**Comment by LielinJiang** [comment]
和分割库中其他模型的预测，可视化方法相同。可以参考：
https://github.com/PaddlePaddle/PaddleSeg/blob/develop/docs/usage.md
https://github.com/PaddlePaddle/PaddleSeg/blob/develop/turtorial/finetune_fast_scnn.md

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。
