### ISSUE TITLE
[Bug]F.interpolate传参数据类型

### ISSUE THREAD

**Issue by xmichelleshihx** [PaddlePaddle/PaddleSeg#2401]
这个工程很多code里面插值F.interpolate传参都是错的，跑着有Bug。
shape应该传list格式的[h, w]，不应该传tuple格式的(h, w)

**Comment by Bobholamovic** [comment]
感谢您指出问题！PaddlePaddle 2.3.0已经修复了此bug，请升级到最新版尝试。
