### ISSUE TITLE
Matting 效果问题

### ISSUE THREAD

**Issue by frensher** [PaddlePaddle/PaddleSeg#2405]
你好,我想问下,内置的matting算法
我没有做什么修改
用自带的预训练模型,和配置文件,得到的抠图效果不好
不管用什么抠图算法
![图片](https://user-images.githubusercontent.com/42425485/183039269-96f8c377-7479-4fc1-add8-8ca0761a3001.png)
![图片](https://user-images.githubusercontent.com/42425485/183039362-b07efe38-def0-47bf-a5b3-005e2d4b5404.png)
![图片](https://user-images.githubusercontent.com/42425485/183039397-954237ca-4469-41fd-9b6f-c56f0598ee19.png)
![图片](https://user-images.githubusercontent.com/42425485/183039445-4c1e1b91-3fd8-4727-8c83-b26a00ffa91a.png)
最后一张是gt
中间两张是predict.py的输出结果
是我哪里弄错了嘛
我什么设置也没有动
唯一的区别是在推理阶段,我用的cpu,我感觉这个不是问题吧

**Comment by shiyutang** [comment]
请问是否有在自己的数据上重新进行训练呢？

**Comment by wuyefeilin** [comment]
『我没有做什么修改』， 也就是修改了，具体哪边修改了呢

**Comment by frensher** [comment]
> 请问是否有在自己的数据上重新进行训练呢？
谢谢回答
没有,直接用的官方权重
![图片](https://user-images.githubusercontent.com/42425485/183325840-5b4ea6d7-fade-4784-a5f4-82dfed933556.png)

**Comment by frensher** [comment]
> 『我没有做什么修改』， 也就是修改了，具体哪边修改了呢
谢谢回答
没修改,就是换了不同的config,连权重都是默认的

**Comment by wuyefeilin** [comment]
config和加载的预训练模型有对应吗

**Comment by frensher** [comment]
> config和加载的预训练模型有对应吗

设置好config以后,根据config网址加载的权重,没有从本地上加载;不对应,也run不了啊

**Comment by wuyefeilin** [comment]
你在预测的时候有通过model_path传入模型预训练模型吗。

具体可以看一下文档教程哈

**Comment by frensher** [comment]
> 你在预测的时候有通过model_path传入模型预训练模型吗。
> 
> 具体可以看一下文档教程哈

的确是加载权重的问题,谢谢你们了

**Comment by fuchao01** [comment]
请问这个问题怎么解决的

**Comment by user00644** [comment]
请问这个问题是如何解决的？

**Comment by wuyefeilin** [comment]
`--config`和`--model_path`的匹配问题
