### ISSUE TITLE
增加实例分割标注功能

### ISSUE THREAD

**Issue by crazy6oy** [PaddlePaddle/PaddleSeg#2407]
欢迎提出一个新功能需求，为了帮助我们更好理解您的需求，辛苦提供下面信息：
1. 能够在标注分割的时候区分哪些封闭区域属于同一个个体；
2. 能够在分割标注手、脚、头、躯干后，将多个部分归属到一个个体（我们想的办法是加下角标）；
3. 目前软件标注结果在实例分割项目上很难被使用。

**Comment by haoyuying** [comment]
感谢您的建议，我们会在后期优化中重点考虑您的需求。
