### ISSUE TITLE
[Bug]EISeg再次点击传播时闪退

### ISSUE THREAD

**Issue by monk-after-90s** [PaddlePaddle/PaddleSeg#2410]
Thanks for your bug report. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Full codes: (if you modify any original code，please show the comparison of the codes before and after)
 7. Detailed error information, releated running log: (if using multi-gpus，the log is saved to log/worklog.0 by default)
 8. Running command or reproduce details：
 9. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3） PaddleSeg release/2.6
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）paddlepaddle-gpu       2.3.1.post116
 3. 操作系统信息：（如Linux/Windows/MacOS）Windows10
 4. Python版本号：（如Python3.6/7/8）Python 3.10.4
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）CUDA11.7 cuDNN8.4.1
 6. 完整的代码：(若修改过原代码，请提供修改前后代码对比）
 7. 详细的错误信息、相关log：（若使用多卡，log默认保存在log/worklog.0）
 
![image](https://user-images.githubusercontent.com/50484238/183359896-fef47dde-2a9e-43d2-b484-d6bae1620b27.png)

 9. 运行指令或复现步骤：
 EISeg标注视频，点击传播之后，不满结果，再次标注后点击传播
 11. 其他内容: （增加其他与问题相关的内容）
 NVIDIA 系统信息报告，创建于： 08/08/2022 15:58:52
系统名称： DESKTOP-7M0A3LD

[显示]
操作系统：	Windows 10 Home China, 64-bit
DirectX 版本：	12.0 
GPU 处理器：		NVIDIA GeForce GTX 1660 SUPER
驱动程序版本：			516.94
驱动器类型：			DCH
Direct3D 功能级别：		12_1
CUDA 核心：		1408 
核心时钟：			1785 MHz 
内存数据速率：			14.00 Gbps
内存接口：			192-位 
内存带宽：			336.05 GB/秒
全部可用的图形内存：		14209MB
专用视频内存：			6144 MB GDDR6
系统视频内存：			0MB
共享系统内存：			8065MB
视频 BIOS 版本：		90.16.5A.00.22
IRQ：			Not used
总线：			PCI Express x16 Gen3
设备 ID：			10DE 21C4 00007377
部件编号：			G161 0026

[组件]

nvui.dll		8.17.15.1694		NVIDIA User Experience Driver Component
nvxdplcy.dll		8.17.15.1694		NVIDIA User Experience Driver Component
nvxdbat.dll		8.17.15.1694		NVIDIA User Experience Driver Component
nvxdapix.dll		8.17.15.1694		NVIDIA User Experience Driver Component
NVCPL.DLL		8.17.15.1694		NVIDIA User Experience Driver Component
nvCplUIR.dll		8.1.940.0		NVIDIA Control Panel
nvCplUI.exe		8.1.940.0		NVIDIA Control Panel
nvLicensingS.dll		6.14.15.1694		NVIDIA Licensing Server
nvViTvSR.dll		31.0.15.1694		NVIDIA Video Server
nvViTvS.dll		31.0.15.1694		NVIDIA Video Server
nvDispSR.dll		31.0.15.1694		NVIDIA Display Server
nvDispS.dll		31.0.15.1694		NVIDIA Display Server
nvDevToolSR.dll		31.0.15.1694		NVIDIA Licensing Server
nvDevToolS.dll		31.0.15.1694		NVIDIA 3D Settings Server
nvWSSR.dll		31.0.15.1694		NVIDIA Workstation Server
nvWSS.dll		31.0.15.1694		NVIDIA Workstation Server
PhysX		09.21.0713		NVIDIA PhysX
NVCUDA64.DLL		31.0.15.1694		NVIDIA CUDA 11.7.101 driver
nvGameSR.dll		31.0.15.1694		NVIDIA 3D Settings Server
nvGameS.dll		31.0.15.1694		NVIDIA 3D Settings Server

**Comment by haoyuying** [comment]
我们会持续跟进该问题的，感谢您的反馈

**Comment by haoyuying** [comment]
初步定义bug是由于paddle，cuda及cudnn版本不匹配导致的，建议使用如下环境，没有复现该问题：
PaddlePaddle：2.3.0/2.3.1
CUDA：10.2.89
cudnn：7.6.5
