### ISSUE TITLE
[General Issue]Matting保存结果报错

### ISSUE THREAD

**Issue by T0L0ve** [PaddlePaddle/PaddleSeg#2414]
paddlepaddle2.6版本
运行Matting操作流程就和quickstart里的一样，在进行背景替换时会报一个错误
![image](https://user-images.githubusercontent.com/38580985/183390057-96218523-6073-4b71-8e5b-3d0b53ef2194.png)
我看了下应该是np数组大小不一致导致的。
![image](https://user-images.githubusercontent.com/38580985/183390287-e0118084-08e0-4ce9-9517-e5b6946adf1a.png)
这边fg的大小是（1,1,3）。
然后我在_estimate_fb_ml这个函数里加了个print语句
![image](https://user-images.githubusercontent.com/38580985/183390638-5cf0ecf3-6d9f-4657-a613-1c7ce255980d.png)
然后代码就正常运行了
![image](https://user-images.githubusercontent.com/38580985/183390786-68bbc995-296a-4b76-8336-e5c0efdab564.png)
我不能理解是什么原因导致的

**Comment by wuyefeilin** [comment]
看提示是因为输入尺寸不匹配的导致的，确定没有修改过代码吗

**Comment by T0L0ve** [comment]
> 看提示是因为输入尺寸不匹配的导致的，确定没有修改过代码吗

没有修改过，这行print语句是唯一自己写的代码
