### ISSUE TITLE
[Feature Request]PaddleSeg做表格识别

### ISSUE THREAD

**Issue by ANDROIDTODO** [PaddlePaddle/PaddleSeg#2416]
Welcome to propose a new feature! To help us understand your great feature, please provide following information:
1. A clear and concise description of the proposed feature.
2. Tell us why the feature is useful. 
3. If possible, please show related codes .

---

欢迎提出一个新功能需求，为了帮助我们更好理解您的需求，辛苦提供下面信息：
1. 清晰简洁的语言提出新功能需求。
2. 请描述这个需求的必要性。
3. 如果可以，辛苦您提供相关代码实现效果。

Hi,
请问使用PaddleSeg做表格识别，
标注为：
1. 实体线的横线 
2. 实体线的竖线 
3. 不可见的横线 
4.不可见的竖线

请问这个可行吗
参照：https://cloud.tencent.com/developer/article/1452973

**Comment by juncaipeng** [comment]
可以做，需要自己标注数据，然后使用paddleseg进行训练。

**Comment by dinglei0719** [comment]
> 可以做，需要自己标注数据，然后使用paddleseg进行训练。

PaddleSeg 现有的模型，有哪个是支持多任务的么？就是能同时预测表格的横线和竖线（因为线会有交点，多以有的像素会有2个label，有哪个模型支持1个encoder接2个decoder的么）

**Comment by juncaipeng** [comment]
最近paddleocr开源了表格文字提取的功能，你可以取看看，说不定可以直接使用。
https://github.com/PaddlePaddle/PaddleOCR
https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/ppstructure
