### ISSUE TITLE
[General Issue]关于设置损失函数的相关问题

### ISSUE THREAD

**Issue by veritas0505yg** [PaddlePaddle/PaddleSeg#2423]
专家您好，想请教一下，如何在config文件中设置不同的损失函数所需要的参数？我似乎没有在官方文档中找到设置这些参数的教学部分，官方给的全流程跑通案例中config只介绍了CrossEntropyLoss和coef参数设置为[1, 1, 1]

Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by juncaipeng** [comment]
通常多个loss，可以设置主loss的权重大一点，辅助loss的权重小一点。 具体可以调参试下，不过对精度来说影响不是非常大。
