### ISSUE TITLE
[Bug] EISeg 在AIstudio中无法启动

### ISSUE THREAD

**Issue by htlbayytq** [PaddlePaddle/PaddleSeg#2428]
通过pip安装EISeg后，用eiseg命令无法启动：

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：paddleseg-2.6.0
 2. PaddlePaddle版本：PaddlePaddle 2.3.1
 3. 操作系统信息：Ubuntu 16.04 (BML codelab）
 4. Python版本号：3.7.4

![image](https://user-images.githubusercontent.com/83695691/183867279-eec3bca3-117c-43fb-9ec4-dcf6e8600809.png)
![image](https://user-images.githubusercontent.com/83695691/183867429-b0523d60-ebe9-4758-af92-bbad66d97a72.png)
![image](https://user-images.githubusercontent.com/83695691/183867538-e1685365-660c-4264-831b-46ed6be5b961.png)

**Comment by haoyuying** [comment]
报错显示opencv安装有问题，可以参考https://blog.csdn.net/noirblack/article/details/125333014
我是用的是4.5.5.64，您可以参考一下。

**Comment by htlbayytq** [comment]
haoyuying老师您好，我想先和您确认一下EISeg是否可以直接从咱AIStudio里启动并使用呢？   

再具体一些，在BML codelab中直接按照EISeg的安装教程对EISeg进行安装（pip install eiseg），然后直接在BML codelab启动EISeg去使用（eiseg），理论上这样是可以的吧？

**Comment by haoyuying** [comment]
在本地用吧，eiseg必须要有带界面的环境才可以，可以用本地电脑安装使用

**Comment by htlbayytq** [comment]
了解了，也就是说除了本地，EISeg无法在AIStudio上用，对嘛haoyuying老师？

（因为我的电脑是mac，没有gpu，EISeg我本地试了一下，非常卡。。。     而且这样的话AIStudio里的算力也派不上用场了。。。

**Comment by haoyuying** [comment]
是你的图比较大吗，轻量化模型应该不会卡，我也用的mac
