### ISSUE TITLE
VisualDL log change curve

### ISSUE THREAD

**Issue by Winnie202** [PaddlePaddle/PaddleSeg#2443]
Thanks for your code contribution, the following is my relevant training environment :

platform: Linux-5.15.0-43-generic-x86_64-with-debian-bullseye-sid
Python: 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59) [GCC 7.5.0]
Paddle compiled with cuda: True
NVCC: Build cuda_11.3.r11.3/compiler.29920130_0
cudnn: 8.2
GPUs used: 1
CUDA_VISIBLE_DEVICES: 0
GPU: ['GPU 0: NVIDIA GeForce', 'GPU 1: NVIDIA GeForce']
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PaddleSeg: 2.6.0
PaddlePaddle: 2.2.2
OpenCV: 4.2.0

I use ocrnet to train my task, but the trend doesn't feel normal, please help me
![2022-08-12 10-39-03屏幕截图](https://user-images.githubusercontent.com/86768013/184277715-0fd1e98e-c96b-4807-b52b-0d49e5bc4b88.png)

![2022-08-12 10-56-02屏幕截图](https://user-images.githubusercontent.com/86768013/184277670-53aac0a6-e1fc-4718-b442-265623684321.png)

**Comment by shiyutang** [comment]
It seems that your training process is broken. Can you train from start and provide the whole vdl which includes the validation metric? I can not see anything wrong in the training config. Some of the parameters is relevant to your data.

**Comment by Winnie202** [comment]
> 看来你的训练过程被打破了。您可以从头开始训练并提供包含验证指标的整个 vdl 吗？我在训练配置中看不到任何错误。一些参数与您的数据相关。

Because cuda memory is not enough, it is interrupted. Is it normal that the value of train/lr does not change?

**Comment by shiyutang** [comment]
No, This is not normal. If your cuda memory is not enough, you can try to use smaller batchsize.
