### ISSUE TITLE
[General Issue] 如何把Paddleseg生成的model.pdparams模型转成tensorflow支持的模型呢

### ISSUE THREAD

**Issue by zhenzi0322** [PaddlePaddle/PaddleSeg#2447]
如何把Paddleseg生成的model.pdparams模型转成tensorflow支持的模型呢

**Comment by haoyuying** [comment]
paddle支持将paddle转化成onnx，然后再用onnx转化成tensorflow吧。具体转化可以去该repo下提问：https://github.com/PaddlePaddle/Paddle2ONNX

**Comment by zhenzi0322** [comment]
> paddle支持将paddle转化成onnx，然后再用onnx转化成tensorflow吧。具体转化可以去该repo下提问：https://github.com/PaddlePaddle/Paddle2ONNX

好的，我已经知道了，谢谢
