### ISSUE TITLE
[General Issue]关于Cityscapes数据集的有关问题

### ISSUE THREAD

**Issue by huangwan-jiayi** [PaddlePaddle/PaddleSeg#2449]
请问是否又方法将cityscapes数据集中的验证集中的label改变下可视化效果。
原：
![1a354a0f8d956f8f0e5b5a260f4109a](https://user-images.githubusercontent.com/71338215/184588048-b557244e-1cb4-4d68-beea-16d28f3376ea.png)
想修改成与预测（predict.py）出来结果相类似的这种：
![4d060a84470e6467ed212b77479927d](https://user-images.githubusercontent.com/71338215/184588121-8784a41f-baf1-47cf-93dc-74c38525c651.png)

 另外还想请教，如何获取得到cityscapes数据集中test集的label，便于对自己修改后的模型用测试集进行评估，目前只能用验证集评估。

**Comment by haoyuying** [comment]
只能讲gt用https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/paddleseg/core/predict.py#L141
这个函数再重新映射一下生成这个结果了。test官方应该没有放出label。

**Comment by huangwan-jiayi** [comment]
> 只能讲gt用https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/paddleseg/core/predict.py#L141 这个函数再重新映射一下生成这个结果了。test官方应该没有放出label。

可以 指教一下怎么做映射么？ 另外，我看别人论文里在test集做的评估指标是怎么得到的呢？

**Comment by haoyuying** [comment]
就需要你把label的格式转化成pred的输入格式，colormap的格式也保持统一，然后调用utils.visualize.get_pseudo_color_map这个函数。test是有一个网站上传，具体可以找一下cityscape的官网查找。
