### ISSUE TITLE
[General Issue] 为什么PaddleSeg中的Modnet模型在PaddleLite中预测不了效果呢

### ISSUE THREAD

**Issue by zhenzi0322** [PaddlePaddle/PaddleSeg#2451]

**Comment by wuyefeilin** [comment]
一般是数据预处理的问题。您详细检查下你的数据预处理和配置文件中val_dataset下transforms的处理流程是否一致

**Comment by zhenzi0322** [comment]
> 一般是数据预处理的问题。您详细检查下你的数据预处理和配置文件中val_dataset下transforms的处理流程是否一致

ok
