### ISSUE TITLE
pp-Human的v2版本用的是什么算法？

### ISSUE THREAD

**Issue by TD-wzw** [PaddlePaddle/PaddleSeg#2454]
请问下人像分割v2里边的MobileSeg这个使用的是什么算法？只看到了backbone是mobilenetv3，想知道具体是由什么算法哪个网络改进得到的v2版本的人像分割网络

**Comment by juncaipeng** [comment]
是PaddleSeg自己搭建的移动端模型，具体可以参考

![image](https://user-images.githubusercontent.com/52520497/184791444-4699fddf-279b-4cba-b8bd-204ebe9d8b83.png)
