### ISSUE TITLE
[General Issue]空间注意力加通道注意力

### ISSUE THREAD

**Issue by m828** [PaddlePaddle/PaddleSeg#2456]
我用ppliteseg跑自己数据集，损失函数为交叉熵，miou为81.2，损失函数改为focal，miou为83.4。
我发现源码只用了空间注意力，我就尝试把通道注意力加进去，然后损失函数为交叉熵，miou为83.0（明显提升了），但是损失函数改为focal，开始的时候损失就变的很低，但miou并不高，也提不上去，只有四五十，与前面的三次相比，差的很多，所以想问一下这样的情况怎么解决，是过拟合了吗？

**Comment by m828** [comment]
![Uploading image.png…]()
空间注意力加通道注意力+focal的损失

**Comment by juncaipeng** [comment]
focal loss相比CE loss，数值会更小，是否可以多训练一下，同时调整一下学习率。

**Comment by m828** [comment]
> 

是训练的不够吗，相比CE，训练已经翻了四倍，学习率调小是否可行，可以的话我再尝试一下

**Comment by juncaipeng** [comment]
嗯  需要你尝试调参

**Comment by m828** [comment]
> 嗯 需要你尝试调参

好的，感谢
