### ISSUE TITLE
[General Issue] resizeop 结构修改

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/PaddleSeg#2457]
我看到结构中大部分采用的都是Resize op 上采样，但是这种形式的导出并不是一种常用的算子，有没有一种普通的上采样层替换掉这个resize 例如使用反卷积层替换，会不会影响特征层提取特征等等

**Comment by juncaipeng** [comment]
resize op还是比较常见的，不同预测框架都可以支持对齐。
反卷积的算量比较大，而且可能出现棋盘效应。

**Comment by chen-del** [comment]
@juncaipeng 我看到resize op roi 里面相比于常见的 folat32[0]有所区别，它貌似使用的是folat32[8] [1,1,1,1,1,1,1,1]

**Comment by juncaipeng** [comment]
可以详细解释下吗？ 没太懂你的意思

**Comment by chen-del** [comment]
@juncaipeng 就是将resize op 的roi 和 scales 设置为空张量，而不是使用roi = float32[8]   [1,1,1,1,1,1,1,1]。有点特别

**Comment by juncaipeng** [comment]
通常resize可视化都是这样啊，没有roi

![image](https://user-images.githubusercontent.com/52520497/185308044-9854e5bd-cced-4814-9c4f-0d1fb7e51f98.png)

**Comment by chen-del** [comment]
转化成onnx 好像就有了
![image](https://user-images.githubusercontent.com/58769772/185324223-e60aa0c6-592d-4434-b21a-2282741a071d.png)

**Comment by juncaipeng** [comment]
这个不太清楚，应该对速度影响不大。

**Comment by chen-del** [comment]
@juncaipeng 有没有方式将 align_corners 设置为True ,因为这种方式之后转化的onnx属性是half_pixel , 我想将其变为align_corners，这样子对结果有影响吗
![image](https://user-images.githubusercontent.com/58769772/186837942-9c194182-6bb0-400c-ad50-952f0cfa85cb.png)
