### ISSUE TITLE
[General Issue] 模型优化后使用不了gpu

### ISSUE THREAD

**Issue by zhenzi0322** [PaddlePaddle/PaddleSeg#2461]
您好！我通过`paddelite`进行模型优化之后，使用不了机器上的`gpu`。这是为什么呢

**Comment by wuyefeilin** [comment]
麻烦给一下具体的优化过程及相关的环境信息。如果报错信息，请提供相关日志

**Comment by zhenzi0322** [comment]
> 麻烦给一下具体的优化过程及相关的环境信息。如果报错信息，请提供相关日志

没有报错信息，cpu下可以正常使用，就是使用不了`gpu`。

环境信息如下：
```
python=3.7.5
paddlelite=2.11
```

**Comment by juncaipeng** [comment]
paddlelite的相关问题，可以在paddleite repo提issue咨询，谢谢

https://github.com/PaddlePaddle/Paddle-Lite
