### ISSUE TITLE
eiseg can't install

### ISSUE THREAD

**Issue by Winnie202** [PaddlePaddle/PaddleSeg#2462]
When I use eiseg annotation, I get the following error,how to solve it please
![2022-08-17 13-05-38屏幕截图](https://user-images.githubusercontent.com/86768013/185039116-5aa7136f-edb0-4360-a0d8-2b29cc3699cb.png)

![2022-08-17 13-06-01屏幕截图](https://user-images.githubusercontent.com/86768013/185039205-3ad7a0c0-312d-4a8d-b683-29a4292b9ba2.png)

**Comment by haoyuying** [comment]
opencv-python doesn't  install successfully, maybe you can try this version: 4.5.5.64
