### ISSUE TITLE
[General Issue] 怎么使用golang调用model.pdiparams和model.pdmodel这两个文件进行预测

### ISSUE THREAD

**Issue by zhenzi0322** [PaddlePaddle/PaddleSeg#2463]
您好，我想尝试使用`Golang`来调用导出后的模型。请问下官方有没有`PaddleSeg`使用`golang`的示例呢？或者是怎么调用模型并进行预测呢？

**Comment by wuyefeilin** [comment]
您好， PaddleSeg 暂时没有使用golang的示例

**Comment by zhenzi0322** [comment]
> 您好， PaddleSeg 暂时没有使用golang的示例

好的。
