### ISSUE TITLE
[General Issue] Mattings中的estimate_foreground_ml函数执行时间较长

### ISSUE THREAD

**Issue by zhenzi0322** [PaddlePaddle/PaddleSeg#2464]
请问有什么办法可以优化estimate_foreground_ml函数中的执行时间较长问题不？

**Comment by wuyefeilin** [comment]
如果追求速度可以通过--fg_estimate False关闭前景评估功能

**Comment by zhenzi0322** [comment]
> 如果追求速度可以通过--fg_estimate False关闭前景评估功能

这个知道，如果关闭前景评估就会出现另一个问题，抠好的图片体积会变得很大，边缘还会有白边。

**Comment by wuyefeilin** [comment]
如果是单纯为了减小体积的话可通过将alpha范围外的像素值设置成0，这样存储图片的时候就会变小很多

**Comment by zhenzi0322** [comment]
> 如果是单纯为了减小体积的话可通过将alpha范围外的像素值设置成0，这样存储图片的时候就会变小很多

这种我试过，但是处理后的效果不好

**Comment by wuyefeilin** [comment]
目前我们没有满足您要求的具体方法，如果您有具体的项目应用，咱们可以进行合作，共同探讨哈

**Comment by zhenzi0322** [comment]
> 目前我们没有满足您要求的具体方法，如果您有具体的项目应用，咱们可以进行合作，共同探讨哈

好的，怎么探讨呢？有qq或wx联系方式不

**Comment by wuyefeilin** [comment]
<img width="345" alt="image" src="https://user-images.githubusercontent.com/30919197/186378726-ce92545f-bb1d-42cb-a099-d204cdf1d8f3.png">
可以扫码加群哈
