### ISSUE TITLE
[General Issue]推理错误

### ISSUE THREAD

**Issue by zqy396** [PaddlePaddle/PaddleSeg#2467]
我在推理的时候，输出的预测结果shape不对，按理说应该是（64，128，128），结果却是（1，64，128，128），错误的npy大小约为正常预测结果的两倍。这是什么原因？
---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（PaddleSeg release/2.3）
 2. PaddlePaddle版本：（PaddlePaddle 2.3.0）
 3. 操作系统信息：（Linux）
 4. Python版本号：（python3.7）
 5. CUDA/cuDNN版本：（ CUDA10.2）
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by shiyutang** [comment]
The shape of the predicted result is determined by your network and input.  If you want to change the shape of the output, you can change it at the end of network or change the input.
