### ISSUE TITLE
[General Issue]  我想问下数据是否支持单通道输入进行训练

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/PaddleSeg#2474]
我看到通道输入维度时三通道的，怎么变为通道进行训练，如果使用单通道也就是灰度输入，我使用voc进行训练会不会受到影响

**Comment by juncaipeng** [comment]
目前没有支持设置输入通道数，默认都是三通道，不过我们会考虑尽快加入。（预计一两周时间）
如果你现在就想使用，需要简单修改一下数据处理模块和模型的第一个输入conv。或者将图像改为3通道的。

**Comment by chen-del** [comment]
@juncaipeng  那我直接改输入哪里嘛，直接取输入的第一个通道，放入到里面进行运算，另外我想在mobleseg网络前面加上一个特征提取层，需要怎么做

**Comment by chen-del** [comment]
@juncaipeng 或者需要简单修改一下数据处理模块和模型的第一个输入conv，需要在那个位置进行修改。因为我看到大部分都是配置文件或者是模块。

**Comment by juncaipeng** [comment]
你可以等一等，我们这两天就提个pr支持单通道输入。

**Comment by chen-del** [comment]
我重新梳理一下这个，PR后，是首先图片输入任意选择单通道和三通道输入是嘛，然后标签label可以是伪彩图也不用改成灰度是嘛进行训练，也就是单通道图片加label伪彩图进行训练是嘛

**Comment by chen-del** [comment]
@juncaipeng

**Comment by juncaipeng** [comment]
对

**Comment by chen-del** [comment]
@juncaipeng ,下一周能增加出，这个PR功能，能快一丢丢嘛，因为时间上比较赶，谢谢！

**Comment by juncaipeng** [comment]
PR： https://github.com/PaddlePaddle/PaddleSeg/pull/2496

使用示例如下，在配置文件中的数据集部分，添加img_channels字段等于1
![image](https://user-images.githubusercontent.com/52520497/187429090-5394ae3f-b9db-4e3e-9b22-c62806122938.png)

**Comment by chen-del** [comment]
@juncaipeng，谢谢
