### ISSUE TITLE
[General Issue]关于EIseg中是否可以预先导入mask的问题

### ISSUE THREAD

**Issue by xieyifeng** [PaddlePaddle/PaddleSeg#2482]
1. 请问EIseg中可以预先导入一些mask信息么，如果可以的话是怎么操作的
2. 请问EIseg中使用掩膜和不使用掩膜有什么区别

**Comment by haoyuying** [comment]
eiseg能够导入用eiseg标注的结果，用导入文件夹的方式会自动在文件夹下保存标注结果，下次标注该文件夹的时候会自动导入上次标注的结果，但目前图像标注支持，视频是不支持导入的。
使用掩膜是使用上一次标注生成的mask作为先验信息进一步推倒，不使用就是不用该部分先验信息，具体可以参考ritm的论文。
