### ISSUE TITLE
Focal Loss 疑问

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/PaddleSeg#2486]
Focal Loss 损失在yaml文件中如何配置每个类别权重 ，我按照softmaxloss那种配置形式是有问题的
![image](https://user-images.githubusercontent.com/58769772/186813392-0e180226-bab0-48b0-be8a-5b64c9d7ff1a.png)
报错： 
assert logit.shape[1] == 2, "The channel of logit should be 2."
AssertionError: The channel of logit should be 2.

**Comment by haoyuying** [comment]
focal loss 暂不支持为每个类别配置权重，可更换为cross entropy loss支持该功能。
