### ISSUE TITLE
[General Issue] Jeston Xavier NX上TRT部署失败

### ISSUE THREAD

**Issue by lizhuo1414** [PaddlePaddle/PaddleSeg#2487]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: PaddleSeg release/2.6
 2. PaddlePaddle version: PaddlePaddle GPU 2.3.2
 3. Operation system: Ubuntu 18.04
 4. Python version: Python3.6
 5. CUDA/cuDNN version: CUDA10.2，cuDNN 8.2.1 Tensorrt 8.0.1.6 
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：PaddleSeg release/2.6
 2. PaddlePaddle版本：PaddlePaddle GPU 2.3.2
 3. 操作系统信息：Ubuntu 18.04
 4. Python版本号：Python3.6
 5. CUDA/cuDNN版本：CUDA10.2，cuDNN 8.2.1 Tensorrt 8.0.1.6
 6. GCC 7.5
 可以用原生GPU运行，PaddleSeg/deploy/cpp/run_seg_gpu.sh运行没有问题。
使用PaddleSeg/deploy/cpp/run_seg_gpu_trt.sh提示
InvalidArgumentError: The input [concat_1.tmp_0] shape of trt subgraph is [-1,256,-1,-1], please enable trt dynamic_shape mode by SetTRTDynamicShapeInfo. (at /home/paddle/data/wangye19/tag_release/remove_paddle/Paddle/paddle/fluid/inference/tensorrt/engine.h:96)
参照PaddleSeg/docs/deployment/inference/cpp_inference_cn.md，使用以下命令
python3 ../python/collect_dynamic_shape.py --config stdc1seg_infer_model/deploy.yaml --image_path ./cityscapes_demo.png --dynamic_shape_path ./dynamic_shape.pbtxt
报以下错误：
![image](https://user-images.githubusercontent.com/29418627/186838808-254d216c-4306-4b98-b20c-aea8a4da6ebb.png)
请问怎样才能用TRT部署分割推理？

**Comment by OpenCDR** [comment]
您好，这个问题有没有解决呢

**Comment by lizhuo1414** [comment]
> 您好，这个问题有没有解决呢

没

**Comment by juncaipeng** [comment]
收到，这是一个bug，我们这两天就会修复。  
上一个版本 2.5 应该没有这个bug，如果你们着急，可以先使用上个版本。

**Comment by juncaipeng** [comment]
修复pr：https://github.com/PaddlePaddle/PaddleSeg/pull/2490
