### ISSUE TITLE
[Bug] 设置 random seed 无效

### ISSUE THREAD

**Issue by liyunfan13** [PaddlePaddle/PaddleSeg#2488]
您好，

我在训练时使用 --seed 参数， 但是在使用同一个seed的情况下，先后两次训练的结果不一样。
我用的是教程中的训练指令：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/docs/train/train.md

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：2.6
 2. PaddlePaddle版本：2.3.1
 3. 操作系统信息：Linux
 4. Python版本号：3.8.5
 5. CUDA/cuDNN版本：CUDA11.6/cuDNN8.4.1
 6. 完整的代码：(若修改过原代码，请提供修改前后代码对比）
 7. 详细的错误信息、相关log：（若使用多卡，log默认保存在log/worklog.0）
 8. 运行指令或复现步骤：
 9. 其他内容: （增加其他与问题相关的内容）

**Comment by shiyutang** [comment]
由下图可见，random seed 只能控制关于paddle/numpy/random生成数据时一致，但是训练结果一致还与数据shuffle方式，网络初始化、卷积计算等有关，如果需要获取完全相同的训练结果，建议关闭shuffle，使用同样参数初始化，并打开[cudnn_deterministic](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/flags/cudnn_cn.html#flags-cudnn-deterministic)开关。
<img width="401" alt="image" src="https://user-images.githubusercontent.com/34859558/187106801-afa7c709-cae9-41fe-b040-7b851ea98a77.png">

**Comment by liyunfan13** [comment]
好的，谢谢！
