### ISSUE TITLE
[Bug] only support 'to_tensor()' in dynamic graph mode

### ISSUE THREAD

**Issue by xieyifeng** [PaddlePaddle/PaddleSeg#2491]
在运行paddleseg的时候，出现问题：
We only support 'to_tensor()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode.
一般第一次运行不会出现上述问题，第二次运行的时候就是报错。
paddleseg环境：
paddle-bfloat：0.1.7
paddlepaddle-gpu：2.3.2.post116

**Comment by haoyuying** [comment]
请问你使用的cuda，cudnn的环境及运行的paddleseg模型是什么呢，出现该问题的原因一般是由于cuda、cudnn及paddle版本不匹配导致的，建议从该方面进行排查。建议使用cuda10.2及cudnn7.6.5

**Comment by juncaipeng** [comment]
可以将复现方法提供一下。

**Comment by Zhengliang-Zhang** [comment]
PaddlePaddle：2.3.1
CUDA：10.2.89
cudnn：7.6.5
也出现了相同问题

**Comment by juncaipeng** [comment]
请问执行的脚本是什么？  需要提供详细的复现步骤，我们来debug。

**Comment by Zhengliang-Zhang** [comment]
Paddlepaddle 2.3.2CUDA 10.2.89
cudnn 7.6.5


在pycharm终端中输入eiseg，等待开启后关闭eiseg，紧接着再次输入，就有较大概率报错，在等待一段时间后恢复正常
在cmd窗口中输入eiseg，等待开启后关闭eiseg，紧接着再次输入，就有较大概率报错且恢复几率很小


另外
在python3.10版本中，程序导入视频点击播放按钮后，闪退报错信息为传入了浮点数？已经删除了3.10版本，记忆不是很清晰了
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月8日(星期四) 晚上7:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleSeg] [Bug] only support &#39;to_tensor()&#39; in dynamic graph mode (Issue #2491)





 
请问执行的脚本是什么？  需要提供详细的复现步骤，我们来debug。

**Comment by haoyuying** [comment]
有没有具体的报错代码，这个报错是不是在使用视频模型之后就会出现paddle.to_tensor的错误，还是不使用video模型就会报错呢？

**Comment by Zhengliang-Zhang** [comment]
> 有没有具体的报错代码，这个报错之后不是在使用视频模型出现orpaddle.to_tens的错误，还是不使用视频模型报错呢？

第一个bug似乎与 https://github.com/PaddlePaddle/Paddle/issues/39027 中提到的相同，但是我没有解决。
第二个bug是另一个独立的bug，在python3.10版本中导入视频点击播放按钮就会报错：open start(self, int): argument 1 has unexpected type 'float'   start(self): too many arguments

**Comment by Zhengliang-Zhang** [comment]
> > 有没有具体的报错代码，这个报错之后不是在使用视频模型出现orpaddle.to_tens的错误，还是不使用视频模型报错呢？
> 
> 第一个bug似乎与 [PaddlePaddle/Paddle#39027](https://github.com/PaddlePaddle/Paddle/issues/39027) 中提到的相同，但是我没有解决。 第二个bug是另一个独立的bug，在python3.10版本中导入视频点击播放按钮就会报错：open start(self, int): argument 1 has unexpected type 'float' start(self): too many arguments

在debug模式下也会有这个bug，不过程序可以正常运行

**Comment by haoyuying** [comment]
https://github.com/PaddlePaddle/PaddleSeg/blob/12b008034854b95c70621f36bb67d680edc5d106/EISeg/eiseg/run.py#L82
第一个bug把这一行注释掉看看还有没有
第二个我没复现出来，是只有python3.10才会出现吗，是必现问题不？

**Comment by Zhengliang-Zhang** [comment]
> https://github.com/PaddlePaddle/PaddleSeg/blob/12b008034854b95c70621f36bb67d680edc5d106/EISeg/eiseg/run.py#L82
> 
> 
> 第一个bug把这一行注释掉看看还有没有
> 第二个我没复现出来，是只有python3.10才会出现吗，是必现问题不？

第一个注释掉就没有这个bug了
第二个是只有3.10才会出现，是必现问题。我在python3.10下安装后就出现了此bug，飞桨cpu版本也不例外

**Comment by Zhengliang-Zhang** [comment]
> https://github.com/PaddlePaddle/PaddleSeg/blob/12b008034854b95c70621f36bb67d680edc5d106/EISeg/eiseg/run.py#L82
> 
> 
> 第一个bug把这一行注释掉看看还有没有
> 第二个我没复现出来，是只有python3.10才会出现吗，是必现问题不？


我使用肝脏的传播模型的传播效果也非常差，是和这个有关吗？

**Comment by haoyuying** [comment]
发一个视频我们来看下？

**Comment by Zhengliang-Zhang** [comment]
https://user-images.githubusercontent.com/112454215/189836105-6825523f-b960-43e7-a2d4-8c4a190ae966.mp4

**Comment by haoyuying** [comment]
您提出的两个问题我们已经定位，近期将会发一个新版的eiseg，发布之后我将在本issue下通知您，感谢您的反馈

**Comment by haoyuying** [comment]
您好，您提出的两个问题已经在eiseg1.0.3修复，请先卸载目前的eiseg，下载1.0.3版本的eiseg进行体验

**Comment by Zhengliang-Zhang** [comment]
收到，谢谢
