### ISSUE TITLE
[General Issue]matting 使用PPM-100数据集训练，训练后的模型预测效果怎么会是这样的？

### ISSUE THREAD

**Issue by 0Xiao0** [PaddlePaddle/PaddleSeg#2493]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）
![1661843536120](https://user-images.githubusercontent.com/43536870/187373354-e1f615d8-b56b-4e0e-9102-18d9fbe0167d.png)
运行命令：
![image](https://user-images.githubusercontent.com/43536870/187373532-72aee3d6-a17a-41b6-b6e3-35526bceba68.png)

**Comment by wuyefeilin** [comment]
PPM-100 is a tutorial dataset which is too small to support you to train a high quality model. Out pretrained model can be used directly.

**Comment by 0Xiao0** [comment]
> thankyou
