### ISSUE TITLE
matting/modnet 测试效果不如官方开源modnet 测试效果[Bug]

### ISSUE THREAD

**Issue by ujsyehao** [PaddlePaddle/PaddleSeg#2498]
首先是官方开源 https://github.com/ZHKKKe/MODNet 测试图片效果

![matte](https://user-images.githubusercontent.com/17454232/187460623-47ef90fa-3b94-4dc8-aa21-87557667f165.png)

第二个是使用 https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/Matting/configs/modnet/modnet-mobilenetv2.yml 测试图片效果
![input_full_alpha_modnet_mobilenetv2](https://user-images.githubusercontent.com/17454232/187460925-0d5b8549-f4da-4027-9a0f-bfa0eb685e0d.jpg)

图片右上角有明显的背景区域识别成了前景

**Comment by wuyefeilin** [comment]
It is not fair to compare by using one image. May be you can use more image witch is not in PPM-100.
