### ISSUE TITLE
关于loss.py中的dice_loss

### ISSUE THREAD

**Issue by fosaken** [PaddlePaddle/PaddleSeg#25]
&emsp;&emsp;您好，我在做二类分割的时候，使用了[loss.py](https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.1.0/pdseg/loss.py)中的[dice_loss](https://github.com/PaddlePaddle/PaddleSeg/blob/92ab56f22f895deb28593e0370f6b7f82a014b7f/pdseg/loss.py#L68)，但是程序总是在运行到`optimizer.minimize`那步报错，我看到默认使用的loss函数中有如下两个语句：
```
    label.stop_gradient = True
    ignore_mask.stop_gradient = True
```
&emsp;&emsp;然后我在dice_loss中也加入了这两句，程序可以运行了，但是损失变得浮动，不怎么下降。
## Q:
1.这个会影响loss的下降吗？
2.这个是dice_loss实现存在的问题吗？

**Comment by nepeplwu** [comment]
@fosaken ，感谢反馈：
1. 这样的修改不会影响loss的下降
2. dice_loss在0.1.0版本中还未开放，这样修改是正确的

**Comment by fosaken** [comment]
@nepeplwu 感谢解答，期待后续更新

**Comment by wuyefeilin** [comment]
@fosaken 新增dice_loss与bce_loss。可通过cfg.SOLVER.LOSS进行配置
