### ISSUE TITLE
用eiseg标注的json格式怎么转换成coco格式

### ISSUE THREAD

**Issue by duduzai2019** [PaddlePaddle/PaddleSeg#2502]
你好，我用eiseg标注的时候生成了json格式保存，请问一下还可以转换成coco格式吗
有没有提供转换的py文件，谢谢！！！

**Comment by haoyuying** [comment]
目前没有提供，我们近期会评估这项需求，感谢您的建议，增加之后我会在本issue通知您。

**Comment by Dandelionym** [comment]
so, is there any solution?
