### ISSUE TITLE
paddleSeg SPPM模块

### ISSUE THREAD

**Issue by jolt2017** [PaddlePaddle/PaddleSeg#2504]
请问最新发布的 paddleHumanSeg  里面的 SPPM 模块在哪个脚本里？ https://mp.weixin.qq.com/s/XkLJU7CvyGs7NCF0ypehFg

**Comment by Bobholamovic** [comment]
你好！PP-HumanSeg v2的实现在[此脚本](https://github.com/PaddlePaddle/PaddleSeg/blob/develop/paddleseg/models/pp_liteseg.py)中实现，SPPM模块位于：
https://github.com/PaddlePaddle/PaddleSeg/blob/dbc7a8471de1aad060975de099e52e6beffc94c0/paddleseg/models/pp_liteseg.py#L197
