### ISSUE TITLE
paddlesegFatalError: `Segmentation fault` is detected by the operating system.

### ISSUE THREAD

**Issue by surelon** [PaddlePaddle/PaddleSeg#2506]
框架版本:paddlePaddle 2.3.2，操作系统Linux（在百度飞桨平台上），python3.7.4，GPUv100 16G，
yml文件中只是修改了数据集路径
 详细的错误信息、相关log：
 /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/norm.py:654: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.
----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1662038445 (unix time) try "date -d @1662038445" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 1835 (TID 0x7fc9305c9700) from PID 0 ***]
 运行指令或复现步骤：
 !export CUDA_VISIBLE_DEVICES=0 # 设置1张可用的卡
!python PaddleSeg/train.py \
       --config PaddleSeg/configs/deeplabv3p/deeplabv3p_resnet50_os8_voc12aug_512x512_40k.yml \
       --do_eval \
       --use_vdl \
       --save_dir output \
       --save_interval 500 \

**Comment by juncaipeng** [comment]
从你给出的log看不出具体问题，大概率是外部环境的问题，建议先按照[quick start](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/docs/quick_start_cn.md)跑一下看是否还出错

**Comment by surelon** [comment]
好的，谢谢老师


| |
康朔
|
|
***@***.***
|
签名由网易邮箱大师定制
On 9/2/2022 ***@***.***> wrote：

从你给出的log看不出具体问题，大概率是外部环境的问题，建议先按照quick start跑一下看是否还出错
