### ISSUE TITLE
BiseNet转onnx，onnxruntime推理没结果

### ISSUE THREAD

**Issue by zxc14751475** [PaddlePaddle/PaddleSeg#2507]
1. PaddleSeg版本：PaddleSeg 2.6
 2. PaddlePaddle版本：PaddlePaddle 2.1.0
 3. 操作系统信息：Linux
 4. Python版本号：Python3.6
 5. CUDA/cuDNN版本：CUDA10.2
 6. 其他内容: 
！使用paddlaseg里quick_start的bisenet_optic_disc_512x512_1k.yml训练的模型转onnx模型成功了，paddleseg中的predict.py能检测出，但用onnxruntime推理没有结果，请问我需要检查哪里来解决这个问题

**Comment by juncaipeng** [comment]
这个主要还是onnxruntime部分的代码问题，这部分请网络搜搜资料看看。
