### ISSUE TITLE
[Bug]加载模型（网络参数）或点击掩膜后软件闪退

### ISSUE THREAD

**Issue by GourdTG666** [PaddlePaddle/PaddleSeg#2508]
Thanks for your bug report. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Full codes: (if you modify any original code，please show the comparison of the codes before and after)
 7. Detailed error information, releated running log: (if using multi-gpus，the log is saved to log/worklog.0 by default)
 8. Running command or reproduce details：
 9. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：PaddleSeg-develop(1.0.0)
 2. PaddlePaddle版本：PaddlePaddle 2.3.2
 3. 操作系统信息：Windows10
 4. Python版本号：Python3.9
 5. CUDA/cuDNN版本：cuda11.3
 6. 完整的代码：没修改过原代码
 7. 详细的错误信息、相关log：

加载模型（命令行界面报错）：
INFO 2022-09-02 11:13:54,851 controller.py:111] User paddle compiled with gpu: use_gpu False
OMP: Error https://github.com/PaddlePaddle/PaddleSeg/pull/15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
QObject::~QObject: Timers cannot be stopped from another thread
![image](https://user-images.githubusercontent.com/110643877/188054056-294465f7-a1fb-45d5-93ac-1a7d61fef12e.png)
点击掩膜（命令行界面报错）：
Traceback (most recent call last):
  File "D:\Anaconda\envs\eiseg\PaddleSeg\EISeg\eiseg\app.py", line 966, in chooseMode
    self.controller.reset_predictor(predictor_params=self.predictor_params)
  File "D:\Anaconda\envs\eiseg\PaddleSeg\EISeg\eiseg\controller.py", line 322, in reset_predictor
    if self.model.model:
AttributeError: 'NoneType' object has no attribute 'model'

**Comment by GourdTG666** [comment]
大佬，帮我看看怎么弄？

**Comment by haoyuying** [comment]
看起来是paddle装错了，请检查paddle，cuda和cudnn三者版本是否匹配，重点检查是不是在有cuda的显卡上装了cpu版本的paddle

**Comment by GourdTG666** [comment]
我选的是cpu的版本啊，我这电脑是没独显的的，我就是用来简单学习一下的。

> 看起来是paddle装错了，请检查paddle，cuda和cudnn三者版本是否匹配，重点检查是不是在有cuda的显卡上装了cpu版本的paddle

**Comment by haoyuying** [comment]
看报错是paddle安装有问题，你先检查下paddle是否可用，看是否能够打印加载的静态图模型，如果paddle可用，请提供paddle版本及相关的本地环境，我们这边尝试复现一下。

**Comment by GourdTG666** [comment]
> paddle

![image](https://user-images.githubusercontent.com/110643877/189286763-777b0905-727b-46a0-9804-5784e0f4245c.png)

**Comment by GourdTG666** [comment]
paddle的版本号是2.3.2

**Comment by 19961115** [comment]
直接安装paddle-cpu就行，不要装gpu的，gpu的打开就闪退，懂我意思吧

**Comment by 1071189147** [comment]
我吧paddle降到2.2.2,就可以用了，其他的设置跟你的一样，cpu版，

**Comment by rayquazaMega** [comment]
昨天搞了一天这个问题，最后使用了这个方法[http://t.csdn.cn/ZDBYo](url)。若前述的paddle-cpu和2.2.2都不能解决问题的话可以试试这个。

具体而言是在_.\PaddleSeg\EISeg\eiseg\exe.py_最前面加上
`import os`
`os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"`

之后`python exe.py`即可运行

**Comment by zhaotun** [comment]
一样的问题，win10，paddle-cpu，加载模型闪退
