### ISSUE TITLE
模型量化问题

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/PaddleSeg#2520]
使用slim/quant/qat_train.py和slim/quant/qat_export.py训练导出的量化模型，如何部署体现加速效果？

直接将正常的模型替换成量化模型测试（python），在cpu上运行，没有明显的加速效果，模型存储体积还是和正常模型一样大。

怎样使用量化模型在cpu和gpu上部署呢？需要修改哪些配置？

**Comment by wuyefeilin** [comment]
请参考文档：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/docs/deployment/inference/python_inference_cn.md#4-%E9%A2%84%E6%B5%8B

**Comment by juncaipeng** [comment]
x86 cpu上部署量化模型： https://www.paddlepaddle.org.cn/inference/optimize/paddle_x86_cpu_int8.html
