### ISSUE TITLE
[General Issue] 无法访问  "懒人搜图"（Can not access the "No Code Matting" website ） 

### ISSUE THREAD

**Issue by buptzwl** [PaddlePaddle/PaddleSeg#2522]
文档地址：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/Matting/README_CN.md
遇到问题：无法访问懒人抠图演示网站（http://seg.itmanbu.com/）
错误信息：502 Bad Gateway

**Comment by wuyefeilin** [comment]
已修复
