### ISSUE TITLE
HumanSegMobileV2模型大小

### ISSUE THREAD

**Issue by zhanglaplace** [PaddlePaddle/PaddleSeg#2523]
你好，请问HumanSegMobileV2(human_pp_humansegv2_mobile.yml)的模型大小是20多M吗，感觉在移动端用是不是太大了，虽然推理速度很快。

**Comment by shiyutang** [comment]
如果有更快速度的需求，可以使用lite版本：PP-HumanSegV2-Lite.yml 手机端推理速度为15.3s：https://github.com/PaddlePaddle/PaddleSeg/blob/f3e14021ce/contrib/PP-HumanSeg/README_cn.md#32-%E9%80%9A%E7%94%A8%E4%BA%BA%E5%83%8F%E5%88%86%E5%89%B2%E6%A8%A1%E5%9E%8B

**Comment by zhanglaplace** [comment]
> 如果有更快速度的需求，可以使用lite版本：PP-HumanSegV2-Lite.yml 手机端推理速度为15.3s：https://github.com/PaddlePaddle/PaddleSeg/blob/f3e14021ce/contrib/PP-HumanSeg/README_cn.md#32-%E9%80%9A%E7%94%A8%E4%BA%BA%E5%83%8F%E5%88%86%E5%89%B2%E6%A8%A1%E5%9E%8B

嗯，这边也做了尝试，这个模型的体积要小一倍左右，推理速度也确实快一些。推理速度都还好，就是觉得模型体积有点大。
另外如果修改输入分辨率，如192->224或者256，是不是stdc和mbv3这些基础backbone都需要重新训练？

**Comment by shiyutang** [comment]
lite的模型体积也不满足要求么？ 其次修改输入分辨率不需要重新训练。

**Comment by juncaipeng** [comment]
导出为paddlelite的模型，体积只有5.4MB，再加上使用paddlelite提供的int16量化（只需要在opt转换中添加一个参数），模型体积可以再减小一半。
模型下载：https://github.com/PaddlePaddle/PaddleSeg/blob/f3e14021ce/contrib/PP-HumanSeg/README_cn.md#31-%E8%82%96%E5%83%8F%E5%88%86%E5%89%B2%E6%A8%A1%E5%9E%8B

**Comment by zhanglaplace** [comment]
> 重新

![image](https://user-images.githubusercontent.com/12178974/189788722-51e74b1c-4213-4da1-83d2-5fa7f08318bd.png)
这边导出的liteV2-lite模型有12M
- 导出方式
```shell
1、python ../../export.py --config configs/human_pp_humansegv2_lite_ZF.yml --model_path output/humansegv2_lite_ZF_Finetune/iter_30000/model.pdparams --save_dir output/humansegv2_lite_ZF_Finetune_Deploy/30000/ --without_argmax --with_softmax
2、paddle2onnx --model_dir output/humansegv2_lite_ZF_Finetune_Deploy/30000/ --model_filename model.pdmodel --params_filename model.pdiparams  --opset_version 11   --save_file output/humansegv2_lite_ZF_Finetune_Deploy/30000/output.onnx --input_shape_dict="{'x': [1,3,192,192]}"
```

**Comment by zhanglaplace** [comment]
> lite的模型体积也不满足要求么？ 其次修改输入分辨率不需要重新训练。

多谢，推理速度是满足的，只是导出的模型觉得有点大。

**Comment by juncaipeng** [comment]
哦  你是使用通用人像的模型。

> 嗯，这边也做了尝试，这个模型的体积要小一倍左右，推理速度也确实快一些。推理速度都还好，就是觉得模型体积有点大。 另外如果修改输入分辨率，如192->224或者256，是不是stdc和mbv3这些基础backbone都需要重新训练？
使用其他尺寸，应该也可以直接使用我们发布的权重进行再次微调。




> > 重新
> 
> ![image](https://user-images.githubusercontent.com/12178974/189788722-51e74b1c-4213-4da1-83d2-5fa7f08318bd.png) 这边导出的liteV2-lite模型有12M
> 
> * 导出方式
> 
> ```shell
> 1、python ../../export.py --config configs/human_pp_humansegv2_lite_ZF.yml --model_path output/humansegv2_lite_ZF_Finetune/iter_30000/model.pdparams --save_dir output/humansegv2_lite_ZF_Finetune_Deploy/30000/ --without_argmax --with_softmax
> 2、paddle2onnx --model_dir output/humansegv2_lite_ZF_Finetune_Deploy/30000/ --model_filename model.pdmodel --params_filename model.pdiparams  --opset_version 11   --save_file output/humansegv2_lite_ZF_Finetune_Deploy/30000/output.onnx --input_shape_dict="{'x': [1,3,192,192]}"
> ```

这个通用模型，我们暂时没有进行轻量化处理，后续会考虑加上

**Comment by zhanglaplace** [comment]
> 哦 你是使用通用人像的模型。
> 
> > 嗯，这边也做了尝试，这个模型的体积要小一倍左右，推理速度也确实快一些。推理速度都还好，就是觉得模型体积有点大。 另外如果修改输入分辨率，如192->224或者256，是不是stdc和mbv3这些基础backbone都需要重新训练？
> > 使用其他尺寸，应该也可以直接使用我们发布的权重进行再次微调。
> 
> > > 重新
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/12178974/189788722-51e74b1c-4213-4da1-83d2-5fa7f08318bd.png) 这边导出的liteV2-lite模型有12M
> > 
> > * 导出方式
> > 
> > ```shell
> > 1、python ../../export.py --config configs/human_pp_humansegv2_lite_ZF.yml --model_path output/humansegv2_lite_ZF_Finetune/iter_30000/model.pdparams --save_dir output/humansegv2_lite_ZF_Finetune_Deploy/30000/ --without_argmax --with_softmax
> > 2、paddle2onnx --model_dir output/humansegv2_lite_ZF_Finetune_Deploy/30000/ --model_filename model.pdmodel --params_filename model.pdiparams  --opset_version 11   --save_file output/humansegv2_lite_ZF_Finetune_Deploy/30000/output.onnx --input_shape_dict="{'x': [1,3,192,192]}"
> > ```
> 
> 这个通用模型，我们暂时没有进行轻量化处理，后续会考虑加上

好的， 多谢解答。
