### ISSUE TITLE
 DomainAdaptation-PixMatch /Running on custom datasets? 

### ISSUE THREAD

**Issue by george-kalitsios** [PaddlePaddle/PaddleSeg#2534]
Hello! I was wondering how I could run the model on a custom dataset? Thanks!

**Comment by juncaipeng** [comment]
The tutorial shows the training on cityscapes dataset. If you want to train the model on other dataset, you need to read and modify the code by yourself.

**Comment by george-kalitsios** [comment]
I've already used this paddleseg repository on my custom dataset for semantic segmentation tasks, but not for DA; is it better to try changing the gta5,synthia loaders here?
or to modify the code in the main paddleseg repository, where I already work?

**Comment by juncaipeng** [comment]
You only need to change the code under DomainAdaptation for using DA on your custom dataset.
