### ISSUE TITLE
[General Issue]

### ISSUE THREAD

**Issue by Zhengliang-Zhang** [PaddlePaddle/PaddleSeg#2535]
请问医疗肝脏标注场景传播模型得出的结果非常不理想可能是由什么原因导致的呢？能否提供一下演示中的视频方便测试？

https://user-images.githubusercontent.com/112454215/189889155-2fe6ef4c-f0de-41c0-b4a7-20d6dd7437d3.mp4

**Comment by wuyefeilin** [comment]
你的视频前后变动较大，需要增加交互信息提升效果
