### ISSUE TITLE
(InvalidArgument) fill_constant(): argument (position 6) must be float, but got str[Bug]

### ISSUE THREAD

**Issue by LeeLear** [PaddlePaddle/PaddleSeg#2538]
加载 configs/human_pp_humansegv2_mobile.yml       使用下载的预训练模型，报上述的错
---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 完整的代码：(若修改过原代码，请提供修改前后代码对比）
 7. 详细的错误信息、相关log：（若使用多卡，log默认保存在log/worklog.0）
 8. 运行指令或复现步骤：
 9. 其他内容: （增加其他与问题相关的内容）

**Comment by Bobholamovic** [comment]
请提供PaddleSeg版本、PaddlePaddle版本、复现步骤等信息，以帮助我们排查问题。
