### ISSUE TITLE
进行下一张图像标注时候 会出现“是否完成最后一个目标的标注，不完成不会进行保存”弹窗

### ISSUE THREAD

**Issue by Linranran** [PaddlePaddle/PaddleSeg#2544]
进行下一张图像标注时候 会出现“是否完成最后一个目标的标注，不完成不会进行保存”弹窗
这个操作的目的是什么？  是防呆模式吗？
https://github.com/PaddlePaddle/PaddleSeg/blob/c608005d4de4a10ae9ec9be76c53951cf658f758/EISeg/eiseg/app.py#L1658-L1662

可以通过直接设置res == QMessageBox.Yes  跳过该操作

**Comment by haoyuying** [comment]
用于提醒用户保存，可以在文件-自动保存中选择默认自动保存的位置，就不回出现该弹框了。__

**Comment by Linranran** [comment]
@haoyuying 不是你说的这样。 设置标签保存位置，同时设置自动保存。点击下一张，还是会出现“是否完成最后一个目标的标注”的弹窗。
