### ISSUE TITLE
How to set image resolution for training and inference?

### ISSUE THREAD

**Issue by sarmientoj24** [PaddlePaddle/PaddleSeg#2551]
I cannot see it from the parameters.

Also, how to set which transforms to use?

**Comment by haoyuying** [comment]
For training, you can change the crop size,for example:https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/configs/_base_/cityscapes_1024x1024.yml#L10
For inference, we take the original image without crop to predict the result.

**Comment by sarmientoj24** [comment]
that seems like random padding crop.

does that mean that the image should be in the expected size already? or is there a validation transforms in the yaml?
