### ISSUE TITLE
paddleseg模型部署支持serving的pipeline吗，只看到serving 的c++部署范例

### ISSUE THREAD

**Issue by CocoSkyler** [PaddlePaddle/PaddleSeg#2556]
Welcome to propose a new feature! To help us understand your great feature, please provide following information:
1. A clear and concise description of the proposed feature.
2. Tell us why the feature is useful. 
3. If possible, please show related codes .

---

欢迎提出一个新功能需求，为了帮助我们更好理解您的需求，辛苦提供下面信息：
1. 清晰简洁的语言提出新功能需求。
2. 请描述这个需求的必要性。
3. 如果可以，辛苦您提供相关代码实现效果。

**Comment by juncaipeng** [comment]
导出paddleseg的预测模型后，就可以全部参考paddle serving的文档进行部署了。
