### ISSUE TITLE
export问题

### ISSUE THREAD

**Issue by superran1** [PaddlePaddle/PaddleSeg#2559]
使用命令：python export.py --config "/home/PaddleSeg/c3_segslider/ppseg_cfg_segformer_b0.yml" --model_path "/home/PaddleSeg/c3_segslider/model.pdparams" --save_dir /home/PaddleSeg/c3_segslider/ --input_shape 1 3 800 64 
 导出模型权重文件使用trt推理时，报错
[09/21/22 13:33:18 +08:00] [warning] [thread 30780] [AIBase-v4.8.1.2 ] paddle enable trt

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The input [reshape2_10.tmp_0] shape of trt subgraph is [-1,-1,32], please enable trt dynamic_shape mode by SetTRTDynamicShapeInfo. (at ..\paddle/fluid/inference/tensorrt/engine.h:116)

[09/21/22 13:33:22 +08:00] [error] [thread 30780] [AIBase-v4.8.1.2 ] initNet try to init failed: Z:\Member_dir\ransi\model\haoji\C3SegSlider\model.pdmodel

模型结构图中有很多问号（输入的尺寸为动态的意思？在模型最刚开始的时候已经定义输入[800 64]），这个如何将模型由动态转换为静态模型呢
![image](https://user-images.githubusercontent.com/53592722/191424644-6668fb70-d49d-4640-8a44-ed8b99e3ba36.png)

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本： PaddleSeg release/2.6
 2. PaddlePaddle版本：paddlepaddle 2.3.1
 3. 操作系统信息：Linux
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：CUDA10.2/cuDNN 7.6.5
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by wuyefeilin** [comment]
`--enable_auto_tune True ` 增加这个配置试试

**Comment by superran1** [comment]
这个是部署到C++上面的，目前只支持静态模型，直接将模型转换为静态结构应该怎么做呢

**Comment by superran1** [comment]
![image](https://user-images.githubusercontent.com/53592722/191436686-fba5a8c3-f241-456a-98f1-ee39be48ff8e.png)
我更换了unet情况是一样的，模型其余部分都能正常显示shape,只有当进行bilinear_interp时会出现-1的问题，这个能帮忙看一下吗
链接：https://pan.baidu.com/s/1dkVF6yM9PA1op_cVCL4s6g 
提取码：zf73 
--来自百度网盘超级会员V4的分享

**Comment by juncaipeng** [comment]
应该是不支持使用固定shape，只能是动态shape。  c++部署，动态shape使用方法：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/docs/deployment/inference/cpp_inference_cn.md#53-trt%E6%96%B9%E5%BC%8F-%E5%8A%A8%E6%80%81shape%E6%A8%A1%E5%BC%8F-%E9%83%A8%E7%BD%B2
