### ISSUE TITLE
[General Issue] How to train using custom dataset?

### ISSUE THREAD

**Issue by sarmientoj24** [PaddlePaddle/PaddleSeg#2560]
The README does not contain any instructions how to do this on custom data.

For example, how do I change these:
```
train_dataset:
  type: OpticDiscSeg
  dataset_root: 
```

**Comment by wuyefeilin** [comment]
参考文档进行自定义数据集的准备https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/docs/data/marker/marker_cn.md

**Comment by sarmientoj24** [comment]
i've already done that, but how do you add it there?

**Comment by wuyefeilin** [comment]
Use the Dataset class, https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/paddleseg/datasets/dataset.py
like:
train_dataset:
  type: Dataset
  dataset_root: xxx
