### ISSUE TITLE
[General Issue] MobleSeg存在部分疑问

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/PaddleSeg#2568]
MobleSeg，在训练过程中，出现的效果异常不对，训练了60000轮，要分割的类别miou结果似乎还是0
![微信图片_20220923103232](https://user-images.githubusercontent.com/58769772/191882170-90274cd6-261d-4b0f-9ed1-561ce3f4ecc4.png)
过程忘记保存了但是，9月22的结果似乎是8月1号这个结果差不多，能否问一下是什么原因?

**Comment by shiyutang** [comment]
请问你能否在cityscapes上获得我们公布的结果？ 另外你使用的数据是否存在严重不均衡问题，如果是，需要在损失增大对应类别的系数进行均衡，并进行一些相应的数据扩充方法。

**Comment by chen-del** [comment]
恩是的，背景像素偏多，要分割的类别像素点少，cityscapes没有试过，只是试过voc数据集，效果确实可以持平的，但是使用自己的数据集我碰到了这个问题。

**Comment by chen-del** [comment]
因为有些网络可以，有些网络不可以，比如这个mobliteset

**Comment by chen-del** [comment]
是类似于这种方式去调整嘛
SOLVER:
    LR: 0.0001
    LR_POLICY: "poly"
    OPTIMIZER: "sgd"
    NUM_EPOCHS: 20
    CROSS_ENTROPY_WEIGHT: [1.0, 1.500,2.00]

**Comment by shiyutang** [comment]
嗯嗯，传入和num-classes长度一致的weight即可，如下列函数中的描述：
![image](https://user-images.githubusercontent.com/34859558/191907918-a299e85d-0cbd-465f-9641-19f36d2c8796.png)

另外你的配置文件似乎是paddleseg较低版本，可以升级到最新版本并作权重调整

**Comment by chen-del** [comment]
@shiyutang 使用了loss去增加不同全中通但是感觉依旧没有效果，我的版本应该是最新的了，是用的2.6的
情况如下：
![微信图片_20220923154010](https://user-images.githubusercontent.com/58769772/191913006-e2de4434-4892-4f31-a41c-85d28b0f470e.png)

![微信图片_20220923154017](https://user-images.githubusercontent.com/58769772/191913001-35aaa62d-94c2-41c3-ac1a-0e84a6bfa1cb.png)

**Comment by shiyutang** [comment]
损失的权重可以设置为像素比例的反比，第二和第三类应当显著高于第一类

**Comment by chen-del** [comment]
@shiyutang ，谢谢！

**Comment by chen-del** [comment]
但是如果这样那么我需要一些背景类数据的特征，那么如果一直提高其他类别会不会造成误分割等其他问题，这又是个问题

**Comment by shiyutang** [comment]
目前来看后两类类别的数据基本完全没有经过网络进行有效学习，建议先提升后两类权重训练，并对后两类数据进行数据扩张，误分割问题可以先等到后两类有一定学习效果之后再进行具体案例具体分析

**Comment by chen-del** [comment]
@shiyutang 好像是过了一段时间了，我差点把这个忘了，显著提高另外两个类别权重，现在这个的miou效果基本达到了70以上，但是误检背景严重，有没有什么建议

**Comment by shiyutang** [comment]
建议增加后面两类的数据，看上去你的网络还是不能很好地对后两类学习
