### ISSUE TITLE
[General Issue] PP-HumanSeg release2.5版本代码和文档不匹配

### ISSUE THREAD

**Issue by XYZ-916** [PaddlePaddle/PaddleSeg#2572]
release2.5版本代码和https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/contrib/PP-HumanSeg/README_cn.md文档不匹配

**Comment by juncaipeng** [comment]
请问有哪里的问题啊？  建议直接使用2.6最新分支。
