### ISSUE TITLE
我想请教一下，现在的EIseg 生成的json文件 是labelme格式的吗

### ISSUE THREAD

**Issue by lijoe123** [PaddlePaddle/PaddleSeg#2575]
您好，我想请教一下，现在的EIseg 生成的json文件 是labelme格式的吗？我看您之前的回答都说准备实现保存labelme 格式的json，不知道现在有没有实现呢？
谢谢

**Comment by haoyuying** [comment]
目前的json还不是labelme的格式，我们会在下一次版本迭代中修改json的格式，敬请关注。

**Comment by lijoe123** [comment]
> 目前的json还不是labelme的格式，我们会在下一次版本迭代中修改json的格式，敬请关注。

谢谢您的回答！我十分期待下个版本，请问有群可以加吗，因为公众号的二维码过期了加不了。

**Comment by haoyuying** [comment]
![image](https://user-images.githubusercontent.com/35907364/192447003-aa2ae034-55cd-4160-a113-1f34bab6b586.png)

**Comment by Linranran** [comment]
@lijoe123 mscoco格式

**Comment by fyj1** [comment]
> 目前的json还不是labelme的格式，我们会在下一次版本迭代中修改json的格式，敬请关注。

想问问最新版本中的json格式和labelme一致了吗
