### ISSUE TITLE
[General Issue]使用paddleslim裁剪后的模型在推理时出现报错

### ISSUE THREAD

**Issue by Tangyuny** [PaddlePaddle/PaddleSeg#2577]
使用未裁剪的模型进行c++部署推理正常，使用裁剪后的模型出现如下报错：
![image](https://user-images.githubusercontent.com/37798338/192447259-aba669fa-23c2-4946-8d01-6792712a2669.png)
请问是什么原因。

版本信息如下：
1. PaddleSeg版本：PaddleSeg 2.5.0
 2. PaddlePaddle版本：PaddlePaddle 2.3.1
 3. PaddleSlim版本：PaddleSlim 2.3.1
 4. 操作系统信息：Linux
 5. CUDA/cuDNN版本：CUDA10.2/cuDNN 8.0.2
 6. TensorRT版本：TensorRT 7.1.3.4

**Comment by juncaipeng** [comment]
是哪个模型啊？可以提供复现的步骤吗？

**Comment by Tangyuny** [comment]
模型：FCN
backbone：HRNet_W48
Config文件：模型训练时的Config文件是用的我自己保存的，具体如图(不清楚是否有影响)：
![image](https://user-images.githubusercontent.com/37798338/192668141-c517d172-fcdf-43ca-b42a-5a0651b2267f.png)
训练、导出、推理部署和裁剪相关命令和流程均与官方提供的一致，未裁剪的模型推理过程及输出结果都正常，仅多了裁剪这一项。

**Comment by Tangyuny** [comment]
@juncaipeng 请问有眉目了吗，或者能否提供一些建议，谢谢
