### ISSUE TITLE
[General Issue]使用Camvid数据集训练stdc分割模型时，报错！

### ISSUE THREAD

**Issue by huangwan-jiayi** [PaddlePaddle/PaddleSeg#2578]
欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（PaddleSeg release/2.5）
 2. PaddlePaddle版本：（PaddlePaddle 2.3.0）
 3. 操作系统信息：（Linux）
 4. Python版本号：（如Python3.7）
 5. CUDA/cuDNN版本：（ CUDA10.2/cuDNN 7.6.5等）
环境：
![image](https://user-images.githubusercontent.com/71338215/192556331-d7321e60-f795-41e2-bdcd-a32f04d1fffa.png)
问题详细描述：
想使用stdc分割模型训练Camvid数据集，在网上下载好Camvid数据集后，数据集原图和label的分辨率都为（720*960）
label有两个版本，
一种是彩色的：
![image](https://user-images.githubusercontent.com/71338215/192557049-d855ef3b-3781-4b86-b67d-8fb4b44bd455.png)
一种是黑白的：
![image](https://user-images.githubusercontent.com/71338215/192557167-52fb2df2-f8a4-479b-a780-147207bf7f32.png)
配置好数据集路径后，按照数据集的说明是有11种种类，所以将numclass配置为11，但是运行后报错（无论是彩色label还是黑白label都是如此）：
![image](https://user-images.githubusercontent.com/71338215/192557512-3067e464-339c-48c2-a2fe-297d306c011a.png)
将numclasses设置为1 ，可以正常训练。不知道哪里出现了问题，迫切请求指导，谢谢了。

**Comment by shiyutang** [comment]
label的shape存在问题，需要将 label 的维度1 squeeze变为（12，720， 960），例如在下图core/train.py所在位置，维度应当如图所示：
<img width="639" alt="image" src="https://user-images.githubusercontent.com/34859558/192682096-b5810654-f1aa-4489-8e24-9f2f54f60674.png">

**Comment by huangwan-jiayi** [comment]
> label的shape存在问题，需要将 label 的维度1 squeeze变为（12，720， 960），例如在下图core/train.py所在位置，维度应当如图所示： <img alt="image" width="639" src="https://user-images.githubusercontent.com/34859558/192682096-b5810654-f1aa-4489-8e24-9f2f54f60674.png">





> label的shape存在问题，需要将 label 的维度1 squeeze变为（12，720， 960），例如在下图core/train.py所在位置，维度应当如图所示： <img alt="image" width="639" src="https://user-images.githubusercontent.com/34859558/192682096-b5810654-f1aa-4489-8e24-9f2f54f60674.png">



![Uploading ad8e2e132aacfb2e4604d24c5ea2a02.png…]()
这是我的label和输入原图的shape， 那么我该怎么去改变我数据集中的label的shape呢？

**Comment by huangwan-jiayi** [comment]
> 
![ad8e2e132aacfb2e4604d24c5ea2a02](https://user-images.githubusercontent.com/71338215/192692510-27cff989-42da-43bc-8b55-a26010e71748.png)

这是我的label和输入原图的shape，感觉没有问题。如果要修改的话， 那么我该怎么去改变我数据集中的label的shape呢？

**Comment by shiyutang** [comment]
请将一开始的错误截图完整截取，方便定位错误具体位置

**Comment by huangwan-jiayi** [comment]
> 请将一开始的错误截图完整截取，方便定位错误具体位置

报错完整截图：
![image](https://user-images.githubusercontent.com/71338215/192709967-d61e5381-c4ea-49d3-8b51-00112b28ad03.png)

**Comment by shiyutang** [comment]
根据错误提示，是输入损失时，logit和label的形状应该是NHWC，但这里的是NCHW，因此需要寻找是否修改了代码导致形状的改变，如果找不到相关修改，建议自行进行transpose改变输入损失的label 和logit的形状。
