### ISSUE TITLE
请问如果要重新训练pphumanv2，有没有相应的数据集？

### ISSUE THREAD

**Issue by zeckireck** [PaddlePaddle/PaddleSeg#2579]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by shiyutang** [comment]
可以参考pphumansegv2文档：https://github.com/PaddlePaddle/PaddleSeg/blob/release%2F2.6/contrib/PP-HumanSeg/README_cn.md#42-%E5%87%86%E5%A4%87%E6%A8%A1%E5%9E%8B%E5%92%8C%E6%95%B0%E6%8D%AE

**Comment by zeckireck** [comment]
请问，mini_supervisely中的annotation是怎么生成的？有相应的工具吗

**Comment by shiyutang** [comment]
可以使用EISeg进行标注，详情可见：https://github.com/PaddlePaddle/PaddleSeg/blob/release%2F2.6/EISeg/README.md
