### ISSUE TITLE
 模型深度增加

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/PaddleSeg#2582]
pphumanseg_lite模型深度增加，是否意味着提取的特征越好，分割的精度越准确？
我对这个方面有点疑惑
例如像如下增加卷积深度：
 
        self.block3 = nn.Sequential(
            InvertedResidual(
                144, stride=2),
            InvertedResidual(
                288, stride=1),
            InvertedResidual(
                288, stride=1),
            InvertedResidual(
                288, stride=1),
            InvertedResidual(
                288, stride=1),
            InvertedResidual(
                288, stride=1),
            InvertedResidual(
                288, stride=1),
            InvertedResidual(
                288, stride=1))

**Comment by shiyutang** [comment]
模型深度也可能导致网络过拟合、网络退化等问题，对于效果的影响不能一概而论。
