### ISSUE TITLE
多卡训练报错

### ISSUE THREAD

**Issue by m828** [PaddlePaddle/PaddleSeg#2584]
1. PaddleSeg版本：PaddleSeg 2.5/2.6
 2. PaddlePaddle版本：PaddlePaddle 2.2.3
 3. 操作系统信息：Linux
 4. Python版本号：Python3.8
 5. CUDA/cuDNN版本：CUDA11.2/cuDNN 8.2
 

按照多卡训练的流程：
export CUDA_VISIBLE_DEVICES=0,1,2,3 # 设置4张可用的卡
python -m paddle.distributed.launch train.py 
出现下面的情况，是什么原因呢？
![55b17725a03c3eec5bec24d58924cc9](https://user-images.githubusercontent.com/45037914/192932071-c8a34d18-0ba2-4cbe-b99e-269f75834d8f.jpg)

**Comment by Bobholamovic** [comment]
你好，看起来是缺少算子的问题，建议升级paddle版本到2.3.2再次尝试~

**Comment by m828** [comment]
> 你好，看起来是缺少算子的问题，建议升级paddle版本到2.3.2再次尝试~

不好意思打错了，是2.3.2，最新的

**Comment by m828** [comment]
![image](https://user-images.githubusercontent.com/45037914/193018796-5de8fdd9-e1d9-4998-8455-c60b5cc67e14.png)

**Comment by Bobholamovic** [comment]
我这边无法复现这个问题~ 看起来应该这个应该是和Paddle库相关的问题，建议移步[PaddlePaddle仓库](https://github.com/PaddlePaddle/Paddle/issues)提问。

**Comment by m828** [comment]
> Paddle库相

好的，谢谢~
