### ISSUE TITLE
pphumansegv2 resize算子

### ISSUE THREAD

**Issue by zeckireck** [PaddlePaddle/PaddleSeg#2589]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）
![image](https://user-images.githubusercontent.com/81000191/194080559-f0549fe4-b9c2-4bc0-9b7f-f708193d20d7.png)

pphumansegv2怎么把所有resize算子中的coordinate_transformation_mode改成 align_corners？我尝试在代码里修改，只有部分resize算子变成了align_corners，然后有部分任然是half_pixel.

**Comment by juncaipeng** [comment]
是将所有的resize op都改了吗？    你这个截图是onnx的显示吧，也不排除paddle2onnx转为onnx模型后出现不对应的问题。

**Comment by zeckireck** [comment]
对，我把F.interpolate中的align_corners都改成了True

**Comment by zeckireck** [comment]
[human_pp_humansegv2_lite.zip](https://github.com/PaddlePaddle/PaddleSeg/files/9738817/human_pp_humansegv2_lite.zip)

**Comment by jiangjiajun** [comment]
https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/paddle2onnx/mapper/nn/interpolate.cc#L66 参照这里的转换逻辑
