### ISSUE TITLE
[Bug] AutoNUE code not working 

### ISSUE THREAD

**Issue by tanbaswal** [PaddlePaddle/PaddleSeg#2591]
Thanks for your bug report. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: PaddleSeg release/2.6
 2. PaddlePaddle version: PaddlePaddle 2.3.2.post116
 3. Operation system: Linux
 4. Python version: Python3.8
 5. CUDA/cuDNN version: CUDA11.6
 6. Full codes:  As mentioned in the Readme of the AutoNUE@CVPR 2021 Challenge, I was doing the **baseline training of the model** according to the instructions. The code is not working for the **auto_nue.py** file. The __getitem__ function of the file is throwing an error when the images and the labels are fed into the transform. The file is using transform from **PaddleSeg/paddleseg/transforms/transforms.py**. After looking at the code of transforms.py, **it expects the input to be in form of **dictionary**** 
![Screenshot 2022-10-08 203327](https://user-images.githubusercontent.com/68341571/194714040-278c180b-f69e-4a47-ae3d-93454924bdf6.png)
So, i tried to change the __getitem__ function of the auto_nue.py with this code: 
![Screenshot 2022-10-08 203524](https://user-images.githubusercontent.com/68341571/194714115-36dab109-beb2-48ff-9068-e75e90692517.png)
The code works but I got very bad results on training the model. The model was not training on some classes of **IDD_Segmentation dataset**
 7. Detailed error information, releated running log:  The error is showing that **TypeError: __call__() got an unexpected keyword argument 'im'** 
![Screenshot 2022-10-08 202443](https://user-images.githubusercontent.com/68341571/194713704-d8e6b2f7-4323-4659-bc8e-1993791142b1.png)

 8. Running command or reproduce details：CUDA_VISIBLE_DEVICES=0 python train.py --config configs/sscale_auto_nue_map+city@1920.yml --use_vdl --save_dir saved_model/sscale_auto_nue_map+city@1920 --save_interval 2000 --num_workers 12 --do_eval

 9. Additional context: (Add any other context about the problem): Please fix the original code, as I think the modified code is not accurate for training.

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 完整的代码：(若修改过原代码，请提供修改前后代码对比）
 7. 详细的错误信息、相关log：（若使用多卡，log默认保存在log/worklog.0）
 8. 运行指令或复现步骤：
 9. 其他内容: （增加其他与问题相关的内容）

**Comment by tanbaswal** [comment]
Any update?

**Comment by wuyefeilin** [comment]
You may use the PaddleSeg release/2.5 first. We will update the AutoNUE  dataset reader soon.
