### ISSUE TITLE
[Feature Request] [EISeg] Semantic and instance segmentation

### ISSUE THREAD

**Issue by ferraridamiano** [PaddlePaddle/PaddleSeg#2593]
With EISeg it seems that given an image we can select just one label for each image. In fact if I click one label and one object and then a second label and a second object, the first object will be converted to the second label. Which is not the expected behaviour. Maybe I'm doing it wrong. I would suggest to improve this in order to have multiple object (classes) in the same image

**Comment by juncaipeng** [comment]
@haoyuying

**Comment by haoyuying** [comment]
You need to  press the space key to certain one object and then annotate the another one.
