### ISSUE TITLE
[General Issue] EISeg 医疗标注

### ISSUE THREAD

**Issue by Zhengliang-Zhang** [PaddlePaddle/PaddleSeg#2598]
1. PaddleSeg版本：PaddleSeg release/2.3
 2. PaddlePaddle版本：PaddlePaddle 2.1.
 3. 操作系统信息：Windows
 4. Python版本号：Python3.8
 5. CUDA/cuDNN版本：CUDA10.2/cuDNN 7.6.5

肝脏图像标注和传播不理想
![image](https://user-images.githubusercontent.com/112454215/194990174-fdd1b570-0ffe-475a-a83e-3fe65385ed95.png)

https://user-images.githubusercontent.com/112454215/194990481-29c340c8-cef9-4cd0-8296-0e6c18d31790.mp4

**Comment by haoyuying** [comment]
多点几个点试一下或者将标注模型换成通用场景模型，多点几个点
