### ISSUE TITLE
[General Issue]我在打开EISeg软件时出现问题

### ISSUE THREAD

**Issue by moonnnpie** [PaddlePaddle/PaddleSeg#2600]
欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：PaddleSeg release/2.6
 2. PaddlePaddle版本：PaddlePaddle 2.3
 3. 操作系统信息：Linux
 4. Python版本号：Python3.8
 5. CUDA/cuDNN版本：CUDA10.2
 6. 其他内容: （增加其他与问题相关的内容）

具体报错如下
qt.qpa.xcb: could not connect to display localhost:10.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1665477618 (unix time) try "date -d @1665477618" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3fe0029d0bd) received by PID 2740413 (TID 0x7fdb37245340) from PID 2740413 ***]

**Comment by moonnnpie** [comment]
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1665473480 (unix time) try "date -d @1665473480" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3fe00293121) received by PID 2699553 (TID 0x7f52a9e8f340) from PID 2699553 ***]

Aborted (core dumped)

**Comment by moonnnpie** [comment]
已解决，是远程服务器问题

**Comment by NingYuanxiang** [comment]
请问如何在远程部署的，我也是出现该问题？

**Comment by freemanhm** [comment]
您好，请问是怎么解决该问题的，我也在启动EISeg出现该同样问题

**Comment by moonnnpie** [comment]
我最后是在本地使用的，在本地用同样的配置就没有出现问题
