### ISSUE TITLE
mobileseg可否给出每个网络模型具体的实现细节?

### ISSUE THREAD

**Issue by IamMegatron2025** [PaddlePaddle/PaddleSeg#2601]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/configs/mobileseg  _可以看到这几个轻量级网络的backbone是mobilenetv2/v3或者shufflenet，但是他们整个网络的实线细节是怎么做的呢？能不能给个展示图或者相关paper作为参考？ 不然不知道是否用了多阶段/空洞卷积/crf等操作。

**Comment by juncaipeng** [comment]
这个暂时没有计划，你可以具体看看代码，其实比较简单。

**Comment by shiyutang** [comment]
可以参考：
![image](https://user-images.githubusercontent.com/34859558/196581071-6cce0aab-a558-4945-98d4-b89f35a9c58a.png)
