### ISSUE TITLE
找不到新发版的模型

### ISSUE THREAD

**Issue by peiwenYe** [PaddlePaddle/PaddleSeg#2602]
请问release/2.6新发版的GCA模型的配置文件和预训练模型在哪里找？
![image](https://user-images.githubusercontent.com/37332773/195038612-0370d9e9-123d-4be7-809a-2e5ae68ee161.png)

**Comment by wuyefeilin** [comment]
目前GCA模型的网络结构已经放置到ppmatting/models下面, 相应的配置文件正在整理当中哈

**Comment by peiwenYe** [comment]
> 目前GCA模型的网络结构已经放置到ppmatting/models下面, 相应的配置文件正在整理当中哈

收到

**Comment by buguaigiser** [comment]
请问GCA模型的配置文件现在整理好了吗？
