### ISSUE TITLE
grid_sample

### ISSUE THREAD

**Issue by m828** [PaddlePaddle/PaddleSeg#2604]
请问grid_sample在部署使用tensorrt加速的时候不支持吗？
![2f9570c3a469e782c75d596520dd41e](https://user-images.githubusercontent.com/45037914/195270073-26308ce3-3820-4cd0-8b88-7032c3daa4d4.jpg)

**Comment by m828** [comment]
def flow_warp(self, input, flow, size):
        input_shape = paddle.shape(input)
        norm = size[::-1].reshape([1, 1, 1, -1])
        norm.stop_gradient = True
        h_grid = paddle.linspace(-1.0, 1.0, size[0]).reshape([-1, 1])
        h_grid = h_grid.tile([size[1]])
        w_grid = paddle.linspace(-1.0, 1.0, size[1]).reshape([-1, 1])
        w_grid = w_grid.tile([size[0]]).transpose([1, 0])
        grid = paddle.concat([w_grid.unsqueeze(2), h_grid.unsqueeze(2)], axis=2)
        grid.unsqueeze(0).tile([input_shape[0], 1, 1, 1])
        grid = grid + paddle.transpose(flow, (0, 2, 3, 1)) / norm

        output = F.grid_sample(input, grid)
        return output

**Comment by wuyefeilin** [comment]
<img width="223" alt="image" src="https://user-images.githubusercontent.com/30919197/195330425-d2ab5fae-f11d-4c1b-8579-2f57372deaeb.png">
按照提示使用这个哈

**Comment by m828** [comment]
> <img alt="image" width="223" src="https://user-images.githubusercontent.com/30919197/195330425-d2ab5fae-f11d-4c1b-8579-2f57372deaeb.png">
> 
> 按照提示使用这个哈

使用了，不行，不是linspace、grid_sample的问题吗

**Comment by wuyefeilin** [comment]
报错信息给一下

**Comment by m828** [comment]
![image](https://user-images.githubusercontent.com/45037914/195337011-2efb39a0-da1f-4f40-980a-363f63da5995.png)

![image](https://user-images.githubusercontent.com/45037914/195336862-45dc1c92-cac6-480c-b360-8205638a29fd.png)

**Comment by m828** [comment]
> 报错信息给一下

把flow_warp这块代码换成普通卷积就可以推理出来，但是这块比较重要==、

**Comment by liumk1998** [comment]
tensorrt8.5应该会支持，但是不知道会不会和onnx一样只支持4d的，要先用的话可以模仿raft或者cre的写法，其实就是抄了mmcv的gridsample，会稍微慢一丢丢

**Comment by liumk1998** [comment]
[https://github.com/ibaiGorordo/CREStereo-Pytorch/blob/main/nets/utils/utils.py](url)maybe you can write grid_sampler like this

**Comment by m828** [comment]
> [https://github.com/ibaiGorordo/CREStereo-Pytorch/blob/main/nets/utils/utils.py](url)maybe you can write grid_sampler like this

很奇怪，我尝试换成这个，能够部署在Windows下，在Linux下跑的模型不能够用tensorrt加速推理，将其权重搬到Windows下，可以推理成功，但是Windows不支持benchmark，不能够计算fps(两边都是2.3.2.post112，tensorrt为8.2.5)

**Comment by liumk1998** [comment]
> > [https://github.com/ibaiGorordo/CREStereo-Pytorch/blob/main/nets/utils/utils.py](url)maybe you can write grid_sampler like this
> 
> 很奇怪，我尝试换成这个，能够部署在Windows下，在Linux下跑的模型不能够用tensorrt加速推理，将其权重搬到Windows下，可以推理成功，但是Windows不支持benchmark，不能够计算fps(两边都是2.3.2.post112，tensorrt为8.2.5)

呃呃，应该不至于会有系统区别吧，我改的可以放jetson开发板上跑

**Comment by liumk1998** [comment]
娘希匹，nvidia说2022q3支持grid_sample，我等不及自己找到接口实现了下，效果一样，快一丢丢。你可以照我[这个](https://blog.csdn.net/weixin_42492254/article/details/127324189 )试试，python的话应该就多一句ctypes.CDLL(plugin_lib)来加载接口

**Comment by m828** [comment]
> 娘希匹

好的，我看看，感谢
