### ISSUE TITLE
两类别分割任务重NUM_CLASSES怎么设置？

### ISSUE THREAD

**Issue by IamMegatron2025** [PaddlePaddle/PaddleSeg#2605]
您好，cityscapes是19个类的分割，所以paddleseg/datasets/cityscapes.py的NUM_CLASSES = 19。
我目前的分割任务是要解决两个类别的分割，label map我做成了0,1值和255值(255是忽略值)的灰度图，但是NUM_CLASSES应该设置几呢？ 按cityscapes的意思 这里应该设置2，但是明显不对呀，因为我的图片还有背景类不需要分割出来，该怎么改呢？
求解答。

**Comment by wuyefeilin** [comment]
可以将背景类单独作为一类，比如2。 然后NUM_CLASSES 设置为3

**Comment by IamMegatron2025** [comment]
@wuyefeilin 感谢及时回复。 
1.如果【将背景类单独作为一类，比如2。 然后NUM_CLASSES 设置为3】，那么label map我需要重新做成了0,1,2值吗？（把之前的255改成3），还是不需要重新做0,1,2值的label map，只需要把paddleseg/datasets/cityscapes.py的NUM_CLASSES改成3？从理论上分析，好像把之前label map的255改成3会让模型学习的更好？
2.我如果做两类别分割任务（这两类不是cityscapes中的任何一类），label map我做成了0,1,2值，那么模型最后predict值也是0,1,2。那我用mobilseg的pretrained作为训练的pretrained model是不是不合适？，因为mobilseg的pretrain预测的0,1,2类是cityscapes的0,1,2类？所以我直接用imagenet pretrained作为mobilseg backone的pretrained是不是会更好？ 你这里还有别的更好的方法吗？
求advises。

**Comment by wuyefeilin** [comment]
你得重新处理ground truth， 将背景作为一个类别。然后用mobileseg作为预训练或直接用backbone的预训练都可以。你可以做一下实验进行对比

**Comment by IamMegatron2025** [comment]
@wuyefeilin 感谢回复。多谢~
