### ISSUE TITLE
单卡训练如何调整训练参数

### ISSUE THREAD

**Issue by xiaodaomingye459** [PaddlePaddle/PaddleSeg#2607]
![image](https://user-images.githubusercontent.com/83204995/195361901-f4a4ad6b-40fb-43e4-b7d9-9f29eb24a0e3.png)
请问，如果我使用单卡训练，需要更改这里面的哪些参数，以及如何更改？

**Comment by Bobholamovic** [comment]
你好！PaddleSeg默认使用4张显卡进行训练，根据学习率调整的[Linear Scaling Rule](https://arxiv.org/pdf/1706.02677.pdf)，如果使用单卡训练、保持每张卡上的batch size不变，需要将学习率缩减4倍，即将`learning_rate`参数设置为`0.00125`。

**Comment by xiaodaomingye459** [comment]
训练的iters需要增加吗？

**Comment by xiaodaomingye459** [comment]
以及损失里面的 min_kept似乎也与总bz有关，需要修改吗

**Comment by Bobholamovic** [comment]
抱歉，是我的疏忽，**在batch size不变的情况下**，iters应该乘以4，而min_kept无需修改（只和每张卡的batch size有关）。
