### ISSUE TITLE
日志无法正常显示

### ISSUE THREAD

**Issue by xiaodaomingye459** [PaddlePaddle/PaddleSeg#2608]
![image](https://user-images.githubusercontent.com/83204995/195475061-55b566ab-036f-407b-b7a3-825f492d0ae8.png)
日志显示时一团乱码 请问如何正常显示?

**Comment by Bobholamovic** [comment]
你好，文本编辑器提示"The file was loaded in a wrong encoding: 'UTF-8'"，建议可以尝试点击右边的"Reload in another encoding"并选择GBK编码。
![image](https://user-images.githubusercontent.com/21275753/195484053-a1c54cd6-b148-4450-96bc-d05dd52a8e07.png)
