### ISSUE TITLE
[Bug]./build/test_seg: error while loading shared libraries: libdnnl.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by persuelx** [PaddlePaddle/PaddleSeg#2609]
Thanks for your bug report. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Full codes: (if you modify any original code，please show the comparison of the codes before and after)
 7. Detailed error information, releated running log: (if using multi-gpus，the log is saved to log/worklog.0 by default)
 8. Running command or reproduce details：
 9. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 完整的代码：(若修改过原代码，请提供修改前后代码对比）
 7. 详细的错误信息、相关log：（若使用多卡，log默认保存在log/worklog.0）
 8. 运行指令或复现步骤：
 9. 其他内容: （增加其他与问题相关的内容）

**Comment by Bobholamovic** [comment]
你好！这一错误是libdnnl库未正确安装导致的。请确认在您的机器上：
（1）已经安装了libdnnl库；
（2）正确设置了环境变量以使libdnnl库能够被找到（一个简单的办法是将.so运行时库文件放置在与编译的可执行程序同样的目录中）且您具有足够的权限使用它。
关于libdnnl库的安装与配置可参考：https://blog.csdn.net/qq_45779334/article/details/123164180

**Comment by persuelx** [comment]
@Bobholamovic  这个库还需要自己安装吗？ 看代码结构的话，它的推理包里面是有libdnnl.so.2 这个库文件的，并且我把这个.so也连接进去了，也是不行，既然有这个.so还需要在安装，那么那个推理包里面存在那个.so就不是没有意义了啊

**Comment by Bobholamovic** [comment]
请问『代码结构』指的是PaddleInference的代码嘛？请问你链接.so的方式是？

**Comment by persuelx** [comment]
是的，是这个包，链接方式是修改CMakelists.txt 1、link_directories("${PADDLE_LIB_THIRD_PARTY_PATH}mkldnn/lib")
将这个注释掉#set(MKLDNN1_LIB ${MKLDNN_PATH}/lib/libmkldnn.so.0)  改成set(MKLDNN1_LIB ${MKLDNN_PATH}/lib/libdnnl.so.2)
一红两种改法。

**Comment by Bobholamovic** [comment]
我理解除了在编译的时候，在运行的时候也需要保证能找到库才行（因为是动态链接库），可以把libdnn.so.2放入/usr/lib或者放在build目录中。

**Comment by persuelx** [comment]
在cmakelist中添加了链接路径以后就确保了运行是能找到了吧！！，你说的将libdnn.so.2放在build目录我也试了没用，我也试过将libdnn.s0.2库目录放进系统搜索目录下面去，发现也不行。

**Comment by Bobholamovic** [comment]
抱歉，重新查找了一下资料发现我先前的认知有错误，将共享库放在`build/`目录应该不是一个解决方案，因为：https://serverfault.com/questions/279068/cant-find-so-in-the-same-directory-as-the-executable

我还是认为这应该是一个Linux/C++相关的问题，而不止和PaddleSeg或PaddleInference有关~ 建议可以检查一下相关的环境变量，以及ldconfig的缓存是否已更新（编译可以通过，库的版本应该是匹配的）。

参见：
1. https://stackoverflow.com/questions/45419253/shared-object-library-not-found-when-running-program-but-its-linked-during-com
2. https://unix.stackexchange.com/questions/22926/where-do-executables-look-for-shared-objects-at-runtime

**Comment by manfrey666** [comment]
@persuelx 想问下您最后怎么解决的？
