### ISSUE TITLE
如何将人像分割的alpha图转换成PaddleSeg训练的标签图

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleSeg#2611]
您好，我想请教下如何将人像分割的alpha图转换成PaddleSeg训练的标签图，我是简单的大于0的像素映射为1，这样做的。但是映射后效果不好，边缘信息丢失严重，请问有什么好的办法吗，万分感谢

**Comment by juncaipeng** [comment]
@wuyefeilin 帮忙看下

**Comment by wuyefeilin** [comment]
直接将大于0的映射为1是可以的。 你所谓的边缘信息丢失严重可以详细描述一下吗

**Comment by jingmingtao** [comment]
![image](https://user-images.githubusercontent.com/114384977/195515962-92fd5cbc-9d92-4516-8af1-bbaa6419b252.png)
您看，左边这张是alpha图，右边这张是将大于0的图映射为255显示的图，发现差距比较大

**Comment by jingmingtao** [comment]
![image](https://user-images.githubusercontent.com/114384977/195516239-05164d7d-03a4-4266-b65e-dab59a3f26bc.png)
这是彩色图

**Comment by jingmingtao** [comment]
很明显alpha图，更接近彩色图，更精细，我用这样的映射显示的图，会边缘损失

**Comment by jingmingtao** [comment]
所以，我怀疑alpha图，直接这样映射，是不是不信，它本身会有一个渐变过程吗，我不太懂了，所以想请教下您

**Comment by jingmingtao** [comment]
而且咱们的pphumanseg使用的标签不是alpha图，而是类别映射的标签图，我想问一下这里可以转化用吗

**Comment by wuyefeilin** [comment]
alpha表示的是透明度，值代表前景的概率，所以形成彩色图会有一个渐变的过程，是一个Matting(抠图）的任务。 映射为二值图肯定会有细节的损失。

pphumanseg是利用语义标签训练的。但在预测的时候可以保留softmax的输出结果，类似于alpha图，可以达到边缘过度的效果。

你具体的任务是什么呢，描述一下，方便我们进行知道哈

**Comment by jingmingtao** [comment]
我的任务是做人像分割、人像抠图，使用的咱们开源的pphumanseg,用的咱们的ESeg标注工具。用的工程就是咱们的PaddleSeg工程，采用的网络是hrnet。我寻找了一批开源人像标注数据，他们是alpha图标注的，我想转成PaddleSeg-humanseg可以训练的标签数据，以供训练使用。

**Comment by jingmingtao** [comment]
我的任务是做人像分割、人像抠图，使用的咱们开源的pphumanseg,用的咱们的ESeg标注工具。用的工程就是咱们的PaddleSeg工程，采用的网络是hrnet。我寻找了一批开源人像标注数据，他们是alpha图标注的，我想转成PaddleSeg-humanseg可以训练的标签数据，以供训练使用。

**Comment by wuyefeilin** [comment]
人像分割按照之前的转化方法是可以直接进行的。  

如果要进行人像抠图可以使用Matting目录下的项目。利用alpha标签直接进行训练，细节会更好

**Comment by jingmingtao** [comment]
人像分割与人像抠图有啥不同呀，用的方法不同吗，为啥使用Matting目录下的项目，会更好呢

**Comment by jingmingtao** [comment]
我看pphumanseg也可以做人像抠图啊，这个文章写的
![image](https://user-images.githubusercontent.com/114384977/195532300-198d0e30-4443-4ff4-84eb-5609c0b6a809.png)

**Comment by jingmingtao** [comment]
Matting目录下的项目也是用HRNET做的吗

**Comment by jingmingtao** [comment]
那做人象抠图的话，数据标定只能使用photoshope来制作alpha图吗，百度飞将有没有其他类似ESeg这样的标注工具呢

**Comment by wuyefeilin** [comment]
这是两个不同的任务，语义分割是对每个像素进行分类，是一个离散的任务。 抠图是只提取出前景，计算每个像素的透明度，是一个回归的任务。

pphumanseg是对结果进行softmax的处理，模仿了抠图的过程，但细节上不如直接用抠图任务训练得到的模型。

具体模型及使用方法可以阅读参考我们的代码和文档

**Comment by wuyefeilin** [comment]
> 那做人象抠图的话，数据标定只能使用photoshope来制作alpha图吗，百度飞将有没有其他类似ESeg这样的标注工具呢

目前没有alpha的标注工具，你可以用ps进行标注哈

**Comment by jingmingtao** [comment]
明白了，网络我看matting是hrnet对吗也是一样训练的对吗

**Comment by wuyefeilin** [comment]
我们提供了多个模型，你可以根据实际情况进行选择

**Comment by jingmingtao** [comment]
好的谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月13日(星期四) 下午5:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleSeg] 如何将人像分割的alpha图转换成PaddleSeg训练的标签图 (Issue #2611)





 
我们提供了多个模型，你可以根据实际情况进行选择
