### ISSUE TITLE
[General Issue]EISeg标注出现问题

### ISSUE THREAD

**Issue by moonnnpie** [PaddlePaddle/PaddleSeg#2614]
使用EISeg标注的时候出现问题，不管什么图片他点一下都标注大半张或者不标注

---
![UCHUO4R}I7RSQSQYSW`2G95](https://user-images.githubusercontent.com/109192531/195527921-4e01df34-d138-4833-a8a5-32948746c345.png)
![image](https://user-images.githubusercontent.com/109192531/195528727-8b7943f5-263b-4f5c-af24-6948d7b27dd8.png)

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.6）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：Linux
 4. Python版本号：Python3.7
 5. CUDA/cuDNN版本：CUDA10.2
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by haoyuying** [comment]
用的什么模型呢，提供一张测试图我本地试一下，说明想要分割的要求

**Comment by moonnnpie** [comment]
> 用的什么模型呢，提供一张测试图我本地试一下，说明想要分割的要求

用的高精度通用模型，就是给的表格里的第一个，想把图片里正中央的东西提取出来，就不光是这个图片，我用别的图片也是只要标注就是选择大半张。

我换了低精度通用模型试了，也是同样的标注半张图片，我找不到问题出在了哪里。我是在远程服务器上跑的
![00007](https://user-images.githubusercontent.com/109192531/195538861-8f6f688b-4eca-45d2-b56e-f62eb4b9acd1.png)

**Comment by haoyuying** [comment]
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/35907364/195801516-9772d082-d020-4f86-b36a-0655607e4a9d.png">
本地并未复现您的问题，我用的paddle cpu版本2.2.1， eiseg1.0.3,模型和你用的同一个，感觉你的模型是不是load错了，我的load日志和你不一样
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/35907364/195802348-192704f4-d788-4781-a85f-2b97d280b26b.png">
<img width="848" alt="image" src="https://user-images.githubusercontent.com/35907364/195802449-d13830e5-edd0-42da-b8d2-bd7b6e503a15.png">

**Comment by moonnnpie** [comment]
我下载的是表格里的第一个模型和第二个模型
然后这是我load时候的选择模型，这里我是有弄错吗，或者模型有规定放在某个特定目录下吗
对我发现我的日志里面有出现failed，和你的不太一样

![{M8(%5TBGIC48LUK )AM8_X](https://user-images.githubusercontent.com/109192531/195806734-e2afa28f-c016-4573-9ab0-c5f9a8221483.png)

![8{UAT QJOP`ZCK{7X~0$1Q1](https://user-images.githubusercontent.com/109192531/195806756-858af0bc-200e-44af-a165-40d1b52d92a2.png)

**Comment by moonnnpie** [comment]
我在本地试了一下，是成功的，和你的效果是一样的，但是日志还是会显示failed，可能是我在远程服务器上有什么不适配吧
感谢感谢
