### ISSUE TITLE
[Feature Request] percision 存在疑问？

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/PaddleSeg#2616]
结果如下，因为我调高了后面两个类别权重，但是最终的结果并不是很理想，还需要做出那个方面调整，才能让精确率提升
![微信图片_20221014093517](https://user-images.githubusercontent.com/58769772/195742372-d14aad11-0e33-4d39-9ed0-caffa443f432.png)

**Comment by wuyefeilin** [comment]
需要详细描述你任务情况，我们才能给出相应的建议哈。另外你这才刚开始训练一会儿，精度较低是正常的

**Comment by chen-del** [comment]
嗯好的谢谢，可能和我设置的batch_size有关，我使用的单卡，所以batch_size设置比较小，然后训练有点慢，另外如果变大batch_size学习率如何进行变动以单卡为例。

**Comment by chen-del** [comment]
另外如果背景误检验证如何调整，训练方式

**Comment by chen-del** [comment]
还有如果背景误检率高，有没有什么策略可以把误解过滤掉，除了加入负样本外，因为负样本多了，又要调loss权重，有没有中和一点的方案，所以麻烦提供一下建议，感谢

**Comment by wuyefeilin** [comment]
> 嗯好的谢谢，可能和我设置的batch_size有关，我使用的单卡，所以batch_size设置比较小，然后训练有点慢，另外如果变大batch_size学习率如何进行变动以单卡为例。

正常来说，bs变大， lr需要跟着变大

**Comment by wuyefeilin** [comment]
> 还有如果背景误检率高，有没有什么策略可以把误解过滤掉，除了加入负样本外，因为负样本多了，又要调loss权重，有没有中和一点的方案，所以麻烦提供一下建议，感谢

背景类是第0类吗，是的话已经挺高的了。

如果样本分布不均衡，可以考虑用dice loss哈

**Comment by chen-del** [comment]
好的谢谢，例如现在是是单卡我将batch_size*2由8变为16 那么学习率是不是也要*2 ，iter迭代次数是不是要除以2

**Comment by chen-del** [comment]
@wuyefeilin 我已经在尝试使用了，但是有个问题在我使用这个的时候，我想提高负样本权重，但是这些损失函数让后面的类别1，2类别学习不到特征

**Comment by chen-del** [comment]
这个有什么办法我想提高正检，在没有分类类别的时候，不会将背景分为1，2类别

**Comment by wuyefeilin** [comment]
> 好的谢谢，例如现在是是单卡我将batch_size_2由8变为16 那么学习率是不是也要_2 ，iter迭代次数是不是要除以2

理论上是这么处理的。具体的也可以根据你的数据进行调整哈

**Comment by wuyefeilin** [comment]
> @wuyefeilin 我已经在尝试使用了，但是有个问题在我使用这个的时候，我想提高负样本权重，但是这些损失函数让后面的类别1，2类别学习不到特征
我们提供了丰富的loss函数像OHEM CE Loss, lovasz loss, connectivity loss等都可以进行尝试哈。https://github.com/PaddlePaddle/PaddleSeg/tree/develop#-overview

如果追求高精度可以选择高精度的模型进行训练。
https://github.com/PaddlePaddle/PaddleSeg/issues/2616#issuecomment-1278813321

**Comment by chen-del** [comment]
@wuyefeilin ,使用高精度模型，模型的参数量普遍偏大，我尝试使用下其他的loss

**Comment by shiyutang** [comment]
好的。
