### ISSUE TITLE
人像抠图 PaddleSeg/Matting中的相关问题请教

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleSeg#2619]
问题1：想问一下，说明文档中提到的数据集，一个是PPM-100，还有一种是the Composition-1k dataset，如下图。想问的是我在哪里可以下载到the Composition-1k dataset，请问有相关的链接可以提供吗。
![image](https://user-images.githubusercontent.com/114384977/195754926-22251c1e-568a-49a8-b273-35cf54efbdcf.png)
问题2：咱们文档中提供的例子是modnet-mobilenetv2模型，它的配置参数什么的，都只是例子对吧。batchsize一般设置多少比较好，是根据训练资源越大越好对吗。一般训练200epoch是不是差不多够了，从而来设置iter对吧？

**Comment by wuyefeilin** [comment]
composition 得发邮件给Deep  Image Matting的作者进行索取哈

配置文件在configs目录下哈

**Comment by jingmingtao** [comment]
您好，一般抠图matting的指标sad多少，证明模型效果还不错，可以分享一下经验吗，还有batchsize跟训练的轮数，可以指导一下经验吗
