### ISSUE TITLE
[General Issue]EISeg保存图像文件名设置

### ISSUE THREAD

**Issue by moonnnpie** [PaddlePaddle/PaddleSeg#2622]
请问EISeg图像标注完成后保存的图片可以自定义文件名吗？比如我选择抠图保存文件名会存XXXX_cutout，请问这个cutout部分可以自己更改吗，比如说文件名里面把cutout删除，就保存为原文件名

**Comment by haoyuying** [comment]
目前没有该功能，您可以在标注完成后写个脚本对自己的图像进行批量处理。

**Comment by moonnnpie** [comment]
好的感谢感谢
