### ISSUE TITLE
人像抠图PaddleSeg/Matting中训练时问题请教

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleSeg#2624]
您好，想跟您请教一下人像抠图训练中的一些技术问题
1、想问一下，咱们训练人像抠图时batchsize一般设置多少，我看例子设置1，是跟其他模型一样是越大越好吗；
2、想问一下，一般epoch设置多少，这个跟数据量是不是有关，如果我有4w数据，设置多少比较好；
3、想问一下，指标sad一般多少证明模型表现不错
以上问题，请求您指教下，万分感谢

**Comment by jingmingtao** [comment]
您好，想跟您请教一下人像抠图训练中的一些技术问题
1、想问一下，咱们训练人像抠图时batchsize一般设置多少，我看例子设置1，是跟其他模型一样是越大越好吗；
2、想问一下，一般epoch设置多少，这个跟数据量是不是有关，如果我有4w数据，设置多少比较好；
3、想问一下，指标sad一般多少证明模型表现不错
以上问题，请求您指教下，万分感谢

**Comment by wuyefeilin** [comment]
你好，配置相关信息在configs下的配置文件中可以找到

关于人像抠图的指标，根据场景的不同，表现不同，不能一概而论
