### ISSUE TITLE
LabelMe标注好图片之后，使用labelme2seg无法生成真值图片

### ISSUE THREAD

**Issue by zhouhaitao1023** [PaddlePaddle/PaddleSeg#263]
我使用LabelMe标注好图片之后，使用labelme2seg生成真值图片，运行labelme2seg的时候报错，报错信息如下：
class_names: ('_background_', 'steel')
Saved class_names: D:\2\class_names.txt
Generating dataset from: D:\2\2020_5_15_13_19_46_995.json
Traceback (most recent call last):
  File "D:\PaddleSeg\pdseg\tools\labelme2seg.py", line 90, in <module>
    main(args)
  File "D:\PaddleSeg\pdseg\tools\labelme2seg.py", line 78, in main
    if lbl.min() >= 0 and lbl.max() <= 255:
AttributeError: 'tuple' object has no attribute 'min'

**Comment by qiyuezhiguang** [comment]
find this line:  lbl= labelme.utils.shapes_to_label(
and change it to : lbl, _ = labelme.utils.shapes_to_label(
then it will works well.


——————————————————
支持paddle，支持国产

**Comment by LutaoChu** [comment]
@qiyuezhiguang 感谢支持。你的方法是对的。
@zhouhaitao1023 labelme接口变更导致的问题，已经提交pr #266，等合入后pull最新代码即可修复该问题

**Comment by zhouhaitao1023** [comment]
非常感谢，我费了半天劲，用halcon写了一个生成真值图片的工具。已经用上了。
