### ISSUE TITLE
关于 RTFormer  ,请问，可以用来视频抠像训练吗？

### ISSUE THREAD

**Issue by zhanghongyong123456** [PaddlePaddle/PaddleSeg#2638]
1. 类似于https://github.com/SHI-Labs/VMFormer 项目,这个论文说transformer 可以很好的解决闪烁问题，所以我想问我们的项目可以进行视频抠像训练吗，能有效缓解视频闪烁问题吗，我们这个transformer 可以实现高清4k实时吗
2.  对于抠像和分割是否只需要修改数据通道以及loss计算的公式就可以直接使用，无需修改模型框架的其他内容

**Comment by Bobholamovic** [comment]
你好，目前PaddleSeg将RTFormer支持为图像语义分割模型。将RTFormer用于抠像任务需要修改数据和损失。套件暂时未提供将RTFormer用于视频任务的功能。

**Comment by zhanghongyong123456** [comment]
> 

请问，我能加时间一致性的损失，用于视频抠像吗，还是说模型必须需要时间一致性的设计

**Comment by Bobholamovic** [comment]
目前PaddleSeg只提供图像分割相关的训练、测试、推理功能，对视频任务的数据预处理、后处理以及训练、推理等暂时不支持，所以我理解可能时间一致性损失不一定能在现有框架中使用哦~

**Comment by zhanghongyong123456** [comment]
> 目前PaddleSeg只提供图像分割相关的训练、测试、推理功能，对视频任务的数据预处理、后处理以及训练、推理等暂时不支持，所以我理解可能时间一致性损失不一定能在现有框架中使用哦~

好的，谢谢解答，那么以后有计划对视频任务实现吗

**Comment by Bobholamovic** [comment]
有的。实际上我们正在开发视频分割相关能力 相信不久以后大家就能用上啦～

**Comment by zhanghongyong123456** [comment]
> 有的。实际上我们正在开发视频分割相关能力 相信不久以后大家就能用上啦～

好的，谢谢
