### ISSUE TITLE
mixedLoss中的Loss比例如何划分

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleSeg#2639]
在语义分割中用到的MixedLoss来进行多个损失函数组合应用
比如LovaszSoftmaxLoss和CrossEntropyLoss中两个的比例分别为0.2和0.8
请教一下这个比例在实际的训练中如何确定，有没有什么评价方法

**Comment by Bobholamovic** [comment]
如果论文中有涉及相关描述，可以采用论文中的配置。在实际工程中可以通过网格法进行参数分析实验确定（即，尝试多种可能的组合）。

**Comment by BeyondYourself** [comment]
多谢大神解答，还有个疑问就是MixedLoss中涉及的损失函数组合一般怎么结合比较好，目前是多分类，样本分布不均衡的，采用CrossEntropyLoss+MultiClassFocalLoss吗 @Bobholamovic

**Comment by Bobholamovic** [comment]
类别不均衡/长尾分布可以考虑加权（设置weight参数，给小类别更大权重）CrossEntropyLoss+MultiClassFocalLoss的组合，FocalLoss在设计时考虑了难样本挖掘，因此能够缓解样本分布不均衡问题。

**Comment by BeyondYourself** [comment]
> 

多谢解惑

**Comment by BeyondYourself** [comment]
CELoss中如果对于类别设置权重，Ignore_index也设置 了，并且ignore_index是忽略的背景分类，权重中需要设置背景的权重吗

> 



> 类别不均衡/长尾分布可以考虑加权（设置weight参数，给小类别更大权重）CrossEntropyLoss+MultiClassFocalLoss的组合，FocalLoss在设计时考虑了难样本挖掘，因此能够缓解样本分布不均衡问题。

**Comment by Bobholamovic** [comment]
weight中还是需要设置被忽略类别的权重值（如果被忽略类别的id小于num_classes的话）~
