### ISSUE TITLE
[Bug] Cannot export model

### ISSUE THREAD

**Issue by ukoehler** [PaddlePaddle/PaddleSeg#2643]
System:
Windows 10
Python 3.9.13
paddle-bfloat      0.1.7
paddle2onnx        1.0.1
paddlefsl          1.1.0
paddlehub          2.3.0
paddlenlp          2.4.1
paddlepaddle       2.3.2
paddleseg          2.6.0

For issue https://github.com/PaddlePaddle/PaddleHub/issues/2083 I have been asked to try and export a model to prepare for the conversion to ONNX. First, I tried to follow the following example: https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/docs/model_export.md

I know it is difficult to document own code, so here some comments:

1. It is unclear how to get the files needed. They can be found here https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.6/configs/bisenet. A link would be helpful. 
2.  What is the input? (Needs to be guessed from Resolution) RGB or BGR?
3.  What is the mean?
4.  What is the std?
5.  What is the output (might also need the node name)?
6.  What are the labels?

This info is missing for most models I have seen in Paddle.
 
After downloading the files and ```set CUDA_VISIBLE_DEVICES=0```, I found that (on Windows) ```python export.py``` does not work. I tried the two export.py scripts with full path

```
./Lib/site-packages/paddle/onnx/export.py
./Lib/site-packages/paddlenlp/transformers/export.py
```
The first script execute quietly and doesn't seem to do anything:
```
(.venv) D:\Local\devel\Python\PaddleSeg\BiSeNet_V2>D:\Local\devel\Python\PaddleS
eg\.venv\Lib\site-packages\paddle\onnx\export.py --config bisenet_cityscapes_102
4x1024_160k.yml --model_path model.pdparams --save_dir output --input_shape 1 3
512 1024

(.venv) D:\Local\devel\Python\PaddleSeg\BiSeNet_V2>dir
 Datenträger in Laufwerk D: ist Data
 Volumeseriennummer: FFBE-7020

 Verzeichnis von D:\Local\devel\Python\PaddleSeg\BiSeNet_V2

21.10.2022  10:57    <DIR>          .
21.10.2022  10:57    <DIR>          ..
21.10.2022  10:56           157.181 bisenet_cityscapes_1024x1024_160k.yml
04.03.2022  14:45        15.301.992 model.pdparams
               2 Datei(en),     15.459.173 Bytes
               2 Verzeichnis(se), 24.066.383.872 Bytes frei
```
The second script wont execute at all
```
(.venv) D:\Local\devel\Python\PaddleSeg\BiSeNet_V2>python D:\Local\devel\Python\
PaddleSeg\.venv\Lib\site-packages\paddlenlp\transformers\export.py --config bise
net_cityscapes_1024x1024_160k.yml --model_path model.pdparams --save_dir output
--input_shape 1 3 512 1024
Traceback (most recent call last):
  File "D:\Local\devel\Python\PaddleSeg\.venv\Lib\site-packages\paddlenlp\transf
ormers\export.py", line 19, in <module>
    from ..utils.log import logger
ImportError: attempted relative import with no known parent package
```
Is there anything I have missed?

**Comment by shiyutang** [comment]
You need to run the python export.py command under “PaddleSeg/” directory rather than “PaddleSeg\BiSeNet_V2”.

**Comment by ukoehler** [comment]
Hi @shiyutang,

hope this additional information helps:

1. Make sure to use the raw version when using wget (I have now, but that doesn't help)
2. I am not using a checked out version of PaddleSeg, but a pip installed version
3. The yml files was referencing recursively other yml files in ```_base_``` . Obviously I did not have those. So I downloaded them and adapted the path in the yml files like ```_base_: './cityscapes_1024x1024.yml'```

Still, the same result for the call:
```
(.venv) D:\Local\devel\Python\PaddleSeg\BiSeNet_V2>python D:\Local\devel\Python\
PaddleSeg\.venv\Lib\site-packages\paddle\onnx\export.py --config bisenet_citysca
pes_1024x1024_160k.yml --model_path model.pdparams --save_dir output --input_sha
pe 1 3 512 1024

(.venv) D:\Local\devel\Python\PaddleSeg\BiSeNet_V2>dir
 Datenträger in Laufwerk D: ist Data
 Volumeseriennummer: FFBE-7020

 Verzeichnis von D:\Local\devel\Python\PaddleSeg\BiSeNet_V2

21.10.2022  13:21    <DIR>          .
21.10.2022  13:21    <DIR>          ..
21.10.2022  13:21               430 bisenet_cityscapes_1024x1024_160k.yml
21.10.2022  13:16               778 cityscapes.yml
21.10.2022  13:21               444 cityscapes_1024x1024.yml
04.03.2022  14:45        15.301.992 model.pdparams
               4 Datei(en),     15.303.644 Bytes
               2 Verzeichnis(se), 24.066.195.456 Bytes frei
```

**Comment by ukoehler** [comment]
I also tried from the directory up. Entries in the yml is now ```_base_: './BiSeNet_V2/cityscapes.yml'```. I also tried with \ and / for directory separator.

```
(.venv) D:\Local\devel\Python\PaddleSeg>python D:\Local\devel\Python\PaddleSeg\.
venv\Lib\site-packages\paddle\onnx\export.py --config BiSeNet_V2\bisenet_citysca
pes_1024x1024_160k.yml --model_path BiSeNet_V2\model.pdparams --save_dir output
--input_shape 1 3 512 1024

(.venv) D:\Local\devel\Python\PaddleSeg>python D:\Local\devel\Python\PaddleSeg\.
venv\Lib\site-packages\paddle\onnx\export.py --config BiSeNet_V2/bisenet_citysca
pes_1024x1024_160k.yml --model_path BiSeNet_V2/model.pdparams --save_dir output
--input_shape 1 3 512 1024

(.venv) D:\Local\devel\Python\PaddleSeg>dir
 Datenträger in Laufwerk D: ist Data
 Volumeseriennummer: FFBE-7020

 Verzeichnis von D:\Local\devel\Python\PaddleSeg

21.10.2022  10:54    <DIR>          .
21.10.2022  10:54    <DIR>          ..
18.10.2022  11:16    <DIR>          .venv
21.10.2022  13:21    <DIR>          BiSeNet_V2
20.10.2022  13:48    <DIR>          deeplabv3p_xception65_humanseg
20.10.2022  15:15    <DIR>          humanseg_server
21.10.2022  13:33             2.395 InstallAndTest.txt
18.10.2022  16:11    <DIR>          opencv_paddlepaddle
20.10.2022  12:24    <DIR>          trial
               1 Datei(en),          2.395 Bytes
               8 Verzeichnis(se), 24.066.248.704 Bytes frei
```

**Comment by ukoehler** [comment]
Hmmmm, I did have a look at the only two ```export.py``` scripts you get when installing with pip. Both of them seem to be related to the task, however, both do not fit. Also, both do not have a main to execute at all.

Where can I get the needed export.py script? Also, the command hub from PaddlePaddle can be executed with the absolute path inside a venv.

**Comment by ukoehler** [comment]
OK, this needs the full checkout of PaddleSeg. A pip install is not enough. This is confusing.

**Comment by shiyutang** [comment]
Did you solve your problem? 
It seems you need to export your model to onnx and the [doc you refer to](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/docs/model_export.md) is actually meant for export to the static model, and we will add the script to export models to onnx in the future.

**Comment by ukoehler** [comment]
Dear @shiyutang ,

many thanks for asking. The status is that I can export models now. However, I have two points

1. The documentation could be clearer for other newbies like me. I know it is difficult to document stuff you use all the time. That is why I am pointing stuff out I find. See also https://github.com/PaddlePaddle/PaddleSeg/issues/2660

2. To export models to ONNX in the end, I seem to have to provide --input_shape. The correct values are guess work since it is not clear if widthxheight or rowsxcolumns is meant. That would be good to detect automatically. See also https://github.com/PaddlePaddle/PaddleSeg/issues/2660

Cheers

Uwe

**Comment by shiyutang** [comment]
Thank you for your suggestion, we will try to improve our docs.
