### ISSUE TITLE
Matting人像分割模型大小

### ISSUE THREAD

**Issue by bigbiglemon** [PaddlePaddle/PaddleSeg#2645]
业务需求在Android做离线人像抠图，对比PP-HumanSeg  和 Matting模块下几个模型效果，最终选择Matting(主要由于PP-HumanSeg边缘模糊），但是Matting几个模型最小都有20+M，opt 工具设置quant_type位int8亦无改变（没有量化的模型？）
问题：应该如何才能压缩 Matting 下模型大小？？？

**Comment by wuyefeilin** [comment]
我们正着手进行压缩和部署功能的强化，轻量化抠图模型的研发。敬请期待哈

**Comment by juncaipeng** [comment]
> 但是Matting几个模型最小都有20+M，opt 工具设置quant_type位int8亦无改变（没有量化的模型？）

应该可以减小到模型1/4的，应该是使用错误，你可以排查一下

**Comment by bigbiglemon** [comment]
@juncaipeng  👌，我再排查一下，辛苦答疑
