### ISSUE TITLE
paddle安装问题

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleSeg#2646]
![image](https://user-images.githubusercontent.com/114384977/197430058-a4a2c0e7-af45-45f9-a6e9-23f4f81e2093.png)
您好，安装paddle的时候包哦了这个错，求解决，万分感谢

**Comment by haoyuying** [comment]
您好，paddle安装问题请移步https://github.com/PaddlePaddle/Paddle/issues
