### ISSUE TITLE
export导出静态图报错

### ISSUE THREAD

**Issue by peiwenYe** [PaddlePaddle/PaddleSeg#2649]
CityscapesSOTA模型导出静态图报错
![image](https://user-images.githubusercontent.com/37332773/197470514-1db4a6b3-0215-4ec8-b995-ca57bac3bb2d.png)

**Comment by haoyuying** [comment]
您好，请给出具体的导出环境及导出时的命令行代码，方便排查问题。

**Comment by peiwenYe** [comment]
> 您好，请给出具体的导出环境及导出时的命令行代码，方便排查问题。

Mac M1
paddle version: 2.2.2
python: 3.8
paddleSeg release/2.4
命令：`python export.py --config ./contrib/CityscapesSOTA/configs/mscale_ocr_cityscapes_autolabel_mapillary_ms_val.yml --model_path https://bj.bcebos.com/paddleseg/dygraph/cityscapes/mscale_ocr_hrnetw48_cityscapes_autolabel_mapillary/model.pdparams   --save_dir ./output --input_shape 1 3 2048 1024`
预训练模型来自于官方教程
![image](https://user-images.githubusercontent.com/37332773/197719173-40c444dc-36ff-4ad1-96d3-441abb307291.png)

**Comment by juncaipeng** [comment]
好  我们跟进看下

**Comment by juncaipeng** [comment]
修复PR： #2684
在develop分支，我们新增了export.py的脚本。
在`~/PaddleSeg/contrib/CityscapesSOTA`目录下，执行
`python export.py --config configs/mscale_ocr_cityscapes_autolabel_mapillary_ms_val.yml --save_dir ./output --input_shape 1 3 2048 1024`
