### ISSUE TITLE
paddleseg在预测时，生不成图片

### ISSUE THREAD

**Issue by maxiaomu** [PaddlePaddle/PaddleSeg#265]
我自己做的40张数据集，修改了paddlepaddle官网上的猫狗识别大战案例，但是总出问题，调试了两天不知道哪儿有问题。太痛苦了，想请教你一下。

![D~E77{XN%~%OI1%$Y2X$P{E](https://user-images.githubusercontent.com/19425758/82811015-609d7f80-9ec2-11ea-8094-167f093c4090.png)
![74J$7(` AYAG4S6`DHY_%I6](https://user-images.githubusercontent.com/19425758/82811035-6c894180-9ec2-11ea-9cda-9536e1552db7.png)
![@I7 7RDK`XUHJ ~YZ2EKP9J](https://user-images.githubusercontent.com/19425758/82811042-6f843200-9ec2-11ea-9665-68cb847a0e4d.png)
![S{M( 1X VVS(1_3)M Q6B77](https://user-images.githubusercontent.com/19425758/82811049-727f2280-9ec2-11ea-8403-4b2cd6d6425b.png)
![5`PS B)2}HI0)_KWKG_ZV67](https://user-images.githubusercontent.com/19425758/82811055-74e17c80-9ec2-11ea-8e3d-883f78929e72.png)
![07TLGZL20NE@ SBVK235ZF](https://user-images.githubusercontent.com/19425758/82811062-78750380-9ec2-11ea-9482-05919554c56d.png)
![$IQMK`G7JM_7C9D8%ASV_K4](https://user-images.githubusercontent.com/19425758/82811069-7b6ff400-9ec2-11ea-93a3-4089bdafd3ce.png)
![ZU`我自己做的40张数据集，修改了paddlepaddle官网上的猫狗识别大战案例，但是总出问题，调试了两天不知道哪儿有问题。太痛苦了，想请教你一下。

![D~E77{XN%~%OI1%$Y2X$P{E](https://user-images.githubusercontent.com/19425758/82811015-609d7f80-9ec2-11ea-8094-167f093c4090.png)
![74J$7(` AYAG4S6`DHY_%I6](https://user-images.githubusercontent.com/19425758/82811035-6c894180-9ec2-11ea-9cda-9536e1552db7.png)
![@I7 7RDK`XUHJ ~YZ2EKP9J](https://user-images.githubusercontent.com/19425758/82811042-6f843200-9ec2-11ea-9665-68cb847a0e4d.png)
![S{M( 1X VVS(1_3)M Q6B77](https://user-images.githubusercontent.com/19425758/82811049-727f2280-9ec2-11ea-8403-4b2cd6d6425b.png)
![5`PS B)2}HI0)_KWKG_ZV67](https://user-images.githubusercontent.com/19425758/82811055-74e17c80-9ec2-11ea-8e3d-883f78929e72.png)
![07TLGZL20NE@ SBVK235ZF](https://user-images.githubusercontent.com/19425758/82811062-78750380-9ec2-11ea-9482-05919554c56d.png)
![$IQMK`G7JM_7C9D8%ASV_K4](https://user-images.githubusercontent.com/19425758/82811069-7b6ff400-9ec2-11ea-93a3-4089bdafd3ce.png)
DRK}TZ3ZA%M3NZOMQM](https://user-images.githubusercontent.com/19425758/82811072-7d39b780-9ec2-11ea-86ce-82d43bf47d2f.png)
![TCQ480HC7Z L(K}NCIZKC3E](https://user-images.githubusercontent.com/19425758/82811079-82970200-9ec2-11ea-8d85-af0795128ae7.png)

**Comment by wuyefeilin** [comment]
把你的项目链接给我们一下，我们直接fork你的项目看看能不能复现。

**Comment by maxiaomu** [comment]
https://aistudio.baidu.com/aistudio/projectdetail/491628  刚看见，不好意思，麻烦你了

**Comment by wstchhwp** [comment]
你好，我想知道进展如何了？ @wuyefeilin

**Comment by wuyefeilin** [comment]
你没有发版，无法fork你的项目。按照官网的aistudio是可以跑通的，你检查一下路径是否设置正确，模型路径，数据集路径。
![image](https://user-images.githubusercontent.com/30919197/83478663-fd66ab00-a4c8-11ea-99ec-08dcf55c033e.png)
这边的模型路径不一样了

**Comment by wstchhwp** [comment]
你好，我见好几个人都fork了，我调试总有问题 @wuyefeilin

**Comment by wstchhwp** [comment]
现在可以fork了 @wuyefeilin

**Comment by wuyefeilin** [comment]
你没添加文件，没办法运行，我看你在训练的时候，提示数据集路径找不到，检查一下你的train_list.txt是否设置正确
![image](https://user-images.githubusercontent.com/30919197/83489708-6d812b00-a4e1-11ea-81e7-7dba7691c9ba.png)

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。
