### ISSUE TITLE
新出的RTFormer在哪里呢？

### ISSUE THREAD

**Issue by linshuchar** [PaddlePaddle/PaddleSeg#2655]

**Comment by aixuedegege** [comment]
顺便问一下用这个训练自己的数据 yml要怎么写？

**Comment by aixuedegege** [comment]
自我解决：拉develop代码下来run就ok了

**Comment by juncaipeng** [comment]
https://github.com/PaddlePaddle/PaddleSeg/tree/develop/configs/rtformer
