### ISSUE TITLE
EdgeFlow - Edge Guidance - Code Location

### ISSUE THREAD

**Issue by danieltudosiu** [PaddlePaddle/PaddleSeg#2656]
Hey,

Thank you very much for the fantastic work you are doing!

I just read your paper "EdgeFlow: Achieving Practical Interactive Segmentation with Edge-Guided Flow" and would like to use some parts of it in my work. 

I tried to find the code linked to the EdgeFlow paper but failed to do so. Could you please point me towards the following components:
- Section 3.2 - Edge-guided Flow - Edge Guidance
    - "object edges estimated from the previous iteration"
    - "flow module to align image and interaction features"

Cheers!

**Comment by haoyuying** [comment]
We provide the edgeflow model in this link, https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/EISeg/docs/image_en.md
![image](https://user-images.githubusercontent.com/35907364/197921111-34ee2f55-4811-4d0a-8d38-90f362a06541.png)
this model is the static model by paddlepaddle, so we do not need to provide code for model structure in our repo, you may use visualdl to visualize the model structure.
