### ISSUE TITLE
PP_HumanSeg val 报错

### ISSUE THREAD

**Issue by peiwenYe** [PaddlePaddle/PaddleSeg#2659]
PaddleSeg: 2.6
paddlepaddle: 2.2.2
python: 3.7.4
通用人像分割val报错
![image](https://user-images.githubusercontent.com/37332773/197971553-8a10532d-85ac-4c48-8f8b-2e6f0d68d47a.png)
使用的命令如下：
`~/PaddleSeg/contrib/PP-HumanSeg$ python ../../val.py --config /home/aistudio/PaddleSeg/contrib/PP-HumanSeg/configs/human_pp_humansegv1_lite.yml`

**Comment by wuyefeilin** [comment]
contrib/PP-HumanSeg只支持预测，如果需要训练评估请移步PaddelSeg目录并利用PaddeSeg/configs下的配置文件进行训练评估

**Comment by juncaipeng** [comment]
升级使用paddle 2.3版本，可以避免这个bug。
