### ISSUE TITLE
[Bug] Error in current "Model Export" documentation

### ISSUE THREAD

**Issue by ukoehler** [PaddlePaddle/PaddleSeg#2660]
Hi,

the following documentation https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/docs/model_export.md has the input size at ```--input_shape 1 3 512 1024```, however it looks like the input for the model should be 1024x1024. See https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.6/configs/bisenet

**Comment by Bobholamovic** [comment]
Thanks for pointing out this bug! We have updated the document in the develop branch. Please check:
https://github.com/PaddlePaddle/PaddleSeg/blob/develop/docs/model_export.md

**Comment by ukoehler** [comment]
Works when changing tools/export.py to export.py

**Comment by ukoehler** [comment]
Also, paddle2onnx only works when using ```--input_shape 1 3 1024 512```, as well. Are we sure that is 1024x512 and not 512x1024?

**Comment by Bobholamovic** [comment]
> Works when changing tools/export.py to export.py

Sorry that I forgot to mention that in the develop branch we have migrated `export.py` to `tools/export.py`. In the next release version, we will remove `export.py` and keep only `tools/export.py`.

**Comment by Bobholamovic** [comment]
> Also, paddle2onnx only works when using `--input_shape 1 3 1024 512`, as well. Are we sure that is 1024x512 and not 512x1024?

Can you give more details about this problem? According to the [paddle2onnx document](https://github.com/PaddlePaddle/Paddle2ONNX/blob/release/0.9.5/README.md), there is only `--input_shape_dict` commandline argument and no `--input_shape`.

**Comment by ukoehler** [comment]
Oh, I didn't know you could provide the input shape to paddle2onnx (I follow instructions from the OpevCV GitHub). I do not pass input shape there and have to provide it to export.py or I get an error in paddle2onnx.

```
paddle2onnx --model_dir pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 11 --save_file pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k\pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k.onnx
```
will result in 
```
(.venv) D:\Local\devel\Python\PaddleSeg\PaddleSeg\PP-LiteSeg>paddle2onnx --model
_dir pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k --model_filename model.p
dmodel --params_filename model.pdiparams --opset_version 11 --save_file pp_lites
eg_stdc1_cityscapes_1024x512_scale0.5_160k\pp_liteseg_stdc1_cityscapes_1024x512_
scale0.5_160k.onnx
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160
k\model.pdmodel
[Paddle2ONNX] Paramters file path: pp_liteseg_stdc1_cityscapes_1024x512_scale0.5
_160k\model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[ERROR][Paddle2ONNX] [pool2d: pool2d_4.tmp_0] Adaptive only support static input
 shape.
[Paddle2ONNX] Due to the operator: pool2d, this model cannot be exported to ONNX
.
[ERROR][Paddle2ONNX] [pool2d: pool2d_5.tmp_0] Adaptive only support static input
 shape.
[Paddle2ONNX] Due to the operator: pool2d, this model cannot be exported to ONNX
.
[ERROR] Model exporting failed, you can report this problem to https://github.co
m/PaddlePaddle/Paddle2ONNX.git.
```
trying with input shape gives the same result
```
paddle2onnx --model_dir pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 11 --save_file pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k\pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k.onnx --input_shape_dict="{'image':[1, 3, 1024, 512]}"
```
Since you always have to provide the input shape by hand to export.py I guess that should be shown in the example. Actually, since it is not easy to find out the input shape (is PP-LiteSeg really operating in portrait mode?), it would be good if auto-detection would work

**Comment by Bobholamovic** [comment]
The error in `paddle2onnx` seems to be caused by missing operators, which is an issue outside the scope of PaddleSeg. Please ask for help from  [the Paddle2ONNX official repo](https://github.com/PaddlePaddle/Paddle2ONNX).

> Since you always have to provide the input shape by hand to export.py I guess that should be shown in the example. Actually, since it is not easy to find out the input shape (is PP-LiteSeg really operating in portrait mode?), it would be good if auto-detection would work

We don't *have to* provide the input shape by hand to `export.py`. If `--input_shape` is not specified, a default shape of `[None, 3, None, None]` will be used. `None` indicates the input image can have **any** size in that dimension. However, this does not work for every model. For some models, you may have to specify `--input_shape` manually.
