### ISSUE TITLE
求求大哥了，帮忙看看吧，这个问题我困扰了两天了shape必须统一的问题

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleSeg#2661]
您好我在使用咱们的工程时，数据array.shape不同，我也知道是这个问题，我将所有的训练集的alpha用np.array读取它的shape发现都是单通道的，没有发现3通道的呀。有三通道的我也用代码转换成单通道了。还是报这个问题。请教一下，如何解决。
![Uploading image.png…]()

**Comment by jingmingtao** [comment]
报的错：File "/home/cy/anaconda3/envs/torch/lib/python3.9/site-packages/numpy/core/shape_base.py", line 428, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape

**Comment by jingmingtao** [comment]
我进入到/home/cy/anaconda3/envs/torch/lib/python3.9/site-packages/numpy/core/shape_base.py下边428行将这个len(shape)打印出来是2，这是什么导致的呀。

**Comment by jingmingtao** [comment]
以前我也遇到这样的情况，我将数据用np.array打印出shape发现有(800,600,3)的，我就用代码给转换成单通道的，就解决了。现在我还是用这种方法，就不能解决了。关键转换后，我去用np.array打印出shape,已经没有(800,600,3)这样三通道的了呀

**Comment by jingmingtao** [comment]
我寻思，是不是咱们工程里边在使用np.array读取alpha的时候，可以这样img_open=Image.open(img_path).convert("L")，而不是img_open=Image.open(img_path)。但是，工程中我又没有找到这个读取使用np.array读取alpha的地方，如果想通过这样修改，来避免我的问题的话，我应该修改那里的代码。如果不这样修改，我应该怎么解决这个shape不同的问题。

**Comment by jingmingtao** [comment]
3通道转换为单通道的代码为：，应该也没什么问题吧
![image](https://user-images.githubusercontent.com/114384977/198166913-f1beff7f-b1ed-4ea3-b765-383644248c9c.png)

**Comment by jingmingtao** [comment]
报的错误：
![image](https://user-images.githubusercontent.com/114384977/198166994-6084e843-24ea-425f-83df-cda7e9d7971b.png)

**Comment by jingmingtao** [comment]
我使用的工程是PPseg中的Matting做人像抠图

**Comment by jingmingtao** [comment]
大哥，球球了，怎么避免解决这个问题呢

**Comment by jingmingtao** [comment]
我改了一下numworker，也没用

**Comment by jingmingtao** [comment]
以前训练分类、检测、分割怎么没有这个问题。为啥到了这个，就必须shape一样，代码到底怎么了

**Comment by wuyefeilin** [comment]
猜测可能是数据增强的问题。麻烦给一下你的训练日志，训练命令以及配置文件

**Comment by jingmingtao** [comment]
训练命令：python tools/train.py --config configs/quick_start/modnet-mobilenetv2.yml --do_eval --use_vdl --save_interval 100 --num_workers 1 --save_dir output_3w
配置文件：
![Uploading image.png…]()

**Comment by jingmingtao** [comment]
配置文件：
![image](https://user-images.githubusercontent.com/114384977/198181042-9a2f5d18-4b41-421b-ad77-77709f73b73d.png)

**Comment by jingmingtao** [comment]
原本我没有增加paddling的时候会报错，shape的问题。增加了paddling时候，变成了ValueError: The shape of `pred`, `gt` and `trimap` should be equal. but they are (1, 1, 750, 563), (1, 1, 563, 750) and (1, 1, 563, 750)

**Comment by jingmingtao** [comment]
我也是看咱们有关评论里，有用增加padding target【512，512】就解决了的，我试了下，就又报ValueError: The shape of pred, gt and trimap should be equal. but they are (1, 1, 750, 563), (1, 1, 563, 750) and (1, 1, 563, 750)这样的错了

**Comment by jingmingtao** [comment]
关键我将所有的alpha，用np.array，读取它的shape，它的shape[2]，都是不存在的呀。因为我已经将部分的shape[2]==3的已经改成单通道了呀，改完后还用代码检查了下，没问题呀

**Comment by jingmingtao** [comment]
训练集验证集都修改了

**Comment by jingmingtao** [comment]
包括fg中的图片发现shpe[2]有等于4的，我也已经删除了，现在除了图片的长宽不同，别的维度都相同了呀

**Comment by jingmingtao** [comment]
不会是长宽不同导致的吗，

**Comment by jingmingtao** [comment]
训练日志怎么给你呀，

**Comment by jingmingtao** [comment]
大哥，可以操作吗

**Comment by jingmingtao** [comment]
我python是3.9有关系吗

**Comment by jingmingtao** [comment]
大哥能看到我的消息吗

**Comment by jingmingtao** [comment]
> 猜测可能是数据增强的问题。麻烦给一下你的训练日志，训练命令以及配置文件

我发了您看到了吗

**Comment by jingmingtao** [comment]
您能收到吗

**Comment by wuyefeilin** [comment]
教程跑通了吗

**Comment by jingmingtao** [comment]
教程早就跑通了，并且在自己制作的训练集、搜集的训练集上训练过几个模型了

**Comment by jingmingtao** [comment]
这次的新的数据，就不可以了

**Comment by jingmingtao** [comment]
教程跑通没问题的

**Comment by jingmingtao** [comment]
![image](https://user-images.githubusercontent.com/114384977/198195885-2ff2ffa6-31d7-416f-aa2a-ef48816924f6.png)

**Comment by jingmingtao** [comment]
求求你帮我看看吧

**Comment by jingmingtao** [comment]
是不是需要图片的长宽都一样啊，

**Comment by jingmingtao** [comment]
教程跑通了

**Comment by jingmingtao** [comment]
大哥，我很着急，能帮我看看吗

**Comment by jingmingtao** [comment]
大哥，如果是数据增强，那可能是那里的问题啊

**Comment by jingmingtao** [comment]
![image](https://user-images.githubusercontent.com/114384977/198203625-6075169b-6384-4d37-98ee-af71e95ff4d8.png)
我将/home/cy/anaconda3/envs/torch/lib/python3.9/site-packages/numpy/core/shape_base.py下边428行将这个(shape)打印出来发现是2，但是代码的意思应该len(shape)是1，这种2是可能什么情况导致的呢，能给点提示吗

**Comment by jingmingtao** [comment]
我估计也是数据增强那部分代码问题，我觉得我的数据应该没啥问题，我检查过好多次了，数据的维度都相同的

**Comment by wuyefeilin** [comment]
你把数据打包一份给我把，还有你的数据增强流程也发我一份。我本地复现一下

**Comment by jingmingtao** [comment]
你能远程我的电脑吗

**Comment by jingmingtao** [comment]
我数据怎么传给你呀

**Comment by jingmingtao** [comment]
![image](https://user-images.githubusercontent.com/114384977/198213905-e46aba47-8e9b-4be4-8eae-c328b9f3c261.png)
数据增强如上所示

**Comment by jingmingtao** [comment]
远程的话：
![image](https://user-images.githubusercontent.com/114384977/198214196-c2541fcc-7429-4d46-acfd-3d28bf370207.png)

**Comment by jingmingtao** [comment]
数据的话，我没传过

**Comment by Bobholamovic** [comment]
@jingmingtao 你好，GitHub issue不是IM软件或者BBS论坛，请不要频繁建立新的issue或是在issue中高频率新建comment，建议每次将需要回复的内容整理后以较完整的形式在一条comment中体现，这将更有利于开发者帮助您定位问题。

**Comment by jingmingtao** [comment]
[train.zip](https://github.com/PaddlePaddle/PaddleSeg/files/9876707/train.zip)
您好这是我的数据的一部分，万分感激，求您帮帮我

**Comment by jingmingtao** [comment]
这个问题我已经定位到了，crop是采用短边裁剪，如果我的图片某一边小于我设置的512，那么就会出现不是512x512的情况，放到set集合中的话，就不会降重，就会导致len(shape)不等于1.解决的办法是，在进行裁剪后，又进行了一步resize，您看这样可以吗，大哥。但是又出现了新的问题：ValueError: The shape of `pred`, `gt` and `trimap` should be equal. but they are (1, 1, 750, 563), (1, 1, 563, 750) and (1, 1, 563, 750)

**Comment by jingmingtao** [comment]
大哥您能说句话嘛，求求您了

**Comment by wuyefeilin** [comment]
看数据shape应该是你对数据的（h,w)进行了相反的操作

**Comment by wuyefeilin** [comment]
> [train.zip](https://github.com/PaddlePaddle/PaddleSeg/files/9876707/train.zip) 您好这是我的数据的一部分，万分感激，求您帮帮我

麻烦确保train.zip能复现你的问题

**Comment by jingmingtao** [comment]
我看代码里边，是这样进行了取反，取的，但是将它反过来，其他图片也会报错
![image](https://user-images.githubusercontent.com/114384977/198461726-84164e79-da46-46b0-99a7-65bb91aeec07.png)

**Comment by jingmingtao** [comment]
这个数据是可以存在问题的，

**Comment by jingmingtao** [comment]
它走到的resize这个地方，但是这不是根本问题，我觉得根本问题还是数据增强部分，因为这是数据传过来的。我现在的数据增强如下图所示，我在训练部分加入了resize来解决shape的问题，而且我发现报错的都是图片的长宽是前小后大的这种，前边大后边小的不会报错。
![image](https://user-images.githubusercontent.com/114384977/198463622-aac658c7-f68b-4521-962a-d4b49463a3e4.png)

**Comment by jingmingtao** [comment]
复现的时候，将所有的做训练，所有的做验证。不要挑出来一部分做验证，这样就存在问题。我也是用的这些在复现我的问题，没问题的，它是存在这些问题的

**Comment by jingmingtao** [comment]
如果图片前大后小的比如（800，600）这样不会报错，如果前小后大比如（600，800）的就会报：ValueError: The shape of pred, gt and trimap should be equal. but they are (1, 1, 750, 563), (1, 1, 563, 750) and (1, 1, 563, 750)类似的这样的错误。

**Comment by jingmingtao** [comment]
初步定位到数据增强的LoadImages导致，因为在ResizeByShort，已经发生变化了

**Comment by jingmingtao** [comment]
您直接看那段代码吧，您比较精通熟悉

**Comment by jingmingtao** [comment]
那段代码也不是，因为到LoadImages已经发生变化了

**Comment by jingmingtao** [comment]
定位到问题了，数据本身的问题，麻烦了

**Comment by wuyefeilin** [comment]
需要确保fg和alpha下的数据的大小相同
如，train/fg/1666713805438307492_1666713801997CGHJFDFADBCEBDACHIHC_original.jpg 这一张的图片和alpha下图片大小不对应(750, 563）， (563, 750)
