### ISSUE TITLE
Matting训练自己的数据集，报形状不同的问题，我检查了训练集的数据，发现shape都相同。求解决。

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleSeg#2662]
报错：
![image](https://user-images.githubusercontent.com/114384977/198168330-65d093a3-d238-476c-acaa-dd89bebe2146.png)

**Comment by jingmingtao** [comment]
我尝试了很多方法去解决，都没有解决掉

**Comment by jingmingtao** [comment]
以前我也遇到这样的情况，我将数据用np.array打印出shape发现有(800,600,3)的，我就用代码给转换成单通道的，就解决了。现在我还是用这种方法，就不能解决了。关键转换后，我去用np.array打印出shape,已经没有(800,600,3)这样三通道的了呀。
我寻思，是不是咱们工程里边在使用np.array读取alpha的时候，可以这样img_open=Image.open(img_path).convert("L")，而不是img_open=Image.open(img_path)。但是，工程中我又没有找到这个读取使用np.array读取alpha的地方，如果想通过这样修改，来避免我的问题的话，我应该修改那里的代码。如果不这样修改，我应该怎么解决这个shape不同的问题。

**Comment by Bobholamovic** [comment]
Duplicate https://github.com/PaddlePaddle/PaddleSeg/issues/2661

**Comment by jingmingtao** [comment]
我在配置文件中加入了    
- type: Padding
      target_size: [512, 512]
又会报错：ValueError: The shape of `pred`, `gt` and `trimap` should be equal. but they are (1, 1, 750, 563), (1, 1, 563, 750) and (1, 1, 563, 750)

**Comment by jingmingtao** [comment]
大哥求求您了，代码怎么修改，我怎么解决
