### ISSUE TITLE
Matting训练自己的数据集，报形状不同的问题，我检查了训练集的数据，发现shape都相同。求解决

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleSeg#2663]
![image](https://user-images.githubusercontent.com/114384977/198168875-a5f2837b-9074-4872-a727-718909771d8e.png)

**Comment by jingmingtao** [comment]
以前我也遇到这样的情况，我将数据用np.array打印出shape发现有(800,600,3)的，我就用代码给转换成单通道的，就解决了。现在我还是用这种方法，就不能解决了。关键转换后，我去用np.array打印出shape,已经没有(800,600,3)这样三通道的了呀

我寻思，是不是咱们工程里边在使用np.array读取alpha的时候，可以这样img_open=Image.open(img_path).convert("L")，而不是img_open=Image.open(img_path)。但是，工程中我又没有找到这个读取使用np.array读取alpha的地方，如果想通过这样修改，来避免我的问题的话，我应该修改那里的代码。如果不这样修改，我应该怎么解决这个shape不同的问题。

**Comment by Bobholamovic** [comment]
Duplicate #2662
