### ISSUE TITLE
LaneSeg评估报错

### ISSUE THREAD

**Issue by peiwenYe** [PaddlePaddle/PaddleSeg#2669]
下载好Tusimple数据集后，按照教程处理好数据格式，运行以下命令报错
`python val.py --config /home/aistudio/PaddleSeg/contrib/LaneSeg/configs/bisenetV2_tusimple_640x368_300k.yml`
报错如下：
![image](https://user-images.githubusercontent.com/37332773/198521652-36a33351-23c2-494a-823e-ce7e85b5b21c.png)

使用的paddle版本： 2.2.2
套件版本： release/2.5
python版本:  3.7

**Comment by shiyutang** [comment]
请问你确定是2.5版本么，这个版本应该不会有这个问题，可以切换到2.5并重新运行

**Comment by Bobholamovic** [comment]
类似的issue：https://github.com/PaddlePaddle/PaddleSeg/issues/2644#event-7680212765

**Comment by peiwenYe** [comment]
> 请问你确定是2.5版本么，这个版本应该不会有这个问题，可以切换到2.5并重新运行

感谢回复，我确定我用的是2.5的版本
![image](https://user-images.githubusercontent.com/37332773/198547744-ef867286-5236-4cce-8154-83de110794ec.png)

**Comment by shiyutang** [comment]
请问是否可以截取这部分代码呢？
<img width="830" alt="image" src="https://user-images.githubusercontent.com/34859558/198548019-f2ebdf92-919c-45b8-8531-28899f7d450d.png">

**Comment by peiwenYe** [comment]
> 请问是否可以截取这部分代码呢？ <img alt="image" width="830" src="https://user-images.githubusercontent.com/34859558/198548019-f2ebdf92-919c-45b8-8531-28899f7d450d.png">

![image](https://user-images.githubusercontent.com/37332773/198548303-b1e17a82-69a8-4700-8f7b-0959afc0e642.png)

**Comment by shiyutang** [comment]
可以尝试使用pdb打断点进入到self.transforms查看__call()__是否存在im参数传入。
[pdb 使用教程](https://docs.python.org/3/library/pdb.html)

**Comment by wuyefeilin** [comment]
pip show paddleseg查看一下是否安装了新的版本

**Comment by peiwenYe** [comment]
> 可以尝试使用pdb打断点进入到self.transforms查看__call()__是否存在im参数传入。 [pdb 使用教程](https://docs.python.org/3/library/pdb.html)

重新安装了PaddleSeg好了。感谢解答！

**Comment by peiwenYe** [comment]
> 重新安装了PaddleSeg好了。感谢解答！

重新安装了PaddleSeg好了。感谢解答！
