### ISSUE TITLE
A new problem in infer.py

### ISSUE THREAD

**Issue by qiyuezhiguang** [PaddlePaddle/PaddleSeg#267]
![image](https://user-images.githubusercontent.com/46549313/82814752-52ebf800-9eca-11ea-8487-23b7ec68e7b9.png)
I used the latest version, 2020.5.24, when the inference it shows the problem.
However, when I use the earlier, it works well

________________________________
支持paddle，支持国产

**Comment by wuyefeilin** [comment]
![image](https://user-images.githubusercontent.com/30919197/82821303-6a30e280-9ed6-11ea-895d-bcf3cc2e0d92.png)
去掉这个就行了
