### ISSUE TITLE
warmup学习率或者自定义学习率设置

### ISSUE THREAD

**Issue by 112wl** [PaddlePaddle/PaddleSeg#2672]
paddleSeg目前不支持warmup学习率或者自定义学习率设置吗？我用paddleseg实现SegNext感觉效果差一点，不知道是不是学习率的问题。

**Comment by shiyutang** [comment]
Paddleseg 支持warmup学习率设置，例如可以设置成下面的配置情况，学习率初始为1.0e-5，在1000个iters后变为0.005：https://github.com/PaddlePaddle/PaddleSeg/blob/develop/configs/pp_liteseg/pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k.yml
<img width="327" alt="image" src="https://user-images.githubusercontent.com/34859558/198914734-b5f40588-2e13-4356-a575-5bf6fddab812.png">
