### ISSUE TITLE
[General Issue] PaddleSeg Custom dataset build error

### ISSUE THREAD

**Issue by sridhar191986** [PaddlePaddle/PaddleSeg#2673]
Dear All,

Could someone help to address the below issue?. I am unable to resolve this issue for last two days.

I am using the datasource and configuration mentioned in https://aistudio.baidu.com/aistudio/projectdetail/4922403?contributionType=1

 1. PaddleSeg version:  2.6.0
 2. PaddlePaddle version: 2.3.2
 3. Operation system: macOS-10.16-x86_64-i386-64bit
 4. Python version: 3.9.12 (main, Apr  5 2022, 01:53:17) [Clang 12.0.0 ]
 5. Paddle compiled with cuda: False
 6. OpenCV: 4.6.0
 7. Additional context: (Add any other context about the problem)

 ---------------Config Information---------------
batch_size: 4
iters: 10000
loss:
  coef:
  - 1
  types:
  - ignore_index: 255
    type: CrossEntropyLoss
lr_scheduler:
  end_lr: 0
  learning_rate: 0.01
  power: 0.9
  type: PolynomialDecay
model:
  num_classes: 2
  pretrained: null
  type: UNet
  use_deconv: false
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 4.0e-05
train_dataset:
  dataset_root: drive/MyDrive/dataset/custom_dataset1
  mode: train
  num_classes: 2
  train_path: drive/MyDrive/dataset/custom_dataset1/train.txt
  transforms:
  - max_scale_factor: 2.0
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - crop_size:
    - 1024
    - 512
    type: RandomPaddingCrop
  - type: RandomHorizontalFlip
  - brightness_range: 0.4
    contrast_range: 0.4
    saturation_range: 0.4
    type: RandomDistort
  - type: Normalize
  type: Dataset
val_dataset:
  dataset_root: drive/MyDrive/dataset/custom_dataset1
  mode: val
  num_classes: 2
  transforms:
  - type: Normalize
  type: Dataset
  val_path: drive/MyDrive/dataset/custom_dataset1/val.txt
------------------------------------------------

Findings: highlighted code is throwing the error
https://github.com/PaddlePaddle/Paddle/blob/3cc6ae69ed93388b2648bcc819d593130dede752/python/paddle/nn/functional/loss.py#L1444

if _non_static_mode():
        if soft_label == False:
            valid_label = paddle.cast(
                label != ignore_index, dtype=label.dtype) * label
            label_min = paddle.min(valid_label)
            label_max = paddle.max(valid_label)
            if label_min < 0:
                raise ValueError("Target {} is out of lower bound.".format(
                    label_min.item()))
            if label_max >= input.shape[axis]:
                print('label_max'+str(label_max))
                print('input.shape[axis]'+str(input.shape[axis]))
                **_raise ValueError("Target {} is out of upper bound.".format(
                    label_max.item()))_**

Error: 

/Users/user1/opt/anaconda3/lib/python3.9/site-packages/hdfs/config.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import load_source
/Users/user1/opt/anaconda3/lib/python3.9/site-packages/paddle/nn/layer/norm.py:653: UserWarning: When training, we now always track global mean and variance.
  warnings.warn(
SSK
2
SSL
Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [255])
label_maxTensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [170])
input.shape[axis]2
Traceback (most recent call last):
  File "/Users/Shared/Previously Relocated Items/Security/sourcecode/python/object detection/drive/MyDrive/PaddleSeg/train.py", line 230, in <module>
    main(args)
  File "/Users/Shared/Previously Relocated Items/Security/sourcecode/python/object detection/drive/MyDrive/PaddleSeg/train.py", line 206, in main
    train(
  File "/Users/Shared/Previously Relocated Items/Security/sourcecode/python/object detection/drive/MyDrive/PaddleSeg/paddleseg/core/train.py", line 212, in train
    loss_list = loss_computation(
  File "/Users/Shared/Previously Relocated Items/Security/sourcecode/python/object detection/drive/MyDrive/PaddleSeg/paddleseg/core/train.py", line 55, in loss_computation
    loss_list.append(coef_i * loss_i(logits, labels))
  File "/Users/user1/opt/anaconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/Users/user1/opt/anaconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/Users/Shared/Previously Relocated Items/Security/sourcecode/python/object detection/drive/MyDrive/PaddleSeg/paddleseg/models/losses/cross_entropy_loss.py", line 87, in forward
    loss = F.cross_entropy(
  File "/Users/user1/opt/anaconda3/lib/python3.9/site-packages/paddle/nn/functional/loss.py", line 1724, in cross_entropy
    raise ValueError("Target {} is out of upper bound.".format(
ValueError: Target 170 is out of upper bound.

**Comment by haoyuying** [comment]
I can not open this link: https://aistudio.baidu.com/aistudio/projectdetail/4922403?contributionType=1
From the information,  you may make mistakes of " F.cross_entropy", maybe the label is illegal, you may print the prediction and the label and find what's wrong.  For more details of " F.cross_entropy", you may find in this link:https://www.paddlepaddle.org.cn/documentation/docs/en/2.2/api/paddle/nn/functional/cross_entropy_en.html#cross-entropy

**Comment by sridhar191986** [comment]
@haoyuying , thanks for looking into the issue. I am new to PaddlePaddle, I may need your extended support on this.

Apologise, the previous link was removed. Please check this one https://aistudio.baidu.com/aistudio/projectdetail/2028968?channelType=0&channel=0

I am unable to run the above dataset .

Let me explain, how i prepared the dataset.

Step 1: I prepared the dataset using EISEG :https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.6/EISeg
Step 2: Then i moved the masked picture generated by EISEG to label folder.
Step 3:  Generated train.txt and val.txt
[custom_dataset2.zip](https://github.com/PaddlePaddle/PaddleSeg/files/9898155/custom_dataset2.zip)

Step 4: executed this code: !python train.py \
       --config configs/unet/unet_cityscapes_1024x512_160k.yml \
       --do_eval \
       --use_vdl \
       --save_interval 500 \
       --save_dir output

I have attached the dataset that I am using locally.

I managed to print the label and prediction value. Please check the below

**label_max** = Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [204])
 input.shape = [4, 512, 512, 2] ,input.shape[axis]= 2

Below is the condition failing

  **if label_max >= input.shape[axis]:**
  raise ValueError("Target {} is out of upper bound.".format(
                    label_max.item()))

I am not sure why the label is returning 204

raise ValueError("Target {} is out of upper bound.".format(
ValueError: Target 204 is out of upper bound.

thanks in advance

**Comment by haoyuying** [comment]
if your label has 204 classes, the max value can be 204, else, it will be wrong,  you must use the gray scale images rather than presedo images as the label.

**Comment by sridhar191986** [comment]
@haoyuying , Awesome. it worked, thanks for your time.
