### ISSUE TITLE
Matting训练过程中断

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleSeg#2674]
训练过程中出现如下错误：
![image](https://user-images.githubusercontent.com/114384977/198909737-e90f5cdd-8063-4c29-aad8-f83bd724add2.png)

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：2.6
 2. PaddlePaddle版本：2.3.2
 3. 操作系统信息：linux
 4. Python版本号：3.9
 5. CUDA/cuDNN版本：cuda11.8 cudnn8.6

**Comment by wuyefeilin** [comment]
麻烦提供一下具体的运行命令和报错信息。

**Comment by jingmingtao** [comment]
这个错不是一开始就报了，而是在运行了13w迭代iter后出现的。
运行命令：export CUDA_VISIBLE_DEVICES=0
python tools/train.py --config configs/quick_start/modnet-mobilenetv2.yml --do_eval --use_vdl --save_interval 100 --num_workers 5 --save_dir output_3w
报错如下：
![image](https://user-images.githubusercontent.com/114384977/198916563-524a2446-09b1-425a-be8e-459f622c5e8c.png)
FatalError: `Segmentation fault` is detected by the operating system.   [TimeInfo: *** Aborted at 16

**Comment by wuyefeilin** [comment]
目前看不出具体哪里出了问题，没有其它报错信息了吗？ 

另外这个能稳定复现吗？
