### ISSUE TITLE
[Feature Request] Brightness and Contrast Adjustment for EISeg

### ISSUE THREAD

**Issue by bigchou** [PaddlePaddle/PaddleSeg#2675]
Thanks for the excellent work. I have some images to be annotated using EISeg but they are difficult to recognize the entire contour due to extreme lighting condition. If the image is too dark, I expect to annotate it under brighter lighting (like this [feature](https://github.com/wkentaro/labelme/blob/734ff14b7ddb799ba6a63d198233152d712c40a2/labelme/widgets/brightness_contrast_dialog.py#L33) from LabelMe).  Is it possible to add the UI to control the brightness and contrast of the image? It may be helpful for both human annotators and segmentation model predictions given the appropriate lighting.

**Comment by haoyuying** [comment]
this feature we will be considered in the next version, thank you.
