### ISSUE TITLE
[Bug]DDRNet模型部署问题

### ISSUE THREAD

**Issue by OpenCDR** [PaddlePaddle/PaddleSeg#2679]
PaddleSeg版本：PaddleSeg release/2.6 
paddleinference版本：4596b9a22540fb0ea5d369c3c804544de61d03d0
操作系统：Win10 20H2
CUDA 版本 11.6
CUDNN版本 8.4.1
TenserRT版本： 8.4.0
使用动态shape导出ddrnet模型后在该电脑上推理出现以下错误：
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
ExternalError: CUDA error(719), unspecified launch failure.
  [Hint: Please search for the error code(719) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at ..\paddle\phi\backends\gpu\gpu_context.cc:435)

请问这种情况应该如何处理？相同情况下PPlite模型推理没有问题

**Comment by juncaipeng** [comment]
你执行代码是什么？
我在linux上执行如下导出、预测代码，是正确的，没有报错。
```
python tools/export.py --config configs/ddrnet/ddrnet23_cityscapes_1024x1024_120k.yml --save_dir output/tmp/ddrnet
python deploy/python/infer.py --config output/tmp/ddrnet/deploy.yaml --image_path tmp/cityscapes_demo.png --save_dir output/tmp
```

**Comment by OpenCDR** [comment]
导出代码是`python tools/export.py --config configs/ddrnet/ddrnet23_cityscapes_1024x1024_120k.yml --save_dir output/tmp/ddrnet`
动态shape收集的代码是`python ../python/collect_dynamic_shape.py --config ddrnet/deploy.yaml --image_path images --dynamic_shape_path ./dynamic_shape.pbtxt`
在使用的是CPP的部署方式而非Python。
CPP的代码就是例程里提供的。

**Comment by juncaipeng** [comment]
这个估计是paddle inference预测库的问题，建议先换个其他的预测库试试。

**Comment by OpenCDR** [comment]
好的谢谢您，我们现在只能用CPP的库。

**Comment by juncaipeng** [comment]
@OpenCDR 是换个其他版本的paddle inference cpp预测库。 我们会跟进下该问题。
