### ISSUE TITLE
eiseg标注问题

### ISSUE THREAD

**Issue by vongolas** [PaddlePaddle/PaddleSeg#2680]
1. PaddleSeg版本：PaddleSeg release/2.6
 2. PaddlePaddle版本：PaddlePaddle 2.3.0
 3. 操作系统信息：Windows 10
 4. Python版本号：Python 3.9
 5. CUDA/cuDNN版本：CUDA11.6/cuDNN 8.4.0
 6. 其他内容: 标注无法选择边界，或者会选择一整张图，用的模型是static_hrnet18_ocr64_cocolvis
![屏幕截图 2022-11-01 095027](https://user-images.githubusercontent.com/117132628/199142072-ee23951a-ec6c-4803-ab13-2e30fa12407d.png)
![屏幕截图 2022-11-01 095053](https://user-images.githubusercontent.com/117132628/199142081-c8e70774-0ed8-4416-9de9-4a40e3f5526b.png)

**Comment by haoyuying** [comment]
您好，把您的测试图片及想要标注的物体给我们，目前您提供的信息不足以复现该问题，目前可以确定的是您加载静态图模型的log打印是不对的，可排查下paddle是否能过正确加载静态图，目前推断的问题上paddle，cuda和cudnn不匹配导致模型加载出问题导致的。
![image](https://user-images.githubusercontent.com/35907364/199156191-8c1842c0-8a75-439c-8d1a-7bc15bd66077.png)

**Comment by vongolas** [comment]
您好，图片如下
想要标注图上的病斑区域和整个叶片的区域

![叶斑](https://user-images.githubusercontent.com/117132628/199183001-4709351c-27d0-4468-b1f6-461bc7820c08.png)

**Comment by vongolas** [comment]
加载图片后有libpng warning: iCCP: known incorrect sRGB profile

**Comment by haoyuying** [comment]
您好，目前初步判定是cuda版本过高，paddle inference预测有问题导致的，建议使用cuda10.2，cudnn7.6.5的版本比较稳定。

**Comment by vongolas** [comment]
好的，感谢

**Comment by INTOUCHABLE-VS** [comment]
1.PaddleSeg版本：PaddleSeg release/2.8
2.PaddlePaddle版本：PaddlePaddle 2.5.0
3.操作系统信息：Windows 10
4.Python版本号：Python 3.8.17
5.CUDA/cuDNN版本：CUDA11.2/cuDNN 8.2
6.其他内容: 标注异常无法大致掩膜目标，用的模型是static_hrnet18s_ocr48_aluminium
![1689751651459](https://github.com/PaddlePaddle/PaddleSeg/assets/51685497/927f0f0a-cbf8-4fa3-bbc9-b98209da94ac)
![1689751631658](https://github.com/PaddlePaddle/PaddleSeg/assets/51685497/5b672fc0-0b84-4548-8046-b8f2a1998d43)
![1689737673990](https://github.com/PaddlePaddle/PaddleSeg/assets/51685497/87db3c3c-0031-4e92-a635-d5b4d4f26b8c)
