### ISSUE TITLE
参数问题

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/PaddleSeg#2681]
训练过程的日志保存train.log，打开那一个参数进行

**Comment by juncaipeng** [comment]
```nohup python -m paddle.distributed.launch --log_dir ./log_dir tools/train.py  xxxxx    2>&1 >  ./log_dir/log_train.txt &```
可以后台执行训练，将输出log保存到脚本 ./log_dir/log_train.txt

**Comment by chen-del** [comment]
好的谢谢
