### ISSUE TITLE
loss疑问

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/PaddleSeg#2688]
非常抱歉，问到了这个问题！
对于OhemCrossEntropyLoss它的min_kept是如何进行计算的，因为我看到他的实现的方式不一样，具体在训练的环境中他具体设置的
是不是(batch_szie*input_w*input_h)//16 这种计算方式，确定损失中要保留的最小数字

**Comment by wuyefeilin** [comment]
min_kept 根据情况进行设置哈，没有统一的一个设置标准。 取输入像素数的1/16是选择之一

**Comment by chen-del** [comment]
嗯好的，非常感谢，我还想问下取像素输入数是不是按照4的倍数或者是2的倍数去进行选的，例如1/16,1/24，1/32,1/8等等

**Comment by wuyefeilin** [comment]
这个不一定哈
