### ISSUE TITLE
[Bug]paddle._C_ops.argsort ValueError while training hrnet_w18

### ISSUE THREAD

**Issue by clementzhao** [PaddlePaddle/PaddleSeg#2691]
ubuntu 22.04因为gcc 11.2问题，安装过paddle 2.3.2及以下不能运行，能运行的只有2.4.0rc0和nightly build verison，均有下面报错。
PaddleSeg 2.6版本
lovasz_loss.py调用函数paddle._C_ops.argsort(errors, 'axis', 0',descending', True)，在python调用paddle的argsort这里第二个参数应该是0，通过c去调用怎么就认不对呢？训练时候报错如下：

------------Environment Information-------------
platform: Linux-5.13.0-52-generic-x86_64-with-glibc2.34
Python: 3.9.7 (default, Jun 22 2022, 20:11:26) [GCC 11.2.0]
Paddle compiled with cuda: True
NVCC: Build cuda_11.5.r11.5/compiler.30672275_0
cudnn: 8.3
GPUs used: 1
CUDA_VISIBLE_DEVICES: 0
GPU: ['GPU 0: NVIDIA GeForce']
GCC: gcc (Ubuntu 11.2.0-7ubuntu2) 11.2.0
PaddleSeg: 2.6.0
PaddlePaddle: 0.0.0
OpenCV: 4.5.5
------------------------------------------------
2022-11-02 14:50:22 [INFO]	
---------------Config Information---------------
batch_size: 4
iters: 80000
loss:
  coef:
  - 1
  types:
  - coef:
    - 0.8
    - 0.2
    losses:
    - type: CrossEntropyLoss
    - type: LovaszSoftmaxLoss
    type: MixedLoss
lr_scheduler:
  end_lr: 0
  learning_rate: 0.01
  power: 0.9
  type: PolynomialDecay
model:
  backbone:
    align_corners: false
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
    type: HRNet_W18
  backbone_indices:
  - -1
  num_classes: 5
  pretrained: null
  type: FCN
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 0.0005
train_dataset:
  dataset_root: escalator/data
  mode: train
  num_classes: 5
  train_path: escalator/data/train.txt
  transforms:
  - max_scale_factor: 2.0
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - type: RandomRotation
  - crop_size:
    - 1024
    - 512
    type: RandomPaddingCrop
  - type: RandomVerticalFlip
  - type: RandomBlur
  - brightness_range: 0.4
    contrast_range: 0.4
    saturation_range: 0.4
    type: RandomDistort
  - type: Normalize
  type: Dataset
val_dataset:
  dataset_root: escalator/data
  mode: val
  num_classes: 5
  transforms:
  - type: Normalize
  type: Dataset
  val_path: escalator/data/val.txt
------------------------------------------------
W1102 14:50:22.885181 994748 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.5, Runtime API Version: 11.5
W1102 14:50:22.885196 994748 gpu_resources.cc:91] device: 0, cuDNN Version: 8.3.
2022-11-02 14:50:23 [INFO]	Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
2022-11-02 14:50:24 [INFO]	There are 1525/1525 variables loaded into HRNet.
/usr/local/lib/python3.9/dist-packages/paddle/nn/layer/norm.py:713: UserWarning: When training, we now always track global mean and variance.
  warnings.warn(
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "/home/robustel/src/PaddleSeg-Escalator/train.py", line 230, in <module>
    main(args)
  File "/home/robustel/src/PaddleSeg-Escalator/train.py", line 206, in main
    train(
  File "/home/robustel/src/PaddleSeg-Escalator/paddleseg/core/train.py", line 207, in train
    loss_list = loss_computation(
  File "/home/robustel/src/PaddleSeg-Escalator/paddleseg/core/train.py", line 48, in loss_computation
    mixed_loss_list = loss_i(logits, labels)
  File "/usr/local/lib/python3.9/dist-packages/paddle/fluid/dygraph/layers.py", line 994, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/robustel/src/PaddleSeg-Escalator/paddleseg/models/losses/mixed_loss.py", line 55, in forward
    output = loss(logits, labels)
  File "/usr/local/lib/python3.9/dist-packages/paddle/fluid/dygraph/layers.py", line 994, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/robustel/src/PaddleSeg-Escalator/paddleseg/models/losses/lovasz_loss.py", line 53, in forward
    loss = lovasz_softmax_flat(vprobas, vlabels, classes=self.classes)
  File "/home/robustel/src/PaddleSeg-Escalator/paddleseg/models/losses/lovasz_loss.py", line 184, in lovasz_softmax_flat
    errors_sorted, perm = paddle._C_ops.argsort(errors, 'axis', 0,
ValueError: (InvalidArgument) argsort(): argument (position 2) must be int, but got str (at /paddle/paddle/fluid/pybind/op_function_common.cc:148)

LAUNCH INFO 2022-11-02 14:50:28,626 Pod failed
[2022-11-02 14:50:28,626] [    INFO] controller.py:109 - Pod failed
LAUNCH ERROR 2022-11-02 14:50:28,627 Container failed !!!
Container rank 0 status failed cmd ['/usr/bin/python', '-u', 'train.py', '--config', 'escalator/configs/fcn_hrnetw18_custom_1024x512_80k.yml', '--do_eval', '--use_vdl', '--save_interval', '100', '--save_dir', 'escalator/out/train/fcn_hrnetw18'] code 1 log log/workerlog.0 
env {'SHELL': '/bin/bash', 'NVDS_ENABLE_COMPONENT_LATENCY_MEASUREMENT': '1', 'PWD': '/home/robustel/src/PaddleSeg-Escalator', 'LOGNAME': 'robustel', 'XDG_SESSION_TYPE': 'tty', 'TZ': 'Asia/Shanghai', 'MOTD_SHOWN': 'pam', 'HOME': '/home/robustel', 'LANG': 'C.UTF-8', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'CUDA_VER': '11.5', 'SSH_CONNECTION': '172.16.13.41 14386 172.16.13.27 22', 'CUDA_VISIBLE_DEVICES': '0', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'XDG_SESSION_CLASS': 'user', 'TERM': 'xterm', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'USER': 'robustel', 'DISPLAY': 'localhost:11.0', 'SHLVL': '1', 'XDG_SESSION_ID': '901', 'LD_LIBRARY_PATH': '/usr/lib/x86_64-linux-gnu:/usr/local/cuda-11.5/lib64:/home/robustel/TensorRT-8.2.1.8/lib:/usr/local/lib/gstreamer-1.0', 'XDG_RUNTIME_DIR': '/run/user/1000', 'SSH_CLIENT': '172.16.13.41 14386 22', 'LC_TIME': 'C.UTF-8', 'CUDA_HOME': '/usr/local/cuda', 'XDG_DATA_DIRS': '/usr/local/share:/usr/share:/var/lib/snapd/desktop', 'PATH': '/home/robustel/.local/bin:/usr/local/cuda-11.5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin', 'NVDS_ENABLE_LATENCY_MEASUREMENT': '1', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'SSH_TTY': '/dev/pts/2', 'OLDPWD': '/home/robustel/src/PaddleSeg-Escalator/escalator', '_': '/usr/bin/python', 'CUSTOM_DEVICE_ROOT': '', 'OMP_NUM_THREADS': '1', 'POD_NAME': 'nfktnd', 'PADDLE_MASTER': '127.0.1.1:54058', 'PADDLE_GLOBAL_SIZE': '1', 'PADDLE_LOCAL_SIZE': '1', 'PADDLE_GLOBAL_RANK': '0', 'PADDLE_LOCAL_RANK': '0', 'PADDLE_NNODES': '1', 'PADDLE_TRAINER_ENDPOINTS': '127.0.1.1:54059', 'PADDLE_CURRENT_ENDPOINT': '127.0.1.1:54059', 'PADDLE_TRAINER_ID': '0', 'PADDLE_TRAINERS_NUM': '1', 'PADDLE_RANK_IN_NODE': '0', 'FLAGS_selected_gpus': '0'}
[2022-11-02 14:50:28,627] [   ERROR] controller.py:110 - Container failed !!!
Container rank 0 status failed cmd ['/usr/bin/python', '-u', 'train.py', '--config', 'escalator/configs/fcn_hrnetw18_custom_1024x512_80k.yml', '--do_eval', '--use_vdl', '--save_interval', '100', '--save_dir', 'escalator/out/train/fcn_hrnetw18'] code 1 log log/workerlog.0 
env {'SHELL': '/bin/bash', 'NVDS_ENABLE_COMPONENT_LATENCY_MEASUREMENT': '1', 'PWD': '/home/robustel/src/PaddleSeg-Escalator', 'LOGNAME': 'robustel', 'XDG_SESSION_TYPE': 'tty', 'TZ': 'Asia/Shanghai', 'MOTD_SHOWN': 'pam', 'HOME': '/home/robustel', 'LANG': 'C.UTF-8', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'CUDA_VER': '11.5', 'SSH_CONNECTION': '172.16.13.41 14386 172.16.13.27 22', 'CUDA_VISIBLE_DEVICES': '0', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'XDG_SESSION_CLASS': 'user', 'TERM': 'xterm', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'USER': 'robustel', 'DISPLAY': 'localhost:11.0', 'SHLVL': '1', 'XDG_SESSION_ID': '901', 'LD_LIBRARY_PATH': '/usr/lib/x86_64-linux-gnu:/usr/local/cuda-11.5/lib64:/home/robustel/TensorRT-8.2.1.8/lib:/usr/local/lib/gstreamer-1.0', 'XDG_RUNTIME_DIR': '/run/user/1000', 'SSH_CLIENT': '172.16.13.41 14386 22', 'LC_TIME': 'C.UTF-8', 'CUDA_HOME': '/usr/local/cuda', 'XDG_DATA_DIRS': '/usr/local/share:/usr/share:/var/lib/snapd/desktop', 'PATH': '/home/robustel/.local/bin:/usr/local/cuda-11.5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin', 'NVDS_ENABLE_LATENCY_MEASUREMENT': '1', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'SSH_TTY': '/dev/pts/2', 'OLDPWD': '/home/robustel/src/PaddleSeg-Escalator/escalator', '_': '/usr/bin/python', 'CUSTOM_DEVICE_ROOT': '', 'OMP_NUM_THREADS': '1', 'POD_NAME': 'nfktnd', 'PADDLE_MASTER': '127.0.1.1:54058', 'PADDLE_GLOBAL_SIZE': '1', 'PADDLE_LOCAL_SIZE': '1', 'PADDLE_GLOBAL_RANK': '0', 'PADDLE_LOCAL_RANK': '0', 'PADDLE_NNODES': '1', 'PADDLE_TRAINER_ENDPOINTS': '127.0.1.1:54059', 'PADDLE_CURRENT_ENDPOINT': '127.0.1.1:54059', 'PADDLE_TRAINER_ID': '0', 'PADDLE_TRAINERS_NUM': '1', 'PADDLE_RANK_IN_NODE': '0', 'FLAGS_selected_gpus': '0'}
LAUNCH INFO 2022-11-02 14:50:28,627 ------------------------- ERROR LOG DETAIL -------------------------
[2022-11-02 14:50:28,627] [    INFO] controller.py:111 - ------------------------- ERROR LOG DETAIL -------------------------
.0005
train_dataset:
  dataset_root: escalator/data
  mode: train
  num_classes: 5
  train_path: escalator/data/train.txt
  transforms:
  - max_scale_factor: 2.0
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - type: RandomRotation
  - crop_size:
    - 1024
    - 512
    type: RandomPaddingCrop
  - type: RandomVerticalFlip
  - type: RandomBlur
  - brightness_range: 0.4
    contrast_range: 0.4
    saturation_range: 0.4
    type: RandomDistort
  - type: Normalize
  type: Dataset
val_dataset:
  dataset_root: escalator/data
  mode: val
  num_classes: 5
  transforms:
  - type: Normalize
  type: Dataset
  val_path: escalator/data/val.txt
------------------------------------------------
W1102 14:50:22.885181 994748 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.5, Runtime API Version: 11.5
W1102 14:50:22.885196 994748 gpu_resources.cc:91] device: 0, cuDNN Version: 8.3.
2022-11-02 14:50:23 [INFO]	Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
2022-11-02 14:50:24 [INFO]	There are 1525/1525 variables loaded into HRNet.
/usr/local/lib/python3.9/dist-packages/paddle/nn/layer/norm.py:713: UserWarning: When training, we now always track global mean and variance.
  warnings.warn(
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "/home/robustel/src/PaddleSeg-Escalator/train.py", line 230, in <module>
    main(args)
  File "/home/robustel/src/PaddleSeg-Escalator/train.py", line 206, in main
    train(
  File "/home/robustel/src/PaddleSeg-Escalator/paddleseg/core/train.py", line 207, in train
    loss_list = loss_computation(
  File "/home/robustel/src/PaddleSeg-Escalator/paddleseg/core/train.py", line 48, in loss_computation
    mixed_loss_list = loss_i(logits, labels)
  File "/usr/local/lib/python3.9/dist-packages/paddle/fluid/dygraph/layers.py", line 994, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/robustel/src/PaddleSeg-Escalator/paddleseg/models/losses/mixed_loss.py", line 55, in forward
    output = loss(logits, labels)
  File "/usr/local/lib/python3.9/dist-packages/paddle/fluid/dygraph/layers.py", line 994, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/robustel/src/PaddleSeg-Escalator/paddleseg/models/losses/lovasz_loss.py", line 53, in forward
    loss = lovasz_softmax_flat(vprobas, vlabels, classes=self.classes)
  File "/home/robustel/src/PaddleSeg-Escalator/paddleseg/models/losses/lovasz_loss.py", line 184, in lovasz_softmax_flat
    errors_sorted, perm = paddle._C_ops.argsort(errors, 'axis', 0,
**ValueError: (InvalidArgument) argsort(): argument (position 2) must be int, but got str (at /paddle/paddle/fluid/pybind/op_function_common.cc:148)**

**Comment by wuyefeilin** [comment]
应该是2.4版本做了调整，目前paddle2.4稳定版还未发布，seg暂未做配套升级, 你可以尝试以下两种方法自行进行修改
1、 paddle._C_ops.argsort(errors, 0, True)
2、 paddle.argsort(errors, 0, True)

**Comment by clementzhao** [comment]
> 应该是2.4版本做了调整，目前paddle2.4稳定版还未发布，seg暂未做配套升级, 你可以尝试以下两种方法自行进行修改 1、 paddle._C_ops.argsort(errors, 0, True) 2、 paddle.argsort(errors, 0, True)

paddle._C_ops.argsort(errors, 0, True)可以，paddle.argsort(errors, 0, True)不行，因为有2个返回值。
