### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by trefoil0219** [PaddlePaddle/PaddleSeg#2692]
使用docker run --name dev --runtime=nvidia -v $PWD:/mnt -p 8888:8888 -it paddlecloud/paddleseg:2.5-gpu-cuda10.2-cudnn7-03e7ce  /bin/bash  命令拉取的docker镜像，根据教程 安装了CuPY 并使用 GPU 进行加速。
在执行  python tools/prepare_lung_coronavirus.py命令时，报错
![%$)FV9N_YO)7277N6%S%}N5](https://user-images.githubusercontent.com/55016894/199431324-ddd756c7-2d8d-4f2c-97f7-e30329b0374c.png)

**Comment by shiyutang** [comment]
1. 建议排查是否下载了最新develop版本的medicalseg；
2. 如果是，可以先不使用Cupy进行加速，即保持和[此处](https://github.com/PaddlePaddle/PaddleSeg/blob/develop/contrib/MedicalSeg/tools/preprocess_globals.yml)设置一致，并且我也会同步在本地看是否复现同样问题
