### ISSUE TITLE
3D slicer 安装paddle报错

### ISSUE THREAD

**Issue by Spinexiang** [PaddlePaddle/PaddleSeg#2697]
![1667468327943](https://user-images.githubusercontent.com/92571567/199689516-ad827130-0536-4480-99cf-f998d5a95f12.png)

**Comment by Spinexiang** [comment]
import sys
import os
sys.executable # 'D:/Slicer 5.0.3/bin/PythonSlicer.exe'

os.system(f"'{sys.executable}' -m python -m pip install paddlepaddle-gpu==2.3.2.post116 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html")

**Comment by shiyutang** [comment]
这个是中文解码错误导致，建议不要在中文目录下安装slicer进行解决。

**Comment by Spinexiang** [comment]
> 这个是中文解码错误导致，建议不要在中文目录下安装slicer进行解决。
D:/Slicer 5.0.3  我的 slicer 安装目录如下

**Comment by shiyutang** [comment]
可以查看一下paddle是否安装成功

**Comment by shiyutang** [comment]
如果没有安装成功，使用文件管理器打开'D:/Slicer 5.0.3/bin/PythonSlicer.exe'， 在里面根据自己的cuda版本安装paddlepaddle，安装说明：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html

**Comment by Spinexiang** [comment]
我使用了cmd命令运行

PythonSlicer.exe -m pip install paddlepaddle-gpu==2.3.1.post111 -f  https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html

完成安装，谢谢支持
