### ISSUE TITLE
[General Issue] Not necessary import of paddle.dataset.common in EISeg classes

### ISSUE THREAD

**Issue by SalvoPisciotta** [PaddlePaddle/PaddleSeg#2699]
1. PaddleSeg version: 2.6.0
 2. PaddlePaddle version: 2.3.2
 3. Operation system: Linux
 4. Python version: Python 3.9.13
 
Hi! I'm using PaddleSeg EISeg library methods and since I'm working on a docker container with no write permission I have permission errors in building the contatiner due to the import of paddle.dataset.common library.

The import makes a the call of the method makedirs() and this cause a PermissionError, as reported in the attached photo. There is a way to avoid these imports, since they are not useful for my task? (it happen the same with the paddle.vision import)

![unnamed](https://user-images.githubusercontent.com/55098062/199754251-163545e3-5595-41a4-82f0-a36ba379cf0f.png)

**Comment by linhandev** [comment]
Hi @SalvoPisciotta

Just to be sure, about your use case, is it correct to say that you are only trying to use some components inside EISeg (like the inference part only maybe) and are not trying to start EISeg GUI inside a docker?

From my observation this error is thrown when importing the paddlepaddle package. This package is necessary for the deep learning related part of EISeg to run. 

I'm not really familiar with docker. But when you say you don't have write permission, does this mean you don't have write permission globally, ie. can't write to anywhere inside the docker or you are not able to write to this particular folder /root/.cache.

If it's the latter I think this problem can be avoided by changing the $HOME folder temporarily to somewhere you can write to. I'm guessing the solution should be something similar to 

```shell
HOME=/path/you/can/write/to python your_script.py
```
