### ISSUE TITLE
[Feature Request] 通用场景的Matting模型

### ISSUE THREAD

**Issue by bittergourd1224** [PaddlePaddle/PaddleSeg#2702]
Welcome to propose a new feature! To help us understand your great feature, please provide following information:
1. A clear and concise description of the proposed feature.
2. Tell us why the feature is useful. 
3. If possible, please show related codes .

---

欢迎提出一个新功能需求，为了帮助我们更好理解您的需求，辛苦提供下面信息：
1. 清晰简洁的语言提出新功能需求。
希望提供一个通用场景的Matting模型让大家试用

2. 请描述这个需求的必要性。
目前提供的可下载的都是人像抠图模型，但是自动抠图的场景远远不止人像，还包括了各种场景各种物体。也有很多方向在研究通用场景的抠图。希望提供一个前沿的优秀的模型可以试用，也方便大家有一个benchmark，再确认是否需要自己准备数据集自己训练。

**Comment by wuyefeilin** [comment]
你好，我们提供了Composition-1k和Distinctions-646训练的PP-Matting模型。是通用的抠图模型。 如果你有更多的数据进行微调训练，鲁棒性会更好。https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.6/Matting/configs/ppmatting

**Comment by bittergourd1224** [comment]
原来2.6版本已经包含啦，非常感谢~
