### ISSUE TITLE
关于PPLite的测速问题

### ISSUE THREAD

**Issue by xiaodaomingye459** [PaddlePaddle/PaddleSeg#2703]
环境：
platform: Linux-5.4.0-59-generic-x86_64-with-debian-buster-sid
Python: 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59) [GCC 7.5.0]
Paddle compiled with cuda: True
NVCC: Cuda compilation tools, release 10.2, V10.2.89
cudnn: 8.0
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: NVIDIA GeForce']
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PaddleSeg: 2.5.0
PaddlePaddle: 2.2.2
OpenCV: 4.5.5

我在测速时遇到如下问题：
![image](https://user-images.githubusercontent.com/83204995/199968982-eb9caf75-bd92-44e5-8493-c60a23a07c1c.png)
请问是什么原因，怎么解决呢？

**Comment by juncaipeng** [comment]
这应该是随机的，多测试几次试下。

此外可以修改这个误差阈值，调大一点。
![image](https://user-images.githubusercontent.com/52520497/200214193-58bc39de-520d-4107-9ecd-cd1cc2353102.png)

**Comment by xiaodaomingye459** [comment]
感谢，PP_Lite已经可以测速了
但是对于RTformer,使用同样方法测速时遇到如下报错：
![image](https://user-images.githubusercontent.com/83204995/200217293-885a8a0e-5d05-423e-9f2e-7013d92e7833.png)
另外，关于测速是只有这一种方法吗

**Comment by juncaipeng** [comment]
rtformer暂时不支持转onnx进行测速。

**Comment by xiaodaomingye459** [comment]
那有没有普通导出模型进行测速的办法，我没有找到对应教程，
只看到这一种转onnx进行测速的说明。

**Comment by juncaipeng** [comment]
普通测试是使用 https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/deploy/python/infer_benchmark.py 进行测试，但是一般没有转onnx速度快。
