### ISSUE TITLE
使用Paddle-Lite在ARM架构平台部署PaddleSeg

### ISSUE THREAD

**Issue by fanxiaochen456** [PaddlePaddle/PaddleSeg#2704]
您好，请问有关于Paddle-Lite在ARM平台部署PaddleSeg的相关文档吗？

**Comment by juncaipeng** [comment]
paddlelite的文档：https://www.paddlepaddle.org.cn/lite

从PaddleSeg中导出预测模型后，建议参考paddellite的使用文档，和其他模型一样进行部署。

**Comment by fanxiaochen456** [comment]
@juncaipeng 您好，当我运行Paddle-Lite-Demo里的human_segmentation的demo时出现了以下错误：
![147422561322895156](https://user-images.githubusercontent.com/101849755/200288790-3c51f48f-25f7-493b-a4d8-47ccf95a96e1.png)
请问这是什么原因呢？
