### ISSUE TITLE
关于RTformer

### ISSUE THREAD

**Issue by xiaodaomingye459** [PaddlePaddle/PaddleSeg#2705]
环境如下：
![image](https://user-images.githubusercontent.com/83204995/200213914-4642d16a-3e1a-4e4c-aebc-3eb7998ef9f9.png)

我在进行训练时，只是将batch_size调大就会显示如下报错，显存明显还剩许多，而且报错原因也与显存无关，非常奇怪！
![image](https://user-images.githubusercontent.com/83204995/200214093-870479a4-d48a-4fb0-bc9b-268d6ee320f0.png)
把batch_size还原则可以正常跑起来
![image](https://user-images.githubusercontent.com/83204995/200214194-c44e5682-5894-4328-9764-1d7a3837596b.png)

**Comment by juncaipeng** [comment]
bs设置为多少啊？ 我调整bs后可以正常训练。

**Comment by xiaodaomingye459** [comment]
只是将原来bz=3设置为6

**Comment by juncaipeng** [comment]
可是试试其他bs。
