### ISSUE TITLE
人像抠图替换不同的backbone

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleSeg#2708]
请问hrnet做人像抠图matting时，有hrnet_18w，我看backbone中的hrnet.py中有很多的backbone如下，我是不是可以随意选择，只需要在config中model的type下写上对应的名字就可以对吧
![image](https://user-images.githubusercontent.com/114384977/200492159-0a0f65a9-ad2b-4a6d-a8c2-23b87250c7ce.png)

**Comment by wuyefeilin** [comment]
是的，你可以根据需要更换backbone

**Comment by jingmingtao** [comment]
好的谢谢
