### ISSUE TITLE
[Question] Rtformer grouped conv2d

### ISSUE THREAD

**Issue by joihn** [PaddlePaddle/PaddleSeg#2710]
Instead on doing a classic conv2d over [batch, channel, Height, Widh], Rtformer does a **grouped** conv2d over [1, Batch*channel, Height, width] where groupsize = batchsize
```
            x = x.reshape([1, -1, 0, 0])  # n,c_in,h,w -> 1,n*c_in,h,w
            x = F.conv2d(
                x, cross_k, bias=None, stride=1, padding=0,
                groups=B)  # 1,n*c_in,h,w -> 1,n*144,h,w  (group=B)
            x = self._act_sn(x)
            x = F.conv2d(
                x, cross_v, bias=None, stride=1, padding=0,
                groups=B)  # 1,n*144,h,w -> 1, n*c_in,h,w  (group=B)
            x = x.reshape([-1, self.in_channels, 0,
                           0])  # 1, n*c_in,h,w -> n,c_in,h,w  (c_in = c_out)
```
[LINK to the code 
](https://github.com/PaddlePaddle/PaddleSeg/blob/e75e264339783dfc1313cebe3389c1b1badc1507/paddleseg/models/rtformer.py#L417)
Why exactly ? Is it an optimization/efficiency trick ? @juncaipeng

**Comment by juncaipeng** [comment]
Hi, the reason is the convolution kernel of each sample is different when doing cross resolution attention.
