### ISSUE TITLE
人像抠图与人像分割中都是使用HRNET，但是人像抠图可以无锯齿感，差距代码在哪部分呀？

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleSeg#2711]
人像抠图使用HRNET时，训练的时候将alpha作为标签进行训练，而人像分割是mask二值图标签，我想请教下，在进行人像抠图的时候同样是hrnet网络，人像抠图是怎么使用alpha进行读取训练的，是需要转化为mask二值图吗，还是直接进行了训练。预测时候呢，head的不同点是什么呀

**Comment by wuyefeilin** [comment]
Matting更准确的说是回归任务，以alpha作为gt， 分割是像素级的分类，以mask作为gt。Matting训练不需要将alpha转换成mask。

**Comment by jingmingtao** [comment]
整个网络流程代码是matting/model/ppmatting.py对吧，如下所示：
![image](https://user-images.githubusercontent.com/114384977/200724233-8b19b5e2-55af-43eb-9416-7de197969060.png)

**Comment by jingmingtao** [comment]
1、这部分代码的fusion就是我们得到的alpha对吧，也就是说我们网络就是这样一步步得到的alpha对吗；
2、semantic、detail分别是什么呀，为啥alpha = detail_map * transition_mask + fg呢，可以帮忙解释一下吗。

**Comment by wuyefeilin** [comment]
这是我们ppmatting的网络逻辑哈, 具体可以参考我们的技术文稿https://arxiv.org/abs/2204.09433
