### ISSUE TITLE
EIseg生成的annotation.json文件问题

### ISSUE THREAD

**Issue by Linranran** [PaddlePaddle/PaddleSeg#2719]
annotation.json的格式如下
`{
"info": [...]
"licenses": [...]
"images": [...]
"annotations": [
]
}`
其中annotations字段存放分了imagesid，categories seg等信息。我发现出现了相同的标注内容被写入了两次，对应不同的id。
如下：
`{"id": 18, "iscrowd": 0, "image_id": 18, "category_id": 1, "segmentation": [[877.0, 433.0, 877.0, 416.0, 871.0, 402.0, 862.0, 391.0, 850.0, 384.0, 832.0, 381.0, 790.0, 381.0, 777.0, 378.0, 703.0, 378.0, 679.0, 382.0, 172.0, 381.0, 161.0, 383.0, 146.0, 393.0, 137.0, 405.0, 133.0, 421.0, 136.0, 434.0, 146.0, 446.0, 163.0, 456.0, 187.0, 460.0, 321.0, 459.0, 337.0, 461.0, 351.0, 460.0, 659.0, 461.0, 676.0, 463.0, 688.0, 463.0, 696.0, 461.0, 828.0, 463.0, 858.0, 455.0, 871.0, 443.0]], "area": 57610.0, "bbox": [133.0, 378.0, 744.0, 85.0]},`
` {"id": 19, "iscrowd": 0, "image_id": 18, "category_id": 1, "segmentation": [[877.0, 433.0, 877.0, 416.0, 871.0, 402.0, 862.0, 391.0, 850.0, 384.0, 832.0, 381.0, 790.0, 381.0, 777.0, 378.0, 703.0, 378.0, 679.0, 382.0, 172.0, 381.0, 161.0, 383.0, 146.0, 393.0, 137.0, 405.0, 133.0, 421.0, 136.0, 434.0, 146.0, 446.0, 163.0, 456.0, 187.0, 460.0, 321.0, 459.0, 337.0, 461.0, 351.0, 460.0, 659.0, 461.0, 676.0, 463.0, 688.0, 463.0, 696.0, 461.0, 828.0, 463.0, 858.0, 455.0, 871.0, 443.0]], "area": 57610.0, "bbox": [133.0, 378.0, 744.0, 85.0]},`

**Comment by haoyuying** [comment]
您是怎么产生的这个结果呢，请详细描述下标注过程，方便我们复现问题。
