### ISSUE TITLE
关于RTFormer论文中GFA的GDN使用，代码中未体现

### ISSUE THREAD

**Issue by Edenmm** [PaddlePaddle/PaddleSeg#2720]
您好！
文件地址：[PaddleSeg](https://github.com/PaddlePaddle/PaddleSeg/tree/develop/paddleseg/models)/rtformer.py

代码：第321-426行类ExternalAttention定义，论文写道：优化过后的GDN denotes Grouped Double Normalization, which splits the second normalization of the original double normalization into H groups.但在代码中Cross_kv设置为True，之后执行的代码只是将特征图resize成群卷积的样子，并未体现Double Normalization，我很疑惑，期待解答！万分感谢

**Comment by Edenmm** [comment]
def forward(self, x, cross_k=None, cross_v=None):
        """
        Args:
            x (Tensor): The input tensor. 
            cross_k (Tensor, optional): The dims is (n*144, c_in, 1, 1) ##k(inter_channels, in_channels, 1, 1)
            cross_v (Tensor, optional): The dims is (n*c_in, 144, 1, 1) ##v(out_channels, inter_channels, 1, 1)
        """
        x = self.norm(x)
        if not self.use_cross_kv:
            x = F.conv2d(
                x, 
                self.k, # k(inter_channels, in_channels, 1, 1)
                bias=None,
                stride=2 if not self.same_in_out_chs else 1,
                padding=0)  # n,c_in,h,w -> n,c_inter,h,w
            x = self._act_dn(x)  
            x = F.conv2d(
                x, self.v, # v(out_channels, inter_channels, 1, 1)
                bias=None, stride=1,
                padding=0)  # n,c_inter,h,w -> n,c_out,h,w
        else:
            assert (cross_k is not None) and (cross_v is not None), \
                "cross_k and cross_v should no be None when use_cross_kv"
            B = x.shape[0]
            assert B > 0, "The first dim of x ({}) should be greater than 0, please set input_shape for export.py".format(B)
            x = x.reshape([1, -1, 0, 0])  # n,c_in,h,w -> 1,n*c_in,h,w
            x = F.conv2d(
                x, cross_k, bias=None, stride=1, padding=0, # cross_k(n*144, c_in, 1, 1)
                groups=B)  # 1,n*c_in,h,w -> 1,n*144,h,w  (group=B)
            **x = self._act_sn(x)这里使用的只是普通注意力正则化，并未体现GDN中的DN**
            x = F.conv2d(
                x, cross_v, bias=None, stride=1, padding=0, # cross_v(n*c_in, 144, 1, 1)
                groups=B)  # 1,n*144,h,w -> 1, n*c_in,h,w  (group=B)
            x = x.reshape([-1, self.in_channels, 0,
                           0])  # 1, n*c_in,h,w -> n,c_in,h,w  (c_in = c_out)
        return x

**Comment by juncaipeng** [comment]
GroupDoubleNormalization只在GPU-Friendly Attention里出现，Cross-resolution Attention不使用GroupDoubleNormalization.

<img width="634" alt="2286c8eab5e024651d203b055f2e472d" src="https://user-images.githubusercontent.com/52520497/201808742-c2a16269-9618-4cf0-84cc-139528142371.png">
