### ISSUE TITLE
there are no images to display for  infer.py

### ISSUE THREAD

**Issue by KeqingWu** [PaddlePaddle/PaddleSeg#2722]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

When I run visualize.ipynb to output the test sample of infer.py, there are no images to display

**Comment by juncaipeng** [comment]
hi, what is the command you run?

The document of infer.py is: https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/docs/deployment/inference/python_inference.md

**Comment by juncaipeng** [comment]
same issue #2094

**Comment by KeqingWu** [comment]
> same issue #2094

I used the infer.py of the MedicalSeg dir, the command I used is: python3 deploy/python/infer.py  --config output/deploy.yaml --image_path data/lung_coronavirus/lung_coronavirus_phase0/images/coronacases_org_007.npy
But npy can't be display direct.
So I use visualize.ipynb, no display either

**Comment by shiyutang** [comment]
I think you should try ipynb with jupyter notebook.
This jupyter lab is not supported yet: https://github.com/InsightSoftwareConsortium/itkwidgets/issues/405
