### ISSUE TITLE
cuda11.2使用tensorrt推理报错

### ISSUE THREAD

**Issue by xiaodaomingye459** [PaddlePaddle/PaddleSeg#2723]
环境：
platform: Linux-5.15.0-52-generic-x86_64-with-Ubuntu-18.04-bionic
Python: 3.7.13 (default, Apr 24 2022, 01:04:09) [GCC 7.5.0]
Paddle compiled with cuda: True
NVCC: Build cuda_11.2.r11.2/compiler.29558016_0
cudnn: 8.1
GPUs used: 1
CUDA_VISIBLE_DEVICES: 4
GPU: ['GPU 0: NVIDIA P106-100', 'GPU 1: NVIDIA GeForce', 'GPU 2: NVIDIA P106-100', 'GPU 3: NVIDIA GeForce', 'GPU 4: NVIDIA GeForce']
GCC: gcc (GCC) 8.2.0
PaddleSeg: develop
PaddlePaddle: 2.3.2
OpenCV: 4.6.0
问题：
使用飞桨官方cuda11.2镜像docker文件，安装TensorRT-8.2.1.8后报错如下：
AttributeError: 'tensorrt.tensorrt.Builder' object has no attribute 'max_workspace_size'
![image](https://user-images.githubusercontent.com/83204995/201935847-b5615084-ff2a-4c0d-94f3-a2ec8a9f63b2.png)

**Comment by Bobholamovic** [comment]
你好，可以尝试TensorRT 7.2.*版本。参见 https://github.com/NVIDIA-AI-IOT/torch2trt/issues/557

**Comment by lbp0200** [comment]
> 环境： platform: Linux-5.15.0-52-generic-x86_64-with-Ubuntu-18.04-bionic Python: 3.7.13 (default, Apr 24 2022, 01:04:09) [GCC 7.5.0] Paddle compiled with cuda: True NVCC: Build cuda_11.2.r11.2/compiler.29558016_0 cudnn: 8.1 GPUs used: 1 CUDA_VISIBLE_DEVICES: 4 GPU: ['GPU 0: NVIDIA P106-100', 'GPU 1: NVIDIA GeForce', 'GPU 2: NVIDIA P106-100', 'GPU 3: NVIDIA GeForce', 'GPU 4: NVIDIA GeForce'] GCC: gcc (GCC) 8.2.0 PaddleSeg: develop PaddlePaddle: 2.3.2 OpenCV: 4.6.0 问题： 使用飞桨官方cuda11.2镜像docker文件，安装TensorRT-8.2.1.8后报错如下： AttributeError: 'tensorrt.tensorrt.Builder' object has no attribute 'max_workspace_size' ![image](https://user-images.githubusercontent.com/83204995/201935847-b5615084-ff2a-4c0d-94f3-a2ec8a9f63b2.png)

你的P106驱动咋搞定的？我试了好几个版本，NVIDIA-smi都报错，提示没有可以找到的设备
