### ISSUE TITLE
拉取paddle docker镜像后同样无法使用tensorRT报错

### ISSUE THREAD

**Issue by xiaodaomingye459** [PaddlePaddle/PaddleSeg#2725]
环境：
platform: Linux-5.15.0-52-generic-x86_64-with-debian-stretch-sid
Python: 3.7.0 (default, Aug 17 2022, 04:05:29) [GCC 8.2.0]
Paddle compiled with cuda: True
NVCC: Cuda compilation tools, release 10.2, V10.2.89
cudnn: 7.6
GPUs used: 1
CUDA_VISIBLE_DEVICES: 4
GPU: ['GPU 0: NVIDIA P106-100', 'GPU 1: NVIDIA GeForce', 'GPU 2: NVIDIA P106-100', 'GPU 3: NVIDIA GeForce', 'GPU 4: NVIDIA GeForce']
GCC: gcc (GCC) 8.2.0
PaddleSeg: 2.5.0
PaddlePaddle: 2.4.0-rc0
OpenCV: 4.6.0

镜像文件：docker pull paddlepaddle/paddle:2.4.0rc0-gpu-cuda10.2-cudnn7.6-trt7.0

报错如下：
![image](https://user-images.githubusercontent.com/83204995/202208689-2cff0e11-be36-41e5-98c0-84040ebd2139.png)
ERROR: Failed to parse the ONNX file.
In node 569 (importGlobalAveragePool): UNSUPPORTED_NODE: Assertion failed: !isDynamic(kernelSize) && "Cannot run global average pool on an input with dynamic spatial dimensions!"
Traceback (most recent call last):
  File "deploy/python/infer_onnx_trt.py", line 492, in <module>
    export_load_infer(args)
  File "deploy/python/infer_onnx_trt.py", line 450, in export_load_infer
    input_data)
  File "deploy/python/infer_onnx_trt.py", line 245, in trt7_run
    with TRTPredictorV2.trt7_get_engine(onnx_file_path, input_shape) as engine, \
AttributeError: __enter__

**Comment by Bobholamovic** [comment]
看起来是ONNX文件解析的时候出现了问题，请尝试TensorRT v7.2.*版本~

**Comment by xiaodaomingye459** [comment]
还是一样的报错

**Comment by xiaodaomingye459** [comment]
![image](https://user-images.githubusercontent.com/83204995/202395728-9e45bbd9-80f0-4584-bbab-fff3b90bb56a.png)
![image](https://user-images.githubusercontent.com/83204995/202396366-03db6b43-aa6c-41fc-a72c-659da9b86bf5.png)

**Comment by Bobholamovic** [comment]
报错的原因已经发生了改变（`Assertion failed`之后的提示信息）。这个问题仍然和TensorRT有关（准确地说，和trt编译时设置的opset的版本有关），请参考这两个issue：

https://github.com/onnx/onnx-tensorrt/issues/414
https://github.com/onnx/onnx-tensorrt/issues/428
