### ISSUE TITLE
训练过程中出现显存不足的问题

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleSeg#2726]
您好，我在使用人像抠图matting，hrnet18w，进行人像抠图训练时，在训练个几十轮，会报显存不足问题。我知道，可以通过降低batsize、减少输入的训练尺寸可以避免这种情况，可是上述两种操作，可能会使模型效果不佳；
问题1：因为我看报错是在relu激活计算时候出现的资源不足情况，而我在进入到激活前是进行crop_size=512的，所以跟原始的图片尺寸是不是没有关系的呢？
问题2：The command is `export FLAGS_use_cuda_managed_memory=false`这个指令作用是啥?我使用了也不管用,应该怎么执行呢
问题3：因为在训练几十轮也没问题，越是训练到后边，突然的为啥会出现这样的显存消耗增加的情况呢？
![image](https://user-images.githubusercontent.com/114384977/202334170-13e218e7-a8ce-4f58-b971-5dd80f0ea2f9.png)
万分感谢！！！

**Comment by wuyefeilin** [comment]
给一下完成的报错日志哈。另外你在训练时是否显存已经达到临界值了呢

**Comment by jingmingtao** [comment]
1、训练时显存为11086M，显卡一共显存11264M，是有些临界了。我想知道为啥波动了，再想对应解决的办法。
2、完整的报错日志指的是？屏幕打印的所有错误吗

**Comment by jingmingtao** [comment]
您好，这个是报错的完整截图：
![image](https://user-images.githubusercontent.com/114384977/202588828-5ffb799d-3892-4a08-8747-9fb4b522e912.png)

**Comment by wuyefeilin** [comment]
屏幕输出的所有结果

另外开启评估了吗

**Comment by jingmingtao** [comment]
是有验证集的，开启了sad的评估

**Comment by jingmingtao** [comment]
您好，这个问题有什么好的解决建议吗，万分感谢

**Comment by jingmingtao** [comment]
你好我可以在relu激活的这个地方，加上with paddle.no_grad():吗

**Comment by wuyefeilin** [comment]
same as #2772
