### ISSUE TITLE
在使用uwsgi这个web服务器调用paddle，来调用训练的人像抠图时报The API call failed because the CUDA driver and runtime could not be initialized

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleSeg#2728]
错误如下：
![78f8b396140974cb5bb3b344519b069](https://user-images.githubusercontent.com/114384977/202342332-daf85057-f94a-4d4b-9b54-47a226877d8d.png)

**Comment by wuyefeilin** [comment]
环境问题，请参考paddle安装教程保证paddle已正确安装https://www.paddlepaddle.org.cn/
