### ISSUE TITLE
MedicalSeg预训练

### ISSUE THREAD

**Issue by lyangfan** [PaddlePaddle/PaddleSeg#2730]
MedicalSeg训练出来的模型是否可以作为预训练模型再次在MedicalSeg中使用？如果可以的话，如何去掉最后一层的分类头？

**Comment by shiyutang** [comment]
请问你说的预训练模型是分类模型么，medicalseg是医疗分割模型库，所以训练出来的模型可以直接使用，不用去除分类头。

**Comment by lyangfan** [comment]
不是分类模型，就是分割模型，只不过两个分割模型输出的类别数不同，且所用数据也不同。这种情况下，medicalseg能否支持用户去迁移以前用medicalseg训练出来的模型的权重，然后再用meidicalseg进行训练？

**Comment by shiyutang** [comment]
如果输出的类别数量不同，可以直接修改最后一层分类层的num_classes即可，原预训练模型还是可以加载，最后一层由于形状不同会自动跳过。

**Comment by lyangfan** [comment]
> 如果输出的类别数量不同，可以直接修改最后一层分类层的num_classes即可，原预训练模型还是可以加载，最后一层由于形状不同会自动跳过。

感谢解答！

**Comment by shiyutang** [comment]
目前问题已经解答，如有需要，欢迎随时reopen。
