### ISSUE TITLE
PP-Matting: High-Accuracy Natural Image Matting中SCB与HRDB两者的输出进行Fusion是对应元素相加吗，论文中没写

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleSeg#2731]
![image](https://user-images.githubusercontent.com/114384977/202397761-84237542-cec4-4931-95fa-0b9be6fd11d8.png)

**Comment by wuyefeilin** [comment]
是把过度Semantic map中的过度区域替换成Detail map

**Comment by jingmingtao** [comment]
好的谢谢
