### ISSUE TITLE
在VS2019新建工程测试peddleseg的demo  testseg.cc出现程序无法启动的情况

### ISSUE THREAD

**Issue by aiwenzhu** [PaddlePaddle/PaddleSeg#2734]
环境:win10,vs2019,cuda11.6,cudnn8.4
在VS2019新建工程测试peddleseg的demo  testseg.cc出现程序无法启动的情况：
配置了paddleinference的lib，opencv，yaml并将所有相关dll放下了工程目录下，项目生成没问题；
 auto predictor = create_predictor(yaml_config)但是加上这句代码，程序就无法调试和运行，会报
程序无法正常启动0xc000007b的错误

**Comment by juncaipeng** [comment]
我们马上会新增win上的部署demo

**Comment by jin1wang** [comment]
我也遇到了相同的问题，请问有方法解决吗？
