### ISSUE TITLE
[General Issue]Seg数据怎么进行数据增强

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSeg#2735]
```
images
labels
test.txt
train.txt
val.txt
```

Seg数据怎么进行离线数据增强
生成增强数据

**Comment by shiyutang** [comment]
不知道你想做什么离线数据增强呢？我们暂时不提供单独的离线数据增强，但是如果和在线数据增强相近的话，也可以在配置中使用我们的transforms，并跳过训练过程直接保存或者借鉴[在线数据增强](https://github.com/PaddlePaddle/PaddleSeg/blob/develop/paddleseg/transforms/transforms.py)的内容自行撰写相关代码。

**Comment by monkeycc** [comment]
好的 谢谢 我试试

主要是在线增强  看不到效果啊
有些增强反而不好

所以想离线搞出来

**Comment by shiyutang** [comment]
如果想看到效果，可以尝试将增强后的图像转换成numpy后保存，相关代码也可以参考predict.py 中保存图片的内容。
