### ISSUE TITLE
从模型网络结构原理的角度出发，人像抠图数据标定，身体被遮挡的部分，如何标注对模型表现更佳？

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleSeg#2736]
如下图所示（左边是原始图，右边是标注的alpha图），这个人被自行车遮挡了，请问这样标注合理吗，还是说舍弃分离主要身体part的部分，比如舍弃脚呢,请问有什么好的建议吗。
![image](https://user-images.githubusercontent.com/114384977/202648157-33ed8677-fd97-4399-bf50-e7401023b80a.png)

**Comment by jingmingtao** [comment]
将遮挡身体的部分标注成身体的一部分这样合理吗

**Comment by shiyutang** [comment]
按理来说是应该这样标注的，可以看到常用的分割数据集cityscapes中也是这样标注的，所以模型是可以学习的：
https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fpic2.zhimg.com%2Fv2-db8eff6044145ae2b2a98b5eaff66f3e_1440w.jpg%3Fsource%3D172ae18b&refer=http%3A%2F%2Fpic2.zhimg.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1671353092&t=e8196d4008f7cfbf5dbba3db63dc8687

**Comment by jingmingtao** [comment]
我是使用的咱们的pp-matting网络，这样也算合理吗

**Comment by jingmingtao** [comment]
比如人手里拿着的手提袋呢、手机 呢
![image](https://user-images.githubusercontent.com/114384977/202660075-47758020-c33f-47c1-a88d-5d703d8cb99e.png)

**Comment by jingmingtao** [comment]
是不是应该严格按照，是人体的就是人体，不是人体的就不是人体的这样的逻辑来进行标注呢

**Comment by wuyefeilin** [comment]
为了网络更好的学习，可以把跟人体相连的显著物体当作目标的一部分，这样子利于整体的抠图。一般会把手持物体，手机等也当做人像的一部分

**Comment by jingmingtao** [comment]
那如果是摩托车、自行车、儿童车呢

**Comment by jingmingtao** [comment]
是应该将车作为人体的一部分吗，也是比较相连，但是却不属于人体的部分较大

**Comment by jingmingtao** [comment]
再比如胸前捧得一束花，或者是抖音特效、文字，这种怎么处理会好一些呢

**Comment by wuyefeilin** [comment]
> 那如果是摩托车、自行车、儿童车呢

这种根据需要，可以包含也可以不包含。





> 再比如胸前捧得一束花，或者是抖音特效、文字，这种怎么处理会好一些呢

这种可以视为一部分
