### ISSUE TITLE
SETR 运行错误: OSError

### ISSUE THREAD

**Issue by ykx123-hub** [PaddlePaddle/PaddleSeg#2738]
import paddleseg

import paddle

from paddleseg.models.backbones import ViT_large_patch16_384

from paddleseg.models import SegmentationTransformer

def SETR(num_classes, pretrained=False):

  """

  构建SETR模型

  :param num_classes: int 类别数

  :param pretrained: bool 是否使用预训练权重

  :return: paddle.nn.Layer

  """

  backbone = ViT_large_patch16_384(pretrained="https://bj.bcebos.com/paddleseg/dygraph/vit_large_patch16_384.tar.gz")

  model = SegmentationTransformer(

​    num_classes,

​    backbone,

​    align_corners=True

  )

  if pretrained:

​    state_dict = paddle.load("models_params/SETR_naive.pdparams")

​    model.set_state_dict(state_dict)

  return model

model = SETR(19)

evaluate_and_predict(model, val_set)  

===================================================================== 

运行上述代码报错：
![LP`D}A`B%Y) 46XGHI4YH@L](https://user-images.githubusercontent.com/74460795/202766063-ebb66d26-6d9b-4785-aa58-d8c09795570e.png)

**Comment by haoyuying** [comment]
您好，无法看到您的报错信息，请给出能够完整复现的代码和报错信息，方便我们排查问题。
