### ISSUE TITLE
[General Issue]启动eiseg时出现以下错误：qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found

### ISSUE THREAD

**Issue by freemanhm** [PaddlePaddle/PaddleSeg#2739]
欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.3.2）
 3. 操作系统信息：（如ubuntu 18.04）
 4. Python版本号：（如Python3.8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）
我的安装过程如下：
1.创建了虚拟环境paddle_env
2.在激活虚拟环境paddle_env下安装了PaddlePaddle 2.3.2
“conda install paddlepaddle-gpu==2.3.2 cudatoolkit=10.2 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/”
3.安装了eiseg
“pip install eiseg”
4.启动eiseg时出现以下错误：
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1668825469 (unix time) try "date -d @1668825469" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x5d32) received by PID 23858 (TID 0x7f231ebd7080) from PID 23858 ***]

已放弃 (核心已转储)

**Comment by freemanhm** [comment]
后来发现，就是远程访问的问题。我是通过Xshell访问服务器，启动eiseg才会出现这个错误。直接通过服务器的命令行启动eiseg就不存在此问题。

**Comment by danny-zhu** [comment]
远程shell连接服务器启动和服务器本地shell直接启动有啥区别吗？为什么回到导致启动失败，不理解
