### ISSUE TITLE
infer.py中的bug

### ISSUE THREAD

**Issue by qiyuezhiguang** [PaddlePaddle/PaddleSeg#274]
（1）132行中，if (ori_h != eval_crop_size[0] or ori_w != eval_crop_size[1]):，eval_crop_size[0]为宽，eval_crop_size[1]为高，应该修改为if ori_h != eval_crop_size[1] or ori_w != eval_crop_size[0]:

（2）117行中的im = cv2.imread(image_path, -1)，如果输入为RGB彩色图片，读入的为im为一维图层，并且会在channels = im.shape[2]处报错，应该修改为im = cv2.imread(image_path)，则读取3维RGB图像。

————————————
支持paddle   支持国产

**Comment by LutaoChu** [comment]
(1)是的，eval_crop_size[0]为宽，eval_crop_size[1]为高，这地方我们修改一下，感谢反馈！
(2)还是得用 cv2.imread(image_path, -1)，因为cv2.imread(image_path)会忽略rgba的alpha通道。这边的问题我们通过另外的方式修复一下，感谢反馈！
