### ISSUE TITLE
标注几张图片后图片变小，放大到最大图片也很小，只有关闭软件重新打开才可以，每次标注四五张图片都会遇到无法放大的问题，请问如何解决呢？

### ISSUE THREAD

**Issue by xiyouji666** [PaddlePaddle/PaddleSeg#2740]
Thanks for your bug report. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Full codes: (if you modify any original code，please show the comparison of the codes before and after)
 7. Detailed error information, releated running log: (if using multi-gpus，the log is saved to log/worklog.0 by default)
 8. Running command or reproduce details：
 9. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 完整的代码：(若修改过原代码，请提供修改前后代码对比）
 7. 详细的错误信息、相关log：（若使用多卡，log默认保存在log/worklog.0）
 8. 运行指令或复现步骤：
 9. 其他内容: （增加其他与问题相关的内容）

**Comment by haoyuying** [comment]
您好，是使用的eiseg吗，请问使用的是什么版本呢？请给出一个具体的视频或者如何复现的方式，方便我们排查问题。

**Comment by xiyouji666** [comment]
&nbsp; &nbsp; &nbsp; 您好，很抱歉未能及时回复，我是使用的eiseg，版本为1.0.3。具体的情况我录了一个视频，放在附件中了，但是没有语音讲，因为我们要标注的数据是像素级的，所以每张图片都需要放大到最大，然后再进行标注。由于我们图片数据是未公开的，我使用了几张风景图片，通过标注里面的云彩来演示，没有很认真的标注，只是想演示一下效果。在视频里面可以看到切换到下一张图片后，点击后的绿色的点是逐渐变小的，再到后面图像放大到最大也不能达到全屏（在视频里面每张图片我都是放大到能放大的最大程度了），然后后面图像就越来越小，最后甚至是一片白，看不到图像。之前我在标注数据时每标注4-5张图片就会出现这种情况，只能是关闭软件重新打开，重新加载模型和数据，所以这个问题不清楚该如何解决。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月21日(星期一) 上午10:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] 标注几张图片后图片变小，放大到最大图片也很小，只有关闭软件重新打开才可以，每次标注四五张图片都会遇到无法放大的问题，请问如何解决呢？ (Issue #2740)





 
您好，是使用的eiseg吗，请问使用的是什么版本呢？请给出一个具体的视频或者如何复现的方式，方便我们排查问题。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

视频演示.rar (16.01M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=7431343354e5c99a29adbb001036044b025005065300045318525506571b02000c03190a0f5253490400515706030f5105085007363a36aee6f781e2ebfc884a475046330b&t=exs_ftn_download&code=5143666d

**Comment by xiyouji666** [comment]
&nbsp; &nbsp; &nbsp; 您好，很抱歉回复的不及时，我是使用的eiseg，版本为1.0.3。具体的情况我录了一个视频，16M，但是发不出去，发出去邮件会被退回。
&nbsp; &nbsp; &nbsp; 复现方式的话：因为我们要标注的数据是像素级的很小的目标，所以每张图片都需要放大到最大，然后再进行标注。所以可以使用几张风景图片通过标注里面的云彩来试一下（每张图片都需要放大到最大，然后找很小的目标进行标注），标注过程中可以看到切换到下一张图片后，点击后的绿色的点是逐渐变小的，再到后面图像放大到最大也不能达到全屏（每张图片都是放大到能放大的最大程度了），然后后面图像就越来越小，最后甚至是一片白，看不到图像。之前我在标注数据时每标注4-5张图片就会出现这种情况，只能是关闭软件重新打开，重新加载模型和数据，所以这个问题不清楚该如何解决。如果我描述不清楚的话，麻烦给我更换一下接收邮箱，我发一下具体的视频吧。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月21日(星期一) 上午10:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] 标注几张图片后图片变小，放大到最大图片也很小，只有关闭软件重新打开才可以，每次标注四五张图片都会遇到无法放大的问题，请问如何解决呢？ (Issue #2740)





 
您好，是使用的eiseg吗，请问使用的是什么版本呢？请给出一个具体的视频或者如何复现的方式，方便我们排查问题。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
