### ISSUE TITLE
[Feature Request]hook 及自定义eval间隔

### ISSUE THREAD

**Issue by Asthestarsfalll** [PaddlePaddle/PaddleSeg#2741]
1. 某些情况下可能需要在训练达到某一阶段后对模型、dataset等做一些处理或者调用一些方法，因此需要在训练过程中注册hook进行处理。
2. 在网络后期可能需要增加eval的频率来得到性能更好的模型，因此希望可以自定义eval的间隔或者iter数，期望的形式如下：
```bash
python train.py --config xxx --save_interval 4000 8000 9000 10000
```

**Comment by shiyutang** [comment]
1. eval interval的设置可以自行修改train.py中保存的代码，并制定相应的iters 保存
2. 关于hook部分，可以进一步详细说明在不同阶段调用方法的需求吗？

**Comment by Asthestarsfalll** [comment]
1. 大致可以分为两种，一种为达到某种条件执行一次，后续不再执行，一种为按照某种规律重复执行。第一种比如模型中使用了某些重参数化的技巧，需要在训练后期的某个阶段（iters达到某个数量后）进行重参数化，再直接在重参数化后的模型上进行微调，而无需resume。第二种比如使用了class uniform sampling的技术，需要每个epoch结束后重新build一下dataset等。
2. 自行修改确实可以，只是我个人认为这或许是一个比较普遍的需求，可以当作一个额外功能增加上去，并且可以与之前的形式保持兼容。

**Comment by shiyutang** [comment]
看上去你已经搭建了相关代码，欢迎给我们贡献～
