### ISSUE TITLE
关于ddrnet

### ISSUE THREAD

**Issue by xiaodaomingye459** [PaddlePaddle/PaddleSeg#2742]
我在config里面只找到关于ddrnet23的配置文件，
而我想自己训练ddrnet23-slim的模型，
请问下官方有没有提供关于ddrnet23-slim的预训练模型呢？

**Comment by xiaodaomingye459** [comment]
还有就是从哪里可以看到官方提供了哪些预训练模型，
有没有一个完整的目录可以查询。

**Comment by haoyuying** [comment]
目前我们只提供了这个模型：https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.6/configs/ddrnet
slim产生模型可参考这个文档：https://github.com/PaddlePaddle/PaddleSeg/blob/12b008034854b95c70621f36bb67d680edc5d106/docs/slim/quant/quant_cn.md
全部模型请参考reame中的overview部分。

**Comment by xiaodaomingye459** [comment]
请问提供的预训练模型是在imagenet上做的预训练吗，
如果我自己想要类似的预训练有没有类似的教程，
您提供的链接好像是模型量化的教程。

**Comment by wuyefeilin** [comment]
整体模型我们提供了cityscapes的预训练，没有imagenet上的预训练。
