### ISSUE TITLE
paddleserving pipeline部署

### ISSUE THREAD

**Issue by Enchanted0911** [PaddlePaddle/PaddleSeg#2746]
翻看文档，好像seg目前还不支持pipeline部署? 如果可以的话，能否给个example呢, 像其他场景如OCR那样的example

**Comment by juncaipeng** [comment]
文档：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/docs/deployment/serving/serving_cn.md

seg模型和其他模型类似部署，所以建议直接参考paddle serving官方的文档。
