### ISSUE TITLE
想请教一下手写字体擦除的问题

### ISSUE THREAD

**Issue by TD-wzw** [PaddlePaddle/PaddleSeg#2749]
因为看到百度网盘的试卷手写字体擦除效果很好，想问下大佬建议，用单纯语义分割的方式可以做到吗？还是建议基于对抗生成网络来做。

**Comment by juncaipeng** [comment]
如果有数据，可以使用语义分割实现。

**Comment by TD-wzw** [comment]
> 如果有数据，可以使用语义分割实现。
好的，感谢大佬回复
