### ISSUE TITLE
请教几个问题

### ISSUE THREAD

**Issue by qiyuezhiguang** [PaddlePaddle/PaddleSeg#275]
（1）在infer.py 里面 有两种模式，analysis和native，请问有什么区别，分别什么原理？
（2）预处理里面的MEAN和STD如何根据自己的数据定义，我的数据集几乎都是黑色背景，整体颜色偏黑，也是采用0.5吗？
（3）bn一般要求batch size>2，等于2的时候与gn相比会是谁更好一点呢？
（4）一些基本参数的设置，比如LR步长一般设置为多少，0.01？
非常感谢！

————————————————————
支持paddle   支持国产

**Comment by LutaoChu** [comment]
（2）0.5是默认值，是针对人像场景统计出来的。mean、std最好是针对你的数据集进行统计
（3）理论上gn会好一些，gn在batch size小的时候更稳定
（4）根据不同模型、不同数据而定，需要尝试

**Comment by Channingss** [comment]
@qiyuezhiguang 
infer.py 的analysis，支持更多的优化，包括如OP的融合、内存/显存的优化、 MKLDNN，TensorRT 等底层加速库的支持等https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/native_infer.html#a-name-analysispredictor-analysispredictor-a

**Comment by qiyuezhiguang** [comment]
> （2）0.5是默认值，是针对人像场景统计出来的。mean、std最好是针对你的数据集进行统计
> （3）理论上gn会好一些，gn在batch size小的时候更稳定
> （4）根据不同模型、不同数据而定，需要尝试

在训练的时候，在哪里可以设定mean和std呢，还是网络自动计算？

**Comment by LutaoChu** [comment]
@qiyuezhiguang 在yaml中新增这两行就可以了，按需要修改mean、std
```
# 均值，图像预处理减去的均值
MEAN: [0.5, 0.5, 0.5]
# 标准差，图像预处理除以标准差·
STD: [0.5, 0.5, 0.5]
```

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。
