### ISSUE TITLE
trt_version

### ISSUE THREAD

**Issue by m828** [PaddlePaddle/PaddleSeg#2753]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.3.2）
 3. 操作系统信息：（如Linux/Windows）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA11.2/cuDNN 8.1等）
 6. 其他内容: （增加其他与问题相关的内容）
![image](https://user-images.githubusercontent.com/45037914/203463697-aedfcbde-3042-43ee-97fd-6605b7dac4a2.png)
![image](https://user-images.githubusercontent.com/45037914/203463815-d45788f8-0a57-4ab0-b10a-009693ba2b76.png)

我使用的是trt8.2，请问[infer_onnx_trt.py]支持吗？(https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/deploy/python/infer_onnx_trt.py)

**Comment by m828** [comment]
> 

![image](https://user-images.githubusercontent.com/45037914/203464055-77bf15c9-851b-4713-adfa-e48a4f830cc6.png)
直接跑的话出现这样的错误

**Comment by wuyefeilin** [comment]
降低trt版本试试哈，比如使用7.1或7.2
