### ISSUE TITLE
[General Issue]PPLiteSeg代码与论文中的出入

### ISSUE THREAD

**Issue by finsary** [PaddlePaddle/PaddleSeg#2754]
在ppLiteSeg的论文中，画出了两个UFAM模块，但在代码中UAFM使用了三次，查看代码时发现是191行中，多出了一个经过sppm模块后的block与没经过sppm的block进行的UFAM操作，但我觉得这个不存在论文中的模块不该有，或者这个有在论文中但是我没有仔细看，求解答

**Comment by juncaipeng** [comment]
对，论文测试的精度和速度的模型都有三个UFAM模块，和代码一致。 论文我们近期会更新一版。
