### ISSUE TITLE
Matting结果输出错误

### ISSUE THREAD

**Issue by user00644** [PaddlePaddle/PaddleSeg#2757]
Thanks for your bug report. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: PaddleSeg release/2.6
 2. PaddlePaddle version: paddlepaddle-gpu     2.3.1
 3. Operation system: Linux
 4. Python version: Python3.8
 5. CUDA/cuDNN version: CUDA10.2/cuDNN 7.6.5
 6. Full codes: 使用config文件夹的配置，使用提供的预训练的模型
 7. Detailed error information, releated running log: (if using multi-gpus，the log is saved to log/worklog.0 by default)
 8. Running command or reproduce details：
python tools/predict.py \
    --config configs/modnet/modnet-hrnet_w18.yml \
    --model_path output/best_model/modnet-hrnet_w18.pdparams \
    --image_path data/PPM-100/val/fg/ \
    --save_dir ./output/results \
    --fg_estimate True
输出alpha结果是很多点，不连续

**Comment by wuyefeilin** [comment]
可以直接利用我们提供的预训练模型进行预测哈

**Comment by user00644** [comment]
> 可以直接利用我们提供的预训练模型进行预测哈
就是利用你们提供的预训练模型进行预测的，python tools/predict.py，但是结果就是不对。。。。。
输出结果是那种类似边缘检测的图片

**Comment by user00644** [comment]
已解决，是我忘记之前修改了paddleseg的normlize的函数
