### ISSUE TITLE
指定多卡训练报server not ready, wait 3 sec to retry... not ready endpoints:['0.1.68.146:44201'][Bug]

### ISSUE THREAD

**Issue by ZhangJingweiYa** [PaddlePaddle/PaddleSeg#2766]
多卡训练，用如下命令：
export CUDA_VISIBLE_DEVICES=0,1,2,3 # 设置4张可用的卡
指定了其中的4块卡

python -m paddle.distributed.launch train.py \
       --config configs/segformer/segformer_b5_cityscapes_1024x1024_160k.yml \
       --do_eval \
       --use_vdl \
       --save_interval 500 \
       --save_dir output

跑的时候不断出现如下报错：
server not ready, wait 3 sec to retry...
not ready endpoints:['0.1.68.146:38149', '0.1.68.146:35087', '0.1.68.146:56455']
server not ready, wait 3 sec to retry...
not ready endpoints:['0.1.68.146:38149', '0.1.68.146:35087', '0.1.68.146:56455']

这是什么原因？

**Comment by shiyutang** [comment]
请更新到最新版本的paddleseg和paddle，并重试一次看是否出现

**Comment by ZhangJingweiYa** [comment]
> 

我用conda命令重新安装paddle没有出现呢上述问题了，之前用的是pip命令，但是之后又出现了新的报错

2022-11-27 19:16:12 [INFO]      There are 1052/1067 variables loaded into SegFormer.
I1127 19:16:12.605310 3907468 tcp_utils.cc:181] The server starts to listen on IP_ANY:51920
I1127 19:18:22.167176 3907468 tcp_utils.cc:107] Retry to connect to 0.1.68.146:51920 while the server is not yet listening.
I1127 19:20:35.287211 3907468 tcp_utils.cc:107] Retry to connect to 0.1.68.146:51920 while the server is not yet listening.
I1127 19:22:48.411125 3907468 tcp_utils.cc:107] Retry to connect to 0.1.68.146:51920 while the server is not yet listening.

请问这是什么原因？

**Comment by ZhangJingweiYa** [comment]
> 请更新到最新版本的paddleseg和paddle，并重试一次看是否出现

找到原因了，我之前用的pip命令安装的paddle只能单卡跑。之后又用conda命令重新安装就可以正常多卡跑了。
但是它又报了新的问题：

2022-11-27 19:16:12 [INFO]      There are 1052/1067 variables loaded into SegFormer.
I1127 19:16:12.605310 3907468 tcp_utils.cc:181] The server starts to listen on IP_ANY:51920
I1127 19:18:22.167176 3907468 tcp_utils.cc:107] Retry to connect to 0.1.68.146:51920 while the server is not yet listening.
I1127 19:20:35.287211 3907468 tcp_utils.cc:107] Retry to connect to 0.1.68.146:51920 while the server is not yet listening.
I1127 19:22:48.411125 3907468 tcp_utils.cc:107] Retry to connect to 0.1.68.146:51920 while the server is not yet listening.

请问这是什么原因？

**Comment by ZhangJingweiYa** [comment]
> 请更新到最新版本的paddleseg和paddle，并重试一次看是否出现

找到原因了，我之前用的pip命令安装的paddle只能单卡跑。之后又用conda命令重新安装就可以正常多卡跑了。
但是它又报了新的问题：

2022-11-27 19:16:12 [INFO] There are 1052/1067 variables loaded into SegFormer.
I1127 19:16:12.605310 3907468 tcp_utils.cc:181] The server starts to listen on IP_ANY:51920
I1127 19:18:22.167176 3907468 tcp_utils.cc:107] Retry to connect to 0.1.68.146:51920 while the server is not yet listening.
I1127 19:20:35.287211 3907468 tcp_utils.cc:107] Retry to connect to 0.1.68.146:51920 while the server is not yet listening.
I1127 19:22:48.411125 3907468 tcp_utils.cc:107] Retry to connect to 0.1.68.146:51920 while the server is not yet listening.

请问这是什么原因？
@shiyutang

**Comment by ZhangJingweiYa** [comment]
> 请更新到最新版本的paddleseg和paddle，并重试一次看是否出现

找到原因了，我之前用的pip命令安装的paddle只能单卡跑。之后又用conda命令重新安装就可以正常多卡跑了。
还有就是nccl安装有问题，重重新安装了nccl。

但是它又报了新的问题：

2022-11-27 19:16:12 [INFO] There are 1052/1067 variables loaded into SegFormer.
I1127 19:16:12.605310 3907468 tcp_utils.cc:181] The server starts to listen on IP_ANY:51920
I1127 19:18:22.167176 3907468 tcp_utils.cc:107] Retry to connect to 0.1.68.146:51920 while the server is not yet listening.
I1127 19:20:35.287211 3907468 tcp_utils.cc:107] Retry to connect to 0.1.68.146:51920 while the server is not yet listening.
I1127 19:22:48.411125 3907468 tcp_utils.cc:107] Retry to connect to 0.1.68.146:51920 while the server is not yet listening.

请问这是什么原因？
@shiyutang

**Comment by shiyutang** [comment]
这个看上去是paddle环境导致的分布式运行出错，建议重启一个新的环境，并重新安装paddle2.3.2尝试
```
conda create -n paddle2.3.2  python=3.8
```
