### ISSUE TITLE
同样的配置，PPLiteSeg和DeepLabV3都可以正常训练，唯独UNet训练报错

### ISSUE THREAD

**Issue by stq054188** [PaddlePaddle/PaddleSeg#2767]
Win10 64位，Python 3.8.5, PaddleSeg: 2.6.0, PaddlePaddle: 2.3.2
——————————————————————————————————
配置文件：
batch_size: 4
iters: 40000

train_dataset:
  type: Dataset
  dataset_root: data/C0402
  train_path: data/C0402/train_list.txt
  num_classes: 2
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [256, 256]
    - type: RandomHorizontalFlip
    - type: RandomVerticalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: data/C0402
  val_path: data/C0402/val_list.txt
  num_classes: 2
  transforms:
    - type: ResizeByLong
      long_size: 1280
    - type: Normalize
  mode: val

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: DiceLoss
  coef: [1]

test_config:
  auc_roc: True

model:
  type: UNet
  num_classes: 2
  use_deconv: False
  pretrained: Null
——————————————————————————————————
训练命令：
python train.py --config configs/quick_start/my_unet.yml --save_interval 500 --do_eval --use_vdl --save_dir output
——————————————————————————————————
同样的配置，PPLiteSeg和DeepLabV3都可以正常训练，唯独UNet训练报错？
报错信息：
2022-11-26 15:58:49 [INFO]
------------Environment Information-------------
platform: Windows-10-10.0.19041-SP0
Python: 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
Paddle compiled with cuda: True
NVCC: Build cuda_11.2.r11.2/compiler.29373293_0
cudnn: 8.1
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: NVIDIA GeForce']
PaddleSeg: 2.6.0
PaddlePaddle: 2.3.2
OpenCV: 4.6.0
------------------------------------------------
2022-11-26 15:58:49 [INFO]
---------------Config Information---------------
batch_size: 1
iters: 40000
loss:
  coef:
  - 1
  types:
  - ignore_index: 255
    type: DiceLoss
lr_scheduler:
  end_lr: 0
  learning_rate: 0.01
  power: 0.9
  type: PolynomialDecay
model:
  num_classes: 2
  pretrained: null
  type: UNet
  use_deconv: false
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 4.0e-05
train_dataset:
  dataset_root: data/C0402
  mode: train
  num_classes: 2
  train_path: data/C0402/train_list.txt
  transforms:
  - max_scale_factor: 2.0
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - crop_size:
    - 256
    - 256
    type: RandomPaddingCrop
  - type: RandomHorizontalFlip
  - type: RandomVerticalFlip
  - brightness_range: 0.4
    contrast_range: 0.4
    saturation_range: 0.4
    type: RandomDistort
  - type: Normalize
  type: Dataset
val_dataset:
  dataset_root: data/C0402
  mode: val
  num_classes: 2
  transforms:
  - long_size: 1280
    type: ResizeByLong
  - type: Normalize
  type: Dataset
  val_path: data/C0402/val_list.txt
------------------------------------------------
W1126 15:58:49.096833  5504 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.2
W1126 15:58:49.096833  5504 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
W1126 15:58:49.734207  5504 gpu_resources.cc:201] WARNING: device:  . The installed Paddle is compiled with CUDNN 8.2, but CUDNN version in your machine is 8.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
D:\Python38\lib\site-packages\paddle\nn\layer\norm.py:653: UserWarning: When training, we now always track global mean and variance.
  warnings.warn(
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [1] and greater than or equal to 0, but received [0]
Traceback (most recent call last):
  File "train.py", line 230, in <module>
    main(args)
  File "train.py", line 206, in main
    train(
  File "E:\Practice\Python\DeepLearning\PaddlePaddle\Paddle_FastDeploy\PaddleSeg\PaddleSeg-release-2.6\paddleseg\core\train.py", line 213, in train
    loss.backward()
  File "D:\Python38\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\Python38\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\Python38\lib\site-packages\paddle\fluid\framework.py", line 434, in __impl__
    return func(*args, **kwargs)
  File "D:\Python38\lib\site-packages\paddle\fluid\dygraph\varbase_patch_methods.py", line 291, in backward
    core.dygraph_run_backward([self], [grad_tensor],
OSError: (External) CUBLAS error(1).
  [Hint: 'CUBLAS_STATUS_NOT_INITIALIZED'.  The cuBLAS library was not initialized. This is usually caused by the lack of a prior cublasCreate() call, an error in the CUDA Runtime API called by the cuBLAS routine, or an error in the hardware setup.  To correct: call cublasCreate() prior to the function call; and check that the hardware, an appropriate version of the driver, and the cuBLAS library are correctly installed.  ] (at ..\paddle\phi\backends\gpu\gpu_resources.cc:140)

**Comment by stq054188** [comment]
@juncaipeng 能否帮忙看下，谢谢

**Comment by haoyuying** [comment]
您好，unet由于本身的模型结构中存在前后桥连的结构，因此对输入的shape有要求，shape必须满足encoder和decoder对应的层shape是一致的，建议使用unet给定的配置文件进行配置。

**Comment by stq054188** [comment]
> 您好，unet由于本身的模型结构中存在前后桥连的结构，因此对输入的shape有要求，shape必须满足encoder和decoder对应的层shape是一致的，建议使用unet给定的配置文件进行配置。

我用UNet给定的配置文件配置了可以训练，但是预测的时候又报错：
预测指令：
python predict.py --config configs/unet/unet_stare_128x128_40k.yml --model_path output/best_model/model.pdparams --image_path data/C0402/JPEGImages/02.jpg --save_dir output/result

报错信息：
---------------Config Information---------------
batch_size: 4
iters: 40000
loss:
  coef:
  - 1
  types:
  - type: DiceLoss
lr_scheduler:
  end_lr: 0
  learning_rate: 0.01
  power: 0.9
  type: PolynomialDecay
model:
  num_classes: 2
  pretrained: null
  type: UNet
  use_deconv: false
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 4.0e-05
test_config:
  auc_roc: true
train_dataset:
  dataset_root: data/STARE
  mode: train
  transforms:
  - max_scale_factor: 2.0
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - crop_size:
    - 128
    - 128
    type: RandomPaddingCrop
  - type: RandomHorizontalFlip
  - type: RandomVerticalFlip
  - brightness_range: 0.4
    contrast_range: 0.4
    saturation_range: 0.4
    type: RandomDistort
  - type: Normalize
  type: STARE
val_dataset:
  dataset_root: data/STARE
  mode: val
  transforms:
  - type: Normalize
  type: STARE
------------------------------------------------
W1128 16:07:53.565258 17532 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.2
W1128 16:07:53.565258 17532 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
2022-11-28 16:07:54 [INFO]      Number of predict images = 1
Traceback (most recent call last):
  File "predict.py", line 185, in <module>
    main(args)
  File "predict.py", line 173, in main
    predict(
TypeError: predict() got an unexpected keyword argument 'auc_roc'

@haoyuying 请问下这个是什么原因？

**Comment by stq054188** [comment]
@haoyuying 还有个问题，STARE数据集解压出来mask图是全黑的，是浮点数还是怎样，看不出来，试着读取发现都是0

**Comment by haoyuying** [comment]
报错信息说的是predict中传入了非法的auc_roc，可以从这里排查下您配置的config是否存在问题。

**Comment by stq054188** [comment]
> 报错信息说的是predict中传入了非法的auc_roc，可以从这里排查下您配置的config是否存在问题。

检查了在stare.yml末尾确实有，但是这个是自带的。。。只能把这个删除了，才能正常推理预测
test_config:
  auc_roc: True
