### ISSUE TITLE
[Bug]cannot import name 'APP_EISeg' from 'app'

### ISSUE THREAD

**Issue by wwdok** [PaddlePaddle/PaddleSeg#2770]
Thanks for your bug report. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Full codes: (if you modify any original code，please show the comparison of the codes before and after)
 7. Detailed error information, releated running log: (if using multi-gpus，the log is saved to log/worklog.0 by default)
 8. Running command or reproduce details：
 9. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）2.6
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）2.4
 3. 操作系统信息：（如Linux/Windows/MacOS）Windows
 4. Python版本号：（如Python3.6/7/8）python 3.8.10
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 完整的代码：(若修改过原代码，请提供修改前后代码对比）
 7. 详细的错误信息、相关log：（若使用多卡，log默认保存在log/worklog.0）
 8. 运行指令或复现步骤：
 9. 其他内容: （增加其他与问题相关的内容）
 
 使用`pip install eiseg`安装好，执行`eiseg`时报错：
```
C:\Users\user>eiseg
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\user\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\Scripts\eiseg.exe\__main__.py", line 4, in <module>
    # you may not use this file except in compliance with the License.
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\eiseg\run.py", line 25, in <module>
    from app import APP_EISeg  # 导入带槽的界面
ImportError: cannot import name 'APP_EISeg' from 'app' (c:\users\user\appdata\local\programs\python\python38\lib\site-packages\app\__init__.py)
```

**Comment by haoyuying** [comment]
eiseg需要在有界面显示的环境下安装，请问您的使用环境是否有显示器呢？

**Comment by wwdok** [comment]
有的，惠普显示器

**Comment by haoyuying** [comment]
您好，可以尝试卸载eiseg后重新安装，或者使用develop分支下使用repo方式来跑通，目前看报错没法定位问题位置，初步判断是包下载导致代码缺失。

**Comment by wwdok** [comment]
重装了还是一样的报错

**Comment by xiegegege** [comment]
@wwdok 你是不是安装了app, pip uninstall app试下呢

**Comment by wwdok** [comment]
没有安装app哦
![image](https://user-images.githubusercontent.com/43233772/205920990-84967045-10a6-4993-9e13-0801dedcecbf.png)

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
