### ISSUE TITLE
使用matting训练至几十轮，突然out of memary，在relu激活能否使用with paddle.no_grad()语句解决

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleSeg#2772]
在训练开始的时候并没有显存不足，几十轮后开始出现，我看着是在relu激活的时候出现的，能否使用with paddle.no_grad()解决？困扰了我很久半个月了这个问题，一直resume进行使用。我的显卡是1080ti（11g），启动训练时11086M，不知什么原因引起的波动。希望给点建议，报错如下：
另外FLAGS_use_cuda_managed_memory=false怎么使用，直接export吗，我试了不管用
![image](https://user-images.githubusercontent.com/114384977/204209595-0fc00dca-7d56-4729-8005-a24451df1890.png)

**Comment by jingmingtao** [comment]
您好我解决了不知道会不会有影响，在train.py中加入：os.environ['FLAGS_use_cuda_managed_memory']='true'，而不是false，显存变成6000M，降低了将近一半

**Comment by wuyefeilin** [comment]
激活使用with paddle.no_grad()不可以哈，os.environ['FLAGS_use_cuda_managed_memory']='true' 不影响训练结果的话就可以用

**Comment by jingmingtao** [comment]
我可以问一下是什么原因可能会导致激活这部分操作导致消耗的显存变大吗

**Comment by jingmingtao** [comment]
还是没有解决这个问题，我可以用这个语句吗：torch.cuda.empty_cache()来解决吗

**Comment by wuyefeilin** [comment]
不行的话可以适当减小batch size

**Comment by jingmingtao** [comment]
我batchsize从4变成2后，不仅训练速度降低一般，而且收敛速度更慢，原因是我的数据分布不是很统一，所以2batsize效果不太好啊

**Comment by jingmingtao** [comment]
领导省钱，不给我换卡，而且让我定位显存溢出的原因，我头都大了

**Comment by jingmingtao** [comment]
我就单卡1080ti

**Comment by wuyefeilin** [comment]
可以换一个小一点模型试试，比如我们换成PP-MattingV2。 这是个小模型，可以节省显存

**Comment by jingmingtao** [comment]
小模型我已经试过了，你们呢所有的几乎试了一遍，效果不好，我们的场景比较复杂，需要拟合的场景比较难办，但是我数据还比较少，没有人标注，我自己动手学习了ps，自己标的，愁人啊兄弟

**Comment by jingmingtao** [comment]
没数据，没训练资源，要求达到国内一流标准，难不难

**Comment by wuyefeilin** [comment]
那就减小bs， 增加训练时间

**Comment by jingmingtao** [comment]
嗯嗯好的
