### ISSUE TITLE
多卡训练Retry to connect to 0.1.68.146:39291 while the server is not yet listening.[Bug]

### ISSUE THREAD

**Issue by ZhangJingweiYa** [PaddlePaddle/PaddleSeg#2773]
1. PaddleSeg版本：2.6.0
 2. PaddlePaddle版本：PaddlePaddle 2.4.0
 3. 操作系统信息：Linux
 4. Python版本号：Python3.8

首先，使用run_check()会报下面这个警告。但是显示是可以在多卡上跑的。
/home/8TDisk/zhang/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/executor.py:1583: UserWarning: Standalone executor is not used for data parallel
  warnings.warn(
W1128 16:42:40.211668 4160744 parallel_executor.cc:666] Cannot enable P2P access from 0 to 1
W1128 16:42:40.211804 4160744 parallel_executor.cc:666] Cannot enable P2P access from 0 to 2
W1128 16:42:40.211812 4160744 parallel_executor.cc:666] Cannot enable P2P access from 0 to 3
W1128 16:42:40.211831 4160744 parallel_executor.cc:666] Cannot enable P2P access from 1 to 0
W1128 16:42:40.211839 4160744 parallel_executor.cc:666] Cannot enable P2P access from 1 to 2
W1128 16:42:40.211844 4160744 parallel_executor.cc:666] Cannot enable P2P access from 1 to 3
W1128 16:42:40.211849 4160744 parallel_executor.cc:666] Cannot enable P2P access from 2 to 0
W1128 16:42:40.211855 4160744 parallel_executor.cc:666] Cannot enable P2P access from 2 to 1
W1128 16:42:40.211864 4160744 parallel_executor.cc:666] Cannot enable P2P access from 2 to 3
W1128 16:42:40.211872 4160744 parallel_executor.cc:666] Cannot enable P2P access from 3 to 0
W1128 16:42:40.211877 4160744 parallel_executor.cc:666] Cannot enable P2P access from 3 to 1
W1128 16:42:40.211882 4160744 parallel_executor.cc:666] Cannot enable P2P access from 3 to 2

其次，在使用多卡命令跑训练时，会一直卡在一个地方，重复报这个错误。

I1128 16:31:41.433620 4158784 tcp_utils.cc:181] The server starts to listen on IP_ANY:39291
I1128 16:33:51.831167 4158784 tcp_utils.cc:107] Retry to connect to 0.1.68.146:39291 while the server is not yet listening.
I1128 16:36:04.951241 4158784 tcp_utils.cc:107] Retry to connect to 0.1.68.146:39291 while the server is not yet listening.

请问这是什么原因？怎么解决？

**Comment by haoyuying** [comment]
您好，先检查下paddle是否正确安装并且能够使用，具体参考https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/windows-pip.html

**Comment by ZhangJingweiYa** [comment]
> 您好，先检查下paddle是否正确安装并且能够使用，具体参考https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/windows-pip.html

是正确安装，并且能够使用的。具体如下：

(paddle) z:[/PaddleSeg]export CUDA_VISIBLE_DEVICES=1,2,3
(paddle) z:[/PaddleSeg]python -c "import paddle;paddle.utils.run_check()"
Running verify PaddlePaddle program ... 
W1128 20:06:08.685379  9822 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.0
W1128 20:06:08.703063  9822 gpu_resources.cc:91] device: 0, cuDNN Version: 8.0.
PaddlePaddle works well on 1 GPU.
/z/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/executor.py:1583: UserWarning: Standalone executor is not used for data parallel
  warnings.warn(
W1128 20:06:32.619498  9822 parallel_executor.cc:666] Cannot enable P2P access from 0 to 1
W1128 20:06:32.619653  9822 parallel_executor.cc:666] Cannot enable P2P access from 0 to 2
W1128 20:06:32.619657  9822 parallel_executor.cc:666] Cannot enable P2P access from 1 to 0
W1128 20:06:32.619660  9822 parallel_executor.cc:666] Cannot enable P2P access from 1 to 2
W1128 20:06:32.619663  9822 parallel_executor.cc:666] Cannot enable P2P access from 2 to 0
W1128 20:06:32.619666  9822 parallel_executor.cc:666] Cannot enable P2P access from 2 to 1
W1128 20:06:47.152163  9822 fuse_all_reduce_op_pass.cc:79] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
PaddlePaddle works well on 3 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

@haoyuying

**Comment by juncaipeng** [comment]
还有问题吗？ 这个log来看是框架底层问题，具体无法直接定位出来，要不先试下paddle2.3？

**Comment by 4399123** [comment]
这个问题后面是如何解决的呀，我也遇到了和你相同的问题
