### ISSUE TITLE
PanopticDeepLab在ADE20K训练集实现全景分割

### ISSUE THREAD

**Issue by Destinycjk** [PaddlePaddle/PaddleSeg#2778]
在阅读Panoptic Segm,entation论文时，我看到作者同时在Cityscapes、ADE20K与Mapillary Vistas三个训练集上实现了全景分割功能，目前在PanopticDeepLab中已有在Cityscapes实现全景分割的Demo。我想知道PanopticDeepLab是否有在ADE20K上实现全景分割的Demo，或者想要实现在ADE20K上的全景分割，我应该怎样构建相应的训练集呢？

**Comment by Bobholamovic** [comment]
PanopticDeepLab目前暂时没有在ADE20K数据集上实现的全景分割demo。如果想要实现ADE20K数据集上的全景分割，需要仿照`datasets/cityscapes_panoptic.py`编写数据集读取接口，并（可能需要）对应修改训练标签生成和模型后处理相关逻辑。该工作比较tricky，实现起来可能需要注意很多细节，如果你尝试自己实现的话，欢迎在issue里和我们交流讨论。

此外，我们正在开发更通用、更易二次开发的全景分割功能，并且已经取得一定进展，PaddleSeg未来的新版本将提供这一功能。

**Comment by Destinycjk** [comment]
好的，非常感谢您的回复，我后续再看一下在ADE20K复现全景分割的可行性，另外，非常期待Paddle最新的全景分割功能，请问这个功能大概将在什么时候上线呢？是否能够更方便用户在自己的应用场景下的数据集上实现全景分割呢？

**Comment by Bobholamovic** [comment]
> 好的，非常感谢您的回复，我后续再看一下在ADE20K复现全景分割的可行性，另外，非常期待Paddle最新的全景分割功能，请问这个功能大概将在什么时候上线呢？是否能够更方便用户在自己的应用场景下的数据集上实现全景分割呢？

感谢你的肯定。强化的全景分割功能最早将在v2.8版本上线（预计发布时间为2023年第一季度），我们有计划支持方便用户自己扩展的全景分割数据集接口。

**Comment by Bobholamovic** [comment]
你好，我们在 develop 分支完成了全景分割功能的开发，不过目前可能尚不稳定。如想尝鲜可试试：
https://github.com/PaddlePaddle/PaddleSeg/tree/develop/contrib/PanopticSeg

自定义数据集相关文档：https://github.com/PaddlePaddle/PaddleSeg/blob/develop/contrib/PanopticSeg/docs/dev_guide_cn.md#4-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E9%9B%86%E5%BC%80%E5%8F%91

**Comment by Destinycjk** [comment]
好的，非常感谢您的告知！我有时间的时候尝试复现一下，有问题再向您请教！
