### ISSUE TITLE
[General Issue]说真的，你们这个东西，太难用了吧，跑个你们新开源的rtformer模型，怎么train的找半天都不知道在那里，跑起来到处报错，我有点无语

### ISSUE THREAD

**Issue by TaoZhang1993** [PaddlePaddle/PaddleSeg#2779]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by yangtianyu92** [comment]
是的，事实上2.7版本连快速开始的DEMO都跑不起来，太离谱了。上传的肯定没上传更新完整。

**Comment by crisz94** [comment]
Factos

**Comment by yangtianyu92** [comment]
淡定，paddle是要自己看代码修改的,但是人能写出这种框架模型，至少水平比我们这些混饭吃的强的多不是吗。

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年10月18日 16:52 |
| 收件人 | PaddlePaddle/PaddleSeg ***@***.***> |
| 抄送人 | yangtianyu92 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleSeg] [General Issue]说真的，你们这个东西，太难用了吧，跑个你们新开源的rtformer模型，怎么train的找半天都不知道在那里，跑起来到处报错，我有点无语 (Issue #2779) |

Factos
