### ISSUE TITLE
新版本C++读取yaml某些字段demo yaml没有给出，请更新一下

### ISSUE THREAD

**Issue by JianJingGao** [PaddlePaddle/PaddleSeg#278]
![image](https://user-images.githubusercontent.com/51236891/83390877-39e0cb00-a425-11ea-9a27-398be4b752fd.png)
目前发现的这个，应该还有别的，请对比同步下文档，谢谢啦

**Comment by JianJingGao** [comment]
搬个板凳，等开发童鞋回复

**Comment by JianJingGao** [comment]
然后我发现这个字段在PaddleDetection的yaml中存在，随我我就添加到humnaseg这个.yaml中，DetectionPreProcessor，运行，凉凉

**Comment by JianJingGao** [comment]
随后调试把值赋为PRE_PROCESSOR: "SegPreProcessor"
继续单步，报错
![image](https://user-images.githubusercontent.com/51236891/83393422-567f0200-a429-11ea-9fc2-e871601e6f55.png)

**Comment by JianJingGao** [comment]
继续蹲，在线蹲

**Comment by Channingss** [comment]
@JianJingGao 请问是什么模型呢？有参考文档的这部分吗，MODEL_PATH路径使用绝对路径。https://github.com/PaddlePaddle/PaddleSeg/tree/release/v0.5.0/deploy/cpp#42-%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。
