### ISSUE TITLE
paddleseg_matting模型预测的时候，可以一个模型同时预测多张图片吗

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleSeg#2782]
一个模型可以同时推理预测多张图片吗，相当与训练的batchsize那样同时喂进多张图片，同时出来多个结果，如果不能的话，代码怎么写可以指导一下吗，万分感谢

**Comment by wuyefeilin** [comment]
如果有多张显卡可以利用python -m paddle.distributed.launch 进行预测，单每张卡的bs还是1

如果要提升单张卡的bs需要对预测流程的前后处理进行batch的处理https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/Matting/ppmatting/core/predict.py

**Comment by jingmingtao** [comment]
我想提升单张卡的bs，这个batch处理的话，有代码参考吗

**Comment by jingmingtao** [comment]
进行batch处理跟训练的时候的batch处理一样吗

**Comment by wuyefeilin** [comment]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/Matting/deploy/python/infer.py#L344 可以参考这边的流程

**Comment by jingmingtao** [comment]
ok,thanks

**Comment by jingmingtao** [comment]
> https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/Matting/deploy/python/infer.py#L344 可以参考这边的流程

这个infer.py就已经实现实现了一个模型同时推理多张图片对吧，那我可以直接拿来用就可以把？

**Comment by jingmingtao** [comment]
我看这个代码里边也是在一个batch里边循环推理，也是一张图片一张图片的在一个batch里边推理，我想要的是几张图片同时进行推理，这样可行吗

**Comment by jingmingtao** [comment]
因为请求数据是同时请求，所以图片也应该同时进行推理，这样能实现吗

**Comment by wuyefeilin** [comment]
这个就是多张图片进行推理的哈。前后处理本来就是逐张进行的，如果求并行你可以考虑多进程

**Comment by jingmingtao** [comment]
好的
