### ISSUE TITLE
使用paddle2onnx转换由PaddleSilm量化训练导出的模型出现不支持的算子

### ISSUE THREAD

**Issue by fanxiaochen456** [PaddlePaddle/PaddleSeg#2787]
您好，我使用PaddleSeg2.5训练模型，然后使用PaddleSilm量化训练导出模型，这是我的模型
![image](https://user-images.githubusercontent.com/101849755/204725682-ae284559-4797-4e53-9801-5a8d016208cd.png)
使用PaddleX和C++部署PaddleSeg模型在本地推理CPU的时间为1.8-2.0s，推理速度缓慢，现在想使用OpenVINO进行模型加速，使用最新的paddle2onnx1.0.3进行模型转换，使用指令是：
 paddle2onnx --model_dir output1010/ --model_filename model.pdmodel --params_filename model.pdiparams --save_file model_seg.onnx
出现以下错误信息：
![image](https://user-images.githubusercontent.com/101849755/204726422-a03c3111-4869-4c40-ad98-63508c25c7ca.png)

**Comment by wuyefeilin** [comment]
--opset_version 11  加上这个参数试试

**Comment by fanxiaochen456** [comment]
@wuyefeilin还是一样的错误信息
![image](https://user-images.githubusercontent.com/101849755/204980288-22577608-ce76-430a-a3a4-1b1886090b37.png)

**Comment by wuyefeilin** [comment]
看来是出现了不支持的op， 可以到https://github.com/PaddlePaddle/Paddle2ONNX 咨询一下
