### ISSUE TITLE
想请教下Model Export步骤的作用与目的是什么

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleSeg#2788]

**Comment by jingmingtao** [comment]
您好，在paddleseg/matting我想请教一下，Model Export步骤的作用与目的是什么 ，如果我不执行这一步而去直接infer.py，可以吗

**Comment by Bobholamovic** [comment]
你好，PaddlePaddle是一个[动静统一](https://www.paddlepaddle.org.cn/overview)的深度学习框架，在开发时使用推荐使用调试更方便的动态图模式，在部署时推荐使用效率更高的静态图模式，而模型导出的作用就是将训练得到的动态图格式模型转为静态图格式。
