### ISSUE TITLE
在paddle-seg/Mating使用PaddleSeg/Matting/deploy/python/infer.py 设置batchisize为2时，报fg与alpha的shape不同的问题

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleSeg#2793]
报错时fg与alpha的shape不同，不能进行拼接，这是什么原因导致的，我看原图是(854, 640, 3)，对应的alpha就变成了(1334, 600, 1)
![image](https://user-images.githubusercontent.com/114384977/204945720-e030401c-4cdb-48e0-bfa0-7d8a3ff905dd.png)

**Comment by jingmingtao** [comment]
难道是因为按照长边或者短边resize的问题？

**Comment by jingmingtao** [comment]
我的deploy.yaml如下：
![image](https://user-images.githubusercontent.com/114384977/204950382-5e3fdf2c-f7c4-4f92-b4a6-ab5020912767.png)

**Comment by wuyefeilin** [comment]
两个concat的图像大小不一致。你看看是否使用错了图像呢

**Comment by jingmingtao** [comment]
意思是输入的两个图像大小必须一致对吗，如果不一样大小，需要提前进行resize的处理，再进行预测吗？

**Comment by jingmingtao** [comment]
那行代码的意思：concat的是fg与alpha呀，我只是输入了fg，并没有输入alpha，alpha是预测出来，并经过后处理得到的

**Comment by wuyefeilin** [comment]
alpha预测后需要回复到原始大小，另外fg应该使用原图进行前景评估后得到的，而不是用经过预处理的图像

**Comment by jingmingtao** [comment]
我将两张输入的rgb图像，他们的长宽shape分别为(854, 640, 3）(1334, 600, 3)，你的意思是这两张输入图片必须大小一样吗

**Comment by jingmingtao** [comment]
我做了个实验，发现只要我输入在同一个batch里边的图片尺寸大小不同，就一定报错，是这样吗；只要图片尺寸相同就不报错；

**Comment by jingmingtao** [comment]
那这样不行啊，现实中图片的大小是不一样的，这个怎么办呢

**Comment by jingmingtao** [comment]
是不是我的transform设置有问题呢，我晕了尺寸计算倒过来倒过去的，能不能指导下

**Comment by jingmingtao** [comment]
这个deplo.yaml是执行export.py产生的，根据我训练的config的yaml，应该没问题的，我训练的时候就这样设置的

**Comment by jingmingtao** [comment]
我看咱们的代码里也有恢复alpha的后处理就完成了，但是就是不对，

**Comment by wuyefeilin** [comment]
你直接调用deploy/python/infer.py 将--batch_size设置成2就行了，不需要去改代码的

**Comment by wuyefeilin** [comment]
> 是不是我的transform设置有问题呢，我晕了尺寸计算倒过来倒过去的，能不能指导下

建议先输入单张图片搞清楚逻辑后再去修改代码哈

**Comment by jingmingtao** [comment]
现在代码是不支持同一batch里边不同尺寸的输入对吗

**Comment by wuyefeilin** [comment]
我这边复现一下哈

**Comment by jingmingtao** [comment]
我的两张图片的尺寸分别为(854, 640, 3)、(1280, 720, 3)；当batchsize=1，经过precross的transform后包括resize_short、ResizeToIntMult，得到的尺寸分别为(1, 3, 672, 512)、(1, 3, 896, 512)是正确的，当batchsize=2时，出来的(2, 3, 672, 512)，然后就会有(1280, 720)的fg与alpha(854, 640)的尺寸不统一的问题了

**Comment by jingmingtao** [comment]
是不是transform的问题，还是说当batchsize=2时，输入进去推理的尺寸必须统一，就比如(2, 3, 672, 512)，而不能（(854, 640, 3)、(1280, 720, 3)）这样呢

**Comment by jingmingtao** [comment]
好像代码只是读了两遍第一张图片

**Comment by jingmingtao** [comment]
生成的结果很明显不对：
![Uploading image.png…]()

**Comment by jingmingtao** [comment]
![image](https://user-images.githubusercontent.com/114384977/205012417-12e30af8-be4c-4337-be7d-68289fe985bf.png)
结果来看就是第一张执行了两边，并且将第一张产生的apha图贴到了第二张身上，由于报错的那两张尺寸不同，因此第一张图产生的alpha图贴不到同batch的另一张fg上，导致的报错

**Comment by jingmingtao** [comment]
你看图片的名字就能看出来是这么回事

**Comment by wuyefeilin** [comment]
这边复现了你的问题，已经更新了。你更新一下2.7分支的代码就可以了

**Comment by jingmingtao** [comment]
我重新下载一下resease2.7就可以了吧

**Comment by wuyefeilin** [comment]
欢迎适用PaddleSeg产品，欢迎反馈使用感受并给予改进的建议
