### ISSUE TITLE
采用PaddleSeg/Matting/deploy/python/infer.py打开--use_trt使用加速的时候报错

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleSeg#2796]
报错如下：
![Uploading image.png…]()

**Comment by jingmingtao** [comment]
![image](https://user-images.githubusercontent.com/114384977/204971416-732062ac-dfde-43f8-8eee-9911c131a2e9.png)

**Comment by wuyefeilin** [comment]
参考以下文档确保trt环境部署正常https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/docs/deployment/inference/python_inference_cn.md#2-%E5%87%86%E5%A4%87%E9%83%A8%E7%BD%B2%E7%8E%AF%E5%A2%83
https://www.paddlepaddle.org.cn/inference/v2.4/guides/nv_gpu_infer/gpu_trt_infer.html
