### ISSUE TITLE
是否有设置边缘裁剪的功能，比如裁剪零散的发丝

### ISSUE THREAD

**Issue by 983183947** [PaddlePaddle/PaddleSeg#2802]
我现在用human_pp_humanseg进行人像抠图，抠图效果已经比较理想。现在有个需求就是抠图时想去掉人物周边相对零散的碎发（特别是长头发的女生），是否有好的方案推荐。望指导～

**Comment by shiyutang** [comment]
可以给出一些示例图片查看具体情况。

**Comment by 983183947** [comment]
![image](https://user-images.githubusercontent.com/25240344/205198648-b5e4b09a-5196-460c-9a2d-85e01b2c7a52.png)
![image](https://user-images.githubusercontent.com/25240344/205198688-92738527-fa93-49b9-9dad-54022b4d8264.png)
第一张是原图，第二张是抠图后的。两边的耳根旁边有一些碎发想去掉，请教有没有好的处理方案，感谢～

**Comment by juncaipeng** [comment]
建议使用opencv自己调试下，比如形态学开闭运算。
