### ISSUE TITLE
获取到paddleseg预测结果的序号

### ISSUE THREAD

**Issue by fanxiaochen456** [PaddlePaddle/PaddleSeg#2804]
请问怎么可以获取到paddleseg模型预测结果的ID呢，就是一张图中有多个同一类别的物体，这些物体之间存在粘连现象，预测结果的粘连物体的mask也是连在一起的，想通过ID一个一个的获取到单个物体，请问要如何修改呢？

**Comment by haoyuying** [comment]
语义分割中的同一类的物体是不进行区分的，想要获取单个物体应该使用实例分割模型，目前paddleseg没有提供实例分割模型，可以尝试使用全景分割模型获得预测结果。
