### ISSUE TITLE
请问EIseg 生成的json文件是labelme格式的吗？

### ISSUE THREAD

**Issue by morganluo** [PaddlePaddle/PaddleSeg#2805]
Welcome to propose a new feature! To help us understand your great feature, please provide following information:
1. A clear and concise description of the proposed feature.
2. Tell us why the feature is useful. 
3. If possible, please show related codes .

---

欢迎提出一个新功能需求，为了帮助我们更好理解您的需求，辛苦提供下面信息：
1. 清晰简洁的语言提出新功能需求。
2. 请描述这个需求的必要性。
3. 如果可以，辛苦您提供相关代码实现效果。

**Comment by haoyuying** [comment]
您好，目前不是，下个版本我们会将json和labelme 对齐，请持续关注eiseg发展动态。

**Comment by morganluo** [comment]
好嘞，谢谢。请问下一个版本大概什么时候能发布呀？

**Comment by haoyuying** [comment]
最晚12月底，请持续关注paddleseg最新动态。

**Comment by monkeycc** [comment]
12月底 期待新版本 
确实想要json和labelme 对齐

**Comment by morganluo** [comment]
请问版本更新完成了吗，eiseg界面没有看到更新消息。

**Comment by lwh104** [comment]
请问，什么时候能出eiseg的json转labelme的json格式

**Comment by monkeycc** [comment]
请问，什么时候能出eiseg的json转labelme的json格式

2024 
2025 
2026
.......

**Comment by shiyutang** [comment]
大家好，EISeg目前已经不再维护，辛苦大家自行实现。
