### ISSUE TITLE
关于paddleseg/matting中deploy/python/infer.py中cpu_threads这个参数的原理请教，enable_mkldnn的原理？

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleSeg#2808]
您好，我想请教下paddleseg/matting中deploy/python/infer.py中cpu_threads这个参数的原理。
问题1：cpu_threads如果设置10 的话，意思是在cpu上进行推理，并开启了10个线程，每个线程处理一张吗？
问题2:我想看看cpu_threads的代码的话，set_cpu_math_library_num_threads函数在哪里看，我根据import的关联性，我找了很多地方，看了paddle底层代码，也没找到，我想找一下，可以提供代码位置吗？
问题3：enable_mkldnn的原理，请问一下代码位置，想要阅读一下。
万分感谢
![image](https://user-images.githubusercontent.com/114384977/205564812-cb8d2a0c-534f-48ad-a3a5-19883559cac0.png)

**Comment by haoyuying** [comment]
您好，您的问题主要是paddle inference问题，建议您到https://github.com/PaddlePaddle/Paddle
提问，以便得到更好的回复。inference文档位置：https://www.paddlepaddle.org.cn/inference/v2.4/guides/introduction/index_intro.html

**Comment by juncaipeng** [comment]
1. cpu_threads是模型内部的kernel可能并行计算的线程数
2. python封装了c++的set_cpu_math_library_num_threads，不太好看到
3. enable_mkldnn就是kenerl内部会使用mkldnn库进行加速，如果支持avx指令集，会有较快加速。

**Comment by fortheday520** [comment]
cpu_threads模型内部的kernel是默认的吗，cpu_threads、enable_mkldnn这两个参数是不是只能我选择divce为 cpu的时候才有用；如果我用gpu去推理，是不是没有用？

**Comment by juncaipeng** [comment]
是的，只在cpu上有效。

**Comment by jingmingtao** [comment]
请问那在使用deploy/python/infer.py进行推理预测时，选择cpu快还是gpu快呢，假设cpu的加速都开了

**Comment by wuyefeilin** [comment]
一版是gpu比较快的，优选gpu
