### ISSUE TITLE
pose摔倒检测问题？

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/PaddleSeg#2811]
我想问下，对于新加的数据怎么转化coco所需要的关键点训练数据，因为我好像没有看到labelme转化的脚本中，有对遮挡关键点怎么处理的样式，有相关的文档嘛，半身的关键点标注，一个侧面的关键点标注

**Comment by wuyefeilin** [comment]
PaddleSeg实现的是语义分割的相关标注，关键点检测任务可以移步PaddleDetection进行咨询：https://github.com/PaddlePaddle/PaddleDetection

**Comment by chen-del** [comment]
@wuyefeilin ，好的
