### ISSUE TITLE
在MSD_Lung训练NNUNet时遇到的问题

### ISSUE THREAD

**Issue by josephydu** [PaddlePaddle/PaddleSeg#2814]
我在对paddleseg里面的medicelseg模型的nnunet网络进行debug时，发现了如下问题，想问问您是如何解决的。
`训练命令如下：!python nnunet/single_fold_eval.py --config configs/nnunet/msd_lung/nnunet_2d_msd_lung_fold0.yml --model_path output/2d_unet/fold0/iter_30000/model.pdparams --val_save_folder output/2d_val --precision fp16`
数据集为：`MSD_TASK06_Lung`
我在模型初始化时，进入到了创建`dataset_properties.pkl`的部分，问题有这部分产生，我用debug定位到了具体问题所在。debug过程如下：
1.程序来到了`MedicalSeg/nnunet/datasets/dataset.py`这个文件，在创建`dataset_properties.pkl`时，如下所示
![image](https://user-images.githubusercontent.com/85502239/206209803-01a3e2ab-d94f-41a3-951d-d7e345274ec2.png)
2.当程序走到第131行`dataset_analyzer.analyze_dataset(collect_intensityproperties)`的时候报错。于是在第二次debug的时候我进入了这个方法：
![image](https://user-images.githubusercontent.com/85502239/206207893-b5a70eec-56f0-4714-bb70-1b33e1c1f55e.png)
3.然后发现是第169行`intensityproperties = self.collect_intensity_properties(len(modalities))`出了问题，我再次进入到这个方法
<img width="908" alt="image" src="https://user-images.githubusercontent.com/85502239/206208109-0fce476b-56fa-4ddc-b3a5-f173343064c2.png">
4.如上所示，最终出问题的代码在124行，` voxels = p.starmap(self._get_voxels_in_foreground, zip(self.patient_identifiers, [mod_id] * len(self.patient_identifiers)))`，于是我进入了方法`self._get_voxels_in_foreground`：
<img width="747" alt="image" src="https://user-images.githubusercontent.com/85502239/206208911-2a477e91-70ff-423c-bb53-d0c996a2afe2.png">
5.最终问题由99行`all_data = np.load(os.path.join(self.folder_with_cropped_data, patient_identifier) + ".npz")['dataset']`抛出，我用pycharm调试过程中的计算器计算了`np.load(os.path.join(self.folder_with_cropped_data, patient_identifier) + ".npz")`，结果如下：
![image](https://user-images.githubusercontent.com/85502239/206209286-9ff1c06a-d684-4eba-9ca3-83ceba892c8c.png)
6.显然，对于上述结果进行['dataset']`操作是报错的。编译器帮我证明了这一点，最后报错输出如下：
![image](https://user-images.githubusercontent.com/85502239/206209573-4cf3ad87-07d9-4927-9886-dd87197f4ed6.png)

**Comment by josephydu** [comment]
我是在我本机的windows上运行的，在aistudio上时没有问题的

**Comment by justld** [comment]
可以打印os.path.join(self.folder_with_cropped_data, patient_identifier) + ".npz"看一下具体路径，并到该文件夹内查看该文件是否存在。数据处理阶段是否有中断程序运行呢？在预处理进行阶段，程序不能终止，可以考虑删除之前预处理生成的数据，重新运行。

**Comment by josephydu** [comment]
> 可以打印os.path.join(self.folder_with_cropped_data, patient_identifier) + ".npz"看一下具体路径，并到该文件夹内查看该文件是否存在。数据处理阶段是否有中断程序运行呢？在预处理进行阶段，程序不能终止，可以考虑删除之前预处理生成的数据，重新运行。

您好，我可能发现了问题，不知道是不是因为版本更新修改了源码或其他未知原因：
![206208911-2a477e91-70ff-423c-bb53-d0c996a2afe2](https://user-images.githubusercontent.com/85502239/206354292-af57c64d-2847-45d8-aad3-ff59f1832f5e.png)
这一函数中，我对比了仓库中的同样文件的源码，发现
![image](https://user-images.githubusercontent.com/85502239/206353724-87050939-9316-460a-89a7-a52df9446fc0.png)
我将`dataset`修改为`data`，程序就能正确运行了。

**Comment by justld** [comment]
hi，该部分代码没有修改过哦，后续有其他问题可以继续提issue。
