### ISSUE TITLE
[Feature Request] 请问使用C++ paddle inference推理，是否产生类似.engine的文件，这样下次使用不需要再经历.pdmodel模型转换的过程？

### ISSUE THREAD

**Issue by clw5180** [PaddlePaddle/PaddleSeg#2820]
如题

**Comment by Bobholamovic** [comment]
你好，Paddle Inference 暂时没有这个功能~ 可以在 [Paddle 框架 issue 区](https://github.com/PaddlePaddle/Paddle/issues)提一个 feature request。
