### ISSUE TITLE
能请教一下使用ps制作matting人像抠图的alpha操作步骤吗

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleSeg#2822]
能请教一下使用ps制作matting人像抠图的alpha操作步骤吗，
我自己研究的步骤，不知道对不对，想跟咱们学习一下，使用ps制作alpha的规范步骤，可以指导一下吗

**Comment by jingmingtao** [comment]
人像分割的mask图与人像抠图的alpha在使用ps制作有什么不同的步骤呢，我现在都不知道自己制作的是否正确、规范，请求指导操作步骤：大体上的步骤也可以；

**Comment by wuyefeilin** [comment]
人像分割可以用eiseg进行标注，ps获取alpha的话网上教程很多，只要自己觉得标注结果满足要求就行了
