### ISSUE TITLE
训练可视化出问题怎么解决

### ISSUE THREAD

**Issue by xiaowuzilou** [PaddlePaddle/PaddleSeg#283]
(base) E:\PaddleSeg-develop>visualdl --logdir train_log --host 10.2.173.206 --port 8888

UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 11321: illegal multibyte sequence

**Comment by ShenYuhan** [comment]
您使用visualdl版本是多少，升级到最新版试试
```shell
pip install visualdl==2.0.0b4 -U
```

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。
