### ISSUE TITLE
EISegMed3D导入3D slicer

### ISSUE THREAD

**Issue by FredJChang** [PaddlePaddle/PaddleSeg#2830]
The module factory manager reported an error. One or more of the requested module(s) and/or dependencies thereof may not have been loaded.
EISeg-med导入3D slicer，一定需要CUDA支持吗

**Comment by shiyutang** [comment]
目前EISeg-Med3D使用GPU推理，因此需要电脑上安装cuda或者其他GPU加速库，并配合相应版本的paddle。

**Comment by shiyutang** [comment]
根据你的安装问题描述，可以看到是如下问题：https://github.com/PaddlePaddle/PaddleSeg/blob/release%2F2.7/EISeg/med3d/README.md

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/34859558/206948222-9e6dbc93-1930-4d88-a9c4-6b26a7a8dbcb.png">

**Comment by Antoniaaa** [comment]
> 根据你的安装问题描述，可以看到是如下问题：https://github.com/PaddlePaddle/PaddleSeg/blob/release%2F2.7/EISeg/med3d/README.md
> 
> <img alt="image" width="1089" src="https://user-images.githubusercontent.com/34859558/206948222-9e6dbc93-1930-4d88-a9c4-6b26a7a8dbcb.png">

我想请问一下 具体是哪些库没有安装啊 还有使用第二步的步骤 就是 git clone 的语句怎么写呀 非常感谢

**Comment by shiyutang** [comment]
我们只需要安装paddle和paddleseg和med3d目录下 requirements.txt. 如果不确定是那些没有安装的话，可以重新走一遍流程。

git clone语句如下：
git clone https://github.com/PaddlePaddle/PaddleSeg.git
