### ISSUE TITLE
在RTFormer中的一个术语的请教

### ISSUE THREAD

**Issue by coallar** [PaddlePaddle/PaddleSeg#2831]
RTFormer的性能结果着实优秀。在阅读论文过程中，我注意到专业术语 global context。如摘要中:

we find that cross-resolution attention is more efficient to gather global context information for high-resolution branch by spreading the high level knowledge learnedfrom low-resolution branch.

global context 是指通过低分辨率的高语义信息来去引导高分辨率分支对类别的识别吗？
在BiSeNetV2中，Context Embedding Block是通过类似通道维度上实现。咱们则是通过coss-attention 是在空间维度上实现，这两者有什么区别吗？

**Comment by juncaipeng** [comment]
对的，低分辨率特征图的语义信息更丰富，可以和高分辨率特征图进行融合。
本质都是信息融合，只是不同维度和实现上的差别。
