### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by urielrosen1981** [PaddlePaddle/PaddleSeg#2832]
Thanks for your bug report. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Full codes: (if you modify any original code，please show the comparison of the codes before and after)
 7. Detailed error information, releated running log: (if using multi-gpus，the log is saved to log/worklog.0 by default)
 8. Running command or reproduce details：
 9. Additional context: (Add any other context about the problem)

1. paddleseg:2.6-gpu-cuda10.2-cudnn7
2.  PaddlePaddle version:2.3.0
3. Operation system:rocky linux version 8.5 running a container with singularity.
4. Python version:Python 3.7.0
5. CUDA/cuDNN version: cuda11.0 -cudnn7
6. not modified codes
7.  python
Python 3.7.0 (default, May  7 2022, 07:55:29)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
W1208 13:48:01.483716 1049202 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 11.0, Runtime API Version: 10.2
W1208 13:48:01.544704 1049202 gpu_context.cc:306] device: 0, cuDNN Version: 7.6.
PaddlePaddle works well on 1 GPU.

W1208 14:24:49.248163 1049202 fuse_all_reduce_op_pass.cc:76] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
WARNING:root:PaddlePaddle meets some problem with 2 GPUs. This may be caused by:
 1. There is not enough GPUs visible on your system
 2. Some GPUs are occupied by other process now
 3. NVIDIA-NCCL2 is not installed correctly on your system. Please follow instruction on https://github.com/NVIDIA/nccl-tests
 to test your NCCL, or reinstall it following https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html
WARNING:root:
 Original Error is: (External) CUDA error(209), no kernel image is available for execution on the device.
  [Hint: 'cudaErrorNoKernelImageForDevice'. This indicates that there is no kernel image available that is suitable for the device. This can occur when a user specifiescode generation options for a particular CUDA source file that do not include the corresponding device configuration.] (at /paddle/paddle/fluid/framework/details/all_reduce_op_handle.cc:299)

PaddlePaddle is installed successfully ONLY for single GPU! Let's start deep learning with PaddlePaddle now.

8. in general I am trying to run paddleseg using a docker container on singularity(containerized environment for HPC),
when running the initial test    paddle.utils.run_check() I get the above errors  , also when running the program it crashed with similar errors . 
I would like to know if this is a known issue or someone knows how to run this using a singulrity container :
my singularity command to run from shell is:

singularity shell --nv   /data/bin/singularity_images/paddleseg:2.6-gpu-cuda10.2-cudnn7-f9e1fc.sif  

I also tried various versions of the docker images from docker hub with same result.
please advice.

**Comment by haoyuying** [comment]
This issue is caused by paddle installation, you may open an issue in paddle's repo to get  a professional reply. 
Paddle repo： https://github.com/PaddlePaddle/Paddle/issues

**Comment by ashutoshIITK** [comment]
To solve this problem, just install paddlepaddle-gpu with appropriate cuda version for your machine. Make sure your the installed version has equal or higher cuda version than your machine
