### ISSUE TITLE
peddleseg C++部署时如何输出伪彩色图

### ISSUE THREAD

**Issue by aiwenzhu** [PaddlePaddle/PaddleSeg#2834]
在peddleseg c++部署推理出的结果是灰度图，但是不同图片的推理结果中的同一类别的灰度虽然接近但是不一样，导致有时候难以判断是哪个类别，能不能让同一类别的颜色或灰度保持一致啊

**Comment by juncaipeng** [comment]
可以先保存预测结果图片，然后参考下面文档进行伪彩色显示。

https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/docs/data/marker/marker_cn.md#13-%E7%81%B0%E5%BA%A6%E6%A0%87%E6%B3%A8%E5%9B%BE%E8%BD%AC%E6%8D%A2%E4%B8%BA%E4%BC%AA%E5%BD%A9%E8%89%B2%E6%A0%87%E6%B3%A8%E5%9B%BE-%E9%9D%9E%E5%BF%85%E9%A1%BB

**Comment by aiwenzhu** [comment]
> 可以先保存预测结果图片，然后参考下面文档进行伪彩色显示。
> 
> https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/docs/data/marker/marker_cn.md#13-%E7%81%B0%E5%BA%A6%E6%A0%87%E6%B3%A8%E5%9B%BE%E8%BD%AC%E6%8D%A2%E4%B8%BA%E4%BC%AA%E5%BD%A9%E8%89%B2%E6%A0%87%E6%B3%A8%E5%9B%BE-%E9%9D%9E%E5%BF%85%E9%A1%BB
你好，为什么同一类别在不同图片的结果图中灰度值不同那，我该怎么判断每张结果图中的类别，有没有结果图对应的类别图

**Comment by juncaipeng** [comment]
是相同的啊，是不是你模型预测错误啊

**Comment by aiwenzhu** [comment]
> 是相同的啊，是不是你模型预测错误啊

我测了很多图片，看上去预测的都是对的，只是同一个类别在不同结果图中的灰度值有大约20以内的差别

**Comment by juncaipeng** [comment]
你说的结果图中的灰度值，是使用c++预测代码保存的结果图吗？ 
提供的c++示例，里面有直方图均衡化的代码，为了直观显示。  如果需要得到准确的分割标签，可以删掉直方图均衡化的代码。
