### ISSUE TITLE
python /PaddleSeg/EISeg/eiseg/exe.py stucked

### ISSUE THREAD

**Issue by BeIFreedom** [PaddlePaddle/PaddleSeg#2836]
I follow the steps below to install：
conda create -n testseg python==3.8
conda activate testseg
conda install qtpy==1.10.0 
conda install qt==5.9.7 
conda install pyqt==5.9.2 
pip install opencv-python  
python -m pip install paddlepaddle -i [https://mirror.baidu.com/pypi/simple ](https://mirror.baidu.com/pypi/simple%E2%80%A9)
conda install pyyaml 
conda install matplotlib 
conda install scikit-Image 
python xxx/PaddleSeg//EISeg/eiseg/exe.py

Stuck in this step
![image](https://user-images.githubusercontent.com/72512415/207008170-5387e40b-cee4-4f0d-a303-53c00a076f2e.png)
What causes it？

**Comment by haoyuying** [comment]
You may refer this link to install eiseg:
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/EISeg/docs/install_en.md
 we recommend you to use  'pip install eiseg' to try again.

**Comment by BeIFreedom** [comment]
> You may refer this link to install eiseg: https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/EISeg/docs/install_en.md we recommend you to use 'pip install eiseg' to try again.

I adopted your recommendation, but the result is the same

**Comment by haoyuying** [comment]
Is there any error message  for ' pip install eiseg' or your pyqt has been installed successfully?

**Comment by BeIFreedom** [comment]
> Is there any error message for ' pip install eiseg' or your pyqt has been installed successfully?

I still failed to run on Linux（Ubuntu server） and reported no errors. I ran successfully on Windows
