### ISSUE TITLE
[General Issue]PaddleSeg中MobileSeg	MobileNetV2的精度与log日志中不符

### ISSUE THREAD

**Issue by cloud9wj** [PaddlePaddle/PaddleSeg#2837]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/configs/mobileseg/README_cn.md 中 backbone为MobileNetV2的mIoU是73.94%，但是右边log中迭代到80000 iter时best mIoU为68.66%,请问以哪个值为准

**Comment by juncaipeng** [comment]
下载log文件，查看精度如下啊，是训练160k，不是80k。
![image](https://user-images.githubusercontent.com/52520497/207312881-c31fa2c3-566d-4fcb-a6e1-46d5b3d946af.png)
