### ISSUE TITLE
[General Issue] Can I run on ubuntu server without qt client？

### ISSUE THREAD

**Issue by BeIFreedom** [PaddlePaddle/PaddleSeg#2841]

**Comment by juncaipeng** [comment]
Sorry, I do not figure out your problem. Please give more details.

**Comment by linhandev** [comment]
paddleseg can be used just with cmd.

To run EISeg remotely you can try x forwarding or VNC remote desktop. But I think both solutions shall require at least x window system to be installed on the server. Both x forwarding and vnc can be setted up without a screen on the server but you will probably need sudo access.
