### ISSUE TITLE
是否存在和paddleOCR类似的内存泄漏问题？

### ISSUE THREAD

**Issue by HuYue233** [PaddlePaddle/PaddleSeg#2842]
训练出现问题，训练一个epoch后CUDA利用率变为0，然后电脑内存开始上升，直到被kill。有解决办法和思路吗？
最离谱的是，我发现debug不会出现类似的情况。。。

 1. PaddleSeg版本：PaddleSeg release/2.7
 2. PaddlePaddle版本：paddlepaddle-gpu 2.4/2.3都有同样的问题
 3. 操作系统信息：Windows10
 4. Python版本号：Python3.8.12
 5. CUDA/cuDNN版本：CUDA11.2/cuDNN 8.2.1

**Comment by juncaipeng** [comment]
我们没有遇到该问题。 你是每次训练都会出现该问题吗？ 你指的ocr类似问题，可以贴一下该issue链接。

**Comment by HuYue233** [comment]
> 我们没有遇到该问题。 你是每次训练都会出现该问题吗？ 你指的ocr类似问题，可以贴一下该issue链接。

我也不知道是什么原因，情况和这个类似：
https://github.com/PaddlePaddle/PaddleOCR/issues/3341

**Comment by HuYue233** [comment]
这里有我的GPU和内存使用情况：内存有两段上升趋势，第一段是训练刚开始的时候，第二段是第一个epoch结束之后。同样的cuda利用率也是在第一个epoch结束之后降为0，然后kill的时候有一个骤升骤降。emmm，大概就是这么个情况。
![性能使用情况截图](https://user-images.githubusercontent.com/92309842/207549148-e202fc5f-cf2a-441c-b645-162ebd36ec2e.jpg)

**Comment by juncaipeng** [comment]
该问题估计是第一次预测后再进行训练，对内存要求更高，超过了机器最大内存，你可以试下设置num_works和batch_size小点。

**Comment by HuYue233** [comment]
> 该问题估计是第一次预测后再进行训练，对内存要求更高，超过了机器最大内存，你可以试下设置num_works和batch_size小点。

我的num_works设置的是0，然后batch_size设置成1也不行

**Comment by KKWY0909** [comment]
@HuYue233 ，您好，我在训练OCR时出现了和您一样的问题，请问您解决了么？

**Comment by HuYue233** [comment]
> 

时间有点久远了，我忘记了当时怎么解决的了。我觉得你可以检查一下是不是环境有和我类似的地方，我怀疑是环境的原因。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
