### ISSUE TITLE
请问可以使用 PaddleSeg/Matting抠图来做头部的头图任务吗

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleSeg#2846]
请问可以使用 PaddleSeg/Matting抠图来做头部的头图任务吗？
还是说咱们的Matting工程只能做人像抠图，单单做头部抠图可以吗？
做头部抠图使用咱们的百度飞桨的PaddleSeg语义分割好，还是Matting好一些

**Comment by wuyefeilin** [comment]
方便展示一下你想要的效果图吗

**Comment by jingmingtao** [comment]
![image](https://user-images.githubusercontent.com/114384977/207491836-a6a3236c-56e8-4f3f-98d0-5f14906f6dad.png)
![image](https://user-images.githubusercontent.com/114384977/207491909-b9fa873f-d182-470b-836e-f596279c15e8.png)

**Comment by jingmingtao** [comment]
脖子不要，头发要，头要

**Comment by jingmingtao** [comment]
这种效果用咱们的什么工程较好呢？

**Comment by wuyefeilin** [comment]
如果你有数据集的话，可以用Matting进行训练哈

**Comment by jingmingtao** [comment]
相比于人像的，效果会有打折扣吗。paddleseg相比于mattting呢，哪个效果好？

**Comment by wuyefeilin** [comment]
理论上跟人像抠图原理是一样的，要做到发丝级精度，建议使用matting哈，前提是得有训练数据
