### ISSUE TITLE
[Bug]matting项目下发布的pretrained ppmattingv2导出到256分辨率并转换为onnx会coredump

### ISSUE THREAD

**Issue by shine-xia** [PaddlePaddle/PaddleSeg#2847]
Thanks for your bug report. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Full codes: (if you modify any original code，please show the comparison of the codes before and after)
 7. Detailed error information, releated running log: (if using multi-gpus，the log is saved to log/worklog.0 by default)
 8. Running command or reproduce details：
 9. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 完整的代码：(若修改过原代码，请提供修改前后代码对比）
 7. 详细的错误信息、相关log：（若使用多卡，log默认保存在log/worklog.0）
 8. 运行指令或复现步骤：
 9. 其他内容: （增加其他与问题相关的内容）

操作系统：centos7
python版本：3.7.13
paddleseg版本： 2.7
paddlepaddle版本：2.3.1
paddle2onnx版本：1.0.5
onnxruntime版本：1.13.1
复现步骤：
1. 下载matting项目readme中提供的 ppmattingv2-stdc1-human_512预训练模型
2. 使用tools/export.py导出到静态图模型，导出成功。
python tools/export.py \
    --config     configs/ppmattingv2/ppmattingv2-stdc1-human_512.yml \
    --model_path exp/ppmattingv2-stdc1-human_512/ppmattingv2-stdc1-human_512.pdparams \
    --save_dir   exp/ppmattingv2-stdc1-human_512/export \
    --input_shape 1 3 256 256
3. 使用paddle2onnx工具转换为onnx模型，转换成功。
paddle2onnx \
    --model_dir       exp/ppmattingv2-stdc1-human_512/export/ \
    --model_filename  model.pdmodel \
    --params_filename model.pdiparams \
    --save_file       exp/ppmattingv2-stdc1-human_512/export/ppmattingv2-stdc1-human_512.onnx
4. 使用onnxruntime加载模型
import onnxruntime as rt
sess = rt.InferenceSession(modelpath)
产生报错信息：
Floating point exception (core dumped)

补充说明：
1.同一个预训练模型，导出设置修改为input_shape 1 3 512 512，一切正常。
2.使用ppmattingv2网络重新训练一个256x256的模型，转换为onnx后同样在onnxruntime加载模型时产生此错误。

**Comment by wuyefeilin** [comment]
具体报了哪个算子的错误吗？给一下更多的报错信息哈
