### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by knsong** [PaddlePaddle/PaddleSeg#2848]
请问用eiseg 0.3.1打开别人标注的结果时，图片和标注结果size不匹配是啥原因？
![111](https://user-images.githubusercontent.com/11374482/207576292-63c948f6-34ee-451c-8874-e59f7f42e2bf.png)

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：0.3.1
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：ubuntu 16.04
 4. Python版本号：python 3.8

**Comment by linhandev** [comment]
能确认不是数据的问题嘛，mask和图片是一样大的吧🤔

之前好像没有收到过这种错误反馈

**Comment by knsong** [comment]
> 能确认不是数据的问题嘛，mask和图片是一样大的吧🤔
> 
> 之前好像没有收到过这种错误反馈

确认了下mask和图片的size是一样的

**Comment by haoyuying** [comment]
标注load要用eiseg标注保存的结果reload回来。其他软件的标注结果不支持load回eiseg。

**Comment by knsong** [comment]
> 标注load要用eiseg标注保存的结果reload回来。其他软件的标注结果不支持load回eiseg。

是这样的：我是在ubuntu 16.04上用eiseg 0.3.0 load其他人在windows上用eiseg 0.5.0标注的结果

**Comment by haoyuying** [comment]
那你就用eiseg最新版本load吧或者也用0.5版本

**Comment by knsong** [comment]
> 那你就用eiseg最新版本load吧或者也用0.5版本

![wecom-temp-252805-63b7ba4ea8395e88ef394f72d00ed8dd](https://user-images.githubusercontent.com/11374482/207766005-d60898fa-5694-43c8-9826-ff7b334e5afc.jpg)

ubuntu 16.04装0.5.0会报这个错

**Comment by knsong** [comment]
> > 那你就用eiseg最新版本load吧或者也用0.5版本
> 
> ![wecom-temp-252805-63b7ba4ea8395e88ef394f72d00ed8dd](https://user-images.githubusercontent.com/11374482/207766005-d60898fa-5694-43c8-9826-ff7b334e5afc.jpg)
> 
> ubuntu 16.04装0.5.0会报这个错

安装方式： `pip install eiseg==0.5.0`

**Comment by linhandev** [comment]
一个可以尝试的方法

- 新开一个py 310的conda环境，一定新开一个。
- 之后安装启动还报这个错的话

![mmexport1671084701970.jpg](https://user-images.githubusercontent.com/29757093/207786211-b5d21758-5099-4969-aacd-5d967a52d5e5.jpg)

把新的报错里，这个位置路径里那个plugin文件夹随便改个名
