### ISSUE TITLE
在PaddleSeg时，如何才能只用模型，不用预训练的参数

### ISSUE THREAD

**Issue by larryhu76** [PaddlePaddle/PaddleSeg#285]
在用PaddleSeg时，如何才能只使用模型，如U-NET,DeeplabV3+等，但是不用已经预训练好的参数，然后在自己的数据集上重新训练。

**Comment by wuyefeilin** [comment]
如果不使用预训练模型，TRAIN.PRETRAINED_MODEL_DIR参数不设置就行了。

**Comment by larryhu76** [comment]
注释掉参数 TRAIN.PRETRAINED_MODEL_DIR 就可以了，感谢！
