### ISSUE TITLE
在使用paddleseg/Matting，在进行预测时，发现由mask图合成rgba图时，estimate_foreground_ml部分消耗cpu资源非常大，有什么办法可以解决吗

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleSeg#2856]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by jingmingtao** [comment]
在使用paddleseg/Matting，在进行预测时，发现由mask图合成rgba图时，estimate_foreground_ml部分消耗cpu资源非常大，有什么办法可以解决吗。因为这一步合成ragba，我们使用40 vCPU 155 GiB （I/O优化）GPU：NVIDIA T4进行的测试，发现只能同时开启5个进程，cpu就已经吃的满满了。我们想要更高的并发，就需要降低estimate_foreground_ml部分cpu的消耗。请问有什么好的办法吗，谢谢您

**Comment by wuyefeilin** [comment]
estimate_foreground_ml 这一部分相当于PS中的颜色净化功能，如果不精益求精的话可以去掉哈
