### ISSUE TITLE
[General Issue] Error in "pip install -e ."

### ISSUE THREAD

**Issue by Leiyi-HU** [PaddlePaddle/PaddleSeg#2859]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3) 2.7
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0) 2.4.1
 3. Operation system: (e.g. Linux/Windows/MacOS) macos
 4. Python version: (e.g. Python3.6/7/8) python3.9.13
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5) none
 6. Additional context: (Add any other context about the problem)
`
(paddleseg) ➜  PaddleSeg git:(release/2.7) pip install -e .
Obtaining file:///Users/hu/Work-Root/git_repo/PaddleSeg
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: -4
  ╰─> [0 lines of output]
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`
---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by juncaipeng** [comment]
I do not meet error using the same environment. Could you provide more information.
