### ISSUE TITLE
[Bug] eiseg在标注完成一张图像后，保存的时候报错，似乎是路径问题

### ISSUE THREAD

**Issue by yongshangli** [PaddlePaddle/PaddleSeg#2860]
1. PaddleSeg版本：2.7.0
 2. PaddlePaddle版本：2.4.1
 3. 操作系统信息：windows11
 4. Python版本号：python3.8.15
 5. CUDA/cuDNN版本：cpu版本
 
安装使用pip install eiseg，之前在ubuntu上可以使用，保存也没有问题，现在由于放假回家，使用win笔记本，没有gpu，安装的paddle cpu的版本，标注过程没有问题，最后保存出现错误，好像是路径格式不匹配的问题。
错误信息：
```
Traceback (most recent call last):
  File "C:\Users\yongs\anaconda3\envs\paddle24\Lib\site-packages\eiseg\app.py", line 2091, in exportLabel      
    open(jsonPath, "w", encoding="utf-8").write(json.dumps(labels))
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/yongs/Desktop/ceshi_eiseg\\label\\labelme\\ceshi_eiseg\\label\\14_2_labelme.json'
```

我刚刚又尝试了eiseg==1.0.3版本，没有问题，但是目前的这个eiseg==1.1.0有问题。

**Comment by haoyuying** [comment]
您好，收到反馈，我们会尽快排查这个问题。

**Comment by haoyuying** [comment]
您好，可以具体说下您是怎么产生这个问题的吗，最好录个操作视频，我这边没有复现。

**Comment by yongshangli** [comment]
> 您好，可以具体说下您是怎么产生这个问题的吗，最好录个操作视频，我这边没有复现。
![image](https://user-images.githubusercontent.com/59642489/208379675-f59c59d9-a5a5-4769-8e22-42d568b6d364.png)
![image](https://user-images.githubusercontent.com/59642489/208379931-90f65c5b-6b3a-48aa-ad06-1311362134c7.png)
当我标注完成点击保存，eiseg就会退出，产生上面的错误。

**Comment by pughua** [comment]
也遇到同样的问题：
1.1.0版本有问题，1.0.3没有这个问题
`
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\eiseg\app.py", line 2091, in exportLabel
    open(jsonPath, "w", encoding="utf-8").write(json.dumps(labels))
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Administrator/Desktop/PS/8\\label\\labelme\\8\\label\\346a0000923a56a63dc508da6a3ae3d6_3_labelme.json'
`

**Comment by haoyuying** [comment]
修复后的代码已经在develop上同步，可尝试拉取最新代码使用。可尝试eiseg 1.1.1看是否仍有此问题。

**Comment by yongshangli** [comment]
It worked.
