### ISSUE TITLE
requests.exceptions.ProxyError: HTTPSConnectionPool(host='bj.bcebos.com', port=443)

### ISSUE THREAD

**Issue by Wahdk** [PaddlePaddle/PaddleSeg#2861]
requests.exceptions.ProxyError: HTTPSConnectionPool(host='bj.bcebos.com', port=443): Max retries exceeded with url: /paddleseg/dygraph/PP_STDCNet2.tar.gz (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by juncaipeng** [comment]
你设置了代理失效了， 可以取消代理。

**Comment by Wahdk** [comment]
我该怎么样取消代理，是取消浏览器代理吗

**Comment by Wahdk** [comment]
> 你设置了代理失效了， 可以取消代理。

我该怎么样取消代理，是取消浏览器代理吗

**Comment by juncaipeng** [comment]
取决于你电脑设置的代理方式

**Comment by Wahdk** [comment]
> 取决于你电脑设置的代理方式

好的，我再试一下。谢谢额

**Comment by Wahdk** [comment]
> 取决于你电脑设置的代理方式

我关闭了电脑代理，还是不太行，可以加你一下微信吗，18860277564
