### ISSUE TITLE
使用OpenVINO直接部署PaddleSeg

### ISSUE THREAD

**Issue by fanxiaochen456** [PaddlePaddle/PaddleSeg#2863]
您好，请问有使用C++和OpenVINO直接部署PaddleSeg的案例吗？

**Comment by shiyutang** [comment]
你好，暂时没有使用openvino的，但是可以基于paddleinference和paddlex进行部署。：https://github.com/PaddlePaddle/PaddleSeg/blob/develop/deploy/cpp/README_cn.md

**Comment by Harryoung** [comment]
你好，可以参考部署专用套件FastDeploy，
https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/segmentation/paddleseg/cpp
https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/how_to_change_backend.md

**Comment by shiyutang** [comment]
这个问题已经长期没有回复，暂时关闭，如有需要可以回复issue，或者再次打开。
