### ISSUE TITLE
训练cityscapes到一定次数会直接跳出(任何网路架构都是)

### ISSUE THREAD

**Issue by SuPoTing** [PaddlePaddle/PaddleSeg#2866]
Thanks for your bug report. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (PaddleSeg release2.7)
 2. PaddlePaddle version: (PaddlePaddle 2.4.1)
 3. Operation system: (Windows10)
 4. Python version: (Python3.6)
 5. CUDA/cuDNN version: (CUDA11.7/cuDNN 8.4.1)

![未命名](https://user-images.githubusercontent.com/52108678/208397968-d544cfce-3d14-4927-bdcd-600b9c0964e1.png)

**Comment by shiyutang** [comment]
请问你是否有修改任何的代码呢？

**Comment by SuPoTing** [comment]
> 请问你是否有修改任何的代码呢？

沒有修改任何程式碼，我的顯示卡是3090，但是2080ti可以正常運作

**Comment by shiyutang** [comment]
你好，如果切换显卡会导致错误的话，大概率是环境问题导致的，需要检查paddle版本，cuda版本等是否安装正确？

**Comment by SuPoTing** [comment]
> 你好，如果切换显卡会导致错误的话，大概率是环境问题导致的，需要检查paddle版本，cuda版本等是否安装正确？

都在同一環境執行
換成2080ti的環境是cuda10.2 cudnn7.6.5其餘都沒變動 感謝您
我的換卡是將卡拔起替換，不是設置device

**Comment by shiyutang** [comment]
建议在换了3090后重新建立一个新的conda环境，安装cuda10.2 cudnn7.6.5以及对应版本的paddle

**Comment by SuPoTing** [comment]
> 建议在换了3090后重新建立一个新的conda环境，安装cuda10.2 cudnn7.6.5以及对应版本的paddle

您好這個我也試過了也是不行

**Comment by juncaipeng** [comment]
有报错信息吗？

**Comment by SuPoTing** [comment]
> 
我發現問題了 一定要用python3.7以上才可以 感謝各位協助
