### ISSUE TITLE
paddleSeg+WIN10+vs2019+C++ debug部署报错

### ISSUE THREAD

**Issue by aiwenzhu** [PaddlePaddle/PaddleSeg#2867]
paddleSeg+WIN10+vs2019+cuda11.0 +C++ release下运行正常，但在debug下运行失败；
问题如下：
std::shared_ptr<paddle_infer::Predictor> create_predictor(
    const YamlConfig& yaml_config) {
    std::string& model_dir = FLAGS_model_dir;

    paddle_infer::Config infer_config;
    infer_config.SetModel(model_dir + "/" + yaml_config.model_file,
        model_dir + "/" + yaml_config.params_file);
    infer_config.EnableMemoryOptim();

    if (FLAGS_devices == "GPU") {
        infer_config.EnableUseGpu(100, 0);

上面函数中的infer_config.SetModel(model_dir + "/" + yaml_config.model_file,
        model_dir + "/" + yaml_config.params_file);报错如下：

0x00007FFEFD7DCD29 处(位于 inference_test.exe 中)有未经处理的异常: Microsoft C++ 异常: std::bad_alloc，位于内存位置 0x000000BAB84FDDA0 处。

**Comment by shiyutang** [comment]
请问你是否有修改预测代码呢？ 看上去是内存分配失败导致的异常；另外是否有更多的报错堆栈信息， 能定位到报错位置的代码？

**Comment by juncaipeng** [comment]
建议直接使用release分支部署，速度比debug快。

此外，该问题应该是paddleinference的内部bug，我们分割团队不太好处理，如果想进一步解决，建议在https://github.com/PaddlePaddle/Paddle提issue，请理解。
