### ISSUE TITLE
[Feature Request]1.能否对前列腺的腺体分割（若能更细分到移行带与外周带更佳）进行支持，或者可以加载现有的分割模型到EISEGMED中。 

### ISSUE THREAD

**Issue by BaiHonglin** [PaddlePaddle/PaddleSeg#2869]
Welcome to propose a new feature! To help us understand your great feature, please provide following information:
1. A clear and concise description of the proposed feature.
2. Tell us why the feature is useful. 
3. If possible, please show related codes .

---

欢迎提出一个新功能需求，为了帮助我们更好理解您的需求，辛苦提供下面信息：
1. 清晰简洁的语言提出新功能需求。
2. 请描述这个需求的必要性。
3. 如果可以，辛苦您提供相关代码实现效果。

**Comment by shiyutang** [comment]
请问需要支持的分割有相关应用落地么？ 我们可以一起新增相关案例。

**Comment by shiyutang** [comment]
另外请问需要支持的是分割模型，还是交互式分割（标注）模型

**Comment by shiyutang** [comment]
这个问题已经长期没有回复，暂时关闭，如有需要可以回复issue，或者再次打开。
