### ISSUE TITLE
[General Issue] 请问推理时是否支持将resize放在pp_liteseg的forward内部？

### ISSUE THREAD

**Issue by clw5180** [PaddlePaddle/PaddleSeg#2870]
我现在是nchw格式原图尺寸输入，然后在pp_liteseg内部加入 F.interpolate来进行resize，但是目前导出model.pdmodel然后用trt推理会报错：bilinear_interp_v2.0.tmp_08: dimension 2 never exceeds -103680 ，这个是什么原因导致的？这么操作能否可行？感谢！

**Comment by wuyefeilin** [comment]
麻烦将你改的代码放一下看看

**Comment by clw5180** [comment]
> 麻烦将你改的代码放一下看看

在 pp_liteseg.py 的 forward 函数最开始的地方，加了一句 x = F.interpolate(x, [1024, 576], mode='bilinear')
想在推理时把resize放在模型中，节约一些时间

**Comment by wuyefeilin** [comment]
这个shape参数的输入得用paddle.tensor的类型，不能是列表。

**Comment by wuyefeilin** [comment]
换成这样试试：x = F.interpolate(x, paddle.to_tensor([1024, 576]), mode='bilinear')
