### ISSUE TITLE
[General Issue] Inquiry about the process of training for PP-HumanSeg

### ISSUE THREAD

**Issue by kisungsim** [PaddlePaddle/PaddleSeg#2872]
I have a few questions about the process of training.
I would be grateful if you answer the questions.

1. I tried to train the 'PP-HumanSegV2-Lite model (portrait segmentation model)' based on given config file (https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/contrib/PP-HumanSeg/configs/portrait_pp_humansegv2_lite.yml), but it did not work well as suggested in README file. 
In README file, the mIou is 96.63%, but I got 95.36%. 
The mIou values looks similar, but when I applied my inference model to image, the performance of segmentation was not good. 
So I wonder which config file did you use when you trained the model.
If you used another config file when training, could you provide the config file for the PP-HumanSeg-Lite model which yields 96.63% mIou?

2.  When I trained the model, I used PP-HumanSeg14K dataset which your PaddleSeg Team provided (I emailed to PaddleSeg Team before). Could you tell me which dataset did you use when you trained the model which yields 96.63% mIou result?

**Comment by juncaipeng** [comment]
Thanks for your interest in our work.
As introduced in [here](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.7/contrib/PP-HumanSeg#41-portrait-segmentation-models) ,we first pretrain the model on a large general human segmentation dataset, and then finetune it on PP-HumanSeg14K.

**Comment by kisungsim** [comment]
Thank you for your reply :)
Then, if possible, can I get the large general human segmentation dataset?

**Comment by juncaipeng** [comment]
Sorry, the general human segmentation dataset can not be released for privacy issues.

**Comment by kisungsim** [comment]
Thank you for your kind reply!
Then, can I get the pretrained model based on a large general human segmentation dataset??

**Comment by langxuelang** [comment]
@kisungsim 
Hi,
I also emailed the official team to request the PP-HumanSeg14K dataset, but unfortunately I haven't received any reply after waiting for quite a while.

Would you mind sharing the dataset with me if you have it? I'd really appreciate your help!

My email is: [gaotengxuelang@gmail.com](mailto:gaotengxuelang@gmail.com)

Thanks a lot in advance!

**Comment by langxuelang** [comment]
@juncaipeng 您好，PP-HumanSeg14K这个数据集，我通过公司邮件申请，但是一直没有回复，可以分享给我一份这个数据集吗
gaotengxuelang@gmail.com
