### ISSUE TITLE
训练人像抠图报错

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleSeg#2882]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用咱们工程报错，cuda版本11.2，显卡p100,而且速度非常慢
OSError: (External) CUDA error(999), unknown error.
  [Hint: Please search for the error code(999) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:259)

**Comment by shiyutang** [comment]
这个错误是cuda环境导致，建议参照：https://stackoverflow.com/questions/58595291/runtime-error-999-when-trying-to-use-cuda-with-pytorch   https://blog.csdn.net/maizousidemao/article/details/108234321

**Comment by jingmingtao** [comment]
链接打不开

**Comment by jingmingtao** [comment]
另外还会报错：
![31b56741a2f5c04702c17faae0d1c2f](https://user-images.githubusercontent.com/114384977/210039905-00756658-3e78-487c-87fd-ec69f019d13c.png)

**Comment by shiyutang** [comment]
<img width="383" alt="image" src="https://user-images.githubusercontent.com/34859558/210045513-c0d77789-73b6-4e5c-baa1-6a92ccee57b7.png">

**Comment by shiyutang** [comment]
> 另外还会报错： ![31b56741a2f5c04702c17faae0d1c2f](https://user-images.githubusercontent.com/114384977/210039905-00756658-3e78-487c-87fd-ec69f019d13c.png)

你这个错误报错可以看到这个链接，里面说切换驱动解决。你的问题和cuda配置有关，建议安装好环境后重新尝试。

**Comment by jingmingtao** [comment]
谢谢，想请教下，p100训练模型的时候，功耗下降很厉害，是什么导致的

**Comment by jingmingtao** [comment]
重新加载内核的指令，我直接执行不了

**Comment by shiyutang** [comment]
请问是报什么错呢？

**Comment by shiyutang** [comment]
另外“功耗下降很厉害“ 是指的什么指标变动呢？
