### ISSUE TITLE
paddleserving部署使用trt怎么设置动态shape

### ISSUE THREAD

**Issue by Enchanted0911** [PaddlePaddle/PaddleSeg#2886]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

想尝试一下trt加速，我的场景是固定输入，模型导出的时候也指定了参数 --input_shape 1 3 1024 1024
但是在paddleserving部署使用tensorrt时，启动会报错，要求我设置动态shape的相关信息，请问我该如何设置呢？
我使用的是ocrnet hrnet18的模型，以下是配置文件https://github.com/PaddlePaddle/PaddleSeg/blob/e2c1af2b9bd24f67fb1bb2b99d556b63c41d6b0f/configs/ocrnet/ocrnet_hrnetw18_cityscapes_1024x512_160k_lovasz_softmax.yml

**Comment by juncaipeng** [comment]
可以参考serving的文档： https://github.com/PaddlePaddle/Serving/blob/v0.9.0/doc/TensorRT_Dynamic_Shape_CN.md

你是使用C++ Serving方式吧，需要修改源码设置SetTRTDynamicShapeInfo，最大、最小、最优shape都设置成你要的固定大小。 模型的输入名字可以使用netron打开。

**Comment by Enchanted0911** [comment]
> 可以参考serving的文档： https://github.com/PaddlePaddle/Serving/blob/v0.9.0/doc/TensorRT_Dynamic_Shape_CN.md
> 
> 你是使用C++ Serving方式吧，需要修改源码设置SetTRTDynamicShapeInfo，最大、最小、最优shape都设置成你要的固定大小。 模型的输入名字可以使用netron打开。

好的，感谢！
