### ISSUE TITLE
关于MedicalSeg的预处理

### ISSUE THREAD

**Issue by lyangfan** [PaddlePaddle/PaddleSeg#2889]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

查看了MedicalSeg对于不同数据集的预处理文件，有两个问题想请教一下各位开发者：
1、MedicalSeg是不是目前不支持patch-based segmentation？
2、对于resample函数，似乎只设置了最近邻插值`image_new = scipy.ndimage.zoom(image, resize_factor, mode='nearest', order=order)`，对于source文件来说，这种插值方式是不是比较粗糙？

**Comment by shiyutang** [comment]
1. 目前Medicalseg的主体训练暂时不支持patch-based segmentation，但是nnUNet-D可支持。
2. resample函数的确使用的是最近邻插值，这里主要是因为没有将标签和image进行区分，可以尝试对二者进行区分并对image使用双线性插值等，看是否对分割精度有所提升。欢迎随时向我们反馈你的实验结果。

**Comment by lyangfan** [comment]
> 

感谢答复！
