### ISSUE TITLE
在windows服务器上训练的时候有时候会卡住 ，不输出日志也不继续训练了

### ISSUE THREAD

**Issue by tudoulei** [PaddlePaddle/PaddleSeg#2891]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在windows服务器上训练的时候有时候会卡住 ，不输出日志也不继续训练了

**Comment by wuyefeilin** [comment]
稳定复现吗，另外看一下退出时的提示信息

**Comment by TakeshiGianlee** [comment]
请问解决了吗
