### ISSUE TITLE
使用EiSeg的视频标注功能，对首帧图片进行标注传播后，能否像标注单张图片一样进行微调？

### ISSUE THREAD

**Issue by OroChippw** [PaddlePaddle/PaddleSeg#2892]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

很高兴能使用到那么优秀的功能，谢谢EiSeg团队的工作和付出
但在使用EiSeg的视频标注功能时，对首帧图片进行标注传播后，能否像标注单张图片一样使用空格切换模式，再对每帧的图像中目标进行微调，通过添加点使得边缘更加平滑？貌似不行，如果是我的操作有误，希望能得到您的纠正
再次感谢EiSeg这项优秀的软件，希望能迅速得到答复，谢谢~

**Comment by haoyuying** [comment]
完成单帧标注后，点击空格键进入多边形标注模式，可以通过对锚点的增删及修改实现微调。或者直接将想标注的图片用图像标注的方法不进行视频传播进行单帧标注。

**Comment by OroChippw** [comment]
> 完成单帧标注后，点击空格键进入多边形标注模式，可以通过对锚点的增删及修改实现微调。或者直接将想标注的图片用图像标注的方法不进行视频传播进行单帧标注。

很高兴收到您的回复
所以如果我对于传播后中间帧的标注结果不满意，我只能通过不断的优化参考帧的精细度，重复使用步骤中的5-6步骤来修正标注结果吗
后续是否会考虑增加对传播后中间帧的微调功能，比如为了减少标注工作量的同时获取更多人体姿态的数据，将视频抽帧再重新组合成视频，部分的动作剧变后发现传播后标识的目标主体大致能进行清晰的标注，但部分边缘的效果不太好，想要通过微调来优化标注，我想这是一个潜在的需求，谢谢您~

**Comment by haoyuying** [comment]
您好，感谢您的反馈，您的需求我们会考虑之后对每一帧增加多边形手工标注的能力来缓解边缘标注差的问题。在目前的使用方式下，对于中间结果不满意主要有两种方式，第一种，重新标注该帧，就想eiseg标注图片这种方式一样；第二种，增加参考帧数量，多增加单张图片的标注进行传播，每次标注一张图都会将其视为新的参考帧，参考帧越多，标注效果越好。

**Comment by Harryoung** [comment]
keep it open as new feature to be considered

**Comment by OroChippw** [comment]
非常感谢EiSeg团队的回复与重视，期待你们的成果，谢谢~

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
