### ISSUE TITLE
CPU模式使用eiseg标注图片，点击完成宫格出现错误闪退

### ISSUE THREAD

**Issue by jionyii** [PaddlePaddle/PaddleSeg#2895]
### 问题确认 Search before asking

- [x] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

用的static_hrnet18s_ocr48_cocolvis模型，最新cpu版本的paddlepaddle，和最新版本的paddleseg
标注完成后，点击完成宫格出现错误闪退
![微信截图_20230104233723](https://user-images.githubusercontent.com/61500782/210591801-ab9bd199-273f-4511-b067-003318b3d64a.png)
第二次打开eiseg读取文件夹图片后
![微信截图_20230104233737](https://user-images.githubusercontent.com/61500782/210591929-e9946ac9-84ae-43d6-83c9-741040723220.png)

**Comment by haoyuying** [comment]
您好，本地没有复现您的问题，请先检查实用的eiseg是否是1.1.1版本，如果是，可以录一个具体的视频发在eiseg的交流群里吗，我们马上跟进排查。或者将复现方式贴在issue下面
![image](https://user-images.githubusercontent.com/35907364/210691791-dc4bdfb7-f364-4079-920e-90e36cc88fee.png)

**Comment by geoyee** [comment]
@jionyii 麻烦您从[develop分支](https://github.com/PaddlePaddle/PaddleSeg/tree/develop/EISeg)尝试下这个问题是否还存在。这个bug应该是有数字是ndarray类型，python内置的json库不知道如何序列化成字符串。在[这个](https://github.com/geoyee/PaddleSeg/commit/293bb1754dd2a1060a9943a4d1805bf5a959d167)修复中尝试将不同类型的ndarray转为int/float/list，应该能解决问题。如果还有问题欢迎继续沟通。
