### ISSUE TITLE
关于ohem损失函数用于计算损失的最小像素点选择

### ISSUE THREAD

**Issue by SevenTae** [PaddlePaddle/PaddleSeg#2896]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，请问OHEM损失函数中那个最少用于计算损失的像素点数量怎么选择呢，我的训练图片的尺寸是512*512的一张共有262144个像素点

**Comment by Bobholamovic** [comment]
你好，一般选择为 batch_size * h * w 的 1/16.
