### ISSUE TITLE
config中crop_size含义

### ISSUE THREAD

**Issue by chenxiaoxio-o** [PaddlePaddle/PaddleSeg#2898]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

配置文件config中的参数crop_size，如crop_size: [1024, 512]是将图像的宽裁剪为1024还是高为1024？

**Comment by haoyuying** [comment]
宽度为1024，高度为512，具体的含义可以看下transform当中源码部分：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/paddleseg/transforms/transforms.py#L576
