### ISSUE TITLE
EISeg 检测标注yolo格式问题

### ISSUE THREAD

**Issue by linhandev** [PaddlePaddle/PaddleSeg#2901]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

EISeg保存的yolo数据集格式为

图片名.txt
类别id xmin ymin bbwidth bbheight

就我这边调研通常用的格式是

图片名.txt
类别id xmid/width ymid/width bbwidth/width bbheight/height

比如这个数据集

https://www.kaggle.com/datasets/valentynsichkar/traffic-signs-dataset-in-yolo-format

现在这个保存格式应该不太方便兼容其他的工具

### 复现环境 Environment

设计问题，与环境关系不大

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by haoyuying** [comment]
欢迎提交pr到develop分支。

**Comment by linhandev** [comment]
👌

**Comment by haoyuying** [comment]
bug已修复，pr地址：https://github.com/PaddlePaddle/PaddleSeg/pull/2902
