### ISSUE TITLE
How to export the op not supported to onnx when I transfrom paddle model to onnx? 

### ISSUE THREAD

**Issue by liuxubit** [PaddlePaddle/PaddleSeg#2909]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hello,
How to export the op not supported to onnx when I transfrom paddle model to onnx? 
for example，I have a model with msda。The onnx doesn't has the op。 When I use torch, the op can be taken place by a fake op like this:
![image](https://user-images.githubusercontent.com/39891612/211701453-7c85ef4f-c70d-4ae8-a842-098b51d35a6e.png)
Then，I can export it to onnx like this:
![image](https://user-images.githubusercontent.com/39891612/211701674-7103811e-6c3d-4109-8c94-010d34dec5ed.png)
And it can be used to generate a trt engine。
So if I use paddle model like rtformer，how can I reproduce the process like what I did in torch? Do you have the same function?

**Comment by wuyefeilin** [comment]
出现算子不支持的情况下可以到[Paddel2ONNX](https://github.com/PaddlePaddle/Paddle2ONNX)建立issue哈。

**Comment by liuxubit** [comment]
OK
