### ISSUE TITLE
如何使用自己的数据训练可用于EiSeg中的交互式分割模型？

### ISSUE THREAD

**Issue by OroChippw** [PaddlePaddle/PaddleSeg#2914]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好 很高兴能使用到EiSeg这么优秀的软件，大幅的提高了标注工作的效率
然而由于自采数据集的特殊性，在提供的通用模型上无法通过少量的点击实现目标物体的分割
在查看EiSeg底层代码及官方提供的通用分割模型后发现交互式分割的模型输入输出及预处理后处理不同于我们常规的分割模型
想问一下 如何使用自己的数据训练可用于EiSeg中的交互式分割模型呢？
Q1:PaddleSeg是否有提供相关的训练代码？如果没有，是否有在计划中进行开放呢？
Q2:在issue#1453中 和 README的“贡献者”中 都提到使用了RITM算法，想问官方提供的通用模型是否都基于RITM算法进行训练？是否使用paddle框架进行复现后即可将模型应用于EiSeg中？
Q3:作为交互式分割的初学者，想问一下EiSeg通过添加正负点微调产生多边形的原理？或者有无相关的论文推荐呢？
以上便是我的问题汇总，抱歉可能有点多，很期待得到您的回复，谢谢~

**Comment by haoyuying** [comment]
Q1：目前由于商业化原因，训练代码暂未开放。
Q2：EISeg使用的RITM训练是经过后期优化的，与原本的RITM算法不完全一致，用paddle复现后不保证可直接应用。
Q3: 推荐RITM及EdgeFlow论文，或者也可以看看这篇知乎：https://zhuanlan.zhihu.com/p/598013895

**Comment by OroChippw** [comment]
很高兴那么快就得到答复，谢谢您的回答~

**Comment by monkeycc** [comment]
要是增加了
飞桨 EasyDL 
飞桨 BML 全功能AI开发平台
怎么还能卖得动 ？
