### ISSUE TITLE
文档中模型精度和log中不一致的问题

### ISSUE THREAD

**Issue by Littlehong-ai** [PaddlePaddle/PaddleSeg#2915]
### 问题确认 Search before asking

- [x] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

模型：DMNet：文档精度0.7967 V.S. log精度0.7976，
           HRNetW48Contrast ： 文档精度0.8230 V.S. log精度0.8240
注： 以上模型按照文档模型评估方法，复现精度同log精度；

BiSeNetv2: 复现精度0.7317， 文档精度0.7319

OCRNet_HRNetW18：复现精度0.8070 ，文档精度0.8067

</body>
</html>

**Comment by Littlehong-ai** [comment]
平台：ubuntu16.04
           cuda 10.1
           paddlepaddle2.4.1

**Comment by Bobholamovic** [comment]
对于 DMNet 和 HRNetW48Contrast，感谢指出错误，我们已修复相关文档。

对于  BiSeNet v2 和 OCRNet_HRNetW18，这可能是由 PaddleSeg 的一个已知 bug 导致的：『使用多卡训练后，部分模型在训练过程中验证集上汇报的精度和训练完对应存下的模型用`val.py`算出的精度有细微偏差』。由于技术原因，目前我们尚未能准确定位这个问题的具体成因。不过值得指出的是，这一 bug 带来的数据误差通常非常『轻微』，例如，在你给出的两个例子中，diff 都在小数点后第4位，即万分之一量级，因此对最终 benchmark 结果影响有限。后续关于此问题修复的最新进展，我们将在此 issue 同步。
