### ISSUE TITLE
PaddleSeg 的 RTFomer 模型转.nb报错

### ISSUE THREAD

**Issue by WYH150123** [PaddlePaddle/PaddleSeg#2917]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

PaddleSeg 的 RTFomer 模型转.nb报错，具体信息如下：
------------------------------------------------------------
- 版本、环境信息：
    1）Paddle Lite 版本：v2.12
    2）Host 环境：Ubuntu 20.04
- 模型信息
    1）模型名称 : RTFormer
    2）模型链接: 链接：https://pan.baidu.com/s/1b88LoRKax3HE3wrQRdEIsQ?pwd=m6og   提取码：m6og 

- 复现信息：paddle_lite_opt --model_dir=./output/exportModel/output_rt_infer --valid_targets=arm --optimize_out=output/out
- 问题描述：报错信息
-                   Loading topology data from ./output/exportModel/output_rt_infer/model.pdmodel
                    Loading params data from ./output/exportModel/output_rt_infer/model.pdiparams
                    1. Model is successfully loaded!
                     段错误 (核心已转储)

### 复现环境 Environment

Ubuntu: 20.04
Paddle: 2.3.2
Paddle-Lite: v2.12

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by juncaipeng** [comment]
收到，我们复现一下。 顺便请问，导出模型在paddle inference是预测成功的吗？只是在paddlelite转换的时候报错？

**Comment by WYH150123** [comment]
谢谢。
1. 我是使用官网发布的模型来验证，训练模型路径如下https://paddleseg.bj.bcebos.com/dygraph/cityscapes/rtformer_slim_cityscapes_1024x512_120k/model.pdparams，
2. export 命令是 python tools/export.py --config configs/rtformer/rtformer_slim_cityscapes_1024x512_120k.yml --model_path output_rtformer/model.pdparams --save_dir output_rtformer/output_new --input_shape 1 3 1024 512 
3. 我们应用场景在Android/IOS 移动端，需要转.nb格式后在Paddle Lite上运行，由于转.nb失败，inference 还没有尝试验证

**Comment by WYH150123** [comment]
Dear juncaipeng,

我们目前项目使用RTFomer替换之前网络，训练效果很好，希望能及时导入移动端，烦请帮忙尽快解决问题

Many Thanks

**Comment by juncaipeng** [comment]
收到  我们需要同步lite的同学来修复，需要点时间，会在这个issue同步进展。   也可以推荐你先试试pp-liteseg，看看效果。

**Comment by WYH150123** [comment]
好的，感谢

**Comment by WYH150123** [comment]
Dear juncaipeng， 

有任何更新和进展吗？

**Comment by hong19860320** [comment]
请问这个模型是需要支持 sparse conv 吗？

**Comment by hong19860320** [comment]
已经安排同学看了，可以关注这个 issue 的进展 https://github.com/PaddlePaddle/Paddle-Lite/issues/9933

**Comment by WYH150123** [comment]
@hong19860320 👍,  感谢

**Comment by WYH150123** [comment]
@hong19860320 ,请更新一下最近的解决进展和计划，谢谢
