### ISSUE TITLE
关于EIseg标注无法保存为json格式的问题

### ISSUE THREAD

**Issue by yuewenzheng** [PaddlePaddle/PaddleSeg#2918]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

初次使用eiseg，按照readme的教程使用develop源码安装，并执行python exe.py使用，但是奇怪的是打开的界面可以保存为coco和YOLO的格式，但是为什么只有中间的labelme的json格式是灰色的，无法保存呢？想保存为labelme的json格式，请问是不是我哪里出问题了。

**Comment by yuewenzheng** [comment]
问题解决啦！

**Comment by haoyuying** [comment]
您好，问题已解决，我们将关闭issue，感谢您的反馈。

**Comment by wujushan** [comment]
Hi, @yuewenzheng 我也遇到一样的问题，是咋解决的呢？
