### ISSUE TITLE
在使用paddleseg进行模型推理，如果开多个进程推理，当每个进程推理的显存增大时，也不能及时释放，请问如何及时释放推理的显存。

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleSeg#2919]
### 问题描述 Please describe your issue

在使用paddleseg进行模型推理，如果开多个进程推理，当每个进程推理的显存增大时，也不能及时释放，请问如何及时释放推理的显存。

**Comment by juncaipeng** [comment]
paddleinferencce只有释放predictor才会释放显存。
