### ISSUE TITLE
eiseg标注软件的加载模型可以进行微调吗

### ISSUE THREAD

**Issue by favoritemc** [PaddlePaddle/PaddleSeg#2921]
目前加载的模型只有官方提供的几个模型，但是当数据集越完善时，想对加载模型进行微调实现更高精度的预标注，但是自己训练和微调的模型转成静态图模型导入时，会发现list out of range报错，经过排查发现官方预标注模型的输入输出和正常训练差异很大，想问如何拿到官方预标注模型的config或者如何解决上述问题

**Comment by favoritemc** [comment]
使用的模型是我根据官方教程进行训练得到的模型，单独对模型进行测试也能够正常分割正常使用，但是转成静态图放到eiseg标注软件后就会报错

**Comment by favoritemc** [comment]
这是我自己训练的模型，input_name只有x
![Uploading 截屏2023-01-16 18.29.13.png…]()
![Uploading 截屏2023-01-16 18.27.09.png…]()
![Uploading 截屏2023-01-16 18.27.09.png…]()

**Comment by favoritemc** [comment]
这是我自己训练的模型，input_name只有x
![Uploading 截屏2023-01-16 18.27.09.png…]()
![Uploading 截屏2023-01-16 18.29.13.png…]()

**Comment by favoritemc** [comment]
这是我自己训练的模型，input_name只有x
<img width="781" alt="2" src="https://user-images.githubusercontent.com/58458221/212657876-86335153-6297-4ded-896e-cda2362a57b0.png">
<img width="1103" alt="1" src="https://user-images.githubusercontent.com/58458221/212657905-e63fcb1e-ea6e-4aaf-850b-280d0e9885e9.png">

**Comment by favoritemc** [comment]
导入官方模型是有两个input_name
<img width="678" alt="3" src="https://user-images.githubusercontent.com/58458221/212658687-d75294ca-c431-49b8-8d93-7f60b039a288.png">

**Comment by haoyuying** [comment]
eiseg目前不支持自己训练模型，交互式分割有自己的训练策略，和普通的分割不同。

**Comment by favoritemc** [comment]
那有什么办法可以解决上述问题呢

**Comment by Harryoung** [comment]
@favoritemc EISeg目前没有开源交互式分割模型微调的能力，如果你有十分强烈的需求，可以参考相关的论文自己尝试一下，参见https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.7/EISeg 最后的学术引用信息。

**Comment by favoritemc** [comment]
@Harryoung 是交互式分割模型微调的方法没有开源还是整个交互式分割模型所有相关的代码都没有开源呢，打扰您了

**Comment by Harryoung** [comment]
@favoritemc 应该是所有训练相关的代码都没有开源
