### ISSUE TITLE
请问训练ppliteseg512*512时候 如果我导出的shape是512*512，是否训练的时候数据集需要512*512

### ISSUE THREAD

**Issue by yueyue0574** [PaddlePaddle/PaddleSeg#2923]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问训练ppliteseg512*512时候 如果我导出的shape是512*512，是否训练的时候数据集需要512*512

**Comment by Bobholamovic** [comment]
你好，由于全卷积神经网络一般具有自适应输入尺寸的能力，训练与测试时的输入尺寸可以不一致，但在不使用多尺度训练的情况下，一般只有在接受与训练输入相近尺寸的图像时，模型才能取得较好的测试效果。

**Comment by yueyue0574** [comment]
> 你好，由于全卷积神经网络一般具有自适应输入尺寸的能力，训练与测试时的输入尺寸可以不一致，但在不使用多尺度训练的情况下，一般只有在接受与训练输入相近尺寸的图像时，模型才能取得较好的测试效果。

感谢
