### ISSUE TITLE
预测 vis.py 结果不正确问题

### ISSUE THREAD

**Issue by j2538318409** [PaddlePaddle/PaddleSeg#293]
亲爱的技术人员：
            经过预测时得到的结果全部为黑色的图片

**Comment by j2538318409** [comment]
全部按照你们官方教程走的基本没动，希望早点解决

**Comment by ceci3** [comment]
请问下是哪个模型？

**Comment by wuyefeilin** [comment]
麻烦提供下你运行时候的配置，可以的话请提供一下你的运行日志, 我这边运行正常，请问你的模型训练收敛了吗，mIoU是多少？

**Comment by j2538318409** [comment]
默认的 unet 这个是你们配置文件里面写的

**Comment by j2538318409** [comment]
配置都是你们默认的  我都没动 loss收敛   我有一个问题 我想把电商图像的主体 单独扣出来 适合你们那个模型？

**Comment by wuyefeilin** [comment]
@j2538318409 可以用于商品抠图，商品类别有限的效果好，类别不限的效果会差一些

**Comment by wuyefeilin** [comment]
> 默认的 unet 这个是你们配置文件里面写的

提供一下运行的日志吧，不然我没办法分析

**Comment by j2538318409** [comment]
@wuyefeilin 前几天来了个其他的项目 之前在忙它  现在加载配置文件我加载deeplabv3p_xception65_optic.yaml这个文件 模型还了 就可以处理了 但是效果看起来很模糊 正常我们训练周期数应该是多少？ 还有我现在要进行到自定义数据把电商类型处理一下，有好的建议吗？还有的就是 后期怎么i提供的有增量学习的接口吗

**Comment by j2538318409** [comment]
感谢你的耐心解答！尊敬的技术员

**Comment by wuyefeilin** [comment]
一般训练个100到200就基本差不多，在网上效果肯能不会有明显的改进，当然跟你的数据量也有关，数据量多的话，epochs数可以少一些，数据量少的话可以多一些轮数助于网络学习。

你可以直接用deeplabv3+ xception65 backbone进行训练。

有增量学习的接口的指什么？

**Comment by j2538318409** [comment]
也不是 我用的是你们开源的数据眼底细胞的 但是训练出来的模型处理预测数据时主题部分还是不能完全的抽出，看似效果一般。后期我们新增数据和label的话在原始模型上做增量训练的时候咱们是否提供的有方法

**Comment by wuyefeilin** [comment]
给我看一下你的结果还有你的训练日志，我看看哪边可以改进的，一般这个数据集mIoU是可以达到90%左右的。

如果新增数据的话可以在原始的模型上进行微调，咱们这边没有提供其他的方法，你也可以把所有的数据合在一起进行微调。

**Comment by j2538318409** [comment]
-----------------------------
3. Check test dataset...
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 464
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 645
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 520
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 527
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 565
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 514
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 497
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 475
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 483
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 531
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 511
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 459
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 665
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 478
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 466
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 675
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 489
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 536
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 500
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 519
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 526
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 498
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 528
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 550
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 518
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 507
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 526
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 491
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 542
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 590
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 531
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 492
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 490
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 571
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 483
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 535
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 491
STREAM b'IHDR' 16 13
STREAM b'PLTE' 41 768
STREAM b'IDAT' 821 537

PASS test_list.txt DATASET.SEPARATOR check

PASS dataset reading check
All images can be read successfully

PASS label gray check
All label images are gray

PASS label format check
total 38 label images are png format, 0 label images are not png format

Doing label pixel statistics:
(label class, total pixel number, percentage) = [(0, 9517692, 0.9813), (1, 181636, 0.0187)] 

PASS label class check!

PASS DATASET.IMAGE_TYPE check

Doing max image size statistics:
max width and max height of images are (512,512)

PASS shape check
All images are the same shape as the labels

PASS EVAL_CROP_SIZE check
satisfy current EVAL_CROP_SIZE: (512,512) >= AUG.FIX_RESIZE_SIZE: (512,512)

**Comment by j2538318409** [comment]
如果是微调的话 咱们模型的类别我应该是可以增加或者是减少的吧，而且我还有问题 就是如果我吧模型训练好了 我正常开发api服务 服务于我抠图的项目 但是我看怎么的vis是在配置文件里面指定好的 这部分我应该怎么处理

**Comment by j2538318409** [comment]
您可以给我您的联系方式吗  我这对于自定义数据集有很多不解的地方 方便沟通

**Comment by wuyefeilin** [comment]
@j2538318409 加我微信cgw642982169

**Comment by lyc1995452-star** [comment]
请问你们在运行可视化时，出现这种情况没？
Traceback (most recent call last):
File "vis.py", line 212, in
visualize(cfg, **args.dict)
File "vis.py", line 133, in visualize
for imgs, grts, img_names, valid_shapes, org_shapes in test_reader:
File "/PaddleSeg-release-v0.7.0/pdseg/reader.py", line 136, in batch_reader
for img, grt, img_name, valid_shape, org_shape in reader():
File "/PaddleSeg-release-v0.7.0/pdseg/reader.py", line 81, in generator
yield self.process_image(line, self.data_dir, self.mode)
File "/PaddleSeg-release-v0.7.0/pdseg/reader.py", line 251, in process_image
line, data_dir, mode=mode)
File "/PaddleSeg-release-v0.7.0/pdseg/reader.py", line 205, in load_image
grt_height = grt.shape[0]
IndexError: tuple index out of range
