### ISSUE TITLE
Medicalseg nnformer相关 其他数据集向数据集ACDC格式的转换

### ISSUE THREAD

**Issue by 258863** [PaddlePaddle/PaddleSeg#2935]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包含open与closed)，没有类似需求。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; 2. 需求场景（请描述你的项目中为什么需要用此功能）; 3. 功能描述（请简单描述或设计这个功能）

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by shiyutang** [comment]
medicalseg目前均对数据先进行预处理转换成npy文件后再进行训练，因此使用nnformer不需要将数据集转换到ACDC，只需要将你的数据集继承 prepare.py 进行需要的数据加载、划分、和缩放保存成npy文件后，即可使用nnformer进行训练。

prepare.py: https://github.com/PaddlePaddle/PaddleSeg/blob/develop/contrib/MedicalSeg/tools/prepare.py
继承prepare.py 进行数据预处理的示例：https://github.com/PaddlePaddle/PaddleSeg/blob/develop/contrib/MedicalSeg/tools/prepare_mri_spine_seg.py

**Comment by 258863** [comment]
![image](https://user-images.githubusercontent.com/91120551/216219377-c7e82ef9-5234-4849-8979-d09b4cb33f03.png)
训练集转成npy后用修改后的nnformer acdc配置文件训练出现以下错误改如何解决呢

**Comment by 258863** [comment]
![image](https://user-images.githubusercontent.com/91120551/216219922-0d7495c8-d4e2-471e-ade9-fa8c0fba4dd1.png)
只修改了训练文件地址和训练的数据类型

**Comment by shiyutang** [comment]
ACDC的数据集不是你截图展示的MSDDataset，而是ACDC，建议切换到ACDC数据集后训练查看是否有报错
<img width="389" alt="image" src="https://user-images.githubusercontent.com/34859558/216292565-9ddf1997-2457-483c-ae50-36c7cd434d84.png">

**Comment by shiyutang** [comment]
这个问题已经长期没有回复，暂时关闭，如有需要可以回复issue，或者再次打开。
