### ISSUE TITLE
[General Issue]验证时报错：Shape of `pred` and `label should be equal, but there are [1, 5472, 3648] and [1, 3648, 5472].

### ISSUE THREAD

**Issue by dsfcdsfdg** [PaddlePaddle/PaddleSeg#2943]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在PSPnet 验证时报错
ValueError: Shape of `pred` and `label should be equal, but there are [1, 5472, 3648] and [1, 3648, 5472].

比较奇怪的是我在另一台服务器上可以运行，但是在第40个epoch的val的时候显示 cuda out of memory，我的batch size已经调到2了.

  dataset_root: /home/xxxx/Paddle/PaddleSeg/total_images/
  img_channels: 3
  mode: train
  num_classes: 2
  train_path: /home/xxxx/Paddle/PaddleSeg/total_images/train.txt
  transforms:
  - max_scale_factor: 2.0
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - crop_size:
    - 1024
    - 512
    type: RandomPaddingCrop
  - type: RandomHorizontalFlip
  - brightness_range: 0.4
    contrast_range: 0.4
    saturation_range: 0.4
    type: RandomDistort
  - type: Normalize
  type: Dataset
val_dataset:
  dataset_root: /home/xxxx/Paddle/PaddleSeg/total_images/
  img_channels: 3
  mode: val
  num_classes: 2
  transforms:
  - type: Normalize
  type: Dataset
  val_path: /home/xxxx/Paddle/PaddleSeg/total_images/val.txt

**Comment by shiyutang** [comment]
这个是说明数据和标签的形状不匹配，请检查你的源数据集是否存在图像和标签的形状不一致的问题。
如果出现OOM报错，说明确实超出显存限制，看到你的数据较大，可以考虑进行裁剪后进行训练，后面可以通过滑窗推导的形式在全图上推理预测结果。

**Comment by dsfcdsfdg** [comment]
数据源和标签都是同一组照片，根据给的划分数据的代码随机划分的。
好的，我会试试剪裁的

**Comment by shiyutang** [comment]
嗯嗯，你可以看看是不是有标签和数据组存在尺寸不匹配的问题。

**Comment by dear-xiaozhu** [comment]
我在跑segnet的第一批验证集的时候也报了类似的错误
ValueError: Shape of `pred` and `label should be equal, but there are [1, 420, 520] and [1, 421, 520].
可是我检查了验证集，他的原图和标签尺寸明明是一样的啊！就很迷惑 @shiyutang 
在网上各种找问题，也没找出来，还请大神指教

**Comment by shiyutang** [comment]
这两个问题应该不是同一个原因：
1. 第二个问题中图片的shape和label只有微小的差距，说明可能是下采样的倍数过多导致下采样中做了近似操作，建议在上采用中使用size=(H，W)，而不是设置ratio=2，其中HW为输入的尺寸。
2. 第一个问题，应该长宽不匹配的原因，需要从数据层面查看。

**Comment by yangkey87** [comment]
> 我在跑segnet的第一批验证集的时候也报了类似的错误 ValueError: Shape of `pred` and `label should be equal, but there are [1, 420, 520] and [1, 421, 520]. 可是我检查了验证集，他的原图和标签尺寸明明是一样的啊！就很迷惑 @shiyutang 在网上各种找问题，也没找出来，还请大神指教

Hi，我也遇到了同样的问题，后来发现确实是我的 label image 的长和宽相比于原图对调了。出现这个问题的原因是，我在生成label image 的时候使用了原图的长和宽去生成 label image，我用的 PIL 的 Image class 读取的图片。但是读取图片有一个坑，你需要这样写代码才能保证图片没有被随机的翻转：
`from PIL import Image, ImageChops
img = Image.open(image_path)
img = ImageOps.exif_transpose(img)`

我也是研究半天才发现，这样能解决我的问题，你试试
