### ISSUE TITLE
PaddleSeg只支持手动修改config吗，支持命令行 -o 修改参数吗？

### ISSUE THREAD

**Issue by MooTong123** [PaddlePaddle/PaddleSeg#2947]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

1. 请问下 paddleSeg 支持命令行 -o 修改参数嘛？换数据集时还得手动修改数据集路径，有点麻烦。
![image](https://user-images.githubusercontent.com/44767255/216289063-1583013c-2b84-4559-bf26-4c27361dd6d2.png)

**Comment by Bobholamovic** [comment]
可以的，请使用`--opts`选项修改。例如`--opts train_dataset.dataset_root=xxx`。

**Comment by MooTong123** [comment]
> 
不支持--opts啊...
![image](https://user-images.githubusercontent.com/44767255/216492962-03b0784b-aaf6-4189-b279-ae18c63e0a7b.png)

**Comment by Bobholamovic** [comment]
请使用 release/2.7 版本或最新 develop 分支。
请注意，release/2.7版本的 key value 间需使用空格分隔（如 `--opts a 1`），而 develop 分支使用等号（如 `--opts a=1`）。

**Comment by MooTong123** [comment]
> 
你好，我用了--opts之后，但是无法进行赋值。
1. 训练命令：
![image](https://user-images.githubusercontent.com/44767255/216504669-a99b57a5-c1b4-492c-b78c-7e2042fa614d.png)

2. 配置文件：
![image](https://user-images.githubusercontent.com/44767255/216504829-a83ee356-f018-440b-8b93-0165241d13d4.png)


3. 然后报错，我print一下文件路径，发现是None。
![image](https://user-images.githubusercontent.com/44767255/216505083-0789af3e-31ff-438c-bb33-b4bf8456db75.png)

![image](https://user-images.githubusercontent.com/44767255/216504935-812ea0ef-249c-4f08-9ebe-c5b701546614.png)

**Comment by Bobholamovic** [comment]
在 PaddleSeg r2.7 中，重复指定 `--opts` 将导致『覆盖』而非『追加』行为。例如，以下用法：

```shell
python tools/train.py --opts a 1 --opts b 2
```

`b 2` 选项将覆盖 `a 1` 选项。正确的用法为：

```shell
# 只要写一次 `--opts`
python tools/train.py --opts a 1 b 2
```

建议在所有命令行选项的最后指定 `--opts`。在今后的版本中，我们将考虑为 `opts` 制定『追加』行为，以便利用户使用。

**Comment by MooTong123** [comment]
感谢回答，已解决
