### ISSUE TITLE
Why PP-Matting-1024 has worse metrics than PP-Matting-512

### ISSUE THREAD

**Issue by unihornWwan** [PaddlePaddle/PaddleSeg#2951]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hi, first of all thank you for your great contribution.

When I observed the metrics of each model in Matting/README.md, I found that PP-Matting-512 ranked first in the three indicators of SAD, MSE, and Conn, PP-Matting-1024 was very low in these three indicators.  According to the configuration file, the difference between the two models are max_short and crop_size during training and validation, then I have the following 2 questions:
1. Is the reason for the poor metrics of PP-Matting-1024 is that high-resolution images are also used in the test, so the difficulty of matting is very high ?
2. If the first point is correct, when both PP-Matting-1024 and PP-Matting-512 are tested on the test set with a resolution of 512, will the performance of PP-Matting-1024 be better?

Looking forward to your reply.

**Comment by wuyefeilin** [comment]
> 

1. Yes, you are right
2. We don't test like this, maybe you can have a try and share with us.
