### ISSUE TITLE
2.4 TensorRT

### ISSUE THREAD

**Issue by m828** [PaddlePaddle/PaddleSeg#2955]
### 问题描述 Please describe your issue

![image](https://user-images.githubusercontent.com/45037914/216915551-1592bad5-3b23-4ffd-b1c9-1257bbc99d59.png)
2.4的预测库hai'mei'chu还没出来吗

**Comment by juncaipeng** [comment]
2.4版本，支持TRT的Python库，直接参考下面文档安装，应该不需要独立下载了：
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4/install/pip/linux-pip.html#erkaishianzhuang

**Comment by m828** [comment]
> 

好的，谢谢
