### ISSUE TITLE
ModuleNotFoundError: No module named 'paddle'

### ISSUE THREAD

**Issue by sansarnia** [PaddlePaddle/PaddleSeg#2957]
Hello, i'm in the very first steps to intall the environement. 
so I did first install **PaddlePaddle**.  and `paddle.utils.run_check()` outputs this : 

> PaddlePaddle works well on 1 GPUs.                                                                                      
> PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.   
 
while installing **PaddleSeg**, I run `pip install -r requirements.txt` then, `pip install -v -e .` it outputs : 

> Successfully installed paddleseg-2.7.0

but, when i want to verify installation with `sh tests/install/check_predict.sh` (I use git bash in windows to run this), it outputs this error: ModuleNotFoundError: No module named 'paddle'

am i doing something wrong?
thanks in advance.

**Comment by juncaipeng** [comment]
Sorry, I can not figure out the problem. You can use `pip list`  to double check whether PaddlePaddle is installed.

**Comment by sansarnia** [comment]
`pip list` outputs this :
![image](https://user-images.githubusercontent.com/62647698/217259197-5020be01-1a0a-4580-a9f8-1a12ff2f78c0.png)

is it because i'm using anaconda?
is "PaddlePaddle" the same thing as "Paddle"?

**Comment by styrmis** [comment]
@shireen1512 I think you may have missed [this step](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/docs/install.md#21-install-paddlepaddle), for installing the PaddlePaddle library, which PaddleSeg needs in order to run.

**Comment by shiyutang** [comment]
It could be the environment diff of git bash and where you install the environment(perhaps windows terminal?)  I guess you need to run the predict command in the windows terminal or other user terminal.

**Comment by sansarnia** [comment]
indeed that was the problem, i shouldn't have used git bash it's not the same environement 🤦‍♂️ 
thank you.

**Comment by shiyutang** [comment]
good job and thanks for your update.
