### ISSUE TITLE
关于输入图片的问题

### ISSUE THREAD

**Issue by lxk767363331** [PaddlePaddle/PaddleSeg#296]
我在使用4通道图片作为输入时 没有修改rgb 和通道数 ，但是运行没有报错， 想问一下 这种情况下输入图片输入的情况还是4通道么  参数如下：
图片：512*384*4  
输入图片：512，512 stepscaling
# 图像镜像左右翻转
cfg.AUG.MIRROR = True
# 图像上下翻转开关，True/False
cfg.AUG.FLIP = True

**Comment by wuyefeilin** [comment]
如果cfg.DATASET.IMAGE_TYPE = 'rgb', 会忽略掉第4通道，只读取前面三个通道的数据
