### ISSUE TITLE
ppliteseg测试camvid数据集

### ISSUE THREAD

**Issue by m828** [PaddlePaddle/PaddleSeg#2961]
### 问题描述 Please describe your issue

![image](https://user-images.githubusercontent.com/45037914/217242339-81d35e58-ec21-41bc-b6fe-77aa69808f99.png)
下载的是官网的权重，我看配置文件给的数据类型是Dataset，使用的是源代码，结果很差，是什么原因呢?源代码不能直接复现吗？（cityscapes数据集就可以直接复现）
![image](https://user-images.githubusercontent.com/45037914/217242566-87b478b4-bdab-41e1-8828-53333729dac7.png)

**Comment by Sunting78** [comment]
您好，经测试运行结果正常，请检查下载的模型是否正确，未解决的话贴下你的运行命令和完整输出。

**Comment by m828** [comment]
> 您好，经测试运行结果正常，请检查下载的模型是否正确，未解决的话贴下你的运行命令和完整输出。

那就奇怪了，我又试了一遍，
命令：python val.py --config configs\pp_liteseg\pp_liteseg_stdc2_cityscapes_1024x512_scale1.0_160k.yml --model_path output/city/model.pdparams
cityscapes的结果：
![image](https://user-images.githubusercontent.com/45037914/217449095-2c644f55-90ef-40e4-b091-750d49402587.png)

什么都没动，camvid:
命令：python val.py --config configs\pp_liteseg\pp_liteseg_stdc2_camvid_960x720_10k.yml --model_path output/camvid/model.pdparams
![image](https://user-images.githubusercontent.com/45037914/217449395-0d28fbb5-772f-49de-a954-7b5636d95717.png)

**Comment by m828** [comment]
![image](https://user-images.githubusercontent.com/45037914/217450196-dc318be4-ffa9-4aef-ad46-34483b01af8f.png)
![image](https://user-images.githubusercontent.com/45037914/217450273-2b73560e-0bb3-44d6-9106-de4f3a32629b.png)
![image](https://user-images.githubusercontent.com/45037914/217450327-552f6a2c-b466-4390-ab64-8eade5d53671.png)

**Comment by m828** [comment]
camvid数据集格式：
val.txt:
![image](https://user-images.githubusercontent.com/45037914/217451527-abbcb008-2b34-4454-9441-8088e9c3a677.png)

labels:
![image](https://user-images.githubusercontent.com/45037914/217452320-23d0fca9-a5e8-4898-bf0d-a232f044d9f2.png)

**Comment by Sunting78** [comment]
猜测是数据标签错误：
<img width="768" alt="image" src="https://user-images.githubusercontent.com/18344247/217519072-30f8c0e2-585d-45f6-9fd5-7e2436e403d5.png">

1.  检查camvid数据集标签，可根据此[链接](https://paddleseg.bj.bcebos.com/dataset/camvid.tar)下载，无需自己转换标签，下载后包含val.txt文件。
2. 建议使用最新版代码，解决预训练模型warning问题，可参考#2181

**Comment by m828** [comment]
> 猜测是数据标签错误： <img alt="image" width="768" src="https://user-images.githubusercontent.com/18344247/217519072-30f8c0e2-585d-45f6-9fd5-7e2436e403d5.png">
> 
> 1. 检查camvid数据集标签，可根据此[链接](https://paddleseg.bj.bcebos.com/dataset/camvid.tar)下载，无需自己转换标签，下载后包含val.txt文件。
> 2. 建议使用最新版代码，解决预训练模型warning问题，可参考[[Fix] Fix the warning of stdcnet when loading pretrained weights #2181](https://github.com/PaddlePaddle/PaddleSeg/pull/2181)

感谢感谢，解决了，是数据集的问题
