### ISSUE TITLE
ubuntu18.04  安装了GDAL，eiseg无法导入。

### ISSUE THREAD

**Issue by Seiano** [PaddlePaddle/PaddleSeg#2962]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

ubuntu18.04  conda安装了GDAL，rasterio也安装了，在python环境下可以导入。但是打开eiseg的界面  显示设置--遥感设置 的时候，提示我无法导入GDAL和rasterio。

**Comment by Bobholamovic** [comment]
请问 EISeg 是在相应的 anaconda 环境中启动的嘛？

**Comment by Seiano** [comment]
是的

**Comment by Seiano** [comment]
当我点击页面显示/遥感设置的时候他提示我无法导入GDAL或rasterio。使用遥感工具需要安装GDAL和rasterion。
![2023-02-20 170852](https://user-images.githubusercontent.com/44127890/220061993-78552bfd-8cfa-4fb6-b018-f8734a31e4be.jpg)
![2023-02-20 170852(1)](https://user-images.githubusercontent.com/44127890/220062039-0a44ec56-7c3d-4e85-82a2-89f2d8c01f1d.jpg)

@Bobholamovic

**Comment by Bobholamovic** [comment]
抱歉回复迟了 请确保 GDAL 的 **Python** 库正常安装。检查方法为

```shell
python -c "from osgeo import gdal"
```

如果没有正常安装，在 Linux 环境中建议使用 anaconda 安装：

```shell
conda install gdal
```
