### ISSUE TITLE
ppmatting backbone w48效果不如w18，正常么

### ISSUE THREAD

**Issue by Hubert2102** [PaddlePaddle/PaddleSeg#2964]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

训练抠图模型，同样的数据，只有HRNET骨干网络不一样，
预训练模型
w18是https://paddleseg.bj.bcebos.com/matting/models/ppmatting-hrnet_w18-human_512.pdparams
w48是https://paddleseg.bj.bcebos.com/matting/models/ppmatting-hrnet_w48-distinctions.pdparams
但是训练之后对比结果，w18的更好

**Comment by Bobholamovic** [comment]
请问具体是在什么数据集上训练的呢？当训练样本不足的时候，容量较小的模型（如 W18）受到过拟合现象影响更小，可能能够在验证集/测试集上取得比大容量模型更好的效果。

**Comment by Hubert2102** [comment]
> 请问具体是在什么数据集上训练的呢？当训练样本不足的时候，容量较小的模型（如 W18）受到过拟合现象影响更小，可能能够在验证集/测试集上取得比大容量模型更好的效果。

自己场景的人物数据集，有7万张图做训练，我理解不至于过拟合呀

**Comment by Stinky-Tofu** [comment]
> 

请问这两个模型的训练和测试环境是一样的吗？

**Comment by Hubert2102** [comment]
> 

一样的

**Comment by Harryoung** [comment]
会不会和w18用的human预训练，而w48用的distinctions物体预训练有关？
