### ISSUE TITLE
How can I use PaddleSeg like diffusers without knowing any information about the model but the image path

### ISSUE THREAD

**Issue by winnechan** [PaddlePaddle/PaddleSeg#2967]
### 问题描述 Please describe your issue

Hi, I want to use one of the provided segmentation models in PaddleSeg for inference in python. However, I have no idea about any parameter concerning the model like num_classe or specific image transform, but only the image path. Is there any way to use the tool like diffusers?

**Comment by juncaipeng** [comment]
We provide detailed usage documentation.   https://github.com/PaddlePaddle/PaddleSeg
You have to read the tutorials and follow the quick start to train and test segmentation model.
