### ISSUE TITLE
运行抠图模型时发生错误

### ISSUE THREAD

**Issue by ccx2022** [PaddlePaddle/PaddleSeg#2968]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

使用eiseg的加载MODNet-MobileNetV2进行抠图，加载模型和添加标签后，鼠标点击抠图区域时软件闪退并报错。
![image](https://user-images.githubusercontent.com/116274341/218254358-cc0145b6-2755-4746-a3f2-8d0e2c74977e.png)
![image](https://user-images.githubusercontent.com/116274341/218254379-b41763cb-19e0-4d3f-b2a1-f518ec641d0d.png)

### 复现环境 Environment

Windos11
python 3.7
cuda 11.6

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by juncaipeng** [comment]
modnet_mv2是你自己的模型吗？ [eiseg](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/EISeg/docs/image.md)没有提供改模型，只能使用官方提供的模型进行标注。

**Comment by ccx2022** [comment]
![Uploading image.png…]()
是你们官方提供的抠图预训练模型，我运行其他官方提供的抠图模型也一样，鼠标点击后就会报错。

**Comment by Harryoung** [comment]
EISeg使用的是专门的【交互式分割模型】，普通的分割模型是用不了的哈，必然会报错。具体原理可参考EISeg中引用的几篇论文。
