### ISSUE TITLE
请问PP-HumanSeg中的inference_models和pretrained_models有什么区别？

### ISSUE THREAD

**Issue by fengyuentau** [PaddlePaddle/PaddleSeg#2969]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

实际使用的是inference_models，但提供的eval脚本只能对pretrained_models评估。我尝试评估infernece_models，但提示只能用pdparams。请问怎么评估inference_models？

**Comment by juncaipeng** [comment]
pretrained_model是动态图模型训练保存的权重，可以用于动态图测试和继续finetune。
inference_model是导出的静态图预测模型，直接用于部署。

**Comment by fengyuentau** [comment]
感谢回答！inference_model是由pretrained_model导出，因此两者的准确率应该不会发生变化吧？

**Comment by juncaipeng** [comment]
是的
