### ISSUE TITLE
请问人像分割的置信度在哪里调式，有些目标不全的就不想要了

### ISSUE THREAD

**Issue by 15651196171** [PaddlePaddle/PaddleSeg#2975]
### 问题描述 Please describe your issue

请问人像分割的置信度在哪里调式，有些目标不全的就不想要了

**Comment by shiyutang** [comment]
请问目标不全是什么含义，是否有示例图片可以说明？

**Comment by shiyutang** [comment]
人像分割infer时中有个后处理设置use_post_process，可以修改内部参数达到需求：https://github.com/PaddlePaddle/PaddleSeg/blob/19351bab9a824a8f96e1c1b527ec2d7db21309c9/contrib/PP-HumanSeg/src/infer.py#L129
