### ISSUE TITLE
Release2.7版本哪些模型支持转onnx？

### ISSUE THREAD

**Issue by LLsmile** [PaddlePaddle/PaddleSeg#2977]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

哪里能看到模型是否支持转onnx?　paddle2onnx里的[列表](https://github.com/PaddlePaddle/Paddle2ONNX/blob/v1.0.5/docs/en/model_zoo.md)感觉太古老了，应该不是最新的。

**Comment by Bobholamovic** [comment]
目前 PaddleSeg 中的大部分模型都支持转 ONNX，少部分模型由于存在控制流算子等问题可能无法转换（已知可能存在问题的有 SETR、SegNet、GSCNN、EPSNetV2和EMANet）。建议你可以先尝试转换需要的模型，如果遇到问题的话欢迎在 issue 区提问。
