### ISSUE TITLE
请问怎么计算模型的速度

### ISSUE THREAD

**Issue by l494342511** [PaddlePaddle/PaddleSeg#2979]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问如何计算模型的速度，我自己写了个程序计算PP-LiteSeg-B2的速度，输入是512*512，在3080上只有50fps

**Comment by Bobholamovic** [comment]
在模型训练阶段（使用`tools/train.py`）， PaddleSeg 会给出处理一个 mini-batch 的总耗时和数据读取+预处理耗时（单位均为秒），并计算 IPS（每秒指令数，在 PaddleSeg 中对应每秒处理的样本数）和 ETA （预计到达时间，可理解为完成训练过程还需要多长时间），如下图所示，通过这些统计数据可以评估模型训练速度。

![image](https://user-images.githubusercontent.com/21275753/220269649-f3256a15-68ba-4f98-abe0-c4d09affe074.png)

在模型推理阶段（使用`deploy/python/infer.py`），指定`--benchmark=True` 进行测速，获取推理阶段的预处理耗时和模型前向耗时等信息（如下图）。请注意，使用此功能需要 AutoLog 库的支持，请参考[此文档](https://github.com/LDOUBLEV/AutoLog/blob/main/README.md)手动安装。

![image](https://user-images.githubusercontent.com/21275753/220269347-d45e0f63-3758-4108-9e2c-bbcce6f06f9f.png)

如果你计划使用自己编写的程序进行测速，并且认为测试出来的速度指标不符合预期，也欢迎在此 issue 中贴出代码，我们可以一起交流讨论。

**Comment by l494342511** [comment]
感谢回答，我想可能原因是论文中用tensorRT测试，相比直接pytorch推理有加速作用

**Comment by juncaipeng** [comment]
你好，这里提供了pp-liteseg测速的文档和代码： https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.7/configs/pp_liteseg
