### ISSUE TITLE
遥感影像语义分割

### ISSUE THREAD

**Issue by chang-png** [PaddlePaddle/PaddleSeg#298]
能否提供一下数据装换为npy格式数据的过程，在转的过程中有一部分图片转换不了
，为什么

**Comment by HOLLIZHAO** [comment]
对于您自己的数据集，您需要按照上述的数据协议进行格式转换，可分别使用numpy和Pillow库保存遥感数据和标注图片。其中numpy API示例如下：

```python
import numpy as np

# 将遥感数据保存到以 .npy 为扩展名的文件中
# img类型：numpy.ndarray
np.save(save_path, img)
```

官方给的文档如上，我使用可以转换。tif转成npy文件。

**Comment by chang-png** [comment]
想问一下，我有三通道的数据我用paddleseg里面的模型进行训练和用RemoteSensing训练有啥区别吗

**Comment by KuntaHu** [comment]
这个模型的输入好像设定为npy数据，所以即使是三通道数据，也建议能够从tiff转到npy之后，进行训练

**Comment by HOLLIZHAO** [comment]
> 想问一下，我有三通道的数据我用paddleseg里面的模型进行训练和用RemoteSensing训练有啥区别吗

模型都是一样的。RemoteSensing是 PaddleSeg产业实践案例中的其中一个，包含了全流程的落地代码，有相关行业数据了就可以直接上手跑模型了，可以非常便捷地落地相关应用。

**Comment by HOLLIZHAO** [comment]
> 这个模型的输入好像设定为npy数据，所以即使是三通道数据，也建议能够从tiff转到npy之后，进行训练

最新的develop分支已经支持tif、img、png、npy 4种格式的直接读取，这四种格式的数据可以直接读取喂入，更加方便。😁

**Comment by chang-png** [comment]
我就想问一下遥感影像能用paddleseg里面的模型去跑会不会有问题






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Holli"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月23日(星期二) 下午3:09
收件人:&nbsp;"PaddlePaddle/PaddleSeg"<PaddleSeg@noreply.github.com&gt;;
抄送:&nbsp;"暮冬-　Gentle°"<1731400493@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] 遥感影像语义分割 (#298)





  
想问一下，我有三通道的数据我用paddleseg里面的模型进行训练和用RemoteSensing训练有啥区别吗
  
模型都是一样的。RemoteSensing是 PaddleSeg产业实践案例中的其中一个，包含了全流程的落地代码，有相关行业数据了就可以直接上手跑模型了，可以非常便捷地落地相关应用。

**Comment by HOLLIZHAO** [comment]
> 我就想问一下遥感影像能用paddleseg里面的模型去跑会不会有问题


遥感图像分割，目前业界落地用得比较多的模型有U-Net，HRNet等，paddleseg都有提供。目前用来做自动解译，效果很好，至少可以节约一半的人力成本。

**Comment by chang-png** [comment]
我的意思使用paddleseg提供的deeplab等网络去训练遥感影像，有没有问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Holli"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月23日(星期二) 下午4:01
收件人:&nbsp;"PaddlePaddle/PaddleSeg"<PaddleSeg@noreply.github.com&gt;;
抄送:&nbsp;"暮冬-　Gentle°"<1731400493@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] 遥感影像语义分割 (#298)





  
我就想问一下遥感影像能用paddleseg里面的模型去跑会不会有问题
  
遥感图像分割，目前业界落地用得比较多的模型有U-Net，HRNet等，paddleseg都有提供。目前用来做自动解译，效果很好，至少可以节约一半的人力成本。

**Comment by wuyefeilin** [comment]
@chang-png 只有你的标注符合标注协议，图像能利用opencv进行读取是可以利用pdseg下的模型进行训练的，pdseg下模型目前最多支持4通道的图像。你可以选择将遥感图像数据转换成jpg或png格式。

**Comment by HOLLIZHAO** [comment]
> 我的意思使用paddleseg提供的deeplab等网络去训练遥感影像，有没有问题

完全没问题！👍👍👍

**Comment by ZeyuChen** [comment]
@HOLLIZHAO 感谢HOLLI同学的回复支持 :)

**Comment by wwj-b221** [comment]
> 
> 
> > 这个模型的输入好像设定为npy数据，所以即使是三通道数据，也建议能够从tiff转到npy之后，进行训练
> 
> 最新的develop分支已经支持tif、img、png、npy 4种格式的直接读取，这四种格式的数据可以直接读取喂入，更加方便。😁

请问遥感的develop分支在哪里找呢，models里只看到了unet和hrnet

**Comment by HOLLIZHAO** [comment]
> > > 这个模型的输入好像设定为npy数据，所以即使是三通道数据，也建议能够从tiff转到npy之后，进行训练
> > 
> > 
> > 最新的develop分支已经支持tif、img、png、npy 4种格式的直接读取，这四种格式的数据可以直接读取喂入，更加方便。😁
> 
> 请问遥感的develop分支在哪里找呢，models里只看到了unet和hrnet

PaddleSeg遥感影像分割可以参看：https://github.com/PaddlePaddle/PaddleSeg/tree/develop/contrib/RemoteSensing

**Comment by w867066886** [comment]
> > > > 这个模型的输入好像设定为npy数据，所以即使是三通道数据，也建议能够从tiff转到npy之后，进行训练
> > > 
> > > 
> > > 最新的develop分支已经支持tif、img、png、npy 4种格式的直接读取，这四种格式的数据可以直接读取喂入，更加方便。😁
> > 
> > 
> > 请问遥感的develop分支在哪里找呢，models里只看到了unet和hrnet
> 
> PaddleSeg遥感影像分割可以参看：https://github.com/PaddlePaddle/PaddleSeg/tree/develop/contrib/RemoteSensing

遥感分割不能实现jpg的吗，需要转换成tiff吗

**Comment by HOLLIZHAO** [comment]
> > > > > 这个模型的输入好像设定为npy数据，所以即使是三通道数据，也建议能够从tiff转到npy之后，进行训练
> > > > 
> > > > 
> > > > 最新的develop分支已经支持tif、img、png、npy 4种格式的直接读取，这四种格式的数据可以直接读取喂入，更加方便。😁
> > > 
> > > 
> > > 请问遥感的develop分支在哪里找呢，models里只看到了unet和hrnet
> > 
> > 
> > PaddleSeg遥感影像分割可以参看：https://github.com/PaddlePaddle/PaddleSeg/tree/develop/contrib/RemoteSensing
> 
> 遥感分割不能实现jpg的吗，需要转换成tiff吗

jpg格式也是可以的。 可以把jpg统一转成npy就行了。
