### ISSUE TITLE
在nnunet中如何更改batchsize

### ISSUE THREAD

**Issue by 258863** [PaddlePaddle/PaddleSeg#2980]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在nnunet中如何更改batchsize

**Comment by shiyutang** [comment]
nnunet中的batchsize可以在配置文件中指定，或者使用命令行直接指定。
<img width="527" alt="image" src="https://user-images.githubusercontent.com/34859558/220264154-8f8f094e-7835-4bd3-b9fd-f09ea4d92c04.png">
<img width="348" alt="image" src="https://user-images.githubusercontent.com/34859558/220264289-74ce8484-3e77-49cb-8c83-90b39975adc0.png">
