### ISSUE TITLE
Bug founded in RandomCrop4D, MedicalSeg

### ISSUE THREAD

**Issue by limberc** [PaddlePaddle/PaddleSeg#2981]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

In latest MedicalSeg:
```python
python train.py --config configs/msd_brain_seg/unetr_msd_brain_seg_1e-4.yml
```

We have found that the transformation in https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/contrib/MedicalSeg/medicalseg/transforms/transform.py#L586

I have got:

```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 247, in _thread_loop
    batch = self._dataset_fetcher.fetch(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/paddle/fluid/dataloader/fetcher.py", line 127, in fetch
    data.append(self.dataset[idx])
  File "/home/ubuntu/PaddleSeg/contrib/MedicalSeg/medicalseg/datasets/dataset.py", line 117, in __getitem__
    im, label = self.transforms(im=image_path, label=label_path)
  File "/home/ubuntu/PaddleSeg/contrib/MedicalSeg/medicalseg/transforms/transform.py", line 67, in __call__
    outputs = op(im, label)
  File "/home/ubuntu/PaddleSeg/contrib/MedicalSeg/medicalseg/transforms/transform.py", line 614, in __call__
    i, j, k, d, h, w = self.get_params(img, self.scale, self.ratio,
  File "/home/ubuntu/PaddleSeg/contrib/MedicalSeg/medicalseg/transforms/transform.py", line 603, in get_params
    k = random.randint(0, img.shape[3] - w)
IndexError: tuple index out of range
```

The image shape is `(128, 128, 128)`. Therefore, the index should not be `3`. 

What's more, 
if `size = img.shape[0]`, which in this config, the given size is identical to the image shape. In this case, the randint will only return 0.

### 复现环境 Environment

- OS: Linux
- PaddlePaddle: 2.4.1
- PaddleSeg: release/2.7
- Python: 3.9
- CUDA: 11.7
- CUDNN: 8.5

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by shiyutang** [comment]
Indeed, if you ser the image size as 128 in image processing, the RandomCrop4D will not do anything. You can simple remove this augmentation to reproduce the result. And I will fix the index bug in the following PR. :)

**Comment by shiyutang** [comment]
I validate that after preprocessoing the data and training the model, one of the img.shape is 4d of [4, 155, 240, 240] rather than [128, 128, 128]. I wonder when you will get the image in 3D. If the scenario is expected, we can change img.shape[1] to img.shape[-3] and so on. 

<img width="612" alt="image" src="https://user-images.githubusercontent.com/34859558/220245569-531adeac-d2ce-475b-b823-06e824bfeb9e.png">

**Comment by limberc** [comment]
Thanks for your elaborate feedback!

In this case, I think this might be problem with the pre-processing script for the MSD dataset. 

Could you update the ready-to-go version of the pre-processing script for all MSD dataset?

Also, by default, the `dataset.json` is not at the `Task_XX_raw` folder. I have to manually copy the `dataset.json` to sub folder.

**Comment by shiyutang** [comment]
In my previous example, I preprocess the MSD dataset with the tools/prepare_msd_brain_seg.py. The result seems to be alright.
And we provide an full MSD preprocess script in tools/prepare_msd.py, you can try to use this and provide us with the feedback if there is anything unexpected happen.
Also, I checked out the place of the dataset.json file, it seems to be the correct place. 
<img width="285" alt="image" src="https://user-images.githubusercontent.com/34859558/220500507-50013b3c-cced-4ed1-aa8c-a63d79a629d6.png">
