### ISSUE TITLE
tti（tampered text image）应用，现在准确率比较高的图像分割模型是哪个？

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/PaddleSeg#2982]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

如题，最近阿里有个比赛，想用paddleseg试试
https://tianchi.aliyun.com/competition/entrance/532052/information

**Comment by Stinky-Tofu** [comment]
> ### 问题确认 Search before asking
> * [x]  我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.
> 
> ### 请提出你的问题 Please ask your question
> 如题，最近阿里有个比赛，想用paddleseg试试 https://tianchi.aliyun.com/competition/entrance/532052/information

你好，目前PPSeg的SOTA模型是MscaleOCRNet，https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.7/contrib/CityscapesSOTA
