### ISSUE TITLE
ppliteseg预训练权重

### ISSUE THREAD

**Issue by m828** [PaddlePaddle/PaddleSeg#2983]
### 问题描述 Please describe your issue

请问ppliteseg预训练权重是通过ImageNet1k训练的吗，我自己修改了解码器，想要重新训练或者微调一下权重，请问有配置文件吗？

**Comment by Stinky-Tofu** [comment]
> ### 问题描述 Please describe your issue
> 请问ppliteseg预训练权重是通过ImageNet1k训练的吗，我自己修改了解码器，想要重新训练或者微调一下权重，请问有配置文件吗？

什么配置文件？

**Comment by m828** [comment]
> > ### 问题描述 Please describe your issue
> > 请问ppliteseg预训练权重是通过ImageNet1k训练的吗，我自己修改了解码器，想要重新训练或者微调一下权重，请问有配置文件吗？
> 
> 什么配置文件？

ppliteseg的预训练权重怎么训练的？比如epoch，学习率，训练时是否有预训练权重

**Comment by juncaipeng** [comment]
ppliteseg预训练权重是通过ImageNet1k训练的。 这个配置文件没有公开，不过可以参考paddleclas套件里面的通用训练配置。
