### ISSUE TITLE
EIsegMed3自己训练模型教程

### ISSUE THREAD

**Issue by masamimayu** [PaddlePaddle/PaddleSeg#2984]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包含open与closed)，没有类似需求。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar feature requests.

### 需求描述 Feature Description

目前只有给定的椎体mri模型，是否可以自己训练模型，如果可以的话如何实现呢~

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by shiyutang** [comment]
您好，暂不支持自己训练其他模型，如果有需要可以进一步说明需求，我们可以为您提供训练模型。
