### ISSUE TITLE
paddleseg为什么载入配置文件和模型后就结束了，没有任何报错且不开始训练？

### ISSUE THREAD

**Issue by censhallwe** [PaddlePaddle/PaddleSeg#2986]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我用的是自定义的数据集，10个类别，之前在MobileNetV2上训练效果可以，是可以训练的，但是尝试把模型换成HarDNet和SFNet，改了对应的配置文件后就不行，运行train.py后读取完配置文件、加载完模型后就不继续运行了，过了一会儿程序就退出了，也没有任何的报错信息，换了2个模型都是这样。这种直接退出的情况一般是什么导致的呢？
这是提示信息：
<img width="684" alt="0b4a2ec64c4243cb7d1eeaafd6ab9b2" src="https://user-images.githubusercontent.com/98868191/220221359-1ecebbe7-5ac2-4237-abbb-5f994da620d0.png">
这是修改后的SFNet对应的配置文件：
<img width="452" alt="6919c0bd54387fa0c348b7a58935d82" src="https://user-images.githubusercontent.com/98868191/220221497-af042b4b-6794-4848-8ad8-bacbaa00c96f.png">

**Comment by censhallwe** [comment]
虽然不知道是怎么回事，但是把batch_size改成2之后就能开始训练了。但是昨天晚上我也试过把batch_size改小，却没有开始训练。感觉一种是很玄的东西。如果有人能解释一下的话就好了，感谢。

**Comment by shiyutang** [comment]
请问下你训练的指令是什么，是否有将输出结果输入到日志中，另外请使用最新版本的paddleseg并确认paddle安装的环境没有问题。

**Comment by censhallwe** [comment]
> 

训练的指令是python .\tools\train.py --config .\configs\_base_\my_video_dataset_sf_18.yml --do_eval --use_vdl --save_interval 500 --save_dir output_1_1.
版本和环境是没有问题的，之前训练MobileNetV2的时候是可行的，现在我把batch_size从4改到2了，也能正常训练。应该是这个batch_size影响了训练的进行，是不是显存的问题？
原本的日志内容如下：
       

meta_data_tag勮槍?R

**Comment by shiyutang** [comment]
请问可以提供显存占用的截图么，一般OOM也是会有报错的，另外其他的资源是否有占用紧张的问题呢？

**Comment by shiyutang** [comment]
根据你说的bs减少后可以训练，说明大概率是显存的问题，如果想增加bs可以尝试多卡，或者使用amp训练，不过amp可能对精度有略微影响。

**Comment by censhallwe** [comment]
显存占用情况如图
![图片](https://user-images.githubusercontent.com/98868191/220267080-76c9126e-5d1f-4f9b-a877-19f6041dbc92.png)
我是本地的笔记本电脑运行的，算力有限，paddleseg是我做的毕设的一个环节，现在能跑起来就满足了。感谢您的解答。

**Comment by shiyutang** [comment]
嗯嗯，好的，看到你的本地算力还是比较有限的，目前在显存超过的边缘了，笔记本的话还是建议主要进行预测推理，训练的话可以使用百度的AIStudio，每天运行项目会有8h的算力卡，对于一些基础的分割任务应该足够的。
https://aistudio.baidu.com/aistudio/projectoverview/public
