### ISSUE TITLE
复现Swin-Unet缺少预训练模型

### ISSUE THREAD

**Issue by Mia01023** [PaddlePaddle/PaddleSeg#2989]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

1. 复现Swin-Unet代码 ，可以正常解压预训练模型压缩包，但加载后出现警告显示缺少部分文件。
2. 可以正常训练，但是初始dice只有11左右，且训练时间很长，约10分钟一个epoch，训练24轮后，dice约为17，一直难以提高。
3. 训练过程cpu占用约30%，但是未使用显存，请问是否正常？

‘’‘python
!export CUDA_VISIBLE_DEVICES=0,1,2,3
!python train.py --config configs/synapse/swinunet_abdomen_224_224_1_14k_5e-2.yml --do_eval --save_interval 1000 --has_dataset_json False --is_save_data False --num_workers 4 --log_iters 10 --use_vdl
’‘’

‘’’
Connecting to https://paddleseg.bj.bcebos.com/paddleseg3d/synapse/abdomen/swinunet_abdomen_224_224_1_14k_5e-2/swinunet_pretrained.zip
Downloading swinunet_pretrained.zip
[==================================================] 100.00%
Uncompress swinunet_pretrained.zip
[==================================================] 100.00%
2023-02-21 10:26:33 [WARNING]	layers_up.0.expand.weight is not in pretrained model
2023-02-21 10:26:33 [WARNING]	layers_up.0.norm.weight is not in pretrained model
2023-02-21 10:26:33 [WARNING]	layers_up.0.norm.bias is not in pretrained model
2023-02-21 10:26:33 [WARNING]	layers_up.1.upsample.expand.weight is not in pretrained model
2023-02-21 10:26:33 [WARNING]	layers_up.1.upsample.norm.weight is not in pretrained model
2023-02-21 10:26:33 [WARNING]	layers_up.1.upsample.norm.bias is not in pretrained model
2023-02-21 10:26:33 [WARNING]	layers_up.2.upsample.expand.weight is not in pretrained model
2023-02-21 10:26:33 [WARNING]	layers_up.2.upsample.norm.weight is not in pretrained model
2023-02-21 10:26:33 [WARNING]	layers_up.2.upsample.norm.bias is not in pretrained model
2023-02-21 10:26:33 [WARNING]	concat_back_dim.1.weight is not in pretrained model
2023-02-21 10:26:33 [WARNING]	concat_back_dim.1.bias is not in pretrained model
2023-02-21 10:26:33 [WARNING]	concat_back_dim.2.weight is not in pretrained model
2023-02-21 10:26:33 [WARNING]	concat_back_dim.2.bias is not in pretrained model
2023-02-21 10:26:33 [WARNING]	concat_back_dim.3.weight is not in pretrained model
2023-02-21 10:26:33 [WARNING]	concat_back_dim.3.bias is not in pretrained model
2023-02-21 10:26:33 [WARNING]	norm.weight is not in pretrained model
2023-02-21 10:26:33 [WARNING]	norm.bias is not in pretrained model
2023-02-21 10:26:33 [WARNING]	norm_up.weight is not in pretrained model
2023-02-21 10:26:33 [WARNING]	norm_up.bias is not in pretrained model
2023-02-21 10:26:33 [WARNING]	up.expand.weight is not in pretrained model
2023-02-21 10:26:33 [WARNING]	up.norm.weight is not in pretrained model
2023-02-21 10:26:33 [WARNING]	up.norm.bias is not in pretrained model
2023-02-21 10:26:33 [WARNING]	output.weight is not in pretrained model
2023-02-21 10:26:33 [INFO]	There are 217/240 variables loaded into SwinUNet.
’‘’

### 复现环境 Environment

platform: Linux-4.15.0-140-generic-x86_64-with-debian-stretch-sid
Python: 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
Paddle compiled with cuda: False
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
PaddlePaddle: 2.4.2

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by shiyutang** [comment]
1. 缺少部分权重应当正常；
2. 这里是说的iters还是epoch？ 总共是14k iters，如果是到24 iter精度不高则不影响，可以继续训练看看。
4. 不应该只使用了cpu，请确认是否安装了paddle-gpu，以及相应的cuda版本等。同时多卡训练请使用：
```
python3 -m paddle.distributed.launch tools/train.py ...
```

**Comment by Mia01023** [comment]
您好，感谢回复！
      训练是到24epoch，训练慢是否是因为数据集是3d的，我再继续训练看看。
      我使用的是平台算力，应该无需安装paddle-gpu而是：
!export CUDA_VISIBLE_DEVICES=0,1,2,3  
对吗


从 Windows 版邮件发送

发件人: shiyutang
发送时间: 2023年2月21日 14:14
收件人: PaddlePaddle/PaddleSeg
抄送: Mia01023; Author
主题: Re: [PaddlePaddle/PaddleSeg] 复现Swin-Unet缺少预训练模型 (Issue #2989)

1. 缺少部分权重应当正常；
2. 这里是说的iters还是epoch？ 总共是14k iters，如果是到24 iter精度不高则不影响，可以继续训练看看。
3. 不应该只使用了cpu，请确认是否安装了paddle-gpu，以及相应的cuda版本等。同时多卡训练请使用：
python3 -m paddle.distributed.launch tools/train.py ...

**Comment by shiyutang** [comment]
如果使用AIStudio，默认应该是enable了gpu的paddle ，以防万一可以进一步打开terminal 进行检查。
```
paddle.is_compiled_with_cuda()
```
另外可以设置
```
paddle.set_device('gpu')
```
从而在GPU上运行程序。如果是使用的paddleseg这个开关应该默认是打开的。
另外训练时间可以看看下面swinunet的log，如果都是V100训练，那么训练时间应该差异很小。
https://paddleseg.bj.bcebos.com/paddleseg3d/synapse/abdomen/swinunet_abdomen_224_224_1_14k_5e-2/train.log

**Comment by Mia01023** [comment]
您好，在terminal进行查看发现确实并未使用gpu，且不可以通过paddle.set_device('gpu') 设置，报错 ValueError: The device should not be 'gpu', since PaddlePaddle is not compiled with CUDA。
我是在AI studio平台且在PaddleSeg下进行的，请问我是否需要额外下载cuda相关的文件解决报错？


从 Windows 版邮件发送

发件人: shiyutang
发送时间: 2023年2月22日 9:59
收件人: PaddlePaddle/PaddleSeg
抄送: Mia01023; Author
主题: Re: [PaddlePaddle/PaddleSeg] 复现Swin-Unet缺少预训练模型 (Issue #2989)

如果使用AIStudio，默认应该是enable了gpu的paddle ，以防万一可以进一步打开terminal 进行检查。
paddle.is_compiled_with_cuda()

另外可以设置 paddle.set_device(‘gpu’)从而在GPU上运行程序。如果是使用的paddleseg这个开关应该默认是打开的。
另外训练时间可以看看下面swinunet的log，如果都是V100训练，那么训练时间应该差异很小。
https://paddleseg.bj.bcebos.com/paddleseg3d/synapse/abdomen/swinunet_abdomen_224_224_1_14k_5e-2/train.log

**Comment by Harryoung** [comment]
请确认在AI Studio启动的是GPU环境，而不是基础的CPU环境

**Comment by Mia01023** [comment]
确认使用的是GPU环境—V100，32GB。
且尝试更换其他GPU（V100，16GB;V100四卡）均显示Paddle compiled with cuda:False
图为使用V100四卡的报错信息

从 Windows 版邮件发送

发件人: You Jiangbin
发送时间: 2023年2月23日 8:33
收件人: PaddlePaddle/PaddleSeg
抄送: Mia01023; Author
主题: Re: [PaddlePaddle/PaddleSeg] 复现Swin-Unet缺少预训练模型 (Issue #2989)

请确认在AI Studio启动的是GPU环境，而不是基础的CPU环境

**Comment by Mia01023** [comment]
您好，在terminal查看发现有gpu，但是代码运行过程中未使用gpu；具体信息如下：



我所使用的环境为V100，32GB
从 Windows 版邮件发送

发件人: You Jiangbin
发送时间: 2023年2月23日 8:33
收件人: PaddlePaddle/PaddleSeg
抄送: Mia01023; Author
主题: Re: [PaddlePaddle/PaddleSeg] 复现Swin-Unet缺少预训练模型 (Issue #2989)

请确认在AI Studio启动的是GPU环境，而不是基础的CPU环境

**Comment by shiyutang** [comment]
你好，你的邮件发布的信息不能呈现图片，建议直接在本条issue下回复：https://github.com/PaddlePaddle/PaddleSeg/issues/2989

同时你的信息显示你的环境中并没有安装paddle-gpu，因此不能开始GPU训练，如果确认选择了GPU环境，建议在AIStudio提交问题反馈：
<img width="335" alt="image" src="https://user-images.githubusercontent.com/34859558/220806141-2529f7d1-a744-4696-a08b-9548796950d1.png">

**Comment by Mia01023** [comment]
您好，
1. 环境中已经确认安装gpu，信息如下：
‘’‘
!pip install paddlepaddle-gpu 
’‘’
‘’‘
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: paddlepaddle-gpu in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (2.3.2.post112)
Requirement already satisfied: protobuf<=3.20.0,>=3.1.0 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from paddlepaddle-gpu) (3.20.0)
Requirement already satisfied: Pillow in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from paddlepaddle-gpu) (8.2.0)
Requirement already satisfied: decorator in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from paddlepaddle-gpu) (4.4.2)
Requirement already satisfied: paddle-bfloat==0.1.7 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from paddlepaddle-gpu) (0.1.7)
Requirement already satisfied: six in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from paddlepaddle-gpu) (1.16.0)
Requirement already satisfied: opt-einsum==3.3.0 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from paddlepaddle-gpu) (3.3.0)
Requirement already satisfied: requests>=2.20.0 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from paddlepaddle-gpu) (2.24.0)
Requirement already satisfied: numpy>=1.13 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from paddlepaddle-gpu) (1.21.5)
Requirement already satisfied: astor in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from paddlepaddle-gpu) (0.8.1)
Requirement already satisfied: idna<3,>=2.5 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from requests>=2.20.0->paddlepaddle-gpu) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from requests>=2.20.0->paddlepaddle-gpu) (2019.9.11)
Requirement already satisfied: chardet<4,>=3.0.2 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from requests>=2.20.0->paddlepaddle-gpu) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from requests>=2.20.0->paddlepaddle-gpu) (1.25.6)
‘’‘
2.  在terminal中检查确认有gpu,信息如下：
 aistudio@jupyter-3122403-5466078:~$ python
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.is_compiled_with_cuda()
True
>>> paddle.set_device('gpu')
Place(gpu:0)
3. 实际训练过程并未使用gpu，信息如下：
‘’‘
!export CUDA_VISIBLE_DEVICES=0
!python train.py --config configs/synapse/swinunet_abdomen_224_224_1_14k_5e-2.yml --do_eval --save_interval 1000 --has_dataset_json False --is_save_data False --num_workers 4 --log_iters 10 --use_vdl
’‘’
‘’‘
2023-02-23 09:45:17 [INFO]	
------------Environment Information-------------
platform: Linux-4.15.0-140-generic-x86_64-with-debian-stretch-sid
Python: 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
Paddle compiled with cuda: False
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
PaddlePaddle: 2.4.2
’‘’

**Comment by shiyutang** [comment]
> 3\. Paddle compiled with cuda: False

你好，可以看到实际运行的环境中时没有安装paddle-gpu的，这个属于AIStudio的环境问题，建议在AiStudio中提交问题反馈

**Comment by Mia01023** [comment]
好的，我已提交问题反馈，感谢回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月23日(星期四) 中午11:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] 复现Swin-Unet缺少预训练模型 (Issue #2989)





  
3. Paddle compiled with cuda: False
  
你好，可以看到实际运行的环境中时没有安装paddle-gpu的，这个属于AIStudio的环境问题，建议在AiStudio中提交问题反馈
