### ISSUE TITLE
u-net支持修改Backbone为ResNet50么

### ISSUE THREAD

**Issue by niuyuanye** [PaddlePaddle/PaddleSeg#299]

**Comment by wangchaochaohu** [comment]
不支持配置自动修改  需要手动修改代码

**Comment by niuyuanye** [comment]
那除了看u-net部分的代码外有可以参考的东西么？

**Comment by nepeplwu** [comment]
@niuyuanye 你是想提升unet模型的精度吗？如果是的话，建议使用deeplabv3+这个模型，可以选择xception或者mobilenet两种backbone
