### ISSUE TITLE
如何合并两个数据集的json文件

### ISSUE THREAD

**Issue by xxPete** [PaddlePaddle/PaddleSeg#2990]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

有没有脚本实现两个标注的coco格式的文件的合并，想把两个数据集混合在一起训练。自己写的脚本不知道为什么，标注位置对不上

**Comment by Sunting78** [comment]
没有，网上可以搜索下应该有很多，合并的时候注意一下image id和annotations中的image id的对应，两个数据集合并时，也要注意让id不要重复了。

**Comment by Harryoung** [comment]
可以看看这里最下面的json文件合并脚本是否满足需求
https://github.com/PaddlePaddle/PaddleRS/blob/develop/docs/data/coco_tools.md
