### ISSUE TITLE
PP-LiteSeg实现和论文有些不一致

### ISSUE THREAD

**Issue by l494342511** [PaddlePaddle/PaddleSeg#2991]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

论文中FLD有两个UAFM进行特征融合，但是在代码中有三个，其中一个是对SPPM的输出和输入做融合

**Comment by juncaipeng** [comment]
感谢提出。实际实现是三个uafm模块，论文中呈现的数据也是使用三个uafm模块的模型。  我们会尽快更新一版模型结构的图片。
