### ISSUE TITLE
Matting export seems to ignore input size for PP-HumanMatting

### ISSUE THREAD

**Issue by ukoehler** [PaddlePaddle/PaddleSeg#2992]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

I successfully managed to run a converted (to ONNX) version of Matting PP_MattingV2-512 in OpenCV.

However, when trying to export based on the contents of this file: https://paddleseg.bj.bcebos.com/matting/models/deploy/pp-humanmatting-resnet34_vd.zip I get an error for paddle2onnx that only fixed size input is supported.

I followed you instructions here https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/Matting/docs/full_develop_en.md#Export-and-Deployment for exporting the model with this command:
```
(.venv) D:\Local\devel\Python\PaddleSeg_2.7.0\Matting>python tools/export.py --c
onfig configs/human_matting/human_matting-resnet34_vd.yml --model_path pretraine
d_models/human_matting-resnet34_vd.pdparams --save_dir pretrained_models/human_m
atting-resnet34_vd --input_shape 1 3 2048 2048
D:\Local\devel\Python\PaddleSeg_2.7.0\Matting\tools\..\ppmatting\metrics\metric.
py:23: DeprecationWarning: Please use `convolve` from the `scipy.ndimage` namesp
ace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import convolve
2023-02-21 14:10:49 [INFO]      Loading pretrained model from https://paddleseg.
bj.bcebos.com/matting/models/ResNet34_vd_pretrained/model.pdparams
2023-02-21 14:10:50 [INFO]      There are 195/195 variables loaded into ResNet_v
d.
2023-02-21 14:10:55 [INFO]      Loaded trained params of model successfully.
<frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method
is deprecated and slated for removal in Python 3.12; use exec_module() instead
2023-02-21 14:11:09 [INFO]      Model is saved in pretrained_models/human_mattin
g-resnet34_vd.
```
However, paddle2ONNX export is still not possible:
```
(.venv) D:\Local\devel\Python\PaddleSeg_2.7.0>paddle2onnx --model_dir Matting\pr
etrained_models\pp-humanmatting-resnet34_vd --model_filename model.pdmodel --par
ams_filename model.pdiparams --opset_version 11 --save_file Matting\pretrained_m
odels\pp-humanmatting-resnet34_vd\pp-humanmatting-resnet34_vd.onnx
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: Matting\pretrained_models\pp-humanmatting-resnet3
4_vd\model.pdmodel
[Paddle2ONNX] Paramters file path: Matting\pretrained_models\pp-humanmatting-res
net34_vd\model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[ERROR][Paddle2ONNX] [pool2d: pool2d_5.tmp_0] Adaptive only support static input
 shape.
[Paddle2ONNX] Due to the operator: pool2d, this model cannot be exported to ONNX
.
[ERROR][Paddle2ONNX] [pool2d: pool2d_6.tmp_0] Adaptive only support static input
 shape.
[Paddle2ONNX] Due to the operator: pool2d, this model cannot be exported to ONNX
.
[ERROR] Model exporting failed, you can report this problem to https://github.co
m/PaddlePaddle/Paddle2ONNX.git.
```

### 复现环境 Environment

Windows 10
Python 3.10.4
paddle-bfloat 0.1.7
paddle2onnx 1.0.5
paddlefsl 1.1.0
paddlehub 2.3.1
paddlenlp 2.4.9
paddlepaddle 2.4.1
paddleseg 2.7.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
