### ISSUE TITLE
将训练的模型转化为nb文件部署在Android端，出现多个分割区域

### ISSUE THREAD

**Issue by wliang410** [PaddlePaddle/PaddleSeg#2993]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

将训练的模型转化为nb文件部署在Android端，出现多个分割区域：
![image](https://user-images.githubusercontent.com/27349969/220548566-cc9f4d3c-3667-4c5b-8f9f-93459eee7fa0.png)

Visualize中的output值出现以下情况：
![image](https://user-images.githubusercontent.com/27349969/220548943-21d16e56-7882-48cf-925d-64fafc355ce8.png)

**Comment by juncaipeng** [comment]
从你给出的图像来看，分割出来了两个人影，模型应该没问题，但是Android中的逻辑代码应该不对，可以检查一下。
