### ISSUE TITLE
交互式视频分割，分辨率降低

### ISSUE THREAD

**Issue by guchuntao** [PaddlePaddle/PaddleSeg#2997]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在交互式视频分割中，我的原视频分辨率为：1920*1080，在EISeg中打开后，分辨率降低，得到的mask的分辨率也对应降低，有办法提高吗？

**Comment by Bobholamovic** [comment]
你好，可以尝试修改这里：

https://github.com/PaddlePaddle/PaddleSeg/blob/13aac35b31b147d2dd9976821ade13dabebff685/EISeg/eiseg/plugin/video/inference_core.py#L81

传入 `min_side` 参数，指定其值为1080。请确保以下两项要求能够得到满足：

1. 修改源码能够直接影响到已经安装的 EISeg（例如，EISeg 采用[『克隆到本地』方式](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/EISeg/docs/install.md#%E5%85%8B%E9%9A%86%E5%88%B0%E6%9C%AC%E5%9C%B0)安装）。
2. 系统具有足够的资源支撑高分辨率视频的渲染。
