### ISSUE TITLE
试了一下MedicalSeg有些问题  不会生成训练模型

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleSeg#2999]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

试了一下MedicalSeg有些问题  不会生成训练模型

-----------

可以在这里进行测试：
https://aistudio.baidu.com/aistudio/projectdetail/5555476?sUid=3341709&shared=1&ts=1677133446565

安装
cd contrib/MedicalSeg/
pip install -r requirements.txt 
pip install medpy

然后训练如下：
python train.py --config configs/lung_coronavirus/vnet_lung_coronavirus_128_128_128_15k_wll.yml --save_dir saved_model/vnet_lung_coronavirus_128_128_128_15k --save_interval 500 --log_iters 100 --num_workers 0 --do_eval --use_vdl --keep_checkpoint_max 5 --seed 0  #运行后不会生成训练模型

![图片](https://user-images.githubusercontent.com/6648329/221066493-aa8a882a-415b-4406-bbcf-640d2269f8ec.png)

![图片](https://user-images.githubusercontent.com/6648329/221066469-faa54740-25c9-4cd6-b0a4-7c036cf31d97.png)

### 复现环境 Environment

可以在这里进行测试：
https://aistudio.baidu.com/aistudio/projectdetail/5555476?sUid=3341709&shared=1&ts=1677133446565

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by shiyutang** [comment]
根据截图，你的训练已经开始，但是突然中断，怀疑是因为显存等资源不够导致训练退出。同时使用你的AIStudio环境会出现如下报错：
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/34859558/221108438-a4308aa2-cda6-49c9-92b8-3bd0ad4bd295.png">

建议在AIStudio上使用最新的PaddleSeg-develop重新处理数据后进行训练验证。

**Comment by gg22mm** [comment]
> 根据截图，你的训练已经开始，但是突然中断，怀疑是因为显存等资源不够导致训练退出。同时使用你的AIStudio环境会出现如下报错： <img alt="image" width="1327" src="https://user-images.githubusercontent.com/34859558/221108438-a4308aa2-cda6-49c9-92b8-3bd0ad4bd295.png">
> 
> 建议在AIStudio上使用最新的PaddleSeg-develop重新处理数据后进行训练验证。

看你运行找不到： case009.npy，把coronacases_case009.npy  改成： case009.npy 即可。  我上传的时候忘了改了。  改完就不报错了。~~， 改完就可以测试了，就跟我上面提到的一样的问题，这个问题。我把它提在这里，如果以后有机会去医院上班才用到，不急，慢慢看

**Comment by shiyutang** [comment]
这里数据名称是不需要修改的。因此建议重新拉取paddleseg-develop代码，并重新处理数据后查看是否会出现相同问题。

**Comment by gg22mm** [comment]
> 并重新处理数据后查看是否会出现相同问题

我用的就是最新代码~~

**Comment by shiyutang** [comment]
那为什么需要修改数据呢？
