### ISSUE TITLE
目前paddleseg支持pp-liteseg网络转为onnx模型吗？

### ISSUE THREAD

**Issue by EudicL** [PaddlePaddle/PaddleSeg#3000]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包含open与closed)，没有类似需求。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar feature requests.

### 需求描述 Feature Description

最近有个项目需求，用到了pp-liteseg,后来发现无法转为onnx

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by juncaipeng** [comment]
https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.7/configs/pp_liteseg
```
Sometimes, the adaptive average pooling op can not be converted to ONNX. To solve the problem, you can adjust the input shape of the model as a multiple of 128.
```
上述页面介绍了如何转成onnx模型。

**Comment by EudicL** [comment]
请问paddle转为onnx时，输入输出的名字怎么指定？

**Comment by Harryoung** [comment]
> 请问paddle转为onnx时，输入输出的名字怎么指定？

请查看上方评论链接中的infer_onnx_trt.py脚本，可根据需要自行二次开发

**Comment by EudicL** [comment]
> > 请问paddle转为onnx时，输入输出的名字怎么指定？
> 
> 请查看上方评论链接中的infer_onnx_trt.py脚本，可根据需要自行二次开发

infer_onnx_trt.py我没有用到这个文件，直接是paddle2onnx转出的

**Comment by juncaipeng** [comment]
> 请问paddle转为onnx时，输入输出的名字怎么指定？

这个问题可以查看paddle2onnx的文档 https://github.com/PaddlePaddle/Paddle2ONNX

**Comment by shiyutang** [comment]
这个问题已经长期没有回复，暂时关闭，如有需要可以回复issue，或者再次打开。
