### ISSUE TITLE
找不到baseline1中medicalseg下的data文件夹

### ISSUE THREAD

**Issue by sunxuelan** [PaddlePaddle/PaddleSeg#3004]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在执行baseline1时找不到baseline1中medicalseg下的data文件夹

**Comment by shiyutang** [comment]
你好，数据通过数据集方式加载，应该可以在data目录下找到，如果找不到，请重启项目，重启项目还不行可以取消挂载数据并重新挂载相同数据。
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/34859558/221510643-f54ce64e-c4ae-4f05-9721-49f73dfb6c46.png">
