### ISSUE TITLE
mobileseg_shufflenetv2没有办法导出onnx，这个是有问题的

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/PaddleSeg#3009]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Exception: Error happened when mapping node ['pool2d_2'] to onnx, which op_type is 'pool2d' with inputs: {'X': ['reshape2_31.tmp_0']} and outputs: {'Out': ['pool2d_2.tmp_0']}, specific error: Converting this model to ONNX need with static input shape, please fix input shape of this model, see doc Q2 in https://github.com/PaddlePaddle/paddle2onnx/blob/develop/docs/en/FAQ.md.

**Comment by Sunting78** [comment]
没有复现你的Error，我尝试导出后的输出Error是：
[ERROR][Paddle2ONNX] [pool2d: pool2d_2.tmp_0] Adaptive only support static input shape.
根据这里的提示，pool2d是一个AdaptivePooling , 而ONNX无此对应OP，因此需要固定原模型的输入shape, 在部分情况下，可以将AdaptivePooling转为普通Pool2d进行导出。

**Comment by chen-del** [comment]
好的，我再进行尝试

**Comment by chen-del** [comment]
可能是配置文件出现了问题

**Comment by chen-del** [comment]
@Sunting78 ，当我重新使用的时候还是出现了同样的问题，有个结构没有办法推断，这个似乎是export出现了问题。报错如下：W0320 11:45:08.702668  7724 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.1
W0320 11:45:08.707962  7724 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
2023-03-20 11:45:09 [INFO]      Loading pretrained model from https://paddleseg.bj.bcebos.com/dygraph/backbone/shufflenetv2_x1_0.zip
2023-03-20 11:45:09 [INFO]      There are 275/275 variables loaded into ShuffleNet.
2023-03-20 11:45:09 [INFO]      Loaded trained params of model successfully.
/home/dell/anaconda3/envs/mmp/lib/python3.8/site-packages/paddle/fluid/layers/math_op_patch.py:336: UserWarning: /tmp/tmpjadmhf6z.py:26
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  warnings.warn(
/home/dell/anaconda3/envs/mmp/lib/python3.8/site-packages/paddle/fluid/layers/math_op_patch.py:336: UserWarning: /tmp/tmprman9_1t.py:7
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  warnings.warn(
/home/dell/anaconda3/envs/mmp/lib/python3.8/site-packages/paddle/fluid/layers/math_op_patch.py:336: UserWarning: /tmp/tmp_5g4f9ph.py:7
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  warnings.warn(
/home/dell/anaconda3/envs/mmp/lib/python3.8/site-packages/paddle/fluid/layers/math_op_patch.py:336: UserWarning: /tmp/tmp2m5hra3u.py:7
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  warnings.warn(
2023-03-20 11:45:13 [INFO]      Model is saved in output/shufflenetv2_256x256_80k/best_model/.
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: output/shufflenetv2_256x256_80k/best_model/model.pdmodel
[Paddle2ONNX] Paramters file path: output/shufflenetv2_256x256_80k/best_model/model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[ERROR][Paddle2ONNX] [pool2d: pool2d_2.tmp_0] Adaptive only support static input shape.
[Paddle2ONNX] Due to the operator: pool2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [pool2d: pool2d_3.tmp_0] Adaptive only support static input shape.
[Paddle2ONNX] Due to the operator: pool2d, this model cannot be exported to ONNX.
[ERROR] Model exporting failed, you can report this problem to https://github.com/PaddlePaddle/Paddle2ONNX.git.
predict.sh: 行 37:  7918 已放弃               (核心已转储) paddle2onnx --model_dir output/shufflenetv2_256x256_80k/best_model/ --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 13 --save_file output/shufflenetv2_256x256_80k/best_model/model.onnx

**Comment by chen-del** [comment]
我将input_shape输入大小已经固定到了320，320的输入大小，但是它还是没有办法推理出来结构这个是存在问题的

**Comment by HonglinChu** [comment]
> 没有复现你的Error，我尝试导出后的输出Error是： [ERROR][Paddle2ONNX] [pool2d: pool2d_2.tmp_0] Adaptive only support static input shape. 根据这里的提示，pool2d是一个AdaptivePooling , 而ONNX无此对应OP，因此需要固定原模型的输入shape, 在部分情况下，可以将AdaptivePooling转为普通Pool2d进行导出。

输入的特征图都是一样的大小，如果固定输入为1，3，192，192，那么AdaptivePooling对应的输入B，C，6，6； MobileSeg的backbone 为MobileMetV2或者V3 的时候都可以正常转onnx， 为什么替换为ShuffleNetV2就会报这个错误呢

**Comment by HonglinChu** [comment]
> > 没有复现你的Error，我尝试导出后的输出Error是： [ERROR][Paddle2ONNX] [pool2d: pool2d_2.tmp_0] Adaptive only support static input shape. 根据这里的提示，pool2d是一个AdaptivePooling , 而ONNX无此对应OP，因此需要固定原模型的输入shape, 在部分情况下，可以将AdaptivePooling转为普通Pool2d进行导出。
> 
> 输入的特征图都是一样的大小，如果固定输入为1，3，192，192，那么AdaptivePooling对应的输入B，C，6，6； MobileSeg的backbone 为MobileMetV2或者V3 的时候都可以正常转onnx， 为什么替换为ShuffleNetV2就会报这个错误呢

另外补充一点，AdaptivePooling是存在于MobileSeg的head部分，和backbone没关系才对，但是换了backbone，输入特征不变就会报错

**Comment by HonglinChu** [comment]
这是报错信息
`[ERROR][Paddle2ONNX] [pool2d: pool2d_1.tmp_0] Adaptive only support static input shape.
[Paddle2ONNX] Due to the operator: pool2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [pool2d: pool2d_2.tmp_0] Adaptive only support static input shape.
[Paddle2ONNX] Due to the operator: pool2d, this model cannot be exported to ONNX.`

**Comment by HonglinChu** [comment]
@chen-del 你的这个报错解决了么

**Comment by chen-del** [comment]
@HonglinChu ，没有，我是使用的原始配置文件去导出发现也是失败的，不知道怎么回事

**Comment by chen-del** [comment]
[PaddleSeg](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.8)/[configs](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.8/configs)/[mobileseg](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.8/configs/mobileseg)
/mobileseg_shufflenetv2_cityscapes_1024x512_80k.yml，我用这个还是一样的结果，静态图里面推不出来，没办法导出，但是paddle是可以进行预测，很奇怪其他模型都是可以导出的

**Comment by JBYan** [comment]
> 

我遇到了和你相同的问题，请问你的问题解决了吗？

**Comment by HonglinChu** [comment]
> [PaddleSeg](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.8)/[configs](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.8/configs)/[mobileseg](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.8/configs/mobileseg) /mobileseg_shufflenetv2_cityscapes_1024x512_80k.yml，我用这个还是一样的结果，静态图里面推不出来，没办法导出，但是paddle是可以进行预测，很奇怪其他模型都是可以导出的

我是在这里改的，把backbone换成了shufflenetv2，导出onnx失败了https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/contrib/PP-HumanSeg/configs/portrait_pp_humansegv2_lite.yml
查看了报错是出现在MobileSeg的自适应pool部分（MobileNetV2和V3都没有这种问题），和shufflenet里面的最大池化没有关系。报错了地方在mobileseg.py文件的第253行  https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/paddleseg/models/mobileseg.py

**Comment by chen-del** [comment]
非常感谢@HonglinChu，我想起来了是自适应的平均池化推断失败，这个好像是有办法可以解决，需要将里面函数，用公式实现一遍，重新训练一遍应该就可以推出来，我之前改过，不过是torch的。
