### ISSUE TITLE
训练指令报错

### ISSUE THREAD

**Issue by liuyantong123** [PaddlePaddle/PaddleSeg#3012]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在本案例中，基于上述大规模数据预训练的模型，在抽取的部分[supervise.ly](https://supervise.ly/)数据集上进行Fine-tuning。为了方便大家快速体验人像分割模型的效果，本教程选取了较为轻量的HRNet w18 small v1模型进行实验，训练命令如下：
export CUDA_VISIBLE_DEVICES=0 # 设置1张可用的卡
# windows下请执行以下命令
# set CUDA_VISIBLE_DEVICES=0
python train.py \
--config configs/fcn_hrnetw18_small_v1_humanseg_192x192_mini_supervisely.yml \
--save_dir saved_model/fcn_hrnetw18_small_v1_humanseg_192x192_mini_supervisely \
--save_interval 100 --do_eval --use_vdl
报错FileNotFoundError: there is not `dataset_root`: test_tipc/data/mini_supervisely.
该路径下有mini_supervisely

**Comment by shiyutang** [comment]
你好，看到你使用的是paddleseg2.5版本的HumanSeg的训练微调指令，建议使用最新的2.7版本教程：https://github.com/PaddlePaddle/PaddleSeg/blob/develop/contrib/PP-HumanSeg/README_cn.md
