### ISSUE TITLE
eiseg:无法使用自己训练的模型进行标注

### ISSUE THREAD

**Issue by Li-Ruiqi777** [PaddlePaddle/PaddleSeg#3014]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

当eiseg的模型选择了自己训练的模型后，一点击图片就会卡主，并有如下报错
Traceback (most recent call last):
File "E:\anaconda3\envs\dl_paddle\Lib\site-packages\eiseg\app.py", line 2060, in canvasClick
self.controller.addClick(x, y, isLeft)
File "E:\anaconda3\envs\dl_paddle\Lib\site-packages\eiseg\controller.py", line 215, in addClick
pred = self.predictor.get_prediction(self.clicker)
File "E:\anaconda3\envs\dl_paddle\Lib\site-packages\eiseg\inference\predictor\base.py", line 97, in get_prediction
pred_logits, pred_edges = self._get_prediction(image_nd, clicks_lists,
File "E:\anaconda3\envs\dl_paddle\Lib\site-packages\eiseg\inference\predictor\base.py", line 147, in _get_prediction
self.input_handle_2 = self.net.get_input_handle(input_names[1])
IndexError: list index out of range

**Comment by Bobholamovic** [comment]
你好，看起来是自训练模型的接口不符合EISeg标准，EISeg交互式模型在前向推理时必须接受2个输入。

**Comment by xiao-keeplearning** [comment]
你好，请问这个使用自训练模型自动化标注有官方教程吗？

**Comment by Bobholamovic** [comment]
我们暂时没有提供训练交互式分割模型的教程。如果对交互式分割模型感兴趣的话，可以尝试阅读并复现参考文献：

https://arxiv.org/abs/2102.06583
https://arxiv.org/abs/2103.07941

**Comment by monkeycc** [comment]
不会增加自训练模型自动标注

要是增加了
飞桨 EasyDL
飞桨 BML 全功能AI开发平台
怎么还能卖得动 ？

**Comment by LGW2LLP** [comment]
你好，自己训练的模型是单个输个，有方法改成两个输入？另外，第二个输入是掩膜图？

**Comment by monkeycc** [comment]
https://github.com/wkentaro/labelme
https://github.com/vietanhdev/anylabeling

都可以实现EISeg的框架效果
而且能自定义模型

@LGW2LLP  @Bobholamovic

**Comment by LGW2LLP** [comment]
@monkeycc 谢谢提供方法 labelme使用过，没有交互式的方便。现在去了解一下anylabeling，看能够使用自己的模型

**Comment by monkeycc** [comment]
labelme 新版本 支持SAM分割标注了 
建议用最新版本

labelme 
可以看这里 模型都下载好了
https://gitee.com/monkeycc/anylabeling/releases/tag/v0.2.24


anylabeling
可以看这里 模型都下载好了
https://gitee.com/monkeycc/anylabeling/releases/tag/v0.2.24

@LGW2LLP
