### ISSUE TITLE
PaddleSeg develop分支  nnUNet问题

### ISSUE THREAD

**Issue by huangguoqing** [PaddlePaddle/PaddleSeg#3015]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问paddleseg medcialseg 下的nnUNet是否在运行的时候是只支持Linux平台，windows不行,数据预处理部分问题？

Error code :

F:\Medical\PaddleSeg\contrib\MedicalSeg>python train.py --config configs/nnunet/msd_lung/nnunet_2d_msd_lung_fold0.yml --log_iters 20 --precision fp16 --nnunet --save_dir output/2d_unet/fold0 --save_interval 1000 --use_vdl
信息: 用提供的模式无法找到文件。
'C:/Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
2023-03-02 11:00:39 [INFO]
------------Environment Information-------------
platform: Windows-10-10.0.19041-SP0
Python: 3.7.16 (default, Jan 17 2023, 16:06:28) [MSC v.1916 64 bit (AMD64)]
Paddle compiled with cuda: True
NVCC: Not Available
cudnn: 8.4
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: NVIDIA GeForce']
GCC: gcc (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 8.1.0
PaddlePaddle: 2.4.2
------------------------------------------------
F:\Medical\PaddleSeg\contrib\MedicalSeg\medicalseg\cvlibs\config.py:451: UserWarning: Warning: The data dir now is F:\Medical\PaddleSeg\contrib\MedicalSeg\data/, you should change the data_root in the global.yml if this directory didn't have enough space
  .format(absolute_data_dir))
msd_lung/Task006_Lung not found, convert data to decathlon.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\anaconda\envs\MedicalSeg\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "D:\anaconda\envs\MedicalSeg\lib\multiprocessing\pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "F:\Medical\PaddleSeg\contrib\MedicalSeg\tools\preprocess_utils\convert_to_decathlon.py", line 95, in split_4d_nifti
    os.path.join(output_folder, file_base[:-7] + "_0000.nii.gz"))
  File "D:\anaconda\envs\MedicalSeg\lib\shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "D:\anaconda\envs\MedicalSeg\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'msd_lung/Task006_Lung\\imagesTr\\Task06_Lung\\imagesTr\\lung_029_0000.nii.gz'

**Comment by Bobholamovic** [comment]
你好，请确认路径`'msd_lung/Task006_Lung\imagesTr\Task06_Lung\imagesTr\lung_029_0000.nii.gz'`是否存在文件。

**Comment by huangguoqing** [comment]
我在官网的AIstudio 上linux平台测试是可以的，lung_029_0000.nii.gz这个文件是数据预处理时候拷贝生成的，我的执行步骤和AIstudio中一样，区别就是我是windows平台

**Comment by huangguoqing** [comment]
代码中msd_lung/Task006_Lung not found, convert data to decathlon.     convert data to decathlon这个函数是生成Task006_Lung文件夹和里面的数据

**Comment by huangguoqing** [comment]
我发现了问题，需要修改源码，split('/')需要改成split('\\')，现在还是linux的写法，windows可能识别有问题，你们可以看看更新一下bug

**Comment by Bobholamovic** [comment]
> 我发现了问题，需要修改源码，split('/')需要改成split('\')，现在还是linux的写法，windows可能识别有问题，你们可以看看更新一下bug

感谢反馈，我们将修复此bug。

**Comment by Bobholamovic** [comment]
此bug已修复~
