### ISSUE TITLE
RTformer.py文件

### ISSUE THREAD

**Issue by Youskrpig** [PaddlePaddle/PaddleSeg#3017]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

第276行建议把+=拆开写，否则在loss反传时容易报inplace operation

### 复现环境 Environment

我是把rtformer改成了torch的形式，然后loss反传报的inplace operation，通过torch.autograd.detct_anomaly定位问题在+=这块。

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Bobholamovic** [comment]
你好，感谢你的建议，但我们在实验过程中并未观察到因为in-place操作导致的梯度异常。PaddlePaddle与PyTorch是两个不同的深度学习框架，在这一场景下，PaddlePaddle对in-place操作的优化也许更优秀，而使用in-place操作有助于在运行期提高性能，因此我们认为这应该不属于bug范畴。

**Comment by Youskrpig** [comment]
好的了解，感谢回复。
