### ISSUE TITLE
窗宽、窗位功能无效

### ISSUE THREAD

**Issue by zhunv** [PaddlePaddle/PaddleSeg#3019]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

打开tiff格式的图像时，窗框窗位调整功能无效，

### 复现环境 Environment

- OS：Linux
- PaddlePaddle：2.3.2
- PaddleSeg：2.6.0
- Python：3.8.13

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by shiyutang** [comment]
请问是使用EISeg时遇到的问题么？

**Comment by zhunv** [comment]
是的，为啥打开tiff格式的文件就不支持窗宽窗位调整呢？

**Comment by linhandev** [comment]
您好，请问tiff格式的是什么数据呢？类似CT，MR的扫描嘛 @zhunv

**Comment by zhunv** [comment]
对的，类似于医疗上拍摄的X射线图像。

**Comment by linhandev** [comment]
我们在研究怎么实现比较合适，话说你的图像是拍完之后经过处理吗，是dcm之类的常用格式转成了tiff还是拍出来就是tiff呢 @zhunv

**Comment by zhunv** [comment]
是拍出来就是Tiff格式的哈，是一种X射线成像的格式
