### ISSUE TITLE
MultiClassFocalLoss 里面是不是存在问题？

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/PaddleSeg#3022]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我看到里面给到了num_class但是实际上这个参数并没有用到计算
![f72c50c49e089d8c5fd784050dc802a](https://user-images.githubusercontent.com/58769772/222612286-0698cf3f-339f-40b5-a131-8597e305aac5.png)
![951e02a1c0c58c863bc02d8516c9d77](https://user-images.githubusercontent.com/58769772/222612298-d98c4976-ac16-4a91-b5a6-e01ddaf282cb.png)
是不是那里隐式调用了，谢谢

**Comment by juncaipeng** [comment]
这个没有隐式调用，开发同学添加了这个无用参数。

**Comment by chen-del** [comment]
@juncaipeng ，这个参数什么时候可以实际用上呢，这个类别权重参数

**Comment by shiyutang** [comment]
GoodFirstIssue： remove unused params

**Comment by shiyutang** [comment]
fixed in #3451
