### ISSUE TITLE
optimizer:里面的_inherited_: False会报异常

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/PaddleSeg#3025]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

很多配置里面的
```
optimizer:
  _inherited_: False
  type: AdamW
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.01
```

一旦运行就报异常
```
2023-03-04 12:35:34 [INFO]	There are 1052/1052 variables loaded into MixVisionTransformer.
Traceback (most recent call last):
  File "/home/aistudio/PaddleSeg-release-2.7/train.py", line 262, in <module>
    main(args)
  File "/home/aistudio/PaddleSeg-release-2.7/train.py", line 239, in main
    optimizer=cfg.optimizer,
  File "/home/aistudio/PaddleSeg-release-2.7/paddleseg/cvlibs/config.py", line 287, in optimizer
    **args)
TypeError: __init__() got an unexpected keyword argument '_inherited_'
```

是不是要统一清理一下？

### 复现环境 Environment

aistudio paddle2.4

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by zhaoyantao-murray** [comment]
请问你那边遇到的是哪几个模型的哪些yml文件会出现这个问题呢

**Comment by zhaoyantao-murray** [comment]
我刚刚测了一下segformer_b0这个yml文件的训练是没有问题的

**Comment by zouhan6806504** [comment]
> 请问你那边遇到的是哪几个模型的哪些yml文件会出现这个问题呢

 我就试了MixVisionTransformer_B5，换成你所说的b0也会出现问题，配置文件如下
[base.zip](https://github.com/PaddlePaddle/PaddleSeg/files/10906124/base.zip)

启动命令
```
!python /home/aistudio/PaddleSeg-release-2.7/train.py --config  /home/aistudio/base.yml \
--do_eval \
--use_vdl \
--save_interval 1000 \
--save_dir /home/aistudio/output \
--log_iters 20 
```

**Comment by zouhan6806504** [comment]
是不是没有开头的_base_，如果含有_inherited_就会异常？

**Comment by zhaoyantao-murray** [comment]
> 

是的，最前面的_base_是要有的
