### ISSUE TITLE
为什么git clone后，在/paddleseg/matting/tools下面没有bg_replace_video.py文件，而网站相关文件夹中有该命令，拷贝过来后执行报错？

### ISSUE THREAD

**Issue by zhouqm2008** [PaddlePaddle/PaddleSeg#3028]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

为什么在/paddleseg/matting/tools下面没有bg_replace_video.py文件，而网站相关文件夹中有该命令，拷贝过来后执行报错？

### 复现环境 Environment

CUDA:11.7
Python:3.8.16

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by zhouqm2008** [comment]
为什么git clone后，在/paddleseg/matting/tools下面没有bg_replace_video.py文件，而网站相关文件夹中有该命令，拷贝过来后执行报错？

**Comment by Sunting78** [comment]
git clone的是release2.7分枝， 这个文件是develop分枝下的，如果要用的话请clone develop分支
