### ISSUE TITLE
RuntimeError: The specified component was not found MODNet.

### ISSUE THREAD

**Issue by wxmchgithub** [PaddlePaddle/PaddleSeg#3032]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

有好兄弟能帮忙解决下吗

**Comment by Harryoung** [comment]
请问你是在运行怎样的代码时遇到的这个报错？请补充完善信息哈

**Comment by wxmchgithub** [comment]
> 请问你是在运行怎样的代码时遇到的这个报错？请补充完善信息哈

没有问题了，我把仓库重新下载了一次。之前下的好像是以前的老版本，没跑通

**Comment by Harryoung** [comment]
好的，那就关闭了哈
