### ISSUE TITLE
经过paddleSeg处理后的nii文件可视化问题

### ISSUE THREAD

**Issue by wuhaoranran** [PaddlePaddle/PaddleSeg#3033]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在项目https://aistudio.baidu.com/aistudio/projectdetail/5124112?contributionType=1中，我训练了模型并使用 Paddle Inference 进行推理，推断后获取nii文件，但是itksnap打开后图像全黑，且无分割显示，2.nii为推断得出文件，请问应该如何正确打开文件，以获取分割图像
[2.nii.zip](https://github.com/PaddlePaddle/PaddleSeg/files/10918238/2.nii.zip)

**Comment by shiyutang** [comment]
请检查结果文件nii是否有数值，如果有数值，建议使用itksnap进行分割结果可视化时同时加载原图和label显示。
