### ISSUE TITLE
多模集成

### ISSUE THREAD

**Issue by hello-it-bit** [PaddlePaddle/PaddleSeg#3034]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

针对同一个模型的时候，我想要做一个不同fold的集成，该如何处理？

**Comment by shiyutang** [comment]
预测阶段自动会集成多个fold的模型，可以通过减少模型参数调整需要集成的fold：https://github.com/PaddlePaddle/PaddleSeg/blob/develop/contrib/MedicalSeg/configs/nnunet/msd_lung/README.md#predict
