### ISSUE TITLE
在使用Medicalseg中的nnunet模型进行3d医疗图像分割时 这个套件对数据进行了那些数据增强措施？

### ISSUE THREAD

**Issue by iyangiii** [PaddlePaddle/PaddleSeg#3039]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在使用Medicalseg中的nnunet模型进行3d医疗图像分割时 这个套件对数据进行了那些数据增强措施？如果想自行添加数据增强措施应该进行哪些操作？比如在配置文件里进行什么样的修改？

**Comment by shiyutang** [comment]
nnUNet没有将数据增强暴露在配置文件中，如果需要修改数据增强，需要修改此处的代码：https://github.com/PaddlePaddle/PaddleSeg/blob/a178d72855053881db628a232b742b2234f1f1f4/contrib/MedicalSeg/nnunet/datasets/dataset.py#L251

**Comment by stillfighter2** [comment]
> nnUNet没有将数据增强暴露在配置文件中，如果需要修改数据增强，需要修改此处的代码：
> 
> https://github.com/PaddlePaddle/PaddleSeg/blob/a178d72855053881db628a232b742b2234f1f1f4/contrib/MedicalSeg/nnunet/datasets/dataset.py#L251

请问训练集中的数据增强如何使用,或者我自己写了数据增强,更改了dataset.json文件,报了一些错误,这是为什么
![Screenshot 2023-03-09 194530](https://user-images.githubusercontent.com/94272548/224013537-3153d3cf-6e81-43a0-8d3b-ec36910e5866.png)
我的增强应该没有改变图像的维度

**Comment by shiyutang** [comment]
你的这个数据增强应该在reshape的时候出现了一些问题，或者查看修改的代码是否修改了原代码数据reshape的逻辑
