### ISSUE TITLE
您好，想问一下paddleseg在线加载预训练模型那个pretrained:参数里边的链接是在哪里查找，的一直找不到

### ISSUE THREAD

**Issue by zhaoyantao-murray** [PaddlePaddle/PaddleSeg#3040]
您好，想问一下paddleseg在线加载预训练模型那个pretrained:参数里边的链接是在哪里查找，的一直找不到

_Originally posted by @WanderJN in https://github.com/PaddlePaddle/PaddleSeg/issues/3011#issuecomment-1461362670_

**Comment by zhaoyantao-murray** [comment]
@WanderJN 在ImageNet上预训练的骨干网络的权重下载请参考https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/models/ImageNet1k/model_list.md
如果是整个模型的预训练权重请在PaddleSeg/configs/目录下的该模型readme中查看下载链接；

**Comment by hello-it-bit** [comment]
你好，请问提供的权重是什么数据集上面训练出来的呢？

**Comment by hello-it-bit** [comment]
老师，就是在(https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.7/contrib/MedicalSeg/configs/nnunet)/msd_lung/就是这个路径下面的权重文件，我想去AMOS2022数据集中使用这些权重文件的话，可以直接使用吗，就是直接用于验证推理，预测，不经过训练？？？
