### ISSUE TITLE
Multimode integration

### ISSUE THREAD

**Issue by hello-it-bit** [PaddlePaddle/PaddleSeg#3043]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

In the verification phase, if I want to check the accuracy of the folds that integrate different models and the json files generated by integrating different folds of the same model, what should I do? Of course, I understand it in the prediction phase.

**Comment by zhaoyantao-murray** [comment]
You can refer to this document https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/docs/evaluation/evaluate.md
