### ISSUE TITLE
20分钟快速上手paddleseg

### ISSUE THREAD

**Issue by hello-it-bit** [PaddlePaddle/PaddleSeg#3044]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

咋在20分钟快速上手paddleseg中指出   只有"PaddleSeg/configs/quick_start"下面配置文件中的学习率为单卡学习率，其他配置文件中均为4卡的学习率。如果大家单卡训练来复现公开数据集上的指标，学习率设置应变成原来的1/4，我查阅了paddleseg/configs/fastfcn里面的yml文件，里面的关于lr的信息不也是单卡的吗？

**Comment by zhaoyantao-murray** [comment]
paddleseg/configs/fastfcn里面的yml文件设置的学习率是4卡训练时的学习率；我没理解你的疑问点在哪里，可以再具体说明一下

**Comment by hello-it-bit** [comment]
老师，就是在(https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.7/contrib/MedicalSeg/configs/nnunet)/msd_lung/就是这个路径下面的权重文件，我想去AMOS2022数据集中使用这些权重文件的话，可以直接使用吗，就是直接用于验证推理，预测，不经过训练？？？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月10日(星期五) 上午10:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleSeg] 20分钟快速上手paddleseg (Issue #3044)





 
paddleseg/configs/fastfcn里面的yml文件设置的学习率是4卡训练时的学习率；我没理解你的疑问点在哪里，可以再具体说明一下

**Comment by zhaoyantao-murray** [comment]
直接使用的话可能效果不一定会很好，因为这个模型是在http://medicaldecathlon.com/  MSD数据集上训练得到的，建议加载此模型权重，在你的数据集上进行finetune训练，效果会好一些。
