### ISSUE TITLE
Paddle inference中的preprocess_time较长

### ISSUE THREAD

**Issue by boreas-l** [PaddlePaddle/PaddleSeg#3047]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包含open与closed)，没有类似需求。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar feature requests.

### 需求描述 Feature Description

paddleseg里inference中的preprocess环节，其耗时大概占整体耗时的四分之一，请问有什么优化方式吗？

### 是否愿意提交PR Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by Stinky-Tofu** [comment]
如果是在gpu上推理，可以考虑将一部分preprocess放到gpu上进行计算。 @boreas-l

**Comment by shiyutang** [comment]
现在可以直接使用基于tensor的预处理方式了。
