### ISSUE TITLE
Elseg - Model Training

### ISSUE THREAD

**Issue by tomo0530** [PaddlePaddle/PaddleSeg#3048]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hi all,

Thank you so much for this great app.

Elseg is supposed to use already trained models, but is it possible to use models trained on my own dataset?
https://github.com/PaddlePaddle/PaddleSeg/blob/develop/EISeg/docs/image_en.md

I plan to use OCRNet in Paddleseg config for the DL model and follow the instructions for training.
https://github.com/PaddlePaddle/PaddleSeg/blob/develop/docs/train/train.md

Thanks again!

**Comment by shiyutang** [comment]
EISeg is an interactive segmentation model rather than a segmentation model, if you want to use a self-trained model, you need to build your own interactive segmentation model. You can refer to this open-source code:https://github.com/SamsungLabs/ritm_interactive_segmentation

**Comment by tomo0530** [comment]
Thank you so much for your response. I understand the difference between a segmentation model and an interactive segmentation model. 
Let me ask one more question: The file extensions of the structure and weights in the Elseg pre-trained model are ".pdmodel" and ".pdiparams." Is this after a particular process, or are you changing only the extension?

I appreciate your consideration.

**Comment by shiyutang** [comment]
You are very welcome. The model is processed through the dytostatic process. Please refer to the [tools/export.py](https://github.com/PaddlePaddle/PaddleSeg/blob/develop/tools/export.py) for more details. This process transfers the dynamic model to the static model for less inference time.

Dytostatic doc：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/jit/basic_usage_cn.html#erdongzhuanjingxunlian

ps: Sorry the dytostatic doc did not have a English version. You may need to use the translator.

**Comment by tomo0530** [comment]
Thank you so much! Totally understood.
