### ISSUE TITLE
调用paddleseg serving的例程，运行客户端代码出现问题

### ISSUE THREAD

**Issue by Orderfrost** [PaddlePaddle/PaddleSeg#3049]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

我直接使用教程里面的代码
!python test_serving.py \
    --serving_client_path ~/serving_client \
    --serving_ip_port ip:port \
    --image_path path/to/image

但是报错
Traceback (most recent call last):
  File "test_serving.py", line 52, in <module>
    run(args)
  File "test_serving.py", line 30, in run
    client = Client()
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle_serving_client/client.py", line 149, in __init__
    from .serving_client import PredictorRes
ImportError: libcrypto.so.10: cannot open shared object file: No such file or directory

### 复现环境 Environment

环境是Aistudio 的A100

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Stinky-Tofu** [comment]
Hi，@Orderfrost 这种环境的问题，建议baidu/google一下

**Comment by nefusmzj** [comment]
+1
