### ISSUE TITLE
关于paddlseg网络修改问题

### ISSUE THREAD

**Issue by lxk767363331** [PaddlePaddle/PaddleSeg#305]
你好，最近尝试了使用 senet  acnet 进行修改hrnet 得到的指标远低于hrnet，还有一些在unet上的一些改进，仿照torch代码进行了改写，但是unet的结果仍然不好，所以存在疑问，网络中的一些初始化是不是仅限于当前网络，如果结构改变相应的东西全部都要改变。这是第一个问题。
第二个问题是，我尝试在hrnet上加空洞卷积 aspp 等方式 均没有得到有效的提升，请问有什么指导性的建议么？

**Comment by wuyefeilin** [comment]
非常欢迎你对网络进行一些新的尝试并提出分享。首先要明确的是，对网络的修改很难说就能得到比较好的效果，往往需要不断的尝试，另外不同的网络，适合的训练方式也是不大一样，这些都是需要大量尝试的。非常欢迎提出新的想法。

空洞卷积和aspp目的是在不下采样的情况下获得比较大的感受野， 而hrnet本身就是high resolution net， 所以加上空洞卷机和aspp很难再有效果上的提升，看网上hrnet+ocr效果还是有比较明显的提升， 你这一块可以尝试尝试， 我们这边也在尝试， 欢迎一起分享。

**Comment by lxk767363331** [comment]
好的，谢谢建议，以前尝试了gsc加入到HRNET也失败了。刚想到我前几天尝试使用可变形卷积在HRNet中 但是 结果反而下降，我放在的是HRNet最后一个阶段，4个分支中 4次block_num中倒数第1层 倒数第3层，想问一下 ，如果使用可变性卷积，他的位置，一般放在什么位置，原文中选择的是res5abc的倒数第三层。
我的数据集在hrnet上的最好IOU是0.875，高于unet与deeplab， 请问着算高么，是不是因为数据没有那么复杂，使用更复杂的网络结构反而得不到好的结果？

**Comment by wuyefeilin** [comment]
可形变卷积一般放在后面几个卷积中，当然你也可以把所有的卷积都替换成可形变卷积，作者在第二个版本中提到将所有的卷积替换成可形变卷积在比较复杂数据集上还是有所提升的。

IoU的高低还是得看数据集的复杂程度，你可以可视化看一下效果是否达到你的要求，同时跟你的标注也是有比较大关系的。
