### ISSUE TITLE
在unetr上训练自己的数据集

### ISSUE THREAD

**Issue by iyangiii** [PaddlePaddle/PaddleSeg#3051]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用MedicalSeg套件unetr模型训练自己的数据集 该怎么训练 图像本身可以转化为三维数组 unetr需要四维数组作为数据传入模型  并且该模型需要的数据为[batch size,channel,height,weight],强行将nii文件转化为三维数组后增加一个维度变为四维数组并交换维度再转化为nii文件传入模型会报错
![image](https://user-images.githubusercontent.com/101607550/224704918-8486cf97-bf25-4e3e-a7a5-5673a531d0f2.png)
请问如何解决

**Comment by shiyutang** [comment]
Hello～
你可以仿照[msd_brain_dataset](https://github.com/PaddlePaddle/PaddleSeg/blob/develop/contrib/MedicalSeg/medicalseg/datasets/msd_brain_seg.py)增加一个自己数据集的文件。其作用在于在预处理文件成为numpy数组之后，通过这个数据集传入dataloader就可以获得指定形状的4维数组，更加详细的在自己数据集上训练的教程在：https://github.com/PaddlePaddle/PaddleSeg/blob/develop/contrib/MedicalSeg/README_CN.md#-%E5%9C%A8%E8%87%AA%E5%B7%B1%E7%9A%84%E6%95%B0%E6%8D%AE%E4%B8%8A%E8%AE%AD%E7%BB%83

**Comment by iyangiiiii** [comment]
你好
![image](https://user-images.githubusercontent.com/101607550/225498485-f4222998-f9fd-4e81-bc93-84cba7d771c8.png)
我是严格按照那个教程上操作的 但是还是会报一个我无法解决的问题 能否再给一些信息

**Comment by iyangiii** [comment]
> 你好~ 你可以仿照[msd_brain_dataset](https://github.com/PaddlePaddle/PaddleSeg/blob/develop/contrib/MedicalSeg/medicalseg/datasets/msd_brain_seg.py)增加一个自己数据集的文件。其作用在于在预处理文件成为numpy数组之后，通过这个数据集传入dataloader就可以获得指定形状的4维数组，更加详细的在自己数据集上训练的教程在：https://github.com/PaddlePaddle/PaddleSeg/blob/develop/contrib/MedicalSeg/README_CN.md#-%E5%9C%A8%E8%87%AA%E5%B7%B1%E7%9A%84%E6%95%B0%E6%8D%AE%E4%B8%8A%E8%AE%AD%E7%BB%83



你好 我是严格按照那个教程来的 配置文件和数据集等 都是按照教程一步一步走的
![image](https://user-images.githubusercontent.com/101607550/225498825-cacbc3af-1914-4491-b037-879805b45f23.png)
但还是出现了以上问题 请问能否再给出一些信息

**Comment by shiyutang** [comment]
看了一下你的报错～
第一个报错是数据类型不符合期望，在transform的时候需要numpy作为输入，但是获取到了nii，说明没有进行prepare_dateset.py 的操作，将数据转换成numpy。
第二个报错，我对应代码看了下，但是没有找到你出错的这行代码，建议更新代码版本到最新的develop，另外这个报错也是数据读取出错，可以往这个方向看看，不过还是建议替换为develop版本，并处理好数据（参考其他数据的prepare dataset）后再进行尝试。如果后续遇到其他问题，欢迎在本条issue下更新。

**Comment by iyangiiiii** [comment]
> > 你好~ 你可以仿照[msd_brain_dataset](https://github.com/PaddlePaddle/PaddleSeg/blob/develop/contrib/MedicalSeg/medicalseg/datasets/msd_brain_seg.py)增加一个自己数据集的文件。其作用在于在预处理文件成为numpy数组之后，通过这个数据集传入dataloader就可以获得指定形状的4维数组，更加详细的在自己数据集上训练的教程在：https://github.com/PaddlePaddle/PaddleSeg/blob/develop/contrib/MedicalSeg/README_CN.md#-%E5%9C%A8%E8%87%AA%E5%B7%B1%E7%9A%84%E6%95%B0%E6%8D%AE%E4%B8%8A%E8%AE%AD%E7%BB%83
> 
> 你好 我是严格按照那个教程来的 配置文件和数据集等 都是按照教程一步一步走的 ![image](https://user-images.githubusercontent.com/101607550/225498825-cacbc3af-1914-4491-b037-879805b45f23.png) 但还是出现了以上问题 请问能否再给出一些信息

你好 我发现自己确实少了一个prepare这一步 但是无法运行prepare_msd_brain_seg.py 根据报错我认为是需要先运行prepare_msd.py 但是我运行后他提示了一个引用库的报错 我已更新develop版本
![image](https://user-images.githubusercontent.com/101607550/225528057-181473b0-5d19-4bf6-879d-98834cb1ee12.png)

**Comment by iyangiiiii** [comment]
> 看了一下你的报错~ 第一个报错是数据类型不符合期望，在transform的时候需要numpy作为输入，但是获取到了nii，说明没有进行prepare_dateset.py 的操作，将数据转换成numpy。 第二个报错，我对应代码看了下，但是没有找到你出错的这行代码，建议更新代码版本到最新的develop，另外这个报错也是数据读取出错，可以往这个方向看看，不过还是建议替换为develop版本，并处理好数据（参考其他数据的prepare dataset）后再进行尝试。如果后续遇到其他问题，欢迎在本条issue下更新。

你好 我发现自己确实少了一个准备这一步 但是无法运行prepare_msd_brain_seg.py 根据报错我认为是需要先运行prepare_msd.py 但是我运行后他提示了一个引用库的报错 我已更新develop版本
![image](https://user-images.githubusercontent.com/101607550/225528222-70882bad-bc8f-489c-8014-64264392042b.png)

**Comment by iyangiiiii** [comment]
> 看了一下你的报错~ 第一个报错是数据类型不符合期望，在transform的时候需要numpy作为输入，但是获取到了nii，说明没有进行prepare_dateset.py 的操作，将数据转换成numpy。 第二个报错，我对应代码看了下，但是没有找到你出错的这行代码，建议更新代码版本到最新的develop，另外这个报错也是数据读取出错，可以往这个方向看看，不过还是建议替换为develop版本，并处理好数据（参考其他数据的prepare dataset）后再进行尝试。如果后续遇到其他问题，欢迎在本条issue下更新。

你好 我发现了自己确实缺少了prepare_msd_brain_seg这步操作 但是我在运行这步操作时 我想对自己的数据集进行预处理该怎么操作 我运行这步命令 他会下载自带的数据集 试图修改后面的数字 都会报错
![image](https://user-images.githubusercontent.com/101607550/225529945-c77d2de6-8e6e-4235-9855-ad07b2ba4de1.png)

**Comment by iyangiii** [comment]
> 看了一下你的报错~ 第一个报错是数据类型不符合期望，在transform的时候需要numpy作为输入，但是获取到了nii，说明没有进行prepare_dateset.py 的操作，将数据转换成numpy。 第二个报错，我对应代码看了下，但是没有找到你出错的这行代码，建议更新代码版本到最新的develop，另外这个报错也是数据读取出错，可以往这个方向看看，不过还是建议替换为develop版本，并处理好数据（参考其他数据的prepare dataset）后再进行尝试。如果后续遇到其他问题，欢迎在本条issue下更新。

你好 我发现了自己确实缺少了prepare_msd_brain_seg这步操作 但是我在运行这步操作时 我想对自己的数据集进行预处理该怎么操作 我运行这步命令 他会下载自带的数据集 试图修改后面的数字 都会报错 也已经尝试过将自己的数据集的压缩包放在了medicalseg对应的data目录下
![image](https://user-images.githubusercontent.com/101607550/225531021-35dd854a-4d6f-4647-b508-0d940a4e46ae.png)

**Comment by shiyutang** [comment]
需要为自己数据仿照撰写一个prepare_msd_brain_seg的脚本，主要是进行格式转换和切图。如果已经有数据，可以跳过数据下载这步。

**Comment by iyangiiiii** [comment]
> 需要为自己数据仿照撰写一个prepare_msd_brain_seg的脚本，主要是进行格式转换和切图。如果已经有数据，可以跳过数据下载这步。

好的好的 还有我在训练SwinUnet模型时出现了如下两个报错 第一个是需要我自己写预处理脚本 第二个是什么问题呢
![image](https://user-images.githubusercontent.com/101607550/225542939-a90e831e-c8c9-4dd8-92b8-6edbc905e6a3.png)

**Comment by iyangiiiii** [comment]
> 需要为自己数据仿照撰写一个prepare_msd_brain_seg的脚本，主要是进行格式转换和切图。如果已经有数据，可以跳过数据下载这步。

好的好的 还有就是我在训练swinunet模型时 出现了如下两种报错 第一个是需要我自己写一个预处理的脚本 那第二个报错是什么情况呢
![image](https://user-images.githubusercontent.com/101607550/225543166-1a03ab5a-a991-4008-bd98-8aa5624bc42c.png)
![image](https://user-images.githubusercontent.com/101607550/225543202-88ef377c-45d8-4641-b043-dff2dee88909.png)
查询了NVIDIA官网相关的信息
![image](https://user-images.githubusercontent.com/101607550/225543309-1b8e0d6c-6a3a-4f14-a1f0-67f722d03ff7.png)
