### ISSUE TITLE
视频传播模型的地址无效

### ISSUE THREAD

**Issue by qazyjg** [PaddlePaddle/PaddleSeg#3054]
### 文档链接&描述 Document Links & Description

你好，视频传播模型的下载地址无效，能否更新一下 谢谢！
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/EISeg/docs/video.md#%E6%A8%A1%E5%9E%8B%E9%80%89%E6%8B%A9

**Comment by shiyutang** [comment]
好的，我们将尽快更新

**Comment by qazyjg** [comment]
感谢回复，能否它提供一个临时的下载地址

**Comment by spencer03172023** [comment]
> 好的，我们将尽快更新

请问什么时候可以更新，方便提供一个临时地址吗，非常感谢。

**Comment by SMY19999** [comment]
等+1

**Comment by Harryoung** [comment]
develop分支是可以下载的哈

**Comment by shiyutang** [comment]
GoodFirstIssue：cherry-pick to 2.8

**Comment by Liyulingyue** [comment]
This issue can be closed due to #3452 @shiyutang
