### ISSUE TITLE
NNUnet 训练显存爆满问题

### ISSUE THREAD

**Issue by huangguoqing** [PaddlePaddle/PaddleSeg#3059]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我目前在自己电脑上配置的，运行MSD数据集做分割时候，12G的显卡内存显示满了，我看batch_size已经设置成1了，gpu也没有被其他程序占用，不知道遇到这个问题改什么参数可以训练网络？

环境配置：
platform: Linux-5.15.0-67-generic-x86_64-with-debian-bullseye-sid
Python: 3.7.16 (default, Jan 17 2023, 22:20:44) [GCC 11.2.0]
Paddle compiled with cuda: True
NVCC: Build cuda_11.6.r11.6/compiler.30794723_0
cudnn: 8.4
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: NVIDIA GeForce']
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PaddlePaddle: 2.4.2
-----------------------

报错如下：

loading dataset
loading all case properties
dataset split over! dataset mode: train, keys: ['lung_001' 'lung_003' 'lung_004' 'lung_005' 'lung_009' 'lung_014'
'lung_015' 'lung_016' 'lung_018' 'lung_020' 'lung_022' 'lung_023'
'lung_025' 'lung_026' 'lung_027' 'lung_028' 'lung_029' 'lung_031'
'lung_036' 'lung_037' 'lung_038' 'lung_043' 'lung_044' 'lung_045'
'lung_047' 'lung_049' 'lung_051' 'lung_053' 'lung_054' 'lung_055'
'lung_057' 'lung_058' 'lung_061' 'lung_062' 'lung_064' 'lung_069'
'lung_071' 'lung_073' 'lung_074' 'lung_075' 'lung_078' 'lung_080'
'lung_081' 'lung_083' 'lung_084' 'lung_086' 'lung_092' 'lung_093'
'lung_095' 'lung_096']
terminate called after throwing an instance of 'paddle::memory::allocation::BadAlloc'
what():
C++ Traceback (most recent call last):

0 conv2d_ad_func(paddle::experimental::Tensor const&, paddle::experimental::Tensor const&, std::vector<int, std::allocator >, std::vector<int, std::allocator >, std::string, int, std::vector<int, std::allocator >, std::string, bool, int, bool)
1 conv2d_ad_func(paddle::experimental::Tensor const&, paddle::experimental::Tensor const&, std::vector<int, std::allocator >, std::vector<int, std::allocator >, std::string, int, std::vector<int, std::allocator >, std::string, bool, int, bool)
2 paddle::experimental::conv2d(paddle::experimental::Tensor const&, paddle::experimental::Tensor const&, std::vector<int, std::allocator > const&, std::vector<int, std::allocator > const&, std::string const&, int, std::vector<int, std::allocator > const&, std::string const&, bool, int, bool)
3 void phi::ConvCudnnKernel<phi::dtype::float16, phi::GPUContext>(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, std::vector<int, std::allocator > const&, std::vector<int, std::allocator > const&, std::string const&, int, std::vector<int, std::allocator > const&, std::string const&, bool, int, bool, phi::DenseTensor*)
4 phi::DnnWorkspaceHandle::ReallocWorkspace(unsigned long)
5 paddle::memory::allocation::Allocator::Allocate(unsigned long)
6 paddle::memory::allocation::StatAllocator::AllocateImpl(unsigned long)
7 paddle::memory::allocation::Allocator::Allocate(unsigned long)
8 paddle::memory::allocation::Allocator::Allocate(unsigned long)
9 paddle::memory::allocation::Allocator::Allocate(unsigned long)
10 paddle::memory::allocation::CUDAAllocator::AllocateImpl(unsigned long)
11 std::string phi::enforce::GetCompleteTraceBackString<std::string >(std::string&&, char const*, int)
12 phi::enforce::GetCurrentTraceBackString[abi:cxx11](https://github.com/PaddlePaddle/PaddleSeg/issues/bool)
Error Message Summary:

ResourceExhaustedError:

Out of memory error on GPU 0. Cannot allocate 384.017822MB memory on GPU 0, 11.543640GB memory has been allocated and available memory is only 198.625000MB.

Please check whether there is any other process using GPU 0.

    If yes, please stop them, or start PaddlePaddle on another GPU.
    If no, please decrease the batch size of your model.
    If the above ways do not solve the out of memory problem, you can try to use CUDA managed memory. The command is export FLAGS_use_cuda_managed_memory=false.
    (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:95)

**Comment by stillfighter2** [comment]
首先12G的显存不够运行这个文件,其次batchsize在网络中修改是没有用的,他写到了nnunet的pkl配置文件中,所以,你最好使用AI Studio,或者你一定要在本地运行的话,推荐你打开configs对应的nnunet.pkl配置,修改内置的batch_size,内置的bc貌似是6,改成4或许可以运行

**Comment by huangguoqing** [comment]
好的，感谢回复

**Comment by huangguoqing** [comment]
还有一个疑问我看到你也增加了自己的数据重新做训练，不知道这一步坑多吗，增加imageTr labelTr 改data.json就可以了吗

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
