### ISSUE TITLE
推理时，训练集的mIOU总是比验证集低很多？

### ISSUE THREAD

**Issue by m828** [PaddlePaddle/PaddleSeg#3060]
### 问题描述 Please describe your issue

我尝试了ppliteseg在Cityscapes和CamVid数据集上的测试结果，val比test高，很多论文中这两个的结果差不多，我在自己的模型上尝试也是这样，是什么问题？是eval代码块的原因吗

**Comment by juncaipeng** [comment]
收到 我们跟踪看下是否和cityscapes官网评估有差别

**Comment by m828** [comment]
> 收到 我们跟踪看下是否和cityscapes官网评估有差别
不是和cityscapes官网评估有无差别，我的意思是模型的验证和测试集结果相差较大，
![image](https://user-images.githubusercontent.com/45037914/225529688-29692a3e-93d8-4713-8b22-24ebcf554b11.png)

**Comment by djl00** [comment]
Hello. I'm also running this model. Can you communicate with me?
