### ISSUE TITLE
开启tensorRT推理时，报错FatalError: `Segmentation fault` is detected by the operating system.

### ISSUE THREAD

**Issue by chenxi0011** [PaddlePaddle/PaddleSeg#3065]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

环境：官方docker镜像 docker pull paddlepaddle/paddle:2.4.2-gpu-cuda11.2-cudnn8.2-trt8.0
自训练pp_liteseg网络模型，导出inference模型后。
进行推理时：
python3 deploy/python/infer.py --config ./models/deploy.yaml --image_path ./models/test_data --save_dir ./models/result --print_detail False --batch_size 1 --device gpu --use_trt True -enable_auto_tune=True
报错：
![image](https://user-images.githubusercontent.com/128033430/225565026-c633f7c1-1e68-494e-8b46-1d5dc8354582.png)
不开启trt，不会报错，正常推理。

### 复现环境 Environment

环境：官方docker镜像 docker pull paddlepaddle/paddle:2.4.2-gpu-cuda11.2-cudnn8.2-trt8.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Bobholamovic** [comment]
你好，请尝试在导出模型时指定`--input_shape`为固定值。

**Comment by chenxi0011** [comment]
你好，我的推理图片有 4096*1000的&nbsp; 有4086*1000的 这个值指定为多少合适呢？(较小的？)
我测试过4096*1000 还是报同样的错误

--------------原始邮件--------------
发件人："Lin&nbsp;Manhui ***@***.***&gt;;
发送时间：2023年3月16日(星期四) 晚上6:07
收件人："PaddlePaddle/PaddleSeg" ***@***.***&gt;;
抄送："陈熙 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [PaddlePaddle/PaddleSeg] 开启tensorRT推理时，报错FatalError: `Segmentation fault` is detected by the operating system. (Issue #3065)
-----------------------------------

 


你好，请尝试在导出模型时指定--input_shape为固定值。

—&amp;mdash;

**Comment by Bobholamovic** [comment]
这样的话，建议尝试使用TensorRT 7.2.*版本，我们在该版本测试通过。

**Comment by chenxi0011** [comment]
你好， 我在dockerhub 没有查到trt7.2版本对应的镜像。
另外，我本机的环境是nvcc -V  cuda=11.2
看了一下 trt7版本 支持的 cuda是10.2，这里是否需要对本机环境做调整呢？



***@***.***
 
发件人： Lin Manhui
发送时间： 2023-03-16 21:39
收件人： PaddlePaddle/PaddleSeg
抄送： chenxi0011; Author
主题： Re: [PaddlePaddle/PaddleSeg] 开启tensorRT推理时，报错FatalError: `Segmentation fault` is detected by the operating system. (Issue #3065)
这样的话，建议尝试使用TensorRT 7.2.*版本，我们在该版本测试通过。

**Comment by Bobholamovic** [comment]
> 你好， 我在dockerhub 没有查到trt7.2版本对应的镜像。 另外，我本机的环境是nvcc -V cuda=11.2 看了一下 trt7版本 支持的 cuda是10.2，这里是否需要对本机环境做调整呢？ ***@***.*** 发件人： Lin Manhui 发送时间： 2023-03-16 21:39 收件人： PaddlePaddle/PaddleSeg 抄送： chenxi0011; Author 主题： Re: [PaddlePaddle/PaddleSeg] 开启tensorRT推理时，报错FatalError: `Segmentation fault` is detected by the operating system. (Issue #3065) 这样的话，建议尝试使用TensorRT 7.2.*版本，我们在该版本测试通过。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

可以尝试官方的7.0镜像，如果仍然出现TRT错误的话可能就只能手动换装TRT 7.2了……后续我们将对更多TRT版本提供支持。

在你的主机上可以找到两个CUDA版本：driver version和runtime version。通过`nvidia-smi`指令获取到的CUDA版本是driver version，而你可以在不同容器、甚至同一个容器中安装多个CUDA runtime，只需要保证它们的CUDA runtime version **不高于** CUDA driver version。因此，如果你的CUDA driver version是11.2，安装10.2的CUDA runtime是没有问题的。

**Comment by chenxi0011** [comment]
收到 谢谢！！！



***@***.***
 
发件人： Lin Manhui
发送时间： 2023-03-17 10:25
收件人： PaddlePaddle/PaddleSeg
抄送： chenxi0011; Author
主题： Re: [PaddlePaddle/PaddleSeg] 开启tensorRT推理时，报错FatalError: `Segmentation fault` is detected by the operating system. (Issue #3065)
你好， 我在dockerhub 没有查到trt7.2版本对应的镜像。 另外，我本机的环境是nvcc -V cuda=11.2 看了一下 trt7版本 支持的 cuda是10.2，这里是否需要对本机环境做调整呢？ @.*** 发件人： Lin Manhui 发送时间： 2023-03-16 21:39 收件人： PaddlePaddle/PaddleSeg 抄送： chenxi0011; Author 主题： Re: [PaddlePaddle/PaddleSeg] 开启tensorRT推理时，报错FatalError: Segmentation fault is detected by the operating system. (Issue #3065) 这样的话，建议尝试使用TensorRT 7.2.版本，我们在该版本测试通过。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.**>
可以尝试官方的7.0镜像，如果仍然出现TRT错误的话可能就只能手动换装TRT 7.2了……后续我们将对更多TRT版本提供支持。
在你的主机上可以找到两个CUDA版本：driver version和runtime version。通过nvidia-smi指令获取到的CUDA版本是driver version，而你可以在不同容器、甚至同一个容器中安装多个CUDA runtime，只需要保证它们的CUDA runtime version 不高于 CUDA driver version。因此，如果你的CUDA driver version是11.2，安装10.2的CUDA runtime是没有问题的。
