### ISSUE TITLE
测试PaddleSeg时infer.py: error: the following arguments are required: --recipe, --mode

### ISSUE THREAD

**Issue by HuajiePan** [PaddlePaddle/PaddleSeg#3067]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在官方的GPU测试示例中，测试代码如下：
`python infer.py --model PP-Matting-512 --image matting_input.jpg --bg matting_bgr.jpg --device gpu`

但我实际运行之后，却报error需要另外两个参数，请问--recipe和--mode参数是如何使用的呢？感谢。

错误提示：
'root@593006d91fbc:~/data/PaddleSeg/deploy/fastdeploy/matting/cpu-gpu/python# python infer.py --model PP-Matting-512 --image matting_input.jpg --bg matting_bgr.jpg --device gpu
usage: infer.py [-h] --recipe RECIPE --mode MODE [--queue_dir QUEUE_DIR]
                [--base BASE] [--docker_args DOCKER_ARGS]
infer.py: error: the following arguments are required: --recipe, --mode'

**Comment by LiaoYuWei1** [comment]
请问解决了吗，我也遇到同样的问题

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
