### ISSUE TITLE
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/EISeg/docs/video.md

### ISSUE THREAD

**Issue by spencer03172023** [PaddlePaddle/PaddleSeg#3070]
### 文档链接&描述 Document Links & Description

https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/EISeg/docs/video.md
这里提供的”配套传播模型下载地址“地址无效。

### 请提出你的建议 Please give your suggestion

请问什么时候可以提供有效的下载链接？

**Comment by zhaoyantao-murray** [comment]
您好，我们会在近期更新链接，请您稍等几天

**Comment by spencer03172023** [comment]
> 您好，我们会在近期更新链接，请您稍等几天

Any update on this? Thanks

**Comment by geoyee** [comment]
@spencer03172023 you can download these parameters from the updated link in #3078 first.
