### ISSUE TITLE
GCA模型的配置文件

### ISSUE THREAD

**Issue by buguaigiser** [PaddlePaddle/PaddleSeg#3080]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问GCA模型的配置文件和预训练模型在哪里找？

**Comment by Sunting78** [comment]
GCA具体指哪个算法呢？ 麻烦写下全称

**Comment by buguaigiser** [comment]
Guided Contextual Attention Matting.  出自论文《Natural Image Matting via Guided Contextual Attention》

**Comment by buguaigiser** [comment]
Guided Contextual Attention Matting.&nbsp; 出自论文《Natural Image Matting via Guided Contextual Attention》




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月21日(星期二) 晚上8:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleSeg] GCA模型的配置文件 (Issue #3080)





 
GCA具体指哪个算法呢？ 麻烦写下全称

**Comment by Sunting78** [comment]
相应的配置文件和模型暂未给出, GCA模型的网络结构的相关代码在ppmatting/models里面，可以尝试自己配置下训练文件。

**Comment by buguaigiser** [comment]
谢谢
