### ISSUE TITLE
EISeg and PyInstaller compatibility

### ISSUE THREAD

**Issue by simoneorlando** [PaddlePaddle/PaddleSeg#3082]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

Trying to bundle a python app using PyInstaller but I got this import error when the application is run:
```
    from eiseg import controller
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "eiseg\controller.py", line 29, in <module>
    from models import EISegModel
ImportError: cannot import name 'EISegModel' from 'models' (unknown location)
```

I was able to fix this issue by editing the import in line 29 of the controller.py file from
`from models import EISegModel`
to
`from eiseg.models import EISegModel`

However, I would like to do this without having to modify manually the eiseg library. Can you fix this?

### 复现环境 Environment

-OS: Windows
-PaddlePaddle: 2.3.2
-PaddleSeg: 2.6.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by geoyee** [comment]
@simoneorlando Done, but FYI I think packaging eiseg with PyInstaller very difficult (I tried and failed :joy:), good luck bro.
