### ISSUE TITLE
win 系统推理

### ISSUE THREAD

**Issue by kewuyu** [PaddlePaddle/PaddleSeg#3084]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/109637491/226608742-32ac3c26-a9ce-4826-9d4d-9b54ee896972.png)

**Comment by shiyutang** [comment]
你好，这个看上去是环境的问题，需要在环境目录里添加cublas的动态链接库文件，找到一个相关解答参考：https://zhuanlan.zhihu.com/p/524187013

**Comment by kewuyu** [comment]
我看了一下，目录里面有那个文件夹，只有使用命令行才会报这个错

**Comment by shiyutang** [comment]
那么命令行对应环境是否是正确的呢？
