### ISSUE TITLE
关于RTFormer网络在Camvid数据集上的配置文件

### ISSUE THREAD

**Issue by universelyh** [PaddlePaddle/PaddleSeg#3085]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我注意到RTFormer在Camvid数据集的表现远远优越于其他模型，
但是没有看你们公布对应的模型和配置文件，
请问你们能不能公开对应的配置文件，
方便我们进行复现，
详细的配置论文中不是很详细，十分感谢。

**Comment by juncaipeng** [comment]
这个数据集没有提供配置文件，建议你可以参考论文自行配置一下。

**Comment by universelyh** [comment]
请问文中配置的random scaling of [288,1152]. 
是将720×960的图像怎么配置随机缩放呢？
具体是下面这三个参数怎么配置
type: ResizeStepScaling
      min_scale_factor: 
      max_scale_factor: 
      scale_step_size: 

还有就是需要配置968个epoch，
具体的iters应该是多少呢？

**Comment by universelyh** [comment]
> 这个数据集没有提供配置文件，建议你可以参考论文自行配置一下。
您好，
请提问论文中配置[288,1152]的随机缩放。
是将720×960的图像怎么配置随机缩小呢？
具体是下面这三个参数怎么配置
type: ResizeStepScaling
min_scale_factor:
max_scale_factor:
max

还有就是需要配置968个epoch，
具体的迭代次数应该是多少呢？

**Comment by universelyh** [comment]
请问文中配置的random scaling of [288,1152]. 
是将720×960的图像怎么配置随机缩放呢？ 
具体是下面这三个参数怎么配置 
type: ResizeStepScaling 
min_scale_factor: 
max_scale_factor: 
scale_step_size:

 还有就是需要配置968个epoch， 
具体的iters应该是多少呢？

**Comment by universelyh** [comment]
> 这个数据集没有提供配置文件，建议你可以参考论文自行配置一下。
我尝试按照论文中的设置配置文件，
复现的结果距离论文差别很大，
平均下降了5个点，
如文中达到82.5%的精度，复现只得到76%左右。
我怀疑是我配置参数的问题、或者数据集的问题。

**Comment by universelyh** [comment]
> 这个数据集没有提供配置文件，建议你可以参考论文自行配置一下。



> 这个数据集没有提供配置文件，建议你可以参考论文自行配置一下。

我尝试按照论文中的设置配置文件，
复现的结果距离论文差别很大，
平均下降了5个点，
如文中达到82.5%的精度，复现只得到76%左右。
我怀疑是我配置参数的问题、或者数据集的问题

**Comment by universelyh** [comment]
> 这个数据集没有提供配置文件，建议你可以参考论文自行配置一下。

我尝试按照论文中的设置配置文件，
复现的结果距离论文差别很大，
平均下降了5个点，
如文中达到82.5%的精度，复现只得到76%左右。
我怀疑是我配置参数的问题、或者数据集的问题

**Comment by Daniel-969** [comment]
请问问题解决了吗

**Comment by ZhengyuXia** [comment]
有同样的困惑，找了PPliteSeg的yml文件作为参考配置，手动按照rtformer的设定调参，用4块3090进行了训练，效果低了近7个百分点。

**Comment by lzg666321** [comment]
> > 这个数据集没有提供配置文件，建议你可以参考论文自行配置一下。
> 
> 我尝试按照论文中的设置配置文件， 复现的结果距离论文差别很大， 平均下降了5个点， 如文中达到82.5%的精度，复现只得到76%左右。 我怀疑是我配置参数的问题、或者数据集的问题

请问一下我在ubuntu上使用RTFormer训练camvid数据集的时候它的Numclasses设置11不行，提示“ValueError: label should not out of bound, but gotTensor(......)”，需要设置为13，是什么原因呢？ 但是在我本地自己电脑上numclasses设置11 是正常的,很疑惑。感谢回复。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
