### ISSUE TITLE
paddleseg中的humanseg是基于hrnet实现的吗，如果不是那是基于什么实现的？

### ISSUE THREAD

**Issue by jdyjjj** [PaddlePaddle/PaddleSeg#3087]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

paddleseg中的humanseg是基于hrnet实现的吗，如果不是那是基于什么实现的？

**Comment by shiyutang** [comment]
PP_humanseg有2种不同类型的模型，即轻量化、移动端模型，分别基于PPLiteSeg、MobileSeg建立，具体可以参见配置文件https://github.com/PaddlePaddle/PaddleSeg/blob/develop/paddleseg/models/pphumanseg_lite.py#L27
