### ISSUE TITLE
关于网络修改的问题

### ISSUE THREAD

**Issue by lxk767363331** [PaddlePaddle/PaddleSeg#309]
看到icnet的多路输出，想在其他模型中使用，有一下问题：
1.最后的损失是加和，那反向传播的时候也会多路反向传播，然后梯度叠加么？
2.多路损失权重设置一般是什么样的，看icnet是【1.0,0.4,0.16】
3.尝试在改进的unet上使用 ["lovasz_softmax_loss","softmax_loss"] 比重是0.2 0.8，但是没有效果上的提升，请问这样的原因是不是数据集本身（本身数据分布不均匀小目标存在的数据较少，不过整体的数据也很少）的复杂程度对于模型来说较简单，普通的softmax_loss就能起到很好的作用，但是我在hrnet上使用就会得到一个明显的改善，这里是不是因为特征丢失的原因 还是说有其他的代码反面的原因我不清楚，望解答，感谢！！！

**Comment by wuyefeilin** [comment]
1. 多路损失产生的梯度是会进行叠加的

2. 像icnet这样的多路损失的权重设置主要也是看网络更注重哪一路的损失，具体取值需根据网络的具体情况而定

3. 损失函数的组合并不一定比单个loss更好。另外loss的选择也跟数据集的复杂程度和分布情况有关，类别分布较均匀的情况下，softmax-loss往往就能取的不错的效果，这时候在进行loss组合不见得有效果上的提升。`hrnet上使用就会得到一个明显的改善`，具体的对比实验是怎么样的，效果提升多少？

**Comment by lxk767363331** [comment]
在hrnet上的实验上 miou从0.8453能提到0.8675这个水平。然后我在我改进的网络（基于unet上的加上了注意力）上使用["lovasz_softmax_loss","softmax_loss"] 就没有改善了。是不是受限于我网络本身的性能了。

**Comment by wuyefeilin** [comment]
能给一下hrnet对比实验的具体细节吗？ 损失函数组合的权重本身也是有影响的。如果参数没有影响的话，有可能是网络本身的原因。你可以具体做一下"lovasz_softmax_loss"和"softmax_loss"的对比实验，单独看看不同损失函数产生的影响，然后进行不同损失函数的组合，做进一步的比较，才能做最终的结论

**Comment by lxk767363331** [comment]
好的，我在PaddleSeg/configs/lovasz_softmax_deeplabv3p_mobilenet_pascal.yaml中到loss是["lovasz_softmax_loss","softmax_loss"]，以为lovasz_softmax_loss不能单独使用呢。
我马上做一下对比实验 再观察一下结果
