### ISSUE TITLE
PP-LiteSeg STDC2的模型tensorRT加速，精度完全丢失

### ISSUE THREAD

**Issue by Enchanted0911** [PaddlePaddle/PaddleSeg#3091]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

用paddleserving python pipeline 部署的seg模型，gpu推理的时候正常，设置好tensorRT后服务正常，但是精度完全丢失了，就是胡乱分割，什么都不变，改回gpu推理精度就正常了。我设置的静态图1024 1024 推理

### 复现环境 Environment

paddlepaddle 2.3.2
paddleserving 0.9
cuda 11.3.1
cudnn 8.2.1
tensorRT 8.0.3.4

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Bobholamovic** [comment]
你好，请尝试使用TensorRT 7.2.x版本进行推理。参见：https://github.com/PaddlePaddle/PaddleSeg/issues/3065

**Comment by Enchanted0911** [comment]
> 你好，请尝试使用TensorRT 7.2.x版本进行推理。参见：#3065

我的显卡是安培架构的，tensorRT8效果会不会比7的版本效果好。

**Comment by Bobholamovic** [comment]
> > 你好，请尝试使用TensorRT 7.2.x版本进行推理。参见：#3065
> 
> 我的显卡是安培架构的，tensorRT8效果会不会比7的版本效果好。

理论上是的，但PP-LiteSeg在使用TRT8推理的时候好像会有些问题（我们还没有测试过）。为了确保PP-LiteSeg能够得到正确的结果，请使用TRT 7.2.x版本。

**Comment by Enchanted0911** [comment]
> > > 你好，请尝试使用TensorRT 7.2.x版本进行推理。参见：#3065
> > 
> > 
> > 我的显卡是安培架构的，tensorRT8效果会不会比7的版本效果好。
> 
> 理论上是的，但PP-LiteSeg在使用TRT8推理的时候好像会有些问题（我们还没有测试过）。为了确保PP-LiteSeg能够得到正确的结果，请使用TRT 7.2.x版本。

好吧，我是多模型串联使用的，期待修复TRT8版本的问题。
