### ISSUE TITLE
已标注形状修改标签

### ISSUE THREAD

**Issue by dwj192** [PaddlePaddle/PaddleSeg#3093]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包含open与closed)，没有类似需求。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; 
标注牲口
3. 需求场景（请描述你的项目中为什么需要用此功能）; 
有多个标签，如马、马脸、马头、马眼，每幅图上都会依次标多个标签
标完一张标下一张时，选中的还是马眼这个标签，误操作就点上去了，点上去标好了马，要切换马脸的时候才发现，标错了。
 3. 功能描述（请简单描述或设计这个功能）
目前这种情况只能删了重来，如果能把右键用起来，选中标注形状的时候，点右键，弹出label列表，更换一个label就好。

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by zhaoyantao-murray** [comment]
请问您是在使用EISeg时的问题嘛

**Comment by dwj192** [comment]
是的


| |
dwj192
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年3月24日 19:26 |
| 收件人 | ***@***.***> |
| 抄送人 | Wenjian ***@***.***> ,
***@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleSeg] 已标注形状修改标签 (Issue #3093) |

请问您是在使用EISeg时的问题嘛

**Comment by dwj192** [comment]
有需要快速演示或说明问题，可以电话：微信同号
| |
dwj192
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年3月24日 19:26 |
| 收件人 | ***@***.***> |
| 抄送人 | Wenjian ***@***.***> ,
***@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleSeg] 已标注形状修改标签 (Issue #3093) |

请问您是在使用EISeg时的问题嘛

**Comment by Harryoung** [comment]
这个需求确实比较合理，我们评估一下，会考虑在未来版本支持哈。

**Comment by fozymaster** [comment]
请问这个需求已经增加了吗，这个问题还挺麻烦的

**Comment by Harryoung** [comment]
不好意思最近没办法排上这个feature，建议您那边在切换图片的时候先多多留意一下哈
