### ISSUE TITLE
关于paddleseg的剪枝prune

### ISSUE THREAD

**Issue by censhallwe** [PaddlePaddle/PaddleSeg#3094]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问，paddleseg提供的剪枝代码prune.py应用的是结构化剪枝还是非结构化剪枝呢？
是针对每一层进行局部的剪枝，还是针对全局整个模型的全局性的剪枝呢？
剪枝具体是将模型的权重参数置0了呢还是直接移除了呢？

**Comment by juncaipeng** [comment]
是结构化剪枝，筛选出部分层，直接移除部分通道。

**Comment by censhallwe** [comment]
> 是结构化剪枝，筛选出部分层，直接移除部分通道。

感谢解答❤
