### ISSUE TITLE
关于肖像分割部分的使用

### ISSUE THREAD

**Issue by naixupan** [PaddlePaddle/PaddleSeg#3095]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问如果我只想使用肖像分割，并且安装了依赖，我可以只保留PP-HumanSeg文件夹下的内容吗？

**Comment by zhaoyantao-murray** [comment]
可以的
