### ISSUE TITLE
SFNet部署时使用TensorRT加速预测报错中止

### ISSUE THREAD

**Issue by censhallwe** [PaddlePaddle/PaddleSeg#3096]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

使用命令：python deploy/python/infer.py --config output_1_1/inference_model/deploy.yaml --image_path data/video_test/decode/ --use_trt True --save_dir output/ --precision 'fp16' --enable_auto_tune True
我在命令行调用了这个infer.py文件，参考的是https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/docs/deployment/inference/python_inference_cn.md  这个文档中关于模型部署的步骤，我想通过tensorRT加速SFNet预测分割，但是遇到了如下的报错：
I0324 21:49:32.911206 168367 engine.cc:675] ====== engine info ======
I0324 21:49:32.917165 168367 engine.cc:680] Layers:
bilinear_interp_v2_4.tmp_0 copy
conv2d_74.tmp_0 copy
conv2d (Output: conv2d_76.tmp_0518)
transpose (Output: transpose_1.tmp_0566)
unsqueeze2 (Output: unsqueeze2_1.tmp_0561)
unsqueeze2 (Output: unsqueeze2_1.tmp_0561)_copy_output
transpose (Output: transpose_0.tmp_0555) + unsqueeze2 (Output: unsqueeze2_0.tmp_0558)
unsqueeze2_0.tmp_0558 copy
(Unnamed Layer* 21) [Shuffle]
Reformatting CopyNode for Input Tensor 0 to PWN(elementwise (Output: tmp_1571), elementwise (Output: tmp_2573))
PWN(elementwise (Output: tmp_1571), elementwise (Output: tmp_2573))
grid_sampler (Output: grid_sample_0.tmp_0575)
elementwise (Output: tmp_3577)
Reformatting CopyNode for Input Tensor 0 to conv2d (Output: batch_norm_29.tmp_2590) + relu (Output: relu_25.tmp_0592)
conv2d (Output: batch_norm_29.tmp_2590) + relu (Output: relu_25.tmp_0592)
Reformatting CopyNode for Output Tensor 0 to conv2d (Output: batch_norm_29.tmp_2590) + relu (Output: relu_25.tmp_0592)
conv2d (Output: conv2d_80.tmp_0620)

Bindings:
bilinear_interp_v2_4.tmp_0
conv2d_74.tmp_0
relu_23.tmp_0
relu_24.tmp_0
tile_0.tmp_0
tile_1.tmp_0
tmp_0
tmp_3577
conv2d_80.tmp_0620
relu_25.tmp_0592
I0324 21:49:32.917204 168367 engine.cc:682] ====== engine info end ======
I0324 21:49:32.918941 168367 tensorrt_subgraph_pass.cc:244] ---  detect a sub-graph with 115 nodes
I0324 21:49:32.929591 168367 tensorrt_subgraph_pass.cc:560] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I0324 21:49:33.003453 168367 engine.cc:119] Run Paddle-TRT FP16 mode
I0324 21:49:33.003485 168367 engine.cc:199] Run Paddle-TRT Dynamic Shape mode.
E0324 21:49:33.061941 168367 helper.h:114] 4: [graphShapeAnalyzer.cpp::processCheck::587] Error Code 4: Internal Error (strided_slice (Output: shape_8.tmp_0_slice_0_strided_slice_0738): ISliceLayer has out of bounds access on axis 0)
E0324 21:49:33.073792 168367 helper.h:114] 2: [builder.cpp::buildSerializedNetwork::636] Error Code 2: Internal Error (Assertion engine != nullptr failed. )

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::OptimizeInferenceProgram()
5   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
8   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
9   paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
10  paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > >*) const
11  paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*)
12  paddle::inference::tensorrt::TensorRTEngine::FreezeNetwork()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1679665773 (unix time) try "date -d @1679665773" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x8) received by PID 168367 (TID 0x7f7169c3f3c0) from PID 8 ***]

Segmentation fault (core dumped)

前面的提示信息省略，因为没有报错且太长。到这里报错了，请问有人知道是什么原因导致的吗？我看文档里提到“少部分模型暂时不支持在Nvidia GPU上使用TensorRT方式部署”，这里的少部分模型包含我所用到的SFNet吗？再详细点问，现在Paddleseg上已知的不支持以TensorRT方式部署的模型有哪些呢？SFNet用的是ResNet18的骨干网络，前面训练、导出、以及导出ONNX模型都是正常进行的。如果需要训练时用的配置文件，我可以再提供。

### 复现环境 Environment

-OS: Linux
-PaddlePaddle: gpu版本2.4.1.post117
-PaddleSeg: 2.7.0
-Python: 3.7.11
-CUDA: 11.7
-CUDNN: 8.4.1
-GCC: 7.5.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by censhallwe** [comment]
Hi 请问paddleseg支持SFNet转成trt加速预测吗？还有哪些模型是不支持trt的呢？

**Comment by juncaipeng** [comment]
可以参考首页文档转onnx，再使用trt加载部署。  可能会存在无法转换的情况。

**Comment by censhallwe** [comment]
> 可以参考首页文档转onnx，再使用trt加载部署。 可能会存在无法转换的情况。

转ONNX再使用trt之前也试过了，模型中有个NonZero模块无法转换，这么看来SFNet无法转换到TensorRT模型的

**Comment by juncaipeng** [comment]
嗯
