### ISSUE TITLE
推理模型移植移动端出现了一些问题

### ISSUE THREAD

**Issue by YSXCC** [PaddlePaddle/PaddleSeg#3097]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我使用自己的数据集训练用于识别图片中文字区域的MobileSeg模型，在PC环境下能够正常运行，但是移植到移动端就会出现尺寸和识别区域重复的问题

**Comment by YSXCC** [comment]
![result](https://user-images.githubusercontent.com/46277907/227719679-ab56f6f5-d2de-4b54-b46e-d5d0a3a2a8af.jpg)

**Comment by Sunting78** [comment]
请将执行的命令，配置文件等信息贴全。
