### ISSUE TITLE
关于导出模型和推理的问题

### ISSUE THREAD

**Issue by universelyh** [PaddlePaddle/PaddleSeg#3098]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

(paddle) root@fca7834e87ae:/Workspace/PaddleSeg-develop# python export.py --config configs/0-cityscapes/S.yml  --model_path output/nightcity/S-N=2/iter_156000/model.pdparams --save_dir output/model-export/0speed-cityscapes/0 --input_shape 1 3 1024 1024
/root/anaconda3/envs/paddle/lib/python3.6/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
W0326 15:54:29.301767 2827793 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 12.0, Runtime API Version: 10.1
W0326 15:54:29.304144 2827793 device_context.cc:465] device: 0, cuDNN Version: 7.6.
2023-03-26 15:54:30 [INFO]	Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet1.tar.gz
2023-03-26 15:54:30 [INFO]	There are 145/145 variables loaded into STDCNet.
2023-03-26 15:54:30 [INFO]	Loaded trained params of model successfully.
2023-03-26 15:54:32 [INFO]	The inference model is saved in output/model-export/0speed-cityscapes/0
2023-03-26 15:54:32 [WARNING]	This `export.py` will be removed in version 2.8, please use `tools/export.py`.
(paddle) root@fca7834e87ae:/Workspace/PaddleSeg-develop# python deploy/python/infer_benchmark.py --config output/model-export/0speed-cityscapes/0/deploy.yaml --image_path  data/cityscapes/leftImg8bit/train/aachen/aachen_000000_000019_leftImg8bit.png
/root/anaconda3/envs/paddle/lib/python3.6/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
2023-03-26 15:54:43 [INFO]	Use GPU
2023-03-26 15:54:44 [INFO]	input shape:(1, 3, 1024, 512)
2023-03-26 15:54:45 [INFO]	Warmup
2023-03-26 15:54:45 [INFO]	Infer
2023-03-26 15:54:46 [INFO]	Average time: 6.552 ms/img

我在导出模型时设置的图片尺寸好像没有作用,
我尝试过--input_shape 更改其他尺寸，
但是在推理时仍然是input shape:(1, 3, 1024, 512)，
请问是什么原因呢？
还是说我理解错误了。

**Comment by Sunting78** [comment]
configs/0-cityscapes/S.yml  猜测是这里面的transform配置导致的，在deploy/python/infer_benchmark.py 时根据config对图像会做transform。可以贴一下配置文件。可以看下[transfom数据](https://github.com/PaddlePaddle/PaddleSeg/blob/2701c577d2379ee792d3ae57e75ec68e4f991bdc/deploy/python/infer_benchmark.py#L165)

**Comment by universelyh** [comment]
batch_size: 8 #8
iters: 160000

train_dataset:
  type: Cityscapes
  dataset_root: data/cityscapes
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [1024, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Cityscapes
  dataset_root: data/cityscapes
  transforms:
    - type: Normalize
  mode: val

是根据训练过程的transform配置的吗，
那我想要测试原图大小的图片应该如何配置呢？

**Comment by Sunting78** [comment]
麻烦贴下这个文件output/model-export/0speed-cityscapes/0/deploy.yaml
另外，请使用tools/export.py进行导出，重新尝试下

**Comment by universelyh** [comment]
您好 当我运行tools/export.py时，
![image](https://user-images.githubusercontent.com/113585843/229008174-8558cd59-4cbc-4df7-8c2d-1385aeb9e986.png)
显示找不到文件
Traceback (most recent call last):
  File "tools/export.py", line 21, in <module>
    from paddleseg.cvlibs import Config
ModuleNotFoundError: No module named 'paddleseg'
请问这种情况要怎么处理，

**Comment by chongchongmao** [comment]
可能需要设置默认的根路径，比如%cd /home/aistudio/u或者使用paddleseg先前版本，先前版本根路径下的有export.py，tools也有exports.py，paddleseg2.8版本之后就只有在tools下有。

**Comment by shiyutang** [comment]
这里有两种原因，第一种是没有安装paddleseg，因此需要进一步提示开发者安装paddleseg；或者像@chongchongmao 所说，是环境变量的原因
