### ISSUE TITLE
SegNet报错：ValueError: The dataset is not Found or the folder structure is nonconfoumance

### ISSUE THREAD

**Issue by ababalaa** [PaddlePaddle/PaddleSeg#3099]
### 问题描述 Please describe your issue

配置文件：
![image](https://user-images.githubusercontent.com/128289606/227776308-2586a7e7-0c60-47ce-a9a2-af113ba4a6cc.png)
数据结构：
![image](https://user-images.githubusercontent.com/128289606/227776349-fdd98c2a-2299-4049-a2d4-3f1f447d2bd7.png)
运行的代码：
python tools/train.py --config configs/segnet/segnet_cityscapes_1024x512_80k.yml --do_eval --use_vdl --save_interval 500 --save_dir output/seg_net
/no_adjust
报错：
![image](https://user-images.githubusercontent.com/128289606/227776411-18fbe8df-e5b7-4e8c-ad09-8ff881f2b1a1.png)

**Comment by Sunting78** [comment]
data这个路径在paddleseg下面吗？检查一下，或者尝试下把dataset_root改为绝对路径。

**Comment by Alex37882388** [comment]
我尝试了不同的模型和yaml配置，都报这个错，也尝试了绝对路径，我使用的paddle 2.4.2，PaddleSeg 2.9release分支，请帮忙看一下：
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/24523802/64a94f8b-b9e4-4665-aef6-3720ed27ea17)
