### ISSUE TITLE
编译inference时出现的错误

### ISSUE THREAD

**Issue by AlmostNoMemory** [PaddlePaddle/PaddleSeg#31]
你好开发者，我在编译inference时出现如下错误信息：
/home/zyf/PycharmProjects/CorpsProject/PaddleSeg/opencv3/lib/libopencv_core.a(system.cpp.o): In function `cv::ipp::IPPInitSingleton::IPPInitSingleton()':
system.cpp:(.text._ZN2cv3ipp16IPPInitSingletonC2Ev[_ZN2cv3ipp16IPPInitSingletonC5Ev]+0x6b): undefined reference to `ippicvGetCpuFeatures'
...
...
中间省略了几十行，都是undefined reference to的错误

在编译inference过程中 按照文档重新编译安装了opencv，安装路为/mypath/Paddleseg/opencv3   opencv版本为3-4-6   
而且出现CmakeList中依赖的路径为/opencv3/lib64/xxxx.a 实际上我的opencv目录下只有lib路径， 将CMakeList中lib64改为lib解决了这一错误，但是又出现了上面这个错误
请问下是opencv编译安装的问题还是CMakeList设置的问题？

**Comment by sjtubinlong** [comment]
1. lib和lib64的问题系不同系统差异造成，我们会尽快修复。

一个快捷的解决方法是在`opencv`目录以及下创建软链接即可:
```shell
ln -s lib64 lib
cd share/OpenCV/3rdparty/
ln -s lib64 lib
```


2. IPP的问题，麻烦提供您的gcc版本和系统版本信息

对于`gcc 5.0`以上的版本，链接会有问题, 因为gcc从5.0后整个符号系统有较大改动，而paddlepaddle的预测库是基于gcc 4.8预编译。建议使用gcc4.9 或者 4.8编译。

如果你的gcc版本为4.9/4.8时仍然出现上述问题，重新解压编译

请尝试删除整个opencv目录，重新解压后执行编译。

**Comment by AlmostNoMemory** [comment]
> 1. lib和lib64的问题系不同系统差异造成，我们会尽快修复。
> 
> 一个快捷的解决方法是在`opencv`目录以及下创建软链接即可:
> 
> ```shell
> ln -s lib64 lib
> cd share/OpenCV/3rdparty/
> ln -s lib64 lib
> ```
> 
> 1. IPP的问题，麻烦提供您的gcc版本和系统版本信息
> 
> 对于`gcc 5.0`以上的版本，链接会有问题, 因为gcc从5.0后整个符号系统有较大改动，而paddlepaddle的预测库是基于gcc 4.8预编译。建议使用gcc4.9 或者 4.8编译。
> 
> 如果你的gcc版本为4.9/4.8时仍然出现上述问题，重新解压编译
> 
> 请尝试删除整个opencv目录，重新解压后执行编译。

gcc版本替换为4.8后编译通过了 非常感谢您的解答！
但是在执行预测时又出现了如下的错误：
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  Cannot open file freeze_model/__model__ at [/paddle/paddle/fluid/inference/api/analysis_predictor.cc:639]
PaddlePaddle Call Stacks: 
0            0x13cdb6dp void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 1645
1            0x13cf379p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
...
...

这个模型是我自己制作的数据集在unet预训练模型上跑出来的结果，但并不是final而是中途自动保存的参数中的一个，不知道是不是因为这个原因所以转化出来不正确呢？

**Comment by AlmostNoMemory** [comment]
> 1. lib和lib64的问题系不同系统差异造成，我们会尽快修复。
> 
> 一个快捷的解决方法是在`opencv`目录以及下创建软链接即可:
> 
> ```shell
> ln -s lib64 lib
> cd share/OpenCV/3rdparty/
> ln -s lib64 lib
> ```
> 
> 1. IPP的问题，麻烦提供您的gcc版本和系统版本信息
> 
> 对于`gcc 5.0`以上的版本，链接会有问题, 因为gcc从5.0后整个符号系统有较大改动，而paddlepaddle的预测库是基于gcc 4.8预编译。建议使用gcc4.9 或者 4.8编译。
> 
> 如果你的gcc版本为4.9/4.8时仍然出现上述问题，重新解压编译
> 
> 请尝试删除整个opencv目录，重新解压后执行编译。

gcc版本替换为4.8后编译通过了 非常感谢您的解答！ 
还有些小错误是两个库libjasper.a和libwebp.a，这两个不知道是不是opencv没有安装额外库导致不存在，我是从之前自己安装在/usr/里直接复制到新安装的opencv下解决的

但是在执行预测时又出现了如下的错误：
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
what(): Cannot open file freeze_model/__mode__ at [/paddle/paddle/fluid/inference/api/analysis_predictor.cc:639]
PaddlePaddle Call Stacks:
0 0x13cdb6dp void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 1645
1 0x13cf379p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
...
...

这个模型是我自己制作的数据集在unet预训练模型上跑出来的结果，但并不是final而是中途自动保存的参数中的一个，不知道是不是因为这个原因所以转化出来不正确呢？

**Comment by sjtubinlong** [comment]
@AlmostNoMemory 

这里的错误应该是路径问题，麻烦确认下配置文件中的模型文件路径是否正确，`Cannot open file freeze_model/mode` 这里的`mode`是否少了一个**l**

**Comment by AlmostNoMemory** [comment]
> @AlmostNoMemory
> 
> 这里的错误应该是路径问题，麻烦确认下配置文件中的模型文件路径是否正确，`Cannot open file freeze_model/mode` 这里的`mode`是否少了一个**l**

这个yaml的配置文件是运行export_model.py自动生产的，我自己并没有修改这里。
freeze_model文集夹下是__model__和__params__以及delpoy.yaml文件

然后yaml里的内容如下：
      ...
        MODEL_PATH : "freeze_model"
        MODEL_FILENAME : "__model__"
        PARAMS_FILENAME : "__params__"
      ...
这些应该都是没有问题的吧？
不知道是不是因为转化模型没有使用最终生成的final的原因呢？  因为训练太久我自己中断的然后选了一个自动保存的模型参数导出的

**Comment by sjtubinlong** [comment]
@AlmostNoMemory 没问题，主要你确认下freeze_model目录下是否有这个文件

**Comment by AlmostNoMemory** [comment]
> @AlmostNoMemory 没问题，主要你确认下freeze_model目录下是否有这个文件。
> 
> 还有一点请确认下是否搞错了相对路径，大致应该是：
> 
> ```shell
> ./demo --conf=freeze_model/deploy.yaml --input_dir=...
> ```
> 
> 这样的相对结构，即当前路径应该跟freeze_model同一级.

已经解决了 谢谢您
还想请问下 为什么预测出来的recover结果和原始尺寸不一样？  xy调换了一下  
还有这个预测出来的标签结果是在哪里可以看出来呢？

**Comment by sjtubinlong** [comment]
@AlmostNoMemory 对于图片 x.jpeg 会有一个预测结果 x_jpeg.png，这个图片的二进制内容实际是每个像素的分类。
