### ISSUE TITLE
关于seg中loss.py的问题

### ISSUE THREAD

**Issue by lxk767363331** [PaddlePaddle/PaddleSeg#310]
在seg中设置动态权重中有这样一段代码，weight / fluid.layers.reduce_sum(weight)已经得到各个比例的权重了，，不理解为什么要*num_classes，望解答 谢谢

https://github.com/PaddlePaddle/PaddleSeg/blob/4bc70d817d5fb448ee26db39bd3e321b13c08052/pdseg/loss.py#L61

weight = weight / fluid.layers.reduce_sum(weight) * num_classes

**Comment by wuyefeilin** [comment]
正常情况下使用交叉熵，每个类别的系数都是1，系数和为num_class, 因此为了保证权重的和等于num_classes进行了*num_class操作。比如两个类比像素数是1:3， 则weight = weight / fluid.layers.reduce_sum(weight) * num_classes  = [3/4， 1/4] * 2 = [3/2. 1/2].
