### ISSUE TITLE
RTFORMER模型只有20M，但是在CPU上推理很慢，比DEEPLABV3 200M的模型还慢。

### ISSUE THREAD

**Issue by darrenlei123** [PaddlePaddle/PaddleSeg#3103]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

RTFORMER模型只有20M，但是在CPU上推理很慢，比DEEPLABV3 200M的模型还慢。请问是否正常？

**Comment by Sunting78** [comment]
正常RTFORMER提出了GPU-Friendly Attention，cpu上可能比CNN速度慢
