### ISSUE TITLE
在损失函数中的OHEM_CE是否出现了一些错误

### ISSUE THREAD

**Issue by zz1105292191** [PaddlePaddle/PaddleSeg#3105]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

                index = prob.argsort()
                threshold_index = index[min(len(index), self.min_kept) - 1]
                threshold_index = int(threshold_index.numpy()[0])
                if prob[threshold_index] > self.thresh:
                    threshold = prob[threshold_index]

在这段代码中，argsort返回了各值对应的索引，但是他并不是有序的，第10000个数字并不是第10000小的数，是否需要对prob先进行升序排列

**Comment by Sunting78** [comment]
argsort()返回是的prob排序后的索引值，是有序的，prob从小到大的顺序对应的索引值

**Comment by zz1105292191** [comment]
收到

**Comment by zz1105292191** [comment]
但是我看prob本身并不是有序的，这是过程中我得到的一组prob的值
Tensor(shape=[1048576], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [0.05906019, 0.05906019, 0.05575364, ..., 0.04331113, 0.04402706,
        0.04402706])

**Comment by Sunting78** [comment]
prob本身不是有序的， prob.argsort()是prob排序后的索引值，你可以理解为.argsort()这个函数里面先把prob排序了，然后返回了排序后prob的索引值。

**Comment by zz1105292191** [comment]
收到
