### ISSUE TITLE
cascade nnunet在第二阶段fullres训练的时候报mmap length is greater than file size的错误

### ISSUE THREAD

**Issue by jjkVictor** [PaddlePaddle/PaddleSeg#3106]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

cascade nnunet在第二阶段fullres训练的时候报mmap length is greater than file size的错误
且该错误在训练正常开始若干轮后出现
![image](https://user-images.githubusercontent.com/95264235/228143879-dd5484de-4877-4878-bd6c-6a9910c04298.png)

**Comment by shiyutang** [comment]
这是部分数据解压错误导致，需要删除nnUNet_preprocessed文件夹下的npy文件，并重新跑一次预处理

**Comment by jjkVictor** [comment]
只用删除pred_next_stage下的npy文件并重新跑一次lowres验证激活fullres的预处理我这么理解是对的嘛

**Comment by jjkVictor** [comment]
感谢 问题已解决
