### ISSUE TITLE
但是我看prob本身并不是有序的，这是过程中我得到的一组prob的值

### ISSUE THREAD

**Issue by zz1105292191** [PaddlePaddle/PaddleSeg#3112]
但是我看prob本身并不是有序的，这是过程中我得到的一组prob的值
Tensor(shape=[1048576], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [0.05906019, 0.05906019, 0.05575364, ..., 0.04331113, 0.04402706,
        0.04402706])

_Originally posted by @zz1105292191 in https://github.com/PaddlePaddle/PaddleSeg/issues/3105#issuecomment-1486292608_

**Comment by shiyutang** [comment]
你好，并不是prob有序，而是按照返回的索引排列，prob就会变成默认升序排列，可以参考API文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/argsort_cn.html#argsort

**Comment by zz1105292191** [comment]
收到
