### ISSUE TITLE
这个模型可以做通用物品抠图吗

### ISSUE THREAD

**Issue by Aimee-Lin** [PaddlePaddle/PaddleSeg#3113]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

这个模型可以做通用物品抠图吗

**Comment by shiyutang** [comment]
请问这个模型是哪个模型呢？

**Comment by Stinky-Tofu** [comment]
模型通不通用取决于数据 @Aimee-Lin
