### ISSUE TITLE
[RTFormer - Not support dynamic batch_size] Grouped 2d convolution inside ExternalAttention

### ISSUE THREAD

**Issue by VietAnhNguyen20** [PaddlePaddle/PaddleSeg#3115]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Dear authors,
The RTFormers has an outstanding performance and precision on lots of semantic segmentation problems and I'm using this model for a few custom dataset. The training curve, and statistics from vdlerecords are all promising. However, I encouter a problem with the phase of exporting to inference model. Briefly, with tools/export.py, this model coudn't be exported with a dynamic batch size ( -1 3 1024 1024) or a dynamic height width ( 1 3 -1 -1). With all the static axes (e.g. 1 3 1024 1024 as input_shape), the model has no problems regarding exporting to inference models.

**Have I searched for this problem? :**
- Yes, I've read every single issues regarding RTFormer on PaddleSeg and Paddle2Onnx. However, this issue hasn't been raised!
- The static input_size (1x3x1024x1024) works like a charm, the problems lies in dynamic batch_size or dynamic height/width

**Suppose we have:**
- Configuration file: customized_RTFormer.yml
- Params of the best model: inference_model/model.pdiparams
 I export the model with the following command: 

> CUDA_VISIBLE_DEVICES=2 python tools/export.py --config custom_configs/textline_RTFormer.yml --model_path output/best_model/model.pdparams --save_dir output/inference_model --input_shape -1 3 1024 1024

**And I get the bugs regarding the Grouped 2d convolution inside ExternalAttention:** 

> W0330 07:43:48.010555 45977 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.8, Runtime API Version: 11.7
> W0330 07:43:48.060210 45977 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
> 2023-03-30 07:43:52 [INFO]      Loading pretrained model from /home/nvietanh/PaddleSeg/pretrained/model.pdparams
> 2023-03-30 07:43:52 [WARNING]   [SKIP] Shape of pretrained params seghead.conv2.weight doesn't match.(Pretrained: [150, 256, 1, 1], Actual: [2, 256, 1, 1])
> 2023-03-30 07:43:52 [WARNING]   [SKIP] Shape of pretrained params seghead.conv2.bias doesn't match.(Pretrained: [150], Actual: [2])
> 2023-03-30 07:43:52 [WARNING]   [SKIP] Shape of pretrained params seghead_extra.conv2.weight doesn't match.(Pretrained: [150, 128, 1, 1], Actual: [2, 128, 1, 1])
> 2023-03-30 07:43:52 [WARNING]   [SKIP] Shape of pretrained params seghead_extra.conv2.bias doesn't match.(Pretrained: [150], Actual: [2])
> 2023-03-30 07:43:52 [INFO]      There are 257/261 variables loaded into RTFormer.
> 2023-03-30 07:43:52 [INFO]      Loaded trained params of model successfully.
> Traceback (most recent call last):

    File "tools/export.py", line 68, in forward
        outs = self.net(x)
    File "/home/nvietanh/PaddleSeg/paddleseg/models/rtformer.py", line 188, in forward
        x4_, x4 = self.layer4(
    File "/home/nvietanh/PaddleSeg/paddleseg/models/rtformer.py", line 562, in forward
        if not self.use_cross_kv:
    File "/home/nvietanh/PaddleSeg/paddleseg/models/rtformer.py", line 572, in forward
        x_h = x_h + self.drop_path(self.attn_h(x_h, cross_k,
    File "/home/nvietanh/PaddleSeg/paddleseg/models/rtformer.py", line 399, in forward
        if not self.use_cross_kv:
    File "/home/nvietanh/PaddleSeg/paddleseg/models/rtformer.py", line 417, in forward
            B)
        x = x.reshape([1, -1, 0, 0])  # n,c_in,h,w -> 1,n*c_in,h,w
        x = F.conv2d(
        ~~~~~~~~~~~~~ <--- HERE
            x, cross_k, bias=None, stride=1, padding=0,
            groups=B)  # 1,n*c_in,h,w -> 1,n*144,h,w  (group=B)

    File "/home/nvietanh/paddle/lib/python3.8/site-packages/paddle/nn/functional/conv.py", line 696, in conv2d
        raise ValueError(

    ValueError: The channel dimension of the input((1, -1, 128, 128)) should be defined. Received: -1.


After debugging the code, I find out that because we use the batch_size inside Grouped 2d convolution, which makes the model unable to be invariant to batch_size: 
```
x = x.reshape([1, -1, 0, 0])  # n,c_in,h,w -> 1,n*c_in,h,w
x = F.conv2d(x, cross_k, bias=None, stride=1, padding=0, groups=B)  # 1,n*c_in,h,w -> 1,n*144,h,w  (group=B)
x = self._act_sn(x)
x = F.conv2d(x, cross_v, bias=None, stride=1, padding=0,groups=B)  # 1,n*144,h,w -> 1, n*c_in,h,w  (group=B)
x = x.reshape([-1, self.in_channels, 0, 0])  # 1, n*c_in,h,w -> n,c_in,h,w  (c_in = c_out)
```





**More information to be taken into consideration :**

_- When I changed to static input_size with the following command, everything works like a charm. Thank to this, I could eliminate the possibilities that my model is having other problems. If static input_size like following (1 3 1024 1024), all the steps has no problems, I export to onnx easily with the guidelines from PaddleSeg (thanks for the clear documentation)._

> CUDA_VISIBLE_DEVICES=2 python tools/export.py --config custom_configs/textline_RTFormer.yml --model_path output/best_model/model.pdparams --save_dir output/inference_model --input_shape 1 3 1024 1024

_- If I fix the batch size, and let the dynamic height and width, I still have errors:_

> CUDA_VISIBLE_DEVICES=2 python tools/export.py --config custom_configs/textline_RTFormer.yml --model_path output/best_model/model.pdparams --save_dir output/inference_model --input_shape 1 3 -1 -1

Error: 

ValueError: In transformed code:

    File "tools/export.py", line 68, in forward
        outs = self.net(x)
    File "/home/nvietanh/PaddleSeg/paddleseg/models/rtformer.py", line 188, in forward
        x4_, x4 = self.layer4(
    File "/home/nvietanh/PaddleSeg/paddleseg/models/rtformer.py", line 562, in forward
        if not self.use_cross_kv:
    File "/home/nvietanh/PaddleSeg/paddleseg/models/rtformer.py", line 572, in forward
        x_h = x_h + self.drop_path(self.attn_h(x_h, cross_k,
    File "/home/nvietanh/PaddleSeg/paddleseg/models/rtformer.py", line 399, in forward
        if not self.use_cross_kv:
    File "/home/nvietanh/PaddleSeg/paddleseg/models/rtformer.py", line 417, in forward
            B)
        x = x.reshape([1, -1, 0, 0])  # n,c_in,h,w -> 1,n*c_in,h,w
        x = F.conv2d(
        ~~~~~~~~~~~~~ <--- HERE
            x, cross_k, bias=None, stride=1, padding=0,
            groups=B)  # 1,n*c_in,h,w -> 1,n*144,h,w  (group=B)

    File "/home/nvietanh/paddle/lib/python3.8/site-packages/paddle/nn/functional/conv.py", line 696, in conv2d
        raise ValueError(

    ValueError: The channel dimension of the input((1, -1, -1, -1)) should be defined. Received: -1.



**_I hope that you could support:_**

- [ ] - Enable dynamic batch_size for RTFormer when exporting to inference model (since I need it to be converted to onnx format)
- [ ] - OR support dynamic height/width since the performance of RTFormer is incredibly fast.

Dear authors, I hope I could receive the responses soon! If you need any additional information, please let me know!

**Comment by Bobholamovic** [comment]
Thanks for your interest in RTFormer. 

Unfortunately, RTFormer models do **NOT** support exporting with variable batch size or variable height/width. We are currently having some technical issues with inferring tensor shapes in these cases. Specifically, RTFormer adopts dynamic convolutions (as in [here](https://github.com/PaddlePaddle/PaddleSeg/blob/c19815f5a42034fa9dd41a47cf820102c1078e5d/paddleseg/models/rtformer.py#L400) and [here](https://github.com/PaddlePaddle/PaddleSeg/blob/c19815f5a42034fa9dd41a47cf820102c1078e5d/paddleseg/models/rtformer.py#L417)), which break the normal shape deduction rules. I have added an `enhancement` label to this issue, and we will work on it. However, I guess we won't be able to fix this problem until the PaddlePaddle framework is upgraded to enhance its shape deduction capabilities with dynamic convolutions. :pensive:

**Comment by VietAnhNguyen20** [comment]
Dear Bobholamovic,
Thanks for your quick supports. I would really appreciate that! I hope that RTFormer could be updated soon with the dynamic batch size or dynamic height/width (of course, with the changes coming from PaddlePaddle framework). 
Again, thank you, I will try finding other models!
