### ISSUE TITLE
使用prepare_msd报错list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by z5406** [PaddlePaddle/PaddleSeg#3116]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

代码：
%cd ~/PaddleSeg/contrib/MedicalSeg/
!python tools/prepare_msd.py 11

报错：
/home/aistudio/PaddleSeg/contrib/MedicalSeg
Preparing task 11 Task11_AMOS
raw_dataset_dir data/Task11_AMOS/Task11_AMOS_raw/ exists, skipping uncompress. To uncompress again, remove this directory
Dataset json exists, skipping. Delete file data/Task11_AMOS/Task11_AMOS_raw/dataset.json to regenerate.
Start convert images to numpy array using CPU, please wait patiently
preprocessing the images:   0%|                         | 0/160 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "tools/prepare_msd.py", line 179, in <module>
    prep.load_save()
  File "/home/aistudio/PaddleSeg/contrib/MedicalSeg/tools/prepare.py", line 236, in load_save
    ".")[0]]["spacing"] if i == 0 else None
TypeError: list indices must be integers or slices, not str

已严格按照实例存放数据，望解答！

**Comment by shiyutang** [comment]
根据报错提示可以看出dataset json生成的结果不正确，即不能通过```dataset_json_dict["training"][osp.basename(f).split(".")[0]]["spacing"] ```找到对应数据，建议打开目前生成的dataset_json_dict 查看dataset_json_dict["training"][osp.basename(f).split(".")[0]] 中存放的内容是什么。正确结构应当如下图所示，建议删除dataset.json 并重新生成解决。
<img width="682" alt="image" src="https://user-images.githubusercontent.com/34859558/228837876-d4d4b35e-633d-45f2-8f2c-bda69d115fb3.png">
