### ISSUE TITLE
在基于pplite单机多卡训练时，僵死，GPU使用率100%

### ISSUE THREAD

**Issue by chenxi0011** [PaddlePaddle/PaddleSeg#3117]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

在基于pplite模型**容器里，单机多卡**训练的时候，出现僵死现象(既不报错，也不退出)
首先：单卡测试跑通 GPU= 0 、GPU =1...
在启动训练命令后：`python3 -m paddle.distributed.launch --gpus="0,1" train.py --config configs/pp_liteseg/pp_liteseg_stdc2_t1024_512.yml --do_eval --use_vdl --save_interval 500`

```python，代码改动说明
代码有部分改动，但是单卡能跑通。
```

```shell
启动训练命令后，卡在这个地方(不报错，不往下打印日志)
![B$_FC WRFDCS)`80_1DIO V](https://user-images.githubusercontent.com/128033430/229002213-881f9a66-58f2-4561-9e5a-3519a03bb357.png)

查看显卡使用情况：发现显存占用不高，但是使用率满了
![GRD{ SPY77LHL03~Q}WT9}D](https://user-images.githubusercontent.com/128033430/229002089-66346b9d-6eda-4ae4-b6e9-b1fb96a92f5c.png)
# 排查
1 分别单卡启动，可以正常往下打印训练日志，不报错
2 查阅资料，多卡训练 GUP通信通过共享内存，所以在做容器的时候加入
--network=host --shm-size=10g
问题并没解决。
```

### 复现环境 Environment

- OS: Linux
- PaddlePaddle: 2.3.0
- PaddleSeg: release/2.4
- Python: 3.7.0
- CUDA: 11.2
- CUDNN: 8.1
- GCC: 8.2.0
- 显卡：A100 

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by juncaipeng** [comment]
建议尝试原版代码是否可以跑通，定位是配置问题或者是改动代码的问题。

**Comment by chenxi0011** [comment]
单卡跑通，同样的代码，在别的机器上，多卡跑通

--------------原始邮件--------------
发件人："Ccc ***@***.***&gt;;
发送时间：2023年3月31日(星期五) 上午10:38
收件人："PaddlePaddle/PaddleSeg" ***@***.***&gt;;
抄送："陈熙 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [PaddlePaddle/PaddleSeg] 在基于pplite单机多卡训练时，僵死，GPU使用率100% (Issue #3117)
-----------------------------------

 

 
建议尝试原版代码是否可以跑通，定位是配置问题或者是改动代码的问题。

**Comment by juncaipeng** [comment]
那大概率是docker环境配置的问题

**Comment by chenxi0011** [comment]
您是指的是？
docker内部我这边是拉取的镜像


***@***.***
 
发件人： Ccc
发送时间： 2023-03-31 18:35
收件人： PaddlePaddle/PaddleSeg
抄送： chenxi0011; Author
主题： Re: [PaddlePaddle/PaddleSeg] 在基于pplite单机多卡训练时，僵死，GPU使用率100% (Issue #3117)
那大概率是docker环境配置的问题

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
