### ISSUE TITLE
paddle.utils.run_check()无问题，加载模型成功，使用Positive Point进行标注程序无响应然后闪退

### ISSUE THREAD

**Issue by Xantastic** [PaddlePaddle/PaddleSeg#3119]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

①按照插件安装说明进行操作均无问题包括：进行paddle.utils.run_check()无问题，load model显示gpu加载成功，但最后进行分割程序无响应，20秒左右程序就自动关闭，不同电脑均试验
<img width="1254" alt="屏幕截图 2023-03-31 142000" src="https://user-images.githubusercontent.com/87003407/229039969-a0ad3dfe-ed14-4fa6-927b-1ffedb99b1cc.png">

### 复现环境 Environment

- WIndows: 11
- CUDA: 11.6（相应cuNN）
- Python: 3.9
- PaddleSeg: 2.7
- Paddle: 2.4

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by shiyutang** [comment]
建议打开windows任务管理器查看是否有显存超出问题，详细情况可以截图回复，建议显存在12G左右。

**Comment by Xantastic** [comment]
> 建议打开windows任务管理器查看是否有显存超出问题，详细情况可以截图回复，建议显存在12G左右。

这个算显存超出嘛 那个3D那一块好像有到100%
<img width="746" alt="屏幕截图 2023-04-03 114654" src="https://user-images.githubusercontent.com/87003407/229407468-b943b4cd-ed3d-4e56-99ca-118a9c8ed518.png">
但是那好像是之前加载模型的时候达到了100%，后面我点了标注，就一直为0%了
<img width="1161" alt="屏幕截图 2023-04-03 114007" src="https://user-images.githubusercontent.com/87003407/229408680-3d971126-f878-4f94-8bf8-9ff1cf85cb13.png">

**Comment by shiyutang** [comment]
建议持续观察，在闪退的最后一刻截图看资源是否存在耗尽问题。
