### ISSUE TITLE
关于车道线检测数据集

### ISSUE THREAD

**Issue by xmy0916** [PaddlePaddle/PaddleSeg#312]
https://aistudio.baidu.com/aistudio/projectdetail/226710这个官方paddleseg项目的车道线检测训练数据集可以提供一下嘛~有详细的训练项目的地址就更好了，这个连接的项目里就直接用训练好的__model__ __params__了，不是很懂怎么训练的，想学习一下，谢谢各位开发小哥哥！

**Comment by xmy0916** [comment]
https://aistudio.baidu.com/aistudio/projectdetail/226710


链接地址，抱歉把文本加到了超链接里面~

**Comment by wuyefeilin** [comment]
https://github.com/PaddlePaddle/PaddleSeg/tree/release/v0.5.0/contrib/LaneNet， 里面提供了数据集的下载脚本

**Comment by xmy0916** [comment]
@wuyefeilin 感谢，我看到了
