### ISSUE TITLE
推理测速时尺寸不匹配

### ISSUE THREAD

**Issue by universelyh** [PaddlePaddle/PaddleSeg#3120]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

(paddle23) root@fca7834e87ae:/Workspace/PaddleSeg-develop# python deploy/python/infer_benchmark.py --config output/model-export/0speed-camvid/rtformer-slim-960/deploy.yaml --image_path data/camvid/images/0001TP_006690.png
/root/anaconda3/envs/paddle23/lib/python3.8/site-packages/sklearn/utils/multiclass.py:14: DeprecationWarning: Please use `spmatrix` from the `scipy.sparse` namespace, the `scipy.sparse.base` namespace is deprecated.
  from scipy.sparse.base import spmatrix
2023-04-02 15:58:23 [INFO]	Use GPU
2023-04-02 15:58:24 [INFO]	input shape:(1, 3, 960, 480)
2023-04-02 15:58:24 [INFO]	Warmup
2023-04-02 15:58:25 [INFO]	Infer
2023-04-02 15:58:26 [INFO]	Average time: 6.962 ms/img
![image](https://user-images.githubusercontent.com/113585843/229340823-ba2ff1d3-c2f2-47b9-8778-55d7a83ee500.png)

这是的shape是(1, 3, 960, 480)，
但是我导出的文件：output/model-export/0speed-camvid/rtformer-slim-960/deploy.yaml
![image](https://user-images.githubusercontent.com/113585843/229340890-796793dd-0398-483b-85d3-178a89760902.png)
图片的尺寸却设置的是（960，720）
我尝试过直接编辑deploy.yaml中transform的尺寸，
推理时候的输出shape最大尺寸的【1，1/2】
请问这是什么问题，
我要如何测试尺寸（960，720）图片的速度呢？

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
