### ISSUE TITLE
请问EdgeFlow的模型实现开源了吗？

### ISSUE THREAD

**Issue by wuxianshen** [PaddlePaddle/PaddleSeg#3125]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

EISeg 2.3的release看到了HRNet_OCRNet的交互分割模型实现，但是没有看到EdgeFlow的模型实现；
请问“EdgeFlow: Achieving Practical Interactive Segmentation with Edge-Guided Flow”文章里EdgeFlow的实现开源了吗？
谢谢！

**Comment by Sunting78** [comment]
没有
