### ISSUE TITLE
EIseg propagation not working?

### ISSUE THREAD

**Issue by ZakryDat** [PaddlePaddle/PaddleSeg#3127]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

I am running the cpu version of paddleseg and using eiseg to annotate & segment short clips. The segmentation model appears to work well and I can label objects no problem.

When I load the propagation model and click propagate however, the progress bar takes some time to complete, but then the mask is not propagated. The mask still only exists in the frame I annotated.

Any ideas what is going wrong?

**Comment by geoyee** [comment]
@ZakryDat could you describe it in detail? if possible, maybe have a video showing how you do it, thank you 😄
