### ISSUE TITLE
关于LaneSeg自定义数据集

### ISSUE THREAD

**Issue by Ryzquo** [PaddlePaddle/PaddleSeg#3128]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问应该怎么制作 PaddleSeg/contrib/LaneSeg 这个项目能够使用的自定义数据集

**Comment by Bobholamovic** [comment]
你好，目前LaneSeg项目尚不支持自定义格式的数据集。如果需要使用自定义数据，请将格式调整为与tusimple数据集类似，可参考[此文档](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/contrib/LaneSeg/README_CN.md#%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87)和[此文件](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/contrib/LaneSeg/datasets/tusimple.py)。

**Comment by Ryzquo** [comment]
> 你好，目前LaneSeg项目尚不支持自定义格式的数据集。如果需要使用自定义数据，请将格式调整为与tusimple数据集类似，可参考[此文档](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/contrib/LaneSeg/README_CN.md#%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87)和[此文件](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/contrib/LaneSeg/datasets/tusimple.py)。

好的，谢谢你
