### ISSUE TITLE
关于nnunet 静态模型部署

### ISSUE THREAD

**Issue by huangguoqing** [PaddlePaddle/PaddleSeg#3129]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

hello，我想问下推理导出的静态图文件有尝试使用C++部署预测吗，可以支持吗？目前看到的示例是Paddle Inference下 deploy/cpp/src的test_seg.cpp, 如果对于要使用C++部署是不是流程上需要在test_seg.cpp下把nnunet的数据预处理模块写成C++的加进来就可以了？

**Comment by shiyutang** [comment]
你好，我们暂时没有尝试进行nnUNet的C++部署，可以尝试使用paddleseg下的c++部署案例进行对应。
