### ISSUE TITLE
infer.py中PIL转opencv不显示

### ISSUE THREAD

**Issue by xmy0916** [PaddlePaddle/PaddleSeg#313]
我把infer.py里面预测结果保存的代码做了点修改想用opencv显示，修改如下：
```python
        # 预测结果保存
        result_path = os.path.join(cfg.vis_dir, im_name + '.png')
        output_im = PILImage.fromarray(np.asarray(parsing, dtype=np.uint8))
        output_im.putpalette(palette)
        output_im.show()
        img = cv2.cvtColor(np.asarray(output_im), cv2.COLOR_RGB2BGR) # PIL转cv
        cv2.imshow("cvPicture",img)
        cv2.waitKey(0)
        output_im.save(result_path)
```

我将最后要写入本地的PIL图片转成了opencv的mat图片，但是imshow出来是一片黑的，请问您知道为什么嘛，需要怎么修改呢？显示结果如下：

![image](https://user-images.githubusercontent.com/43675899/87240224-2c6a2800-c44a-11ea-9c8b-55f3cb3c34ea.png)

**Comment by wuyefeilin** [comment]
你可以打开图片读取一下，是否有预测数值。网络输出的预测结果是0，1，2..., 你如果要可视化，可以通过乘以一个系数再保存，就不会一片黑了。

**Comment by xmy0916** [comment]
@wuyefeilin 感谢，我乘了255它终于能看见了
