### ISSUE TITLE
deeplabv3p的推理模型和训练模型结果不一致

### ISSUE THREAD

**Issue by Tomhardy13** [PaddlePaddle/PaddleSeg#3135]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

paddlepaddle 2.3.2
python 3.6
直接使用configs/quick_start/deeplabv3p_resnet50_os8_optic_disc_512x512_1k_teacher.yml进行训练的，训练的数据集是来自工程paddleX的表计读数数据集。
训练完成后，直接采用python tools/predict.py的结果(训练模型的推理)和先python tools/export.py导出预测模型再python deploy/python/infer.py的结果(推理模型的推理)不一致。

**Comment by Tomhardy13** [comment]
![crop_img](https://user-images.githubusercontent.com/41933588/230594360-14b811fb-be6f-400e-98e5-7fadbd1548d3.png)
![crop_img](https://user-images.githubusercontent.com/41933588/230594408-0d04e9e7-2784-4c69-8923-1f4a999f3b6e.png)
上面那张图时训练模型的推理结果，下面的则是推理模型的推理结果

**Comment by Tomhardy13** [comment]
另外还想问下推理模型推理的时候
```
I0410 10:08:21.474902 32582 naive_executor.cc:102] ---  skip [feed], feed -> x
I0410 10:08:21.477406 32582 naive_executor.cc:102] ---  skip [argmax_0.tmp_0], fetch -> fetch
```
是什么意思？因为部署到其他平台出现了
```
var is not a tensor! fetch
var is not a tensor! feed
```

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
