### ISSUE TITLE
 在用STDCseg模型训练时，GPU利用率不足，出现了数据等待的情况

### ISSUE THREAD

**Issue by Jasonx0123** [PaddlePaddle/PaddleSeg#3136]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

用的多卡模型训练，配置是双卡3090，num_workers设置为了8，但是发现显卡利用率不足，总是有数据等待的情况，还需要设置别的参数吗？

**Comment by Stinky-Tofu** [comment]
num_workers加大试试 @Jasonshao0123

**Comment by FB-wh** [comment]
请问怎么解决的？
