### ISSUE TITLE
MedicalSeg中nnunet在predict_next_stage时的代码小优化

### ISSUE THREAD

**Issue by Szc-coder** [PaddlePaddle/PaddleSeg#3139]
### 问题描述 Please describe your issue

你好，在使用nnunet的过程中发现一个可优化的点：在cascade_utils.py中的predict_next_stage函数内，是先加载了数据再进行是否已经推理过的路径判断，导致时间的浪费，建议修改一下。
https://github.com/PaddlePaddle/PaddleSeg/blob/a178d72855053881db628a232b742b2234f1f1f4/contrib/MedicalSeg/nnunet/utils/cascade_utils.py#L108

**Comment by shiyutang** [comment]
你好，欢迎给我们提交修改的PR。
