### ISSUE TITLE
关于ICNET网络结构的正确性问题

### ISSUE THREAD

**Issue by lxk767363331** [PaddlePaddle/PaddleSeg#314]
请问ICNET是完全按照论文中的进行的么，原图中1/16,1/8的预测结果都有加入到下一次CCF中，1/4的预测也没有看到存在位置。另一个问题是，1/4的预测结果是由1/16/1/8的预测结果再次上采样得到的的么 ？ 在代码中没有体现

**Comment by LielinJiang** [comment]
是和原论文一样的。你说的问题可以仔细看下这里的代码：https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.5.0/pdseg/models/modeling/icnet.py#L132-L148
