### ISSUE TITLE
MedicalSeg实现对BraTs2020基准的分割

### ISSUE THREAD

**Issue by DianaNerualNetwork** [PaddlePaddle/PaddleSeg#3140]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，请问在MedicalSeg中如何训练BraTs2020基准数据集？现在的MedicalSeg的处理方式似乎只能处理一个模态？大部分对于BraTs数据集的处理方式似乎是四个模态叠加到一起在再做处理。是否已经实现了相关功能，亦或是我需要自己写一个prepare_data的处理方式？

**Comment by shiyutang** [comment]
你好，目前MedicalSeg暂时不支持叠加四个模态，可以写一个叠加模态的函数增加到现有prepare文件中。

**Comment by jaceqin** [comment]
> ### 问题确认 Search before asking
> * [x]  我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.
> 
> ### 请提出你的问题 Please ask your question
> 您好，请问在MedicalSeg中如何训练BraTs2020基准数据集？现在的MedicalSeg的处理方式似乎只能处理一个模态？大部分对于BraTs数据集的处理方式似乎是四个模态叠加到一起在再做处理。是否已经实现了相关功能，亦或是我需要自己写一个prepare_data的处理方式？

请问你后面解决了吗

**Comment by DianaNerualNetwork** [comment]
您好，我已收到您的来信，谢谢。
