### ISSUE TITLE
label.txt文件怎么生成呢

### ISSUE THREAD

**Issue by loxoo6** [PaddlePaddle/PaddleSeg#3141]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![J ZL7AB7{~J9%R8KUXYXYUX](https://user-images.githubusercontent.com/119844692/230828954-37649599-ebfc-4d10-9b83-8ddbf96f8db0.png)

**Comment by Sunting78** [comment]
如果使用的数据type是Dataset，那么不需要label_list.txt  其他文件，如train_list.txt中每一行是图像和标注图像的路径 即可。如果不是上述的情况，可以将你的运行命令和config等贴全，谢谢～

**Comment by loxoo6** [comment]
我的数据type是dataset，请教您一个问题，像图中这样生成的class
iou，我如何知道[0.9704,0.2728,0.8668]分别对应哪一个类别呢？（我的标注的标签是：1geng，2guo）[image:
a789dba451b31704e42f94c8cbf9b66.png]

Sunflower7788 ***@***.***> 于2023年4月11日周二 19:17写道：

**Comment by Sunting78** [comment]
class iou的顺序是0 1 2...标签训练时对应的类别
