### ISSUE TITLE
是否考虑在EIseg中添加对Segment Anything模型的支持🤔

### ISSUE THREAD

**Issue by luosifenq1q** [PaddlePaddle/PaddleSeg#3142]
如果能把SAM与交互式分割标注方法相结合，效果肯定会很棒！

**Comment by Sunting78** [comment]
请关注即将发布的PaddleSeg v2.8新版本，将支持SAM。后续结合交互分割等工作，敬请期待。

**Comment by CalvinSMU** [comment]
现在的PaddleSeg v2.8可以把SAM模型加载到EIseg里吗

**Comment by shiyutang** [comment]
目前以及以后暂时不会支持，但是SAM推理代码已经放出，可以尝试自行加入。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
