### ISSUE TITLE
对于非0/1mask的二值数据集训练bug

### ISSUE THREAD

**Issue by DianaNerualNetwork** [PaddlePaddle/PaddleSeg#3145]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

1.首先对于RandomCrop这个算子，会偶发性将mask中置为全0
2.PaddleSeg是否未对 二值分布为 [0,2-255]这类的做处理？他们在训练过程中logger打印的类别miou一直是0/1类别的，如果是 0/20二值化mask的数据集，打印的logger和计算的miou将为错误的

**Comment by Sunting78** [comment]
1. 可能由于图像较大背景较大，crop到的全是背景区域
2. 请将输入的GT数据的数值转为连续整型，0，1，2...
若仍有问题，请具体贴训练命令，数据形式，代码，环境等信息，谢谢～

**Comment by DianaNerualNetwork** [comment]
您好，我已收到您的来信，谢谢。
