### ISSUE TITLE
关于人像分割的训练数据

### ISSUE THREAD

**Issue by Fight-hawk** [PaddlePaddle/PaddleSeg#316]
最近在做人像分割相关工作，目前的模型主要存在两个问题：
1.手被识别为背景
2.椅子靠背会被识别为前景
使用的数据集均为开源数据集，所以想请问一下，你们的训练数据集是开源的吗？关于以上两个问题，通过数据增强的方式能解决吗

**Comment by wuyefeilin** [comment]
我们的数据集是不开源的。当数据量较少的时候，进行数据增强是能有效提升分割效果的，你也可以尝试组合不同的数据增强方式

**Comment by Fight-hawk** [comment]
好的 非常感谢指导
