### ISSUE TITLE
class iou有一类永远为0，这是为什么呢？

### ISSUE THREAD

**Issue by loxoo6** [PaddlePaddle/PaddleSeg#3167]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

将loss 设为一个的时候，输出的class iou 有一类永远为0，为什么呢？
我做的是三分类（包括背景），loss应该设置两个吗？
![ebe8fabc11ba24d9316cf0e3da8dfbf](https://user-images.githubusercontent.com/119844692/231366264-36878256-5363-4869-8d28-f3d31a21e86b.png)
![3ce0158bd32f6b6076ce87c8d20df45](https://user-images.githubusercontent.com/119844692/231366273-06d81206-0601-4a8e-9f7a-7d809beb686e.png)

**Comment by shiyutang** [comment]
请问第二类是背景类别么？ 还是什么类别呢？可以将背景类设置为255不加入损失的计算中。这个结果和损失的个数没有关系。

**Comment by loxoo6** [comment]
> 
第二类我猜是1geng类别，但是我不确定。
我标记数据的时候的标签是1geng，2guo；请问怎么看这三类分别对应什么类别呢

**Comment by shiyutang** [comment]
可以看图像和标签的对应。打开一个图像和对应的标签，看标签1和2对应什么
