### ISSUE TITLE
动态图问题

### ISSUE THREAD

**Issue by luuuyi** [PaddlePaddle/PaddleSeg#317]
你好，请问下动态图repo和静态图的repo都是保持同步更新的么。

**Comment by wuyefeilin** [comment]
动态图目前正处于开发阶段，目前发版的还是静态图。等动态图发版以后将会以动态图为主，持续进行更新，到时将不会对静态图进行跟新。

**Comment by luuuyi** [comment]
@wuyefeilin 好的 期待 大概的时间安排有了么

**Comment by wuyefeilin** [comment]
我们目前正全力往动态图上迁移，会随着paddle2.0的发布尽快的发版。敬请期待哈

**Comment by luuuyi** [comment]
@wuyefeilin 了解，谢谢
