### ISSUE TITLE
Could not load library libcublasLt.so.12, 我的是libcublasLt.so.11

### ISSUE THREAD

**Issue by alantseone** [PaddlePaddle/PaddleSeg#3171]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

【编译命令】sh tests/install/check_predict.sh
【系统平台】: Linux x64(Ubuntu 22.04)
【硬件】： Nvidia GPU 4080， CUDA 11.7 cuDNN 8.8.
【编译语言】：Python(3.10）
Please NOTE: device: 0, GPU Compute Capability: 8.9, Driver API Version: 12.0, Runtime API Version: 11.7
我是driver 12.0 ，但我是跑11.7 cuda

彈出錯誤: Could not load library libcublasLt.so.12. Error: libcublasLt.so.12: cannot open shared object file: No such file or directory
我查過11.7 底下只有libcublasLt.so.11的文件，要怎麼才能把他要求的12版本換到11裡?

我沒辦法安裝cuda12因為飛樂也只支援到11.7，有其他方法可以改善嗎?

**Comment by Bobholamovic** [comment]
你好，使用CUDA driver version为12而runtime version为11.7是没有问题的，CUDA runtime version只需小于等于driver version即可。

对于错误：
> Could not load library libcublasLt.so.12. Error: libcublasLt.so.12: cannot open shared object file: No such file or directory

可能的原因是，cudatoolkit 11.7未正常安装或者无法被程序识别。请确认环境变量是否已正确配置，尤其注意机器上是否存在多个版本cudatoolkit共存的情况。

**Comment by alantseone** [comment]
> 你好，使用CUDA driver version为12而runtime version为11.7是没有问题的，CUDA runtime version只需小于等于driver version即可。
> 
> 对于错误：
> 
> > Could not load library libcublasLt.so.12. Error: libcublasLt.so.12: cannot open shared object file: No such file or directory
> 
> 可能的原因是，cudatoolkit 11.7未正常安装或者无法被程序识别。请确认环境变量是否已正确配置，尤其注意机器上是否存在多个版本cudatoolkit共存的情况。

我輸入nvcc -V 能正常顯示 我正使用cudatoolkit 11.7 
我輸入nvidia-smi 也正常顯示 我正使用driver的版本為 12
环境变量應該是沒問題，是飛樂可能在安裝時抓到我的12版本，
在cuda-11.7/targets/x86_64-linux/底下不可能有libcublasLt.so.12，只會有libcublasLt.so.11
還是我能改變飛樂抓取我libcublasLt.so.12 這個參數呢?

**Comment by Bobholamovic** [comment]
除了编译器NVCC，在编译/构建过程中一般还会涉及一些一些运行时库，例如`libcublasLt.so.12`等。为此，请确保cudatoolkit 11.7存放so共享库文件的路径能够被`LD_LIBRARY_PATH`环境变量检索到（NVCC是一个可执行文件，一般在`bin`目录中，通过`PATH`环境变量检索到，这一点和共享库不同）。

**Comment by alantseone** [comment]
你說的沒有錯，但在cudatoolkit 11.7存放so共享库文件LD_LIBRARY_PATH讀到的會是libcublasLt.so.11 ，但他需求是libcublasLt.so.12， 我有嘗試過別人做的

export LD_LIBRARY_PATH=/path/to/cuda-11.5/targets/x86_64-linux/lib/:${LD_LIBRARY_PATH} 后再执行
注意使用绝对路径


但我仍然是無法抓libcublasLt.so.12，在/cuda-11.5/targets/x86_64-linux/lib/裡也只有libcublasLt.so.11
請問我該如何做，謝謝你

**Comment by Bobholamovic** [comment]
抱歉，我想先前我可能误解你的意思了……请问你在本地安装的PaddlePaddle版本是哪一个呀？

**Comment by alantseone** [comment]
沒關係，我也更新一下我的問題是我沒辦法安裝cuda12 因為飛樂只支援到11.7，而4080只能裝cuda12的driver版本，導致現在飛樂好像是根據我drive的cuda版本來抓libcublasLt.so.12這個檔案，該如何把他修改成libcublasLt.so.11的版本

我是安裝這個指令 python -m pip install paddlepaddle-gpu==2.4.2.post117 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
最後也有成功安裝的提示。

但最後我要跑sh tests/install/check_predict.sh 就出現剛才提到的抓不到libcublasLt.so.12的檔案

**Comment by Bobholamovic** [comment]
我认为这个安装方式应该没问题，但看起来目前安装的`paddlepaddle-gpu`的`2.4.2.post117`这个版本依赖于CUDA 12的动态库，这是违反直觉的（理论上应该依赖cuda runtime而不是cuda driver？）。考虑到这是一个paddlepaddle框架安装问题，暂时还没有涉及到paddleseg库的层面，我建议可以移步[Paddle框架issue区](https://github.com/PaddlePaddle/Paddle/issues)提问，那里会有更专业的同学提供解答~

**Comment by alantseone** [comment]
謝謝你，我過去那邊請教一下其他同學。

**Comment by Ghy1209** [comment]
> 謝謝你，我過去那邊請教一下其他同學。

请问解决了吗，我也遇到同样问题

**Comment by Ghy1209** [comment]
> 我认为这个安装方式应该没问题，但看起来目前安装的`paddlepaddle-gpu`的`2.4.2.post117`这个版本依赖于CUDA 12的动态库，这是违反直觉的（理论上应该依赖cuda runtime而不是cuda driver？）。考虑到这是一个paddlepaddle框架安装问题，暂时还没有涉及到paddleseg库的层面，我建议可以移步[Paddle框架issue区](https://github.com/PaddlePaddle/Paddle/issues)提问，那里会有更专业的同学提供解答~

请问解决了吗，我也遇到同样的问题

**Comment by shiyutang** [comment]
你好，可以前往[Paddle框架issue区](https://github.com/PaddlePaddle/Paddle/issues)提问。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
