### ISSUE TITLE
segment anything train 

### ISSUE THREAD

**Issue by fujianhai** [PaddlePaddle/PaddleSeg#3175]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包含open与closed)，没有类似需求。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar feature requests.

### 需求描述 Feature Description

请问有复现segment anything train code 的打算吗？

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Sunting78** [comment]
暂无定论 规划中
