### ISSUE TITLE
SegmentAnything使用Mask prompt分割时报错

### ISSUE THREAD

**Issue by GitHubTJW** [PaddlePaddle/PaddleSeg#3177]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我在使用contrib/SegmentAnything/script文件夹下的promt_predict分割时，输入一张512*512大小的0和1的二值mask_prompt图像后，报错ValueError: (InvalidArgument) Too many indices (3) for tensor of dimension 2，请问是什么原因呢？

**Comment by Sunting78** [comment]
您好，是mask prompt的bug，由于使用较复杂，更新后mask prompt已经去除。如果想用mask prompt，需要保存上一次分割结果的logits 然后作为mask传入。
