### ISSUE TITLE
你好，关于ElSeg标注工具需求

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleSeg#3179]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包含open与closed)，没有类似需求。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; 2. 需求场景（请描述你的项目中为什么需要用此功能）; 3. 功能描述（请简单描述或设计这个功能）
![image](https://user-images.githubusercontent.com/87969070/231934097-39718b20-730a-43fb-8ae3-5363a93fa2f5.png)
你好，我发现标注工具无法标注这种对比度比较低的划痕，为什么不增加一些手动绘制的功能呢？类似于笔这种 画上去的

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by monkeycc** [comment]
工业检测
确实需要多点标注

现在标注工具和自动标注
只合适轮廓明显的

一个小划痕  
一个小黑点
死活都检测不出来

**Comment by juncaipeng** [comment]
这种场景下，推荐使用paddlelabel标注工具。后续会考虑在EISeg中新增该功能。
