### ISSUE TITLE
是否支持模糊类别。

### ISSUE THREAD

**Issue by hao-qiang** [PaddlePaddle/PaddleSeg#3185]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

PaddleSeg工作人员，
您好，我目前在做的一项分割任务，有些区域难以明确标注为某一类，标注人员将其标为“最可能是某一类”的模糊标签。比如我们有ABC三类，有一个区域标为“可能是B”，我想将模糊标签的one-hot label设置为[0.2, 0.6, 0.2]，请问PaddleSeg是否支持这种label的训练，谢谢。

**Comment by Stinky-Tofu** [comment]
当然支持 @hao-qiang

**Comment by hao-qiang** [comment]
@Stinky-Tofu 很高兴听到这个消息，请问有具体的教程吗？或者我大致应该怎么准备label图片。谢谢。

**Comment by Stinky-Tofu** [comment]
抱歉，没有教程，这个比较简单吧，就把one-hot标签当成概率分布就行啦。 @hao-qiang
