### ISSUE TITLE
PaddleSeg的微信用户群,异常,为空

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSeg#3190]
### 问题描述 Please describe your issue

https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.8/contrib/QualityInspector

![微信图片_20230418090214](https://user-images.githubusercontent.com/6490927/232642407-a3fc18a8-a2c6-4bca-af9f-17285c6ec0d7.jpg)

**Comment by Sunting78** [comment]
https://user-images.githubusercontent.com/30883834/213601179-0813a896-11e1-4514-b612-d145e068ba86.jpeg

可以用这个 我们也会更新下
