### ISSUE TITLE
QualityInspector  建议可以用 FastDeploy 部署

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSeg#3194]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包含open与closed)，没有类似需求。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; 

QualityInspector  建议可以用 FastDeploy 部署推理

2. 需求场景（请描述你的项目中为什么需要用此功能）;
python 打包部署 费劲
端到端要打通

3. 功能描述（请简单描述或设计这个功能）
 FastDeploy 部署推理

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Sunting78** [comment]
收到建议，后面会考虑规划添加部署功能。
