### ISSUE TITLE
EISeg 文档 使用教程 没有超链接

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSeg#3195]
### 文档链接&描述 Document Links & Description

https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.8/EISeg
`
使用教程 * [安装说明](docs/install.md) * [图像分割标注](docs/image.md) * [视频及3D医疗分割标注](docs/video.md) * [遥感分割特色功能](docs/remote_sensing.md) * [医疗分割特色功能](docs/medical.md) * [图像检测标注](docs/det.md) * [数据处理脚本文档](docs/tools.md)`

没有超链接对应的文档

### 请提出你的建议 Please give your suggestion

使用教程

* [安装说明](https://github.com/PaddlePaddle/PaddleSeg/tree/develop/EISeg/docs/install.md)
* [图像分割标注](https://github.com/PaddlePaddle/PaddleSeg/tree/develop/EISeg/docs/image.md) 
* [视频及3D医疗分割标注](https://github.com/PaddlePaddle/PaddleSeg/tree/develop/EISeg/docs/video.md) 
* [遥感分割特色功能](https://github.com/PaddlePaddle/PaddleSeg/tree/develop/EISeg/docs/remote_sensing.md)
* [医疗分割特色功能](https://github.com/PaddlePaddle/PaddleSeg/tree/develop/EISeg/docs/medical.md) 
* [图像检测标注](https://github.com/PaddlePaddle/PaddleSeg/tree/develop/EISeg/docs/det.md) 
* [数据处理脚本文档](https://github.com/PaddlePaddle/PaddleSeg/tree/develop/EISeg/docs/tools.md)

增加对应链接

**Comment by shiyutang** [comment]
文档在对应名字的这个链接下：https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.8/EISeg/docs
也可以查看这个readme：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/EISeg/README.md
