### ISSUE TITLE
FatalError: `Erroneous arithmetic operation` is detected by the operating system.

### ISSUE THREAD

**Issue by largerwxt** [PaddlePaddle/PaddleSeg#3197]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，我在复现ppmatting时，出现一下问题，请问我应该怎么解决呢
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
1   void paddle::imperative::Tracer::TraceOpImpl<paddle::imperative::VarBase>(std::string const&, paddle::imperative::details::NameVarMapTrait<paddle::imperative::VarBase>::Type const&, paddle::imperative::details::NameVarMapTrait<paddle::imperative::VarBase>::Type const&, paddle::framework::AttributeMap&, phi::Place const&, bool, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&, paddle::framework::AttributeMap*, bool)
2   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap const&, paddle::framework::AttributeMap const&)
3   phi::KernelImpl<void (*)(phi::GPUContext const&, phi::DenseTensor const&, paddle::experimental::IntArrayBase<phi::DenseTensor> const&, paddle::experimental::IntArrayBase<phi::DenseTensor> const&, paddle::experimental::IntArrayBase<phi::DenseTensor> const&, std::vector<long, std::allocator<long> > const&, std::vector<long, std::allocator<long> > const&, std::vector<long, std::allocator<long> > const&, std::vector<long, std::allocator<long> > const&, std::vector<paddle::experimental::ScalarBase<phi::DenseTensor>, std::allocator<paddle::experimental::ScalarBase<phi::DenseTensor> > > const&, phi::DenseTensor*), &(void phi::SetValueKernel<float, phi::GPUContext>(phi::GPUContext const&, phi::DenseTensor const&, paddle::experimental::IntArrayBase<phi::DenseTensor> const&, paddle::experimental::IntArrayBase<phi::DenseTensor> const&, paddle::experimental::IntArrayBase<phi::DenseTensor> const&, std::vector<long, std::allocator<long> > const&, std::vector<long, std::allocator<long> > const&, std::vector<long, std::allocator<long> > const&, std::vector<long, std::allocator<long> > const&, std::vector<paddle::experimental::ScalarBase<phi::DenseTensor>, std::allocator<paddle::experimental::ScalarBase<phi::DenseTensor> > > const&, phi::DenseTensor*))>::Compute(phi::KernelContext*)
4   void phi::SetValueKernel<float, phi::GPUContext>(phi::GPUContext const&, phi::DenseTensor const&, paddle::experimental::IntArrayBase<phi::DenseTensor> const&, paddle::experimental::IntArrayBase<phi::DenseTensor> const&, paddle::experimental::IntArrayBase<phi::DenseTensor> const&, std::vector<long, std::allocator<long> > const&, std::vector<long, std::allocator<long> > const&, std::vector<long, std::allocator<long> > const&, std::vector<long, std::allocator<long> > const&, std::vector<paddle::experimental::ScalarBase<phi::DenseTensor>, std::allocator<paddle::experimental::ScalarBase<phi::DenseTensor> > > const&, phi::DenseTensor*)
5   void phi::SetTensorValueKernel<float, phi::GPUContext>(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, paddle::experimental::IntArrayBase<phi::DenseTensor> const&, paddle::experimental::IntArrayBase<phi::DenseTensor> const&, paddle::experimental::IntArrayBase<phi::DenseTensor> const&, std::vector<long, std::allocator<long> > const&, std::vector<long, std::allocator<long> > const&, std::vector<long, std::allocator<long> > const&, phi::DenseTensor*)
6   void phi::SetValueImpl<float, phi::GPUContext, 4ul>(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, paddle::experimental::IntArrayBase<phi::DenseTensor> const&, paddle::experimental::IntArrayBase<phi::DenseTensor> const&, paddle::experimental::IntArrayBase<phi::DenseTensor> const&, std::vector<long, std::allocator<long> > const&, std::vector<long, std::allocator<long> > const&, std::vector<long, std::allocator<long> > const&, phi::DenseTensor*)
7   phi::kps::details::BroadcastConfig::BroadcastConfig(std::vector<long, std::allocator<long> > const&, std::vector<long, std::allocator<long> > const&, int)

----------------------
Error Message Summary:
----------------------
FatalError: `Erroneous arithmetic operation` is detected by the operating system.
  [TimeInfo: *** Aborted at 1681818315 (unix time) try "date -d @1681818315" if you are using GNU date ***]
  [SignalInfo: *** SIGFPE (@0x7efc6a9e4962) received by PID 3628535 (TID 0x7efd6a6e94c0) from PID 1788758370 ***]

Floating point exception (core dumped)

**Comment by shiyutang** [comment]
请问你是运行的什么命令出错的呢？

**Comment by Stinky-Tofu** [comment]
可能是cuda版本的问题，可以参考这个[issue](https://github.com/PaddlePaddle/PaddleOCR/issues/4333) @largerwxt
