### ISSUE TITLE
Regarding matric

### ISSUE THREAD

**Issue by pushpendra9950** [PaddlePaddle/PaddleSeg#3198]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

@ZeyuChen @chliang @QingshuChen @sjtubinlong @louis-she when did you add the F1 score matric.?

**Comment by shiyutang** [comment]
Hello, we already have precision and recall, you can use them to calculate the F1 score. :https://github.com/PaddlePaddle/PaddleSeg/pull/1911/files#diff-35a8845cc2c228fe8a484e6b8773c603696abe77d46a20dfc357fd43f89b38fc
