### ISSUE TITLE
QualityInspector，将全图分割数据转为coco格式的json文件,提示没有mt_catIDs.json

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSeg#3199]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/contrib/QualityInspector/docs/tools_data/prepare_data.md

1.4 将全图分割数据转为coco格式的json文件

`python3 tools/convert_tools/convert_mask_to_coco.py --image_path dataset/MT_dataset/images/train --anno_path dataset/MT_dataset/annos/train --class_num 5 --label_file dataset/MT_dataset/mt_catIDs.json --output_name dataset/MT_dataset/train.json --suffix .png
`

Traceback (most recent call last):
  File "tools/convert_tools/convert_mask_to_coco.py", line 139, in <module>
    convert_mask_to_coco(args)
  File "tools/convert_tools/convert_mask_to_coco.py", line 124, in convert_mask_to_coco
    id_to_label = json.load(open(args.label_file))
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\dataset\\MT_dataset\\mt_catIDs.json'

所有步骤中
都没有这个产生mt_catIDs.json
那么mt_catIDs.json 怎么来的

**Comment by Sunting78** [comment]
[数据转coco参数说明](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/contrib/QualityInspector/docs/tools_data/conver_tools.md#322-%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E)
mt_catIDs.json这个json文件中是一个字典 保存类别id和类别名称的映射，也可以不设置，这样类别id就是类别名

**Comment by monkeycc** [comment]
明白了

1.3 将全图分割数据转为RoI分割文件
`python3 tools/convert_tools/convert_mask_to_RoI.py --image_path dataset/MT_dataset/images/train --anno_path dataset/MT_dataset/annos/train --class_num 5 --output_path dataset/MT_dataset/RoI/ --suffix .png --to_binary
`

建议这里增加一个 --label_file

因为到
1.4 将全图分割数据转为coco格式的json文件
示例代码中  就要调用这个 --label_file

以后可能会让其他人重复问这个问题
