### ISSUE TITLE
用RetinaNet训练自己的数据集报错求助

### ISSUE THREAD

**Issue by zwf1234** [PaddlePaddle/PaddleSeg#320]
各位RD同学、老师，我用RetinaNet训练自己的数据集运行时出现以下问题，麻烦帮忙看一下，非常感谢！
（我将retinanet_r101_fpn_1x.yml中的数据集的路径换成了自己的数据集的路径）
InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [-1, 256, 100, 167] and the shape of Y = [-1, 256, 100, 168]. Received [167] in X is not equal to [168] in Y at i:3.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] at (/paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:157)
  [operator < elementwise_add > error]

**Comment by nepeplwu** [comment]
你好，你用的是PaddleDetection训练检测模型吗？如果是的话，请将相关问题提到PaddleDetection的[**issue**](https://github.com/PaddlePaddle/PaddleDetection/issues)中
