### ISSUE TITLE
adamw unexpected keyword argument 'momentum'

### ISSUE THREAD

**Issue by DeepForget** [PaddlePaddle/PaddleSeg#3200]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

使用adamw 时会报错 TypeError: __init__() got an unexpected keyword argument 'momentum'

### 复现环境 Environment

paddlepaddle==2.4.2

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by shiyutang** [comment]
你好，adamw的参数如[API文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/AdamW_cn.html#adamw)所示，其中没有momentum的参数，因此会报错，需要去除momentum传入，并根据你的需要和参数说明传入相应的参数。
