### ISSUE TITLE
EIseg 数据类型转化为paddlex 报错

### ISSUE THREAD

**Issue by maxuserc** [PaddlePaddle/PaddleSeg#3201]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

![image](https://user-images.githubusercontent.com/91525677/233040127-94a55476-d5f7-4139-a8d3-aabde5047182.png)

我用EIseg 标注完标签文件里就不存在autosave_label.txt文件
### 复现环境 Environment

-OS  windows
-paddlepaddle-gpu 2.4.2
-paddleseg 2.8

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by smalie2222** [comment]
我也遇到了这个问题，请问您解决了吗

**Comment by chinesejunzai12** [comment]
同上问题, 有人给回答么

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
