### ISSUE TITLE
C++ Traceback (most recent call last): -------------------------------------- 0   paddle::pybind::ThrowExceptionToPython(std::__exception_ptr::exception_ptr)

### ISSUE THREAD

**Issue by largerwxt** [PaddlePaddle/PaddleSeg#3202]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

C++ Traceback (most recent call last):
--------------------------------------
0   paddle::pybind::ThrowExceptionToPython(std::__exception_ptr::exception_ptr)

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1681910254 (unix time) try "date -d @1681910254" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800060af7) received by PID 396023 (TID 0x7fcfed7c0740) from PID 396023 ***]

Aborted (core dumped)

**Comment by largerwxt** [comment]
我想问一下这个问题怎么解决

**Comment by shiyutang** [comment]
你好，请问你在运行什么命令时出现这个问题呢？

**Comment by Bobholamovic** [comment]
建议首先检查一下程序的显存用量，在显存超限的情况下也可能会出现这个错误

**Comment by Deardongfl** [comment]
你好，请问这个问题解决了吗？我也遇到了这个问题

**Comment by largerwxt** [comment]
> 你好，请问这个问题解决了吗？我也遇到了这个问题

我的原因的GPU内存没有释放，内存不足导致

**Comment by IbrarBabar009** [comment]
facing same issue,
I might think it is not the memory issue,
I am just testing 1 image on GPU and facing this issue.

anyone facing the same problem?
