### ISSUE TITLE
masked prediction to polygonal points

### ISSUE THREAD

**Issue by nitinsharanarthi** [PaddlePaddle/PaddleSeg#3204]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hello,

i have segmentation mask output images, how do i convert these to polygonal points json or txt? will the model output the points too?

**Comment by Bobholamovic** [comment]
To extract polygons from a binary mask, you can use OpenCV. Here is an [official tutorial](https://docs.opencv.org/4.x/d4/d73/tutorial_py_contours_begin.html). For multi-class masks, you may need to convert them to binary masks first by assigning foreground pixels with 1 and the background pixels with 0. After extracting the polygonal points, the Python standard library `json` can be used to dump the points. Alternatively, use `open` and `file.write` to dump the points to a text file. It is a bit tricky if you want to convert the mask to some standard format, say, the COCO format. For this, I would recommend searching for open-source solutions on GitHub.

Currently, all models of PaddleSeg take an RGB image as input and output a mask. However, it is convenient to convert the masks to polygonal points using the method presented above.
