### ISSUE TITLE
Training with TIFF images

### ISSUE THREAD

**Issue by gmommi** [PaddlePaddle/PaddleSeg#3210]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hello, is it possible to train a model on custom dataset containing .tif images? They are aerial images for building footprint segmentation. Thank you!

**Comment by juncaipeng** [comment]
Yes, PaddleSeg is able to read tiff images for model training. For details, please refer to: https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/paddleseg/transforms/transforms.py#L63

**Comment by gmommi** [comment]
Thank you, but when I try to make prediction on a tiff image I get this error:
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1249: character maps to <undefined>.

**Comment by juncaipeng** [comment]
Do you means run tools/predict.py ?

**Comment by gmommi** [comment]
yes!

**Comment by gmommi** [comment]
Any news?? :)

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
