### ISSUE TITLE
关于nnunet的类别的问题

### ISSUE THREAD

**Issue by iyangiii** [PaddlePaddle/PaddleSeg#3211]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用nnuent进行对医疗图像进行分割 我能否查看每个器官类别对应的ID？

**Comment by shiyutang** [comment]
输出的预测结果中，即可看到预测结果的标签，和标注数据对应一致。

**Comment by iyangiiiii** [comment]
就是运行可视化软件 看一下结果 根据左下角的label判断吗 比如label1对应的类别id就是1？
![image](https://user-images.githubusercontent.com/101607550/233572858-75fb3be2-9183-4aa5-887d-6ed89c8a97ff.png)

**Comment by iyangiii** [comment]
> 输出的预测结果中，即可看到预测结果的标签，和标注数据对应一致。

就是运行可视化软件 看一下结果 根据左下角的label判断吗 比如label1对应的类别id就是1？
![image](https://user-images.githubusercontent.com/101607550/233573087-1a531812-908d-4e48-85e6-478cf80eb2ad.png)

**Comment by iyangiii** [comment]
还有就是请问 nnunet能不能不用交叉验证 直接进行正常的训练呢？ 如果可以应该对哪里进行修改呢？

**Comment by huangguoqing** [comment]
> 还有就是请问 nnunet能不能不用交叉验证 直接进行正常的训练呢？ 如果可以应该对哪里进行修改呢？

这个你找到修改了吗？
