### ISSUE TITLE
请问FD部署是否只能输出list型

### ISSUE THREAD

**Issue by kkpssr** [PaddlePaddle/PaddleSeg#3212]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

对于切割来说，尽管使用tensorrt加速了模型，但是np.array(list)实在太太太慢了，一张3000x2000得图，我resize后，模型运行才10ms，但np.array用了70ms

**Comment by juncaipeng** [comment]
关于FD部署，请具体到FD repo提issue，谢谢。
https://github.com/PaddlePaddle/FastDeploy
