### ISSUE TITLE
运行tools下的train.py报错

### ISSUE THREAD

**Issue by WaperGit** [PaddlePaddle/PaddleSeg#3213]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

终端输入 python tools/train.py 会提示 ModuleNotFoundError:No module named ‘paddleseg‘，
但将train.py复制到上级目录”PaddleSeg-2.8.0“下，终端输入python train.py就没有问题，之前2.7版本也会这样

### 复现环境 Environment

windows 
python 3.8.16
paddlepaddle-gpu 11.2
PaddleSeg-2.8.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by juncaipeng** [comment]
需要参考文档安装paddleseg,  pip install -e .

**Comment by WaperGit** [comment]
> 需要参考文档安装paddleseg, pip install -e .

谢谢回复，按源码安装就行了
2.2.1 源码安装PaddleSeg
pip install -v -e .
2.2.2 安装发布的PaddleSeg
pip install paddleseg
