### ISSUE TITLE
我在执行predict.py时，遇到了module 'paddleseg' has no attribute 'optimizers'的错误

### ISSUE THREAD

**Issue by izhaolinger** [PaddlePaddle/PaddleSeg#3214]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我的操作系统为  Mac OS13.2
Python版本为3.6.13
paddlepaddle版本为2.4.2  CPU
我安装了/PaddleSeg/Matting下的requirements.txt

我执行的命令是：
python tools/predict.py --config configs/ppmatting/ppmatting-hrnet_w18-human_512.yml --model_path ppmatting-hrnet_w18-human_512.pdparams --image_path a.jpg --save_dir ./output/result --fg_estimate True --device cpu

遇到了以下的错误：
Traceback (most recent call last):
  File "tools/predict.py", line 20, in <module>
    import paddleseg
  File "/opt/anaconda3/envs/pad/lib/python3.6/site-packages/paddleseg/__init__.py", line 15, in <module>
    from . import models, datasets, transforms, optimizers
  File "/opt/anaconda3/envs/pad/lib/python3.6/site-packages/paddleseg/optimizers/__init__.py", line 14, in <module>
    from .optimizer import *
  File "/opt/anaconda3/envs/pad/lib/python3.6/site-packages/paddleseg/optimizers/optimizer.py", line 19, in <module>
    import paddleseg.optimizers.custom_optimizers as custom_opt
AttributeError: module 'paddleseg' has no attribute 'optimizers'

请问是什么原因呢？

**Comment by dingqizhou** [comment]
请问解决了吗？我也遇到同样的问题

**Comment by izhaolinger** [comment]
> 请问解决了吗？我也遇到同样的问题

并没有解决，我是用intel芯片的mac上出现的该问题，后来转为使用windows后就没遇到过这个问题了。

**Comment by LeeBinshan** [comment]
我也遇到了相同的问题，请问有大神给个解决思路吗？

**Comment by LeeBinshan** [comment]
把我paddleseg环境下的'miniconda3/envs/paddle/lib/python3.6/site-packages/paddleseg/optimizers/optimizer.py'中的
‘import paddleseg.optimizers.custom_optimizers as custom_opt’
改为
‘from paddleseg.optimizers import custom_optimizers as custom_opt'
后可成功运行

**Comment by kakashiz** [comment]
> 把我paddleseg环境下的'miniconda3/envs/paddle/lib/python3.6/site-packages/paddleseg/optimizers/optimizer.py'中的 ‘import paddleseg.optimizers.custom_optimizers as custom_opt’ 改为 ‘from paddleseg.optimizers import custom_optimizers as custom_opt' 后可成功运行
使用"pip install - v - e."命令安装PaddleSeg时，会报"AttributeError: module 'paddleseg' has no attribute 'optimizers'"错误，按照上述修改可以正常运行。但是为什么"import"不行"from import"可以？

**Comment by kakashiz** [comment]
> 把我paddleseg环境下的'miniconda3/envs/paddle/lib/python3.6/site-packages/paddleseg/optimizers/optimizer.py'中的 ‘import paddleseg.optimizers.custom_optimizers as custom_opt’ 改为 ‘from paddleseg.optimizers import custom_optimizers as custom_opt' 后可成功运行

**Comment by kakashiz** [comment]
> 把我paddleseg环境下的'miniconda3/envs/paddle/lib/python3.6/site-packages/paddleseg/optimizers/optimizer.py'中的 ‘import paddleseg.optimizers.custom_optimizers as custom_opt’ 改为 ‘from paddleseg.optimizers import custom_optimizers as custom_opt' 后可成功运行

使用"pip install - v - e."命令安装PaddleSeg时，会报"AttributeError: module 'paddleseg' has no attribute 'optimizers'"错误，按照上述修改可以正常运行。但是为什么"import"不行"from import"可以？
