### ISSUE TITLE
python: relocation error: /usr/local/cuda-11.1/lib64/libcublas.so: symbol runGemmShortApi, version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference

### ISSUE THREAD

**Issue by largerwxt** [PaddlePaddle/PaddleSeg#3215]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我在运行tools/train时出现了以下错误，请问我该如何解决
(python: relocation error: /usr/local/cuda-11.1/lib64/libcublas.so: symbol runGemmShortApi, version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference)

**Comment by juncaipeng** [comment]
你这个是cuda环境安装的报错，可能是重复安装了CUDA toolKit。
具体可以参考：https://stackoverflow.com/questions/74394695/how-does-one-fix-when-torch-cant-find-cuda-error-version-libcublaslt-so-11-no

**Comment by dewishyi** [comment]
请问您这边的问题解决了吗，我遇到了相同的问题
