### ISSUE TITLE
Inference on pp_liteseg

### ISSUE THREAD

**Issue by MaxEAB** [PaddlePaddle/PaddleSeg#3216]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hi, I was trying to run the inference on cityscape demo image following the instructions [here](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/docs/deployment/inference/python_inference.md).

When I run the following, I get the image pasted below. Could anyone let me know why this is happening? I am running this on Windows.

```
python deploy/python/infer.py \
    --config ./pp_liteseg_infer_model/deploy.yaml \
    --image_path ./cityscapes_demo.png
```

![cityscapes_demo](https://user-images.githubusercontent.com/103768359/233694191-8f00cd75-dd2a-4b00-89c1-b0f327e3b163.png)

**Comment by juncaipeng** [comment]
It seems to me that there might be a problem in the PaddleInference library. You can reinstall it and try again.

**Comment by MaxEAB** [comment]
I did the installation based on this: https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/docs/install.md

Is there a separate installation for PaddleInference ?

**Comment by MaxEAB** [comment]
I reinstalled, and also tried the following:

`sh tests/install/check_predict.sh`

This gives the following result:

![optic_test_image](https://user-images.githubusercontent.com/103768359/234113140-1f79e03c-1969-4d43-aa53-2712384f68da.png)

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
