### ISSUE TITLE
语义分割类别嵌套，一个小面积类别永远在大面积类别里面，请问这种情况怎么处理呢？

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleSeg#3217]
### 问题描述 Please describe your issue

语义分割类别嵌套，一个小面积类别永远在大面积类别里面，请问这种情况怎么处理呢？是按正常流程走，还是有什么特殊的处理

**Comment by marshall-dteach** [comment]
&emsp;&emsp;我觉着可以按照正常流程走，从原理来讲所有图像都是一个$L^2(R)$空间中的一个点，这也意味着一个完整的图像都被无穷个0像素包围着。
&emsp;$emsp;在实际CV任务中对于大部分图片，某一类都是在背景类中的，最直观的就是医学影像分割；当然也可以利用新方法，可以考虑从探究边界特性入手。

**Comment by marshall-dteach** [comment]
我觉着可以按照正常流程走，从原理来讲所有图像都是一个$L^2(R)$空间中的一个点，这也意味着一个完整的图像都被无穷个0像素包围着。
 &emsp;在实际CV任务中对于大部分图片，某一类都是在背景类中的，最直观的就是医学影像分割；当然也可以利用新方法，可以考虑从探究边界特性入手。

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：https://github.com/PaddlePaddle/PaddleOCR/issues/10223
