### ISSUE TITLE
EISeg PaddleX 语义分割数据集构建,不清楚

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSeg#3219]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/EISeg/docs/tools.md
```

python eiseg2paddlex.py -d save_folder_path -o image_folder_path [-l label_folder_path] [-m mode -s split_rate]
其中:

save_folder_path: 为需要保存PaddleX数据的路径，必填。
image_folder_path: 为图像的路径，必填。
label_folder_path: 为标签的路径，非必填，若不填则为自动保存的位置（image_folder_path/label）。
mode：数据集的类型，非必填，默认为“seg”，若是目标检测数据集则可使用“det”。
split_rate: 训练集和验证集划分的比例，非必填，若不填则为0.9。
```

我的数据集结构

D:/AAA
里面是图像
并且 label 也有
D:/AAA/label 

用转换命令
python eiseg2paddlex.py -d D:/BBB -o image_folder_path D:/AAA
提示报错 
eiseg2paddlex.py: error: unrecognized arguments: D:/AAA
改为
python eiseg2paddlex.py -d D:/BBB -o image_folder_path D:/AAA/label 
一样报错

请给出转换命令的示例

**Comment by shiyutang** [comment]
试下这样呢：python eiseg2paddlex.py -d D:/BBB -o D:/AAA
