### ISSUE TITLE
EISeg 标注好的 , 怎么转换为训练数据集

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSeg#3220]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

比如我有200张图片

只标注了80张

怎么一键转换？

**Comment by shiyutang** [comment]
你好，你是说你之前用之前的标注软件，想要转换格式，只标注剩下的120张数据吗？

**Comment by monkeycc** [comment]
不

是我只标注了 80 张

然后想用这80张 进行转换训练数据集

**Comment by shiyutang** [comment]
标注好的数据格式是什么样的呢？ 可以对应将标签转化成png的图片即可，类别值从0-N
