### ISSUE TITLE
使用eiseg时，为什么点击图像边缘，分割结果为什么是整张图呢

### ISSUE THREAD

**Issue by Dohbby** [PaddlePaddle/PaddleSeg#3222]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

点击分割图像内部可以得到一个很好的分割结果，得到的是指定的图像部分，但是当点击图像的边缘轮廓部分得到的分割结果效果不好，得到的是上传的整张图，而不是指定的图像部分，想请问这是什么原因造成的呢

**Comment by shiyutang** [comment]
交互式分割训练的时候，根据用户习惯设置了先验信息，会模拟点击在中心附近的效果，因此模型更加适应点击在物体中间而不是边缘。
