### ISSUE TITLE
EISeg标签显示和修改

### ISSUE THREAD

**Issue by hurri2000** [PaddlePaddle/PaddleSeg#3223]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包含open与closed)，没有类似需求。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标：工业检测，分割数据集标注
2. 需求场景：标签标完以后，我想检查标签有没有标正确，在图片上好像不能显示已经标好的标签，这张图片有没有标也不知道
3. 功能描述：希望能显示标签，并提供修改

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Harryoung** [comment]
请问你是指在 EISeg 软件里面检查还是直接在文件夹里查看图片来检查呢？如果是在 EISeg 软件里面的话，是有不同的掩码颜色可以区分标注类别的，且均支持二次编辑。如下图所示
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/30883834/234779632-356177b1-d783-4d7f-b1d3-2b5bd2b0f165.png">

在本地的话，可以查看伪彩色图，不同的类别使用不同的颜色标识，如下图所示
![image](https://user-images.githubusercontent.com/30883834/234779709-15a6bd13-f45a-4aa3-9c20-4b4757e3f1ff.png)

**Comment by hurri2000** [comment]
谢谢，今天再用的时候没这个问题了，前面两天用都有这个问题。就是标注完成，点上一张，上一张的标注结果不显示，也无法修改。重新打开文件夹，标注结果也看不到。但是结果是保存了的，label文件夹里面能看到结果。当时还录了视频在微信群里面咨询了的。看了您的回答今天再用就正常了，可能是之前环境没有装好。谢谢！

**Comment by Harryoung** [comment]
好的，客气了
