### ISSUE TITLE
安装依赖包报错

### ISSUE THREAD

**Issue by tanshuai555** [PaddlePaddle/PaddleSeg#3225]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/48782961/233961066-e72d270e-eb53-4c35-8b49-a7594926e1ac.png)

**Comment by Stinky-Tofu** [comment]
这种环境问题建议自己查一下 @tanshuai555
