### ISSUE TITLE
运行upernet_vit报错了

### ISSUE THREAD

**Issue by loxoo6** [PaddlePaddle/PaddleSeg#3228]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

![56bc602e4490f823efd70947e235c37](https://user-images.githubusercontent.com/119844692/234159209-39324783-f510-4296-8ea4-5cded603e696.png)

### 复现环境 Environment

paddlepaddle:2.4.0
paddleseg:2.8

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Sunting78** [comment]
请补充下运行命令

**Comment by shiyutang** [comment]
ms_deform_attn是外部新增算子，需要额外安装，请按照提示下载压缩包并安装ms_deform_attn算子。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
