### ISSUE TITLE
使用 modnet-mobilenetv2 模型，图像分割效果远离预期

### ISSUE THREAD

**Issue by mayqiyue** [PaddlePaddle/PaddleSeg#3229]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我用的是官方提供的训练好的模型modnet-mobilenetv2.pdparams，使用的release/2.8分支的demo中human.jpg图片；使用bg_replace.py文件进行图片背景替换；但是输出的结果是并没有对人像进行分割；更像是把一个绿色直接盖在了原图片上；下图为结果图；是我是什么弄错了吗
![human](https://user-images.githubusercontent.com/6397015/234166016-70194fde-4200-42fd-835a-ab503cca0932.jpg)

**Comment by Sunting78** [comment]
请给出具体执行命令 环境等

**Comment by mayqiyue** [comment]
环境：
mac os 13.2.1
M1 芯片
Python 3.9.12
Paddle hub 2.3.1

指令

    model = hub.Module(name='deeplabv3p_xception65_humanseg')
    model.segmentation(paths=files, visualization=True, use_gpu=True,
                       output_dir=outputDir)

**Comment by shiyutang** [comment]
看上去是使用的PaddleHub，请按照[humanseg](https://github.com/PaddlePaddle/PaddleSeg/blob/release%2F2.9/contrib/PP-HumanSeg/README_cn.md)中的文档进行尝试，也可以使用[Matting算法](https://github.com/PaddlePaddle/PaddleSeg/blob/release%2F2.9/Matting/README_CN.md)。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
