### ISSUE TITLE
readme有点问题

### ISSUE THREAD

**Issue by xmy0916** [PaddlePaddle/PaddleSeg#323]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.5.0/docs/model_export.md

这个readme的最底下的
python pdseg/export_model.py --cfg configs/unet_optic.yaml TEST.TEST_MODEL ./saved_model/unet_optic/final

这个命令在pdseg/export_model.py这个地方的“/”左右加了空格，执行命令会报错：
/opt/conda/envs/python35-paddle120-env/bin/python: can't find '__main__' module in 'pdseg'

需要把空格删除！

**Comment by nepeplwu** [comment]
@xmy0916 感谢反馈，文档里面并没有多余的空格存在
