### ISSUE TITLE
Error: Can not import paddle core while this file exists: /home/amt/work/software/anaconda3/envs/Pytorch/lib/python3.6/site-packages/paddle/fluid/libpaddle.so

### ISSUE THREAD

**Issue by LFL19991003** [PaddlePaddle/PaddleSeg#3231]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Error: Can not import paddle core while this file exists: /home/amt/work/software/anaconda3/envs/Pytorch/lib/python3.6/site-packages/paddle/fluid/libpaddle.so
到相应路径下存在这个文件，为什么会打不开？

**Comment by shiyutang** [comment]
参考：https://github.com/PaddlePaddle/Paddle/issues/52383 可能是GPU的问题，建议确认显卡驱动等安装正确。
