### ISSUE TITLE
nnunet模型问题

### ISSUE THREAD

**Issue by iyangiii** [PaddlePaddle/PaddleSeg#3234]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

nnunet能不能不用交叉验证 直接进行正常的训练呢？ 如果可以应该对哪里进行修改呢？

**Comment by shiyutang** [comment]
关闭训练过程的do_eval 的argument就可以了

**Comment by iyangiii** [comment]
> 关闭训练过程的do_eval 的argument就可以了

我看了一下代码 我把fold改成all 然后训练 看了一下训练集的长度 确实是全部数据 这种方法可以吗

**Comment by iyangiii** [comment]
> > 关闭训练过程的do_eval 的argument就可以了
> 
> 我看了一下代码 我把fold改成all 然后训练 看了一下训练集的长度 确实是全部数据 这种方法可以吗

我也尝试了你们给的方案 发现训练集的len 不是全部数据？

**Comment by shiyutang** [comment]
默认都是五折训练的，每次有20%数据保留用于评估，训练5次的话，所有数据都用到了，也就是你说的fold=all的设置。

**Comment by iyangiii** [comment]
> 默认都是五折训练的，每次有20%数据保留用于评估，训练5次的话，所有数据都用到了，也就是你说的fold=all的设置。

这个我知道 但是我把do_eval相关的内容删掉 发现训练集并不是全部数据？ 然后如果是每个fold都跑然后集成的话 效果应该和直接跑一次全部数据集是不一样的吧 fold=all 是不是直接用全部数据跑一个模型 而且不能验证？
