### ISSUE TITLE
pp_mobileseg pp_liteseg compare

### ISSUE THREAD

**Issue by lh-13** [PaddlePaddle/PaddleSeg#3235]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

pp_mobileseg 与 pp_liteseg 速度与精度对比结果是什么样的？

**Comment by shiyutang** [comment]
这两个模型偏向于不同的设备，分别是移动端和GPU轻量模型，因此我们没有进行相同设备下的速度/精度对比，欢迎自行测试结果并交流。

**Comment by xuxinda** [comment]
> ### 问题确认 Search before asking
> * [x]  我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.
> 
> ### 请提出你的问题 Please ask your question
> pp_mobileseg 与 pp_liteseg 速度与精度对比结果是什么样的？

大佬有没有测过
