### ISSUE TITLE
保存标签列表文件不自动添加后缀名.txt

### ISSUE THREAD

**Issue by hurri2000** [PaddlePaddle/PaddleSeg#3238]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包含open与closed)，没有类似需求。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar feature requests.

### 需求描述 Feature Description

只是个小问题，但是能改进下的话,对用户更友好。
保存标签列表的时候，默认是保存*.txt文件，输入文件名后.txt不会自动添加
按一般用户习惯，比如我们用自带的notepad保存，我想保存为abc.txt只用填一个abc，abc.txt就保存好了。
在EIseg里，填如abc，保存的文件名就是abc，下次打开时由于设置了过滤abc并不会显示，也加载不了。一定要在保存的时候手动填入abc.txt才可以正常保存和加载

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
