### ISSUE TITLE
PaddleSeg demo cpp cant't use different models

### ISSUE THREAD

**Issue by unblock7** [PaddlePaddle/PaddleSeg#3241]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

I compiled PaddleSeg/deploy/cpp/.
ran demo_name.exe -model_dir=pp_liteseg_infer_model -img_path=test.jpg -save_dir=save -devices=CPU
The program was successful.
But when I change the model to [modnet-hrnet_w18](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.8/Matting#Models) or [modnet-resnet50_vd](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.8/Matting#Models) the program doesn't save the result
[log.txt](https://github.com/PaddlePaddle/PaddleSeg/files/11360834/log.txt)

**Comment by Bobholamovic** [comment]
Hi, MODNet is a Matting model (in contrast to a semantic segmentation model), and currently Matting models do not support cpp deployment on a server.
