### ISSUE TITLE
按照官方文档，使用PP-HumanSeg和Matting效果极差

### ISSUE THREAD

**Issue by WS-W** [PaddlePaddle/PaddleSeg#3243]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

`python src/seg_demo.py --config inference_models/portrait_pp_humansegv2_lite_256x144_inference_model_with_softmax/de
ploy.yaml --img_path data/images/portrait_heng.jpg --save_dir data/images_result/portrait_heng_v2.jpg`
按照readme进行了下载模型和数据的操作，使用上述命令用官方模型对官方提供的样例图片进行分割，没有报错，成功保存结果图片，但是结果如下
![portrait_heng_v2](https://user-images.githubusercontent.com/65066631/235355530-3b4fac1f-4a86-4af8-a2be-b1468c9a68ee.jpg)

另外，在使用Matting的时候，将下述语句写为.sh并运行
`export CUDA_VISIBLE_DEVICES=0
python tools/predict.py \
    --config F:/PaddleSeg-release-2.8/Matting/ppmattingv2-stdc1-human_512/deploy.yaml \
    --model_path F:/PaddleSeg-release-2.8/Matting/ppmattingv2-stdc1-human_512/model.pdmodel \
    --image_path demo/human.jpg \
    --save_dir ./output/results \
    --fg_estimate True`
可以运行，但效果极差，如下图所示
![human_rgba](https://user-images.githubusercontent.com/65066631/235355661-6d8ceb4d-6e62-4f89-af6d-45d128eb17af.png)
不知道是什么原因？

**Comment by cvv-student** [comment]
![human_rgba](https://github.com/PaddlePaddle/PaddleSeg/assets/58026988/f2e6e250-70bc-4e7b-a4e4-55781f8f3c5f)
我也一样奇奇怪怪的问题

**Comment by JIANG3330** [comment]
我也是
![human](https://github.com/PaddlePaddle/PaddleSeg/assets/42256557/71777840-4745-45ce-994b-63c3be907062)

**Comment by JIANG3330** [comment]
windows上会出现这个问题，Linux下正常

**Comment by falcomlife** [comment]
我也出现了上面这种情况，最后发现是paddlepaddle版本和此项目版本不对应导致的。起初我的paddlepaddle-gpu是2.5.1版本，该项目我切换到release/2.8.0版本，出现了你上面这种问题。后来我遵从2.8.0的说明文件，降低了paddlepaddle-gpu的版本到2.4.0，该问题就解决了。另附一个2.4.0的安装指令
python -m pip install paddlepaddle-gpu==2.4.0.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

**Comment by aiXia121** [comment]
> windows上会出现这个问题，Linux下正常

linux 一样如上有问题

**Comment by tensor-song** [comment]
官方没人出来解释一下吗

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
