### ISSUE TITLE
安卓demo使用MODNet-HRNet_W18模型的效果与Python效果差很多，是简化了吗？

### ISSUE THREAD

**Issue by astraylinux** [PaddlePaddle/PaddleSeg#3244]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我在python上跑了一些图进行测试，再和安卓demo进行对比，发现python使用MODNet-HRNet_W18模型不只是能分割人像，其他一些主体比较明确的图也能很好的分割。而安卓端使用同一模型人像效果比python要差一些，非人像的几乎不可用，在不考虑运行时间的情况下，能否调出一样的效果，谢谢。

以下是一些例图：
原图：
![image](https://user-images.githubusercontent.com/4121264/235369247-538379b6-9607-4a0f-9596-b4ca3d010ccb.png)
python:
![image](https://user-images.githubusercontent.com/4121264/235369564-9b1fe56e-afb1-4c3f-973f-40d7c9cdb18b.png)
android:
![image](https://user-images.githubusercontent.com/4121264/235369297-b3990c83-0393-4690-ac30-fe71fe3c87c6.png)

原图：
![image](https://user-images.githubusercontent.com/4121264/235369479-6e7416c4-a8f2-41dd-abce-ecd32d89b895.png)
python:
![image](https://user-images.githubusercontent.com/4121264/235369658-e38056f6-3776-4a68-a91d-ca9894d0c261.png)
android:
![image](https://user-images.githubusercontent.com/4121264/235369516-aba59a75-9a9a-4c1a-8065-1de65d650dc3.png)

原图：
![image](https://user-images.githubusercontent.com/4121264/235369316-65ac158c-35b9-4c3e-9670-dda8ab7a8827.png)
python:
![image](https://user-images.githubusercontent.com/4121264/235369603-d0ece685-754d-4ad0-a2ea-1ea136006d30.png)
android:
![image](https://user-images.githubusercontent.com/4121264/235369525-b4fc8882-aecb-4945-97e7-eb2745b1525b.png)

原图：
![image](https://user-images.githubusercontent.com/4121264/235369586-171e5dde-a9c9-47b7-a559-791878bef107.png)
python:
![image](https://user-images.githubusercontent.com/4121264/235369617-b72dec1a-ddab-4e91-9b71-73f8469d34ba.png)
android:
![image](https://user-images.githubusercontent.com/4121264/235369628-b5c93e64-78bf-405e-8cde-a8ef73228b2b.png)

**Comment by Stinky-Tofu** [comment]
部署问题，待排查 @astraylinux
