### ISSUE TITLE
nnunet模型修改

### ISSUE THREAD

**Issue by iyangiii** [PaddlePaddle/PaddleSeg#3245]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

如果想修改nnunet网络的结构应该是在哪个文件进行修改？ 比如将普通卷积改为可变形卷积

**Comment by Bobholamovic** [comment]
你好，在这里可以找到nnUNet的模型定义：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/contrib/MedicalSeg/medicalseg/models/nnunet.py

**Comment by iyangiii** [comment]
> 你好，在这里可以找到nnUNet的模型定义：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/contrib/MedicalSeg/medicalseg/models/nnunet.py

嗯 这个文件我知道 这个模型 不是很懂在哪里修改 能给点思路吗 比如想把最后一层卷积改为可变形卷积

**Comment by Bobholamovic** [comment]
从代码上看，将最后数层改成可变形卷积可以考虑把[此处](https://github.com/PaddlePaddle/PaddleSeg/blob/d596cf7a2a2333bea624f66ac9e528f4daf8706f/contrib/MedicalSeg/medicalseg/models/nnunet.py#L486)的`conv_op`修改为[`DeformConv2D`](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/ops/DeformConv2D_cn.html#deformconv2d)。如果只想要修改最后一层，只需修改`self.seg_heads`的最后一个元素。不过可变形卷积可能需要不止一个输入，为此也需要修改[此处](https://github.com/PaddlePaddle/PaddleSeg/blob/d596cf7a2a2333bea624f66ac9e528f4daf8706f/contrib/MedicalSeg/medicalseg/models/nnunet.py#L532)的调用。

**Comment by iyangiii** [comment]
> 从代码上看，将最后数层改成可变形卷积可以考虑把[此处](https://github.com/PaddlePaddle/PaddleSeg/blob/d596cf7a2a2333bea624f66ac9e528f4daf8706f/contrib/MedicalSeg/medicalseg/models/nnunet.py#L486)的`conv_op`修改为[`DeformConv2D`](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/ops/DeformConv2D_cn.html#deformconv2d)。如果只想要修改最后一层，只需修改`self.seg_heads`的最后一个元素。不过可变形卷积可能需要不止一个输入，为此也需要修改[此处](https://github.com/PaddlePaddle/PaddleSeg/blob/d596cf7a2a2333bea624f66ac9e528f4daf8706f/contrib/MedicalSeg/medicalseg/models/nnunet.py#L532)的调用。

请问这个修改最后一个元素是什么意思呢

**Comment by Bobholamovic** [comment]
> > 从代码上看，将最后数层改成可变形卷积可以考虑把[此处](https://github.com/PaddlePaddle/PaddleSeg/blob/d596cf7a2a2333bea624f66ac9e528f4daf8706f/contrib/MedicalSeg/medicalseg/models/nnunet.py#L486)的`conv_op`修改为[`DeformConv2D`](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/ops/DeformConv2D_cn.html#deformconv2d)。如果只想要修改最后一层，只需修改`self.seg_heads`的最后一个元素。不过可变形卷积可能需要不止一个输入，为此也需要修改[此处](https://github.com/PaddlePaddle/PaddleSeg/blob/d596cf7a2a2333bea624f66ac9e528f4daf8706f/contrib/MedicalSeg/medicalseg/models/nnunet.py#L532)的调用。
> 
> 请问这个修改最后一个元素是什么意思呢

`self.seg_heads`是一个列表，其中有很多个元素（对象），每个元素对应模型中的一层。只修改最后一个元素（`self.seg_heads[-1]`）就是只修改模型的最后一层。

**Comment by iyangiii** [comment]
> > > 从代码上看，将最后数层改成可变形卷积可以考虑把[此处](https://github.com/PaddlePaddle/PaddleSeg/blob/d596cf7a2a2333bea624f66ac9e528f4daf8706f/contrib/MedicalSeg/medicalseg/models/nnunet.py#L486)的`conv_op`修改为[`DeformConv2D`](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/ops/DeformConv2D_cn.html#deformconv2d)。如果只想要修改最后一层，只需修改`self.seg_heads`的最后一个元素。不过可变形卷积可能需要不止一个输入，为此也需要修改[此处](https://github.com/PaddlePaddle/PaddleSeg/blob/d596cf7a2a2333bea624f66ac9e528f4daf8706f/contrib/MedicalSeg/medicalseg/models/nnunet.py#L532)的调用。
> > 
> > 
> > 请问这个修改最后一个元素是什么意思呢
> 
> `self.seg_heads`是一个列表，其中有很多个元素（对象），每个元素对应模型中的一层。只修改最后一个元素（`self.seg_heads[-1]`）就是只修改模型的最后一层。

就是说我需要在这个 self.seg_heads.append 结束后对最后一个元素进行修改吗  然后可变形卷积中的offset和mask是需要自己实现吗

**Comment by Bobholamovic** [comment]
> 就是说我需要在这个 self.seg_heads.append 结束后对最后一个元素进行修改吗

是的，这是一个办法，也可以通过修改循环体部分的逻辑来实现『最后一个元素与列表中其它元素不同』。

> 然后可变形卷积中的offset和mask是需要自己实现吗

这是一个算法层面的问题。如果确定使用可变形卷积，应该在算法设计上考虑如何获取offset，例如通过另一个普通卷积从上一层输入中获取。

**Comment by iyangiiiii** [comment]
> 从代码上看，将最后数层改成可变形卷积可以考虑把[此处](https://github.com/PaddlePaddle/PaddleSeg/blob/d596cf7a2a2333bea624f66ac9e528f4daf8706f/contrib/MedicalSeg/medicalseg/models/nnunet.py#L486)的`conv_op`修改为[`DeformConv2D`](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/ops/DeformConv2D_cn.html#deformconv2d)。如果只想要修改最后一层，只需修改`self.seg_heads`的最后一个元素。不过可变形卷积可能需要不止一个输入，为此也需要修改[此处](https://github.com/PaddlePaddle/PaddleSeg/blob/d596cf7a2a2333bea624f66ac9e528f4daf8706f/contrib/MedicalSeg/medicalseg/models/nnunet.py#L532)的调用。

最后修改此处的调用这个地方 添加了offset  append报错了 应该把offset加在哪里呢

**Comment by iyangiii** [comment]
> > 就是说我需要在这个 self.seg_heads.append 结束后对最后一个元素进行修改吗
> 
> 是的，这是一个办法，也可以通过修改循环体部分的逻辑来实现『最后一个元素与列表中其它元素不同』。
> 
> > 然后可变形卷积中的offset和mask是需要自己实现吗
> 
> 这是一个算法层面的问题。如果确定使用可变形卷积，应该在算法设计上考虑如何获取offset，例如通过另一个普通卷积从上一层输入中获取。

怎么从上一层获取输出定义offset 搞蒙了....

**Comment by Bobholamovic** [comment]
使用什么作为offset或者如何构造offset是一个算法层面的问题，严格来说与本issue无关。在设计模型时，如果希望使用可变形卷积的话，需要制定好相关的策略。

**Comment by iyangiiiii** [comment]
在修改的过程中 我遇到了一个问题 就是我只需要修改最后一层 但是如果修改最后一层的[此处](https://github.com/PaddlePaddle/PaddleSeg/blob/d596cf7a2a2333bea624f66ac9e528f4daf8706f/contrib/MedicalSeg/medicalseg/models/nnunet.py#L532)普通卷积只不需要offset这个参数 可变形卷积又需要  会报错 这个问题能给点解决思路吗

**Comment by iyangiii** [comment]
> 使用什么作为offset或者如何构造offset是一个算法层面的问题，严格来说与本issue无关。在设计模型时，如果希望使用可变形卷积的话，需要制定好相关的策略。

修改过程中 原本的x是一个五维张量 但是[DeformConv2D](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/ops/DeformConv2D_cn.html#deformconv2d)只能接受一个四维张量 就会报错 这个有解决方法吗

**Comment by Bobholamovic** [comment]
> > 使用什么作为offset或者如何构造offset是一个算法层面的问题，严格来说与本issue无关。在设计模型时，如果希望使用可变形卷积的话，需要制定好相关的策略。
> 
> 修改过程中 原本的x是一个五维张量 但是[DeformConv2D](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/ops/DeformConv2D_cn.html#deformconv2d)只能接受一个四维张量 就会报错 这个有解决方法吗

这样的话看起来没有简单的实现了……可能需要自己实现一个DeformConv3D来处理5D输入的情况，可以参考DeformConv2D的实现：https://github.com/PaddlePaddle/Paddle/blob/release/2.4/python/paddle/vision/ops.py#L1093
