### ISSUE TITLE
使用nnUnet训练自己的任务，转换数据集为decathlon格式时报错

### ISSUE THREAD

**Issue by henryccl** [PaddlePaddle/PaddleSeg#3247]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我在使用NNUnet训练自己的任务时出现了错误，具体来说我使用如下命令：

> %cd ~/PaddleSeg/contrib/MedicalSeg/
!python train.py --config ~/configs/nnunet_fold2.yml \
        --log_iters 20 --precision fp16 --nnunet --save_dir output/base/fold2 --save_interval 2000 --use_vdl 

运行后报错：

> /home/aistudio/PaddleSeg/contrib/MedicalSeg/medicalseg/cvlibs/config.py:463: UserWarning: Warning: The data dir now is /home/aistudio/PaddleSeg/contrib/MedicalSeg/data/, you should change the data_root in the global.yml if this directory didn't have enough space
  .format(absolute_data_dir))
data/decathlon not found, convert data to decathlon.
Traceback (most recent call last):
  File "train.py", line 232, in <module>
    main(args)
  File "train.py", line 172, in main
    train_dataset = cfg.train_dataset
  File "/home/aistudio/PaddleSeg/contrib/MedicalSeg/medicalseg/cvlibs/config.py", line 374, in train_dataset
    return self._load_object(_train_dataset)
  File "/home/aistudio/PaddleSeg/contrib/MedicalSeg/medicalseg/cvlibs/config.py", line 437, in _load_object
    return component(**params)
  File "/home/aistudio/PaddleSeg/contrib/MedicalSeg/nnunet/datasets/dataset.py", line 70, in __init__
    self.preprocess_and_generate_plans()
  File "/home/aistudio/PaddleSeg/contrib/MedicalSeg/nnunet/datasets/dataset.py", line 113, in preprocess_and_generate_plans
    self.decathlon_dir, default_num_threads=self.num_threads)
  File "/home/aistudio/PaddleSeg/contrib/MedicalSeg/tools/preprocess_utils/integrity_checks.py", line 243, in verify_dataset_integrity
    default_num_threads=default_num_threads)
  File "/home/aistudio/PaddleSeg/contrib/MedicalSeg/tools/preprocess_utils/integrity_checks.py", line 122, in verify_training_dataset
    expected_label_file)
  File "/home/aistudio/PaddleSeg/contrib/MedicalSeg/tools/preprocess_utils/integrity_checks.py", line 79, in verify_same_geometry_and_shape_and_nonan
    "are coregistered and have the same geometry as the label.".format(image_path, label_path)
AssertionError: The geometry of the image data/decathlon/imagesTr/45301564-771e-45b5-8a55-27f153c56d6f_0000.nii.gz does not match the geometry of the label data/decathlon/labelsTr/45301564-771e-45b5-8a55-27f153c56d6f.nii.gz. The pixel arrays will not be aligned and nnU-Net cannot use this data. Please make sure your image modalities are coregistered and have the same geometry as the label.

**Comment by henryccl** [comment]
检查这两个样本的shape  发现结果是一样的，求解答，求正确的打开方式
> import os
import matplotlib.pyplot as plt
import numpy as np
import SimpleITK as sitk
import cv2 as cv
from collections import Counter
from tqdm import tqdm, trange
volume_f1 = sitk.GetArrayFromImage(sitk.ReadImage("PaddleSeg/contrib/MedicalSeg/data/decathlon/labelsTr/45301564-771e-45b5-8a55-27f153c56d6f.nii.gz"))  # (82, 768, 768)
volume_f2 = sitk.GetArrayFromImage(sitk.ReadImage("PaddleSeg/contrib/MedicalSeg/data/decathlon/imagesTr/45301564-771e-45b5-8a55-27f153c56d6f_0000.nii.gz"))  # (82, 768, 768)
print(volume_f1.shape, volume_f2.shape, "DSADASD")


![image](https://user-images.githubusercontent.com/44051761/236384569-2207e2de-7216-43d1-a71e-ceeae03197f8.png)

**Comment by weihuang-cs** [comment]
在检查MRI文件的信息的时候，不光会检查Shape，同时会对Spacing，Origin等进行检查
以下是核心代码
```python
def verify_same_geometry(img_1: sitk.Image, img_2: sitk.Image):
    ori1, spacing1, direction1, size1 = img_1.GetOrigin(), img_1.GetSpacing(
    ), img_1.GetDirection(), img_1.GetSize()
    ori2, spacing2, direction2, size2 = img_2.GetOrigin(), img_2.GetSpacing(
    ), img_2.GetDirection(), img_2.GetSize()
    return np.all(np.isclose(ori1, ori2)) and np.all(
        np.isclose(spacing1, spacing2)) and np.all(
            np.isclose(direction1, direction2)) and np.all(
                np.isclose(size1, size2))
```
