### ISSUE TITLE
找不到human body parsing 相关教程和模型

### ISSUE THREAD

**Issue by KelvinHong** [PaddlePaddle/PaddleSeg#3248]
### 问题确认 Search before asking

- [x] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我想用PaddleSeg API来做 human body parsing, 我在相关的paper中发现这个用法，很符合我的需求

![image](https://user-images.githubusercontent.com/34021827/236404924-cad0aaf7-ab75-4c5a-9164-8563b7fc312f.png)

我翻找了几个教程，包括这个（face parsing) [不太符合我的需求，需要的是对半身或全身 parsing]
https://aistudio.baidu.com/aistudio/projectdetail/5326422
和这个 (portrait and body segmentation) [很靠近，不过目前只有人-背景分割，并没有如paper内的可以对身体不同部位细分割]
https://aistudio.baidu.com/aistudio/projectdetail/4504982

对于body segmentation, 我尝试run code， 发现Predictor 的 get_output_handle 会return 一个shape (1, 2, 256, 144) 的tensor, 当我把两个部分分别当 masks 作图后，得到黑白两个mask。 以下是原图和得到的两个masks。
![img2](https://user-images.githubusercontent.com/34021827/236405835-a415d7d4-4d23-438e-9ce3-37643bc63e08.png)
![mask1](https://user-images.githubusercontent.com/34021827/236405857-36368ce8-c235-4650-a4b7-dab1ca5ed931.png)
![mask2](https://user-images.githubusercontent.com/34021827/236405874-e86ad7c2-96d8-4272-b394-5bdfb0f48c27.png)
如图，并没有human body parsing 那般的细分。

想请问有什么教程是关于human body parsing 的吗？

**Comment by juncaipeng** [comment]
你需要human body parsing的数据集进行训练，才可以对输入图像进行人体部件分割。

**Comment by KelvinHong** [comment]
好的，那我明白了，感谢解答。
