### ISSUE TITLE
LaneSeg Error

### ISSUE THREAD

**Issue by jonbakerfish** [PaddlePaddle/PaddleSeg#3249]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

运行prediction例子时报错：

```bash
export CUDA_VISIBLE_DEVICES=0
python predict.py \
    --config configs/bisenetV2_tusimple_640x368_300k.yml \
    --model_path output/best_model/model.pdparams \
    --image_path data/test_images/3.jpg \
    --save_dir ./output/results
```

```
W0505 18:14:10.506129 293239 default_variables.cpp:95] Fail to fscanf: Bad file descriptor [9]
Traceback (most recent call last):
  File "/PaddleSeg/contrib/LaneSeg/predict.py", line 110, in <module>
    main(args)
  File "PaddleSeg/contrib/LaneSeg/predict.py", line 81, in main
    val_dataset = cfg.val_dataset
AttributeError: 'Config' object has no attribute 'val_dataset
```

### 复现环境 Environment

- OS: Linux
- Paddle: 2.4.2.post116
- PaddleSeg: 2.8.0
- CUDA: 11.6

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by juncaipeng** [comment]
请参考下面文档安装并执行
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/contrib/LaneSeg/README_CN.md

**Comment by jonbakerfish** [comment]
这个原因是Config无法从yaml文件构建相应的class，除了val_dataset外，model，Transform，train_dataset这些类别都无法构建
