### ISSUE TITLE
C++ 预测报错

### ISSUE THREAD

**Issue by pele228** [PaddlePaddle/PaddleSeg#325]
使用windows的C++预测接口，  显示输入输出不匹配错误，具体报错信息如下
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0730 09:19:23.339763 21596 analysis_predictor.cc:474] ======= optimize end =======
I0730 09:19:23.340760 21596 naive_executor.cc:105] ---  skip [feed], feed -> image
I0730 09:19:23.344750 21596 naive_executor.cc:105] ---  skip [relu_4.tmp_0], fetch -> fetch
W0730 09:19:23.685129 21596 device_context.cc:236] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 11.0, Runtime API Version: 9.0
W0730 09:19:23.694104 21596 device_context.cc:244] device: 0, cuDNN Version: 7.6.
runtime = 18082
size of outputs[0]: (1,1,512,512,)
E0730 09:19:24.683012 21596 seg_predictor.cpp:92]  [FATAL] unequal: input vs output [524288|262144]

使用AIStudio训练的deeplabv3模型， 十几天前训练的模型导出后使用正常，本周的模型导出后报错。

**Comment by wuyefeilin** [comment]
更新到最新版本看一下有没有问题

**Comment by x12901** [comment]
> 使用windows的C++预测接口， 显示输入输出不匹配错误，具体报错信息如下
> e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
> I0730 09:19:23.339763 21596 analysis_predictor.cc:474] ======= optimize end =======
> I0730 09:19:23.340760 21596 naive_executor.cc:105] --- skip [feed], feed -> image
> I0730 09:19:23.344750 21596 naive_executor.cc:105] --- skip [relu_4.tmp_0], fetch -> fetch
> W0730 09:19:23.685129 21596 device_context.cc:236] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 11.0, Runtime API Version: 9.0
> W0730 09:19:23.694104 21596 device_context.cc:244] device: 0, cuDNN Version: 7.6.
> runtime = 18082
> size of outputs[0]: (1,1,512,512,)
> E0730 09:19:24.683012 21596 seg_predictor.cpp:92] [FATAL] unequal: input vs output [524288|262144]
> 
> 使用AIStudio训练的deeplabv3模型， 十几天前训练的模型导出后使用正常，本周的模型导出后报错。

请问楼主怎么解决的?
