### ISSUE TITLE
nnunet转onnx模型

### ISSUE THREAD

**Issue by huangguoqing** [PaddlePaddle/PaddleSeg#3252]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

目前paddle2onnx支持nnunet pdmodel转成onnx模型吗？

**Comment by shiyutang** [comment]
可以使用tools/model/export_onnx.py进行尝试，如果遇到进一步问题可以在本条issue下跟进。
