### ISSUE TITLE
推理显存不够

### ISSUE THREAD

**Issue by huangguoqing** [PaddlePaddle/PaddleSeg#3253]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我使用python加载nnunet模型推理，显存没有报错，但是我用同样的模型用C++来加载推理，显示显存不够

**Comment by Stinky-Tofu** [comment]
@huangguoqing 辛苦贴出具体报错log
