### ISSUE TITLE
SAM 的decoder支持导出为onnx吗？

### ISSUE THREAD

**Issue by SchrodingerLLX** [PaddlePaddle/PaddleSeg#3255]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我想请问下paddle 的segment anything支持将decode部分导出为onnx模型吗？

**Comment by shiyutang** [comment]
目前已经验证可以导出静态图模型+Paddle inference推理，因此可以自行尝试onnx导出，应该没有问题。

**Comment by mrljwlm** [comment]
> 目前已经验证可以导出静态图模型+Paddle inference推理，因此可以自行尝试onnx导出，应该没有问题。

请问SAM静态图如何导出？
