### ISSUE TITLE
EISeg功能

### ISSUE THREAD

**Issue by lueker** [PaddlePaddle/PaddleSeg#3260]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包含open与closed)，没有类似需求。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）
数据标注，包括语义标注和检测标注。
2. 需求场景（请描述你的项目中为什么需要用此功能）
深度学习模型训练
3. 遇到的问题？
(1). 视频分割功能很好用，比检测自动标注准确，但是不能导出json文件，在后面转换检测框时不方便;
(2). 视频分割保存的图片不能直接使用，应该直接保存原图，且要保存为.jpg格式;
(3). 视频分割功能可以极大的提高生产力，应该在后续的优化中重点优化，且要易用，减少视频分割后的后续工作。

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by juncaipeng** [comment]
感谢你的反馈，我们后续会排期优化。
