### ISSUE TITLE
pdmodel from Europe ?

### ISSUE THREAD

**Issue by MuhammadEP** [PaddlePaddle/PaddleSeg#3265]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hello, I can't install pdmodel (sg80) because I need to create an account that I can't because I have a French number phone how can I do to install it ? 
Thanks

**Comment by juncaipeng** [comment]
What does `install pdmodel (sg80)` means?
To install paddleseg, please refer to https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/docs/install.md

**Comment by MuhammadEP** [comment]
This one

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
