### ISSUE TITLE
关于本模型的调用方式的提问

### ISSUE THREAD

**Issue by AntyRia** [PaddlePaddle/PaddleSeg#3266]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

想问问如何通过输入文本的方式来分割我想要的东西。

**Comment by Sunting78** [comment]
本模型？请详细描述您的问题。如果需要输入文本的方式来分割，可以采用SAM+CLIP基于文本提示进行分割，可以参考[sam](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.8/contrib/SegmentAnything)
