### ISSUE TITLE
如何通过ppmatting实现绿幕抠图的效果

### ISSUE THREAD

**Issue by MicroCountry** [PaddlePaddle/PaddleSeg#3267]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

通过实验人像分割ppmatting效果不错，但是有业务场景是想实现绿幕抠图，但是网上的算法都不是太好用，能不能通过ppmatting来实现绿幕抠图

**Comment by juncaipeng** [comment]
绿幕抠图场景比较简单，可以直接使用传统的背景分割算法，当然也可以使用ppmatting

**Comment by MicroCountry** [comment]
但是人物边缘绿边效果不好，并且对于头发或者衣服上的绿光比较难去除。有些场景下，还要自己调整HSV阈值
