### ISSUE TITLE
eiseg能否在服务器上安装使用，后续有没有网页端

### ISSUE THREAD

**Issue by Czs99** [PaddlePaddle/PaddleSeg#3268]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

eiseg能否在服务器上安装使用，发现启动不了软件

**Comment by Bobholamovic** [comment]
你好，EISeg可以在服务器上使用，只需要确保在服务器上安装、配置好xserver。如果你使用的是远程服务器，同时本地机器为Windows系统，可以考虑Xming等解决方案。

EISeg没有网页端，但PaddleCV-SIG开发了一款支持交互式分割标注的web应用PaddleLabel，感兴趣的话可以看[这里](https://github.com/PaddleCV-SIG/PaddleLabel)~
