### ISSUE TITLE
传播模型无法跳转到下载页面

### ISSUE THREAD

**Issue by xiaoli26** [PaddlePaddle/PaddleSeg#3269]
### 文档链接&描述 Document Links & Description

[static_propagation](https://www.wjx.cn/vm/wWw3pRc.aspx)
视频分割里面点击配套的传播模型无法跳转到下载页面

### 请提出你的建议 Please give your suggestion

直接连接到下载或者更新问卷星

**Comment by Bobholamovic** [comment]
你好，可以在这里找到需要的模型链接：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/EISeg/docs/video.md

**Comment by xiaoli26** [comment]
感谢回复，目前中文页面的传播模型下载会跳转到问卷星，问卷过期了。可以采取英文界面，填写谷歌文档问卷后下载。
