### ISSUE TITLE
请问有没有适用opt工具的移动端部署的demo?

### ISSUE THREAD

**Issue by Kevin-1993-35** [PaddlePaddle/PaddleSeg#327]

**Comment by wuyefeilin** [comment]
可以参考这个 https://paddlex.readthedocs.io/zh_CN/develop/examples/human_segmentation.html#paddle-lite

**Comment by Kevin-1993-35** [comment]
> 可以参考这个 https://paddlex.readthedocs.io/zh_CN/develop/examples/human_segmentation.html#paddle-lite

**Comment by Kevin-1993-35** [comment]
> > 可以参考这个 https://paddlex.readthedocs.io/zh_CN/develop/examples/human_segmentation.html#paddle-lite

**Comment by Kevin-1993-35** [comment]
@wuyefeilin 非常感谢！另外请问您这边有没有移动端处理视频数据的demo？

**Comment by wuyefeilin** [comment]
@li-guang-li  https://github.com/PaddlePaddle/Paddle-Lite-Demo
