### ISSUE TITLE
请问有transunet针对512*512图像，12num_classes的yml文件吗

### ISSUE THREAD

**Issue by Lsxxy** [PaddlePaddle/PaddleSeg#3270]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包含open与closed)，没有类似需求。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; 2. 需求场景（请描述你的项目中为什么需要用此功能）; 3. 功能描述（请简单描述或设计这个功能）

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Bobholamovic** [comment]
我们无法提供所有可能的超参数配置组合。请根据需要自行修改[配置文件](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/contrib/MedicalSeg/configs/synapse/transunet_abdomen_224_224_1_14k_1e-2.yml)。
