### ISSUE TITLE
cascade第二阶段预测的命令

### ISSUE THREAD

**Issue by DLee0102** [PaddlePaddle/PaddleSeg#3271]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

原命令为：python nnunet/predict.py --image_folder msd_lung/Task006_Lung/imagesTs  --output_folder output/nnunet_predict/fullres_pred --plan_path msd_lung/preprocessed/Task006_Lung/nnUNetPlansv2.1_plans_3D.pkl --model_paths output/cascade_fullres/fold0/iter_100000/model.pdparams output/cascade_fullres/fold1/iter_100000/model.pdparams output/cascade_fullres/fold2/iter_100000/model.pdparams output/cascade_fullres/fold3/iter_100000/model.pdparams output/cascade_fullres/fold4/iter_100000/model.pdparams --postprocessing_json_path output/cascade_lowres_val/postprocessing.json --model_type cascade_fullres --save_npz --lowres_segmentations output/nnunet_predict/lowres_pred
应该讲其中的
--postprocessing_json_path output/cascade_lowres_val/postprocessing.json
改成
--postprocessing_json_path output/cascade_fullres_val/postprocessing.json

### 复现环境 Environment

linux下的paddlepaddle环境

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by shiyutang** [comment]
PR is merged
