### ISSUE TITLE
PP-mobileseg-tiny和PP-mobileseg模型miou相差0.1

### ISSUE THREAD

**Issue by ZHIZIHUABU** [PaddlePaddle/PaddleSeg#3273]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

PP-mobileseg-tiny模型Miou和PP-mobilese相差0.1，pp-mobileseg在自己的数据集上miou=0.91，但是pp-mobileseg_tiny 模型miou=0.81

**Comment by ZHIZIHUABU** [comment]
同时我将pp-mobileseg模型导出onnx然后部署到瑞芯微rv1126上，推理速度为18ms,而mobileseg(backbone=0.75)推理速度为10ms。

**Comment by juncaipeng** [comment]
pp-mobileseg-tiny模型的精度会比pp-mobileseg更低点
pp-mobileseg是针对较好的手机芯片设计的，比如高通855 865等，其他芯片上可能mobileseg模型的速度会更快。

**Comment by shiyutang** [comment]
请问导出到onnx是否打开了upsample为VIM呢？ 默认训练时是intpolate，打开vim可以大幅提升速度：
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/34859558/b26493b8-cd47-4347-a4af-043fb6d4b73c)

**Comment by xiaoqingzheng** [comment]
请问pp-mobileseg如何导出为onnx，我导出时报错conditional_block op不支持
