### ISSUE TITLE
新发布的全景分割模型PanopticSeg存在错误AttributeError: 'Config' object has no attribute 'postprocessor'，请问怎么解决？

### ISSUE THREAD

**Issue by WeiYangHui** [PaddlePaddle/PaddleSeg#3276]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

我在使用PanopticSeg进行预测，预测命令如下：
`python tools/predict.py --config configs/panoptic_deeplab/panoptic_deeplab_resnet50_os32_cityscapes_1025x513_bs8_90k.yml --model_path model.pdparams --image_path demo.png --save_dir vis`

遇到的问题如下：

Question1：
predict.py文件内，获取postprocessor配置的语句如下：
`cfg = Config(args.config)`
`postprocessor=cfg.postprocessor`
使用Config类将配置文件中的postprocessor获取，并将对应实例属性赋值给cfg。Config类中获取postprocessor的代码如下：
`@property`
    `def postprocessor_cfg(self):`
            `return self.dic.get('postprocessor', {}).copy()`
上述函数返回的实例属性名为"postprocessor_cfg"，而predict.py文件内获取实例属性时所写的属性名为postprocessor，二者名称不匹配。

Question2：
predict.py文件实际上调用了别处定义好的predict函数，而在该函数内，它的形参中的postprocessor应该是一个后处理器函数，而非字典。以下是函数对postprocessor参数的形参描述：
`postprocessor (paddlepanseg.postprocessors.Postprocessor): Used to postprocess model output.`
那在预测命令中调用的predict.py文件内，传入predict函数的postprocessor参数是一个字典而非函数，两者相互矛盾。

请问我该怎么解决以上问题？

### 复现环境 Environment

-OS:Windows
-PaddlePaddle:2.4.0
-PaddleSeg:release-2.8
-Python:3.9.10
-CUDA:11.6
-CUDNN:8.4

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Bobholamovic** [comment]
你好，感谢提问，为你细致的分析点赞！这个问题是由于我们没有将develop分支修复bug的commit及时同步到release分支，我已经提了一个PR实现这一点：https://github.com/PaddlePaddle/PaddleSeg/pull/3281

**Comment by WeiYangHui** [comment]
好的，谢谢您。
