### ISSUE TITLE
PP-MobileSeg backbone weights not working

### ISSUE THREAD

**Issue by madhu-basavanna** [PaddlePaddle/PaddleSeg#3277]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

The pre-trained weights loaded for pp-mobilseg backbone(StrideFormer-Base) from the config file is throwing the warning saying weights not available for certain layers.

Please check the pdf for environment and error description
[backbone_weights_error.pdf](https://github.com/PaddlePaddle/PaddleSeg/files/11524317/backbone_weights_error.pdf)

### 复现环境 Environment

platform: Linux-5.19.0-41-generic-x86_64-with-glibc2.35
Python: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Paddle compiled with cuda: True
NVCC: Build cuda_11.7.r11.7/compiler.31442593_0
cudnn: 8.4
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: NVIDIA GeForce']
GCC: gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
PaddleSeg: 2.8.0
PaddlePaddle: 2.4.2
OpenCV: 4.5.5

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by shiyutang** [comment]
This log shows the correct result. The injection model is not included in the classification pre-train, therefore is not loaded. This is confusing because we misplaced the injection module in the backbone. But your process here is correct, and you can continue training.

**Comment by madhu-basavanna** [comment]
i was trying to do the inference using the predict.py python code in the tools folder, but im getting very bad prediction compared to all other architectures in the paddleseg, please see the prediction attached from different architectures. and let me know if i'm doing anything wrong in the inference procedure?

so, i thought the warning shown in the log is the reason for the bad prediction.
DeepLabV3
![DeepLabV3](https://github.com/PaddlePaddle/PaddleSeg/assets/65730679/5801d58e-4beb-4ae5-9739-806aba74afa4)
mobileseg
![mobileseg](https://github.com/PaddlePaddle/PaddleSeg/assets/65730679/6ec4d514-44ac-4efc-a352-7ebc300d4761)
ocrnet
![ocrnet](https://github.com/PaddlePaddle/PaddleSeg/assets/65730679/0c0201f6-197e-4848-92b6-cae828109449)
pp_mobileseg
![pp_mobileseg](https://github.com/PaddlePaddle/PaddleSeg/assets/65730679/3c76beb2-cc37-4401-a718-36b26661359c)

**Comment by shiyutang** [comment]
I would like to know more details:

Did you train your model on the corresponding data set?  And what is the pre-train model you load into these tested models, that is to say, which dataset the pretrain model is trained on? 

You are welcomed to provided more relevant details as well.

**Comment by madhu-basavanna** [comment]
Steps i followed to do the inference 
1) I downloaded the PP-MobileSegBase model from [here.](https://bj.bcebos.com/paddleseg/dygraph/ade20k/pp_mobileseg_base/model.pdparams)
2) I downloaded 60 test images from coco dataset and added to a folder named CocoDataset.
3) Then run the predict.py python file present in the tools folder with the below arguments.

python predict.py --config PaddleSeg/configs/pp_mobileseg/pp_mobileseg_base_ade20k_512x512_80k.yml --model_path PP-MobileSeg.pdparams --image_path CocoDataset --save_dir image_output

I followed the same procedure for all the architectures in the paddleseg and i got good prediction except PP-MobileSeg

**Comment by shiyutang** [comment]
please infer the following image from ade20k to see if it works alright.
![ADE_val_00000001](https://github.com/PaddlePaddle/PaddleSeg/assets/34859558/88280e32-d4a1-4f0b-85cc-043898d0bb87)

If it is, it is the generalization problem of pp-mobileseg. Otherwise, there is some problem with the model weights.
