### ISSUE TITLE
关于新建一个dataset出现报错：RuntimeError: The specified component (BRATSDataset) was not found.

### ISSUE THREAD

**Issue by jaceqin** [PaddlePaddle/PaddleSeg#3278]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Traceback (most recent call last):
  File "/home/x012/anaconda3/envs/paddle/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/x012/anaconda3/envs/paddle/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/x012/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/x012/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/x012/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/x012/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/x012/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/x012/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/x012/QJC/PaddleSeg-release-2.8/tools/train.py", line 195, in <module>
    main(args)
  File "/home/x012/QJC/PaddleSeg-release-2.8/tools/train.py", line 160, in main
    model = utils.convert_sync_batchnorm(builder.model, args.device)
  File "/home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages/paddleseg/utils/utils.py", line 275, in __get__
    val = self.func(obj)
  File "/home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages/paddleseg/cvlibs/builder.py", line 123, in model
    assert hasattr(self.train_dataset_class, 'NUM_CLASSES'), \
  File "/home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages/paddleseg/utils/utils.py", line 275, in __get__
    val = self.func(obj)
  File "/home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages/paddleseg/cvlibs/builder.py", line 286, in train_dataset_class
    return self.load_component_class(dataset_type)
  File "/home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages/paddleseg/cvlibs/builder.py", line 86, in load_component_class
    raise RuntimeError("The specified component ({}) was not found.".format(
RuntimeError: The specified component (BRATSDataset) was not found.

**Comment by jaceqin** [comment]
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/108056546/9054f7fd-37f0-4fbb-9880-422b56521cf3)
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/108056546/ddf14a78-9130-4eed-affd-1f49d6b4b88a)
已经按照教程设置

**Comment by shiyutang** [comment]
请问是否更新你的代码为develop模式，即实时同步你的修改到python库中：
```
cd PaddleSeg
python setup.py develop
```

**Comment by jaceqin** [comment]
> 请问是否更新你的代码为develop模式，即实时同步你的修改到python库中：
> 
> ```
> cd PaddleSeg
> python setup.py develop
> ```

python setup.py develop
running develop
/home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
creating paddleseg.egg-info
writing paddleseg.egg-info/PKG-INFO
writing dependency_links to paddleseg.egg-info/dependency_links.txt
writing requirements to paddleseg.egg-info/requires.txt
writing top-level names to paddleseg.egg-info/top_level.txt
writing manifest file 'paddleseg.egg-info/SOURCES.txt'
reading manifest file 'paddleseg.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'paddleseg.egg-info/SOURCES.txt'
running build_ext
Creating /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages/paddleseg.egg-link (link to .)
Adding paddleseg 2.8.0 to easy-install.pth file

Installed /home/x012/QJC/PaddleSeg-release-2.8
Processing dependencies for paddleseg==2.8.0
Searching for scikit-learn==1.2.2
Best match: scikit-learn 1.2.2
Adding scikit-learn 1.2.2 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for prettytable==3.7.0
Best match: prettytable 3.7.0
Adding prettytable 3.7.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for scipy==1.9.1
Best match: scipy 1.9.1
Adding scipy 1.9.1 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for filelock==3.12.0
Best match: filelock 3.12.0
Adding filelock 3.12.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for tqdm==4.65.0
Best match: tqdm 4.65.0
Adding tqdm 4.65.0 to easy-install.pth file
Installing tqdm script to /home/x012/anaconda3/envs/paddle/bin

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for opencv-python==4.5.5.64
Best match: opencv-python 4.5.5.64
Adding opencv-python 4.5.5.64 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for visualdl==2.5.2
Best match: visualdl 2.5.2
Adding visualdl 2.5.2 to easy-install.pth file
Installing visualdl script to /home/x012/anaconda3/envs/paddle/bin

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for PyYAML==6.0
Best match: PyYAML 6.0
Adding PyYAML 6.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for threadpoolctl==3.1.0
Best match: threadpoolctl 3.1.0
Adding threadpoolctl 3.1.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for joblib==1.2.0
Best match: joblib 1.2.0
Adding joblib 1.2.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for numpy==1.24.3
Best match: numpy 1.24.3
Adding numpy 1.24.3 to easy-install.pth file
Installing f2py script to /home/x012/anaconda3/envs/paddle/bin
Installing f2py3 script to /home/x012/anaconda3/envs/paddle/bin
Installing f2py3.8 script to /home/x012/anaconda3/envs/paddle/bin

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for wcwidth==0.2.6
Best match: wcwidth 0.2.6
Adding wcwidth 0.2.6 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for onnx==1.14.0
Best match: onnx 1.14.0
Adding onnx 1.14.0 to easy-install.pth file
Installing backend-test-tools script to /home/x012/anaconda3/envs/paddle/bin
Installing check-model script to /home/x012/anaconda3/envs/paddle/bin
Installing check-node script to /home/x012/anaconda3/envs/paddle/bin

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for psutil==5.9.5
Best match: psutil 5.9.5
Adding psutil 5.9.5 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for tritonclient==2.33.0
Best match: tritonclient 2.33.0
Adding tritonclient 2.33.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for gradio==3.11.0
Best match: gradio 3.11.0
Adding gradio 3.11.0 to easy-install.pth file
Installing gradio script to /home/x012/anaconda3/envs/paddle/bin

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for rarfile==4.0
Best match: rarfile 4.0
Adding rarfile 4.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for paddle2onnx==1.0.6
Best match: paddle2onnx 1.0.6
Adding paddle2onnx 1.0.6 to easy-install.pth file
Installing paddle2onnx script to /home/x012/anaconda3/envs/paddle/bin

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for x2paddle==1.4.1
Best match: x2paddle 1.4.1
Adding x2paddle 1.4.1 to easy-install.pth file
Installing x2paddle script to /home/x012/anaconda3/envs/paddle/bin

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for packaging==23.1
Best match: packaging 23.1
Adding packaging 23.1 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for pandas==2.0.1
Best match: pandas 2.0.1
Adding pandas 2.0.1 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for matplotlib==3.7.1
Best match: matplotlib 3.7.1
Adding matplotlib 3.7.1 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for six==1.16.0
Best match: six 1.16.0
Adding six 1.16.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for requests==2.30.0
Best match: requests 2.30.0
Adding requests 2.30.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for protobuf==3.20.3
Best match: protobuf 3.20.3
Adding protobuf 3.20.3 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for Pillow==9.5.0
Best match: Pillow 9.5.0
Adding Pillow 9.5.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for flask-babel==3.1.0
Best match: flask-babel 3.1.0
Adding flask-babel 3.1.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for Flask==2.3.2
Best match: Flask 2.3.2
Adding Flask 2.3.2 to easy-install.pth file
Installing flask script to /home/x012/anaconda3/envs/paddle/bin

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for bce-python-sdk==0.8.83
Best match: bce-python-sdk 0.8.83
Adding bce-python-sdk 0.8.83 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for typing-extensions==4.5.0
Best match: typing-extensions 4.5.0
Adding typing-extensions 4.5.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for aiohttp==3.8.4
Best match: aiohttp 3.8.4
Adding aiohttp 3.8.4 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for geventhttpclient==2.0.2
Best match: geventhttpclient 2.0.2
Adding geventhttpclient 2.0.2 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for python-rapidjson==1.10
Best match: python-rapidjson 1.10
Adding python-rapidjson 1.10 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for grpcio==1.54.0
Best match: grpcio 1.54.0
Adding grpcio 1.54.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for websockets==11.0.3
Best match: websockets 11.0.3
Adding websockets 11.0.3 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for uvicorn==0.22.0
Best match: uvicorn 0.22.0
Adding uvicorn 0.22.0 to easy-install.pth file
Installing uvicorn script to /home/x012/anaconda3/envs/paddle/bin

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for python-multipart==0.0.6
Best match: python-multipart 0.0.6
Adding python-multipart 0.0.6 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for pydub==0.25.1
Best match: pydub 0.25.1
Adding pydub 0.25.1 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for pydantic==1.10.7
Best match: pydantic 1.10.7
Adding pydantic 1.10.7 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for pycryptodome==3.17
Best match: pycryptodome 3.17
Adding pycryptodome 3.17 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for paramiko==3.1.0
Best match: paramiko 3.1.0
Adding paramiko 3.1.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for orjson==3.8.12
Best match: orjson 3.8.12
Adding orjson 3.8.12 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for markdown-it-py==2.2.0
Best match: markdown-it-py 2.2.0
Adding markdown-it-py 2.2.0 to easy-install.pth file
Installing markdown-it script to /home/x012/anaconda3/envs/paddle/bin

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for Jinja2==3.1.2
Best match: Jinja2 3.1.2
Adding Jinja2 3.1.2 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for httpx==0.24.0
Best match: httpx 0.24.0
Adding httpx 0.24.0 to easy-install.pth file
Installing httpx script to /home/x012/anaconda3/envs/paddle/bin

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for h11==0.12.0
Best match: h11 0.12.0
Adding h11 0.12.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for fsspec==2023.5.0
Best match: fsspec 2023.5.0
Adding fsspec 2023.5.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for ffmpy==0.3.0
Best match: ffmpy 0.3.0
Adding ffmpy 0.3.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for fastapi==0.95.1
Best match: fastapi 0.95.1
Adding fastapi 0.95.1 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for sympy==1.12
Best match: sympy 1.12
Adding sympy 1.12 to easy-install.pth file
Installing isympy script to /home/x012/anaconda3/envs/paddle/bin

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for tzdata==2023.3
Best match: tzdata 2023.3
Adding tzdata 2023.3 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for pytz==2023.3
Best match: pytz 2023.3
Adding pytz 2023.3 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for python-dateutil==2.8.2
Best match: python-dateutil 2.8.2
Adding python-dateutil 2.8.2 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for importlib-resources==5.12.0
Best match: importlib-resources 5.12.0
Adding importlib-resources 5.12.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for pyparsing==3.0.9
Best match: pyparsing 3.0.9
Adding pyparsing 3.0.9 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for kiwisolver==1.4.4
Best match: kiwisolver 1.4.4
Adding kiwisolver 1.4.4 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for fonttools==4.39.4
Best match: fonttools 4.39.4
Adding fonttools 4.39.4 to easy-install.pth file
Installing fonttools script to /home/x012/anaconda3/envs/paddle/bin
Installing pyftmerge script to /home/x012/anaconda3/envs/paddle/bin
Installing pyftsubset script to /home/x012/anaconda3/envs/paddle/bin
Installing ttx script to /home/x012/anaconda3/envs/paddle/bin

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for cycler==0.11.0
Best match: cycler 0.11.0
Adding cycler 0.11.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for contourpy==1.0.7
Best match: contourpy 1.0.7
Adding contourpy 1.0.7 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for certifi==2023.5.7
Best match: certifi 2023.5.7
Adding certifi 2023.5.7 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for urllib3==2.0.2
Best match: urllib3 2.0.2
Adding urllib3 2.0.2 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for idna==3.4
Best match: idna 3.4
Adding idna 3.4 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for charset-normalizer==3.1.0
Best match: charset-normalizer 3.1.0
Adding charset-normalizer 3.1.0 to easy-install.pth file
Installing normalizer script to /home/x012/anaconda3/envs/paddle/bin

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for Babel==2.12.1
Best match: Babel 2.12.1
Adding Babel 2.12.1 to easy-install.pth file
Installing pybabel script to /home/x012/anaconda3/envs/paddle/bin

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for importlib-metadata==6.6.0
Best match: importlib-metadata 6.6.0
Adding importlib-metadata 6.6.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for blinker==1.6.2
Best match: blinker 1.6.2
Adding blinker 1.6.2 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for click==8.1.3
Best match: click 8.1.3
Adding click 8.1.3 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for itsdangerous==2.1.2
Best match: itsdangerous 2.1.2
Adding itsdangerous 2.1.2 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for Werkzeug==2.3.4
Best match: Werkzeug 2.3.4
Adding Werkzeug 2.3.4 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for future==0.18.3
Best match: future 0.18.3
Adding future 0.18.3 to easy-install.pth file
Installing futurize script to /home/x012/anaconda3/envs/paddle/bin
Installing pasteurize script to /home/x012/anaconda3/envs/paddle/bin

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for aiosignal==1.3.1
Best match: aiosignal 1.3.1
Adding aiosignal 1.3.1 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for frozenlist==1.3.3
Best match: frozenlist 1.3.3
Adding frozenlist 1.3.3 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for yarl==1.9.2
Best match: yarl 1.9.2
Adding yarl 1.9.2 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for async-timeout==4.0.2
Best match: async-timeout 4.0.2
Adding async-timeout 4.0.2 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for multidict==6.0.4
Best match: multidict 6.0.4
Adding multidict 6.0.4 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for attrs==23.1.0
Best match: attrs 23.1.0
Adding attrs 23.1.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for Brotli==1.0.9
Best match: Brotli 1.0.9
Adding Brotli 1.0.9 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for gevent==22.10.2
Best match: gevent 22.10.2
Adding gevent 22.10.2 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for PyNaCl==1.5.0
Best match: PyNaCl 1.5.0
Adding PyNaCl 1.5.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for cryptography==40.0.2
Best match: cryptography 40.0.2
Adding cryptography 40.0.2 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for bcrypt==4.0.1
Best match: bcrypt 4.0.1
Adding bcrypt 4.0.1 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for mdit-py-plugins==0.3.5
Best match: mdit-py-plugins 0.3.5
Adding mdit-py-plugins 0.3.5 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for linkify-it-py==2.0.2
Best match: linkify-it-py 2.0.2
Adding linkify-it-py 2.0.2 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for mdurl==0.1.2
Best match: mdurl 0.1.2
Adding mdurl 0.1.2 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for MarkupSafe==2.1.2
Best match: MarkupSafe 2.1.2
Adding MarkupSafe 2.1.2 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for sniffio==1.3.0
Best match: sniffio 1.3.0
Adding sniffio 1.3.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for httpcore==0.15.0
Best match: httpcore 0.15.0
Adding httpcore 0.15.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for starlette==0.26.1
Best match: starlette 0.26.1
Adding starlette 0.26.1 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for mpmath==1.3.0
Best match: mpmath 1.3.0
Adding mpmath 1.3.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for zipp==3.15.0
Best match: zipp 3.15.0
Adding zipp 3.15.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for greenlet==2.0.2
Best match: greenlet 2.0.2
Adding greenlet 2.0.2 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for setuptools==66.0.0
Best match: setuptools 66.0.0
Adding setuptools 66.0.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for zope.interface==6.0
Best match: zope.interface 6.0
Adding zope.interface 6.0 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for zope.event==4.6
Best match: zope.event 4.6
Adding zope.event 4.6 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for cffi==1.15.1
Best match: cffi 1.15.1
Adding cffi 1.15.1 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for uc-micro-py==1.0.2
Best match: uc-micro-py 1.0.2
Adding uc-micro-py 1.0.2 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for anyio==3.6.2
Best match: anyio 3.6.2
Adding anyio 3.6.2 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Searching for pycparser==2.21
Best match: pycparser 2.21
Adding pycparser 2.21 to easy-install.pth file

Using /home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages
Finished processing dependencies for paddleseg==2.8.0

请问是这样更新吗？但是我这样更新后还是出现同样的问题，找不到我添加的dataset类

**Comment by jaceqin** [comment]
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/108056546/749b0753-350a-427b-8fdd-bfc5adfe5e25)

**Comment by jaceqin** [comment]
运行python setup.py develop后，截图如上，但是还是会出现RuntimeError: The specified component (BRATSDataset) was not found.的报错

**Comment by jaceqin** [comment]
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/108056546/3266d67c-8a48-4b04-9fc1-a64cde360c1c)
是我的Python装饰器使用错误吗，字典值里没有我新添加的类

**Comment by jaceqin** [comment]
> 请问是否更新你的代码为develop模式，即实时同步你的修改到python库中：
> 
> ```
> cd PaddleSeg
> python setup.py develop
> ```
 
请问我这个完全按照步骤，但是datasets里面仍然没有我的类是为什么

**Comment by shiyutang** [comment]
你这个数据集是建立在PaddleSeg目录下的？ BRATSDataset应该是医疗数据集吧，如果需要使用医疗套件medicalseg，需要建立在contrib/MedicalSeg/dataset下。

**Comment by jaceqin** [comment]
> 
我把BraTs切成2D的 想看看普通的语义分割的效果

**Comment by shiyutang** [comment]
建议查看/home/x012/anaconda3/envs/paddle/lib/python3.8/site-packages/paddleseg/下代码是否和你的修改同步

**Comment by bigbaicoding** [comment]
我也遇到了同样的问题，但是我用pycharm可以运行，terminal会报一样的错误。

**Comment by shiyutang** [comment]
这个是环境安装不到位的问题，请使用pip install -e .安装。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
