### ISSUE TITLE
使用自己的数据集运行segnet后程序运行暂停

### ISSUE THREAD

**Issue by jaceqin** [PaddlePaddle/PaddleSeg#3279]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://github.com/PaddlePaddle/PaddleSeg/assets/108056546/abad3b01-dcfd-412a-af32-99983dcbfbb8)
如图，没有报错也不继续运行

**Comment by juncaipeng** [comment]
建议使用paddleseg的开发者模式安装，然后具体调试一下跑到哪里了。  没有具体错误log，我们无法提供建议。
