### ISSUE TITLE
尝试添加新的模型，RuntimeError: The specified component (DDRNet_39) was not found.

### ISSUE THREAD

**Issue by alan-student** [PaddlePaddle/PaddleSeg#3285]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我尝试将DDRNet_39加入到model里，按照教程，应该是配置好了修饰器
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/62475117/c541c3c4-d9d9-4a74-a575-6630fa455155)
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/62475117/5ce20c83-8827-446f-a214-f7e418eec483)
操作完上面两步以后，我在yml里调用了DDRNet39
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/62475117/96699727-614b-4984-a632-e1bca75b0e08)
但是还是报错了
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/62475117/7833665c-5050-48fe-9c30-c9c5df54e14e)
我的系统环境，但是跑其他的模型是正常的
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/62475117/2a2574f1-74db-41f4-b037-a2918a5fd1c0)
能帮助我一下吗，不胜感激

**Comment by alan-student** [comment]
这个是报错信息
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/62475117/a23e22c6-af86-4a17-bc2d-0f9fe58f3588)

**Comment by Bobholamovic** [comment]
你好，我注意到报错信息中显示paddleseg库被安装在`site-packages`目录中，这说明你在安装时可能使用了`python setup.py install`或者`pip install paddleseg`的方式。如果需要进行定制化开发的话，请使用develop模式安装PaddleSeg（pip的editable模式）。使用该模式安装的PaddleSeg可以让你对代码的修改及时生效，而不需要每次运行前重新安装。

可以参考这里：
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/docs/install.md#221-install-paddleseg-from-source

在使用pip工具安装时指定`-e`选项或者在使用`setup.py`安装时用`python setup.py develop`。

**Comment by alan-student** [comment]
感谢您的回复，按照你说给定的方法，成功实现了训练，另外我还想请教一个问题，如果我想修改SFNet的骨干网络为MobileNet_V3,我需要做什么工作？
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/62475117/aec26463-b3ea-42f4-9549-df634b9a9e21)
这个是我按照常规的ResNet18所写的配置文件，可以正常训练，我将ResNet18替换为MobileNet，会报错
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/62475117/8276e9f3-ee7d-4bdb-9e91-dbb2ce654ce5)
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/62475117/834af2b7-735e-424f-bac7-9fa9b7ddc542)
能帮我看看需要如何配置吗？

**Comment by Bobholamovic** [comment]
SFNet当前不支持ResNet以外的backbone~ 如果要使用MobileNet作为backbone，恐怕没有比较简单的办法，需要对源码进行修改
