### ISSUE TITLE
关于im-=mean

### ISSUE THREAD

**Issue by yang-chenyu104** [PaddlePaddle/PaddleSeg#3292]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

进行图像分割出现一个预处理问题
![B 2Y)ORAOM1V2%25% 3R~}9](https://github.com/PaddlePaddle/PaddleSeg/assets/61871674/ac8b9df8-8c98-4efa-8c48-eb691e81e547)
im -= mean出现类型不匹配

**Comment by Bobholamovic** [comment]
你好，请确认输入图像的通道数与`Normalize`所设置的mean和variance的通道数是否相同。

**Comment by yang-chenyu104** [comment]
我在调试一下，感谢大佬回复！！！



---原始邮件---
发件人: "Lin ***@***.***&gt;
发送时间: 2023年5月31日(周三) 上午10:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleSeg] 关于im-=mean (Issue #3292)




 
你好，请确认输入图像的通道数与Normalize所设置的mean和variance的通道数是否相同。
