### ISSUE TITLE
模型加载数据出错

### ISSUE THREAD

**Issue by yang-chenyu104** [PaddlePaddle/PaddleSeg#3293]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在模型加载数据出错或者打断点调试，推出断点，程序会一直卡着
![WKB TY$9HSPZAF3CJ5GCU3H](https://github.com/PaddlePaddle/PaddleSeg/assets/61871674/9d0e472e-45da-4038-a7f0-efc1a2aedf69)

**Comment by Bobholamovic** [comment]
你好，可能是pdb导致资源回收无法按照正常流程，从而主进程无法正常退出。通常来说，只需要按下Ctrl+C就可以让程序退出。如果这个方法不奏效，可以考虑按Ctrl+Z将程序切到后台，然后通过`kill %1`指定向其发送SIGTERM信号以使其退出。如果你显式使用了多进程（例如设置`num_workers`>1），建议通过`ps`或者`top`检查是否有遗留的孤儿进程、僵尸进程，如果有的话，kill掉这些进程可以即刻完全释放资源。

**Comment by yang-chenyu104** [comment]
谢谢回复，我尝试一下，感谢大佬的回复！！！



---原始邮件---
发件人: "Lin ***@***.***&gt;
发送时间: 2023年5月31日(周三) 上午10:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleSeg] 模型加载数据出错 (Issue #3293)




 
你好，可能是pdb导致资源回收无法按照正常流程，从而主进程无法正常退出。通常来说，只需要按下Ctrl+C就可以让程序退出。如果这个方法不奏效，可以考虑按Ctrl+Z将程序切到后台，然后通过kill %1指定向其发送SIGTERM信号以使其退出。如果你显式使用了多进程（例如设置num_workers&gt;1），建议通过ps或者top检查是否有遗留的孤儿进程、僵尸进程，如果有的话，kill掉这些进程可以即刻完全释放资源。
