### ISSUE TITLE
可能存在的笔误，参数不一致问题。

### ISSUE THREAD

**Issue by 1160404405** [PaddlePaddle/PaddleSeg#3294]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

[[len(args.model_paths), len(args.params_paths))](https://github.com/PaddlePaddle/PaddleSeg/blob/1da705cc16e6482c89fe4444e887d253fd2bddd3/contrib/MedicalSeg/nnunet/infer.py#L248)](url)此处的‘params_paths’参数有误，上文并没有定义。应该是‘param_paths’

### 复现环境 Environment

None

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by 1160404405** [comment]
[https://github.com/PaddlePaddle/PaddleSeg/blob/1da705cc16e6482c89fe4444e887d253fd2bddd3/contrib/MedicalSeg/nnunet/infer.py#L248](url)

**Comment by Bobholamovic** [comment]
你好，请问这个typo是在哪个文件中哦？

**Comment by 1160404405** [comment]
有连接的锕

**Comment by Bobholamovic** [comment]
好的呀，我找到啦，看起来确实是一个typo。你勾选了『我愿意提交PR』，请问是有计划向PaddleSeg提交修复的PR嘛？

**Comment by shiyutang** [comment]
close due to https://github.com/PaddlePaddle/PaddleSeg/pull/3460
