### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by jdyjjj** [PaddlePaddle/PaddleSeg#3296]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

python:
class Predictor:
    def predict(self, processed_img):

        input_names = self.predictor.get_input_names()
        input_handle = self.predictor.get_input_handle(input_names[0])

        processed_img = np.expand_dims(processed_img, 0)
        input_handle.reshape(processed_img.shape)
        input_handle.copy_from_cpu(processed_img)

        self.predictor.run()

        output_names = self.predictor.get_output_names()
        output_handle = self.predictor.get_output_handle(output_names[0])
        output = output_handle.copy_to_cpu()

        return (np.argmax(output.squeeze(), axis=0)*255).astype('uint8')

the problem comes in "self.predictor.run()"

bug:
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1685362505 (unix time) try "date -d @1685362505" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 8826 (TID 0x7fe4ca50b740) from PID 0 ***]

Segmentation fault (core dumped)

### 复现环境 Environment

os: linux
paddlepaddle-gpu        2.4.0
python 3.7.12
CUDA: 11.4

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Bobholamovic** [comment]
There are a bunch of reasons causing a segmentation fault, and I think the first thing is to check if the inference library is perperly built on your machine. Please run this [demo](https://paddle-inference.readthedocs.io/en/master/guides/quick_start/python_demo.html) to do the check.

**Comment by GDbbq** [comment]
我也遇到了同样的问题

**Comment by shiyutang** [comment]
@GDbbq 可以前往[Paddle Issue区](https://github.com/PaddlePaddle/Paddle/issues)提问。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
