### ISSUE TITLE
使用自己的数据集训练vnet导出静态图infer.py效果很差

### ISSUE THREAD

**Issue by Vibion** [PaddlePaddle/PaddleSeg#3298]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我使用AMOS2022数据集和[vnet](https://github.com/PaddlePaddle/PaddleSeg/blob/develop/contrib/MedicalSeg/README_CN.md)对11个器官进行训练，通过训练中的do_eval我知道我的模型效果很好，但是在导出静态图进行infer时，标注却出奇的差并且可以看成乱码
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/87748437/bea03cb3-9ba2-4259-8ec9-05cbe9551dd3)
上图为训练过程的do_eval保存的预测，下图为导出静态图后的调用infer.py文件
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/87748437/564777b9-878b-4ee9-a58d-8821dd007d67)

**Comment by shiyutang** [comment]
建议排查导出静态图后固定同样输入情况下是否得到相同的结果，另外在导出过程中是否报错？是否是使用float32数据类型作为导出的输入呢？
