### ISSUE TITLE
PaddleSeg遥感影像分割问题咨询

### ISSUE THREAD

**Issue by 642721838** [PaddlePaddle/PaddleSeg#330]
请问现在PaddleSeg遥感影像分割只能分两类么，还有就是我们在试用的时候用8波段数据要报错，是因为现在还不支持3波段以上的数据吗？另外，3波段的数据是不是只能是8位的，求解答，谢谢。

**Comment by HOLLIZHAO** [comment]
遥感分割可以支持多类别的。也支持10+以上多通道。具体可以参看：https://github.com/PaddlePaddle/PaddleSeg/tree/develop/contrib/RemoteSensing
