### ISSUE TITLE
PP-LiteSeg predict a video

### ISSUE THREAD

**Issue by EthanAbitbol3** [PaddlePaddle/PaddleSeg#3300]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

First, thank you for your amazing work ! 
I am working on PP-LiteSeg and i was wondering if i can predict a video ? i tried but without sucess and i did not find anything related to it, so i will be very gratefull if you have any idea about it ? 

Thank you again !

**Comment by juncaipeng** [comment]
PP-LiteSeg is usually used for image segmentation, but it can also predict each frame for a video.

**Comment by EthanAbitbol3** [comment]
Thank you for your explanation! Given its real-time nature, I assumed that it had also undergone testing on videos to provide evidence of its effectiveness.

**Comment by TahaSener** [comment]
I have an example of video inference using the method mentioned by juncaipeng if you like i can provide the code.
I get around 32 ms with an RTX 4090.

**Comment by EthanAbitbol3** [comment]
It will be amazing if you can do that ! thank you !!

**Comment by TahaSener** [comment]
Sorry for the delay @EthanAbitbol3; I had a deadline. The method is a bit tangled, but it gets the job done. The script utilizes some .py files from the original repository for frame preprocessing (line 9 and 10), so please ensure that the script is placed in the main file. Generally, the hierarchy should look like this:

- Main:
   - `paddleseg`
       - cvlibs
       - transforms
       - utils
   - `paddlemodel`
       -  deploy.yaml
       -  model.pdiparams
       -  model.pdmodel
   - test2.mp4
   - video.py

Feel free to modify the directories 'paddlemodel' and 'test2.mp4' on line 16 and 17, respectively. If you encounter any issues with the provided script, please let me know. Apologies again for the spaghetti code and the delay. Have a wonderful day!

[video.zip](https://github.com/PaddlePaddle/PaddleSeg/files/11699588/video.zip)

**Comment by EthanAbitbol3** [comment]
Thank you so much !! I appreciate your help! I will try it out and provide you with feedback.
