### ISSUE TITLE
PaddlePaddle Installation Issue

### ISSUE THREAD

**Issue by tarumishra9498** [PaddlePaddle/PaddleSeg#3301]
### 文档链接&描述 Document Links & Description

I seemed to be running into quite a few errors on both the PyCharm and VS Code. The main issue that I have been having is with the compilation of the code and importing the libraries, even though the paddle libraries are being installed properly. In the terminal it says in VS Code that the libraries are successfully installed. However, when I try to enter the code for the library to confirm the installation, I get many errors in my output. Any recommendations for how to solve this problem?

**Comment by Bobholamovic** [comment]
Please provide the detailed error message and the code you used to confirm the installation.

**Comment by livingbody** [comment]
error message please!
