### ISSUE TITLE
inference time 

### ISSUE THREAD

**Issue by djl00** [PaddlePaddle/PaddleSeg#3302]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

I would like to ask if the inference time is calculated based on the prediction model or the ONNX model. The deployment in the document is calculated based on the prediction model, but the documents in the PPLITE SEG are accelerated by TRT after the ONNX model. The two results are different. May I ask which calculation was used for the PPLITE SEG paper?

**Comment by juncaipeng** [comment]
We use the onnx+trt prediction for the PPLITE SEG paper.

**Comment by djl00** [comment]
This is the result of using a regular prediction model with trt,
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/135192633/c9284943-5c0b-4c85-9804-2dd1c61551a2)
and this is the result of using the onnx model with trt，
<img width="415" alt="image" src="https://github.com/PaddlePaddle/PaddleSeg/assets/135192633/a30e1c8e-1a1f-41bf-965d-fe1a1d00d191">
Why are these two results so different? The server used is 2080ti。

**Comment by djl00** [comment]
Corresponding FPS calculation results：
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/135192633/db6e4d74-8c8b-4811-9761-570de820021a)

![image](https://github.com/PaddlePaddle/PaddleSeg/assets/135192633/bb5c043f-b648-4b71-82a5-16b0b720df55)

**Comment by Deardongfl** [comment]
> This is the result of using a regular prediction model with trt, ![image](https://user-images.githubusercontent.com/135192633/244397378-c9284943-5c0b-4c85-9804-2dd1c61551a2.png) and this is the result of using the onnx model with trt， <img alt="image" width="415" src="https://user-images.githubusercontent.com/135192633/244397812-a30e1c8e-1a1f-41bf-965d-fe1a1d00d191.png"> Why are these two results so different? The server used is 2080ti。

Hello,  How do you achieve the results of using the onnx model with trt?  When I reproduce this method, it is only 6.2 ms .this is my issue:[https://github.com/PaddlePaddle/PaddleSeg/issues/3369#issue-1800213748](url)

**Comment by Asthestarsfalll** [comment]
> > This is the result of using a regular prediction model with trt, ![image](https://user-images.githubusercontent.com/135192633/244397378-c9284943-5c0b-4c85-9804-2dd1c61551a2.png) and this is the result of using the onnx model with trt， <img alt="image" width="415" src="https://user-images.githubusercontent.com/135192633/244397812-a30e1c8e-1a1f-41bf-965d-fe1a1d00d191.png"> Why are these two results so different? The server used is 2080ti。
> 
> Hello, How do you achieve the results of using the onnx model with trt? When I reproduce this method, it is only 6.2 ms .this is my issue:[https://github.com/PaddlePaddle/PaddleSeg/issues/3369#issue-1800213748](url)

2080ti比2060性能好多了

**Comment by djl00** [comment]
> 

按照paddle提供的部署文档就可以
