### ISSUE TITLE
Bug in the calculation of accuracy metric in PaddleSeg/paddleseg/utils /metrics.py

### ISSUE THREAD

**Issue by gitlonglong** [PaddlePaddle/PaddleSeg#3305]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

Dear PaddleSeg team,

I'm writing to report a bug found in the accuracy computation method inside the accuracy function in the PaddleSeg/paddleseg/utils/metrics.py file.

Specifically, the current line of code:
acc = intersect_area[i] / pred_area[i]
is incorrect. It should be amended to:
acc = intersect_area[i] / label_area[i]

The reason is that the formula for precision is:
Precision = True Positives / (True Positives + False Positives),
not
Precision = True Positives / (True Positives + True Negatives).

In this case, the current implementation seems to compute other number instead of precision.

I hope this issue will be addressed soon. Thank you for your attention to this matter.

### 复现环境 Environment

paddlepaddle2.2.2

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by zengshao0622** [comment]
Thanks for your interest in our work.
In the code you mentioned, the `pred_area` means prediction area, and it is equal to TP+FP.
And, the `accuracy` function in `PaddleSeg/paddleseg/utils/metrics.py` is a deprecated function, please use [class_measurement](https://github.com/PaddlePaddle/PaddleSeg/blob/develop/paddleseg/utils/metrics.py#L192) function.
