### ISSUE TITLE
PPLiteSeg Predict

### ISSUE THREAD

**Issue by EthanAbitbol3** [PaddlePaddle/PaddleSeg#3307]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

Hello, 
I executed this : 

![image](https://github.com/PaddlePaddle/PaddleSeg/assets/43862103/65e25837-cf27-4c43-9295-870dc56c8820)

I don't understand the warning message stating that "ppseg_head.arm_list.0._scale" is not present in the pretrained model. Despite obtaining the model from the pretrained models, everything else seems to be in order.

### 复现环境 Environment

- Windows 10 
- python 3.9.13
- CUDA 11.2
- PaddleSeg: 2.8.0
- PaddlePaddle: 2.4.2
- Cudnn : 8.1

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by EthanAbitbol3** [comment]
Also, i predict on the next image : 
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/43862103/58db5913-6aa3-4ae7-bbac-3a5ed3fe1d8e)

And i got this result : 
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/43862103/ac31e63e-89dd-40fa-8ce1-6116e9ce720a)

I predicted with pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k.

**Comment by juncaipeng** [comment]
The weights loaded for prediction need to correspond to the model.  So, you should use the weights saved in training stage. 
Besides, the weights we released are trained on Cityscapes dataset. If you want to segment the above image, you have to train PP-LiteSeg on custom dataset.

**Comment by EthanAbitbol3** [comment]
Thank you for your answer, 
i took the models from here : 
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/43862103/30223d6b-a8b5-4347-aceb-c6f0f49b5589)
I'm sorry, i am new with this and i try to understand !
