### ISSUE TITLE
RTFormer模型导出报错

### ISSUE THREAD

**Issue by sxl1007** [PaddlePaddle/PaddleSeg#3308]
### Bug描述 Describe the Bug

RTFormer导出，input_shape=[-1,3,512,512]，导出报错：
AssertionError: The first dim of x (-1) should be greater than 0, please set input_shape for export.py

### 复现环境 Environment

windows
paddlepaddle-gpu:2.3.0.post110
paddleseg:2.8

**Comment by Bobholamovic** [comment]
你好，请问可以给出你执行导出时使用的具体指令嘛？

**Comment by sxl1007** [comment]
> 你好，请问可以给出你执行导出时使用的具体指令嘛？

python tools/export.py --config D:\Projects\Pycharm-Git\PaddleSeg\configs\quick_start\rtformer_huashang_512_512.yml --model_path F:\Dataset\segment\HuaShang\custom\output\model\best_model.pdparams --save_dir D:\Projects\Pycharm-Git\PaddleSeg\output\inference  --input_shape -1 3 512 512

**Comment by sxl1007** [comment]
> 你好，请问可以给出你执行导出时使用的具体指令嘛？

我将input_shape设置为1 3 512 512的时候，可以导出成功，也可以正常推断。

**Comment by Bobholamovic** [comment]
这样的话很可能是因为这个模型不支持任意的batch_size大小，可能只能在导出时将batch size设置为一个固定的正整数

**Comment by sxl1007** [comment]
> 这样的话很可能是因为这个模型不支持任意的batch_size大小，可能只能在导出时将batch size设置为一个固定的正整数

请问您那边是否有试过这个网络的导出？

**Comment by Bobholamovic** [comment]
是的，我也尝试了一下，观察到的现象和你一致，即无法指定batch size为-1，但指定batch size为1或者2时都可以正常导出（没有测试其它的取值）。从代码上来看，我推测这和RTFormer使用了动态卷积有关，目前PaddlePaddle框架对动态卷积的张量形状推断不如通常的『静态』卷积成熟。
