### ISSUE TITLE
QualityInspector Padim

### ISSUE THREAD

**Issue by zyy0877** [PaddlePaddle/PaddleSeg#3310]
I am using QualityInspector Padim for unsupervised anomaly detection and reported an error when exporting the model
RuntimeError: Sanity check on the configuration file has failed. There should be some problems with your config file. Please check it carefully.
The failed rule is DefaultPrimaryRule, and the error message is: 
No iters specified in the configuration file.

The error message shows that the content of my configuration file is incomplete, but my configuration file has not been deleted or modified. Is it because Paddleseg's export model does not include unsupervised exception detection

My environment is Linux system cuda 10.2 cudnn 7.6.5
I hope everyone can help me out, and I am still confused. If the export is successful, how should the unsupervised anomaly detection be deployed in terms of deployment? Thank you

**Comment by Sunting78** [comment]
Please provide specific running commands, configuration files, and error reports for us to troubleshoot the problem.  Thanks

**Comment by Leonardo0325** [comment]
Hello, I would like to ask a question. Now I have found that the Gaussian distribution at certain points exhibits a double Gaussian distribution, and there may be deviations when calculating the mean and covariance. I would like to distinguish the channels that conform to the double Gaussian distribution, and then calculate the minimum Mahalanobis distance separately from the two distributions. Do you have any ideas about this?
