### ISSUE TITLE
how to pixel tracking in semantic segmentation

### ISSUE THREAD

**Issue by YoungjaeDev** [PaddlePaddle/PaddleSeg#3311]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

hello
I am using lightseg well in PaddleSeg.
How can I apply the Tracker function, which is mainly used in Object Detection, to semantic segmentation?

**Comment by juncaipeng** [comment]
You should try to use video semantic segmentation methods.

**Comment by YoungjaeDev** [comment]
@juncaipeng 

Is there support part that mentioned above in PaddleSEG?

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
