### ISSUE TITLE
TRAIN PPLITESEG ON COCO STUFF

### ISSUE THREAD

**Issue by EthanAbitbol3** [PaddlePaddle/PaddleSeg#3317]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hello, i am actually trying to train ppliteseg on the coco stuff dataset. 
First i downloaded the dataset and execute this : 
!python tools/data/convert_cocostuff.py --annotation_path data/cocostuff_avant/annotations --save_path data/cocostuff/annotations

Next, I put the folder like that : 
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/43862103/e2afc58f-f2f3-4add-9622-63b280f79cb8)

After that, i did the configs file like that : 
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/43862103/f307e15b-1779-4389-b1a4-95a0767c7896)

And finally, i execute this code : 
!set CUDA_VISIBLE_DEVICES=0
!python tools/train.py \
       --config configs/pp_liteseg/pp_liteseg_stdc1_coco_stuff_1024x512_scale1.0_80k.yml \
       --do_eval \
       --use_vdl \
       --save_interval 500 \
       --save_dir output

But i got nothing, i searched but i don't where the error can come from, if you can help me ! thank you !

**Comment by Bobholamovic** [comment]
Hi, by "got nothing" do you mean there is no output to the screen? If that is the case, I would suggest trying `python -c "import paddle; print(paddle.utils.run_check())"` to check if PaddlePaddle is properly installed. A successful run will show messages similar to:

![image](https://github.com/PaddlePaddle/PaddleSeg/assets/21275753/edefa104-1286-4416-9862-3a90d5e92c34)

**Comment by EthanAbitbol3** [comment]
Indeed, there is no output. I followed your instructions, and here is the result:


![image](https://github.com/PaddlePaddle/PaddleSeg/assets/43862103/a28064fc-e19d-47bd-88a7-3a21a4d49389)

It's possible that the lack of GPU memory is causing the training to fail.

**Comment by Bobholamovic** [comment]
It looks like PaddlePaddle is working fine. Can you execute the training commands in the terminal? Sometimes a Jupyter notebook does not handle the program output well.

**Comment by EthanAbitbol3** [comment]
Something did happen! I had all the configuration information printed, and this is what I got at the end:
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/43862103/842fe230-5c9b-43ce-9bab-8bd14a54314f)
I attempted training with Cityscapes, and it worked. However, it doesn't work with ADE20k or COCOStuff.

**Comment by Bobholamovic** [comment]
> It's possible that the lack of GPU memory is causing the training to fail.

This is the most likely reason. Try specifying `--device cpu` and see if the training proceeds.

**Comment by EthanAbitbol3** [comment]
Great !! thank you so much ! 
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/43862103/38f13937-0977-4283-91c4-803ff4740492)

**Comment by EthanAbitbol3** [comment]
Hello, due to limited GPU memory, I couldn't train on cocostuff dataset. Instead, I trained on mini supervisely dataset to gain some insights. Consequently, my YAML file has the following structure:
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/43862103/7ec55813-42b0-4289-bd5a-51716b466ac9)

After completing the training, I proceeded to make predictions on a single image. However, during the prediction process, I encountered the following warning messages:
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/43862103/f468e12b-8921-4c6d-b023-ed010edd8c00)

Can you explain me this ? 
Thank you !

**Comment by Bobholamovic** [comment]
This is an expected output. 

If the `pretrianed` field is specified in the configuration file, PaddleSeg will automatically load the pretrained weights to initialize the model parameters. Not all shapes of pretrained params match the new parameter shapes, especially for the classification layers, which triggers these warnings. 

After loading the pretrained weights, PaddleSeg will load full weights of the model from the file specified by `--model_path`.  In this step, there should be no mismatch of weight params.

Finally the models makes predictions on the input image, and you can check the results in the location specified by `--save_dir`.

**Comment by EthanAbitbol3** [comment]
Thank you for your quick and clear answer!
