### ISSUE TITLE
Get bbox from mobileseg or liteseg

### ISSUE THREAD

**Issue by dFuong** [PaddlePaddle/PaddleSeg#3319]
- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

I want getting bbox from mobileseg or liteseg model.
I've tried to get bbox by image processing that's not good.
Please propose some proposal

**Comment by Bobholamovic** [comment]
For binary segmentation tasks (i.e. with exactly two classes), the output of MobileSeg and LiteSeg models is a binary mask (filled with 0s and 1s). A common practice is to:
1. Apply morphological operations (such as the opening operation) to remove noise. 
2. Separate each individual foreground *object* in the image. 
3. Find the bounding rectangle of each forground object.

You can implement these functions using OpenCV. For step 1, there is `cv2.morphology`. For step 2, `cv2.connectedComponents` or `cv2.connectedComponentsWithStats` is of help. For step3, `cv2.findContours`, `cv2.boundingRect`, and `cv2.minAreaRect` can be chosen for use depending on your need.

For multi-class segmentation tasks, every time you select one class as the foreground, with the other classes as the background, and repeat the process introduced above to obtain bounding boxes with class information.
