### ISSUE TITLE
C++部署预测人像分割，想尝试出xception以外的其他模型，如mobilenetV2的，repo有提供分享么？

### ISSUE THREAD

**Issue by HongChow** [PaddlePaddle/PaddleSeg#332]

**Comment by wuyefeilin** [comment]
https://github.com/PaddlePaddle/PaddleSeg/tree/release/v0.5.0/contrib/HumanSeg
这边提供了三种人像分割模型，欢迎尝试哈

**Comment by polor1010** [comment]
@wuyefeilin 

我使用 https://github.com/PaddlePaddle/PaddleSeg/tree/release/v0.5.0/contrib/HumanSeg 里提供的模型

尝试在 c++ 上使用  https://github.com/PaddlePaddle/PaddleSeg/tree/release/v0.5.0/deploy/cpp

错误讯息为
size of outputs[0]: (1,513,513,1,)
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0811 15:55:32.610400 275452 seg_predictor.cpp:216] output with a unexpected size

如果使用 https://paddleseg.bj.bcebos.com/inference_model/deeplabv3p_xception65_humanseg.tgz 模型则没有问题

humanseg.yaml  修改成
DEPLOY:
    USE_GPU: 0
    MODEL_PATH: "./humanseg_server_inference"
    MODEL_FILENAME: "__model__"
    PARAMS_FILENAME: "__params__"
    EVAL_CROP_SIZE: (513, 513)
    MEAN: [0.5, 0.5, 0.5]
    STD: [0.5, 0.5, 0.5]
    IMAGE_TYPE: "rgb"
    NUM_CLASSES: 2
    CHANNELS : 3
    PRE_PROCESSOR: "SegPreProcessor"
    PREDICTOR_MODE: "NATIVE"
    BATCH_SIZE : 1

请问是我哪边有设定错误吗?

谢谢

**Comment by wuyefeilin** [comment]
size of outputs[0]: (1,513,513,1,) 应该是这边的问题， 你看看能不能增加一个转换让他变成（1，1，513， 513）试试，或者加一步transpose重新导出一个模型

**Comment by polor1010** [comment]
如果使用 https://paddleseg.bj.bcebos.com/inference_model/deeplabv3p_xception65_humanseg.tgz 模型, 可以正常执行

输出为

size of outputs[0]: (1,2,513,513,)

同样的设定和输入影像

**Comment by wuyefeilin** [comment]
@polor1010  https://github.com/PaddlePaddle/PaddleSeg/tree/release/v0.5.0/contrib/HumanSeg 里提供的模型输出有两个，你取第二个输出试试

**Comment by michaelfu123** [comment]
> size of outputs[0]: (1,513,513,1,) 应该是这边的问题， 你看看能不能增加一个转换让他变成（1，1，513， 513）试试，或者加一步transpose重新导出一个模型

想问一下有什么比较好的方法可以将已有的模型导出输出（1，1，513， 513）这种吗
