### ISSUE TITLE
nnunet五折训练修改

### ISSUE THREAD

**Issue by huangguoqing** [PaddlePaddle/PaddleSeg#3320]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问，paddleseg下nnunet的五折交叉训练，加哪个训练参数直接可以训练所有数据，不采用五折交叉训练验证？

**Comment by shiyutang** [comment]
可以修改 fold 为all：  https://github.com/PaddlePaddle/PaddleSeg/blob/08dd01c62a7bdef32af93fc1e95d7549b88a3aaf/contrib/MedicalSeg/configs/nnunet/msd_lung/nnunet_2d_msd_lung_fold0.yml#L23
