### ISSUE TITLE
Error in MiT B3 (segformer) 

### ISSUE THREAD

**Issue by EthanAbitbol3** [PaddlePaddle/PaddleSeg#3322]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

As you can see in the following image : 
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/43862103/efc95ef9-323f-4786-a1eb-577a36272caf)
In the original paper on the right, the mix transformer B3 has a depth configuration of L = [3,3,18,3].
However, in the image on the left, we can observe that the depths are equal to [3,4,18,3].

I don't know if it's done on purpose or if it's a small error that could explain why SegFormer B3 is better than SegFormer B4 on cityscapes val 

### 复现环境 Environment

- os : windows

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Bobholamovic** [comment]
There is an inconsistence between the original paper and the official code released by the authors, and PaddleSeg follows [the settings in the official code](https://github.com/NVlabs/SegFormer/blob/65fa8cfa9b52b6ee7e8897a98705abf8570f9e32/mmseg/models/backbones/mix_transformer.py#L401).

**Comment by EthanAbitbol3** [comment]
ohh okay thank you so much !!
