### ISSUE TITLE
是否会出 SAM万物分割模型 ，基于自己的数据集进行finetune的教程

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/PaddleSeg#3323]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包含open与closed)，没有类似需求。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar feature requests.

### 需求描述 Feature Description

想基于自己的场景finetune一个SAM模型，请问时候会有此类的工作呢？

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by juncaipeng** [comment]
PaddleSeg没有提供SAM微调的代码，可以看下SAM官方repo

**Comment by shiyutang** [comment]
SAM暂时没有训练的代码，需要根据论文进行复现，欢迎复现后给我们提交PR
