### ISSUE TITLE
请问怎么利用paddleseg去除白纸背景，提取文字前景

### ISSUE THREAD

**Issue by bemjimm** [PaddlePaddle/PaddleSeg#3324]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

有一些黑色字体写在白纸上，要怎么将字体前景提取出来？

**Comment by leelbc** [comment]
试试paddleOCR

**Comment by Bobholamovic** [comment]
你好，我认为使用分割手段提取文本可能会有一些算法层面的难点，有可能无法容易地取得较好的效果。建议尝试PaddleOCR，这是一个专注于光学字符识别的套件，支持文本检测、识别等，说不定能满足你的要求。

**Comment by bemjimm** [comment]
好的，我去看看paddleocr，谢谢两位大佬
