### ISSUE TITLE
使用Paddle Inference加载训练的模型时，报错：”The inverse of Fused batch norm variance should be finite. “

### ISSUE THREAD

**Issue by wenmingwei** [PaddlePaddle/PaddleSeg#3326]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The inverse of Fused batch norm variance should be finite. Found nonfinite values! Please check batch_norm2d_15.w_2 
  [Hint: Expected std::isfinite(variance_array[i]) == true, but received std::isfinite(variance_array[i]):0 != true:1.] (at /paddle/paddle/fluid/framework/ir/conv_bn_fuse_pass.cc:105)

==============训练参数======================

amp_level: O1
batch_size: 1
do_eval: true
epoch: 2
eval_batch_size: 1
iters: 80000
keep_checkpoint_max: 5
log_iters: 10
loss:
  coef:
    - 1
  types:
    - type: CrossEntropyLoss
lr_scheduler:
  end_lr: 0
  learning_rate: 1
  power: 0.9
  type: PolynomialDecay
model:
  backbone:
    align_corners: false
    pretrained: 'https://bj.bcebos.com/paddleseg/dygraph/hrnet_w48_ssld.tar.gz'
    type: HRNet_W48
  backbone_indices:
    - -1
  num_classes: 19
  pretrained: null
  type: FCN
num_workers: 0
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 0.0005
precision: fp16
resume_model: None
save_dir: /train/models
save_interval: 10
train_dataset:
  dataset_root: data/cityscapes
  mode: train
  transforms:
    - max_scale_factor: 2
      min_scale_factor: 0.5
      scale_step_size: 0.25
      type: ResizeStepScaling
    - crop_size:
        - 1024
        - 512
      type: RandomPaddingCrop
    - type: RandomHorizontalFlip
    - brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
      type: RandomDistort
    - type: Normalize
  type: MyImageDataset
use_vdl: true
val_dataset:
  dataset_root: data/cityscapes
  mode: val
  transforms:
    - type: Normalize
  type: MyImageDataset
eval: true

**Comment by Bobholamovic** [comment]
你好，可能`batch_norm2d_15.w_2`这个参数的数值是异常的，导致在进行算子融合的时候出现了inf（例如方差数值为0）。请确认模型权重中不包含这样的异常参数~

**Comment by wenmingwei** [comment]
> 你好，可能`batch_norm2d_15.w_2`这个参数的数值是异常的，导致在进行算子融合的时候出现了inf（例如方差数值为0）。请确认模型权重中不包含这样的异常参数~

这个是怎么确认呢？我是直接使用PaddleSeg的train脚本进行的训练。

**Comment by Bobholamovic** [comment]
可以使用`paddle.load`读取权重参数（`model.pdparams`）文件，载入完成后将会得到一个字典，之后可以检视字典中相应的value（bn层的参数）是否存在异常值。

由于数据增强和随机梯度下降法带来了一定的随机性，即使完全规范的训练过程也有可能出现这样的数值问题（在质量一般的自定义数据集上这一现象可能更明显）。如果可能的话，建议调整随机种子重新训练以获得数值正常的权重。

**Comment by HustleOoo** [comment]
> 可以使用`paddle.load`读取权重参数（`model.pdparams`）文件，载入完成后将会得到一个字典，之后可以检视字典中相应的value（bn层的参数）是否存在异常值。
> 
> 由于数据增强和随机梯度下降法带来了一定的随机性，即使完全规范的训练过程也有可能出现这样的数值问题（在质量一般的自定义数据集上这一现象可能更明显）。如果可能的话，建议调整随机种子重新训练以获得数值正常的权重。

您好，我也遇到了这个问题，我使用paddleseg训练得到的pdparams文件进行推理是可以正常推理的，但是通过export生成了pdiparams文件后使用paddleseg/deploy/python/infer进行部署推理报了(InvalidArgument) The inverse of Fused batch norm variance should be finite. Found nonfinite values! Please check batch_norm2d_0.w_2这个错误，但是通过paddle.load去获取batch_norm2d_15.w_2的值时，pdparams和pdiparams这两个权重参数都没有获取到，应该如何解决这个问题呢？使用的硬件环境是昆仑R200加速卡

**Comment by YinRui1991** [comment]
我发现加载pretrained模型来训练自己的数据集，会出现batch norm weights 为空的情况，暂时还没有细挖为啥会出现这种情况，不过观察log有输出Found inf or nan, current scale is: 0.0, decrease to: 0.0*0.5，看起来是梯度爆炸了。我去掉pretrained模型从头训练，模型导出就正常了。或者可以试试加载预训练模型情况下，把lr调低一些。
