### ISSUE TITLE
pp-lite seg accuracy

### ISSUE THREAD

**Issue by djl00** [PaddlePaddle/PaddleSeg#3328]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hello, I have reproduced your pp liteseg, but it cannot meet your accuracy on the cityscapes dataset. Using cuda11.8, Tensorrt8.2.1, and an RTX 2080 server. In the pp liteseg B structure, the result differs by three points from yours. My reproduction is 71%, while yours is 73.9%. Can you tell me the possible reasons？

**Comment by juncaipeng** [comment]
Training accuracy maybe up-and-down, please train the model multiple times.
