### ISSUE TITLE
关于matting复现的问题

### ISSUE THREAD

**Issue by largerwxt** [PaddlePaddle/PaddleSeg#3329]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，我目前在复现您的ppmatting模型。在使用了您的预训练模型进行微调后，sad还是达不到您论文的效果。请问您在训练时是有什么方法吗？

**Comment by wuyefeilin** [comment]
是在哪个数据集上呢

**Comment by largerwxt** [comment]
您好，我是在Distinctions-646上进行训练的，配置按照论文和代码中的配置进行的，但是我总是达不到40。我训练出来的sad是44.请问你们在训练的时候的参数是有改动吗。

**Comment by wuyefeilin** [comment]
参数没有改动的，看看预训练模型加载是否成功了。

**Comment by largerwxt** [comment]
加载成功了的，我使用您的预训练模型进行跑，是不是学习率应该改小一点。

**Comment by wuyefeilin** [comment]
是的，可以调整bs和lr

**Comment by largerwxt** [comment]
好的谢谢您
