### ISSUE TITLE
No loss specified in the configuration file.

### ISSUE THREAD

**Issue by simplew2011** [PaddlePaddle/PaddleSeg#3330]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

![image](https://github.com/PaddlePaddle/PaddleSeg/assets/66729924/e99e1c5c-edc8-4531-8a8c-d8ed28806453)

### 复现环境 Environment

PaddleSeg v2.8.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by simplew2011** [comment]
cd Matting后再执行，解决。

**Comment by chiragshetty-fynd** [comment]
Is the issue resolved? still facing it in `v2.9`

**Comment by aiXia121** [comment]
更新之后readme感觉无人维护了一样，新入手的人各种文件对应不上
