### ISSUE TITLE
nnunet模型精度问题

### ISSUE THREAD

**Issue by huangguoqing** [PaddlePaddle/PaddleSeg#3334]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

hello，我使用AIstudio教程训练模型，无改动，训练出来的3D-UNet模型flod0、flod1...对应直接下载你们训练的权重文件flod0，flod1......结果相差很大？

**Comment by huangguoqing** [comment]
<img width="1105" alt="1" src="https://github.com/PaddlePaddle/PaddleSeg/assets/40251123/a8e11f29-0cab-47a1-8e9c-7c83a249a21c">
训练的iter是30000，默认的训练参数

**Comment by huangguoqing** [comment]
我看到训练时候使用默认的batch_size=2，请问你们训练时候batch_size为多少，参数配置是怎么样的？

**Comment by shiyutang** [comment]
你好，请问从哪里看出来精度差距很大呢？

另外，参数配置可以参考我们的配置文件：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/contrib/MedicalSeg/configs/nnunet/msd_lung/nnunet_3d_fullres_msd_lung_fold0.yml

**Comment by huangguoqing** [comment]
@shiyutang ，谢谢回复，我从分别加载两个模型推导一个CT图像，得到的结果差距很大

**Comment by huangguoqing** [comment]
我没有任何改动参数训练得到的模型：配置文件就是读取的这个https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/contrib/MedicalSeg/configs/nnunet/msd_lung/nnunet_3d_fullres_msd_lung_fold0.yml，所以不知道是否和batch_size有关，这里面默认的是2，你们训练也是2训练的吗？

**Comment by huangguoqing** [comment]
<img width="877" alt="企业微信截图_16877699629266" src="https://github.com/PaddlePaddle/PaddleSeg/assets/40251123/877cf190-00f7-425b-8388-0c426870bc8a">
<img width="853" alt="企业微信截图_16877700171576" src="https://github.com/PaddlePaddle/PaddleSeg/assets/40251123/ce25996f-a6ec-4d29-a90c-29bbb6fb31e7">
第一张是直接下载你们模型得到，第二个是我aistudio训练得到的第iter30000的结果。也不是精度问题，是我得到的模型有很多错误

**Comment by shiyutang** [comment]
这个就是我们训练时使用的配置文件，建议不要修改配置训练一下？

**Comment by huangguoqing** [comment]
> 这个就是我们训练时使用的配置文件，建议不要修改配置训练一下？

我没有修改任何配置得到的上述结果

**Comment by huangguoqing** [comment]
但是我现在提高batch_size就可以了

**Comment by AeBoPi** [comment]
也就是说一开始是batch_size低了，迭代30000iter的epoch并没有原文的多，导致效果差了，是这样吗？
