### ISSUE TITLE
使用剪枝时,缺失segbuilder，ImportError: cannot import name 'SegBuilder' from 'paddleseg.cvlibs.config' 

### ISSUE THREAD

**Issue by hybdxxw** [PaddlePaddle/PaddleSeg#3335]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

使用剪枝命令时 python deploy/slim/prune/prune.py ，报缺失segbuilder，ImportError: cannot import name 'SegBuilder' from 'paddleseg.cvlibs.config' 

### 复现环境 Environment

windows10
PaddleSeg-release-2.8
cuda 11.7
python 3.9

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Bobholamovic** [comment]
你好，这是一个bug，我们正在 https://github.com/PaddlePaddle/PaddleSeg/pull/3341 修复中。

**Comment by Bobholamovic** [comment]
此bug已修复，请拉取最新develop分支尝试。
