### ISSUE TITLE
deploy/onnxruntime_cpp demo error, using my exported BISENETV2 onnx model instead of download onnx model

### ISSUE THREAD

**Issue by ccqedq** [PaddlePaddle/PaddleSeg#3336]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

deploy/onnxruntime_cpp demo error, using my exported BISENETV2 onnx model instead of download onnx model
Segmentation fault (core dumped)
the error is  located  in the post processing part

### 复现环境 Environment

-OS :Linux
-PaddlePaddle 2.22
-PaddleSeg release/2.8
-python: 3.8.13

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Bobholamovic** [comment]
There are many reasons that cause a segmentation fault, a typical one of which is the access to illegal memory. Please check if there is out-of-bounds memory read/write in the postprocessing part.

**Comment by ccqedq** [comment]
yes, the output label is extremely large. the deploy/onnxruntime_cpp demo can only run the onnx model download from the website link, not the onnx model from my training step, so I want to know why I follow the training and export step provided by the tutorial, but can't run the  deploy/onnxruntime_cpp demo proprely, by the way, I use the configuration of pp_liteseg_optic_disc_512*512_1k.yml to train and export

**Comment by Bobholamovic** [comment]
> deploy/onnxruntime_cpp demo error, using my exported BISENETV2 onnx model instead of download onnx model

Here you mentioned that you exported BISENETV2. 

> by the way, I use the configuration of pp_liteseg_optic_disc_512*512_1k.yml to train and export

And here the configuration is of the PP-LiteSeg model.

Please ensure that you use the same configuration file for training and exportation, and that the tutorial you follow matches the PaddleSeg version you are currently using.

**Comment by Bobholamovic** [comment]
> the output label is extremely large

For large images, you may consider more complex preprocessing/postprocessing strategies, as the deploy/onnxruntime_cpp demo is a simple one to demonstrate the basic usage, not the final product that can be used in complicated real-world scenarios.

**Comment by ccqedq** [comment]
I tested PP-LiteSeg and BISENETV2 model, both of them couldn't work.  The train demo use pp_liteseg_optic_disc_512*512_1k.yml  configuration, images used by the demo are small, I want to know why it couldn't work, you can test it, it's all from tutorial step

**Comment by ccqedq** [comment]
I tried the other way to run the deploy/onnxruntime_cpp demo
1. first download model.pdparams.  wget https://paddleseg.bj.bcebos.com/dygraph/cityscapes/bisenet_cityscapes_1024x1024_160k/model.pdparams
2. export model. python tools/export.py        --config configs/bisenet/bisenet_cityscapes_1024x1024_160k.yml        --model_path model.pdparams         --input_shape 1 3 1024 1024 
3.  convert to onnx model. paddle2onnx --model_dir output/inference_model/    --model_filename model.pdmodel             --params_filename model.pdiparams             --opset_version 11             --save_file output.onnx
4. copy output.onnx to deploy/onnxruntime_cpp folder and run ./onnxruntime_cpp_inference_demo_app cityscapes_demo.png output.onnx, Segmentation fault occurred
I think maybe the step of converting to onnx model may be wrong

**Comment by Bobholamovic** [comment]
I have reproduced this bug locally. Thanks for reporting this bug! We are currently investigating the causes and we will notify you in this issue untill the bug is resolved.

**Comment by Bobholamovic** [comment]
Hi, change `int64_t` to `int32_t` in this line solves the problem:

https://github.com/PaddlePaddle/PaddleSeg/blob/94a80c1f47e4d77e38351a12cd2191e935b933b6/deploy/onnxruntime_cpp/src/test_seg.cpp#L35C6-L35C6

We will fix this bug in another pull request. Thank you again for reporting the bug!
