### ISSUE TITLE
已经利用QT将paddleseg推理模型部署到软件中，如何将软件移植到其他电脑中？

### ISSUE THREAD

**Issue by elkslanlanlan** [PaddlePaddle/PaddleSeg#3337]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

已经利用QT将paddleseg推理模型部署到软件中，如何将软件移植到其他电脑中？是否需要新的电脑与开发电脑的cuda-GPU版本保持一致？

**Comment by Bobholamovic** [comment]
你好，这个问题有多种处理办法，你可以根据实际需要选择不同的方法。此外，也需要考虑到『将paddleseg推理模型部署到软件中』的具体集成方式。例如，如果你使用C++语言编写模型部署逻辑，并将Paddle Inference动态链接库与软件一起发行，可以考虑针对不同的CUDA&cuDNN配置为软件提供不同的发行版。

**Comment by elkslanlanlan** [comment]
> 你好，这个问题有多种处理办法，你可以根据实际需要选择不同的方法。此外，也需要考虑到『将paddleseg推理模型部署到软件中』的具体集成方式。例如，如果你使用C++语言编写模型部署逻辑，并将Paddle Inference动态链接库与软件一起发行，可以考虑针对不同的CUDA&cuDNN配置为软件提供不同的发行版。

请问如何能将Paddle Inference动态链接库与软件一起发行呢？

**Comment by elkslanlanlan** [comment]
> 你好，这个问题有多种处理办法，你可以根据实际需要选择不同的方法。此外，也需要考虑到『将paddleseg推理模型部署到软件中』的具体集成方式。例如，如果你使用C++语言编写模型部署逻辑，并将Paddle Inference动态链接库与软件一起发行，可以考虑针对不同的CUDA&cuDNN配置为软件提供不同的发行版。

请问如何能将Paddle Inference动态链接库与软件一起发行呢？

**Comment by Bobholamovic** [comment]
将Paddle Inference动态链接库（so/dll）放置在软件能够检索到的路径，与软件本体一起发行即可。Paddle Inference并不是一个特殊的动态链接库，可以和其它动态链接库采用相同的处理方式。

**Comment by elkslanlanlan** [comment]
> 将Paddle Inference动态链接库（so/dll）放置在软件能够检索到的路径，与软件本体一起发行即可。Paddle Inference并不是一个特殊的动态链接库，可以和其它动态链接库采用相同的处理方式。

好的 谢谢
