### ISSUE TITLE
Matting 在自己的数据集上微调时如何保持 Detail 精度不退化

### ISSUE THREAD

**Issue by unihornWwan** [PaddlePaddle/PaddleSeg#3339]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，目前我正在自己的 Matting 数据集上进行 ppmatting 模型的 finetune，但自己的数据集中对于头发等精细的部分抠图质量不高，导致训练出的模型在发丝上的抠图表现有退化（不如ppmatting预训练模型），请问是否有方法能使得模型只学习新数据集Semantic方面的知识，不学习Detail？例如调整 Loss 中 semantic、detail、fusion 的权重，将 detail 和 fusion 两个分支的loss 权重设置为0，不确定这个想法在理论上是否可行，期待您的解答，谢谢。

**Comment by wuyefeilin** [comment]
单纯控制loss不行，还需要将细节分支的权重和bn固定以及相关的backbone层固定。
