### ISSUE TITLE
paddleSeg使用光流的效果不怎么样啊？ 现在解决视频分割边缘抖动问题的主流解决方法是什么？

### ISSUE THREAD

**Issue by pxEkin** [PaddlePaddle/PaddleSeg#334]

**Comment by pennypm** [comment]
您好，请问可以补充下细节么，比如应用场景之类的

**Comment by pxEkin** [comment]
> 您好，请问可以补充下细节么，比如应用场景之类的

比如视频人像分割这类场景

**Comment by pennypm** [comment]
能讲具体点吗，比如您是如何使用的，您的分割结果是否准确，视频中的人物是否剧烈运动等等。大多数情况下按照我们整套流程下来效果还是很好的。

**Comment by pxEkin** [comment]
> 能讲具体点吗，比如您是如何使用的，您的分割结果是否准确，视频中的人物是否剧烈运动等等。大多数情况下按照我们整套流程下来效果还是很好的。

就是手机上前置/后置摄像头实时分割， 另外用户上传视频分割等等。 目前我们单帧分割看上去还行(存在误分割情况)，合成视频看抖动就比较明显了。  光流是有点效果的，但是手机上稠密光流真的好慢，感觉收益不是太好

**Comment by pxEkin** [comment]
> 能讲具体点吗，比如您是如何使用的，您的分割结果是否准确，视频中的人物是否剧烈运动等等。大多数情况下按照我们整套流程下来效果还是很好的。

我直接用paddlepaddleSeg跑里面的预训练模型，感觉效果不怎么样，模型分割就不太准了(我没做训练)，像跳舞等动作快一点的视频，手和脚基本上分割不出来。

**Comment by pennypm** [comment]
如果您的视频有明显的运动模糊，实时的小模型的分割结果不会很准确，建议您用大模型。光流是需要在较为准确的分割结果上实现的，如果本身分割结果就不准的话，光流的改善效果十分有限。关于速度的问题，您用的是否是python版本，python版速度会相对较慢，建议用c++版本

**Comment by pxEkin** [comment]
> 如果您的视频有明显的运动模糊，实时的小模型的分割结果不会很准确，建议您用大模型。光流是需要在较为准确的分割结果上实现的，如果本身分割结果就不准的话，光流的改善效果十分有限。关于速度的问题，您用的是否是python版本，python版速度会相对较慢，建议用c++版本

单帧来看，分割效果还行， 合成视频看起来抖动就大了，如果存在误分割，光流也搞不定，大佬有什么好方案么

**Comment by abcliguanxi** [comment]
> > 如果您的视频有明显的运动模糊，实时的小模型的分割结果不会很准确，建议您用大模型。光流是需要在较为准确的分割结果上实现的，如果本身分割结果就不准的话，光流的改善效果十分有限。关于速度的问题，您用的是否是python版本，python版速度会相对较慢，建议用c++版本
> 
> 单帧来看，分割效果还行， 合成视频看起来抖动就大了，如果存在误分割，光流也搞不定，大佬有什么好方案么

这个有开源的C++的版本吗？
