### ISSUE TITLE
Windows下利用QT编写的包含paddle推理模型的软件发行到其他电脑中软件会闪退。（加载模型正常，使用模型推理会闪退，但发行的软件在开发电脑中正常运行）

### ISSUE THREAD

**Issue by elkslanlanlan** [PaddlePaddle/PaddleSeg#3344]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

利用QT编写的包含paddle推理模型的软件发行到其他电脑中软件会闪退。（加载模型正常，使用模型推理会闪退，但发行的软件在开发电脑中正常运行）
排除了海康SDK、opencv等的问题，要发行的电脑中配置了和开发电脑一致的cuda和cudnn，软件在新电脑中其他功能包括相机取图及显示，opencv处理等功能均正常，但加载模型后调用模型进行推理就会闪退。
发行软件的文件夹中包含的paddle动态库如下：
test_seg.dll、test_seg.lib、libiomp5md.dll、mkldnn.dll 、mklml.dll 、paddle_inference.dll
其中，test_seg.dll为使用VS生成的模型加载及推理接口动态库。
是否缺少了其他paddle推理模型必备的动态库导致发行的软件闪退呢？

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
