### ISSUE TITLE
如何提前指定推理时的gpu id？我尝试了好久都只能默认记载到0

### ISSUE THREAD

**Issue by hsdjkfnsfc** [PaddlePaddle/PaddleSeg#3345]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

如何提前指定推理时的gpu id？我尝试了好久都只能默认记载到0

**Comment by Asthestarsfalll** [comment]
你好，我尝试提交了一个[PR](https://github.com/PaddlePaddle/PaddleSeg/pull/3347)，你试试本地按照这段代码修改呢？

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：https://github.com/PaddlePaddle/PaddleOCR/issues/10223
