### ISSUE TITLE
Integrate MobileSAM into the pipeline for lightweight and faster inference

### ISSUE THREAD

**Issue by qiaoyu1002** [PaddlePaddle/PaddleSeg#3346]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包含open与closed)，没有类似需求。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; 2. 需求场景（请描述你的项目中为什么需要用此功能）; 3. 功能描述（请简单描述或设计这个功能）

1. 我们完成了faster segment anything 模型的优化，目前github的项目star已经有**1.5K星** Reference: https://github.com/ChaoningZhang/MobileSAM
2. 需求场景：我们的项目与原始 SAM 的性能相当，并且除了图像编码上的更改之外，与原始 SAM 保持完全相同的管道，因此，很容易集成到任何项目中。MobileSAM 比原始 SAM 小约 60 倍，快约 50 倍，比并发 FastSAM 小约 7 倍，快约 5 倍。 整个pipeline的对比总结如下：
 
![image](https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/102718175/ecc801de-a7c9-4ccb-84f7-477e359a1892)
 
![image](https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/102718175/39f257e2-dca0-4956-bdb1-4326e6b5d13b)
 

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Asthestarsfalll** [comment]
你好，我尝试完成了一个[PR](https://github.com/PaddlePaddle/PaddleSeg/pull/3349)，推理结果稍后上传

**Comment by ToddBear** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：https://github.com/PaddlePaddle/PaddleOCR/issues/10223

**Comment by shiyutang** [comment]
> 以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～ 我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)

上述PR暂时未通过，需要等PR通过后这条issue才解决@ToddBear

**Comment by shiyutang** [comment]
该PR目前已经已经验证通过，即将被合入，因此关闭此条Issue～

以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～ 我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：https://github.com/PaddlePaddle/PaddleOCR/issues/10223
