### ISSUE TITLE
paddleseg 断了继续训练错误

### ISSUE THREAD

**Issue by huangguoqing** [PaddlePaddle/PaddleSeg#3348]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

<img width="864" alt="企业微信截图_16881296686513" src="https://github.com/PaddlePaddle/PaddleSeg/assets/40251123/531fe2f2-0ef8-4174-a49d-d74baf8e8f9b">

使用--resume_model 参数报错如上

**Comment by Asthestarsfalll** [comment]
resume_model参数应该传入具体到哪次保存，如`/home/aistudio/PaddleSeg/contrib/MedicalSeg/output/model/iter_1000/`

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：https://github.com/PaddlePaddle/PaddleOCR/issues/10223
