### ISSUE TITLE
PP-MobileSeg通过paddl2onnx转换报错

### ISSUE THREAD

**Issue by Yang507** [PaddlePaddle/PaddleSeg#3350]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

    `paddle2onnx --model_dir=./models --model_filename=model.pdmodel --params_filename=model.pdiparams -- 
      save_file=./models/inference.onnx --opset_version=11 --enable_onnx_checker=True  --enable_dev_version True`

    paddlepaddle-gpu: 2.4.2.post112
    paddle2onnx:           1.0.6
   
    [Paddle2ONNX] Start to parse PaddlePaddle model...
    [Paddle2ONNX] Model file path: ./models/model.pdmodel
    [Paddle2ONNX] Paramters file path: ./models/model.pdiparams
    [Paddle2ONNX] Start to parsing Paddle model...
    [Paddle2ONNX] Oops, there are some operators not supported yet, including conditional_block,
    [ERROR] Due to the unsupported operators, the conversion is aborted.
    Aborted (core dumped)

**Comment by shiyutang** [comment]
mobileseg中有一些不支持的op，例如里面提示的条件op和unique op，目前可以使用动转静+paddlelite部署。如果有onnx转op需要，可以到paddle2onnx进行新增op的提问。
