### ISSUE TITLE
pp-liteseg ：different test resolutions problem

### ISSUE THREAD

**Issue by djl00** [PaddlePaddle/PaddleSeg#3351]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hello, I would like to ask how the results of different test resolutions were obtained in pp liteseg. In the code configuration, there is only 1024 * 512, and how did the results of 1536 * 768 be obtained? Do you need to train at different resolutions before testing? The image I provided shows a training resolution, which corresponds to several different test resolutions. Could you please help me answer this question
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/135192633/df477c01-6250-42d7-899f-86cc57746572)

**Comment by djl00** [comment]
I trained at 1024 * 512 and set the crop size to 1536 * 768 when predicting images. I submitted it to the cityscapes official website and found that the test results obtained were the same as those of the crop size of 1024 * 512

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
