### ISSUE TITLE
使用eiseg半自动标注长视频时如何加速？

### ISSUE THREAD

**Issue by tianbinli** [PaddlePaddle/PaddleSeg#3352]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问下我用eiseg标注视频分割任务，如果视频时长几百帧到上千帧，推理其他帧的时候非常慢，或者会oom，这个问题应该怎么优化呢？比如如何多卡推理或者如何加速呢，可以接受适当降低推理的精度。

**Comment by Asthestarsfalll** [comment]
你好，目前eiseg不支持多卡推理，可以考虑适当降低图像分辨率，或使用更轻量的模型进行推理，或者将[视频分隔为100帧左右长度的多个子视频](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/EISeg/docs/video.md#%E4%BD%BF%E7%94%A8%E6%AD%A5%E9%AA%A4)进行推理，可用[cut_video.py](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/EISeg/tool/cut_video.py)进行视频分段。

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)
