### ISSUE TITLE
直接调用paddleseg里的pspnet报错

### ISSUE THREAD

**Issue by YonghuiTAN22** [PaddlePaddle/PaddleSeg#3354]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

from paddleseg.models.backbones import ResNet50_vd
ResNet50_vd = ResNet50_vd()

model = PSPNet(num_classes=2, backbone=ResNet50_vd)
在paddleseg/models/pspnet.py直接这样调用会报错：
2023-07-04 21:40:29 [INFO]	No pretrained model to load, ResNet_vd will be trained from scratch.
/home/tyh/project/PaddleSeg/paddleseg/cvlibs/manager.py:113: UserWarning: PSPNet exists already! It is now updated to <class '__main__.PSPNet'> !!!
  warnings.warn("{} exists already! It is now updated to {} !!!".
2023-07-04 21:40:29 [INFO]	No pretrained model to load, ResNet_vd will be trained from scratch.
要怎么解决呢

**Comment by Asthestarsfalll** [comment]
上述代码并没有报错，只是有警告:
1. ResNet50_vd中没有传入预训练模型的地址或者链接，因此抛出警告，默认从头训练。
2. 在从paddleseg中导入ResNet50_vt和当前在pspnet.py中的PSPNet类定义会导致`PSPNet`重复注册两次，因此有警告，实际不影响结果。

推荐使用paddleseg中的config配置等进行训练等操作，或者在paddleseg之外的py文件单独实现逻辑。

**Comment by shiyutang** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：[PaddlePaddle/PaddleOCR#10223](https://github.com/PaddlePaddle/PaddleOCR/issues/10223)
