### ISSUE TITLE
PP-Matting license

### ISSUE THREAD

**Issue by leo27heady** [PaddlePaddle/PaddleSeg#3355]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

**Dear PaddlePaddle Team,**

I am seeking clarification regarding the commercial usage of the PP-Matting model, which is available under the _Apache 2.0 license_. I have reviewed the model description and noticed that there are some details regarding training and prediction based on specific datasets that require further clarification.

As I understand, the PP-Matting model is an open-source pre-trained human matting model and is licensed under the Apache 2.0 license, which generally allows for commercial usage. However, I also noted some unclear statements in the model description.

To ensure that I am fully compliant with the licensing terms and any additional requirements, I kindly request clarification on the following points:
1. Can the PP-Matting model be used for _commercial purposes_ without any restrictions or additional permissions beyond those stated in the _Apache 2.0 license_?
2. Does the statement regarding finetuning the model with a small amount of annotated dataset mean that I am allowed to adapt the model for specific human matting scenes in a commercial setting? Are there any restrictions or guidelines I should be aware of when performing such adaptations?

I greatly appreciate your assistance in clarifying these points. Obtaining clear information will ensure that I can confidently and appropriately utilize the PP-Matting model for my commercial project while respecting the licensing terms and any additional requirements.

Thank you for your time and attention. I look forward to your prompt response.

**Comment by Bobholamovic** [comment]
Sorry for the tardy response. We have the following statements on these two points:

1. The PP-Matting model can be used for commercial purposes without any restrictions or additional permissions beyond those stated in the Apache 2.0 license.
2. Finetuning the PP-Matting model with custom dataset, or adapting the model for specific human matting scenes in other ways, is permitted for commercial use, without violating the terms in our license. There are no restrictions or guidelines for such adaptations.
