### ISSUE TITLE
pp_liteseg demo result not so good. anything wrong here?

### ISSUE THREAD

**Issue by jimmyflycv** [PaddlePaddle/PaddleSeg#3357]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hi, i just config the paddleseg environment according to official guide.
but the inference result of the demo is poor, any tips available?
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/70056717/b36e7304-26da-43d7-a65b-5f6aa4c4e849)

**Comment by jimmyflycv** [comment]
with this script.
python deploy/python/infer.py \
    --config ./pp_liteseg_infer_model/deploy.yaml \
    --image_path ./drecall \
    --device 'cpu'

**Comment by jimmyflycv** [comment]
ok.
i just tested the model with demo picture and the result is fine.
so it should be the model accuracy problem.


closed.

**Comment by Asthestarsfalll** [comment]
Hi, It seems that you follow the document of python inference. What would the result be if use the citycapes demo? And what does the origin image `drecall` look like?"

**Comment by jimmyflycv** [comment]
> Hi, It seems that you follow the document of python inference. What would the result be if use the citycapes demo? And what does the origin image `drecall` look like?"

![image](https://github.com/PaddlePaddle/PaddleSeg/assets/70056717/f463ac93-be26-460f-ad7e-a00a93325fe6)
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/70056717/52fcb4be-0121-4bd4-b53b-ef3e51950a0d)

private test data:
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/70056717/65075215-4cb8-4f1f-a62d-c39e50ef65b2)
not only this one, i have tested 200+ images here. guess its easy to image the original scene like this:
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/70056717/91a0baef-a075-48d0-8a46-e0e4e6ce4323)

**Comment by Asthestarsfalll** [comment]
It seem that your private images do not follow the same distribution of Cityscapes. Maybe you need to fine-tune the model.
