### ISSUE TITLE
cmake -DWITH_GPU=ON -DCUDNN_ROOT=/usr/local/cuda/lib64 ..  报错

### ISSUE THREAD

**Issue by weiaoliu** [PaddlePaddle/PaddleSeg#336]
-- Found Paddle host system: ubuntu, version: 16.04.3
-- Found Paddle host system's CPU: 56 cores
-- The CXX compiler identification is GNU 5.4.0
-- The C compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- CXX compiler: /usr/bin/c++, version: GNU 5.4.0
-- C compiler: /usr/bin/cc, version: GNU 4.8.5
-- Found Git: /usr/bin/git (found version "2.7.4")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Performing Test MMX_FOUND
-- Performing Test MMX_FOUND - Success
-- Performing Test SSE2_FOUND
-- Performing Test SSE2_FOUND - Success
-- Performing Test SSE3_FOUND
-- Performing Test SSE3_FOUND - Success
-- Performing Test AVX_FOUND
-- Performing Test AVX_FOUND - Success
-- Performing Test AVX2_FOUND
-- Performing Test AVX2_FOUND - Success
-- Performing Test AVX512F_FOUND
-- Performing Test AVX512F_FOUND - Failed
-- Do not have AVX2 intrinsics and disabled MKL-DNN
paddle serving source dir: /data/wei/PaddleSeg/gpu_test/serving
python env:
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CUDNN_ROOT

-- Build files have been written to: /data/wei/PaddleSeg/gpu_test/serving/build
说没有设置CUDNN_ROOT

**Comment by Channingss** [comment]
@weiaoliu 这是warnning，提示说这个CUDNN_ROOT参数并没有被使用到。
![image](https://user-images.githubusercontent.com/12471701/89869738-5d737f00-dbe7-11ea-9416-4f7d17c5e6fa.png)

编译指令参考这里：
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.5.0/deploy/cpp/docs/linux_build.md#step4-%E7%BC%96%E8%AF%91
