### ISSUE TITLE
D:\PaddleSeg-release-2.8\contrib\RSSegBenchmark

### ISSUE THREAD

**Issue by 12345github123456** [PaddlePaddle/PaddleSeg#3362]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

我按照要求进行下载了potsdam数据集，并制作了数据路径文件和label.txt
然后配置相应模型的yaml配置文件，结果显示出现了没有这个属性的问题，是什么原因呢？

‘’‘2023-07-10 18:14:48 [INFO]
------------Environment Information-------------
platform: Windows-10-10.0.19041-SP0
Python: 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
Paddle compiled with cuda: True
NVCC: Cuda compilation tools, release 10.1, V10.1.105
cudnn: 7.6
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: NVIDIA GeForce']
PaddleSeg: 2.8.0
PaddlePaddle: 2.3.2
OpenCV: 4.5.5
------------------------------------------------
Traceback (most recent call last):
  File "D:\PaddleSeg-release-2.8\contrib\RSSegBenchmark\train.py", line 261, in <module>
    main(args)
  File "D:\PaddleSeg-release-2.8\contrib\RSSegBenchmark\train.py", line 211, in main
    train_dataset = cfg.train_dataset
AttributeError: 'Config' object has no attribute 'train_dataset'

(paddle38) D:\PaddleSeg-release-2.8>python D:\PaddleSeg-release-2.8\contrib\RSSegBenchmark\train.py
2023-07-10 18:18:10 [INFO]
------------Environment Information-------------
platform: Windows-10-10.0.19041-SP0
Python: 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
Paddle compiled with cuda: True
NVCC: Cuda compilation tools, release 10.1, V10.1.105

------------------------------------------------
Traceback (most recent call last):
  File "D:\PaddleSeg-release-2.8\contrib\RSSegBenchmark\train.py", line 261, in <module>
    main(args)
  File "D:\PaddleSeg-release-2.8\contrib\RSSegBenchmark\train.py", line 211, in main
    train_dataset = cfg.train_dataset
AttributeError: 'Config' object has no attribute 'train_dataset'’‘’

### 复现环境 Environment

cudnn: 7.6
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: NVIDIA GeForce']
PaddleSeg: 2.8.0
PaddlePaddle: 2.3.2
OpenCV: 4.5.5

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Asthestarsfalll** [comment]
@12345github123456 与[该issue](https://github.com/PaddlePaddle/PaddleSeg/issues/3358#issuecomment-1628363147)原因类似，可以考虑使用更早的版本

**Comment by 12345github123456** [comment]
2.6版本适配吗

**Comment by Asthestarsfalll** [comment]
> 2.6版本适配吗

你可以尝试一下，有问题再反馈～

**Comment by ToddBear** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：https://github.com/PaddlePaddle/PaddleOCR/issues/10223
