### ISSUE TITLE
新增需求征集（Collect Feature Request）

### ISSUE THREAD

**Issue by shiyutang** [PaddlePaddle/PaddleSeg#3363]
我们将这个Issue 保持开放状态，以收集用户的功能请求并听取您的声音。我们的发布计划将在不同的问题上进行更新。

在这个Issue中，您可以：
1. 通过发表评论来建议新功能。
2. 使用 👍 投票支持功能请求，或者使用 👎 反对。 （请记住，我们也许无法响应所有功能请求，因此请投票给您最喜欢的功能请求！）
3. 如果你也愿意参加代码贡献，欢迎参与我们的活动 #10223。
4. 我们会在上述活动的技术研讨会中对需求进行讨论，如果想要参与讨论你觉得重要的需求，欢迎加入上述活动微信群。

We keep this issue open to collect feature requests from users and hear your voice. Our release plan will be updated on different issues.

In this issue, you can either:

1. Suggest a new feature by leaving a comment.
2. Vote for a feature request with 👍 or be against it with 👎. (Remember that developers are busy and cannot respond to all feature requests, so vote for your most favorable one!)
3. Tell us that you would like to help implement one of the features in the list or review the PRs. Welcome to participate in our activity  #10223(This is the greatest thing to hear about! )
4. Join the above WeChat group in the activity link if you want to discuss the new features with us

**Comment by shiyutang** [comment]
范例：
需求描述：复现高精度移动端模型
需求场景（这个需求可以解决哪些应用场景的问题）： 覆盖移动端的分割场景
潜在解决方案（问题分解）：基于论文复现指南复现。


example:
Description of feature request:
Requirement scenarios (what application scenarios can this feature request solve):
Potential solutions (problem breakdown):

**Comment by yanyonghua** [comment]
需求描述：复现demo里面的操作
需求场景（这个需求可以解决哪些应用场景的问题）： 根据官方文档是没有办法一步一步走下来的，就像下面的，然后cd进入到PaddleSeg/contrib/Matting目录 ，contrib下根本就没有Matting目录 。。。如果结构改变，至少要维护一下现有的项目让人看得懂吧。
潜在解决方案（问题分解）：基于论文复现指南复现。

首先git最新的[PaddleSeg](https://github.com/paddlepaddle/paddleseg/tree/develop)项目，然后cd进入到PaddleSeg/contrib/Matting目录。将下载下来的modnet-hrnet_w18.pdparams动态图模型文件（也可以自行训练得到）放置在当前文件夹（PaddleSeg/contrib/Matting）下面。然后修改配置文件 configs/modnet_mobilenetv2.yml(注意：虽然采用hrnet18模型，但是该模型依赖的配置文件modnet_hrnet_w18.yml本身依赖modnet_mobilenetv2.yml),修改其中的val_dataset字段如下

**Comment by shiyutang** [comment]
> 如果结构改变，至少要维护一下现有的项目让人看得懂吧。

@yanyonghua 这个问题更像是enhancement而不是feature，欢迎根据你走通的流程提交PR，或者向我们提交Issue请其他的开发者共同参与。

**Comment by Asthestarsfalll** [comment]
需求描述：将head等组件独立出来，清理重复代码，如`BasicBlock` `Bottleneck` 等很多重复定义的模块
需求场景： 便于用户更换不同的模块实验及便于阅读代码

**Comment by shiyutang** [comment]
@Asthestarsfalll Hi，这个模块的抽取可能对现有代码的改变较大，我们暂时可能不会有相关的计划进行修改，但是非常感谢你的建议～

**Comment by Asthestarsfalll** [comment]
需求描述：支持多标签分割
需求场景：多标签语义分割任务 multi-label semantic segmentation #2174

**Comment by shiyutang** [comment]
@Asthestarsfalll 
 嗯嗯呢，多标签这个感觉可以加，应该就是改一下输出和损失，我们可以出成一个命题任务让大家认领，你是否感兴趣按照[模版](https://github.com/PaddlePaddle/PaddleOCR/issues/10450)建立一个issue呢？

**Comment by Aoldcat1997** [comment]
需求描述：遥感多类别语义标注
需求场景：能够使用自己提供部分数据集对模型进微调，以提对遥感数据应用场景的覆盖
潜在解决方案：对现有建筑分割的模型开源
注：遥感标注方面出具处理感觉做的挺好的，但标签类型目前停留在建筑；对一些中小型遥感公司，进行解译业务开展时如何快速获取深度学习样本多数情况还是手工提取，效率非常低

**Comment by zouxiaodong** [comment]
需求描述：大图片小目录SAM Anything
需求场景：sam Anything需要支持SAHI

**Comment by ZS-YANG** [comment]
场景描述：在使用EiSeg进行交互式标注时，出现边界简化前后差距过大的问题
潜在解决方案：是否可以在ui中添加一个控制简化倍率的参数值，使用户可以更加灵活的控制简化倍率
https://github.com/PaddlePaddle/PaddleSeg/blob/6f79be16088cc7fb4fd708e94c8d8301d26050c4/EISeg/eiseg/util/polygon.py#L48-L54

**Comment by chenghuaWang** [comment]
需求描述：SAM 中 Generate masks by sampling a grid over the image with this many points to a side. 如 meta 的 SAM everything demo. [ref code](https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/segment_anything/automatic_mask_generator.py#L35)。
需求场景：产生 low-level 任务中全图不同物体的 mask。


需求描述：aistudio 套件中的 PaddleSeg 套件的版本太旧了，没有SAM。建议与github release 保持同步。
需求场景：所有在aistudio 中希望使用最新版 PaddleSeg 的用户。

**Comment by God-song** [comment]
需求场景：想要分割图片各种不同类型的线段，期望还能得到线段的端点坐标，并且每条线段的端点坐标要和分割出来的线段匹配上

**Comment by hyxzhang** [comment]
需求场景：rgb视频抠图，支持多线程并行，提升matting抠图效率

**Comment by hekaimeng123** [comment]
需求描述：提供伪装目标分割(COS\COD)的支持
需求场景：低对比度、边界难识别的场景下目标的分割提取

**Comment by hekaimeng123** [comment]
需求描述：提供伪装目标分割(COS\COD)的支持
需求场景：低对比度、边界难识别的场景下目标的分割提取

**Comment by KillerQueen-dust** [comment]
需求描述：提供更全面的backbone预训练模型参数和配置文件，像是xception_deeplab之类的，明明之前静态图版本都有的
需求场景：论文复现

**Comment by dulicui742** [comment]
需求描述：MedicalSeg中nnUNet能否按照nnUNetV2版本实现？
需求场景：直接使用nnUnetV2训练的过程不能直接用在paddle中，而且paddle中使用相同的数据训练出来的多分类结果较nnUNetV2来说差了好多，不好定位原因。

**Comment by 534114658** [comment]
需求描述：非监督模块[uad]  模型导出及c++推理部分

**Comment by lingdu-xu** [comment]
需求导出onnx模型以后多个batch-size，需求对于不规则物体的实例分割，比如，晶圆上的划痕，，，，有交叉有轻度弯曲，分成一条一条的，，，

**Comment by laborer123** [comment]
> 需求导出onnx模型以后多个batch-size，需求对于不规则物体的实例分割，比如，晶圆上的划痕，，，，有交叉有轻度弯曲，分成一条一条的，，，

用的啥分割模型

**Comment by DazzlingGalaxy** [comment]
路面、草坪上的积水识别，有数据集吗？

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.

**Comment by servucn** [comment]
Segment Anything with PaddleSeg
如何微调预训练模型？

**Comment by juncyan** [comment]
增加与paddle3.0适配版本，增加基于Mamba的新分割算法，例如Mamba-UNet

**Comment by juncyan** [comment]
这个project是不是放弃了已经
