### ISSUE TITLE
params

### ISSUE THREAD

**Issue by djl00** [PaddlePaddle/PaddleSeg#3364]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

How to see the unit of parameter quantity? When running ppliteseg, a parameter quantity and floating point value appear, but I don't know the specific number of M, so I can't compare them。
<img width="239" alt="f80462e0a15b0a0f14f7244cd848ccd" src="https://github.com/PaddlePaddle/PaddleSeg/assets/135192633/5fcb37c2-247b-4659-8446-d28872303f74">

**Comment by Asthestarsfalll** [comment]
参数量计算基于paddle.flops，目前并不支持更改单位，可以手动计算，1M=10^6。

**Comment by shiyutang** [comment]
验证通过

**Comment by ToddBear** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：https://github.com/PaddlePaddle/PaddleOCR/issues/10223
