### ISSUE TITLE
CPU 部署的时候为什么显卡上会有我的paddleSeg的程序

### ISSUE THREAD

**Issue by weiaoliu** [PaddlePaddle/PaddleSeg#337]
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.40       Driver Version: 430.40       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:04:00.0 Off |                  N/A |
| 22%   36C    P2    68W / 250W |    167MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:05:00.0 Off |                  N/A |
| 22%   31C    P8    21W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  Off  | 00000000:08:00.0 Off |                  N/A |
| 22%   30C    P8     1W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  Off  | 00000000:09:00.0 Off |                  N/A |
| 22%   29C    P8    20W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce RTX 208...  Off  | 00000000:84:00.0 Off |                  N/A |
| 22%   29C    P8     1W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce RTX 208...  Off  | 00000000:85:00.0 Off |                  N/A |
| 22%   28C    P8     1W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  GeForce RTX 208...  Off  | 00000000:88:00.0 Off |                  N/A |
| 22%   28C    P8     8W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  GeForce RTX 208...  Off  | 00000000:89:00.0 Off |                  N/A |
| 22%   29C    P8     1W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     39919      C   ./seg-serving                                157MiB |
+-----------------------------------------------------------------------------+

**Comment by Channingss** [comment]
@weiaoliu 编译的时候是否按照文档中：CPU版本预测库进行编译
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.5.0/deploy/cpp/docs/linux_build.md#step4-%E7%BC%96%E8%AF%91

**Comment by weiaoliu** [comment]
/root/projects/PaddleSeg/deploy/cpp/predictor/seg_predictor.cpp:16:42: fatal error: unsupported/Eigen/CXX11/Tensor: 没有那个文件或目录
compilation terminated.
CMakeFiles/libpaddleseg_inference.dir/build.make:110: recipe for target 'CMakeFiles/libpaddleseg_inference.dir/predictor/seg_predictor.cpp.o' failed
make[2]: *** [CMakeFiles/libpaddleseg_inference.dir/predictor/seg_predictor.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/libpaddleseg_inference.dir/all' failed
make[1]: *** [CMakeFiles/libpaddleseg_inference.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2


cmake 时报错了，

**Comment by weiaoliu** [comment]
有没有paddlesegServing 预编译版本（cuda10.1, cudnn7.6+ ubuntu的）

**Comment by weiaoliu** [comment]
/root/projects/PaddleSeg/deploy/cpp/predictor/seg_predictor.cpp:16:42: fatal error: unsupported/Eigen/CXX11/Tensor: 没有那个文件或目录      我查看我的目录下面这个文件是存在的
