### ISSUE TITLE
PP-MobileSeg Cityscapes weights

### ISSUE THREAD

**Issue by nullkatar** [PaddlePaddle/PaddleSeg#3370]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包含open与closed)，没有类似需求。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar feature requests.

### 需求描述 Feature Description

Hello! Thanks a lot for your job and impact you make! Do you have any plans on publishing PP-MobileSeg weights trained on Cityscapes dataset? 

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by shiyutang** [comment]
sure.
[Here](https://github.com/shiyutang/files/blob/main/ppmobileseg_best_city_model.pdparams) it is.

**Comment by nullkatar** [comment]
Thanks a lot! Just to note for further readers - those are weights for base version of the model.

P.S @shiyutang feel free to close, but maybe further readers might like to have weights for tiny version of the model, so leaving it for you to decide what to do with it. Thanks again!
