### ISSUE TITLE
eiseg 预测出没有标记的类别

### ISSUE THREAD

**Issue by tianbinli** [PaddlePaddle/PaddleSeg#3374]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

eiseg在标注视频的过程中，如果label_list里边有3个类别，然后当前视频帧标了两个类别，为什么会出现预测出在标注帧里边没有的第三个类别的情况，以及如何解决？

**Comment by wuyefeilin** [comment]
如果只有两个类别，label_list设置成两个类别试试

**Comment by tianbinli** [comment]
设置成两个类当前视频肯定没问题，但是有N个视频，其他视频里有第三个类别呀

**Comment by shiyutang** [comment]
说明推理错误，可以使用负点点击消除。

**Comment by tianbinli** [comment]
使用负点点击消除的话只能修改单帧的结果，但是实际不应该每个视频上点了哪几个类就只推理出这几个类别的结果。

**Comment by tianbinli** [comment]
通过在输入模型前后进行mask映射，问题解决了。在有三十个类别的情况下，如果当前视频只有一两个物体，整体速度快了将近十倍。不过要注意self.prob中记录了之前推理的信息，多次推理时输入的映射类别需要保持一致。
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/46390195/48a6b0b2-92f0-4663-a2f0-afd5f746d4a5)

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
