### ISSUE TITLE
eiseg标注视频时，在部分没有目标的视频帧上如何进行标记

### ISSUE THREAD

**Issue by tianbinli** [PaddlePaddle/PaddleSeg#3375]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用eiseg进行视频的标注时，有的视频部分片段上帧没有物体，然后其他帧标注推理后会误预测出标签，没有物体的部分帧该如何标注及用它来推理其他帧？因为没有物体没法进行推理，现在只点击右键标记负点之后还是会拿之前帧预测得到的错误的伪标签进行推理。

**Comment by shiyutang** [comment]
你好，看上去这个应该是一个点击负点消除的新需求，现有方式只能对错误预测的图单张点击进行错误消除。
