### ISSUE TITLE
dataset数据加载异常

### ISSUE THREAD

**Issue by Lyn3Mu** [PaddlePaddle/PaddleSeg#3376]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

在“paddleseg/transforms/transforms.py”文件的“Compose”的__call__() 方法中，当cv2.imread()读取的数据不存在时，会引发“AttributeError: 'NoneType' object has no attribute 'astype'”异常，而对于读取的数据的判空操作位于astype操作之后，后续判断无法捕获NoneType引发的异常。
<img width="701" alt="Snipaste_2023-07-13_15-44-23" src="https://github.com/PaddlePaddle/PaddleSeg/assets/83578091/cc5b0fbf-5726-46c2-9175-36dc8fab163d">

### 复现环境 Environment

OS: Windows
PaddlePaddle: 2.2.2
PaddleSeg: release/2.8
Python: 3.9
CUDA:  11.3
CUDNN:  8.5.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Lyn3Mu** [comment]
当数据集处理不规范时会引发此问题，即train/val_list.txt文件中路径索引所指向的图像被异常删除时会导致图像数据为空

**Comment by Asthestarsfalll** [comment]
感谢反馈，稍后会进行修复
