### ISSUE TITLE
Android cpp demo does not work on other models than the given but java code works

### ISSUE THREAD

**Issue by vjayd** [PaddlePaddle/PaddleSeg#3380]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

I have trained and converted all the models to nb file 
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/9303331/b2430c15-a061-46f0-bb36-334ee64b362e)

There are two examples given to deploy the nb file to android
Java based and JNI(cpp ) based. When I deploy to java based android example .. the segmentation maps appear properly without any single line changes to the code. But when I deploy on the cpp example.. the segmentation masks does not appear to be proper. Can you please help me with this I am stuck from past one month.

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
