### ISSUE TITLE
predict时，总是到这一步就停止了，没有输出预测结果

### ISSUE THREAD

**Issue by loxoo6** [PaddlePaddle/PaddleSeg#3381]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

![b7e11cc29add3c39b939e56b6b51943](https://github.com/PaddlePaddle/PaddleSeg/assets/119844692/01a1e182-ca3e-4c2b-9291-34a57d7e68d7)

### 复现环境 Environment

paddlepaddle 2.2.2

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Asthestarsfalll** [comment]
建议打断点调试一下，或者用print插桩，看一下到底在哪里终止运行了。
