### ISSUE TITLE
PaddleSeg可视化的问题

### ISSUE THREAD

**Issue by loxoo6** [PaddlePaddle/PaddleSeg#3382]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用visualdl可视化，怎么可视化出val/loss呢。默认设置中只有train/loss。
![Uploading 图片1.png…]()

**Comment by loxoo6** [comment]
图片不知道为什么上传不上去。现在可视化的结果就只有默认的几种：val/miou,val/acc;train/loss。怎么得到val/loss呢，因为我想判断模型训练是否收敛或者过拟合

**Comment by Asthestarsfalll** [comment]
你好，paddleseg的evaluate[不支持计算loss](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/paddleseg/core/val.py#L28-L237)，需要你自行更改

**Comment by ToddBear** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：https://github.com/PaddlePaddle/PaddleOCR/issues/10223
