### ISSUE TITLE
PP-MobileSeg模型转arm架构nb模型时遇到不支持算子问题

### ISSUE THREAD

**Issue by stormand** [PaddlePaddle/PaddleSeg#3386]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

PP-MobileSeg模型，下载exported model后，通过paddleLite opt转到arm下的nb格式模型，报错提示Error: This model is not supported, because 3 ops are not supported on 'arm'. These unsupported ops are: 'linear_interp_v2, set_value, unique'.

请问现在PP-MobileSeg模型是还不支持通过paddleLite在arm端或者android端部署吗

**Comment by shiyutang** [comment]
支持的，需要升级develop版本的PaddleLite即可。
