### ISSUE TITLE
想要EISeg-Med3D的CT数据标注插件，希望尽快获得联系

### ISSUE THREAD

**Issue by guli-7721** [PaddlePaddle/PaddleSeg#3388]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包含open与closed)，没有类似需求。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标：标注CT数据并3D重建; 2. 需求场景：分割CT椎体，CT数据3D重建，并模型训练; 3. 功能描述：EISeg-Med3D的CT标注插件能快速标注数据，能快速训练模型和得到结果。
2. 想要EISeg-Med3D的CT数据标注插件

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
