### ISSUE TITLE
标注异常

### ISSUE THREAD

**Issue by INTOUCHABLE-VS** [PaddlePaddle/PaddleSeg#3389]
### 问题描述 Please describe your issue

1.PaddleSeg版本：PaddleSeg release/2.8
2.PaddlePaddle版本：PaddlePaddle 2.5.0
3.操作系统信息：Windows 10
4.Python版本号：Python 3.8.17
5.CUDA/cuDNN版本：CUDA11.2/cuDNN 8.2
6.其他内容: 标注异常无法大致掩膜目标，用的模型是static_hrnet18s_ocr48_aluminium
![1689752413597](https://github.com/PaddlePaddle/PaddleSeg/assets/51685497/31c8beb1-f0f5-470a-b71b-39a692e71aaa)
![1689752413487](https://github.com/PaddlePaddle/PaddleSeg/assets/51685497/085579e8-a483-4804-954a-3759e264cce3)
![1689737673990](https://github.com/PaddlePaddle/PaddleSeg/assets/51685497/913e161f-76b4-4732-93d2-be7d71f0a515)

**Comment by yiheng-wang-duke** [comment]
啊这，我也有这个问题

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
