### ISSUE TITLE
ppliteseg模型在rk3588上部署问题

### ISSUE THREAD

**Issue by Wst-sd** [PaddlePaddle/PaddleSeg#3391]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我用C++在rk3588上部署ppliteseg模型时，遇到resize报错的问题“E RKNN: [13:57:11.527] failed to submit!, op id: 62, op name: Resize:p2o.Resize.1, flags: 0x5, task start: 85, task number: 64, run task counter: 9, int status: 0”    请问这个问题怎么解决？

**Comment by Wst-sd** [comment]
我用python推理时 ，resize操作时显示“W RKNN: [14:55:49.390] Model initializer tensor data is empty, name: p2o.helper.constant.9”，但是能正常出推理结果，请问是ppliteseg里面的resize有问题吗？

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
