### ISSUE TITLE
请教一下enet训练过程中loss爆炸可能是什么原因导致的 

### ISSUE THREAD

**Issue by USTCKAY** [PaddlePaddle/PaddleSeg#3392]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

PaddleSeg版本是最新的develop分支，在用npu训练enet时训练几百个step后loss会突然变得巨大。想请教一下套件的同学这有可能是什么原因造成的？训练指令如下：
`python tools/train.py --config configs/enet/enet_cityscapes_1024x512_80k.yml --device npu --do_eval --use_vdl --save_interval 500`
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/50285351/983baa6e-ca24-483c-bcf3-f60755076907)

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
