### ISSUE TITLE
_inherited_啥意思，代码中解析没发现啊

### ISSUE THREAD

**Issue by wstchhwp** [PaddlePaddle/PaddleSeg#3395]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

# 模型
model:
  _inherited_: False
  type: PPLiteSeg
  backbone:
    type: STDC2
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet2.tar.gz

请问这个参数: _inherited_啥意思，代码中解析没发现啊

**Comment by Asthestarsfalll** [comment]
解析代码见[此](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/paddleseg/cvlibs/config.py#L175-L190)，表示不会继承__base__ yaml文件中的内容

**Comment by ToddBear** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：https://github.com/PaddlePaddle/PaddleOCR/issues/10223
