### ISSUE TITLE
在3D slicer中用eideg-med3d模块进行标注的时候程序死机 

### ISSUE THREAD

**Issue by AeBoPi** [PaddlePaddle/PaddleSeg#3397]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

我在windows中可以导入模型，但在标注的时候程序运行提示running inference 20%时slicer会崩溃。我以为是GPU显存的原因，就换了3090的机器尝试，不过那台机器是ubantu系统，在ubantu系统中导入模型，slicer就会崩溃。
'''
![1689923900204](https://github.com/PaddlePaddle/PaddleSeg/assets/109503402/a2cfa65f-44f5-4a32-84a4-8d36f1014393)
'''
请问这是什么原因？我该如何解决呢？

### 复现环境 Environment

- OS :Linux/Windows
- PaddlePaddle: 2.3.1
- paddleseg:2.8.0
- python:3.9.10
- cuda:11.6
- cudnn:8.8
- gcc:7.3.1

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by shiyutang** [comment]
你好，你的猜测没有错误，确实可能是显卡的原因，目前我们在mac和windows下测试过，建议能不能在windows下尝试呢

**Comment by AryaDan11** [comment]
我在win上使用4G显卡也会出现这种情况，显存不够？

**Comment by AeBoPi** [comment]
可能是吧

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
