### ISSUE TITLE
how was pp_mobileseg export_model.zip obtained?

### ISSUE THREAD

**Issue by janimo** [PaddlePaddle/PaddleSeg#3399]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

The exported models listed in the pp_mobileseg README, for example https://bj.bcebos.com/paddleseg/dygraph/ade20k/pp_mobileseg_base/export_model.zip are much larger and having a different architecture (cannot be exported to ONNX) than what  can be obtained via the model exportation command listed there.

```
python tools/export.py \
      --config configs/pp_mobileseg/pp_mobileseg_base_ade20k_512x512_80k.yml \
      --save_dir output/pp_mobileseg_base  \
      --input_shape 1 3 512 512 \ # The model is set to infer one image with this input shape, feel free to suit this to your dataset.
      --output_op none   # If do not use VIM, you need to set this to argmax to get the final prediction rather than logits.

```
What causes the difference?

**Comment by shiyutang** [comment]
Hi
It should not have any architecture difference, you can check it out through the netron on .pdmodel file. 
<img width="140" alt="image" src="https://github.com/PaddlePaddle/PaddleSeg/assets/34859558/73b3c87c-1682-4846-aa70-c4a8f80f8a01">
