### ISSUE TITLE
pp_liteseg预测问题

### ISSUE THREAD

**Issue by djl00** [PaddlePaddle/PaddleSeg#3400]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

pp_liteseg没有给预测代码，只有paddle总的预测代码，如果这样配置预测参数，预测的是多大尺寸的图片：
python tools/predict.py \
        --config configs/pp_liteseg/pp_liteseg_stdc2_cityscapes_1024x512_scale0.5_160k.yml \
        --model_path city_stdc2_0.5/best_model/model.pdparams \
        --image_path data/cityscapes/leftImg8bit/test \
        --save_dir output

其中configs/pp_liteseg/pp_liteseg_stdc2_cityscapes_1024x512_scale0.5_160k.yml代码如下：

_base_: './pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k.yml'

test_config:
  aug_eval: True
  scales: 0.5

model:
  _inherited_: False  # not inherit the model params from the base yaml
  type: PPLiteSeg
  backbone:
    type: STDC2
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet2.tar.gz

**Comment by Asthestarsfalll** [comment]
根据[代码](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/tools/predict.py#L129)，使用的是val_transforms，具体可以看配置文件中的大小

**Comment by ToddBear** [comment]
参考数据集对应的config，测试时似乎不会改变输入图片的尺寸: https://github.com/PaddlePaddle/PaddleSeg/blob/d236b99411fd3a487d0f9bea3135c3d90584d767/contrib/CityscapesSOTA/configs/mscale_ocr_cityscapes_autolabel_mapillary.yml
