### ISSUE TITLE
基于paddle复现的SAM有微调训练接口么

### ISSUE THREAD

**Issue by xupengao** [PaddlePaddle/PaddleSeg#3405]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

基于paddle复现的SAM有微调训练接口么

**Comment by Asthestarsfalll** [comment]
暂时没有，欢迎你提PR添加这个功能

**Comment by ToddBear** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：https://github.com/PaddlePaddle/PaddleOCR/issues/10223
