### ISSUE TITLE
nnunet 用自己的数据集时出现在多线程的数据加载过程中出现了异常，请问这问题如何解决，哪位大佬指导一下呢，谢谢！

### ISSUE THREAD

**Issue by guli-7721** [PaddlePaddle/PaddleSeg#3406]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://github.com/PaddlePaddle/PaddleSeg/assets/139946751/e4aa4132-434a-478c-9462-bb98f702b315)

**Comment by Asthestarsfalll** [comment]
请问你本地运行的环境是什么样呢，调低num_workers的值试试呢

**Comment by guli-7721** [comment]
我不是在本地运行的，在服务器上创建虚拟环境建为 paddle，装了paddle，运行代码 出现的以上错误 。 
好的 我调num_workers试试

**Comment by ToddBear** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：https://github.com/PaddlePaddle/PaddleOCR/issues/10223
