### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by GDbbq** [PaddlePaddle/PaddleSeg#3407]
### Bug描述 Describe the Bug

![image](https://github.com/PaddlePaddle/PaddleSeg/assets/86715812/489ed482-af39-4a84-93a7-5c0aaf176707)

### 复现环境 Environment

linux
paddlepaddle 2.4.2
paddleseg 2.8.0
python 3.9.12
CUDA 10.2

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by GDbbq** [comment]
自定义的数据集，可以跑其他模型UHRNet_W18_Small   ，所以是HRNet存在的bug?
![image](https:github.com/PaddlePaddle/PaddleSeg/assets/86715812/7ee01c56-6091-4b4e-8faf-ca2a07c60031)
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/86715812/8c9dd78b-ea20-48c3-9434-406d9fb48261)
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/86715812/f06b827b-0cbf-459b-bd2b-c642684ebca7)

**Comment by Asthestarsfalll** [comment]
请问设备显存多大呢

**Comment by GDbbq** [comment]
24G

**Comment by Asthestarsfalll** [comment]
可以单独加载模型试试前向反向是不是正常的
