### ISSUE TITLE
pretrained_weights onnx  mnn

### ISSUE THREAD

**Issue by yubinyes** [PaddlePaddle/PaddleSeg#341]
你好，我下載pretrained_weights的模型，都可以轉成onnx，但是好像不能設置onnx的輸入，
x2paddle --model=humanseg_lite_inference  --onnx_opset=11   --framework=paddle2onnx  --save_dir=onnx_model，
MNNConvert -f ONNX --modelFile x2paddle_model.onnx --MNNModel x2paddle_model.mnn  --bizCode biz
humanseg_lite_inference的onnx轉換mnn有一處op錯誤： Check failed: (notSupportOps.size()) == (0) ==> These Op Not Support: ONNX::Slice
請問這幾個公開的模型，可以成功轉話成mnn使用嗎？

**Comment by nepeplwu** [comment]
@yubinyes 感谢反馈，我们未尝试过将相关模型转为mnn模型进行使用，如果你需要做移动端部署的话，可以使用PaddleLite进行部署，参考[PaddleLite教程](https://paddle-lite.readthedocs.io/zh/latest/)
