### ISSUE TITLE
训练结果问题

### ISSUE THREAD

**Issue by VanderLinde1** [PaddlePaddle/PaddleSeg#3410]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我的数据集有多个类别，在运行训练脚本后，结果显示如下
[EVAL] Class IoU:
[0.6516 0.9742 0.773  0.5478 0.8545 0.6149 0.9301]
那么我该如何得知每一个类别对应的iou是什么呢？

**Comment by Asthestarsfalll** [comment]
与gt类别顺序一致

**Comment by VanderLinde1** [comment]
> 与gt类别顺序一致

能否说一下gt类别是什么？

**Comment by Asthestarsfalll** [comment]
> > 与gt类别顺序一致
> 
> 能否说一下gt类别是什么？

每个通道所代表的类别

**Comment by ToddBear** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：https://github.com/PaddlePaddle/PaddleOCR/issues/10223
