### ISSUE TITLE
模型预测出错 TypeError: predict() got an unexpected keyword argument 'auc_roc'

### ISSUE THREAD

**Issue by Jerome-yale** [PaddlePaddle/PaddleSeg#3415]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

我在训练完unet之后，想用模型预测去查看输出的图片
python tools/predict.py \
       --config configs/unet/unet_drive_128x128_40k.yml \
       --model_path output/drive/best_model/model.pdparams \
       --image_path data/DRIVE/images/training/21.png \
       --save_dir output/drive/result
然后就报出这个错误。经过查阅，我发现auc_roc在drive.yml里的
test_config:
  auc_roc: True

报错文本如下
W0728 08:50:13.112543 40846 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.4, Runtime API Version: 10.2
W0728 08:50:13.112588 40846 gpu_resources.cc:149] device: 0, cuDNN Version: 8.2.
2023-07-28 08:50:15 [INFO]	The number of images: 1
Traceback (most recent call last):
  File "/root/distil-unet1/PaddleSeg-release-2.8/tools/predict.py", line 145, in <module>
    main(args)
  File "/root/distil-unet1/PaddleSeg-release-2.8/tools/predict.py", line 140, in main
    **test_config)
TypeError: predict() got an unexpected keyword argument 'auc_roc'

### 复现环境 Environment

platform: Linux-5.4.0-84-generic-x86_64-with-debian-buster-sid
Python: 3.7.13 (default, Mar 29 2022, 02:18:16) [GCC 7.5.0]
Paddle compiled with cuda: True
NVCC: Build cuda_11.2.r11.2/compiler.29558016_0
cudnn: 8.2
GPUs used: 1
CUDA_VISIBLE_DEVICES: 7
GPU: ['GPU 0: Tesla T4', 'GPU 1: Tesla T4', 'GPU 2: Tesla T4', 'GPU 3: Tesla T4', 'GPU 4: Tesla T4', 'GPU 5: Tesla T4', 'GPU 6: Tesla T4', 'GPU 7: Tesla T4']
GCC: gcc (GCC) 8.2.0
PaddleSeg: 2.8.0
PaddlePaddle: 2.5.0
OpenCV: 4.5.5

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Asthestarsfalll** [comment]
是bug，本来应该用于evaluate的，后续会进行修复
