### ISSUE TITLE
关于非监督模型训练问题

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleSeg#3424]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

配置文件padim_resnet18_mvtec.yml，请问一下，非监督训练为什么epoch一次就停止了，而且预测的结果都不正确，这种情况是什么原因呢？
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/87969070/18b69930-b4cd-49dc-88bd-31018af2db62)

**Comment by Asthestarsfalll** [comment]
看代码是只支持一个epoch...

**Comment by ToddBear** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：https://github.com/PaddlePaddle/PaddleOCR/issues/10223
