### ISSUE TITLE
使用nnunet中的export.py将模型导出后如何进行进一步的推理

### ISSUE THREAD

**Issue by 1-on** [PaddlePaddle/PaddleSeg#3429]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

nnunet中的infer.py看着和pridict.py差不多，而且infer.py的输入参数并未用到导出的deploy.yaml

**Comment by Asthestarsfalll** [comment]
见[此](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/contrib/MedicalSeg/configs/nnunet/msd_lung/README.md#%E9%9D%99%E6%80%81%E5%9B%BE%E6%8E%A8%E7%90%86)
