### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by ZeroLelouch1205** [PaddlePaddle/PaddleSeg#3431]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Cuda11.2+Cudnn8.2、Cuda12.2+Cudnn8.9版本下都无法进行训练，paddle版本2.5.1，
**报错代码如下：**
OSError: (External) CUDNN error(9), CUDNN_STATUS_NOT_SUPPORTED.
  [Hint: 'CUDNN_STATUS_NOT_SUPPORTED'.  The functionality requested is not presently supported by cuDNN.  ] (at ../paddle/phi/backends/gpu/cuda/cudnn_desc.h:167)

**环境如下：**
platform: Windows-10-10.0.22621-SP0
Python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Paddle compiled with cuda: True
NVCC: Build cuda_12.2.r12.2/compiler.33053471_0
cudnn: 8.9
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: NVIDIA GeForce']
PaddleSeg: 2.8.0
PaddlePaddle: 2.5.1
OpenCV: 4.5.5

W0803 17:19:36.956816 12184 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.2, Runtime API Version: 11.2
W0803 17:19:36.956816 12184 gpu_resources.cc:149] device: 0, cuDNN Version: 8.9.

**Comment by Asthestarsfalll** [comment]
看起来是Paddle和cuDNN的问题，可以去Paddle仓库提issue
