### ISSUE TITLE
标注问题

### ISSUE THREAD

**Issue by 1219883c** [PaddlePaddle/PaddleSeg#3432]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

EISeg宫格模式标注出来labeelme文件夹下的json文件中的shape为空是什么原因？

**Comment by 1219883c** [comment]
标注生成的json文件是这样的
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/141380964/fa2ed26f-a713-4a8e-a04c-f1cdd9d8519f)

**Comment by ljhwrrr** [comment]
请问您解决此问题了吗，我也遇到了类似问题。labelme文件下的json文件中points坐标为空

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
