### ISSUE TITLE
Data augmentation or modification of data ? 

### ISSUE THREAD

**Issue by EthanAbitbol3** [PaddlePaddle/PaddleSeg#3436]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hello everyone and thank you for your work ! 
I have a question concerning the "transforms" parameter in the configuration files.

I am curious to know whether the "transforms" correspond to data augmentation (i.e., adding more data) or data modification (i.e., simply altering the original data without adding any new data)?

**Comment by Asthestarsfalll** [comment]
yes, transforms is data augmentation, given a input image, apply transforms, return a modified image.

**Comment by EthanAbitbol3** [comment]
Thank you for your answer, so if I understand correctly, we return a single image with all the modifications? and not one image per edit.

**Comment by Asthestarsfalll** [comment]
> Thank you for your answer, so if I understand correctly, we return a single image with all the modifications? and not one image per edit.

Yes. By default, it returns only one modified image, but it can also provide images after each modification.

**Comment by EthanAbitbol3** [comment]
Alright, perfect, I understand better now. I apologize for repeating myself, but I just have a small doubt. When I start the training with the configuration file, will the transformers return a modified image? This implies that for training, I will have both the original image and the modified image, not just the modified image. Thanks again for your help!

**Comment by Asthestarsfalll** [comment]
> When I start the training with the configuration file, will the transformers return a modified image? This implies that for training, I will have both the original image and the modified image, not just the modified image.

It only returns the modified image.

**Comment by EthanAbitbol3** [comment]
Therefore, this implies that while the data will undergo modifications, the overall amount of data will remain unchanged, indicating that it does not constitute data augmentation.

**Comment by Asthestarsfalll** [comment]
> Therefore, this implies that while the data will undergo modifications, the overall amount of data will remain unchanged, indicating that it does not constitute data augmentation.

Yes.

But on the other hand, the modified images differ from the original ones and corresponding modified images in different epoch, indicating that they are a form of data augmentation.

This is a `online` data augmentation.

**Comment by EthanAbitbol3** [comment]
Thank you for your response. I tried to look into how this is done, but it seems that the modification is done only at the beginning of training and not dynamically as suggested by online augmentation.


Again , thank you so much !

**Comment by Asthestarsfalll** [comment]
The dataset is divided into multiple batches during the training procedure, with transformations applied before each batch. This is why it called `online augmentation`

**Comment by EthanAbitbol3** [comment]
Thank you once more! I now have a clear understanding!
