### ISSUE TITLE
请问如何在本地笔记本打开超算服务器的visualdl

### ISSUE THREAD

**Issue by weidazhaoooo** [PaddlePaddle/PaddleSeg#3437]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

http://localhost:8080/怎么样可以访问

**Comment by Asthestarsfalll** [comment]
host参数改为0.0.0.，再访问服务器地址对应端口试试。
或者直接用ssh -L 命令转发服务器端口

**Comment by ToddBear** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：https://github.com/PaddlePaddle/PaddleOCR/issues/10223
