### ISSUE TITLE
pp humanseg v2 lite人像模型预测人像mask存在偏移

### ISSUE THREAD

**Issue by sidluther** [PaddlePaddle/PaddleSeg#3438]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

pp humanseg v2 lite人像模型预测人像mask存在一定几率向下或向右偏移
可视化结果:
![baby-boy-hat-covered-101537_1](https://github.com/PaddlePaddle/PaddleSeg/assets/97332116/06cc96a6-b4f3-4cc3-980f-bef1b179c8d0)
![baby-boy-hat-covered-101537_2](https://github.com/PaddlePaddle/PaddleSeg/assets/97332116/304bdc45-1ea0-41e9-b2ea-ec220e92b0c0)
![baby-boy-hat-covered-101537_3](https://github.com/PaddlePaddle/PaddleSeg/assets/97332116/d5941bfa-dab5-4893-98ef-d19307edb11c)
![baby-boy-hat-covered-101537_4](https://github.com/PaddlePaddle/PaddleSeg/assets/97332116/e3257f23-c1e7-45ad-8161-7364bad5634f)

![girl-dress-bounce-nature-160826_1](https://github.com/PaddlePaddle/PaddleSeg/assets/97332116/6a81c8ec-ac72-4f8f-97f4-35fe537a7d51)
![girl-dress-bounce-nature-160826_2](https://github.com/PaddlePaddle/PaddleSeg/assets/97332116/2f54f49e-702e-4652-8967-b11b5347b234)
![girl-dress-bounce-nature-160826_3](https://github.com/PaddlePaddle/PaddleSeg/assets/97332116/c91b3af7-4c17-4ea4-a260-879015f9d36d)
![girl-dress-bounce-nature-160826_4](https://github.com/PaddlePaddle/PaddleSeg/assets/97332116/d1adcc19-65ec-4c6e-a1e4-019bd7aaa952)

模型推理代码
```
python ../../predict.py \
  --config configs/human_pp_humansegv2_lite.yml \
  --model_path pretrained_models/human_pp_humansegv2_lite_192x192_pretrained/model.pdparams \
  --image_path data/images/XXXXX.jpg \
  --save_dir ./data/images_result
```

原图和结果上传在files.zip
[files.zip](https://github.com/PaddlePaddle/PaddleSeg/files/12271766/files.zip)

### 复现环境 Environment

------------Environment Information-------------
platform: Linux-5.4.0-153-generic-x86_64-with-glibc2.10
Python: 3.8.0 (default, Nov  6 2019, 21:49:08) [GCC 7.3.0]
Paddle compiled with cuda: True
NVCC: Build cuda_11.2.r11.2/compiler.29373293_0
cudnn: 8.1
GPUs used: 1
CUDA_VISIBLE_DEVICES: 2
GPU: ['GPU 0: NVIDIA TITAN', 'GPU 1: NVIDIA TITAN', 'GPU 2: NVIDIA TITAN', 'GPU 3: NVIDIA TITAN', 'GPU 4: NVIDIA TITAN', 'GPU 5: NVIDIA TITAN', 'GPU 6: NVIDIA TITAN']
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PaddleSeg: 2.8.0
PaddlePaddle: 2.3.2
OpenCV: 4.5.5

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Asthestarsfalll** [comment]
是指输入图片横过来的时候预测结果有偏移？

**Comment by sidluther** [comment]
正常拍摄图像预测结果也很容易有偏移情况，比如观察肩膀位置很容易向下偏移了几个像素（图片横着看能更加明显感觉到向下偏移，所以上传了几张横着的）。

![hard275_254](https://github.com/PaddlePaddle/PaddleSeg/assets/97332116/0a9ab9eb-76a9-4370-8d95-85613c0e8320)

![image_13](https://github.com/PaddlePaddle/PaddleSeg/assets/97332116/1874a22d-963d-47b2-a183-1e5aadf48170)
![image_16](https://github.com/PaddlePaddle/PaddleSeg/assets/97332116/874b7d2f-2e69-47d5-8c30-0f6817cea4cf)

比如这几张图像模型预测的mask如果向上移动几个像素值会更加贴合。
所以感觉什么地方有问题使最终推理结果偏移了些。

原图和结果打包上传 
[results.zip](https://github.com/PaddlePaddle/PaddleSeg/files/12279062/results.zip)

**Comment by Asthestarsfalll** [comment]
个人认为边界预测还是比较正常的事情（因为分割就是为了界定不同种类之间的界限，如果能完美解决这个问题，就不需要再研究了），一是模型比较小，因此精度也会低一点，二是这些图像和训练数据的不在同一个分布上，三可能是图片比例的原因，包括各种插值的影响、模型的泛化性等。

对于横着的图片偏移更大的原因，我推测训练集中并没有这样的数据，况且卷积的旋转不变性可能也没有那么强，只是靠局部的特征的进行分类。

至于向下偏移，可能检查一下输入的分辨率和比例，可能是网络中插值的影响

**Comment by sidluther** [comment]
@Asthestarsfalll 
应该不是这个原因，我试了把模型预测的mask沿h方向向上偏移了一个像素再插值到原图尺寸后就贴合多了。

![hard275_254](https://github.com/PaddlePaddle/PaddleSeg/assets/97332116/e0d8864f-eb8a-4682-8905-9ecfd33ae440)
![image_13](https://github.com/PaddlePaddle/PaddleSeg/assets/97332116/e289919e-67ce-4651-bbf6-f046b36f4b3e)

![image_16](https://github.com/PaddlePaddle/PaddleSeg/assets/97332116/957ac158-3aad-446e-823e-8222c00f50bc)

具体原因我还是要深究下代码。

**Comment by Asthestarsfalll** [comment]
代码中应该不会含有任何偏移的行为，能造成这种现象的感觉还是插值的问题，可以试试不同的分辨率推理看看
