### ISSUE TITLE
pp_mobileseg测试提供模型精度问题 

### ISSUE THREAD

**Issue by Yang-Changhui** [PaddlePaddle/PaddleSeg#3441]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，我从这里下载的模型，pp_mobileseg实测ade20k数据集，base: miou 0.3638,tiny:miou 0.2929，并没有达到41.57和36.39，请问是什么原因呢
![1ccb5d63f0487046d96341896e96920](https://github.com/PaddlePaddle/PaddleSeg/assets/71805205/964d7053-7af4-4fe6-b4fe-4c9514a4590e)

**Comment by shiyutang** [comment]
请问可以给出你的日志嘛？ 权重参数是否都加载上了呢？

**Comment by Yang-Changhui** [comment]
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/71805205/205d429f-870a-4beb-a474-76877a6a91c0)
这是验证记录，模型都加载上了，是直接从官网下的模型，这里是我的Ai studio的测试项目：https://aistudio.baidu.com/aistudio/projectdetail/6589121

**Comment by xiexinch** [comment]
Hi @shiyutang,
我测试了 pp_mobileseg 和 knet，发现knet的精度是对上的，但是pp_mobileseg的精度对不上。
[workerlog.0.txt](https://github.com/PaddlePaddle/PaddleSeg/files/12299152/workerlog.0.txt)

**Comment by shiyutang** [comment]
Hi，我在本地复现了这个问题，并且发现是最后改了一个激活函数导致的，非常感谢你们支持，我已经在https://github.com/PaddlePaddle/PaddleSeg/pull/3443 中修复，现在结果已经正常：
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/34859558/03ab2da2-3197-46e0-9e18-4ed30d1bf866)

**Comment by shiyutang** [comment]
如果没有其他问题，我将关闭这个issue
