### ISSUE TITLE
Paddleseg on C++ 

### ISSUE THREAD

**Issue by EthanAbitbol3** [PaddlePaddle/PaddleSeg#3445]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hello!
I have used PaddleSeg to train a model on a custom dataset, and I was able to export the model to ONNX format. I wanted to know if there is any documentation or tutorial available for using this ONNX weight file in C++ to predict an image.

Thank you !

**Comment by Asthestarsfalll** [comment]
You can refer [here](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.8/deploy/onnxruntime_cpp)

**Comment by EthanAbitbol3** [comment]
Thank you for your response ! 
I forgot to mention that i am on windows :s

**Comment by Asthestarsfalll** [comment]
> Thank you for your response ! I forgot to mention that i am on windows :s

You may find it helpful to refer to the official ONNX tutorial. However, building ONNX on a Windows platform may be slightly inconvenient. Fortunately the code is similar, which means they can be utilized with a little change.

**Comment by ToddBear** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：https://github.com/PaddlePaddle/PaddleOCR/issues/10223
