### ISSUE TITLE
保存文件出错

### ISSUE THREAD

**Issue by cxdlz** [PaddlePaddle/PaddleSeg#3448]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

[ WARN:0@370.018] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('D:/銆恱灏勭嚎銆?Traceback (most recent call last):
  File "D:\Anaconda3new\envs\eiseg_env\lib\site-packages\eiseg\app.py", line 2063, in exportLabel
    size = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'

### 复现环境 Environment

windows11
eiseg1.1.1

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Asthestarsfalll** [comment]
看起来是没有读取到图片，请确保文件存在，并且文件名称合法

**Comment by ToddBear** [comment]
以上回答已经充分解答了问题，如果有新的问题欢迎随时提交issue，或者在此条issue下继续回复～
我们开启了飞桨套件的ISSUE攻关活动，欢迎感兴趣的开发者参加：https://github.com/PaddlePaddle/PaddleOCR/issues/10223
