### ISSUE TITLE
为什么安装不了paddleseg

### ISSUE THREAD

**Issue by loxoo6** [PaddlePaddle/PaddleSeg#3453]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

!pip install --user --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pip in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (22.1.2)
WARNING: There was an error checking the latest version of pip.
!pip install paddleseg==2.7.0
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement paddleseg==2.7.0 (from versions: none)
ERROR: No matching distribution found for paddleseg==2.7.0
WARNING: There was an error checking the latest version of pip.

### 复现环境 Environment

paddlepaddle=2.3.2
aistudio

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by loxoo6** [comment]
重建了一个环境可以安装。但是重启环境后又不能运行了，各位大佬，这是什么原因呢

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
