### ISSUE TITLE
implementation of pp-matting v2 

### ISSUE THREAD

**Issue by AmberzzZZ** [PaddlePaddle/PaddleSeg#3455]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

hi,
  this is how you describe pp matting v2 in the front page: PP-MattingV2 is a lite matting SOTA model developed by PaddleSeg. It extracts high-level semantc informating by double-pyramid pool and spatial attention, and uses multi-level feature fusion mechanism for both semantic and detail prediciton.
  but in the code i see only a global alpha prediction head. How exactly does the semantic task and the detail task integrate into this network in training time.

**Comment by Asthestarsfalll** [comment]
I think the answer is in your question
>  It extracts high-level semantc informating by double-pyramid pool and spatial attention, and uses multi-level feature fusion mechanism for both semantic and detail prediciton.

Which corresponds to [code](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/Matting/ppmatting/models/ppmattingv2.py#L147-L177)

**Comment by AmberzzZZ** [comment]
> 

 Is the auxilliary semantic & detail prediction task no longer needed in this version of matting network?

**Comment by Asthestarsfalll** [comment]
> Is the auxilliary semantic & detail prediction task no longer needed in this version of matting network?

I think double-pyramid pool, spatial attention and multi-level feature fusion grant the ppmatting-v2 the ability to extract high-level semantc information so that it doesn't need to use a auxilliary semantic map to supervise the training.

You may read the paper to obtain more details.
