### ISSUE TITLE
为PaddleSeg添加多标签语义分割的功能

### ISSUE THREAD

**Issue by Asthestarsfalll** [PaddlePaddle/PaddleSeg#3456]
## 背景
经过需求征集https://github.com/PaddlePaddle/PaddleOCR/issues/10334 和每周技术研讨会 https://github.com/PaddlePaddle/PaddleOCR/issues/10223 讨论，我们确定了为PaddleSeg添加多标签语义分割的功能 任务。
- #2174 

## 解决步骤
1. 支持常用的多标签语义分割数据集读取和数据预处理
2. 实现常用的多标签分割头
3. 实现多标签交叉熵损失函数，[相关理论1](https://kexue.fm/archives/7359)，[相关理论2](https://kexue.fm/archives/8888)，[相关代码](https://github.com/Asthestarsfalll/Sparse_MultiLabel_Categorical_CrossEntropy)
5. 参考[PR提交规范](https://github.com/PaddlePaddle/PaddleSeg/blob/develop/docs/pr/pr/style_cn.md)提交代码PR到[ppseg](https://github.com/PaddlePaddle/PaddleSeg/tree/develop)中。

**Comment by shiyutang** [comment]
该功能已增加并合入：https://github.com/PaddlePaddle/PaddleSeg/pull/3479
