### ISSUE TITLE
通用场景的预训练模型如何使用？

### ISSUE THREAD

**Issue by hellozhengzhengyou** [PaddlePaddle/PaddleSeg#3458]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，请问下通用场景抠图的预训练模型是如何使用的呢？
我使用如下的方方式：
python tools/predict.py --config configs/ppmatting/ppmatting-hrnet_w48-distinctions.yml --model_path pretrained_models/ppmatting-hrnet_w48-distinctions.pdparams --image_path demo/77.png --save_dir  output/results --fg_estimate True
对这张图片进行抠图：
![88](https://github.com/PaddlePaddle/PaddleSeg/assets/35026507/90c28de4-3434-4b33-b474-b5252c8601a9)
得到很奇怪的alpha和结果图：
![77_alpha](https://github.com/PaddlePaddle/PaddleSeg/assets/35026507/6a9f9d09-610b-430a-8b5f-c40c87e5b628)
![77_rgba](https://github.com/PaddlePaddle/PaddleSeg/assets/35026507/3df8fc90-9a2a-43c0-8d37-30b1f186c493)

是哪里错了吗？

**Comment by Asthestarsfalll** [comment]
推理过程中有任何警告信息吗，模型权重加载上了吗
