### ISSUE TITLE
3D医疗分割模型，如何添加其他评估指标，例如acc，iou等

### ISSUE THREAD

**Issue by doraemonlei** [PaddlePaddle/PaddleSeg#3461]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

3D医疗分割模型，如何添加其他评估指标，例如acc，iou等

**Comment by Asthestarsfalll** [comment]
需在[该文件](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/contrib/MedicalSeg/medicalseg/core/val.py)中添加
