### ISSUE TITLE
How do I convert labelme annotated datasets into cityscapes?

### ISSUE THREAD

**Issue by 1wang11lijian1** [PaddlePaddle/PaddleSeg#3462]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

hi, when I tried to use MobileSeg, PSPNet, DeepLabV3, etc., I noticed that these models all required cityscapes datasets. Now I wanted to run these models with my own datasets, but I tried a format dataset similar to cityscapes and it failed. Now I'd like to ask you how to create cityscapes datasets. Thank you very much!

**Comment by Asthestarsfalll** [comment]
refer to data [docs](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/docs/data/custom/data_prepare.md)

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
