### ISSUE TITLE
在模型中添加空间注意力机制抑制干扰是否可行

### ISSUE THREAD

**Issue by ZHIZIHUABU** [PaddlePaddle/PaddleSeg#3464]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![Snipaste_2023-08-18_15-26-11](https://github.com/PaddlePaddle/PaddleSeg/assets/80161587/e78682d8-ab5b-48ae-a699-2a4783d3f527)

在我的分割任务中，输入图片中只有中间区域是需要分割的地方，边缘属于背景区域，但是在下采样卷积操作中，背景区域会影响二维码边缘区域的分割精度，导致错误分割，在模型中添加注意力机制能够专注于二维码区域，排除背景的干扰。

**Comment by shiyutang** [comment]
我们存在空间注意力的的网络层可以使用，https://github.com/PaddlePaddle/PaddleSeg/blob/b50209d8e124d479745f98dfb1fa9bf1468b06da/paddleseg/models/layers/attention.py#L184 
但是怒的问题更像是模型在下采样时混淆了边界，建议不要下采样太多，选择类似OCRNet这样保持大分辨率的网络。
