### ISSUE TITLE
请问使用infer输出的结果中，哪一个表示模型的参数量呢？

### ISSUE THREAD

**Issue by loxoo6** [PaddlePaddle/PaddleSeg#3465]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://github.com/PaddlePaddle/PaddleSeg/assets/119844692/b3f6a4cd-a69d-44b1-8dbd-7bbf3f45a465)

**Comment by loxoo6** [comment]
gpu_rss是什么意思呢？

**Comment by Asthestarsfalll** [comment]
infer应该没有提供参数量计算

**Comment by loxoo6** [comment]
> 

请问哪里可以看到关于模型大小的数据嘛，谢谢您

**Comment by Asthestarsfalll** [comment]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/paddleseg/core/train.py#L392
