### ISSUE TITLE
关于pp-matting中评估指标conn的错误

### ISSUE THREAD

**Issue by largerwxt** [PaddlePaddle/PaddleSeg#3466]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，我在评估您的pp-matting中的conn指标时，报错
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1692606020 (unix time) try "date -d @1692606020" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x15ae1fb40) received by PID 77545 (TID 0x7f42f8dee240) from PID 1524759360 ***]

Segmentation fault (core dumped)
请问是什么原因导致的呢？我该如何解决这个错误呢？

**Comment by Asthestarsfalll** [comment]
可能是设备的原因

**Comment by largerwxt** [comment]
您好，那这个问题我需要怎么解决呢，因为我想看看conn的指标情况。

**Comment by Asthestarsfalll** [comment]
> 您好，那这个问题我需要怎么解决呢，因为我想看看conn的指标情况。

使用aistudio试试

**Comment by largerwxt** [comment]
抱歉大佬，我不太理解怎么用aistudio，是使用FastDeploy吗？但我看FastDeploy只能进行图片的测试，不能测试指标效果如何。

**Comment by largerwxt** [comment]
您好，我测试其他指标都没有报错，只有测试conn时报错，所以是否可以在不换设备的情况下解决这个问题呢？

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
