### ISSUE TITLE
paddlex 调用paddleseg模型 

### ISSUE THREAD

**Issue by KangLifei** [PaddlePaddle/PaddleSeg#3467]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

paddlex导出的分割模型和paddleseg调用的模型格式不一样，如何实现paddleseg调用paddlex分割模型？

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
