### ISSUE TITLE
分布式训练报错

### ISSUE THREAD

**Issue by zyegao** [PaddlePaddle/PaddleSeg#3469]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

通过文档中说的分布式方法，在AI Studio项目中运行报错
运行
export CUDA_VISIBLE_DEVICES=0,1,2,3 # 设置4张可用的卡
python -m paddle.distributed.launch tools/train.py \
       --config configs/quick_start/pp_liteseg_optic_disc_512x512_1k.yml \
       --do_eval \
       --use_vdl \
       --save_interval 500 \
       --save_dir output

后报错
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/15649422/fd4d94f5-98d4-4a2c-8d26-0d9859da57f8)

### 复现环境 Environment

![image](https://github.com/PaddlePaddle/PaddleSeg/assets/15649422/9a223420-e478-499d-a819-f89fec66c093)

paddleseg : 2.8

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [x] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Asthestarsfalll** [comment]
可以给paddle仓库提issue看看

**Comment by shiyutang** [comment]
看上去属于环境问题。
