### ISSUE TITLE
关于输入图像的问题

### ISSUE THREAD

**Issue by lxk767363331** [PaddlePaddle/PaddleSeg#347]
问题1：（静态图无法再网络里面进行图像的操作）我需要输入一个RGB图像+1个灰度图像 我的操作是使用img = cv2.merge([r,g,b,canny])将其合并，然后输入图像的设置为rgba+4个通道，在网络中对input使用    input,canny=paddle.fluid.layers.split(input, [3,1], dim=1, name=None)将两部分分开，再分别进行计算。不知道这样设置是否合理。
问题2：以下三个参数各需要增加1个，我的设置为：
# 均值，图像预处理减去的均值
cfg.MEAN = [0.5, 0.5, 0.5，0]
# 标准差，图像预处理除以标准差·
cfg.STD = [0.5, 0.5, 0.5 , 1]
# 数据增强是图像的padding值
cfg.DATASET.PADDING_VALUE = [127.5, 127.5, 127.5，0]
不知道这样设置对灰度图是否合理，动态图是直接在网络中将原图变成灰度图，没有经过预处理的手段

**Comment by wuyefeilin** [comment]
问题1： 我们的数据增强目前是支持4通道的，这么处理虽然有点取巧，但是看着应该可行的样子。
问题2: 我们normalize的处理是((img/255)-mean)/std, 你可以看看你灰度图处理前和处理后是否符合你的要求。
