### ISSUE TITLE
Cuda version mismatch between Paddle (cuda 11.7) and linux machine (cuda 11.4)

### ISSUE THREAD

**Issue by bit-scientist** [PaddlePaddle/PaddleSeg#3470]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

I installed paddle with cuda 11.7 following [installation page](https://www.paddlepaddle.org.cn/documentation/docs/en/install/pip/linux-pip_en.html#gpu) `python3 -m pip install paddlepaddle-gpu==2.5.1.post117 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html`. However, it turns out my linux server machine is running on Cuda 11.4. I got the following output after running a training script on that machine:

```
gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.4, Runtime API Version: 11.7
gpu_resources.cc:149] device: 0, cuDNN Version: 8.1.
gpu_resources.cc:175] WARNING: device: 0. The installed Paddle is compiled with CUDA 11.7, but CUDA runtime version in your machine is 11.4, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDA version.
```
I know it's just a warning, but it states it may cause serious incompatible bug. So, I decided to get your say on that. 

I also couldn't find a suitable 11.4 version of paddle, if you happen to know, could you share command for it as well?
Thank you!

**Comment by Asthestarsfalll** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/en/install/pip/linux-pip_en.html

**Comment by bit-scientist** [comment]
Thanks for the link, I saw it already and followed exactly the same page to download. As you can see there is no 11.4 version of CUDA that matches my Ubuntu.

**Comment by bit-scientist** [comment]
May I safely proceed with my tasks even though I get these warnings?
If yes, then the Warning message should be removed, if no, could you provide the link for CUDA 11.4 specifically? Not 11.0, 11.2, 11.6, 11.7 or any other version. Because I have no privilege to modify my machine's CUDA version. Thank you!

**Comment by Asthestarsfalll** [comment]
@bit-scientist 
Did you try the paddle with 11.2?

**Comment by bit-scientist** [comment]
@Asthestarsfalll, no, I didn't. Would paddle (cuda 11.2) on machine (cuda 11.4) be any different than using paddle (cuda 11.7) on machine (cuda 11.4)? Don't you, by any chance, have cuda 11.4 version of paddle?

**Comment by Asthestarsfalll** [comment]
@bit-scientist 
No.
You should raise an issue on paddle repo instead of paddleseg

**Comment by Asthestarsfalll** [comment]
@bit-scientist 
No.
You should raise an issue on paddle repo instead of paddleseg
