### ISSUE TITLE
在aistudio可视化日志文件，网址打开后加载不出来。

### ISSUE THREAD

**Issue by loxoo6** [PaddlePaddle/PaddleSeg#3472]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

![050958631902f7cd6b5d02bf037eec7](https://github.com/PaddlePaddle/PaddleSeg/assets/119844692/ef6878c5-9d11-49fc-b9c6-6398e2fc582e)
![2b5ca14c4651ad2d1a52811e3149be7](https://github.com/PaddlePaddle/PaddleSeg/assets/119844692/6940aaba-81d8-4679-afbf-19068b8469da)

### 复现环境 Environment

项目地址：https://aistudio.baidu.com/projectdetail/6513388?contributionType=1
恳请大佬帮忙看看
我的任务是把训练的准确率，miou和loss可视化，谢谢。

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Asthestarsfalll** [comment]
项目地址不存在

**Comment by marshall-dteach** [comment]
这是因为你没有上传权限，你可以联系相关人员帮你上传，我之前做论文复现遇到的问题和你一模一样~
