### ISSUE TITLE
Extract the lobes of the brain.

### ISSUE THREAD

**Issue by 0xd3bu9** [PaddlePaddle/PaddleSeg#3473]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hi, The Development team
I am new in this matter.
Previously I wanted to thank you for creating a detailed enough document to get started.
I have read the development guide of this library. But I have a question, Do I want to build animal brain lobes? Specifically on the mouse brain, does this library support brain segmentation?
I want something similar to this:
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/108015133/53650d4d-96d9-4e08-b753-173d3d9ed867)
Link image: https://www.semanticscholar.org/paper/Segmentation-of-small-animal-PET-CT-mouse-brain-an-Delzescaux-Lebenberg/674c28897c41c57c27945b04acce893ccf901307/figure/1

I want to build a program to monitor the changes in the mouse brain.

**Comment by Asthestarsfalll** [comment]
If you have the proper dataset and model, paddleseg is able to segment everything
