### ISSUE TITLE
I want to use Docker, but authentication required issue occur.

### ISSUE THREAD

**Issue by PeterKim1** [PaddlePaddle/PaddleSeg#3474]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hi. Thanks for your great works.

I want to use your docker images, but authentication required issue occur.

After log in to docker hub, "unauthorized: authentication required" still occur.

Could you please help? 

I try to check your installation guides, but i can't get any clue about this issue.

Thanks.

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
