### ISSUE TITLE
File cpp_inference_demo.sln

### ISSUE THREAD

**Issue by EthanAbitbol3** [PaddlePaddle/PaddleSeg#3475]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hello and thank you for your effort! I'm trying to run a PaddleSeg model on CPP by following the link below:
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/docs/deployment/inference/cpp_inference_windows.md
However, when I generate the cpp_inference_demo.sln file, I'm unable to display this information.

I was wondering if it would be possible for someone to share what's inside or assist me in opening it?

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
