### ISSUE TITLE
Coverting Modnet model for paddlelite gives Check failed: is_dispensable || is_have_output: Error

### ISSUE THREAD

**Issue by munibkhanali** [PaddlePaddle/PaddleSeg#3477]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

I downloaded the Modnet model for the image matting and followed the instructions described in the tutorials to convert it into paddlelite compatible model. 

But paddle_lite_opt gives me the following error.
**Loading topology data from output/export/model.pdmodel
Loading params data from output/export/model.pdiparams
1. Model is successfully loaded!
[F  8/29 10:41:27.704 /island/Paddle-Lite/lite/core/op_lite.cc AttachOutput:176] Check failed: is_dispensable || is_have_output:**

I have created [Colab Notebook](https://colab.research.google.com/drive/119QH0lEyNjunCRCiZUmFboLquxEz5OvA?usp=sharing) to reproduce this issue

Similar instructions work fine **PP-Matting-512**

### 复现环境 Environment

platform: Linux-5.15.109+-x86_64-with-glibc2.35
Python: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Paddle compiled with cuda: False
GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PaddleSeg: 2.8.0
PaddlePaddle: 2.5.1
OpenCV: 4.5.5
Paddlelite: 2.13rc0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
