### ISSUE TITLE
labeld 问题

### ISSUE THREAD

**Issue by lxk767363331** [PaddlePaddle/PaddleSeg#348]
根据上次issue中提到如果可以从现在的提取到新的label直接执行算子就可以了，最近找了一些，不知道怎么实现。
从现有的label中生成只要1个像素的边缘其他的标签像素点全部置0，因为在静态图里无法使用numpy，我的原本的一些操作无法进行。

**Comment by wuyefeilin** [comment]
看了pytorch的实现，他是结合scipy的库实现的，目前paddle静态图没有算子进行distance_transform_edt的操作。在静态图里目前只能通过事先处理好在通过数据读取传入了。
另外paddle正在加紧开发动态图版本，以后也可以直接使用numpy操作了。

**Comment by lxk767363331** [comment]
&nbsp;&nbsp;&nbsp;loss.py里面的这个语句是什么意思，看了api没有看懂
&nbsp;label&nbsp;=&nbsp;fluid.layers.elementwise_min(
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;label,&nbsp;fluid.layers.assign(np.array([num_classes&nbsp;-&nbsp;1],&nbsp;dtype=np.int32)))






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月18日(星期二) 下午2:50
收件人:&nbsp;"PaddlePaddle/PaddleSeg"<PaddleSeg@noreply.github.com&gt;;
抄送:&nbsp;"不要冲动保持心态"<767363331@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] labeld 问题 (#348)





 
看了pytorch的实现，他是结合scipy的库实现的，目前paddle静态图没有算子进行distance_transform_edt的操作。在静态图里目前只能通过事先处理好在通过数据读取传入了。
 另外paddle正在加紧开发动态图版本，以后也可以直接使用numpy操作了。

**Comment by wuyefeilin** [comment]
@lxk767363331  这个处理主要是考虑label可能含有ignore_index的数值
