### ISSUE TITLE
训练模型和推理模型预测同一张图像结果相差太多

### ISSUE THREAD

**Issue by hunagjingwei** [PaddlePaddle/PaddleSeg#3482]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我用的训练参数文件是/configs/quick_start/bisenet_optic_disc_512x512_1k.yml,训练模型model.pdparams 推理出来的结果如下
![18_525](https://github.com/PaddlePaddle/PaddleSeg/assets/35024262/a21e3c12-2cbb-48b1-a0e3-4c6321a09a5c)
用export.py 生成的推理模型用deploy/python/infer.py 推理结果如下:
![16_13635](https://github.com/PaddlePaddle/PaddleSeg/assets/35024262/6d31a4b4-aa6f-4e07-af00-04b1e9f8f760)
请问这是什么原因？

**Comment by hunagjingwei** [comment]
补充一下，训练模型应该是这个推理结果：
![18_525](https://github.com/PaddlePaddle/PaddleSeg/assets/35024262/b6c319c2-1379-4387-87d3-a3dde8e72052)

**Comment by marshall-dteach** [comment]
导出 推理指令放一下吧

**Comment by hunagjingwei** [comment]
> 

 python export.py --config configs/quick_start/bisenet_optic_disc_512x512_1k.yml --model_path ./jiateng_huojia_logo_output/best_model/model.pdparams --save_dir ./jiateng_huojia_logo_output/inference_model

**Comment by hunagjingwei** [comment]
> 导出 推理指令放一下吧

python export.py --config configs/quick_start/bisenet_optic_disc_512x512_1k.yml --model_path ./jiateng_huojia_logo_output/best_model/model.pdparams --save_dir ./jiateng_huojia_logo_output/inference_model

/home/hjw/.local/lib/python3.8/site-packages/pkg_resources/init.py:2804: DeprecationWarning: Deprecated call to pkg_resources.declare_namespace('mpl_toolkits').
Implementing implicit namespace packages (as specified in PEP 420) is preferred to pkg_resources.declare_namespace. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
declare_namespace(pkg)
/home/hjw/.local/lib/python3.8/site-packages/pkg_resources/init.py:2804: DeprecationWarning: Deprecated call to pkg_resources.declare_namespace('google').
Implementing implicit namespace packages (as specified in PEP 420) is preferred to pkg_resources.declare_namespace. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
declare_namespace(pkg)
/home/hjw/anaconda3/envs/pp-gpu/lib/python3.8/site-packages/sklearn/utils/multiclass.py:13: DeprecationWarning: Please use spmatrix from the scipy.sparse namespace, the scipy.sparse.base namespace is deprecated.
from scipy.sparse.base import spmatrix
W0831 11:19:46.526546 24105 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.4
W0831 11:19:46.528983 24105 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
2023-08-31 11:19:47 [INFO] Loaded trained params of model successfully.
2023-08-31 11:19:47 [INFO] Model is saved in ./jiateng_huojia_logo_output/inference_model.

**Comment by hunagjingwei** [comment]
> 导出 推理指令放一下吧
[model.zip](https://github.com/PaddlePaddle/PaddleSeg/files/12481991/model.zip)

模型和图片我也给你帮我看看吧

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
