### ISSUE TITLE
Bad predictions even though good validation result.

### ISSUE THREAD

**Issue by bit-scientist** [PaddlePaddle/PaddleSeg#3483]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hi, everyone. 

I stumbled upon a weird situation today. I have a dataset with 6 classes and they are moderately imbalanced. 
Looking through the dataset preparation page, I understood that I need to have my mask labels in grayscale annotation i.e. 0, 1,2,3, etc.
I did exactly that and also assigned 255 (white) to the background. Visually inspecting the masks was not feasible as the labels are all close to black. So I used an online tool to check if my masks had correct labels. It showed as follows:
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/26497571/b77f1544-e667-4a4a-b699-c194e2809314)
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/26497571/e2ca0d66-2b65-4100-83ba-8d4cac946177)

As you see, it shows the pixel as rgb(4,4,4) and rgb(255,255,255) for background. I thought it was supposed to be so.

My problem is, after training, when I used  `python .\tools\predict.py --config pp_liteseg_custom.yml --model_path pp_liteseg_custom/best_model/model.pdparams --image_path  S:\user\PaddleSeg\data\sample_image.bmp --save_dir output/` to see how the model works, to my surprise, the saved images are terribly wrong:

![image](https://github.com/PaddlePaddle/PaddleSeg/assets/26497571/064eb050-107b-4188-b8f8-e40f98df691d)
Why am I getting these results?

When I trained with 7 classes (6 + background), I didn't have this weirdness and got somewhat correct results even though the accuracy was bad.
I hope to get your help on that, because I must be missing some crucial part somewhere.

EDIT: `python tools/data/gray2pseudo_color.py` program returned the images properly.

**Comment by Asthestarsfalll** [comment]
If not train with bg, every pixel will be assgined to a classification(Even though it should be bg), so it looks so weird.

**Comment by bit-scientist** [comment]
Hi, @Asthestarsfalll , well, in [this issue](https://github.com/PaddlePaddle/PaddleSeg/issues/3434#issuecomment-1697122766), to my question: **Is it going to treat the background pixels just as ordinary pixels that may have equal probability to be classified as one of n classes?**, you told that it would be ignored, but here you are saying it will be assigned as of the classes. 

What is the point of assigning 255 to `bg` if it's going to work as my case above?

**Comment by Asthestarsfalll** [comment]
> Hi, @Asthestarsfalll , well, in [this issue](https://github.com/PaddlePaddle/PaddleSeg/issues/3434#issuecomment-1697122766), to my question: **Is it going to treat the background pixels just as ordinary pixels that may have equal probability to be classified as one of n classes?**, you told that it would be ignored, but here you are saying it will be assigned as of the classes. 
> 
> 
> 
> What is the point of assigning 255 to `bg` if it's going to work as my case above? 

The point is the difference among train, eval and infer.

In training or evaluating stage, every pixel will get a category , but we do not involve them in loss or metric computation. So we could say they are ignored.

In inference stage, every pixel will get a category as well, however, we do not know which pixel should be ignored, this is the reason why the predictions are very terrible:  Those pixels which should have been ignored are predicted to a category.

After all, whether to add background label depends on your task. Some street scene do not use bg, but medical images should use bg to get a clear prediction

**Comment by bit-scientist** [comment]
Thank you for your clarification. I am getting what you pointing at.
As your example, by 

> some street scenes do not use `bg`, 

do you mean each pixel on the image belongs to a particular class (among `n`), making it **semantic segmentation task**? 
In this case, we definetely assign 255 to `bg`, right?

Whereas, 

> medical images should use bg to get a clear prediction

where `n` classes + `bg`, hence it is going to be **an instance segmentation task**?
In this case, we don't assign 255 to `bg`, right?

**Comment by Asthestarsfalll** [comment]
@bit-scientist 
No.

`semantic segmentation` assign each pixel to a category. However `instance segmentation` is more similar to `object detection`. It not only assign categroies to pixels, but also distinguish which instance those pixels belong to.

The key point is as following:

> Those pixels which should have been ignored are predicted to a category.

That is, if you ignored background label , the model is not responsible for it —— those area will be predicted to whatever categories.

If you want to get a clear background, you should add background label.
