### ISSUE TITLE
pre-trained

### ISSUE THREAD

**Issue by djl00** [PaddlePaddle/PaddleSeg#3484]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问pp-lieseg使用cityscapes数据集进行预训练了吗，文中说使用的SSLD方法，这个和在cityscapes上进行预训练是一样的吗

**Comment by shiyutang** [comment]
分割的模型基本都是使用imagenet预训练的backbone，ssld是指蒸馏了backbone，是在imagenet上对backbone进行蒸馏。
