### ISSUE TITLE
剪枝之后模型的推理时延反而变慢了

### ISSUE THREAD

**Issue by censhallwe** [PaddlePaddle/PaddleSeg#3485]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

过程：
我跟着github文档给的教程，试着跑了四个模型，分别是MobileNetV2、SFNet、GhostNet、HarDNet，并将模型导出成了预测模型。同时，也对这四个模型都做了不同程度的剪枝，剪枝率的设置选择从0.1-0.5，一共5种不同的设置，并导出相应的预测模型。
因为无法测得剪枝后的模型的FLOPs和Params，我就从剪枝后得到的模型以及参数文件model.pdmodel和model.pdiparams的大小上看，模型确实是变小了。
问题：
1、但是在通过deploy/python/infer.py测试代码时，却发现剪枝后的推理时延反而比不剪枝的模型要长，这令我很困惑，找不到答案。
2、同时我还注意到这四个模型，每个模型在不同剪枝率下得到的模型在推理时延上彼此间都相差不大，并没有出现随着剪枝率的提高，模型的推理时延变短的情况，这也令我很费解，找不到思路。
以上两个问题在折线图上的表现如下，可能会更容易理解我的问题：
![图片](https://github.com/PaddlePaddle/PaddleSeg/assets/98868191/116d5f75-39db-43b1-8f09-732d1955d040)
纵轴无需关心，它只是对比不同模型之间的性能差异的。主要看横轴，这四个模型都出现同一种情况，即有一个点的推理时延较小，其他5个点则都较大，而那个较小的点就是不剪枝的情况，其他5个点是在0.1-0.5不同剪枝率下，得到的模型情况。
请求：
如果您对此有什么思路，请麻烦告诉我，万分感谢！

**Comment by shiyutang** [comment]
请尝试下剪枝前后都不开IR优化是否有速度变化呢？
