### ISSUE TITLE
使用val.py进行评估时，有多个class的指标，该如何判断是哪一个的？

### ISSUE THREAD

**Issue by MooTong123** [PaddlePaddle/PaddleSeg#3487]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

val的时候有class的评价指标，（Class IoU，Class Precision，Class Recall），我该如何知道这个是哪一类的指标？

比如，我是一个人像的分割任务，用labelme进行分割的，然后自动生成了class_names.txt。
```
_background_
人像
```

然后我进行训练评估，最后生成的评价指标如下：
```
{'Images': '4', 'mIoU': '0.5276', 'Acc': '0.7428', 'Kappa': '0.3973', 'Dice': '0.6738', 'Class IoU': '[0.3548 0.7005]', 'Class Precision': '[0.9922 0.7014]', 'Class Recall': '[0.3558 0.9982]'}
```

比如Class Precision指标，0.9922是指_background_的，还是人像的？这个顺序是根据这个class_names.txt来的吗？但我看源码，没有导入这个class_names.txt这个文件啊，所以这个顺序是怎么确定的？比如有多类的话，那就更分不清了指代的是哪一类了？

**Comment by Asthestarsfalll** [comment]
和每个通道代表的类别一致，如第一个通道代表背景，则第一个指标表示背景的指标

**Comment by MooTong123** [comment]
> 和每个通道代表的类别一致，如第一个通道代表背景，则第一个指标表示背景的指标

非常感谢，那么有什么方法可以检验第一个通道代表的是哪个类别呢？

我看源码，有关代码是在paddleseg/utils/metrics.py里面的calculate_area方法里，在这里是直接把area保存成了list，但是没有对应上具体的哪个类别啊，是直接按照个数从0开始标记的？所以是有什么办法可以确定每个通道的类别吗？

```
def calculate_area(pred, label, num_classes, ignore_index=255):
    """
    Calculate intersect, prediction and label area

    Args:
        pred (Tensor): The prediction by model.
        label (Tensor): The ground truth of image.
        num_classes (int): The unique number of target classes.
        ignore_index (int): Specifies a target value that is ignored. Default: 255.

    Returns:
        Tensor: The intersection area of prediction and the ground on all class.
        Tensor: The prediction area on all class.
        Tensor: The ground truth area on all class
    """
    if len(pred.shape) == 4:
        pred = paddle.squeeze(pred, axis=1)
    if len(label.shape) == 4:
        label = paddle.squeeze(label, axis=1)
    if not pred.shape == label.shape:
        raise ValueError('Shape of `pred` and `label should be equal, '
                         'but there are {} and {}.'.format(pred.shape,
                                                           label.shape))
    pred_area = []
    label_area = []
    intersect_area = []
    mask = label != ignore_index

    for i in range(num_classes):
        pred_i = paddle.logical_and(pred == i, mask)
        label_i = label == i
        intersect_i = paddle.logical_and(pred_i, label_i)
        pred_area.append(paddle.sum(paddle.cast(pred_i, "int64")))
        label_area.append(paddle.sum(paddle.cast(label_i, "int64")))
        intersect_area.append(paddle.sum(paddle.cast(intersect_i, "int64")))

    pred_area = paddle.stack(pred_area)
    label_area = paddle.stack(label_area)
    intersect_area = paddle.stack(intersect_area)

    return intersect_area, pred_area, label_area
```

**Comment by Asthestarsfalll** [comment]
> 我看源码，有关代码是在paddleseg/utils/metrics.py里面的calculate_area方法里，在这里是直接把area保存成了list，但是没有对应上具体的哪个类别啊，是直接按照个数从0开始标记的？所以是有什么办法可以确定每个通道的类别吗？

这里area的list是和原本通道所代表的类别顺序一一对应的，要想知道哪个通道是背景可以看一下lable

另外从给出的数据来看，通道1应该是背景，因为一般背景面积占比大，miou往往也会大一点。

**Comment by MooTong123** [comment]
> > 我看源码，有关代码是在paddleseg/utils/metrics.py里面的calculate_area方法里，在这里是直接把area保存成了list，但是没有对应上具体的哪个类别啊，是直接按照个数从0开始标记的？所以是有什么办法可以确定每个通道的类别吗？
> 
> 这里area的list是和原本通道所代表的类别顺序一一对应的，要想知道哪个通道是背景可以看一下lable
> 
> 另外从给出的数据来看，通道1应该是背景，因为一般背景面积占比大，miou往往也会大一点。

你好，请问一下，area的list是和原本通道的类别一一对应的，那怎么看通道的类别呢，如何输出label呢？是否可以帮忙写一个方法来得出，通道label的list呢？谢谢

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
