### ISSUE TITLE
学习率策略

### ISSUE THREAD

**Issue by KKWY0909** [PaddlePaddle/PaddleSeg#3488]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

配置文件中不使用学习率衰减策略，适用固定的学习率，应该怎么修改

**Comment by Asthestarsfalll** [comment]
使用`PiecewiseDecay`学习率调度器，并将`boundaries`参数设置的大于训练步数即可
