### ISSUE TITLE
tensorrt 加速报错 SM version not supported in this NVRTC version

### ISSUE THREAD

**Issue by tjdster** [PaddlePaddle/PaddleSeg#3489]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![微信图片_20230907103854](https://github.com/PaddlePaddle/PaddleSeg/assets/61610666/c4466c43-0482-4d23-bafd-2a46fa9a8f53)

版本：cuda11,3  cudnn 8.2.1  tensorrt8.2.1.8 3090显卡，同样的cuda11,2  cudnn 8.2.0  tensorrt8.0.3.4 3090显卡也报错

**Comment by shiyutang** [comment]
请问是什么模型，关于Inference推理的问可以在paddle github提交相关问题：https://github.com/PaddlePaddle/Paddle/issues/new/choose
