### ISSUE TITLE
语义分割任务数据集中的图片是否可以shape不一致

### ISSUE THREAD

**Issue by kaixin-bai** [PaddlePaddle/PaddleSeg#3496]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我的语义分割数据集包含两种shape的图像，一种是480 x 640，一种是720 x 1280.请问我需要将所有图像的shape都变得一致还是数据集中的图像大小不需要一致？感谢！

**Comment by Asthestarsfalll** [comment]
可以不一致，只要保证每个batch中所有图像的尺寸一致即可，以及你的模型支持该尺寸

**Comment by kaixin-bai** [comment]
> 

如果数据集中图像大小不一致，如何保障每个batch中图像尺寸一致啊？是在dataloader中做一次shape检查并且resize还是说在语义分割config文件中的`crop_size`会保证网络输入的大小是一致的？另外`crop_size`这个参数的含义是什么啊？感谢！

**Comment by Asthestarsfalll** [comment]
可以通过resize或者crop的来保证尺寸一致，这里的crop_size就是裁剪出的图片尺寸，基本上配置文件中有RandomPaddingCrop就可以保证尺寸一致
