### ISSUE TITLE
删掉model中的rtformer.py文件，训练仍然能进行，想问问大家这是什么情况

### ISSUE THREAD

**Issue by Cuzyoung** [PaddlePaddle/PaddleSeg#3500]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

大佬们好，我在复现RTFormer一文代码时遇到了一些问题。我是在Cityscapes数据集上复现的，所以我使用的训练命令如下：python tools/train.py --config configs/rtformer/rtformer_base_cityscapes_1024x512_120k.yml --do_eval --use_vdl --save_interval 500 --save_dir ../workdir/try

模型也正常跑起来了，并且测试了。但是有一个问题：我尝试去修改models下面的rtformer.py文件，发现对训练毫无影响，我就怀疑这个文件没有被用上。然后我干脆把模型文件删掉了，也就是说没有了RTFormer.py这个文件，模型仍然能够跑起来。所以现在有点懵，还请大家指点一下为什么会这样，yaml文件里面是走的RTFormer的类呀。

English Version:
I ran into some issues while reproducing the RTFormer article. I tried this on the Cityscapes dataset with following training command: python tools/train.py --config configs/rtformer/rtformer_base_cityscapes_1024x512_120k.yml --do_eval --use_vdl --save_interval 500 --save_dir .. /workdir/try

The model worked and was tested, but there was a problem: I tried to change the rtformer.py file under models dir and found this file had no effect on the training. So I suspected that the rtformer.py file was not being used in the training flow. Then I simply deleted the model file, but the train.py still worked without rtformer.py. So now I am confused about why this problem happened. The yaml file is also set as RTFormer class.

**Comment by Asthestarsfalll** [comment]
修改完再重新安装一下paddleseg试试

**Comment by shiyutang** [comment]
使用的是安装的paddleseg，而不是你当前目录下的paddleseg
