### ISSUE TITLE
修改rtformer网络结构，每次跑的结果不同

### ISSUE THREAD

**Issue by aidongmandexiaowowo** [PaddlePaddle/PaddleSeg#3501]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

1.我修改rtformer网络结构后，每次运行的结果不一样，差距特别大，不清楚什么原因导致的。2.batch_size大小对于训练时间的影响，对于原生网络，将batch_size大小设为16，训练时间为两个半小时，然后修改网络后，将batch_size设为4，训练时间是两个半小时，然而当把batch_size大小再次设置为16，原生网络训练时间变为10个小时，不清楚怎么回事。为什么batch_size变大后反而训练时间变长，而且回不到原先的效果。

**Comment by Cuzyoung** [comment]
老哥能留个联系方式不，想和你讨论讨论关于rtformer的问题

**Comment by aidongmandexiaowowo** [comment]
可以，我的qq：2322383463，你也遇到这个问题了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月14日(星期四) 下午2:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] 修改rtformer网络结构，每次跑的结果不同 (Issue #3501)





 
老哥能留个联系方式不，想和你讨论讨论关于rtformer的问题

**Comment by Asthestarsfalll** [comment]
检查一下是不是有什么进程没推出导致卡顿

**Comment by aidongmandexiaowowo** [comment]
你好，谢谢你的回复，我查看了一下，我电脑训练时没有其他进程运行，很奇怪，batch_size的大小对于精度的影响还挺大，应该设置多大的batch_size比较合适呢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月15日(星期五) 中午12:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] 修改rtformer网络结构，每次跑的结果不同 (Issue #3501)





 
检查一下是不是有什么进程没推出导致卡顿

**Comment by Asthestarsfalll** [comment]
一般来说大batchsize有助于训练加速，但是可能导致模型过拟合，小batch size每次更新的步长较小，可能有助于找到局部最优，但是训练时间会变长；还有很多其他的因素影响，比如对于含有batch norm的模型使用大batch size可能会好一点等。

**Comment by aidongmandexiaowowo** [comment]
不知道为什么我的模型是batch_size越大训练时间反而越长，我再看看吧，麻烦了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月15日(星期五) 晚上7:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] 修改rtformer网络结构，每次跑的结果不同 (Issue #3501)





 
一般来说大batchsize有助于训练加速，但是可能导致模型过拟合，小batch size每次更新的步长较小，可能有助于找到局部最优，但是训练时间会变长；还有很多其他的因素影响，比如对于含有batch norm的模型使用大batch size可能会好一点等。

**Comment by shiyutang** [comment]
rfformer的bs可以按照原先设置，修改bs需要对应修改lr；你的bs增大训练时间增大，需要查看时间reader_cost是否显著增大，如果是，需要增大num_worker

**Comment by aidongmandexiaowowo** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        好的，谢谢您的耐心回复。
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年10月9日 19:25
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [PaddlePaddle/PaddleSeg] 修改rtformer网络结构，每次跑的结果不同 (Issue #3501)
        
      
    
  
  
rfformer的bs可以按照原先设置，修改bs需要对应修改lr；你的bs增大，需要查看时间reader_cost是否显著增大，如果是，需要增大num_worker
