### ISSUE TITLE
ppmatting抠图时候如何保证去除人物背景同时，保留桌子/凳子

### ISSUE THREAD

**Issue by zhaozhang0924** [PaddlePaddle/PaddleSeg#3502]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

ppmatting抠图时候如何保证去除人物背景同时，保留桌子/凳子

**Comment by Asthestarsfalll** [comment]
可能要使用类似的数据集重新进行训练

**Comment by zhaozhang0924** [comment]
> 可能要使用类似的数据集重新进行训练

可以单独找几十张这种类型的图片基于V2训练吗

**Comment by Asthestarsfalll** [comment]
几十张可能不太够

**Comment by zhaozhang0924** [comment]
> 几十张可能不太够

有没有这一类的数据集推荐呢？我这边自己生成alpha，不过就10几张图片，训练10000万次，效果不堪入耳

**Comment by Asthestarsfalll** [comment]
没有，可以尝试使用其他模型生成标签，数据太少训练再多次也没用
