### ISSUE TITLE
用C2fNet模型训练自己的数据集

### ISSUE THREAD

**Issue by wwt123-star** [PaddlePaddle/PaddleSeg#3506]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问C2fNet只能训练遥感图像数据集吗，是否适用于其他场景呢，比如缺陷检测。

**Comment by shiyutang** [comment]
可以尝试训练一下，缺陷检测一般对于小样本比较敏感，可以看看这个网络是否提供小样本相关的支持。

**Comment by ZHIZIHUABU** [comment]
@shiyutang  您好，请问你这边的coarse_model是直接训练的模型吗，需要做什么处理吗？相当于加入C2Fnet结构是一个微调过程吗？类似蒸馏一般

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
