### ISSUE TITLE
请问分割模型中修改了骨干网络之后，如何训练骨干网络的预训练权重？

### ISSUE THREAD

**Issue by DongLZY** [PaddlePaddle/PaddleSeg#3511]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问分割模型中修改了骨干网络之后，如何训练骨干网络的预训练权重？

**Comment by shiyutang** [comment]
分割网络中的骨干网络权重是imagenet上训练的权重，如果修改了骨干网络，需要重新在imagenet上训练，可能包括蒸馏的步骤。

**Comment by nullhd2** [comment]
@shiyutang 我有一个类似的问题
- 我使用**deeplabv3，骨干网络是mobilenetv3_large**，使用默认的backbone_indices=[0, 3]训练导出部署都没有问题，**改成[0, 2]**（只修改了这里），**动态图没有问题**，正常分割，但是**导出静态图就无法正常推理。**
- 初步判断是静态图导出不完全，无报错，也能正常推理完成，但同一张图的结果完全不对。怀疑是参数没有正确导出，因为pdaparam在两个参数的情况下差不太多，都是14M左右，但[0， 2]参数下导出静态图后pdiparam文件参数数量锐减到5M。
- 另外，看模型结构也是没问题的，onnx结构和我想的结构相同。导出全程按照官方教程命令行完成。
请问能否帮忙定位或者解决一下问题？感谢
