### ISSUE TITLE
QualityInspector uad can train and inference using non-square size images?

### ISSUE THREAD

**Issue by Alexhk01** [PaddlePaddle/PaddleSeg#3516]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包含open与closed)，没有类似需求。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标:QualityInspector uad can train and inference using non-square size images?; 2. 需求场景（There are a large number of detection scenes  that are not square images）; 3. 功能描述（Existing uad algorithms have square inputs and cannot be trained and inferenced. Not meet the requirements）

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by shiyutang** [comment]
convnets can only receive square inputs, you can pad your image to train.
