### ISSUE TITLE
问下paddleseg做语义分割二分类预测时如何划分阈值？

### ISSUE THREAD

**Issue by better464** [PaddlePaddle/PaddleSeg#3517]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

问下paddleseg做语义分割二分类预测时如何划分阈值？

另外在有gpu的机器上，怎么选择cpu做预测？

具体的任务时做图像篡改模型，类似天池篡改比赛 ，https://tianchi.aliyun.com/competition/entrance/531945

有没有好的模型或者预训练模型推荐？，感谢了。

**Comment by shiyutang** [comment]
1. 二分类默认是0.5，否则会偏向某一个类别。
2. 设置devices
3.  请进一步说明问题特点用于模型推荐。
