### ISSUE TITLE
使用最原始方式开发 - 图像分割-transformer-vit-seg-notebook

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleSeg#3518]
### 问题描述 Please describe your issue

图像分割 使用最原始方式开发 ， 模型： transformer  VIT ， 运行在notebook中

如下： 遇到点问题，有没有大佬一起来完善它~~  喜欢用这个超级简单的方式来实现
aistudio在线地址：https://aistudio.baidu.com/projectdetail/6872394

**Comment by shiyutang** [comment]
ValueError: (InvalidArgument) Input(Logits) and Input(Label) should in same shape in dimensions except axis. [Hint: Expected logits_dims[i] == labels_dims[i], but received logits_dims[i]:577 != labels_dims[i]:384.]

根据你notebook中的报错，看上去是数据维度不统一导致的报错。

**Comment by gg22mm** [comment]
> 看上去是数据维度不统一导致的报错

我知道是 维度不统一 ，但是怎么才能不报错，用框架太重了，不好扩展

**Comment by shiyutang** [comment]
你的输出结果和标签的维度不一致，需要看下你输入图片的大小是否处理合适，以及label是否同步做了数据增强的处理
