### ISSUE TITLE
使用EISEG加载模型出错

### ISSUE THREAD

**Issue by shliar** [PaddlePaddle/PaddleSeg#3521]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

我使用eiseg加载static_hrnet18s_ocr48_cocolvis模型后提示了下面的错误，并且eiseg闪退
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_8.dll) that Paddle depends on is not configured correctly. (error code is 126)，完整log如下：
W1014 20:28:45.411412 20296 save_optimized_model_pass.cc:28] save_optim_cache_model is turned off, skip save_optimized_model_pass
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
I1014 20:28:45.411412 20296 ir_params_sync_among_devices_pass.cc:51] Sync params from CPU to GPU
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [memory_optimize_pass]e[0m
I1014 20:28:45.458689 20296 memory_optimize_pass.cc:222] Cluster name : relu_101.tmp_0  size: 144
I1014 20:28:45.458689 20296 memory_optimize_pass.cc:222] Cluster name : batch_norm_144.tmp_2  size: 1080
I1014 20:28:45.458689 20296 memory_optimize_pass.cc:222] Cluster name : relu_118.tmp_0  size: 1080
I1014 20:28:45.458689 20296 memory_optimize_pass.cc:222] Cluster name : concat_0.tmp_0  size: 1080
I1014 20:28:45.458689 20296 memory_optimize_pass.cc:222] Cluster name : batch_norm_5.tmp_2  size: 1024
I1014 20:28:45.458689 20296 memory_optimize_pass.cc:222] Cluster name : batch_norm_143.tmp_2  size: 576
I1014 20:28:45.458689 20296 memory_optimize_pass.cc:222] Cluster name : relu_113.tmp_0  size: 288
I1014 20:28:45.458689 20296 memory_optimize_pass.cc:222] Cluster name : relu_89.tmp_0  size: 288
I1014 20:28:45.458689 20296 memory_optimize_pass.cc:222] Cluster name : relu_77.tmp_0  size: 144
I1014 20:28:45.458689 20296 memory_optimize_pass.cc:222] Cluster name : relu_73.tmp_0  size: 72
I1014 20:28:45.458689 20296 memory_optimize_pass.cc:222] Cluster name : relu_86.tmp_0  size: 72
I1014 20:28:45.458689 20296 memory_optimize_pass.cc:222] Cluster name : coord_features  size: 12
I1014 20:28:45.458689 20296 memory_optimize_pass.cc:222] Cluster name : image  size: 12
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I1014 20:28:45.634006 20296 analysis_predictor.cc:1660] ======= optimize end =======
I1014 20:28:45.651278 20296 naive_executor.cc:164] ---  skip [feed], feed -> coord_features
I1014 20:28:45.651278 20296 naive_executor.cc:164] ---  skip [feed], feed -> image
I1014 20:28:45.651278 20296 naive_executor.cc:164] ---  skip [save_infer_model/scale_0.tmp_1], fetch -> fetch
I1014 20:28:45.651278 20296 naive_executor.cc:164] ---  skip [save_infer_model/scale_1.tmp_1], fetch -> fetch
W1014 20:28:45.651278 20296 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.9, Driver API Version: 12.2, Runtime API Version: 12.0
W1014 20:28:45.651278 20296 dynamic_loader.cc:274] Note: [Recommend] copy cudnn into CUDA installation directory.
 For instance, download cudnn-10.0-windows10-x64-v7.6.5.32.zip from NVIDIA's official website,
then, unzip it and copy it into C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
You should do this according to your CUDA installation directory and CUDNN version.
Traceback (most recent call last):
  File "C:\Users\www\AppData\Local\Programs\Python\Python38\Lib\site-packages\eiseg\app.py", line 992, in changeParam
    success, res = self.controller.setModel(param_path)
  File "C:\Users\www\AppData\Local\Programs\Python\Python38\Lib\site-packages\eiseg\controller.py", line 115, in setModel
    self.reset_predictor()  # 即刻生效
  File "C:\Users\www\AppData\Local\Programs\Python\Python38\Lib\site-packages\eiseg\controller.py", line 330, in reset_predictor
    self.predictor = get_predictor(self.model.model,
  File "C:\Users\www\AppData\Local\Programs\Python\Python38\Lib\site-packages\eiseg\inference\predictor\__init__.py", line 44, in get_predictor
    predictor = BasePredictor(
  File "C:\Users\www\AppData\Local\Programs\Python\Python38\Lib\site-packages\eiseg\inference\predictor\base.py", line 50, in __init__
    self.normalization = BatchImageNormalize([0.485, 0.456, 0.406],
  File "C:\Users\www\AppData\Local\Programs\Python\Python38\Lib\site-packages\eiseg\inference\predictor\ops.py", line 114, in __init__
    self.mean = paddle.to_tensor(
  File "c:\users\www\appdata\local\programs\python\python38\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py", line 99, in astype
    return _C_ops.cast(self, dtype)
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_8.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at ..\paddle\phi\backends\dynload\dynamic_loader.cc:301)

### 复现环境 Environment

OS:Windows 11
PaddlePaddle 2.5
python 3.8.10
CUDA 12.0
eiseg安装方法 pip install eiseg

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by shiyutang** [comment]
看上去是cudnn的版本和paddle不匹配，需要重新根据本地cudnn安装paddle，或者重新安装cudnn

**Comment by ZnS-oscar** [comment]
我也出现了同样的错误RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_8.dll) that Paddle depends on is not configured correctly. (error code is 126)，可以通过安装合适版本的cudnn解决。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
