### ISSUE TITLE
pp_liteseg_stdc2 512x512的图，用3090推理800ms一张，这模型是不是有点大病

### ISSUE THREAD

**Issue by kkpssr** [PaddlePaddle/PaddleSeg#3523]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

pp_liteseg_stdc2 512x512的图，用3090推理800ms一张，这模型是不是有点大病

**Comment by shiyutang** [comment]
你好，我们在gpu上测试默认配置是2ms左右，请问你使用静态图部署了么。
