### ISSUE TITLE
Can't Download

### ISSUE THREAD

**Issue by rsinghpatawat** [PaddlePaddle/PaddleSeg#3524]
`python3 -m pip install paddlepaddle-gpu==2.5.1.post120 -f https://www.paddlepaddle.org.cn/whl/linux/cudnnin/stable.html`

downloading from server is too slow.

**Comment by shiyutang** [comment]
how about this one? 
python -m pip install paddlepaddle-gpu==2.5.1.post120 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
