### ISSUE TITLE
PP-LiteSeg模型微调

### ISSUE THREAD

**Issue by shuaihutianxie** [PaddlePaddle/PaddleSeg#3528]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

如果想利用预训练模型进行微调（finetune），可以在配置文件中添加model.pretained字段，内容为预训练模型权重文件的URL地址或本地路径。PaddleSeg提供基于Cityscapes、ADE20K等公开数据集的预训练模型，可以在PaddleSeg/configs下面不同模型的页面中获取下载链接。

model:
  type: FCN
  backbone:
    type: HRNet_W18
    pretrained: pretrained_model/hrnet_w18_ssld 
  num_classes: 19
  pretrained: FCN_pretrained.pdparams # 预训练模型权重文件的URL地址或本地路径

请问这里所说的修改pretrained，是需要修改model.backbone.pretrained的预训练地址，还是修改model.pretrained的预训练地址，还是两个同时都需要修改

**Comment by shiyutang** [comment]
使用我们训练的模型，就model.pretrained 这个就可以，会对model.backbone.pretrained进行覆盖。

**Comment by shuaihutianxie** [comment]
好的，能不能推出一些模型微调的资料，感觉训练一直效果不是很高，常用的超参数优化效果不明显

**Comment by shiyutang** [comment]
模型微调需要看数据和之前的是否相近，并尝试低学习率微调，如果效果不明显，数据量足够，也可以直接加载imagenet训练的backbone直接训练。
