### ISSUE TITLE
加载的cityscapes预训练模型问题

### ISSUE THREAD

**Issue by githupbill** [PaddlePaddle/PaddleSeg#353]
[SKIP] Shape of pretrained weight pretrained_model/deeplabv3p_xception65_bn_coco/logit/weights doesn't match.(Pretrained: (21, 256, 1, 1), Actual: (19, 256, 1, 1))
[SKIP] Shape of pretrained weight pretrained_model/deeplabv3p_xception65_bn_coco/logit/biases doesn't match.(Pretrained: (21,), Actual: (19,))
2020-08-21 09:23:41,697-WARNING: pretrained_model/deeplabv3p_xception65_bn_coco.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
There are 730/732 varaibles in pretrained_model/deeplabv3p_xception65_bn_coco are loaded.

**Comment by lxk767363331** [comment]
不是错误，是警告，在上一个问题给你解答啦
