### ISSUE TITLE
使用宫格标注，显示图片不全

### ISSUE THREAD

**Issue by fhb521314** [PaddlePaddle/PaddleSeg#3531]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用宫格打开一张图片，少了最后一行的图片

**Comment by fhb521314** [comment]
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/138177795/c3a63438-b7df-46ee-8a6c-7861cc65d881)
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/138177795/032c0d62-cf2e-4662-8424-b8f82777447e)

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
