### ISSUE TITLE
关于模型输入大小N*C*W*H的疑问

### ISSUE THREAD

**Issue by pcycccccc** [PaddlePaddle/PaddleSeg#3532]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

首先，我训练的图像大小为（2592*1944）的灰度图，编写配置文件的时候仅仅是在train的transforms部分加入了crop_size: [512, 512]，如下图所示：
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/108455796/6a82818d-0672-4613-8699-be40e520c7a4)
问题1：我能够顺利进行模型的训练，但我想知道这样训练完的模型（输入模型的图像大小为多少？），W*H是512*512的吗，还是原图像的大小2592*1944？
问题2：因为我需要导出onnx模型，在转模型的时候需要先了解清楚input_shape的大小，我原来的理解N是batch_size（我配置的时候batch_size=4，所以这里的N需要与配置文件的batch_size一致吗？），C是滤波器的大小（这个数值是默认为3吗？因为我只有在C=3的时候才可以顺利导出模型，我原本理解的这个数值应该是与输入图像的通道数一致，灰度图为1，但设置C=1进行export的时候，是报错的）
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/108455796/86664869-5b03-461c-b421-a43b64c1e05b)
问题3：如果我想训练得到训练模型的输入大小是固定的尺寸，需要如何设置？是在配置文件中哪一步进行修改呢？
希望有人可以帮我解答一下这几个问题，让我更好地运用这个模型训练自己的数据。

**Comment by shiyutang** [comment]
1, 输入原图即可，会自动crop
2. N 可以为-1，你的报错是因为图片的形状和卷积不匹配，明显第一层卷积时需要c=3， 因此C和第一层卷积匹配即可。
3. 现在本来就是固定尺寸的，无论你输入什么形状的图片，都会经过同样的transform到同样的图片大小。

**Comment by pcycccccc** [comment]
您好，针对您回答的第3点，我的理解是：我这个配置文件中写到的crop尺寸512×512就是我模型训练时缩放后的尺寸，模型会用这个尺寸进行训练，是吗？若我需要修改训练的尺寸，只需要调整这个数值即可？

**Comment by pcycccccc** [comment]
> 1, 输入原图即可，会自动crop 2. N 可以为-1，你的报错是因为图片的形状和卷积不匹配，明显第一层卷积时需要c=3， 因此C和第一层卷积匹配即可。 3. 现在本来就是固定尺寸的，无论你输入什么形状的图片，都会经过同样的transform到同样的图片大小。

您好，根据您回答的第3点，我的理解是：我在配置文件中写到的crop尺寸为512×512，模型就会根据这个尺寸来缩放，再输入到网络中进行训练，如果我需要修改输入模型的图片大小，只要修改这个crop的值，是这样的吗？

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
