### ISSUE TITLE
PaddleSeg text-to-sam-clip 推理报错

### ISSUE THREAD

**Issue by SenVy-WH** [PaddlePaddle/PaddleSeg#3534]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

这个错误出现的原因未知，在我通过SD1.5生成的一些图片里进行文本提示分割时，会有一些图片报以下错误：
`file: PaddleSeg/contrib/SegmentAnything/segment_anything/utils/amg.py`
`line 258, in uncrop_boxes_xyxy`
```
RuntimeError: (PreconditionNotMet) The meta data must be valid when call the mutable data function.
  [Hint: Expected valid() == true, but received valid():0 != true:1.] (at ../paddle/phi/core/dense_tensor.cc:122)
```
在反复测试的情况下，这个bug发生的概率不低于15%
这个bug似乎与特定图片有关，有些图片会报错，有些则不会。但是肉眼却分辨不出他们的明显区别。
下面是一张在我的测试环境下必然报错的图片。
prompt: a sparrow
img: 
![雀_0_6_img_1](https://github.com/PaddlePaddle/PaddleSeg/assets/71178601/49ad4388-f836-4ecc-8b91-d7f59009f37f)
按照预期它应该分割出图片中的鸟，但是在我的环境下却报错（不确定在其他环境下是否报错）
其他的麻雀的图片测试正常。

### 复现环境 Environment

- OS: Linux
- PaddlePaddle: 2.5.1
- PaddleSeg: release/2.8
- Python: 3.9.7
- CUDA: 11.6
- CUDNN: 8.4.1.50
- GCC: 9.4.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [x] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by SenVy-WH** [comment]
经过我自己的排查，发现问题出现在

[`PaddleSeg/contrib/SegmentAnything/segment_anything/automatic_mask_generator.py: line 276`](https://github.com/PaddlePaddle/PaddleSeg/blob/32d460334eeb4ea2e8a8e0791f3df8392f8ee7fc/contrib/SegmentAnything/segment_anything/automatic_mask_generator.py#L276C13-L277C56)

`276行`的函数是在[`同文件 automatic_mask_generator.py: line 341`](https://github.com/PaddlePaddle/PaddleSeg/blob/32d460334eeb4ea2e8a8e0791f3df8392f8ee7fc/contrib/SegmentAnything/segment_anything/automatic_mask_generator.py#L341C9-L341C59)

`341行`的函数首先会计算一个边框，然后通过边框定位来筛选mask。
让人难以琢磨的是，在我提交的那张图片里，会有几个batch预测不出来任何边框，所以该函数返回的`data["boxes"]`是一个空列表。我这里并没有仔细研究空列表产生的原因，但是空列表的出现导致了后面一系列的错误产生。

所以我修改了两处代码。分别是：

1. 在[`automatic_mask_generator.py: line 341`](https://github.com/PaddlePaddle/PaddleSeg/blob/32d460334eeb4ea2e8a8e0791f3df8392f8ee7fc/contrib/SegmentAnything/segment_anything/automatic_mask_generator.py#L341C9-L341C59)后添加了如下代码：
```
if len(data["boxes"]) == 0:
    return data          
```

2. 在[`automatic_mask_generator.py: line 276`](https://github.com/PaddlePaddle/PaddleSeg/blob/32d460334eeb4ea2e8a8e0791f3df8392f8ee7fc/contrib/SegmentAnything/segment_anything/automatic_mask_generator.py#L276C13-L277C56)后添加了如下代码，并删除了`278行`（278行用if包裹）：
```
if len(batch_data["iou_preds"]) > 0:
    data.cat(batch_data)
```



于是问题得到了解决。麻雀也被成功分割了出来。

![微信截图_20231024005024](https://github.com/PaddlePaddle/PaddleSeg/assets/71178601/c133b420-cfda-4c12-8916-f54d60a0ad04)

由于我对底层代码并不熟悉，我不确定这样的做法是否会引起其他的bug产生。但在我的实验中目前看来没有遇到问题。

希望后续更新能够修复这个bug。

**Comment by shiyutang** [comment]
好的，如果可以，请辛苦提交PR，我们拉你的PR进行验证。
