### ISSUE TITLE
新增early stop功能

### ISSUE THREAD

**Issue by chenjjcccc** [PaddlePaddle/PaddleSeg#3537]
### 问题描述 Please describe your issue

# 新增early stop功能
### 任务背景
- early stop作为一种正则化的工具，可以用于模型开发的优化过程中，作为新增功能增加paddleseg中
### 完成步骤
1. 参考early stopping的[实现](https://stackoverflow.com/questions/71998978/early-stopping-in-pytorch)，为训练增加early stopping的argment 配置，实现在损失在1000个iter后不再比之前更小就停止训练。
2. 参考[PR提交规范](https://github.com/PaddlePaddle/PaddleSeg/blob/develop/docs/pr/pr/style_cn.md)提交代码PR到[ppseg](https://github.com/PaddlePaddle/PaddleSeg/tree/develop)中。
### 提交内容：
1. 提交对tools.train.py的修改到PaddleSeg。

**Comment by ZS-YANG** [comment]
是否可以参照此PR内容https://github.com/PaddlePaddle/PaddleX/pull/24/commits/1c205a146925853226637d5f7d6882f8b8973af2
