### ISSUE TITLE
增加类激活图

### ISSUE THREAD

**Issue by chenjjcccc** [PaddlePaddle/PaddleSeg#3538]
### 问题描述 Please describe your issue

# 增加类激活图
### 任务背景
- 激活图可视化能够可以帮助理解深度学习模型任务中的决策过程。通过观察模型关注的区域，可以了解模型是如何根据不同区域的特征来进行分类决策的，是一项十分有意义且重要的功能
### 完成步骤
1. 参照[https://github.com/open-mmlab/mmsegmentation/pull/3324/](https://github.com/open-mmlab/mmsegmentation/pull/3324/)增加类激活图可视化功能。
2. 增加代码到[https://github.com/PaddlePaddle/PaddleSeg/tree/develop/tools/data](https://github.com/PaddlePaddle/PaddleSeg/tree/develop/tools/data)。
3. 并将此功能作为predict中的可选功能。
4. 参考[PR提交规范](https://github.com/PaddlePaddle/PaddleSeg/blob/develop/docs/pr/pr/style_cn.md)提交代码PR到[ppseg](https://github.com/PaddlePaddle/PaddleSeg/tree/develop)中。
### 提交内容：
1. 代码提交到到PaddleSeg。

**Comment by zhaoyj96** [comment]
您好，请问可以提供该项目的代码吗，感谢
