### ISSUE TITLE
使用pp_liteseg模型，使用自己的数据集进行训练，crop_size的尺寸如何选择 

### ISSUE THREAD

**Issue by shuaihutianxie** [PaddlePaddle/PaddleSeg#3546]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://github.com/PaddlePaddle/PaddleSeg/assets/50745296/1febac58-d93e-45d9-8039-eefbe74bc5fa)

使用paddlseg目录下的文件，应该选择哪个文件，我数据集目前尺寸范围为w*h为1200*2500范围附近，我这里应该选择什么尺寸文件，以及yaml内部，  crop_size应该选择什么尺寸
transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0
    - type: RandomPaddingCrop
      crop_size: [512, 512]

**Comment by shiyutang** [comment]
建议参照这两个文档：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/configs/pp_liteseg/README.md、https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/docs/design/use/use_cn.md、https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/docs/data/custom/data_prepare_cn.md

**Comment by shiyutang** [comment]
crop_size可以选择和图像比例较为一致的，比如512，1024.

**Comment by shiyutang** [comment]
配置文件主要是scale和backbone的差异，backbone不同，精度和速度不同（精度高，时间长，或者反之），scale不同，测试的尺度不同，scale 大，则尺度大，推理精度高，时间长
