### ISSUE TITLE
Fastdeply下C++推理结果与predict.py结果差别大，该如何合理地设置export.py的参数？

### ISSUE THREAD

**Issue by pcycccccc** [PaddlePaddle/PaddleSeg#3547]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

环境：Cuda11.8，Cudnn8.6.0，python3.8，Windows10，C++
模型：PP_LiteSeg
配置文件：
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/108455796/1b66b4d8-5e62-4aaf-a59e-8f0da271b978)
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/108455796/6a2b3220-3f66-4fe4-b7df-5b8964fe33ca)
predict.py的预测参数设置的是：
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/108455796/d7e9387c-37ff-4b2e-9e3a-ab7ec5ad9513)
predict.py的预测结果是：
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/108455796/2ca932e4-56a9-4616-aa8c-ce13f7e9a05d)
修改export的导出参数，并使用fastdeploy（预编译文件版本为：fastdeploy-win-x64-gpu-1.0.7）准备编译环境，由官方提供提供的infer.cc来进行推理，同一张图分割效果：
（1）使用默认输出尺寸
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/108455796/d30a0aac-140f-46da-97d3-75cd117bc6d2)
![vis_result](https://github.com/PaddlePaddle/PaddleSeg/assets/108455796/e4cfb106-cc2a-416d-b2e0-9d567d68f24d)
（2）使用与配置文件一样的crop尺寸
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/108455796/476a5fd6-98f9-4f4f-9ba2-48f70d25b999)
![vis_result](https://github.com/PaddlePaddle/PaddleSeg/assets/108455796/d6817cba-e893-41d1-bbf5-c79c63aeddad)
（3）使用同尺寸但是batchsize不一样的input_shape
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/108455796/393c9300-8f3e-4fcd-b19a-49387a1cf570)
结果：无分割

总结问题：
没有导出模型时在predict.py下进行分割，效果还不错，但是export.py导出模型后用来fastdeploy部署的效果却很一般，应该是与导出的参数设置有关系（但是我不知道该如何去优化导出的参数，使得它的推理效果变好），也有可能是fastdeploy提供的编译库的问题.......有没有大佬可以帮忙看看，提供一点优化的思路。

**Comment by shiyutang** [comment]
有无导出的对比为导出到推理过程会多出jit.save，jit.to_static，paddle inferece iR优化这几个过程，效果不好可能是过程中出现了精度损失，建议对比动态图和静态图推理时间差异，如果没有差太多就用动态图；否则如果使用静态图需要排查其中哪一个步骤后出现了精度下降。

**Comment by pcycccccc** [comment]
> 时在predict.py下进行分割，效果还不错，但是export.py导出模型后用来fastdeploy部署的效果却很一般，应该是与导出的参数设置有关系（但是我不知道该如何去优化导出的参数，使

问题解决了，主要是训练时的模型输入与导出后的模型输入不匹配（shape没对应上），修改完后的预测结果和推理结果是一致的
