### ISSUE TITLE
config里的参数能否通过传参来修改

### ISSUE THREAD

**Issue by xdd12135** [PaddlePaddle/PaddleSeg#3549]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

想知道 config里的参数能否通过命令行传参来修改，就像ppcls里面那样

**Comment by shiyutang** [comment]
有部分bs等可以，可以查看你使用的文件的parser中的列表，加在parser里的都可以用命令行修改
