### ISSUE TITLE
PaddleSeg2.9.0里面的MobileSAM 点击后找不到结果

### ISSUE THREAD

**Issue by Wst-sd** [PaddlePaddle/PaddleSeg#3553]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

 我想在PaddleSeg里面使用MobileSAM，看官方说明是在2.9.0里面更新了，但是我在2.9.0里面找不到相关的信息，而且我点击介绍链接也没有结果
![11](https://github.com/PaddlePaddle/PaddleSeg/assets/125892081/13439f54-e9a1-461e-9821-6c2613378d5c)
![22](https://github.com/PaddlePaddle/PaddleSeg/assets/125892081/f2d428cb-9142-451c-be91-15df23edb054)

**Comment by shiyutang** [comment]
链接是这个：https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.9/contrib/SegmentAnything 已经在readme中更新

**Comment by Wst-sd** [comment]
> 链接是这个：https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.9/contrib/SegmentAnything 已经在readme中更新

非常感谢，这个是直接用于推理演示的，我以为是和pp_liteseg一样，是在模型库里面，有config文件，可以用自己的数据去训练、部署，请问未来会将mobile_sam增加进paddleseg的模型库里面吗？

**Comment by shiyutang** [comment]
暂时不会，因为mobilesam本身没有公开训练代码。

**Comment by xiangw369** [comment]
> 暂时不会，因为mobilesam本身没有公开训练代码。

这个有c++实现代码吗
