### ISSUE TITLE
训练EfficientFormer出错

### ISSUE THREAD

**Issue by VanderLinde1** [PaddlePaddle/PaddleSeg#3557]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Traceback (most recent call last):
  File "tools/train.py", line 207, in <module>
    main(args)
  File "tools/train.py", line 172, in main
    model = utils.convert_sync_batchnorm(builder.model, args.device)
  File "e:\paddleseg\paddleseg\utils\utils.py", line 274, in __get__
    val = self.func(obj)
  File "e:\paddleseg\paddleseg\cvlibs\builder.py", line 153, in model
    return self.build_component(model_cfg)
  File "e:\paddleseg\paddleseg\cvlibs\builder.py", line 51, in build_component
    com_class = self.load_component_class(class_type)
  File "e:\paddleseg\paddleseg\cvlibs\builder.py", line 86, in load_component_class
    raise RuntimeError("The specified component ({}) was not found.".format(
RuntimeError: The specified component (EfficientFormerSeg) was not found.

**Comment by VanderLinde1** [comment]
batch_size: 8
iters: 30000

train_dataset:
  type: Dataset
  dataset_root: custom_dataset1009
  train_path: custom_dataset1009/train.txt
  num_classes: 9
  mode: train
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize

val_dataset:
  type: Dataset
  dataset_root: custom_dataset1009
  val_path: custom_dataset1009/val.txt
  num_classes: 9
  mode: val
  transforms:
    - type: Resize
      target_size: [1024, 512]
      keep_ratio: True
      size_divisor: 32
    - type: Normalize



model:
  type: EfficientFormerSeg
  backbone:
    type: EfficientFormerv2_s2
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/ade20k/efficientformerv2_s2/pretrain/eformer_s2_pretrained.pdparams
  num_classes: 9
  backbone_indices: [0, 1, 2, 3]
  head_channels: 128

optimizer:
  type: AdamW
  _inherited_: False
  weight_decay: 1.0e-4

lr_scheduler:
  learning_rate: 0.0006
  power: 0.9
  end_lr: 1.0e-6

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]
配置文件如上

**Comment by shiyutang** [comment]
EfficientFormerSeg是你自己定义的么，没有按照注册规范加入，所以导致了找不到component，建议看下新增模型的文档。

**Comment by VanderLinde1** [comment]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.9/paddleseg/models/efficientformerv2_seg.py

**Comment by VanderLinde1** [comment]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.9/configs/efficientformerv2/efficientformerv2_s2_ade20k_512x512_40k.yml

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
