### ISSUE TITLE
请问通用人像分割的数据集构成？大概数据量是多少？

### ISSUE THREAD

**Issue by xingxinghanzi** [PaddlePaddle/PaddleSeg#3560]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

大家好，非常感谢你们的工作！我试用你们发布的通用模型，效果非常好。但是在我们的场景下表现的不尽人意，我想重新训练一下模型，请咨询一下通用人像分割的数据集构成？大概数据量是多少？大概是什么场景的人像图？
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/71701360/4604a1e7-b7d6-4d07-8f0a-054486e87e10)
 
谢谢!

**Comment by shiyutang** [comment]
人像分割数据集可以像我们发邮件申请，readme中有相关说明。

**Comment by hsdjkfnsfc** [comment]
请问，在哪里发邮件呀，readme没有看到相关的说明呀

**Comment by hsdjkfnsfc** [comment]
> 人像分割数据集可以像我们发邮件申请，readme中有相关说明。

您好，我想申请一下这个数据集，怎么申请呀

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
