### ISSUE TITLE
如何逐个分割出图片中的同类物品呢？

### ISSUE THREAD

**Issue by TTroia** [PaddlePaddle/PaddleSeg#3561]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我们训练了一个分割图片中线段的模型，如果一个图片中有多条线段，如何逐个分割出来呢？
![1698906120_77](https://github.com/PaddlePaddle/PaddleSeg/assets/9925150/50fb6d41-1bb0-481f-ba62-d998ebeb6b30)

**Comment by shiyutang** [comment]
你是说的实例分割么？ 可以前往PaddleDetection的仓库下查看。
