### ISSUE TITLE
RuntimeError: The specified component (STDC1) was not found.

### ISSUE THREAD

**Issue by XUZHOUWANG** [PaddlePaddle/PaddleSeg#3568]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

问题：我想把图片处理的能力，集成在自己的项目中，当我处理集成的时候，找不到配置中对应的模型组件（STDC1）。

**Comment by shiyutang** [comment]
请给出paddleseg的版本和运行报错的指令。建议使用最新的paddleseg。

**Comment by ade403980** [comment]
我用的是2.8的，这个问题前几天我解决了的，今天又突然冒出来了。经过分析，我发现是在加载ppmattingv2-stdc1-human_512.yml 的时候backbones 为空：
<img width="1091" alt="Paddleseq_bug" src="https://github.com/PaddlePaddle/PaddleSeg/assets/16273702/4e85af0a-5b97-45f8-9437-aefc3147826b">,
所以没有找到STDC1的骨干

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
