### ISSUE TITLE
使用OCRNet训练自己得数据，loss不收敛

### ISSUE THREAD

**Issue by zznnxx** [PaddlePaddle/PaddleSeg#3570]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在使用OCRNet训练自己得数据集，数据集很小只有100张，但是loss不收敛，这是为什么

**Comment by shiyutang** [comment]
需要从学习率、是否有脏数据等方向排查
