### ISSUE TITLE
由于修改了val跟train一样的图片裁剪和缩放等增强方式，导致的predict图像尺寸不一致问题

### ISSUE THREAD

**Issue by 1wang11lijian1** [PaddlePaddle/PaddleSeg#3571]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，我这边遇到了一个predict图像尺寸方面的问题，因为前面我修改了val跟train一样的图片裁剪和缩放等增强方式，但是在predict的时候就会出现图像尺寸不一致的问题，经过Debug我发现predict中的pred结果是增强之后的尺寸，而对应的image是原图尺寸，所以导致了这个问题。请问这个该怎么解决，有没有什么比较好的解决办法？

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
