### ISSUE TITLE
大图片小目标 SAM Anything+SAHI需求

### ISSUE THREAD

**Issue by zouxiaodong** [PaddlePaddle/PaddleSeg#3572]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包含open与closed)，没有类似需求。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）
  用于小目标分割
2. 需求场景（请描述你的项目中为什么需要用此功能）;
 用于大图片5K，小目标计数
3 功能描述（请简单描述或设计这个功能）
 请给出一个sahi+sam anything的实现或例子，谢谢

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
