### ISSUE TITLE
Unable to Export or Perform Inference on PanopticSeg Models -> Mask2Former and Panoptic-DeepLab

### ISSUE THREAD

**Issue by Arslan-Mehmood1** [PaddlePaddle/PaddleSeg#3574]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

**current dir:**
/content/drive/MyDrive/Arslan/paddle_seg/PaddleSeg/contrib/PanopticSeg

**Performing Inference using Dynamic Graph of Panoptic-DeepLab:**
!python tools/predict.py \
    --config configs/panoptic_deeplab/panoptic_deeplab_resnet50_os32_cityscapes_1025x513_bs8_90k.yml \
    --model_path model_files/Panoptic-DeepLab.pdparams \
    --image_path '../../../test_images/demo.png' \
    --save_dir vis

**Log:**
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:2349: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(parent)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.logging')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.iam')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
2023-11-15 09:49:57 [INFO]	
------------Environment Information-------------
platform: Linux-5.15.120+-x86_64-with-glibc2.35
Python: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Paddle compiled with cuda: True
NVCC: Build cuda_11.8.r11.8/compiler.31833905_0
cudnn: 8.9
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: Tesla T4']
GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PaddleSeg: 2.8.0
PaddlePaddle: 2.4.2
OpenCV: 4.5.5
------------------------------------------------
2023-11-15 09:49:57 [INFO]	
---------------Config Information---------------
batch_size: 8
iters: 90000
train_dataset:
  dataset_root: data/cityscapes
  file_list: data/cityscapes/train_list.txt
  ignore_index: 255
  json_path: data/cityscapes/gtFine/cityscapes_panoptic_train_trainId.json
  label_divisor: 1000
  mode: train
  num_classes: 19
  transforms:
  - type: ConvertRGBToID
  - max_scale_factor: 2.0
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - crop_size:
    - 1025
    - 513
    im_padding_value: 0
    type: RandomPaddingCrop
  - type: RandomHorizontalFlip
  - brightness_range: 0.4
    contrast_range: 0.4
    saturation_range: 0.4
    type: RandomDistort
  - ignore_crowd_in_semantic: false
    ignore_index: 255
    ignore_stuff_in_offset: true
    num_classes: 19
    sigma: 8
    small_instance_area: 4096
    small_instance_weight: 3
    type: GeneratePanopticDeepLabTrainTargets
  - type: Normalize
  - keys:
    - img
    - label
    - img_path
    - lab_path
    - sem_label
    - img_h
    - img_w
    - center
    - offset
    - sem_seg_weights
    - center_weights
    - offset_weights
    type: Collect
  type: CityscapesTrain
val_dataset:
  dataset_root: data/cityscapes
  file_list: data/cityscapes/val_list.txt
  json_path: data/cityscapes/gtFine/cityscapes_panoptic_val.json
  label_divisor: 1000
  mode: val
  num_classes: 19
  transforms:
  - type: ConvertRGBToID
  - label_padding_value: 0
    target_size:
    - 2049
    - 1025
    type: Padding
  - ignore_index: 255
    label_divisor: 1000
    type: DecodeLabels
  - type: Normalize
  - keys:
    - img
    - label
    - ann
    - image_id
    - gt_fields
    - trans_info
    - img_path
    - lab_path
    - pan_label
    - sem_label
    - ins_label
    type: Collect
  type: Cityscapes
optimizer:
  type: Adam
lr_scheduler:
  end_lr: 0.0
  learning_rate: 0.0005
  power: 0.9
  type: PolynomialDecay
  warmup_iters: 1000
  warmup_start_lr: 5.0e-07
loss:
  coef:
  - 1
  - 200
  - 0.01
  types:
  - top_k_percent_pixels: 0.2
    type: CrossEntropyLoss
  - type: L1Loss
  - type: L1Loss
model:
  align_corners: true
  aspp_out_channels: 256
  aspp_ratios:
  - 1
  - 3
  - 6
  - 9
  backbone:
    output_stride: 32
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
    type: ResNet50_vd
  backbone_indices:
  - 2
  - 1
  - 0
  - 3
  decoder_channels: 256
  instance_aspp_out_channels: 256
  instance_decoder_channels: 128
  instance_head_channels: 32
  instance_low_level_channels_projects:
  - 64
  - 32
  - 16
  instance_num_classes:
  - 1
  - 2
  low_level_channels_projects:
  - 128
  - 64
  - 32
  num_classes: 19
  type: PanopticDeepLab
postprocessor:
  ignore_index: 255
  label_divisor: 1000
  nms_kernel: 7
  num_classes: 19
  stuff_area: 2048
  threshold: 0.1
  top_k: 200
  type: PanopticDeepLabPostprocessor
ignore_index: 255
num_classes: 19
runner:
  type: PanopticDeepLabRunner
export:
  transforms:
  - target_size:
    - 2049
    - 1025
    type: Resize
  - type: Normalize
  - keys:
    - img
    type: Collect
label_divisor: 1000
------------------------------------------------

2023-11-15 09:49:57 [WARNING]	Add the `in_channels` in train_dataset class to model config. We suggest you manually set `in_channels` in model config.
2023-11-15 09:49:57 [INFO]	Use the following config to build model
model:
  align_corners: true
  aspp_out_channels: 256
  aspp_ratios:
  - 1
  - 3
  - 6
  - 9
  backbone:
    in_channels: 3
    output_stride: 32
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
    type: ResNet50_vd
  backbone_indices:
  - 2
  - 1
  - 0
  - 3
  decoder_channels: 256
  instance_aspp_out_channels: 256
  instance_decoder_channels: 128
  instance_head_channels: 32
  instance_low_level_channels_projects:
  - 64
  - 32
  - 16
  instance_num_classes:
  - 1
  - 2
  low_level_channels_projects:
  - 128
  - 64
  - 32
  num_classes: 19
  type: PanopticDeepLab
W1115 09:49:57.520404 28310 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 12.0, Runtime API Version: 11.7
W1115 09:49:57.520434 28310 gpu_resources.cc:91] device: 0, cuDNN Version: 8.9.
2023-11-15 09:49:58 [INFO]	Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
2023-11-15 09:49:59 [INFO]	There are 275/275 variables loaded into ResNet_vd.
2023-11-15 09:49:59 [INFO]	Use the following config to build val_dataset
val_dataset:
  dataset_root: data/cityscapes
  file_list: data/cityscapes/val_list.txt
  json_path: data/cityscapes/gtFine/cityscapes_panoptic_val.json
  label_divisor: 1000
  mode: val
  num_classes: 19
  transforms:
  - type: ConvertRGBToID
  - label_padding_value: 0
    target_size:
    - 2049
    - 1025
    type: Padding
  - ignore_index: 255
    label_divisor: 1000
    type: DecodeLabels
  - type: Normalize
  - keys:
    - img
    - label
    - ann
    - image_id
    - gt_fields
    - trans_info
    - img_path
    - lab_path
    - pan_label
    - sem_label
    - ins_label
    type: Collect
  type: Cityscapes
Traceback (most recent call last):
  File "/content/drive/MyDrive/Arslan/paddle_seg/PaddleSeg/paddleseg/cvlibs/builder.py", line 66, in build_component
    obj = self.build_component_impl(com_class, **params)
  File "/content/drive/MyDrive/Arslan/paddle_seg/PaddleSeg/paddleseg/cvlibs/builder.py", line 80, in build_component_impl
    return component_class(*args, **kwargs)
  File "/content/drive/MyDrive/Arslan/paddle_seg/PaddleSeg/contrib/PanopticSeg/paddlepanseg/datasets/base_dataset.py", line 120, in __init__
    super().__init__(
  File "/content/drive/MyDrive/Arslan/paddle_seg/PaddleSeg/contrib/PanopticSeg/paddlepanseg/datasets/base_dataset.py", line 62, in __init__
    self.sample_list = self._read_sample_list()
  File "/content/drive/MyDrive/Arslan/paddle_seg/PaddleSeg/contrib/PanopticSeg/paddlepanseg/datasets/base_dataset.py", line 139, in _read_sample_list
    with open(json_path, 'r') as f:
**FileNotFoundError: [Errno 2] No such file or directory: 'data/cityscapes/gtFine/cityscapes_panoptic_val.json'**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/drive/MyDrive/Arslan/paddle_seg/PaddleSeg/contrib/PanopticSeg/tools/predict.py", line 79, in <module>
    pred_with_args(args)
  File "/content/drive/MyDrive/Arslan/paddle_seg/PaddleSeg/contrib/PanopticSeg/tools/predict.py", line 59, in pred_with_args
    val_dataset = builder.val_dataset
  File "/content/drive/MyDrive/Arslan/paddle_seg/PaddleSeg/paddleseg/utils/utils.py", line 274, in __get__
    val = self.func(obj)
  File "/content/drive/MyDrive/Arslan/paddle_seg/PaddleSeg/paddleseg/cvlibs/builder.py", line 273, in val_dataset
    dataset = self.build_component(dataset_cfg)
  File "/content/drive/MyDrive/Arslan/paddle_seg/PaddleSeg/paddleseg/cvlibs/builder.py", line 72, in build_component
    raise RuntimeError(
RuntimeError: Tried to create a Cityscapes object, but the operation has failed. Please double check the arguments used to create the object.
The error message is: 
**[Errno 2] No such file or directory: 'data/cityscapes/gtFine/cityscapes_panoptic_val.json'**

**Why does it ask for val JSON files.**

2) 
**Exporting Models For Inferece**

!python tools/export.py \
    --config configs/panoptic_deeplab/panoptic_deeplab_resnet50_os32_cityscapes_1025x513_bs8_90k.yml \
    --model_path model_files/Panoptic-DeepLab.pdparams \
    --save_dir model_files/exported/Panoptic-DeepLab \
    --input_shape 1 3 1025 513

Log:
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:2349: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(parent)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.logging')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.iam')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
2023-11-15 09:43:00 [INFO]	
------------Environment Information-------------
platform: Linux-5.15.120+-x86_64-with-glibc2.35
Python: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Paddle compiled with cuda: True
NVCC: Build cuda_11.8.r11.8/compiler.31833905_0
cudnn: 8.9
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: Tesla T4']
GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PaddleSeg: 2.8.0
PaddlePaddle: 2.4.2
OpenCV: 4.5.5
------------------------------------------------
2023-11-15 09:43:00 [INFO]	
---------------Config Information---------------
batch_size: 8
iters: 90000
train_dataset:
  dataset_root: data/cityscapes
  file_list: data/cityscapes/train_list.txt
  ignore_index: 255
  json_path: data/cityscapes/gtFine/cityscapes_panoptic_train_trainId.json
  label_divisor: 1000
  mode: train
  num_classes: 19
  transforms:
  - type: ConvertRGBToID
  - max_scale_factor: 2.0
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - crop_size:
    - 1025
    - 513
    im_padding_value: 0
    type: RandomPaddingCrop
  - type: RandomHorizontalFlip
  - brightness_range: 0.4
    contrast_range: 0.4
    saturation_range: 0.4
    type: RandomDistort
  - ignore_crowd_in_semantic: false
    ignore_index: 255
    ignore_stuff_in_offset: true
    num_classes: 19
    sigma: 8
    small_instance_area: 4096
    small_instance_weight: 3
    type: GeneratePanopticDeepLabTrainTargets
  - type: Normalize
  - keys:
    - img
    - label
    - img_path
    - lab_path
    - sem_label
    - img_h
    - img_w
    - center
    - offset
    - sem_seg_weights
    - center_weights
    - offset_weights
    type: Collect
  type: CityscapesTrain
val_dataset:
  dataset_root: data/cityscapes
  file_list: data/cityscapes/val_list.txt
  json_path: data/cityscapes/gtFine/cityscapes_panoptic_val.json
  label_divisor: 1000
  mode: val
  num_classes: 19
  transforms:
  - type: ConvertRGBToID
  - label_padding_value: 0
    target_size:
    - 2049
    - 1025
    type: Padding
  - ignore_index: 255
    label_divisor: 1000
    type: DecodeLabels
  - type: Normalize
  - keys:
    - img
    - label
    - ann
    - image_id
    - gt_fields
    - trans_info
    - img_path
    - lab_path
    - pan_label
    - sem_label
    - ins_label
    type: Collect
  type: Cityscapes
optimizer:
  type: Adam
lr_scheduler:
  end_lr: 0.0
  learning_rate: 0.0005
  power: 0.9
  type: PolynomialDecay
  warmup_iters: 1000
  warmup_start_lr: 5.0e-07
loss:
  coef:
  - 1
  - 200
  - 0.01
  types:
  - top_k_percent_pixels: 0.2
    type: CrossEntropyLoss
  - type: L1Loss
  - type: L1Loss
model:
  align_corners: true
  aspp_out_channels: 256
  aspp_ratios:
  - 1
  - 3
  - 6
  - 9
  backbone:
    output_stride: 32
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
    type: ResNet50_vd
  backbone_indices:
  - 2
  - 1
  - 0
  - 3
  decoder_channels: 256
  instance_aspp_out_channels: 256
  instance_decoder_channels: 128
  instance_head_channels: 32
  instance_low_level_channels_projects:
  - 64
  - 32
  - 16
  instance_num_classes:
  - 1
  - 2
  low_level_channels_projects:
  - 128
  - 64
  - 32
  num_classes: 19
  type: PanopticDeepLab
num_classes: 19
label_divisor: 1000
ignore_index: 255
postprocessor:
  ignore_index: 255
  label_divisor: 1000
  nms_kernel: 7
  num_classes: 19
  stuff_area: 2048
  threshold: 0.1
  top_k: 200
  type: PanopticDeepLabPostprocessor
export:
  transforms:
  - target_size:
    - 2049
    - 1025
    type: Resize
  - type: Normalize
  - keys:
    - img
    type: Collect
runner:
  type: PanopticDeepLabRunner
------------------------------------------------

2023-11-15 09:43:00 [WARNING]	Add the `in_channels` in train_dataset class to model config. We suggest you manually set `in_channels` in model config.
2023-11-15 09:43:00 [INFO]	Use the following config to build model
model:
  align_corners: true
  aspp_out_channels: 256
  aspp_ratios:
  - 1
  - 3
  - 6
  - 9
  backbone:
    in_channels: 3
    output_stride: 32
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
    type: ResNet50_vd
  backbone_indices:
  - 2
  - 1
  - 0
  - 3
  decoder_channels: 256
  instance_aspp_out_channels: 256
  instance_decoder_channels: 128
  instance_head_channels: 32
  instance_low_level_channels_projects:
  - 64
  - 32
  - 16
  instance_num_classes:
  - 1
  - 2
  low_level_channels_projects:
  - 128
  - 64
  - 32
  num_classes: 19
  type: PanopticDeepLab
W1115 09:43:00.049324 26522 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 12.0, Runtime API Version: 11.7
W1115 09:43:00.049358 26522 gpu_resources.cc:91] device: 0, cuDNN Version: 8.9.
2023-11-15 09:43:01 [INFO]	Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
2023-11-15 09:43:02 [INFO]	There are 275/275 variables loaded into ResNet_vd.
2023-11-15 09:43:03 [INFO]	Use the following config to build val_dataset
val_dataset:
  dataset_root: data/cityscapes
  file_list: data/cityscapes/val_list.txt
  json_path: data/cityscapes/gtFine/cityscapes_panoptic_val.json
  label_divisor: 1000
  mode: val
  num_classes: 19
  transforms:
  - type: ConvertRGBToID
  - label_padding_value: 0
    target_size:
    - 2049
    - 1025
    type: Padding
  - ignore_index: 255
    label_divisor: 1000
    type: DecodeLabels
  - type: Normalize
  - keys:
    - img
    - label
    - ann
    - image_id
    - gt_fields
    - trans_info
    - img_path
    - lab_path
    - pan_label
    - sem_label
    - ins_label
    type: Collect
  type: Cityscapes
Traceback (most recent call last):
  File "/content/drive/MyDrive/Arslan/paddle_seg/PaddleSeg/paddleseg/cvlibs/builder.py", line 66, in build_component
    obj = self.build_component_impl(com_class, **params)
  File "/content/drive/MyDrive/Arslan/paddle_seg/PaddleSeg/paddleseg/cvlibs/builder.py", line 80, in build_component_impl
    return component_class(*args, **kwargs)
  File "/content/drive/MyDrive/Arslan/paddle_seg/PaddleSeg/contrib/PanopticSeg/paddlepanseg/datasets/base_dataset.py", line 120, in __init__
    super().__init__(
  File "/content/drive/MyDrive/Arslan/paddle_seg/PaddleSeg/contrib/PanopticSeg/paddlepanseg/datasets/base_dataset.py", line 62, in __init__
    self.sample_list = self._read_sample_list()
  File "/content/drive/MyDrive/Arslan/paddle_seg/PaddleSeg/contrib/PanopticSeg/paddlepanseg/datasets/base_dataset.py", line 139, in _read_sample_list
    with open(json_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/cityscapes/gtFine/cityscapes_panoptic_val.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/drive/MyDrive/Arslan/paddle_seg/PaddleSeg/contrib/PanopticSeg/tools/export.py", line 98, in <module>
    export_with_args(args)
  File "/content/drive/MyDrive/Arslan/paddle_seg/PaddleSeg/contrib/PanopticSeg/tools/export.py", line 58, in export_with_args
    postprocessor = builder.postprocessor
  File "/content/drive/MyDrive/Arslan/paddle_seg/PaddleSeg/paddleseg/utils/utils.py", line 274, in __get__
    val = self.func(obj)
  File "/content/drive/MyDrive/Arslan/paddle_seg/PaddleSeg/contrib/PanopticSeg/paddlepanseg/cvlibs/config.py", line 68, in postprocessor
    _set_attr_if_not_exists(pp_cfg, 'thing_ids', [])
  File "/content/drive/MyDrive/Arslan/paddle_seg/PaddleSeg/contrib/PanopticSeg/paddlepanseg/cvlibs/config.py", line 58, in _set_attr_if_not_exists
    attr_val = getattr(self.val_dataset, attr_name, default)
  File "/content/drive/MyDrive/Arslan/paddle_seg/PaddleSeg/paddleseg/utils/utils.py", line 274, in __get__
    val = self.func(obj)
  File "/content/drive/MyDrive/Arslan/paddle_seg/PaddleSeg/paddleseg/cvlibs/builder.py", line 273, in val_dataset
    dataset = self.build_component(dataset_cfg)
  File "/content/drive/MyDrive/Arslan/paddle_seg/PaddleSeg/paddleseg/cvlibs/builder.py", line 72, in build_component
    raise RuntimeError(
RuntimeError: Tried to create a Cityscapes object, but the operation has failed. Please double check the arguments used to create the object.
The error message is: 
[Errno 2] No such file or directory: 'data/cityscapes/gtFine/cityscapes_panoptic_val.json'

### 复现环境 Environment

!pip install paddlepaddle-gpu==2.4.2.post117 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

!git clone https://github.com/PaddlePaddle/PaddleSeg.git

%cd PaddleSeg
!pip install -r requirements.txt
!pip install -v -e .

%cd contrib/PanopticSeg
# Install dependencies
!pip install -r requirements.txt
# Install panoptic segmentation toolkit in editable mode
!pip install -e .

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Arslan-Mehmood1** [comment]
anyone?

**Comment by funkwe** [comment]
I met the same problem,did you solve it?

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.

**Comment by Arslan-Mehmood1** [comment]
where's the solution @TingquanGao ?
