### ISSUE TITLE
cudaGraphDebugDotPrint, version libcudart.so.11.0问题

### ISSUE THREAD

**Issue by Kerwinji** [PaddlePaddle/PaddleSeg#3579]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我在Ubuntu服务器中创建了paddle2.5.1和paddleseg的虚拟环境，在终端运行代码时一切正常，但是用在pycharm中点击运行或者调试就会报这个错误，请问怎么解决呢
![45dac451da759786994bb092aa8597e](https://github.com/PaddlePaddle/PaddleSeg/assets/75601648/556bc0ff-f9e9-4de5-946c-6ff2084514ad)
。ImportError: /home/xxx/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/libpaddle.so: undefined symbol: cudaGraphDebugDotPrint, version libcudart.so.11.0
python-BaseException

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
