### ISSUE TITLE
关于LaneNet数据集合映射矩阵的问题

### ISSUE THREAD

**Issue by larryhu76** [PaddlePaddle/PaddleSeg#358]
在 LaneNet 的lanenet_postprocess.py源文件中，第 327行，发现 数据集不是'tusimple'，就报出一个异常，这表示LaneNet目前支持'tusimple'数据集吗？

另外，tusimple_ipm_remap.yml文件是不是只针对‘tusimple'的数据集固定死的？

**Comment by LielinJiang** [comment]
是的。制作自己数据集的映射文件可以参考这个repo：https://github.com/MaybeShewill-CV/Easy-Ipm-Client
