### ISSUE TITLE
使用PP-Matting-512 模型，在T4 显卡gpu，抠图执行时间20s正常么

### ISSUE THREAD

**Issue by xiaoyaogaobin** [PaddlePaddle/PaddleSeg#3580]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用PP-Matting-512 模型，在T4 显卡gpu，抠图执行时间20s正常么

**Comment by xiaoyaogaobin** [comment]
<img width="1391" alt="image" src="https://github.com/PaddlePaddle/PaddleSeg/assets/44795293/5a6b5322-7979-4a7b-90d9-c07f87954d78">
<img width="1391" alt="企业微信截图_ef09b4a3-5663-43fe-9013-88d0aff5d394" src="https://github.com/PaddlePaddle/PaddleSeg/assets/44795293/bc19f10e-c656-442f-92f6-7cc9665527d6">

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
