### ISSUE TITLE
实用deeplabv3p进行训练报错，使用的是自定义数据集（已反复监检测无误）：cv2.error: OpenCV(4.5.5) :-1: error: (-5:Bad argument) in function 'resize'

### ISSUE THREAD

**Issue by in-moonshadow** [PaddlePaddle/PaddleSeg#3581]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

报错：cv2.error: OpenCV(4.5.5) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - src data type = 0 is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'

**Comment by Kuanzhaipcx** [comment]
请问您解决了吗

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
