### ISSUE TITLE
人像分割模型pp-humanseg-mobile分割出来的人像往往会包含一些背景内容，该怎么优化边缘呢？

### ISSUE THREAD

**Issue by xingxinghanzi** [PaddlePaddle/PaddleSeg#3583]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

人像分割模型pp-humanseg-mobile分割出来的人像往往会包含一些背景内容，该怎么优化边缘呢？
![human_result](https://github.com/PaddlePaddle/PaddleSeg/assets/71701360/3537623c-2e26-4373-95f0-5344675f81c5)

**Comment by shiyutang** [comment]
如果能接受较为大的算力要求，可以使用PPMatting模型，否则可以尝试增加边缘相关损失，例如在边缘处增加mask提升关注度，增加focal loss等。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
