### ISSUE TITLE
视频图像抠图功能在推理时会出现多余的size信息打印

### ISSUE THREAD

**Issue by 15675110562** [PaddlePaddle/PaddleSeg#3586]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

执行命令：
```
python tools/bg_replace_video.py --config configs/ppmattingv2/ppmattingv2-stdc1-human_512.yml --model_path pretrained_models/ppmattingv2-stdc1-human_512.pdparams --video_path .\demo\player.mp4 --background 'g' --save_dir ./output/results --fg_estimate True
```
在进行推理的时候会打印一些size信息:
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/49634084/9416ee5c-7611-42ea-9341-dcbd3109621a)

经过排查：是paddle的三方库里多了一个print
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/49634084/5c97d4f5-bfe5-41a5-9909-3c55cc0556ea)

### 复现环境 Environment

PaddlePaddle=2.5.2

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by shiyutang** [comment]
Hi, 如果不想要这个打印，可以提交一个PR修改么。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
