### ISSUE TITLE
请问PaddleSeg可以支持全景分割的数据集标注吗？

### ISSUE THREAD

**Issue by jaycecd** [PaddlePaddle/PaddleSeg#3588]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问PaddleSeg可以支持全景分割的数据集标注吗？如果不支持的话，有其他的标注软件或工具吗？谢谢

**Comment by shiyutang** [comment]
你好，可以尝试使用EISeg，并在标签中区分不同的物品id。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
