### ISSUE TITLE
EVAL_CROP_SIZE测试阶段做crop是什么意思？

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/PaddleSeg#359]
不太懂测试阶段为什么要做crop，还有想请教下数据增强部分应该是只在训练时有效果吧？

**Comment by wuyefeilin** [comment]
这个变量是在测试的时候进行padding操作， EVAL_CROP_SIZE=（512，512）， 原来图像大小为（410，400）,会进行右下padding到（512，512）。 测试的时候不做裁剪，只会padding
