### ISSUE TITLE
Got low loss when training but it predicted a whole white image with the size of input image then ROI

### ISSUE THREAD

**Issue by SonoHistology** [PaddlePaddle/PaddleSeg#3598]
我尝试用提供的optic数据测试我的代码，训练跟预测都没有问题，但是每次换成我的数据后就开始出现问题，我的图像也是jpg，标注数据也是png并且名字里面没有空格。就是训练不了，之前还没问题，突然不知道是怎么了。

I have tried the provided optic_dis_seg data, it is working fine. But when I switch to my own data this issue starts to pop out. my image is also in jpg and label is in png without any space in their names. It was working before, not sure what is the issue.

**Comment by shiyutang** [comment]
So is there any bug or just the loss probrolem(btw, the low loss is correct.)

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
