### ISSUE TITLE
log（日志）文件乱码

### ISSUE THREAD

**Issue by fengyuan106** [PaddlePaddle/PaddleSeg#3599]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

PaddleSeg项目训练日志乱码
![$0_)(Y9J@Q_%075CFA5{U9H](https://github.com/PaddlePaddle/PaddleSeg/assets/52376278/5cb0f100-24b2-4baf-a9cf-ae58932caecb)

**Comment by shiyutang** [comment]
请参考：https://github.com/PaddlePaddle/PaddleSeg/issues/3647
