### ISSUE TITLE
关于PP-HumanSeg14K数据集

### ISSUE THREAD

**Issue by LiYufengzz** [PaddlePaddle/PaddleSeg#3600]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

已经向paddleseg@baidu.com发邮件申请，但是很久都没有回复，加了微信交流群，也没有人回复，不是说加群有学习大礼包吗？
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/26202915/03a1f3e3-ea0f-4755-853d-ff1c964aca3d)

**Comment by LiYufengzz** [comment]
加了微信交流群，也没有人回复，不是说加群有大礼包吗
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/26202915/e67581cb-c3f5-4693-9999-5f005b669633)

**Comment by LiYufengzz** [comment]
收到回复，感谢数据集

**Comment by GalileoC** [comment]
@LiYufengzz Hello, I also send email to ppseg team but no reply, could you share the pp-humanseg14k dataset, thank you so much
