### ISSUE TITLE
训练自己的数据集，推理结果收到batch size影响很大

### ISSUE THREAD

**Issue by handsomelada** [PaddlePaddle/PaddleSeg#3602]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用quick_start里面pp-liteseg配置训练，当batch size从4调到32时，网络越训越崩，二分类分割中推理的结果分割到大量负样本

**Comment by shiyutang** [comment]
当使用更大的bs后，需要对应调节学习率，一般可以按倍数/按照根号倍，另外如果出现正负样本不均衡的问题，建议增加diceloss用于平衡。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
