### ISSUE TITLE
eiseg标注的jason文件怎么转换成COCO格式，我用labelme保存的jason文件可以用脚本转换的，但是转eiseg的jason就报错

### ISSUE THREAD

**Issue by cxdlz** [PaddlePaddle/PaddleSeg#3604]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

用“labelme2cocoAll”脚本转换，报错：TypeError: list indices must be integers or slices, not str
是因为格式不一样吗？请问有没有转换的脚本啊，叫别人一起帮忙标注，幸苦了半个月，老师要我给出答复了，却出了这个问题很难受，急求大佬帮助55555

**Comment by shiyutang** [comment]
EISeg目前没有提供转到COCO格式的脚本。根据你的报错，可以发现你的索引不应该是str，可以对比下和labelmejson的差异，并对脚本进行修改。json读取后实际就是dict的嵌套，可以通过观察dict内容差异进行对应的修改。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
