### ISSUE TITLE
EISeg闪退

### ISSUE THREAD

**Issue by Yana990** [PaddlePaddle/PaddleSeg#3608]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

我已经使用eiseg标注过大概50张左右的图片了，当我改txt文件的标签ID后，重新打开eiseg标注完一张图，再标注下一张图时，会出现如下报错并闪退：
W1226 17:09:41.272948  7401 gpu_resources.cc:149] device: 0, cuDNN Version: 8.9.
Traceback (most recent call last):
  File "/home/buu/anaconda3/envs/PaddleSeg/lib/python3.7/site-packages/eiseg/app.py", line 3256, in focusToLable
    self.labelListClicked(idx, 0)
  File "/home/buu/anaconda3/envs/PaddleSeg/lib/python3.7/site-packages/eiseg/app.py", line 1252, in labelListClicked
    table.item(row, cl).setBackground(QtGui.QColor(48, 140, 198))
AttributeError: 'NoneType' object has no attribute 'setBackground'

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1703581807 (unix time) try "date -d @1703581807" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800001ce9) received by PID 7401 (TID 0x7fca63001180) from PID 7401 ***]

Aborted (core dumped)

### 复现环境 Environment

- OS: Linux Ubuntu20.04
- -PaddlePaddle: 2.2.2
- PaddleSeg: release/2.8
- eiseg：1.1.1
- Python: 3.7.16

Package                Version       Editable project location
---------------------- ------------- -----------------------------------------
actionlib              1.14.0
addict                 2.4.0
albumentations         1.3.1
ansi2html              1.9.1
anyio                  3.7.1
astor                  0.8.1
attrs                  23.1.0
Babel                  2.13.0
backcall               0.2.0
bce-python-sdk         0.8.92
catkin                 0.8.10
certifi                2022.12.7
charset-normalizer     3.3.1
click                  8.1.7
comm                   0.1.4
ConfigArgParse         1.7
cv-bridge              1.16.2
cycler                 0.11.0
Cython                 3.0.7
dash                   2.14.2
dash-core-components   2.0.0
dash-html-components   2.0.0
dash-table             5.0.0
decorator              5.1.1
dynamic-reconfigure    1.7.3
easydict               1.11
EISeg                  0.4.0
exceptiongroup         1.1.3
fastjsonschema         2.19.0
ffmpeg                 1.4
filelock               3.12.2
Flask                  2.2.5
flask-babel            3.1.0
fonttools              4.38.0
future                 0.18.3
gencpp                 0.7.0
geneus                 3.0.0
genlisp                0.4.18
genmsg                 0.6.0
gennodejs              2.0.2
genpy                  0.6.15
h11                    0.14.0
httpcore               0.17.3
httpx                  0.24.1
idna                   3.4
imageio                2.31.2
importlib-metadata     6.7.0
importlib-resources    5.12.0
ipython                7.34.0
ipywidgets             8.1.1
itsdangerous           2.1.2
jedi                   0.19.1
Jinja2                 3.1.2
joblib                 1.3.2
jsonschema             4.17.3
jupyter_core           4.12.0
jupyterlab-widgets     3.0.9
kiwisolver             1.4.5
MarkupSafe             2.1.3
matplotlib             3.5.3
matplotlib-inline      0.1.6
message-filters        1.16.0
nbformat               5.7.0
nest-asyncio           1.5.8
networkx               2.6.3
numpy                  1.21.6
open3d                 0.17.0
opencv-contrib-python  4.8.1.78
opencv-python          4.5.5.64
opencv-python-headless 4.8.1.78
opt-einsum             3.3.0
packaging              23.2
paddle-bfloat          0.1.7
paddlepaddle-gpu       2.5.2.post112
paddleseg              2.8.0         /home/buu/zhangting/PaddleSeg-release-2.8
pandas                 1.3.5
parso                  0.8.3
pexpect                4.9.0
pickleshare            0.7.5
Pillow                 9.5.0
pip                    22.3.1
pkgutil_resolve_name   1.3.10
plotly                 5.18.0
prettytable            3.7.0
prompt-toolkit         3.0.43
protobuf               3.20.0
psutil                 5.9.6
ptyprocess             0.7.0
pycocotools            2.0.7
pycryptodome           3.19.0
Pygments               2.17.2
pyparsing              3.1.1
PyQt5                  5.15.2
PyQt5-Qt5              5.15.2
PyQt5-sip              12.13.0
pyquaternion           0.9.9
pyrsistent             0.19.3
python-dateutil        2.8.2
python-qt-binding      0.4.4
pytz                   2023.3.post1
PyWavelets             1.3.0
PyYAML                 6.0.1
qt-dotgraph            0.4.2
qt-gui                 0.4.2
qt-gui-cpp             0.4.2
qt-gui-py-common       0.4.2
QtPy                   2.4.1
qudida                 0.0.4
rarfile                4.1
requests               2.31.0
retrying               1.3.4
rosbag                 1.16.0
rosclean               1.15.8
rosgraph               1.16.0
roslaunch              1.16.0
roslib                 1.15.8
roslz4                 1.16.0
rosmaster              1.16.0
rosmsg                 1.16.0
rosnode                1.16.0
rosparam               1.16.0
rospy                  1.16.0
rosservice             1.16.0
rostest                1.16.0
rostopic               1.16.0
rosunit                1.15.8
roswtf                 1.16.0
rqt_action             0.4.9
rqt_bag                0.5.1
rqt_bag_plugins        0.5.1
rqt-console            0.4.12
rqt_dep                0.4.12
rqt_graph              0.4.14
rqt_gui                0.5.3
rqt_gui_py             0.5.3
rqt-image-view         0.4.17
rqt_launch             0.4.9
rqt-logger-level       0.4.12
rqt_msg                0.4.10
rqt_plot               0.4.13
rqt_publisher          0.4.10
rqt_py_common          0.5.3
rqt_py_console         0.4.10
rqt-reconfigure        0.5.5
rqt_service_caller     0.4.10
rqt_shell              0.4.11
rqt_srv                0.4.9
rqt_top                0.4.10
rqt_topic              0.4.13
rqt_web                0.4.10
scikit-image           0.19.3
scikit-learn           1.0.2
scipy                  1.7.3
sensor-msgs            1.13.1
setuptools             65.6.3
six                    1.16.0
sklearn                0.0.post10
smclib                 1.8.6
sniffio                1.3.0
tenacity               8.2.3
tf                     1.13.2
tf2-client             1.0.0
tf2-geometry-msgs      0.7.7
tf2-kdl                0.7.7
tf2-py                 0.7.7
tf2-ros                0.7.7
tf2-sensor-msgs        0.7.7
tf2-server             1.1.2
threadpoolctl          3.1.0
tifffile               2021.11.2
topic-tools            1.16.0
tqdm                   4.66.1
traitlets              5.9.0
typing_extensions      4.7.1
urllib3                2.0.7
visualdl               2.5.3
wcwidth                0.2.8
Werkzeug               2.2.3
wget                   3.2
wheel                  0.38.4
widgetsnbextension     4.0.9
zipp                   3.15.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by shiyutang** [comment]
你好，这看上去是一个前端错误，我们目前暂时无法跟进，请查看这个对象为什么会变成None入手排除。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
