### ISSUE TITLE
About PP-LiteSeg: What's the official  flops? 

### ISSUE THREAD

**Issue by EudicL** [PaddlePaddle/PaddleSeg#3611]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

About PP-LiteSeg: What's the official  flops?

**Comment by shiyutang** [comment]
You can calculate it on the model using Paddle.flops API。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
