### ISSUE TITLE
关于CPS的数据导入问题dataloader StopIteration

### ISSUE THREAD

**Issue by RzzzLiu** [PaddlePaddle/PaddleSeg#3612]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://github.com/PaddlePaddle/PaddleSeg/assets/87182943/4e623ca7-ed5b-4503-abe1-aac1cd546bc9)
我导入数据后，尝试打印出/core/train.py中的num_train_imgs和num_unsup_imgs数量并没有错误，不知道为什么会发生StopIteration表示已经读完，请大佬指教

**Comment by shiyutang** [comment]
如果数据读完了，应该不会报错，可以看看数据集的getitem中是否返回了除了numpy之后的值。如果返回None之类的数据会出现异常。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
