### ISSUE TITLE
paddleseg模型部署，开启服务后。正常运行两天左右，服务便会自动终止，输出日志中没有找到终止原因

### ISSUE THREAD

**Issue by magicendaver** [PaddlePaddle/PaddleSeg#3617]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![paddleseg错误信息2](https://github.com/PaddlePaddle/PaddleSeg/assets/101374791/19a8d350-051e-4335-9c3f-0ec9cd94b403)
![paddleseg错误信息](https://github.com/PaddlePaddle/PaddleSeg/assets/101374791/85a504e7-bcc4-4905-8af9-36e36d3884b1)

**Comment by magicendaver** [comment]
paddleseg模型部署，开启服务后，也能够正常进行图像预测，虽然日志中会输出model.py94行报错，但是实际上该报错并没有影响服务的正常运行，也就是说不会导致服务被关闭，但是这样运行两天左右，服务便会输出none-graceful deternimation detected，然后服务便会被杀死，目前也没有找到更详细的日志信息，请问这个问题改如何解决，另外在部署yolov5模型的时候，也会报同样的不存在as_numpy属性的错，但是改错不会影响服务正常运行，且yolov5的服务一直能保持稳定运行而不会被以外终止。

**Comment by shiyutang** [comment]
你好，看上去是模型部署过程中报错了，而且你是否是使用FastDeploy框架？ 如果想要解决你的问题，首先需要定位到哪个代码报错，由于你使用的是FD的框架，建议可以前往Paddle官网下Issue再次进行提问。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
