### ISSUE TITLE
Run inference from Python script

### ISSUE THREAD

**Issue by RomRoc** [PaddlePaddle/PaddleSeg#3618]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hello, thanks for your amazing library.
I have a model trained with PaddleSeg, and exported.
I need to run inference from Pyrhon script, can you tell me how to find the python api to run inference?
I just found infer.py script, but I don't want to run inference from bash command, I need to execute from my Python code.
Thanks

**Comment by shiyutang** [comment]
Hi, we infer the static model using Paddle Inference, you can see the python code here:https://github.com/PaddlePaddle/PaddleSeg/blob/release%2F2.9/deploy/python/infer.py

**Comment by RomRoc** [comment]
Yes, this is what I did, anyway it could be useful for others to make an example how to run inference from Python.
Thanks

**Comment by Daniel-969** [comment]
https://github.com/PaddlePaddle/PaddleSeg/blob/166f366047777c1b61c4c71bcef9d2e3ed77960a/deploy/python/infer.py#L217C21-L217C53
请问这句代码我执行后的结果为None是因为导出模型的时候出现了问题吗
