### ISSUE TITLE
pip install paddleseg install 2.8.0 version instead of 2.9.0

### ISSUE THREAD

**Issue by RomRoc** [PaddlePaddle/PaddleSeg#3619]
### 文档链接&描述 Document Links & Description

https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.9/docs/install.md

Documentation in 2.9.0 assert to install PaddleSeg I have to run:
`pip install paddleseg`

but it install 2.8.0 indeed.

### 请提出你的建议 Please give your suggestion

You can please update package installed using pip.

**Comment by shiyutang** [comment]
Hi, You can try install from source using `pip install -e . ` under Paddleseg/

**Comment by RomRoc** [comment]
Yes, I installed from source, maybe you can update the 2.9.0 installation guide, it says you can install it using pip.
Thanks
