### ISSUE TITLE
C2Fnet训练问题

### ISSUE THREAD

**Issue by ZHIZIHUABU** [PaddlePaddle/PaddleSeg#3620]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，请问针对遥感图像的C2Fnet需要的coarse模型是指直接训练得到的模型吗？我是否可以训练一个ppliteseg模型（遥感图像 baseline中没有该模型），然后再用C2Fnet进行训练。这个过程是一个finetune吗？

**Comment by Bobholamovic** [comment]
理论上是的，但目前C2FNet只支持特定的模型，其中不包括PP-LiteSeg。具体可参考这里：https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.9/contrib/RSSegBenchmark
