### ISSUE TITLE
想通过paddleseg训练和分割4通道的影像

### ISSUE THREAD

**Issue by Programrookie33** [PaddlePaddle/PaddleSeg#3622]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

各位大佬，本人是学生小白，想通过PaddleSeg分割4通道的遥感影像，能否请各位解答一下该怎么搞？谢谢各位！

**Comment by shiyutang** [comment]
你好，我们有一个仓库PaddleRS可以参考，专门针对遥感数据的相关任务：https://github.com/PaddlePaddle/PaddleRS

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
