### ISSUE TITLE
关于安装paddleseg过程中出现的包版本不兼容问题

### ISSUE THREAD

**Issue by tianliye6** [PaddlePaddle/PaddleSeg#3623]
### 问题描述 Please describe your issue

我的python版本为：3.6.9，采用源码或已发布的包方式安装paddleseg均会碰到以下问题：
![微信截图_20240119141034](https://github.com/PaddlePaddle/PaddleSeg/assets/58807217/29557fa2-420f-461f-a536-1fb9d3bde6dd)
当我试图通过离线包安装flask-babel=3.0.0时，报错提示requires Python '>=3.7,<4.0'
![微信截图_20240119141111](https://github.com/PaddlePaddle/PaddleSeg/assets/58807217/cb14b849-6748-4358-be8f-65fdbe63a8e3)
请问应该怎么解决

**Comment by shiyutang** [comment]
你好，是由于你的python版本不对导致相关的软件包找不到对应版本。
需要安装>=3.7,<4.0的python版本

**Comment by tianliye6** [comment]
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/58807217/edb29192-9653-4733-9d80-9fae831c2f96)

我是在jetson nx设备上基于jetpack4.6安装的，如果给python版本升级，是不是就没有对应paddlepaddle-gpu的whl包下载安装了呢
![微信截图_20240119150927](https://github.com/PaddlePaddle/PaddleSeg/assets/58807217/b2cbeea0-c331-403c-bb6a-08767e01a97e)

**Comment by tianliye6** [comment]
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/58807217/a1af3bbb-e094-4f37-ab1d-541efcc08141)
需要重刷jetpack4.6.1然后安装paddlepaddle_gpu-2.3.2-cp37-cp37m-linux_aarch64.whl再安装paddleseg吗

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
