### ISSUE TITLE
请问如何指定使用哪一块GPU？我在笔记本上，默认使用集成显卡的GPU0,如何更改为GPU1？

### ISSUE THREAD

**Issue by hutaotao1** [PaddlePaddle/PaddleSeg#3625]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问如何指定使用哪一块GPU？我在笔记本上，默认使用集成显卡的GPU0,如何更改为GPU1？

**Comment by hutaotao1** [comment]
补充一下问题：train.py里面指定 --device default='gpu:0'时会报错，这个方法行不通。是需要重新配置CUDA到GPU1上吗？

**Comment by michaelowenliu** [comment]
先在命令行运行 export CUDA_VISIBLE_DEVICES=1

**Comment by hutaotao1** [comment]
您发给我的邮件我已经收到！

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.

**Comment by hutaotao1** [comment]
您发给我的邮件我已经收到！
