### ISSUE TITLE
在jetson nx设备上执行run_seg_gpu_trt_dynamic_shape.sh脚本进行推理时遇到的问题

### ISSUE THREAD

**Issue by tianliye6** [PaddlePaddle/PaddleSeg#3627]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

以下为完整运行信息：
`(paddleseg) root@ubuntu:~/project/PaddleSeg/deploy/cpp# ./build/test_seg --model_dir=./belt_coal_infer_model --img_path=./belt_coal_images/02.png --devices=GPU --use_trt=True --trt_precision=fp32  --use_trt_dynamic_shape=True --dynamic_shape_path=./dynamic_shape.pbtxt
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0125 15:29:24.954989 10800 test_seg.cc:74] Use GPU
I0125 15:29:24.955289 10800 test_seg.cc:79] Use TRT
I0125 15:29:24.955322 10800 test_seg.cc:80] trt_precision:fp32
I0125 15:29:24.955389 10800 test_seg.cc:98] Enable TRT dynamic shape
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0125 15:29:29.509850 10800 analysis_predictor.cc:881] TensorRT subgraph engine is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [adaptive_pool2d_convert_global_pass]
I0125 15:29:29.717460 10800 fuse_pass_base.cc:57] ---  detected 1 subgraphs
--- Running IR pass [shuffle_channel_detect_pass]
--- Running IR pass [quant_conv2d_dequant_fuse_pass]
--- Running IR pass [delete_quant_dequant_op_pass]
--- Running IR pass [delete_quant_dequant_filter_op_pass]
--- Running IR pass [delete_weight_dequant_linear_op_pass]
--- Running IR pass [delete_quant_dequant_linear_op_pass]
--- Running IR pass [add_support_int8_pass]
I0125 15:29:30.056416 10800 fuse_pass_base.cc:57] ---  detected 278 subgraphs
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [preln_embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [multihead_matmul_fuse_pass_v3]
--- Running IR pass [skip_layernorm_fuse_pass]
--- Running IR pass [preln_skip_layernorm_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I0125 15:29:30.351207 10800 fuse_pass_base.cc:57] ---  detected 63 subgraphs
--- Running IR pass [unsqueeze2_eltwise_fuse_pass]
--- Running IR pass [trt_squeeze2_matmul_fuse_pass]
--- Running IR pass [trt_reshape2_matmul_fuse_pass]
--- Running IR pass [trt_flatten2_matmul_fuse_pass]
--- Running IR pass [trt_map_matmul_v2_to_mul_pass]
--- Running IR pass [trt_map_matmul_v2_to_matmul_pass]
--- Running IR pass [trt_map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
I0125 15:29:30.472626 10800 fuse_pass_base.cc:57] ---  detected 67 subgraphs
--- Running IR pass [tensorrt_subgraph_pass]
I0125 15:29:30.569200 10800 tensorrt_subgraph_pass.cc:145] ---  detect a sub-graph with 142 nodes
[libprotobuf ERROR /home/paddle/data/xly/workspace/23281/Paddle/build_cpp_all/third_party/protobuf/src/extern_protobuf/src/google/protobuf/text_format.cc:298] Error parsing text-format paddle.inference.proto.ShapeRangeInfos: 6510:12: Message type "paddle.inference.proto.ShapeRangeInfos.ShapeRangeInfo" has no field named "min_value".
I0125 15:29:30.649102 10800 tensorrt_subgraph_pass.cc:433] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I0125 15:29:32.701087 10800 op_converter.h:270] trt input [x] dynamic shape info not set, please check and retry.
terminate called after throwing an instance of 'phi::enforce::EnforceNotMet'
  what():  

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::CreatePredictor(paddle::AnalysisConfig const&)
1   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
2   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
3   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
5   paddle::AnalysisPredictor::OptimizeInferenceProgram()
6   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
8   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
9   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
10  paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
11  paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > >*) const
12  paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*)
13  phi::enforce::EnforceNotMet::EnforceNotMet(phi::ErrorSummary const&, char const*, int)
14  phi::enforce::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
**InvalidArgumentError: some trt inputs dynamic shape info not set, check the INFO log above for more details.
  [Hint: Expected all_dynamic_shape_set == true, but received all_dynamic_shape_set:0 != true:1.**] (at /home/paddle/data/xly/workspace/23281/Paddle/paddle/fluid/inference/tensorrt/convert/op_converter.h:308)

Aborted (core dumped)
`
请问该怎么解决呢

**Comment by shiyutang** [comment]
你好，这个可以看出是Paddle Inference报错，建议前往[paddle官网](https://github.com/PaddlePaddle/Paddle/issues)提问～

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
