### ISSUE TITLE
将自动压缩蒸馏训练中的参数alpha: 1.0后理论上可以不需要标签，进行自监督训练，但是报错train.txt格式错误，能否对代码进行适配，使其能够自监督训练？

### ISSUE THREAD

**Issue by Wst-sd** [PaddlePaddle/PaddleSeg#3628]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包含open与closed)，没有类似需求。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar feature requests.

### 需求描述 Feature Description

如果将这里的参数alpha设置为1.0，并且删除量化相关参数，是不是可以理解为只从教师模型学习，这样的话就不需要标签了。[deploy/slim/act/configs/segformer/segformer_b0_qat.yaml](url)   但是我将train.txt中的标签删除后，报错提示train.txt格式错误。

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by shiyutang** [comment]
你好，这个暂时不会支持，建议查看代码修改～

**Comment by Wst-sd** [comment]
已收到邮件，谢谢！
