### ISSUE TITLE
bilinear_interp_v2输出shape为啥是[1 2 ？？]我已经固定inputshape [1 3 512 512]

### ISSUE THREAD

**Issue by 13950182204** [PaddlePaddle/PaddleSeg#3629]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![Uploading mode.png…]()

**Comment by 13950182204** [comment]
![Uploading 微信图片_20240126204855.png…]()

**Comment by shiyutang** [comment]
你好，你的图片看不到，但是双线性采样存在问题的确不对，不太确定是动转静还是推理的问题，建议前往[paddle官网](https://github.com/PaddlePaddle/Paddle/issues)提问～

**Comment by 13950182204** [comment]
![微信图片_20240121031650](https://github.com/PaddlePaddle/PaddleSeg/assets/102646780/7e5d324d-7272-4403-a6d5-6a1095b00cae)

**Comment by 13950182204** [comment]
![微信图片_20240121031634](https://github.com/PaddlePaddle/PaddleSeg/assets/102646780/ac95740e-a7a2-448c-a2e8-0107d6def084)

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
