### ISSUE TITLE
ValueError: (InvalidArgument) Currently, Tensor.__indices__() only allows indexing by Boolean, Integers, Slices, Ellipsis, None, Tuples of these types and List / Tensor of Bool and Integers, but received str in 1th slice item (at ..\paddle/fluid/pybind/slice_utils.h:325)

### ISSUE THREAD

**Issue by gabrielmercado90** [PaddlePaddle/PaddleSeg#3630]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

I am trying to follow up the documentation [https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.9/Matting/docs/quick_start_en.md](guide for matting) but after running all the steps exactly as it says I am getting the following under the command:

Folder : /PaddleSeg/Matting

python tools\bg_replace.py --config configs\ppmattingv2\ppmattingv2-stdc1-human_512.yml       --model_path pretrained_models\ppmattingv2-stdc1-human_512.pdparams       --image_path demo\human.jpg       --background 'g'     --save_dir .\output\results   --fg_estimate True

 ---------------Config Information---------------                                                        
batch_size: 16                                                                                          
iters: 100000                                                                                           
train_dataset:                                                                                            
dataset_root: data/PPM-100                                                                              
mode: train                                                                                             
train_file: train.txt                                                                                   
transforms:                                                                                             
- type: LoadImages                                                                                      
- max_short: 512                                                                                          
- type: LimitShort                                                                                      
- crop_size:                                                                                              
- 512                                                                                                   
- 512                                                                                                   
- type: RandomCrop                                                                                      
- target_size:                                                                                            
- 512                                                                                                   
- 512                                                                                                   
- type: Padding                                                                                         
- type: RandomDistort                                                                                   
- prob: 0.1                                                                                               
- type: RandomBlur                                                                                      
- prob: 0.2                                                                                               
- type: RandomSharpen                                                                                   
- prob: 0.5                                                                                               
- type: RandomNoise                                                                                     
- prob: 0.2                                                                                               
- type: RandomReJpeg                                                                                    
- type: RandomHorizontalFlip                                                                            
- type: Normalize                                                                                       
- type: MattingDataset                                                                                  
- val_dataset:                                                                                              
- dataset_root: data/PPM-100                                                                              
- get_trimap: false                                                                                       
- mode: val                                                                                               
- transforms:                                                                                             
  - type: LoadImages                                                                                      
  - max_short: 512                                                                                          
  - type: LimitShort                                                                                      
  - mult_int: 32                                                                                            
  - type: ResizeToIntMult                                                                                 
  - type: Normalize                                                                                       
  - type: MattingDataset                                                                                    
  - val_file: val.txt                                                                                     
  - optimizer:                                                                                                
  - momentum: 0.9                                                                                           
  - type: sgd                                                                                               
  - weight_decay: 0.0005                                                                                  
  - lr_scheduler:                                                                                             
  - end_lr: 0                                                                                               
  - learning_rate: 0.01                                                                                     
  - power: 0.9                                                                                              
  - type: PolynomialDecay                                                                                   
  - warmup_iters: 1000                                                                                      
  - warmup_start_lr: 1.0e-05                                                                              
  - model:                                                                                                    
  - backbone:                                                                                                 
  - pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet1.tar.gz                                  
  - type: STDC1                                                                                           
  - decoder_channels:                                                                                       
  - 128                                                                                                   
  - 96                                                                                                    
  - 64                                                                                                    
  - 32                                                                                                    
  - 16                                                                                                    
  - dpp_merge_type: add                                                                                     
  - dpp_output_channel: 256                                                                                 
  - head_channel: 8                                                                                         
  - type: PPMattingV2                                                                                     
  ------------------------------------------------                                                                                                                                                              
 -Set device: cpu                                                         
2024-01-25 12:00:12 [INFO]      
Use the following config to build model                                 
model:                                                                                                    
backbone:                                                                                                 
pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet1.tar.gz                                  
type: STDC1                                                                                           
decoder_channels:                                                                                       
- 128                                                                                                   
- 96                                                                                                    
- 64                                                                                                    
- 32                                                                                                    
- 16                                                                                                    
- dpp_merge_type: add                                                                                     
- dpp_output_channel: 256                                                                                 
- head_channel: 8                                                                                         
- type: PPMattingV2                                                                                     
2024-01-25 12:00:12 [INFO]      Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet1.tar.gz                                                                                        2024-01-25 12:00:12 [INFO]      There are 145/145 variables loaded into STDCNet.                        
2024-01-25 12:00:12 [INFO]      Loading pretrained model from pretrained_models\ppmattingv2-stdc1-human_512.pdparams                                                                                            2024-01-25 12:00:12 [INFO]      There are 485/485 variables loaded into PPMattingV2.                    
2024-01-25 12:00:12 [INFO]      Start to predict...                                                    

Traceback (most recent call last):                                                                       
File "E:\DEV_PYTHON\PaddlePaddleSource\PaddleSeg\Matting\tools\bg_replace.py", line 148, in <module>      main(args)                                                                                            File "E:\DEV_PYTHON\PaddlePaddleSource\PaddleSeg\Matting\tools\bg_replace.py", line 106, in main          alpha, fg = predict(                                                                                  File "E:\DEV_PYTHON\PaddlePaddleSource\PaddleSeg\Matting\tools\..\ppmatting\core\predict.py", line 158, in predict                                                                                                result = model(data['img'])                                                                           

File "E:\DEV_PYTHON\PaddlePaddleSource\lib\site-packages\paddle\nn\layer\layers.py", line 1429, in __call__                                                                                                       return self.forward(*inputs, **kwargs)               
                                                 File "E:\DEV_PYTHON\PaddlePaddleSource\PaddleSeg\Matting\tools\..\ppmatting\models\ppmattingv2.py", line 143, in forward                                                                                          img = inputs['img']                                                                                   

File "E:\DEV_PYTHON\PaddlePaddleSource\lib\site-packages\paddle\base\dygraph\tensor_patch_methods.py", line 896, in __getitem__                                                                                   
return self._getitem_dygraph(item)                     
                                             
ValueError: (InvalidArgument) Currently, Tensor.__indices__() only allows indexing by Boolean, Integers, Slices, Ellipsis, None, Tuples of these types and List / Tensor of Bool and Integers, but received str in 1th slice item (at ..\paddle/fluid/pybind/slice_utils.h:325)

### 复现环境 Environment

------------Environment Information-------------              
platform: Windows-10-10.0.19044-SP0                                                                     
Python: 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]                  
Paddle compiled with cuda: False                                                                        
PaddleSeg: 2.9.0                                                                                        
PaddlePaddle: 2.6.0                                                                                     
OpenCV: 4.5.5       

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by shiyutang** [comment]
你好，你应该进入到PaddleSeg/Matting目录中指定训练，外部的API进行了升级但是内部没有。

**Comment by gabrielmercado90** [comment]
Hi, thank you I solved it by uninstalling and reinstalling everything, seems that there was some cross-versions issues with the environment.
