### ISSUE TITLE
PP-HumanSeg: IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed

### ISSUE THREAD

**Issue by andy315** [PaddlePaddle/PaddleSeg#3631]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

训练微调之后得到的model（human_pp_humansegv2_lite）,
运行推理的时候报错：
Traceback (most recent call last):
  File "C:\Python38\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Python38\lib\tkinter\__init__.py", line 814, in callit
    func(*args)
  File ".\src\test.py", line 125, in main
    out = predictor.run(bgr_image, bg)
  File "D:\Workplace\PaddleSeg\contrib\PP-HumanSeg\src\infer.py", line 122, in run
    return self.postprocess(output, img, data, bg)
  File "D:\Workplace\PaddleSeg\contrib\PP-HumanSeg\src\infer.py", line 126, in postprocess
    score_map = pred_img[0, 1, :, :]
IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed

### 复现环境 Environment

-OS: windows
-PaddlePaddle: 2.6.0
-PaddleSeg: release/2.9
-python: 3.8.10
-Cuda: 11.8
-cudnn: 8.9.7

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by andy315** [comment]
export 的时候带上output_op参数（试了softmax）没有问题。default 是argmax，难道这个有问题？

**Comment by shiyutang** [comment]
看上去是预测图像中的问题，我们会尽快确认排除。

**Comment by chenjjcccc** [comment]
> export 的时候带上output_op参数（试了softmax）没有问题。default 是argmax，难道这个有问题？

我用提供的推理模型测试好像是没问题的

**Comment by tongchangD** [comment]
@andy315 
我 也遇到了相似的问题  ，如果是用`download_pretrained_models.py` 这个代码下载下来的模型是能用的，但是简介里提供的其他模型是用不了的。不知为何
请问你知道问题出在哪里不？

**Comment by tongchangD** [comment]
突然发现是自己蠢了，提供了 argmax 和 softmax的 ，我不该用softmax的代码 argmax的模型

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
