### ISSUE TITLE
关于config文件的一些问题

### ISSUE THREAD

**Issue by rememberBr** [PaddlePaddle/PaddleSeg#3632]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

paddleSeg的模型完全基于config文件进行配置，包括损失函数，数据预处理，模型backbone等，但是每个部件有哪些可选项，每个可选项的配置案例是否有完整的文档，因为我发现paddle的api与config文件中的设置似乎不一样，例如pp-liteSeg的config文件中使用了RandomDistort的数据transform，但是https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4/api/paddle/vision/Overview_cn.html#about-transforms中却不包含这个api，而api文档中存在的[to_grayscale]方法，在config文件中无法直接通过type: to_grayscale设置，这意味着二者并不完全统一，但是我没有找到文档告诉我config文件中具体有哪些transform方法可以设置，以及相关的参数，相同的还包含loss，lr_scheduler与optimizer部件

**Comment by Asthestarsfalll** [comment]
代码见[此](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.9/paddleseg/transforms/transforms.py)，文档见[此](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.9/docs/apis/transforms/transforms_cn.md)

**Comment by rememberBr** [comment]
感谢，这雀食是我想要的，我一直在paddlepaddle的文档里面去找我想要的内容，看来方向是错了，多问一句，如果我想自己加一些预处理的方法，是不是仿照https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8.1/paddleseg/transforms/transforms.py的写法，使用@manager.TRANSFORMS.add_component注册就行了哇

**Comment by Asthestarsfalll** [comment]
是的，注册完成后需要在配置文件中使用该方法

**Comment by rememberBr** [comment]
好的非常感谢
