### ISSUE TITLE
Question: Can I fix model's output's shape?

### ISSUE THREAD

**Issue by PeterKim1** [PaddlePaddle/PaddleSeg#3635]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hi. Thanks for your great works.

I want to use PaddleSeg for making my model.

Installation, and training don't have any issue. 

But, after convert trained model to ONNX format, issue occur.

I use (1024, 1024) image, and I need to set input_shape => (1, 1024, 1024, 3) and output_shape => (1, 1024, 1024, 18) (I have 18 classes.)

But, after using paddle2onnx to convert onnx format, this onnx model has input_shape => float32[p2o.DynamicDimension.0,3,p2o.DynamicDimension.1,p2o.DynamicDimension.2] and output_shape => int32[p2o.DynamicDimension.3,p2o.DynamicDimension.4,p2o.DynamicDimension.5]

How can I change PaddleSeg model's input shape and output shape?

If I don't fix my model's input shape and output shape, system can't use my model, so it is very very important issue for me.

Thanks.

**Comment by TingquanGao** [comment]
Could you please provide the used code to convert onnx format model?

**Comment by PeterKim1** [comment]
@TingquanGao Thanks for your fast reply!

os.chdir('/project/work/shared/NAS/00_workspace/workspace/Paddle2ONNX/paddle2onnx')

!python command.py --model_dir /project/work/shared/NAS/00_workspace/workspace/PaddleSeg/Winder_output_v2/inference_model \
            --model_filename model.pdmodel \
            --params_filename model.pdiparams \
            --opset_version 11 \
            --save_file /project/work/shared/NAS/00_workspace/workspace/PaddleSeg/Winder_output_v2/Winder_output_v2.onnx

I read https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.9/docs/model_export_onnx.md, but in my ubuntu server, paddle2onnx command can't use. So I try to use source codes.

Thanks.

**Comment by shiyutang** [comment]
HI, this is an issue of paddle2ONNX, can you go to here to raise your question? [paddle Issue](https://github.com/PaddlePaddle/Paddle/issues)

**Comment by PeterKim1** [comment]
@shiyutang Many Thanks! I will try to raise my question in paddle issue.

**Comment by shiyutang** [comment]
You are welcome, closing due to this issue is replied there.
