### ISSUE TITLE
代码复现结果极差的问题

### ISSUE THREAD

**Issue by lxk767363331** [PaddlePaddle/PaddleSeg#364]
在复现R2UNet时结果极差不知道哪里出了问题，从结构上看 我应该没有浮现错误。下面分别是我的代码与torch代码

https://github.com/LeeJunHyun/Image_Segmentation/blob/db34de21767859e035aee143c59954fa0d94bbcd/network.py#L60

‘’
def RRCNN_block(data,out_ch):
    with scope("conv0"):
        x =conv(data, out_ch, 1, stride=1, padding=0)
    with scope("Recurrent_block1"):
        data=Recurrent_block(x,out_ch)
        data=Recurrent_block(data,out_ch)
    return x+data

def Recurrent_block(data,out_ch):
    with scope("rconv0"):
        x1 = bn_relu(
            conv(data, out_ch, 3, stride=1, padding=1))
    with scope("rconv1"):
        r1=data+x1
        r1 = bn_relu(
            conv(r1, out_ch, 3, stride=1, padding=1))
    with scope("rconv2"):
        r2=r1+data
        r2 = bn_relu(
            conv(r2, out_ch, 3, stride=1, padding=1))
    return r2
‘’

我是讲unet代码中的所有double_conv都替换为RRCNN_block。 在眼底数据集上，目前miou效果最佳没有超过0.85，unet的miou效果是0.91左右。复现的attention unet效果是可以的。

**Comment by wuyefeilin** [comment]
![image](https://user-images.githubusercontent.com/30919197/92220334-71508f00-eece-11ea-9262-026f99a5a17e.png)
![image](https://user-images.githubusercontent.com/30919197/92220787-123f4a00-eecf-11ea-892a-827ed321e066.png)
这两边的Recurrent_block实现存在diff， torch 中的卷积是共享的，这边的三个卷积是独立的。你可以放到同一个scope下去实现就可以了

**Comment by lxk767363331** [comment]
好的 谢谢，原来想分开能更清晰，没想到画蛇添足了。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月4日(星期五) 下午4:59
收件人:&nbsp;"PaddlePaddle/PaddleSeg"<PaddleSeg@noreply.github.com&gt;;
抄送:&nbsp;"不要冲动保持心态"<767363331@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] 代码复现结果极差的问题 (#364)





 

 
 这两边的Recurrent_block实现存在diff， torch 中的卷积是共享的，这边的三个卷积是独立的。你可以放到同一个scope下去实现就可以了

**Comment by lxk767363331** [comment]
还有个疑问，咱们unet代码中的double conv中的2个卷积也是互相独立的么，我不太清楚这个独立与共享的区别 可以帮我说明一下么  谢谢
