### ISSUE TITLE
如何使用paddleseg进行自监督训练

### ISSUE THREAD

**Issue by ChenjieXu** [PaddlePaddle/PaddleSeg#3641]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

工业场景里，是有部分有标签数据和海量无标签数据，无标签数据里还有大量的负样本。我如何使用ppseg来训练这样的数据？

**Comment by TingquanGao** [comment]
尚未支持自监督训练。

**Comment by Wst-sd** [comment]
我也想进行自监督训练，准备通过模型蒸馏的代码来自己改

**Comment by shiyutang** [comment]
自监督训练有一个[PASSL](https://github.com/PaddlePaddle/PASSL/tree/main)的仓库，里面集成了很多自监督的算法例如MOCO等，可以进行尝试。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.

**Comment by Wst-sd** [comment]
已收到邮件，谢谢！
