### ISSUE TITLE
如何用matting数据集来微调人像分割模型呢？

### ISSUE THREAD

**Issue by LiYufengzz** [PaddlePaddle/PaddleSeg#3645]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

如题，对人像分割模型精度不是很满意，手里没有足够的分割数据集，有matting数据集（alpha值从0-255），如何科学使用这些数据集进行优化微调呢？有没有建议，感谢

**Comment by shiyutang** [comment]
你好，最基础的方法可以对这些alpha值设置一个门限来确定边缘，例如对alpha大于255/2的可以认为是1，否则为0，并通过这些matting数据集微调。微调时可以选用一些注重边缘和错分样本的损失，例如focal loss和boundary aggregated loss。
