### ISSUE TITLE
日志文件.log乱码，请问编码方式以及怎么正常显示？

### ISSUE THREAD

**Issue by SSZ1** [PaddlePaddle/PaddleSeg#3647]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

训练完成后最后输出的log文件我用了很多编码软件打开都是乱码，UltraEdit，Sublime Text，VSCode等，请问解决方案？

### 复现环境 Environment

 ubuntu20.04，paddle就目前最新版本

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by paddle-models** [comment]
能展示一下具体的出错截图吗

**Comment by SSZ1** [comment]
> 能展示一下具体的出错截图吗

![image](https://github.com/PaddlePaddle/PaddleSeg/assets/36888758/08a59612-bd63-4e79-b55a-10b4704be55c)
训练完成后打开.log日志文件，显示是这样的，看样子应该是用了16进制，我想把它转为十进制显示出来，但是不知道文件写入是的结构是怎么样的，或者您能提供读取训练日志文件解决方案吗？方便记录loss的时刻变化。感激不尽！

**Comment by SSZ1** [comment]
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/36888758/cfe8fa5f-9d65-4d4f-a9dd-9bf499fc9332)

**Comment by addiojhe** [comment]
您好，也想要问相同的问题，找过之前的issue，问题似乎都没有解决
![螢幕擷取畫面 2024-02-24 163455](https://github.com/PaddlePaddle/PaddleSeg/assets/50653289/6d45cde1-6075-4738-bcb1-08a770c6d52e)

**Comment by shiyutang** [comment]
你好，这个是visualdl的log，不是为了用文本编辑器打开的，而是通过visualdl打开，请参考：https://github.com/PaddlePaddle/VisualDL?tab=readme-ov-file#launch-by-command-line

**Comment by addiojhe** [comment]
了解了，谢谢您的回覆解说

> 你好，这个是visualdl的log，不是为了用文本编辑器打开的，而是通过visualdl打开，请参考：https://github.com/PaddlePaddle/VisualDL?tab=readme-ov-file#launch-by-command-line

**Comment by SSZ1** [comment]
> 你好，这个是visualdl的log，不是为了用文本编辑器打开的，而是通过visualdl打开，请参考：https://github.com/PaddlePaddle/VisualDL?tab=readme-ov-file#launch-by-command-line

好的，谢谢

**Comment by bobbylee0810** [comment]
直接运行下面的指令：
visualdl --log_dir output/ --port 8080

如果出现一下错误：
Port 8080 is in use by another program. Either identify and stop that program, or start the server with a different port.
请换一个端口，打开多个浏览器窗口进行展示

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
