### ISSUE TITLE
RandomPaddingCrop transform

### ISSUE THREAD

**Issue by alejandrogarcia11** [PaddlePaddle/PaddleSeg#3652]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hi, I want to know if RandomPaddingCrop is only for data augmentation or it also defines the input size of the model (or each model resizes all images to this dimensions). I mean, can I have images of 512x512 and also a RandomPaddingCrop of 256x128? Thanks in advance!

**Comment by shiyutang** [comment]
Hi, 
   Normally we train the model in multiple sizes like [1024, 512],  [512, 512], defined through the RandomPaddingCrop operation. However, you can use a model to resize images to 256x128 as well, which means you train the model on an input resolution of 256x128, it just may not be able to use all the information in a 512x512 image.

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
