### ISSUE TITLE
模型训练问题

### ISSUE THREAD

**Issue by ad5248** [PaddlePaddle/PaddleSeg#3653]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问下能否通过模型训练方法训练特定物品的抠图模型？比如扣衣服，鞋子等商品，一般需要多少训练数据呢

**Comment by shiyutang** [comment]
你好，如果需较精细的抠图模型，建议使用[PPMatting](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.9/Matting)，具体的数据量可以参照语义分割给出。不过如果不需要那么精细的话，也可以尝试先使用[SAM](https://github.com/PaddlePaddle/PaddleSeg/blob/release%2F2.9/contrib/SegmentAnything/README.md)进行一些数据的粗略标注。

数据量部分可以参考Cityscapes，其中训练数据为近3k张，因此在这个数量集的数据可以使用我们仓库中的语义分割模型获得较好的分割结果。

**Comment by ad5248** [comment]
> 你好，如果需较精细的抠图模型，建议使用[PPMatting](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.9/Matting)，具体的数据量可以参照语义分割给出。不过如果不需要那么精细的话，也可以尝试先使用[SAM](https://github.com/PaddlePaddle/PaddleSeg/blob/release%2F2.9/contrib/SegmentAnything/README.md)进行一些数据的粗略标注。
> 
> 数据量部分可以参考Cityscapes，其中训练数据为近3k张，因此在这个数量集的数据可以使用我们仓库中的语义分割模型获得较好的分割结果。

谢谢回答。现在使用了sam进行抠图，抠图结果边缘不太平整，锯齿较多，现在想达到精细化的抠图效果，[PPMatting](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.9/Matting) 是主要基于人像的吗？如果需要训练特定对象（非人物）的抠图模型基于哪个模型训练比较好？

**Comment by shiyutang** [comment]
可以在PPMatting上进行微调，但是想要训练得到边缘比较好的模型，需要本身有边缘好的数据，并可以使用focal loss等对边缘进行着重学习。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
