### ISSUE TITLE
tools/predict.py 好像不能推理视频，什么时候可以支持呢？

### ISSUE THREAD

**Issue by Wst-sd** [PaddlePaddle/PaddleSeg#3655]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

tools/predict.py 好像不能推理视频，什么时候可以支持呢？

**Comment by shiyutang** [comment]
你好tools/predict目前只会支持推理图像，可以通过前后处理实现图像和视频的转换～
