### ISSUE TITLE
网络参数是.pdiparams文件还是.pdparams文件？有没有“i”？

### ISSUE THREAD

**Issue by ppsohandsome** [PaddlePaddle/PaddleSeg#3657]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![aaaa](https://github.com/PaddlePaddle/PaddleSeg/assets/143994144/902f6b64-3c72-404a-9ff6-c693ed3ad419)
感觉有一点点费解，从github下载的网络参数，但是无法加载。
因为elseg可选择的文件后缀是.pdparams(没i)，但是下载的文件后缀是.pdiparams(有i)
所以应该怎么做呢？

**Comment by shiyutang** [comment]
你好，有i的模型是静态图权重，应该是静态图模型的，可以参考下EISeg的文档：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.9/EISeg/docs/image.md#%E4%BD%BF%E7%94%A8。

**Comment by ppsohandsome** [comment]
> 你好，有i的模型是静态图权重，应该是静态图模型的，可以参考下EISeg的文档：[https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.9/EISeg/docs/image.md#%E4%BD%BF%E7%94%A8。](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.9/EISeg/docs/image.md#%E4%BD%BF%E7%94%A8%E3%80%82)

好的谢谢，get您的意思了。

您看一下我打开eiseg之后加载权重时的画面，文件类型只能选择添加不带i的

![Snipaste_2024-02-27_15-43-11](https://github.com/PaddlePaddle/PaddleSeg/assets/143994144/f880c8e5-a163-4964-a81f-b94d509da4aa)

然后当我手动修改下来的文件，后缀名删掉i再导入，软件闪退，cmd窗口提示：“按回车继续” 后cmd窗口关闭

**Comment by shiyutang** [comment]
不能删除i的，按理来说可以导入，是不是没有到正确的场景呢，你这个界面是视频模型么，切换下tab里的场景看看呢？

**Comment by Air1000thsummer** [comment]
遇到了相同的问题，未能得到解决。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
