### ISSUE TITLE
关于通用人像分割数据集

### ISSUE THREAD

**Issue by LiYufengzz** [PaddlePaddle/PaddleSeg#3658]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://github.com/PaddlePaddle/PaddleSeg/assets/26202915/69272e86-a0f3-407c-8715-54b414f4d228)
这里提到的大规模通用人像分割数据集是什么？数据量大概有多少，可以开源吗？我发现没有预训练，仅使用PP-HumanSeg-14K数据集效果挺一般的

**Comment by shiyutang** [comment]
你好，你可以尝试使用我们的预训练模型，基于这个模型在你的数据上进行微调。通用人像分割数据集应该是一些公开数据集。

**Comment by hsdjkfnsfc** [comment]
您好请问怎么申请数据集

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
