### ISSUE TITLE
关于管胞多标签分割数据集

### ISSUE THREAD

**Issue by sy-l123** [PaddlePaddle/PaddleSeg#3659]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，关于管胞（植物细胞的一种）分割场景，有个问题还请大佬解答一下：
1、我目前是用了多标签分割的，目的是测量每个细胞的尺寸：
![13000_pseudo](https://github.com/PaddlePaddle/PaddleSeg/assets/96708528/70fc4718-f717-4559-8804-d96d3436ea4b)
原图：
<img width="331" alt="image" src="https://github.com/PaddlePaddle/PaddleSeg/assets/96708528/2f12dc0e-1545-443e-8363-f2e1499e51fa">
机器学习的结果是每个细胞的边界连在一起的，我要怎样改进标注或者训练算法，来让每个细胞边界清晰划分？
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/96708528/33391421-07cc-432f-8f05-f1822491eca5)

**Comment by sy-l123** [comment]
是不是可以用PaddleDetection实例分割？

**Comment by sy-l123** [comment]
另外关于增加边缘相关损失，有没有相关的教程？

**Comment by shiyutang** [comment]
可以对于原图中的背景增加semantic weight，迫使模型对这部分分割准确。https://github.com/PaddlePaddle/PaddleSeg/blob/166f366047777c1b61c4c71bcef9d2e3ed77960a/paddleseg/models/losses/cross_entropy_loss.py#L57C37-L57C53

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
