### ISSUE TITLE
关于配置文件中损失函数的配置

### ISSUE THREAD

**Issue by 1687412531** [PaddlePaddle/PaddleSeg#3664]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，向您请教一个问题，有关配置文件中损失函数的，
损失函数
参数
types : 损失函数列表
type : 损失函数类型，所支持值请参考损失函数库
coef : 对应损失函数列表的系数列表
关于types中的损失函数的列表，可以选择多个损失函数，请问应该选择几个损失函数，然后选择多个损失函数相比于一个损失函数，有什么优势嘛。

**Comment by shiyutang** [comment]
不同的损失关注分割结果的不同部分，比如基础的CE损失关注像素级别的差异，focal loss关注难样本类别，diceloss关注mask层级的差异，因此选择损失函数需要根据关注的内容，以及如果有多个返回logit需要分别设置损失函数。

**Comment by yuqilol** [comment]
> 不同的损失关注分割结果的不同部分，比如基础的CE损失关注像素级别的差异，focal loss关注难样本类别，diceloss关注mask层级的差异，因此选择损失函数需要根据关注的内容，以及如果有多个返回logit需要分别设置损失函数。

你好如果我要用pp-mattingv2用什么损失函数呢，因为我在跑时候发现配置文件中缺失了损失函数的参数，有具体的loss文档参考吗

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
