### ISSUE TITLE
```ValueError: (InvalidArgument) The input tensor's dimension should be equal to the axis's size. But received input tensor's dimension is 5, axis's size is 4   [Hint: Expected x_rank == axis_size, but received x_rank:5 != axis_size:4.] (at /paddle/paddle/phi/infermeta/unary.cc:3883)```

### ISSUE THREAD

**Issue by BarryAlllen** [PaddlePaddle/PaddleSeg#3665]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

用CVAT导出的数据集，使用UNet，训练显示维度错误，训练的语句```python -m paddle.distributed.launch  --gpus "0,1,2,3,4,5,6,7"  tools/train.py --config configs/unet/unet_hrf_256x256_40k.yml```，不知道是哪一步出现了问题。

**Comment by BarryAlllen** [comment]
数据集的标签用的是伪彩图，不知道会不会有影响

**Comment by shiyutang** [comment]
你好，需要辛苦具体报错位置才能明确可能原因。
