### ISSUE TITLE
Does MSE and SAD eval metrics works for binary classification (Sematic segmentation)?

### ISSUE THREAD

**Issue by Sanath1998** [PaddlePaddle/PaddleSeg#3670]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hi @jzhang533 @ZeyuChen @llxxxll @QingshuChen, 

Thanks for this wonderful repository. But I have 1 question will MSE (Mean Squared Error) and SAD (Sum of Absolute Difference) works for Binary Classification where I have only background and foreground class while doing this Sematic Training?
If yes could you please give your understanding on it which helps us a lot?

Reference from the code:- https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.9/Matting/ppmatting/metrics/metric.py

Thanks and reply is much appreciated.

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
