### ISSUE TITLE
处理对象的问题

### ISSUE THREAD

**Issue by XiruiTeng** [PaddlePaddle/PaddleSeg#3671]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

抠图的对象是有什么要求吗，为什么我试了下面的一幅图抠不出主体？

![img](https://github.com/PaddlePaddle/PaddleSeg/assets/131317640/e873842f-6d1a-4f08-aeef-14a389940983)

抠出来的结果是这样的
![08295_output_i_6_b_0_rgba](https://github.com/PaddlePaddle/PaddleSeg/assets/131317640/1c16673e-23a4-4c25-9c1a-72cfce8c045f)

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
