### ISSUE TITLE
swin_Transformer设置参数ape=True后报错

### ISSUE THREAD

**Issue by KillerQueen-dust** [PaddlePaddle/PaddleSeg#3672]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

报错信息：```ValueError: (InvalidArgument) transpose(): argument (position 2) must be list or tuple, but got int (at ..\paddle\fluid\pybind\op_function_common.cc:438)```

这行代码```x = (x + absolute_pos_embed).flatten(2).transpose(1, 2)  # B Wh*Ww C```直接照抄的吧，paddle根本运行不起来

### 复现环境 Environment

- PaddlePaddle: 2.9.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
