### ISSUE TITLE
 sphinx-build 创建html文档失败

### ISSUE THREAD

**Issue by OrdinaryChen** [PaddlePaddle/PaddleSeg#3674]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

 我在paddleseg/docs下使用sphinx-build -b html  . output创建html文档  但是失败，报错：
Extension error (sphinx_markdown_tables):
Handler <function process_tables at 0x7f2d15365940> for event 'source-read' threw an exception (exception: __init__() missing 1 required positional argument: 'config')
但是这个docs下是有conf.py啊  是哪里不对呢

### 复现环境 Environment

unbuntu20.04 in docker
sphinx                        7.1.2
sphinx-markdown-tables        0.0.15
sphinx-rtd-theme              2.0.0
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.1
sphinxcontrib-jquery          4.1
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5

### Bug描述确认 Bug description confirmation

- [x] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by ooooo-create** [comment]
升级 sphinx-markdown-tables 到 0.0.17 应该可以解决

**Comment by OrdinaryChen** [comment]
> 升级 sphinx-markdown-tables 到 0.0.17 应该可以解决

正解  已经解决了
