### ISSUE TITLE
nnUNetV1和nnUNetV2的差异？

### ISSUE THREAD

**Issue by dulicui742** [PaddlePaddle/PaddleSeg#3675]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

**现象**
原始训练数据相同(胸部CT)，经过MedicalSeg中nnUNet 预处理，训练，预测后的结果 和 直接使用官方nnUNetV2预处理，训练，预测出来的结果相差好多(支气管/血管断裂严重)；

**分析**
MedicalSeg中的nnUnet应该是按照nnUNetV1修改的，为此，从以下几个方面和官方nnUnetV2做了对比：
1、Processed Data，对比了预处理代码并可视化了预处理后的数据，并无太大差异；
2、网络结构，
3、优化函数、lr及其衰减策略；
4、loss函数
5、数据增强过程
6、训练过程

**问题**
造成测试结果有如此大差异的原因会有哪些呢？

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
