### ISSUE TITLE
为何我使用GPU训练出现直接退出

### ISSUE THREAD

**Issue by seastronger** [PaddlePaddle/PaddleSeg#3679]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

为何我使用GPU训练出现直接退出，而不安装pip install paddlepaddle-gpu==2.4.2，直接CPU训练就正常训练，退出的地方在训练过程中保存模型时进行评估时退出。以下是我的环境：
------------Environment Information-------------
platform: Windows-10-10.0.19041-SP0
Python: 3.6.13 |Anaconda, Inc.| (default, Mar 16 2021, 11:37:27) [MSC v.1916 64 bit (AMD64)]
Paddle compiled with cuda: True
NVCC: Build cuda_11.2.r11.2/compiler.29373293_0
cudnn: 8.1
GPUs used: 1
CUDA_VISIBLE_DEVICES: 0
GPU: ['GPU 0: NVIDIA GeForce']     是3060的显卡
PaddleSeg: 2.8.0
PaddlePaddle: 2.4.2
OpenCV: 4.5.5

**Comment by shiyutang** [comment]
你好，如果可以请升级并正确安装paddle2.6.0版本。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
