### ISSUE TITLE
paddleseg模型和onnx模型的推理结果不一致，精度差距较大

### ISSUE THREAD

**Issue by LS1030** [PaddlePaddle/PaddleSeg#3682]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

## 问题描述

发现`paddleseg`模型和使用`paddle2onnx`转换出来的`onnx`模型的推理结果不一致，精度差距较大。

不知道是因为什么原因导致的。

### 飞桨版本

```
paddle2onnx              1.1.0
paddlepaddle-gpu         2.5.1.post120
paddleseg                2.9.0    
```

## 问题复现

通过脚本计算`paddleseg`模型和`onnx`模型的miou不一致，使用同样的数据集测试的结果为：
```
paddle miou为95.10%，onnx miou为89.13%，精度差距较大
```

模型的目标是将地面与其他物体分割开，只分割两类，标签0为背景，标签1为背景。

通过查看推理的图片发现推理结果与miou表现一致，精度差距较大。
![推理结果对比](https://github.com/LS1030/paddle_onnx_test/blob/master/merge_images/back_20240112-111331_1009.png?raw=true "推理结果对比")
左边为原图，中间为paddleseg模型的推理结果，右边为onnx模型的推理结果。

具体的复现工程可以查看：https://github.com/LS1030/paddle_onnx_test.git

**Comment by wangkd0** [comment]
这个怎么处理，和导出时设置参数有关吗，另外导出时必须指定input_shape吗。不指定导出会报错

**Comment by shiyutang** [comment]
你好，和指定inputshape 没有关系，这说明paddle2onnx或者onnxruntime存在精度误差，请前往[paddle官网](https://github.com/paddlepaddle/paddle)提问或者切换其他后端。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
