### ISSUE TITLE
速度有点慢了！

### ISSUE THREAD

**Issue by 48383167** [PaddlePaddle/PaddleSeg#3683]
### 问题确认 Search before asking

- [x] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

用 ppmattingv2-stdc1-human_512.pdparams模型替换图片背景，对单张图片的替换需要2s 左右，后来我用flask先加载模型后速度达到了1s左右，这个速度正常吗 ？我感觉有点慢。有没有大佬指点指点 ？
我的设备是：
win11 ，3050

**Comment by shiyutang** [comment]
你好，如果想提升部署速度可以尝试使用triton进行高并发处理。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
