### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'to_static_training'

### ISSUE THREAD

**Issue by SijieY** [PaddlePaddle/PaddleSeg#3686]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![1711792371146](https://github.com/PaddlePaddle/PaddleSeg/assets/125887031/f68164d7-6d13-4d9d-a4fd-d00266852758)
这个问题怎么解决呢

**Comment by Alex37882388** [comment]
我也遇到这个问题，有人知道如何解决吗？

**Comment by Alex37882388** [comment]
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/24523802/b85142d7-72a4-4efb-8499-5f70d36a01f6)
什么时候升级2.9修复这个问题呢？

**Comment by Alex37882388** [comment]
#卸载2.8版本
pip unintall paddleseg
#克隆代码仓库并本地安装dev分支作为依赖
cd PaddleSeg && pip install -e /data/project/PaddleSeg

看git日志官方1月4日更新了代码，但是没有release到pypi，参照上面的方法修改，我先跑起来训练了。

**Comment by SijieY** [comment]
是下载develop吗，我这还是报同样的错。卸载掉paddleseg2.8之后，后面再装还是这个版本的啊

**Comment by SijieY** [comment]
> #卸载2.8版本 pip unintall paddleseg #克隆代码仓库并本地安装dev分支作为依赖 cd PaddleSeg && pip install -e /data/project/PaddleSeg
> 
> 看git日志官方1月4日更新了代码，但是没有release到pypi，参照上面的方法修改，我先跑起来训练了。

是下载develop吗，我这还是报同样的错。卸载掉paddleseg2.8之后，后面再装还是这个版本的啊

**Comment by Alex37882388** [comment]
> > #卸载2.8版本 pip unintall paddleseg #克隆代码仓库并本地安装dev分支作为依赖 cd PaddleSeg && pip install -e /data/project/PaddleSeg
> > 看git日志官方1月4日更新了代码，但是没有release到pypi，参照上面的方法修改，我先跑起来训练了。
> 
> 是下载develop吗，我这还是报同样的错。卸载掉paddleseg2.8之后，后面再装还是这个版本的啊

注意，是下面这样，把PaddleSeg开发版当做依赖包安装：
```bash
cd PaddleSeg
pip install -e /data/project/PaddleSeg
```

安装之后pip show paddleseg会显示版本为0.0.0.dev0，这是因为它引用了PaddleSeg/paddleseg/__init__.py里面写的版本号。。

**Comment by SijieY** [comment]
> > > #卸载2.8版本 pip unintall paddleseg #克隆代码仓库并本地安装dev分支作为依赖 cd PaddleSeg && pip install -e /data/project/PaddleSeg
> > > 看git日志官方1月4日更新了代码，但是没有release到pypi，参照上面的方法修改，我先跑起来训练了。
> > 
> > 
> > 是下载develop吗，我这还是报同样的错。卸载掉paddleseg2.8之后，后面再装还是这个版本的啊
> 
> 注意，是下面这样，把PaddleSeg开发版当做依赖包安装：
> 
> ```shell
> cd PaddleSeg
> pip install -e /data/project/PaddleSeg
> ```
> 
> 安装之后pip show paddleseg会显示版本为0.0.0.dev0，这是因为它引用了PaddleSeg/paddleseg/**init**.py里面写的版本号。。

![image](https://github.com/PaddlePaddle/PaddleSeg/assets/125887031/5834a6a2-6051-4c75-80ed-736523a97d34)
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/125887031/0f3adb42-b0e8-45a2-b605-b52fb58f46cc)
是这个意思吗，paddleseg版本变成2.9.0了

**Comment by LinHoujie** [comment]
> #卸载2.8版本 pip unintall paddleseg #克隆代码仓库并本地安装dev分支作为依赖 cd PaddleSeg && pip install -e /data/project/PaddleSeg
> 
> 看git日志官方1月4日更新了代码，但是没有release到pypi，参照上面的方法修改，我先跑起来训练了。

我参照上面的方法改了，还是同样的问题
请问您有解决到这个问题吗，怎么解决的呀

**Comment by LinHoujie** [comment]
> > > > #卸载2.8版本 pip unintall paddleseg #克隆代码仓库并本地安装dev分支作为依赖 cd PaddleSeg && pip install -e /data/project/PaddleSeg
> > > > 看git日志官方1月4日更新了代码，但是没有release到pypi，参照上面的方法修改，我先跑起来训练了。
> > > 
> > > 
> > > 是下载develop吗，我这还是报同样的错。卸载掉paddleseg2.8之后，后面再装还是这个版本的啊
> > 
> > 
> > 注意，是下面这样，把PaddleSeg开发版当做依赖包安装：
> > ```shell
> > cd PaddleSeg
> > pip install -e /data/project/PaddleSeg
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 安装之后pip show paddleseg会显示版本为0.0.0.dev0，这是因为它引用了PaddleSeg/paddleseg/**init**.py里面写的版本号。。
> 
> ![image](https://private-user-images.githubusercontent.com/125887031/318447921-5834a6a2-6051-4c75-80ed-736523a97d34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5OTU3MjgsIm5iZiI6MTcxMTk5NTQyOCwicGF0aCI6Ii8xMjU4ODcwMzEvMzE4NDQ3OTIxLTU4MzRhNmEyLTYwNTEtNGM3NS04MGVkLTczNjUyM2E5N2QzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxODE3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGY5MzRlNGYyYmUxNjU1NDcyMmYzZDNhZDY2ZGI0YTFjOGI2MGY3NzUzOWYxOTE5Mzk0YzA3MmQ0Yzk2NDdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x9wnWdYNv2XHxX8eQtdoXzk-FcLOPBRUuxDwEqR2xvE) ![image](https://private-user-images.githubusercontent.com/125887031/318448023-0f3adb42-b0e8-45a2-b605-b52fb58f46cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5OTU3MjgsIm5iZiI6MTcxMTk5NTQyOCwicGF0aCI6Ii8xMjU4ODcwMzEvMzE4NDQ4MDIzLTBmM2FkYjQyLWIwZTgtNDVhMi1iNjA1LWI1MmZiNThmNDZjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxODE3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjZlMmVmMzY2NWIzMjYxZWJhZGE1ZGUxZjMxMjA1ZTgzOTYwMjk3ZjZhMDBjZmQ2OGMxOWM4MGY0MGU3MjZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Eeil-HnauZDhWLPmotmF_E0nosAziKwAnbrFknTfd-U) 是这个意思吗，paddleseg版本变成2.9.0了

解决了吗

**Comment by SijieY** [comment]
> > > > > #卸载2.8版本 pip unintall paddleseg #克隆代码仓库并本地安装dev分支作为依赖 cd PaddleSeg && pip install -e /data/project/PaddleSeg
> > > > > 看git日志官方1月4日更新了代码，但是没有release到pypi，参照上面的方法修改，我先跑起来训练了。
> > > > 
> > > > 
> > > > 是下载develop吗，我这还是报同样的错。卸载掉paddleseg2.8之后，后面再装还是这个版本的啊
> > > 
> > > 
> > > 注意，是下面这样，把PaddleSeg开发版当做依赖包安装：
> > > ```shell
> > > cd PaddleSeg
> > > pip install -e /data/project/PaddleSeg
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 安装之后pip show paddleseg会显示版本为0.0.0.dev0，这是因为它引用了PaddleSeg/paddleseg/**init**.py里面写的版本号。。
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/125887031/318447921-5834a6a2-6051-4c75-80ed-736523a97d34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5OTU3MjgsIm5iZiI6MTcxMTk5NTQyOCwicGF0aCI6Ii8xMjU4ODcwMzEvMzE4NDQ3OTIxLTU4MzRhNmEyLTYwNTEtNGM3NS04MGVkLTczNjUyM2E5N2QzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxODE3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGY5MzRlNGYyYmUxNjU1NDcyMmYzZDNhZDY2ZGI0YTFjOGI2MGY3NzUzOWYxOTE5Mzk0YzA3MmQ0Yzk2NDdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x9wnWdYNv2XHxX8eQtdoXzk-FcLOPBRUuxDwEqR2xvE) ![image](https://private-user-images.githubusercontent.com/125887031/318448023-0f3adb42-b0e8-45a2-b605-b52fb58f46cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5OTU3MjgsIm5iZiI6MTcxMTk5NTQyOCwicGF0aCI6Ii8xMjU4ODcwMzEvMzE4NDQ4MDIzLTBmM2FkYjQyLWIwZTgtNDVhMi1iNjA1LWI1MmZiNThmNDZjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxODE3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjZlMmVmMzY2NWIzMjYxZWJhZGE1ZGUxZjMxMjA1ZTgzOTYwMjk3ZjZhMDBjZmQ2OGMxOWM4MGY0MGU3MjZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Eeil-HnauZDhWLPmotmF_E0nosAziKwAnbrFknTfd-U) 是这个意思吗，paddleseg版本变成2.9.0了
> 
> 解决了

**Comment by SijieY** [comment]
> > > > > #卸载2.8版本 pip unintall paddleseg #克隆代码仓库并本地安装dev分支作为依赖 cd PaddleSeg && pip install -e /data/project/PaddleSeg
> > > > > 看git日志官方1月4日更新了代码，但是没有release到pypi，参照上面的方法修改，我先跑起来训练了。
> > > > 
> > > > 
> > > > 是下载develop吗，我这还是报同样的错。卸载掉paddleseg2.8之后，后面再装还是这个版本的啊
> > > 
> > > 
> > > 注意，是下面这样，把PaddleSeg开发版当做依赖包安装：
> > > ```shell
> > > cd PaddleSeg
> > > pip install -e /data/project/PaddleSeg
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 安装之后pip show paddleseg会显示版本为0.0.0.dev0，这是因为它引用了PaddleSeg/paddleseg/**init**.py里面写的版本号。。
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/125887031/318447921-5834a6a2-6051-4c75-80ed-736523a97d34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5OTU3MjgsIm5iZiI6MTcxMTk5NTQyOCwicGF0aCI6Ii8xMjU4ODcwMzEvMzE4NDQ3OTIxLTU4MzRhNmEyLTYwNTEtNGM3NS04MGVkLTczNjUyM2E5N2QzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxODE3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGY5MzRlNGYyYmUxNjU1NDcyMmYzZDNhZDY2ZGI0YTFjOGI2MGY3NzUzOWYxOTE5Mzk0YzA3MmQ0Yzk2NDdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x9wnWdYNv2XHxX8eQtdoXzk-FcLOPBRUuxDwEqR2xvE) ![image](https://private-user-images.githubusercontent.com/125887031/318448023-0f3adb42-b0e8-45a2-b605-b52fb58f46cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5OTU3MjgsIm5iZiI6MTcxMTk5NTQyOCwicGF0aCI6Ii8xMjU4ODcwMzEvMzE4NDQ4MDIzLTBmM2FkYjQyLWIwZTgtNDVhMi1iNjA1LWI1MmZiNThmNDZjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxODE3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjZlMmVmMzY2NWIzMjYxZWJhZGE1ZGUxZjMxMjA1ZTgzOTYwMjk3ZjZhMDBjZmQ2OGMxOWM4MGY0MGU3MjZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Eeil-HnauZDhWLPmotmF_E0nosAziKwAnbrFknTfd-U) 是这个意思吗，paddleseg版本变成2.9.0了
> 
> 解决了吗

跑起来了，但我不确定这样做对不对

**Comment by Alex37882388** [comment]
Hi, LinHoujie，你可以尝试重置这个仓库再操作一遍：
```bash
git checkout -b develop origin/develop

pip uninstall paddleseg

pip install -e d:/your_path/PaddleSeg
```
