### ISSUE TITLE
关于显存占用过大问题

### ISSUE THREAD

**Issue by TechCraft0** [PaddlePaddle/PaddleSeg#3687]
### 问题确认 Search before asking

我想咨询一下，如果我训练自己的数据集，建议使用的显存大小是多少，目前，我的设备是12G显存，我使用pp-liteseg模型，设置batch size为4都出现OOM

### 环境 Environment

- OS: Linux
- paddlepaddle-gpu: 2.4.0rc0.post111
- PaddleSeg: 2.9.0
- python: 3.7.16
- CUDA: 12.2 
- CUDNN: 8.1.0
- GCC: 7.5.0
- 显卡: NVIDIA GeForce RTX 4070 
- 显存: 12G

**Comment by shiyutang** [comment]
你好，可以尝试减小图片输入的尺度，不过这个也许会对精度产生一定影响，12G显存不小，但也对于单卡训练来说也不是很大。其他降低显存方法可以采用fp16训练等。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
