### ISSUE TITLE
*demo的seg例子报错问题 the model is correct. Available fronted: Aborted core dumped.

### ISSUE THREAD

**Issue by funny000** [PaddlePaddle/PaddleSeg#3690]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Ask a Question: use fastdeploy demo pp_liteseg in linux c++,appear "the model is correct. available fronted: Aborted (core dumped)"

./exap /home/xd/Downloads/PP_LiteSeg_B_STDC2_cityscapes_without_argmax_infer /home/xd/Documents/examples/cityscapes_demo.png 0
[INFO] fastdeploy/vision/common/processors/transform.cc(93)::FuseNormalizeHWC2CHW	Normalize and HWC2CHW are fused to NormalizeAndPermute  in preprocessing pipeline.
[INFO] fastdeploy/vision/common/processors/transform.cc(159)::FuseNormalizeColorConvert	BGR2RGB and NormalizeAndPermute are fused to NormalizeAndPermute with swap_rb=1
terminate called after throwing an instance of 'ov::Exception'
  what():  [ NETWORK_NOT_READ ] Unable to read the model: 

/home/xd/Downloads/PP_LiteSeg_B_STDC2_cityscapes_without_argmax_infer/model.pdmodel Please check that model format: pdmodel is supported and the model is correct. Available frontends: 
Aborted (core dumped)

**Comment by shiyutang** [comment]
please try to raise this question in fastdeploy or paddlepaddle repository.

**Comment by funny000** [comment]
yes,i will




2152550864
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月11日(星期四) 晚上8:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] *demo的seg例子报错问题 the model is correct. Available fronted: Aborted core dumped. (Issue #3690)





 
please try to raise this question in fastdeploy or paddlepaddle repository.

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
