### ISSUE TITLE
模型导出问题

### ISSUE THREAD

**Issue by Daniel-969** [PaddlePaddle/PaddleSeg#3694]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我修改网络后，在导出模型的时候必须指定图片大小，否则会报错形状不匹配。
找到原因是在forward的时候需要拿到输入的shape，在导出的时候如果不设置图片大小，它会默认图片大小为-1，然后就会报错。
请问这个时候，我如果要预测裁剪后的cityscapes图片（如1024*1024），但原始图片是2048*1024，我应该怎么做才行。

**Comment by shiyutang** [comment]
你好，可以直接执行为预测图片大小，1024*1024。

**Comment by Daniel-969** [comment]
使用export.py指定输入大小(如 1024*512)后导出模型，这个时候用原始的cityscapes图片大小(2048*1024)执行infer.py函数是会报错形状不匹配的，这种情况我应该怎么做才能用原始cityscapes测试infer呢？因为我需要测量以1024*512大小的图片输入网络所需要的推理时间。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
