### ISSUE TITLE
could not create a descriptor for a pooling forward propagation primitive

### ISSUE THREAD

**Issue by izhaolinger** [PaddlePaddle/PaddleSeg#3695]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

在AMD CPU上进行人像分割的推理，使用的是ppmatting v2模型，出现could not create a descriptor for a pooling forward propagation primitive的异常。

但该异常并不是必现的，时而有时而无。

### 复现环境 Environment

操作系统：centos 7 
CPU： AMD EPYC 7642 48-Core Processor
内存：8G

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by shiyutang** [comment]
你好，这是一个paddlelite相关的问题，建议前往paddlelite或者paddle 仓库下进行提问。

**Comment by izhaolinger** [comment]
> 你好，这是一个paddlelite相关的问题，建议前往paddlelite或者paddle 仓库下进行提问。

好的，谢谢

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
