### ISSUE TITLE
模型推理问题

### ISSUE THREAD

**Issue by djl00** [PaddlePaddle/PaddleSeg#3696]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

为什么我在2080ti上能够复现成功且成功使用Tensorrt进行推理。但是我把模型放到3090ti上能够训练，但是推理的时候报错，显示数据不匹配，有什么解决方法吗

**Comment by shiyutang** [comment]
你好，请展示你具体的报错信息。

**Comment by djl00** [comment]
运行的时候报错：AssertionError: 
Not equal to tolerance rtol=0, atol=0.001

Mismatched elements: 1748394 / 5767168 (30.3%)
Max absolute difference: 0.00674272
Max relative difference: 58.494873
 x: array([[[[ 1.147214,  1.147214,  1.29746 , ...,  0.759871,  0.605249,
           0.605249],
         [ 1.147214,  1.147214,  1.29746 , ...,  0.759871,  0.605249,...
 y: array([[[[ 1.147725,  1.147725,  1.297974, ...,  0.76047 ,  0.60574 ,
           0.60574 ],
         [ 1.147725,  1.147725,  1.297974, ...,  0.76047 ,  0.60574 ,...

Process finished with exit code 1

**Comment by djl00** [comment]
运行代码为：python deploy/python/infer_onnx_trt.py --config
../../configs/pp_liteseg/pp_liteseg_stdc1_camvid_960x720_10k.yml
--width
1024
--height
512

**Comment by mandylyin** [comment]
@djl00 请问你这个问题解决了吗？我也遇到同样的问题，不知道怎么解决

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
