### ISSUE TITLE
可以部署自定义的模型训练自己的数据集吗

### ISSUE THREAD

**Issue by 2375963934a** [PaddlePaddle/PaddleSeg#3697]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

部署自己的模型自动标注怎么设置

**Comment by shiyutang** [comment]
你好，你的表述似乎不是很清楚，部署的时候是用于推理，因此请进一步描述你是想要训练时模型自定义还是数据集自定义呢？或者是其他什么意思呢？

**Comment by 2375963934a** [comment]
训练自己的数据集来自动标注

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
