### ISSUE TITLE
No module named 'paddle'

### ISSUE THREAD

**Issue by zhaolei2019** [PaddlePaddle/PaddleSeg#3700]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

python版本：3.12；
paddlepadedle版本：GPU版 2.6；
按照正常的安装流程进行，paddlepaddle验证安装成功，只有一个python环境，
执行命令pip install -v -e .时报错： ModuleNotFoundError: No module named 'paddle'

**Comment by ooooo-create** [comment]
可能是 python 版本过高的原因叭~，试试其他 python 版本（也可能文档没有更新
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/106524776/fab8c8d8-0891-49d1-85bc-c48dc9278ac2)

**Comment by zhaolei2019** [comment]
> 可能是 python 版本过高的原因叭~，试试其他 python 版本（也可能文档没有更新 ![图像](https://private-user-images.githubusercontent.com/106524776/323470410-fab8c8d8-0891-49d1-85bc-c48dc9278ac2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NDg5NTMsIm5iZiI6MTcxMzc0ODY1MywicGF0aCI6Ii8xMDY1MjQ3NzYvMzIzNDcwNDEwLWZhYjhjOGQ4LTA4OTEtNDlkMS04NWJjLWM0OGRjOTI3OGFjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQwMTE3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGNhZjI0ZGU5OWM2NjUxZTMzZTMwY2NhZWUyMjFkNzlkNjNkNDVlYjFlMzA5MmI5ZjI4YWQ4ZTMxOWI0ZGZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XDJN46wu0kmhI61v_IlGdjR4FrRDYgrLdp3QliEwyeE)

感谢，python降级到3.10后好用了

**Comment by CuteBadEgg** [comment]
"pip install PaddlePaddle " ,solved！

**Comment by leach-chen** [comment]
有效我是3.12版本，一直报这个错，降低到3.10就正常了，感谢！

**Comment by hysjly** [comment]
> "pip install PaddlePaddle " ,solved！
非常感谢，成功解决

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
