### ISSUE TITLE
PPMatting对人像视频抠图，动作片段抠图边缘效果不佳，怎么做优化呢

### ISSUE THREAD

**Issue by hyxzhang** [PaddlePaddle/PaddleSeg#3701]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，请教下，最近我在研究人物视频抠图，基于PPMatting进行的人像抠图，其中ppmatting-hrnet_w18-human_1024的抠图效果精度挺高的，但是也遇到一些问题，当视频中人物做动作时，出现重影，手部抠图效果不佳，如下所示，请教下怎么基于ppmatting-hrnet_w18-human_1024这个公开模型进行优化训练，以达到好的动态抠图效果，大概需要多少数据集量。
![抠图效果重影](https://github.com/PaddlePaddle/PaddleSeg/assets/160761669/d33ca027-5ffb-482e-9d66-f547633b4635)

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
