### ISSUE TITLE
不知道是不是我数据格式不对，eiseg打开tif图片就报错并退出界面，后端报错 NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix will be returned.

### ISSUE THREAD

**Issue by zzwtop1** [PaddlePaddle/PaddleSeg#3704]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

 eiseg打开tif图片，后端报错NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix will be returned.
TypeError: __new__() missing 5 required positional arguments: 'b', 'c', 'd', 'e', and 'f'

### 复现环境 Environment

paddle 2.5.2
eiseg 1.1.2

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by julinfn** [comment]
遥感图像没有坐标？

**Comment by zzwtop1** [comment]
好像是图片的问题，同事处理的，太久了忘了具体情况了
