### ISSUE TITLE
部署时的loadimage预处理问题

### ISSUE THREAD

**Issue by gunh4mmer** [PaddlePaddle/PaddleSeg#3706]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

如#1858和#1745所说，我根据PaddleSeg\Matting\ppmatting\transforms\transforms.py中对于loadimage预处理类的理解，因为matting模型与传统语义分割不同，数据集可能有三值图trimap的情况，因此在matting模型训练中，新增了该loadimage预处理，为了来区分rgb与gbr，区分图像是src、alpha、trimap，但是直到目前为止paddleX与fastdeploy所支持的预处理方法中均没有loadimage方法

**Comment by gunh4mmer** [comment]
如果按照我以上对loadimage的理解，它仅仅是对图像的分类处理，按理来说并不应该出现在预测模型的配置文件中？除此以外，应工程需要，环境为.net，以目前情况来看，似乎只有将paddle模型转为onnx模型一条路可走，是否还有其他可以解决该问题的方法

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
