### ISSUE TITLE
Obtain mask

### ISSUE THREAD

**Issue by zj114514** [PaddlePaddle/PaddleSeg#3708]
### 问题确认 Search before asking

- [x] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Using the human_pp_humansegv2 model, how to obtain the mask map of segmented pictures？

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
