### ISSUE TITLE
QualityInspector无监督学习,padim_resnet18_mvtec训练后对good图做预测结果也很差.

### ISSUE THREAD

**Issue by David-dotcom666** [PaddlePaddle/PaddleSeg#3711]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

![bottle_pre_0](https://github.com/PaddlePaddle/PaddleSeg/assets/84842493/151f08ef-6c31-4246-95e5-cd9c2c191035)
配置如下:
# common arguments
device: gpu
seed: 3

# dataset arguments
batch_size: 1
num_workers: 0
category: bottle
resize: [256, 256]
crop_size: [224, 224]
data_path: data/mvtec_anomaly_detection
save_path: output/

# train arguments
do_eval: False  # After training, whether to eval model;
backbone: resnet18  # Support resnet18, resnet50, wide_resnet50_2

# val and predict arguments
save_pic: True # Whether to save one output example picture in val and predict;
model_path: output/resnet18/bottle/bottle.pdparams

# predict arguments
img_path: data/mvtec_anomaly_detection/bottle/test/good/001.png
threshold: 0.5
另外除了这个，另外两种算法都无法运行.

### 复现环境 Environment

paddle 2.6.1
paddleseg 2.8
cuda 11.7,cudnn 8.4.1

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by LijialinHub** [comment]
这个东西本身就是小孩儿玩具 ，不稳定的  不建议商用，无法落地的

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
