### ISSUE TITLE
AttributeError: module 'cv2.dnn' has no attribute 'DictValue'

### ISSUE THREAD

**Issue by tsongsun** [PaddlePaddle/PaddleSeg#3712]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

按照官方文档安装paddlepaddle和EISeg后，在虚拟环境中启动EISeg失败。报错：AttributeError: module 'cv2.dnn' has no attribute 'DictValue'

### 复现环境 Environment

Windows
python 3.8
paddlepaddle==2.6.1 cpu

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by virtual8888** [comment]
一样的问题，git clone 下来也是各种问题打不开

**Comment by virtual8888** [comment]
pip install eiseg我也是这个问题。 后面git clone了，官网上漏了一句，还要安装 PaddleSeg\EISeg 下的 requirements.txt

**Comment by fanfan838012328** [comment]
我安装requirements.txt之后还有这个问题

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.

**Comment by Septembit** [comment]
你好， 我也遇到这个问题了， 请问一下你们解决了吗
