### ISSUE TITLE
RSSegBenchmark-c2fnet复现出现bug

### ISSUE THREAD

**Issue by famersalltheday** [PaddlePaddle/PaddleSeg#3715]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

'''NotImplementedError: (Unimplemented) Invalid dimension to be accessed. Now only supports access to dimension 0 to 9, but received dimension is 10. (at C:\home\workspace\Paddle_release\paddle/phi/core/ddim.h:53)
  [operator < split > error]'''

我在复现C2FNet模块的时候，出现了上述bug，我曾见其他人员提出过这个问题，但是它依然存在。我严格按照官方指定的环境进行测试，出现了这个bug。我升级各种版本的paddlepaddle，但是bug依然存在，希望可以得到帮助解决，谢谢。

### 复现环境 Environment

Python: 3.7
PaddlePaddle: 2.3.2
PaddleSeg: 2.6

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
