### ISSUE TITLE
我参照文档训练自己的数据集，效果不好，但是不知道从哪里着手优化，能否帮我看一下？

### ISSUE THREAD

**Issue by zuonidelaowang** [PaddlePaddle/PaddleSeg#3716]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

参照文档
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.9/Matting/docs/full_develop_cn.md#%E6%95%B0%E6%8D%AE%E9%9B%86%E5%87%86%E5%A4%87

需求是这样的
输入原图
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/16249614/bb117a4e-5edf-4f07-8fd7-5ad5378518cf)
抠出衣服
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/16249614/d0b6e519-d811-4fd5-a833-5854c1756d56)

我自己用了650张图片来训练，但是效果却是下面这样的，没有抠出衣服，我应该从哪里着手优化。
谢谢了。

原图
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/16249614/30c751ba-2a15-428a-96ee-ea6d24a7bcd4)
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/16249614/d611642e-0f3a-4ed3-8356-875db04fd627)
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/16249614/0d701f3c-5600-4a69-b21b-c6d91176a436)

评估出来的图
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/16249614/4bc863e9-3644-4287-a739-64acc1e532f8)
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/16249614/33fd8334-46cf-4983-8c2a-960c8d45e883)
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/16249614/de315e1f-7440-46dd-af43-07af3bbbbd65)

**Comment by izhaolinger** [comment]
看着像是数据量不够，您方便给少量您训练时的数据demo看看吗？

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
