### ISSUE TITLE
U-Net模型eval和vis问题

### ISSUE THREAD

**Issue by gxqnba** [PaddlePaddle/PaddleSeg#372]
使用的是自己的数据集（gt图像是灰度图像，背景黑色，目标为白色），通过了数据检校
训练好之后进行eval：python pdseg/eval.py --use_gpu --cfg ./configs/unet_optic.yaml，报错如下：
[EVAL]step=1 loss=0.00022 acc=1.0000 IoU=0.5000 step/sec=2.59 | ETA 00:00:01
[EVAL]step=2 loss=0.00023 acc=1.0000 IoU=0.5000 step/sec=8.15 | ETA 00:00:00
[EVAL]step=3 loss=0.00025 acc=1.0000 IoU=0.5000 step/sec=8.96 | ETA 00:00:00
[EVAL]step=4 loss=0.00024 acc=1.0000 IoU=0.5000 step/sec=9.09 | ETA 00:00:00
[EVAL]step=5 loss=0.00024 acc=1.0000 IoU=0.5000 step/sec=16.76 | ETA 00:00:00
[EVAL]#image=18 acc=1.0000 IoU=0.5000
[EVAL]Category IoU: [1.0000 0.0000]
[EVAL]Category Acc: [1.0000 0.0000]
/home/aistudio/work/PaddleSeg/pdseg/metrics.py:144: RuntimeWarning: invalid value encountered in double_scalars
  kappa = (po - pe) / (1 - pe)
[EVAL]Kappa:nan

另外，在进行vis时：python pdseg/vis.py --use_gpu --cfg ./configs/unet_optic.yaml，得到的分割结果是一张全黑图像

**Comment by wuyefeilin** [comment]
背景为0， 目标为1， 你看看数据集的标注是否符合要求

**Comment by gxqnba** [comment]
> 背景为0， 目标为1， 你看看数据集的标注是否符合要求

谢谢了，我的目标像素是255，改过来就好了。

**Comment by lyc1995452-star** [comment]
你好，你在预测时出现过这种情况没
Traceback (most recent call last):
File "vis.py", line 212, in
visualize(cfg, **args.dict)
File "vis.py", line 133, in visualize
for imgs, grts, img_names, valid_shapes, org_shapes in test_reader:
File "/PaddleSeg-release-v0.7.0/pdseg/reader.py", line 136, in batch_reader
for img, grt, img_name, valid_shape, org_shape in reader():
File "/PaddleSeg-release-v0.7.0/pdseg/reader.py", line 81, in generator
yield self.process_image(line, self.data_dir, self.mode)
File "/PaddleSeg-release-v0.7.0/pdseg/reader.py", line 251, in process_image
line, data_dir, mode=mode)
File "/PaddleSeg-release-v0.7.0/pdseg/reader.py", line 205, in load_image
grt_height = grt.shape[0]
IndexError: tuple index out of range
