### ISSUE TITLE
batchsize设置为16的时候报错设置为32or2可以正常运行

### ISSUE THREAD

**Issue by swy0823** [PaddlePaddle/PaddleSeg#3722]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

 报错详情：`Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1716346117 (unix time) try "date -d @1716346117" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 31388 (TID 0x7f23faf08700) from PID 0 ***]

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
