### ISSUE TITLE
C++推理不同size图像代码报错

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleSeg#3726]
### 问题描述 Please describe your issue

您好 ，我这边发现了一个问题，例如 ：我第一次处理的图像是640*640，我第二次处理第一次运行图像的一部分（320*320），此时就会出现问题 ，报错信息是外部组件发生异常，如果我 反过来第一次处理的是320*320的，第二次处理640*640还是会报错，请问这种问题如何解决呢？
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/87969070/ad437a7f-0b71-49c8-91b9-53a2d04e7673)

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
