### ISSUE TITLE
humanseg 能分割纯背面人像嘛

### ISSUE THREAD

**Issue by wei-ma** [PaddlePaddle/PaddleSeg#3734]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

能分割背面人像嘛？只有后脑勺或者只有一点点人脸

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
