### ISSUE TITLE
Eiseg:启动遥感模式之后,打开.tif结尾图片不显示

### ISSUE THREAD

**Issue by fanfan838012328** [PaddlePaddle/PaddleSeg#3736]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

打开遥感模式之后,导入.tif图片不显示,后台报错
```Traceback (most recent call last):
  File "D:\software\anaconda202402\envs\eiseg_test\Lib\site-packages\eiseg\app.py", line 1381, in openImage
    if not self.loadImage(filePath):
  File "D:\software\anaconda202402\envs\eiseg_test\Lib\site-packages\eiseg\app.py", line 1535, in loadImage
    self.raster = Raster(path)
  File "D:\software\anaconda202402\envs\eiseg_test\Lib\site-packages\eiseg\plugin\remotesensing\raster.py", line 61, in __init__
    self.geoinfo = self.__getRasterInfo()
  File "D:\software\anaconda202402\envs\eiseg_test\Lib\site-packages\eiseg\plugin\remotesensing\raster.py", line 80, in __getRasterInfo
    geoinfo.geotf = meta["transform"]
  File "D:\software\anaconda202402\envs\eiseg_test\lib\site-packages\easydict\__init__.py", line 149, in __setattr__
    value = type(value)(self.__class__(x)
TypeError: __new__() missing 5 required positional arguments: 'b', 'c', 'd', 'e', and 'f'
```

### 复现环境 Environment

- OS:Windows11
- Paddlepaddle:2.6.1,CPU版本
- python:3.9.19

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by funny000** [comment]
楼主你是标注多大的图像

**Comment by Chaiy1** [comment]
我也遇到同样的问题

**Comment by ELfinxin** [comment]
同样的问题，不知道如何解决

**Comment by ELfinxin** [comment]
> 我也遇到同样的问题

请问您解决这个问题了吗

**Comment by Chaiy1** [comment]
用arcgis打标签

**Comment by ELfinxin** [comment]
> ### 问题确认 Search before asking
> * [x]  我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.
> 
> ### Bug描述 Describe the Bug
> 打开遥感模式之后,导入.tif图片不显示,后台报错
> 
> ```
>   File "D:\software\anaconda202402\envs\eiseg_test\Lib\site-packages\eiseg\app.py", line 1381, in openImage
>     if not self.loadImage(filePath):
>   File "D:\software\anaconda202402\envs\eiseg_test\Lib\site-packages\eiseg\app.py", line 1535, in loadImage
>     self.raster = Raster(path)
>   File "D:\software\anaconda202402\envs\eiseg_test\Lib\site-packages\eiseg\plugin\remotesensing\raster.py", line 61, in __init__
>     self.geoinfo = self.__getRasterInfo()
>   File "D:\software\anaconda202402\envs\eiseg_test\Lib\site-packages\eiseg\plugin\remotesensing\raster.py", line 80, in __getRasterInfo
>     geoinfo.geotf = meta["transform"]
>   File "D:\software\anaconda202402\envs\eiseg_test\lib\site-packages\easydict\__init__.py", line 149, in __setattr__
>     value = type(value)(self.__class__(x)
> TypeError: __new__() missing 5 required positional arguments: 'b', 'c', 'd', 'e', and 'f'
> ```
> 
> ### 复现环境 Environment
> * OS:Windows11
> * Paddlepaddle:2.6.1,CPU版本
> * python:3.9.19
> 
> ### Bug描述确认 Bug description confirmation
> * [x]  我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.
> 
> ### 是否愿意提交PR？ Are you willing to submit a PR?
> * [ ]  我愿意提交PR！I'd like to help by submitting a PR!

请问楼主是否解决这个问题

**Comment by ELfinxin** [comment]
已解决：修改.\eiseg\plugin\remotesensing\raster.py中__getRasterInfo函数，将geoinfo.geotf = meta["transform"]改为geoinfo.geotf = list(meta["transform"])，即可读取遥感影像

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
