### ISSUE TITLE
怎么导出比 192x192 更小的模型？ 

### ISSUE THREAD

**Issue by sg0771** [PaddlePaddle/PaddleSeg#3737]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

怎么导出比 192x192 更小的模型？

请问一下 HumanSeg 在Win7 上不能使用GPU加速时， CPU 跑起来比较慢，怎么才能加速

**Comment by michaelowenliu** [comment]
不建议更小了

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
