### ISSUE TITLE
Matting 自定数据集训练问题

### ISSUE THREAD

**Issue by izhaolinger** [PaddlePaddle/PaddleSeg#3739]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我使用ppmattingv2-stdc1-human_512，根据自定义数据集训练了自己的模型，加载了ppmattingv2-stdc1-human_512.pdparams作为预训练模型，但预测的结果很奇怪。

原图：
![1](https://github.com/PaddlePaddle/PaddleSeg/assets/29848522/d2d16f22-b06e-496e-9f89-3934baae4ff1)

预测的alpha图：
![1_alpha](https://github.com/PaddlePaddle/PaddleSeg/assets/29848522/71f561f5-318d-4d9a-aa2c-462171a3926c)

预测的结果图：
![1_rgba](https://github.com/PaddlePaddle/PaddleSeg/assets/29848522/65ff9cfc-4c6d-4335-a594-1f6f46832748)

请问这可能是什么问题呢？

**Comment by izhaolinger** [comment]
预测出来的mask图为什么会是灰度图？而不是黑白的呢？

**Comment by izhaolinger** [comment]
请大家帮忙看看~

**Comment by izhaolinger** [comment]
@wuyefeilin

可以请您指导下吗

**Comment by izhaolinger** [comment]
真心请教，付费咨询

**Comment by michaelowenliu** [comment]
不经过自定义数据集，直接使用官方预训练模型的结果正常吗？

**Comment by yuqilol** [comment]
你好，你的loss怎么设定的，我的ppmattingv2缺失了loss好神奇，The failed rule is DefaultPrimaryRule, and the error message is: 
No loss specified in the configuration file.

**Comment by izhaolinger** [comment]
> 不经过自定义数据集，直接使用官方预训练模型的结果正常吗？

是正常的

**Comment by izhaolinger** [comment]
> 你好，你的loss怎么设定的，我的ppmattingv2缺失了loss好神奇，The failed rule is DefaultPrimaryRule, and the error message is: No loss specified in the configuration file.

我的loss没有做改动，用的官方配置文件给出的值，您这个看起来像是把loss配置删除了？

**Comment by yuqilol** [comment]
> > 你好，你的loss怎么设定的，我的ppmattingv2缺失了loss好神奇，The failed rule is DefaultPrimaryRule, and the error message is: No loss specified in the configuration file.
> 
> 我的loss没有做改动，用的官方配置文件给出的值，您这个看起来像是把loss配置删除了？

这个问题我已经解决了，是工作目录问题，要在matting目录下运行才有loss

**Comment by yuqilol** [comment]
> > 不经过自定义数据集，直接使用官方预训练模型的结果正常吗？
> 
> 是正常的

我的是不正常的，我直接用官方的aplha是没有结果的

**Comment by yuqilol** [comment]
![human_alpha](https://github.com/PaddlePaddle/PaddleSeg/assets/52739016/a37e4178-f49b-4f1c-bd51-7f8bf64b4000)
![Uploading human_rgba.png…]()

**Comment by yuqilol** [comment]
@michaelowenliu 
使用命令如下
python tools/predict.py --config configs/ppmattingv2/ppmattingv2-stdc1-human_512.yml --model_path checkpoint/ppmattingv2-stdc1-human_512.pdparams --image_path demo/human.jpg  --save_dir ./output/results --fg_estimate True
配置文件未改动过，电脑windows cpu端，更改device为cpu之后输出结果仍旧一致。

**Comment by LeslisXu** [comment]
我也是一模一样，自己使用了ppmattingv2-stdc1-human_512做微调，得到的结果也是灰度图，但是不做微调，直接使用下载下来的pretrain model结果就是正常的。

**Comment by izhaolinger** [comment]
> 我也是一模一样，自己使用了ppmattingv2-stdc1-human_512做微调，得到的结果也是灰度图，但是不做微调，直接使用下载下来的pretrain model结果就是正常的。

请问你的问题解决了吗？

**Comment by LeslisXu** [comment]
> > 我也是一模一样，自己使用了ppmattingv2-stdc1-human_512做微调，得到的结果也是灰度图，但是不做微调，直接使用下载下来的pretrain model结果就是正常的。
> 
> 请问你的问题解决了吗？

没有解决，但是我决定试一试用PP3-100数据集等试一下。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
