### ISSUE TITLE
使用fastdeploy C++预编译库推理时，结果score_map为空值，导出模型时设置--output_op none一样没有解决，有什么其他办法吗？

### ISSUE THREAD

**Issue by Evle-liu** [PaddlePaddle/PaddleSeg#3740]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用fastdeploy C++预编译库推理时，结果score_map为空值，导出模型时设置--output_op none一样没有解决，有什么其他办法吗？

**Comment by viwe-monai** [comment]
【FastDeploy版本】：fastdeploy-gpu-python 1.0.7
【系统平台】: Windows x64(Windows11)
【硬件】： 说明具体硬件型号，如 Nvidia GPU 4060， CUDA 11.6 CUDNN 8.4
【语言】： Python
同样遇到该问题，预训练pp_liteseg模型stdc1，导出模型已经设置--output_op none；输出的score_map是空值

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
