### ISSUE TITLE
请问使用paddleseg怎么构建图文大模型，比如做语义分割的？

### ISSUE THREAD

**Issue by funny000** [PaddlePaddle/PaddleSeg#3741]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包含open与closed)，没有类似需求。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标
使用自己的数据构建一个图文大模型，支持分割、检测等任务
请问paddle有相关的方法吗

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
