### ISSUE TITLE
多卡改单卡问题，学习率和iters需要对应调整吗

### ISSUE THREAD

**Issue by zhangshaotong** [PaddlePaddle/PaddleSeg#3744]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在复现cityscapes时，始终达不到论文的精度，我是用的两卡2080ti，lr和iters都没改，比论文差1%，如果用双卡或单卡 是不是相对于四卡同时训练 需要调整参数 请教一下

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
