### ISSUE TITLE
可以支持mha格式数据标注么

### ISSUE THREAD

**Issue by zhenligod** [PaddlePaddle/PaddleSeg#3745]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包含open与closed)，没有类似需求。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标脑科学亚微米成像数据标注; 2. 需求场景深亚微米脑科学数据标注，用于脑科学图谱; 3. 功能描述支持mha格式、ims格式数据标注

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
