### ISSUE TITLE
怎么将MaskFormer的模型转换为ONNX模型

### ISSUE THREAD

**Issue by dadaligoudan** [PaddlePaddle/PaddleSeg#3747]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，我用自己的数据集训练了一个MaskFormer的模型，参考https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.9/docs/model_export_onnx_cn.md
可以将paddle的模型成功转换为预测模型文件。但是将预测模型文件转为ONNX时，提示
![1719985195350](https://github.com/PaddlePaddle/PaddleSeg/assets/33470552/2ef7d3c7-1840-4b8f-a45e-2613f7388d13)
请问如何解决这个问题呢？谢谢。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
