### ISSUE TITLE
pp-human-matting的结果与论文里面的结果并不一致，是否GitHub提供的模型，并非是跑出论文里面结果的模型？

### ISSUE THREAD

**Issue by WilliamOChai** [PaddlePaddle/PaddleSeg#3753]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

论文里面提到用超过1w张人像和7.7w张背景进行训练，训练结果很优秀，GitHub提供的human_matting-resnet34_vd.pdparams，与论文里面结果相似，但仍有差距，请问是否两者并非同一模型呢？

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
