### ISSUE TITLE
Compatibility of Model with Backbone

### ISSUE THREAD

**Issue by jawi289o** [PaddlePaddle/PaddleSeg#3754]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

How can I determine which model is compatible with which backbone? Can I use any backbone with a single model, or are there specific constraints? I'm unclear about this.

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
