### ISSUE TITLE
pp_liteseg模型池化层疑问

### ISSUE THREAD

**Issue by enemy1205** [PaddlePaddle/PaddleSeg#3755]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用https://github.com/PaddlePaddle/PaddleSlim/blob/9f3e9b2f0f9948b780900d1299f2c3fe47322deb/example/auto_compression/semantic_segmentation/README.md
提供的pp_liteseg模型
使用`paddle2onnx --model_dir RES-paddle2-PPLIteSegSTDC1 --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 13 --save_file output.onnx`命令转为onnx模型后发现
```
Node name: p2o.AveragePool.0
Kernel shape: [3, 3]
Strides: [2, 2]
Pads: [1, 1, 1, 1]
Node name: p2o.AveragePool.1
Kernel shape: [3, 3]
Strides: [2, 2]
Pads: [1, 1, 1, 1]
Node name: p2o.AveragePool.2
Kernel shape: [3, 3]
Strides: [2, 2]
Pads: [1, 1, 1, 1]
Node name: p2o.AveragePool.3
Kernel shape: [-1, -1]
Strides: [0, 0]
Node name: p2o.AveragePool.4
Kernel shape: [-1, -1]
Strides: [0, 0]
```
其中`p2o.AveragePool.3`和`p2o.AveragePool.4`层的kernel shape为-1
为什么AveragePool 层的 kernel_shape 属性为负值呢

**Comment by cookielicker** [comment]
同问

**Comment by mjz0110** [comment]
同问，我也遇到了这个问题

**Comment by reza-shahriari** [comment]
have you solved it?
i have the same porblem

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
