### ISSUE TITLE
Regarding training the model on custom dataset for ariel images on binary segmentation.

### ISSUE THREAD

**Issue by goku206125** [PaddlePaddle/PaddleSeg#3760]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![warsaw_0_-1_osm_resized](https://github.com/user-attachments/assets/d994c707-9a00-4db6-8b8b-7b81edc85c43)

![warsaw_0_-1_sat_resized](https://github.com/user-attachments/assets/3c7e313e-8a46-477b-a000-490f66e8b9ce)

Can you please tell me how I should make my own dataset config file to use paddleseg to train model on my own dataset.

I have to segment two classes ( "road' and "not road") from ariel images. I have following the custom dataset instructions but its not helping. 

I have used the custom dataset tutorial ( python tools/data/split_dataset_list.py D:\PaddleSeg\data D:\PaddleSeg\data\images D:\PaddleSeg\data\labels --split 0.6 0.2 0.2  --format "jpg" "jpg") to split my dataset. 

But after changing the parameters of model, it is getting error 
 File "C:\Users\nn\miniconda3\envs\paddleseg\lib\site-packages\paddle\nn\functional\loss.py", line 2818, in cross_entropy
    _, out = _C_ops.cross_entropy_with_softmax(
ValueError: (InvalidArgument) Input(Logits) and Input(Label) should in same shape in dimensions except axis.
  [Hint: Expected logits_dims[i] == labels_dims[i], but received logits_dims[i]:512 != labels_dims[i]:3.] (at ..\paddle\phi\infermeta\binary.cc:940).
  
  
[config_paddle.txt](https://github.com/user-attachments/files/16386456/config_paddle.txt)

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
