### ISSUE TITLE
predict中无法使用GPU进行预测，device判断疑似bug，永远无法相等

### ISSUE THREAD

**Issue by YuetKaka15** [PaddlePaddle/PaddleSeg#3765]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

在tools\predict.py中，对于设备device的判断。
gpu设备会默认为 'gpu:0'，而在utils\utils.py中对device的判断函数def set_device(device)中会判断是否直接相等，if 'gpu:0 '== 'gpu' ......，是否不会相等？从而只能默认使用cpu。
<img width="523" alt="bbfa172b6667305465f52cbbb13d4eb" src="https://github.com/user-attachments/assets/03858557-f5cc-44a5-9682-74752490c3bf">
<img width="471" alt="04a601c300b7dca4fcb67bde0e1b2e4" src="https://github.com/user-attachments/assets/1a763fc9-5be3-413c-87be-751ff4ef4512">

假若我将此判断修改，使得能使用GPU进行predict，得出的结果依旧有问题，因此不知道是不是此判断不能修改，若此处确实为bug，后续可以提供Pull Request修复后续问题。
![image](https://github.com/user-attachments/assets/f60d81a6-29ba-423a-a68e-47c5f284f394)
![image](https://github.com/user-attachments/assets/f756fc57-f831-435b-87c3-79d83a888ba3)

### 复现环境 Environment

![image](https://github.com/user-attachments/assets/9cd4edcf-6bb5-4a79-a88e-c1e0ab08a1b1)

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by YuetKaka15** [comment]
![image](https://github.com/user-attachments/assets/0f6afe67-4a80-4aa3-b3ad-74f49bde98ee)
补充：调用的set_device函数位置

**Comment by Bobholamovic** [comment]
你好，请问你使用的是哪个版本的PaddleSeg呀？我注意到在最新的稳定版本应该是没有这个问题的～

**Comment by YuetKaka15** [comment]
我之前一直尝试cuda不成功，索性更换了cuda版本，也重装了最新的paddle，现在是正常的了。之前的版本应该是3.0beta-cuda12.3 但是我怀疑是我安装Paddleseg出错了，程序调用函数调错了位置，paddleseg的版本已经忘了，那个paddleseg.utils.utils.py可能你们已经弃用了。
