### ISSUE TITLE
LAUNCH WARNING 2024-08-01 00:44:29,461 save gpu log failed [2024-08-01 00:44:29,461] [ WARNING] watcher.py:92 - save gpu log failed LAUNCH WARNING 2024-08-01 00:45:02,626 save gpu log failed [2024-08-01 00:45:02,626] [ WARNING] watcher.py:92 - save gpu log failed

### ISSUE THREAD

**Issue by caolingen2022** [PaddlePaddle/PaddleSeg#3767]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

LAUNCH WARNING 2024-08-01 00:44:29,461 save gpu log failed
[2024-08-01 00:44:29,461] [ WARNING] watcher.py:92 - save gpu log failed
LAUNCH WARNING 2024-08-01 00:45:02,626 save gpu log failed
[2024-08-01 00:45:02,626] [ WARNING] watcher.py:92 - save gpu log failed

### 复现环境 Environment

LAUNCH WARNING 2024-08-01 00:44:29,461 save gpu log failed
[2024-08-01 00:44:29,461] [ WARNING] watcher.py:92 - save gpu log failed
LAUNCH WARNING 2024-08-01 00:45:02,626 save gpu log failed
[2024-08-01 00:45:02,626] [ WARNING] watcher.py:92 - save gpu log failed

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by cuicheng01** [comment]
您好，建议使用官方的docker来训练

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_

**Comment by caolingen2022** [comment]
我用的是官方的代码训练的

**Comment by cuicheng01** [comment]
有使用官方镜像吗？

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
