### ISSUE TITLE
ppliteseg模型推理时是否有置信度数据

### ISSUE THREAD

**Issue by alanxinn** [PaddlePaddle/PaddleSeg#3768]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用ppliteseg推理，直接给出INT32的分割结果数据，是否有置信度数据？

**Comment by cuicheng01** [comment]
可以通过修改后处理来支持

**Comment by alanxinn** [comment]
@cuicheng01 
![image](https://github.com/user-attachments/assets/059076c1-6352-476d-88f5-40f09e942b0d)
输入图像数据为 [1,3,1440,1080]
获取bilinear_interp_v2_6.tmp_0的数据，根据该数据进行对比，发现概率值为不确定的，如下图所示
![image](https://github.com/user-attachments/assets/5f612e0e-db51-45b1-9f93-21c84c699ac9)
左边为background的概率值，右边为种类1的概率值，arg_max只是提取每个像素位置的种类最大值，但是这个值我观察没有固定范围 类似置信度0-1

**Comment by Bobholamovic** [comment]
在导出模型时传入`--output_op softmax`可以使模型输出置信度。

**Comment by alanxinn** [comment]
> 在导出模型时传入`--output_op softmax`可以使模型输出置信度。

好的，谢谢
