### ISSUE TITLE
面对大图片网格标注时边缘部分将无法显示

### ISSUE THREAD

**Issue by WalkerZJH** [PaddlePaddle/PaddleSeg#3773]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

我使用3000\*4000的图片标注时图像被分割为6\*8的宫格，但是边缘部分既无法标注，也无法生成有效标签。
初步推测问题出现于
PaddleSeg-release-2.9.1\PaddleSeg-release-2.9.1\EISeg\eiseg\plugin\n2grid\grid.py
文件，如果希望解决这个问题也许可以尝试在图像边缘paddle，保证图像可以被网格整除。

### 复现环境 Environment

环境不是必须的。

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by zhang-prog** [comment]
收到，晚些时候我们去确认下。

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
