### ISSUE TITLE
PPLiteSeg

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleSeg#3774]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，如何修改这个PPLiteSeg网络头中的卷及和池花层呢？

**Comment by zhang-prog** [comment]
你是想用已有的模块去调整，还是想使用自定义的卷积层和池化层调整？

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
