### ISSUE TITLE
运行出现bug，没有解决

### ISSUE THREAD

**Issue by wanghonen** [PaddlePaddle/PaddleSeg#3775]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

2024-08-08 06:16:46 [INFO]	
------------Environment Information-------------
platform: Linux-5.4.0-139-generic-x86_64-with-debian-stretch-sid
Python: 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
Paddle compiled with cuda: True
NVCC: Build cuda_11.2.r11.2/compiler.29618528_0
cudnn: 8.2
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: Tesla V100-SXM2-32GB']
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
PaddleSeg: 2.7.0
PaddlePaddle: 2.3.2
OpenCV: 4.1.1
------------------------------------------------
2024-08-08 06:16:46 [INFO]	
---------------Config Information---------------
batch_size: 16
iters: 30000
loss:
  coef:
  - 1
  types:
  - coef:
    - 0.8
    - 0.2
    losses:
    - type: CrossEntropyLoss
    - type: LovaszSoftmaxLoss
    type: MixedLoss
lr_scheduler:
  learning_rate: 6.0e-05
  power: 1
  type: PolynomialDecay
model:
  align_corners: true
  backbone:
    in_channels: 1
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/backbone/mix_vision_transformer_b3.tar.gz
    type: MixVisionTransformer_B3
  embedding_dim: 768
  num_classes: 7
  type: SegFormer
optimizer:
  beta1: 0.9
  beta2: 0.999
  type: AdamW
  weight_decay: 0.01
train_dataset:
  dataset_root: /home/aistudio/data/src/
  img_channels: 1
  mode: train
  num_classes: 7
  train_path: /home/aistudio/data_split/train.txt
  transforms:
  - max_scale_factor: 1.25
    min_scale_factor: 0.75
    scale_step_size: 0.25
    type: ResizeStepScaling
  - type: RandomVerticalFlip
  - type: RandomBlur
  - type: RandomRotation
  - type: RandomHorizontalFlip
  - crop_size:
    - 512
    - 512
    type: RandomPaddingCrop
  - type: Normalize
  type: Dataset
val_dataset:
  dataset_root: /home/aistudio/data/src/
  img_channels: 1
  mode: val
  num_classes: 7
  transforms:
  - type: Normalize
  type: Dataset
  val_path: /home/aistudio/data_split/val.txt
------------------------------------------------
W0808 06:16:46.936419  6406 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 12.0, Runtime API Version: 11.2
W0808 06:16:46.936477  6406 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
2024-08-08 06:16:48 [INFO]	Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/backbone/mix_vision_transformer_b3.tar.gz
2024-08-08 06:16:48 [WARNING]	[SKIP] Shape of pretrained params patch_embed1.proj.weight doesn't match.(Pretrained: [64, 3, 7, 7], Actual: [64, 1, 7, 7])
2024-08-08 06:16:48 [INFO]	There are 571/572 variables loaded into MixVisionTransformer.
2024-08-08 06:16:48 [INFO]	use AMP to train. AMP level = O1
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py:278: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float32, but right dtype is paddle.float16, the right dtype will convert to paddle.float32
  format(lhs_dtype, rhs_dtype, lhs_dtype))
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py:278: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float16, but right dtype is paddle.float32, the right dtype will convert to paddle.float16
  format(lhs_dtype, rhs_dtype, lhs_dtype))
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/norm.py:654: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py:278: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float32, but right dtype is paddle.int64, the right dtype will convert to paddle.float32
  format(lhs_dtype, rhs_dtype, lhs_dtype))
Traceback (most recent call last):
  File "/home/aistudio/PaddleSeg/train.py", line 262, in <module>
    main(args)
  File "/home/aistudio/PaddleSeg/train.py", line 254, in main
    to_static_training=cfg.to_static_training)
  File "/home/aistudio/PaddleSeg/paddleseg/core/train.py", line 200, in train
    scaled.backward()  # do backward
  File "<decorator-gen-133>", line 2, in backward
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 434, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 293, in backward
    framework._dygraph_tracer())
RuntimeError: (NotFound) There are no kernels which are registered in the pad3d_grad operator.
  [Hint: Expected kernels_iter != all_op_kernels.end(), but received kernels_iter == all_op_kernels.end().] (at /paddle/paddle/fluid/imperative/prepared_operator.cc:341)

### 复现环境 Environment

paddlepaddle 2.7 三天之前刚运行过程序，没有任何问题，中间也没有对程序有任何修改，今天运行程序突然出现了上面的错误，不知道是什么问题造成的，目前我已经大概知道问题在哪里了，因为我用了--precision fp16这个，如果我把这个去掉的话，程序能正常运行，但是前几天我也是加的这个啊，也能正常运行，请问是因为你们更新了什么吗

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by JianDan0212** [comment]
你好，感谢使用paddle，从你现在这里的描述，我们无法定位到问题，如果你方便的话建议你提供一个最小的复现例子，如果无法提供的话，至少给我们提供下运行指令，方便我们排查问题

**Comment by wanghonen** [comment]
!python /home/aistudio/PaddleSeg/train.py \
    --config  /home/aistudio/PaddleSeg/segformerb3.yml \
    --save_dir /home/aistudio/outputmodel \
    --do_eval \
    --use_vdl \
    --batch_size 16 \
    --iters 30000 \
    --save_interval 500 \
    --log_iters 50 \
    --num_workers 4 \
    --precision fp16


你好 我的指令是这个，如果你们方便的话，我可以把项目单独分享给你们，因为我这个项目是私有的，我的邮箱是985388035@qq.com

**Comment by JianDan0212** [comment]
稍等晚些调试完成回复你

**Comment by JianDan0212** [comment]
你好，想问下您是在CPU环境训练的还是在GPU环境下训练的

**Comment by wanghonen** [comment]
> 你好，想问下您是在CPU环境训练的还是在GPU环境下训练的

您好，我是在V100 32G，GPU环境下运行的

**Comment by JianDan0212** [comment]
我这边测试过你给我发的工程，确实使用半精度浮点形跑不了，之前组内同学好像是升级过Seg，我确认下，你这边可以先试用全精度进行。

**Comment by wanghonen** [comment]
> 我这边测试过你给我发的工程，确实使用半精度浮点形跑不了，之前组内同学好像是升级过Seg，我确认下，你这边可以先试用全精度进行。

您好，请问现在有解决方法了吗，因为我要跑对比实验，所有方法都是用半精度跑的

**Comment by TingquanGao** [comment]
你好，之后由我来跟进该问题。请问该问题是否解决了？另外是必须用paddle 2.7版本吗？因为该版本比较旧，套件诸多地方已经不兼容了。

**Comment by wanghonen** [comment]
> 你好，之后由我来跟进该问题。请问该问题是否解决了？另外是必须用paddle 2.7版本吗？因为该版本比较旧，套件诸多地方已经不兼容了。

你好，问题还没有解决，我是想着已经跑了很多个对比实验了，最好是2.7版本，如果改了版本那我是不是就需要把其他的模型环境都换成别的重跑一遍。现在关键是我之前在2.7版本运行是好的，过了几天就没法运行了，如果你们实在是解决不了，那我可以考虑换版本，如果更换版本的话需要换成什么版本呢

**Comment by TingquanGao** [comment]
如果这样的话，建议可以尝试使用git回退PaddleSeg试试，能否确定之前使用的是paddleseg版本，比如2.6分支。
上面我说错了，paddle2.3.2版本太旧了，如果换paddle的话，建议使用最新的3.0-beta版本或是2.6版本。
我们会维护最新的release分支和最新版的paddle，所以也可以尝试最新的paddleseg2.9.1分支。
如仍有问题，可以继续留言。

**Comment by wanghonen** [comment]
> 如果这样的话，建议可以尝试使用git回退PaddleSeg试试，能否确定之前使用的是paddleseg版本，比如2.6分支。 上面我说错了，paddle2.3.2版本太旧了，如果换paddle的话，建议使用最新的3.0-beta版本或是2.6版本。 我们会维护最新的release分支和最新版的paddle，所以也可以尝试最新的paddleseg2.9.1分支。 如仍有问题，可以继续留言。

好的谢谢啦，不过我好像没有说清楚，我用的一直都是2.7版本，一开始是可以正常运行的，但是不知道为什么，我没有做任何操作，过了两三天，再运行的时候就报错了

**Comment by TingquanGao** [comment]
好的，那该issue我就先close了，如后续仍有问题可reopen或是new issue。

**Comment by wanghonen** [comment]
> 好的，那该issue我就先close了，如后续仍有问题可reopen或是new issue。

不是，问题没解决啊，谁给我解决了？我不是说了吗，我的其他对比实验都已经在2.7版本跑完了，最好是不要换版本，我的代码什么都没改就不能运行了，你们难道不可以看看是什么问题吗，如果后续我都跑完实验了，然后代码又不能跑了怎么办？我还能用你们这个平台不。。。。

**Comment by wanghonen** [comment]
@TingquanGao  我自己尝试更换，paddleseg 2.9.1分支，还是出现同样的问题；更换paddle版本为2.6会出现不同的bug，麻烦你们帮忙看下吧
