### ISSUE TITLE
标签问题

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleSeg#3776]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![1](https://github.com/user-attachments/assets/b9bb3c02-ca1a-4414-befc-bf0e453548c4)
您好，这种标签能直接用来训练么？还需要转换么?

**Comment by liuhongen1234567** [comment]
应该可以直接用，用数据集的代码打印了一下，转换后是0， 1
![image](https://github.com/user-attachments/assets/1cf21b12-250e-47cd-b36d-5a5c06d2ecf8)

**Comment by zcswdt** [comment]
> 应该可以直接用，用数据集的代码打印，转换后是0， 1 ![图像](https://private-user-images.githubusercontent.com/65936492/357439277-1cf21b12-250e-47cd-b36d-5a5c06d2ecf8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MDYyODQsIm5iZiI6MTcyMzYwNTk4NCwicGF0aCI6Ii82NTkzNjQ5Mi8zNTc0MzkyNzctMWNmMjFiMTItMjUwZS00N2NkLWIzNmQtNWE1YzA2ZDJlY2Y4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDAzMjYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMmE2MzllM2UwZGI0NWNmYTlmYTFiN2Q3Y2E1OTRjNjRkZTk3N2FjMDlkMTc3ZTM3MmQ3M2FmYTY0YTEyNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n5dFldQdFz2PSkK2DFSacQqzerP-61Ko29xcM9yx6JE)

![image](https://github.com/user-attachments/assets/5cf2ef0e-fd1e-418e-bdbc-3d532d7c3d5a)
我用这个标签训练，不行，训练结果都是这样的，如何给我这个图弄成符合你们代码训练的标签呢？

**Comment by liuhongen1234567** [comment]
您好，可以给出一些分割的可视化结果和具体的配置吗？loss看起来是正常收敛了
