### ISSUE TITLE
用GPU训练deeplabv3+一直会报错，用cpu没有问题

### ISSUE THREAD

**Issue by mahuaxiaotuanzi** [PaddlePaddle/PaddleSeg#378]
![image](https://user-images.githubusercontent.com/33740556/92688684-5bc8e280-f370-11ea-8062-092d659576d7.png)
用GPU训练deeplabv3+一直会报错，用cpu没有问题

**Comment by LutaoChu** [comment]
你好，你的Paddle是使用cudnn 7.6编译的，但你的机器的cudnn version只有5.1，需要升级一下。cuda 10对应的cudnn推荐版本是7.6，建议升级到cudnn 7.6 。
