### ISSUE TITLE
multiabelseg

### ISSUE THREAD

**Issue by 123studying** [PaddlePaddle/PaddleSeg#3787]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

是在评估的时候报错 Start evaluating (total_samples: 4, total_iters: 4)
报错内容是维度不一致    ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 3, 550, 697] and the shape of Y = [1, 1, 550, 698]. Received [697] in X is not equal to [698] in Y at i:3.

### 复现环境 Environment

python：3.8
CPU

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by UserWangZz** [comment]
请问可以提供一个可以复现的最小demo吗

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
