### ISSUE TITLE
关于分割模型中的MLA Transformer，请问这个模型出自哪篇文章？还是说这个是飞桨原创的？

### ISSUE THREAD

**Issue by Programrookie33** [PaddlePaddle/PaddleSeg#3796]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

关于分割模型中的MLA Transformer，请问这个模型是出自哪篇文章？还是说这个是飞桨原创的？

**Comment by liu-jiaxuan** [comment]
请参考[链接](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.9.1/contrib/AutoNUE)
