### ISSUE TITLE
How add swin-large transformer as backbone use to mask2former?

### ISSUE THREAD

**Issue by funny000** [PaddlePaddle/PaddleSeg#3802]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包含open与closed)，没有类似需求。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar feature requests.

### 需求描述 Feature Description

thank author for this work.
I want to use mask2former with swinlarge transformer as backbone, So How add it?

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by cuicheng01** [comment]
You can refer to [this document](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.9.1/docs/pr/pr/style.md)～

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
