### ISSUE TITLE
Grad-CAM

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleSeg#3803]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问Grad-CAM怎么应用在这个仓库里面呢？有教程么？谢谢

**Comment by cuicheng01** [comment]
目前PaddleSeg是没有的，可以参考[这里](https://github.com/PaddlePaddle/InterpretDL)实现哦

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
