### ISSUE TITLE
STDC Tiny预训练模型

### ISSUE THREAD

**Issue by consistent1997** [PaddlePaddle/PaddleSeg#3804]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包含open与closed)，没有类似需求。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar feature requests.

### 需求描述 Feature Description

我需要重新训练一个满足耗时要求的抠图模型，但是目前STDC1作为预训练模型耗时还是无法达到实时，因此想问问能否提供STDC Tiny的预训练模型，因为从头开始训练一个抠图模型实在是太慢了，感谢！

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Bobholamovic** [comment]
你好，在这个页面可以找到STDC1模型的预训练权重参数下载链接：https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.9.1/configs/stdcseg

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
