### ISSUE TITLE
将annotations和images图像进行裁剪后训练，对结果有影响吗？

### ISSUE THREAD

**Issue by wwma** [PaddlePaddle/PaddleSeg#3809]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

受使用条件的限制，需要把图像进行分割后，再进行训练和识别。我现在是使用原图和labelme进行标注的，请问，直接裁剪原图和标注后的图像进行训练，会有影响吗？标签不会更改吧？谢谢

**Comment by zhangyubo0722** [comment]
对原图进行裁剪的同时需要对标签文件同步进行裁剪，PaddleSeg在训练时会进行图像的缩放，可以不用手动裁剪吧

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
