### ISSUE TITLE
在将模型导出后使用PaddleServing，预处理及后处理

### ISSUE THREAD

**Issue by iceriver97** [PaddlePaddle/PaddleSeg#381]
我将 PaddleSeg 训练好的模型导出为 Serving 所要的模型之后，对模型输入的预处理及对模型输出的后处理需要自己来写吗？

**Comment by nepeplwu** [comment]
@iceriver97 ，需要自行处理，可以参考这个[demo](https://github.com/PaddlePaddle/PaddleSeg/tree/release/v0.6.0/deploy/serving)编写

**Comment by iceriver97** [comment]
@nepeplwu 您好，PaddleSegServing 现在还是需要安装这么多的依赖库吗？我的系统是 ubuntu 16.04 LTS ，在安装依赖时出现了很多问题，PaddleSegServing 支持这个系统吗？我应该安装的依赖版本是那些呢？感谢！

**Comment by nepeplwu** [comment]
@iceriver97 Serving相关的依赖和安装问题可以到[PaddleServing](https://github.com/PaddlePaddle/Serving) repo 提问
