### ISSUE TITLE
Python inference by Fastdeploy

### ISSUE THREAD

**Issue by nvip12041994** [PaddlePaddle/PaddleSeg#3810]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

I tried to run 
deploy/fastdeploy/semantic_segmentation/serving/fastdeploy_serving/README.md
I use docker image paddlepaddle/fastdeploy:1.0.0-gpu-cuda11.4-trt8.4-21.10
but when I run the paddleseg_grpc_client.py, I got these errors, please help me

 Failed to process the request(s) for model 'postprocess_0', message: AssertionError: <class 'fastdeploy.libs.fastdeploy_main.vision.SegmentationResult'> Conversion to JSON format is not supported

![image](https://github.com/user-attachments/assets/8b8e356f-1f5b-4f0d-ab81-d7c1a8853fd4)

**Comment by liu-jiaxuan** [comment]
The error message Conversion to JSON format is not supported indicates that there is an issue with the result type being returned by the model, specifically the SegmentationResult. This suggests that the FastDeploy might not be able to serialize the output in the expected JSON format.
﻿
Ensure that the model you are using is compatible with the FastDeploy framework and TensorRT optimizations. Some models may have layers or operations that are not supported in the current FastDeploy version. Consider using a simpler model or re-evaluating the model architecture.If possible, update to the latest version.
﻿
Besides, you can debug the outputs of your model manually to ensure they are in the expected format.

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
