### ISSUE TITLE
deeplabv3p和ppliteseg是否支持tensorrt加速呢

### ISSUE THREAD

**Issue by 22ling** [PaddlePaddle/PaddleSeg#3812]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我将deeplabv3p和ppliteseg两模型都转换为onnx后，用官网python部署推理代码infer_onnx_trt,在确认安装包不冲突的情况下，无法使用trt加速，是否网络结构的一些模块在trt中不支持加速呢？

**Comment by cuicheng01** [comment]
您好，是支持的，详情可以使用[PaddleX的高性能部署](https://github.com/PaddlePaddle/PaddleX)。

**Comment by xiaowen0407** [comment]
deeplabv3p和ppliteseg  你好请问这两个推理耗时大概差多少？

**Comment by 22ling** [comment]
> 您好，是支持的，详情可以使用[PaddleX的高性能部署](https://github.com/PaddlePaddle/PaddleX)。

这边查看支持linux下tensorrt加速 是否win下也支持呢

**Comment by cuicheng01** [comment]
win的话还在支持中，可以持续关注PaddleX

**Comment by cuicheng01** [comment]
> deeplabv3p和ppliteseg 你好请问这两个推理耗时大概差多少？

可以查看PaddleX的语义分割模块的文档，里边有相关的速度指标哈

**Comment by 22ling** [comment]
> win的话还在支持中，可以持续关注PaddleX

请问这里是指还在开发中，目前暂不支持windows下tensorrt加速 对吗

**Comment by cuicheng01** [comment]
是的

**Comment by 22ling** [comment]
> 是的
