### ISSUE TITLE
split_dataset_list切分数据顺序错乱

### ISSUE THREAD

**Issue by yzyMichael** [PaddlePaddle/PaddleSeg#3813]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用：python tools/data/split_dataset_list.py data/custom_dataset/ images labels --split 0.7 0.3 0 --format jpg png 制作数据集生成如图顺序的内容，如何解决生成的trai.txt和val.txt内容顺序一致
![image](https://github.com/user-attachments/assets/adb87a8d-9c36-43e2-9be3-172ed283f1e6)

**Comment by yzyMichael** [comment]
PaddleSeg 版本：2.9.1
PaddlePaddle 版本：2.6.2
python:3.12.5

**Comment by liuhongen1234567** [comment]
您好，可以参考PaddleX的代码，把图片和label的路径用空格拼接成一个字符串，然后将这些字符串写入到一个list中，并使用random.shuffle打乱。

<img width="318" alt="image" src="https://github.com/user-attachments/assets/9a0ebd0a-a4a5-489f-8f54-89d839d9b8ab">

<img width="601" alt="image" src="https://github.com/user-attachments/assets/910052de-ca59-45e6-9336-1136788dcad3">

https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/paddlex/modules/semantic_segmentation/dataset_checker/dataset_src/split_dataset.py
