### ISSUE TITLE
用uint16格式的灰度图训练，得到的结果是乱的

### ISSUE THREAD

**Issue by KillerQueen-dust** [PaddlePaddle/PaddleSeg#3817]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

需要用uint16的单通道灰度图像来训练，已经在Compose类里面把OpenCV的读入标志cv2.IMREAD_GRAYSCALE改成cv2.IMREAD_UNCHANGED了，config里也设置了img_channels=1，但得到的预测结果是没有意义的结果。想知道还有哪些地方需要修改的。PS：uint16直接转为tensor的bfloat16可能出现精度溢出问题，但我看框架会在预处理时先将图片转为float32，按道理应该不会是精度的问题

**Comment by zhangyubo0722** [comment]
如果直接使用单通道图像训练会报错吗

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
