### ISSUE TITLE
工业质检缺陷分割上面的小样本问题

### ISSUE THREAD

**Issue by jiamfeng** [PaddlePaddle/PaddleSeg#3818]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包含open与closed)，没有类似需求。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar feature requests.

### 需求描述 Feature Description

你好，想要咨询下，我看了下当前PPSeg里面使用的语义分割模型需求的缺陷样本较多，高达几百张，实际场景使用想要收集较大量的缺陷样本是比较困难的，是否有合成数据增强的方法来提升数据量以及数据合成的一个真实性？

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by cuicheng01** [comment]
这块暂时没有呢，不过可以持续关注下PaddleX，会持续集成相关的图像异常检测或者图像缺陷检测的算法和方法～

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
