### ISSUE TITLE
请问有使用把pp-litseg部署到jetson板子上的吗，想请问一下推理耗时

### ISSUE THREAD

**Issue by xiaowen0407** [PaddlePaddle/PaddleSeg#3819]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问有使用把pp-litseg部署到jetson板子上的吗，想请问一下推理耗时

**Comment by cuicheng01** [comment]
您好，这块PaddleX正在支持，相关的细节将在[PaddleX](https://github.com/PaddlePaddle/PaddleX)的develop文档中体现，可以关注下

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
