### ISSUE TITLE
https://pan.baidu.com/s/1vu0ZIbGumlFvRlMGbMvWAg)-pw 的密码不对

### ISSUE THREAD

**Issue by myboyliu2025** [PaddlePaddle/PaddleSeg#3822]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.9.1/EISeg/med3d
文档里面的百度盘密码不对，麻烦重新提供一下。谢谢。

**Comment by daisyshiyu** [comment]
你好，可以尝试这个：
链接：https://pan.baidu.com/s/10GRZjXPYZhQcTcXsr6FIIA?pwd=VsBH 
提取码：VsBH
