### ISSUE TITLE
小白求助，我需要输入10波段的遥感影像，该怎么修改代码呢

### ISSUE THREAD

**Issue by zjy888688** [PaddlePaddle/PaddleSeg#3823]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

任务是二分类语义分割，我的数据是10波段的遥感多光谱影像tif格式，标签是1波段二值图像tif格式。该怎么修改代码。

**Comment by cuicheng01** [comment]
可以再详细描述下需求吗？

**Comment by zjy888688** [comment]
> 可以再详细描述下需求吗？

就是怎么修改dataset和transformer部分，让网络可以输入超过3通道的tif影像，我在Dataset类里直接img_channels=12定义为我想要的通道数，如图所示
![image](https://github.com/user-attachments/assets/2982e251-2c24-48c1-891b-66c0f657346e)
但是程序会在transformer 这里抛出错误，不能读取image
![image](https://github.com/user-attachments/assets/8a840a27-e0bb-417e-a4b0-985dbe7cc795)

于是我又定义了这样一个读取image的类，并在Dataset类里修改
class ReadTiff(object):
    def readTif_to_Ndarray(self, img_path):
        dataset = gdal.Open(img_path)
        # 获得矩阵的列数
        self.width = dataset.RasterXSize
        # 栅格矩阵的行数
        self.height = dataset.RasterYSize
        # 获得数据
        self.data = dataset.ReadAsArray(0, 0, self.width, self.height)
        return self.data
![image](https://github.com/user-attachments/assets/d994653f-3594-4e94-a8e1-8f36b176c587)

但这样似乎还是不行，这里又报错
![image](https://github.com/user-attachments/assets/f8d89176-7541-4fd9-8119-db4f0582a03d)
不知道是哪里修改的形状，似乎传入没有正确数据类型

**Comment by cuicheng01** [comment]
哦，这个问题建议还是debug进去看看数据流呢？正确的数据流了解了之后就知道怎么改了

**Comment by zjy888688** [comment]
我这样改的方向是对的吗，还是不需要这么复杂



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月10日 22:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleSeg] 小白求助，我需要输入10波段的遥感影像，该怎么修改代码呢 (Issue #3823) |

哦，这个问题建议还是debug进去看看数据流呢？正确的数据流了解了之后就知道怎么改了

**Comment by cuicheng01** [comment]
可以往这个方向改，具体怎么改，还是需要关注下数据流的方向，只要清楚了数据流，应该就好改了，这块我们也是需要用真实的数据走一遍流程才会知道，可以再尝试尝试

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
