### ISSUE TITLE
请问下eiseg 传播模型的地址 怎么是一个问卷调查停止的链接呢？[static_propagation](https://www.wjx.cn/vm/wWw3pRc.aspx

### ISSUE THREAD

**Issue by huxianhui282** [PaddlePaddle/PaddleSeg#3824]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问下eiseg 传播模型的地址 怎么是一个问卷调查停止的链接呢？[static_propagation](https://www.wjx.cn/vm/wWw3pRc.aspx

**Comment by daisyshiyu** [comment]
可以尝试这个链接
链接：https://pan.baidu.com/s/10GRZjXPYZhQcTcXsr6FIIA?pwd=VsBH 
提取码：VsBH

**Comment by haoyuying** [comment]
https://github.com/PaddlePaddle/PaddleSeg/blob/develop/EISeg/docs/video.md
试试这个页面呢
