### ISSUE TITLE
请教各位关于动态尺寸推理的问题

### ISSUE THREAD

**Issue by xiaowen0407** [PaddlePaddle/PaddleSeg#3827]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问是不是 只有 多尺度训练 的模型 在导出ONNX的时候才可以动态尺寸导出， 如果我训练网络固定了尺寸，比如输入的图片都是1280X720 这边做预处理都resize成640X360  那么在导出模型ONNX 时候就不能设置动态尺寸导出，不然动态尺寸推理效果不好？
还是说 推理时候的尺寸 和训练的尺寸无关？？？？？  真心求教 一直有这个疑问

**Comment by LijialinHub** [comment]
我是需要训练静态尺寸 请问如何设置 大佬

**Comment by xiaowen0407** [comment]
> 我是需要训练静态尺寸 请问如何设置 大佬

改config文件  把  transforms:
    - type: Resize
      target_size: [1920, 544]
    # - type: ResizeStepScaling
    #   min_scale_factor: 0.5
    #   max_scale_factor: 2.0
    #   scale_step_size: 0.25
    # - type: RandomPaddingCrop
    #   crop_size: [512, 512]

多尺度这个注释掉 改成直接resize就可以了

**Comment by xiaowen0407** [comment]
改config文件 把 transforms:
- type: Resize
target_size: [1920, 544]
# - type: ResizeStepScaling
# min_scale_factor: 0.5
# max_scale_factor: 2.0
# scale_step_size: 0.25
# - type: RandomPaddingCrop
# crop_size: [512, 512]

多尺度这个注释掉 改成直接resize就可以了





文文
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月22日(星期二) 中午1:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] 请教各位关于动态尺寸推理的问题 (Issue #3827)





 
我是需要训练静态尺寸 请问如何设置 大佬

**Comment by LijialinHub** [comment]
> 改config文件 把 transforms: - type: Resize target_size: [1920, 544] # - type: ResizeStepScaling # min_scale_factor: 0.5 # max_scale_factor: 2.0 # scale_step_size: 0.25 # - type: RandomPaddingCrop # crop_size: [512, 512] 多尺度这个注释掉 改成直接resize就可以了 文文 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddlePaddle/PaddleSeg" ***@***.***&gt;; 发送时间:&nbsp;2024年10月22日(星期二) 中午1:58 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] 请教各位关于动态尺寸推理的问题 (Issue #3827) 我是需要训练静态尺寸 请问如何设置 大佬 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

感谢大佬，我在推理模型转出onnx时候出现[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: ./model.pdmodel
[Paddle2ONNX] Paramters file path: ./model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[ERROR] Cannot found attribute threshold in op: relu6 报错，我明明paddleseg paddle2onnx都是安装的最新版，请问您遇到类似的问题了嘛

**Comment by Sunting78** [comment]
您好 能给下执行的命令吗？

**Comment by xiaowen0407** [comment]
> > 改config文件 把 transforms: - type: Resize target_size: [1920, 544] # - type: ResizeStepScaling # min_scale_factor: 0.5 # max_scale_factor: 2.0 # scale_step_size: 0.25 # - type: RandomPaddingCrop # crop_size: [512, 512] 多尺度这个注释掉 改成直接resize就可以了 文文 _**@**_.***  
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "PaddlePaddle/PaddleSeg" _**@**_._**>; 发送时间: 2024年10月22日(星期二) 中午1:58 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [PaddlePaddle/PaddleSeg] 请教各位关于动态尺寸推理的问题 (Issue #3827) 我是需要训练静态尺寸 请问如何设置 大佬 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 感谢大佬，我在推理模型转出onnx时候出现[Paddle2ONNX] Start to parse PaddlePaddle model... [Paddle2ONNX] Model file path: ./model.pdmodel [Paddle2ONNX] Paramters file path: ./model.pdiparams [Paddle2ONNX] Start to parsing Paddle model... [ERROR] Cannot found attribute threshold in op: relu6 报错，我明明paddleseg paddle2onnx都是安装的最新版，请问您遇到类似的问题了嘛

这个我没遇到过哦  可能是算子不兼容把 你安装最新的paddle2onnx试试呢

**Comment by Sunting78** [comment]
您好，可以尝试下 安装最新的Paddle，然后重新导出模型。然后再导出paddle2onnx

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
