### ISSUE TITLE
stfpm 导出模型使用FastDeploy  c++推理无结果

### ISSUE THREAD

**Issue by 534114658** [PaddlePaddle/PaddleSeg#3828]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

数据用的paddx  stfpm里面范例的数据
python tools/train.py --config configs/stfpm/stfpm_resnet18_mvtec.yml
训练正常
python tools/predict.py --config configs/stfpm/stfpm_resnet18_mvtec.yml --model_path output/iter_5000/model.pdparams --image_path mvtec_examples/test/broken/001.png
python识别正常
![001](https://github.com/user-attachments/assets/68c72434-25a9-4a55-b8db-9efaa2a9c330)

python tools/export.py --config configs/stfpm/stfpm_resnet18_mvtec.yml --model_path output/iter_5000/model.pdparams --save_dir output/inference_model
导出模型正常

deploy/fastdeploy/semantic_segmentation/cpu-gpu/cpp/infer.cc
同样的图片使用FastDeploy推理无结果

deploy/cpp/src/test_seg.cc
同样的图片使用paddle_inference推理无结果

**Comment by TingquanGao** [comment]
建议使用[PaddleX](https://github.com/paddlepaddle/paddlex)，PaddleX支持多种推理方式，此外PaddleX也支持语义分割模型的训练导出及推理，[seg模型使用教程](https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/module_usage/tutorials/cv_modules/semantic_segmentation.md)，[seg产线使用教程](https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/pipeline_usage/tutorials/cv_pipelines/semantic_segmentation.md)
