### ISSUE TITLE
PP-MobileSeg-Tiny在高通DSP上部署推理异常

### ISSUE THREAD

**Issue by gitqinxinyu** [PaddlePaddle/PaddleSeg#3834]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

PP-MobileSeg-Tiny这个模型导出onnx使用高通SNPE量化工具可以正常量化，但在DSP上推理异常，想请帮忙分析下模型当中是否不支持该设备部署的算子？

### 复现环境 Environment

paddlepaddle-gpu=2.6.1.post116
paddle-seg=2.9.0
paddle2onnx=1.2.9

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by changdazhou** [comment]
辛苦提供一下报错信息看看哈

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
