### ISSUE TITLE
依赖中opencv-python的版本要求

### ISSUE THREAD

**Issue by alanxinn** [PaddlePaddle/PaddleSeg#3838]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

requirements.txt中
opencv-python <= 4.6.0

使用>=4.6版本是否可以

**Comment by zhangyubo0722** [comment]
目前使用opencv-python > 4.6.0的话，代码中部分使用到cv2的地方会报错，后续我们也会逐渐支持更高的opencv版本

**Comment by alanxinn** [comment]
> 目前使用opencv-python > 4.6.0的话，代码中部分使用到cv2的地方会报错，后续我们也会逐渐支持更高的opencv版本

期待更新，感谢回复
