### ISSUE TITLE
使用tool/export.py 导出模型时，指定了input_shape，模型仍有-1的维度

### ISSUE THREAD

**Issue by cojoho** [PaddlePaddle/PaddleSeg#3839]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

python tools/export.py  --config contrib/PP-HumanSeg/configs/human_pp_humansegv1_lite.yml  --model_path model.pdparams  --save_dir output_model/pp_humansegV1-Lite-192x192 --input_shape 1 3 192 192
能导出模型，但是只固定的输入的shape。
整个模型的shape可以固定下来吗？需要怎么修改？
![企业微信截图_17308606699916](https://github.com/user-attachments/assets/eddb050e-6c44-4023-afca-b11dc978de1e)
![企业微信截图_17308606575435](https://github.com/user-attachments/assets/f10897c8-a623-4191-bc9a-d8214b3fdcd5)

**Comment by liu-jiaxuan** [comment]
Hi，在导出静态图时，如果指定了shape（比如你的指令里面的“ --input_shape 1 3 192 192”），模型shape在导出之后就已经固定下来了~

**Comment by cojoho** [comment]
> Hi，在导出静态图时，如果指定了shape（比如你的指令里面的“ --input_shape 1 3 192 192”），模型shape在导出之后就已经固定下来了~

不是，我图里的pdmodel文件。只有输入尺寸的固定下来了啊 。麻烦看一下pdmodel，输入确定的情况下，后面应该也不会有-1可变的张量？ 但是我导出的模型后续的算子处理中是有-1的动态shape的，就是图里红框标的？ 问号。 怎么将整个模型的shape固定下来啊 ？
