### ISSUE TITLE
EIseg在标注的时候YOLO格式保存按钮为灰色

### ISSUE THREAD

**Issue by chinesejunzai12** [PaddlePaddle/PaddleSeg#3840]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

PaddlePaddle: 2.2.2
python:3.9
PaddleSeg:2.8
EIseg在标注的时候YOLO格式保存按钮为灰色, 为什么

**Comment by chinesejunzai12** [comment]
![image](https://github.com/user-attachments/assets/6689d506-8f11-4569-86b0-8510b3040902)是这样的情况, 如何解决

**Comment by liu-jiaxuan** [comment]
标注暂时只支持JSON和COCO格式保存，具体说明请参考[文档](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/EISeg/docs/image.md#%E7%89%B9%E8%89%B2%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E)中的“保存格式”部分。
