### ISSUE TITLE
分割图标标注的时候闪退

### ISSUE THREAD

**Issue by chinesejunzai12** [PaddlePaddle/PaddleSeg#3842]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

报错信息:
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
zsh: abort      python -m eiseg

环境:
paddlepaddle:2.2.2
paddleseg:2.8.0
mac本:cpu
python:3.8.20

**Comment by liu-jiaxuan** [comment]
是numpy版本的问题哈，参考官方环境要求设置你的numpy版本即可~

**Comment by chinesejunzai12** [comment]
> 是numpy版本的问题哈，参考官方环境要求设置你的numpy版本即可~

我降低了对应的numpy版本, 但是对应的pandas和matplotlib等一些列的都需要更换版本, 咱们有指定的一些安装版本么?
