### ISSUE TITLE
模型训练完成后在终端部署时报错

### ISSUE THREAD

**Issue by flyinggx** [PaddlePaddle/PaddleSeg#385]
**将训练好的模型导出后，在终端部署时显示打不开model文件，文件路径这些都没错，请问有人遇到这过个问题吗？应该怎么解决呢？**
命令行：python G:\python\infer.py --conf=G:\freeze_model\deploy.yaml --input_dir=G:\img
报错：
--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.
----------------------
Error Message Summary:
----------------------
Error: Cannot open file G:reeze_model\model at (D:\1.8.4\paddle\paddle\fluid\inference\api\analysis_predictor.cc:706)

**Comment by nepeplwu** [comment]
@flyinggx 麻烦贴下你的deploy.yaml文件内容

**Comment by flyinggx** [comment]
> @flyinggx 麻烦贴下你的deploy.yaml文件内容

你好，目前问题已解决，是终端设置的问题，感谢回复~
