### ISSUE TITLE
为什么在val的时候会极大的增加gpu的占用率

### ISSUE THREAD

**Issue by zwf159** [PaddlePaddle/PaddleSeg#3850]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包含open与closed)，没有类似需求。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar feature requests.

### 需求描述 Feature Description

为什么我在正常训练的时候gpu占用率是16g但是一到val的时候gpu占用率会把共享gpu内存也给占满，这种情况出现非常多次，我就算把batch_size降低到2都不行，我的显卡是4070tis肯定是够训练的，需要我提供什么信息

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by TingquanGao** [comment]
用的paddle版本是多少？方便的话可以提供下训练命令

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
