### ISSUE TITLE
VDL链接失效

### ISSUE THREAD

**Issue by Asthestarsfalll** [PaddlePaddle/PaddleSeg#3853]
### 文档链接&描述 Document Links & Description

config中的vdl链接失效

**Comment by cuicheng01** [comment]
您好，这块是哪个config呢？

**Comment by Asthestarsfalll** [comment]
比如这里的https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.10/configs/segnext，看了其他的也失效了

**Comment by Bobholamovic** [comment]
你好，这些VDL链接不可用了，我们在 https://github.com/PaddlePaddle/PaddleSeg/pull/3859 先下掉了这些链接～

**Comment by Bobholamovic** [comment]
感谢指出文档中的错误
