### ISSUE TITLE
lite转换分割模型，输出output_tensor的含义

### ISSUE THREAD

**Issue by boceng** [PaddlePaddle/PaddleSeg#386]
您好，我这里在arm Linux下将unet模型部署到lite后，输出tensor的shape为[1, 3, 512, 512]，其中所有像素值都为0~1的小数值，且值要么极大（0.9+）要么极小（0.1-），请问这些值的含义是什么？

**Comment by boceng** [comment]
或者说会不会是我的预处理不对？
我有采用两种方法进行处理：

1. 

    def read_img(im_path, resize_h, resize_w):
        im = cv2.imread(im_path).astype('float32')  # 转32浮点型
        im = cv2.cvtColor(im, cv2.COLOR_BGR2RGB)  # 颜色空间转换
        h, w, _ = im.shape
        im_scale_x = resize_h / float(w)
        im_scale_y = resize_w / float(h)
        out_img = cv2.resize(im, None, None, fx=im_scale_x, fy=im_scale_y, interpolation=cv2.INTER_CUBIC)
        mean = np.array([0.485, 0.456, 0.406]).reshape((1, 1, -1))
        std = np.array([0.229, 0.224, 0.225]).reshape((1, 1, -1))
        out_img = (out_img / 255.0 - mean) / std  # z-score
        out_img = out_img.transpose((2, 0, 1))
        return out_img
    image_data = read_img(img, height, width).flatten()

2.

    image = Image.open(args.img_data)
    resized_image = image.resize((height, width), Image.BILINEAR)
    image_data = np.array(resized_image).flatten().tolist()

我也没有想到适合的后处理方法，还请麻烦解答一下，感谢~

**Comment by wuyefeilin** [comment]
模型返回的数值是经过softmax处理的， 所以每个通道上的数值代表的是相应类的概率。 预处理的均值跟方差最好跟训练的时候保持一致。

**Comment by boceng** [comment]
> 模型返回的数值是经过softmax处理的， 所以每个通道上的数值代表的是相应类的概率。 预处理的均值跟方差最好跟训练的时候保持一致。

您好，我换了几个模型都进行了实验，发现输出的信息，只有第一个通道的值全是0.999+，其余通道全是0.00，且不论测试图片是否真正含有目标，都输出一样的信息，我这里确定模型都是没问题的，请问这种情况如何解释。

**Comment by boceng** [comment]
您好，今早代码随便一实验发现可以了，可能昨天有些姿势不对，我现在也没发现是为啥😓，感谢您的指导。 @wuyefeilin
