### ISSUE TITLE
HRNet_W18/bn Cityscapes 0.7936 能提供训练日志吗？

### ISSUE THREAD

**Issue by xiangliu886** [PaddlePaddle/PaddleSeg#391]
这个小模型要比别的框架高很多，能提供训练和验证日志吗，我想了解下这个模型的训练技巧。

**Comment by wuyefeilin** [comment]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.6.0/configs/ocrnet_w18_bn_cityscapes.yaml 数据增强和训练的配置可以参考这个。后续我们会推出动态图版本，欢迎体验

**Comment by deep-practice** [comment]
没有hrnet_w48的预训练模型吗

**Comment by wuyefeilin** [comment]
@deep-practice 你可以使用imagenet的预训练模型
