### ISSUE TITLE
Lovasz loss 无法使用

### ISSUE THREAD

**Issue by iceriver97** [PaddlePaddle/PaddleSeg#393]
我在设置 Lovasz loss 后报错：
```
#Device count: 1
batch_size_per_dev: 8
Traceback (most recent call last):
  File "PaddleSeg/pdseg/train.py", line 466, in <module>
    main(args)
  File "PaddleSeg/pdseg/train.py", line 453, in main
    train(cfg)
  File "PaddleSeg/pdseg/train.py", line 237, in train
    train_prog, startup_prog, phase=ModelPhase.TRAIN)
  File "/home/aistudio/PaddleSeg/pdseg/models/model_builder.py", line 196, in build_model
    probas = fluid.layers.softmax(logits, axis=1)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 2663, in softmax
    'softmax')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 80, in check_variable_and_dtype
    extra_message)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 97, in check_type
    (input_name, op_name, expected_type, type(input), extra_message))
TypeError: The type of 'input' in softmax must be (<class 'paddle.fluid.framework.Variable'>, <class 'paddle.fluid.core_avx.VarBase'>), but received <class 'tuple'>. 
```
下面是配置文件内容：
```
# 数据集配置
DATASET:
    DATA_DIR: "./work/dataset/land_train/"
    NUM_CLASSES: 7
    TEST_FILE_LIST: "./work/dataset/land_train/test.txt"
    TRAIN_FILE_LIST: "./work/dataset/land_train/train.txt"
    VAL_FILE_LIST: "./work/dataset/land_train/val.txt"
    VIS_FILE_LIST: "./work/dataset/land_train/test.txt"

# 预训练模型配置
MODEL:
    MODEL_NAME: "ocrnet"
    DEFAULT_NORM_TYPE: "bn"
    # 此处设置backbone的配置
    HRNET:
        STAGE2:
            NUM_CHANNELS: [18, 36]
        STAGE3:
            NUM_CHANNELS: [18, 36, 72]
        STAGE4:
            NUM_CHANNELS: [18, 36, 72, 144]
    # 此处设置OCR HEAD
    OCR:
        OCR_MID_CHANNELS: 512
        OCR_KEY_CHANNELS: 256
    MULTI_LOSS_WEIGHT: [1.0, 1.0]

# 其他配置
TRAIN_CROP_SIZE: (512, 512)
EVAL_CROP_SIZE: (512, 512)
AUG:
    AUG_METHOD: "unpadding"
    FIX_RESIZE_SIZE: (512, 512)
    RICH_CROP:
        ENABLE: True
        BLUR: True
        BLUR_RATIO: 0.2
        MAX_ROTATION: 45
        MIN_AREA_RATIO: 0.5
    MIRROR: True
    FLIP: True
BATCH_SIZE: 8
TRAIN:
    PRETRAINED_MODEL_DIR: "./PaddleSeg/pretrained_model/ocrnet_w18_bn_cityscapes/"
    MODEL_SAVE_DIR: "./PaddleSeg/saved_model/ocrnet_optic/"
    SNAPSHOT_EPOCH: 40
TEST:
    TEST_MODEL: "./PaddleSeg/saved_model/ocrnet_optic/final"
SOLVER:
    NUM_EPOCHS: 200
    LR: 0.001
    LR_POLICY: "poly"
    OPTIMIZER: "sgd"
    LOSS: ["lovasz_softmax_loss","softmax_loss"]
    LOSS_WEIGHT:
        LOVASZ_SOFTMAX_LOSS: 0.2
        SOFTMAX_LOSS: 0.8
```

**Comment by iceriver97** [comment]
@michaelowenliu  您知道是什么原因吗？

**Comment by LutaoChu** [comment]
你好，目前lovasz loss和OCRNet的适配有个小问题，我们正在修复。
你要是着急的话可以先git clone我的分支试试 https://github.com/LutaoChu/PaddleSeg/tree/lovasz-ocrnet
或者对照这个commit进行手动修改  https://github.com/PaddlePaddle/PaddleSeg/compare/develop...LutaoChu:lovasz-ocrnet?expand=1

**Comment by iceriver97** [comment]
@LutaoChu  您好，您的分支会出现下面的错误：
```
Traceback (most recent call last):
  File "PaddleSeg/pdseg/train.py", line 466, in <module>
    main(args)
  File "PaddleSeg/pdseg/train.py", line 453, in main
    train(cfg)
  File "PaddleSeg/pdseg/train.py", line 237, in train
    train_prog, startup_prog, phase=ModelPhase.TRAIN)
  File "/home/aistudio/PaddleSeg/pdseg/models/model_builder.py", line 196, in build_model
    multi_lovasz_softmax_loss(logits, label, ignore=mask))
TypeError: multi_lovasz_softmax_loss() got an unexpected keyword argument 'ignore'
```
修改 model_builder.py 中：
`multi_lovasz_softmax_loss(logits, label, ignore=mask))`
为
`multi_lovasz_softmax_loss(logits, label, ignore_mask=mask))`后
目前可以正常训练，非常感谢您的帮助

**Comment by michaelowenliu** [comment]
@iceriver97 hi, thanks for your interest in our repo. Glad to see you have solved this problem. Btw, I found you have several active questions there. May I know what application you are building? Then we would help you further and better.

**Comment by iceriver97** [comment]
@michaelowenliu 谢谢！我在用 PaddleSeg 做一些遥感方向的应用：

1. 在道路提取方面我注意到可以使用 Lovasz loss 做优化；
2. 在地物分类方面，使用 Deeplabv3+进行训练 miou是比较低的，我更换了最新的 OCRNet 模型进行尝试，但只有很微小的提升（1% ~2%），在使用数据增强进一步做一些调整后也只是提升了一点点，请问关于地物分类，我该如何继续优化呢？
3. 最后我想将训练好的分割模型进行部署，我尝试使用 Serving 套件，但好像你们的预处理或者后处理函数有一些问题，官方人员给我推荐了 PaddleSeg Serving，我发现它对环境条件要求比较苛刻，如果要使用的话现在还是必须使用特定的系统并安装特定版本的软件吗？

**Comment by LutaoChu** [comment]
> @LutaoChu 您好，您的分支会出现下面的错误：
> 
> ```
> Traceback (most recent call last):
>   File "PaddleSeg/pdseg/train.py", line 466, in <module>
>     main(args)
>   File "PaddleSeg/pdseg/train.py", line 453, in main
>     train(cfg)
>   File "PaddleSeg/pdseg/train.py", line 237, in train
>     train_prog, startup_prog, phase=ModelPhase.TRAIN)
>   File "/home/aistudio/PaddleSeg/pdseg/models/model_builder.py", line 196, in build_model
>     multi_lovasz_softmax_loss(logits, label, ignore=mask))
> TypeError: multi_lovasz_softmax_loss() got an unexpected keyword argument 'ignore'
> ```
> 
> 修改 model_builder.py 中：
> `multi_lovasz_softmax_loss(logits, label, ignore=mask))`
> 为
> `multi_lovasz_softmax_loss(logits, label, ignore_mask=mask))`后
> 目前可以正常训练，非常感谢您的帮助

感谢，我这边进行修复

**Comment by LutaoChu** [comment]
> @michaelowenliu 谢谢！我在用 PaddleSeg 做一些遥感方向的应用：
> 
> 1. 在道路提取方面我注意到可以使用 Lovasz loss 做优化；
> 2. 在地物分类方面，使用 Deeplabv3+进行训练 miou是比较低的，我更换了最新的 OCRNet 模型进行尝试，但只有很微小的提升（1% ~2%），在使用数据增强进一步做一些调整后也只是提升了一点点，请问关于地物分类，我该如何继续优化呢？
> 3. 最后我想将训练好的分割模型进行部署，我尝试使用 Serving 套件，但好像你们的预处理或者后处理函数有一些问题，官方人员给我推荐了 PaddleSeg Serving，我发现它对环境条件要求比较苛刻，如果要使用的话现在还是必须使用特定的系统并安装特定版本的软件吗？

1. Lovasz loss有weight参数可以调节，如果需要可以进行尝试。
2. 建议对数据集分布做一个摸底，看看是否需要清洗。如果存在类别不均衡的现象可以尝试lovasz loss或weighted softmax loss。另外针对数据的情况进行数据增强
