### ISSUE TITLE
在lanenet中运行示例中的训练代码时报错：Error: Blocking queue is killed because the data reader raises an exception

### ISSUE THREAD

**Issue by ouroboros-phy** [PaddlePaddle/PaddleSeg#398]
有谁明白这是怎么回事吗？

**Comment by michaelowenliu** [comment]
@hkhgjk hi, would you mind provide more detailed training log? Thank you.

**Comment by ouroboros-phy** [comment]
报错的细节
libpng error: IDAT: CRC error
2020-09-23 09:01:28,685-WARNING: Your reader has raised an exception!
D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")


--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\reader.py", line 1080, in _init_non_iterable
    attrs={'drop_last': self._drop_last})
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\reader.py", line 978, in __init__
    self._init_non_iterable()
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\reader.py", line 620, in from_generator
    iterable, return_list, drop_last)
  File "D:\ProgrameProject\PaddleSeg-develop\PaddleSeg-develop\contrib\LaneNet\models\model_builder.py", line 130, in build_model
    use_double_buffer=True)
  File "train.py", line 196, in train
    data_loader, avg_loss, lr, pred, grts, masks, emb_loss, seg_loss, accuracy, fp, fn = build_model(
  File "train.py", line 378, in main
    print_info(pprint.pformat(cfg))
  File "train.py", line 391, in <module>
    sys.exit(1)

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (D:\1.8.4\paddle\paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]
W0923 09:01:28.686986 12536 operator.cc:187] read raises an exception class std::future_error, no state
F0923 09:01:28.686986 12536 exception_holder.h:37] std::exception caught, no state
*** Check failure stack trace: ***

**Comment by ouroboros-phy** [comment]
paddlepaddle版本为paddlepaddle-gpu                   1.8.4.post107
cuda版本10.2

**Comment by ouroboros-phy** [comment]
其他都是按照readme里一步步弄的，什么也没改

**Comment by LielinJiang** [comment]
试试paddleseg 0.4.0的版本和paddle 1.7的版本

**Comment by ouroboros-phy** [comment]
已解决，谢谢

**Comment by liguoyu666** [comment]
> 已解决，谢谢

请问怎么解决的

**Comment by ouroboros-phy** [comment]
就是按照上面降低版本
