### ISSUE TITLE
deeplab3v+如何使用resnet作为backbone?

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/PaddleSeg#406]
我看到预训练模型中有使用res50_vd的预训练权重，但是没有找到对应的配置文件，且在deeplab.py中似乎没有resnet这个backbone，请问需要进行哪些修改？

**Comment by michaelowenliu** [comment]
@zhengzhe97 hi, which deeplab.py file are you using?

**Comment by zhengzhe97** [comment]
I use the version of paddleseg is version  5.
