### ISSUE TITLE
LaneNet：使用其他数据集出现错误

### ISSUE THREAD

**Issue by iceriver97** [PaddlePaddle/PaddleSeg#412]
我使用官方的LaneNet车道线分割项目，但更换了自己的数据集，格式都按照官方项目数据集的格式整理好了，但报错：
```
#Device count: 1
batch_size_per_dev: 2
W0924 18:20:06.613276 12848 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.2, Runtime API Version: 10.0
W0924 18:20:06.621250 12848 device_context.cc:260] device: 0, cuDNN Version: 7.6.
[SKIP] Pretrained weight ./pretrained_models/VGG16_pretrained/score_origin/weights doesn't exist
[SKIP] Pretrained weight ./pretrained_models/VGG16_pretrained/deconv_1/weights doesn't exist
[SKIP] Pretrained weight ./pretrained_models/VGG16_pretrained/score_1/weights doesn't exist
[SKIP] Pretrained weight ./pretrained_models/VGG16_pretrained/deconv_2/weights doesn't exist
[SKIP] Pretrained weight ./pretrained_models/VGG16_pretrained/score_2/weights doesn't exist
[SKIP] Pretrained weight ./pretrained_models/VGG16_pretrained/deconv_final/weights doesn't exist
[SKIP] Pretrained weight ./pretrained_models/VGG16_pretrained/score_final/weights doesn't exist
[SKIP] Pretrained weight ./pretrained_models/VGG16_pretrained/weights doesn't exist
2020-09-24 18:20:08,732-WARNING: ./pretrained_models/VGG16_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
There are 13/21 varaibles in ./pretrained_models/VGG16_pretrained are loaded.
Use multi-thread reader
W0924 18:20:08.925722 12848 build_strategy.cc:170] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.
epoch=1 step=10 lr=0.00050 loss=242.3553 seg_loss=10.7224 emb_loss=231.6328 accuracy=0.383 fp=0.9665 fn=0.617 step/sec=5.359 | ETA 11:22:36
W0924 18:20:11.018095 12848 operator.cc:187] cast raises an exception class thrust::system::system_error, parallel_for failed: invalid configuration argument
F0924 18:20:11.019109 12848 exception_holder.h:37] std::exception caught, parallel_for failed: invalid configuration argument
*** Check failure stack trace: ***
```
这是什么原因呢？我在AIStudio上运行也是同样的错误

**Comment by iceriver97** [comment]
@LutaoChu 您能帮忙解答一下吗？我实在是找不出哪里有问题。我只是单纯的更换了数据集，新数据集的图片格式，标注格式都与原数据集保持一致；LaneNet这个项目的代码只能用于官方整理的那份数据集吗？还是说数据文件名称也得跟原数据集保持一致呢？

**Comment by iceriver97** [comment]
这是官方项目地址：https://github.com/PaddlePaddle/PaddleSeg/tree/release/v0.6.0/contrib/LaneNet
你们有试过更换不同的数据集来训练吗？

**Comment by LielinJiang** [comment]
目前只测试过linux，gpu上的训练，可以换个有gpu的环境试试

**Comment by iceriver97** [comment]
@LielinJiang 我在**AIStudio**上也是同样的问题，我想问下你们有试过使用其他数据集进行训练吗？

**Comment by LielinJiang** [comment]
没有额，不过你的错误不像是数据集的错误

**Comment by iceriver97** [comment]
@LielinJiang  我也觉得数据集应该没问题。但是如上所述，我仅修改了训练所用数据集，其他都与原项目保持一致，还是会报这种错误，我在交流群中得知：*** Check failure stack trace: *** 应该是CUDA驱动报错，然后建议我检查数据集，检查了一天也没发现问题。

**Comment by iceriver97** [comment]
@LielinJiang 你们能否使用其他数据集+该项目的代码进行测试一下，看是否遇到同样的问题？

**Comment by iceriver97** [comment]
@LielinJiang  还有我在尝试更换backbone时会出现这种奇怪的错误：
```
Traceback (most recent call last):
  File "train.py", line 392, in <module>
    main(args)
  File "train.py", line 379, in main
    train(cfg)
  File "train.py", line 197, in train
    train_prog, startup_prog, phase=ModelPhase.TRAIN)
  File "/home/aistudio/LaneNet/models/model_builder.py", line 136, in build_model
    logits = seg_model(image, class_num)
  File "/home/aistudio/LaneNet/models/model_builder.py", line 74, in seg_model
    logits = lanenet.lanenet(image, class_num)
  File "/home/aistudio/LaneNet/models/modeling/lanenet.py", line 560, in lanenet
    output = encoder(img)
  File "/home/aistudio/LaneNet/models/modeling/lanenet.py", line 554, in encoder
    cfg.MODEL.LANENET.BACKBONE))
Exception: LaneNet expect enet and vgg backbone, but received enet
```
我已经设置 backbone 使用 enet ，但却提示我 except enet？

**Comment by michaelowenliu** [comment]
> @LielinJiang 还有我在尝试更换backbone时会出现这种奇怪的错误：
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 392, in <module>
>     main(args)
>   File "train.py", line 379, in main
>     train(cfg)
>   File "train.py", line 197, in train
>     train_prog, startup_prog, phase=ModelPhase.TRAIN)
>   File "/home/aistudio/LaneNet/models/model_builder.py", line 136, in build_model
>     logits = seg_model(image, class_num)
>   File "/home/aistudio/LaneNet/models/model_builder.py", line 74, in seg_model
>     logits = lanenet.lanenet(image, class_num)
>   File "/home/aistudio/LaneNet/models/modeling/lanenet.py", line 560, in lanenet
>     output = encoder(img)
>   File "/home/aistudio/LaneNet/models/modeling/lanenet.py", line 554, in encoder
>     cfg.MODEL.LANENET.BACKBONE))
> Exception: LaneNet expect enet and vgg backbone, but received enet
> ```
> 
> 我已经设置 backbone 使用 enet ，但却提示我 except enet？

@iceriver97 hi, could you please check cfg.MODEL.LANET.BACKBONE in your config file?

**Comment by iceriver97** [comment]
@michaelowenliu 谢谢，我就是那样设置啊，你可以去试试，是不是有这个BUG

**Comment by michaelowenliu** [comment]
@iceriver97 hi, may I know your paddle/paddleSeg version? Let me reproduce the error. Thank you.

**Comment by iceriver97** [comment]
@michaelowenliu  paddle = 1.8.4 ; paddleSeg = 0.6.0

**Comment by michaelowenliu** [comment]
@iceriver97 relay you once I get the point.

**Comment by iceriver97** [comment]
@michaelowenliu thx. But I also want to know why I make mistakes when I use my dataset in the LaneNet project. Can you help me?

**Comment by michaelowenliu** [comment]
@iceriver97 sure, it might take some time due to the national day.

**Comment by michaelowenliu** [comment]
> @LielinJiang 还有我在尝试更换backbone时会出现这种奇怪的错误：
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 392, in <module>
>     main(args)
>   File "train.py", line 379, in main
>     train(cfg)
>   File "train.py", line 197, in train
>     train_prog, startup_prog, phase=ModelPhase.TRAIN)
>   File "/home/aistudio/LaneNet/models/model_builder.py", line 136, in build_model
>     logits = seg_model(image, class_num)
>   File "/home/aistudio/LaneNet/models/model_builder.py", line 74, in seg_model
>     logits = lanenet.lanenet(image, class_num)
>   File "/home/aistudio/LaneNet/models/modeling/lanenet.py", line 560, in lanenet
>     output = encoder(img)
>   File "/home/aistudio/LaneNet/models/modeling/lanenet.py", line 554, in encoder
>     cfg.MODEL.LANENET.BACKBONE))
> Exception: LaneNet expect enet and vgg backbone, but received enet
> ```
> 
> 我已经设置 backbone 使用 enet ，但却提示我 except enet？

@iceriver97  hi, the issue has been resolved, please update the code.

**Comment by iceriver97** [comment]
> @iceriver97 sure, it might take some time due to the national day.
Thank you very much. Can I train with my own dataset now?

**Comment by michaelowenliu** [comment]
> > @iceriver97 sure, it might take some time due to the national day.
> > Thank you very much. Can I train with my own dataset now?

@iceriver97 hi, as I know, there could be some problem with a customized data, but whatever, how about your data? e.g. image size/resolution.

**Comment by iceriver97** [comment]
> > > @iceriver97 sure, it might take some time due to the national day.
> > > Thank you very much. Can I train with my own dataset now?
> 
> @iceriver97 hi, as I know, there could be some problem with a customized data, but whatever, how about your data? e.g. image size/resolution.

thx.This project provides datasets, and I modified my own datasets in the official format, including size/resolution and annotation format.

**Comment by phoenares** [comment]
> > > > @iceriver97 sure, it might take some time due to the national day.
> > > > Thank you very much. Can I train with my own dataset now?
> > 
> > 
> > @iceriver97 hi, as I know, there could be some problem with a customized data, but whatever, how about your data? e.g. image size/resolution.
> 
> thx.This project provides datasets, and I modified my own datasets in the official format, including size/resolution and annotation format.

@iceriver97 我也碰到过这种问题，不计算instance_loss就不太容易出现这种情况，可能是discriminative_loss实现里面有些地方越界或者异常了，可以调试一下
