### ISSUE TITLE
如何进行自定义的多尺度训练？

### ISSUE THREAD

**Issue by pengqianli** [PaddlePaddle/PaddleSeg#430]

**Comment by michaelowenliu** [comment]
@pengqianli Hi, in the current release version, the multi-scale training strategy is not supported yet. Sorry about that. Now we are upgrading the Seg repo together with PaddlePaddle2.0, and the feature of multi-scale training would be supported in the future version.

**Comment by BeyondYourself** [comment]
@michaelowenliu  目前是不是还不支持呢
