### ISSUE TITLE
Get negative loss with dice_loss or bcd_loss

### ISSUE THREAD

**Issue by linhandev** [PaddlePaddle/PaddleSeg#436]
在用dice或者bce训练的时候loss出现了负数，dice是偶尔几个，bce有的时候是全是负的而且越来越小。代码直接pull没有改过，请问这个情况正常吗。
![image](https://user-images.githubusercontent.com/29757093/94990862-a4f80500-05b1-11eb-83b4-428abe1cfa79.png)

**Comment by linhandev** [comment]
找到原因了，分割标签中有大于种类数的值，二分类的标签里有3,所以出现的负数

**Comment by Murphy-MML** [comment]
你好 很冒昧打扰  可以麻烦讲一下具体怎么更改的代码吗  我这边也遇到类似的问题但没有顺利解决 谢谢
