### ISSUE TITLE
图片过大，内存显示不足

### ISSUE THREAD

**Issue by 642721838** [PaddlePaddle/PaddleSeg#449]
在训练语义分割模型时，图片大小为1024X1024，内存显示不足，把batchsize设置为1仍然不行，请问怎么解决啊，谢谢

**Comment by michaelowenliu** [comment]
> 在训练语义分割模型时，图片大小为1024X1024，内存显示不足，把batchsize设置为1仍然不行，请问怎么解决啊，谢谢

@642721838 hi, how about your GPU memory？

**Comment by Harryoung** [comment]
Can not reproduce, long time no response, close.
