### ISSUE TITLE
请问一下怎么用eval.py看测试集的指标呢？默认的看的是验证集的吧

### ISSUE THREAD

**Issue by eddieheyutong** [PaddlePaddle/PaddleSeg#459]

**Comment by eddieheyutong** [comment]
我试着修改了cfg文件中的DATASET.TEST_FILE_LIST 这个路径改为了test.list但是还是之前验证集的结果

**Comment by wuyefeilin** [comment]
DATASET.VAL_FILE_LIST  修改这个参数

**Comment by eddieheyutong** [comment]
@wuyefeilin 我修改了这个配置选项之后执行eval.py文件loss、acc、iou这些指标一直是0.0000

**Comment by eddieheyutong** [comment]
@wuyefeilin 
我按照您所说的修改了这个路径为test.list的路径，但是所有的指标都是0，以下为提示信息：
[EVAL]#image=1525 acc=0.0000 IoU=0.0000
[EVAL]Category IoU: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[EVAL]Category Acc: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
/home/heyutong/PaddleSeg/pdseg/metrics.py:141: RuntimeWarning: invalid value encountered in double_scalars
  pe = tp / (total * total)
/home/heyutong/PaddleSeg/pdseg/metrics.py:142: RuntimeWarning: invalid value encountered in double_scalars
  po = tc / total
[EVAL]Kappa:nan

**Comment by wuyefeilin** [comment]
麻烦提供一下你的运行命令和日志

**Comment by eddieheyutong** [comment]
> 麻烦提供一下你的运行命令和日志

您好，还是这个问题，我现在无法用eval.py对测试集进行测试，我执行的代码是python3 pdseg/eval.py --use_gpu --cfg ./configs/deeplabv3p_resnet50_vd_cityscapes.yaml
然后我的模型这句话可以对验证集进行测试，但是 路径改为测试集就指标全是0

**Comment by eddieheyutong** [comment]
> 麻烦提供一下你的运行命令和日志

DATASET:
    DATA_DIR: "./dataset/cityscapes/"
    IMAGE_TYPE: "rgb"  # choice rgb or rgba
    NUM_CLASSES: 19
    TEST_FILE_LIST: "dataset/cityscapes/val.list"
    TRAIN_FILE_LIST: "dataset/cityscapes/train.list"
    VAL_FILE_LIST: "dataset/cityscapes/test.list"
    VIS_FILE_LIST: "dataset/cityscapes/val.list"
    IGNORE_INDEX: 255
    SEPARATOR: " "
这是我的配置文件中的关于数据集这里的配置，烦请您帮忙看一下问题出在哪里？

**Comment by eddieheyutong** [comment]
@wuyefeilin @nepeplwu

**Comment by wuyefeilin** [comment]
cityscape的测试机不能进行eval， 它没有提供相应的标签，你如果要知道测试集的结果需要把预测的结果按照官方的要求进行上传。

**Comment by eddieheyutong** [comment]
> cityscape的测试机不能进行eval， 它没有提供相应的标签，你如果要知道测试集的结果需要把预测的结果按照官方的要求进行上传。

首先非常感谢您的回复，您说的这个想要知道测试集（test）的结果需要把预测的结果进行上传是具体什么意思我没有太理解，意思是PaddleSeg里并不提供对测试集的验证吗？我想知道测试集的结果需要把我保存的训练结果上传给Ctiyscapes官方吗？

**Comment by wuyefeilin** [comment]
是的，需要按照官方要求将测试集的预测结果上传到官方网站进行评估
