### ISSUE TITLE
lanenet的FP一直是0.7几

### ISSUE THREAD

**Issue by qinshihao111** [PaddlePaddle/PaddleSeg#472]
我是直接使用的lanenet的官方示例的，然后他的FP一直是在0.7以上，我下载了你们训练好的模型，测试了一下也是这么多，但是我看论文只有0.078，请问下这是为什么？据我理解，FP=0.7应该表示预测错误的点占了70%吧
![SFHOR}3$APAA 1`0II@~8@E](https://user-images.githubusercontent.com/40258758/95971311-a17f3c00-0e43-11eb-8f4f-70f00695fa97.png)

**Comment by phoenares** [comment]
> 我是直接使用的lanenet的官方示例的，然后他的FP一直是在0.7以上，我下载了你们训练好的模型，测试了一下也是这么多，但是我看论文只有0.078，请问下这是为什么？据我理解，FP=0.7应该表示预测错误的点占了70%吧
> ![SFHOR}3$APAA 1`0II@~8@E](https://user-images.githubusercontent.com/40258758/95971311-a17f3c00-0e43-11eb-8f4f-70f00695fa97.png)

@qinshihao111 这个可能是预测的线条相对于ground truth来说太宽了，所以fp就很高，视觉效果上应该看不太出来。这个跟制作gt的时候线条的宽度和图像缩放应该是有关的。个人看法

**Comment by qinshihao111** [comment]
这不是说明它还是没有很好地拟合训练集吗，fp这么高，iou会很低吧

**Comment by michaelowenliu** [comment]
> 这不是说明它还是没有很好地拟合训练集吗，fp这么高，iou会很低吧

@qinshihao111 Hi, yes, it is not fitting labels well, but actually, the lane labels are not good enough. You might visualize the results, and compare them with what you need, e.g. a lane area or lane line?

**Comment by qinshihao111** [comment]
@michaelowenliu 
Thanks.I think I need a lane area.Maybe I need to set the width of lane to 30?

**Comment by michaelowenliu** [comment]
> @michaelowenliu
> Thanks.I think I need a lane area.Maybe I need to set the width of lane to 30?

@qinshihao111 hi, I guess tuning the width could help. May I have a question on how you will use the lane area later? I mean your downstream application.

**Comment by qinshihao111** [comment]
@michaelowenliu 
It's really useful for me.Now I just need the results to complete my paper~
