### ISSUE TITLE
数据集找不到

### ISSUE THREAD

**Issue by brainchen2020** [PaddlePaddle/PaddleSeg#481]
hello，我刚才尝试运行下教程报找不到数据集错误。
我也不知道去哪找数据。。
有建议吗？

<img width="1256" alt="截屏2020-10-16上午7 30 49" src="https://user-images.githubusercontent.com/29730101/96196390-d5607b80-0f81-11eb-8adb-8adb85f4891e.png">

**Comment by LutaoChu** [comment]
你好，我们正在升级最新版的教程，请耐心等候一下。等升级好通知你

**Comment by LutaoChu** [comment]
最新版教程已升级好，你可以再体验一下 https://aistudio.baidu.com/aistudio/projectdetail/100798
