### ISSUE TITLE
多类别Diceloss

### ISSUE THREAD

**Issue by shiontao** [PaddlePaddle/PaddleSeg#495]
我看到loss.py中是写了多类别的diceloss的但是在参数文件中设置后程序显示不支持多类别。

**Comment by LutaoChu** [comment]
你好，loss.py中的multi_dice_loss不是多类别的意思，是指多路损失函数的意思，主要适配ICNet。
多分类的dice loss已列入我们的开发计划中，敬请期待！

**Comment by Qingcsai** [comment]
期待
