### ISSUE TITLE
u-net输出mask图片大小问题

### ISSUE THREAD

**Issue by gxqnba** [PaddlePaddle/PaddleSeg#498]
请问使用paddleseg中的u-net模型，能让输出的mask图片大小与输入图片大小一致吗？我输入的图片有好几种分辨率的，但预测得到的mask图片都是521*512的。

**Comment by wuyefeilin** [comment]
你利用pdseg/vis.py进行预测，最终得到的图像是跟你输入图像的大小一致的

**Comment by gxqnba** [comment]
> 你利用pdseg/vis.py进行预测，最终得到的图像是跟你输入图像的大小一致的

那paddleseg进行训练的时候是不是先将我的输入图片（例如1500*2000）resize成512*512，然后预测得到512*512的logits，然后将GroundTrurhresize成512*512，然后求loss？vis的时候是不是将得到的mask（512*512）resize成1500*2000？

**Comment by gxqnba** [comment]
> 你利用pdseg/vis.py进行预测，最终得到的图像是跟你输入图像的大小一致的

那么paddleseg训练的时候是不是会将输入图片统一resize到一个分辨率，得到512-512的mask，然后将GroundTruth也rezie到一个分辨率，最后用mask和resize后的GroundTruth计算loss？利用vis.py进行预测的时候，是不是将得到的512-512mask .resize到输入图像大小？

**Comment by wuyefeilin** [comment]
在训练的时候经过数据增强后会得到大小一致的图像和ground truth。利用vis.py会根据所选取的数据增强方法恢复回原始的图像大小

**Comment by gxqnba** [comment]
> 在训练的时候经过数据增强后会得到大小一致的图像和ground truth。利用vis.py会根据所选取的数据增强方法恢复回原始的图像大小

那这样来回resize会不会造成精度损失啊？

**Comment by wuyefeilin** [comment]
具体的可以参考数据增强这一章节，https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.6.0/docs/data_aug.md

**Comment by gxqnba** [comment]
> 具体的可以参考数据增强这一章节，https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.6.0/docs/data_aug.md

好的，谢谢解疑。
