### ISSUE TITLE
请问，标定图片是需要什么样的，为什么mini_pet/annotations/trimaps中的图片都是(1,1,1)？

### ISSUE THREAD

**Issue by Jihongwei1** [PaddlePaddle/PaddleSeg#50]

**Comment by wuyefeilin** [comment]
请问你所说的图片都是(1,1,1)，是指所有标签只有1吗？还是个别图像？另外你是怎么得到的图片都是（1，1，1），不介意的话，请给一下你的代码

mini_pet是一个3类数据集，标签为：0，1和2，其中0表示背景。

**Comment by LutaoChu** [comment]
您好，mini_pet的标定图片实际上是单通道灰度图，建议使用cv2.imread(image, -1)来进行查看原始的图片。

关于标定图片标准，最好是单通道灰度图，像素标注类别需要从0开始递增。

**Comment by Jihongwei1** [comment]
> 您好，mini_pet的标定图片实际上是单通道灰度图，建议使用cv2.imread（image，-1）来进行查看原始图片。
> 
> 关于标定图片标准，最好是单通道灰度图，定义标注类别需要从0开始递增。

感谢，已解决。
