### ISSUE TITLE
学习率设置问题

### ISSUE THREAD

**Issue by TuoniTuoni** [PaddlePaddle/PaddleSeg#500]
在detection库中，学习率根据gpu_num和batch_size有个计算方法。请问Seg的学习率应该如何设置，根据不同的算法和loss设置不同？

**Comment by wuyefeilin** [comment]
在我们pdseg中，我的batch_size 是指整体的batch_size， 所以学习率跟gpu_num没关系，理论上当你增加batch_size时，学习率也得同步增加
