### ISSUE TITLE
paddle对自己设计和改进的Unet如何进行单元测试

### ISSUE THREAD

**Issue by GinkgoX** [PaddlePaddle/PaddleSeg#502]
您好，请问如何对PaddleSeg/pdseg/models/modeling/unet.py进行模型测试和验证呢？

**Comment by nepeplwu** [comment]
@GinkgoX ，你说的是模型效果的验证还是接口的单测？如果是单测，可以直接参考网上的python单测教程，如果是模型效果验证，可以参考[使用教程](https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.6.0/docs/usage.md)，跑下训练和评估流程
