### ISSUE TITLE
2020 CCF BDCI: 遥感影像地块分割baseline 默认配置未按文件更新

### ISSUE THREAD

**Issue by Charlie-Wilson0211** [PaddlePaddle/PaddleSeg#504]
2020 CCF BDCI: 遥感影像地块分割baseline中运行，数据集已经配置好，数据核验时如下

aistudio@jupyter-134162-1125032:~/work/PaddleSeg$ python pdseg/check.py --cfg ./unet.yaml
Traceback (most recent call last):
  File "pdseg/check.py", line 657, in <module>
    main(args)
  File "pdseg/check.py", line 627, in main
    cfg.check_and_infer()
  File "/home/aistudio/work/PaddleSeg/pdseg/utils/collect.py", line 120, in check_and_infer
    'utf-8').readlines()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/codecs.py", line 904, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: './dataset/cityscapes/test.list'

定位问题：check.py的626行中update_from_segconfig未生效，调用后配置文件信息未更新为文件的信息，依然未默认配置config.py的信息

**Comment by Charlie-Wilson0211** [comment]
在check.py中加入print(cfg.DATASET.DATA_DIR,cfg.DATASET.TRAIN_FILE_LIST,cfg.DATASET.VAL_FILE_LIST,cfg.DATASET.TEST_FILE_LIST)

输出：
./dataset/rs_data ./dataset/rs_data/train_list.txt ./dataset/rs_data/val_list.txt ./dataset/cityscapes/test.list

**Comment by cocolord** [comment]
你好，这个问题后来有解决吗
