### ISSUE TITLE
paddle.fluid.install_check.run_check() 出错

### ISSUE THREAD

**Issue by abanger** [PaddlePaddle/PaddleSeg#507]
root@test:~# export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/TensorRT/lib
root@test:~# python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid
>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ...
W1021 12:53:05.700925 19797 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.0, Runtime API Version: 9.0
W1021 12:53:05.702206 19797 device_context.cc:260] device: 0, cuDNN Version: 7.6.
/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/install_check.py", line 124, in run_check
    test_simple_exe()
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/install_check.py", line 122, in test_simple_exe
    fetch_list=[out0.name, param_grads[1].name])
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::GEMM<float>(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, float const*, float, float*) const
3   void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::MatMul<float>(paddle::framework::Tensor const&, paddle::operators::math::MatDescriptor const&, paddle::framework::Tensor const&, paddle::operators::math::MatDescriptor const&, float, paddle::framework::Tensor*, float) const
4   paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
7   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
8   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
9   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
10  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
11  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/layer_object_helper.py", line 52, in append_op
    stop_gradient=stop_gradient)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/nn.py", line 962, in forward
    type="matmul", inputs=inputs, outputs={"Out": tmp}, attrs=attrs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/layers.py", line 461, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/install_check.py", line 41, in forward
    x = self._linear1(inputs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/layers.py", line 461, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/install_check.py", line 113, in test_simple_exe
    out0 = simple_layer0(inp0)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/install_check.py", line 124, in run_check
    test_simple_exe()
  File "<stdin>", line 1, in <module>

----------------------
Error Message Summary:
----------------------
ExternalError:  Cublas error, CUBLAS_STATUS_EXECUTION_FAILED  at (/paddle/paddle/fluid/operators/math/blas_impl.cu.h:34)
  [operator < matmul > error]

**Comment by abanger** [comment]
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

**Comment by abanger** [comment]
发现还有问题,重新发到: https://github.com/PaddlePaddle/Paddle/issues/28258

**Comment by abanger** [comment]
运行train.py也出错，但能正常运行
python pdseg/train.py --use_gpu --cfg  a.yaml



Use multi-thread reader


--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::operators::CUDNNConvOpKernel<float>::Compute(paddle::framework::ExecutionContext const&) const
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform
::CUDAPlace, false, 0ul, paddle::operators::CUDNNConvOpKernel<float>, paddle::operators::CUDNNConvOpKernel<double>, paddle::operators::CUDNNConvOpKernel<paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
6   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
7   paddle::framework::details::ComputationOpHandle::RunImpl()
8   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
9   paddle::framework::details::FastThreadedSSAGraphExecutor::RunTracedOps(std::vector<paddle::framework::details::OpHandleBase*, std::allocator<paddle::framework::details::OpHandleBase*> > const&)
10  paddle::framework::details::FastThreadedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&, bool)
11  paddle::framework::details::ScopeBufferedMonitor::Apply(std::function<void ()> const&, bool)
12  paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&, bool)
13  paddle::framework::ParallelExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layers/nn.py", line 2938, in conv2d
    "data_format": data_format,
  File "/home/bdci/PaddleSeg/pdseg/models/backbone/resnet_vd.py", line 253, in conv_bn_layer
    name=name + '.conv2d.output.1')
  File "/home/bdci/PaddleSeg/pdseg/models/backbone/resnet_vd.py", line 107, in net
------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layers/nn.py", line 2938, in conv2d
    "data_format": data_format,
  File "/home/bdci/PaddleSeg/pdseg/models/backbone/resnet_vd.py", line 253, in conv_bn_layer
    name=name + '.conv2d.output.1')
  File "/home/bdci/PaddleSeg/pdseg/models/backbone/resnet_vd.py", line 107, in net
    name="conv1_1")
  File "/home/bdci/PaddleSeg/pdseg/models/modeling/deeplab.py", line 365, in resnet_vd
    dilation_dict=dilation_dict)
  File "/home/bdci/PaddleSeg/pdseg/models/modeling/deeplab.py", line 382, in deeplabv3p
    data, decode_shortcut = resnet_vd(img)
  File "/home/bdci/PaddleSeg/pdseg/models/model_builder.py", line 78, in seg_model
    logits = deeplab.deeplabv3p(image, class_num)
  File "/home/bdci/PaddleSeg/pdseg/models/model_builder.py", line 167, in build_model
    logits = seg_model(image, class_num)
  File "pdseg/train.py", line 237, in train
    train_prog, startup_prog, phase=ModelPhase.TRAIN)
  File "pdseg/train.py", line 453, in main
    train(cfg)
  File "pdseg/train.py", line 466, in <module>
    main(args)

----------------------
Error Message Summary:
----------------------
ExternalError:  Cudnn error, CUDNN_STATUS_EXECUTION_FAILED  at (/paddle/paddle/fluid/operators/conv_cudnn_op.cu:300)
  [operator < conv2d > error]
epoch=1 step=20 lr=0.03000 loss=0.9517 step/sec=1.850 | ETA 134:12:38
epoch=1 step=30 lr=0.03000 loss=0.9186 step/sec=2.056 | ETA 120:48:10
epoch=1 step=40 lr=0.03000 loss=0.7732 step/sec=2.074 | ETA 119:44:44
epoch=1 step=50 lr=0.03000 loss=0.6341 step/sec=1.823 | ETA 136:11:54
epoch=1 step=60 lr=0.03000 loss=0.7294 step/sec=1.928 | ETA 128:47:24
epoch=1 step=70 lr=0.03000 loss=0.6148 step/sec=1.945 | ETA 127:40:11
epoch=1 step=80 lr=0.03000 loss=0.6855 step/sec=2.023 | ETA 122:45:34
epoch=1 step=90 lr=0.03000 loss=0.6335 step/sec=2.058 | ETA 120:39:43
......

**Comment by wuyefeilin** [comment]
初步看是版本的问题， 你的cudnn， cuda和paddle版本是多少

**Comment by LutaoChu** [comment]
应该是你的cudnn版本不匹配，安装paddle时需要注意对应的cuda和cudnn版本

**Comment by abanger** [comment]
> 应该是你的cudnn版本不匹配，安装paddle时需要注意对应的cuda和cudnn版本

PaddlePaddle 1.8.5
GeForce RTX 2080 ti
Cuda compilation tools, release 9.0, V9.0.176 和CUDNN7.6
Ubuntu 18.04

pip3 install paddlepaddle-gpu==1.8.5.post97

按要求版本安装了。
能正常运行：python pdseg/train.py --use_gpu --cfg a.yaml，出错，但能运行。
不能正常运行：python pdseg/vis.py --use_gpu --cfg a.yaml，出错，不能运行。

**Comment by LutaoChu** [comment]
运行一下
```shell
cat /usr/local/cuda/version.txt

nvidia-smi

dpkg -S cudnn
```
3个运行结果贴出来看一下

**Comment by abanger** [comment]
root@test:~# cat /usr/local/cuda/version.txt
CUDA Version 9.0.176

root@test:~# nvidia-smi
Tue Oct 27 14:06:12 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.57                 Driver Version: 410.57                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:00:05.0 Off |                  N/A |
| 69%   68C    P2   255W / 250W |   8179MiB / 10989MiB |     99%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:00:06.0 Off |                  N/A |
| 37%   38C    P0     1W / 250W |      0MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  Off  | 00000000:00:07.0 Off |                  N/A |
| 64%   65C    P2   162W / 250W |  10743MiB / 10989MiB |     75%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     12158      C   python3                                     8169MiB |
|    2      5376      C   python3                                    10733MiB |
+-----------------------------------------------------------------------------+

注：0  GeForce RTX 2080 正在运行python pdseg/train.py --use_gpu --cfg a.yaml；
       1   GeForce RTX 2080 没用
       2   GeForce RTX 2080  ，在运行一个tensoflow程序。

“”“
root@test:~# cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 6
#define CUDNN_PATCHLEVEL 5
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"
root@test:~#
“”“

CUDNN手工安装。

**Comment by LutaoChu** [comment]
试试用conda安装，新建一个conda环境
```
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
conda config --set show_channel_urls yes
conda install paddlepaddle-gpu cudatoolkit=9.0
```

还是不行的话建议去飞桨官方技术交流群问问
(QQ群号:703252161)

**Comment by abanger** [comment]
> 试试用conda安装，新建一个conda环境
> 
> ```
> conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
> conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
> conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
> conda config --set show_channel_urls yes
> conda install paddlepaddle-gpu cudatoolkit=9.0
> ```
> 
> 还是不行的话建议去飞桨官方技术交流群问问
> (QQ群号:703252161)

群答案？

**Comment by LutaoChu** [comment]
什么意思？

**Comment by LutaoChu** [comment]
试了一下，它的意思是去加新群 1108045677

**Comment by abanger** [comment]
Cuda 升级为 release 10.1, V10.1.243，正常。
