### ISSUE TITLE
请问，所有预训练模型的mean和std都是默认0.5吗？为何不给出预训练模型对应的归一化参数呢？

### ISSUE THREAD

**Issue by pengqianli** [PaddlePaddle/PaddleSeg#509]

**Comment by nepeplwu** [comment]
@pengqianli ，mean和std对于最终训练结果影响很小，直接设置为0.5即可，只要保证预测时归一化所用的mean和std与训练保持一致即可

**Comment by pengqianli** [comment]
好的，谢谢！

**Comment by zhuang-hao-ming** [comment]
@nepeplwu  你好，请问一下，paddleseg提供的快速入门程序，好像没有在参数中设置归一化的mean和std，是不是它已经在内部进行了归一化

**Comment by nepeplwu** [comment]
@zhuang-hao-ming ，是的，默认使用`[0.5, 0.5, 0.5]`作为std和mean
