### ISSUE TITLE
vis.py 文件当中：test_prog = test_prog.clone(for_test=True) 

### ISSUE THREAD

**Issue by warsing1** [PaddlePaddle/PaddleSeg#51]
我在训练时设置batch_size=1, CPU_NUM=1。为何在利用vis.py画图或eval.py执行evaluation时，代码test_prog = test_prog.clone(for_test=True) 不加for_test=True得效果要比加入for_test=True参数得map要高很多；并且vis.py画预测图的效果也明显好很多？是因为batch_norm的缘故吗？难道不是设置batch_size=1，batch_norm就失效了吗？ 求大神帮忙解答以下。

**Comment by wuyefeilin** [comment]
> 我在训练时设置batch_size = 1，CPU_NUM = 1。为什么在利用vis.py画图或eval.py执行评估时，代码test_prog = test_prog.clone（for_test = True）不加for_test = True得效果要比加入for_test是因为batch_norm的缘故吗？难道不是设置batch_size = 1，batch_norm就可以失效了吗？求大神帮忙解答以下。

在测试中，batch_size是不会影响预测结果的。

在卷积运算中，bn是针对每一个通道进行计算的，所以并不能通过将batch_size = 1设置成1让其失效的。

test_prog = test_prog.clone（for_test = True）和不加for_test = True的实验，你能提供一下相关结果吗？以及相应的配置

**Comment by lyf6** [comment]
我也遇到了相同的问题，loss和miou都差好多。我选用的配置是pspnet，layers:101
将for_test设置为False的结果：loss=0.09，acc=0.9968，IOU=0.8845
将for_test设置为true的结果：loss=1.417，acc=0.9196，IOU=0.4760

**Comment by wuyefeilin** [comment]
你好，能提供一下具体的运行场景和运行日志吗？

**Comment by lyc1995452-star** [comment]
请问你们在运行可视化时，出现这种情况没？
Traceback (most recent call last):
File "vis.py", line 212, in
visualize(cfg, **args.dict)
File "vis.py", line 133, in visualize
for imgs, grts, img_names, valid_shapes, org_shapes in test_reader:
File "/PaddleSeg-release-v0.7.0/pdseg/reader.py", line 136, in batch_reader
for img, grt, img_name, valid_shape, org_shape in reader():
File "/PaddleSeg-release-v0.7.0/pdseg/reader.py", line 81, in generator
yield self.process_image(line, self.data_dir, self.mode)
File "/PaddleSeg-release-v0.7.0/pdseg/reader.py", line 251, in process_image
line, data_dir, mode=mode)
File "/PaddleSeg-release-v0.7.0/pdseg/reader.py", line 205, in load_image
grt_height = grt.shape[0]
IndexError: tuple index out of range
