### ISSUE TITLE
ERROR: Profiler is deactivated, and no profiling report will be generated

### ISSUE THREAD

**Issue by foreverseer** [PaddlePaddle/PaddleSeg#514]
完整报错信息

I1024 07:54:51.418932 12372 analysis_predictor.cc:138] Profiler is deactivated, and no profiling report will be generated.
I1024 07:54:51.434559 12372 analysis_predictor.cc:875] MODEL VERSION: 1.8.5
I1024 07:54:51.434559 12372 analysis_predictor.cc:877] PREDICTOR VERSION: 1.8.5
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [conv_affine_channel_fuse_pass]e[0m
e[32m--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
I1024 07:54:51.809556 12372 graph_pattern_detector.cc:101] ---  detected 64 subgraphs
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [multihead_matmul_fuse_pass_v2]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
e[32m--- Running IR pass [fc_elementwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add_act_fuse_pass]e[0m
I1024 07:54:51.903313 12372 graph_pattern_detector.cc:101] ---  detected 44 subgraphs
e[32m--- Running IR pass [conv_elementwise_add2_act_fuse_pass]e[0m
I1024 07:54:51.918923 12372 graph_pattern_detector.cc:101] ---  detected 16 subgraphs
e[32m--- Running IR pass [conv_elementwise_add_fuse_pass]e[0m
I1024 07:54:51.918923 12372 graph_pattern_detector.cc:101] ---  detected 5 subgraphs
e[32m--- Running IR pass [transpose_flatten_concat_fuse_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
I1024 07:54:51.934547 12372 ir_params_sync_among_devices_pass.cc:41] Sync params from CPU to GPU
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [memory_optimize_pass]e[0m
I1024 07:54:52.012671 12372 memory_optimize_pass.cc:223] Cluster name : batch_norm_6.tmp_2  size: 68689920
I1024 07:54:52.012671 12372 memory_optimize_pass.cc:223] Cluster name : res5c.add.output.5.tmp_1  size: 68689920
I1024 07:54:52.012671 12372 memory_optimize_pass.cc:223] Cluster name : depthwise_conv2d_3.tmp_0  size: 160318656
I1024 07:54:52.012671 12372 memory_optimize_pass.cc:223] Cluster name : batch_norm_8.tmp_0  size: 8192
I1024 07:54:52.012671 12372 memory_optimize_pass.cc:223] Cluster name : concat_1.tmp_0  size: 160318656
I1024 07:54:52.012671 12372 memory_optimize_pass.cc:223] Cluster name : batch_norm_14.tmp_2  size: 135005184
I1024 07:54:52.012671 12372 memory_optimize_pass.cc:223] Cluster name : image  size: 25202700
I1024 07:54:52.012671 12372 memory_optimize_pass.cc:223] Cluster name : batch_norm_8.tmp_1  size: 8192
I1024 07:54:52.012671 12372 memory_optimize_pass.cc:223] Cluster name : relu_2.tmp_0  size: 68689920
I1024 07:54:52.012671 12372 memory_optimize_pass.cc:223] Cluster name : bilinear_interp_0.tmp_0  size: 8586240
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
Traceback (most recent call last):
  File "infer.py", line 324, in <module>
    run(gflags.FLAGS.conf, gflags.FLAGS.input_dir, gflags.FLAGS.ext)
  File "infer.py", line 306, in run
    seg_predictor.predict(imgs)
  File "infer.py", line 277, in predict
    output_data = self.predictor.run(input_data)[0]
paddle.fluid.core_avx.EnforceNotMet: 
--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.
------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\layers\tensor.py", line 375, in concat
    type='concat', inputs=inputs, outputs={'Out': [out]}, attrs=attrs)
  File "C:\data\zxb\PaddleSeg\pdseg\models\modeling\deeplab.py", line 147, in encoder
    data = fluid.layers.concat(concat_logits, axis=1)
  File "C:\data\zxb\PaddleSeg\pdseg\models\modeling\deeplab.py", line 390, in deeplabv3p
    data = encoder(data)
  File "C:\data\zxb\PaddleSeg\pdseg\models\model_builder.py", line 78, in seg_model
    logits = deeplab.deeplabv3p(image, class_num)
  File "C:\data\zxb\PaddleSeg\pdseg\models\model_builder.py", line 167, in build_model
    logits = seg_model(image, class_num)
  File "pdseg/export_model.py", line 88, in export_inference_model
    infer_prog, startup_prog, phase=ModelPhase.PREDICT)
  File "pdseg/export_model.py", line 130, in main
    export_inference_model(args)
  File "pdseg/export_model.py", line 134, in <module>
    main()
----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The 2-th dimension of input[0] and input[1] is expected to be equal.But received input[0]'s shape = [1, 256, 65, 129], input[1]'s shape = [1, 256, 33, 33].
  [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:65 != inputs_dims[i][j]:33.] at (D:\1.8.5\paddle\paddle/fluid/operators/concat_op.h:63)
  [operator < concat > error]
I1024 07:54:52.043922 12372 analysis_predictor.cc:496] ======= optimize end =======
W1024 07:54:52.075171 12372 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 11.1, Runtime API Version: 10.0
W1024 07:54:52.122056 12372 device_context.cc:260] device: 0, cuDNN Version: 7.6.`

环境：windows server 2019
GPU:8*RTX 2080Ti
CPU:Intel(R)_Xeon(R)_CPU_E5-2678_v3_@_2.50GHz
硬盘：Samsung&Prod_SSD_860_EVO_250G
内存：64GB

版本信息：
Python 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Cuda compilation tools, release 10.0, V10.0.130
cudnn 7.6.5.32
paddlepaddle-gpu 1.8.5
paddlex 1.2.1

报错文件
链接：https://pan.baidu.com/s/12iDDWlLGjyR54Aaq_Vunvg 
提取码：7dww

**Comment by wuyefeilin** [comment]
![image](https://user-images.githubusercontent.com/30919197/97127316-3f440680-1774-11eb-814c-258e611c6c80.png)
![image](https://user-images.githubusercontent.com/30919197/97127352-5551c700-1774-11eb-970f-4b6b30a98ded.png)
按照提示，是你的传回到deeplab进行concat的两个tensoreshape不一致导致的
