### ISSUE TITLE
如何修改能将vis.py的输出结果为单通道灰度图？

### ISSUE THREAD

**Issue by TuoniTuoni** [PaddlePaddle/PaddleSeg#516]
![paddleseg](https://user-images.githubusercontent.com/18210024/97104259-5e4b8580-16ed-11eb-8429-d55642b96d41.PNG)
这样操作之后还是不行呀

**Comment by TuoniTuoni** [comment]
![paddleseg](https://user-images.githubusercontent.com/18210024/97104277-876c1600-16ed-11eb-8535-62ba28883d9e.PNG)

**Comment by TuoniTuoni** [comment]
图片怎么显示不出来，其实就是如下修改了一下vis.py,但是输出的还是彩色分割png
if grt is not None:
                    grt = grt[0:valid_shape[0], 0:valid_shape[1]]
                    grt_pil = PILImage.fromarray(grt.astype(np.uint8), mode='P')
                    #grt_pil.putpalette(color_map)
                    grt_pil = grt_pil.resize((org_shape[1], org_shape[0]))
                    #grt = np.array(grt_pil.convert("RGB"))
                    log_writer.add_image("Label/{}".format(img_name),grt_pil,epoch)
                    #log_writer.add_image("Label/{}".format(img_name), grt,epoch)

**Comment by wuyefeilin** [comment]
你改错地方了，https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.7.0/pdseg/vis.py#L165 这个地方你修改为你想要的格式。 这个是vdl 可视化使用的
