### ISSUE TITLE
多卡训练的batchsize是config里设置的值，还是需要该值乘以显卡数

### ISSUE THREAD

**Issue by liguoyu666** [PaddlePaddle/PaddleSeg#521]
我用４张显卡训练，发现设置的值乘以单个epoch的step数就约等于图片总数了

**Comment by liguoyu666** [comment]
还是说多卡训练的时候，单个epoch内，每张显卡上都要把所有图片跑一遍？我个人理解的多卡训练，单个epoch内，是把图片按数量平分在每张显卡上的。

**Comment by wuyefeilin** [comment]
静态图里面，多卡训练的batchsize是config里设置的值

**Comment by liguoyu666** [comment]
> 静态图里面，多卡训练的batchsize是config里设置的值

谢谢解答，动态图里是设置的值乘以显卡数吗，即将发布的新版本好像就是换成动态图了吧

**Comment by wuyefeilin** [comment]
> > 静态图里面，多卡训练的batchsize是config里设置的值
> 
> 谢谢解答，动态图里是设置的值乘以显卡数吗，即将发布的新版本好像就是换成动态图了吧

是的

**Comment by liguoyu666** [comment]
> > > 静态图里面，多卡训练的batchsize是config里设置的值
> > 
> > 
> > 谢谢解答，动态图里是设置的值乘以显卡数吗，即将发布的新版本好像就是换成动态图了吧
> 
> 是的

谢谢！
