### ISSUE TITLE
关于yaml文件配置的一些问题

### ISSUE THREAD

**Issue by wstchhwp** [PaddlePaddle/PaddleSeg#522]
1.数据增强方式在配置文件中，改变以后是训练集和其label一起都做出相应的改变了吗？
# **************************数据增强配置******************************
AUG:
    AUG_METHOD: "unpadding"
    FIX_RESIZE_SIZE: (256, 256)
    # # 图像镜像左右翻转
    # MIRROR: True
2.比如想使用OCRnet+Resnet101的搭配，以下的MODEL怎么改？
# **********************  预训练模型配置*******************************
MODEL:
    MODEL_NAME: "ocrnet"
    DEFAULT_NORM_TYPE: "bn"
    HRNET:
        STAGE2:
            NUM_CHANNELS: [18, 36]
        STAGE3:
            NUM_CHANNELS: [18, 36, 72]
        STAGE4:
            NUM_CHANNELS: [18, 36, 72, 144]
    OCR:
        OCR_MID_CHANNELS: 512
        OCR_KEY_CHANNELS: 256
    MULTI_LOSS_WEIGHT: [1.0, 1.0]

**Comment by wuyefeilin** [comment]
是的， label的变化会同步进行
