### ISSUE TITLE
语义分割打卡7日营：单张图像预测出现随机结果bug

### ISSUE THREAD

**Issue by sunnyhuang731** [PaddlePaddle/PaddleSeg#525]
dummy_data数据集50张图像训练出来的deelpab模型，每次检查加载模型的参数都一样，每次预测的原图一样时，会出现不一样的预测结果，这是bug项目的链接[https://aistudio.baidu.com/aistudio/projectdetail/1161160?shared=1](url)

**Comment by wuyefeilin** [comment]
提示项目不存在， 你可以试试拉一下release/0.7.0分支最新的代码看看是否还是一样
