### ISSUE TITLE
AI studio没法安装tensor RT怎么办啊：AttributeError: module 'paddle' has no attribute 'enable_static'

### ISSUE THREAD

**Issue by knightyxp** [PaddlePaddle/PaddleSeg#526]
AI studio没法安装tensor RT怎么办啊
想采用hrnet-ocr进行其他数据集的分割预测
出现如下报错：
TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvrtc.so.11.0: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure TensorRT dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Wind嘛ows: set PATH by `set PATH=XXX;Traceback (most recent call last):
  File "./pdseg/train.py", line 457, in <module>
    paddle.enable_static()
AttributeError: module 'paddle' has no attribute 'enable_static'

但是 aistudio的cuda版本为9.2 tensorrt上没有对应的版本 ，人傻了 这咋整呢？百度能回复下

**Comment by nepeplwu** [comment]
@knightyxp 完整的报错堆栈麻烦贴下

**Comment by liguoyu666** [comment]
我也报了次这个错，好像把这行代码注释掉不影响

**Comment by nepeplwu** [comment]
@liguoyu666 @knightyxp 这个问题是因为paddle版本较低，不存在`enable_static`这个接口导致，可以直接删除PaddleSeg中的这行代码
