### ISSUE TITLE
关于预训练模型

### ISSUE THREAD

**Issue by botaoye** [PaddlePaddle/PaddleSeg#528]
你好。我在使用提供的预训练模型的时候，发现预训练模型没有提供训练时的图像预处理的信息。比如，我想要使用hrnet_w64_bn_imagenet 这一预训练模型。我想要只想到在imagenet预训练的时候的输入图像通道顺序（rgb还是bgr）以及预训练时图像有没有除以255。由于这些信息可能影响训练的模型效果，所以，想要咨询一下有没有提供这些信息，只是我没有找到？要是没有的话，请问可以不可以告知一下这些数据？谢谢。

**Comment by wuyefeilin** [comment]
imagenet数据集的预训练模型，是从PaddleClas直接拿过来的，具体模型的配置可以到其repo查看相关日志。像hrent_64_bn_imagenet是采用rgb的训练模式，预训练时图像是有除以255的

**Comment by botaoye** [comment]
> imagenet数据集的预训练模型，是从PaddleClas直接拿过来的，具体模型的配置可以到其repo查看相关日志。像hrent_64_bn_imagenet是采用rgb的训练模式，预训练时图像是有除以255的
好的，明白了。多谢回复。
