### ISSUE TITLE
AttributeError: module 'paddleseg' has no attribute 'cvlibs'

### ISSUE THREAD

**Issue by deep-practice** [PaddlePaddle/PaddleSeg#532]
按照动态图ReadMe里面的步骤操作，出现了这个错误

**Comment by michaelowenliu** [comment]
@deep-practice Hi, did you set PYTHONPATH?

**Comment by deep-practice** [comment]
Yes,just follow the readme.

**Comment by michaelowenliu** [comment]
> Yes,just follow the readme.

@deep-practice hi, could you provide the error log?

**Comment by deep-practice** [comment]
![8](https://user-images.githubusercontent.com/54052915/98463616-587a9780-21f7-11eb-8e4a-e492563e1b68.jpg)

**Comment by michaelowenliu** [comment]
@deep-practice Hi, thanks. Could you please provide the versions of python/paddle/OS? Then we can reproduce the issue easier.

**Comment by deep-practice** [comment]
OS:Ubuntu18.04
python:3.6.9
paddle:2.0rc
@michaelowenliu

**Comment by michaelowenliu** [comment]
@deep-practice  Hi, thanks, we have reproduced and resolved the issue with the same environment, where there is a little bit difference between py3.6 and 3.7. Please pull the updates.

**Comment by deep-practice** [comment]
Wow,I can use the pdseg dygraph version now.Thx.

**Comment by deep-practice** [comment]
L
![error](https://user-images.githubusercontent.com/54052915/98908306-2de05580-24fb-11eb-9111-9784509121ff.jpg)
加载HRNet48的预训练模型报错
@michaelowenliu

**Comment by deep-practice** [comment]
不加载预训练模型，又出现了内存错误
![error2](https://user-images.githubusercontent.com/54052915/98908752-dabad280-24fb-11eb-85bd-b591974f7363.jpg)

**Comment by michaelowenliu** [comment]
@deep-practice hi, how did you load the model or run the model?

**Comment by deep-practice** [comment]
python train.py --config config_file

**Comment by deep-practice** [comment]
The dataset reader is same as optic_disc_seg

**Comment by michaelowenliu** [comment]
> OS:Ubuntu18.04
> python:3.6.9
> paddle:2.0rc
> @michaelowenliu

@deep-practice Could you please update paddle to 2.0-rc? We have already localized the pretrain loading error that would be resolved by today, but you can use another way to load it, i.e. download the pretrained model manually, and specify the local path in the config file instead of using its url. As for memory issue, we have yet to reproduce it, does it occur every time? I guess it could be related to your local running environment. Anyway, we are still trying to figure out the problem.

**Comment by deep-practice** [comment]
my paddle version is 2.0-rc already

**Comment by deep-practice** [comment]
@michaelowenliu Any luck?

**Comment by deep-practice** [comment]
The latest version fix my problem.
