### ISSUE TITLE
在尝试第二种模型的时候报了这个错：W1101 09:57:19.773896  3228 build_strategy.cc:170] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU

### ISSUE THREAD

**Issue by shuhan666** [PaddlePaddle/PaddleSeg#534]
之前使用的是unet，昨晚想试试其他的，但是就报这个错了，不知道如何解决，麻烦啦

**Comment by nepeplwu** [comment]
@shuhan666 ，麻烦贴下完整的堆栈

**Comment by shuhan666** [comment]
> @shuhan666 ，麻烦贴下完整的堆栈

您是说这个吗？（对不起我啥也不太懂，很抱歉）

2020-11-02 14:54:04,619-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000040] in Optimizer will
 not take effect, and it will only be applied to other Parameters!
W1102 14:54:05.734200  4536 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.2, Runtime API Version: 10.0
W1102 14:54:05.807003  4536 device_context.cc:260] device: 0, cuDNN Version: 7.6.
[SKIP] Shape of pretrained weight ./pretrained_model/deeplabv3p_xception65_bn_coco//logit/weights doesn't match.(Pretrained: (21, 256, 1, 1), Actual: (2, 256, 1, 1))
[SKIP] Shape of pretrained weight ./pretrained_model/deeplabv3p_xception65_bn_coco//logit/biases doesn't match.(Pretrained: (21,), Actual: (2,))
2020-11-02 14:54:16,894-WARNING: ./pretrained_model/deeplabv3p_xception65_bn_coco/.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
There are 730/732 varaibles in ./pretrained_model/deeplabv3p_xception65_bn_coco/ are loaded.
Use multi-thread reader
W1102 14:54:20.667256  4536 build_strategy.cc:170] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.

**Comment by nepeplwu** [comment]
@shuhan666 `fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.`这个只是warning，不会影响训练

**Comment by shuhan666** [comment]
> @shuhan666 `fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.`这个只是warning，不会影响训练

我刚开始是报显存的不够的错，后来就直接警告完就结束运行了，我不太明白为啥我用cmd看显存是有的啊，但是就报错只有二十几m可用

**Comment by nepeplwu** [comment]
@shuhan666 ，报错只有二十几m可用，是因为paddle已经分配掉部分显存，在继续申请的时候，发现显存不足，才报了相关提示，可以试试把batch_size调小看看
