### ISSUE TITLE
padseg的损失计算

### ISSUE THREAD

**Issue by liguoyu666** [PaddlePaddle/PaddleSeg#540]
１、yml文件里：
`loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]`
这个coef是什么意思，代码里https://github.com/PaddlePaddle/PaddleSeg/blob/b9c4505398a4ff2a7009dc20f2987ba84c4b8580/dygraph/paddleseg/core/train.py#L34
的损失计算方式怎么理解，直接用个交叉熵不行吗？
２、我使用多卡训练，下面这几行是否需要取消注释：
https://github.com/PaddlePaddle/PaddleSeg/blob/062cebfb4baf8bae3a6fb90c03fbd780ba61a7da/dygraph/paddleseg/core/train.py#L117
https://github.com/PaddlePaddle/PaddleSeg/blob/062cebfb4baf8bae3a6fb90c03fbd780ba61a7da/dygraph/paddleseg/core/train.py#L119
https://github.com/PaddlePaddle/PaddleSeg/blob/062cebfb4baf8bae3a6fb90c03fbd780ba61a7da/dygraph/paddleseg/core/train.py#L132

**Comment by michaelowenliu** [comment]
@liguoyu666 Hi,

1. The coef weighs the multiple losses.

2. No, just keep it. The codes in comments were supported in the last Paddle version, and they would be deleted soon.

**Comment by liguoyu666** [comment]
> @liguoyu666 Hi,
> 
> 1. The coef weighs the multiple losses.
> 2. No, just keep it. The codes in comments were supported in the last Paddle version, and they would be deleted soon.

Thank you
