### ISSUE TITLE
AUG中的TO_RGB的作用

### ISSUE THREAD

**Issue by choimroc** [PaddlePaddle/PaddleSeg#544]
你好，请问进行数据增广时的TO_RGB参数有何作用呢？这个是在`deeplabv3p_resnet50_vd_cityscapes.yaml`中看到的。

**Comment by wuyefeilin** [comment]
三通道图像分为rgb和bgr两种格式，opencv读取的是bgr顺序，如果要转化成rgb可以通过将TO_RGB设置为True进行转换。

**Comment by choimroc** [comment]
@wuyefeilin 感谢你的答复！我发现了一个问题，我train的时候，TO_RGB是True；然后我进行eval的时候，如果TO_RGB改为False，iou就会低一点（例如0.3）；如果TO_RGB为True，则iou会高一点（例如 0.6）；所以这个属性是会影响到eval吗？

**Comment by wuyefeilin** [comment]
> @wuyefeilin 感谢你的答复！我发现了一个问题，我train的时候，TO_RGB是True；然后我进行eval的时候，如果TO_RGB改为False，iou就会低一点（例如0.3）；如果TO_RGB为True，则iou会高一点（例如 0.6）；所以这个属性是会影响到eval吗？

会的，train 和eval需要统一

**Comment by choimroc** [comment]
@wuyefeilin 谢谢你的耐心解答！
