### ISSUE TITLE
样本类数目

### ISSUE THREAD

**Issue by Charlie-Wilson0211** [PaddlePaddle/PaddleSeg#548]
CCF BDCI中训练
数据集样本类别数目为7，外加未标注
yaml文件中设置样本类数目为7，经训练，除了unet，deeplab、fast-scnn-pet、hrnet、训练后验证得到的第六个IOU全部为0，如下所示，请问是要把样本数目类别设置成8吗？如果不是，问题出在哪儿？
epoch 58:
[EVAL]#image=2919 acc=0.7806 IoU=0.3270
[EVAL]Category IoU: [0.0037 0.7376 0.6095 0.6840 0.0238 0.0000 0.2301]
[EVAL]Category Acc: [0.9298 0.7465 0.8857 0.8845 0.3000 0.0000 0.5866]
[EVAL]Kappa:0.6327

**Comment by wuyefeilin** [comment]
未标注是指要忽略的像素还是背景类， 如果时背景类应该把类别数设置为8， 如果是要忽略的像素（忽略像素的标注一般用255表示）则类别数为7。你现在未标注的标签时什么？
