### ISSUE TITLE
在进行deeplabv3+的时候，进行到PaddleSeg C++预测部署的时候，make后报出以下错误

### ISSUE THREAD

**Issue by eddieheyutong** [PaddlePaddle/PaddleSeg#55]
[ 92%] Linking CXX executable demo
/usr/bin/ld: 找不到 -lsnappystream
/usr/bin/ld: 找不到 -lsnappy
collect2: error: ld returned 1 exit status
CMakeFiles/demo.dir/build.make:131: recipe for target 'demo' failed
make[2]: *** [demo] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/demo.dir/all' failed
make[1]: *** [CMakeFiles/demo.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by eddieheyutong** [comment]
有大佬知道这个是什么原因吗

**Comment by arcral** [comment]
你不会看错误信息？找不到snappy库啊，你装一个不就完事了

**Comment by joey12300** [comment]
目前已修复了该链接错误，重新拉一下代码即可顺利编译：）
