### ISSUE TITLE
win10 可视化一直卡在输出VisualDL 2.0.4的地方

### ISSUE THREAD

**Issue by lyf6** [PaddlePaddle/PaddleSeg#551]

**Comment by ShenYuhan** [comment]
您的启动方式是怎么样的，打开浏览器是否能够看到页面呢

**Comment by lyf6** [comment]
感谢您的回复，我已经找到问题了，是我的使用方法不对。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ShenYuhan <notifications@github.com&gt;
发送时间: 2020年11月5日 10:49
收件人: PaddlePaddle/PaddleSeg <PaddleSeg@noreply.github.com&gt;
抄送: lyf6 <247820289@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[PaddlePaddle/PaddleSeg] win10 可视化一直卡在输出VisualDL 2.0.4的地方 (#551)





 
您的启动方式是怎么样的，打开浏览器是否能够看到页面呢
