### ISSUE TITLE
静态图如何不固定shape导出模型呢？

### ISSUE THREAD

**Issue by deep-practice** [PaddlePaddle/PaddleSeg#553]

**Comment by wuyefeilin** [comment]
可以在导出模型时将image_shape的h和w维改成-1
![image](https://user-images.githubusercontent.com/30919197/98496127-d4b6be80-227b-11eb-9686-e6d9568ed1ea.png)

**Comment by deep-practice** [comment]
改为-1之后报错
File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layers/nn.py", line 8653, in image_resize
    "Each dimension size given in out_shape must be greater than 0."
AssertionError: Each dimension size given in out_shape must be greater than 0.
