### ISSUE TITLE
在windows上使用vs2019进行cmake问题

### ISSUE THREAD

**Issue by gxqnba** [PaddlePaddle/PaddleSeg#555]
在模型导出以后，参照https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.7.0/deploy/cpp/docs/windows_vs2019_build.md
进行编译，使用cpu版本，报错如下：
![image](https://user-images.githubusercontent.com/61399616/98212884-370f7680-1f7f-11eb-85a5-9d90e057a6fc.png)
我的cmake设置如下：
![image](https://user-images.githubusercontent.com/61399616/98212993-61f9ca80-1f7f-11eb-9d95-c67713b0186f.png)

**Comment by gxqnba** [comment]
去掉CMAKE_BUILD_TYPE后面的钩选之后，前两个错误没有出现了，就剩下第三个错误

**Comment by Channingss** [comment]
@gxqnba 最近修复了Eigen报错的问题， 麻烦clone一下最新的代码
