### ISSUE TITLE
paddleseg的预训练模型支持finetune吗？

### ISSUE THREAD

**Issue by flyinggx** [PaddlePaddle/PaddleSeg#559]
想利用deeplabv3+模型分割遥感图像，要用到xception65等预训练模型，但是这些预训练模型都是基于公开数据集的，想尝试finetune提高模型精度，但是找了一圈发现没有接口可以进行finetune，希望官方后台解答，敬谢！

**Comment by michaelowenliu** [comment]
@flyinggx Hi, do you mean using the imagenet pretrained model into a new task?
