### ISSUE TITLE
Paddle Seg可以使用多gpu并行吗?

### ISSUE THREAD

**Issue by Rayaction** [PaddlePaddle/PaddleSeg#560]
看文档没找到，issue好像也没人问，如果有，请问怎么操作？

**Comment by Rayaction** [comment]
找到了

**Comment by yukang123** [comment]
麻烦请问是在哪里找到的呢？谢谢!

**Comment by Rayaction** [comment]
> 麻烦请问是在哪里找到的呢？谢谢!
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.8.0/docs/multiple_gpus_train_and_mixed_precision_train.md
