### ISSUE TITLE
能不能在参数设置里直接设置通道数，替换图像类型，这样就可以直接支持多通道的遥感数据了

### ISSUE THREAD

**Issue by lyf6** [PaddlePaddle/PaddleSeg#561]

**Comment by wuyefeilin** [comment]
pdseg里面只支持灰度图，rgb三通道图像和rgba四通道图像，不支持任意通道的要干图像。

如果要进行要干图像分割请参考：
https://github.com/PaddlePaddle/PaddleSeg/tree/release/v0.7.0/contrib/RemoteSensing

**Comment by lyf6** [comment]
请问遥感图像分割的这个可以直接用pdseg里面的导出和推断脚本来导出模型和做推断吗

**Comment by wuyefeilin** [comment]
如果通道数符合pdseg的要求，可以直接用pdseg直接训练导出和推断。用遥感图像分割训练，直接用pdseg导出的话应该会有问题的。
