### ISSUE TITLE
deeplabv3p训练时内存占用特别高

### ISSUE THREAD

**Issue by liguoyu666** [PaddlePaddle/PaddleSeg#562]
在AiStudio上用V100 32G的卡训练，模型为deeplabv3p_resnet50_vd_cityscapes，内存占用特别高，还是第一次遇到显存没占用完，内存反而溢出的，请问这种情况时候正常？
CPU：38.83%
内存：31.07GB/32GB
GPU：98%
显存：17.32GB/31.72GB

**Comment by wuyefeilin** [comment]
查看一下是否是其他程序占用了内存。麻烦给一下运行前后的内存占用情况

**Comment by liguoyu666** [comment]
> 查看一下是否是其他程序占用了内存。麻烦给一下运行前后的内存占用情况

我是在AIstudio平台上训练deeplabv3p，AIStudio就只运行了训练代码，也没其他东西，版本是1.8静态图。
![2020-11-09 11-21-08屏幕截图](https://user-images.githubusercontent.com/47743761/98497017-ee590580-227d-11eb-8c8e-984b083405d4.png)
![2020-11-09 11-21-37屏幕截图](https://user-images.githubusercontent.com/47743761/98497027-f2852300-227d-11eb-937d-7264051b9e62.png)

另外：还有２个问题请教下：
我再次训练时LOSS使用["softmax_loss", "lovasz_softmax_loss"]，比只使用softmax_loss训练时长翻了一倍，其余参数都没有改变，请问是否正常？
　
本地环境deeplabv3p使用eval.py测试时，报错
`Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at　(/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]
`
我查找问题发现很多报这个错误的，但都没给出个可靠的解决方法，我本地跑unet的eval.py没问题，路径设置也没问题。
报错信息如下：
`2020-11-09 11:28:47,873-WARNING: Your reader has raised an exception!

Exception in thread Thread-1:

Traceback (most recent call last):

  File "/home/lgy/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner

    self.run()

  File "/home/lgy/anaconda3/lib/python3.7/threading.py", line 865, in run

    self._target(*self._args, **self._kwargs)

  File "/home/lgy/anaconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1145, in __thread_main__

    six.reraise(*sys.exc_info())

  File "/home/lgy/anaconda3/lib/python3.7/site-packages/six.py", line 703, in reraise

    raise value

  File "/home/lgy/anaconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1125, in __thread_main__

    for tensors in self._tensor_reader():

  File "/home/lgy/anaconda3/lib/python3.7/site-packages/paddxingxile/fluid/data_feeder.py", line 196, in __call__

    for each_sample in self.generator():

  File "pdseg/eval.py", line 88, in data_generator

    for b in data_gen:

  File "/home/lgy/PycharmProjects/Paddle_Projects/PaddleSeg1.8/pdseg/reader.py", line 81, in generator

    yield self.process_image(line, self.data_dir, self.mode)

  File "/home/lgy/PycharmProjects/Paddle_Projects/PaddleSeg1.8/pdseg/reader.py", line 310, in process_image

    img, grt = aug.rand_crop(img, grt, mode=mode)

  File "/home/lgy/PycharmProjects/Paddle_Projects/PaddleSeg1.8/pdseg/data_aug.py", line 398, in rand_crop

    .format(crop_width, crop_height, img_width, img_height))

Exception: Crop size(256,256) must large than img size(512,512) when in EvalPhase.`


定位最后一行的报错信息，是在数据增强的def rand_crop(crop_img, crop_seg, mode=ModelPhase.TRAIN)里：

`    if not ModelPhase.is_train(mode):

        if (crop_height < img_height or crop_width < img_width):

            raise Exception(
                "Crop size({},{}) must large than img size({},{}) when in EvalPhase."
                .format(crop_width, crop_height, img_width, img_height))`

这里让我疑惑的是，非训练阶段时，crop_size必须大于img_size?难以理解该代码的意思，且我的img_size和crop_size均为256，报错信息里的img_size为512，也有点不对劲，代码本身应该是没有问题的，毕竟跑unet都很正常。

我把该段代码注释掉，能跑通eval.py，但是测试出来的miou很低，权重是在AIstudio上训练好下载下来的，在AIstudio上不是这么低。

**Comment by wuyefeilin** [comment]
1. 这是运行的内存消耗情况， 运行前的内存占用情况麻烦也给一下

3. 预测的时候 EVAL_CROP_SIZE必须比最大的宽和高大， 因为在eval的时候，是不能对图像进行crop的。

**Comment by LutaoChu** [comment]
“我再次训练时LOSS使用["softmax_loss", "lovasz_softmax_loss"]，比只使用softmax_loss训练时长翻了一倍，其余参数都没有改变，请问是否正常？”

-------------------------------
这是已知的问题，当图像尺寸和batch size较大的时候，静态图版本的lovasz loss耗时较多，减少图像尺寸和batch size可以缓解这个情况。
动态图版本的lovasz loss正在开发计划中，性能会有大幅提升，敬请期待！

**Comment by liguoyu666** [comment]
> 1. 这是运行的内存消耗情况， 运行前的内存占用情况麻烦也给一下
> 2. 预测的时候 EVAL_CROP_SIZE必须比最大的宽和高大， 因为在eval的时候，是不能对图像进行crop的。

1.运行前：
![2020-11-09 15-26-32屏幕截图](https://user-images.githubusercontent.com/47743761/98513199-79e48d80-22a2-11eb-8186-1282d85f1500.png)
![2020-11-09 15-34-21屏幕截图](https://user-images.githubusercontent.com/47743761/98513215-7ea94180-22a2-11eb-8348-9631405e1008.png)
运行后：
![2020-11-09 15-42-47屏幕截图](https://user-images.githubusercontent.com/47743761/98513235-849f2280-22a2-11eb-9876-be546fd77e71.png)
![2020-11-09 15-43-13屏幕截图](https://user-images.githubusercontent.com/47743761/98513255-8963d680-22a2-11eb-8013-dff568075e32.png)

2.eval_crop_size和img_size我找到问题所在了，我训练时把数据增强注释掉了部分，包括`    # FIX_RESIZE_SIZE: (2048, 1024) # (width, height), for unpadding`，而在eval和test时，要对img和label进行resize，
https://github.com/PaddlePaddle/PaddleSeg/blob/3bd44fff890b93f26389b82f8a8cbf42c9316964/pdseg/reader.py#L308-L315
此时会读取config.py里默认的resize大小
https://github.com/PaddlePaddle/PaddleSeg/blob/3bd44fff890b93f26389b82f8a8cbf42c9316964/pdseg/utils/config.py#L79
个人认为此处设置不是很好，毕竟有可能图片已经预处理为相同大小了，此时训练就不会使用padlle配置的数据增强里的resize，一旦注释掉就会导致后面eval跟test出错，建议推理时加个判断是否需要进行resize，或者在配置参数的yaml文件里，将增强的参数分成train和eval(test)。

**Comment by liguoyu666** [comment]
> “我再次训练时LOSS使用["softmax_loss", "lovasz_softmax_loss"]，比只使用softmax_loss训练时长翻了一倍，其余参数都没有改变，请问是否正常？”
> 
> 这是已知的问题，当图像尺寸和batch size较大的时候，静态图版本的lovasz loss耗时较多，减少图像尺寸和batch size可以缓解这个情况。
> 动态图版本的lovasz loss正在开发计划中，性能会有大幅提升，敬请期待！

谢谢

**Comment by wuyefeilin** [comment]
> > 1. 这是运行的内存消耗情况， 运行前的内存占用情况麻烦也给一下
> > 2. 预测的时候 EVAL_CROP_SIZE必须比最大的宽和高大， 因为在eval的时候，是不能对图像进行crop的。
> 
> 1.运行前：
> ![2020-11-09 15-26-32屏幕截图](https://user-images.githubusercontent.com/47743761/98513199-79e48d80-22a2-11eb-8186-1282d85f1500.png)
> ![2020-11-09 15-34-21屏幕截图](https://user-images.githubusercontent.com/47743761/98513215-7ea94180-22a2-11eb-8348-9631405e1008.png)
> 运行后：
> ![2020-11-09 15-42-47屏幕截图](https://user-images.githubusercontent.com/47743761/98513235-849f2280-22a2-11eb-9876-be546fd77e71.png)
> ![2020-11-09 15-43-13屏幕截图](https://user-images.githubusercontent.com/47743761/98513255-8963d680-22a2-11eb-8013-dff568075e32.png)
> 
> 2.eval_crop_size和img_size我找到问题所在了，我训练时把数据增强注释掉了部分，包括` # FIX_RESIZE_SIZE: (2048, 1024) # (width, height), for unpadding`，而在eval和test时，要对img和label进行resize，
> https://github.com/PaddlePaddle/PaddleSeg/blob/3bd44fff890b93f26389b82f8a8cbf42c9316964/pdseg/reader.py#L308-L315
> 
> 
> 此时会读取config.py里默认的resize大小
> https://github.com/PaddlePaddle/PaddleSeg/blob/3bd44fff890b93f26389b82f8a8cbf42c9316964/pdseg/utils/config.py#L79
> 
> 
> 个人认为此处设置不是很好，毕竟有可能图片已经预处理为相同大小了，此时训练就不会使用padlle配置的数据增强里的resize，一旦注释掉就会导致后面eval跟test出错，建议推理时加个判断是否需要进行resize，或者在配置参数的yaml文件里，将增强的参数分成train和eval(test)。

感谢你的反馈， 我们在动态图版本中已经进行了改善。

其他模型内存占用也会出现相似的情况吗， 还是只有deeplabv3p_resnet50_vd_cityscapes存在这种情况？

**Comment by liguoyu666** [comment]
> > > 1. 这是运行的内存消耗情况， 运行前的内存占用情况麻烦也给一下
> > > 2. 预测的时候 EVAL_CROP_SIZE必须比最大的宽和高大， 因为在eval的时候，是不能对图像进行crop的。
> > 
> > 
> > 1.运行前：
> > ![2020-11-09 15-26-32屏幕截图](https://user-images.githubusercontent.com/47743761/98513199-79e48d80-22a2-11eb-8186-1282d85f1500.png)
> > ![2020-11-09 15-34-21屏幕截图](https://user-images.githubusercontent.com/47743761/98513215-7ea94180-22a2-11eb-8348-9631405e1008.png)
> > 运行后：
> > ![2020-11-09 15-42-47屏幕截图](https://user-images.githubusercontent.com/47743761/98513235-849f2280-22a2-11eb-9876-be546fd77e71.png)
> > ![2020-11-09 15-43-13屏幕截图](https://user-images.githubusercontent.com/47743761/98513255-8963d680-22a2-11eb-8013-dff568075e32.png)
> > 2.eval_crop_size和img_size我找到问题所在了，我训练时把数据增强注释掉了部分，包括` # FIX_RESIZE_SIZE: (2048, 1024) # (width, height), for unpadding`，而在eval和test时，要对img和label进行resize，
> > https://github.com/PaddlePaddle/PaddleSeg/blob/3bd44fff890b93f26389b82f8a8cbf42c9316964/pdseg/reader.py#L308-L315
> > 
> > 此时会读取config.py里默认的resize大小
> > https://github.com/PaddlePaddle/PaddleSeg/blob/3bd44fff890b93f26389b82f8a8cbf42c9316964/pdseg/utils/config.py#L79
> > 
> > 个人认为此处设置不是很好，毕竟有可能图片已经预处理为相同大小了，此时训练就不会使用padlle配置的数据增强里的resize，一旦注释掉就会导致后面eval跟test出错，建议推理时加个判断是否需要进行resize，或者在配置参数的yaml文件里，将增强的参数分成train和eval(test)。
> 
> 感谢你的反馈， 我们在动态图版本中已经进行了改善。
> 
> 其他模型内存占用也会出现相似的情况吗， 还是只有deeplabv3p_resnet50_vd_cityscapes存在这种情况？

目前我用了pdseg的unet和deeplabv3p，unet训练时我把batch_size加到显存占用满，也没发生内存溢出的情况，具体多少就没注意了，而deeplabv3p就是图上所示，显存占用一半左右，内存就快爆了。

**Comment by wuyefeilin** [comment]
unet 和deeplab的batch_size 一样吗？ 

另外你的项目存一个版本， 地址给一下，我fork一下复现一下你的情况

**Comment by liguoyu666** [comment]
> unet 和deeplab的batch_size 一样吗？
> 
> 另外你的项目存一个版本， 地址给一下，我fork一下复现一下你的情况

我使用的是遥感影像地块分割baseline，[https://aistudio.baidu.com/aistudio/projectdetail/1090790](url)
unet和deeplabv3的batch_size都设置为80，用的32G显存的V100。我项目里文件数太多保存不了版本，解压后的数据集在里面
