### ISSUE TITLE
使用vs2019 编译paddleseg后，运行demo.exe报错不能读取config file ：deploy.yaml

### ISSUE THREAD

**Issue by gxqnba** [PaddlePaddle/PaddleSeg#564]
报错如下：

D:\Cmake_paddleseg\paddlepaddle-PaddleSeg-release-v0.7.0\PaddleSeg\deploy\out\Release>demo.exe --conf=D:\Cmake_paddleseg\freeze_model\deploy.yaml --input_dir=D:\Data\DataSet\crack\1
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1107 10:07:00.807379 15320 seg_predictor.cpp:22] Fail to load config file: [D:\Cmake_paddleseg\freeze_model\deploy.yaml]
*** Check failure stack trace: ***

D:\Cmake_paddleseg\freeze_model\deploy.yaml  该yaml路径已经核对，应该没问题

**Comment by Channingss** [comment]
@gxqnba 麻烦贴一下deploy.yaml的内容，应该是里面的配置出错了。

**Comment by gxqnba** [comment]
> @gxqnba 麻烦贴一下deploy.yaml的内容，应该是里面的配置出错了。
DEPLOY:
        USE_GPU : 1
        USE_PR : 0
        MODEL_PATH : "D:/Cmake_paddleseg/freeze_model"
        MODEL_FILENAME : "__model__"
        PARAMS_FILENAME : "__params__"
        EVAL_CROP_SIZE : (512, 512)
        MEAN : [0.5, 0.5, 0.5]
        STD : [0.5, 0.5, 0.5]
        IMAGE_TYPE : "rgb"
        NUM_CLASSES : 2
        CHANNELS : 3
        PRE_PROCESSOR : "SegPreProcessor"
        PREDICTOR_MODE : "NATIVE"
        BATCH_SIZE : 1

**Comment by gxqnba** [comment]
> @gxqnba 麻烦贴一下deploy.yaml的内容，应该是里面的配置出错了。
DEPLOY:
        USE_GPU : 1
        USE_PR : 0
        MODEL_PATH : "D:/Cmake_paddleseg/freeze_model"
        MODEL_FILENAME : "__model__"
        PARAMS_FILENAME : "__params__"
        EVAL_CROP_SIZE : (512, 512)
        MEAN : [0.5, 0.5, 0.5]
        STD : [0.5, 0.5, 0.5]
        IMAGE_TYPE : "rgb"
        NUM_CLASSES : 2
        CHANNELS : 3
        PRE_PROCESSOR : "SegPreProcessor"
        PREDICTOR_MODE : "NATIVE"
        BATCH_SIZE : 1
这是配置，用paddleseg里面的模型导出功能得到的，就修改了一下 MODEL_PATH : "D:/Cmake_paddleseg/freeze_model"和 PREDICTOR_MODE : "NATIVE"

**Comment by gxqnba** [comment]
> > @gxqnba 麻烦贴一下deploy.yaml的内容，应该是里面的配置出错了。
> > DEPLOY:
> > USE_GPU : 1
> > USE_PR : 0
> > MODEL_PATH : "D:/Cmake_paddleseg/freeze_model"
> > MODEL_FILENAME : "**model**"
> > PARAMS_FILENAME : "**params**"
> > EVAL_CROP_SIZE : (512, 512)
> > MEAN : [0.5, 0.5, 0.5]
> > STD : [0.5, 0.5, 0.5]
> > IMAGE_TYPE : "rgb"
> > NUM_CLASSES : 2
> > CHANNELS : 3
> > PRE_PROCESSOR : "SegPreProcessor"
> > PREDICTOR_MODE : "NATIVE"
> > BATCH_SIZE : 1
> > 这是配置，用paddleseg里面的模型导出功能得到的，就修改了一下 MODEL_PATH : "D:/Cmake_paddleseg/freeze_model"和 PREDICTOR_MODE : "NATIVE"

粘贴的格式有问题，我放截图吧。
![image](https://user-images.githubusercontent.com/61399616/98495540-4ee64380-227a-11eb-9b4c-a66ef03d3062.png)

**Comment by Channingss** [comment]
@gxqnba 好的，直接把文件发给我吧？我这边看能否直接复现。

**Comment by gxqnba** [comment]
> @gxqnba 好的，直接把文件发给我吧？我这边看能否直接复现。

我有试了一下，好像又可以了，真奇怪。麻烦您了！
另外想问一下，（1）我在编译生成的时候报错如下：
![image](https://user-images.githubusercontent.com/61399616/98497737-d71b1780-227f-11eb-9d7c-fc5c1d7ce234.png)

是不是把这句话注释掉就行了啊？会不会对预测造成什么不利影响？
![image](https://user-images.githubusercontent.com/61399616/98497800-147fa500-2280-11eb-8df6-06a13ee52de7.png)

**Comment by Channingss** [comment]
@gxqnba 您是编译的时候报错了：
![image](https://user-images.githubusercontent.com/12471701/98497958-8821b200-2280-11eb-99a3-db94dd21f893.png)
然后注释掉了下面的代码，然后就不报错了吧？能成功run吗？
![image](https://user-images.githubusercontent.com/12471701/98498009-a4bdea00-2280-11eb-9d50-9f4c96206d34.png)

**Comment by gxqnba** [comment]
可以run成功。

**Comment by Channingss** [comment]
@gxqnba 好的，可以就行

**Comment by gxqnba** [comment]
> @gxqnba 好的，可以就行

好的，谢谢了！
