### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by 642721838** [PaddlePaddle/PaddleSeg#565]
老师您好，我的paddle是按装的windows GPU版本，而且GPU 是RTX3090，但是在paddleseg模型训练的时候GPU调用不起来，一直没有反应。请问应该怎么解决

**Comment by Rayaction** [comment]
咨询：RTX3090哪里买的多少钱哇，我也想买。RTX3080疯狂涨价，“但是在paddleseg模型训练的时候GPU调用不起来”--有没有export CUDA_VISIBLE_DEVICES=0

**Comment by 642721838** [comment]
老师您好，我们也是刚刚才买的，通过电脑供应商采购的，不过现在3090京东好像降价了。另外一个问题就是我export CUDA_VISIBLE_DEVICES=0后提示我export是外部命令，不认，然后我百度了，说windows是set CUDA_VISIBLE_DEVICES=0，输入到是认了，但是GPU还是调用不起来




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月8日(星期天) 下午4:50
收件人:&nbsp;"PaddlePaddle/PaddleSeg"<PaddleSeg@noreply.github.com&gt;;
抄送:&nbsp;"棉花糖"<642721838@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] 咨询 (#565)





 
咨询：RTX3090哪里买的多少钱哇，我也想买。RTX3080疯狂涨价，“但是在paddleseg模型训练的时候GPU调用不起来”--有没有export CUDA_VISIBLE_DEVICES=0

**Comment by wuyefeilin** [comment]
你好，麻烦你贴一下具体错误。
另外你在安装完paddle的时候， 按照如下方式运行一下是否安装成功
![image](https://user-images.githubusercontent.com/30919197/98496947-bf429400-227d-11eb-9bad-63fcd1205eab.png)
具体安装教程请参考：https://www.paddlepaddle.org.cn/install/quick/zh/2.0rc-windows-pip

**Comment by Rayaction** [comment]
> 你好，麻烦你贴一下具体错误。
> 另外你在安装完paddle的时候， 按照如下方式运行一下是否安装成功
> ![image](https://user-images.githubusercontent.com/30919197/98496947-bf429400-227d-11eb-9bad-63fcd1205eab.png)
> 具体安装教程请参考：https://www.paddlepaddle.org.cn/install/quick/zh/2.0rc-windows-pip

可否看下我的问题，加载预训练模型出现shape不对，最新的issues

**Comment by 642721838** [comment]
老师您好，我安装paddle完了验证的时候一直是正在验证，没有出现安装成功的提示，请问怎么解决啊。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月9日(星期一) 中午11:25
收件人:&nbsp;"PaddlePaddle/PaddleSeg"<PaddleSeg@noreply.github.com&gt;;
抄送:&nbsp;"棉花糖"<642721838@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] 咨询 (#565)





  
你好，麻烦你贴一下具体错误。
 另外你在安装完paddle的时候， 按照如下方式运行一下是否安装成功
 
 具体安装教程请参考：https://www.paddlepaddle.org.cn/install/quick/zh/2.0rc-windows-pip
  
可否看下我的问题，加载预训练模型出现shape不对，最新的issues

**Comment by wuyefeilin** [comment]
> 老师您好，我安装paddle完了验证的时候一直是正在验证，没有出现安装成功的提示，请问怎么解决啊。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddlePaddle/PaddleSeg" <notifications@github.com&gt;; 发送时间:&nbsp;2020年11月9日(星期一) 中午11:25 收件人:&nbsp;"PaddlePaddle/PaddleSeg"<PaddleSeg@noreply.github.com&gt;; 抄送:&nbsp;"棉花糖"<642721838@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] 咨询 (#565) 你好，麻烦你贴一下具体错误。 另外你在安装完paddle的时候， 按照如下方式运行一下是否安装成功 具体安装教程请参考：https://www.paddlepaddle.org.cn/install/quick/zh/2.0rc-windows-pip 可否看下我的问题，加载预训练模型出现shape不对，最新的issues — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

安装问题的话可以到Paddle repo提issue问一下哈。https://github.com/PaddlePaddle/Paddle
