### ISSUE TITLE
无法加载pretrained model

### ISSUE THREAD

**Issue by Rayaction** [PaddlePaddle/PaddleSeg#567]
利用官方提供代码python pretrained_model/download_model.py unet_bn_coco下载的预训练模型
Downloading unet_coco_v3.tgz
[==================================================] 100.00%
Uncompress unet_coco_v3.tgz
[==================================================] 100.00%
Pretrained Model download success!
训练时
[SKIP] Shape of pretrained weight ./pretrained_model/unet_bn_coco//logit/weights doesn't match.(Pretrained: (21, 64, 3, 3), Actual: (7, 64, 3, 3))
2020-11-09 10:18:58,182-WARNING: ./pretrained_model/unet_bn_coco/.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
这个是哪里的shape对不上？

**Comment by wuyefeilin** [comment]
因为类别数不一致，最后ligit的参数没有加载成功是正常的。

**Comment by Rayaction** [comment]
> 因为类别数不一致，最后ligit的参数没有加载成功是正常的。

了解了。thx!

**Comment by Rayaction** [comment]
> 因为类别数不一致，最后ligit的参数没有加载成功是正常的。想修改最后的分类数，但是from utils.load_model_utils import load_pretrained_weights没找到这个utils在哪。无法跳转，请问有什么方法修改吗

**Comment by Rayaction** [comment]
> 因为类别数不一致，最后ligit的参数没有加载成功是正常的。

因为类别数不一致，最后ligit的参数没有加载成功是正常的。想修改最后的分类数，但是from utils.load_model_utils import load_pretrained_weights没找到这个utils在哪。无法跳转，请问有什么方法修改吗
