### ISSUE TITLE
在进行C++预测库部署的时候，进行到编译这步的时候make后报错，这个错误是什么原因

### ISSUE THREAD

**Issue by eddieheyutong** [PaddlePaddle/PaddleSeg#57]
本人系统为ubuntu18.04 GCC/G++版本为4.8.5 CUDA版本为10.0，opencv编译没有问题，就是生成可执行文件的时每次make到最后的时候会报以下的错误：
[ 92%] Linking CXX executable demo
/root/projects/opencv3/lib64/libopencv_core.a(hal_internal.cpp.o)：在函数‘lapack_QR32f(float*, unsigned long, int, int, int, float*, unsigned long, float*, int*)’中：
hal_internal.cpp:(.text._Z12lapack_QR32fPfmiiiS_mS_Pi+0x250)：对‘sgels_’未定义的引用
hal_internal.cpp:(.text._Z12lapack_QR32fPfmiiiS_mS_Pi+0x2bc)：对‘sgels_’未定义的引用
hal_internal.cpp:(.text._Z12lapack_QR32fPfmiiiS_mS_Pi+0x6e9)：对‘sgels_’未定义的引用
hal_internal.cpp:(.text._Z12lapack_QR32fPfmiiiS_mS_Pi+0x751)：对‘sgels_’未定义的引用
/root/projects/opencv3/lib64/libopencv_core.a(hal_internal.cpp.o)：在函数‘lapack_QR64f(double*, unsigned long, int, int, int, double*, unsigned long, double*, int*)’中：
hal_internal.cpp:(.text._Z12lapack_QR64fPdmiiiS_mS_Pi+0x295)：对‘dgels_’未定义的引用
hal_internal.cpp:(.text._Z12lapack_QR64fPdmiiiS_mS_Pi+0x325)：对‘dgels_’未定义的引用
hal_internal.cpp:(.text._Z12lapack_QR64fPdmiiiS_mS_Pi+0x5ee)：对‘sgels_’未定义的引用
hal_internal.cpp:(.text._Z12lapack_QR64fPdmiiiS_mS_Pi+0x63e)：对‘sgels_’未定义的引用
hal_internal.cpp:(.text._Z12lapack_QR64fPdmiiiS_mS_Pi+0x8de)：对‘dgels_’未定义的引用
hal_internal.cpp:(.text._Z12lapack_QR64fPdmiiiS_mS_Pi+0x96f)：对‘dgels_’未定义的引用
hal_internal.cpp:(.text._Z12lapack_QR64fPdmiiiS_mS_Pi+0xb14)：对‘sgels_’未定义的引用
hal_internal.cpp:(.text._Z12lapack_QR64fPdmiiiS_mS_Pi+0xb64)：对‘sgels_’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/demo.dir/build.make:131: recipe for target 'demo' failed
make[2]: *** [demo] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/demo.dir/all' failed
make[1]: *** [CMakeFiles/demo.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by joey12300** [comment]
可以试试用以下命令编译opencv。
```
cmake .. -DCMAKE_INSTALL_PREFIX=/root/projects/opencv3 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DWITH_ZLIB=ON -DBUILD_ZLIB=ON -DWITH_JPEG=ON -DBUILD_JPEG=ON -DWITH_PNG=ON -DBUILD_PNG=ON -DWITH_TIFF=ON -DBUILD_TIFF=ON -DWITH_IPP=OFF -DBUILD_IPP_IW=OFF -DWITH_LAPACK=OFF -DWITH_EIGEN=OFF -DCMAKE_INSTALL_LIBDIR=lib64
```
之后会在文档中更新这个命令，谢谢反馈！ ：）
