### ISSUE TITLE
Inference speed difference on mobile device

### ISSUE THREAD

**Issue by sadknight0001** [PaddlePaddle/PaddleSeg#572]
Hi
I just tested the pretrained model and custom model (deeolabv3+, mobilenet V2, more classes) deployed on mobile device, it seems two-class model is much faster than multi-class model(about two times). Is it normal? Is there anything that can speed up the inference, like pruning or other tricks?
Thanks in advance

**Comment by michaelowenliu** [comment]
@sadknight0001 Hi, did you use Human Seg? Theoretically, there is no gap between the two-class model and multi-class model, since the computation complexity is almost the same. What is your model deployment pipeline?

**Comment by sadknight0001** [comment]
@michaelowenliu Thank you for the reply. It's strange and really makes me confused
1. Humanseg pretrained quant model is about 178ms(HRnet w18 input 192, 1 thread), and finetuned quant multi class model(input 256, 1 thread) needs more than 500ms, multi class model with 192 input requires 300ms. I also tested mobilenetv2 with same input(257) for two class and multi class, which cost about 270ms and 500+ms respectively
2. The pipeline is based on the tool opt_linux. Train, export and opt for arm.

**Comment by michaelowenliu** [comment]
@sadknight0001 Hi, how did you finetune quant multi-class model? Did you quantize the model after the training?

**Comment by sadknight0001** [comment]
@michaelowenliu 
For HumanSeg project and HRnet model ,yes. Load the pretrained model, train, quant_online and export. Basically only the dataset config was changed
For mobilenet model, no quantization is applied
