### ISSUE TITLE
DeepLabv3+模型使用教程下载的模型无法加载

### ISSUE THREAD

**Issue by Rayaction** [PaddlePaddle/PaddleSeg#574]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.7.0/tutorial/finetune_deeplabv3plus.md
这个里面用python pretrained_model/download_model.py deeplabv3p_xception65_bn_coco
下载下来的模型文件夹目录结构好像不能加载，
跑train的时候提示SKIP] Pretrained weight ./pretrained_model/deeplab_mobilenet_x1_0_coco/xception_65/entry_flow/conv1/weights doesn't exist
而下载下来的目录结构没有没有文件夹，都是一个个的conv1_1_bn_mean这种的文件，加载的时候就找不到。请问怎么解决？

**Comment by nepeplwu** [comment]
@Rayaction ` ./pretrained_model/deeplab_mobilenet_x1_0_coco/xception_65/entry_flow/conv1/weights`，麻烦检查下配置中的TRAIN.PRETRAINED_MODEL_DIR是否配置错误了

**Comment by Rayaction** [comment]
> @Rayaction ` ./pretrained_model/deeplab_mobilenet_x1_0_coco/xception_65/entry_flow/conv1/weights`，麻烦检查下配置中的TRAIN.PRETRAINED_MODEL_DIR是否配置错误了
yaml的配置：
PRETRAINED_MODEL_DIR: "./pretrained_model/deeplab_mobilenet_x1_0_coco"

下载下来的位置：
PaddleSeg/pretrained_model/deeplab_mobilenet_x1_0_coco

因为train在PaddleSeg下，所以./不会错。这个之前load unet成功过
主要的问题是，貌似多了点前缀dir，down下来的模型文件夹里没有什么目录层级

**Comment by nepeplwu** [comment]
@Rayaction 看你下载的预训练模型是deeplab_mobilenet_x1_0，但是训练时提示的是xception的参数没加载到，你配置的模型参数MODEL.DEEPLAB.BACKBONE是xception吗？如果是的话，那就是配置和预训练模型对不上导致的

**Comment by Rayaction** [comment]
> @Rayaction 看你下载的预训练模型是deeplab_mobilenet_x1_0，但是训练时提示的是xception的参数没加载到，你配置的模型参数MODEL.DEEPLAB.BACKBONE是xception吗？如果是的话，那就是配置和预训练模型对不上导致的

刚看到，我修改下试试
it works~ thx bro！
