### ISSUE TITLE
模型训练完，评估时，IoU的数值很低，只有0.23多

### ISSUE THREAD

**Issue by Beibarton** [PaddlePaddle/PaddleSeg#579]
开始训练模型，使用下面语句：
# 指定GPU卡号（以0号卡为例）
export CUDA_VISIBLE_DEVICES=0
# 训练
python work/pdseg/train.py --use_gpu --cfg work/PaddleSeg/configs/deeplabv3p_resnet50_vd_cityscapes.yaml

模型评估使用下面语句：
!python work/PaddleSeg/pdseg/eval.py --use_gpu --cfg work/PaddleSeg/configs/deeplabv3p_resnet50_vd_cityscapes.yaml

评估结果：
[EVAL]#image=2919 acc=0.9116 IoU=0.2399
[EVAL]Category IoU: [0.7778 0.8772 0.8416 0.9095 0.2639 0.2408 0.6473 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000]
[EVAL]Category Acc: [0.8641 0.9266 0.9168 0.9540 0.6009 0.6139 0.7644 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000]
[EVAL]Kappa:0.8661

**Comment by michaelowenliu** [comment]
@Beibarton Hi, could you please provide your running environment, e.g. paddle/paddleSeg version? Actually, your iou is not very low, since there are extra classes.
