### ISSUE TITLE
问一下与 VisualDL 的集成度

### ISSUE THREAD

**Issue by iceriver97** [PaddlePaddle/PaddleSeg#581]
PaddleSeg 目前是不是只在 train.py 和 vis.py 添加了 VisualDL 的 Scalar 和 Image ? 其他功能都没有集成是吧？
比如说，我想查看图像增强的过程，是不是要自己添加到代码里？

**Comment by michaelowenliu** [comment]
@iceriver97 Hi, yes, so far if you need additional information, you should add them by yourself. The VDL usage refers to https://github.com/PaddlePaddle/VisualDL

**Comment by iceriver97** [comment]
> @iceriver97 Hi, yes, so far if you need additional information, you should add them by yourself. The VDL usage refers to https://github.com/PaddlePaddle/VisualDL

好的，谢谢，我正在尝试做

**Comment by iceriver97** [comment]
我遇到了一点问题，我把 data_loader 改为 iterable=True，然后在 train.py 中 通过`for data in data_loader:`
试图取出我的想要的图片时，会**循环**报以下的错误，我不是很明白问题在哪里，报错信息中的提示应该是不对的，我检查了 drop_last，他的默认值是 true 我并没有将其设置为 false；当我使用GPU训练的时候一切正常；可能是与 device num 有关系？ AIStudio的CPU_NUM=4，我还需要修改哪里呢？

```
--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::framework::ParallelExecutor::FeedTensorsIntoLocalScopes(std::vector<std::unordered_map<std::string, paddle::framework::LoDTensor, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, paddle::framework::LoDTensor> > >, std::allocator<std::unordered_map<std::string, paddle::framework::LoDTensor, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, paddle::framework::LoDTensor> > > > > const&)

----------------------
Error Message Summary:
----------------------
UnimplementedError: The feed data number 1 does not match the device number 4. If you are using DataLoader to feed data, this may be because you set drop_last=False in training network. Currently, drop_last=False for DataLoader is not supported for training network. Please set drop_last=True when defining DataLoader.
  [Hint: Expected tensors.size() == member_->local_scopes_.size(), but received tensors.size():1 != member_->local_scopes_.size():4.] at (/paddle/paddle/fluid/framework/parallel_executor.cc:852)
```

**Comment by iceriver97** [comment]
> @iceriver97 Hi, yes, so far if you need additional information, you should add them by yourself. The VDL usage refers to https://github.com/PaddlePaddle/VisualDL

我这样能得到数据吗？为什么我将得到的数据保存下来，看到的是空文件？
```
for data in data_loader():                
     img = np.array(data[0]['image'])[0]
     cv2.imwrite('./test.jpg', img)
```

**Comment by michaelowenliu** [comment]
@iceriver97 Hi,  could you try it in the following way?

```
img = data[0][0]
img = img.numpy()
img = np.transpose(img, (1, 2, 0))
cv2.imwrite("test.jpg", img)
````

**Comment by iceriver97** [comment]
> @iceriver97 Hi, could you try it in the following way?
> 
> ```
> img = data[0][0]
> img = img.numpy()
> img = np.transpose(img, (1, 2, 0))
> cv2.imwrite("test.jpg", img)
> ```

谢谢，但是 data[0] 是一个字典，我将其信息打印了一下，同时我按照 Key='image'将其取了出来，打印了其类型，data[0]['image']的值都是负的，这是怎么回事啊？
```
data[0]:
{'mask': <paddle.fluid.core_avx.LoDTensor object at 0x7f61993dad30>, 'label': <paddle.fluid.core_avx.LoDTensor object at 0x7f61992c1df0>, 'image': <paddle.fluid.core_avx.LoDTensor object at 0x7f61992c1ef0>}

type(data[0]["image"]):
<class 'paddle.fluid.core_avx.LoDTensor'>
```

**Comment by michaelowenliu** [comment]
@iceriver97 Hi, sorry, the example I provided above is a dynamic version. Have you tried the new version?

**Comment by iceriver97** [comment]
> @iceriver97 Hi, sorry, the example I provided above is a dynamic version. Have you tried the new version?

因为是想利用 PaddleSeg + VisualDL，利用 VDL-image 功能查看数据增强过程，使用VDL-Graph、VDL-Histogram，来辅助网络结构的设计，做一个完整的项目出来，但是VDL-Graph好像还不支持动态图版本？

**Comment by michaelowenliu** [comment]
@iceriver97 Yes, VDL-Graph has yet yo support the new version. As for dataloader usage in the static graph, could you refer to the official document? https://paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/DataLoader_cn.html#dataloader

**Comment by iceriver97** [comment]
> @ iceriver97是的，VDL-Graph尚未支持新版本。至于静态图中数据加载器的用法，您可以参考官方文档吗？https://paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/DataLoader_cn.html#dataloader

好的，我之前就是根据这个文档进行修改的，我再好好看看文档；

**Comment by iceriver97** [comment]
> @iceriver97 Yes, VDL-Graph has yet yo support the new version. As for dataloader usage in the static graph, could you refer to the official document? https://paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/DataLoader_cn.html#dataloader

我在 pdseg/reader.py 中没看到 self.reader 的定义， batch_reader()函数调用了 batch()函数，而batch()函数已经将返回格式固定死了，我想知道哪里调用了 batch_reader()？

**Comment by iceriver97** [comment]
> @iceriver97 Yes, VDL-Graph has yet yo support the new version. As for dataloader usage in the static graph, could you refer to the official document? https://paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/DataLoader_cn.html#dataloader

PaddleSeg 在哪里做了处理吗？固定返回这样一个字典？
`{'mask': <paddle.fluid.core_avx.LoDTensor object at 0x7f61993dad30>, 'label': <paddle.fluid.core_avx.LoDTensor object at 0x7f61992c1df0>, 'image': <paddle.fluid.core_avx.LoDTensor object at 0x7f61992c1ef0>}`

**Comment by iceriver97** [comment]
> @iceriver97 Yes, VDL-Graph has yet yo support the new version. As for dataloader usage in the static graph, could you refer to the official document? https://paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/DataLoader_cn.html#dataloader

我在 reader 读取的过程中，抽取十张图片记录后，进行了return; 有时候会正常结束，有时候会报下面的错误，这是因为什么呢？
```
terminate called without an active exception
W1116 15:11:23.310771 14131 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1116 15:11:23.310803 14131 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1116 15:11:23.310806 14131 init.cc:231] The detail failure signal is:

W1116 15:11:23.310822 14131 init.cc:234] *** Aborted at 1605510683 (unix time) try "date -d @1605510683" if you are using GNU date ***
W1116 15:11:23.312394 14131 init.cc:234] PC: @                0x0 (unknown)
W1116 15:11:23.312590 14131 init.cc:234] *** SIGABRT (@0x3e8000036f4) received by PID 14068 (TID 0x7f5783043700) from PID 14068; stack trace: ***
W1116 15:11:23.313650 14131 init.cc:234]     @     0x7f580846e390 (unknown)
W1116 15:11:23.314654 14131 init.cc:234]     @     0x7f58080c8428 gsignal
W1116 15:11:23.315614 14131 init.cc:234]     @     0x7f58080ca02a abort
W1116 15:11:23.316274 14131 init.cc:234]     @     0x7f57c8e4684a __gnu_cxx::__verbose_terminate_handler()
W1116 15:11:23.316804 14131 init.cc:234]     @     0x7f57c8e44f47 __cxxabiv1::__terminate()
W1116 15:11:23.317417 14131 init.cc:234]     @     0x7f57c8e44f7d std::terminate()
W1116 15:11:23.317996 14131 init.cc:234]     @     0x7f57c8e44c5a __gxx_personality_v0
W1116 15:11:23.318504 14131 init.cc:234]     @     0x7f57c9137b97 _Unwind_ForcedUnwind_Phase2
W1116 15:11:23.318998 14131 init.cc:234]     @     0x7f57c9137e7d _Unwind_ForcedUnwind
W1116 15:11:23.319978 14131 init.cc:234]     @     0x7f580846d070 __GI___pthread_unwind
W1116 15:11:23.320924 14131 init.cc:234]     @     0x7f5808465845 __pthread_exit
W1116 15:11:23.321166 14131 init.cc:234]     @     0x5579687a9e59 PyThread_exit_thread
W1116 15:11:23.321241 14131 init.cc:234]     @     0x55796862fc17 PyEval_RestoreThread.cold.798
W1116 15:11:23.321859 14131 init.cc:234]     @     0x7f57e3d0d29c (unknown)
W1116 15:11:23.322119 14131 init.cc:234]     @     0x55796872b744 _PyMethodDef_RawFastCallKeywords
W1116 15:11:23.322463 14131 init.cc:234]     @     0x55796872b861 _PyCFunction_FastCallKeywords
W1116 15:11:23.322705 14131 init.cc:234]     @     0x5579687972bd _PyEval_EvalFrameDefault
W1116 15:11:23.323035 14131 init.cc:234]     @     0x5579686db539 _PyEval_EvalCodeWithName
W1116 15:11:23.323356 14131 init.cc:234]     @     0x55796872aef5 _PyFunction_FastCallKeywords
W1116 15:11:23.323590 14131 init.cc:234]     @     0x557968792806 _PyEval_EvalFrameDefault
W1116 15:11:23.323791 14131 init.cc:234]     @     0x5579686db539 _PyEval_EvalCodeWithName
W1116 15:11:23.323992 14131 init.cc:234]     @     0x55796872af57 _PyFunction_FastCallKeywords
W1116 15:11:23.324209 14131 init.cc:234]     @     0x5579687938cc _PyEval_EvalFrameDefault
W1116 15:11:23.324396 14131 init.cc:234]     @     0x55796872accb _PyFunction_FastCallKeywords
W1116 15:11:23.324612 14131 init.cc:234]     @     0x557968792a93 _PyEval_EvalFrameDefault
W1116 15:11:23.324723 14131 init.cc:234]     @     0x557968733b31 gen_send_ex
W1116 15:11:23.324944 14131 init.cc:234]     @     0x557968792e36 _PyEval_EvalFrameDefault
W1116 15:11:23.325053 14131 init.cc:234]     @     0x557968733b31 gen_send_ex
W1116 15:11:23.325271 14131 init.cc:234]     @     0x557968792e36 _PyEval_EvalFrameDefault
W1116 15:11:23.325381 14131 init.cc:234]     @     0x557968733b31 gen_send_ex
W1116 15:11:23.325609 14131 init.cc:234]     @     0x557968792e36 _PyEval_EvalFrameDefault
W1116 15:11:23.325825 14131 init.cc:234]     @     0x5579686db81a _PyEval_EvalCodeWithName
```
这种报错有办法避免吗？

**Comment by michaelowenliu** [comment]
@iceriver97 hi, are there a few "dirty" images unexpectedly?

**Comment by iceriver97** [comment]
@michaelowenliu  应该是没有脏数据，这个数据集已经用来训练很多次了，报这种错误的场景是：
首先我遍历reader : `for data in data_loader`，然后取出了我想要的图片，达到一定数量之后，我直接在这个循环中return了，有时候就会报这种错误，但有时侯会正常结束；

**Comment by michaelowenliu** [comment]
@iceriver97 Hi, could you please provide a minimum code clip that helps us reproduce the error?

**Comment by iceriver97** [comment]
将压缩包中的visualize_Seg_transform.py 放到 pdseg 目录下，
我在 reader 的 __init__  中定义了一个变量 self.old_img =None,在每次Normalize之前进行值的更新：self.old_img = img;
同时定义了一个函数，来返回self.old_img

```
def pass_img_to_vdl(self):
        return self.old_img
```
压缩包中也放了修改后的 reader，注意我修改了 model_build 中的reader 为可迭代的；
[code.zip](https://github.com/PaddlePaddle/PaddleSeg/files/5545445/code.zip)

**Comment by iceriver97** [comment]
@michaelowenliu 我还想问您一下，Seg对图像做完增强处理，原图还会用来训练吗？是不是仅用增强后的图片呢？一张图像，经过我的一系列增强操作后，最后是一张图像用于训练还是两张？

**Comment by michaelowenliu** [comment]
@iceriver97 Hi, thanks. I got the same error with your code. The error is related to resource release when dataloader is not finished. For your another question, Seg would train on the augmented image.

**Comment by iceriver97** [comment]
> @iceriver97 Hi, thanks. I got the same error with your code. The error is related to resource release when dataloader is not finished.

非常感谢您的帮助。我是否有办法避免报此类错误？

**Comment by michaelowenliu** [comment]
@iceriver97 hi, do not break the for loop intermediately, instead, traverse the dataloader to the end.

**Comment by iceriver97** [comment]
> @iceriver97 hi, do not break the for loop intermediately, instead, traverse the dataloader to the end.

好的，了解了；非常感谢；关于图像增强的问题，为什么原图不再用于训练了呢？如果我想用增强后的图像与原图一同作为训练集，会有所帮助吗？比如我利用上面的程序得到一系列增强后的图片，然后加入训练集；

**Comment by michaelowenliu** [comment]
@iceriver97 hi, since the question might not be answered clearly here, you better refer to basic data augmentation knowledge, and then it would become clear on the mechanism.

**Comment by iceriver97** [comment]
> @iceriver97 hi, since the question might not be answered clearly here, you better refer to basic data augmentation knowledge, and then it would become clear on the mechanism.

好的，谢谢
