### ISSUE TITLE
使用paddleSeg里的cityscape_fast_scnn.yamlGPU利用率很低

### ISSUE THREAD

**Issue by Fly-hub** [PaddlePaddle/PaddleSeg#582]
使用paddleSeg里的cityscape_fast_scnn.yaml，GPU利用率很低，batch_size是32，显存利用率50%多，但是GPU利用率只有不到5%.尝试过在yaml文件里更改DATALOADER:  NUM_WORKERS: 320  BUF_SIZE: 2560，但是没有一点作用

**Comment by michaelowenliu** [comment]
@Fly-hub Hi, Fast SCNN is a small model, the performance bottleneck is the image I/O operation but no GPU utilization, i.e. GPU is waiting for image inputs.

**Comment by Fly-hub** [comment]
> @Fly集线器嗨， 快速 SCNN 是一个小模型， 性能瓶颈是图像 I/ O 操作， 但没有 GPU 利用率， 即 GPU 正在等待图像输入。

那有没有什么办法提高GPU利用率呀

**Comment by michaelowenliu** [comment]
@Fly-hub hi, that's not a GPU problem. You could try a smaller batch size, e.g. 8 or 16.

**Comment by kymoran3169** [comment]
reader的数据增强被打开了，关掉就行了，就是下面这个东西。
# RichCrop数据增广开关，用于提升模型鲁棒性
cfg.AUG.RICH_CROP.ENABLE = False

**Comment by kymoran3169** [comment]
可以的话，调用训练命令的时候把--use_mpio 打开，效果加倍
