### ISSUE TITLE
每个epoch训练完都会报错，Error Message Summary: Error: Blocking queue is killed because the data reader raises an exception

### ISSUE THREAD

**Issue by maxuetao** [PaddlePaddle/PaddleSeg#583]
paddle1.8，paddleseg0.7，用默认的配置文件训练ORCNet模型，每个epoch训练完都会报错。求解，报错如下：
----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]
W1115 22:32:03.203456 24562 operator.cc:187] read raises an exception std::future_error, No associated state
F1115 22:32:03.203572 24562 exception_holder.h:37] std::exception caught, No associated state
*** Check failure stack trace: ***
    @     0x7f1b36c368ad  google::LogMessage::Fail()
    @     0x7f1b36c3a35c  google::LogMessage::SendToLog()
    @     0x7f1b36c363d3  google::LogMessage::Flush()
    @     0x7f1b36c3b86e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f1b39e21928  paddle::framework::details::ExceptionHolder::Catch()
    @     0x7f1b39ebecce  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync()
    @     0x7f1b39eb94b4  paddle::framework::details::FastThreadedSSAGraphExecutor::RunTracedOps()
    @     0x7f1b39ebd8f3  paddle::framework::details::FastThreadedSSAGraphExecutor::Run()
    @     0x7f1b39e12e5c  _ZZN6paddle9framework7details29ScopeBufferedSSAGraphExecutor3RunERKSt6vectorISsSaISsEEbENKUlvE_clEv
    @     0x7f1b39e173c4  paddle::framework::details::ScopeBufferedMonitor::Apply()
    @     0x7f1b39e13a94  paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run()
    @     0x7f1b36cfd78d  paddle::framework::ParallelExecutor::Run()
    @     0x7f1b3696f7b7  _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL22pybind11_init_core_avxERNS_6moduleEEUlRNS2_9framework16ParallelExecutorERKSt6vectorISsSaISsEEbE210_NS_6objectEIS8_SD_bEINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESW_
    @     0x7f1b369bc5d9  pybind11::cpp_function::dispatcher()
    @     0x564c2ae38fc4  _PyMethodDef_RawFastCallKeywords
    @     0x564c2ae390e1  _PyCFunction_FastCallKeywords
    @     0x564c2ae956b2  _PyEval_EvalFrameDefault
    @     0x564c2add6059  _PyEval_EvalCodeWithName
    @     0x564c2ae38307  _PyFunction_FastCallKeywords
    @     0x564c2ae91841  _PyEval_EvalFrameDefault
    @     0x564c2add6059  _PyEval_EvalCodeWithName
    @     0x564c2ae38307  _PyFunction_FastCallKeywords
    @     0x564c2ae91841  _PyEval_EvalFrameDefault
    @     0x564c2add6059  _PyEval_EvalCodeWithName
    @     0x564c2ae38307  _PyFunction_FastCallKeywords
    @     0x564c2ae91841  _PyEval_EvalFrameDefault
    @     0x564c2add6919  _PyEval_EvalCodeWithName
    @     0x564c2ae38307  _PyFunction_FastCallKeywords
    @     0x564c2ae90a66  _PyEval_EvalFrameDefault
    @     0x564c2ae3807b  _PyFunction_FastCallKeywords
    @     0x564c2ae90a66  _PyEval_EvalFrameDefault
    @     0x564c2add6059  _PyEval_EvalCodeWithName
Aborted (core dumped)

**Comment by maxuetao** [comment]
check检查无误。

**Comment by wuyefeilin** [comment]
请问你跑的是什么数据集，如果利用我们提供的数据集能够跑通的话说明是你数据集的原因？

另外check的日志信息也发一下
