### ISSUE TITLE
paddleseg中的参数命名

### ISSUE THREAD

**Issue by Fly-hub** [PaddlePaddle/PaddleSeg#584]
想在train.py中取出模型的权重，如何实现呀？比如：想在train.py中打印出unet网络模型的conv训练参数权重。

**Comment by michaelowenliu** [comment]
@Fly-hub Hi, could you please try the dygraph version that is much easier for debugging? https://github.com/PaddlePaddle/PaddleSeg/tree/release/v0.7.0/dygraph
