### ISSUE TITLE
PaddleSeg DeepLabv3+ 想用二分类 的bce_loss和dice_loss 会报错

### ISSUE THREAD

**Issue by Tzr-black** [PaddlePaddle/PaddleSeg#590]
主要是设置标签的问题，如果在label.txt中设置为：背景\n目标\n
开始训练的时候会报错，这不是二分类
![image](https://user-images.githubusercontent.com/39473756/99477483-8ac18d00-298d-11eb-9ddc-4f59eb14e9ab.png)
如果在label.txt中设置为：目标\n
训练可以进行一个epoch之后，开始验证会报错，行列索引越界的问题都会出现
![image](https://user-images.githubusercontent.com/39473756/99477702-00c5f400-298e-11eb-8fd4-3b9d5fef50c3.png)
标签图像 8为彩图 像素值为0，1
![image](https://user-images.githubusercontent.com/39473756/99477814-3cf95480-298e-11eb-9340-36238c5412db.png)

**Comment by wuyefeilin** [comment]
麻烦你提供一下训练的日志

**Comment by yangy996** [comment]
我也出现了这个问题，请问你解决了吗？
