### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by merlinarer** [PaddlePaddle/PaddleSeg#592]
- 标题：Segmentation fault (core dumped)
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle_gpu-1.8.5.post107-cp38
    2）GPU：Tesla T4/cuda 10.1/cudnn 7.6

- 训练信息
    1）单机多卡

- 问题描述：在云服务器上训练报错，给的信息很少，数据已经check过没问题

报错信息如下：

`
W1119 17:02:08.179440 12160 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 10.0
W1119 17:02:08.182862 12160 device_context.cc:260] device: 0, cuDNN Version: 7.6.
W1119 17:02:09.262043 12160 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1119 17:02:09.262073 12160 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1119 17:02:09.262084 12160 init.cc:231] The detail failure signal is:

W1119 17:02:09.262089 12160 init.cc:234] *** Aborted at 1605776529 (unix time) try "date -d @1605776529" if you are using GNU date ***
W1119 17:02:09.263607 12160 init.cc:234] PC: @                0x0 (unknown)
W1119 17:02:09.263702 12160 init.cc:234] *** SIGSEGV (@0x0) received by PID 12160 (TID 0x7f73265ff700) from PID 0; stack trace: ***
W1119 17:02:09.265028 12160 init.cc:234]     @     0x7f73261e5390 (unknown)
W1119 17:02:09.266345 12160 init.cc:234]     @                0x0 (unknown)
Segmentation fault (core dumped)
`
应该怎么处理呢

**Comment by nepeplwu** [comment]
@merlinarer 出错前的训练日志麻烦也给下，另外，这个问题是必现的吗？

**Comment by merlinarer** [comment]
对，每次都会出现，不知道具体原因，通过安装docker，用docker里的cuda环境解决了，谢谢！
