### ISSUE TITLE
dataset的padding value修改不生效

### ISSUE THREAD

**Issue by Rayaction** [PaddlePaddle/PaddleSeg#594]
DATASET:
    DATA_DIR: "xxxx"
    NUM_CLASSES: x
    TRAIN_FILE_LIST: "xxxx"
    VAL_FILE_LIST: "xxxx"
    TEST_FILE_LIST: "xxxx"
    VIS_FILE_LIST: "xxxx"
    PADDING_VALUE: [255, 255, 255]

这里padding value修改后不生效啊

跑起来程序后是这个 'PADDING_VALUE': [73.9261575, 98.05992615, 84.09281115]‘

**Comment by wuyefeilin** [comment]
请问你是否设置了cfg.MEAN， 如果设置了该项，则会利用MEAN来计算PADDING_VALUE， 这样你的设置就不会生效了。

**Comment by Rayaction** [comment]
> 请问你是否设置了cfg.MEAN， 如果设置了该项，则会利用MEAN来计算PADDING_VALUE， 这样你的设置就不会生效了。

mean设置了，但我理解这个padding的值理论上应该是ignore的值？我想让他原图padding成0，0，0或者label padding成ignore的index应该怎么做

**Comment by wuyefeilin** [comment]
> > 请问你是否设置了cfg.MEAN， 如果设置了该项，则会利用MEAN来计算PADDING_VALUE， 这样你的设置就不会生效了。
> 
> mean设置了，但我理解这个padding的值理论上应该是ignore的值？我想让他原图padding成0，0，0或者label padding成ignore的index应该怎么做

采用默认的参数就是这么操作的，如果你既要修改mean， 又想更改图像的padding，可以在下面代码后直接对PADDING_VALUE进行修改。
https://github.com/PaddlePaddle/PaddleSeg/blob/9ca3ebd5f27b56847c0633f96cd46c786982a457/pdseg/train.py#L452
或者注释掉下面两行代码
https://github.com/PaddlePaddle/PaddleSeg/blob/9ca3ebd5f27b56847c0633f96cd46c786982a457/pdseg/utils/collect.py#L101
