### ISSUE TITLE
miou计算问题

### ISSUE THREAD

**Issue by wstchhwp** [PaddlePaddle/PaddleSeg#595]
你好，我想问下我用paddleseg做一个课题，现在有4个类别(包含背景），背景是0，其他是1，2，3.
现在计算出来混淆矩阵是4*4的，我想问下计算miou,ap之类的评价指标，如何考虑背景？
是把混淆矩阵直接输入进去算吗？还是取出来3*3不包含背景的混淆矩阵再计算？

**Comment by wstchhwp** [comment]
@wuyefeilin

**Comment by wuyefeilin** [comment]
我们计算的混淆矩阵是包含背景类的即4x4, 不包含背景类的就是3x3。 miou和ap的计算都是根据混淆矩阵计算的。至于要不要包含背景类取决于你的需求

**Comment by wstchhwp** [comment]
好的
