### ISSUE TITLE
适配PaddlePaddle 2.0rc0时，PaddleSeg/dygraph/paddleseg/models/backbones/hrnet.py 两处错误

### ISSUE THREAD

**Issue by jordan2013** [PaddlePaddle/PaddleSeg#598]
一、拼写错误
     self.pool2d_gap = nn.AdaptiveAvgPool2d(1)应为：
      self.pool2d_gap = nn.AdaptiveAvgPool2D(1)

二、Linear中参数错误
self.squeeze = nn.Linear(
            num_channels,
            med_ch,
            act="relu",
            ParamAttr=paddle.ParamAttr(
                initializer=nn.initializer.Uniform(-stdv, stdv)))

        stdv = 1.0 / math.sqrt(med_ch * 1.0)
        self.excitation = nn.Linear(
            med_ch,
            num_filters,
            act="sigmoid",
          ParamAttr=paddle.ParamAttr(
                initializer=nn.initializer.Uniform(-stdv, stdv)))

以上语句，应改为：
self.squeeze = nn.Linear(
            num_channels,
            med_ch,
            #act="relu",
            weight_attr=paddle.ParamAttr(
                initializer=nn.initializer.Uniform(-stdv, stdv)))

        stdv = 1.0 / math.sqrt(med_ch * 1.0)
        self.excitation = nn.Linear(
            med_ch,
            num_filters,
            #act="sigmoid",
            weight_attr=paddle.ParamAttr(
                initializer=nn.initializer.Uniform(-stdv, stdv)))

**Comment by wuyefeilin** [comment]
多谢反馈，马上纠正
