### ISSUE TITLE
加载两个训练好的模型

### ISSUE THREAD

**Issue by sxlyiyiyi** [PaddlePaddle/PaddleSeg#602]
怎么同时加载两个训练好的模型对同一个数据进行预测？

InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 256, the input's shape is [1, 256, 64, 64]; the filter's channels is 64, the filter's shape is [7, 64, 3, 3]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.
  [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:256 != filter_dims[1] * groups:64.] at (D:\1.8.5\paddle\paddle\fluid\operators\conv_op.cc:94)
  [operator < conv2d > error]

**Comment by michaelowenliu** [comment]
@sxlyiyiyi Hi, how did you use the two models?

**Comment by lytk01** [comment]
同问，怎么同时加载两个或两个以上的模型，然后分别计算
