### ISSUE TITLE
deeplabv3p_resnet50_vd_cityscapes.yaml的问题

### ISSUE THREAD

**Issue by Hustle-Tung** [PaddlePaddle/PaddleSeg#605]
在windows平台利用deeplabv3p做遥感影像地块分割训练，出现一些问题：
配置：windows10, RTX 3070, CUDA 10.2, cuDNN 7.6.5, paddlepaddle2.0rc. paddle.fluid.install_check.run_check() 输出Your Paddle Fluid is installed succesfully!

问题在以下输出中提出：
问题1：运行到这个地方需要等一二十分钟，是在读取训练数据还是校验数据还是卡住？
问题2：这里真实输入与预训练模型输入不匹配该怎么办？
问题3： 这里fusion_group在windows10不能使用怎么办？
问题4： 从此出开始应该是开始训练了，但是GPU显存占用率较高，GPU利用率很低只有0%~3%，这是正常调用GPU了吗？GPU利用率难道不应该这么低吧？

(bdci) E:\code\PaddleSeg>python pdseg/train.py --use_gpu --cfg ./deeplab.yaml --log_steps 2000
{'AUG': {'AUG_METHOD': 'unpadding',
         'FIX_RESIZE_SIZE': (256, 256),
         'FLIP': False,
         'FLIP_RATIO': 0.5,
         'INF_RESIZE_VALUE': 500,
         'MAX_RESIZE_VALUE': 600,
         'MAX_SCALE_FACTOR': 2.0,
         'MIN_RESIZE_VALUE': 400,
         'MIN_SCALE_FACTOR': 0.5,
         'MIRROR': True,
         'RICH_CROP': {'ASPECT_RATIO': 0.33,
                       'BLUR': False,
                       'BLUR_RATIO': 0.1,
                       'BRIGHTNESS_JITTER_RATIO': 0.5,
                       'CONTRAST_JITTER_RATIO': 0.5,
                       'ENABLE': False,
                       'MAX_ROTATION': 15,
                       'MIN_AREA_RATIO': 0.5,
                       'SATURATION_JITTER_RATIO': 0.5},
         'SCALE_STEP_SIZE': 0.25,
         'TO_RGB': False},
 'BATCH_SIZE': 16,
 'DATALOADER': {'BUF_SIZE': 256, 'NUM_WORKERS': 8},
 'DATASET': {'DATA_DIM': 3,
             'DATA_DIR': './dataset/rs_data',
             'IGNORE_INDEX': 255,
             'IMAGE_TYPE': 'rgb',
             'NUM_CLASSES': 7,
             'PADDING_VALUE': [127.5, 127.5, 127.5],
             'SEPARATOR': ' ',
             'TEST_FILE_LIST': './dataset/rs_data/testA_list.txt',
             'TEST_TOTAL_IMAGES': 10000,
             'TRAIN_FILE_LIST': './dataset/rs_data/train_list.txt',
             'TRAIN_TOTAL_IMAGES': 97321,
             'VAL_FILE_LIST': './dataset/rs_data/val_list.txt',
             'VAL_TOTAL_IMAGES': 48660,
             'VIS_FILE_LIST': './dataset/rs_data/val_list.txt'},
 'EVAL_CROP_SIZE': (256, 256),
 'FREEZE': {'MODEL_FILENAME': 'model',
            'PARAMS_FILENAME': 'params',
            'SAVE_DIR': 'freeze_model'},
 'MEAN': [0.5, 0.5, 0.5],
 'MODEL': {'BN_MOMENTUM': 0.99,
           'DEEPLAB': {'ASPP_WITH_SEP_CONV': True,
                       'BACKBONE': 'resnet_vd_50',
                       'BACKBONE_LR_MULT_LIST': [0.1, 0.1, 0.2, 0.2, 1.0],
                       'DECODER': {'CONV_FILTERS': 256,
                                   'OUTPUT_IS_LOGITS': False,
                                   'USE_SUM_MERGE': False},
                       'DECODER_USE_SEP_CONV': True,
                       'DEPTH_MULTIPLIER': 1.0,
                       'ENABLE_DECODER': True,
                       'ENCODER': {'ADD_IMAGE_LEVEL_FEATURE': True,
                                   'ASPP_CONVS_FILTERS': 256,
                                   'ASPP_RATIOS': None,
                                   'ASPP_WITH_CONCAT_PROJECTION': True,
                                   'ASPP_WITH_SE': False,
                                   'POOLING_CROP_SIZE': None,
                                   'POOLING_STRIDE': [1, 1],
                                   'SE_USE_QSIGMOID': False},
                       'ENCODER_WITH_ASPP': True,
                       'OUTPUT_STRIDE': 16},
           'DEFAULT_EPSILON': 1e-05,
           'DEFAULT_GROUP_NUMBER': 32,
           'DEFAULT_NORM_TYPE': 'bn',
           'FP16': False,
           'HRNET': {'STAGE2': {'NUM_CHANNELS': [40, 80], 'NUM_MODULES': 1},
                     'STAGE3': {'NUM_CHANNELS': [40, 80, 160],
                                'NUM_MODULES': 4},
                     'STAGE4': {'NUM_CHANNELS': [40, 80, 160, 320],
                                'NUM_MODULES': 3}},
           'ICNET': {'DEPTH_MULTIPLIER': 0.5, 'LAYERS': 50},
           'MODEL_NAME': 'deeplabv3p',
           'MULTI_LOSS_WEIGHT': [1.0],
           'OCR': {'OCR_KEY_CHANNELS': 256, 'OCR_MID_CHANNELS': 512},
           'PSPNET': {'DEPTH_MULTIPLIER': 1, 'LAYERS': 50},
           'SCALE_LOSS': 'DYNAMIC',
           'UNET': {'UPSAMPLE_MODE': 'bilinear'}},
 'NUM_TRAINERS': 1,
 'SLIM': {'KNOWLEDGE_DISTILL': False,
          'KNOWLEDGE_DISTILL_IS_TEACHER': False,
          'KNOWLEDGE_DISTILL_TEACHER_MODEL_DIR': '',
          'NAS_ADDRESS': '',
          'NAS_IS_SERVER': True,
          'NAS_PORT': 23333,
          'NAS_SEARCH_STEPS': 100,
          'NAS_SPACE_NAME': '',
          'NAS_START_EVAL_EPOCH': 0,
          'PREPROCESS': False,
          'PRUNE_PARAMS': '',
          'PRUNE_RATIOS': []},
 'SOLVER': {'BEGIN_EPOCH': 1,
            'CROSS_ENTROPY_WEIGHT': None,
            'DECAY_EPOCH': [10, 20],
            'GAMMA': 0.1,
            'LOSS': ['softmax_loss'],
            'LOSS_WEIGHT': {'BCE_LOSS': 1,
                            'DICE_LOSS': 1,
                            'LOVASZ_HINGE_LOSS': 1,
                            'LOVASZ_SOFTMAX_LOSS': 1,
                            'SOFTMAX_LOSS': 1},
            'LR': 0.05,
            'LR_POLICY': 'poly',
            'LR_WARMUP': False,
            'LR_WARMUP_STEPS': 2000,
            'MOMENTUM': 0.9,
            'MOMENTUM2': 0.999,
            'NUM_EPOCHS': 10,
            'OPTIMIZER': 'sgd',
            'POWER': 0.9,
            'WEIGHT_DECAY': 4e-05},
 'STD': [0.5, 0.5, 0.5],
 'TEST': {'TEST_MODEL': 'saved_model/deeplabv3p_resnet50_vd_bn_cityscapes/final'},
 'TRAIN': {'MODEL_SAVE_DIR': 'saved_model/deeplabv3p_resnet50_vd_bn_cityscapes',
           'PRETRAINED_MODEL_DIR': 'pretrained_model/deeplabv3p_resnet50_vd_cityscapes',
           'RESUME_MODEL_DIR': '',
           'SNAPSHOT_EPOCH': 10,
           'SYNC_BATCH_NORM': False},
 'TRAINER_ID': 0,
 'TRAIN_CROP_SIZE': (256, 256)}
#Device count: 1
batch_size_per_dev: 16
W1123 23:32:37.564334 16116 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 86, Driver API Version: 11.1, Runtime API Version: 10.2
W1123 23:32:37.569320 16116 device_context.cc:346] device: 0, cuDNN Version: 7.6.
**# 问题1：运行到这个地方需要等一二十分钟，是在读取训练数据还是校验数据还是卡住？**
[SKIP] Shape of pretrained weight logit/weights doesn't match.(Pretrained: (19, 256, 1, 1), Actual: (7, 256, 1, 1))
[SKIP] Shape of pretrained weight logit/biases doesn't match.(Pretrained: (19,), Actual: (7,))
**# 问题2：这里真实输入与预训练模型输入不匹配该怎么办？**
There are 345/347 varaibles in pretrained_model/deeplabv3p_resnet50_vd_cityscapes are loaded.
Use multi-thread reader
W1123 23:50:36.134191 16116 build_strategy.cc:170] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.
**# 问题3： 这里fusion_group在windows10不能使用怎么办？**
epoch=1 step=2000 lr=0.04852 loss=1.3468 step/sec=2.573 | ETA 06:21:00
**# 问题4： 从此出开始应该是开始训练了，但是GPU显存占用率较高，GPU利用率很低只有0%~3%，这是正常调用GPU了吗？GPU利用率难道不应该这么低吧？**

问题在以上输出中提出：
问题1：运行到这个地方需要等一二十分钟，是在读取训练数据还是校验数据还是卡住？
问题2：这里真实输入与预训练模型输入不匹配该怎么办？
问题3： 这里fusion_group在windows10不能使用怎么办？
问题4： 从此出开始应该是开始训练了，但是GPU显存占用率较高，GPU利用率很低只有0%~3%，这是正常调用GPU了吗？GPU利用率难道不应该这么低吧？

**Comment by Hustle-Tung** [comment]
求大佬和开发者老师们帮忙答疑解惑，感谢
![屏幕截图 2020-11-24 004752](https://user-images.githubusercontent.com/41102889/99990433-c1186580-2dee-11eb-843b-69145de955d0.png)

**Comment by LutaoChu** [comment]
问题1：运行到这个地方需要等一二十分钟，是在读取训练数据还是校验数据还是卡住？
你可以在pdseg/train.py这2个位置前后打印日志，看看到底是卡在哪个地方
```
    dataset = SegDataset(
        file_list=cfg.DATASET.TRAIN_FILE_LIST,
        mode=ModelPhase.TRAIN,
        shuffle=True,
        data_dir=cfg.DATASET.DATA_DIR)
```
和
```
    data_loader, avg_loss, lr, pred, grts, masks = build_model(
        train_prog, startup_prog, phase=ModelPhase.TRAIN)
    build_model(test_prog, fluid.Program(), phase=ModelPhase.EVAL)
    data_loader.set_sample_generator(
        data_generator, batch_size=batch_size_per_dev, drop_last=drop_last)
```

问题2：这里真实输入与预训练模型输入不匹配该怎么办？
没有关系，因为类别数不一样，跳过参数是正常的

问题3： 这里fusion_group在windows10不能使用怎么办？
确定你用的是paddle2.0rc吗？这里只是warning，看日志应该符合预期

问题4： 从此出开始应该是开始训练了，但是GPU显存占用率较高，GPU利用率很低只有0%~3%，这是正常调用GPU了吗？GPU利用率难道不应该这么低吧？
不正常。你试试开启--use_mpio，多进程读取数据


另外log_steps设为2000是不是太多了，打印日志会很少。我们一般用默认值

**Comment by Hustle-Tung** [comment]
感谢您的回复！

问题1：经过打印输出，上述两处均没有问题，是卡在了`pdseg/train.py`的`exe.run(startup_prog)`处，再深入是`E:\anaconda3\envs\bdci\Lib\site-packages\paddle\fluid\executor.py`的`self._default_executor.run(program.desc, scope, 0, True, True, fetch_var_name)`处，再深入是`C:\Users\wxx\AppData\Local\JetBrains\PyCharmCE2020.1\python_stubs\-228631969\paddle\fluid\core_avx\Executor.py`的`def run(self, arg0, *args, **kwargs): pass`处，就到这里，我看这里是pass，那应该继续运行呀，为何会卡在这里？

问题2和问题3不是Error不用解决是嘛？

问题4：在[https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.7.0/docs/config.md](https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.7.0/docs/config.md#%E5%91%BD%E4%BB%A4%E8%A1%8Cflags)的`命令行FLAGS`里，`--use_mpio`不支持windows平台，我还能用多进程读取吗？这里的多进程读取是从磁盘读到内存的多进程，还是从内存到显存的多进程？另外，paddle训练的时候是读取一次磁盘还是动态多次读取呀？

**Comment by LutaoChu** [comment]
不客气
问题1：我还第一次听说这个问题，还不知道是什么原因。你用的是静态图版本，将不再添加新的feature，可以尝试动态图版本，动态图添加了很多feature，可以试用一下，或许可以解决你碰到的问题。https://github.com/PaddlePaddle/PaddleSeg/tree/release/v0.7.0/dygraph
问题2和3：是的，不是error
问题4：暂时没有其他多进程读取的功能，可以试用动态图版本，动态图在windows下是可以使用多进程读取的。
多进程是从磁盘到内存的多进程。
是动态多次读取的。

**Comment by Hustle-Tung** [comment]
谢谢您的回复

问题1：我测试了动态图版本，依然卡住20分钟左右，卡在[dygraph/train.py](https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.7.0/dygraph/train.py)第123行`train()`，这里调用的是[dygraph/paddleseg/core/train.py](https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.7.0/dygraph/paddleseg/core/train.py)第51行`def train()`吗？
问题4：加上`--use_mpio`后提示没有这个选项的，所以还是没法用这个选项。

**Comment by LutaoChu** [comment]
问题1：是的。是不是你的机器有其他程序也在运行呢？你也可以具体再定位一下卡住的位置
问题4：动态图中没有--use_mpio这个选项的，你可以设置--num_workers开启多进程IO，设为4或2试试

**Comment by Hustle-Tung** [comment]
谢谢，现在问题主要还是启动之后卡住等待的问题，时长比较固定：19分钟

问题1：通过加输入输出，我测试出[dygraph/train.py](https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.7.0/dygraph/train.py)第123行`train()`调用的是[dygraph/paddleseg/core/train.py](https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.7.0/dygraph/paddleseg/core/train.py)第51行`def train()`，在该函数开头64行前面加输出，结果显示卡住过程之后才进入这里的`def train()`；考虑到`dygraph/train.py)`第123行`train()`传参时还调用了`cfg.model`等函数，继续在[dygraph/paddleseg/cvlibs/config.py](https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.7.0/dygraph/paddleseg/cvlibs/config.py)加输出，同样显示卡住过程之后才进入`dygraph/paddleseg/cvlibs/config.py`，实在是不知道卡在哪里了，请问这个train()都还调用了哪些py文件呢，总不能卡在`__init__.py`里吧

**Comment by LutaoChu** [comment]
cfg中会构建指定的model、optimizer等实例，看起来是卡在了config.py中。train函数中包含cfg.model, cfg.optimizer, cfg.iters, cfg.batch_size，你可以把这4个提出来，先计算完再传入train函数，看看是卡在哪个cfg中。

我猜大概率是卡在cfg.model上。

换成其他模型会碰到这个问题吗？

```
    train(
        cfg.model,
        train_dataset,
        val_dataset=val_dataset,
        optimizer=cfg.optimizer,
        save_dir=args.save_dir,
        iters=cfg.iters,
        batch_size=cfg.batch_size,
        resume_model=args.resume_model,
        save_interval=args.save_interval,
        log_iters=args.log_iters,
        num_workers=args.num_workers,
        use_vdl=args.use_vdl,
        losses=losses)
```

**Comment by Hustle-Tung** [comment]
确实卡在cfg.model上。

我在`dygraph/train.py`第123行`train()`前添加输出：
```
print("start")
aaa = cfg.model
print("aaa")
bbb = cfg.optimizer
print("bbb")
ccc = cfg.iters
print("ccc")
ddd = cfg.batch_size
print("ddd")
```
`aaa`等替换`train`的参数。
在`dygraph/paddleseg/cvlibs/config.py`第230行前后添加输出：
```
print("cfg.model")
self._model = self._load_object(model_cfg)
print("cfg.model-end")
```
在`dygraph/paddleseg/cvlibs/config.py`第278行添加输出：
```
print("cfg._load_object")
return component(**params)
```
结果如下：
```
(bdci) E:\code\PaddleSeg-develop\dygraph>python train.py --config my.yml --save_dir save_model --save_interval 1000 --log_iters 200 --do_eval --use_vdl --num_workers 8
2020-12-01 21:25:11 [INFO]
------------Environment Information-------------
platform: Windows-10-10.0.18362-SP0
Python: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Paddle compiled with cuda: True
NVCC: Cuda compilation tools, release 10.2, V10.2.89
cudnn: 7.6
GPUs used: 1
CUDA_VISIBLE_DEVICES: 0
GPU: ['GPU 0: GeForce RTX']
PaddlePaddle: 2.0.0-rc0
OpenCV: 4.4.0
------------------------------------------------
2020-12-01 21:25:11 cfg._load_object----------------------------------------
2020-12-01 21:25:11 cfg._load_object----------------------------------------
2020-12-01 21:25:11 cfg._load_object----------------------------------------
2020-12-01 21:25:11 cfg._load_object----------------------------------------
2020-12-01 21:25:11 cfg._load_object----------------------------------------
2020-12-01 21:25:11 cfg._load_object----------------------------------------
2020-12-01 21:25:11 cfg._load_object----------------------------------------
2020-12-01 21:25:11 cfg._load_object----------------------------------------
2020-12-01 21:25:11 cfg._load_object----------------------------------------
2020-12-01 21:25:11 cfg._load_object----------------------------------------
2020-12-01 21:25:11 cfg._load_object----------------------------------------
2020-12-01 21:25:11 cfg._load_object----------------------------------------
2020-12-01 21:25:11 cfg._load_object----------------------------------------
2020-12-01 21:25:11 cfg._load_object----------------------------------------
2020-12-01 21:25:11 cfg._load_object----------------------------------------
2020-12-01 21:25:11 cfg._load_object----------------------------------------
2020-12-01 21:25:11 cfg._load_object----------------------------------------
2020-12-01 21:25:11 cfg._load_object----------------------------------------
2020-12-01 21:25:12 cfg._load_object----------------------------------------
2020-12-01 21:25:12 [INFO]
---------------Config Information---------------
batch_size: 16
iters: 20000
learning_rate:
  decay:
    end_lr: 0.0
    power: 0.9
    type: poly
  value: 0.015
loss:
  coef:
  - 1
  types:
  - ignore_index: 255
    type: CrossEntropyLoss
model:
  backbone:
    align_corners: false
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w48_ssld.tar.gz
    type: HRNet_W48
  backbone_indices:
  - -1
  type: FCN
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 4.0e-05
train_dataset:
  dataset_root: ../dataset/rs_data
  mode: train
  num_classes: 7
  train_path: ../dataset/rs_data/train_list.txt
  transforms:
  - max_scale_factor: 1.5
    min_scale_factor: 0.75
    scale_step_size: 0.25
    type: ResizeStepScaling
  - type: RandomHorizontalFlip
  - type: RandomVerticalFlip
  - max_rotation: 30
    type: RandomRotation
  - brightness_range: 0.2
    contrast_range: 0.2
    saturation_range: 0.2
    type: RandomDistort
  - crop_size:
    - 256
    - 256
    type: RandomPaddingCrop
  - type: Normalize
  type: Dataset
val_dataset:
  dataset_root: ../dataset/rs_data
  mode: val
  num_classes: 7
  transforms:
  - type: Normalize
  type: Dataset
  val_path: ../dataset/rs_data/val_list.txt
------------------------------------------------
2020-12-01 21:25:12 start----------------------------------------
2020-12-01 21:25:12 cfg._load_object----------------------------------------
2020-12-01 21:25:12 cfg._load_object----------------------------------------
2020-12-01 21:25:12 cfg._load_object----------------------------------------
2020-12-01 21:25:12 cfg._load_object----------------------------------------
2020-12-01 21:25:12 cfg._load_object----------------------------------------
2020-12-01 21:25:12 cfg._load_object----------------------------------------
2020-12-01 21:25:12 cfg._load_object----------------------------------------
2020-12-01 21:25:12 cfg._load_object----------------------------------------
2020-12-01 21:25:13 cfg.model----------------------------------------
2020-12-01 21:25:13 cfg._load_object----------------------------------------
W1201 21:25:13.253166 13896 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 86, Driver API Version: 11.1, Runtime API Version: 10.2
W1201 21:25:13.253166 13896 device_context.cc:346] device: 0, cuDNN Version: 7.6.
# 可以看到这里卡住18分钟
2020-12-01 21:43:07 [INFO]      Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/hrnet_w48_ssld.tar.gz
2020-12-01 21:43:08 [INFO]      There are 1525/1525 variables loaded into HRNet.
2020-12-01 21:43:08 cfg._load_object----------------------------------------
2020-12-01 21:43:08 cfg.model-end----------------------------------------
2020-12-01 21:43:08 aaa----------------------------------------
2020-12-01 21:43:08 cfg._load_object----------------------------------------
2020-12-01 21:43:08 cfg._load_object----------------------------------------
2020-12-01 21:43:08 cfg._load_object----------------------------------------
2020-12-01 21:43:08 cfg._load_object----------------------------------------
2020-12-01 21:43:08 cfg._load_object----------------------------------------
2020-12-01 21:43:08 cfg._load_object----------------------------------------
2020-12-01 21:43:08 cfg._load_object----------------------------------------
2020-12-01 21:43:08 cfg._load_object----------------------------------------
2020-12-01 21:43:09 cfg.model-end----------------------------------------
2020-12-01 21:43:09 bbb----------------------------------------
2020-12-01 21:43:09 ccc-----------------------------------------
2020-12-01 21:43:09 ddd----------------------------------------
2020-12-01 21:43:09 def train start----------------------------------------
2020-12-01 21:45:58 [INFO]      [TRAIN] epoch=1, iter=200/20000, loss=8992919653491692.0000, lr=0.014866, batch_cost=0.8439, reader_cost=0.0013 | ETA 04:38:29
2020-12-01 21:48:46 [INFO]      [TRAIN] epoch=1, iter=400/20000, loss=1.3173, lr=0.014730, batch_cost=0.8425, reader_cost=0.0000 | ETA 04:35:13
2020-12-01 21:51:35 [INFO]      [TRAIN] epoch=1, iter=600/20000, loss=1.3383, lr=0.014595, batch_cost=0.8429, reader_cost=0.0000 | ETA 04:32:32
2020-12-01 21:54:24 [INFO]      [TRAIN] epoch=1, iter=800/20000, loss=1.3391, lr=0.014460, batch_cost=0.8452, reader_cost=0.0000 | ETA 04:30:27
```
`dygraph/paddleseg/cvlibs/config.py`第278行不是直接`return component(**params)`嘛，为啥卡在这里呢？我还需要在哪里加输出呢？

**Comment by LutaoChu** [comment]
看日志不是因为卡在return component(**params)上，而是在_load_object(model_cfg)更新key，value上。这加载FCN的过程太久了。
我们再看一下

**Comment by Hustle-Tung** [comment]
好的
