### ISSUE TITLE
CCF遥感动态图baseline: FatalError: Blocking queue is killed because the data reader raises an exception.

### ISSUE THREAD

**Issue by pdogdoy** [PaddlePaddle/PaddleSeg#608]
数据集准备是按照之前paddleSeg的baseline，pdseg/check.py校验后也没有问题，以下是报错

ERROR:root:DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    main(args)
  File "train.py", line 136, in main
    losses=losses)
  File "/home/aistudio/PaddleSeg/dygraph/paddleseg/core/train.py", line 107, in train
    for data in loader:
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 743, in __next__
    data = self._reader.read_next_var_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::thread::_State_impl<std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1}> > >::_M_run()
1   std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)
2   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
5   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:154)

**Comment by michaelowenliu** [comment]
@Bulimito Hi, how did you set the num_works parameter?
