### ISSUE TITLE
请问xception-41, xception-65的预训练模型的训练超参数是什么呀

### ISSUE THREAD

**Issue by CoinCheung** [PaddlePaddle/PaddleSeg#612]
大佬好，

想问xception-41和xception-65的backbone做预训练时使用的超参数数还有aug方法啥的，不知道这个可以在哪里查到呢

**Comment by wuyefeilin** [comment]
你好，预训练模型来自于PaddleClas， 想知道具体的训练方式可以到PaddleClas上进行咨询

**Comment by CoinCheung** [comment]
感谢回复 !!
