### ISSUE TITLE
请问，为什么export CUDA_VISIBLE_DEVICES=0，1指定了两块gpu之后会报错？

### ISSUE THREAD

**Issue by 33749110** [PaddlePaddle/PaddleSeg#614]
请问，为什么   export CUDA_VISIBLE_DEVICES=0，1  指定了两块gpu之后会报错

报错信息是 ：‘NoneType’ object has no attribute ’run‘

而且是不停的再刷这一条错误信息，请问是我少填了哪个参数嘛？

**Comment by wuyefeilin** [comment]
，后面不能有空格

**Comment by 33749110** [comment]
我没有加空格，那个是因为输入问题的时候是手动的添加的,1  ，当时是中文输入法所以显得有空格。
我在运行的时候是没有添加空格的
export CUDA_VISIBLE_DEVICES=0,1   就是这样

**Comment by wuyefeilin** [comment]
麻烦提供一下完整的报错信息，及运行的环境，paddle， cuda, cudnn版本

**Comment by 33749110** [comment]
cuda是10.2的 cudnn是7.6的  paddle是2.0.0-rc0  ，服务器操作系统是Ubuntu16.04
完整的报错信息的话，它就是和正常运行一样 输出信息，然后到了Use multi-thread reader
这卡了一下之后 
就开始刷‘NoneType’ object has no attribute ’run‘。
在Use multi-thread reader这句话之后有没有输出什么，我不能肯定 因为‘NoneType’ object has no attribute ’run‘刷新太快了

**Comment by Lie-huo** [comment]
> cuda是10.2的 cudnn是7.6的 paddle是2.0.0-rc0 ，服务器操作系统是Ubuntu16.04
> 完整的报错信息的话，它就是和正常运行一样 输出信息，然后到了Use multi-thread reader
> 这卡了一下之后
> 就开始刷‘NoneType’ object has no attribute ’run‘。
> 在Use multi-thread reader这句话之后有没有输出什么，我不能肯定 因为‘NoneType’ object has no attribute ’run‘刷新太快了

我也遇到了这个问题，还没有解决

**Comment by wuyefeilin** [comment]
数据校验通过了吗

**Comment by 33749110** [comment]
通过了的，就是相同的配置，相同的数据表，一块gpu可以运行，但是指定两块就会出错

**Comment by wuyefeilin** [comment]
> cuda是10.2的 cudnn是7.6的 paddle是2.0.0-rc0 ，服务器操作系统是Ubuntu16.04
> 完整的报错信息的话，它就是和正常运行一样 输出信息，然后到了Use multi-thread reader
> 这卡了一下之后
> 就开始刷‘NoneType’ object has no attribute ’run‘。
> 在Use multi-thread reader这句话之后有没有输出什么，我不能肯定 因为‘NoneType’ object has no attribute ’run‘刷新太快了
一旦报错马上停止，然后给出报错信心

**Comment by 33749110** [comment]
我只能卡到Use multi-thread reader这句话，之后的，我。。反应力可能跟不上吧。反正我试了好几次 都是停止之后，往上翻到头也只有满屏的‘NoneType’ object has no attribute ’run‘。    已经看不到报错信息了

**Comment by JerryDeepl** [comment]
同样的问题，满屏‘NoneType’ object has no attribute ’run‘，看不到其它信息了

**Comment by nepeplwu** [comment]
@33749110 可以先指定单卡，并且不要加上`--use_mpio`这个选项，这样比较好定位错误

**Comment by 33749110** [comment]
emmm....我没有使用use_mpio 选项  只添加了use_gpu  
同样的设置 如果指定单卡 可以正常运行
指定双卡的话 就不行

**Comment by nepeplwu** [comment]
配置是否方便给下？

**Comment by 33749110** [comment]
cuda是10.2的 cudnn是7.6的 paddle是2.0.0-rc0 ，服务器操作系统是Ubuntu16.04
GPU是4块泰坦1080
还需要其他信息嘛

**Comment by nepeplwu** [comment]
训练的配置麻烦也给下，另外，错误日志没法截全的问题，可以试试通过重定向输出来拿到日志，通过在训练命令后面加上`> test.log 2>&1`来把训练日志和错误日志都输出到test.log，例如：
```cmd
python pdseg/train.py --cfg xxxx.yaml > test.log 2>&1
```

**Comment by fsted** [comment]
我也是这个问题，好烦
