### ISSUE TITLE
deeplabv3p_mobilenetv3_large_cityscapes.yaml文件中的参数含义

### ISSUE THREAD

**Issue by yukang123** [PaddlePaddle/PaddleSeg#625]
请问，configs/deeplabv3p_mobilenetv3_large_cityscapes.yaml中的 MODEL.DEEPLAB.ENCODER.ASPP_WITH_SE参数的含义是什么呢，是决定是否使用Squeeze-and-Excitation模块吗？但我在pdseg/models/modeling/deeplab.py里没找到这个参数，而在pdseg/models/backbone/mobilenet_v3.py里面已经根据model_name = large或small来指定各层是否使用SE模块，是不是这个参数已经没有意义了呢？

yaml文件有关模型的内容
MODEL:
    DEFAULT_NORM_TYPE: "bn"
    MODEL_NAME: "deeplabv3p"
    DEEPLAB:
        BACKBONE: "mobilenetv3_large"
        ASPP_WITH_SEP_CONV: True
        DECODER_USE_SEP_CONV: True
        ENCODER_WITH_ASPP: True
        ENABLE_DECODER: True
        OUTPUT_STRIDE: 32
        BACKBONE_LR_MULT_LIST: [0.15,0.35,0.65,0.85,1]
        ENCODER:
            POOLING_STRIDE: (4, 5)
            POOLING_CROP_SIZE: (769, 769)
            **ASPP_WITH_SE: True**
            SE_USE_QSIGMOID: True
            ASPP_CONVS_FILTERS: 128
            ASPP_WITH_CONCAT_PROJECTION: False
            ADD_IMAGE_LEVEL_FEATURE: False
        DECODER:
            USE_SUM_MERGE: True
            CONV_FILTERS: 19
            OUTPUT_IS_LOGITS: True

**Comment by nepeplwu** [comment]
@yukang123 该配置主要用于判断是否要在ASPP模块中使用Squeeze-and-Excitation模块，代码见：
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.7.0/pdseg/models/modeling/deeplab.py#L160
