### ISSUE TITLE
关于动态图预测的方便性

### ISSUE THREAD

**Issue by iceriver97** [PaddlePaddle/PaddleSeg#627]
比如我想在云端训练，在本地进行预测，我在执行 predict.py 的时候为什么还会去 check train_list.txt 以及 val_list.txt 存不存在呢？这样我就必须在云端把这两个文件下载下来放到指定的位置以便通过校验，可是这跟 predict 没有关系不是吗？

**Comment by michaelowenliu** [comment]
@iceriver97 Hi, yes, you are right. Improve it in a future version. Thanks a lot.
