### ISSUE TITLE
更新develop分支之后，连官网提供的预训练模型都用不了了

### ISSUE THREAD

**Issue by deep-practice** [PaddlePaddle/PaddleSeg#628]
deeplabv3p_resnet101_os8_cityscapes_769x769_80k
![dttbug](https://user-images.githubusercontent.com/54052915/100515196-24224780-31b5-11eb-9ba5-a1c070222822.jpg)

**Comment by michaelowenliu** [comment]
@deep-practice Hi, I just tested it. It works well. How did you use the pretrained model?

**Comment by deep-practice** [comment]
我就是在model的pretrain那儿把预训练模型的路径加进去了。
怎么说呢，感觉动态图版本碰到的莫名其妙的问题很多，有时候换个机器就正常了，但是在某个机器上就是不行。
