### ISSUE TITLE
lovasz softmax loss在多分类问题中使用不了

### ISSUE THREAD

**Issue by PrimSun** [PaddlePaddle/PaddleSeg#629]
参考教程https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.7.0/docs/lovasz_loss.md后，二分类可做，但是多分类配置有问题

**Comment by LutaoChu** [comment]
请问是什么问题呢

**Comment by LutaoChu** [comment]
你好，PaddleSeg已推出动态图版本Lovasz loss，欢迎体验！
https://github.com/PaddlePaddle/PaddleSeg/blob/develop/docs/lovasz_loss.md
