### ISSUE TITLE
在准备训练数据的时候通过labelme生成了原图所对应的.json文件，但是在数据格式转换时报错ModuleNotFoundError: No module named 'labelme'

### ISSUE THREAD

**Issue by eddieheyutong** [PaddlePaddle/PaddleSeg#63]
如题，已经生成了对应的json文件但是在格式转换的时候，提示
Traceback (most recent call last):
  File "labelme2seg.py", line 15, in <module>
    import labelme
ModuleNotFoundError: No module named 'labelme'
找不到labelme是什么原因呢

**Comment by LutaoChu** [comment]
你好，有可能是安装labelme的python和运行labelme2seg的python不是同一个，比如在python2上安装labelme，在python3上运行的labelme2seg。
之前也有用户碰到了这个问题。请核对一下

**Comment by eddieheyutong** [comment]
@LutaoChu 大神您好上个问题我解决了，现在我运行这个文件的时候，那个python labelme2seg.py <path/to/label_json_file> <path/to/output_dataset>这句命令里，<path/to/output_dataset>该打什么呢，我看说明说不用预先创建，脚本运行时会自动创建，否则会报错。就把这个地方空着了然后报错labelme2seg.py: error: the following arguments are required: output_dir，但是当我新建一个out文件夹时输入地址，报错Output directory already exists: ./out，所以这个究竟该怎样去执行是正确的呢？

**Comment by LutaoChu** [comment]
你可以输入任意一个目录，如果是linux的话，比如"/home/123"。重点是需要输入文件夹的完整路径，绝对路径或相对路径都可以。

上个问题可以告知一下是怎么解决的吗？

**Comment by eddieheyutong** [comment]
@LutaoChu 您好我现在运行这个labelme2seg.py文件可以生成文件夹和class_names.txt但是在文件夹JPEGImages中和文件夹SegmentationClassPNG中都没有生成的图片，在class_name.txt中也只有background这个一个类别，想问您一下这个是什么问题？然后我之前问您的那个问题我是通过把pip路径调整后解决的，就如您所说应该是在不同版本的python上运行和下载的labelme，应为我这台电脑上存在着多版本的python，需要进行核对。

**Comment by LutaoChu** [comment]
运行labelme2seg.py有报错和警告信息吗 ？

也可能是用labelme标注生成的json不对。请确认一下json里是否有保存类别边缘坐标。正常的json是这样的：

![image](https://user-images.githubusercontent.com/30695251/67194032-edfa8c00-f428-11e9-9672-ea377dc83bd5.png)

**Comment by eddieheyutong** [comment]
@LutaoChu 我运行这个文件是没有报错的信息的，我在终端输入的指令如下：
python labelme2seg.py home/zhengyuan/PaddleSeg/docs/annotation/data_annotated/ output
然后终端的返回信息为：
Creating dataset: output
class_names: ('_background_',)
Saved class_names: output/class_names.txt
并无错误信息，我进行测试的json文件为data_annotated中的样例文件“2011_000025.json”，
![2019-10-21 17-38-23屏幕截图](https://user-images.githubusercontent.com/45486682/67194416-a88a8e80-f429-11e9-9ec6-48adab84b7a2.png)

**Comment by LutaoChu** [comment]
回复到这个issue里了 https://github.com/PaddlePaddle/PaddleSeg/issues/68

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。
