### ISSUE TITLE
动态图 本地运行训练报错提示 local variable 'nvcc' referenced before assignment

### ISSUE THREAD

**Issue by Darki-luo** [PaddlePaddle/PaddleSeg#630]
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    main(args)
  File "train.py", line 92, in main
    env_info = get_sys_env()
  File "/home/w/env/sensoring/dygraph/paddleseg/utils/env/sys_env.py", line 93, in get_sys_env
    env_info['NVCC'] = _get_nvcc_info(cuda_home)
  File "/home/w/env/sensoring/dygraph/paddleseg/utils/env/sys_env.py", line 65, in _get_nvcc_info
    return nvcc
UnboundLocalError: local variable 'nvcc' referenced before assignment

在aistudio运行没有问题，本地18.04，paddle2.0rc-gpu版本，nividia驱动440，就报错了

**Comment by wuyefeilin** [comment]
多谢反馈
![image](https://user-images.githubusercontent.com/30919197/100562912-fd205e80-32f7-11eb-9021-5b01d9760f09.png)
这个函数改成这样试试
def _get_nvcc_info(cuda_home):
    if cuda_home is not None and os.path.isdir(cuda_home):
        try:
            nvcc = os.path.join(cuda_home, 'bin/nvcc')
            nvcc = subprocess.check_output(
                "{} -V".format(nvcc), shell=True).decode()
            nvcc = nvcc.strip().split('\n')[-1]
        except:
            nvcc = "Not Available"
else:
    nvcc = "Not Available"
    return nvcc

**Comment by liguoyu666** [comment]
> 多谢反馈
> ![image](https://user-images.githubusercontent.com/30919197/100562912-fd205e80-32f7-11eb-9021-5b01d9760f09.png)
> 这个函数改成这样试试
> def _get_nvcc_info(cuda_home):
> if cuda_home is not None and os.path.isdir(cuda_home):
> try:
> nvcc = os.path.join(cuda_home, 'bin/nvcc')
> nvcc = subprocess.check_output(
> "{} -V".format(nvcc), shell=True).decode()
> nvcc = nvcc.strip().split('\n')[-1]
> except:
> nvcc = "Not Available"
> else:
> nvcc = "Not Available"
> return nvcc

刚好也遇到这个bug了，多卡环境修改后正常运行

**Comment by Darki-luo** [comment]
> 多谢反馈
> ![image](https://user-images.githubusercontent.com/30919197/100562912-fd205e80-32f7-11eb-9021-5b01d9760f09.png)
> 这个函数改成这样试试
> def _get_nvcc_info(cuda_home):
> if cuda_home is not None and os.path.isdir(cuda_home):
> try:
> nvcc = os.path.join(cuda_home, 'bin/nvcc')
> nvcc = subprocess.check_output(
> "{} -V".format(nvcc), shell=True).decode()
> nvcc = nvcc.strip().split('\n')[-1]
> except:
> nvcc = "Not Available"
> else:
> nvcc = "Not Available"
> return nvcc

本地只有一张卡，这样改了还是一样的问题，最后直接把这句话（env_info['NVCC'] = _get_nvcc_info(cuda_home)）注释掉了

**Comment by Darki-luo** [comment]
> > 多谢反馈
> > ![image](https://user-images.githubusercontent.com/30919197/100562912-fd205e80-32f7-11eb-9021-5b01d9760f09.png)
> > 这个函数改成这样试试
> > def _get_nvcc_info(cuda_home):
> > if cuda_home is not None and os.path.isdir(cuda_home):
> > try:
> > nvcc = os.path.join(cuda_home, 'bin/nvcc')
> > nvcc = subprocess.check_output(
> > "{} -V".format(nvcc), shell=True).decode()
> > nvcc = nvcc.strip().split('\n')[-1]
> > except:
> > nvcc = "Not Available"
> > else:
> > nvcc = "Not Available"
> > return nvcc
> 
> 本地只有一张卡，这样改了还是一样的问题，最后直接把这句话（env_info['NVCC'] = _get_nvcc_info(cuda_home)）注释掉了

找到原因了，之前在ubuntu建的conda环境下装的paddle-gpu, cuda-tookit。ubuntu系统里只安装了源的nvidia-driver驱动，在系统源安装了nvidia-cuda-toolkit之后就没问题了（sudo apt update&&sudo apt install nvidia-cuda-toolkit)
