### ISSUE TITLE
实验用电脑没有联网，CPP部署build过程中make出错，又会download错误，从一台电脑拷贝ext-yaml-cpp文件也会报错不知道如何修改makefile文件

### ISSUE THREAD

**Issue by michaelfu123** [PaddlePaddle/PaddleSeg#631]
![image](https://user-images.githubusercontent.com/38556449/100560756-d0694880-32f1-11eb-883d-a016542b9b59.png)

**Comment by Channingss** [comment]
@michaelfu123 
可以下载 [yaml.zip](https://bj.bcebos.com/paddlex/deploy/deps/yaml-cpp.zip) 后解压，

然后修改文件的这一行：https://github.com/PaddlePaddle/PaddleSeg/blob/29ab4e924cac93ccb3ed8b778d76f9760d1651bd/deploy/cpp/external-cmake/yaml-cpp.cmake#L10

改为如下，URL后面接解压的yaml目录：
URL path/to/yaml/

然后删除这一行：
https://github.com/PaddlePaddle/PaddleSeg/blob/29ab4e924cac93ccb3ed8b778d76f9760d1651bd/deploy/cpp/external-cmake/yaml-cpp.cmake#L11

**Comment by michaelfu123** [comment]
> @michaelfu123
> 可以下载 [yaml.zip](https://bj.bcebos.com/paddlex/deploy/deps/yaml-cpp.zip) 后解压，
> 
> 然后修改文件的这一行：
> 
> https://github.com/PaddlePaddle/PaddleSeg/blob/29ab4e924cac93ccb3ed8b778d76f9760d1651bd/deploy/cpp/external-cmake/yaml-cpp.cmake#L10
> 
> 改为如下，URL后面接解压的yaml目录：
> URL path/to/yaml/
> 
> 然后删除这一行：
> https://github.com/PaddlePaddle/PaddleSeg/blob/29ab4e924cac93ccb3ed8b778d76f9760d1651bd/deploy/cpp/external-cmake/yaml-cpp.cmake#L11

感谢，按照您的指示build成功了

**Comment by Channingss** [comment]
@michaelfu123 不客气
