### ISSUE TITLE
pdseg的动态图预训练模型在哪找？

### ISSUE THREAD

**Issue by liguoyu666** [PaddlePaddle/PaddleSeg#633]
1. develop分支遥感分割比赛的例子，用的hrnet_w48_ssld预训练模型，但是我在PaddleSeg/docs/model_zoo.md里并未找到预训练模型，请问该在哪找？
2.  
`model:

  type: FCN

  backbone:

    type: HRNet_W48

    align_corners: False

    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w48_ssld.tar.gz

  backbone_indices: [-1]

  pretrained: Null`

 pretrained: Null 是表示啥意思，不用预训练模型？

3. 上面这个例子里，使用了多尺度评估的方法，请问该方法是才出来的吗，能否告知是哪篇论文，静态图会添加这个方法吗？

**Comment by michaelowenliu** [comment]
@liguoyu666 Hi, in general, there are two "pretrained" in a model config file, where one is for the whole model, and the other is only for the backbone. 

![infoflow 2020-11-30 10-22-25](https://user-images.githubusercontent.com/14087480/100562223-fee92280-32f5-11eb-99e2-1c273a5bc6cc.png)


Usually, we trained a model using a pre-trained backbone, so you can find there is a URL link in backbone config which is the pre-trained model link. If you download the pre-trained model to your local machine first, and the URL link can be replaced with the local path of the pre-trained model.
As for the other "pretrained" under model config, it is a pre-trained model of the entire model, so we usually set it as null expect that you want to fine-tune on a new small dataset.

**Comment by liguoyu666** [comment]
> @liguoyu666 Hi, in general, there are two "pretrained" in a model config file, where one is for the whole model, and the other is only for the backbone.
> 
> ![infoflow 2020-11-30 10-22-25](https://user-images.githubusercontent.com/14087480/100562223-fee92280-32f5-11eb-99e2-1c273a5bc6cc.png)
> 
> Usually, we trained a model using a pre-trained backbone, so you can find there is a URL link in backbone config which is the pre-trained model link. If you download the pre-trained model to your local machine first, and the URL link can be replaced with the local path of the pre-trained model.
> As for the other "pretrained" under model config, it is a pre-trained model of the entire model, so we usually set it as null expect that you want to fine-tune on a new small dataset.

明白了，假如我微调整个网络的时候，第二个pre-trained设为整个网络训练出来的模型，第一个pre-trained需要改为null吗？上面提到的另外两个问题也请帮忙看哈

**Comment by michaelowenliu** [comment]
@liguoyu666 Yes, you can set the first pre-trained as null. Actually, although the first one is specified, the second pre-trained would also overwrite the first one while loading the model. 

For the pre-trained of the entire model on remote sensing, please download from "model" in the following link:
https://github.com/PaddlePaddle/PaddleSeg/tree/develop/dygraph/contrib/remote_sensing

The multi-scale inference is not new. We do not add any new features in the static version but only fix the bug. If you are interested in the multi-scale training, you may refer to the new article (Hierarchical Multi-Scale Attention for Semantic Segmentation) which has a SOTA result in Cityscapes dataset.

**Comment by liguoyu666** [comment]
> @ liguoyu666是的，您可以将第一个预训练设置为null。实际上，尽管指定了第一个，但第二个经过预训练的模型在加载模型时也会覆盖第一个。
> 
> 对于整个模型的遥感预训练，请从以下链接的“模型”中下载：[https](https://github.com/PaddlePaddle/PaddleSeg/tree/develop/dygraph/contrib/remote_sensing) :
> [//github.com/PaddlePaddle/PaddleSeg/tree/develop/dygraph/contrib/remote_sensing](https://github.com/PaddlePaddle/PaddleSeg/tree/develop/dygraph/contrib/remote_sensing)
> 
> 多尺度推理并不是新事物。我们不会在静态版本中添加任何新功能，而只会修复该错误。如果您对多尺度训练感兴趣，可以参考新文章（语义分割的分层多尺度注意），该文章在Cityscapes数据集中具有SOTA结果。

遥感分割比赛动态图baseline用的预训练模型为hrnet_w48_ssld，但是我在PaddleSeg/docs/model_zoo.md与/PaddleSeg-develop/pretrained_model/download_model.py里并未找到该预训练模型，不是问的整个模型的权重，问的backbone的预训练模型

**Comment by michaelowenliu** [comment]
@liguoyu666 Hi, do you mean the static graph version?

**Comment by ElegantGod** [comment]
@michaelowenliu 你好，动态图的预训练模型在哪里，develop/pretrained_model/download_model.py这个是静态图的预训练模型，有没有动态图的预训练模型相应的download_model.py

**Comment by liguoyu666** [comment]
> @liguoyu666 Hi, do you mean the static graph version?

谢谢了，是我搞晕了，在dygraph下找到了

**Comment by liguoyu666** [comment]
> @michaelowenliu 你好，动态图的预训练模型在哪里，develop/pretrained_model/download_model.py这个是静态图的预训练模型，有没有动态图的预训练模型相应的download_model.py

官方好像没有提供动态图预训练权重的download_model.py，可以模仿静态图的写个脚本。在dygraph下的configs里，自己手动下载，或者在yaml文件里给个下载链接。
