### ISSUE TITLE
Seg 静态图的预训练模型就是使用 Seg 中网络进行训练的吗？

### ISSUE THREAD

**Issue by iceriver97** [PaddlePaddle/PaddleSeg#634]
比如对于预训练模型：pspnet50_bn_cityscapes
该模型是使用 pdseg/models/modeling/pspnet.py 训练得来的吗？为什么我查看预训练模型的网络结构发现有个地方有差异，

backbone: resnet.py 中 在bottleneck_block 结束的部分，第191 行开始有两个操作：

```
pool = fluid.layers.pool2d(
                input=conv, pool_size=7, pool_type='avg', global_pooling=True)
stdv = 1.0 / math.sqrt(pool.shape[1] * 1.0)
out = fluid.layers.fc(
                input=pool,
                size=class_dim,
                param_attr=fluid.param_attr.ParamAttr(
                    initializer=fluid.initializer.Uniform(-stdv, stdv)))
```

但是我在预训练的模型结构中并没有发现有这两个操作，bottleneck_block 结束之后直接就进入了 pspnet 的部分，这是为什么呢？

**Comment by nepeplwu** [comment]
@iceriver97 你列出的这三个op是resnet进行分类的层，在分割中不需要用到

**Comment by iceriver97** [comment]
> @iceriver97 你列出的这三个op是resnet进行分类的层，在分割中不需要用到

谢谢，但是哪里的代码忽略掉了这三个op呢？

**Comment by nepeplwu** [comment]
在backbone的传入参数中有个`end_points`，组网时会根据这个参数来选取需要的featmap，其他的未用到的op在保存模型时就会被去除掉
