### ISSUE TITLE
CPP部署预测过程中其他几个训练好的模型（除humanseg_server_inference外）output with a unexpected size，求解决方法。如何通过修改cpp代码或者转换模型输出tensor格式

### ISSUE THREAD

**Issue by michaelfu123** [PaddlePaddle/PaddleSeg#638]
![image](https://user-images.githubusercontent.com/38556449/100611306-1ce17200-334c-11eb-8fea-2c4f1ba78419.png)

**Comment by Channingss** [comment]
@michaelfu123 请问有模型的输入shape和yaml中预处理输出shape一致吗？麻烦把yaml和模型输出大小（拖动__model__文件到netorn可视化软件可查看）信息提供一下

**Comment by michaelfu123** [comment]
您好，netorn看不到输出大小，
![image](https://user-images.githubusercontent.com/38556449/100818308-cfb4eb80-3484-11eb-90f7-9ff522f9ca40.png)
![image](https://user-images.githubusercontent.com/38556449/100818357-ed825080-3484-11eb-8fd7-fe3d434ab59c.png)
问题
![image](https://user-images.githubusercontent.com/38556449/100818436-199dd180-3485-11eb-8520-4b19be16827c.png)

**Comment by Channingss** [comment]
按一下左上角的菜单键，然后可以看到左侧弹出输入输出的信息：
![image](https://user-images.githubusercontent.com/12471701/100837118-8f1c9880-34ab-11eb-979a-d86374ad4957.png)

**Comment by michaelfu123** [comment]
humanseg_lite_quant 的__model__文件
![image](https://user-images.githubusercontent.com/38556449/100840687-3819c200-34b1-11eb-9f15-716ca41904d6.png)

**Comment by michaelfu123** [comment]
> humanseg_lite_quant 的__model__文件
> ![image](https://user-images.githubusercontent.com/38556449/100840687-3819c200-34b1-11eb-9f15-716ca41904d6.png)

好像都是没有固定输入输出大小的

**Comment by Channingss** [comment]
@michaelfu123 这样的话，报错是这一行：
https://github.com/PaddlePaddle/PaddleSeg/blob/15c8a112c11bd67b870b8da720c672e5c3d04bdf/deploy/cpp/predictor/seg_predictor.cpp#L219
打印一下影响`size_mismatch `变量的相关变量？看是哪个导致了`size_mismatch `为true的

**Comment by michaelfu123** [comment]
@Channingss 
打印出结果这样的：
![image](https://user-images.githubusercontent.com/38556449/100857061-2a6f3700-34c7-11eb-856c-812eb4947b5c.png)

![image](https://user-images.githubusercontent.com/38556449/100857046-23482900-34c7-11eb-9970-c2ddafeb2c91.png)

**Comment by Channingss** [comment]
@michaelfu123 这样吧，你先用用python的部署脚本测试一下看能正常run吗？
https://github.com/PaddlePaddle/PaddleSeg/tree/release/v0.7.0/deploy/python

**Comment by michaelfu123** [comment]
@Channingss 好的谢谢，python部署先不测试了。不知道能不能调节一下输出维度的顺序原本输出的tensor是（1,192,192,1），不知道能不能调节成（1,1,192,192）。

**Comment by Channingss** [comment]
@michaelfu123 这个你可以在输出后面做个后处理转换成（1,1,192,192）。

**Comment by michaelfu123** [comment]
@Channingss 我试试看，如果你们有好的方法可以告诉我，谢谢
