### ISSUE TITLE
关于paddleseg中pspnet的测试问题

### ISSUE THREAD

**Issue by besttrying** [PaddlePaddle/PaddleSeg#639]
训练好后启用测试，当测试val数据集正常，把val数据集改为test数据集测试结果全为0
![XQ2 9ZEV{LH 3$2}H69G $N](https://user-images.githubusercontent.com/18502224/100692648-3b844f00-33c6-11eb-9ddd-ec7855d6d6f5.png)

**Comment by wuyefeilin** [comment]
请问你用的是什么数据集，测试数据集和验证数据集的格式一样吗

**Comment by besttrying** [comment]
用的cityscapes的数据集
![C_~(H%KC`2A {B@X4B_)H O](https://user-images.githubusercontent.com/18502224/100715531-4a80f680-33f2-11eb-8bb1-49ce6c86b69a.png)
config.py中路径没变。
代码中在eval.pyz中修改了图片路径
![7XQA@2F$_8PH{T2BT0IF7IU](https://user-images.githubusercontent.com/18502224/100715915-e448a380-33f2-11eb-98f7-cfd32bd4cdf9.png)

**Comment by besttrying** [comment]
用的cityscapes的数据集
![C_~(H%KC`2A {B@X4B_)H O](https://user-images.githubusercontent.com/18502224/100716085-2d98f300-33f3-11eb-93ab-22da9534dc49.png)

config.py中路径没变。
代码中在eval.pyz中修改了图片集，VAL改为TEST
![Inked7XQA@2F$_8PH{T2BT0IF7IU_LI](https://user-images.githubusercontent.com/18502224/100716348-836d9b00-33f3-11eb-82ee-6b3f56e3414a.jpg)

**Comment by wuyefeilin** [comment]
cityscape的test数据集的标注文件只有标签0和255，是不能拿来eval的，test的指标需要你预测结果然后上传到官网才能得到结果的

**Comment by besttrying** [comment]
非常感谢
