### ISSUE TITLE
动态图版本的predict.py没有--aug_pred开启多尺度翻转预测和--is_slide开启滑窗预测这两个选项

### ISSUE THREAD

**Issue by xiaoranchenwai** [PaddlePaddle/PaddleSeg#640]
运行predict.py开启滑窗预测会提示如下：
usage: predict.py [-h] [--config CFG] [--model_path MODEL_PATH]
                  [--image_path IMAGE_PATH] [--save_dir SAVE_DIR]
predict.py: error: unrecognized arguments: --is_slide --crop_size 256 256 --stride 128 128

**Comment by wuyefeilin** [comment]
请问你使用的是哪一个版本

**Comment by xiaoranchenwai** [comment]
我知道了，原来要用develop版本，谢谢大佬
