### ISSUE TITLE
UNet vis.py 识别结果背景图片不是黑色的问题.

### ISSUE THREAD

**Issue by phker** [PaddlePaddle/PaddleSeg#647]
pdseg/vis.py输出的图片第一张图片的背景是黑色正确的,后面的几张图片颜色都是不对的.

**Comment by wuyefeilin** [comment]
麻烦给一下运行时的日志输出

另外可以正确评估吗？

**Comment by lantudou** [comment]
https://github.com/PaddlePaddle/PaddleSeg/issues/670可以检查参考一下是否是这个BUG
