### ISSUE TITLE
pdseg/export_model.py 导出Unet 模型无法导出model.yaml文件.

### ISSUE THREAD

**Issue by phker** [PaddlePaddle/PaddleSeg#648]
pdseg/export_model.py 导出Unet 模型无法导出model.yaml文件. 导致无法使用 paddlex 标准的模型进行部署.

**Comment by jiangjiajun** [comment]
> pdseg/export_model.py 导出Unet 模型无法导出model.yaml文件. 导致无法使用 paddlex 标准的模型进行部署.

Hi，你好，目前使用PaddleSeg训练导出的模型配置还无法在PaddleX中兼容。我们正在推进PaddleX支持PaddleSeg训练产出模型的事情，欢迎关注PaddleX了解项目的进展。  https://github.com/PaddlePaddle/PaddleX

当前为了解决你的问题，有两种方法
- 1. 使用PaddleX训练UNet模型，训练代码参考 https://github.com/PaddlePaddle/PaddleX/blob/develop/tutorials/train/semantic_segmentation/unet.py
- 2. 使用PaddleSeg训练完模型后，导出模型，并手动写一个PaddleX的yml文件
