### ISSUE TITLE
环境配置好后，使用人体模型预测 有结果。使用自己通过paddleSeg训练的unet模型预测。mask内容为空

### ISSUE THREAD

**Issue by JD012** [PaddlePaddle/PaddleSeg#65]
自己训练的模型 通过 PaddleSeg源码中的vis.py 预测，可以看到 预测结果。将模型导出后，放入下载好的 seg-serving 中 。修改了 seg_conf.yaml中的均值方差和图片大小。但 就是无结果。

1.使用 官方提供的人体模型 在 seg-serving  上预测 有结果。
2.自己训练的模型使用PaddleSeg 中的vis.py 测试 有结果。
3.官方模型使用的是 deeplab ，自己训练使用的是unit  

请帮忙定位下原因，十分感谢。

**Comment by joey12300** [comment]
无结果是指生成了全黑的图像吗？请问您是使用过image_seg_client.py进行访问的吗？

**Comment by JD012** [comment]
> 无结果是指生成了全黑的图像吗？请问您是使用过image_seg_client.py进行访问的吗？

您好 ，是生成了全黑的图像，我是使用的image_seg_client.py

**Comment by joey12300** [comment]
您应该是运行多分类的模型吧。该demo针对的是二分类的分割模型。seg-serving返回的结果是每个像素类别为1（即前景）的置信度。所以该脚本的作用是把人像（前景）抠出来，放在白色的背景上。

**Comment by JD012** [comment]
> 您应该是运行多分类的模型吧。该demo针对的是二分类的分割模型。seg-serving返回的结果是每个像素类别为1（即前景）的置信度。所以该脚本的作用是把人像（前景）抠出来，放在白色的背景上。

您好，感谢，我运行的是多分类。我再调一下换成二分类试试。
