### ISSUE TITLE
pdseg train报段错误

### ISSUE THREAD

**Issue by Rayaction** [PaddlePaddle/PaddleSeg#653]
cuda 版本10.2 cudnn 8.0 paddle 2.0rc
运行pdseg train报段错误：

Use multi-thread reader

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Segmentation fault) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1607139882 (unix time) try "date -d @1607139882" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 72277 (TID 0x7fced744c700) from PID 0 ***]
请问怎么解决

**Comment by nepeplwu** [comment]
@Rayaction cuda版本和cudnn版本是多少？训练配置麻烦也贴下

**Comment by Rayaction** [comment]
> @Rayaction cuda版本和cudnn版本是多少？训练配置麻烦也贴下

cuda 版本10.2 cudnn 8.0 paddle 2.0rc

TRAIN_CROP_SIZE: (512, 512)
EVAL_CROP_SIZE: (512, 512)
AUG:
    AUG_METHOD: "unpadding"
    FIX_RESIZE_SIZE: (512, 512)
    MIRROR: True
    FLIP: False
    FLIP_RATIO: 0.5
    RICH_CROP:
        ENABLE: False
        MAX_ROTATION: 90
        MIN_AREA_RATIO: 0.5
        ASPECT_RATIO: 0.33
        BLUR: False
        BLUR_RATIO: 0.1
BATCH_SIZE: 16
TRAIN:
    PRETRAINED_MODEL_DIR: "./pretrained_model/ocnet_w18_bn_cityscapes"
    # PRETRAINED_MODEL_DIR: "./saved_model/unet_series/unet_ais_50_pretrained_aug/final_1/"
    MODEL_SAVE_DIR: "./saved_model/ocr/ocr_cityscapes_bs16_sgd/"
    SNAPSHOT_EPOCH: 1

SOLVER:
    NUM_EPOCHS: 100
    LR: 0.001
    LR_POLICY: "cosine"
    OPTIMIZER: "sgd"
    MOMENTUM: 0.9
#    WEIGHT_DECAY: 0.0005
    LOSS: ["softmax_loss"]
    # LOSS: ["lovasz_softmax_loss","softmax_loss"]
#        LOSS_WEIGHT:
#            LOVASZ_SOFTMAX_LOSS: 0.2
#            SOFTMAX_LOSS: 0.8
#    CROSS_ENTROPY_WEIGHT: 'dynamic'
    LR_WARMUP: True
    LR_WARMUP_STEPS: 500

DATALOADER:
    NUM_WORKERS: 8
    BUF_SIZE: 256

TEST:
    TEST_MODEL: "./saved_model/ocr/ocr_cityscapes_bs16_sgd/11"

**Comment by Rayaction** [comment]
cuda 版本10.2 cudnn 8.0 paddle 2.0rc

TRAIN_CROP_SIZE: (512, 512)
EVAL_CROP_SIZE: (512, 512)
AUG:
    AUG_METHOD: "unpadding"
    FIX_RESIZE_SIZE: (512, 512)
    MIRROR: True
    FLIP: False
    FLIP_RATIO: 0.5
    RICH_CROP:
        ENABLE: False
        MAX_ROTATION: 90
        MIN_AREA_RATIO: 0.5
        ASPECT_RATIO: 0.33
        BLUR: False
        BLUR_RATIO: 0.1
BATCH_SIZE: 8
TRAIN:
    PRETRAINED_MODEL_DIR: "./pretrained_model/ocnet_w18_bn_cityscapes"
    MODEL_SAVE_DIR: "./saved_model/ocr/ocr_cityscapes_bs16_sgd/"
    SNAPSHOT_EPOCH: 1

SOLVER:
    NUM_EPOCHS: 100
    LR: 0.001
    LR_POLICY: "cosine"
    OPTIMIZER: "sgd"
    MOMENTUM: 0.9

    LOSS: ["softmax_loss"]
    LR_WARMUP: True
    LR_WARMUP_STEPS: 500

DATALOADER:
    NUM_WORKERS: 8
    BUF_SIZE: 256

TEST:
    TEST_MODEL: "./saved_model/ocr/ocr_cityscapes_bs16_sgd/11"

**Comment by nepeplwu** [comment]
@Rayaction 建议将cudnn降级到7.6

**Comment by Rayaction** [comment]
> @Rayaction 建议将cudnn降级到7.6

降级后可以支持更大batch size是吗

**Comment by nepeplwu** [comment]
嗯，是的，只要不超过显存大小就行

**Comment by Rayaction** [comment]
> 嗯，是的，只要不超过显存大小就行

8.0的cudnn占用不到1/8的 显存可以运行，否则就是之前的错误。 6269MiB / 32510MiB 这个可以运行。

**Comment by Rayaction** [comment]
> 嗯，是的，只要不超过显存大小就行

降级后可以更大bs，close了，感谢
