### ISSUE TITLE
请问在deploy下的python版预测安装中，contrib/humanseg/pretrained_weights/humanseg_lite_inference无法部署啊

### ISSUE THREAD

**Issue by wsy1991** [PaddlePaddle/PaddleSeg#658]

**Comment by wsy1991** [comment]
![截屏2020-12-07 下午7 34 05](https://user-images.githubusercontent.com/33680999/101346200-2d04ce80-38c3-11eb-92b5-407689b841a7.png)

**Comment by wuyefeilin** [comment]
请把你创建的yml文件贴一下
