### ISSUE TITLE
运行seg-serving 时客户端传输 Gray 格式图片 服务端报错。 传输RGB格式的没有问题。

### ISSUE THREAD

**Issue by JD012** [PaddlePaddle/PaddleSeg#66]
运行seg-serving 时客户端传输 Gray 格式图片 服务端报错。 传输RGB格式的没有问题。

**Comment by joey12300** [comment]
你好，是报以下的异常错误吗？
> "Image XXX  has incompitable size (hh, ww, cc)" 
如果是，请修改seg_conf.yaml中CHANNELS的值。 Gray 格式图片的CHANNELS值为1，RGB格式图片的CHANNELS值为3。PS：如果是RGBA格式图片，CHANNELS值为4。

**Comment by JD012** [comment]
感谢。现在采取的处理方式是 所有图片都先转换成 RGB格式。
