### ISSUE TITLE
Segmentation fault 报错，无法val

### ISSUE THREAD

**Issue by 33749110** [PaddlePaddle/PaddleSeg#662]
我本来有三个网络在训练  deeplabv3+resnet101、deeplabv3+resnet101、fcn+hrnetw48
然后昨天中午的时候服务器被重启了一下。
等到再开的时候，我的两个deep就无法正常val了，而fcn+hrnet还可以正常运行

以下是进行val时的报错
C++ Traceback (most recent call last):
paddle: :framework: :SignalHandle(char const*, int)
paddle: :platform: :GetCurrentTraceBackstring abi :cxx11]()
Error Message Summary:
FatalError: A serious error (Segmentation fault) is detected by the operating system. (at /paddle/paddle/ fluid/platform/ init. cc :303)
[TimeInfo: *** Aborted at 1607431144 (unix time) try "date -d @1607431144" if you are using GNU date ***]
[signalInfo: *** SIGSEGV (@ex0) received by PID 23040 (TID 0x7f4fb51e3700) from PID 0 ***]
INFO 2020-12- 08 20:39:09,656 utils. py:275] terminate all the procs
ERROR 2020-12 08 20:39:09 , 656 utils.py:445] ABORT!!! out of all 1 trainers, the trainer process with rank=[0] was aborted. please check its log .
INFO 2020-12- 08 20:39:12, 660 utils.py:275] terminate all the procs

版本信息
W1208 20:38:58. 16616223040 device_ context.cc:338] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 11.0, Runtime API Version: 10.1
W1208 20:38:58 .16619323040 device_ context. CC:346] device: 0, CuDNN Version: 8.0.

如果用nvidia-smi指令  所显示的cuda版本信息是11.0
如果用cat 指令   所显示的cuda版本信息是10.2

paddlepaddle的版本是2.0.0

**Comment by wuyefeilin** [comment]
你好，请给一下完整的报错的信息。 另外，因为是意外终止， 请确保模型是否保存完整

**Comment by 33749110** [comment]
W1209 10:19:08.788491   459 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 11.0, Runtime API Version: 10.1
W1209 10:19:08.788540   459 device_context.cc:346] device: 0, cuDNN Version: 8.0.
2020-12-09 10:19:10 [INFO]      Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/resnet101_vd_ssld.tar.gz
2020-12-09 10:19:11 [INFO]      There are 530/530 variables loaded into ResNet_vd.
2020-12-09 10:19:16 [INFO]      Loaded trained params of model successfully
2020-12-09 10:19:16 [INFO]      Start evaluating (total_samples=2920, total_iters=2920)...


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Segmentation fault) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1607480357 (unix time) try "date -d @1607480357" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 459 (TID 0x7faeecb95700) from PID 0 ***]

INFO 2020-12-09 10:19:20,542 utils.py:275] terminate all the procs
ERROR 2020-12-09 10:19:20,543 utils.py:445] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2020-12-09 10:19:23,546 utils.py:275] terminate all the procs

**Comment by 33749110** [comment]
模型保存完整  换一台机器可以正常val。
另外，我和伙伴反复排查过后 确定应该是
logits = model(im)  这句报错

**Comment by wuyefeilin** [comment]
CuDNN Version 降到7.6试试，这个问题是环境问题引起的
