### ISSUE TITLE
paddleseg/contrib/Humanseg下的模型如何部署在padldeseg/deploy/python或者padldeseg/deploy/cpp下

### ISSUE THREAD

**Issue by wsy1991** [PaddlePaddle/PaddleSeg#664]
想把paddleseg/contrib/humanseg/pretrained_wights/humanseg_lite_inference部署安装在padleseg/deploy/python。

但paddleseg提供的安装模型方式是：pdseg/export_model.py，得到（deploy.yaml，model，params），所以想安装部署模型必须利用：pdseg/export_model.py。但在paddleseg下只支持deeplab，fast_scnn，hrnet，icnet，ocnet,pspnet,unet，而humanseg_lite_inference模型是shufflenet_slim做的，所以无法将paddleseg/contrib/humanseg/pretrained_wights/humanseg_lite_inference部署安装在paddleseg/deploy/python或者paddleseg/deploy/cpp下

**Comment by Channingss** [comment]
@wsy1991 这里导出humanseg_lite模型的脚本：
https://github.com/PaddlePaddle/PaddleSeg/tree/release/v0.8.0/contrib/HumanSeg#%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA

deploy.yaml的话可以copy：
https://github.com/PaddlePaddle/PaddleSeg/tree/release/v0.8.0/deploy/cpp#42-%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE

针对humanseg_lite相应修改一下。

**Comment by wsy1991** [comment]
对，这个方法我之前试了，在deploy下运行的时候，报错 @Channingss

**Comment by wsy1991** [comment]
> @wsy1991 这里导出humanseg_lite模型的脚本：
> https://github.com/PaddlePaddle/PaddleSeg/tree/release/v0.8.0/contrib/HumanSeg#%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA
> 
> deploy.yaml的话可以copy：
> https://github.com/PaddlePaddle/PaddleSeg/tree/release/v0.8.0/deploy/cpp#42-%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE
> 
> 针对humanseg_lite相应修改一下。

**Comment by wsy1991** [comment]
@@用paddleseg/contrib/Humanseg/export，导出的模型，在paddleseg/deploy/python.infer.py中运行，模型的输出为(batch_size=1,w=192,h=192,channel=1)，而paddle/pdseg/export_model导出的模型，在paddleseg/deploy/python.infer.py中运行，模型输出为(batch_size=1,channel=2,w=192,h=192) @Channingss

**Comment by Channingss** [comment]
@wsy1991 把具体报错贴出来看看

**Comment by wsy1991** [comment]
![Uploading 截屏2020-12-11 下午3.27.47.png…]()

**Comment by wsy1991** [comment]
![截屏2020-12-11 下午3 30 23](https://user-images.githubusercontent.com/33680999/101875570-cedb3280-3bc5-11eb-93e3-acdbe88cc102.png)

**Comment by wsy1991** [comment]
![Uploading 截屏2020-12-11 下午3.30.23.png…]()

**Comment by wsy1991** [comment]
@Channingss 


Traceback (most recent call last):
  File "infer.py", line 370, in <module>
    run(gflags.FLAGS.conf, gflags.FLAGS.input_dir, gflags.FLAGS.ext)
  File "infer.py", line 352, in run
    seg_predictor.predict(imgs)
  File "infer.py", line 327, in predict
    self.output_result(img_datas, output_data, use_pr)
  File "infer.py", line 255, in output_result
    score_png[i, j] = color_map[score_png[i, j, 0]]
IndexError: list index out of range

**Comment by wuyefeilin** [comment]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.8.0/contrib/HumanSeg/nets/shufflenet_slim.py#L151
把这一行的3改成1，重新导出试试

**Comment by wsy1991** [comment]
可以了，非常感谢

**Comment by wsy1991** [comment]
@wuyefeilin    infer.py不报错了，但得到的seg结果，全黑。seg的结果是不正确的

**Comment by wuyefeilin** [comment]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.8.0/deploy/python/infer.py#L277 把这一行的0改成1试一下

另外给一下你的yml.

**Comment by wsy1991** [comment]
@wuyefeilin 可以了


Model: HumanSegLite
_Attributes:
  eval_metric: {}
  labels: []
  num_classes: 2
_ModelInputsOutputs:
  test_inputs:
  - - image
    - image
  test_outputs:
  - - pred
    - unsqueeze2_0.tmp_0
  - - logit
    - softmax_0.tmp_0
_init_params:
  class_weight: null
  ignore_index: 255
  num_classes: 2
  sync_bn: true
  use_bce_loss: false
  use_dice_loss: false
status: Infer
test_transforms:
- Resize:
    interp: LINEAR
    target_size:
    - 192
    - 192
- Normalize:
    mean:
    - 0.5
    - 0.5
    - 0.5
    std:
    - 0.5
    - 0.5
    - 0.5

**Comment by wsy1991** [comment]
Model: HumanSegLite
_Attributes:
  eval_metric: {}
  labels: []
  num_classes: 2
_ModelInputsOutputs:
  test_inputs:
  - - image
    - image
  test_outputs:
  - - pred
    - unsqueeze2_0.tmp_0
  - - logit
    - softmax_0.tmp_0
_init_params:
  class_weight: null
  ignore_index: 255
  num_classes: 2
  sync_bn: true
  use_bce_loss: false
  use_dice_loss: false
status: Infer
test_transforms:
- Resize:
    interp: LINEAR
    target_size:
    - 192
    - 192
- Normalize:
    mean:
    - 0.5
    - 0.5
    - 0.5
    std:
    - 0.5
    - 0.5
    - 0.5
@wuyefeilin 可以了

**Comment by wsy1991** [comment]
@wuyefeilin  cpp下如何修改呢
