### ISSUE TITLE
[Feature Request] Add support for npy format input

### ISSUE THREAD

**Issue by linhandev** [PaddlePaddle/PaddleSeg#671]
希望能在输入部分增加对npy格式数据的支持．
标签上用png一般都不会有问题，但是图片作为输入数据有数据范围和通道数量的限制．
- 通道限制
比如在医学影像领域，数据都是3D的，使用2D的网络处理时会希望可以增加到5通道或者7通道来扩大网络在3D方向上的感受野．在做卫星遥感处理的时候，在群里看到有反馈希望对多于3种传感器的数据放到一起进行处理，这样图片的３通道都是一个没法突破的限制．
-　数据范围限制
在rgb图像场景下数据范围基本都不会有问题，但是在一些灰度图，比如在医学影像场景下，CT的有效强度值大概分布在超过2048的区间，如果加上一些噪点范围可以超过1w．虽然在进行训练之前会进行去噪并用窗宽窗位的操作减小范围，但是0~255的范围还是比较小的．之前有看到过16bit的png，可能是一个可行的方向，不知道现在的pdseg是否支持．

总体来说直接增加npy格式的numpy数组支持可以给pdseg很大的灵活性，就我做的比较多的医学影像场景来说是十分有意义的．

个人认为可能在数据增强部分会引入一些问题，看代码一些操作是调包实现的，不知道能不能支持任意通道数和范围的的npy

**Comment by michaelowenliu** [comment]
@linhandev Hi, thanks a lot for your suggestions. PaddleSeg team will discuss mentioned features carefully and will add them in a future version. If you have a solution or idea to implement already, please feel free to let us know.

**Comment by linhandev** [comment]
之前我可能0.4版本左右的时候写过这个，现在肯定是merge不进去了，当时写的也比较简单，直接绕过了所有的数据增强．期待大佬们能加入新功能！
