### ISSUE TITLE
在配置/数据校验时（自定义图片），训练和验证的图片都显示通过，而测试图片显示读取失败？

### ISSUE THREAD

**Issue by sunhufei** [PaddlePaddle/PaddleSeg#674]
-----------------------------
3. Check test dataset...
100%|█████████████████████████████████████████████████████████████████
███████████████████████████████████████████| 1/1 [00:00<?, ?it/s]

PASS E:/dataset/test.txt DATASET.SEPARATOR check

NOT PASS dataset reading check
Failed to read 1 images

PASS DATASET.IMAGE_TYPE check

Doing max image size statistics:
max width and max height of images are (0,0)

PASS EVAL_CROP_SIZE check
satisfy current EVAL_CROP_SIZE: (2736,3648) >= max width and max height of images: (0,0)

Detailed error information can be viewed in detail.log file.

**Comment by lantudou** [comment]
错误提示为cv2没有读取到图片，你应该检查一下测试集的配置文件或者图片路径是否正确

**Comment by weiluonika** [comment]
我也是遇到这个问题 大佬解决了吗

**Comment by sunhufei** [comment]
解决了，数据集弄错了
