### ISSUE TITLE
请问一下，我在使用deeplabv3+的时候训练尺寸的大小为何影响较大

### ISSUE THREAD

**Issue by eddieheyutong** [PaddlePaddle/PaddleSeg#679]
在使用deeplabv3+时，原本的配置文件中默认 train crop size为769x769，我将这一配置改为512x1024会使miou下降3%左右，请问这是优化的问题吗还是什么问题呢

**Comment by nepeplwu** [comment]
@eddieheyutong `TRAIN_CROP_SIZE`中的第一位表示width，第二位表示height，所以应该是改为1024x512。另外，如果`TRAIN_CROP_SIZE`为1024x512，那么建议`EVAL_CROP_SIZE`设置为2048x1024
