### ISSUE TITLE
在PaddleSeg数据准备，LabelMe标注教程中所遇到的问题，无法生存对应的真值图片。

### ISSUE THREAD

**Issue by eddieheyutong** [PaddlePaddle/PaddleSeg#68]
我在看这个LabelMe教程的时候按照操作可以运行labelme2seg.py然后对文件夹中的事例图像“2011_000025.jpg”进行数据转换想要通过该图像和对应的.json文件生成像素真值图像，但是现在遇到的问题是我运行这个labelme2seg.py脚本后可以生成JPEGImages和SegmentationClassPNG这两个文件夹，以及class_names.txt这个文件，但是两个文件中没有文件生成，calssname中的类别名称也只有background一种，想知道一下这个是什么原因导致的？以下是我执行的代码和输出的结果：
执行命令：
python labelme2seg.py home/zhengyuan/PaddleSeg/docs/annotation/data_annotated/ output
终端的返回：
Creating dataset: output
class_names: ('_background_',)
Saved class_names: output/class_names.txt
然后这两个文件夹内为空，classnametxt类别名称只有background

**Comment by LutaoChu** [comment]
可能是用labelme标注生成的json不对。
请确认一下指定目录是否有对应的json文件。
json里是否有保存类别边缘坐标。正常的json是这样的：
![image](https://user-images.githubusercontent.com/30695251/67194432-ade7d900-f429-11e9-89c7-8d4c47b75e3f.png)

**Comment by LutaoChu** [comment]
你试一下将2011_000025.json和2011_000025.jpg放到一个新建文件夹里，再跑labelme2seg.py试试。
我这边测试是有真值图片的，命令如下，供参考
```~/code/PaddleSeg/docs/annotation$ python labelme2seg.py test/ ./data```

**Comment by zhaotun** [comment]
@LutaoChu 我利用精灵标注工具进行标注，并按照教程使用 jingling2seg.py 转换后，生成的PNG标注图片为啥是全黑的啊？是打开的方式不对吗？要怎样才能看到内容？这些图片是可以正常训练的。还有就是运行训练好的模型将对图片 L1.jpeg 进行检测 ，将在同目录下生成 L1_jpeg.png、L1_jpeg_recover.png、L1_jpeg_scoremap.png 三张图片，这三张图片里只有L1_jpeg_recover.png 与原图大小相同，这个可以直接当成原图的标注图片，从而参与训练吗？如果不是，那怎样才能通过模型生成可用于训练的标注图片，谢谢！

**Comment by LutaoChu** [comment]
你好，全黑是正常的。因为标注图片像素是0，1，2，3... 像素值很小，所以都是黑色的。若要彩色显示，需要写一个脚本，可参考pdseg/vis.py
我们正在开发彩色标注的功能，可直接以彩色图片显示，敬请期待！

关于L1.jpeg，L1_jpeg.png和L1_jpeg_scoremap.png 是经过resize的，L1_jpeg_recover.png是原图大小。你可以将 L1_jpeg.png  用最近邻插值resize回原图大小，就可以参与训练了。

**Comment by zhaotun** [comment]
@LutaoChu 非常感谢您的及时回复，我遍历了下像素值，发现确实是这样的，另外还想问一下就是，paddleseg 训练出来的分割模型还有没有什么加速的办法，谢谢！

**Comment by LutaoChu** [comment]
你是想训练过程加速还是预测过程加速呢？
如果是训练加速，可以打开--use_mpio
『如果在Linux系统下训练，可以使用--use_mpio使用多进程I/O，通过提升数据增强的处理速度进而大幅度提升GPU利用率。』
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.2.0/docs/usage.md

如果是预测加速，可以使用c++预测库

**Comment by zhaotun** [comment]
@LutaoChu  是预测加速，我用了C++预测库，但是还想提升一下速度，训练出来的分割模型可以用 paddle slim 量化或加速 吗？

**Comment by slf12** [comment]
> @LutaoChu 是预测加速，我用了C++预测库，但是还想提升一下速度，训练出来的分割模型可以用 paddle slim 量化或加速 吗？

分割模型可以使用paddle slim加速，可参考 paddleslim 量化分类模型 https://github.com/PaddlePaddle/models/tree/develop/PaddleSlim/classification/quantization 
量化检测模型 https://github.com/PaddlePaddle/PaddleDetection/tree/master/slim/quantization
以上两种是量化的高级api使用方法
量化的低级api使用方法可参考 https://github.com/PaddlePaddle/models/tree/develop/PaddleSlim/quant_low_level_api

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。
