### ISSUE TITLE
请问下ICNET的cfg.MODEL.ICNET.LAYERS设置为18后训练报错

### ISSUE THREAD

**Issue by xdhuang** [PaddlePaddle/PaddleSeg#685]
报错内容如下：
  File "PaddleSeg-0.6.0\pdseg\models\modeling\icnet.py", line 128, in resnet
    dilation_dict=dilation_dict)
ValueError: too many values to unpack (expected 2)

**Comment by nepeplwu** [comment]
@xdhuang 感谢反馈，这个问题我们将会在后续版本中修复。你现在使用的版本还是静态图版本，PaddleSeg目前已经支持动态图版本，并且实现了更多的优质模型，欢迎试用下：[PaddleSeg动态图](https://github.com/PaddlePaddle/PaddleSeg/tree/release/v0.8.0/dygraph)

**Comment by xdhuang** [comment]
动态图还不稳定无法落地吧

**Comment by xdhuang** [comment]
感谢您的答复，静态图这个问题解决也不难吧，先稳定一个版本再切换下个版本才是正途吧

**Comment by nepeplwu** [comment]
@xdhuang 

> 动态图还不稳定无法落地吧

目前无论是PadldlePaddle或者是PaddleSeg，动态图的功能都已经稳定可用了，我们将在这周就全面切换动态图版本

> 感谢您的答复，静态图这个问题解决也不难吧，先稳定一个版本再切换下个版本才是正途吧

ICNet的这个问题我们会在下周修复。

**Comment by nepeplwu** [comment]
@xdhuang 最新的release/v2.0.0-rc分支已经修复ICNet的问题，请更新到该分支尝试下
