### ISSUE TITLE
数据准备--使用精灵标注的像素级标注导出的文件如何转换

### ISSUE THREAD

**Issue by noirlyrik** [PaddlePaddle/PaddleSeg#689]
使用精灵标注的像素级项目标注，导出的json文件中没有多边形坐标点，但是有attachments文件夹，文件下有每一个类别的灰度图。尝试把attachments中的图片二值化后叠加，但是json中的类别顺序与attachments图片顺序不是对应的，并且叠加得到的图片有重叠，会有误差。请问如何进行格式转换？
```
# 导出json文件格式
outputs: {
  object:[
     name: 'insert'
  ]
}
...
attachments:[
   ...
  path:"/outputs/attachments/000000000580_1.png"
  file_name:"000000000580_1.png"
]
```
![image](https://user-images.githubusercontent.com/39143373/102313180-150c0980-3fab-11eb-809f-c47e06a7ec76.png)
![image](https://user-images.githubusercontent.com/39143373/102313236-35d45f00-3fab-11eb-9ce8-2c9883a5895c.png)
![image](https://user-images.githubusercontent.com/39143373/102314215-09b9dd80-3fad-11eb-9597-44f62986137d.png)

**Comment by LutaoChu** [comment]
请问attachments是标注工具自己产生的还是你创建的呢？
看起来是精灵标注导出格式变了。

**Comment by noirlyrik** [comment]
> 请问attachments是标注工具自己产生的还是你创建的呢？
> 看起来是精灵标注导出格式变了。

精灵标注生成的文件。我重新标注了。

**Comment by LutaoChu** [comment]
重新标注后问题解决了吗

**Comment by noirlyrik** [comment]
> 重新标注后问题解决了吗

重新标注后可以的，看了代码仅支持位置标注中使用多边形标注

**Comment by LutaoChu** [comment]
是的，只支持多边形标注，这种标注相对比较简单快捷。你用的是什么类型的标注呢

**Comment by noirlyrik** [comment]
> 是的，只支持多边形标注，这种标注相对比较简单快捷。你用的是什么类型的标注呢

像素级分割
![image](https://user-images.githubusercontent.com/39143373/102971016-890e5a80-4533-11eb-88b3-b49799b2c181.png)
