### ISSUE TITLE
动态图 develop 中bce_loss出错

### ISSUE THREAD

**Issue by Zhangfc682** [PaddlePaddle/PaddleSeg#691]
使用动态图unet做num_classes=2的训练，使用bce_loss出现错误。

You are using Paddle compiled with TensorRT, but TensorRT dynamic library is not found. Ignore this if TensorRT is not needed.2020-12-16 18:55:12 [INFO]	
------------Environment Information-------------
platform: Linux-4.4.0-150-generic-x86_64-with-debian-stretch-sid
Python: 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
Paddle compiled with cuda: True
NVCC: Cuda compilation tools, release 10.1, V10.1.243
cudnn: 7.6
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: Tesla V100-SXM2-32GB']
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
PaddlePaddle: 2.0.0-rc0
OpenCV: 4.1.1
------------------------------------------------
2020-12-16 18:55:12 [INFO]	
---------------Config Information---------------
batch_size: 4
iters: 4000
learning_rate:
  decay:
    end_lr: 0.0
    power: 0.9
    type: poly
  value: 0.1
loss:
  coef:
  - 1
  types:
  - ignore_index: 255
    type: BCELoss
model:
  num_classes: 2
  pretrained: null
  type: UNet
  use_deconv: false
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 4.0e-05
train_dataset:
  dataset_root: /home/aistudio/
  mode: train
  num_classes: 2
  train_path: ./png/train_list.txt
  transforms:
  - type: Resize
  - type: RandomHorizontalFlip
  - type: RandomVerticalFlip
  - max_rotation: 30
    type: RandomRotation
  - brightness_range: 0.2
    contrast_range: 0.2
    saturation_range: 0.2
    type: RandomDistort
  - crop_size:
    - 512
    - 512
    type: RandomPaddingCrop
  - type: Normalize
  type: Dataset
val_dataset:
  dataset_root: /home/aistudio/
  mode: val
  num_classes: 2
  transforms:
  - type: Normalize
  type: Dataset
  val_path: ./png/val_list.txt
------------------------------------------------
W1216 18:55:12.015664 23421 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 10.1
W1216 18:55:12.015722 23421 device_context.cc:346] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "./PaddleSeg/dygraph/train.py", line 141, in <module>
    main(args)
  File "./PaddleSeg/dygraph/train.py", line 136, in main
    losses=losses)
  File "/home/aistudio/PaddleSeg/dygraph/paddleseg/core/train.py", line 120, in train
    loss = loss_computation(logits, labels, losses)
  File "/home/aistudio/PaddleSeg/dygraph/paddleseg/core/train.py", line 46, in loss_computation
    loss_i = losses['types'][i](logit, label)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 829, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleSeg/dygraph/paddleseg/models/losses/binary_cross_entroy_loss.py", line 138, in forward
    pos_weight=self.pos_weight)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/loss.py", line 279, in binary_cross_entropy_with_logits
    out = core.ops.sigmoid_cross_entropy_with_logits(logit, label)
paddle.fluid.core_avx.EnforceNotMet: 
----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Input(X) and Input(Label) shall have the same shape except the last dimension. But received: the shape of Input(X) is [4, 2, 512, 512], the shape of Input(Label) is [4, 1, 512, 512].
  [Hint: Expected framework::slice_ddim(x_dims, 0, rank) == framework::slice_ddim(labels_dims, 0, rank), but received framework::slice_ddim(x_dims, 0, rank):4, 2, 512, 512 != framework::slice_ddim(labels_dims, 0, rank):4, 1, 512, 512.] (at /paddle/paddle/fluid/operators/sigmoid_cross_entropy_with_logits_op.cc:63)
  [operator < sigmoid_cross_entropy_with_logits > error]
terminate called without an active exception

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Process abort signal) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1608116116 (unix time) try "date -d @1608116116" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800005b7d) received by PID 23421 (TID 0x7f56a93cc700) from PID 23421 ***]

Aborted (core dumped)

**Comment by wuyefeilin** [comment]
多谢反馈， 我们这边会尽快解决这个问题

**Comment by wuyefeilin** [comment]
@Zhangfc682  已修复， 请更新最新的develop版本进行使用
