### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by stu166** [PaddlePaddle/PaddleSeg#699]
现在的这个感觉就是没法二次创作，在paddleSeg 下修改已有的模型难度太大了，没有torch那么好用 ，建议可以出一些经典的案例，从数据处理 ，到模型组网，到模型训练，再到模型评估，相信有了一些经典案例，会有越来越多人会在paddleSeg上进行二次修改。

**Comment by michaelowenliu** [comment]
@stu166 Hi, thanks for your suggestion. Did you try the new version of PaddleSeg, i.e. the dynamic graph version?
