### ISSUE TITLE
希望可以增加对多通道图像（遥感）读取的支持。

### ISSUE THREAD

**Issue by zjhellofss** [PaddlePaddle/PaddleSeg#700]
遥感图像处理是图像分割领域一个重要的应用，道路识别、云层识别、绿化覆盖区域识别都可以用图网络进行处理，但是遥感图像往往是多通道的，目前paddleSeg还不能满足要求。希望可以尽早增加对多通道图像的支持（可以由多张单通道图像组合而成，例如自然光、各种传感器）。

非常非常地感谢！！

**Comment by michaelowenliu** [comment]
@zjhellofss Hi, thanks for the new feature suggestion.
