### ISSUE TITLE
关于ICNet loss的问题

### ISSUE THREAD

**Issue by beichen2012** [PaddlePaddle/PaddleSeg#71]
弱弱问一下，论文中ICNet是用真值标签图像的1/16, 1/8，1/4作为监督信号的，工业检测中缩小16倍后图像上基本上什么缺陷也看不出来了。有没有人试过只使用一个分支的loss进行训练？或者是这里有什么要注意的吗？

**Comment by LielinJiang** [comment]
没有试过仅使用一个分支的loss来训练。使用1/16其实是融合了浅层特征的。其次缩小16倍后基本缺陷看不出来，这个是否有量化？比如说缺陷在缩小后的图像上的比例。感觉可以做实验试试，不过个人认为仅使用一个分支loss，效果可能不会太好。

**Comment by LielinJiang** [comment]
> 弱弱问一下，论文中ICNet是用真值标签图像的1/16, 1/8，1/4作为监督信号的，工业检测中缩小16倍后图像上基本上什么缺陷也看不出来了。有没有人试过只使用一个分支的loss进行训练？或者是这里有什么要注意的吗？

没有试过仅使用一个分支的loss来训练。使用1/16其实是融合了浅层特征的。其次缩小16倍后基本缺陷看不出来，这个是否有量化？比如说缺陷在缩小后的图像上的比例。感觉可以做实验试试，不过个人认为仅使用一个分支loss，效果可能不会太好。

**Comment by beichen2012** [comment]
> > 弱弱问一下，论文中ICNet是用真值标签图像的1/16, 1/8，1/4作为监督信号的，工业检测中缩小16倍后图像上基本上什么缺陷也看不出来了。有没有人试过只使用一个分支的loss进行训练？或者是这里有什么要注意的吗？
> 
> 没有试过仅使用一个分支的loss来训练。使用1/16其实是融合了浅层特征的。其次缩小16倍后基本缺陷看不出来，这个是否有量化？比如说缺陷在缩小后的图像上的比例。感觉可以做实验试试，不过个人认为仅使用一个分支loss，效果可能不会太好。

谢谢回复。
比如缺陷是5*5像素的，如果缩小16倍，即使使用float(0~1)，也难免给缩小没了？

**Comment by LielinJiang** [comment]
> > > 弱弱问一下，论文中ICNet是用真值标签图像的1/16, 1/8，1/4作为监督信号的，工业检测中缩小16倍后图像上基本上什么缺陷也看不出来了。有没有人试过只使用一个分支的loss进行训练？或者是这里有什么要注意的吗？
> > 
> > 
> > 没有试过仅使用一个分支的loss来训练。使用1/16其实是融合了浅层特征的。其次缩小16倍后基本缺陷看不出来，这个是否有量化？比如说缺陷在缩小后的图像上的比例。感觉可以做实验试试，不过个人认为仅使用一个分支loss，效果可能不会太好。
> 
> 谢谢回复。
> 比如缺陷是5*5像素的，如果缩小16倍，即使使用float(0~1)，也难免给缩小没了？

是这样的，不过感觉还是要看缺陷的大小和原图大小的比例。

**Comment by beichen2012** [comment]
> > > > 弱弱问一下，论文中ICNet是用真值标签图像的1/16, 1/8，1/4作为监督信号的，工业检测中缩小16倍后图像上基本上什么缺陷也看不出来了。有没有人试过只使用一个分支的loss进行训练？或者是这里有什么要注意的吗？
> > > 
> > > 
> > > 没有试过仅使用一个分支的loss来训练。使用1/16其实是融合了浅层特征的。其次缩小16倍后基本缺陷看不出来，这个是否有量化？比如说缺陷在缩小后的图像上的比例。感觉可以做实验试试，不过个人认为仅使用一个分支loss，效果可能不会太好。
> > 
> > 
> > 谢谢回复。
> > 比如缺陷是5*5像素的，如果缩小16倍，即使使用float(0~1)，也难免给缩小没了？
> 
> 是这样的，不过感觉还是要看缺陷的大小和原图大小的比例。

嗯。我用一个loss去训练PSPNet（res18），好像很难训练，loss都不怎么降。

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。
