### ISSUE TITLE
关于fast scnn 训练的问题

### ISSUE THREAD

**Issue by kymoran3169** [PaddlePaddle/PaddleSeg#725]
我使用分割套件在平台上训练fast scnn 出现了GPU利用率特别低的情况（CPU利用率，内存都还正常）
![image](https://user-images.githubusercontent.com/53987628/102868283-f60eeb00-4474-11eb-87ca-f31697cdaf5c.png)

**Comment by kymoran3169** [comment]
数据增强没有关，，，

**Comment by wuyefeilin** [comment]
可以开启 --use_mpio加快数据的读取
