### ISSUE TITLE
请教：labelme2seg.py支持labelme使用line进行标注的转换吗

### ISSUE THREAD

**Issue by zhuyushi** [PaddlePaddle/PaddleSeg#73]
使用labelme进行标注的时候，可以选择line类型，标注一个线段。labelme2seg.py支持这种类型标注的转换吗？谢谢。

**Comment by LutaoChu** [comment]
你好，亲测对line类型是支持的。
转换后的label图片中，线段大约具有7个像素左右的宽度。

**Comment by zhuyushi** [comment]
多谢
