### ISSUE TITLE
可以使用 paddle.distributed 分布式训练吗

### ISSUE THREAD

**Issue by ARQlalala** [PaddlePaddle/PaddleSeg#734]
hello，请教下，paddleseg 分支是否可以使用分布式训练呢，类似python -m paddle.distributed.launch --selected_gpus 0,1,2,3，

**Comment by wuyefeilin** [comment]
可以的， 使用方法请参考： 
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v2.0.0-rc/docs/quick_start.md#%E6%A8%A1%E5%9E%8B%E8%AE%AD%E7%BB%83

**Comment by ARQlalala** [comment]
好的，谢谢，这个是要用 paddleseg 的2.0分支，paddle 版本有什么要求吗

**Comment by wuyefeilin** [comment]
可以使用paddlepaddel-gpu==2.0.0rc1版本
