### ISSUE TITLE
关于data_aug.py中的检测数据的处理问题

### ISSUE THREAD

**Issue by kymoran3169** [PaddlePaddle/PaddleSeg#736]
![data_aug](https://user-images.githubusercontent.com/53987628/103077861-99920400-460b-11eb-8afa-409056ca9dfb.png)
这个部分是数据加载的 裁剪部分，从检测模式（不是训练模式）输入的角度来说，
如果图片小于预定尺寸进行了填充，为了修正填充结果进行了二次裁剪（这是我对这段代码的理解）
但是填充函数是在bottom，right（也就是下方和右方）进行填充，而修正的二次裁剪却是
crop_img = crop_img[h_off:(crop_height + h_off), w_off:( w_off + crop_width), :]
从左侧和上侧 进行的。
请问，这是为什么呢？或者是我错误理解了这下面部分函数的意义？

**Comment by wuyefeilin** [comment]
填充是因为图片尺寸小雨所需要的裁剪尺寸， 后面是随机裁剪。 当你进行填充的时候，其实后面的裁剪就是填充后的图，这时候h_off或w_off是等于0的

**Comment by wuyefeilin** [comment]
欢迎使用我们的动态图版本，动态图版本易用性和可读性都好很多

**Comment by kymoran3169** [comment]
好吧，我没有算出来hoff和woff是等于0，
我也想用动态图，实验都做完了，下一篇再说吧
