### ISSUE TITLE
请问如何获取可视化得到的类别坐标？

### ISSUE THREAD

**Issue by noirlyrik** [PaddlePaddle/PaddleSeg#739]
使用vis.py可视化得到的是图片，请问如何获取每个类别的坐标？使用canny边缘检测得到的是全部轮廓并且准确度也不高。

另外，如果是仅展示预测图片上的其中一个类别，其他类别都涂白，要怎么处理？

**Comment by wuyefeilin** [comment]
请问一下你怎么处理的目的是什么？ 是在什么场景下需要应用的？

**Comment by noirlyrik** [comment]
> 请问一下你怎么处理的目的是什么？ 是在什么场景下需要应用的？

在ocr中用到的，需要识别特定符号并获取位置

**Comment by wuyefeilin** [comment]
你看是否可以根据类别标签直接获取坐标呢？

仅预测一个类别的话，你可以进行二分类训练，目标标签为1，背景为0

**Comment by BeyondYourself** [comment]
@wuyefeilin    多类别，如何获取坐标呢

**Comment by wuyefeilin** [comment]
@BeyondYourself 能具体描述一下你的目的吗？有图像说明更好

**Comment by BeyondYourself** [comment]
![image](https://user-images.githubusercontent.com/12640462/109498710-cf9da980-7ace-11eb-9ebf-45f7841fdfc2.png)
![image](https://user-images.githubusercontent.com/12640462/109498753-dc220200-7ace-11eb-9c30-bde45c1a0c10.png)


@wuyefeilin 就比如这样的图片，用unet训练后，如何获取各个类别下的坐标值，不同颜色代表不同的类别。在训练的时候这些类别的坐标都是已知的

**Comment by wuyefeilin** [comment]
@BeyondYourself 训练的时候这些类别的坐标是什么样的？

**Comment by BeyondYourself** [comment]
@wuyefeilin 直线的坐标是两个端点，多边形是四点坐标

**Comment by wuyefeilin** [comment]
你这个情况比较复杂，需要经过一些后处理才能得到坐标，比如通过直线拟合， 四边形拟合之类的方法得到坐标。我觉你既然要得到坐标，可以换种思路，通过目标检测或者关键点检测的方法来满足你的需求。

**Comment by BeyondYourself** [comment]
好的，非常感谢你的解答

**Comment by BeyondYourself** [comment]
@wuyefeilin  能否利用unet将一张图上的多个分割类别图像作为一个fetch_list进行训练

**Comment by wuyefeilin** [comment]
这个跟多类别分割有什么区别呢？

**Comment by BeyondYourself** [comment]
主要是想获取各个多边形的坐标，最终拟合成为直线

**Comment by wuyefeilin** [comment]
你可以在输出的时候保留多个通道，然后每个通道单独拿出来做拟合就行了

**Comment by BeyondYourself** [comment]
好的，多谢大神指点
