### ISSUE TITLE
PaddleSeg训练可视化网址打不开

### ISSUE THREAD

**Issue by yy11223** [PaddlePaddle/PaddleSeg#750]
程序：
#训练可视化
!visualdl --logdir output/

运行结果：
VisualDL 2.0.3
Running VisualDL at http://localhost:8040/ (Press CTRL+C to quit)
Serving VisualDL on localhost; to expose to the network, use a proxy or pass --host 0.0.0.0

复制网址http://localhost:8040/ 在谷歌浏览器上打不开，错误显示：
无法访问此网站localhost 拒绝了我们的连接请求。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
ERR_CONNECTION_REFUSED

**Comment by nepeplwu** [comment]
@yy11223 你启动visualdl服务的机器和浏览器打开的机器是同一台吗

**Comment by yy11223** [comment]
是的，同一台



---原始邮件---
发件人: "wuzewu"<notifications@github.com&gt;
发送时间: 2020年12月31日(周四) 上午10:39
收件人: "PaddlePaddle/PaddleSeg"<PaddleSeg@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"yy11223"<928813176@qq.com&gt;;
主题: Re: [PaddlePaddle/PaddleSeg] PaddleSeg训练可视化网址打不开 (#750)




 
@yy11223 你启动visualdl服务的机器和浏览器打开的机器是同一台吗

**Comment by LISIJIA0629** [comment]
我也出现了同样问题，请问解决了嘛？xiexie
