### ISSUE TITLE
Fine-tune保存的模型如何转化为一个PaddleHub Module,    此时的模型是量化后的吗？

### ISSUE THREAD

**Issue by sunhufei** [PaddlePaddle/PaddleSeg#752]

**Comment by nepeplwu** [comment]
@sunhufei Finetune后的模型不是量化模型。可以参考[PaddleHub Module编写教程](https://github.com/PaddlePaddle/PaddleHub/blob/release/v2.0.0-beta/docs/docs_ch/contribution/contri_pretrained_model.md)进行转换

**Comment by sunhufei** [comment]
量化模型可以转化吗？

**Comment by nepeplwu** [comment]
@sunhufei 可以的
