### ISSUE TITLE
PaddleSeg跑cityscapes数据集的问题

### ISSUE THREAD

**Issue by yy11223** [PaddlePaddle/PaddleSeg#764]
#模型评估
!cd work/PaddleSeg && python pdseg/eval.py --use_gpu \
                     --cfg configs/deeplabv3p_mobilenetv3_large_cityscapes.yaml \
                     TEST.TEST_MODEL saved_model/deeplabv3p_mobilenetv3_large_cityscapes/best_model
运行结果：
[EVAL]#image=500 acc=0.9529 IoU=0.7251
[EVAL]Category IoU: [0.9779 0.8250 0.9087 0.4881 0.5561 0.5690 0.6265 0.7335 0.9160 0.6307 0.9382 0.7701 0.5423 0.9379 0.6543 0.7905 0.6180 0.5689 0.7254]
[EVAL]Category Acc: [0.9895 0.8980 0.9444 0.7817 0.7766 0.7893 0.8002 0.8743 0.9502 0.8188 0.9594 0.8514 0.7229 0.9655 0.8730 0.8536 0.8881 0.7644 0.8347]
问题：EVAL输出的的 acc和IoU是怎么计算的，是Category IoU和Category Acc的均值吗？我计算了IoU是均值，acc不是

**Comment by wuyefeilin** [comment]
acc ：预测正确的像素数/总像素数

**Comment by yy11223** [comment]
那[EVAL]#image=500 acc=0.9529 IoU=0.7251里的 IoU也不是平均指标是吧？

**Comment by wuyefeilin** [comment]
> 那[EVAL]#image=500 acc=0.9529 IoU=0.7251里的 IoU也不是平均指标是吧？

mIoU是取的各类的iou平均值

**Comment by yy11223** [comment]
程序输出是IoU，意思其实是mIoU是吧？

**Comment by wuyefeilin** [comment]
> 程序输出是IoU，意思其实是mIoU是吧？

是的， 我们在新版本动态图已经进行了相应的规范，欢迎使用我们的动态图版本
