### ISSUE TITLE
PaddleSeg跑cityscapes数据集的问题

### ISSUE THREAD

**Issue by yy11223** [PaddlePaddle/PaddleSeg#765]
yaml文件：
EVAL_CROP_SIZE: (4096, 2048) # (width, height), for unpadding rangescaling and stepscaling
TRAIN_CROP_SIZE: (769, 769) # (width, height), for unpadding rangescaling and stepscaling
AUG:
    AUG_METHOD: "stepscaling" # choice unpadding rangescaling and stepscaling
    MAX_SCALE_FACTOR: 2.0  # for stepscaling
    MIN_SCALE_FACTOR: 0.5  # for stepscaling
    SCALE_STEP_SIZE: 0.25  # for stepscaling
    MIRROR: True
示例显示：EVAL_CROP_SIZE的宽高应不小于原图中最大的宽和高怎么理解呢？我选EVAL_CROP_SIZE: (4096, 2048) 为何会报错？或者我能选用哪些值呢？

**Comment by wuyefeilin** [comment]
EVAL_CROP_SIZE的宽高应不小于原图中最大的宽和高， 是指EVAL_CROP_SIZE[0]应该大于你数据集中最大的宽，EVAL_CROP_SIZE[1]应该大于你数据集中最大的高
