### ISSUE TITLE
在windows运行paddleseg时，IoU和Acc全是0

### ISSUE THREAD

**Issue by Taoboan1999** [PaddlePaddle/PaddleSeg#766]
load test model: ./saved_model/unet_covid/2
[EVAL]#image=0 acc=0.0000 IoU=0.0000
[EVAL]Category IoU: [0 0]
[EVAL]Category Acc: [0 0]
[EVAL]Kappa:nan
这是为什么呢

**Comment by haoyuying** [comment]
您好，请将具体执行的模型和脚本发给我们，方便复现问题。

**Comment by Taoboan1999** [comment]
> 执行

我是在windows本地运行的alstudio上的一个模型

**Comment by haoyuying** [comment]
请给我们一个可以复现问题的环境，方便我们为您解决问题，如果是我们提供的模型，请指出模型具体的名称和运行的paddle及paddleseg的环境，如果是自己搭建的模型，请给我们能够复现的aistudio链接地址，感谢您的配合。

**Comment by Taoboan1999** [comment]
> 请给我们一个可以复现问题的环境，方便我们为您解决问题，如果是我们提供的模型，请指出模型具体的名称和运行的paddle以及paddleseg的环境，如果是自己建造的模型，请给我们能够复现的aistudio链接地址，感谢您的配合。

您可以加我qq 2097383526私聊吗
我是在windows本地复现的，可能需要teamviewver帮助

**Comment by haoyuying** [comment]
请您加paddleseg的qq群提问850378321，看相关同学是否遇到相同的问题。

**Comment by Taoboan1999** [comment]
> 请您加paddleseg的qq群提问850378321，看相关同学是否遇到相同的问题。

我问过了，没人理我

**Comment by haoyuying** [comment]
再发一次问题吧，技术同学没看到您的问题，或者aistudio能复现吗，可以把aistudio公开链接发给我们，不然这样描述无法复现问题。

**Comment by haoyuying** [comment]
同学加你了

**Comment by Taoboan1999** [comment]
> 同学加你了
不好意思，我的qq今天出了点儿问题，明天再跟您联系吧
