### ISSUE TITLE
from test_utils import download_file_and_uncompress 错误，要安装什么包？

### ISSUE THREAD

**Issue by lguowang** [PaddlePaddle/PaddleSeg#768]
from test_utils import download_file_and_uncompress 错误，要安装什么包？
Traceback (most recent call last):
  File "dataset/download_optic.py", line 23, in <module>
    from test_utils import download_file_and_uncompress
ImportError: cannot import name 'download_file_and_uncompress'

**Comment by wuyefeilin** [comment]
看样子是你的路径问题，找不到对应的函数，请问你是在哪个目录下运行什么命令导致的错误

**Comment by lguowang** [comment]
PaddleSeg 目录下执行：python3 dataset/download_optic.py

我 git clone -b  release/0.7.0   https://github.com/PaddlePaddle/PaddleSeg.git

**Comment by wuyefeilin** [comment]
我这边能够正常下载，无法复现你的情况， 请问你是在什么环境下执行的
