### ISSUE TITLE
关于自定义数据集的训练问题

### ISSUE THREAD

**Issue by ChaunceySun7** [PaddlePaddle/PaddleSeg#770]
我通过修改configs里的配置文件unet_cityscapes_1024x512_160k.yml以及cityscapes.yml来训练自定义数据集时会报错，请问教程中的自定义数据集训练的配置文件有没有更完整的示例？

**Comment by wuyefeilin** [comment]
若你要按照标准数据集的方式对自定义数据集进行使用，需要把自定义数据集按照标准数据集的目录结构进行整理。

我们提供了对自定义数据集的使用文档，请参考链接https://github.com/PaddlePaddle/PaddleSeg/blob/release/v2.0.0-rc/docs/data_prepare.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E9%9B%86
