### ISSUE TITLE
训练时使用--do_eval进行验证时直接退出程序

### ISSUE THREAD

**Issue by QinchengZhang** [PaddlePaddle/PaddleSeg#772]
控制台输出:
2021-01-12 23:24:14 [INFO]      [TRAIN] epoch=1, iter=10/1000, loss=2.3988, lr=0.009919, batch_cost=0.2232, reader_cost=0.0174 | ETA 00:03:40
2021-01-12 23:24:14 [INFO]      Start evaluating (total_samples=76, total_iters=76)...
76/76 [==============================] - 2s 26ms/step - batch_cost: 0.0252 - reader cost: 4.6070e-04
在验证过程进度条满之后直接退出程序，我在进行debug时发现问题出现在core/val.py中for iter, (im, label) in enumerate(loader):这一句，在最后一遍循环时直接退出程序，没有任何报错信息

**Comment by wuyefeilin** [comment]
请给一下你运行的环境信息以及Paddle和PaddleSeg等版本信息

**Comment by GitHubyu007** [comment]
我也出现过这个问题：Process finished with exit code -1073741819 (0xC0000005) ，报错这个代码然后直接结束验证。
 解决方法：重新配置paddleSeg的环境：直接在pycharm 点击requirements.txt  然后install ,后面缺什么就pip 相应的。
注意的是：出现这个bug的原因是我配置环境直接pip install -r requirements.txt（清华源） 。
对比两个安装方法：1、pycharm+ pip缺的包  2、pip install -r requirements.txt 。发现1、方法pip show tqdm 是没有的，而2方法pip show tqdm 是有的。  怀疑装的tqdm 有影响？ 具体不知道
