### ISSUE TITLE
关于PaddleSeg2.0部署

### ISSUE THREAD

**Issue by AlexDish** [PaddlePaddle/PaddleSeg#773]
**请问 PaddleSeg2.0有没有部署说明介绍？**
目前使用PaddlesClas2.0+PaddleHub2.0的在线部署挺方便的。
https://github.com/PaddlePaddle/PaddleClas/tree/dygraph/deploy/hubserving
**PaddleSeg2.0可以像PaddleClass的那样使用？**

**Comment by nepeplwu** [comment]
@AlexDish 感谢反馈，相关部署能力正在开发中

**Comment by AlexDish** [comment]
好的，能否告知一下大概发布时间。好让我们的项目做一下安排，谢谢了。

**Comment by CeciliaPYY** [comment]
现在动态图怎么像之前legacy下面静态图那样部署啊？

**Comment by AlexDish** [comment]
请问完全了吗？

**Comment by Harryoung** [comment]
请问这个是否满足你的需求？
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/docs/deployment/serving/serving.md
