### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by yy11223** [PaddlePaddle/PaddleSeg#776]
yaml:
!export CUDA_VISIBLE_DEVICES=0 # 设置1张可用的卡
# windows下请执行以下命令
!set CUDA_VISIBLE_DEVICES=0
!cd work/PaddleSeg && python pdseg/train.py \
       --cfg configs/deeplabv3p_resnet50_vd_cityscapes.yaml \
       --use_gpu \
       --do_eval \
运行结果：
You are using Paddle compiled with TensorRT, but TensorRT dynamic library is not found. Ignore this if TensorRT is not needed.
Traceback (most recent call last):
  File "pdseg/train.py", line 468, in <module>
    main(args)
  File "pdseg/train.py", line 444, in main
    cfg.update_from_list(args.opts)
  File "/home/aistudio/work/PaddleSeg/pdseg/utils/collect.py", line 140, in update_from_list
    format(config_list))
ValueError: Command line options config format error! Please check it: ['\\']
为何用有的骨干网络不会报错，有的会报错

**Comment by haoyuying** [comment]
您好，请问您使用的paddleseg的版本是动态图版本吗，建议使用paddleseg2.0动态图版本和我们提供的配置参数,参考配置如下：
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v2.0.0-rc/configs/deeplabv3p/deeplabv3p_resnet50_os8_cityscapes_1024x512_80k.yml

**Comment by yy11223** [comment]
_base_: '../_base_/cityscapes.yml'

batch_size: 2
iters: 800

model:
  type: DeepLabV3P
  backbone:
    type: ResNet50_vd
    output_stride: 8
    multi_grid: [1, 2, 4]
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  num_classes: 19
  backbone_indices: [0, 3]
  aspp_ratios: [1, 12, 24, 36]
  aspp_out_channels: 256
  align_corners: False
  pretrained: null
这个类型的yaml在哪里设置参数呢？比如输入数据集标签位置

**Comment by yy11223** [comment]
您好，
效果可视化
当保存完模型后，可以通过PaddleSeg提供的脚本对模型预测结果进行可视化，查看分割效果。

python predict.py \
       --config configs/quick_start/bisenet_optic_disc_512x512_1k.yml \
       --model_path output/iter_1000/model.pdparams \
       --image_path data/optic_disc_seg/JPEGImages/H0003.jpg \
       --save_dir output/result
其中image_path也可以是一个目录，这时候将对目录内的所有图片进行预测并保存可视化结果图。

我设置image_path为一个目录，出错：
File "predict.py", line 172, in <module>
    main(args)
  File "predict.py", line 166, in main
    stride=args.stride,
  File "/home/aistudio/work/PaddleSeg/paddleseg/core/predict.py", line 78, in predict
    ori_shape = im.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
请问如果可视化为一个目录，怎么改程序呢？

**Comment by haoyuying** [comment]
您好，--image_path data/optic_disc_seg/JPEGImages 这样尝试仍然会报错吗，这个报错原因是没有输入图片导致的，im应该是个空，所以才会报错。可以打印出https://github.com/PaddlePaddle/PaddleSeg/blob/release/v2.0.0-rc/predict.py#L151的输出，看看图片是否传入正确。
