### ISSUE TITLE
能否介绍一下代码的目录结构呢

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleSeg#781]
刚开始接触这部分代码，看了半天有点不清楚seg的代码目录结构。有清楚的可以帮我讲解一下吗

**Comment by michaelowenliu** [comment]
@BeyondYourself https://aistudio.baidu.com/aistudio/projectdetail/1136799

**Comment by BeyondYourself** [comment]
谢谢 @michaelowenliu
