### ISSUE TITLE
人像分割模型转换为nb模型，使用Paddle-Lite加载报错

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PaddleSeg#782]
Paddle-Lite：2.7.1

使用的是这个三个模型，这三个我都试过了，加载就报错。
https://github.com/PaddlePaddle/PaddleSeg/tree/release/v2.0.0-rc/legacy/contrib/HumanSeg

转换模型代码：
```python
from paddlelite.lite import *

# 1. 创建opt实例
opt = Opt()
# 2. 指定输入模型地址
opt.set_model_file("output/inference_model/__model__")
opt.set_param_file("output/inference_model/__params__")
# 3. 指定转化类型： arm、x86、opencl、xpu、npu
opt.set_valid_places("arm")
# 4. 指定模型转化类型： naive_buffer、protobuf
opt.set_model_type("naive_buffer")
# 4. 输出模型地址
opt.set_optimize_out("output/model")
# 5. 执行模型优化
opt.run()

```

Paddle-Lite-Demo这个模型不满足预想效果：
https://github.com/PaddlePaddle/Paddle-Lite-Demo/blob/c7c1ce31a833e2522470bda5a430774d595dd197/PaddleLite-android-demo/human_segmentation_demo/app/build.gradle#L83

**Comment by wuyefeilin** [comment]
你好，麻烦给一下具体的报错信息？

**Comment by yeyupiaoling** [comment]
@wuyefeilin 沒有报任何错误，应用直接闪退。
