### ISSUE TITLE
求问怎么finetune模型deeplabv3p_xception65_humanseg

### ISSUE THREAD

**Issue by juzuo** [PaddlePaddle/PaddleSeg#783]
通过hub install deeplabv3p_xception65_humanseg==1.1.1安装了deeplabv3p_xception65_humanseg。因为deeplabv3p_xception65_humanseg这个模型对我的数据效果比较好，所以我打算用这个模型当pretrained_weights，想对它进行finetune。
请看这个教程：https://aistudio.baidu.com/aistudio/projectdetail/475345
这里的HumanSeg-server和deeplabv3p_xception65_humanseg应该是相同的模型，于是我把
!python train.py --model_type HumanSegServer
--save_dir output/
--data_dir data/mini_supervisely
--train_list data/mini_supervisely/train.txt
--val_list data/mini_supervisely/val.txt
--pretrained_weights pretrained_weights/humanseg_server_ckpt
--batch_size 8
--learning_rate 0.001
--num_epochs 10
--image_shape 512 512
改成了：
!python train.py --model_type HumanSegServer
--save_dir output/
--data_dir data/mini_supervisely
--train_list data/mini_supervisely/train.txt
--val_list data/mini_supervisely/val.txt
--pretrained_weights ~/.paddlehub/modules/deeplabv3p_xception65_humanseg/deeplabv3p_xception65_humanseg_model/
--batch_size 8
--learning_rate 0.001
--num_epochs 10
--image_shape 512 512
这么改了也能训练，但是出来的miou只有0.3。所以请帮我看下这样做对吗？附件是训练输出。
[output.txt](https://github.com/PaddlePaddle/PaddleSeg/files/5813374/output.txt)

**Comment by wuyefeilin** [comment]
pretrained_weights/humanseg_server_ckpt， ~/.paddlehub/modules/deeplabv3p_xception65_humanseg/deeplabv3p_xception65_humanseg_model/ 这两个模型分别是从哪里下载的，麻烦给一下链接

**Comment by juzuo** [comment]
@wuyefeilin 你好，是通过hub install deeplabv3p_xception65_humanseg==1.1.1安装的啊。安装好之后在~/.paddlehub/modules目录下就有这个模型了。

**Comment by wuyefeilin** [comment]
你把两者的训练日志都给我一下

**Comment by juzuo** [comment]
@wuyefeilin 好的，麻烦问一下训练日志在哪存放？还是只要屏幕上的输出就可以？新手，轻拍。。

**Comment by wuyefeilin** [comment]
屏幕上输出就行了，或者在命令的最后面增加一个 > train.log 进行重定向就行了

**Comment by juzuo** [comment]
[output_humansegserver.txt](https://github.com/PaddlePaddle/PaddleSeg/files/5833516/output_humansegserver.txt)
收到，请看这个附件，这个是finetune humanseg_server_ckpt的训练输出。
最开始粘的那个输出是finetune deeplabv3p_xception65_humanseg的训练输出。
请查看。谢谢！@wuyefeilin

**Comment by wuyefeilin** [comment]
看起来没问题，应该是不同的预训练模型对你的这个数据集效用不一样

**Comment by juzuo** [comment]
好吧，多谢了。
