### ISSUE TITLE
自定义数据集在执行python pdseg/check.py --cfg ./configs/unet_optic.yaml

### ISSUE THREAD

**Issue by yanzhuangzhuang123** [PaddlePaddle/PaddleSeg#786]

**Comment by yanzhuangzhuang123** [comment]
NOT PASS label format check
2021-01-15 19:55:27,359-INFO: No label image to check
No label image to check
2021-01-15 19:55:27,365-INFO:
PASS DATASET.IMAGE_TYPE check
请问如何解决呀？

**Comment by LutaoChu** [comment]
这个日志说明没有检测到标注图片，请检查一下自定义数据集是否符合PaddleSeg的规范。另外命令行只显示校验结果的概览信息，详细的错误信息可到detail.log文件中查看
