### ISSUE TITLE
Cityscapes数据集的labelTrainIds文件怎么转成彩色图可视输出呢？

### ISSUE THREAD

**Issue by yy11223** [PaddlePaddle/PaddleSeg#787]

**Comment by LutaoChu** [comment]
可以参考这个教程  https://github.com/PaddlePaddle/PaddleSeg/blob/develop/legacy/docs/data_prepare.md#%E7%81%B0%E5%BA%A6%E6%A0%87%E6%B3%A8%E8%BD%AC%E6%8D%A2%E4%B8%BA%E4%BC%AA%E5%BD%A9%E8%89%B2%E6%A0%87%E6%B3%A8

另外如果只是想看标注图片的彩色效果，cityscapes自带以“_color.png”结尾的图片就可以看了，例如bochum_000000_000313_gtFine_color.png

**Comment by yy11223** [comment]
好的，谢谢，我下载的Cityscapes数据集训练过程可视化的时候，看到标签图片和原Cityscapes数据集的标注（_gtFine_color.png）颜色不一样，请问在release/v0.8.0这个版本，类似
name |  id | trainId |       category | categoryId | hasInstances | ignoreInEval|        color
    --------------------------------------------------------------------------------------------------
                unlabeled |   0 |     255 |           void |          0 |            0 |            1 |         (0, 0, 0)
              ego vehicle |   1 |     255 |           void |          0 |            0 |            1 |         (0, 0, 0)
     rectification border |   2 |     255 |           void |          0 |            0 |            1 |         (0, 0, 0)
               out of roi |   3 |     255 |           void |          0 |            0 |            1 |         (0, 0, 0)
                   static |   4 |     255 |           void |          0 |            0 |            1 |         (0, 0, 0)
                  dynamic |   5 |     255 |           void |          0 |            0 |            1 |      (111, 74, 0)
                   ground |   6 |     255 |           void |          0 |            0 |            1 |       (81, 0, 81)
分类的程序在哪里可以查看呢？

**Comment by LutaoChu** [comment]
是这样的，PaddleSeg没有用cityscapes的调色板，为了更通用，使用的是另一套调色板，可支持任意数量的类别。源码见
https://github.com/PaddlePaddle/PaddleSeg/blob/9e58f1765b94e914ce5cff98f7a4e82a4ff0de21/dygraph/paddleseg/utils/visualize.py#L65
如果你想用cityscapes的调色板，可以改写get_color_map_list这个函数

**Comment by yy11223** [comment]
想看PaddleSeg调色板每类的具体像素值，怎么看呢？visualize.py里只是一行程序，看不懂

**Comment by LutaoChu** [comment]
运行一下就明白了
```
print(get_color_map_list(256))
```

将返回256种颜色，每种颜色以3元组构成，例如第1类的颜色对应前面3个数值

**Comment by yy11223** [comment]
您好，运行print(get_color_map_list(256))后得到的是256种颜色的像素值，我只想要分类19类相应颜色对应的像素值又怎么看呢？

**Comment by LutaoChu** [comment]
你好，PaddleSeg默认分类256种，想要看分类19类的像素值的话就看前面19*3个数值即可

**Comment by Yuuhooow** [comment]
你好.之前发的那个链接失效了.还有其他的可视化教程吗.最好能直接适用于cityscapes

**Comment by LutaoChu** [comment]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/legacy/docs/data_prepare.md
2.2版本的链接还在
