### ISSUE TITLE
pred = pred[:, :, 0:h, 0:w]为什么

### ISSUE THREAD

**Issue by belovingu** [PaddlePaddle/PaddleSeg#788]
def reverse_transform(pred, ori_shape, transforms):
    """recover pred to origin shape"""
    reverse_list = get_reverse_list(ori_shape, transforms)
    for item in reverse_list[::-1]:
        if item[0] == 'resize':
            h, w = item[1][0], item[1][1]
            pred = F.interpolate(pred, (h, w), mode='nearest')
        elif item[0] == 'padding':
            h, w = item[1][0], item[1][1]
            pred = pred[:, :, 0:h, 0:w]
        else:
            raise Exception("Unexpected info '{}' in im_info".format(item[0]))
    return pred
中为什么pred = pred[:, :, 0:h, 0:w]，原来padding不是四周都有吗，现在为什么不还原为中间的部分？

**Comment by wuyefeilin** [comment]
在数据增强的时候，padding是针对右下角的。所以还原的时候去了左上角的
