### ISSUE TITLE
通过离线量化产出的推理模型为何不可以进行paddlehub封装？？？？？？求哥哥姐姐们传授一下经验？

### ISSUE THREAD

**Issue by sunhufei** [PaddlePaddle/PaddleSeg#794]
import os
import cv2
import os.path as osp
import tqdm
import numpy as np
from paddle.fluid.core import AnalysisConfig, PaddleTensor
from paddle.fluid.core import create_paddle_predictor

#设置模型的路径
model = "/home/aistudio/HumanSeg/koutu/HumanSeg/out/out1/__model__"
params = "/home/aistudio/HumanSeg/koutu/HumanSeg/out/out1/__params__"
#使用AnalysisConfig对模型进行配置
config = AnalysisConfig(model,params)
config.disable_gpu() #关闭GPU使用CPU进行推理
config.enable_mkldnn() #启用MKLDNN加速
config.disable_glog_info() #禁用预测中的glog日志
config.switch_use_feed_fetch_ops() #删去feed 和 fetchops op

#使用create_paddle_predictor创建模型预测器。
predictor = create_paddle_predictor(config)
#获取模型的输入输出向量
input_names = predictor.get_input_names()
output_names = predictor.get_output_names()
input_tensor = predictor.get_input_tensor(input_names[0])
output_tensor = predictor.get_output_tensor(output_names[0])
#准备输入数据
inputs = np.random.randn(1,3,600,800).astype("float32")
input_tensor.copy_from_cpu(inputs)
#运行预测器执行前向运算
predictor.zero_copy_run()
#获取输出数据
output_data = output_tensor.copy_to_cpu()
print(output_data)

InvalidArgumentError: The column index of current feeding variable is expected to be less than the length of feeding list. But received column index = 0, the length of feeding list = 0
  [Hint: Expected static_cast<size_t>(col) < feed_list.size(), but received static_cast<size_t>(col):0 >= feed_list.size():0.] at (D:\1.8.5\paddle\paddle\fluid\operators\controlflow\feed_op.cc:68)
  [operator < feed > error]

**Comment by haoyuying** [comment]
尝试下这样是否可以：
```
import os
import cv2
import os.path as osp
import tqdm
import numpy as np
from paddle.fluid.core import AnalysisConfig, PaddleTensor
from paddle.fluid.core import create_paddle_predictor

#设置模型的路径
model = "/home/aistudio/HumanSeg/koutu/HumanSeg/out/out1/model"
params = "/home/aistudio/HumanSeg/koutu/HumanSeg/out/out1/params"
#使用AnalysisConfig对模型进行配置
config = AnalysisConfig(model,params)
config.disable_gpu() #关闭GPU使用CPU进行推理
config.enable_mkldnn() #启用MKLDNN加速
config.disable_glog_info() #禁用预测中的glog日志
config.switch_use_feed_fetch_ops() #删去feed 和 fetchops op

#使用create_paddle_predictor创建模型预测器。
predictor = create_paddle_predictor(config)

#准备输入数据
inputs = np.random.randn(1,3,600,800).astype("float32")
inputs = PaddleTensor(inputs.copy())
#运行预测器执行前向运算
output = predictor.run([inputs])
#获取输出数据
output_data = output[0].as_ndarray()
print(output_data)
```
如果你想尝试包一个hub module，可以参考https://github.com/PaddlePaddle/PaddleHub/tree/release/v2.0.0-rc/modules/image/semantic_segmentation/humanseg_mobile
这是一个人像分割的模型

**Comment by haoyuying** [comment]
尝试下这样是否可以：
```
import os
import cv2
import os.path as osp
import tqdm
import numpy as np
from paddle.fluid.core import AnalysisConfig, PaddleTensor
from paddle.fluid.core import create_paddle_predictor

#设置模型的路径
model = "/home/aistudio/HumanSeg/koutu/HumanSeg/out/out1/model"
params = "/home/aistudio/HumanSeg/koutu/HumanSeg/out/out1/params"
#使用AnalysisConfig对模型进行配置
config = AnalysisConfig(model,params)
config.disable_gpu() #关闭GPU使用CPU进行推理
config.enable_mkldnn() #启用MKLDNN加速
config.disable_glog_info() #禁用预测中的glog日志
config.switch_use_feed_fetch_ops(False) #删去feed 和 fetchops op

#使用create_paddle_predictor创建模型预测器。
predictor = create_paddle_predictor(config)
#获取模型的输入输出向量
input_names = predictor.get_input_names()
input_tensor = predictor.get_input_tensor(input_names[0])
#准备输入数据
inputs = np.random.randn(1,3,600,800).astype("float32")
input_tensor.copy_from_cpu(inputs)
#运行预测器执行前向运算
predictor.zero_copy_run()
#获取输出数据
output_names = predictor.get_output_names()
output_tensor = predictor.get_output_tensor(output_names[0])
output_data = output_tensor.copy_to_cpu() # numpy.ndarray类型
print(output_data.shape)
```
或者
```
import os
import cv2
import os.path as osp
import tqdm
import numpy as np
from paddle.fluid.core import AnalysisConfig, PaddleTensor
from paddle.fluid.core import create_paddle_predictor

#设置模型的路径
model = "/home/aistudio/HumanSeg/koutu/HumanSeg/out/out1/model"
params = "/home/aistudio/HumanSeg/koutu/HumanSeg/out/out1/params"
#使用AnalysisConfig对模型进行配置
config = AnalysisConfig(model,params)
config.disable_gpu() #关闭GPU使用CPU进行推理
config.enable_mkldnn() #启用MKLDNN加速
config.disable_glog_info() #禁用预测中的glog日志
config.switch_use_feed_fetch_ops() #删去feed 和 fetchops op

#使用create_paddle_predictor创建模型预测器。
predictor = create_paddle_predictor(config)

#准备输入数据
inputs = np.random.randn(1,3,600,800).astype("float32")
inputs = PaddleTensor(inputs.copy())
#运行预测器执行前向运算
output = predictor.run([inputs])
#获取输出数据
output_data = output[0].as_ndarray()
print(output_data)
```
如果你想尝试包一个hub module，可以参考https://github.com/PaddlePaddle/PaddleHub/tree/release/v2.0.0-rc/modules/image/semantic_segmentation/humanseg_mobile
这是一个人像分割的模型
