### ISSUE TITLE
[2.0.0-rc]使用predict.py预测时模型加载报错。

### ISSUE THREAD

**Issue by whjdark** [PaddlePaddle/PaddleSeg#797]
File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
ValueError: (InvalidArgument) Deserialize to tensor failed, maybe the loaded file is not a paddle model(expected file format: 0, but 1904018048 found).
  [Hint: Expected version == 0U, but received version:1904018048 != 0U:0.] (at /paddle/paddle/fluid/framework/lod_tensor.cc:313)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
  [operator < load > error]

模型： deeplabV3p-resnet50v2
checkpoints可以恢复训练, 但是predict.py预测时报错。

**Comment by cncowboy** [comment]
我也遇到一样的问题，--model_path指定model.pdparams路径，就好了
