### ISSUE TITLE
请问一下，PaddleSeg现在在Cityscapes数据集上精度最高的是哪个模型呢？

### ISSUE THREAD

**Issue by songyuc** [PaddlePaddle/PaddleSeg#809]
尊敬的开发者，你好，
请问一下，PaddleSeg现在在Cityscapes数据集上精度最高的是哪个模型呢？

期待你的回复！

**Comment by michaelowenliu** [comment]
@songyuc Hi, Please refer to https://arxiv.org/pdf/2101.06175.pdf and https://github.com/PaddlePaddle/PaddleSeg/tree/release/v2.0.0-rc/configs/ocrnet

**Comment by LutaoChu** [comment]
是的，目前最高的是OCRNet。

马上要开源 Hierarchical Multi-Scale Attention for Semantic Segmentation，精度更高，敬请期待！
https://arxiv.org/abs/2005.10821

**Comment by songyuc** [comment]
@LutaoChu ，请问一下，这个模型大概什么时候出来呢，有具体的时间表吗？

**Comment by LutaoChu** [comment]
大概2月中到2月底

**Comment by songyuc** [comment]
好的，谢谢两位老师的回复！

**Comment by LutaoChu** [comment]
@songyuc 你好，更高的模型已经出来了，请见https://github.com/PaddlePaddle/PaddleSeg/tree/develop/contrib/CityscapesSOTA
