### ISSUE TITLE
labelme2seg.py工具生成的png文件是全黑的

### ISSUE THREAD

**Issue by zhuyushi** [PaddlePaddle/PaddleSeg#81]
您好，我使用labelme进行标注，然后使用labelme2seg.py生成数据集，但是生成的png文件打开之后是全黑的，看不到标注的物体，麻烦帮忙看看原因，谢谢。

下面附上labelme生成的json文件：
{
  "version": "3.16.7",
  "flags": {},
  "shapes": [
    {
      "label": "test",
      "line_color": null,
      "fill_color": null,
      "points": [
        [
          130.10619469026545,
          275.87610619469024
        ],
        [
          261.0796460176991,
          419.2389380530973
        ],
        [
          492.9380530973451,
          430.74336283185835
        ],
        [
          507.98230088495563,
          297.99999999999994
        ],
        [
          348.6902654867256,
          183.84070796460176
        ],
        [
          191.16814159292034,
          236.93805309734512
        ]
      ],
      "shape_type": "polygon",
      "flags": {}
    },
    {
      "label": "ttt",
      "line_color": null,
      "fill_color": null,
      "points": [
        [
          211.52212389380526,
          482.9557522123893
        ],
        [
          247.80530973451323,
          602.4247787610619
        ],
        [
          412.4070796460177,
          623.6637168141592
        ],
        [
          446.0353982300884,
          513.929203539823
        ],
        [
          425.68141592920347,
          459.9469026548672
        ],
        [
          262.84955752212386,
          460.8318584070796
        ]
      ],
      "shape_type": "polygon",
      "flags": {}
    }
  ],
  "lineColor": [
    0,
    255,
    0,
    128
  ],
  "fillColor": [
    255,
    0,
    0,
    128
  ],
  "imagePath": "6.jpg",
  "imageData": "太多，省略",
  "imageHeight": 694,
  "imageWidth": 685
}

**Comment by wuyefeilin** [comment]
@zhuyushi 生成的标注图像的数值是从0，1，2，...开始的。因此直接用图像浏览器打开，显示全黑的是正常的，你可以尝试读取标注数据，看看是否有包含这些标签值

**Comment by zhuyushi** [comment]
再请教一下：
1、labelme2seg.py生成数据集中没有list文件（例如train.list、val.list等），这些list文件是必要的吗？如果是必要的，是否用工具可以生成这些文件，或者是否有工具生成完成的数据集。
2、png直接用图像浏览器打开看似全黑的问题，这个如何读取标注数据？我是使用labelme中直线类型标记的，想看看标记的效果。
谢谢

**Comment by wuyefeilin** [comment]
1. 列表生成可参考文档https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.2.0/docs/data_prepare.md
2. 可以使用opencv读取哈，利用cv2.imread读取图像，np.unique查看数值，检查图像的标签类别。你也可以通过乘以一个系数增大数值再保存图像，这样就可以清晰看清标注图像了。

**Comment by zhuyushi** [comment]
多谢解惑，谢谢
