### ISSUE TITLE
./slim/prune如何对./contirb/Humanseg中的shufflenet人像分割模型进行剪枝啊

### ISSUE THREAD

**Issue by wsy1991** [PaddlePaddle/PaddleSeg#810]

**Comment by wanghaoshuang** [comment]
PaddleSlim还没有支持Humanseg中使用的训练API, 所以暂时需要用户按以下建议修改Humanseg API以支持剪枝：


[./slim/prune](https://github.com/PaddlePaddle/PaddleSeg/blob/develop/legacy/slim/prune/train_prune.py)路径下的示例介绍了如何对Program进行剪裁，其中关键代码如下：
https://github.com/PaddlePaddle/PaddleSeg/blob/develop/legacy/slim/prune/train_prune.py#L313-L320
```python
pruner = Pruner()
    train_prog = pruner.prune(
        train_prog,
        fluid.global_scope(),
        params=pruned_params,
        ratios=pruned_ratios,
        place=place,
        only_graph=False)[0]
```
以上代码调用slim的pruner接口对program进行剪裁，program是paddlepaddle中相对底层的一个概念。

Humanseg将对porgram的训练逻辑封装在[SegModel.train](https://github.com/PaddlePaddle/PaddleSeg/blob/d7bfdfacb2f63a262cc0db40ba00712e9e22a4a0/legacy/contrib/HumanSeg/models/humanseg.py#L395)方法中。
您可以参考SegModel.train中量化的实现：https://github.com/PaddlePaddle/PaddleSeg/blob/d7bfdfacb2f63a262cc0db40ba00712e9e22a4a0/legacy/contrib/HumanSeg/models/humanseg.py#L432-L441
并结合[slim/prune 中对program的剪裁方法](https://github.com/PaddlePaddle/PaddleSeg/blob/develop/legacy/slim/prune/train_prune.py#L313-L320)，使SegModel.train支持剪裁逻辑。

后续，我们会推动Humanseg迁移到动态图，并提供简单的剪裁接口。
