### ISSUE TITLE
请教各位一下，如果我想在预训练模型的基础之上再添加自己标注的类别，怎么自定义类别的掩膜颜色？

### ISSUE THREAD

**Issue by eddieheyutong** [PaddlePaddle/PaddleSeg#82]
如题，控制颜色的应该是vis.py文件，这个默认的是自动生成的调色板，如果想要改为自己的颜色的话应该具体修改vis.py中的哪个部分呢？希望有大佬帮忙答疑解惑一下感激不尽。

**Comment by wuyefeilin** [comment]
可以修改vis.py中的 get_color_map(num_classes)函数，将返回的color_map替换成你自己想要的颜色就行了

**Comment by Jinji97** [comment]
怎么修改呀
def get_color_map_list(num_classes):
    colormap = [
        128, 64, 128, 244, 35, 232, 70, 70, 70, 102, 102, 156, 190, 153, 153,
        153, 153, 153, 250, 170, 30, 220, 220, 0, 107, 142, 35, 152, 251, 152,
        0, 130, 180, 220, 20, 60, 255, 0, 0, 0, 0, 142, 0, 0, 70, 0, 60, 100, 0,
        80, 100, 0, 0, 230, 119, 11, 32
    ] + [0, 0, 0] * (256 - num_classes)

    return colormap

**Comment by fuzhiheng2003** [comment]
基于该回答应该能够解决你的问题： https://github.com/PaddlePaddle/PaddleSeg/issues/1886#issuecomment-2708332494
