### ISSUE TITLE
使用Lanenet使用自己的数据集起动训练时报出维度错误

### ISSUE THREAD

**Issue by AkimotoAyako** [PaddlePaddle/PaddleSeg#820]
_具体的报错如下：_
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [-1, 64, 49, 49] and the shape of Y = [-1, 64, 50, 50]. Received [49] in X is not equal to [50] in Y at i:2.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:160)
  [operator < elementwise_add > error]

_lanenet.yaml的配置文件我是这样写的_
EVAL_CROP_SIZE: (1536, 1536) # (width, height), for unpadding rangescaling and stepscaling
TRAIN_CROP_SIZE: (800, 800) # (width, height), for unpadding rangescaling and stepscaling
AUG: 
    AUG_METHOD: u"unpadding" # choice unpadding rangescaling and stepscaling
    FIX_RESIZE_SIZE: (800, 800) # (width, height), for unpadding
    INF_RESIZE_VALUE: 500  # for rangescaling
    MAX_RESIZE_VALUE: 600  # for rangescaling
    MIN_RESIZE_VALUE: 400  # for rangescaling
    MAX_SCALE_FACTOR: 2.0  # for stepscaling
    MIN_SCALE_FACTOR: 0.5  # for stepscaling
    SCALE_STEP_SIZE: 0.25  # for stepscaling
    MIRROR: True
    RICH_CROP: 
        ENABLE: False 

BATCH_SIZE: 2

DATASET: 
    DATA_DIR: "/home/aistudio/" #数据文件夹
    IMAGE_TYPE: "rgb"  # choice rgb or rgba
    NUM_CLASSES: 15
    TEST_FILE_LIST: "/home/aistudio/val_list.txt"   # 测试集文件列表
    TRAIN_FILE_LIST: "/home/aistudio/train_list.txt"    # 训练集文件列表
    VAL_FILE_LIST: "/home/aistudio/val_list.txt"    # 验证集文件列表，可以与测试集一致
    #VIS_FILE_LIST: "/home/aistudio/vis_list.txt"    # 待推理的文件列表
    VIS_FILE_LIST: None
    IGNORE_INDEX: 255
    SEPARATOR: " "

FREEZE:
    MODEL_FILENAME: "model"
    PARAMS_FILENAME: "params"
MODEL:
    MODEL_NAME: "lanenet"
    DEFAULT_NORM_TYPE: "bn"
TEST:
    TEST_MODEL: "./saved_model/lanenet/final/"
TRAIN:
    MODEL_SAVE_DIR: "./saved_model/lanenet/"
    PRETRAINED_MODEL_DIR: "./pretrained_model/VGG16_pretrained"
    SNAPSHOT_EPOCH: 1
SOLVER:
    #WEIGHT_DECAY: 0.001
    LR: 0.005   # 初始学习率
    LR_POLICY: "poly"   # 学习率策略
    OPTIMIZER: "sgd"    # 优化器方案
    NUM_EPOCHS: 25     # 训练轮数
    CROSS_ENTROPY_WEIGHT: [0.1, 1, 1, 1, 1, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 1, 1 ,0.8, 1] # 每一个类别loss权重
报错如上，在使用paddleseg的deeplabv3p使用相似的配置（指的是AUG部分没动）时是可以正常训练的，不知道是为啥出现了这样的报错orz

**Comment by phoenares** [comment]
看着像特征图分辨率没对齐，不知道是不是网络下采样或者padding的时候取整的问题
