### ISSUE TITLE
配置参数数据集的transform的问题

### ISSUE THREAD

**Issue by kingbirdWc** [PaddlePaddle/PaddleSeg#830]
大佬，在配置文件中看到对于数据集的transforms，我有个疑问，对于多个type，训练的时候会自动对训练数据集和对应的标签做响应的变化吗？
transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.75
      max_scale_factor: 1.5
      scale_step_size: 0.25
    - type: RandomHorizontalFlip
    - type: RandomVerticalFlip
    - type: RandomRotation
      max_rotation: 30
    - type: RandomDistort
      brightness_range: 0.2
      contrast_range: 0.2
      saturation_range: 0.2
    - type: RandomPaddingCrop
      crop_size: [256, 256]
    - type: Normalize

**Comment by wuyefeilin** [comment]
会的，在经过transforms后，标签和图片是对应的

**Comment by kingbirdWc** [comment]
谢谢，不过还有一些疑问，感觉文档没那么完善，请教一下，yml文件里的loss损失函数这个，coef系数里面的含义是什么意思？权重越大表名这个类别越重要吗？
loss:
  types:
    - type: CrossEntropyLoss
  coef: [1, 1]

**Comment by wuyefeilin** [comment]
coef代表你每一路的损失系数。可以理解为权重越大表示这一路的损失越重要
