### ISSUE TITLE
标注图片的背景值太多影响训练效果吗？

### ISSUE THREAD

**Issue by kingbirdWc** [PaddlePaddle/PaddleSeg#833]
大佬们，请教个问题。
标注图片有很多背景值（类别255）会影响训练吗？如图所示，黄色和绿色分别是0和1,白色是255即背景。几乎每个标注都是这样的，有的背景值占比更高。
![image](https://user-images.githubusercontent.com/23066646/107173579-0bc77800-6a03-11eb-8f89-0f54a327e9f3.png)

**Comment by wuyefeilin** [comment]
255默认为忽略类，如果你进行二分类的话，评估不受影响，但在预测的时候，255区域会随机划分，对你的可视化结果不好。

请问一下你的应用场景是什么，我们可以给出相应的建议？

**Comment by kingbirdWc** [comment]
> 255默认为忽略类，如果你进行二分类的话，评估不受影响，但在预测的时候，255区域会随机划分，对你的可视化结果不好。
> 
> 请问一下你的应用场景是什么，我们可以给出相应的建议？

训练的话影响大吗？因为白色区域也就是标注为255的我们没有进行标注，所以就忽略了。
应用是遥感影像的语义分割，我们只对感兴趣的地块标注为0某作物和1非作物，其他的没标注的区域就设置为255了。

**Comment by wuyefeilin** [comment]
训练没影响的，可以训练的。
