### ISSUE TITLE
RuntimeError: (NotFound) Operator nearest_interp_v2 does not have kernel for data_type[int]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN].

### ISSUE THREAD

**Issue by ZhangXinNan** [PaddlePaddle/PaddleSeg#838]
RuntimeError: (NotFound) Operator nearest_interp_v2 does not have kernel for data_type[int]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at /home/teamcity/work/ef54dc8a5b211854/paddle/fluid/imperative/prepared_operator.cc:118)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
  [operator < nearest_interp_v2 > error]

**Comment by michaelowenliu** [comment]
@ZhangXinNan Hi, could you please provide a more detailed log?

**Comment by tvshow5727** [comment]
faced with the same problem

**Comment by michaelowenliu** [comment]
@tvshow5727 Hi, could you please put the error log?

**Comment by tvshow5727** [comment]
cmd：


python3.5 predict.py --config ./configs/quick_start/bisenet_optic_disc_512x512_1k.yml&nbsp; --model_path model/cityscapes/model.pdparams --image_path data/optic_disc_seg/JPEGImages/H0003.jpg&nbsp; --save_dir output/result




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月22日(星期一) 下午5:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] RuntimeError: (NotFound) Operator nearest_interp_v2 does not have kernel for data_type[int]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN]. (#838)





 
@tvshow5727 Hi, could you please put the error log?

**Comment by Peng-ss** [comment]
采用了CPU训练没有报错，模型也成功生成了，预测时出现了以下的错误，请问有解决方法吗
`RuntimeError: (NotFound) Operator nearest_interp_v2 does not have kernel for data_type[int]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at /paddle/paddle/fluid/imperative/prepared_operator.cc:128)
  [operator < nearest_interp_v2 > error]
`
