### ISSUE TITLE
报错 “PaddleCheckError: cudaGetDeviceProperties failed in paddle...”

### ISSUE THREAD

**Issue by lakebodhi** [PaddlePaddle/PaddleSeg#84]
按照 [https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.2.0/docs/usage.md](url) 提供的示例训练模型执行
`set  CUDA_VISIBLE_DEVICES=0`

`python pdseg/train.py --use_gpu \
                      --do_eval \
                      --use_tb \
                      --tb_log_dir train_log \
                      --cfg configs/unet_pet.yaml \
                      BATCH_SIZE 4 \
                      TRAIN.PRETRAINED_MODEL_DIR pretrained_model/unet_bn_coco \
                      SOLVER.LR 5e-5`

系统报错

> PaddleCheckError: cudaGetDeviceProperties failed in paddle::platform::GetCUDAComputeCapability, error code : 30, Please see detail in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038: unknown error at [D:\1.6.1\paddle\paddle\fluid\platform\gpu_info.cc:84]

请问怎么解决？

操作系统windows10 64位 cuda10.1

**Comment by ZeyuChen** [comment]
目前windows下对cuda10.1小版本还在适配中，请降级cuda版本至10.0后再试。

**Comment by lakebodhi** [comment]
@ZeyuChen 解决了。谢谢！
