### ISSUE TITLE
backbone_indices for Xception

### ISSUE THREAD

**Issue by Jefflier** [PaddlePaddle/PaddleSeg#840]
你好，我在使用PaddleSeg动态图api训练模型时使用了deeplabv3的Xception backbone，但是程序出现了list index out of range的错误，具体是backbone.feat_channels[i] for i in backbone_indices中的错误。而当我将backbone_indices从（0，3）改为（1，1）时却没有报任何错误，请问官方的backbone_indices是多少，感谢你们的帮助！

**Comment by wuyefeilin** [comment]
感谢你的反馈，xception的backbone_indices为（0，1), 我们将会提供xception 版本deeplabv3的配置文件。

**Comment by Jefflier** [comment]
我使用了（0，1）的配置，还是出现了错误，希望你们尽快更新，谢谢！
