### ISSUE TITLE
BootstrappedCrossEntropyLoss errors when setting

### ISSUE THREAD

**Issue by 2436185647** [PaddlePaddle/PaddleSeg#844]
window 
aistudio notebook
python3,7  paddle2.0
num_class=15
loss设置如下：
————————————————————————————————
loss:
  types:
    - type: BootstrappedCrossEntropyLoss
      min_K: 4096
      loss_th: 0.3
      weight: [0.1, 1, 1, 1, 1, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 1, 1 ,0.8, 1]
  coef: [1]
——————————————————————
出现报错：
——————————————————————————
Error: /paddle/paddle/fluid/operators/gather.cu.h:62 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [15] and greater or equal to 0, but received [0]
Error: /paddle/paddle/fluid/operators/gather.cu.h:62 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [15] and greater or equal to 0, but received [0]
Error: /paddle/paddle/fluid/operators/gather.cu.h:62 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [15] and greater or equal to 0, but received [0]
Error: /paddle/paddle/fluid/operators/gather.cu.h:62 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [15] and greater or equal to 0, but received [0]
Error: /paddle/paddle/fluid/operators/gather.cu.h:62 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [15] and greater or equal to 0, but received [0]
Error: /paddle/paddle/fluid/operators/gather.cu.h:62 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [15] and greater or equal to 0, but received [0]
Error: /paddle/paddle/fluid/operators/gather.cu.h:62 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [15] and greater or equal to 0, but received [0]
Error: /paddle/paddle/fluid/operators/gather.cu.h:62 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [15] and greater or equal to 0, but received [0]
Error: /paddle/paddle/fluid/operators/gather.cu.h:62 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [15] and greater or equal to 0, but received [0]
Error: /paddle/paddle/fluid/operators/gather.cu.h:62 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [15] and greater or equal to 0, but received [0]
Error: /paddle/paddle/fluid/operators/gather.cu.h:62 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [15] and greater or equal to 0, but received [0]
Error: /paddle/paddle/fluid/operators/gather.cu.h:62 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [15] and greater or equal to 0, but received [0]
Error: /paddle/paddle/fluid/operators/gather.cu.h:62 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [15] and greater or equal to 0, but received [0]
Error: /paddle/paddle/fluid/operators/gather.cu.h:62 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [15] and greater or equal to 0, but received [0]
Error: /paddle/paddle/fluid/operators/gather.cu.h:62 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [15] and greater or equal to 0, but received [0]
Error: /paddle/paddle/fluid/operators/gather.cu.h:62 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [15] and greater or equal to 0, but received [0]
Error: /paddle/paddle/fluid/operators/gather.cu.h:62 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [15] and greater or equal to 0, but received [0]
Error: /paddle/paddle/fluid/operators/gather.cu.h:62 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [15] and greater or equal to 0, but received [0]
Error: /paddle/paddle/fluid/operators/gather.cu.h:62 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [15] and greater or equal to 0, but received [0]
Error: /paddle/paddle/fluid/operators/gather.cu.h:62 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [15] and greater or equal to 0, but received [0]
    main(args)
  File "PaddleSeg/train.py", line 136, in main
    losses=losses)
  File "/home/aistudio/PaddleSeg/paddleseg/core/train.py", line 141, in train
    edges=edges)
  File "/home/aistudio/PaddleSeg/paddleseg/core/train.py", line 44, in loss_computation
    loss += losses['coef'][i] * loss_i(logits, labels)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleSeg/paddleseg/models/losses/bootstrapped_cross_entropy.py", line 65, in forward
    sorted_loss = paddle.sort(loss, descending=True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/search.py", line 464, in sort
    out, _ = core.ops.argsort(x, 'axis', axis, 'descending', descending)
SystemError: (Fatal) Operator argsort raises an thrust::system::system_error exception.
The exception content is
:tabulate: failed to synchronize: cudaErrorLaunchFailure: unspecified launch failure. (at /paddle/paddle/fluid/imperative/tracer.cc:172)
————————————————————————————————————————————————————

**Comment by michaelowenliu** [comment]
@2436185647 Hi, please put your detailed config info.

**Comment by 2436185647** [comment]
batch_size: 2
iters: 80000

model:
  type: DeepLabV3P
  backbone:
    type: ResNet101_vd
    output_stride: 8
    multi_grid: [1, 2, 4]
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet101_vd_ssld.tar.gz
  num_classes: 15

  backbone_indices: [0, 3]
  aspp_ratios: [1, 12, 24, 36]
  aspp_out_channels: 256
  align_corners: False
  pretrained: null

train_dataset:
  type: Dataset
  dataset_root: ./
  train_path: train_list.txt
  num_classes: 15
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [1024, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: ./
  val_path: val_list.txt
  num_classes: 15
  transforms:
    - type: Normalize
  mode: val


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

learning_rate:
  value: 0.0025
  decay:
    type: poly
    power: 0.9
    end_lr: 0.0

loss:
  types:
    - type: BootstrappedCrossEntropyLoss
      min_K: 4096
      loss_th: 0.3
      weight: [0.1,0.5,1,0.7,1.5,1,0.1,1,0.5,1,0.5,1,1,1,1]
  coef: [1]

**Comment by michaelowenliu** [comment]
@2436185647 Hi, we test it on Cityscapes dataset. 

1. Can you try different values of min_K or loss_th? 
2. From your log info, the error occurs in "sorted_loss = paddle.sort(loss, descending=True)".
3. Try using the config first with adding the weight, https://github.com/PaddlePaddle/PaddleSeg/blob/release/v2.0.0-rc/configs/hardnet/hardnet_cityscapes_1024x1024_160k.yml

**Comment by 2436185647** [comment]
@michaelowenliu  hello， i have just tried the config you recommended ,the result is as followed
after 'weight' are added to the project you recommanded ,it can run succesfully
according to my observation,i found the difference between my file and the one you recommanded :

————————————————————————————————————————————————-
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [512, 512]                        #crop_size: [1024,512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train
————————————————————————————————————————————————

the difference is in the value of 'crop_size'
when i turn the crop_size in my project into [512,512],it can run as successful as the config you recommended.
i dont know why


the former errow is:
————————————————————-————————————————————————————
Error: /paddle/paddle/fluid/operators/gather.cu.h:62 Assertion index_value >= 0 && index_value < input_dims[j] failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [15] and greater or equal to 0, but received [0]
—————————————————————————————————————————————————


by the way, could you tell me what id the meaning of 'min_K and  loss_th',i want to know how to adjust it 
thank you very much indeed!

**Comment by michaelowenliu** [comment]
@2436185647 Hi, please refer to the loss file, https://github.com/PaddlePaddle/PaddleSeg/blob/release/v2.0.0-rc/paddleseg/models/losses/bootstrapped_cross_entropy.py#L28
