### ISSUE TITLE
resume的时候出错

### ISSUE THREAD

**Issue by Lordores** [PaddlePaddle/PaddleSeg#846]
您好，我尝试使用两组训练资料在一次执行中进行训练，为此我准备了两个yml配置文档A,B，两者的区别只有dataset的路径与iters（A中的iters为12000；B中的iters为24000）

yml使用remote sensing下的`ocrnet_hrnetw48_ccf_256x256_80k.yml`做模板，仅改变了data路径与iters。

我在一次执行中进行如下的训练操作的时候：
`train(Path_of_A)`
`resume_train(Path_of_B)`

在完成train(Path_of_A)进行resume_train(Path_of_B)时出现
`Message=optimizer Tensor conv2d_316.w_0_velocity_0 not found`
与[https://github.com/PaddlePaddle/PaddleSeg/issues/837](url)的问题类似

将`train(Path_of_A)`注释后直接进行`resume_train(Path_of_B)`可正常恢复训练，想请问下这是由于什么造成的。
（目前主要是想一组data按年份一个文件夹一个文件夹的进行训练）
顺便问下现在optimizer有哪些可选项了。

**Comment by nepeplwu** [comment]
@Lordores 相关代码是否可以贴出来下？
