### ISSUE TITLE
cyclical cosine annealing learning rate，目前paddle2.0和paddleseg支持吗？

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleSeg#848]
最近在做cv，看到了SWA Object Detection，想将这个用于训练模型，查了一下paddle的api文档，只发现了paddle.fluid.layers. cosine_decay和paddle.optimizer.lr.CosineAnnealingDecay，但这两个似乎是针对整个训练流程的，那种每个epoch都来一次的周期余弦退火有吗？

**Comment by LutaoChu** [comment]
你好，paddle.optimizer.lr.CosineAnnealingDecay就是周期的余弦退火，假设你每个epoch有10个step，想要每个epoch都来一次完整周期的余弦退火，T_max设为5就可以了
