### ISSUE TITLE
label 中间像素值空缺问题

### ISSUE THREAD

**Issue by minhoooo1** [PaddlePaddle/PaddleSeg#852]
PaddleSeg做分割时 label 中的像素值中间值可以空缺嘛？  比如那个车道线的比赛 ，我改做二分类，对0 和14的像素分类，而label图像只是有0和14的像素 可以的嘛？

**Comment by wuyefeilin** [comment]
中间不能空缺，二类的只能0，1。 你可以有两种做法进行修改：1.将数据集的标签值进行改变， 2. 可以在数据读取环节对标签值进行更改。
对于预测出来结果可以根据需要将1映射回14。

**Comment by minhoooo1** [comment]
感谢您的迅速回复！祝PaddleSeg越来越好！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wuyefeilin"<notifications@github.com&gt;; 
发送时间: 2021年3月1日(星期一) 中午11:17
收件人: "PaddlePaddle/PaddleSeg"<PaddleSeg@noreply.github.com&gt;; 
抄送: "Derrick。"<1121851272@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleSeg] label 中间像素值空缺问题 (#852)





 
中间不能空缺，二类的只能0，1。 你可以有两种做法进行修改：1.将数据集的标签值进行改变， 2. 可以在数据读取环节对标签值进行更改。
 对于预测出来结果可以根据需要将1映射回14。

**Comment by minhoooo1** [comment]
但还想麻烦一下 ，预测出来结果可以根据需要将1映射回14 的代码段请问在那个地方 ？

**Comment by minhoooo1** [comment]
本人也是选择第二种方法 因为需要val 所以需要在val之前将1映射回14

**Comment by wuyefeilin** [comment]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v2.0/paddleseg/datasets/dataset.py#L143， 在这里面直接修改就行了，这样就可以直接训练和评估了

**Comment by minhoooo1** [comment]
感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wuyefeilin"<notifications@github.com&gt;; 
发送时间: 2021年3月1日(星期一) 中午11:26
收件人: "PaddlePaddle/PaddleSeg"<PaddleSeg@noreply.github.com&gt;; 
抄送: "Derrick。"<1121851272@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleSeg] label 中间像素值空缺问题 (#852)





 
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v2.0/paddleseg/datasets/dataset.py#L143， 在这里面直接修改就行了，这样就可以直接训练和评估了
