### ISSUE TITLE
预测输出上采样的问题

### ISSUE THREAD

**Issue by minhoooo1** [PaddlePaddle/PaddleSeg#857]
训练时数据增强选择了RandomPaddingCrop：[1024,512] 那么网络输入 输出的都是长宽为 [1024,512]的图片
predict时 输入数据是长宽为1536*1536的彩色图片 输出也是长宽为1536*1536的单通道图  请问PaddleSeg中预测的时候是要对图片做怎样的处理才用的上 针对高宽为1024*512的模型参数呢？ 
由于代码内容量较大 暂且麻烦Seg的团队能帮助解答 感谢！！

**Comment by wuyefeilin** [comment]
麻烦你提供一下训练时和预测时的数据预处理

**Comment by minhoooo1** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月3日(星期三) 上午10:47
收件人:&nbsp;"PaddlePaddle/PaddleSeg"<PaddleSeg@noreply.github.com&gt;;
抄送:&nbsp;"Derrick。"<1121851272@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] 预测输出上采样的问题 (#857)





 
麻烦你提供一下训练时和预测时的数据预处理

**Comment by yangrisheng** [comment]
我也想知道咋解决的，能公开下解决方法吗？麻烦了
