### ISSUE TITLE
关于参数问题

### ISSUE THREAD

**Issue by yangrisheng** [PaddlePaddle/PaddleSeg#859]
请问一下
`def parse_args():
    parser = argparse.ArgumentParser(description='Model prediction')

    # params of prediction
    parser.add_argument(
        "--config", dest="cfg", help="The config file.", default=None, type=str)
    parser.add_argument(
        '--model_path',
        dest='model_path',
        help='The path of model for prediction',
        type=str,
        default=None)
    parser.add_argument(
        '--image_path',
        dest='image_path',
        help=
        'The path of image, it can be a file or a directory including images',
        type=str,
        default=None)
    parser.add_argument(
        '--save_dir',
        dest='save_dir',
        help='The directory for saving the predicted results',
        type=str,
        default='./output/result')

    # augment for prediction
    parser.add_argument(
        '--aug_pred',
        dest='aug_pred',
        help='Whether to use mulit-scales and flip augment for prediction',  #多尺度和翻转增强
        action='store_true')
    parser.add_argument(
        '--scales',
        dest='scales',
        nargs='+',
        help='Scales for augment',  #扩大规模
        type=float,
        default=1.0)
    parser.add_argument(
        '--flip_horizontal',
        dest='flip_horizontal',
        help='Whether to use flip horizontally augment',  #水平翻转
        action='store_true')
    parser.add_argument(
        '--flip_vertical',
        dest='flip_vertical',
        help='Whether to use flip vertically augment',  #垂直窗口
        action='store_true')

    # sliding window prediction
    parser.add_argument(
        '--is_slide',
        dest='is_slide',
        help='Whether to prediction by sliding window',  #滑动窗口
        action='store_true')
    parser.add_argument(
        '--crop_size',
        dest='crop_size',
        nargs=2,
        help=
        'The crop size of sliding window, the first is width and the second is height.',  #滑动窗口大小
        type=int,
        default=None)
    parser.add_argument(
        '--stride',
        dest='stride',
        nargs=2,
        help=
        'The stride of sliding window, the first is width and the second is height.',  #滑动窗口步长
        type=int,
        default=None)

    return parser.parse_args()
`
这种参数比如--scales后面应该跟的参数是什么样子的？在哪里能找到说明？
麻烦了。

**Comment by wuyefeilin** [comment]
@yangrisheng https://github.com/PaddlePaddle/PaddleSeg/blob/release/v2.0/docs/quick_start.md#%E6%A8%A1%E5%9E%8B%E8%AF%84%E4%BC%B0 这里有说明
