### ISSUE TITLE
新版本API没有对数据预处理的类吗

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleSeg#863]
今天在用unet进行图像分割的时候，采用自定义的数据，出现
`ValueError: all input arrays must have the same shape`
当前的API里有这方面的数据处理方式吗

**Comment by BeyondYourself** [comment]
是根据transform中对数据做一定能的处理吗

**Comment by michaelowenliu** [comment]
@BeyondYourself Hi, add a transform method as image preprocessing.

**Comment by BeyondYourself** [comment]
了解，谢谢
