### ISSUE TITLE
2.0版本的目前在predit的时候必须读val_dataset

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleSeg#866]
2.0版本的目前在predit的时候必须读val_dataset,，感觉这个没有必要吧，
预测这部分代码，目前还没跑通，另外predit时候,yml里面具体怎么配置也没有说明，还请大佬解答一下

**Comment by BeyondYourself** [comment]
在预测的时候为啥yml文件里中必须配置
`type: Dataset
  dataset_root
  val_path:  `
在实际的预测中，这几个参数并不会用到，跳过这几个参数的设置

**Comment by wuyefeilin** [comment]
感谢你的反馈，在predict的时候我们使用的是val_dataset的数据预处理， 如果评估没有问题，predict就可以正常运行的。感谢你提的建议，我们会不断优化的。

**Comment by BeyondYourself** [comment]
我在predit的时候，控制台一直如下卡着，没有继续进行，这可能是什么原因呢 @wuyefeilin 
![image](https://user-images.githubusercontent.com/12640462/110755163-9a8a1780-8283-11eb-90dc-dfc187df7e23.png)

**Comment by wuyefeilin** [comment]
你是用gpu还是cpu, 另外你看一下保存目录里是否有结果生成

**Comment by BeyondYourself** [comment]
训练的时候是用的gpu,predit的时候用的CPU，保存的目录下没有任何文件生成

**Comment by wuyefeilin** [comment]
cpu计算很慢的，建议你用gpu

**Comment by BeyondYourself** [comment]
好的，那我试试predit用GPU试试

**Comment by BeyondYourself** [comment]
GPU只用了几十毫秒，CPU十几分钟一直卡着，我在想差距有这么大么，如果以后我用CPU部署会不会很慢？有什么好的方法吗

**Comment by wuyefeilin** [comment]
可以考虑用bisenet， 减小图片尺寸

**Comment by BeyondYourself** [comment]
@wuyefeilin 大佬可否加个微信，我的是WXH是861937180
