### ISSUE TITLE
强烈推荐添加dockerfile

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleSeg#868]

**Comment by LutaoChu** [comment]
你好，具体是碰到什么环境问题了呢？
PaddleSeg不需要编译，安装非常容易。如果是安装Paddle过程遇到问题，可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/index_cn.html  ，或者使用Paddle提供的镜像，可以移步这里提issue https://github.com/PaddlePaddle/Paddle/issues

**Comment by ghost** [comment]
我需要在docker容器中进行训练模型

**Comment by ghost** [comment]
> 你好，具体是碰到什么环境问题了呢？�
> PaddleSeg不需要编译，安装非常容易。如果是安装Paddle过程遇到问题，可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/index_cn.html ，或者使用Paddle提供的镜像，可以移步这里提issue https://github.com/PaddlePaddle/Paddle/issues

我需要在docker容器中进行训练模型

**Comment by LutaoChu** [comment]
可以拉取paddle的镜像   https://www.paddlepaddle.org.cn/documentation/docs/zh/install/docker/linux-docker.html
