### ISSUE TITLE
transforms功能可以关闭吗？

### ISSUE THREAD

**Issue by keepgoing365** [PaddlePaddle/PaddleSeg#869]
我的数据集不需要再进行数据增强，想关掉transforms数据增强功能怎么关？
我本来以为不要增强就在配置文件 .yml 里留下个normalize就行，但是我看了PaddleSeg-release-v2.0.0-rc\paddleseg\transform文件的transforms.py文件后发现它是有默认值的，好像不设置它也会按照默认参数来扩充数据集？

**Comment by wuyefeilin** [comment]
“不要增强就在配置文件 .yml 里留下个normalize就行”， 没错，就是这样的

**Comment by BeyondYourself** [comment]
@wuyefeilin 还是不清楚这个怎么配置，可以写个示例吗

**Comment by wuyefeilin** [comment]
@BeyondYourself 类似这样：
transforms:
    - type: Normalize

**Comment by BeyondYourself** [comment]
好的，谢谢

**Comment by BeyondYourself** [comment]
`    raise RuntimeError('No object information in {}.'.format(cfg))
RuntimeError: No object information in {'transforms': [{'type': 'Normalize'}], 'mode': 'val'}.`
改成上述的配置后出现如下异常
@wuyefeilin

**Comment by wuyefeilin** [comment]
你把配置文件发一下
