### ISSUE TITLE
imagenet resnet50预训练使用的具体细节

### ISSUE THREAD

**Issue by littletomatodonkey** [PaddlePaddle/PaddleSeg#87]
我看PSPNet中使用r50作为pretrain，但是预处理似乎与imagenet的不相同（从configs中的配置文件看mean和std，与标准paddle imagenet的预处理不同），想问下这个对指标会有多大影响呢？
![image](https://user-images.githubusercontent.com/14270174/68587980-5b975680-04c3-11ea-9fcc-90e1fbecf663.png)

**Comment by sandyhouse** [comment]
不是很确定，可能需要具体测一下。

**Comment by littletomatodonkey** [comment]
好的，就是说官网提供的训练结果都是在这个默认的mean和std下去运行的？没有和分类严格对齐？

**Comment by nepeplwu** [comment]
@littletomatodonkey ，是的，PaddleSeg里面的分割模型在训练时用的mean和std都是[0.5, 0.5, 0.5]

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。
