### ISSUE TITLE
用infer.py预测模型的时候报了数据不匹配的错误，但是评估的时候是没问题，大佬们麻烦给看下

### ISSUE THREAD

**Issue by lybcodes** [PaddlePaddle/PaddleSeg#870]
InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 18, 310, 415] and the shape of Y = [1, 18, 310, 411]. Received [415] in X is not equal to [411] in Y at i:3.
      [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at D:\v2.0
.0\paddle\paddle/fluid/operators/elementwise/elementwise_op_function.h:160)
      [operator < elementwise_add > error]

**Comment by wuyefeilin** [comment]
你好，麻烦给一下具体的运行日志和运行命令
