### ISSUE TITLE
训练结束后出现一些不清楚的警告

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleSeg#871]
在AIStudio下训练，采用paddle2最新稳定版本，训练结束后出现一下警告或错误，有大佬能帮看看是什么问题吗

`/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py:238: UserWarning: The dtype of left and right variables are not the same, left dtype is VarType.FP32, but right dtype is VarType.INT32, the right dtype will convert to VarType.FP32
  format(lhs_dtype, rhs_dtype, lhs_dtype))
<class 'paddle.nn.layer.conv.Conv2D'>'s flops has been counted
Customize Function has been applied to <class 'paddle.nn.layer.norm.SyncBatchNorm'>
Cannot find suitable count function for <class 'paddle.nn.layer.pooling.MaxPool2D'>. Treat it as zero FLOPs.`

**Comment by michaelowenliu** [comment]
@BeyondYourself Hi, that's fine.

**Comment by BeyondYourself** [comment]
ok,thx
