### ISSUE TITLE
如何根据paddle.Model.summary查看网络结构

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleSeg#876]
今天在测试的时候，想打印模型的网络结构，目前的代码如何使用Paddle接口，如何打印网络结构

**Comment by michaelowenliu** [comment]
@BeyondYourself Hi, please check https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/hapi/model_summary/summary_cn.html#summary

**Comment by BeyondYourself** [comment]
已解决，谢谢
