### ISSUE TITLE
预测模型怎么输出？

### ISSUE THREAD

**Issue by LarryHYQ** [PaddlePaddle/PaddleSeg#878]
https://github.com/AgentMaker/PaTTA
就是输出能load进PaTTA的模型

**Comment by WhiteFireFox** [comment]
> https://github.com/AgentMaker/PaTTA
> 就是输出能load进PaTTA的模型

@LarryHYQ  hello，您的问题已经收到，您直接使用paddleseg里面的export.py导出的模型即可load进PaTTA了

**Comment by GT-ZhangAcer** [comment]
> > https://github.com/AgentMaker/PaTTA
> > 就是输出能load进PaTTA的模型
> 
> @LarryHYQ hello，您的问题已经收到，您直接使用paddleseg里面的export.py导出的模型即可load进PaTTA了

曹佬给力
