### ISSUE TITLE
模型导出失败

### ISSUE THREAD

**Issue by changbaishan** [PaddlePaddle/PaddleSeg#879]
isenet && cd bisenet
(paddle) yong@yong-virtual-machine:~/Documents/sandbox/paddle/PaddleSeg/bisenet$ wget https://paddleseg.bj.bcebos.com/dygraph/cityscapes/bisenet_cityscapes_1024x1024_160k/model.pdparams
--2021-03-12 09:50:53--  https://paddleseg.bj.bcebos.com/dygraph/cityscapes/bisenet_cityscapes_1024x1024_160k/model.pdparams
Resolving paddleseg.bj.bcebos.com (paddleseg.bj.bcebos.com)... 103.235.46.61, 2409:8c00:6c21:10ad:0:ff:b00e:67d
Connecting to paddleseg.bj.bcebos.com (paddleseg.bj.bcebos.com)|103.235.46.61|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15301992 (15M) [application/octet-stream]
Saving to: ‘model.pdparams’

model.pdparams      100%[===================>]  14.59M   212KB/s    in 81s     

2021-03-12 09:52:16 (186 KB/s) - ‘model.pdparams’ saved [15301992/15301992]

(paddle) yong@yong-virtual-machine:~/Documents/sandbox/paddle/PaddleSeg/bisenet$ cd ..
(paddle) yong@yong-virtual-machine:~/Documents/sandbox/paddle/PaddleSeg$ python export.py \
>        --config configs/bisenet/bisenet_cityscapes_1024x1024_160k.yml \
>        --model_path bisenet/model.pdparams
2021-03-12 09:59:00 [INFO]	Loaded trained params of model successfully.
Traceback (most recent call last):
  File "export.py", line 85, in <module>
    main(args)
  File "export.py", line 62, in main
    in_shape = [1] + list(cfg.val_dataset[0][0].shape)
  File "/home/yong/Documents/sandbox/paddle/PaddleSeg/paddleseg/cvlibs/config.py", line 259, in val_dataset
    return self._load_object(_val_dataset)
  File "/home/yong/Documents/sandbox/paddle/PaddleSeg/paddleseg/cvlibs/config.py", line 293, in _load_object
    return component(**params)
  File "/home/yong/Documents/sandbox/paddle/PaddleSeg/paddleseg/datasets/cityscapes.py", line 74, in __init__
    "The dataset is not Found or the folder structure is nonconfoumance."
ValueError: The dataset is not Found or the folder structure is nonconfoumance.

**Comment by nepeplwu** [comment]
@changbaishan ，感谢反馈，这个问题是因为你本地不存在指定数据集导致（导出模型时，需要读取测试数据集的transforms，读取的时候发现数据集路径不存在，从而报错），可以先下载对应的数据集。

**Comment by changbaishan** [comment]
(1)
https://paddleseg.bj.bcebos.com/dygraph/cityscapes/bisenet_cityscapes_1024x1024_160k/model.pdparams
--2021-03-12 09:50:53-- https://paddleseg.bj.bcebos.com/dygraph/cityscapes/bisenet_cityscapes_1024x1024_160k/model.pdparams
Resolving paddleseg.bj.bcebos.com (paddleseg.bj.bcebos.com)... 103.235.46.61, 2409:8c00:6c21:10ad:0:ff:b00e:67d
Connecting to paddleseg.bj.bcebos.com (paddleseg.bj.bcebos.com)|103.235.46.61|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15301992 (15M) [application/octet-stream]
Saving to: ‘model.pdparams’

model.pdparams 100%[===================>] 14.59M 212KB/s in 81s

_**2021-03-12 09:52:16 (186 KB/s) - ‘model.pdparams’ saved [15301992/15301992]**_
(2) 
需要读取测试数据集的transforms，读取的时候发现数据集路径不存在，从而报错

**Comment by changbaishan** [comment]
(3) ls -al .paddleseg
total 20
drwxr-xr-x  5 yong yong 4096 Mar 11 10:11 .
drwxr-xr-x 53 yong yong 4096 Mar 17 08:23 ..
drwxr-xr-x  2 yong yong 4096 Mar 11 10:11 dataset
drwxr-xr-x  2 yong yong 4096 Mar 11 10:11 pretrained_model
drwxr-xr-x  2 yong yong 4096 Mar 11 10:11 tmp

ls -al .paddleseg/dataset
total 8
drwxr-xr-x 2 yong yong 4096 Mar 11 10:11 .
drwxr-xr-x 5 yong yong 4096 Mar 11 10:11 ..

 ls -al .paddleseg/pretrained_model
total 8
drwxr-xr-x 2 yong yong 4096 Mar 11 10:11 .
drwxr-xr-x 5 yong yong 4096 Mar 11 10:11 ..

**Comment by nepeplwu** [comment]
@changbaishan 感谢反馈，我们已经优化了模型导出的逻辑，解决了上面提到的本地不存在数据导致导出失败的问题，请在`release/v2.0`分支上更新到最新的代码再体验下

**Comment by stoneWeb** [comment]
预训练模型能直接使用吗？直接用会报错
```
python predict.py \
    --config configs/panoptic_deeplab/panoptic_deeplab_resnet50_os32_cityscapes_1025x513_120k.yml \
    --model_path https://bj.bcebos.com/paddleseg/dygraph/pnoptic_segmentation/panoptic_deeplab_resnet50_os32_cityscapes_1025x513_bs8_90k_lr00005/model.pdparams \
    --image_path /home/xxx/1.jpg \
    --save_dir ./output/result
```
Traceback (most recent call last):
  File "predict.py", line 149, in <module>
    main(args)
  File "predict.py", line 113, in main
    val_dataset = cfg.val_dataset
  File "/home/xxx/.conda/envs/paddle/lib/python3.7/site-packages/paddleseg/cvlibs/config.py", line 321, in val_dataset
    return self._load_object(_val_dataset)
  File "/home/xxx/.conda/envs/paddle/lib/python3.7/site-packages/paddleseg/cvlibs/config.py", line 355, in _load_object
    return component(**params)
  File "/home/xxxx/workspace/PaddleSeg/contrib/PanopticDeepLab/datasets/cityscapes_panoptic.py", line 97, in __init__
    "The dataset is not Found or the folder structure is nonconfoumance."
ValueError: The dataset is not Found or the folder structure is nonconfoumance.
INFO 2021-07-16 17:05:08,498 launch_utils.py:327] terminate all the procs
ERROR 2021-07-16 17:05:08,498 launch_utils.py:584] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-07-16 17:05:11,501 launch_utils.py:327] terminate all the procs

**Comment by ghost** [comment]
> @changbaishan 感谢反馈，我们已经优化了模型导出的逻辑，解决了上面提到的本地不存在数据导致导出失败的问题，请在`release/v2.0`分支上更新到最新的代码再体验下

我在 release/v2.5 分支上依然遇到类似问题。

请问一下，当我把数据集下载好以后，应该如何操作？文档里并没有提及此操作。

感谢您的解答！~

**Comment by fjremnav** [comment]
Same problem on release/v2.6. I just want to do prediction with my own images but have no cityscapes dataset installed.

Please help

Thanks
