### ISSUE TITLE
这个咋回事啊，有这么大么

### ISSUE THREAD

**Issue by tt8000** [PaddlePaddle/PaddleSeg#883]
![1](https://user-images.githubusercontent.com/73922533/111121165-4646a680-85a7-11eb-9cdc-3667fb1d8df0.jpg)
![2](https://user-images.githubusercontent.com/73922533/111121178-49da2d80-85a7-11eb-88e1-9a0a0c3a93ec.jpg)

**Comment by BeyondYourself** [comment]
这个没关系的，这个不是实际模型保存大小
