### ISSUE TITLE
2.0版本的如何设置epoch？

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleSeg#884]
目前在使用2.0版本的训练模型时，只看到了迭代次数和batch_size大小相关的设置，想问一下，epoch是怎么计算的，在哪里可以设置

**Comment by Irvingao** [comment]
epochs = images_num / batch_size

**Comment by BeyondYourself** [comment]
不是吧，我之前测试看到epoch是与迭代数有关的

**Comment by BeyondYourself** [comment]
目前测试下来的epoch是  epoch = iter_size/(batch_size*2)

**Comment by michaelowenliu** [comment]
> 目前测试下来的epoch是 epoch = iter_size/(batch_size*2)

@BeyondYourself it depends on the number of GPUs.

**Comment by BeyondYourself** [comment]
> 

> > 目前测试下来的epoch是 epoch = iter_size/(batch_size*2)
> 
> @BeyondYourself it depends on the number of GPUs.

也就是epoch =  epoch = iter_size/(batch_size*num_GPU) ，这个理解对吗

**Comment by michaelowenliu** [comment]
@BeyondYourself 

Total number of the dataset: N
Batch Size: batch_size
The number of GPUs: num_gpus
Total iterations: iters
epoch = (iters\*batch_size\*num_gpus)/N
