### ISSUE TITLE
模型导出错误

### ISSUE THREAD

**Issue by btobab** [PaddlePaddle/PaddleSeg#887]
![github](https://user-images.githubusercontent.com/66876429/111144046-8155d380-85c1-11eb-9877-fb1ce20c6ce6.jpg)
使用的是paddleSeg的export文件

**Comment by nepeplwu** [comment]
@IamDestiny 感谢反馈，请更新最新代码试试

**Comment by btobab** [comment]
懂了懂了，我试试
