### ISSUE TITLE
部署预测时有python版本的吗？

### ISSUE THREAD

**Issue by exploreearth** [PaddlePaddle/PaddleSeg#89]
请问有python语言的部署预测代码吗？

**Comment by joey12300** [comment]
> 请问有python语言的部署预测代码吗？

你好，当前版本还没有发布python版本的预测部署。不过以后将会上线python版本的预测部署，请继续关注PaddleSeg的最新进展：）

**Comment by sjtubinlong** [comment]
@exploreearth Python 版本的预测部署已经发布，欢迎使用反馈 https://github.com/PaddlePaddle/PaddleSeg/tree/release/v0.3.0/deploy/python
