### ISSUE TITLE
训练ADE20K数据集时报错

### ISSUE THREAD

**Issue by JiehangXie** [PaddlePaddle/PaddleSeg#890]
![image](https://user-images.githubusercontent.com/51190264/111233540-06c98b80-85a2-11eb-9c5c-c8100b45ab5b.png)

似乎是标签的问题，试过设置num class为149、150、151都不行
数据集是自动下载的，ade20k也没改动

**Comment by wuyefeilin** [comment]
@JiehangXie 感谢反馈， 已提pr：https://github.com/PaddlePaddle/PaddleSeg/pull/896

**Comment by michaelowenliu** [comment]
@JiehangXie Hi, we have already reloved the problem, please update the code and try again.

**Comment by JiehangXie** [comment]
> @JiehangXie Hi, we have already reloved the problem, please update the code and try again.

Test succeed!The bug has been fixed. Thank you!
