### ISSUE TITLE
gpu利用率低，提升加载速度

### ISSUE THREAD

**Issue by clannadcl** [PaddlePaddle/PaddleSeg#891]
用deeplabv3，xception的模型，训练apollo的数据时，gpu占用率经常会降为0；
如何有效的提升数据加载速度呢

**Comment by michaelowenliu** [comment]
@clannadcl Hi, how do you set the num_workers?

**Comment by clannadcl** [comment]
@michaelowenliu Setting it to 16 and 32 both cause the above problem. And it is noteworthy that the GPU memory is almost full.

**Comment by michaelowenliu** [comment]
@clannadcl Hi, try a smaller input size or batch size. btw, which PaddleSeg version are you using?

**Comment by clannadcl** [comment]
@michaelowenliu Thanks! The problem has just been solved by choosing multiprocess reader. And I‘m using version 0.8.

**Comment by lybcodes** [comment]
你好，我也遇到了这个 问题，请问是要加改什么参数吗

**Comment by clannadcl** [comment]
@lybcodes 把train.py中的--use_mpio开关打开就可以了，设置成多进程数据读取，默认是用的多线程

**Comment by lybcodes** [comment]
> @lybcodes 把train.py中的--use_mpio开关打开就可以了，设置成多进程数据读取，默认是用的多线程

谢谢你哈，不过我开了这个也不行。。。我提个issue吧

**Comment by lybcodes** [comment]
> @lybcodes 把train.py中的--use_mpio开关打开就可以了，设置成多进程数据读取，默认是用的多线程

谢谢你哈，不过我开了这个也不行。。。我提个issue吧
