### ISSUE TITLE
使用imgaug库进行数据增强后，报错Cudnn error

### ISSUE THREAD

**Issue by Yeoh-Yang** [PaddlePaddle/PaddleSeg#892]
![Snipaste_2021-03-16_17-06-47](https://user-images.githubusercontent.com/77280564/111283602-4368b600-867a-11eb-8c8e-1b812da9c9df.png)

**Comment by wuyefeilin** [comment]
请问一下你是如何使用imgaug的， 另外麻烦你提供一下PaddleSeg， Paddle,  cudnn， cuda版本

**Comment by yang20085936** [comment]
> 请问一下你是如何使用imgaug的， 另外麻烦你提供一下PaddleSeg， Paddle, cudnn， cuda版本

我也出现了类似的问题，在本地重现官方“PaddleSeg与放射临床工作的小结合(Paddle2.0)” `https://aistudio.baidu.com/aistudio/projectdetail/2072960 '时候报错：
`OSError: (External)  Cudnn error, CUDNN_STATUS_VERSION_MISMATCH  (at /paddle/paddle/fluid/operators/pool_cudnn_op.cu.cc:484)`
新重装的系统，系统和对应虚拟环境的cuda为11.1，cudnn为8.1。ubuntu系统下conda的虚拟环境，paddle为2.1版本,paddleseg也是2.1版本。最开始以为是paddle 的问题，按照官方的issue下搞了半天发现没用。后来发现不用padeleseg，单独的paddele并没有报错。怀疑是paddleseg 的问题。

**Comment by wuyefeilin** [comment]
> > 请问一下你是如何使用imgaug的， 另外麻烦你提供一下PaddleSeg， Paddle, cudnn， cuda版本
> 
> 我也出现了类似的问题，在本地重现官方“PaddleSeg与放射临床工作的小结合(Paddle2.0)” `https://aistudio.baidu.com/aistudio/projectdetail/2072960 '时候报错： `OSError: (External) Cudnn error, CUDNN_STATUS_VERSION_MISMATCH (at /paddle/paddle/fluid/operators/pool_cudnn_op.cu.cc:484)`
> 新重装的系统，系统和对应虚拟环境的cuda为11.1，cudnn为8.1。ubuntu系统下conda的虚拟环境，paddle为2.1版本,paddleseg也是2.1版本。最开始以为是paddle 的问题，按照官方的issue下搞了半天发现没用。后来发现不用padeleseg，单独的paddele并没有报错。怀疑是paddleseg 的问题。

你可以运行一下paddle.utils.run_check()检查是否安装正确
