### ISSUE TITLE
No rule to make target '/PaddleSeg-develop/opencv/share/OpenCV/3rdparty/lib64/libIlmImf.a', needed by 'demo'.  Stop

### ISSUE THREAD

**Issue by YAwei666** [PaddlePaddle/PaddleSeg#893]
大佬们，cpp make时出错，opencv编译是不是缺了点啥啊

**Comment by michaelowenliu** [comment]
@YAwei666 Hi, can you put the detailed error log?

**Comment by YAwei666** [comment]
![image](https://user-images.githubusercontent.com/34396185/111447097-0f5bc680-8748-11eb-9b4c-d6d0cd478a3f.png)

**Comment by Channingss** [comment]
@YAwei666 请描述一下系统环境，包括操作系统，GCC版本，以及opencv使用的方式等，尽可能细节一下。

**Comment by YAwei666** [comment]
ubuntu16.04  gcc version 7.5.0 opencv按照https://github.com/PaddlePaddle/PaddleSeg/blob/develop/legacy/deploy/cpp/docs/linux_build.md
![image](https://user-images.githubusercontent.com/34396185/111570054-f18d7080-87de-11eb-9f82-001ff531984a.png)
按这个过程操作出现在编译环节make出现该问题，编译为cpu版

**Comment by Channingss** [comment]
@YAwei666 所以你将opencv的路径放在了`/PaddleSeg-develop/opencv/` ？然后 --DCMAKE_INSTALL_PREFIX=/PaddleSeg-develop/opencv/ ?

**Comment by YAwei666** [comment]
对

**Comment by Channingss** [comment]
@YAwei666 参考一下这两个链接试试：
https://github.com/opencv/opencv/issues/15497
https://blog.csdn.net/pihuanwan3227/article/details/85229942
