### ISSUE TITLE
padseg如何调整config文件或者loss函数实现对不同类别使用不同的权重进行训练？

### ISSUE THREAD

**Issue by Irvingao** [PaddlePaddle/PaddleSeg#894]

**Comment by michaelowenliu** [comment]
@Irvingao Hi, just add a weight parameter into config file. https://github.com/PaddlePaddle/PaddleSeg/blob/release/v2.0/paddleseg/models/losses/cross_entropy_loss.py

**Comment by Irvingao** [comment]
### But there is no input param which is weight  in my paddleseg's cross_entropy_loss.py.
![image](https://user-images.githubusercontent.com/58903762/111456512-0ff95a80-8752-11eb-95a8-75e7657b3ba0.png)
### So can I just copy the lastest cross_entropy_loss.py to my project and use it?

**Comment by michaelowenliu** [comment]
@Irvingao Hi, please update the repo. We enabled the feature last week.

**Comment by Irvingao** [comment]
Thanks bro !
