### ISSUE TITLE
2.0训练出来的模型经过export.py导出后，通过c++预测部署

### ISSUE THREAD

**Issue by lybcodes** [PaddlePaddle/PaddleSeg#897]
2.0训练出来的模型经过export.py导出后，通过c++预测部署可以直接按照legacy/deploy/cpp里的c++预测部署文档来吗？但是我看模型导出后的deploy.yaml文件还有模型文件名称这些都跟legacy/deploy/cpp里的部署文档里写的不一样

**Comment by michaelowenliu** [comment]
@lybcodes Hi, CPP deployment in 2.0 is under development. Coming soon.
