### ISSUE TITLE
DeepLabv3+中backbone为mobilenetv3训练问题

### ISSUE THREAD

**Issue by yy11223** [PaddlePaddle/PaddleSeg#899]
DeepLabv3+中仅backbone替换为mobilenetv3_large，训练时以下参数中，仅
ASPP_WITH_SEP_CONV: False
ASPP_WITH_SE: False
这两个参数设置为False，
（1）为何训练100epoch后，miou值（Cityscapes val）只有52%左右，这与开源论文：《Searching for MobileNetV3》里MobileNetV3用于Semantic Segmentation results on Cityscapes val set的72%（什么也不加的前提）差别怎么这么大呢？
（2）当把
DEFAULT_NORM_TYPE: "gn"
ASPP_WITH_SEP_CONV: True
ASPP_WITH_SE: True
这两个参数改为True且用gn代替bn后，训练100epoch，miou值能达到72%左右，这与paddle示例和开源论文中结论大体一致，注意力机制SE和gn提升效果应该有限，不明白在DeepLabv3+中，为何增加这两个后，miou值就能够大幅度提升？
MODEL:
    DEFAULT_NORM_TYPE: "bn"
    MODEL_NAME: "deeplabv3p"
    DEEPLAB:
        BACKBONE: "mobilenetv3_large"
        ASPP_WITH_SEP_CONV: False
        DECODER_USE_SEP_CONV: True
        ENCODER_WITH_ASPP: True
        ENABLE_DECODER: True
        OUTPUT_STRIDE: 32
        BACKBONE_LR_MULT_LIST: [0.15,0.35,0.65,0.85,1]
        ENCODER:
            POOLING_STRIDE: (4, 5)
            POOLING_CROP_SIZE: (769, 769)
            ASPP_WITH_SE: False
            SE_USE_QSIGMOID: True

**Comment by michaelowenliu** [comment]
@yy11223 Hi, separable conv is the key idea in deeplabv3+.

**Comment by yy11223** [comment]
可是在deeplabv3+中，单独应用separable conv（即ASPP_WITH_SEP_CONV:&nbsp;True）获得的miou反而比ASPP_WITH_SEP_CONV:&nbsp;False（其它参数不变）时还要低




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 晚上8:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] DeepLabv3+中backbone为mobilenetv3训练问题 (#899)





 
@yy11223 Hi, separable conv is the key idea in deeplabv3+.

**Comment by michaelowenliu** [comment]
@michaelowenliu Hi, how about your dataset?

**Comment by yy11223** [comment]
Cityscapes val




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月19日(星期五) 上午9:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] DeepLabv3+中backbone为mobilenetv3训练问题 (#899)





 
@michaelowenliu Hi, how about your dataset?

**Comment by Dasenyoung** [comment]
大佬，求一个deeplabv3p骨干网络为V3的源码

**Comment by yyfde** [comment]
> 大佬，求一个deeplabv3p骨干网络为V3的源码

老哥，找到了嘛
