### ISSUE TITLE
deeplabv3p_xception65_optic.yaml训练出错

### ISSUE THREAD

**Issue by lybcodes** [PaddlePaddle/PaddleSeg#902]
训练命令python pdseg/train.py --cfg configs deeplabv3p_xception65_optic.yaml --use_gpu --do-eval
训练不到一轮就会出现这句刷屏错误 std::furture error  no state
而且GPU利用率特别低 只有不到4%，有时候甚至是0，好像就没用GPU一样

**Comment by wuyefeilin** [comment]
你好，麻烦提供一下完整的训练日志。目前我们已提供动态图版本，欢迎使用哈。
