### ISSUE TITLE
export CUDA_VISIBLE_DEVICES=1 没有用，在代码里加os也没有用

### ISSUE THREAD

**Issue by yunchangxiaoguan** [PaddlePaddle/PaddleSeg#907]
请问怎么配置使用的GPU呢，怎么设置都没用，还是读GPU0
train.py里加了os.environ['CUDA_VISIBLE_DEVICES']=‘1‘  也没用

[root@ywcx-ailab-aly PaddleSeg]# export CUDA_VISIBLE_DEVICES=1
[root@ywcx-ailab-aly PaddleSeg]# python3 train.py --config configs/my.yaml --save_interval 500 --save_dir output/my
2021-03-20 11:43:20 [INFO]	
------------Environment Information-------------
platform: Linux-3.10.0-1127.8.2.el7.x86_64-x86_64-with-centos-7.8.2003-Core
Python: 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Paddle compiled with cuda: True
NVCC: Cuda compilation tools, release 10.0, V10.0.130
cudnn: 7.6
GPUs used: 1
CUDA_VISIBLE_DEVICES: 1
GPU: ['GPU 0: Tesla P100-PCIE-16GB', 'GPU 1: Tesla P100-PCIE-16GB']
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
PaddlePaddle: 2.0.1
OpenCV: 4.2.0
------------------------------------------------
2021-03-20 11:43:20 [INFO]	
---------------Config Information---------------
batch_size: 1
iters: 1000
learning_rate:
  decay:
    end_lr: 0
    power: 0.9
    type: poly
  value: 0.01
loss:
  coef:
  - 1
  - 1
  - 1
  - 1
  - 1
  types:
  - ignore_index: 255
    type: CrossEntropyLoss
model:
  pretrained: null
  type: BiSeNetV2
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 4.0e-05
train_dataset:
  dataset_root: data/my_data
  mode: train
  num_classes: 19
  train_path: data/my_data/train.txt
  transforms:
  - target_size:
    - 512
    - 512
    type: Resize
  - type: RandomHorizontalFlip
  - type: Normalize
  type: Dataset
val_dataset:
  dataset_root: data/my_data
  mode: val
  num_classes: 19
  train_path: data/my_data/val.txt
  transforms:
  - target_size:
    - 512
    - 512
    type: Resize
  - type: Normalize
  type: Dataset
------------------------------------------------
W0320 11:43:20.923413 25547 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 6.0, Driver API Version: 10.2, Runtime API Version: 10.2
W0320 11:43:20.923449 25547 device_context.cc:372] device: 0, cuDNN Version: 7.6.
/usr/local/lib64/python3.6/site-packages/paddle/nn/layer/norm.py:648: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    main(args)
  File "train.py", line 154, in main
    fp16=args.fp16)
  File "/ailab/gx/PaddleSeg/paddleseg/core/train.py", line 203, in train
    avg_loss += loss.numpy()[0]
OSError: (External)  Cuda error(719), unspecified launch failure.
  [Advise: Please search for the error code(719) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:301)

**Comment by xmy0916** [comment]
请问怎么解决的？

**Comment by xmy0916** [comment]
@yunchangxiaoguan
