### ISSUE TITLE
请问一下，在使用piecewise_decay的学习率衰减策略时，milestone参数一般是怎么设置的呢？

### ISSUE THREAD

**Issue by songyuc** [PaddlePaddle/PaddleSeg#917]
尊敬的开发者们，你好👋，

请问一下，在使用piecewise_decay的学习率衰减策略时，milestone参数一般是怎么设置的呢？

期待你们的回复！

**Comment by LutaoChu** [comment]
你好，据我所知，picewise_decay并没有milstone参数
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/optimizer/lr/PiecewiseDecay_cn.html#piecewisedecay

**Comment by songyuc** [comment]
不好意思，我看的可能是之前版本的paddle模型；我还想请教一下，那学习率调整的boundaries参数一般是怎么设置的呢？

**Comment by LutaoChu** [comment]
这个大致是等距分布，每个区间逐级递减。你可以参考一下文档里的示例  https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/optimizer/lr/PiecewiseDecay_cn.html#piecewisedecay

**Comment by songyuc** [comment]
@LutaoChu ，谢谢你的回复；我觉得这也是一个需要调节的超参数；

**Comment by LutaoChu** [comment]
是的，具体怎么调节需要自己摸索一下
不客气~

**Comment by songyuc** [comment]
十分感谢你的帮助！
