### ISSUE TITLE
“EVAL_CROP_SIZE”和“AUG.FIX_RESIZE_SIZE”

### ISSUE THREAD

**Issue by zhuyushi** [PaddlePaddle/PaddleSeg#92]
您好，请教一下，PaddleSeg的配置文件中，“EVAL_CROP_SIZE”和“AUG.FIX_RESIZE_SIZE”之间是什么关系，如果都配置了，是先进行corp然后在resize吗？如果我不想做任何裁剪，只想做resize应该如何配置呢？谢谢

TRAIN_CROP_SIZE: (512, 512) # (width, height), for unpadding rangescaling and stepscaling
EVAL_CROP_SIZE: (512, 512) # (width, height), for unpadding rangescaling and stepscaling
AUG:
    AUG_METHOD: "unpadding" # choice unpadding rangescaling and stepscaling
    FIX_RESIZE_SIZE: (512, 512) # (width, height), for unpadding

    INF_RESIZE_VALUE: 500  # for rangescaling
    MAX_RESIZE_VALUE: 600  # for rangescaling
    MIN_RESIZE_VALUE: 400  # for rangescaling

    MAX_SCALE_FACTOR: 1.25  # for stepscaling
    MIN_SCALE_FACTOR: 0.75  # for stepscaling
    SCALE_STEP_SIZE: 0.25  # for stepscaling
    MIRROR: True

**Comment by zhuyushi** [comment]
上面问题描述有误，是想知道训练时TRAIN_CROP_SIZE和AUG.FIX_RESIZE_SIZE的关系，不是EVAL_CROP_SIZE和AUG.FIX_RESIZE_SIZE的关系，谢谢

**Comment by LutaoChu** [comment]
您好，首先AUG.FIX_RESIZE_SIZE只在AUG_METHOD指定为unpadding模式下生效。此时，预处理过程会将图像resize到AUG.FIX_RESIZE_SIZE大小，随后再进行其他数据增强。

TRAIN_CROP_SIZE在AUG.FIX_RESIZE_SIZE的操作之后，对于数据增强后的图像以TRAIN_CROP_SIZE大小进行随机裁剪。最后输入网络的训练图像大小为TRAIN_CROP_SIZE。

具体数据增强过程请见：
https://github.com/LutaoChu/PaddleSeg/blob/release/v0.2.0/docs/data_aug.md

**Comment by zhuyushi** [comment]
文档已经看了，刚开始做语意分割，请想教些初级问题，烦请指教：
1、语意分割的模型，是否要求输入网络的图片是固定尺寸？
2、如果不想进行裁剪，是不是将TRAIN_CROP_SIZE配置从配置文件中删掉即可？
3、如果配置了TRAIN_CROP_SIZE，预处理时，除了将随机裁剪后的图片输入网络训练之外，是否还会降裁剪之前的图片送入网络训练？

**Comment by LutaoChu** [comment]
1、原始图片尺寸不要求固定，对于不同尺寸的训练图片，PaddleSeg会自动进行预处理保证输入到网络的图片是固定尺寸的。
2、TRAIN_CROP_SIZE是必填项，删除会导致错误。如果不想裁剪，并且训练集尺寸是一样的，可以设置TRAIN_CROP_SIZE为原图大小，AUG_METHOD指定为unpadding，这样就会跳过裁剪过程。
3、不会。只会将预处理后的图片输入到网络中。

**Comment by zhuyushi** [comment]
1、原始图片尺寸不要求固定，对于不同尺寸的训练图片，PaddleSeg会自动进行预处理保证输入到网络的图片是固定尺寸的。
-----输入到网络的图片固定尺寸的值，是可以通过TRAIN_CROP_SIZE来配置的吗？还是模型已经固定了一个值，我们不能进行配置。

还有个问题，关于AUG中下面三个参数的问题
    INF_RESIZE_VALUE: 500  # for rangescaling
    MAX_RESIZE_VALUE: 600  # for rangescaling
    MIN_RESIZE_VALUE: 400  # for rangescaling
我看了相关的文档，有个疑问，图片的长边固定为INF_RESIZE_VALUE，短边按比例缩放，这时图片尺寸已经确定下来，那MAX_RESIZE_VALUE和MIN_RESIZE_VALUE这两个值有什么作用呢？谢谢

**Comment by LutaoChu** [comment]
是的，就是通过TRAIN_CROP_SIZE进行设置的。

MAX_RESIZE_VALUE和 MIN_RESIZE_VALUE是在训练阶段生效，每张图片的长边在MIN_RESIZE_VALUE到MAX_RESIZE_VALUE之间随机均匀取值。
INF_RESIZE_VALUE则在其他阶段生效，图片的长边固定为INF_RESIZE_VALUE

**Comment by zhuyushi** [comment]
非常感谢

**Comment by lfxx** [comment]
> 是的，就是通过TRAIN_CROP_SIZE进行设置的。
> 
> MAX_RESIZE_VALUE和 MIN_RESIZE_VALUE是在训练阶段生效，每张图片的长边在MIN_RESIZE_VALUE到MAX_RESIZE_VALUE之间随机均匀取值。
> INF_RESIZE_VALUE则在其他阶段生效，图片的长边固定为INF_RESIZE_VALUE

您好， 想问一下TRAIN_CROP_SIZE的值理论上来说是不是越大训练效果越好。比如同样一个数据集，1024*1024是不是会比512*512更好一点？

**Comment by LutaoChu** [comment]
理论上是这样的，只要不超过原图大小。

**Comment by lfxx** [comment]
> 理论上是这样的，只要不超过原图大小。

谢谢，还有三个问题望您能解惑：
1.如果训练集的图片分辨率均为3000*3000，TRAIN_CROP_SIZE选择1024还是512更好呢？
2.我理解的这几个参数的处理顺序：Resize到AUG.FIX_RESIZE_SIZE大小，然后再分训练和评估分别应用TRAIN_CROP_SIZE和EVAL_CROP_SIZE，这样理解对吗？但是在开发文档里有句话：`当AUG.AUG_METHOD为unpadding时，EVAL_CROP_SIZE的宽高应不小于AUG.FIX_RESIZE_SIZE的宽高`这句话不能理解，正常来说crop后的size小于原图size不是很正常的事吗?改成宽高不大于才正常吧？
3.在aug方式为unpadding时，TRAIN_CROP_SIZE并不能随意设置，应该是要不大于AUG.FIX_RESIZE_SIZE吧@LutaoChu
