### ISSUE TITLE
使用C++推理时，出现未加载kernelbase.pdq,报EnforceNotMet异常是什么原因

### ISSUE THREAD

**Issue by JustinHuang1984** [PaddlePaddle/PaddleSeg#922]
下载PaddleSeg  C++推理代码，先用Cmake编译，编译后导入参数，初始化能通过，过图片加载进去里，报未加载kernelbase.pdq错误，如图所示，想问下这个问题要怎么解决
![)_(BIX$ SJ4L8)D_6R5HJO](https://user-images.githubusercontent.com/59753769/112782789-7484b580-9080-11eb-8138-b2998508cf70.png)
![J(Y3 6A4}XE}4`2V0BNCBP](https://user-images.githubusercontent.com/59753769/112782798-764e7900-9080-11eb-90cb-0fc7f0136d7d.jpg)
![XD18_T0JTYV3RU7E}IWZ1XM](https://user-images.githubusercontent.com/59753769/112782807-78b0d300-9080-11eb-8bc1-0c59506eaba0.jpg)

**Comment by JustinHuang1984** [comment]
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0331 20:34:22.151665 14396 analysis_predictor.cc:88] Profiler is deactivated, and no profiling report will be generated.
I0331 20:34:22.277359 14396 op_compatible_info.cc:201] The default operator required version is missing. Please update the model version.
I0331 20:34:22.277359 14396 analysis_predictor.cc:852] MODEL VERSION: 0.0.0
I0331 20:34:22.278352 14396 analysis_predictor.cc:854] PREDICTOR VERSION: 1.6.1
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [conv_affine_channel_fuse_pass]e[0m
e[32m--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
I0331 20:34:24.370865 14396 graph_pattern_detector.cc:96] ---  detected 78 subgraphs
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [multihead_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
e[32m--- Running IR pass [fc_elementwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add_act_fuse_pass]e[0m
I0331 20:34:25.338344 14396 graph_pattern_detector.cc:96] ---  detected 53 subgraphs
e[32m--- Running IR pass [conv_elementwise_add2_act_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add_fuse_pass]e[0m
I0331 20:34:25.363276 14396 graph_pattern_detector.cc:96] ---  detected 26 subgraphs
e[32m--- Running IR pass [transpose_flatten_concat_fuse_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
I0331 20:34:25.383230 14396 ir_params_sync_among_devices_pass.cc:41] Sync params from CPU to GPU
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [memory_optimize_pass]e[0m
I0331 20:34:25.560871 14396 memory_optimize_pass.cc:223] Cluster name : relu_4.tmp_0  size: 33817088
I0331 20:34:25.560871 14396 memory_optimize_pass.cc:223] Cluster name : bilinear_interp_0.tmp_0  size: 1115136
I0331 20:34:25.561873 14396 memory_optimize_pass.cc:223] Cluster name : relu_67.tmp_0  size: 8921088
I0331 20:34:25.561873 14396 memory_optimize_pass.cc:223] Cluster name : batch_norm_4.tmp_2  size: 33817088
I0331 20:34:25.561873 14396 memory_optimize_pass.cc:223] Cluster name : depthwise_conv2d_1.tmp_0  size: 33817088
I0331 20:34:25.562835 14396 memory_optimize_pass.cc:223] Cluster name : relu_1.tmp_0  size: 16908544
I0331 20:34:25.562835 14396 memory_optimize_pass.cc:223] Cluster name : relu_72.tmp_0  size: 8921088
I0331 20:34:25.563834 14396 memory_optimize_pass.cc:223] Cluster name : image  size: 3158028
I0331 20:34:25.563834 14396 memory_optimize_pass.cc:223] Cluster name : relu_73.tmp_0  size: 1115136
I0331 20:34:25.563834 14396 memory_optimize_pass.cc:223] Cluster name : relu_69.tmp_0  size: 1115136
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0331 20:34:25.621702 14396 analysis_predictor.cc:481] ======= optimize end =======
e[37m---  skip [feed], feed -> imagee[0m
e[37m---  skip [depthwise_conv2d_1.tmp_0], fetch -> fetche[0m
W0331 20:34:26.628644 14396 device_context.cc:235] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 11.1, Runtime API Version: 10.0
W0331 20:34:26.708429 14396 device_context.cc:243] device: 0, cuDNN Version: 7.6.

**Comment by michaelowenliu** [comment]
@JustinHuang1984 Hi, it could be a problem with the VS or Window system. Can you try this way, https://docs.microsoft.com/en-us/answers/questions/233615/having-bad-problem-with-kernelbasepdb-not-found.html

**Comment by JustinHuang1984** [comment]
0x00007FFFEE8A3B29 处(位于 demo.exe 中)有未经处理的异常: Microsoft C++ 异常: paddle::platform::EnforceNotMet，位于内存位置 0x000000E965FBF0F0 处。

**Comment by JustinHuang1984** [comment]
还是会报上面的错
