### ISSUE TITLE
当前unet模型是不是不支持多尺度训练

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleSeg#926]
最近测试了一下unet模型，发现好像不支持多尺度的训练，后续这方面会支持吗

**Comment by michaelowenliu** [comment]
@BeyondYourself You may refer to this part, Hierarchical Multi-Scale Attention, https://github.com/PaddlePaddle/PaddleSeg/tree/release/v2.0/contrib/CityscapesSOTA
