### ISSUE TITLE
DeepLabv3+中 Pascal VOC数据集训练问题

### ISSUE THREAD

**Issue by yy11223** [PaddlePaddle/PaddleSeg#927]
Paddle版本：PaddlePaddle 2.0.1
训练yaml文件：lovasz_softmax_deeplabv3p_mobilenet_pascal.yaml

TRAIN_CROP_SIZE: (500, 500) # (width, height), for unpadding rangescaling and stepscaling  #训练时图像裁剪尺寸（宽，高）
EVAL_CROP_SIZE: (500, 500) # (width, height), for unpadding rangescaling and stepscaling  #验证时图像裁剪尺寸（宽，高）
AUG:
    AUG_METHOD: "stepscaling" # choice unpadding rangescaling and stepscaling
    FIX_RESIZE_SIZE: (500, 500) # (width, height), for unpadding

    INF_RESIZE_VALUE: 500  # for rangescaling
    MAX_RESIZE_VALUE: 600  # for rangescaling
    MIN_RESIZE_VALUE: 400  # for rangescaling

    MAX_SCALE_FACTOR: 1.25  # for stepscaling
    MIN_SCALE_FACTOR: 0.75  # for stepscaling
    SCALE_STEP_SIZE: 0.05  # for stepscaling
    MIRROR: True
    FLIP: True
BATCH_SIZE: 16  #批处理大小
DATASET:
    DATA_DIR: "./dataset/VOCtrainval_11-May-2012/VOC2012/"  #图片路径
    IMAGE_TYPE: "rgb"  # choice rgb or rgba  #图片类别“RGB”
    NUM_CLASSES: 21  #类别数（包括背景类别）
    TEST_FILE_LIST: "dataset/VOCtrainval_11-May-2012/VOC2012/ImageSets/Segmentation/val.list"
    TRAIN_FILE_LIST: "dataset/VOCtrainval_11-May-2012/VOC2012/ImageSets/Segmentation/train.list"
    VAL_FILE_LIST: "dataset/VOCtrainval_11-May-2012/VOC2012/ImageSets/Segmentation/val.list"
    VIS_FILE_LIST: "dataset/VOCtrainval_11-May-2012/VOC2012/ImageSets/Segmentation/val.list"
    IGNORE_INDEX: 255
    SEPARATOR: " "
MODEL:
    MODEL_NAME: "deeplabv3p"
    DEFAULT_NORM_TYPE: "bn"  #指定norm的类型，此处提供bn和gn（默认）两种选择，分别指batch norm和group norm。
    DEEPLAB:
        BACKBONE: "mobilenetv2"
        DEPTH_MULTIPLIER: 1.0
        ENCODER_WITH_ASPP: False
        ENABLE_DECODER: False
TRAIN:
    PRETRAINED_MODEL_DIR: ""
    MODEL_SAVE_DIR: "./saved_model/lovasz-softmax-voc"  #模型保存路径
    SNAPSHOT_EPOCH: 10
TEST:
    TEST_MODEL: "./saved_model/lovasz-softmax-voc/final"  #为测试模型路径
SOLVER:
    NUM_EPOCHS: 100  #训练epoch数，正整数
    LR: 0.0001  #初始学习率
    LR_POLICY: "poly"  #学习率下降方法, 选项为poly、piecewise和cosine
    OPTIMIZER: "sgd" #优化算法, 选项为sgd和adam
    LOSS: ["lovasz_softmax_loss","softmax_loss"]
    LOSS_WEIGHT:
        LOVASZ_SOFTMAX_LOSS: 0.2
        SOFTMAX_LOSS: 0.8

报错：Traceback (most recent call last):
  File "pdseg/train.py", line 468, in <module>
    main(args)
  File "pdseg/train.py", line 454, in main
    train(cfg)
  File "pdseg/train.py", line 238, in train
    train_prog, startup_prog, phase=ModelPhase.TRAIN)
  File "/home/aistudio/work/PaddleSeg/pdseg/models/model_builder.py", line 196, in build_model
    multi_lovasz_softmax_loss(logits, label, mask))
  File "/home/aistudio/work/PaddleSeg/pdseg/lovasz_losses.py", line 226, in multi_lovasz_softmax_loss
    avg_loss = lovasz_softmax(probas, label, ignore=ignore_mask)
  File "/home/aistudio/work/PaddleSeg/pdseg/lovasz_losses.py", line 133, in lovasz_softmax
    loss = lovasz_softmax_flat(vprobas, vlabels, classes=classes)
  File "/home/aistudio/work/PaddleSeg/pdseg/lovasz_losses.py", line 166, in lovasz_softmax_flat
    fg_sorted = fluid.layers.gather(fg, perm)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 8305, in gather
    attrs={'overwrite': overwrite})
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3023, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2222, in __init__
    self.desc.infer_shape(self.block.desc)
ValueError: (InvalidArgument) The last dim of index should be 1 when it is 2D, but we get -1
  [Hint: Expected index_dims[1] == 1, but received index_dims[1]:-1 != 1:1.] (at /paddle/paddle/fluid/operators/gather_op.cc:46)
  [operator < gather > error]

**Comment by michaelowenliu** [comment]
@yy11223 Hi, could you please try the dynamic graph version? https://github.com/PaddlePaddle/PaddleSeg/tree/release/v2.0/configs/deeplabv3p
