### ISSUE TITLE
关于基于UNet的工业标记表盘分割模型的问题

### ISSUE THREAD

**Issue by zhuyushi** [PaddlePaddle/PaddleSeg#93]
您好，PaddleSeg最新发布了一个基于UNet的工业标记表盘分割的模型，我下载了训练样本图片，看到图片的尺寸是不一致的，又看到模型的配置文件unet_mechanical_meter.yaml中有下面这条配置：
TRAIN_CROP_SIZE: (769, 769) # (width, height), for unpadding rangescaling and stepscaling
那么是否意味着，在训练之前会将图片裁剪为769*769的尺寸呢？很多训练原图已经达到了2048*1536，如果随机裁剪为769*769，那岂不是很可能裁剪的目标都没有了，还如何保证训练效果呢。还请释疑，非常感谢。

**Comment by LielinJiang** [comment]
> 您好，PaddleSeg最新发布了一个基于UNet的工业标记表盘分割的模型，我下载了训练样本图片，看到图片的尺寸是不一致的，又看到模型的配置文件unet_mechanical_meter.yaml中有下面这条配置：
> TRAIN_CROP_SIZE: (769, 769) # (width, height), for unpadding rangescaling and stepscaling
> 那么是否意味着，在训练之前会将图片裁剪为769_769的尺寸呢？很多训练原图已经达到了2048_1536，如果随机裁剪为769*769，那岂不是很可能裁剪的目标都没有了，还如何保证训练效果呢。还请释疑，非常感谢。

您好！随机裁剪是一种图像分割中非常常见的数据增广方式。它的具体做法是，先对图像在某一范围内(0.5-2.0)进行缩放。然后再对缩放的图像进行裁剪，尺寸不足的时候会先padding再裁剪。有的时候裁剪的确会造成某个类别缺失。但是由于图像上每个像素点都是有标注类别的，并不存在缺失目标的情况。相反这样的做法能够增加算法的鲁棒性。

**Comment by nepeplwu** [comment]
此issue在最近三个月内暂无更新，我们将关闭该问题。如有需要，请重新打开该issue。
