### ISSUE TITLE
请问humansegserver模型在预测的时候能否支持多个cpu？

### ISSUE THREAD

**Issue by liandanjia** [PaddlePaddle/PaddleSeg#930]
请看https://aistudio.baidu.com/aistudio/projectdetail/475345
我安装了paddlepaddle 2.0.1 cpu版，然后跑infer.py，发现用cpu跑比较慢。paddlepaddle提示要设置环境变量CPU_NUM，我设成4或者8，结果预测时间和不设置是一样的，我怀疑这个设置没起作用。而且infer.py也没有use_gpu=False的参数。

谢谢！

**Comment by LutaoChu** [comment]
你好，如果你安装的paddle cpu版本，infer.py会自动使用cpu，不会使用gpu的。
如果 CPU_NUM 与物理核心数相同，可能可以加速程序的运行。你可以试一下。
分割是计算密集型的应用，想要加速最好还是使用gpu

**Comment by liandanjia** [comment]
收到。物理核心是8个核，我试过CPU_NUM=8，看来是没效果。

**Comment by LutaoChu** [comment]
嗯嗯，humanseg应该还不支持多进程，所以CPU_NUM没效果是正常的
