### ISSUE TITLE
同一张图片预测结果不同，且成水平对称，如何解决

### ISSUE THREAD

**Issue by uiuinj** [PaddlePaddle/PaddleSeg#931]
用模型预测同一张图，结果不同，且水平对称，如何解决

>

**Comment by uiuinj** [comment]
[
](https://aistudio.baidu.com/aistudio/projectdetail/1339458?channelType=0&channel=0)
-

**Comment by uiuinj** [comment]
![1111](https://user-images.githubusercontent.com/65482999/112985699-17c5ef80-9193-11eb-9946-201e6d9356e0.png)
![2222](https://user-images.githubusercontent.com/65482999/112985737-26140b80-9193-11eb-93dd-b8f235d0a5c0.png)
官方训练集预测官方图片，却出现两种水平对称的情况，为什么

**Comment by BeyondYourself** [comment]
预测的配置可以发出来看看

**Comment by wuyefeilin** [comment]
你好，请给一下你的预测命令

**Comment by uiuinj** [comment]
我调用的是paddleseg包的API

![12344](https://user-images.githubusercontent.com/65482999/113098606-468fa480-922b-11eb-8b0f-15cb913ca7ab.png)
具体参数就是配置的这些

**Comment by wuyefeilin** [comment]
方便的话给一下你完整的预测的流程，预估应该是你在配置transform的时候添加了随机翻转的操作

**Comment by uiuinj** [comment]
已解决就是配置问题，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月31日(星期三) 下午2:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleSeg] 同一张图片预测结果不同，且成水平对称，如何解决 (#931)





 
方便的话给一下你完整的预测的流程，预估是应该你在配置transform的时候添加了随机翻转的操作
