### ISSUE TITLE
训练报错，RuntimeError: The length of logits_list should equal to the types of loss config: 5 != 2.

### ISSUE THREAD

**Issue by kingbirdWc** [PaddlePaddle/PaddleSeg#934]
训练报错提示RuntimeError: The length of logits_list should equal to the types of loss config: 5 != 2.

**Comment by kingbirdWc** [comment]
![image](https://user-images.githubusercontent.com/23066646/113243776-3a1c5200-92e6-11eb-86a1-f17d6501b77c.png)
教程上是这样的，我模仿着写提示找不到

**Comment by michaelowenliu** [comment]
@kingbirdWc Hi, please check the number of model output. It should be the same as the number of loss types in the config file.

**Comment by kingbirdWc** [comment]
> @kingbirdWc Hi, please check the number of model output. It should be the same as the number of loss types in the config file.

Hello, this model output only contains 2 classes, I have configured it in .yml file. Loss types also have 2 number. Some are as follows.

val_dataset:
  type: Dataset
  dataset_root: ./data/df_dataset_paddle/
  val_path: ./data/df_dataset_paddle/paddle_val_list.txt
  num_classes: 2
  transforms:
    - type: Normalize
  mode: val

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

learning_rate:
  value: 0.001
  decay:
    type: poly
    power: 0.9
    end_lr: 0

loss:
  types:
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
  coef: [0.4, 0.6]

model:
  type: UNet
  num_classes: 2
  use_deconv: False
  pretrained: Null

**Comment by michaelowenliu** [comment]
@kingbirdWc Hi, the length of logit_list in UNet is only one, but the number of loss is two, please check the output of UNet model there , https://github.com/PaddlePaddle/PaddleSeg/blob/release/v2.0/paddleseg/models/unet.py#L67
