### ISSUE TITLE
使用paddleseg训练的fcn_hrnetw18模型，在windows上使用tensorrt预测推理时报错

### ISSUE THREAD

**Issue by HuangLonghao** [PaddlePaddle/PaddleSeg#936]
![image](https://user-images.githubusercontent.com/62374694/113271251-e113e480-930c-11eb-9941-84a8c7a5b96e.png)
paddleseg 2.0 tensorrt7.2 paddlepaddle2.0 paddle-inference推理库
提示broadcast dimention mismatch，关掉tensorrt后可以正常推理
predict 部分代码：
![image](https://user-images.githubusercontent.com/62374694/113272487-40262900-930e-11eb-8e82-0e799c624934.png)

**Comment by cryoco** [comment]
您好，可否贴一下您用的预测模型，我们定位下原因

**Comment by HuangLonghao** [comment]
> 您好，可否贴一下您用的预测模型，我们定位下原因

链接：https://pan.baidu.com/s/1zpcYPvhRQlOS4aFE8NI8bg 
提取码：sx02 
我用的fcn-HRNetw18模型进行训练之后导出的部署模型

**Comment by cryoco** [comment]
您好，这个问题预计在下个版本2.0.2会修复，这两天会发布，您可以关注验证下
