### ISSUE TITLE
测试代码导出的模型推理结果和直接predict结果不一致

### ISSUE THREAD

**Issue by yoyao1** [PaddlePaddle/PaddleSeg#938]
测试代码导出的模型推理infer.py结果和直接predict.py结果不一致。大体位置一样，边缘有区别

**Comment by wuyefeilin** [comment]
检查一下是否是数据预处理不一致导致的问题

**Comment by yoyao1** [comment]
debugfile('H:/py/PaddleSeg/predict.py',args='--config configs/quick_start/bisenet_optic_disc_512x512_1k.yml \
       --model_path output/iter_1000/model.pdparams \
       --image_path data/optic_disc_seg/JPEGImages/H0003.jpg \
       --save_dir output/result', wdir='H:/py/PaddleSeg')
debugfile('H:/py/PaddleSeg/deploy/python/infer.py',args='--config output/1/deploy.yaml --image_path data/optic_disc_seg/JPEGImages/H0003.jpg', wdir='H:/py/PaddleSeg')

预处理都是一样的

**Comment by yoyao1** [comment]
runfile('H:/py/PaddleSeg/export.py',args='--config configs/quick_start/bisenet_optic_disc_512x512_1k.yml \
--save_dir output/3 \
--model_path output/iter_1000/model.pdparams ', wdir='H:/py/PaddleSeg')
导出的代码

**Comment by wuyefeilin** [comment]
这种情况是正常的，因为导出的时候默认的transform只有normalize, 跟predict有所差异，你可以在导出的时候修改transform的配置（https://github.com/PaddlePaddle/PaddleSeg/blob/release/v2.0/export.py#L72）， 然后在推理的时候相应的对后处理进行更改（https://github.com/PaddlePaddle/PaddleSeg/blob/release/v2.0/deploy/python/infer.py#L108）。

我们后续会对这一块进行优化，提升体验。

**Comment by yoyao1** [comment]
predict也是normalize啊？ 我看预处理后结果是一样的

**Comment by wuyefeilin** [comment]
> predict也是normalize啊？ 我看预处理后结果是一样的

predict的预处理还有一个resize到512x512的操作哈

**Comment by yoyao1** [comment]
data/optic_disc_seg/JPEGImages/H0003.jpg 这个图本身就是512x512 的，我看预处理后tensor的数据是一样的

**Comment by wuyefeilin** [comment]
> data/optic_disc_seg/JPEGImages/H0003.jpg 这个图本身就是512x512 的，我看预处理后tensor的数据是一样的

方便的话，可以定位一下是数据预处理，模型推理，数据后处理的哪个环节开始出现不同

**Comment by yoyao1** [comment]
应该是 模型推理 出的问题， 推理前的预处理后的数据是一样的，推理后的tensor就不一样了

**Comment by wuyefeilin** [comment]
好的，多谢反馈哈，我们这边会尽快修复问题
