### ISSUE TITLE
在docker中多卡训练问题

### ISSUE THREAD

**Issue by pkuCactus** [PaddlePaddle/PaddleSeg#939]
在docker中（--shm-size已经设置为机器的内存大小），用多卡训练报错
```
CUDA_VISIBLE_DEVICES=0,1 python -u -m paddle.distributed.launch train.py --config configs/mscale_ocr_cityscapes_autolabel_mapillary.yml --use_vdl --save_dir saved_model/mscale_ocr_cityscapes_autolabel_mapillary --save_interval 2000 --num_workers 2 --do_eval
```

OSError: (External)  Nccl error, invalid data type, detail: Resource temporarily unavailable
Please try one of the following solutions:
1. export NCCL_SHM_DISABLE=1;
2. export NCCL_P2P_LEVEL=SYS;
3. Increase shared memory by setting the -shm-size option when starting docker container, e.g., setting  -shm-size=2g.
  (at /paddle/paddle/fluid/operators/collective/broadcast_op.cu.cc:65)
  [operator < broadcast > error]
terminate called without an active exception

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1617366731 (unix time) try "date -d @1617366731" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x6941) received by PID 26945 (TID 0x7fbd52c03700) from PID 26945 ***]

INFO 2021-04-02 20:32:17,600 launch_utils.py:307] terminate all the procs
ERROR 2021-04-02 20:32:17,601 launch_utils.py:545] ABORT!!! Out of all 8 trainers, the trainer process with rank=[3] was aborted. Please check its log.
INFO 2021-04-02 20:32:20,603 launch_utils.py:307] terminate all the procs

但是只用单卡训练就一切正常
2021-04-02 20:52:02 [INFO]      [TRAIN] epoch=1, iter=80/65000, loss=3.4729, lr=0.004988, batch_cost=6.2621, reader_cost=0.00100, ips=0.1597 samples/sec | ETA 112:55:37

想请教一下这是什么问题，有什么解决办法吗

**Comment by LutaoChu** [comment]
试一下这3种方法的任意一种能不能成功？
1 训练启动命令去掉--num_workers；
2 export NCCL_SHM_DISABLE=1;
3 export NCCL_P2P_LEVEL=SYS;

**Comment by pkuCactus** [comment]
感谢，已经解决，重新安装了docker里的nccl和cudnn就好了

**Comment by LutaoChu** [comment]
不客气，恭喜解决
