### ISSUE TITLE
训练结束后自动导出IOU指标最好的模型

### ISSUE THREAD

**Issue by chliang** [PaddlePaddle/PaddleSeg#94]
自动导出IOU指标最好的模型，而不是导出 `final`

**Comment by LutaoChu** [comment]
您好，此功能正在开发中，敬请期待！

**Comment by HOLLIZHAO** [comment]
Save best model ... mIoU = 0.7354， 这个在 2020.02.25 v0.4.0 已经实现！👍👍👍
