### ISSUE TITLE
自己数据集上eval.py无法运行

### ISSUE THREAD

**Issue by clannadcl** [PaddlePaddle/PaddleSeg#944]
paddleseg版本为0.8，quick start里关于optic数据集的eval.py是能够跑通的，可以得到iou和acc结果，但是在自己数据集上会报错，具体日志如下：

W0407 09:36:18.678267 134708 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.2, Runtime API Version: 10.1
W0407 09:36:18.679236 134708 device_context.cc:346] device: 0, cuDNN Version: 7.6.
{'AUG': {'AUG_METHOD': 'stepscaling',
         'FIX_RESIZE_SIZE': (3384, 2710),
         'FLIP': False,
         'FLIP_RATIO': 0.5,
         'INF_RESIZE_VALUE': 500,
         'MAX_RESIZE_VALUE': 600,
         'MAX_SCALE_FACTOR': 2.0,
         'MIN_RESIZE_VALUE': 400,
         'MIN_SCALE_FACTOR': 0.5,
         'MIRROR': True,
         'RICH_CROP': {'ASPECT_RATIO': 0.33,
                       'BLUR': False,
                       'BLUR_RATIO': 0.1,
                       'BRIGHTNESS_JITTER_RATIO': 0.5,
                       'CONTRAST_JITTER_RATIO': 0.5,
                       'ENABLE': False,
                       'MAX_ROTATION': 15,
                       'MIN_AREA_RATIO': 0.5,
                       'SATURATION_JITTER_RATIO': 0.5},
         'SCALE_STEP_SIZE': 0.25,
         'TO_RGB': False},
 'BATCH_SIZE': 16,
 'DATALOADER': {'BUF_SIZE': 256, 'NUM_WORKERS': 16},
 'DATASET': {'DATA_DIM': 3,
             'DATA_DIR': '',
             'IGNORE_INDEX': 255,
             'IMAGE_TYPE': 'rgb',
             'NUM_CLASSES': 6,
             'PADDING_VALUE': [127.5, 127.5, 127.5],
             'SEPARATOR': ' ',
             'TEST_FILE_LIST': './dataset/val.txt',
             'TEST_TOTAL_IMAGES': 5683,
             'TRAIN_FILE_LIST': './dataset/re_train.txt',
             'TRAIN_TOTAL_IMAGES': 364722,
             'VAL_FILE_LIST': './dataset/val.txt',
             'VAL_TOTAL_IMAGES': 5683,
             'VIS_FILE_LIST': './dataset/val.txt'},
 'EVAL_CROP_SIZE': (3384, 2710),
 'FREEZE': {'MODEL_FILENAME': 'model',
            'PARAMS_FILENAME': 'params',
            'SAVE_DIR': 'freeze_model'},
 'MEAN': [0.5, 0.5, 0.5],
 'MODEL': {'BN_MOMENTUM': 0.99,
           'DEEPLAB': {'ASPP_WITH_SEP_CONV': True,
                       'BACKBONE': 'xception_65',
                       'BACKBONE_LR_MULT_LIST': None,
                       'DECODER': {'CONV_FILTERS': 256,
                                   'OUTPUT_IS_LOGITS': False,
                                   'USE_SUM_MERGE': False},
                       'DECODER_USE_SEP_CONV': True,
                       'DEPTH_MULTIPLIER': 1.0,
                       'ENABLE_DECODER': True,
                       'ENCODER': {'ADD_IMAGE_LEVEL_FEATURE': True,
                                   'ASPP_CONVS_FILTERS': 256,
                                   'ASPP_RATIOS': None,
                                   'ASPP_WITH_CONCAT_PROJECTION': True,
                                   'ASPP_WITH_SE': False,
                                   'POOLING_CROP_SIZE': None,
                                   'POOLING_STRIDE': [1, 1],
                                   'SE_USE_QSIGMOID': False},
                       'ENCODER_WITH_ASPP': True,
                       'OUTPUT_STRIDE': 16},
           'DEFAULT_EPSILON': 1e-05,
           'DEFAULT_GROUP_NUMBER': 32,
           'DEFAULT_NORM_TYPE': 'bn',
           'FP16': False,
           'HRNET': {'STAGE2': {'NUM_CHANNELS': [40, 80], 'NUM_MODULES': 1},
                     'STAGE3': {'NUM_CHANNELS': [40, 80, 160],
                                'NUM_MODULES': 4},
                     'STAGE4': {'NUM_CHANNELS': [40, 80, 160, 320],
                                'NUM_MODULES': 3}},
           'ICNET': {'DEPTH_MULTIPLIER': 0.5, 'LAYERS': 50},
           'MODEL_NAME': 'deeplabv3p',
           'MULTI_LOSS_WEIGHT': [1.0],
           'OCR': {'OCR_KEY_CHANNELS': 256, 'OCR_MID_CHANNELS': 512},
           'PSPNET': {'DEPTH_MULTIPLIER': 1, 'LAYERS': 50},
           'SCALE_LOSS': 'DYNAMIC',
           'UNET': {'UPSAMPLE_MODE': 'bilinear'}},
 'NUM_TRAINERS': 1,
 'SLIM': {'KNOWLEDGE_DISTILL': False,
          'KNOWLEDGE_DISTILL_IS_TEACHER': False,
          'KNOWLEDGE_DISTILL_TEACHER_MODEL_DIR': '',
          'NAS_ADDRESS': '',
          'NAS_IS_SERVER': True,
          'NAS_PORT': 23333,
          'NAS_SEARCH_STEPS': 100,
          'NAS_SPACE_NAME': '',
          'NAS_START_EVAL_EPOCH': 0,
          'PREPROCESS': False,
          'PRUNE_PARAMS': '',
          'PRUNE_RATIOS': []},
 'SOLVER': {'BEGIN_EPOCH': 1,
            'CROSS_ENTROPY_WEIGHT': None,
            'DECAY_EPOCH': [10, 20],
            'GAMMA': 0.1,
            'LOSS': ['softmax_loss'],
            'LOSS_WEIGHT': {'BCE_LOSS': 1,
                            'DICE_LOSS': 1,
                            'LOVASZ_HINGE_LOSS': 1,
                            'LOVASZ_SOFTMAX_LOSS': 1,
                            'SOFTMAX_LOSS': 1},
            'LR': 0.003,
            'LR_POLICY': 'poly',
            'LR_WARMUP': False,
            'LR_WARMUP_STEPS': 2000,
            'MOMENTUM': 0.9,
            'MOMENTUM2': 0.999,
            'NUM_EPOCHS': 36,
            'OPTIMIZER': 'sgd',
            'POWER': 0.9,
            'WEIGHT_DECAY': 4e-05},
 'STD': [0.5, 0.5, 0.5],
 'TEST': {'TEST_MODEL': 'saved_model/deeplabv3p_xception65_bn_optic/20'},
 'TRAIN': {'MODEL_SAVE_DIR': './saved_model/deeplabv3p_xception65_bn_optic/',
           'PRETRAINED_MODEL_DIR': './pretrained_model/deeplabv3p_xception65_bn_coco/',
           'RESUME_MODEL_DIR': '',
           'SNAPSHOT_EPOCH': 5,
           'SYNC_BATCH_NORM': True},
 'TRAINER_ID': 0,
 'TRAIN_CROP_SIZE': (769, 769)}
#Device count: 4
load test model: saved_model/deeplabv3p_xception65_bn_optic/20
/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:278: UserWarning: /root/paddlejob/workspace/road_inspection/code/paddleseg-v0.8/pdseg/models/backbone/xception.py:295
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:278: UserWarning: /root/paddlejob/workspace/road_inspection/code/paddleseg-v0.8/pdseg/loss.py:79
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Termination signal) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1617759466 (unix time) try "date -d @1617759466" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x20e34) received by PID 134734 (TID 0x7f3daca3e700) from PID 134708 ***]

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Termination signal) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1617759466 (unix time) try "date -d @1617759466" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x20e34) received by PID 134778 (TID 0x7f3daca3e700) from PID 134708 ***]

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Termination signal) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1617759466 (unix time) try "date -d @1617759466" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x20e34) received by PID 134742 (TID 0x7f3daca3e700) from PID 134708 ***]

----------------------
Error Message Summary:
----------------------

FatalError: A serious error (Termination signal) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)

----------------------
  [TimeInfo: *** Aborted at 1617759466 (unix time) try "date -d @1617759466" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x20e34) received by PID 134763 (TID 0x7f3daca3e700) from PID 134708 ***]
----------------------
Error Message Summary:

Error Message Summary:
----------------------
----------------------
FatalError: A serious error (Termination signal) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
FatalError: A serious error (Termination signal) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1617759466 (unix time) try "date -d @1617759466" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x20e34) received by PID 134754 (TID 0x7f3daca3e700) from PID 134708 ***]
  [TimeInfo: *** Aborted at 1617759466 (unix time) try "date -d @1617759466" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x20e34) received by PID 134760 (TID 0x7f3daca3e700) from PID 134708 ***]

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Termination signal) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1617759466 (unix time) try "date -d @1617759466" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x20e34) received by PID 134781 (TID 0x7f3daca3e700) from PID 134708 ***]

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Termination signal) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1617759466 (unix time) try "date -d @1617759466" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x20e34) received by PID 134784 (TID 0x7f3daca3e700) from PID 134708 ***]

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Termination signal) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1617759466 (unix time) try "date -d @1617759466" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x20e34) received by PID 134766 (TID 0x7f3daca3e700) from PID 134708 ***]

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Termination signal) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1617759466 (unix time) try "date -d @1617759466" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x20e34) received by PID 134751 (TID 0x7f3daca3e700) from PID 134708 ***]

----------------------
Error Message Summary:
----------------------

FatalError: A serious error (Termination signal) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
----------------------
Error Message Summary:
----------------------
  [TimeInfo: *** Aborted at 1617759466 (unix time) try "date -d @1617759466" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x20e34) received by PID 134739 (TID 0x7f3daca3e700) from PID 134708 ***]
FatalError: A serious error (Termination signal) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)

  [TimeInfo: *** Aborted at 1617759466 (unix time) try "date -d @1617759466" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x20e34) received by PID 134775 (TID 0x7f3daca3e700) from PID 134708 ***]

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Termination signal) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)

  [TimeInfo: *** Aborted at 1617759466 (unix time) try "date -d @1617759466" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x20e34) received by PID 134745 (TID 0x7f3daca3e700) from PID 134708 ***]
----------------------

Error Message Summary:
----------------------
----------------------
Error Message Summary:
FatalError: A serious error (Termination signal) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
----------------------
FatalError: A serious error (Termination signal) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1617759466 (unix time) try "date -d @1617759466" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x20e34) received by PID 134748 (TID 0x7f3daca3e700) from PID 134708 ***]
  [TimeInfo: *** Aborted at 1617759466 (unix time) try "date -d @1617759466" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x20e34) received by PID 134769 (TID 0x7f3daca3e700) from PID 134708 ***]

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Termination signal) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1617759466 (unix time) try "date -d @1617759466" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x20e34) received by PID 134757 (TID 0x7f3daca3e700) from PID 134708 ***]

----------------------
Error Message Summary:
----------------------
FatalError: A serious error (Termination signal) is detected by the operating system. (at /paddle/paddle/fluid/platform/init.cc:303)
  [TimeInfo: *** Aborted at 1617759466 (unix time) try "date -d @1617759466" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x20e34) received by PID 134772 (TID 0x7f3daca3e700) from PID 134708 ***]

Traceback (most recent call last):
  File "pdseg/eval.py", line 182, in <module>
    main()
  File "pdseg/eval.py", line 177, in main
    evaluate(cfg, **args.__dict__)
  File "pdseg/eval.py", line 138, in evaluate
    test_prog, fetch_list=fetch_list, return_numpy=True)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1107, in run
    six.reraise(*sys.exc_info())
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1105, in run
    return_merged=return_merged)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1229, in _run_impl
    use_program_cache=use_program_cache)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1314, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

  Compile Traceback (most recent call last):
    File "pdseg/eval.py", line 182, in <module>
      main()
    File "pdseg/eval.py", line 177, in main
      evaluate(cfg, **args.__dict__)
    File "pdseg/eval.py", line 95, in evaluate
      test_prog, startup_prog, phase=ModelPhase.EVAL)
    File "/root/paddlejob/workspace/road_inspection/code/paddleseg-v0.8/pdseg/models/model_builder.py", line 167, in build_model
      logits = seg_model(image, class_num)
    File "/root/paddlejob/workspace/road_inspection/code/paddleseg-v0.8/pdseg/models/model_builder.py", line 78, in seg_model
      logits = deeplab.deeplabv3p(image, class_num)
    File "/root/paddlejob/workspace/road_inspection/code/paddleseg-v0.8/pdseg/models/modeling/deeplab.py", line 374, in deeplabv3p
      data, decode_shortcut = xception(img)
    File "/root/paddlejob/workspace/road_inspection/code/paddleseg-v0.8/pdseg/models/modeling/deeplab.py", line 331, in xception
      decode_points=decode_point)
    File "/root/paddlejob/workspace/road_inspection/code/paddleseg-v0.8/pdseg/models/backbone/xception.py", line 101, in net
      data = self.entry_flow(input)
    File "/root/paddlejob/workspace/road_inspection/code/paddleseg-v0.8/pdseg/models/backbone/xception.py", line 145, in entry_flow
      param_attr=param_attr))
    File "/root/paddlejob/workspace/road_inspection/code/paddleseg-v0.8/pdseg/models/libs/model_libs.py", line 129, in conv
      return fluid.layers.conv2d(*args, **kargs)
    File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 1597, in conv2d
      "data_format": data_format,
    File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2917, in append_op
      attrs=kwargs.get("attrs", None))
    File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2014, in __init__
      for frame in traceback.extract_stack():
----------------------
Error Message Summary:
----------------------
ExternalError:  Cudnn error, CUDNN_STATUS_NOT_SUPPORTED  (at /paddle/paddle/fluid/platform/cudnn_desc.h:162)
  [operator < conv2d > error]
/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/reader.py:1188: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  logging.warn('Your reader has raised an exception!')
WARNING:root:Your reader has raised an exception!

**Comment by clannadcl** [comment]
@michaelowenliu 但是自己数据集训练和训练后的可视化结果都可以

**Comment by michaelowenliu** [comment]
@clannadcl Hi, Can you try the new version, i.e. 2.0?

**Comment by clannadcl** [comment]
@michaelowenliu 因为我的paddle版本不支持最新的2.0，所以没用

**Comment by wuyefeilin** [comment]
检查一下验证集的数据是否异常。 欢迎使用我们的动态图版本哈

**Comment by clannadcl** [comment]
@wuyefeilin 用check.py检查验证集没有问题，都pass通过了。目前的报错还是
----------------------                                                                                                               
Error Message Summary:                                                                                                               
----------------------                                                                                                               
ExternalError:  Cudnn error, CUDNN_STATUS_NOT_SUPPORTED  (at /paddle/paddle/fluid/platform/cudnn_desc.h:162)                         
  [operator < conv2d > error]

**Comment by clannadcl** [comment]
@wuyefeilin 用check.py检查验证集没有问题，都pass通过了。目前的报错还是
Error Message Summary:
ExternalError: Cudnn error, CUDNN_STATUS_NOT_SUPPORTED (at /paddle/paddle/fluid/platform/cudnn_desc.h:162)
[operator < conv2d > error]

与optic数据集应该只有测试图大小不同

**Comment by wuyefeilin** [comment]
> @michaelowenliu 但是自己数据集训练和训练后的可视化结果都可以

你用训练集进行验证看看是否正常

**Comment by clannadcl** [comment]
@wuyefeilin 不可以，同样的错误。设置文件里是这么设置的：

EVAL_CROP_SIZE: (3384, 2710)
TRAIN_CROP_SIZE: (769, 769)
AUG:
    AUG_METHOD: "stepscaling" # choice unpadding rangescaling and stepscaling
    FIX_RESIZE_SIZE: (3384, 2710) # (width, height), for unpadding
    INF_RESIZE_VALUE: 500  # for rangescaling
    MAX_RESIZE_VALUE: 600  # for rangescaling
    MIN_RESIZE_VALUE: 400  # for rangescaling
    MAX_SCALE_FACTOR: 2.0  # for stepscaling
    MIN_SCALE_FACTOR: 0.5  # for stepscaling
    SCALE_STEP_SIZE: 0.25  # for stepscaling
    MIRROR: True

**Comment by wuyefeilin** [comment]
换成这个配置试一下
EVAL_CROP_SIZE: (512, 512)
TRAIN_CROP_SIZE: (512, 512)
AUG:
AUG_METHOD: "unpadding" # choice unpadding rangescaling and stepscaling
FIX_RESIZE_SIZE: (512, 512) # (width, height), for unpadding

**Comment by clannadcl** [comment]
> 换成这个配置试一下
> EVAL_CROP_SIZE: (512, 512)
> TRAIN_CROP_SIZE: (512, 512)
> AUG:
> AUG_METHOD: "unpadding" # choice unpadding rangescaling and stepscaling
> FIX_RESIZE_SIZE: (512, 512) # (width, height), for unpadding

这样可以了，是因为原图太大了吗？
