### ISSUE TITLE
在使用官方的预训练进行训练后，如何进行finetune训练？

### ISSUE THREAD

**Issue by HuangLonghao** [PaddlePaddle/PaddleSeg#949]
我看训练接口没有pretrain相关的参数，只有一个resumecheckpoint可以从中断点继续训练，在config中的pretrain也只能设置为从网上下载的预训练模型

**Comment by michaelowenliu** [comment]
@HuangLonghao Hi, what's your question?

**Comment by HuangLonghao** [comment]
> @HuangLonghao Hi, what's your question?

在使用官方的预训练进行训练后，如何进行finetune训练？config中pretrained没法使用之前训练好的模型，训练相关接口中也只有resumecheckpoint中断点训练，没有finetune相关参数

**Comment by michaelowenliu** [comment]
@HuangLonghao Hi, please refer to the previous issue, https://github.com/PaddlePaddle/PaddleSeg/issues/633
