### ISSUE TITLE
人像分割有2.0.0版本的吗？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PaddleSeg#950]
这个模型：https://github.com/PaddlePaddle/PaddleSeg/tree/release/v2.0/legacy/contrib/HumanSeg
有没有2.0.0版本的。这个在新环境无法部署。

**Comment by michaelowenliu** [comment]
@yeyupiaoling Hi, coming soon.

**Comment by yeyupiaoling** [comment]
@michaelowenliu 那是时多快？

**Comment by yeyupiaoling** [comment]
@michaelowenliu 有没有工具将
![image](https://user-images.githubusercontent.com/26297768/114001697-bedf1100-988e-11eb-924e-1f195bb43991.png)

转为

![image](https://user-images.githubusercontent.com/26297768/114001730-c69eb580-988e-11eb-9858-08207e35ca16.png)
