### ISSUE TITLE
legacy模型压缩问题

### ISSUE THREAD

**Issue by qiyuezhiguang** [PaddlePaddle/PaddleSeg#953]
### 在模型剪枝的教程中有这样一步：
2. 确定待分析参数
我们通过剪裁卷积层参数达到缩减卷积层通道数的目的，在剪裁之前，我们需要确定待裁卷积层的参数的名称。 通过以下命令查看当前模型的所有参数：

 查看模型所有Paramters
for x in train_prog.list_vars():
    if isinstance(x, fluid.framework.Parameter):
        print(x.name, x.shape)
  ### 该代码需要运行在哪里，如何读取模型参数并进行显示呢？该代码孤零零的，无法使用，感谢答复。

**Comment by nepeplwu** [comment]
@qiyuezhiguang 抱歉造成了不好的体验，参考如下步骤
1. 将`PaddleSeg/legacy/pdseg`设置为PYTHONPATH
```shell
# 根据实际路径设置
export PYTHONPATH=XXXX/PaddleSeg/legacy/pdseg
# windows设置方式为
# set PYTHONPATH=XXXX/PaddleSeg/legacy/pdseg
```
2. 执行以下代码进行打印
```python
import paddle
import paddle.fluid as fluid

from utils.config import cfg
from models.model_builder import build_model, ModelPhase

# 替换为自己的配置文件路径
cfg.update_from_file('configs/cityscape_fast_scnn.yaml')

# 如果是2.0以上版本的paddlepaddle，调用下面的接口使用静态图模式
# paddle.enable_static()

startup_prog = fluid.Program()
train_prog = fluid.Program()
build_model(train_prog, startup_prog, phase=ModelPhase.TRAIN)

for x in train_prog.list_vars():
    if isinstance(x, fluid.framework.Parameter):
        print(x.name, x.shape)
```

另外，目前动态图版本已经支持剪枝、蒸馏等功能，查看[教程](https://github.com/PaddlePaddle/PaddleSeg/tree/release/v2.0/slim)动态图模式下有更多前沿的模型支持，欢迎体验
