### ISSUE TITLE
the model of decoupledsegnet

### ISSUE THREAD

**Issue by wangjiangtao916** [PaddlePaddle/PaddleSeg#954]
the model of decoupledsegnet can not be used, it will be take about Segmentation fault (core dumped),can you tell how to solve the problem?

**Comment by michaelowenliu** [comment]
@wangjiangtao916 Hi, Could you please put more information on the running environment, e.g. PaddlePaddle, PaddleSeg, CUDA version.

**Comment by wangjiangtao916** [comment]
I used the aistudio and PaddleSeg2.0

**Comment by wangjiangtao916** [comment]
i just run the yml according to the Paddleseg github, but is not successful

**Comment by michaelowenliu** [comment]
@wangjiangtao916 How about your cuda version?

**Comment by wangjiangtao916** [comment]
11.0

**Comment by michaelowenliu** [comment]
@wangjiangtao916 Hi, can you try cuda 10.2?
