### ISSUE TITLE
Remove unnecessary parameters whenever possible

### ISSUE THREAD

**Issue by franva** [PaddlePaddle/PaddleSeg#957]
Learning from this article:
https://aistudio.baidu.com/aistudio/projectdetail/1339458

One of the line of the code drew my attention:

```
from paddleseg.core import predict
predict(
        model,
        model_path='output/best_model/model.pdparams',
        transforms=transforms,
        image_list=image_list,
        image_dir=image_dir,
        save_dir='output/results'
    )
```

To an normal person's understanding, once we have the `model` loaded and ready to use, why do we need the `model_path` again?

Preferably the model_path should be inferred automatically, if not, then please move the `model_path` to the place where the model is initialized.

Not sure if this is possible with PaddleSeg.

Cheers,

Winston

**Comment by michaelowenliu** [comment]
@franva Hi, thanks for your suggestion. The `model_path` allows the user to run `predict` using different pre-trained parameters without initiating the model every time.
