### ISSUE TITLE
当前是否支持训练集为灰度图？

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleSeg#959]
想请教一下，当前训练是否支持输入图片为灰度图，或者是否支持混合类型的图片，比如输入图像既有3通道，又有单通道的图像。
上述所指的图像不包含标注图

**Comment by michaelowenliu** [comment]
@BeyondYourself Hi, currently not. We consider this new feature in a future version. Thanks for your good suggestion.

**Comment by BeyondYourself** [comment]
OK,thanks
