### ISSUE TITLE
windows平台使用GPU版本预测库编译出错

### ISSUE THREAD

**Issue by zhaotun** [PaddlePaddle/PaddleSeg#96]
按照[Windows平台使用 Visual Studio 2015 编译指南](https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.2.0/inference/docs/windows_vs2015_build.md)使用GPU版本的预测库编译时发生以下错误
![image](https://user-images.githubusercontent.com/13940249/69114742-360cdd00-0ac1-11ea-96d9-a6656a29c5fd.png)
编译命令为：
```shell
cmake .. -G "Visual Studio 14 2015 Win64" -DWITH_GPU=ON -DPADDLE_DIR=F:\ImageSegmentation\fluid_inference_cuda10_cudnn7_avx_mkl_v160 -DCUDA_LIB=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\lib\x64 -DOPENCV_DIR=C:\opencv_3.4 -T host=x64
```
使用的GPU版本库是从这里下载的：[安装与编译Windows预测库](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/deploy/inference/windows_cpp_inference.html)
![image](https://user-images.githubusercontent.com/13940249/69114827-6eacb680-0ac1-11ea-818c-8d7b320582df.png)
CUDA版本为：
![image](https://user-images.githubusercontent.com/13940249/69114848-8dab4880-0ac1-11ea-82f1-abbc96198ac1.png)

**使用CPU版本编译是没错的。**

**Comment by joey12300** [comment]
@zhaotun 你好，-DCUDA_LIB后的路径有空格，所以请使用双引号包住路径。至于预测库，可以通过该链接下载1.6.1版本的预测库：https://bj.bcebos.com/paddlehub/paddle_inference_lib/fluid_inference_install_dir_win_cuda10_1.6.1.zip

**Comment by zhaotun** [comment]
@joey12300 确实是的，加双引号包住后跑通了，GTX1050TI  4G  gpu 比 i5 cpu 速度快了10倍多，谢谢大佬！

**Comment by ZeyuChen** [comment]
问题已解决，如果还有其他问题可以随时Reopen issues咨询，谢谢。
