### ISSUE TITLE
ResizeByLong has no attribute 'target_size'

### ISSUE THREAD

**Issue by Birdylx** [PaddlePaddle/PaddleSeg#960]
when I use ResizeByLong for evaluation, the infer.py in paddleseg/core report a error that ResizeByLong has no attribute 'target_size'.
It seems that there is a bug in ResizeByLong class, it has args of long_size, but not target_size, and the infer.py need transforms op.target_size. So, I just simply add a new attribute ` self.target_size = im.shape[:2] ` in ResizeByLong class, and it works. I'm not sure if I fixed the bug, maybe you shouled update it?

**Comment by michaelowenliu** [comment]
@Birdylx Hi, yes, we will fix the bug soon, thanks for your great issue!

**Comment by michaelowenliu** [comment]
@Birdylx Hi, fix it already, please update it. https://github.com/PaddlePaddle/PaddleSeg/pull/971/files
