### ISSUE TITLE
'BiSeNetV2' object has no attribute 'data_format'

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSeg#962]
paddlepaddle-gpu   2.0.1.post110
paddleseg          2.0.0
Cuda compilation tools, release 11.0, V11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0

验证安装
python train.py --config configs/quick_start/bisenet_optic_disc_512x512_1k.yml

报错
------------------------------------------------
W0412 22:29:38.847007 16703 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 11.0
W0412 22:29:38.847024 16703 device_context.cc:372] device: 0, cuDNN Version: 8.0.
/home/mm/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py:89: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if isinstance(slot[0], (np.ndarray, np.bool, numbers.Number)):
Traceback (most recent call last):
  File "train.py", line 182, in <module>
    main(args)
  File "train.py", line 177, in main
    fp16=args.fp16)
  File "/home/mm/PaddleSeg/paddleseg/core/train.py", line 155, in train
    if model.data_format == 'NHWC':
  File "/home/mm/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 1050, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'BiSeNetV2' object has no attribute 'data_format'

**Comment by wuyefeilin** [comment]
使用的话，请使用release/v2.0分支哈。如果需要最新版本，可以基于develop分支哈
