### ISSUE TITLE
PaddleSeg做了减枝后的模型如何进行C++预测部署

### ISSUE THREAD

**Issue by feeling69** [PaddlePaddle/PaddleSeg#968]
PaddleSeg剪枝后训练模型，包括pdmodel，pdopt，pdparams，__groups__， __shapes__ 5个文件，如何将其转换成C++环境中的预测模型，即__models__，__params__，deploy.yaml

**Comment by michaelowenliu** [comment]
@feeling69 Hi, there is an unofficial tutorial from a developer, https://blog.csdn.net/qianbin3200896/article/details/112635275
