### ISSUE TITLE
对于标注的数据如何做增广

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleSeg#969]
自定义标签数据在保存的时候是用的PIL.Image.save("xxxx",model="P)方法

在数据增广阶段，采用了transofrom里的方法，但是结果保存的时候用的cv2.imwrite的方法，保存的标签数据变成RGB格式的图像，这样就不符合标签格式图，为了解决这个问题，我讲RGB格式的转化为PIL.Image.save("xxxx",model="P)保存格式。
这样在训练的时候出现以下错误：

`
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[9302] expected >= 0 and < 5, or == 255,but got 5. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[9302] expected >= 0 and < 5, or == 255,but got 5. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[9302] expected >= 0 and < 5, or == 255,but got 5. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[9302] expected >= 0 and < 5, or == 255,but got 5. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[9303] expected >= 0 and < 5, or == 255,but got 5. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[9303] expected >= 0 and < 5, or == 255,but got 5. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[9303] expected >= 0 and < 5, or == 255,but got 5. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[9303] expected >= 0 and < 5, or == 255,but got 5. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[9303] expected >= 0 and < 5, or == 255,but got 5. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[9304] expected >= 0 and < 5, or == 255,but got 13. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[9304] expected >= 0 and < 5, or == 255,but got 13. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[9304] expected >= 0 and < 5, or == 255,but got 13. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[9304] expected >= 0 and < 5, or == 255,but got 13. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[9304] expected >= 0 and < 5, or == 255,but got 13. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[25685] expected >= 0 and < 5, or == 255,but got 10. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[25685] expected >= 0 and < 5, or == 255,but got 10. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[25685] expected >= 0 and < 5, or == 255,but got 10. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[25685] expected >= 0 and < 5, or == 255,but got 10. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[25685] expected >= 0 and < 5, or == 255,but got 10. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[25686] expected >= 0 and < 5, or == 255,but got 5. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[25686] expected >= 0 and < 5, or == 255,but got 5. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[25686] expected >= 0 and < 5, or == 255,but got 5. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[25686] expected >= 0 and < 5, or == 255,but got 5. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[25686] expected >= 0 and < 5, or == 255,but got 5. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[25687] expected >= 0 and < 5, or == 255,but got 5. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[25687] expected >= 0 and < 5, or == 255,but got 5. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[25687] expected >= 0 and < 5, or == 255,but got 5. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[25687] expected >= 0 and < 5, or == 255,but got 5. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[25687] expected >= 0 and < 5, or == 255,but got 5. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[25688] expected >= 0 and < 5, or == 255,but got 7. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[25688] expected >= 0 and < 5, or == 255,but got 7. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[25688] expected >= 0 and < 5, or == 255,but got 7. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[25688] expected >= 0 and < 5, or == 255,but got 7. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[25688] expected >= 0 and < 5, or == 255,but got 7. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[37804] expected >= 0 and < 5, or == 255,but got 5. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[37805] expected >= 0 and < 5, or == 255,but got 9. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[37805] expected >= 0 and < 5, or == 255,but got 9. Please check input value.`

感觉可能是保存的标签图和原图的color_map不一样了，我想请教一下又什么方法可以在不改变标签的color_map，对标签做数据增广 @wuyefeilin  @michaelowenliu

**Comment by wuyefeilin** [comment]
> 自定义标签数据在保存的时候是用的PIL.Image.save("xxxx",model="P)方法
> 
> 在数据增广阶段，采用了transofrom里的方法，但是结果保存的时候用的cv2.imwrite的方法，保存的标签数据变成RGB格式的图像，这样就不符合标签格式图，为了解决这个问题，我讲RGB格式的转化为PIL.Image.save("xxxx",model="P)保存格式。
> 这样在训练的时候出现以下错误：
> 
> `Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[9302] expected >= 0 and < 5, or == 255,but got 5. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[9302] expected >= 0 and < 5, or == 255,but got 5. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[9302] expected >= 0 and < 5, or == 255,but got 5. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[9302] expected >= 0 and < 5, or == 255,but got 5. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[9303] expected >= 0 and < 5, or == 255,but got 5. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[9303] expected >= 0 and < 5, or == 255,but got 5. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[9303] expected >= 0 and < 5, or == 255,but got 5. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[9303] expected >= 0 and < 5, or == 255,but got 5. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[9303] expected >= 0 and < 5, or == 255,but got 5. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[9304] expected >= 0 and < 5, or == 255,but got 13. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[9304] expected >= 0 and < 5, or == 255,but got 13. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[9304] expected >= 0 and < 5, or == 255,but got 13. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[9304] expected >= 0 and < 5, or == 255,but got 13. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[9304] expected >= 0 and < 5, or == 255,but got 13. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[25685] expected >= 0 and < 5, or == 255,but got 10. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[25685] expected >= 0 and < 5, or == 255,but got 10. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[25685] expected >= 0 and < 5, or == 255,but got 10. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[25685] expected >= 0 and < 5, or == 255,but got 10. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[25685] expected >= 0 and < 5, or == 255,but got 10. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[25686] expected >= 0 and < 5, or == 255,but got 5. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[25686] expected >= 0 and < 5, or == 255,but got 5. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[25686] expected >= 0 and < 5, or == 255,but got 5. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[25686] expected >= 0 and < 5, or == 255,but got 5. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[25686] expected >= 0 and < 5, or == 255,but got 5. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[25687] expected >= 0 and < 5, or == 255,but got 5. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[25687] expected >= 0 and < 5, or == 255,but got 5. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[25687] expected >= 0 and < 5, or == 255,but got 5. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[25687] expected >= 0 and < 5, or == 255,but got 5. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[25687] expected >= 0 and < 5, or == 255,but got 5. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[25688] expected >= 0 and < 5, or == 255,but got 7. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[25688] expected >= 0 and < 5, or == 255,but got 7. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[25688] expected >= 0 and < 5, or == 255,but got 7. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[25688] expected >= 0 and < 5, or == 255,but got 7. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[25688] expected >= 0 and < 5, or == 255,but got 7. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[37804] expected >= 0 and < 5, or == 255,but got 5. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_`failed. The value of label[37805] expected >= 0 and < 5, or == 255,but got 9. Please check input value. Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:481 Assertion`labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[37805] expected >= 0 and < 5, or == 255,but got 9. Please check input value.`
> 
> 感觉可能是保存的标签图和原图的color_map不一样了，我想请教一下又什么方法可以在不改变标签的color_map，对标签做数据增广 @wuyefeilin @michaelowenliu

数据增广可以通过transform进行设置的，你是怎么进行数据增广的

**Comment by BeyondYourself** [comment]
@wuyefeilin 我目前是想单独提高训练数据量，所以采用了transform中的一些方法来扩充数据量。如果直接引用只是对原有数据进行图像增强，并未对数据量进行增加。当前主要是标注数据，由于是单通道，通过cv2读取后，再转换为PIL，最后将其保存单通道图片（model ="P")

**Comment by wuyefeilin** [comment]
> @wuyefeilin 我目前是想单独提高训练数据量，所以采用了transform中的一些方法来扩充数据量。如果直接引用只是对原有数据进行图像增强，并未对数据量进行增加。当前主要是标注数据，由于是单通道，通过cv2读取后，再转换为PIL，最后将其保存单通道图片（model ="P")

自己增加数据量，跟利用transform进行数据增强效果是一样的。

**Comment by BeyondYourself** [comment]
当前采取这种方式是基于训练集的数据量较小的情况采用的方式，如果直接采用原数据进行增强而未增加数据量，可能并不一定效果好。目前测试的结果是这样的
