### ISSUE TITLE
DecoupledSegNet错误

### ISSUE THREAD

**Issue by choujujua** [PaddlePaddle/PaddleSeg#973]
1.环境：（首先安装cpu版本，测试成功）
 
![当前环境](https://user-images.githubusercontent.com/52094265/115170646-aaeba880-a0f3-11eb-8a22-04cd130f4ddb.png)

2.安装GPU版本
命令：python -m pip install paddlepaddle-gpu==2.0.0 -i https://mirror.baidu.com/pypi/simple

3.出现问题
 
![出现问题一](https://user-images.githubusercontent.com/52094265/115170506-62cc8600-a0f3-11eb-8160-fc211569fce5.png)

4.解决方案
（1）env | grep cuda
（2）port LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
（3） /usr/local/cuda/lib64
（4）ln -s libcusolver.so.10 libcusolver.so

5. 运行 
Python./train.py -config ./configs/decoupled_segnet/decoupledsegnet_resnet50_os8_cityscapes_832x832_80k.yml

6.新问题
![出现问题二](https://user-images.githubusercontent.com/52094265/115170587-91e2f780-a0f3-11eb-81a7-42b22cedd807.png)

**Comment by LYA-Ansel** [comment]
Hi, 我也出了一模一样的问题  请问你有找到解决方案吗？

**Comment by choujujua** [comment]
> Hi, 我也出了一模一样的问题 请问你有找到解决方案吗？

Sorry, I haven't solved this problem yet。

**Comment by choujujua** [comment]
> Hi, 我也出了一模一样的问题 请问你有找到解决方案吗？

对不起，我现在还没有解决这个问题。

**Comment by michaelowenliu** [comment]
@choujujua Hi, we are reproducing this issue.
