### ISSUE TITLE
建议开设FAQ专栏

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleSeg#974]
现在也有好多issues已经close，评论区还是有很多人会重复提一些已经解决的issues，在项目中开设FAQ专栏，一方面是知识积淀，另一方面也能够让更多人了解到可能遇到的问题及解决方法

**Comment by michaelowenliu** [comment]
@BeyondYourself Hi, the feature is coming soon. Thanks for your suggestion!

**Comment by BeyondYourself** [comment]
Great
