### ISSUE TITLE
运行unet眼球训练例子报错

### ISSUE THREAD

**Issue by cloudsurging** [PaddlePaddle/PaddleSeg#978]
![image](https://user-images.githubusercontent.com/32347832/115347264-c504b400-a1e3-11eb-8dce-54407b1074b0.png)
'NoneType' object has no attribute 'run'
'NoneType' object has no attribute 'run'Traceback (most recent call last):
  File "d:/PaddleSeg/pdseg/train.py", line 420, in train
    loss, lr = exe.run(

**Comment by michaelowenliu** [comment]
@cloudsurging Hi, please use the latest version which supports the dynamic graph.

**Comment by cloudsurging** [comment]
#Device count: 1
batch_size_per_dev: 4
Traceback (most recent call last):
&nbsp; File "d:/PaddleSeg/pdseg/train.py", line 518, in <module&gt;
&nbsp; &nbsp; main(args)
&nbsp; File "d:/PaddleSeg/pdseg/train.py", line 505, in main
&nbsp; &nbsp; train(cfg)
&nbsp; File "d:/PaddleSeg/pdseg/train.py", line 255, in train
&nbsp; &nbsp; py_reader, avg_loss, lr, pred, grts, masks = build_model(
&nbsp; File "d:\PaddleSeg\pdseg\models\model_builder.py", line 189, in build_model
&nbsp; &nbsp; image = fluid.layers.data(
&nbsp; File "C:\ProgramData\Anaconda3\envs\paddle_env\lib\site-packages\decorator.py", line 231, in fun
&nbsp; &nbsp; return caller(func, *(extras + args), **kw)
&nbsp; File "C:\ProgramData\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
&nbsp; &nbsp; return wrapped_func(*args, **kwargs)
&nbsp; File "C:\ProgramData\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\framework.py", line 232, in __impl__
&nbsp; &nbsp; assert not in_dygraph_mode(
AssertionError: In PaddlePaddle 2.x, we turn on dynamic graph mode by default, and 'data()' is only supported in static graph mode. So if you want to use this api, please call 'paddle.enable_static()' before this api to enter static graph mode.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月20日(星期二) 下午4:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSeg] 运行unet眼球训练例子报错 (#978)





 
@cloudsurging Hi, please use the latest version which supports the dynamic graph.

**Comment by michaelowenliu** [comment]
@cloudsurging Hi, please upgrade PaddleSeg, https://github.com/PaddlePaddle/PaddleSeg
