### ISSUE TITLE
关于VisualDL可视化

### ISSUE THREAD

**Issue by Abris-087** [PaddlePaddle/PaddleSeg#979]
我在aistudio上训练模型，由于算力卡原因，分两次才训练完毕。

**Comment by Abris-087** [comment]
> 我在aistudio上训练模型，由于算力卡原因，分两次才训练完毕。

output文件夹下有两个log文件，但是visualDL只能显示后一段的训练曲线。有什么办法可以展示完整的训练过程吗？
![image](https://user-images.githubusercontent.com/61613537/115354511-495b3500-a1ec-11eb-9ce0-a0844f0bb2a0.png)

![image](https://user-images.githubusercontent.com/61613537/115354448-38122880-a1ec-11eb-9c6f-2f3b28eb79d7.png)

**Comment by ShenYuhan** [comment]
一个比较简单的办法是：
把第一次生成的日志和第二次生成的日志中的内容拷贝到一个新的二进制文件中，然后读取。

我们将会在不久的将来在新版本中支持多个日志合并。

另外如果是类似这种中断后继续训练的情况，可以在调用visualdl的时候指定日志名，这样就可以直接在指定的日志文件中继续续写了，资料见 https://github.com/PaddlePaddle/VisualDL/blob/develop/docs/faq_CN.md#%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9%E5%B7%B2%E6%9C%89%E7%9A%84%E6%97%A5%E5%BF%97%E6%96%87%E4%BB%B6
