### ISSUE TITLE
关于pascal context数据集的一些问题

### ISSUE THREAD

**Issue by syp2ysy** [PaddlePaddle/PaddleSeg#983]
>当我们在尝试使用pascal `context出现了一个问题导致程序停止正常工作,请问该如何 解决这个问题?

> W0422 16:28:37.910310   850 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Runtime API Version: 10.2
> W0422 16:28:37.910326   850 device_context.cc:372] device: 0, cuDNN Version: 7.6.
> 2021-04-22 16:28:39,577 - INFO - Lock 139810382529200 acquired on /home/sun/.paddleseg/tmp/hrnet_w48_ssld
> 2021-04-22 16:28:39,577 - INFO - Lock 139810382529200 released on /home/sun/.paddleseg/tmp/hrnet_w48_ssld
> 2021-04-22 16:28:39 [INFO]	Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/hrnet_w48_ssld.tar.gz
> 2021-04-22 16:28:41 [INFO]	There are 1525/1525 variables loaded into HRNet.
> 2021-04-22 16:28:41,926 - ERROR - DataLoader reader thread raised an exception!
> Traceback (most recent call last):
>   File "/home/sun/code/PaddleSeg/train.py", line 154, in <module>
>     main(args)
>   File "/home/sun/code/PaddleSeg/train.py", line 149, in main
>     keep_checkpoint_max=args.keep_checkpoint_max)
>   File "/home/sun/code/PaddleSeg/paddleseg/core/train.py", line 149, in train
>     for data in loader:
>   File "/home/sun/anaconda3/envs/pad/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 779, in __next__
>     data = self._reader.read_next_var_list()
> SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
>   [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)

**Comment by haoyuying** [comment]
您好，您目前的报错信息只能看出是dataloder报错，具体哪句什么问题等通过该报错栈是无法定位的，建议您定位到准确的报错原因方便我们排查，可以从dataset里面打印，看下从哪一句开始崩了。

**Comment by syp2ysy** [comment]
您好，错误是从datasets.py中的

> if self.edge:
开始的。transforms的过程是没有错误的，但是跳回来进行这个if语句时卡住了

**Comment by haoyuying** [comment]
把 self.edge这个关掉呢，不要进这个选项，看这一句https://github.com/PaddlePaddle/PaddleSeg/blob/release/v2.0/paddleseg/datasets/dataset.py#L155

image和label是否正常，如果不正常，打印下https://github.com/PaddlePaddle/PaddleSeg/blob/release/v2.0/paddleseg/datasets/dataset.py#L144
看path是否正常并存在。

**Comment by syp2ysy** [comment]
关掉后就会在return im, label处卡住，打印path是由结果的。调试过程中发现在处理完2008_003667.jpg后返回datasets.py，进行下一步是会卡住
![image](https://user-images.githubusercontent.com/39050296/116530554-bff4e280-a910-11eb-948c-af27b943899a.png)

**Comment by haoyuying** [comment]
请问pascal_context已经进行预处理了吗，如果还是定位不到问题，方便在aistudio上给一个复现环境吗，这个提示错误其实是定位不到具体问题的。具体预处理请参考https://github.com/PaddlePaddle/PaddleSeg/blob/release/v2.0/tools/convert_voc2010.py

**Comment by syp2ysy** [comment]
pascal_context预处理过了。好的，我尝试在aistudio上复现一下

**Comment by syp2ysy** [comment]
https://aistudio.baidu.com/aistudio/projectdetail/1884642
谢谢您看下

**Comment by syp2ysy** [comment]
您好，这个问题解决了是由于pascal_context里面没有edge信息，将paddleseg/datasets/pascal_context.py中的def __init__() 修改成为：

>     def __init__(self, transforms=None, dataset_root=None, mode='train', edge=False):
        self.dataset_root = dataset_root
        self.transforms = Compose(transforms)
        mode = mode.lower()
        self.mode = mode
        self.file_list = list()
        self.num_classes = self.NUM_CLASSES
        self.ignore_index = 255
        self.edge = edge
非常感谢~~，期望正式版本可以修改一下。
