### ISSUE TITLE
使用fast_scnn预训练模型训练自定义数据集

### ISSUE THREAD

**Issue by MansGod** [PaddlePaddle/PaddleSeg#984]
![2021-04-22 19-46-43 的屏幕截图](https://user-images.githubusercontent.com/73273430/115710640-2a53d300-a3a5-11eb-8a06-09e413d81160.png)

[SKIP] Shape of pretrained weight ./pretrained_model/fast_scnn_cityscapes//classifier/weights doesn't match.(Pretrained: (19, 128, 1, 1), Actual: (3, 128, 1, 1))
[SKIP] Shape of pretrained weight ./pretrained_model/fast_scnn_cityscapes//classifier/biases doesn't match.(Pretrained: (19,), Actual: (3,))
There are 222/224 varaibles in ./pretrained_model/fast_scnn_cityscapes/ are loaded.
自定义数据的num_class=3,与预训练模型的19不匹配，但是能正常训练并保存结果，请问这样有影响吗，或者该怎么修改呢？

**Comment by michaelowenliu** [comment]
@MansGod Hi, that does not matter.

**Comment by MansGod** [comment]
好的 谢谢解答
