### ISSUE TITLE
有关多卡训练

### ISSUE THREAD

**Issue by Abris-087** [PaddlePaddle/PaddleSeg#985]
您好，我在尝试用多卡训练时有几个问题不能理解

**Comment by Abris-087** [comment]
> 
> 
> 您好，我在尝试用多卡训练时有几个问题不能理解

1、
![图片](https://user-images.githubusercontent.com/61613537/115804987-a20e1600-a416-11eb-8980-dfad936c8f02.png)
![图片](https://user-images.githubusercontent.com/61613537/115805008-aa665100-a416-11eb-9dc2-95ce5a8a660d.png)
我设置学习率为0.01，为什么训练时从0.001开始衰减？
2、相同的任务，我用“四张Titan XP”训练的预计用时比“单张V100”多将近一倍时间，这是正常的吗？还是我哪里可能设置错误呢？

**Comment by Abris-087** [comment]
> 
> 
> 您好，我在尝试用多卡训练时有几个问题不能理解

3、还有一个问题：我用单张16G的V100，batchsize最多设置为2，占用显存约10G；我用4张Titan Xp，总显存12G*4，为什么batchsize最多还是2，且每张显卡占用10G？我以为四张卡batchsize可以增大到8的。

**Comment by BeyondYourself** [comment]
多卡应该是并行处理吧，而且应该是每个卡处理同样的batch_size吧

**Comment by wenjie-yuan** [comment]
我也遇到一样的问题，多卡不能增加batch_size，不增加batch_size的多卡训练，速度并不增加，希望得到回复
