### ISSUE TITLE
voc2012

### ISSUE THREAD

**Issue by xLuge** [PaddlePaddle/PaddleSeg#988]
deeplabv3p 在voc2012测试集上的官网测试结果能达到多少？

**Comment by michaelowenliu** [comment]
@xLuge Hi, we have yet to submit the results. Please let us know if you get the score.

**Comment by xLuge** [comment]
@michaelowenliu 额外的问题。关于voc12我们通常在train_aug上训练，然后在origin set进行finetune 。当进行finetune时是否需要冻结bn层呢？

**Comment by michaelowenliu** [comment]
@xLuge Hi, what does it mean "origin set"?

**Comment by xLuge** [comment]
@michaelowenliu sorry。。就是voc12原始的训练集。包含1464张图片。
