### ISSUE TITLE
导出模型报错，Please define the layer with parameters in `__init__` function.

### ISSUE THREAD

**Issue by yangy996** [PaddlePaddle/PaddleSeg#992]
![image](https://user-images.githubusercontent.com/15188456/116390974-2f0b0200-a851-11eb-8971-382abf04e391.png)

**Comment by michaelowenliu** [comment]
@YY007H Hi, what is your question?

**Comment by yangy996** [comment]
@michaelowenliu 我新加了个组件，训练的时候都是正常的，到了导出的时候就出现上面那个错误，不知道是什么导致了，网络也只是个基于VGG16的一个HED网络

**Comment by michaelowenliu** [comment]
@YY007H Hi, add __init__ function into your new component.
