### ISSUE TITLE
HumanSeg 训练细节

### ISSUE THREAD

**Issue by lovejing0306** [PaddlePaddle/PaddleSeg#999]
你好，请问人像分割项目 HumanSeg 的模型训练细节在哪里可以找到？

**Comment by wuyefeilin** [comment]
参考这边哈：https://github.com/PaddlePaddle/PaddleSeg/tree/release/v2.0/legacy/contrib/HumanSeg#%E8%AE%AD%E7%BB%83

**Comment by lovejing0306** [comment]
感谢回复
